### ISSUE TITLE
主题更新失败，解压时报错文件

### ISSUE THREAD

**Issue by liuhr-ncu** [halo-dev/halo#1000]
![image](https://user-images.githubusercontent.com/29883424/88613778-cbd12100-d0c0-11ea-867a-2463a52600f0.png)

**Comment by zhixiangyuan** [comment]
我这边上传主题时也报错，不知道是不是同一个问题

![image](https://user-images.githubusercontent.com/25138766/89114725-319f1d80-d4b2-11ea-8111-d7f2d7e914c5.png)

**Comment by JohnNiang** [comment]
是的，这是一个 bug，正在着手修复。

**Comment by ruibaby** [comment]
Resolved
