### ISSUE TITLE
私密文章可以设置在前台展示

### ISSUE THREAD

**Issue by dliceya** [halo-dev/halo#1004]
## 概述
  Menu：博客设置 --> 文章设置  中希望可以加入私密文章是否在前台展示的Switch
## 动机
  通过后台访问私密文章挺麻烦的，尤其是在某个分类下面全是私密文章的情况下。
## 详细解释
  如果能添加某个分类访问需要密码的功能就更好了
么么哒

**Comment by ruibaby** [comment]
可以考虑。

关于加密整个分类之前也已经有 issue 提到了，这些都将在未来某个版本中实现。

**Comment by zhixiangyuan** [comment]
> 可以考虑。
> 
> 关于加密整个分类之前也已经有 issue 提到了，这些都将在未来某个版本中实现。

强烈支持，大佬加油，期待

**Comment by zhixiangyuan** [comment]
@ruibaby 大佬，分类加密的功能我正准备实现，想问以下实现这个功能有哪些注意事项

**Comment by ruibaby** [comment]
> @ruibaby 大佬，分类加密的功能我正准备实现，想问一下实现这个功能有哪些注意事项

1. 你所说的分类加密是加密分类还是加密分类下的文章，加密之后文章是否还能被其他地方查询到。
2.  如何与目前的私密文章兼容。
3. 向下兼容之前已经加密的文章。
4. 路由处理。

希望在研究之后提一个 issue 详细描述和讨论你的方案。直接提交 pr，我们很可能不会合并。

**Comment by LIlGG** [comment]
@ruibaby  我认为他们想要的私密文章，可能是那种能够在前端输入密码进行访问的私密文章。
虽然我个人不喜欢那种，本来就是个开放的公共博客，又使用加密才能看到的文章，实在是让人无法理解。但这种需求确实是有的。

**Comment by zhixiangyuan** [comment]
@ruibaby  开了讨论链接，在 #1225

**Comment by Your-Pluviophile** [comment]
我觉得可能对于博客的初衷不一样，有些人可能把它作为一个纯技术分享的平台，我个人喜欢记录生活中的所有事，技术上的总结可以全放开，但其中一些生活上的记录，我只希望被家人或者恋人看见，所以如果可以针对某个分类进行加密，或者对文章进行加密，又能在前台被知道密码的亲友访问，我觉得会极大的提高我对这款博客的忠诚度。所以很期待类似功能的上线！

**Comment by ruibaby** [comment]
> 我觉得可能对于博客的初衷不一样，有些人可能把它作为一个纯技术分享的平台，我个人喜欢记录生活中的所有事，技术上的总结可以全放开，但其中一些生活上的记录，我只希望被家人或者恋人看见，所以如果可以针对某个分类进行加密，或者对文章进行加密，又能在前台被知道密码的亲友访问，我觉得会极大的提高我对这款博客的忠诚度。所以很期待类似功能的上线！

https://github.com/halo-dev/halo/issues/2362#issuecomment-1242906508

**Comment by JohnNiang** [comment]
目前在 Halo 2.9 中，我们实现了作者登录后可在主体端查看私密文章的功能。

参考：

- https://github.com/halo-dev/halo/pull/4412

我将关闭当前 Issue，如果有任何问题可随时重新打开。

/close
