### ISSUE TITLE
关于API设置设置项

### ISSUE THREAD

**Issue by wencyGit** [halo-dev/halo#1006]
<img width="409" alt="123654" src="https://user-images.githubusercontent.com/21151964/89095602-3906ee00-d402-11ea-924b-582c320e8f16.png">

后台管理系统中。
系统——博客设置——API设置
已经取消API设置功能了么？
怎么登陆没看到设置项

**Comment by ruibaby** [comment]
右下角有一个蓝色按钮 -> 高级设置。

**Comment by wencyGit** [comment]
@ruibaby 好吧，放到那里去了，根github图片不一样，稍微有点隐蔽，😄
