### ISSUE TITLE
全站加速报503

### ISSUE THREAD

**Issue by codesensi** [halo-dev/halo#1007]
您好，我是用docker compose方式部署的halo最新版
做了又拍云的全站加速之后，访问加速域名报503 Service Temporarily Unavailable，请问我该怎么解决呢
谢谢

**Comment by ruibaby** [comment]
不清楚。
但是如果要使用全站加速的话，实际上你部署并不需要 docker compose。反向代理没有必要，回源地址直接填写 ip + 端口，把你博客的二级域使用 CNAME 解析到又拍云提供的 CNAME 地址即可。你可能还需要开启 `重定向跟随`，`参数跟随` 之类的。

**Comment by codesensi** [comment]
> 不清楚。
> 但是如果要使用全站加速的话，实际上你部署并不需要 docker compose。反向代理没有必要，回源地址直接填写 ip + 端口，把你博客的二级域使用 CNAME 解析到又拍云提供的 CNAME 地址即可。你可能还需要开启 `重定向跟随`，`参数跟随` 之类的。

谢谢，我知道了
