### ISSUE TITLE
为评论系统添加私密评论功能

### ISSUE THREAD

**Issue by cetr** [halo-dev/halo#1012]
给大家安排个任务哈，实现私密评论功能，思路我已想好，但由于网络不好以及修改地方较多，所以靠你们了

## 概述

评论模块实现私密评论

## 需修改部分

数据库

1. 在评论表添加一列表示这条评论是否私密类型，默认普通类型

后端代码

1. 新添评论时判断评论模块传来的值是否私密类型并存入
2. 查询评论时将私密类型评论替换成统一标志，不往前台传实际评论内容，只传标志

评论模块

1. 提交评论时如果用户勾选私密类型需向后台传类型
2. 遍历展示时如果这条评论为私密标志则在页面有相应表现

后台控制台模块

1. 评论列表需添加相应指示，是否私密评论
2. 回复评论时可选择普通类型回复还是私密类型回复
3. 如果是给私密类型评论回复建议默认私密类型回复

## 整体情况

用户将私密评论提交之后就看不了评论内容了，只能博主在后台查看，博主回复可选择普通类型或私密类型，用户查看私密类型评论也只能在邮件里查看，后台往页面传值展示的时候只需要传个标记，指出那条评论是私密的就行，然后由评论模块表现

**Comment by JohnNiang** [comment]
应用场景太少，不开发。
