### ISSUE TITLE
附件分页失效，主题不可编辑，日志不能查看

### ISSUE THREAD

**Issue by javami888** [halo-dev/halo#1013]
## 我的环境

---

## 错误日志

---

**Comment by ruibaby** [comment]
搞了 CDN 之类的？如果有日志，请给出日志。你这样你让我猜？

**Comment by javami888** [comment]
大佬&nbsp; 我也想看啊&nbsp; 查看不到 报错是要去虚拟机看么
好像就是加了CDN之后出现的问题







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ryan Wang"<notifications@github.com&gt;; 
发送时间: 2020年8月5日(星期三) 上午10:26
收件人: "halo-dev/halo"<halo@noreply.github.com&gt;; 
抄送: "黑晶石"<miguannan@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [halo-dev/halo] 附件分页失效，主题不可编辑，日志不能查看 (#1013)





 
搞了 CDN 之类的？如果有日志，请给出日志。你这样你让我猜？

**Comment by ruibaby** [comment]
> 大佬&nbsp; 我也想看啊&nbsp; 查看不到 报错是要去虚拟机看么
> 
> 好像就是加了CDN之后出现的问题
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 
> 发件人: "Ryan Wang"<notifications@github.com&gt;; 
> 
> 发送时间: 2020年8月5日(星期三) 上午10:26
> 
> 收件人: "halo-dev/halo"<halo@noreply.github.com&gt;; 
> 
> 抄送: "黑晶石"<miguannan@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
> 
> 主题: Re: [halo-dev/halo] 附件分页失效，主题不可编辑，日志不能查看 (#1013)
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
>  
> 
> 搞了 CDN 之类的？如果有日志，请给出日志。你这样你让我猜？
> 
>  
> 
> —
> 
> You are receiving this because you authored the thread.
> 
> Reply to this email directly, view it on GitHub, or unsubscribe.

你可能需要开启 重定向跟随，参数跟随 之类的。

**Comment by javami888** [comment]
我想起来了 出现这种问题后&nbsp;&nbsp;我想着更新1.4&nbsp; 但是按照一下的步骤&nbsp; 启动失败了&nbsp; &nbsp;但是也已经备份旧的安装包了&nbsp; 怎么办
# 备份数据 cp -r ~/.halo ~/.halo.bak # 备份旧的安装包 mv halo-latest.jar halo-latest.jar.bak # 下载最新的 Halo 安装包，{{version}} 为版本号，不带 v，更多下载地址请访问 https://halo.run/archives/download.html wget https://dl.halo.run/release/halo-{{version}}.jar -O halo-latest.jar # 测试是否能够正常启动 java -jar halo-latest.jar # 重启应用 service halo restart




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ryan Wang"<notifications@github.com&gt;; 
发送时间: 2020年8月5日(星期三) 上午10:30
收件人: "halo-dev/halo"<halo@noreply.github.com&gt;; 
抄送: "黑晶石"<miguannan@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [halo-dev/halo] 附件分页失效，主题不可编辑，日志不能查看 (#1013)





  
大佬&nbsp; 我也想看啊&nbsp; 查看不到 报错是要去虚拟机看么
 
好像就是加了CDN之后出现的问题
 
------------------&nbsp;原始邮件&nbsp;------------------
 
发件人: "Ryan Wang"<notifications@github.com&gt;;
 
发送时间: 2020年8月5日(星期三) 上午10:26
 
收件人: "halo-dev/halo"<halo@noreply.github.com&gt;;
 
抄送: "黑晶石"<miguannan@qq.com&gt;; "Author"<author@noreply.github.com&gt;;
 
主题: Re: [halo-dev/halo] 附件分页失效，主题不可编辑，日志不能查看 (#1013)
 
搞了 CDN 之类的？如果有日志，请给出日志。你这样你让我猜？
 
—
 
You are receiving this because you authored the thread.
 
Reply to this email directly, view it on GitHub, or unsubscribe.
  
你可能需要开启 重定向跟随，参数跟随 之类的。
