### ISSUE TITLE
feat: 使用图库时支持外链

### ISSUE THREAD

**Issue by LDity** [halo-dev/halo#1014]
## 概述

在选择图库的图片时，只能够在附件库中选取相应的图片，不能够直接使用图片外链

## 动机

我拍摄了接近三百张图片，之前存储于码云中，使用hexo搭建的博客。现在需要迁移到halo中，而halo1.3.2版本的图库中，仅仅支持缩略图的是外链引用，而实际的内容图片需要一张一张地从附件库中选取，并不是十分方便。希望可以通过添加选取外链的方式进行图库中图片的选取和修改

**Comment by JohnNiang** [comment]
图库确实需要支持外链。下个版本见。

**Comment by ruibaby** [comment]
https://github.com/halo-dev/halo-admin/pull/258
