### ISSUE TITLE
halo.mv.db文件怎么查看

### ISSUE THREAD

**Issue by codesensi** [halo-dev/halo#1016]
请问db文件怎么可以查看，还有重新部署的halo需要h2数据库的用户名密码和旧halo的一致吗？

**Comment by JohnNiang** [comment]
http://www.h2database.com/html/download.html

**Comment by ruibaby** [comment]
1. https://halo.run/archives/use-reset-password.html#%E7%B2%97%E6%9A%B4%E7%9A%84%E6%96%B9%E5%BC%8F

2. 重新部署如果不需要原来的数据可以不一致。

**Comment by codesensi** [comment]
谢谢
