### ISSUE TITLE
feat: 备份功能增强

### ISSUE THREAD

**Issue by zhixiangyuan** [halo-dev/halo#1019]
## 概述

备份功能支持定时备份并上传备份文件到 oss

## 动机

提高安全等级

## 详细解释

目前的备份功能只能本地备份，如果被黑客攻击破坏数据或服务器忘记续费导致服务器回收则数据全部丢失，所以建议添加定时备份并上传文件到 oss 的功能，这样即使服务器到期也不会出现数据丢失的问题。

**Comment by ruibaby** [comment]
@zhixiangyuan 这种功能外部实现起来很简单，参考 https://ryanc.cc/archives/record-how-to-save-my-blog.html

**Comment by zhixiangyuan** [comment]
> @zhixiangyuan 这种功能外部实现起来很简单，参考 https://ryanc.cc/archives/record-how-to-save-my-blog.html

我之前也是使用的这个方案，当时还记了一篇博客，http://xiangbei.life/2020/03/16/5abda6f12eb44aef85345894c574d27478ab72f00cab44d4924cc257c47cf28f，但是这种方式的问题有个问题，我是 10 分钟备份一次，结果一段时间用下来 git 超级大，占用空间上 g，导致每次备份特别慢，😂，我也把备份频率调低吧

**Comment by ruibaby** [comment]
@zhixiangyuan 是的这是这种方式的弊端，但是也有其他的备份方案嘛，总之我觉得集成在系统里不是一个太好的方案。

**Comment by zhixiangyuan** [comment]
> @zhixiangyuan 是的这是这种方式的弊端，但是也有其他的备份方案嘛，总之我觉得集成在系统里不是一个太好的方案。

确实是，我也调整一下备份策略

**Comment by ruibaby** [comment]
https://bore.vip/archives/halo-backup
