### ISSUE TITLE
feat: Logo 和 Favicon 支持本站相对路径

### ISSUE THREAD

**Issue by zhixiangyuan** [halo-dev/halo#1023]
## 概述

目前 logo 和 favicon 不支持本站相对路径，不是很方便

## 动机

配置本站相对路径在更换域名也能正常使用

## 详细解释

![image](https://user-images.githubusercontent.com/25138766/89727978-f5dcf880-da5b-11ea-8c0c-d0dd4907c3ef.png)

**Comment by ruibaby** [comment]
@zhixiangyuan 这个呢？https://halo.run/archives/use-hidden-features.html#favicon-的统一地址

**Comment by zhixiangyuan** [comment]
> @zhixiangyuan 这个呢？[https://halo.run/archives/use-hidden-features.html#favicon - 的统一地址](https://halo.run/archives/use-hidden-features.html#favicon-%E7%9A%84%E7%BB%9F%E4%B8%80%E5%9C%B0%E5%9D%80)

棒
