### ISSUE TITLE
搜索功能bug

### ISSUE THREAD

**Issue by cancan16** [halo-dev/halo#1027]
## 我的环境

---

## 错误日志

后台和博客内搜索文章，不能正常返回搜索结果

---

## 期望行为

搜索先匹配文章标题，再匹配文章内容

**Comment by JohnNiang** [comment]
搜索这块需要重新设计，目前仅依赖数据库的搜索是不太合理的。

**Comment by zhixiangyuan** [comment]
> 搜索这块需要重新设计，目前仅依赖数据库的搜索是不太合理的。

我也觉得，大佬打算怎么改这块，有没有什么方案分享

**Comment by ruibaby** [comment]
/close

https://github.com/halo-dev/halo/issues/2637
