### ISSUE TITLE
feat: md档，无法英文自动换行。

### ISSUE THREAD

**Issue by xjchenGit** [halo-dev/halo#1029]
## 概述
![image](https://user-images.githubusercontent.com/43399390/90211259-cabf2400-de22-11ea-9ac6-ca63aed4c438.png)
Markdown在写markdown的时候英文无法自动换行，希望可以做到自动换行

**Comment by JohnNiang** [comment]
这应该是主题样式有关系：

```css
hyphens: auto;
```
