### ISSUE TITLE
feat: 希望回收站支持 30 后自动删除的功能

### ISSUE THREAD

**Issue by zhixiangyuan** [halo-dev/halo#1031]
## 概述

希望回收站支持 30 后自动删除的功能

## 动机

增强后使用回收站非常方便

**Comment by ruibaby** [comment]
能详细描述下吗？

**Comment by zhixiangyuan** [comment]
> 能详细描述下吗？

目前回收站的功能是删除文章后将文章改成回收站，如果需要删除文章需要用户手动删除，这里可以增加一个功能。在文章状态改成回收站后，每天有一个定时任务扫描，如果有文章达到 30 天则将文章删除掉。

![image](https://user-images.githubusercontent.com/25138766/90534835-c8efba80-e1ac-11ea-98c1-08e7c4993424.png)

**Comment by ruibaby** [comment]
可以考虑。
