### ISSUE TITLE
feat: 附件可以批量添加到图库

### ISSUE THREAD

**Issue by xzhuz** [halo-dev/halo#1032]
希望管理后台附件可以批量添加到图库。
不知道是不是我没有找到还是怎么的，希望有这个功能

**Comment by LIlGG** [comment]
甚至我希望图库并不只能从附件拿过去。。实际上我想放外链，一般想这样做的话我是手动改的数据库，太麻烦。。。

**Comment by xzzai** [comment]
> 甚至我希望图库并不只能从附件拿过去。。实际上我想放外链，一般想这样做的话我是手动改的数据库，太麻烦。。。

这个好像在做了
