### ISSUE TITLE
halo.run挂了很久了

### ISSUE THREAD

**Issue by milesking** [halo-dev/halo#1033]
你好，我发现halo.run挂了很久了，不知道是不是跑路了。还有其他渠道获取相关信息吗？

**Comment by JohnNiang** [comment]
没有挂啊。你的网络环境是什么呢？

**Comment by ruibaby** [comment]
经过测试大部分地区都可以访问，不知道你是什么地区和网络环境。

跑路？您可真会开玩笑。

**Comment by ruibaby** [comment]
http://ping.chinaz.com/halo.run

**Comment by milesking** [comment]
我是杭州电信，从8/12开始不能访问，稍早时候访问也是不行。看到回复之后试了下可以了，cf的cdn就可以理解

**Comment by ruibaby** [comment]
> 我是杭州电信，从8/12开始不能访问，稍早时候访问也是不行。看到回复之后试了下可以了，cf的cdn就可以理解

将在不久后更换 cdn 和 服务厂商。
