### ISSUE TITLE
关于https和ssl

### ISSUE THREAD

**Issue by DamanYang-cn** [halo-dev/halo#1043]
本人使用centos和nginx，配置了反向代理，我的证书配置没有问题，我其他的站点都是有效，halo的yaml也配置了ssl，但是https链接仍然显示不安全。想问一下详细一点如何给halo配置ssl。
我的mail：2402664612@qq.com

**Comment by ruibaby** [comment]
配置 ssl 证书可以和 halo 没有任何关系。不知道你修改配置文件的用途。如果你已经反向代理成功，http 访问没有问题。那么配置 ssl 证书在网络上应该有很多这样的教程。

http://nginx.org/en/docs/http/configuring_https_servers.html

**Comment by DamanYang-cn** [comment]
好的，我已经找出问题了，是因为使用了一些http资源，谢谢你的回复。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Ryan Wang <notifications@github.com&gt;
发送时间: 2020年8月24日 17:19
收件人: halo-dev/halo <halo@noreply.github.com&gt;
抄送: Daman Yang <2402664612@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[halo-dev/halo] 关于https和ssl (#1043)





 
配置 ssl 证书可以和 halo 没有任何关系。不知道你修改配置文件的用途。如果你已经反向代理成功，http 访问没有问题。那么配置 ssl 证书在网络上应该有很多这样的教程。
 
http://nginx.org/en/docs/http/configuring_https_servers.html
