### ISSUE TITLE
文章编辑页面显示数学公式，在博客内容页面不显示，会显示成为markdown代码

### ISSUE THREAD

**Issue by y84858226** [halo-dev/halo#1046]
## 我的环境
版本：1.3.2
数据库：H2 1.4.196 (2017-06-10)
运行模式：production
User Agent：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36

---

## 错误日志
应该是前端插件的问题，和后台日志没关系吧？我看后台全是认证失败的日志。

---

## 期望行为
正常显示数学公式

## 当前行为
$f(x, y) = x^2 + y^2, x \epsilon [0, 100], y \epsilon \{1,2,3\}$
这段代码为一个数学公式，在后台编辑显示正常，在前端显示错误。
![QQ截图20200828211837](https://user-images.githubusercontent.com/23625530/91565726-3ce04e80-e975-11ea-92de-02974477c68c.png)
![QQ截图20200828211904](https://user-images.githubusercontent.com/23625530/91565730-3eaa1200-e975-11ea-94aa-5e750a56baff.png)

**Comment by ruibaby** [comment]
@y84858226 先尝试一下这个。https://halo.run/archives/use-markdown.html#数学公式

**Comment by y84858226** [comment]
这个方法对我无效。其实是后台和前台的markdown 公式解析不对。后台显示的是正确的，前台查看文章就有问题

**Comment by ruibaby** [comment]
@y84858226 那就是已知问题。

具体请看 https://github.com/halo-dev/halo/issues/607

建议关注 https://github.com/halo-dev/halo/issues/989

**Comment by y84858226** [comment]
谢谢！
