### ISSUE TITLE
字段验证错误，请完善后重试！

### ISSUE THREAD

**Issue by CHENkai8385** [halo-dev/halo#1050]
当自定义全局Head或自定义内容也Head过长时，会报错如下：

字段验证错误，请完善后重试！
Length of option value must not be more than 1023

期望：
可不可以放开这个长度限制，
当我加了1.百度的统计2.谷歌广告3.微信的JSSDK调用（这段尤其会很长）时，长度就不够了

**Comment by CHENkai8385** [comment]
@JohnNiang

**Comment by JohnNiang** [comment]
是的，这个我们也注意到了，后面考虑取消这样的限制。

**Comment by ruibaby** [comment]
取消限制还是不太好，可以加大 length。
