### ISSUE TITLE
feat: 希望能做一个自动同步git库里面的md文档的功能

### ISSUE THREAD

**Issue by ToForgiveNoll** [halo-dev/halo#1051]
# 概述

可以给文章指定一个链接，定时去那里获取md文档，更新文档

## 动机

比较习惯本地的markdown编辑器，加上文章是在git中管理，希望提供支持

**Comment by ruibaby** [comment]
对于动态博客系统来说太鸡肋，你不如用 Hexo 之类的。

**Comment by ToForgiveNoll** [comment]
> 对于动态博客系统来说太鸡肋，你不如用Hexo之类的。

修改的比较频繁 改了之后还要再blog里面再改 太麻烦了..

**Comment by ToForgiveNoll** [comment]
> 对于动态博客系统来说太鸡肋，你不如用 Hexo 之类的。

而且和别人 协同做文档的话会很麻烦...

**Comment by ToForgiveNoll** [comment]
> 对于动态博客系统来说太鸡肋，你不如用 Hexo 之类的。

大佬 这对我很重要...

**Comment by ruibaby** [comment]
理解你的需求，但不会考虑做在系统里，我们还是希望以插件的形势来做这些需求。

但是还不支持。

**Comment by ToForgiveNoll** [comment]
> 理解你的需求，但不会考虑做在系统里，我们还是希望以插件的形势来做这些需求。
> 
> 但是还不支持。

大佬 预计何时会提供这方面的支持呢 我想自己改一波 但是水平太差 怕房子塌了.

**Comment by ruibaby** [comment]
@ToForgiveNoll 不会太快。

**Comment by ghostsf** [comment]
先自己整个呗，我貌似也有此需要，有空开发个

**Comment by ToForgiveNoll** [comment]
> 先自己整个呗，我貌似也有此需要，有空开发个

开个源呗

**Comment by SenLief** [comment]
可以用action自动部署，我打算写个脚本，用GitHub做编辑器，利用api自动部署到halo。
