### ISSUE TITLE
hi,this code debug is not work 

### ISSUE THREAD

**Issue by lnsane** [halo-dev/halo#1053]
https://github.com/halo-dev/halo/blob/437d4bd81bc828b4c9cc23f6a122e15726da0771/src/main/java/run/halo/app/controller/admin/api/AdminController.java#L52-L58

I Login my username and password , but the code is not work , please tell me how do it ?

**Comment by ruibaby** [comment]
这是正式调用登录接口前检查是否有两步验证的接口，不是正常的登录接口。在 admin 那边调用登录接口前会先调用一下这个接口，不知道你的问题在于哪里，看得不是很懂。

**Comment by lnsane** [comment]
> 这是正式调用登录接口前检查是否有两步验证的接口，不是正常的登录接口。在 admin 那边调用登录接口前会先调用一下这个接口，不知道你的问题在于哪里，看得不是很懂。

在idea 2020.2.1版本debug时候我明明看到前端源码调用了这个接口，但是idea确没有任何提示。真神奇。。。
