### ISSUE TITLE
希望文章别名支持英文大写及下划线

### ISSUE THREAD

**Issue by zwc456baby** [halo-dev/halo#1054]
目前 halo 在发布时，设定的别名不支持英文大写及下划线方式。而 hexo 支持，当从 hexo 迁移到 halo 时，会导致一些链接失效

例如：使用 hexo 创建一篇文章：
```
hexo new HelloWorld
hexo g
```
生成的访问链接大概是这样：
https://xxxxxxxxx/2020/09/05/HelloWorld/

而如果导入到halo，设定别名为：`HelloWorld` ，则链接是这样的：
https://xxxxxxxxx/2020/09/05/helloworld/

不支持大小写会使从其它博客迁移过来时，某些链接失效，下划线同理。`hello_world` 会变成：`helloworld`

希望能使别名支持大写及下划线。目前虽然输入框支持输入大写进去，但是刷新之后，自动被格式化为小写。

**Comment by ruibaby** [comment]
Halo 支持识别 markdown 文本的 `Front-matter` 的 `permalink `。

https://hexo.io/docs/front-matter#Settings-amp-Their-Default-Values

直接在 Halo 的小工具里就可以导入 Markdown。

**Comment by zwc456baby** [comment]
> Halo 支持识别 markdown 文本的 `Front-matter` 的 `permalink `。
> 
> https://hexo.io/docs/front-matter#Settings-amp-Their-Default-Values
> 
> 直接在 Halo 的小工具里就可以导入 Markdown。

你好，我的意思不是说不支持识别，而是识别时不支持大小写英文字母：

![IZ3E9Q_4RL}(O`H0U6W@GR8](https://user-images.githubusercontent.com/20961202/92301896-079db700-ef9a-11ea-9ee6-fb999baaeff7.png)

请注意看， `HelloWorld` 中的英文字母 `H` 和 `W` 是大写的，但是导入后，变成小写的 `h` 和 `w` 了

这样会导致原有的 url 和 现有的 url 不同，导致之前的链接失效

**Comment by infinitemecn** [comment]
这个问题可能还是halo需要优化一下slug的自动识别和转换问题：

1. 中文标题是否可以自动转换为拼音？或者翻译为英文(调translate api )？并用短横线分割单词
     e.g.  title:  这是一篇文章 -> slug:  zhe-shi-yi-pian-wen-zhang.html  or slug:  this-is-an-article.html

2. 英文标题转换到slug是否识别单词之间的空格并按照统一的格式做转换，而不是直接把空格、短横线直接去掉，所有单词都挤到一起  
    e.g. title:  hello world  -> slug : hello-world.html  ; title: HelloWorld -> slug: hello-world.html  

当然这只是一个slug默认值的优化，有时能让用户少填一次slug(如果标题是准确的-,-)

**Comment by ruibaby** [comment]
> 这个问题可能还是halo需要优化一下slug的自动识别和转换问题：
> 
> 1. 中文标题是否可以自动转换为拼音？或者翻译为英文(调translate api )？并用短横线分割单词
>    e.g.  title:  这是一篇文章 -> slug:  zhe-shi-yi-pian-wen-zhang.html  or slug:  this-is-an-article.html
> 2. 英文标题转换到slug是否识别单词之间的空格并按照统一的格式做转换，而不是直接把空格、短横线直接去掉，所有单词都挤到一起
>    e.g. title:  hello world  -> slug : hello-world.html  ; title: HelloWorld -> slug: hello-world.html
> 
> 当然这只是一个slug默认值的优化，有时能让用户少填一次slug(如果标题是准确的-,-)

https://github.com/halo-dev/halo/releases/tag/v1.4.0-beta.3

热乎的。
