### ISSUE TITLE
Halo 访问 H2 web控制台连接被拒绝

### ISSUE THREAD

**Issue by LJ-panda** [halo-dev/halo#1055]
您好，最近我访问我的halo数据库时，测试连接能通过，但是一点击连接，页面就白色了，显示被拒了，整个人一脸懵逼，以前是可以正常连接的，想请问下是怎么回事，具体如下图。

- 连接图：
![error](http://image.wandererchen.xyz/wandererchenSite/error_1599401625104.png)

**Comment by ruibaby** [comment]
使用 ip 加端口的形式访问控制台试试，另外也可以尝试换个浏览器试试。

**Comment by LJ-panda** [comment]
谢谢楼主，用你说的方法成功解决了
