### ISSUE TITLE
feat: 关于文章编辑器的建议，让其更专注写作内容本身

### ISSUE THREAD

**Issue by zhangfeibiao** [halo-dev/halo#1060]
## 概述
hello，能否增加像typora这样的所见即所得编辑器，这里有一个很不错的开源编辑器项目推荐可以看一下
https://github.com/Vanessa219/vditor ，提供了三种编辑方式，支持md语法，而且也有自己的markdown渲染引擎增强渲染效果。

## 动机
希望写作的重点更加专注在内容本身，老实说我本人如果在分屏模式下，经常会看右侧的排版。
今天看到halo后非常nice，功能很强大，如果编辑器能够提升的话，相信会更棒，当然我自身也会迁移到halo使用。

## 详细解释
上述推荐的编辑器开源项目很不错，其开源作者本身也是将其项目另外应用到了自身开发的社区端、博客端、桌面应用等程序上，体验友好度上应该是可以保障的，感谢查阅。

**Comment by JohnNiang** [comment]
我尝试过用 <https://tiptap.dev/> 自定义编辑器，不过该编辑器对 markdown 支持得还不是特别好，特别是无法获取到源 markdown 格式的内容，富文本格式支持得挺好的。

**Comment by ruibaby** [comment]
感谢你的建议和推荐的编辑器，Vditor 很不错，但我们并不打算使用。

之前的讨论 https://github.com/halo-dev/halo/issues/989


@JohnNiang 我认为没有必要纠结对 Markdown 的支持程度，使用 Markdown 也不是编辑体验好的唯一因素，反而在某些特殊的场景使用体验很不好。

**Comment by zhangfeibiao** [comment]
> 感谢你的建议和推荐的编辑器，Vditor 很不错，但我们并不打算使用。
> 
> 之前的讨论 #989
> 
> @JohnNiang 我认为没有必要纠结对 Markdown 的支持程度，使用 Markdown 也不是编辑体验好的唯一因素，反而在某些特殊的场景使用体验很不好。

好的，明白。
