### ISSUE TITLE
feat: 关于URL自定义的程度能否更高一些

### ISSUE THREAD

**Issue by veneris** [halo-dev/halo#1061]
## 概述

1. 自定义页面能否不需要前缀，大多数博客的自定义页面，例如关于页面，都是/about，而不是/s/about；
2. 文章的固定链接，是否可以允许自定义，提供{slug}，{id}等参数允许用户自己输入拼接，而不是固定的几个选项；

## 动机

1. 从其他的旧站迁移时候，已有的固定URL不能满足；
2. 利于SEO；
3. 强迫症；

感谢作者。

**Comment by praming** [comment]
强烈附议，这两点都是我想提的！！

**Comment by aumk** [comment]
再附议一条，URL支持非中文字符。
自动把日文字符都去掉了。

**Comment by laijinyou** [comment]
附议

**Comment by LIlGG** [comment]
已经提交了 issue，参见 #1177 以及 #1174

**Comment by LIlGG** [comment]
至于文章的 {slug}，本身便是可以自定义的，如下
![image](https://user-images.githubusercontent.com/31335418/101229430-2f0c3900-36db-11eb-9e92-a2dd72746182.png)

**Comment by veneris** [comment]
关于自定义链接，我的意思是，给定用户几个变量，例如{slug}，{year}，{month}，{day}，{id}等，然后用户可以自己根据以上的变量去搭配出来自己需要的链接形式，而不是固定的这几种组合方式。
![image](https://user-images.githubusercontent.com/28482172/101232667-d5613a00-36ed-11eb-9117-5fdb2b7f9514.png)

**Comment by LIlGG** [comment]
收到

**Comment by ruibaby** [comment]
> 关于自定义链接，我的意思是，给定用户几个变量，例如{slug}，{year}，{month}，{day}，{id}等，然后用户可以自己根据以上的变量去搭配出来自己需要的链接形式，而不是固定的这几种组合方式。
> ![image](https://user-images.githubusercontent.com/28482172/101232667-d5613a00-36ed-11eb-9117-5fdb2b7f9514.png)

目前做不到，有机会会尝试。
