### ISSUE TITLE
别名的字符问题

### ISSUE THREAD

**Issue by jianfei96** [halo-dev/halo#1063]
## 我的环境

版本：1.4.0-beta.3
数据库：H2 1.4.196 (2017-06-10)
运行模式：production
User Agent：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36
---

## 错误日志

日志并未报错

---

## 期望行为

读取标题作为“文章别名”，且可以为任意语言
## 当前行为
标题：`G検定公式テキスト　一部要点まとめ`
别名会生成：`g検定公式一部要点`
手动设置依然无效

日文字符直接被全部切掉了

**Comment by ruibaby** [comment]
很不建议使用标题作为别名，但我们会尝试去兼容。
