### ISSUE TITLE
feat: 关于halo webp图片格式支持的问题

### ISSUE THREAD

**Issue by LeagueJhin** [halo-dev/halo#1067]
## 概述
支持webp图片上传与解析

## 动机

webp对于页面访问是很好的压缩图片格式

**Comment by ruibaby** [comment]
会尝试兼容，不过我觉得有更好的方案，推荐 https://halo.run/archives/halo-and-webp.html

**Comment by LeagueJhin** [comment]
谢谢，这个方案如果可以嵌入到内部是极好的，不过部署没什么难度
