### ISSUE TITLE
图片上传jpg闪黑屏无法上传

### ISSUE THREAD

**Issue by LeagueJhin** [halo-dev/halo#1071]
## 我的环境
已经尝试从issues中查找解决方案，但个人能力有限并无法解决

版本：1.3.2
数据库：MySQL 8.0.21
运行模式：production
User Agent：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4260.0 Safari/537.36 Edg/87.0.637.0
---

## 错误日志

[halo-log-1600081497943.log](https://github.com/halo-dev/halo/files/5217991/halo-log-1600081497943.log)

---

## 期望行为

希望jpg上传成功
## 当前行为
![image](https://user-images.githubusercontent.com/44092516/93078592-54317280-f6bd-11ea-9cf1-747940190948.png)
![2233](https://user-images.githubusercontent.com/44092516/93078601-58f62680-f6bd-11ea-9375-f68f1affeff1.jpg)

**Comment by LeagueJhin** [comment]
有的jpg又可以上传成功，不知道是否是图片上传大小 或者分辨率限制

**Comment by ruibaby** [comment]
这个日志看不出来是什么问题。我看你这图片有2.8m，是不是因为被 Nginx 拦截了？

https://halo.run/archives/other-faq.html#q4-%E4%B8%BA%E4%BB%80%E4%B9%88%E4%B8%8A%E4%BC%A0%E4%B8%BB%E9%A2%98%E6%88%96%E8%80%85%E9%99%84%E4%BB%B6%E4%BC%9A%E5%A4%B1%E8%B4%A5413-request-entity-too-large

**Comment by JohnNiang** [comment]
以上错误日志中的错误和上传接口没有关联的。如果没有报别的错误，那么极有可能是 nginx 的限制。可以看看上传后浏览器的报错信息。

**Comment by LeagueJhin** [comment]
抱歉叨扰了，，同一个nginx 也配置了 wordpress的sakura主题 之前设置过，忽略了不在同一个server下。
