### ISSUE TITLE
部署到github

### ISSUE THREAD

**Issue by FelicxFoster** [halo-dev/halo#1074]
请问可以像hexo那样部署到github page吗，不用部署在自己服务器上

**Comment by ruibaby** [comment]
不支持，之前打算支持，但是后面因为各种原因砍掉了。

**Comment by FelicxFoster** [comment]
好的谢谢

**Comment by ruibaby** [comment]
> > 不支持，之前打算支持，但是后面因为各种原因砍掉了。
> 
> 
> 
> 砍掉的原因是什么?

动态 CMS 和静态页面生成框架几乎是完全不同的架构，我们很难综合起来考虑动态和静态这两种部署或者说页面生成方式。

目前有很多功能都要依赖后端服务，比如评论、搜索、数据统计，以及不少插件都需要依赖后端。即便我们能通过一些手段使用其他方案为静态页面生成提供适配，那只会让这个程序变的越来越不伦不类。

如果一定要使用 Halo 作为数据提供方，用于为静态页面生成提供数据，那么目前最好的方案是结合市面上的 SSG 框架，比如 Astro、Nuxt.js、Next.js 等，他们都支持通过不同的数据源来做 SSG。比如 https://github.com/AeroWang/theme-next
