### ISSUE TITLE
feat: 增加视频库

### ISSUE THREAD

**Issue by sheiy** [halo-dev/halo#1078]
## 概述

有些自己收藏的视频可以像图库一样保存起来，并且可以在文章中引用

## 动机

有些东西用图片和语言不怎么好描述，还有收藏视频的功能

## 详细解释

这个应该没什么好详细解释的

**Comment by ruibaby** [comment]
@sheiy 目前不会考虑内置在系统里。等插件机制。

**Comment by sheiy** [comment]
@ruibaby 了解
