### ISSUE TITLE
使用docker版本的halo，升级成最新的版本后，原先安装的主题已经没了

### ISSUE THREAD

**Issue by NGLSL** [halo-dev/halo#108]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://docs.halo.run/)
- [x] [Github Wiki 常见问题](https://github.com/ruibaby/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/ruibaby/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

拉取最新的代码，构建成了docker image ，推送到了个人的服务器中，将旧的容器删除运行新的容器后，之前安装的主题已经不在了。

**Comment by JohnNiang** [comment]
好的，明天我们将 Check 一下。

**Comment by ruibaby** [comment]
@NGLSL 因为主题的目录没有挂载到宿主机，我想办法解决下。

**Comment by JohnNiang** [comment]
@ruibaby 可以考虑在 Halo 启动的时候自动 sync 一下。

**Comment by ruibaby** [comment]
在 V1 中，该问题已经不存在。
