### ISSUE TITLE
feat: 新增附件分组功能

### ISSUE THREAD

**Issue by guqing** [halo-dev/halo#1084]
## 概述
新增对文章附件进行分组展示功能，包括如下功能:
- 在附件管理页对附件以文件夹和文件的形式展示
- 可以新增文件夹即附件分组
- 可以对附件进行移动（归类到文件夹或舍弃归类）
- 可以删除分组（如果文件夹下包含文件递归删除）

## 动机
附件分组功能可以更高效和简洁的管理附件，防止附件杂乱无章
例如我可以将文章插图归类到**文章插图**文件夹，将图库所需要展示的附件归类到**图库**文件夹等等
## 详细解释
附件管理页面展示的列表为文件夹和附件混合,如（忽略样式）:
![image](https://user-images.githubusercontent.com/38999863/94222413-df153700-ff1f-11ea-8d02-080eb712b87d.png)

## 细节讨论
- 分组是否允许多子级，如果不允许则只能新建第一层文件夹，文件夹里不允许包含文件夹
- 是否新增切换展示方式功能，点击切换按钮可以以文件夹形式（如果附件没有分组则展示附件）展示或扁平化分页展示附件列表（不以文件夹的形式展示）
- 删除文件夹时是否递归删除文件夹下的所有内容
- 是否支持排序

## 实现方式
**附件分组功能**
1. 新建附件分组类并映射到表：
| 属性名     | 类型    | 说明     |
| ---------- | ------- | -------- |
| id         | Integer | 分组id   |
| parentId         | Integer | 附级分组id   |
| name       | String  | 分组名称 |
| createTime | Date    | 创建时间 |
| updateTime | Date    | 更新时间 |
| deleted    | Boolean | 删除状态 |

2. 为附件`Attachment`类新增`附件分组id`属性以表示附件所属文件夹，如果为`null`则表示附件不属于任何分组

**附件列表功能**
接口返回值
```
class 分组With附件DTO {
    List 分组集合;
    List 文件集合;
}
```
1. 页面将`分组集合`以文件夹样式渲染，在将`文件集合`以文件样式渲染得到附件管理列表
2. 点击切换时扁平化显示附件（分页查询附件并以附件样式渲染）
3. 点击文件夹时按`文件夹id`查询得到`分组With附件DTO`并重复`步骤1`,如果分组不允许多子层级则展示该分组下的文件

**移动功能**
如果是附件则将附件的`分组id`更新为所属分组id,如果时分组则将分组的`parentId`更新为所属`分组id`

**删除功能**
- 如果删除分组时一并删除分组下的文件和文件夹：递归将文件夹下的所有附件和分组的`deleted`更新为`true`
- 如果删除分组时不删除子级: 
  - [单层级] 将文件夹下的所有附件的`分组id`更新为`null`
  - [多层级] 将文件夹下的所有附件的`分组id`更新为`null`,并将所有子分组的parentId更新为上层`分组id`

**Comment by ruibaby** [comment]
小说不看了？

**Comment by guqing** [comment]
@ruibaby 上班不能看小说🌚  小说在手机上  最多只能用听的

**Comment by guqing** [comment]
@guqing 预览草图:  https://www.figma.com/file/XKtXzVklts6tssmNtTY8Wg/Figma-Admin-Dashboard-UI-Kit-Community?node-id=0%3A1

**Comment by ruibaby** [comment]
> https://www.figma.com/file/XKtXzVklts6tssmNtTY8Wg/Figma-Admin-Dashboard-UI-Kit-Community?node-id=0%3A1

是否要区分一下文件来源。

**Comment by guqing** [comment]
@ruibaby 啥文件来源 存储位置吗

**Comment by ruibaby** [comment]
> @ruibaby 啥文件来源 存储位置吗

嗯，要不要独立一下。

**Comment by guqing** [comment]
@ruibaby 如果是切换为item布局可以显示文件来源

**Comment by ruibaby** [comment]
> @ruibaby 如果是切换为item布局可以显示文件来源

不是，我的意思是如果筛选条件选择了存储位置，那么列表应该怎么展示。

**Comment by guqing** [comment]
@ruibaby 现在的存储位置筛选好像是只能选择一个  如果只能选择一个的话就没必要显示存储位置  如果存储位置条件允许多选的话 或许只能在文件名前或者上方显示一个存储位置

**Comment by Htryhard** [comment]
特地登录账号来提一下是否考虑加附件分组的功能，就看到网友提来，顶一下

**Comment by guqing** [comment]
> 特地登录账号来提一下是否考虑加附件分组的功能，就看到网友提来，顶一下

该功能正在讨论中，具体是否开发  现在还无法告知你

**Comment by ruibaby** [comment]
目前已经支持分组+多策略，欢迎体验：https://github.com/halo-dev/halo/releases/tag/v2.0.0

/close
