### ISSUE TITLE
feat: 希望能够增加短网址功能

### ISSUE THREAD

**Issue by SplendorAnLin** [halo-dev/halo#1086]
文章分享出去每次都是一长串网址，也不想依赖其他三方提供的短网址服务。主要还是怕跑路，影响之前的浏览。

**Comment by ruibaby** [comment]
使用博客域名做短网址服务？不太明白你需求的场景。

**Comment by ruibaby** [comment]
长时间未回复，先关闭了，如有其他补充可以 reopen。
