### ISSUE TITLE
使用Anatole主题时，点击菜单出现404，而使用Next-halo-1.4，则不会出现这个问题

### ISSUE THREAD

**Issue by NGLSL** [halo-dev/halo#109]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://docs.halo.run/)
- [x] [Github Wiki 常见问题](https://github.com/ruibaby/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/ruibaby/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

使用Anatole主题时，点击菜单出现404，而使用Next-halo-1.4，则不会出现这个问题。

**Comment by ruibaby** [comment]
@NGLSL 发一下你的博客地址

**Comment by NGLSL** [comment]
@ruibaby http://www.codedream.xin

**Comment by NGLSL** [comment]
@ruibaby 

在什么情况下，这里的图片不会出来？

![image](https://user-images.githubusercontent.com/40338580/53717626-b76d0280-3e93-11e9-9839-9ff41bffddad.png)

**Comment by ruibaby** [comment]
@NGLSL 你服务器不支持中文的情况下

**Comment by NGLSL** [comment]
@ruibaby 但是在上一个版本它是可以的

**Comment by JohnNiang** [comment]
@NGLSL 请问您刚刚是更新了一波么？

**Comment by NGLSL** [comment]
@ruibaby 是的，我没有使用我自己的构建的镜像了，现在用的是ruibaby/halo镜像

**Comment by JohnNiang** [comment]
@NGLSL 问题似乎消失了哦。

**Comment by NGLSL** [comment]
> @NGLSL 问题似乎消失了哦。

并没有，你可以试试点击菜单，我现在切换了主题。

**Comment by ruibaby** [comment]
@NGLSL 这个主题没有category.ftl模板

**Comment by ruibaby** [comment]
@NGLSL 我待会儿提交一个

**Comment by NGLSL** [comment]
> @NGLSL 我待会儿提交一个

好的

**Comment by ruibaby** [comment]
@NGLSL 已修复，在dev分支，你自己copy一个category.ftl到你的文件夹下面即可。
