### ISSUE TITLE
屏蔽搜索引擎的功能无效

### ISSUE THREAD

**Issue by ghostsf** [halo-dev/halo#1091]
## 我的环境

版本：1.4.0
数据库：MySQL 5.7

## 期望行为

屏蔽搜索引擎 屏蔽各大搜索引擎

## 当前行为

![image](https://user-images.githubusercontent.com/9978816/94368918-6bd71500-0119-11eb-9c07-4af9a66820b1.png)

屏蔽后仍有大量搜索引擎爬取请求日志

xxx `Request Method: [GET], IP: [49.7.20.90]`  xxx

![image](https://user-images.githubusercontent.com/9978816/94368997-d12b0600-0119-11eb-9b12-65539f29c6fb.png)

**Comment by ruibaby** [comment]
这功能属于防君子不防小人，希望你能理解。

**Comment by ghostsf** [comment]
> 这功能属于防君子不防小人，希望你能理解。

OK
