### ISSUE TITLE
关于docker容器删除并重启后建站日期更新的问题

### ISSUE THREAD

**Issue by niannianyu** [halo-dev/halo#1093]
## 我的环境

版本：1.4.0
---

## 错误日志

---

## 期望行为
docker容器在删除并重新启动后，仪表盘中的“建立天数”依然保留，现在每次都会归零...

## 当前行为
我把容器删除，然后重新运行，会让我走初始化流程（我映射目录没有改变，这也有点奇怪，但是没有出问题，先不管），然后我成功导入停止容器前导出的配置后，发现仪表盘中的建站日期竟然被更新成了新启动的日期...

**Comment by ruibaby** [comment]
嗯，导入数据的时候，建站日期是会被清零的。这算是这个缺陷。

**Comment by ruibaby** [comment]
你可以在开发者选项中的系统变量里手动修改 birthday 的值。

https://halo.run/archives/use-hidden-features.html#%E7%B3%BB%E7%BB%9F%E5%8F%98%E9%87%8F

**Comment by niannianyu** [comment]
所以这个根本原因在于我重新导入吗？因为我之前动了一下数据库，所以不知道如果容器被删除并重新启动（配置不变，原映射目录不变）的情况下是不是依然会要初始化啊？

**Comment by niannianyu** [comment]
那建站日期我直接改数据库理论上是不是也可以的

**Comment by ruibaby** [comment]
> 所以这个根本原因在于我重新导入吗？因为我之前动了一下数据库，所以不知道如果容器被删除并重新启动（配置不变，原映射目录不变）的情况下是不是依然会要初始化啊？

是的，数据导入会重置建站时间。如果你没有删除或者修改数据表 options 里面的 is_installed 值，重新启动不可能会要求重新初始化的。

**Comment by ruibaby** [comment]
> 那建站日期我直接改数据库理论上是不是也可以的

上面给了你解决方案，不需要去手动操作数据库。

![image](https://user-images.githubusercontent.com/21301288/94419226-05073980-01b5-11eb-9811-781f20918c78.png)

**Comment by niannianyu** [comment]
> > 那建站日期我直接改数据库理论上是不是也可以的
> 
> 上面给了你解决方案，不需要去手动操作数据库。
> 
> ![image](https://user-images.githubusercontent.com/21301288/94419226-05073980-01b5-11eb-9811-781f20918c78.png)

ok  了解了

**Comment by Wing-Li** [comment]
开发者选项，现在没有了吗？

**Comment by JohnNiang** [comment]
> 开发者选项，现在没有了吗？

Halo 2.x 是全新的版本，目前暂时没有开发者选项的功能。
