### ISSUE TITLE
七牛云上传附件失败

### ISSUE THREAD

**Issue by wellmoonloft** [halo-dev/halo#110]
报错信息
`{"error":"incorrect region, please use up-z1.qiniup.com"}`
我查了一下大概是这个原因，我在对象存储里面设置的分区是华北，但如果你没有在UploadManager里面特别设置zone的话，它默认往zong1传，zong1是华东。
所以在需要额外暴露一个设置空间区域的设定，或者放yaml里配，合理的应该是在做一个选项在附件设置里面，选择分区。

```java
        //————http上传,指定zone的具体区域——
        //Zone.zone0:华东
        //Zone.zone1:华北
        //Zone.zone2:华南
        //Zone.zoneNa0:北美
        //———http上传，自动识别上传区域——
        //Zone.httpAutoZone
        //———https上传，自动识别上传区域——
        //Zone.httpsAutoZone

        Configuration config = new Configuration.Builder()
                .chunkSize(256 * 1024)  //分片上传时，每片的大小。 默认256K
                .putThreshhold(512 * 1024)  // 启用分片上传阀值。默认512K
                .connectTimeout(10) // 链接超时。默认10秒
                .responseTimeout(60) // 服务器响应超时。默认60秒
                .recorder(null)  // recorder分片上传时，已上传片记录器。默认null
                .recorder(null, null)  // keyGen 分片上传时，生成标识符，用于片记录器区分是那个文件的上传记录
                .zone(Zone.zone2) // 设置区域，指定不同区域的上传域名、备用域名、备用IP。
                .build();
        this.uploadManager = new UploadManager(config);

**Comment by JohnNiang** [comment]
好的，感谢贡献解决方案！我们会认真考虑这个解决方案并尽快修复。

**Comment by JohnNiang** [comment]
@wellmoonloft 希望您有时间测试一下，谢谢！

> IF 没有配置 **qiniu_zone**（用于手动指定 zone）;
> ELSE 将会调用 **com.qiniu.common.Zone.Builder#autoZone**。

**Comment by wellmoonloft** [comment]
> @wellmoonloft 希望您有时间测试一下，谢谢！
> 
> > IF 没有配置 **qiniu_zone**（用于手动指定 zone）;
> > ELSE 将会调用 **com.qiniu.common.Zone.Builder#autoZone**。

收到，今晚回家测试后反馈。

**Comment by wellmoonloft** [comment]
是有问题的，前台显示上传成功，但是存储里面是空的。
跟了半天跟到HaloUtils里面发现OPTIONS.get("qiniu_zone")取不出值，switch是null，无法进行判断，加了一条
`if(qiniuZone == null)  qiniuZone = "xx";`就好了，你可以用正则优化一下。

![image](https://user-images.githubusercontent.com/20944693/53795018-0a19ed80-3f6c-11e9-9b02-117ebce96074.png)

**Comment by JohnNiang** [comment]
> 是有问题的，前台显示上传成功，但是存储里面是空的。
> 跟了半天跟到HaloUtils里面发现OPTIONS.get("qiniu_zone")取不出值，switch是null，无法进行判断，加了一条
> `if(qiniuZone == null) qiniuZone = "xx";`就好了，你可以用正则优化一下。
> 
> ![image](https://user-images.githubusercontent.com/20944693/53795018-0a19ed80-3f6c-11e9-9b02-117ebce96074.png)

尴尬！ 忘记判空了。立即修复！
