### ISSUE TITLE
window 怎么指定配置文件启动啊 application.yaml

### ISSUE THREAD

**Issue by a610569731** [halo-dev/halo#1100]
怎么启动 jar 包 指定配置文件修改端口？

**Comment by ruibaby** [comment]
文档上的 `~/.halo` 对应 Windows 下的 c:/users/{user}/.halo。所以你去你系统的用户目录的 .halo 文件夹下创建 application.yaml 就可以识别到了，其他地方和文档一致。

`~` 在绝大多数操作系统都代表当前登录用户的用户目录。
