### ISSUE TITLE
feat: ID型url改为伪静态

### ISSUE THREAD

**Issue by praming** [halo-dev/halo#1103]
## 概述

1.希望ID型url可以改成伪静态，如：“archives/1”。
2.单页的“/s/xxx”可否去掉前缀的“/s/”。

## 动机

1.其他很多程序都有 “archives/1”之类的url，修改后其他程序url可以无损转入。
2. “http://xxx.com/s/about” 总是不如 “http://xxx.com/about” 看着舒服 。

**Comment by ruibaby** [comment]
1. 可以。
2. 不是不想去掉，我们也想去掉，比较麻烦。建议换成比较顺眼的。比如 `/p/`

**Comment by praming** [comment]
好的 👍
