### ISSUE TITLE
重装主题后的缓存问题

### ISSUE THREAD

**Issue by codesensi** [halo-dev/halo#1106]
大佬，我想问一下，我把自己修改的主题删除了，服务也重启了，浏览器的缓存也清理了，cdn也刷新了，然后重新上传的未修改的主题，但是主题还是有我之前自己修改的内容。请问这是缓存问题吗？还是这是主题的问题？我该怎么处理

**Comment by LIlGG** [comment]
是修改的主题文件吗？应该不是主题配置吧？

**Comment by ruibaby** [comment]
不好判断，你删除主题的话，服务器上的物理文件会被删除，所以理论上你再上传新主题，之前的修改的内容将不会存在。

**Comment by codesensi** [comment]
> 是修改的主题文件吗？应该不是主题配置吧？

修改的是主题文件

**Comment by codesensi** [comment]
> 不好判断，你删除主题的话，服务器上的物理文件会被删除，所以理论上你再上传新主题，之前的修改的内容将不会存在。

后台日志并没有相关的报错

**Comment by LIlGG** [comment]
> > 是修改的主题文件吗？应该不是主题配置吧？
> 
> 修改的是主题文件

那确实不好判断，你在后台删除完之后，再去服务器物理地址下看一下是否删掉了

**Comment by codesensi** [comment]
> > > 是修改的主题文件吗？应该不是主题配置吧？
> > 
> > 
> > 修改的是主题文件
> 
> 那确实不好判断，你在后台删除完之后，再去服务器物理地址下看一下是否删掉了

好勒，多谢大佬
