### ISSUE TITLE
feat: Halo api 增加创建文章api

### ISSUE THREAD

**Issue by SenLief** [halo-dev/halo#1108]
## 概述
目前我看到api都是获取文章类的，请问能增加创建类的api吗？

后台编辑器不好用，想用自己的编辑器来写。
## 动机
增强后端能力

**Comment by SenLief** [comment]
API后台开启自己设置好access_key后，设置header为ADMIN-Authorization字段，值为ak,但是响应401，后台查看显示Token已过期或不存在。

**Comment by ruibaby** [comment]
@SenLief 那是 content api 授权用的，admin api 需要先登录授权拿到 token。

**Comment by SenLief** [comment]
> @SenLief 那是 content api 授权用的，admin api 需要先登录授权拿到 token。

那登录授权是如何授权的？Basic Auth授权吗？这些api文档也没有啊。崩溃了。

**Comment by ruibaby** [comment]
> > @SenLief 那是 content api 授权用的，admin api 需要先登录授权拿到 token。
> 
> 
> 
> 那登录授权是如何授权的？Basic Auth授权吗？这些api文档也没有啊。崩溃了。

https://api.halo.run/admin-api.html#operation/authUsingPOST

**Comment by SenLief** [comment]
> > > @SenLief 那是 content api 授权用的，admin api 需要先登录授权拿到 token。
> > 
> > 
> > 那登录授权是如何授权的？Basic Auth授权吗？这些api文档也没有啊。崩溃了。
> 
> https://api.halo.run/admin-api.html#operation/authUsingPOST

终于是成功获取了，感谢。这个每次获取token都必须要两步认证吗？没看到其他方案来着。

**Comment by ruibaby** [comment]
precheck 只是用来判断是否开了二次验证，实际登录接口还是 login。可以参考 admin 的逻辑。

https://github.com/halo-dev/halo-admin/blob/master/src/components/Login/LoginForm.vue

**Comment by SenLief** [comment]
> precheck 只是用来判断是否开了二次验证，实际登录接口还是 login。可以参考 admin 的逻辑。
> 
> https://github.com/halo-dev/halo-admin/blob/master/src/components/Login/LoginForm.vue

是真的不懂前端的逻辑，我看api文档authcode不能忽略，我意思是如果后台没有开启二次认证，那么能不能不提交这个字段，只提交username和password来认证呢？

**Comment by ruibaby** [comment]
@SenLief 可以。直接用login接口即可。

**Comment by SenLief** [comment]
> @SenLief 可以。直接用login接口即可。

多谢！
