### ISSUE TITLE
环境信息有误？

### ISSUE THREAD

**Issue by kkonghao** [halo-dev/halo#1109]
已经更新到最新的1.4.1版本，为什么环境信息还是现实1.3.2呢？是没更新成功么？
![image](https://user-images.githubusercontent.com/57028687/95934943-a5d83480-0e04-11eb-8cdf-c2f5b719c71b.png)

**Comment by ruibaby** [comment]
没有

**Comment by kkonghao** [comment]
> 没有

可是按照步骤升级之后，版本信息怎么没变化呢

**Comment by ruibaby** [comment]
请给出你的环境信息和升级步骤，不然我们没有办法判断。

**Comment by kkonghao** [comment]
我是按照1.4.0下面的升级步骤升级的1.4.1

停止运行 Halo：service halo stop。
备份数据：cp -r ~/.halo ~/.halo.bak。
重命名（备份）旧运行包：mv halo-latest.jar halo-latest.jar.bak。
下载新运行包：wget https://dl.halo.run/release/halo-1.4.1.jar -O halo-latest.jar。
运行：service halo start。

环境信息：
版本：1.3.2
数据库：H2 1.4.196 (2017-06-10)
运行模式：production
启动时间：2020-10-14 10:19


升级后还是显示1.3.2
如果升级有误烦请告知，谢谢哈

**Comment by kkonghao** [comment]
> 我是按照1.4.0下面的升级步骤升级的1.4.1
> 
> 停止运行 Halo：service halo stop。
> 备份数据：cp -r ~/.halo ~/.halo.bak。
> 重命名（备份）旧运行包：mv halo-latest.jar halo-latest.jar.bak。
> 下载新运行包：wget https://dl.halo.run/release/halo-1.4.1.jar -O halo-latest.jar。
> 运行：service halo start。
> 
> 环境信息：
> 版本：1.3.2
> 数据库：H2 1.4.196 (2017-06-10)
> 运行模式：production
> 启动时间：2020-10-14 10:19
> User Agent：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36
> 升级后还是显示1.3.2
> 如果升级有误烦请告知，谢谢哈

**Comment by ruibaby** [comment]
地址提供一个。

**Comment by kkonghao** [comment]
> 地址提供一个。

是博客地址么？还是

**Comment by ruibaby** [comment]
@kkonghao 嗯

**Comment by kkonghao** [comment]
https://myblogs.cool/

**Comment by ruibaby** [comment]
确实没有升级，仔细检查一下吧。我们也不知道你服务器的具体情况。

**Comment by kkonghao** [comment]
> 确实没有升级，仔细检查一下吧。我们也不知道你服务器的具体情况。

好的，我再检查下，谢谢
