### ISSUE TITLE
feat: 增加文章明文加密

### ISSUE THREAD

**Issue by 1205747671** [halo-dev/halo#1113]
## 概述
希望增加文章加密功能，登录后台后私密文章需要输入秘钥才能查看，数据库非明文储存。

## 动机
朋友要看下后台，或者账号密码被破等等安全问题，可以防止私密文章被泄露。

**Comment by zwc456baby** [comment]
连后台密码都已经泄露了。那么无论样加密都没用吧，毕竟有了后台密码。那么数据库都可以直接导出了。

而且管理员的意义不就是最高权限么。万一这个加密文章的秘钥丢失，或者忘了，又该怎么找回呢。

如果设定找回机制，校验的数据最终还是存储在 h2 数据库中，然后数据库又回到上面的问题，有了后台密码，数据库可以导出。

这样的话后台系统得做成多用户或者说多级用户权限。普通的后台管理员权限没有最高权限。

这就不是普通的个人博客系统了吧，算是允许注册和登录的博客平台了。。。

**Comment by zwc456baby** [comment]
这就像 Linux 电脑的 root 账号密码都给了黑客了，然后 Linux 还要保证你的安全。。。

所以 Linux 搞出了一个 SELinux

**Comment by 1205747671** [comment]
> 连后台密码都已经泄露了。那么无论样加密都没用吧，毕竟有了后台密码。那么数据库都可以直接导出了。
> 
> 而且管理员的意义不就是最高权限么。万一这个加密文章的秘钥丢失，或者忘了，又该怎么找回呢。
> 
> 如果设定找回机制，校验的数据最终还是存储在 h2 数据库中，然后数据库又回到上面的问题，有了后台密码，数据库可以导出。
> 
> 这样的话后台系统得做成多用户或者说多级用户权限。普通的后台管理员权限没有最高权限。
> 
> 这就不是普通的个人博客系统了吧，算是允许注册和登录的博客平台了。。。

我还是觉得很有必要啊，就像手机借别人了但是可以加上应用锁。数据库是没有对外网开放，如果加密文章不存明文应该不会泄露。

**Comment by ruibaby** [comment]
评估之后决定暂时不考虑该功能。
