### ISSUE TITLE
halo用docker创建容器经常创建完就自动退出

### ISSUE THREAD

**Issue by xjchenGit** [halo-dev/halo#1115]
halo用docker创建容器经常创建完就自动退出

**Comment by ruibaby** [comment]
@xjchenGit 看日志。

**Comment by xjchenGit** [comment]
但是那個容器已经自动退出了，我无法通过：docker logs contain_id 的方式查看

**Comment by ruibaby** [comment]
@xjchenGit 会保存在宿主机的 ~/.halo/logs

**Comment by xjchenGit** [comment]
我想请教下怎样才能最快定位到失败的原因

**Comment by ruibaby** [comment]
@xjchenGit 就是看日志呀，因为我们文档的 docker 构建命令加了 -rm 参数，所以 halo 只要启动报错就会自动删除容器。你可以去掉 -rm 参数再构建看看日志。或者按照我上面说的去看日志文件。

**Comment by xjchenGit** [comment]
解決了謝謝
