### ISSUE TITLE
发布、预览空内容文章->服务错误

### ISSUE THREAD

**Issue by ufan0** [halo-dev/halo#1118]
发布、预览空内容文章->服务错误

部署的版本为1.4.1，我检索过其他issues没发现报告这个问题。
不知道这是feature还是bug，修正方案是允许空内容文章还是修正页面提示语呢？
我可以提PR。

**Comment by JohnNiang** [comment]
That's a bug.

**Comment by ruibaby** [comment]
这是一个 bug，不过已经在 https://github.com/halo-dev/halo/pull/1099 修复。
