### ISSUE TITLE
Markdown附件不能正常显示

### ISSUE THREAD

**Issue by lzmvlog** [halo-dev/halo#1121]
七牛云上传图片Markdown不能显示，后台附件管理也不能正常显示图片，修复后的版本v1.4.1
暂时不知道是七牛云的问题还是Markdown

**Comment by ruibaby** [comment]
打开 F12 一看便知。

**Comment by WenyinWei** [comment]
![image](https://user-images.githubusercontent.com/33152225/98199656-a75dce00-1f66-11eb-893a-40085f91ee75.png)

你好，我也碰到了这个问题，我用的是又拍云，Halo 1.4.2，报告如上。
