### ISSUE TITLE
markdown表格显示不对，麻烦告知一下怎么操作

### ISSUE THREAD

**Issue by guoyuncong** [halo-dev/halo#1123]
页面上这么显示
![1603637981(1)](https://user-images.githubusercontent.com/31962518/97110739-dcbc1d80-1715-11eb-948e-e5b806ee4056.png)
要肿么改

**Comment by ruibaby** [comment]
![image](https://user-images.githubusercontent.com/21301288/97110778-17be5100-1716-11eb-8940-62332d9c6fc7.png)
![image](https://user-images.githubusercontent.com/21301288/97110779-1ab94180-1716-11eb-96c6-cee387b0ebb7.png)


没有成功复现，请提供可以复现的 Markdown 文本案例。

**Comment by guoyuncong** [comment]
http://www.guoyuncong.com/archives/mysql%E6%95%B0%E6%8D%AE%E7%B1%BB%E5%9E%8B

**Comment by guoyuncong** [comment]
麻烦看一下这个

**Comment by ruibaby** [comment]
```
MySQL 支持所有标准 SQL 数值数据类型。这些类型包括严格数值数据类型(INTEGER、SMALLINT、DECIMAL 和 NUMERIC)，以及近似数值数据类型(FLOAT、REAL 和 DOUBLE PRECISION)。

|column1|column2|column3|
|-------|-------|-------|
|content1|content2|content3|
```

表格语法和上方文本加一个换行符就好了，这应该属于一个缺陷。

**Comment by guoyuncong** [comment]
非常感谢，已解决。
