### ISSUE TITLE
feat: 新增文章插入视频

### ISSUE THREAD

**Issue by ybmiao** [halo-dev/halo#1126]
## 概述
新增文章文章编辑插入视频

## 动机
丰富文章内容

**Comment by ruibaby** [comment]
那么你希望是怎样的？希望有个大改描述。

**Comment by jiangqiang2020** [comment]
我也希望文章内容中能直接插入视频。

**Comment by LIlGG** [comment]
> 我也希望文章内容中能直接插入视频。

等待富文本组件重写之后，这个功能应该还是很方便嵌入的。现在想嵌入的话实在是没有好的思路， 但想重写富文本组件不是那么容易的事，因此暂时来说可能无法实现这个功能。当前的话就手动编写html，比如可以采用第三方的 iframe 来实现这个功能吧。。【之后重写之后，其实也是这种方式。】

**Comment by jiangqiang2020** [comment]
> > 我也希望文章内容中能直接插入视频。
> 
> 等待富文本组件重写之后，这个功能应该还是很方便嵌入的。现在想嵌入的话实在是没有好的思路， 但想重写富文本组件不是那么容易的事，因此暂时来说可能无法实现这个功能。当前的话就手动编写html，比如可以采用第三方的 iframe 来实现这个功能吧。。【之后重写之后，其实也是这种方式。】

隔壁社区有个vditor编辑器，感觉还行，有没有考虑过搬过来用？

**Comment by ruibaby** [comment]
> > > 我也希望文章内容中能直接插入视频。
> > 
> > 
> > 等待富文本组件重写之后，这个功能应该还是很方便嵌入的。现在想嵌入的话实在是没有好的思路， 但想重写富文本组件不是那么容易的事，因此暂时来说可能无法实现这个功能。当前的话就手动编写html，比如可以采用第三方的 iframe 来实现这个功能吧。。【之后重写之后，其实也是这种方式。】
> 
> 隔壁社区有个vditor编辑器，感觉还行，有没有考虑过搬过来用？

抱歉，不会考虑。

**Comment by LIlGG** [comment]
> > > > 我也希望文章内容中能直接插入视频。
> > > 
> > > 
> > > 等待富文本组件重写之后，这个功能应该还是很方便嵌入的。现在想嵌入的话实在是没有好的思路， 但想重写富文本组件不是那么容易的事，因此暂时来说可能无法实现这个功能。当前的话就手动编写html，比如可以采用第三方的 iframe 来实现这个功能吧。。【之后重写之后，其实也是这种方式。】
> > 
> > 
> > 隔壁社区有个vditor编辑器，感觉还行，有没有考虑过搬过来用？
> 
> 抱歉，不会考虑。

无情的回复机器
