### ISSUE TITLE
希望在编写文章的时候，能实时的把内容存储到sessionstorage，避免意外刷新页面导致数据丢失。

### ISSUE THREAD

**Issue by jiangqiang2020** [halo-dev/halo#1129]
希望在编写文章的时候，能实时的把内容存储到sessionstorage，避免意外刷新页面导致数据丢失，并且希望能自动保存到草稿最好。

**Comment by ruibaby** [comment]
暂时不考虑做这个。

https://github.com/halo-dev/halo-admin/issues/229

**Comment by LIlGG** [comment]
之前考虑做过这个，也编写了一些代码，但目前还有一些问题还需要待解决。
