### ISSUE TITLE
使用nginx做代理时，是否支持nginx二级目录的方式？

### ISSUE THREAD

**Issue by RuoLing** [halo-dev/halo#1132]
使用nginx做代理时，是否支持nginx二级目录的方式？

**Comment by ruibaby** [comment]
@RuoLing 不支持。

**Comment by yuhldr** [comment]
希望可以支持一下，nextcloud、gitlab等都支持了二级目录；我想在我们课题组网站下面部署一个，没有多余的外网访问端口
