### ISSUE TITLE
feat: 在编写Markdown文档的时候，我觉得是否该使用 editor.md 工具

### ISSUE THREAD

**Issue by yinxiulong** [halo-dev/halo#1134]
## 概述

  写文章功能的编辑器建议。
  

## 动机

  在使用了 halo 写文档的时候，没发现有快捷键的功能，那样在编写markdown文档的时候很痛苦。效率很低。
  之前我一直使用的工具是 editor.md  （https://pandao.github.io/editor.md/） 它有一个好处，就是在编辑markdown 文档的时候能使用快捷键来输入markdown 的语法，大大提升了写markdown 文档的速度。不用每次去关心markdown语法。

**Comment by ruibaby** [comment]
不考虑 editor.md。

关于编辑器的相关讨论：https://github.com/halo-dev/halo/issues/989

**Comment by yinxiulong** [comment]
为什么不考虑 ？

**Comment by ruibaby** [comment]
目前编辑器也支持快捷键。https://github.com/hinesboy/mavonEditor#%E5%BF%AB%E6%8D%B7%E9%94%AE

**Comment by ruibaby** [comment]
> 为什么不考虑 ？

超过6年不维护的产品...

**Comment by yinxiulong** [comment]
要是有其他的编辑器，在写markdown 而且都支持快捷键。我觉得还是满不错。

**Comment by ruibaby** [comment]
> 要是有其他的编辑器，在写markdown 而且都支持快捷键。我觉得还是满不错。

编辑器是我们下一步的主要开发目标，耐心等待。目前编辑器的快捷键支持在上面的链接。

**Comment by jquanC** [comment]
我之前blog用的就是editor.md，在后台可以编辑并预览公式, 前端的话，公式就无法正常显示
请教下大佬们，如果目前只是想在前端正确渲染markdown+latex语法的文本，有什么方式推荐？

**Comment by ruibaby** [comment]
> 我之前blog用的就是editor.md，在后台可以编辑并预览公式, 前端的话，公式就无法正常显示 请教下大佬们，如果目前只是想在前端正确渲染markdown+latex语法的文本，有什么方式推荐？

在 Halo 1.5 的时候已经支持了保存 Katex 的结构，主题只需要引用 Katex 的 css 文件即可。详情可以查看：https://bbs.halo.run/d/2227-halo-150

**Comment by jquanC** [comment]
谢谢，我找个时间试一下



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ryan ***@***.***&gt;; 
发送时间: 2022年10月31日(星期一) 上午10:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [halo-dev/halo] feat: 在编写Markdown文档的时候，我觉得是否该使用 editor.md 工具 (#1134)





  
我之前blog用的就是editor.md，在后台可以编辑并预览公式, 前端的话，公式就无法正常显示 请教下大佬们，如果目前只是想在前端正确渲染markdown+latex语法的文本，有什么方式推荐？
  
在 Halo 1.5 的时候已经支持了保存 Katex 的结构，主题只需要引用 Katex 的 css 文件即可。详情可以查看：https://bbs.halo.run/d/2227-halo-150
