### ISSUE TITLE
目录下的子目录，没有归并到目录下

### ISSUE THREAD

**Issue by waiting0324** [halo-dev/halo#1136]
## 我的环境

版本：1.4.1
数据库：H2 1.4.196 (2017-06-10)
运行模式：production
启动时间：2020-11-03 10:08

## 期望行为

文章分类的标签，应该包含目录与子目录的标签

## 当前行为

目前在保存文章资讯的时候，前端只有传入子目录ID，并没有传入目录ID，导致子目录下的文章没有归并到目录下

![QQ截图20201105100130](https://user-images.githubusercontent.com/16068120/98188815-b2a4ff80-1f4e-11eb-8619-b8730afbe775.png)

![QQ截图20201105100457](https://user-images.githubusercontent.com/16068120/98188819-b3d62c80-1f4e-11eb-88b3-30c43bc4ef42.png)

**Comment by ruibaby** [comment]
现在的多级分类设计没有考虑这种情况。也就是各个分类是独立的，只是分类之间有层级关系。后面会实现你所说的那种形式。

**Comment by waiting0324** [comment]
了解，因为我的直觉是，
如果我想看学习笔记目录的文章，
那么就应该把学习笔记目录下的文章都列出来，
而非像现在的模式，
学习笔记目录下的文章是空的，
必须要查看基础框架目录才能看到我想看的文章。

**Comment by xvzan** [comment]
既然父节点处在半选择状态时并不会将父节点的ID传出去，那么能否取消父子节点选中状态的关联，让用户自己决定是否选中父节点？
