### ISSUE TITLE
文章修改后，摘要信息不能自动更新

### ISSUE THREAD

**Issue by kenny-qiao** [halo-dev/halo#1137]
## 我的环境

版本：1.4.2
数据库：H2 1.4.196 (2017-06-10)
运行模式：production

---

## 错误日志

无

---

## 期望行为

文章内容修改并保存后，文章摘要信息能够自动更新。

## 当前行为

文章内容修改并保存后，文章摘要信息未发生变动

## 信息补充

1. 文章支持自定义以及自动生成两种摘要信息，并且自定义摘要信息不能被自动生成的覆盖
2. 保存草稿后，数据库中的摘要信息未标记来源是自定义还是自动生成
3. 基于以上两点，故文章后续修改后不能再自动生成摘要信息进行覆盖

**Comment by kenny-qiao** [comment]
@ruibaby 我fork了repo，然后已经修复了这个问题，现在是直接发起一个PR就可以了吗？

**Comment by ruibaby** [comment]
> @ruibaby 我fork了repo，然后已经修复了这个问题，现在是直接发起一个PR就可以了吗？

好的。

**Comment by JohnNiang** [comment]
文章摘要要等到发布文章之后才会更新。

**Comment by kenny-qiao** [comment]
> 文章摘要要等到发布文章之后才会更新。

我在网站上测试了发布，摘要信息并没有更新。😥

**Comment by ruibaby** [comment]
现在的逻辑是，新发布的文章如果没有自定义摘要才回去生成。更新文章是不会进行操作的。这并不是 bug。现在你要求解决的应该是每次编辑文章的时候都会同步去更新摘要。那么我在发布文章的时候就是自定义的摘要呢？也自动去给他刷新吗？

**Comment by kenny-qiao** [comment]
> 现在的逻辑是，新发布的文章如果没有自定义摘要才回去生成。更新文章是不会进行操作的。这并不是 bug。现在你要求解决的应该是每次编辑文章的时候都会同步去更新摘要。那么我在发布文章的时候就是自定义的摘要呢？也自动去给他刷新吗？

嗯，两个问题
1. 自定义摘要，这个疏忽了，可以再修改一下。
2. 发布会更新摘要，这个我在站点后台测试，发现并没有更新摘要。

**Comment by kenny-qiao** [comment]
一个思路：
获取文章信息时，将当前后台存储的摘要信息返回前端。
管理员编辑文章时可以看到当前的摘要信息，然后保存文章时
1. 管理员清空摘要，则表示管理员认为摘要信息需要重新生成，后台接口接收到空的摘要信息，后台生成自动摘要
2. 管理员不清空（无论修改与否）摘要，则可以认为管理员已确认摘要信息无误，后台接口接收到摘要信息，直接保存

**Comment by kenny-qiao** [comment]
@ruibaby 我理解错了，代码没有问题，不好意思。
