### ISSUE TITLE
上传附件是否可以添加用自定义的webapi呢

### ISSUE THREAD

**Issue by mz5210** [halo-dev/halo#1139]
类似picGo的web-uploader插件一样，可以用自己提供的webapi来上传。
![image](https://user-images.githubusercontent.com/29273353/98230805-8c0ab700-1f96-11eb-9b64-ffeecb1aa3f3.png)

**Comment by ruibaby** [comment]
@mz5210 可以考虑，待我们评估

**Comment by ruibaby** [comment]
评估结果，待我们完成 [app id](https://github.com/halo-dev/halo/issues/474) 之后，这个功能将很方便支持。目前你也可以使用 admin api 的上传接口来实现，但 token 可能不太优雅的能获取到。
