### ISSUE TITLE
关于Ehcache的问题

### ISSUE THREAD

**Issue by CodeLunatic** [halo-dev/halo#114]
SpringBoot官方支持Ehcache2.x版本，所以项目中的Ehcache3.x没有起作用，而是使用了默认的SpringCache，希望Git主改一下，亲测~

**Comment by JohnNiang** [comment]
好的，感谢反馈！我们尽快去研究一下，并作出相应的更改。

**Comment by CodeLunatic** [comment]
非常感谢使用你们的博客系统，愿你们技术日渐繁华

发送自 Windows 10 版邮件应用

发件人: John Niang
发送时间: 2019年3月7日 20:12
收件人: halo-dev/halo
抄送: CodeLunatic; Author
主题: Re: [halo-dev/halo] 关于Ehcache的问题 (#114)

好的，感谢反馈！我们尽快去研究一下，并作出相应的更改。

**Comment by ruibaby** [comment]
@CodeLunatic 该问题已修复，非常感谢你的反馈。

**Comment by qrqhuang** [comment]
想了解下， 为什么之前用的Ehcache， 后面出于什么考量自己实现的inmomery呢

**Comment by ruibaby** [comment]
> 想了解下， 为什么之前用的Ehcache， 后面出于什么考量自己实现的inmomery呢

自己实现更帅。

**Comment by JohnNiang** [comment]
> 想了解下， 为什么之前用的Ehcache， 后面出于什么考量自己实现的inmomery呢

主要是因为 Ehcache 依赖比较大。

**Comment by qrqhuang** [comment]
前面两位回答我给满分
