### ISSUE TITLE
发布MD格式文章，预览正确，发布出来后格式错误（md表格）

### ISSUE THREAD

**Issue by Planeswalker23** [halo-dev/halo#1140]
## 我的环境
版本：1.4.1
数据库：H2 1.4.196 (2017-06-10)
运行模式：production
User Agent：Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.4 Safari/605.1.15

---

## 错误日志
无

---

## 期望行为
md解析正确

## 当前行为
正文内容：

```
### 2.1 唯一索引列等值查询
首先来说唯一索引列的等值查询，这里的等值查询可以分为两种情况：命中与未命中。

当唯一索引列的等值查询命中时：
| sessionA | sessionB |
| --- | --- |
| begin; | |
| select * from user where id=5 for update; | |
| | insert into user values(1,'斯斯与帆',1),(6,'夏日阳光',6),(11,'告五人',11),(16,'面孔',16); |
| | update user set age=18 where id=5;（**Blocked**） |
| | update user set age=18 where id=10; |
| | update user set age=18 where id=15; |
```

预览内容
![预览内容](https://user-images.githubusercontent.com/37952778/98240303-2c1b0d00-1fa4-11eb-9ada-3a937333ac51.png)

发布后内容
![发布后内容](https://user-images.githubusercontent.com/37952778/98240318-31785780-1fa4-11eb-9fd5-b2caa0b626f0.png)

本文链接：[https://javageekers.club/archives/mysql5-lock](https://javageekers.club/archives/mysql5-lock)

**Comment by ruibaby** [comment]
@Planeswalker23 表格语法和上方文本段落中加一个换行符。这是由于前后端 markdown 渲染不一致导致的。

**Comment by Planeswalker23** [comment]
感谢

**Comment by Planeswalker23** [comment]
> @Planeswalker23 表格语法和上方文本段落中加一个换行符。这是由于前后端 markdown 渲染不一致导致的。

感谢
