### ISSUE TITLE
markdown中<h字符导致文章不能查看问题

### ISSUE THREAD

**Issue by eelve** [halo-dev/halo#1141]
markdown中，包含   <h 字符串是，导致文章不能正常查看
![图片](https://user-images.githubusercontent.com/13844973/98445993-dede9d00-2155-11eb-9eae-73d3c39a2eba.png)
预览或者发布是，文章都不能正常渲染
![图片](https://user-images.githubusercontent.com/13844973/98446009-f3bb3080-2155-11eb-84b2-2bf0e8c498b3.png)

**Comment by JohnNiang** [comment]
似乎是主题的问题。

**Comment by ruibaby** [comment]
![image](https://user-images.githubusercontent.com/21301288/98446363-ffa7f200-2157-11eb-8bcf-1123f3873db2.png)


![image](https://user-images.githubusercontent.com/21301288/98446359-fc146b00-2157-11eb-9d6c-5d77acbe4717.png)


我这边测试是可以通过的，应该是主题做了特殊处理。

**Comment by eelve** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/21301288/98446363-ffa7f200-2157-11eb-8bcf-1123f3873db2.png)
> 
> ![image](https://user-images.githubusercontent.com/21301288/98446359-fc146b00-2157-11eb-9d6c-5d77acbe4717.png)
> 
> 我这边测试是可以通过的，应该是主题做了特殊处理。

我这边也经过重新验证，是halo-theme-xue主题的问题

**Comment by ruibaby** [comment]
> > ![image](https://user-images.githubusercontent.com/21301288/98446363-ffa7f200-2157-11eb-8bcf-1123f3873db2.png)
> > ![image](https://user-images.githubusercontent.com/21301288/98446359-fc146b00-2157-11eb-9d6c-5d77acbe4717.png)
> > 我这边测试是可以通过的，应该是主题做了特殊处理。
> 
> 我这边也经过重新验证，是halo-theme-xue主题的问题

你可以向他的仓库提交一下 issue。

**Comment by eelve** [comment]
经过验证为主题导致，并非halo造成
