### ISSUE TITLE
当配置使用redis作为缓存时，必须修改redis配置文件，开启集群；而且不能只有一台redis，需要多台组合成集群

### ISSUE THREAD

**Issue by HMingR** [halo-dev/halo#1142]
## 我的环境
  版本：1.4.1
  数据库：MySQL 5.7.32
  运行模式：production
  User Agent：Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) 
  Chrome/86.0.4240.183 Safari/537.36

---

## 错误日志 
  redis.clients.jedis.exceptions.JedisNoReachableClusterNodeException: No reachable node in cluster

---

## 期望行为
  个人认为，作为一个博客，没必要开启集群，或者新增一个选项，是否开启集群。

**Comment by JohnNiang** [comment]
可以提供一下 application.yml 中 redis 相关的配置么？

**Comment by HMingR** [comment]
> 可以提供一下 application.yml 中 redis 相关的配置么？

halo:

  # Your admin client path is https://your-domain/{admin-path}
  admin-path: admin

  # memory, level, redis
  cache: redis

  # if cache = redis, you need to set the following options
  cache-redis-nodes: ['127.0.0.1:6379']
  cache-redis-password: 123456

**Comment by lanemy** [comment]
感觉要做完善的话, redis得支持单机, 哨兵, 集群这些模式吧...

**Comment by HMingR** [comment]
> 感觉要做完善的话, redis得支持单机, 哨兵, 集群这些模式吧...

个人博客感觉没必要使用这些模式，只要支持单机就可以了。但是目前是只能当redis配置了集群才能使用redis缓存。
https://github.com/HMingR/halo 这个是我个人fork下来修改的，兼容了支持单机redis，但是不能使用外部配置文件了[捂脸]。。

**Comment by ruibaby** [comment]
下个版本考虑去除 redis 缓存，目前来说必要不大。

**Comment by lanemy** [comment]
> > 感觉要做完善的话, redis得支持单机, 哨兵, 集群这些模式吧...
> 
> 个人博客感觉没必要使用这些模式，只要支持单机就可以了。但是目前是只能当redis配置了集群才能使用redis缓存。
> https://github.com/HMingR/halo 这个是我个人fork下来修改的，兼容了支持单机redis，但是不能使用外部配置文件了[捂脸]。。

https://github.com/lanemy/halo/commit/7f4c5e34c88562d1c4ece8edfd423521b975762c

我加了个单机的实现, 利用原有的jedis, 配置文件可以生效的

  cache: redis-standalone
  cache-redis-host: 127.0.0.1
  cache-redis-port: 6379
  cache-redis-password: mypassword
