### ISSUE TITLE
服务器下centOS-7.x无法后台启动

### ISSUE THREAD

**Issue by JessyTsu1** [halo-dev/halo#1143]
##环境：
服务器centOS-7.x

##问题：
正常用java -jar halo-latest.jar运行没有问题
但尝试用sudo service halo start或是sudo systemctl start halo.service来后台启动，都失败了
是按照官方文档进行配置的，不知道哪里出了问题，希望得到解答，感谢！

**Comment by ruibaby** [comment]
是否按照文档要求创建了 halo 用户，如果没有，删掉 halo.service 中的 User=halo，try again.

**Comment by JessyTsu1** [comment]
> 是否按照文档要求创建了 halo 用户，如果没有，删掉 halo.service 中的 User=halo，try again.

删掉之后就可以用systemctl启动了，感谢！
