### ISSUE TITLE
feat: 附件回收功能

### ISSUE THREAD

**Issue by zhixiangyuan** [halo-dev/halo#1145]
## 动机

由于 Halo 的附件功能很好用，所以我们的很多图片都存在里面，但是随着文章的增加、删除和修改，很多图片可能就用不上了，但是图片依然会留在系统中，所以对这个东西有个想法。

## 详细解释

这里可以增加一个附件回收功能，判断一份附件是否还有效可以通过两个维度来判断，第一是通过解析 markdown 中的图片链接来判断获得当前还在使用的图片，第二是可以在系统中记录每份文件的最近访问时间，然后增加一个定时任务扫描，比如说每天扫描一次，如果 markdown 中有该链接则说明该图片当前还在使用，如果没有使用的文件可能是外部别的地方在用，这里可以在判断最近文件的访问时间，如果一个月（可配置）都没有被访问则定为垃圾文件，自动回收或放入回收站让用户处理

**Comment by ruibaby** [comment]
可以考虑，但不纳入目前开发任务。
