### ISSUE TITLE
bug: 引入外部字体不工作

### ISSUE THREAD

**Issue by zhixiangyuan** [halo-dev/halo#1148]
## 我的环境

版本：1.4.2
数据库：H2 1.4.196 (2017-06-10)
运行模式：production
User Agent：Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.193 Safari/537.36

## 期望行为

在后台中通过 css 引入外部字体，虽然我已在文档中使用了该字体，但是浏览器并不会下载字体

![image](https://user-images.githubusercontent.com/25138766/98907894-87945000-24fa-11eb-9215-7b08ed894967.png)

## 当前行为

实际并没有下载该字体

**Comment by ruibaby** [comment]
啊这？怎么打上 bug 标签。

**Comment by ruibaby** [comment]
搜了个帖子，这样是可以的 https://bbs.halo.run/d/850

**Comment by zhixiangyuan** [comment]
> 搜了个帖子，这样是可以的 https://bbs.halo.run/d/850

大佬，你看我在最下面的那段代码，指定了代码用 JetBrains Mono，但是没有效果

```css
code {
    font-family: JetBrains Mono !important;
}
```

![image](https://user-images.githubusercontent.com/25138766/98911705-0049db00-2500-11eb-91c4-c8a3230fac24.png)
