### ISSUE TITLE
bug: 数学公式不居中

### ISSUE THREAD

**Issue by zhixiangyuan** [halo-dev/halo#1149]
## 我的环境

版本：1.4.2
数据库：H2 1.4.196 (2017-06-10)
运行模式：production
User Agent：Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.193 Safari/537.36

## 期望行为

数学公式居中

## 当前行为

数学公式使用 `$$xxx$$` 时不居中

![image](https://user-images.githubusercontent.com/25138766/99020637-f96fa680-2599-11eb-9223-44ec6f9778d8.png)

**Comment by ruibaby** [comment]
这是不是应该和主题的样式有关。
