### ISSUE TITLE
博客是单用户把，前台页面的url都加了${options.blog_url!}前缀？？

### ISSUE THREAD

**Issue by dengji85** [halo-dev/halo#115]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x ] [Halo 使用文档](https://docs.halo.run/)
- [x ] [Github Wiki 常见问题](https://github.com/ruibaby/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [ x] [其他 Issues](https://github.com/ruibaby/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x ] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

**Comment by ruibaby** [comment]
没错。
