### ISSUE TITLE
导入markdown文件后，服务无法正常运行，后台日志显示内存溢出

### ISSUE THREAD

**Issue by yunajia** [halo-dev/halo#1153]
2020-11-16 15:47:30.597  WARN 1806 --- [qtp1544518128-15] o.e.j.u.thread.strategy.EatWhatYouKill   :

java.lang.OutOfMemoryError: Metaspace

[root@iZm5ebvlfc3n57gphm2koqZ blog]# jstat -gc 1806
 S0C    S1C    S0U    S1U      EC       EU        OC         OU       MC     MU    CCSC   CCSU   YGC     YGCT    FGC    FGCT     GCT
40960.0 40960.0  0.0    0.0   40960.0    0.0     184320.0   49810.3   102400.0 93875.3 13696.0 12243.9    134    4.196 1318   306.490  310.686

**Comment by ruibaby** [comment]
上传了多少？

**Comment by yunajia** [comment]
> 上传了多少？

就刚刚上传一个文件

**Comment by yunajia** [comment]
> > 上传了多少？
> 
> 就刚刚上传一个文件

问价大小4kb。还没有进行大批量的上传

**Comment by ruibaby** [comment]
没有复现，你现在服务是被停了吗？

**Comment by yunajia** [comment]
> 没有复现，你现在服务是被停了吗？

是的，我刚刚已经重启了服务，版本是1.4.2，也可能是我设置了jvm参数：
-Xmx300M 
-Xms300M 
-Xmn120M 
-XX:MetaspaceSize=100M 
-XX:MaxMetaspaceSize=100M 
-Xss256K 
-XX:+DisableExplicitGC 
-XX:SurvivorRatio=1 
-XX:+UseConcMarkSweepGC 
-XX:+UseParNewGC 
-XX:+CMSParallelRemarkEnabled 
-XX:+UseCMSCompactAtFullCollection 
-XX:CMSFullGCsBeforeCompaction=0 
-XX:+CMSClassUnloadingEnabled 
-XX:LargePageSizeInBytes=128M 
-XX:+UseFastAccessorMethods 
-XX:+UseCMSInitiatingOccupancyOnly 
-XX:CMSInitiatingOccupancyFraction=55 
-XX:SoftRefLRUPolicyMSPerMB=0 
-XX:+PrintClassHistogram 
-XX:+PrintGCDetails 
-XX:+PrintGCTimeStamps 
-XX:+PrintHeapAtGC 
-Xloggc:/var/log/halo-gc.log

**Comment by ruibaby** [comment]
没有按照你的参数测试过，建议按照文档要求设置 -Xmx -Xms 再试试。

**Comment by yunajia** [comment]
> -Xmx -Xms 再试试。

好的，谢谢
