### ISSUE TITLE
关于Https图片外链无法显示问题(附解决方法)

### ISSUE THREAD

**Issue by Stars-One** [halo-dev/halo#1155]
当使用Https引用别的平台外链,图片会无法显示,如https://img2020.cnblogs.com/blog/1210268/202004/1210268-20200413161422035-1188549898.gif

**解决方法:**
在Html的head标签中添加以下代码即可
```
<meta name="referrer" content="no-referrer">
```

大佬看到,麻烦顺手修复以下,感谢!

**Comment by ruibaby** [comment]
谢谢，但这不是 bug，也不是我们需要解决的范畴。甚至，我们不建议解决。
