### ISSUE TITLE
feat: 优化英文标题自动生成的别名

### ISSUE THREAD

**Issue by micross** [halo-dev/halo#1157]
## 概述

比如标题为”Hello halo“，目前系统会自动生成”H-e-l-l-o- -h-a-l-o“这样的别名，建议改成”Hello-halo“这样的形式。

## 动机

我认为采用-连接单词而不是将单词的每个字母拆出来再用-连接对SEO会更友好。

**Comment by ruibaby** [comment]
好的，我们已经发现了这个问题，将在后面的版本中优化，
