### ISSUE TITLE
静态存储上传js文件时出现HTTP2_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by AnotiaWang** [halo-dev/halo#1161]
## 我的环境
版本：1.4.2
数据库：H2 1.4.196 (2017-06-10)
运行模式：production
User Agent：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36

网站已开启SSL

---

## 错误日志
[halo-log-2020-11-22-13-52-54.log](https://github.com/halo-dev/halo/files/5579052/halo-log-2020-11-22-13-52-54.log)

---

## 期望行为
我想给一个静态页面上传 jQuery js 文件

## 当前行为
在开发者选项中的“静态存储”中，点击上传，选中 jquery.js，上传，随后页面提示网络异常，再刷新就变成了 ERR_HTTP2_PROTOCOL_ERROR。
然后我去后台`sudo systemctl restart halo`，等待几分钟后恢复了。

这是剩余的js文件，都上传成功了，只差 jquery.js 了
![image](https://user-images.githubusercontent.com/62269186/99896646-7226df00-2ccd-11eb-9fad-035c5dd340bf.png)

**Comment by ruibaby** [comment]
刚刚测试了上传 jQuery.js 是没有问题的，建议你上传的时候看一下请求是否被 nginx 拦截了。
