### ISSUE TITLE
为什么不同用户运行 Halo 程序，需要重新注册网站

### ISSUE THREAD

**Issue by AnotiaWang** [halo-dev/halo#1162]
服务器：Ubuntu
我按照教程配置的时候用的是 root 用户，配置好了之后添加了 halo 用户并且添加到了systemd中，然后登录后台时要求重新注册一遍后台，最后我先换回root，导出配置 json，再换回 halo 导入才解决，这是为什么呢？

**Comment by ruibaby** [comment]
Halo 的工作目录固定为当前系统用户下的 .halo 文件夹，所以你用不同的用户运行会有不同的工作目录。

**Comment by AnotiaWang** [comment]
> Halo 的工作目录固定为当前系统用户下的 .halo 文件夹，所以你用不同的用户运行会有不同的工作目录。

好的，谢谢
