### ISSUE TITLE
feat: 模板的问题，让我在文章中用MD语法时出现灰色前缀字号

### ISSUE THREAD

**Issue by clien9025** [halo-dev/halo#1163]
## 概述

去掉博客文章的灰色前缀字号（h1,h2,h3,h4,h5.....等等）
## 动机

因为这样真的很影响我博客的阅读，以至于在有时候博客文章采用的markdown语法书写时，标号太小导致文章中的有序排列的序号和灰色前缀字号重合，导致超级影响阅读。
## 详细解释

1.  我在写留言板的时候，发现写完留言板之后，在留言板发布的页面上有个[模板]选项（默认是 link），我点选[link]之后就没有像我其他文章那样的灰色前缀字号出现了，蛮好用的。

2.  我希望在[文章] --> [写文章] 之后发布的时候，发布页面也有这样一个模板选项，让我来勾选 [link] 选项，用来消除灰色前缀字号

**Comment by ruibaby** [comment]
这应该是主题样式的问题，请问您用的哪个主题？

**Comment by clien9025** [comment]
#### 这是我使用的主题，请大大过目
id: bao
name: 雪
author:
  name: 雪
  website: https://baozi.fun
description: 大道至简
logo:
website: https://github.com/xzzai/halo-theme-xue
repo: https://github.com/xzzai/halo-theme-xue
version: 1.0
require: 1.3.0

**Comment by ruibaby** [comment]
> #### 这是我使用的主题，请大大过目
> 
> id: bao
> 
> name: 雪
> 
> author:
> 
>   name: 雪
> 
>   website: https://baozi.fun
> 
> description: 大道至简
> 
> logo:
> 
> website: https://github.com/xzzai/halo-theme-xue
> 
> repo: https://github.com/xzzai/halo-theme-xue
> 
> version: 1.0
> 
> require: 1.3.0
> 
> 

在这里去提 issue 吧。https://github.com/xzzai/halo-theme-xue

**Comment by clien9025** [comment]
好的。
