### ISSUE TITLE
feat: 希望添加文章中解析豆瓣的功能

### ISSUE THREAD

**Issue by huangzong1998** [halo-dev/halo#1167]
## 概述

在文章中插入豆瓣url，可以自动解析成具体的内容（包括电影书籍的封面作者日期之类的信息）。

就是wordpress中wp-douban的功能，希望能移植到halo上。

## 动机

写一些观后感或读后感的文章，想插入关于影视的介绍，方便读者知道具体是哪部电影（书籍）。

## 详细解释

插入方式：直接在文章添加url，或者某个特殊标签，里面写豆瓣电影id文章id，然后能自动识别、解析

**Comment by ruibaby** [comment]
目前不打算再修改当前的编辑器来做支持，待新的编辑器开发完毕后再做这方面的支持。

https://github.com/halo-dev/halo/issues/989
