### ISSUE TITLE
feat: 希望增加一个文章导出的功能，比如说导出成markdown

### ISSUE THREAD

**Issue by Xizicl** [halo-dev/halo#1168]
## 概述
希望增加一个文章导出的功能，比如说导出成markdown（一篇文章连带其资源导出为一个文件夹）

## 动机
在把之前写的markdown导入为文章后想导出备份到本地一下（服务器快到期了想更换其他服务器，或者想换其他博客系统【这么说是不是不太好哈哈哈哈】），目前咱们halo好像是只能备份~/.halo这一整个文件夹  :)

**Comment by ruibaby** [comment]
暂时不打算做这个功能。你可以可以考虑再本地访问 h2，写一个小小的程序读取 posts 表，将 Markdown 导出。

**Comment by Xizicl** [comment]
好的，可是相关资源的引用路径比如图片都是指向网站的，可能会有些麻烦

顺便问一下：不知能不能在资源这一块做个类似资源管理器的功能（方便上传和下载）【目前好像是按月份放在同一文件夹中，或者改变一下按文章来存放也可】。

**Comment by ruibaby** [comment]
> 好的，可是相关资源的引用路径比如图片都是指向网站的，可能会有些麻烦
> 
> 顺便问一下：不知能不能在资源这一块做个类似资源管理器的功能（方便上传和下载）【目前好像是按月份放在同一文件夹中，或者改变一下按文章来存放也可】。

你可以将 upload 目录放到其他系统的根目录

~正考虑重构附件管理。
