### ISSUE TITLE
博客后台在一个月前突然收到大量来自你们开发组的issue评论，请问是什么原因？

### ISSUE THREAD

**Issue by LainNetWork** [halo-dev/halo#1172]
如图所示
![image](https://user-images.githubusercontent.com/20994069/100520728-54301180-31da-11eb-8f93-11fc55cba200.png)

**Comment by ruibaby** [comment]
@LainNetWork https://bbs.halo.run/d/1059-halo

**Comment by LainNetWork** [comment]
> @LainNetWork https://bbs.halo.run/d/1059-halo

看来是你们被别人搞了。。我还以为是在测试什么新功能呢

**Comment by corgile** [comment]
也可能是你halo后台配置的邮箱与GitHub登录邮箱一样，这样一旦你参与过issue，GitHub就会以邮件方式通知你issue的最新动态，从而你就会收到内容为某issue最新评论的邮件。而halo的回复评论功能也用到了通过邮件通知功能，所以halo后台就误以为这些issue邮件来自别人在你网站上的留言/回复。解决方法：unsubscribe.

**Comment by corgile** [comment]
## 而不是所谓的被恶意调用api了.

**Comment by corgile** [comment]
unsubscribe的方法：点进去你曾经参与过的issue，划到下面，有个按钮

![IMG_20210115_021105](https://user-images.githubusercontent.com/48396880/104631263-f8acdb00-56d6-11eb-9d8c-bed2f4b5a27b.jpg)

**Comment by ruibaby** [comment]
> ## 而不是所谓的被恶意调用api了.

和你说的似乎没有关系。这是攻击者挑了一个 issue 作为评论内容对使用者进行攻击。

**Comment by corgile** [comment]
> > ## 而不是所谓的被恶意调用api了.
> 
> 和你说的似乎没有关系。这是攻击者挑了一个 issue 作为评论内容对使用者进行攻击。

真的吗 对不起哈哈哈不好意思
