### ISSUE TITLE
修改自定义页面路径形式

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#1174]
目前有不少人反应自定义页面带了 /s/ 二级路径看着很奇怪，所以这个 issue 征集大家的意见。

1. 去除 `/s/`，直接使用 slug 根路径，类似 https://ryanc.cc/about
2. 保留现状，类似 https://ryanc.cc/s/about。 （目前这种方式的 /s/ 二级路径是可以在后台修改的）
3. 

![image](https://user-images.githubusercontent.com/21301288/100626735-232e1900-3361-11eb-981b-2b2fa507321a.png)（自己在后台选择路径方式）

**Comment by LIlGG** [comment]
个人是比较喜欢直接使用 slug 根路径的方式，也许是强迫症的原因，看到有个多余的二级 URI 就感觉很不舒服。
但以目前的情况，想切换成第一种方式还是有以下问题的：
1. 旧用户已经**被收录**的自定义页面将在更新版本后失效。
2. 旧用户**已经存在的自定义页面别名与现有的默认菜单名冲突**，将会造成不可预知的问题。
3. 在新增自定义时，将要校验自定义页面别名是否与现有默认页面名冲突，即需要多查一次库。

如果能解决掉如上所述的问题 ~~【我全都要？？？】~~，我个人还是比较喜欢直接 slug 根路径的方式。

**Comment by xzhuz** [comment]
没有用过后台的自定义路径，所以不确定自定义页面路径是否支持自定义成`https://ryanc.cc/about`？如果可以支持自定义这种，那么感觉就没有必要讨论。即使不支持， 支持自定义页面路径，也可以让使用者自己DIY。

**Comment by ruibaby** [comment]
> 没有用过后台的自定义路径，所以不确定自定义页面路径是否支持自定义成`https://ryanc.cc/about`？如果可以支持自定义这种，那么感觉就没有必要讨论。即使不支持， 支持自定义页面路径，也可以让使用者自己DIY。

不支持，必须有二级。

**Comment by xzhuz** [comment]
> > 没有用过后台的自定义路径，所以不确定自定义页面路径是否支持自定义成`https://ryanc.cc/about`？如果可以支持自定义这种，那么感觉就没有必要讨论。即使不支持， 支持自定义页面路径，也可以让使用者自己DIY。
> 
> 不支持，必须有二级。

那如果把这个限制放开，只限制路径不能重复。至于需要怎么样的路径，让使用者自己DIY。个人觉得，这样就很好了。

**Comment by ruibaby** [comment]
> 那如果把这个限制放开，只限制路径不能重复。至于需要怎么样的路径，让使用者自己DIY。个人觉得，这样就很好了。

个人觉得也没必要限制路径不能和内置页面的路径重复，把自定义的优先级提高就好了，比如 /links，我想覆盖这个页面就可以新建一个自定义页面，slug 命名为 links。

**Comment by xzhuz** [comment]
> > 那如果把这个限制放开，只限制路径不能重复。至于需要怎么样的路径，让使用者自己DIY。个人觉得，这样就很好了。
> 
> 个人觉得也没必要限制路径不能和内置页面的路径重复，把自定义的优先级提高就好了，比如 /links，我想覆盖这个页面就可以新建一个自定义页面，slug 命名为 links。

👍这样设计感觉更好了

**Comment by LIlGG** [comment]
> > 那如果把这个限制放开，只限制路径不能重复。至于需要怎么样的路径，让使用者自己DIY。个人觉得，这样就很好了。
> 
> 个人觉得也没必要限制路径不能和内置页面的路径重复，把自定义的优先级提高就好了，比如 /links，我想覆盖这个页面就可以新建一个自定义页面，slug 命名为 links。

强行覆盖？你在教用户做事？？【狗头保命】

**Comment by praming** [comment]
1不是不好实现吗？如果能实现那肯定选1或者3啊。

**Comment by ruibaby** [comment]
> 1不是不好实现吗？如果能实现那肯定选1或者3啊。

以前不好实现，但现在好实现了，属于历史遗留问题，但要考虑老用户的兼容问题。

**Comment by praming** [comment]
> > 1不是不好实现吗？如果能实现那肯定选1或者3啊。
> 
> 以前不好实现，但现在好实现了，属于历史遗留问题，但要考虑老用户的兼容问题。

如果是这样的话我觉得3比较合适啊。

**Comment by praming** [comment]
> 以前不好实现，但现在好实现了，属于历史遗留问题，但要考虑老用户的兼容问题。

如果是这样的话我觉得3比较合适啊。
