### ISSUE TITLE
feat: 增加git类附件上传仓库的选项

### ISSUE THREAD

**Issue by hongcyu** [halo-dev/halo#1175]
## 概述

想拥有类似PicGo一样的可以通过上传到github/gitee获取附件的功能。

## 动机

目前看到后台附件处有许多云存储的配置，希望增加这git类的配置0.0

## 详细解释

![image](https://user-images.githubusercontent.com/41502466/100683266-f145a280-33b2-11eb-9de8-a520e8f79e68.png)
![image](https://user-images.githubusercontent.com/41502466/100683288-002c5500-33b3-11eb-98cd-4e96c889f259.png)

**Comment by ruibaby** [comment]
可以考虑，但不作为目前开发重点。
