### ISSUE TITLE
代码如何添加高亮

### ISSUE THREAD

**Issue by 19950820** [halo-dev/halo#118]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://docs.halo.run/)
- [ ] [Github Wiki 常见问题](https://github.com/ruibaby/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [ ] [其他 Issues](https://github.com/ruibaby/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [x] 请求技术支持

**Comment by ruibaby** [comment]
@19950820 哪个主题？

**Comment by 19950820** [comment]
默认的两个主题

**Comment by 19950820** [comment]
Material和Anatole

**Comment by ruibaby** [comment]
```语言
代码块
```

如：

```java
public static void main(String [] args){
    System.out.println("Hello World");
}
```

高亮样式可以在主题设置里面找到。

**Comment by 19950820** [comment]
没有找到....
![QQ截图20190315164214](https://user-images.githubusercontent.com/20716500/54419006-5cfc5d80-4741-11e9-88ea-e3aad086d787.png)

**Comment by ruibaby** [comment]
![TIM截图20190315164405](https://user-images.githubusercontent.com/21301288/54419100-92a14680-4741-11e9-8ab2-2d1ab5201845.png)
