### ISSUE TITLE
写文章时点击预览会出现404

### ISSUE THREAD

**Issue by OnionSmile** [halo-dev/halo#1183]
写文章的时候点击预览，会报404notfound错误，无法预览

**Comment by ruibaby** [comment]
请补充利于我们判断的详细信息，否则我们将关闭此 issue。

**Comment by OnionSmile** [comment]
写文章的时候点击预览，会报404notfound错误，无法预览。

**Comment by ruibaby** [comment]
版本多少。

**Comment by OnionSmile** [comment]
> 版本多少。

版本：1.3.2
数据库：H2 1.4.196 (2017-06-10)
运行模式：production
User Agent：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36

**Comment by ruibaby** [comment]
@OnionSmile 升级到最新版即可解决。

**Comment by OnionSmile** [comment]
> @OnionSmile 升级到最新版即可解决。

升级到1.4.2了还是不行

**Comment by ruibaby** [comment]
> > @OnionSmile 升级到最新版即可解决。
> 
> 
> 
> 升级到1.4.2了还是不行

其他功能是否异常？有没有使用全局 cdn 的服务？ 预览的问题已经修复很久，目前没有发现过遇到您这种情况的。需要更多信息才能帮你判断。

**Comment by OnionSmile** [comment]
其他功能正常，用了cdn，是cdn的问题吗

**Comment by ruibaby** [comment]
https://github.com/halo-dev/halo-admin/issues/253

**Comment by OnionSmile** [comment]
感觉大佬解答，果然是cdn的问题，没设置参数跟随。
