### ISSUE TITLE
feat: 后台渲染 Markdown 时让 Table 居中

### ISSUE THREAD

**Issue by MakiseVon** [halo-dev/halo#1187]
## 概述

测试后台 Markdown 时发现 Table 默认居左

![](https://i.loli.net/2020/12/08/49HZPzJqnmy8YSt.png)

希望能让 Table 居中。

## 动机

一点强迫症 & 希望有更好的写作体验 ~

**Comment by coortop** [comment]
这是主题样式写的不对，和halo后台无关，你可以修改主题的css实现

**Comment by MakiseVon** [comment]
> 这是主题样式写的不对，和halo后台无关，你可以修改主题的css实现

Halo 的前后端渲染不是分离的吗？主题 CSS 中没有发现有关 Editor 的内容...

**Comment by coortop** [comment]
后台编辑框的样式也不对，但发布完主要是给前端显示啊，你不用管后台咋显示，你把前端主题的样式改好不就行了

**Comment by MakiseVon** [comment]
> 后台编辑框的样式也不对，但发布完主要是给前端显示啊，你不用管后台咋显示，你把前端主题的样式改好不就行了

我前端没有任何问题，提这个 issue 只是因为写文章时看着很怪（好像表格、图片之类的都没有居中？）。无论如何，谢谢你 ~

**Comment by ruibaby** [comment]
这其实是编辑器的样式规定，大多数 Markdown 样式都这样的，Github 的 Markdown 样式也一样。

|column1|column2|column3|
|-------|-------|-------|
|content1|content2|content3|

**Comment by MakiseVon** [comment]
> 这其实是编辑器的样式规定，大多数 Markdown 样式都这样的，Github 的 Markdown 样式也一样。
> 
> column1	column2	column3
> content1	content2	content3

谢谢 ~ 知道是规定之后就好受多了
