### ISSUE TITLE
遇到一个奇怪都问题 点击后台布局设置就会黑屏

### ISSUE THREAD

**Issue by fei1025** [halo-dev/halo#1188]
## 我的环境

我这个是一个hdim转vga 都屏幕,发现有些主题就会黑屏,
我尝试过打开其他人的halo博客,有些主题就会导致屏幕无线黑屏
![V01208-212615](https://user-images.githubusercontent.com/46546005/101497453-f653b480-39a5-11eb-92ed-b731d21f4a84.gif)

**Comment by ruibaby** [comment]
无法判断硬件的情况，建议升级浏览器或者换个浏览器试试。从理论上讲，一个 web 程序应该影响不到硬件。

**Comment by JohnNiang** [comment]
难道是动效搞死了显卡？：P

**Comment by fei1025** [comment]
> 难道是动效搞死了显卡？：P

我感觉是,有一个博客我打开,那个屏幕就黑屏显示无信号连接.....感觉有些东西要渲染但是hdim转vga就支持不了.....

**Comment by fei1025** [comment]
补充下,我这个是双屏一个是vga一个是hdim转vga,vga没问题,
但是hdim转vga就有这个问题,
感觉像有点主题要渲染数据 但是hdim转vga造成了数据丢失,然后显示屏黑屏

**Comment by ruibaby** [comment]
那就非常抱歉了，这个不属于我们需要解决的范畴。
