### ISSUE TITLE
上传文件出现OOM错误

### ISSUE THREAD

**Issue by thomas10011** [halo-dev/halo#1195]
## 我的环境
版本：1.4.2
数据库：H2 1.4.196 (2017-06-10)
运行模式：production
启动时间：2020-12-11 18:11

---

## 错误日志
```
2020-12-11 18:20:20.427  INFO 25147 --- [qtp630028734-11] r.h.app.handler.file.LocalFileHandler    : Uploading file: [IMG_8149.jpeg]to directory: [/root/.halo/upload/2020/12/IMG_8149-e1985bd3bb664a0cb97b8833ed2ab8e8.jpeg]
2020-12-11 18:20:20.830 ERROR 25147 --- [qtp630028734-11] r.h.app.core.ControllerExceptionHandler  : Captured an exception: [Handler dispatch failed; nested exception is java.lang.OutOfMemoryError: Java heap space]
```

---

## 期望行为
上传小于5m的文件成功，大于5m的文件就会报错

## 当前行为
上传大于5m的文件报错。jvm内存参数设置的是512m。

**Comment by ruibaby** [comment]
这个问题应该已经被修复了。https://github.com/halo-dev/halo/pull/1122

方便告知你服务器的配置吗？

**Comment by thomas10011** [comment]
> 这个问题应该已经被修复了。#1122
> 
> 方便告知你服务器的配置吗？

可以的，我的服务器是1核2G的配置，查看了内存可用情况，jvm可用内存基本维持在300M左右；另外我测试上传别的大图片倒是成功了，上传失败的两张图片均是全景图，分辨率比较高（不知道是不是这个原因？）

**Comment by ruibaby** [comment]
> > 这个问题应该已经被修复了。#1122
> > 方便告知你服务器的配置吗？
> 
> 可以的，我的服务器是1核2G的配置，查看了内存可用情况，jvm可用内存基本维持在300M左右；另外我测试上传别的大图片倒是成功了，上传失败的两张图片均是全景图，分辨率比较高（不知道是不是这个原因？）

那确实有可能是图片太大导致的，因为 Halo 内部在上传图片的时候会生成缩略图，这一步往往随着图片的质量而消耗的资源更多，很容易导致 OOM，如果可以的话，你可以把图片发送到 i@ryanc.cc。我们测试一下。

**Comment by thomas10011** [comment]
> > > 这个问题应该已经被修复了。#1122
> > > 方便告知你服务器的配置吗？
> > 
> > 
> > 可以的，我的服务器是1核2G的配置，查看了内存可用情况，jvm可用内存基本维持在300M左右；另外我测试上传别的大图片倒是成功了，上传失败的两张图片均是全景图，分辨率比较高（不知道是不是这个原因？）
> 
> 那确实有可能是图片太大导致的，因为 Halo 内部在上传图片的时候会生成缩略图，这一步往往随着图片的质量越高而消耗的资源更多，很容易导致 OOM，如果可以的话，你可以把图片发送到 [i@ryanc.cc](mailto:i@ryanc.cc)。我们测试一下。

已发送

**Comment by ruibaby** [comment]
@thomas10011 确实是在生成缩略图的时候产生的问题。目前你可以考虑压缩一下图片，或者调高一下 -Xms -Xmx 。

**Comment by thomas10011** [comment]
> @thomas10011 确实是在生成缩略图的时候产生的问题。目前你可以考虑压缩一下图片，或者调高一下 -Xms -Xmx 。

好的，这个不急，可以等待修复

**Comment by JohnNiang** [comment]
> > @thomas10011 确实是在生成缩略图的时候产生的问题。目前你可以考虑压缩一下图片，或者调高一下 -Xms -Xmx 。
> 
> 好的，这个不急，可以等待修复

最新代码里面似乎已经修复了此问题。在压缩图片过程中如果出现了 OOM，我们会自动忽略，并将缩略图设置为原图链接。

**Comment by JohnNiang** [comment]
Duplicate #1085

**Comment by ruibaby** [comment]
> > > @thomas10011 确实是在生成缩略图的时候产生的问题。目前你可以考虑压缩一下图片，或者调高一下 -Xms -Xmx 。
> > 
> > 
> > 好的，这个不急，可以等待修复
> 
> 最新代码里面似乎已经修复了此问题。在压缩图片过程中如果出现了 OOM，我们会自动忽略，并将缩略图设置为原图链接。

you are right.
