### ISSUE TITLE
可以自定义图库位置么

### ISSUE THREAD

**Issue by silly-Richard** [halo-dev/halo#1197]
写博客的时候会用到很多图片，但是图库的默认位置在c盘，想把它放在别的盘下。不知道这个可以自定义路径么？

**Comment by ruibaby** [comment]
不可以，这是固定的。

**Comment by silly-Richard** [comment]
还想冒昧地请教一下，我可以将整个halo配置文件配置在其他盘么？
我是技术小白，不是很懂这里面的配置。我只是想尝试使用halo搭一个私人的数据库或者是笔记本。
或许我应该死了这条心，换一个软件23333

**Comment by JohnNiang** [comment]
> 还想冒昧地请教一下，我可以将整个halo配置文件配置在其他盘么？
> 我是技术小白，不是很懂这里面的配置。我只是想尝试使用halo搭一个私人的数据库或者是笔记本。
> 或许我应该死了这条心，换一个软件23333

可以。稍后给你解决方案。

**Comment by JohnNiang** [comment]
可以在 `~/.halo/application.yml` 中新增如下配置：

```yaml
halo:
    work-dir: D://xxx
```
