### ISSUE TITLE
feat: 搜索不支持大小写，希望能支持，谢谢

### ISSUE THREAD

**Issue by wesecret** [halo-dev/halo#1202]

**Comment by JohnNiang** [comment]
搜索这块确实需要好好搞，不过可能要计划更后面进行了。

**Comment by Raremaa** [comment]
@JohnNiang  
集成一个Lucene如何，不然面对不一样的搜索引擎，我看halo好像是用的JPA criteria(Hibernate实现)做的数据库查询，我印象中这东西是没办法控制是否区分大小写的，而是取决于数据库的索引方式。

**Comment by JohnNiang** [comment]
> @JohnNiang
> 集成一个Lucene如何，我看halo好像是用的JPA criteria(Hibernate实现)做的数据库查询，我印象中这东西是没办法控制是否区分大小写的，而是取决于数据库的索引方式。

不建议在数据库中进行查询，无法进行模糊匹配，效率还低。

**Comment by zhixiangyuan** [comment]
@wesecret 用 h2 数据库的话参考这篇文章可以解决，[文章链接](http://xiangbei.life/?p=34)

**Comment by Raremaa** [comment]
> @wesecret 用 h2 数据库的话参考这篇文章可以解决，[文章链接](http://xiangbei.life/?p=34)

这种方式感觉就没那么灵活，就我的使用习惯来说，是否需要严格大小写应该是让用户来选择😂

**Comment by guqing** [comment]
要不要对文章内容进行分词（trie） 建立词与文章id关系索引可以持久化到文件  更新和新增文章时对索引进行维护  搜索时对搜索文本分词后到索引查找文章id（HashMap或二分查找） 然后对根据词频对结果排序后根据id到数据库查询文章 返回

**Comment by Cui-Yusong** [comment]
请问这个问题，可以构建一个全文检索表吗？具体方法是，把每个文章先分词，然后给每个分词加上文章编号，相当于每个词是key值，文章编号是value值，到时候直接通过词去找文章
这个思路可以吗？

**Comment by JohnNiang** [comment]
@Cui-Yusong 有兴趣的话建议了解一下：<http://hibernate.org/search/>

**Comment by dejavuwl** [comment]
集成google站内搜索是不是也可以作为一种思路 搜索的关键词后面加上 site:xxx.com

**Comment by ruibaby** [comment]
Instead of this issue https://github.com/halo-dev/halo/issues/1545

**Comment by huasio** [comment]
是在不行弄个 elasticsearch 也是不错的选择，就是太重量级了。

**Comment by UncoDong** [comment]
> @wesecret 用 h2 数据库的话参考这篇文章可以解决，[文章链接](http://xiangbei.life/?p=34)

您好这个文章链接打不开了。。如果可以的话能请教您一下解决这个搜索问题的大致思路么？非常感谢
