### ISSUE TITLE
获取文件名时特殊字符没有转码

### ISSUE THREAD

**Issue by Lwenguang** [halo-dev/halo#1205]
## 我的环境

版本：1.4.2
数据库：MySQL 5.7.30-log
运行模式：production
User Agent：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36

---

## 错误信息

请求后端接口获取文件时 文件名特殊字符没有转码

文件名：` !@#$%^&()[]{}￥.jpg

后端传过来的文件名： ` !@#$%^&()[]{}￥.jpg

url实际能访问的文件名： %60%20%21%40%23%24%25%5E%26%28%29%5B%5D%7B%7D%EF%BF%A5.jpg

**Comment by JohnNiang** [comment]
下个版本修复。

**Comment by ruibaby** [comment]
具体是哪个地方。

**Comment by Lwenguang** [comment]
> 具体是哪个地方。

目前看到的有问题的接口：/api/admin/attachments
还有图库页面：/www.xxx.com/photos
暂时就发现这两个

**Comment by ruibaby** [comment]
是的，接口确实没有做处理，但是在 admin 是有编码处理的。所以不太清楚你所遇到的问题到底在哪里。

**Comment by Lwenguang** [comment]
## 错误1
```language
调用接口: https://www.xxx.com/api/admin/attachments?page=0&size=18
返回结果: 
	content:[
		{
			...
			name: "\` !@#$%^&()[]{}￥",
			path: "https://xxx.com/upload/2020/12/` !@#$%^&()[]{}￥-c397236b0cd4434aab7dfe36fba1a3bd.jpg",
			thumbPath: "https://xxx.com/upload/2020/12/` !@#$%^&()[]{}￥-c397236b0cd4434aab7dfe36fba1a3bd-thumbnail.jpg
			...
		}
	]
	
数据库对应数据:
	表名: attachments
	name: ` !@#$%^&()[]{}￥
	path: upload/2020/12/` !@#$%^&()[]{}￥-c397236b0cd4434aab7dfe36fba1a3bd.jpg
	thumb_path: upload/2020/12/` !@#$%^&()[]{}￥-c397236b0cd4434aab7dfe36fba1a3bd-thumbnail.jpg
	
文件正确请求地址： https://www.xxx.com/upload/2020/12/%60%20%21%40%23%24%25%5E%26%28%29%5B%5D%7B%7D%EF%BF%A5-c397236b0cd4434aab7dfe36fba1a3bd.jpg

结论：没有对任何特殊字符进行转码处理
```

## 错误2
```language
访问页面: /photos  
数据库对应数据:
	表名: photos
	name: ` !@#$%^&()[]{}￥
	thumbnail: https://www.xxx.com/upload/2020/12/%60%20!@#$%25%5E&()%5B%5D%7B%7D%EF%BF%A5-c397236b0cd4434aab7dfe36fba1a3bd-thumbnail.jpg
	url: https://www.xxx.com/upload/2020/12/%60%20!@#$%25%5E&()%5B%5D%7B%7D%EF%BF%A5-c397236b0cd4434aab7dfe36fba1a3bd.jpg

文件正确请求地址： https://www.xxx.com/upload/2020/12/%60%20%21%40%23%24%25%5E%26%28%29%5B%5D%7B%7D%EF%BF%A5-c397236b0cd4434aab7dfe36fba1a3bd.jpg

结论：没有对部分特殊字符进行转码处理
```

建议对所有特殊字符都进行转码处理，免得再出其他bug

**Comment by ruibaby** [comment]
> ## 错误1
> 
> ```language
> 
> 调用接口: https://www.xxx.com/api/admin/attachments?page=0&size=18
> 
> 返回结果: 
> 
> 	content:[
> 
> 		{
> 
> 			...
> 
> 			name: "\` !@#$%^&()[]{}￥",
> 
> 			path: "https://xxx.com/upload/2020/12/` !@#$%^&()[]{}￥-c397236b0cd4434aab7dfe36fba1a3bd.jpg",
> 
> 			thumbPath: "https://xxx.com/upload/2020/12/` !@#$%^&()[]{}￥-c397236b0cd4434aab7dfe36fba1a3bd-thumbnail.jpg
> 
> 			...
> 
> 		}
> 
> 	]
> 
> 	
> 
> 数据库对应数据:
> 
> 	表名: attachments
> 
> 	name: ` !@#$%^&()[]{}￥
> 
> 	path: upload/2020/12/` !@#$%^&()[]{}￥-c397236b0cd4434aab7dfe36fba1a3bd.jpg
> 
> 	thumb_path: upload/2020/12/` !@#$%^&()[]{}￥-c397236b0cd4434aab7dfe36fba1a3bd-thumbnail.jpg
> 
> 	
> 
> 文件正确请求地址： https://www.xxx.com/upload/2020/12/%60%20%21%40%23%24%25%5E%26%28%29%5B%5D%7B%7D%EF%BF%A5-c397236b0cd4434aab7dfe36fba1a3bd.jpg
> 
> 
> 
> 结论：没有对任何特殊字符进行转码处理
> 
> ```
> 
> 
> 
> ## 错误2
> 
> ```language
> 
> 访问页面: /photos  
> 
> 数据库对应数据:
> 
> 	表名: photos
> 
> 	name: ` !@#$%^&()[]{}￥
> 
> 	thumbnail: https://www.xxx.com/upload/2020/12/%60%20!@#$%25%5E&()%5B%5D%7B%7D%EF%BF%A5-c397236b0cd4434aab7dfe36fba1a3bd-thumbnail.jpg
> 
> 	url: https://www.xxx.com/upload/2020/12/%60%20!@#$%25%5E&()%5B%5D%7B%7D%EF%BF%A5-c397236b0cd4434aab7dfe36fba1a3bd.jpg
> 
> 
> 
> 文件正确请求地址： https://www.xxx.com/upload/2020/12/%60%20%21%40%23%24%25%5E%26%28%29%5B%5D%7B%7D%EF%BF%A5-c397236b0cd4434aab7dfe36fba1a3bd.jpg
> 
> 
> 
> 结论：没有对部分特殊字符进行转码处理
> 
> ```
> 
> 
> 
> 建议对所有特殊字符都进行转码处理，免得再出其他bug
> 
> 
> 
> 

没错，上面我已经说了，所有后端接口对文章图片都没有做编码处理，但是在 admin 取图片的时候是已经在前端处理过的，所以我想问的是目前你具体在哪个功能出现了图片不能显示的问题。

至于到底要不要在接口处理，有待讨论。

**Comment by Lwenguang** [comment]
所有页面都无法显示这种图片

**Comment by ruibaby** [comment]
> 所有页面都无法显示这种图片

好吧，附件详情显示的链接确实没有做 urlencode 处理，但是对其进行复制和选择的时候是处理了的。接下来我们会直接在后端处理。

**Comment by Simple-Stark** [comment]
如果要在后端接口处理，是要在获取的接口，也就是上面提到的
  `/api/admin/attachments     /api/admin/photos` 中进行处理还是在入库之前进行处理呢？

**Comment by ruibaby** [comment]
> 如果要在后端接口处理，是要在获取的接口，也就是上面提到的 `/api/admin/attachments /api/admin/photos` 中进行处理还是在入库之前也就是上传接口进行处理呢？

这一块还需要验证，目前没收到其他反馈会有这个问题。

**Comment by Lwenguang** [comment]
我把bug详情写在这篇文章里了 https://lwguang.com/archives/urlencode-bug

**Comment by Simple-Stark** [comment]
> > 如果要在后端接口处理，是要在获取的接口，也就是上面提到的 `/api/admin/attachments /api/admin/photos` 中进行处理还是在入库之前也就是上传接口进行处理呢？
> 
> 这一块还需要验证，目前没收到其他反馈会有这个问题。

经过本人验证，当含有# % 这两个特殊符号时，会出现 @[Lwenguang](https://github.com/Lwenguang)  所说的这个问题
如果仅仅是两个特殊符号的问题，还需要修改吗？
如果需要修改的话，建议是查询的接口进行处理可以兼容之前的数据。
如果不需要修改的话，建议关闭此Issue

**Comment by guqing** [comment]
考虑到兼容性问题，应该在此行对文件名进行 url encoding 处理，即只对返回结果编码
https://github.com/halo-dev/halo/blob/913002d56d64b7dbd20b169921754a12790fcf80/src/main/java/run/halo/app/service/impl/AttachmentServiceImpl.java#L177
可以如下操作
```
// 将 local 存储的链接中的文件名替换为编码后的文件名
String path = attachmentDTO.getPath()
                .replace(attachmentDTO.getName(), encodeValue(attachmentDTO.getName()));
// ....
// 附件缩略图亦如是
 String basename = FilenameUtils.getBasename(attachmentDTO.getName());
 String extension = FilenameUtils.getExtension(attachmentDTO.getName());
// 得到 thumbail name
 String thumbnailName = String.format("%s-thumbnail%s", basename, extension);
 String thumbnailPath = attachmentDTO.getThumbPath()
      .replace(thumbnailName, encodeValue(thumbnailName));

// ...
 private String encodeValue(String value) {
    return UriUtils.encode(value, StandardCharsets.UTF_8);
}
```
以上代码中关于缩略图文件名获取的方式需要考虑：后续如果缩略图规则改变不应该影响到此处功能，所以要确保本地上传策略生存缩略图和此处规则一致

**Comment by ruibaby** [comment]
@Simple-Stark 可以看看这里 https://github.com/halo-dev/halo/pull/1874#pullrequestreview-955803501

我们打算在后端接口统一处理。

**Comment by JohnNiang** [comment]
Hi @FanZeros，方便的话，可以回复一下 `/assign`，halo-ci-bot 会自动将这个 issue assign 给你。:heart:
