### ISSUE TITLE
服务器端口只开在ipv6？

### ISSUE THREAD

**Issue by stone16** [halo-dev/halo#1206]
## 我的环境
CentOS 7.x 

---

## 错误日志

---
正在配置服务器的过程当中，跟着官方指南刷新了Systemd 启动了Halo，然后我使用了`netstat -tlnp` 来看端口监听情况，发现只在ipv6上开了端口，ipv4上没有开。
```
>>> netstat -ltnp
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -
tcp6       0      0 ::1:25                  :::*                    LISTEN      -
tcp6       0      0 :::8090                 :::*                    LISTEN      -
tcp6       0      0 :::111                  :::*                    LISTEN      -
tcp6       0      0 :::22                   :::*                    LISTEN      -
```

## 期望行为
理论上应该在tcp 和tcp6上都开端口的，想知道是哪里出了问题

## 当前行为

只开在ipv6. 尝试直接调用jar包加上ipv4Pref的配置，`java -jar /home/halo/halo-latest.jar -Djava.net.preferIPv4Stack=true ` 这样子是能够在服务器ipv4地址上访问到的。

但是转向System halo文件的配置，同样的参数还是只在ipv6开了端口 `/usr/bin/java -server -Xms256m -Xmx256m -jar /home/halo/halo-latest.jar -Djava.net.preferIPv4Stack=true `

不知道有没有还遇到这样的问题了..

**Comment by JohnNiang** [comment]
可以尝试配置 application.yml：

```yaml
server:
    address: 0.0.0.0
```

**Comment by stone16** [comment]
> 可以尝试配置 application.yml：
> 
> ```yaml
> server:
>     address: 0.0.0.0
> ```

尝试了下，还是只有ipv6的

**Comment by ruibaby** [comment]
参考一下 v2ex 的这个帖子。https://www.v2ex.com/t/474718

**Comment by stone16** [comment]
谢谢，意识到问题是在EC2 VPC还有防火墙那里的配置，另外关于ipv4 还有ipv6的问题[stackoverflow](https://stackoverflow.com/questions/44718174/spring-boot-application-listens-over-ipv6-without-djava-net-preferipv4stack-tru) 意识到是会默认先找ipv6，可以通过下面指令来进行配置
```
ExecStart=/usr/bin/java -server -Xms256m -Xmx256m -jar YOUR_JAR_PATH -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses
```
