### ISSUE TITLE
orcl.cc,cccccc.me,ccccc.me,有个疑问，就是如果使用3个域名做集群，文章路径都是第一个开启项目的域名

### ISSUE THREAD

**Issue by JohnNiang** [halo-dev/halo#122]
orcl.cc,cccccc.me,ccccc.me,有个疑问，就是如果使用3个域名做集群，文章路径都是第一个开启项目的域名

_Originally posted by @proxygit in https://github.com/halo-dev/halo/issues/26#issuecomment-474387922_

**Comment by JohnNiang** [comment]
没有彻底明白你的意思。

**Comment by proxygit** [comment]
就是想多域名访问同一服务，这里又很多页面都是默认拼接博客设置的地址栏。

**Comment by JohnNiang** [comment]
@proxygit 直接用 cname 不就解决了么

**Comment by proxygit** [comment]
emmm，刚谷歌了半天，又学到了新东西，还真不知道有这种解析方式，感谢大佬
