### ISSUE TITLE
就是日志功能可以改善为朋友圈的功能

### ISSUE THREAD

**Issue by winsway** [halo-dev/halo#1223]
希望能够将日志的功能扩展为朋友圈的功能，实现九宫宫格或者插入多张图片的形式。因为日志功能文字的字数是有上限的。一排版就不能操作了。

**Comment by JohnNiang** [comment]
不错的思路，可以考虑添加 star 其他 halo 博客的功能，然后将日志列表融合起来。

**Comment by winsway** [comment]
对的，因为现在微信朋友圈实在是政治化和站队化的风格，不属于自己的私人领地了。

**Comment by corgile** [comment]
这个难道不可以通过修改ftl文件或主题代码实现吗

**Comment by RealKiro** [comment]
Bug？
- 写日志无法评论点赞，但是后台又有评论点赞按钮
- 发表的日志还是希望在`首页`和`归档`里面显示
以上，否则这个功能似乎没什么用啊（大雾

**Comment by winsway** [comment]
不是哈，就是希望写一写自己的生活的状态，每次都这一个文档太多了，没有必要，也写不出这么多话。



---原始邮件---
发件人: "未日"<notifications@github.com&gt;
发送时间: 2021年2月16日(周二) 下午5:47
收件人: "halo-dev/halo"<halo@noreply.github.com&gt;;
抄送: "winsway"<winsway_zero@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [halo-dev/halo] 就是日志功能可以改善为朋友圈的功能 (#1223)




 
Bug？
  
写日志无法评论点赞，但是后台又有评论点赞按钮 

发表的日志还是希望在首页和归档里面显示
 以上，否则这个功能似乎没什么用啊（大雾

**Comment by java-aodeng** [comment]
亲，这边建议注册个微博，还能骂人哦:smirk:

**Comment by ruibaby** [comment]
目前 2.0 的 Moments 插件已经支持这样的特性，且 1.x 不再打算进行功能更新，所以关闭此 issue。

https://github.com/halo-sigs/plugin-moments

/close
