### ISSUE TITLE
文章字数统计算法过滤的内容不适合

### ISSUE THREAD

**Issue by cetr** [halo-dev/halo#1224]
## 我的环境

版本：1.4.2
数据库：MySQL 8.0.22
运行模式：production
User Agent：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36

---

## 错误

文章字数统计算法过滤的内容不适合

---

## 期望行为

只统计访客浏览时能看到的文字数，将其他比如将标签，图片的src内容和一切访问是不能直接看到的全不计入统计

## 当前行为

比如我在文章中插入几个Base64编码的图片，好家伙，最后统计出来几十万字的文章，当然不止图片的src属性，还有其他各种情况也需要剔除

**Comment by JohnNiang** [comment]
Confirmed.

**Comment by ruibaby** [comment]
https://github.com/halo-dev/halo/pull/1354
