### ISSUE TITLE
feat: 加密分类实现方案讨论

### ISSUE THREAD

**Issue by zhixiangyuan** [halo-dev/halo#1225]
## 概述

增加分类加密功能，当分类 A 被加密，文章 A、B 均处于该分类下时，需要输入分类 A 的加密密码。若某篇文章处于多个加密分类下，则输入正确任意加密分类的密码即可访问。

## 动机

总有一些内容是希望能通过验证的人才能看到

## 详细解释

目前加密文章的访问时序图：

<img width="742" alt="目前访问加密文章的流程" src="https://user-images.githubusercontent.com/25138766/104563892-35e87d00-5685-11eb-8b8a-12c5893421e0.png">

改动过后分类及文章的访问时序图：

<img width="648" alt="加密分类时序图" src="https://user-images.githubusercontent.com/25138766/104564130-8364ea00-5685-11eb-9618-b685c3501ae0.png">

**Comment by zhixiangyuan** [comment]
>1. 你所说的分类加密是加密分类还是加密分类下的文章，加密之后文章是否还能被其他地方查询到。
>2. 如何与目前的私密文章兼容。
>3. 向下兼容之前已经加密的文章。
>4. 路由处理。
> @ruibaby 

1. 对分类进行加密，密码设置在分类上。分类被加密则分类下面的文章均无法访问
2. 目前的私密文章加密通过判断密码是否相同来进行加密，加密分类同样采用判断密码是否相同的方式实现
3. 通过优先级的方式兼容已加密的文章，如果文章设置了密码，那么文章密码的优先级大于分类密码的优先级
4. 该改动只支持 restful api，不向 freemarker 跳转，无路由问题

**Comment by ruibaby** [comment]
@zhixiangyuan 只支持 rest api 是？

**Comment by ruibaby** [comment]
@JohnNiang 有时间 check 一下。

**Comment by zhixiangyuan** [comment]
> @zhixiangyuan 只支持 rest api 是？

是的

**Comment by ruibaby** [comment]
> > @zhixiangyuan 只支持 rest api 是？
> 
> 是的

那现有主题怎么兼容？

**Comment by zhixiangyuan** [comment]
> > > @zhixiangyuan 只支持 rest api 是？
> > 
> > 
> > 是的
> 
> 那现有主题怎么兼容？

如果要兼容现有主题可以复用目前的 `post_password.ftl`，该模版页面用于给用户输入密码。在用户访问目录的时候判断访问的目录是否有加密，如果有的话则跳转到输入密码的页面，在输入密码后再跳转到主题分类列表页面。访问文章同理。这样就可以完成对现有主题的支持，并且不需要目前的主题做任何修改。

**Comment by LIlGG** [comment]
> > > > @zhixiangyuan 只支持 rest api 是？
> > > 
> > > 
> > > 是的
> > 
> > 
> > 那现有主题怎么兼容？
> 
> 如果要兼容现有主题可以复用目前的 `post_password.ftl`，该模版页面用于给用户输入密码。在用户访问目录的时候判断访问的目录是否有加密，如果有的话则跳转到输入密码的页面，在输入密码后再跳转到主题分类列表页面。访问文章同理。这样就可以完成对现有主题的支持，并且不需要目前的主题做任何修改。

实际上这样做还是会对所有主题有影响。 意味着所有主题都必须存在 `post_password.ftl`，也就意味着如果在这个版本更新之后，没有这个 ftl 的主题将会出现功能不完善的问题。所有的主题都需要同步增加。

**Comment by zhixiangyuan** [comment]
> > > > > @zhixiangyuan 只支持 rest api 是？
> > > > 
> > > > 
> > > > 是的
> > > 
> > > 
> > > 那现有主题怎么兼容？
> > 
> > 
> > 如果要兼容现有主题可以复用目前的 `post_password.ftl`，该模版页面用于给用户输入密码。在用户访问目录的时候判断访问的目录是否有加密，如果有的话则跳转到输入密码的页面，在输入密码后再跳转到主题分类列表页面。访问文章同理。这样就可以完成对现有主题的支持，并且不需要目前的主题做任何修改。
> 
> 实际上这样做还是会对所有主题有影响。 意味着所有主题都必须存在 `post_password.ftl`，也就意味着如果在这个版本更新之后，没有这个 ftl 的主题将会出现功能不完善的问题。所有的主题都需要同步增加。

`post_password.ftl` 是系统里面目前已有的通用 ftl 模版，目前点击加密文章弹出来的那个页面就是这个模版，这里在跳转的时候可以先去找用户有没有自定义 `post_password.ftl`，如果有的话就跳到用户自定义的 ftl 上，如果没有的话就调到默认 ftl 上

**Comment by ruibaby** [comment]
> > > > > > @zhixiangyuan 只支持 rest api 是？
> > > > > 
> > > > > 
> > > > > 是的
> > > > 
> > > > 
> > > > 那现有主题怎么兼容？
> > > 
> > > 
> > > 如果要兼容现有主题可以复用目前的 `post_password.ftl`，该模版页面用于给用户输入密码。在用户访问目录的时候判断访问的目录是否有加密，如果有的话则跳转到输入密码的页面，在输入密码后再跳转到主题分类列表页面。访问文章同理。这样就可以完成对现有主题的支持，并且不需要目前的主题做任何修改。
> > 
> > 
> > 实际上这样做还是会对所有主题有影响。 意味着所有主题都必须存在 `post_password.ftl`，也就意味着如果在这个版本更新之后，没有这个 ftl 的主题将会出现功能不完善的问题。所有的主题都需要同步增加。
> 
> `post_password.ftl` 是系统里面目前已有的通用 ftl 模版，目前点击加密文章弹出来的那个页面就是这个模版，这里在跳转的时候可以先去找主题有没有自定义 `post_password.ftl`，如果有的话就跳到用户自定义的 ftl 上，如果没有的话就跳到默认 ftl 上

嗯，这是计划中的。

**Comment by zhixiangyuan** [comment]
> > > > > > > @zhixiangyuan 只支持 rest api 是？
> > > > > > 
> > > > > > 
> > > > > > 是的
> > > > > 
> > > > > 
> > > > > 那现有主题怎么兼容？
> > > > 
> > > > 
> > > > 如果要兼容现有主题可以复用目前的 `post_password.ftl`，该模版页面用于给用户输入密码。在用户访问目录的时候判断访问的目录是否有加密，如果有的话则跳转到输入密码的页面，在输入密码后再跳转到主题分类列表页面。访问文章同理。这样就可以完成对现有主题的支持，并且不需要目前的主题做任何修改。
> > > 
> > > 
> > > 实际上这样做还是会对所有主题有影响。 意味着所有主题都必须存在 `post_password.ftl`，也就意味着如果在这个版本更新之后，没有这个 ftl 的主题将会出现功能不完善的问题。所有的主题都需要同步增加。
> > 
> > 
> > `post_password.ftl` 是系统里面目前已有的通用 ftl 模版，目前点击加密文章弹出来的那个页面就是这个模版，这里在跳转的时候可以先去找主题有没有自定义 `post_password.ftl`，如果有的话就跳到用户自定义的 ftl 上，如果没有的话就跳到默认 ftl 上
> 
> 嗯，这是计划中的。

大佬，没什么问题的话我就按照这个思路开始开发了

**Comment by ruibaby** [comment]
> 大佬，没什么问题的话我就按照这个思路开始开发了

晚点我再通知 @JohnNiang 看一下。

**Comment by zhixiangyuan** [comment]
> > 大佬，没什么问题的话我就按照这个思路开始开发了
> 
> 晚点我再通知 @JohnNiang 看一下。

👌

**Comment by JohnNiang** [comment]
不太明白使用分类进行加密的场景是什么。

**Comment by zhixiangyuan** [comment]
> 不太明白使用分类进行加密的场景是什么。

比如说个人的投资日记

**Comment by zhixiangyuan** [comment]
> 不太明白使用分类进行加密的场景是什么。

老哥，你看下这个方案有没有什么问题，没问题的话，我就开始开发了

**Comment by JohnNiang** [comment]
> > 不太明白使用分类进行加密的场景是什么。
> 
> 老哥，你看下这个方案有没有什么问题，没问题的话，我就开始开发了

好的，感谢您的贡献！
