### ISSUE TITLE
请教一下这个项目的sql语句是怎么自动导入的？（因为我在研究该项目的源码）

### ISSUE THREAD

**Issue by mebest100** [halo-dev/halo#1227]
请教一下这个项目的sql语句是怎么自动导入的？（因为我在研究该项目的源码）

另外一个问题：我看到admin页面貌似不是从controller控制的，好像是从resource文件夹下的vue构建的静态页面进来的，
但是我并没有在这个admin目录的html页面文件中找到登录表单这些东西，能帮忙看看这些内容在哪个文件吗？　

另外：localhost:8090/根路径是直接跳转到用户博客列表的路由的，但是我在controller里面也没找到(controller里面全是/api开头的)，这个跳转路由的定义文件也能帮忙看看吗？ 谢谢

**Comment by ruibaby** [comment]
研究一下 Hibernate 和 Spring Data JPA。

https://github.com/halo-dev/halo

https://github.com/halo-dev/halo/blob/master/src/main/java/run/halo/app/controller/content/ContentIndexController.java#L60

**Comment by mebest100** [comment]
> 研究一下 Hibernate 和 Spring Data JPA。
> 
> https://github.com/halo-dev/halo
> 
> https://github.com/halo-dev/halo/blob/master/src/main/java/run/halo/app/controller/content/ContentIndexController.java#L60

好的，谢谢！这个JPA的问题大致搞清楚了。

还有那个resource目录下的admin目录下的html页面文件中并找到登录表单这些东西，能帮忙看看这些内容在哪个文件吗？

**Comment by ruibaby** [comment]
https://github.com/halo-dev/halo-admin 构建之后的产物，css 和 js 在公共 cdn。

上面链接给错了。

**Comment by mebest100** [comment]
好的，谢谢！
