### ISSUE TITLE
CentOS不是halo用户的时候，无法进行数据备份。

### ISSUE THREAD

**Issue by Lilac-Dream** [halo-dev/halo#1228]
## 我的环境
部署系统：CentOS7直接部署，没有使用Docker部署。
版本：1.4.2
数据库：MySQL 8.0.22
运行模式：production
User Agent：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36

---

## 错误日志

+ 2021-01-16 06:05:00.851 ERROR 980 --- [qtp1920907467-52] r.h.app.core.ControllerExceptionHandler  : Captured an exception: [Failed to backup halo]
+ 2021-01-16 06:05:05.522 ERROR 980 --- [qtp1920907467-43] r.h.app.core.ControllerExceptionHandler  : Captured an exception: [导出数据失败]

---

## 期望行为
+ CentOS部署到不是halo的用户下，博客备份和数据导出能够生成备份文件。

## 当前行为

1. CentOS不是halo用户的时候，当前“博客备份”的“整站导出”操作，会提示"Failed to backup halo"。
2. CentOS不是halo用户的时候，当前“博客备份”的“数据导出”操作，会提示"导出数据失败"。

## 补充：
+ 经过一系列测试后发现，只有当CentOS中的用户是halo的情况下，博客备份功能才能够正常使用，换其他CentOS的用户后，无法导出备份文件，并且博客的其他功能都正常。
+ 对于配置文件的权限，已经多次试验，即使chmod 777 ~/.halo的权限，也依然无法导出。所以我怀疑，当前是不支持halo用户以外的用户进行备份操作）

**Comment by ruibaby** [comment]
没有这样的限制。

**Comment by JohnNiang** [comment]
@Lilac-Dream 建议用以下 jar 包复现一下，同时也建议开启 debug 模式。

> https://github.com/JohnNiang/halo/releases/download/v1.5.7/halo-1.4.2.jar

**Comment by Lilac-Dream** [comment]
嗯嗯，先不管了，能用就好了~非常感谢回复~
