### ISSUE TITLE
BUG 反馈

### ISSUE THREAD

**Issue by aquanlerou** [halo-dev/halo#123]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://docs.halo.run/)
- [x] [Github Wiki 常见问题](https://github.com/ruibaby/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/ruibaby/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

----

Halo后台就是编辑文章更新操作时，按了更新后，再不小心按到别的菜单后修改的内容更新了，可是再进来该更新的文件，会变成回没更新的，【写文章】【主题编辑】这两个功能都会出现这样的Bug。
现在的解决办法就是重启项目或则服务器...

**Comment by JohnNiang** [comment]
`可能`是由于 前端 `localStorage` 的问题。不过需要逐步排查。
