### ISSUE TITLE
feat: 私密文章功能体验优化

### ISSUE THREAD

**Issue by graydovee** [halo-dev/halo#1230]
## 概述
1. 能否检测admin是否已登陆，若admin已经登陆则无需再输入文章密码
2. 私密文章分享功能，能否生成私密文章一次性的分享链接，以方便将文章分享给朋友

## 动机
* 我现在博客里有些文章包含一些敏感数据，比如mysql配置的文章里有我的数据库的常用密码，所以我将这些敏感数据独立到了另一篇私密文章里，并在原文章保存了一个跳转url，但体验不是很好，每次打开文章都要重新输入密码。
* 我在有时候想将私密文章分享给朋友时，对方打开文章还得输入密码，操作比较麻烦。而且我并不希望对方一直能知道文章的密码，分享后改密码又比较麻烦，所以希望能生成一次性的分享链接

**Comment by ruibaby** [comment]
1. 暂时无法解决，但是我们会研究。
2. 有这个计划。

**Comment by ruibaby** [comment]
> 能否检测admin是否已登陆，若admin已经登陆则无需再输入文章密码

2.x 支持登录之后访问私有文章

> 私密文章分享功能，能否生成私密文章一次性的分享链接，以方便将文章分享给朋友

2.x 社区已经有了类似的插件：https://github.com/guqing/plugin-share-post-via-link

/close
