### ISSUE TITLE
feat: 希望能够增加自动备份至对象存储的功能

### ISSUE THREAD

**Issue by Techoc** [halo-dev/halo#1234]
## 概述
设置定时任务备份数据至远端的对象存储

## 动机
能让数据能够保障性

**Comment by ruibaby** [comment]
通过外部脚本就可以很好的实现你的需求，目前不打算加类似功能。

参考：https://ryanc.cc/archives/record-how-to-save-my-blog.html

当然不限于文章内的远程 Git 仓库。
