### ISSUE TITLE
为什么访问会有5秒钟左右的等待 大概第六秒才能访问通 开始加载页面

### ISSUE THREAD

**Issue by xxxxuanya** [halo-dev/halo#1243]
为什么访问会有5秒钟左右的等待 大概第六秒才能访问通 开始加载页面

**Comment by ruibaby** [comment]
不好判断，请提供你的站点链接。

**Comment by xxxxuanya** [comment]
ip是 106.54.114.83:8090 感谢帮忙看看

> 不好判断，请提供你的站点链接。

**Comment by ruibaby** [comment]
无法判断具体问题，大概率和服务器性能有关。

**Comment by ruibaby** [comment]
是不是用的 MySQL？换成默认的数据库试试？
