### ISSUE TITLE
feat: 增加多用户管理、发布功能

### ISSUE THREAD

**Issue by YuYongzhi** [halo-dev/halo#1251]
希望增加多用户管理功能，同时各个用户可独立登录后台发布文章

## 概述

1、增加多用户管理

## 动机

小团队内各个成员在 Halo 平台上使用时，由于使用相同账号登录发布文章，导致无法区分是谁发布的。

## 详细解释

新增这个功能，更方便团队内管理、统计等

**Comment by ruibaby** [comment]
会考虑，但得排在后面的大版本了。

**Comment by moon-sixpence** [comment]
希望增加多用户管理功能

**Comment by lemoniiio** [comment]
希望增加多用户功能

**Comment by myread-code** [comment]
希望增加多用户管理功能

**Comment by yiweizhi** [comment]
希望增加多用户管理功能

**Comment by dysf888** [comment]
> 希望增加多用户管理功能

现阶段用来班级日志记录,单用户只能以专业名+班级 来发布,希望早日提上日程

**Comment by guqing** [comment]
> > 希望增加多用户管理功能
> 
> 现阶段用来班级日志记录,单用户只能以专业名+班级 来发布,希望早日提上日程

可以关注 milestone2.0 https://github.com/halo-dev/halo/milestone/19 开发进度，提供了此功能

**Comment by ruibaby** [comment]
已经在 [next](https://github.com/halo-dev/halo/tree/next) 分支支持，将在 2.0 发布。

/close
