### ISSUE TITLE
文章保存错误

### ISSUE THREAD

**Issue by MakiseVon** [halo-dev/halo#1253]
## 我的环境

版本：1.4.3
数据库：H2 1.4.197 (2018-03-18)
运行模式：production
User Agent：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36

---

## 错误日志

保存的过程中没有产生错误日志。

---

## 期望行为

保存成功

## 当前行为

PC端，后台。
新建一篇文章，起标题。
在文章中输入如下内容（定位到的，我也不知道为啥）：

````
tell (x : y : []) = "The list has two elements: " ++ show x ++ " and " ++ show y
tell (x : y : _) = "This list is long. The first two elements are: " ++ show x ++ " and " ++ show y
````

然后用鼠标点击保存草稿（而不是用键盘快捷键），产生错误。

![](https://i.loli.net/2021/01/31/S1itRDczUPVMBZ2.png)

不断重复用鼠标点击保存草稿，会提示网络错误，最后页面崩溃。

![](https://i.loli.net/2021/01/31/dubf3HUegCnJlRs.png)

其他信息：

我用 docker 部署 halo，由于容器内连不上网，添加了 `--net=host` 选项，不知道有没有关系。

其他尝试：

![](https://i.loli.net/2021/01/31/EDxkZ5aG7LnIgd1.png)

![](https://i.loli.net/2021/01/31/VCkzSiqlQnDcFos.png)

我真的懵了 qaq

**Comment by MakiseVon** [comment]
补充：发布也错误 orz

**Comment by lnsane** [comment]
> 补充：发布也错误 orz

正在 复现 bug

**Comment by ruibaby** [comment]
根据你的内容测试没有复现问题。建议先打开浏览器看看是否是 Nginx 那边报的错。

**Comment by ruibaby** [comment]
@ruibaby 补充：出现这种没有内容的提示，一般就是 nginx 的异常，都还没有经过 halo 服务。

**Comment by lnsane** [comment]
的确没有办法复现这个bug

**Comment by MakiseVon** [comment]
555 我懂了，我开了宝塔的 nginx 防火墙服务，然后就这样子了 orz
感谢各位的帮助 qaq
