### ISSUE TITLE
How to change language in markdown halo editor

### ISSUE THREAD

**Issue by salahatwa** [halo-dev/halo#1254]
How we can change language for halo editor  to be English rather than Chinese ,

` <halo-editor
      ref="md"
      v-model="originalContentData"
      :boxShadow="false"
      :toolbars="toolbars"
      :ishljs="true"
      autofocus
      @imgAdd="handleAttachmentUpload"
      @save="handleSaveDraft"
    />`

Thanks.

**Comment by ruibaby** [comment]
https://github.com/halo-dev/halo-editor

**Comment by salahatwa** [comment]
there's no information about how to do that in provided link , please your support

**Comment by ruibaby** [comment]
> there's no information about how to do that in provided link , please your support

maybe you need fork it and publish to your npm packages. then install in your halo-admin.

By the way, do you want to translate into another language and use it?

**Comment by salahatwa** [comment]
yes ,  when we trying write article , markdown appears with Chinese (mean bold - italic -headlines ) tooltip appear with chinese language , how we can change it to english language

**Comment by ruibaby** [comment]
> yes , when we trying write article , markdown appears with Chinese (mean bold - italic -headlines ) tooltip appear with chinese language , how we can change it to english language

The halo editor only supports Chinese for the time being, so you can fork it, After translation, you can publish to your npm packages, Finally install your npm packages in halo-admin.

By the way, we already have plans to support internationalization and will support it in future major versions.

**Comment by salahatwa** [comment]
Thanks for your gentle support .
