### ISSUE TITLE
能否增加链接转换开关？ 

### ISSUE THREAD

**Issue by yhl452493373** [halo-dev/halo#1257]
## 概述

编辑文章时，增加一个文字自动转链接的开关

## 动机

经常自动把不需要转链接的转成了链接，比如我写个申请域名的博客，必然会涉及到一些假构域名，例如a.b.com这种，但是也自动转成链接了，为了让其不显得奇怪（点击后不能正常访问），我必须对其进行修正，改成正常的连接才行。

**Comment by ruibaby** [comment]
没有太明白你的意思。是编辑器吗？

**Comment by yhl452493373** [comment]
是的，编辑文章的时候。

**Comment by yhl452493373** [comment]
> 没有太明白你的意思。是编辑器吗？

是的，编辑文章的时候。

**Comment by ruibaby** [comment]
> > 没有太明白你的意思。是编辑器吗？
> 
> 是的，编辑文章的时候。

你可以通过 `` 语法包裹链接试试。

**Comment by yhl452493373** [comment]
> > > 没有太明白你的意思。是编辑器吗？
> > 
> > 
> > 是的，编辑文章的时候。
> 
> 你可以通过 `` 语法包裹链接试试。

好的，回头试试。这个一直没找到方法

**Comment by JohnNiang** [comment]
是否符合预期呢？
