### ISSUE TITLE
添加cdn

### ISSUE THREAD

**Issue by husky105** [halo-dev/halo#1260]
请问，有helo博客如何添加cdn的介绍或教程吗?
感谢！！！

**Comment by JohnNiang** [comment]
可以看看： https://github.com/halo-dev/halo/issues/944

**Comment by JohnNiang** [comment]
或者：https://championmi.cn/archives/网站博客配置又拍云cdn

**Comment by husky105** [comment]
> 或者：[https://championmi.cn/archives/网站博客配置又拍云cdn](https://championmi.cn/archives/%E7%BD%91%E7%AB%99%E5%8D%9A%E5%AE%A2%E9%85%8D%E7%BD%AE%E5%8F%88%E6%8B%8D%E4%BA%91cdn)

感谢
