### ISSUE TITLE
无法进入开发者模式

### ISSUE THREAD

**Issue by codesensi** [halo-dev/halo#1261]
点击10次Dashboard之后，提示已进入开发者模式，页面跳转到小工具页面，但是页面不显示开发者模式菜单。
域名和IP+端口号访问情况一致。
![image](https://user-images.githubusercontent.com/66196408/107111515-a309bf80-688b-11eb-9f1b-1824a68c989a.png)

使用环境：
服务器：阿里云 centos8.2
数据库：docker mysql 最新版
halo：docker 最新版
nginx：docker nginx 最新版
浏览器：最新版Edge

**Comment by JohnNiang** [comment]
无法复现...

**Comment by codesensi** [comment]
> 无法复现...

emmmm，这就有点尴尬了，我再重新部署试试吧

**Comment by JohnNiang** [comment]
我在本地用 docker 运行了一个实例，仍然无法复现。

**Comment by codesensi** [comment]
> 我在本地用 docker 运行了一个实例，仍然无法复现。

我猜有可能是nginx的问题，我在虚拟机里装了halo和MySQL，直接用ip访问，是没问题的，我也没再做测试了，大概率是我nginx配置有问题，这个issue我就关了哈，多谢大佬

**Comment by ruibaby** [comment]
检查一下 nginx 的缓存配置。
