### ISSUE TITLE
halo换服务器后能否平行迁移

### ISSUE THREAD

**Issue by ChunelFeng** [halo-dev/halo#1262]
我在阿里云ecs上通过docker部署halo。
如果我要更换ecs的机器了，在新的机器上，能否通过docker直接登录账号和密码，直接获取原先博客里的所有内容？
需要做什么迁移操作么？

**Comment by ruibaby** [comment]
可以先看看 https://docs.halo.run/install/prepare 里面对于工作目录（.halo）的说明。

实际上只需要迁移 .halo 目录即可。前提是你 docker 容器有把 /root/.halo 目录映射到宿主机。

**Comment by ChunelFeng** [comment]
> 可以先看看 https://docs.halo.run/install/prepare 里面对于工作目录（.halo）的说明。
> 
> 实际上只需要迁移 .halo 目录即可。前提是你 docker 容器有把 /root/.halo 目录映射到宿主机。

了解了，是很方便呢！感谢大佬
