### ISSUE TITLE
feat: 希望能添加相册、文章密码访问功能

### ISSUE THREAD

**Issue by Lulululx** [halo-dev/halo#1263]
## 概述
希望Halo可以提供一个相册＆文章加密的功能

## 动机
之前用过typecho里面的handsome主题支持文章、相册的加密访问功能，因为博客站点可能就会记录一些生活上的事情，并不希望让所有人都知道，halo是一个非常优秀的博客系统，希望在typecho上出现的实用的功能在halo上也能实现

## 详细解释
文章、相册要输入指定密码才能访问，从而只让一部分人看到某些内容。

**Comment by LIlGG** [comment]
文章、分类输入密码已经实现，详见 #1225 #1235 。

**Comment by ruibaby** [comment]
如上所说，文章已经支持。但是相册是独立的，不是太想去实现。你可以在一个指定主题里面新建一个 post_photos.ftl，然后在发表文章的时候选择这个自定义模板来实现相册加密。
