### ISSUE TITLE
文章密码访问功能 404

### ISSUE THREAD

**Issue by hotspring-zwb** [halo-dev/halo#1265]
## 操作方式
halo 1.4.4 版本，从 首页 -> 分类 -> 点击加密文章， 输入 密码， 页面一致报404 
返回到 首页， 再次点击 可以直接打开 加密文章
## 期望

1. 如何处理这个问题
2. 密码正确 或密码错误 都是放回 404 ，这个能给个具体提示么

**Comment by ruibaby** [comment]
@hotspring-zwb 会在今晚发布一个版本解决此问题。https://github.com/halo-dev/halo/pull/1264
