### ISSUE TITLE
Halo OpenAPI 文档描述与实际不符合

### ISSUE THREAD

**Issue by cwxyz007** [halo-dev/halo#1274]
## 我的环境

版本：1.4.3
数据库：H2 1.4.197 (2018-03-18)
运行模式：production
User Agent：Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36 Edg/88.0.705.68

---

## 错误日志

无

---

## 期望行为

Halo OpenAPI 文档描述与实际不符合，期望 OpenAPI 文档描述与实际一致

## 当前行为

例如 `/api/content/posts` 的返回值如下

![image](https://user-images.githubusercontent.com/14226737/108299399-54d4b480-71d9-11eb-844b-8da5df7537c7.png)

但是实际返回值如下

![image](https://user-images.githubusercontent.com/14226737/108299466-72098300-71d9-11eb-9f41-41a8e93a4f2c.png)

实际应该不止这个 API 的描述不一致，其它 API 也有不一致的地方。

**Comment by JohnNiang** [comment]
关于分页返回参数问题，稍后解决。

**Comment by cwxyz007** [comment]
请问一下 1.4.6 的版本会以 OpenAPI 文档为准吗？还是以现在实际返回的为准呢？

**Comment by ruibaby** [comment]
> 请问一下 1.4.6 的版本会以 OpenAPI 文档为准吗？还是以现在实际返回的为准呢？

实际返回结果。

**Comment by JohnNiang** [comment]
以实际返回为准。
