### ISSUE TITLE
安全性建议，可设置是否允许使用邮箱登录

### ISSUE THREAD

**Issue by cetr** [halo-dev/halo#1276]
建议后台可以设置是否允许使用邮箱登录，避免被人暴力试密码

**Comment by ruibaby** [comment]
开个 2FA？

**Comment by cetr** [comment]
> 开个 2FA？

需求不同，我还是觉得加个是否运行邮箱好些，让用户自己选择

**Comment by JohnNiang** [comment]
为什么使用邮箱登录就能够避免暴力试密码呢？

**Comment by JohnNiang** [comment]
目前登录接口只允许 5s 后重试，能够简单应付暴力破解。

**Comment by cetr** [comment]
> 目前登录接口只允许 5s 后重试，能够简单应付暴力破解。

我想表达的其实也不算暴力破解，就是说当他不知道账号时，怎么试也没用
