### ISSUE TITLE
feat: 希望 content api 中能增加获取网站相关数据 api

### ISSUE THREAD

**Issue by cwxyz007** [halo-dev/halo#1280]
## 概述

![image](https://user-images.githubusercontent.com/14226737/108594303-41ca0c00-73b4-11eb-8457-196452480550.png)

希望能在 content api 中增加接口，获取这些数据。

## 动机

目前正在通过 content API 写 halo 主题 https://github.com/cwxyz007/halo-theme-sakura

发现无法获取 site 相关数据，期望能够增加接口获取相关数据。

**Comment by JohnNiang** [comment]
如果我提供这样 API 看是否合适呢？

```bash
GET http://localhost:8090/api/content/options/bulk?names=option1&names=option2&names=option3
```

**Comment by LIlGG** [comment]
> 如果我提供这样 API 看是否合适呢？
> 
> ```shell
> GET http://localhost:8090/api/content/options/bulk?names=option1&names=option2&names=option3
> ```

感觉是不是使用逗号分隔的形式会更好。比如 GET http://localhost:8090/api/content/options/bulk?names=option1,option2,option3

**Comment by ruibaby** [comment]
> 感觉是不是使用逗号分隔的形式会更好。比如 GET http://localhost:8090/api/content/options/bulk?names=option1,option2,option3

实际情况下，上面那种方式是数组的形式，后端也是用数组接收，你这种前后端处理起来都更麻烦。

**Comment by JohnNiang** [comment]
其实处理起来都不算麻烦。

**Comment by ruibaby** [comment]
> 其实处理起来都不算麻烦。

但我更愿意这样传：

```
const keys = ["blog_title","blog_url"]

axios.get("http://localhost:8090/api/content/options/bulk",{ keys }).then()
```

**Comment by JohnNiang** [comment]
> > 其实处理起来都不算麻烦。
> 
> 但我更愿意这样传：
> 
> ```
> const keys = ["blog_title","blog_url"]
> 
> axios.get("http://localhost:8090/api/content/options/bulk",{ keys }).then()
> ```

这里似乎需要用 qs.stringify 来转换。

**Comment by LIlGG** [comment]
> > 感觉是不是使用逗号分隔的形式会更好。比如 GET http://localhost:8090/api/content/options/bulk?names=option1,option2,option3
> 
> 实际情况下，上面那种方式是数组的形式，后端也是用数组接收，你这种前后端处理起来都更麻烦。

emm。 相较而言，我还是更喜欢我的那种方式。
使用前者迷惑性实在是太强了，如果在多个 names 里面，混入一个其他的参数，比如 `?names=option1&names=option2&mames=option3&names=option4`
而且参数过多以后，接口会过长，还是间接一点好，而且~~毕竟 GET 类型的 url 参数是有限制的~~，虽然一般达不到这个限制。
当然了，上面两个理由都比较牵强，实际上一般是不会出现上述情况的。

但对于 RESTful 风格的 api，目前推荐的还是使用类似 https://segmentfault.com/a/1190000017028535 的投影参数 fields。

结论：看大家喜欢哪种。

**Comment by JohnNiang** [comment]
那就定为：names=key1,key2,key3 吧。

**Comment by JohnNiang** [comment]
我刚刚发现 map_view 接口是提供了 key 数组参数的。
