### ISSUE TITLE
feat: 建议博客系统支持多域名访问

### ISSUE THREAD

**Issue by ZONGQUAN-HU** [halo-dev/halo#1281]
## 概述

建议博客系统支持多域名访问，对于一些情况，可能需要多个域名访问同一个博客系统包括数据库，请在后台支持多个域名支持
## 详细解释
![image](https://user-images.githubusercontent.com/36360150/108619998-c0ca4d80-7463-11eb-93c9-9426a52624bf.png)

**Comment by ZONGQUAN-HU** [comment]
多个博客地址

**Comment by ruibaby** [comment]
现在是兼容的，你可以到博客设置中关闭全局绝对路径就行了。

![image](https://user-images.githubusercontent.com/21301288/108620067-5665dd00-7464-11eb-9c48-76a57e3b88db.png)

**Comment by ZONGQUAN-HU** [comment]
> 现在是兼容的，你可以到博客设置中关闭全局绝对路径就行了。
> 
> ![image](https://user-images.githubusercontent.com/21301288/108620067-5665dd00-7464-11eb-9c48-76a57e3b88db.png)

关掉对吧
