### ISSUE TITLE
feat: 集成 umami 到 halo

### ISSUE THREAD

**Issue by JohnNiang** [halo-dev/halo#1285]
## 概述

将 umaimi 集成到 halo 中，实现访问统计。

## 动机

halo 期望能够有一个独有的访问统计模块，<https://github.com/mikecao/umami> 是一个合适的选择。

## 详细解释

![image](https://user-images.githubusercontent.com/16865714/109019973-7d3a4280-76f4-11eb-889e-baad4f14d659.png)

**Comment by JohnNiang** [comment]
Look at https://github.com/johnniang/spring-boot-umami

**Comment by le0zh0u** [comment]
这个feat还有什么可以参与吗

**Comment by ruibaby** [comment]
> 这个feat还有什么可以参与吗

还在规划当中，可能在 2.0 会以插件的形式提供。

**Comment by le0zh0u** [comment]
你的邮件已收到。谢谢。~

**Comment by ruibaby** [comment]
目前正在开发一个简单的 Umami 集成，可以看看是否满足需求：https://github.com/halo-sigs/plugin-umami

目前支持配置追踪代码的配置、在后台查看访问数据（通过 iframe 嵌入 Umami 的 分享链接）。后续计划通过 Umami 的 API 提供仪表盘的 Widget。

**Comment by ruibaby** [comment]
/close 

https://github.com/halo-sigs/plugin-umami
