### ISSUE TITLE
使用sitemap 提交Google Search Console无法识别

### ISSUE THREAD

**Issue by daochen23** [halo-dev/halo#1288]
### 问题
你好，我使用halo生成的sitemap.xml 提交到Google Search Console，谷歌提示无法识别
![image](https://user-images.githubusercontent.com/49630946/109410981-a4855e00-79d9-11eb-8a32-1a6bbebf5056.png)
但是我通过浏览器的地址栏输入`https://www.kandx.icu/sitemap.xml`是可以找到地图的
![image](https://user-images.githubusercontent.com/49630946/109411027-f1693480-79d9-11eb-9d46-0eb9f3ab1415.png)
请问我这个是什么问题呢
### 其它
- 博客网址：www.kandx.icu
- 博客版本：1.4.5

**Comment by ruibaby** [comment]
不清楚，但大概率是 Google 的问题。

![image](https://user-images.githubusercontent.com/21301288/109411069-4907a000-79da-11eb-8724-ba5a37ddba92.png)

**Comment by daochen23** [comment]
好的，那还有其它的方法让Google收录一下网站么

**Comment by ruibaby** [comment]
你的网站可能用的 1.4.5，先用 1.4.3 吧，这个版本有一个 bug。

https://github.com/halo-dev/halo/issues/1270

**Comment by daochen23** [comment]
好的，谢谢
