### ISSUE TITLE
feat: 基于配置文件完成初始化过程

### ISSUE THREAD

**Issue by liangyuanpeng** [halo-dev/halo#1290]
## 概述

  
当前在每次在部署一个新的halo博客时都需要在页面填写初始化信息，如果这个信息可以在spring的配置文件配置完成，那么就省去了这个初始化的过程，同时对于docker环境来说可以直接使用环境变量来完成这个内容，会比当前便利不少。

## 动机

  

在不同机器上部署halo(每次在新环境部署)后都需要在页面填写初始化信息

**Comment by ruibaby** [comment]
在页面上初始化对于大多数人来说是最好的选择。不认同你的说法。

**Comment by ruibaby** [comment]
在下一个版本，你可以通过数据导入导出来实现你的需求。

参考：

- https://github.com/halo-dev/halo/issues/1213
- https://github.com/halo-dev/halo-admin/pull/296

**Comment by LIlGG** [comment]
我也认为尽量不要使用各种配置文件来初始化。对于用户来说，具有零配置的初始化界面是最好的，且并不是每个用户都了解什么是 spring 的配置文件。
但可以针对于特殊人群，例如开发者等，单独给予功能更强大的方式。

**Comment by liangyuanpeng** [comment]
感谢如此快速回复，需要纠正的一点是 这个issue是希望提供多一个方式，并不需要抛弃现有的页面填写内容初始化的方式。

**Comment by ruibaby** [comment]
@liangyuanpeng 可以尝试一下 json 数据文件导入的方式，我认为要比写一个一个配置方便很多。你只需要创建一个初始博客，然后在后台导出就可以得到这个文件。然后每次新建博客的时候导入就行了。

**Comment by liangyuanpeng** [comment]
> @liangyuanpeng 可以尝试一下 json 数据文件导入的方式，我认为要比写一个一个配置方便很多。你只需要创建一个初始博客，然后在后台导出就可以得到这个文件。然后每次新建博客的时候导入就行了。

OK thanks
