### ISSUE TITLE
备份后无法下载

### ISSUE THREAD

**Issue by daochen23** [halo-dev/halo#1302]
# 问题
在halo后台管理页面进行整站备份后无法下载
![image](https://user-images.githubusercontent.com/49630946/110232897-aa3fee00-7f5b-11eb-92e0-eb322e21f03c.png)
查看日志后发现有报错
![image](https://user-images.githubusercontent.com/49630946/110232914-ca6fad00-7f5b-11eb-8b3c-de19ea0d3278.png)
[halo-log-2021-03-07-15-35-47.txt](https://github.com/halo-dev/halo/files/6096755/halo-log-2021-03-07-15-35-47.txt)
# 配置
- halo 版本 1.4.4
- 服务器 Root用户以及halo用户均无法下载

**Comment by ruibaby** [comment]
今晚会发布一个修复版本，届时你可以在尝试一下。

**Comment by daochen23** [comment]
好的，谢谢回复

**Comment by daochen23** [comment]
你好，1.4.6版本备份还是无法下载，我看后台的实时日志没有打印错误，貌似日志不打印了

**Comment by JohnNiang** [comment]
我怀疑不是 halo 的问题。你可以描述一下部署的拓扑结构么。

**Comment by daochen23** [comment]
halo服务是部署到了阿里的服务器上，h2的数据库，cdn是又拍云

**Comment by ruibaby** [comment]
> halo服务是部署到了阿里的服务器上，h2的数据库，cdn是又拍云

建议找找又拍云的问题，可以给他们提交工单。`Connection reset by peer` ，不止一次有用户出现这种问题。

**Comment by ruibaby** [comment]
> > halo服务是部署到了阿里的服务器上，h2的数据库，cdn是又拍云
> 
> 建议找找又拍云的问题，可以给他们提交工单。`Connection reset by peer` ，不止一次有用户出现这种问题。

当然，又拍云那边每次都说是阿里云的问题，白名单之类的。

所以这不是 Halo 的问题。

**Comment by daochen23** [comment]
好的，谢谢回复

**Comment by 3293172751** [comment]
我想问下这个问题有其他的解决方案吗，备份的数据是保存在哪个位置啊。我自己是用docker部署，也是没办法下载
 @daochen23 @JohnNiang @ruibaby @johnwonder

**Comment by ruibaby** [comment]
> 我想问下这个问题有其他的解决方案吗，备份的数据是保存在哪个位置啊。我自己是用docker部署，也是没办法下载
> 
>  @daochen23 @JohnNiang @ruibaby @johnwonder 

你可以先阅读一下 <https://docs.halo.run/getting-started/prepare#工作目录>

理论上备份只需要备份工作目录即可。如果使用的 Docker，那么就备份你挂载的地址。如果还有使用外部数据库，那么再同时备份数据库。

**Comment by 3293172751** [comment]
我是直接把镜像打包，是镜像叠加后的大概1g多，然后传送到另一台服务器，但是好像另一台服务器运行这台镜像后进去网站还需要初始化~，我就很郁闷了

**Comment by ruibaby** [comment]
@3293172751 你最初创建 Docker 容器的命令可以提供一下吗？

**Comment by 3293172751** [comment]
对不起，这个我忘记了，就是很普通的拉取命令，而且有原因的是：
1. 添加了端口映射，但是这个好像不重要
2. 没有设置容器卷映射  not `-v`
3. 我发现本地（没有容器卷映射），这个里面的`root/.halo/`目录里面是空的
```cd /var/lib/docker/overlay2/c8f134fea63403f01448aab421ff9db2f3b6bf255d046827ba41d4eb774413fe/diff
```

**tmp里面有我备份的文件吗**
![image](https://user-images.githubusercontent.com/86140903/198830020-b3ac5859-ffd8-4254-9466-43530c2de37b.png)

**root/.halo里面是空的，但`exec`进入容器中的对应目录不是**
![image](https://user-images.githubusercontent.com/86140903/198830054-8b580573-d4d1-45b2-8270-cecce8cc0824.png)
> 容器内部截图如下：
> 
![image](https://user-images.githubusercontent.com/86140903/198830094-6fa85c0e-3748-4bab-90cf-312bea041e69.png)

**Comment by ruibaby** [comment]
@3293172751 你这个很显然不是常规的方式。我们文档已经标注了要将工作目录（.halo）映射到宿主机。你目前如果无法下载备份，那么只能想办法将容器内的工作目录（/root/.halo）复制出来然后恢复到新的服务器。

**Comment by 3293172751** [comment]
哦豁，对不起，那我想问下，就是是不是新的服务器只要重新pull你们的镜像，然后直接替换工作目录（/root/.halo）就可以了吗？
还是用我之前的那个叠加很多成的镜像（就是后面随着时间发展不断增大的镜像）
@ruibaby

**Comment by ruibaby** [comment]
@3293172751 

你这种情况现在推荐的做法是：

1. 先想办法将容器内的工作目录复制出来。
2. 在新服务器上按照文档挂载工作目录。 https://docs.halo.run/getting-started/install/docker

```
docker run -it -d --name halo -p 8090:8090 -v ~/.halo:/root/.halo --restart=unless-stopped halohub/halo:1.6.0
```

这里的 `~/.halo` 即你复制出来的工作目录位置。后续升级版本或者迁移服务器就只需要备份这个工作目录即可，不需要去直接操作容器。

**Comment by 3293172751** [comment]
好的谢谢你，我想问下我可以直接使用2.0版本吗，像下面这样：
```bash
docker run -it -d --name halo-next -p 8090:8090 -v ~/halo-next:/root/halo-next --restart=unless-stopped halohub/halo-dev:2.0.0-alpha.3
```

**Comment by 3293172751** [comment]
我好像重新开启了，但是没有端口
![image](https://user-images.githubusercontent.com/86140903/198837221-2581ca5e-006b-46b9-b072-261dc2d70d7d.png)

@ruibaby

**Comment by JohnNiang** [comment]
> @ruibaby 好的谢谢你，我想问下我可以直接使用2.0版本吗，像下面这样：
> 
> ```shell
> docker run -it -d --name halo-next -p 8090:8090 -v ~/halo-next:/root/halo-next --restart=unless-stopped halohub/halo-dev:2.0.0-alpha.3
> ```

不能直接使用 2.0.0-alpha.3 镜像。建议用 docker cp 命令将容器内的数据拷贝到宿主机。可参考：<https://docs.docker.com/engine/reference/commandline/cp/>。

**Comment by 3293172751** [comment]
噢噢这个我可以完成，但是我想问下 **不能直接使用 2.0.0-alpha.3 镜像。** 指的是先搭建 `1.6` 版本，后面升级到 `2.0.0-alpha.3` 吗？
@JohnNiang

**Comment by ruibaby** [comment]
> 噢噢这个我可以完成，但是我想问下 **不能直接使用 2.0.0-alpha.3 镜像。** 指的是先搭建 `1.6` 版本，后面升级到 `2.0.0-alpha.3` 吗？
> 
> @JohnNiang 

1.6 无法直接升级到 2.0。请查看 https://github.com/halo-dev/halo/releases/tag/v2.0.0-alpha.3
