### ISSUE TITLE
Token Header字段没有使用标准的OAuth 2.0认证方式是有什么特殊意义吗？

### ISSUE THREAD

**Issue by liangyuanpeng** [halo-dev/halo#1307]
标准的Bearer Token是Header字段key为`Authorization` ,value为`Bearer {token}`,  

# 动机  
当前我希望使用Prometheus抓取Halo的Metrics，但是发现需要传递Header key为`Admin-Authorization` value为token的方式,亦或者是URL后面添加`admin_token`参数, 并且token是动态的，如果标准的Bearer Token就可以很方便的处理。  

# 其他  

是否有特殊的设计意义？如果我忽略了什么文档，请提示我，Thanks.

**Comment by JohnNiang** [comment]
当初这么设计主要是为了区分到底是 admin 相关的 api 或者是 content 相关的 api。不过现在看来确实没必要区分。

**Comment by liangyuanpeng** [comment]
当前只是简单的从Header获取token，因此是否可以先简单处理取`Authorization`为key的header,然后将value去除`Bearer `的方式来支持`Bearer {token}`这种方式发送token的需求

**Comment by JohnNiang** [comment]
确实可以简单兼容这样的 header。

**Comment by ruibaby** [comment]
https://github.com/halo-dev/halo/issues/1309
