### ISSUE TITLE
默认文档分类不小心给删了，导致默认分类页面404，该如何找回原来的分类页面？

### ISSUE THREAD

**Issue by loks666** [halo-dev/halo#1308]
## 我的环境
Centos7.6 docker安装

---

## 期望行为

  可以恢复原来的分类页面

## 当前行为

  误删了默认生成的分类页面.md

**Comment by ruibaby** [comment]
不太明白你到底删除了哪个地方：

假设1：

删除了菜单的默认分类。你再加一个菜单就行了，路径为 `/categories/default`。

假设2：

删除了默认分类。去分类管理新建一个默认分类就行了。别名为 `default`。
