### ISSUE TITLE
feat: 重构 API 授权服务并新增 scope 选项

### ISSUE THREAD

**Issue by JohnNiang** [halo-dev/halo#1309]
## 概述

直到 Halo 1.4.6，Halo 一直采用非常简单的 header 传入方式进行授权接口，且授权码的数量无法扩展，授权的范围无法自定义。

## 动机

所以，需要对接口划分范围，允许授权多个授权码，且可设置授权码有效期或可随时撤销授权码。

**Comment by JohnNiang** [comment]
## 关于 Halo API Scope 的讨论

> 这里主要参考 GitLab Access Token Scope 做法：<https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html#personal-access-token-scopes>.

### Admin API

- api：对所有 API 都有读写权限
- read_api：
- attachment_api
- read_attachment
- backup_api
- read_backup
- category_api
- read_category
- journal_comment_api
- read_journal_comment
- journal_api
- read_journal
- link_api
- read_link
- read_log
- mail_api
- menu_api
- read_menu
- option_api
- read_option
- photo_api
- read_photo
- post_comment_api
- read_post_comment
- post_api
- read_post
- sheet_comment_api
- read_sheet_comment_api
- sheet_api
- read_sheet
- static_storage_api
- read_static_storage
- read_statistics
- tag_api
- read_tag
- theme_api
- read_theme
- user_api
- read_user

### Portal（Content）API

- api: 对所有 API 都有读写权限
- read_api
- read_archive
- read_journal
- read_link
- read_menu
- read_option
- read_photo
- read_sheet
- read_statistic
- read_tag
- read_theme
- read_user

以上为我整理的 API scope，粒度比较细，不一定符合具体的使用场景。所以还需要大家的意见和建议。

@ruibaby @guqing @LIlGG

**Comment by ruibaby** [comment]
假设的场景：

1. 创建微信小程序，这时候我们可以创建一个可以访问所有 Content API 的 access token。
2. 我们提供一些三方应用的扩展，比如 Chrome 插件，这个插件的用途是设置 api 地址和 access token，可以用来保存内容到博客的日志中，这个时候可以建一个仅访问 Admin API 中创建日志接口的 access token。

**Comment by LIlGG** [comment]
1. api - 获取所有 API 的权限，admin
2. read_content - 对非 admin 信息有读的权限
3. read_user - 对用户有读的权限（为多用户考虑）
4. read_xxx - 对 cms 内容有读的权限，例如小程序
5. write_xxx - 对 cms 内容有写的权限，例如第三方写文章，写日志
6. upload_xxx - 文件上传权限

**Comment by ruibaby** [comment]
是否可以根据 crud 来做 scope，比如：

admin api:

- PostController
   - read
   - write
   - delete
   - update

**Comment by JohnNiang** [comment]
> 是否可以根据 crud 来做 scope，比如：
> 
> admin api:
> 
> * PostController
>   
>   * read
>   * write
>   * delete
>   * update

这样的 Scope 会不会太细了呢。或者说定义成这样有什么明显的好处么？

**Comment by ruibaby** [comment]
> 这样的 Scope 会不会太细了呢。或者说定义成这样有什么明显的好处么？

@JohnNiang 分成 read 和 write 也行。

**Comment by JohnNiang** [comment]
For the first implementation, we will only provide access token generation, distinguish between content APIs and admin APIs, and have no read and write scope set.

**Comment by JohnNiang** [comment]
Inspired from GitLab:

```sql
CREATE TABLE personal_access_tokens (
    id integer NOT NULL,
    user_id integer NOT NULL,
    name character varying NOT NULL,
    revoked boolean DEFAULT false,
    expires_at date,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    scopes character varying DEFAULT '--- []'::character varying NOT NULL,
    impersonation boolean DEFAULT false NOT NULL,
    token_digest character varying,
    expire_notification_delivered boolean DEFAULT false NOT NULL,
    last_used_at timestamp with time zone,
    after_expiry_notification_delivered boolean DEFAULT false NOT NULL
);
```
