### ISSUE TITLE
请问一下为什么安装了halo后远程拉取主题以及更新主题都会报连接超时网络错误，上传附件评论都可以

### ISSUE THREAD

**Issue by xiazhaoxiao** [halo-dev/halo#1310]
环境：
系统：centos8.2
版本：1.4.6
数据库：H2 1.4.197 (2018-03-18)
运行模式：production
User Agent：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36
错误信息
![image](https://user-images.githubusercontent.com/40377520/110735480-d6fa4b00-8264-11eb-9088-ba016fb2ee41.png)

![image](https://user-images.githubusercontent.com/40377520/110735556-fd1feb00-8264-11eb-8241-7a75a5e4baeb.png)

**Comment by xiazhaoxiao** [comment]
nginx配置都和官网上写的一样

**Comment by ruibaby** [comment]
@xiazhaoxiao 可能是由于你的服务器是国内的，访问 Github 超时了。https://bbs.halo.run/d/1292-halo-146/2

**Comment by xiazhaoxiao** [comment]
> @xiazhaoxiao可能是由于你的服务器是国内的，访问Github上超时了。https://bbs.halo.run/d/1292-halo-146/2

感谢您的答复，问题已经解决，的确是这个问题
