### ISSUE TITLE
关于全局绝对路径

### ISSUE THREAD

**Issue by cetr** [halo-dev/halo#1312]
## 我的环境

version: 1.4.6

## 当前行为

当后台开启全局绝对路径后导致数据库也会将一部分地址存储为绝对路径，如将附件里的图片添加到相册后，相册表里的图片地址为绝对路径，这就导致更改域名后所有相册图片全部失效

## 期望行为

应当无论开不开启全局绝对路径，数据库都存储相对路径，然后开启时向前端输出绝对路径

**Comment by ruibaby** [comment]
此问题已过时。

/close
