### ISSUE TITLE
feat: content api中分类接口是否可以添加一个文章数属性

### ISSUE THREAD

**Issue by fuzui** [halo-dev/halo#1314]
## 概述
content api的分类列表及详情中添加文章数属性。

## 动机
目前分类接口返回结果中有分类名、描述、封面图属性，当我在扩展应用中(例如小程序)想要为分类列表中单独提出一个界面，只有这三个属性显示的有些单调。

## 详细解释
分类列表及详情中增加文章数(该分类下的文章数)，如果可以的话希望还有个访问数~

**Comment by ruibaby** [comment]
文章数可以。分类访问数，目前做不到。

**Comment by fuzui** [comment]
感谢~~
（访问数是想要分类下文章的总访问，有文章数也足够了！）

**Comment by ruibaby** [comment]
发现分类列表的接口是可以获取到文章数的。你需要传一个参数 `?more=true`。

**Comment by fuzui** [comment]
收到，感谢！
