### ISSUE TITLE
运行成功后，启用主题报404

### ISSUE THREAD

**Issue by tuanzi-ne** [halo-dev/halo#1316]
运行成功后，安装完主题，启用主题，然后访问报404，请问是什么问题？[](url)
![83A236B881024C6C73EF29F000EB8E92](https://user-images.githubusercontent.com/50617712/111178218-e3283480-85e5-11eb-9f6d-0c8cf280ba4d.jpg)
![QQ20210315-232453](https://user-images.githubusercontent.com/50617712/111178239-e6bbbb80-85e5-11eb-89d0-228367b612eb.png)

**Comment by ruibaby** [comment]
请问所有主题都是这样吗？请提供一下日志。

**Comment by tuanzi-ne** [comment]
只有默认自带的主题是能用的，其他安装的都404。没有报错信息
![image](https://user-images.githubusercontent.com/50617712/111228955-0cfe4d00-8620-11eb-9c83-192cfe69fcca.png)

**Comment by ruibaby** [comment]
你是通过什么方式安装的呢

**Comment by tuanzi-ne** [comment]
下载的zip包，然后下载的默认主题。想换其他主题就在后台管理端添加了主题包，然后启用就404了

**Comment by ruibaby** [comment]
无法判断是什么原因导致的，你可以先下载我们构建好的 jar 包试试。

**Comment by tuanzi-ne** [comment]
构建好的jar包可以。下的源码不行，不知道为啥

**Comment by JohnNiang** [comment]
请开启 debug 模式在 IDEA 中启动。
