### ISSUE TITLE
feat: 开启全站CDN后 文章访问数不正确

### ISSUE THREAD

**Issue by xun404** [halo-dev/halo#1319]
## 动机

请求数以被访问的接口为准；也为日后静态话做准备

## 详细解释

在使用CDN对全站静态加速后，会导致访问数不正确，希望可以增加统计API，单独统计。
类似百度统计、google统计的嵌入方式，CDN对部分接口做忽略缓存策略

**Comment by ruibaby** [comment]
请问是哪里的访问数不正确？

**Comment by xun404** [comment]
> 请问是哪里的访问数不正确？

我是使用了CDN全站加速，实际访问时并不会到服务上，导致的访问数不正确。

**Comment by ruibaby** [comment]
明白了，我们会在 1.5.x 考虑此特性。

**Comment by ruibaby** [comment]
目前已经在 2.0 添加了 `halo-tracker.js` 来统计访问信息，可参考 https://github.com/halo-dev/halo/pull/2476

已经可以在 2.0.0-alpha.1 体验。<https://github.com/halo-dev/halo/releases/tag/v2.0.0-alpha.1>
