### ISSUE TITLE
限流问题

### ISSUE THREAD

**Issue by lnsane** [halo-dev/halo#1329]
https://github.com/halo-dev/halo/blob/e6b32ac8c2be431f2b095425bf75a97a4c939f8a/src/main/java/run/halo/app/annotation/DisableOnCondition.java#L25

https://github.com/halo-dev/halo/blob/e6b32ac8c2be431f2b095425bf75a97a4c939f8a/src/main/java/run/halo/app/aspect/DisableOnConditionAspect.java#L35-L43

貌似我看了这个注解的相关逻辑和切面好像没有开启呀

请问该注解目前存在的意义是什么？

**Comment by ruibaby** [comment]
这是我们在演示环境禁用部分接口用的。

https://github.com/halo-dev/halo/blob/e6b32ac8c2be431f2b095425bf75a97a4c939f8a/src/main/java/run/halo/app/aspect/DisableOnConditionAspect.java#L31

**Comment by lnsane** [comment]
> 这是我们在演示环境禁用部分接口用的。
> 
> https://github.com/halo-dev/halo/blob/e6b32ac8c2be431f2b095425bf75a97a4c939f8a/src/main/java/run/halo/app/aspect/DisableOnConditionAspect.java#L31

谢谢


https://github.com/halo-dev/halo/blob/e6b32ac8c2be431f2b095425bf75a97a4c939f8a/src/main/java/run/halo/app/cache/lock/CacheLock.java#L22-L46

https://github.com/halo-dev/halo/blob/e6b32ac8c2be431f2b095425bf75a97a4c939f8a/src/main/java/run/halo/app/cache/lock/CacheLockInterceptor.java#L81

https://github.com/halo-dev/halo/blob/e6b32ac8c2be431f2b095425bf75a97a4c939f8a/src/main/java/run/halo/app/controller/admin/api/AdminController.java#L58-L71

默认 5s 的全局缓存锁 没有考虑根据IP访问次数动态缩短时间吗？
我看了下好像没有动态时间的逻辑
冒失也没有设置白名单的功能~

**Comment by JohnNiang** [comment]
> > 这是我们在演示环境禁用部分接口用的。
> > https://github.com/halo-dev/halo/blob/e6b32ac8c2be431f2b095425bf75a97a4c939f8a/src/main/java/run/halo/app/aspect/DisableOnConditionAspect.java#L31
> 
> 谢谢
> 
> https://github.com/halo-dev/halo/blob/e6b32ac8c2be431f2b095425bf75a97a4c939f8a/src/main/java/run/halo/app/cache/lock/CacheLock.java#L22-L46
> 
> https://github.com/halo-dev/halo/blob/e6b32ac8c2be431f2b095425bf75a97a4c939f8a/src/main/java/run/halo/app/cache/lock/CacheLockInterceptor.java#L81
> 
> https://github.com/halo-dev/halo/blob/e6b32ac8c2be431f2b095425bf75a97a4c939f8a/src/main/java/run/halo/app/controller/admin/api/AdminController.java#L58-L71
> 
> 默认 5s 的全局缓存锁 没有考虑根据IP访问次数动态缩短时间吗？
> 我看了下好像没有动态时间的逻辑
> 冒失也没有设置白名单的功能~

我们会参考 https://github.com/spring-cloud/spring-cloud-gateway/tree/master/spring-cloud-gateway-server/src/main/java/org/springframework/cloud/gateway/filter/ratelimit 实现。
