### ISSUE TITLE
halo系统升级后数据丢失

### ISSUE THREAD

**Issue by moon2008** [halo-dev/halo#1338]

**Comment by moon2008** [comment]
今天我将halo博客系统更新后，发现之前的数据全部丢失了，我只是重新拉了一下配置文件，不知道应当如何找回之前的数据

**Comment by JohnNiang** [comment]
请详细告知一下更新步骤。

**Comment by moon2008** [comment]
应该是不一致的，我无法使用/h2-console查看我的数据库数据

**Comment by ruibaby** [comment]
> > 请详细告知一下更新步骤。
> 
> 你好，我是按照文档步骤进行的，但是我发现我在halo用户目录下和root用户目录下具有两套.halo文件

有用到 systemd 吗？ systemd 是否指定了 USER。

**Comment by moon2008** [comment]
> > > 请详细告知一下更新步骤。
> > 
> > 
> > 你好，我是按照文档步骤进行的，但是我发现我在halo用户目录下和root用户目录下具有两套.halo文件
> 
> 有用到 systemd 吗？ systemd 是否指定了 USER。

是的，我使用了守护进程，但是没有具体指定USER

**Comment by ruibaby** [comment]
> > > > 请详细告知一下更新步骤。
> > > 
> > > 
> > > 你好，我是按照文档步骤进行的，但是我发现我在halo用户目录下和root用户目录下具有两套.halo文件
> > 
> > 
> > 有用到 systemd 吗？ systemd 是否指定了 USER。
> 
> 是的，我使用了守护进程，但是没有具体指定USER

指定 USER 字段为 halo，执行 service halo restart 应该就可以解决此问题。

**Comment by moon2008** [comment]
> > > > > 请详细告知一下更新步骤。
> > > > 
> > > > 
> > > > 你好，我是按照文档步骤进行的，但是我发现我在halo用户目录下和root用户目录下具有两套.halo文件
> > > 
> > > 
> > > 有用到 systemd 吗？ systemd 是否指定了 USER。
> > 
> > 
> > 是的，我使用了守护进程，但是没有具体指定USER
> 
> 指定 USER 字段为 halo，执行 service halo restart 应该就可以解决此问题。

你好，是我说错了，我的USER已经指定过了，主要区别就是我使用的管理员用户名密码和之前不一样了

**Comment by ruibaby** [comment]
@moon2008 那你就分别用 halo 和 root 启动一下看看，看看到底哪个账户是你使用的，然后整理一下 .halo 目录。

**Comment by moon2008** [comment]
> @moon2008 那你就分别用 halo 和 root 启动一下看看，看看到底哪个账户是你使用的，然后整理一下 .halo 目录。
我比较了一下halo.mv.db文件，然后我发现在root目录下的.halo.bak/.halo/db目录中的数据库是我应该使用的数据，我应当把.halo.back中的.halo文件直接覆盖掉现在root下的.halo文件吗？

**Comment by ruibaby** [comment]
> > @moon2008 那你就分别用 halo 和 root 启动一下看看，看看到底哪个账户是你使用的，然后整理一下 .halo 目录。
> > 我比较了一下halo.mv.db文件，然后我发现在root目录下的.halo.bak/.halo/db目录中的数据库是我应该使用的数据，我应当把.halo.back中的.halo文件直接覆盖掉现在root下的.halo文件吗？

可以试试，做好备份。

**Comment by moon2008** [comment]
> > > @moon2008 那你就分别用 halo 和 root 启动一下看看，看看到底哪个账户是你使用的，然后整理一下 .halo 目录。
> > > 我比较了一下halo.mv.db文件，然后我发现在root目录下的.halo.bak/.halo/db目录中的数据库是我应该使用的数据，我应当把.halo.back中的.halo文件直接覆盖掉现在root下的.halo文件吗？
> 
> 可以试试，做好备份。

已经成功了，非常感谢，主要解决方法是把需要的.halo文件放到用户根目录下，然后systemd配置文件的USER指向该用户
最后我还想问两个问题：
1、具体是如何通过systemd配置实现对.halo文件的访问的呢？
2、我使用的系统是centOS，我对halo用户赋予了管理员权限，但是相关权限仍然受限制。

**Comment by ruibaby** [comment]
1. USER 字段指定之后会使用指定的用户运行 Halo，而 Halo 的工作目录又是放在运行用户的用户目录的。
2. 什么权限？如果是按照文档创建的 halo 账户，应该是不会有问题的。
