### ISSUE TITLE
后台文章页面只显示10篇

### ISSUE THREAD

**Issue by xmengnet** [halo-dev/halo#1340]
如题，后台的文章页面只能显示十篇文章，不能翻页，选择每页显示的文章数目为20也没作用，请问怎么解决啊！

**Comment by ruibaby** [comment]
- https://github.com/halo-dev/halo/issues/844
- https://github.com/halo-dev/halo-admin/issues/253

**Comment by xmengnet** [comment]
> - https://github.com/halo-dev/halo/issues/844
> - https://github.com/halo-dev/halo-admin/issues/253

好的，非常感谢！
