### ISSUE TITLE
小工具导入hexo的markdown出错了

### ISSUE THREAD

**Issue by MaiSR9527** [halo-dev/halo#1344]
![屏幕截图 2021-04-08 220416](https://user-images.githubusercontent.com/38725713/114041504-2d37c980-98b7-11eb-8269-01a9259cf475.png)最新的1.47版本

**Comment by ruibaby** [comment]
已经修复，等待下个版本发布。https://github.com/halo-dev/halo-admin/issues/310

**Comment by MaiSR9527** [comment]
好的，请问什么时候发布。刚想体验提下halo的，想把hexo的文章转移过去

**Comment by ruibaby** [comment]
你可以先使用 1.4.5 版本。
