### ISSUE TITLE
添加菜单时，会把博客的域名也加上，导致无法访问

### ISSUE THREAD

**Issue by liaozan** [halo-dev/halo#1346]
## 我的环境

---

## 错误日志

---

**Comment by JohnNiang** [comment]
希望能提供更详细的信息。

**Comment by JohnNiang** [comment]
我发现你添加的菜单链接出现了问题：`https://blog.yuanbing.top/https://blog.yuanbing.top/categories`。添加菜单路径时请直接设置为：`/categories` 即可。

**Comment by liaozan** [comment]
> 我发现你添加的菜单链接出现了问题：`https://blog.yuanbing.top/https://blog.yuanbing.top/categories`。添加菜单路径时请直接设置为：`/categories` 即可。

并不是，这个菜单路径是批量添加的
![image](https://user-images.githubusercontent.com/26990889/114149607-ad107300-994d-11eb-9611-d7cea459f6cf.png)
传到后台`run.halo.app.controller.admin.api.MenuController#updateBatchBy`时带上了域名前缀

**Comment by ruibaby** [comment]
这是主题的问题，建议去对应仓库提交 issue。https://github.com/CodeLunatic/halo-theme-simple-bootstrap

**Comment by liaozan** [comment]
这个和主题有什么关系？不懂，明明是在后台管理里操作的，拉取的数据也都是从接口返回的，怎么还扯到主题了？

**Comment by ruibaby** [comment]
https://github.com/CodeLunatic/halo-theme-simple-bootstrap/blob/30cb9b4c4baa9ef90b6a819ae8fea86d0faffb9c/module/navbar.ftl#L24

改为：

```
<a class="nav-link" href="${menu.url!}" target="${menu.target!}">
```

应该就可以解决你的问题。

**Comment by liaozan** [comment]
![image](https://user-images.githubusercontent.com/26990889/114153073-8a805900-9951-11eb-9149-5f66ece44a23.png)
![image](https://user-images.githubusercontent.com/26990889/114153217-ab48ae80-9951-11eb-8f61-2c8379fe9e26.png)

**Comment by ruibaby** [comment]
这是作者为了保证菜单路径始终在 / 下所做的判断，所以不兼容全路径。实际上这个判断是有问题的。

你可以去给作者提交 issue，或者自己修改我说的那行。

**Comment by liaozan** [comment]
这么说我就懂了，存储的时候是存储的全路径，展示的时候不需要判断路径的开始，但是这个限制于批量添加。
如果我是单独添加的话，那是不是也要加上域名前缀？

**Comment by ruibaby** [comment]
> 这么说我就懂了，存储的时候是存储的全路径，展示的时候不需要判断路径的开始，但是这个限制于批量添加。
> 如果我是单独添加的话，那是不是也要加上域名前缀？

不需要，能访问就行，你可以添加为 /links 也可以写完整的路径。

**Comment by liaozan** [comment]
还有个小问题，新增菜单分组，设置新分组为默认，然后将新分组删除，默认的分组没有置为默认，导致前台看不到任何菜单
