### ISSUE TITLE
群晖docker容器启动后，使用watchtower自动更新后丢失容器

### ISSUE THREAD

**Issue by trainliang** [halo-dev/halo#1347]
## 我的环境

>  群晖docker容器启动
---

## 错误日志

> 使用watchtower自动更新后丢失容器，暂无错误信息提示
---

## 期望行为

> 希望使用自动更新工具自动更新halo， 怀疑halo不适配watchtower更新方式
## 当前行为

> 使用watchtower自动更新后丢失容器,使用的是cleanup模式

**Comment by JohnNiang** [comment]
有可能容器启动失败了，你可以看看 watchtower 的日志。

**Comment by trainliang** [comment]
不知道为什么，我的gitea和nexus等容器都更新正常名单时halo更新错误好几次了，halo更新失败导致的宕机好几次了

**Comment by JohnNiang** [comment]
你可以检查一下 halo 日志文件：`~/.halo/logs/spring.log`。

**Comment by trainliang** [comment]
log里边没有什么东西，就剩启动正常的了，昨天的我也看了没有东西，我这边建议docker环境测试一下，我的watchtower的启动代码是 -cleanup -s 0 20 3 * * *

**Comment by JohnNiang** [comment]
建议你提供一下 docker 启动命令，以及 watchtower 启动命令，以及对 halo 容器的设置。尽可能详细，这样我们才能够正确复现。

**Comment by JohnNiang** [comment]
以及对应的版本信息。

**Comment by trainliang** [comment]
问题发生在版本升级后，所以镜像为当前latest，机器系统为群晖ds3617x，docker版本:Docker version 18.09.8, build bfed4f5，
群晖界面启动的容器，配置了文件映射：（/docker/halo/data：/root/.halo）端口映射（38091： 8090），开启自动启动，限制1g内存，最终结果是更新后容器丢失，数据库使用的是外部的mysql

**Comment by ruibaby** [comment]
@trainliang 加了 rm 参数吗？怎么会发生容器被删的情况呢。

**Comment by trainliang** [comment]
> @trainliang 加了 rm 参数吗？怎么会发生容器被删的情况呢。

没有单独加rm的，使用的是watchtower 的更新有，代码有-cleanup旧镜像，只有这些，watchtower 不能拉起问题
