### ISSUE TITLE
feat: 可配置用户默认头像的avatar服务器

### ISSUE THREAD

**Issue by trainliang** [halo-dev/halo#1348]
## 概述

希望用户默认头像可以配置avatar服务器

## 动机
头像服务器大陆被墙

**Comment by ruibaby** [comment]
1.4.8 已经支持。

**Comment by trainliang** [comment]
只找到了头像的配置地址，请问首页用户头像服务器地址在哪个菜单配置的

**Comment by ruibaby** [comment]
> 只找到了头像的配置地址，请问首页用户头像服务器地址在哪个菜单配置的

你说的是评论还是博主的头像呢？

博主的头像可以在个人资料修改。

**Comment by trainliang** [comment]
博主的头像，我默认不也是avatar头像么，看代码文档里，不知道为啥只改了评论的

**Comment by ruibaby** [comment]
> 博主的头像，默认不也是avatar头像么，看代码文档里，不知道为啥只改了评论的

那确实是只针对评论头像的修改。个人资料那个还是默认的 Gravatar 源。暂时你可以考虑手动上传头像。

**Comment by trainliang** [comment]
嗯，后边也建议吧版本号打在dockerfile里，类似mysql

**Comment by ruibaby** [comment]
> 嗯，后边也建议吧版本号打在dockerfile里，类似mysql

建议新提交一个 issue 详细描述一下，我们方便跟踪，这个 issue 我就先关闭了。

**Comment by trainliang** [comment]
那这个issus里的 博主的默认头像地址服务器 会用上配置的地址么，cn服务器国内不大能用了
