### ISSUE TITLE
feat: 建议附件存储使用时间戳命名，方便附件存储管理

### ISSUE THREAD

**Issue by trainliang** [halo-dev/halo#1349]
## 概述

目前的附件存储直接使用名称存储，不方便s3存储，而且没有按照日期分文件夹，可能路径有文字，有URI编码问题，不方便后期维护和使用

**Comment by ruibaby** [comment]
附件存储会重构，这些我们会考虑进去。

**Comment by zhixiangyuan** [comment]
> 附件存储会重构，这些我们会考虑进去。

如果用有规律的名字，那么可能会有安全漏洞，别人能够自由爬取

**Comment by ruibaby** [comment]
> > 附件存储会重构，这些我们会考虑进去。
> 
> 
> 
> 如果用有规律的名字，那么可能会有安全漏洞，别人能够自由爬取

现在没有规律吧。

**Comment by trainliang** [comment]
> > > 附件存储会重构，这些我们会考虑进去。
> > 
> > 
> > 如果用有规律的名字，那么可能会有安全漏洞，别人能够自由爬取
> 
> 现在没有规律吧。

用 年月日文件夹/时间戳 基本不会被爆破了吧

**Comment by zhixiangyuan** [comment]
现在是固定前缀 + 时间戳的模式，如果我想拉别人的所有图片只需要看一下固定前缀是什么，然后写个程序遍历时间戳就能将指定 halo 博客的所有图片全部拉出来，如果这些图片里面涉及到了别人的隐私的话就会出现安全漏洞
