### ISSUE TITLE
前端内容不同步

### ISSUE THREAD

**Issue by Cui-Yusong** [halo-dev/halo#1355]
## 我的环境

最新版本：1.4.8

---

问题是：在管理端对文章内容进行更改后，用户端看到的内容 在预览界面并没有发生改变，只有点进去这篇文章，才会看到改变后的内容。

测试： 在管理端写一篇文章，文章内容是 同步。发布后，在用户端的预览内容是 同步，此时并没有问题。
但是，在管理端进行更改后，改为：测试当前更改后是否同步。发现此时 在用户端，预览时的内容还是 同步，并没有变化。只有点进该文章，才能看到发生的变化。

![image](https://user-images.githubusercontent.com/45391593/115175442-8f859b00-a0fd-11eb-8aa6-e8afeb597c8c.png)
![image](https://user-images.githubusercontent.com/45391593/115175451-93b1b880-a0fd-11eb-990f-35645e97c59c.png)
内容并不一样

**Comment by LIlGG** [comment]
在最外部查看到的是摘要而不是详细内容，属于正常逻辑，不属于 bug。对于摘要仅仅只会在第一次文章渲染时自动生成，你可以在后续更新文章时，手动更改摘要。
