### ISSUE TITLE
1.4.8版本，编写文章，内容超过一定长度出现滚动条以后，富文本工具栏消失

### ISSUE THREAD

**Issue by jeffxjh** [halo-dev/halo#1356]
## 我的环境
版本：1.4.8
数据库：H2 1.4.197 (2018-03-18)
运行模式：production
User Agent：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36

---

## 错误日志

---

## 期望行为
在超过长度后，显示文本框内的滚动条

## 当前行为
在超过长度后，显示网页滚动条
![image](https://user-images.githubusercontent.com/44387640/115209929-a8f40a80-a130-11eb-94fd-7e3a6a04a791.png)

**Comment by ruibaby** [comment]
新的编辑器会解决此问题。预计 1.5.0 发布。
