### ISSUE TITLE
升级后，服务无法正常启动

### ISSUE THREAD

**Issue by DavenAaron** [halo-dev/halo#1358]
![image](https://user-images.githubusercontent.com/20857689/115393886-c26e8280-a214-11eb-9b5e-3b6e4f905ea1.png)

**Comment by DavenAaron** [comment]
启动方式为docker启动

**Comment by ruibaby** [comment]
能否提供 ~/.halo/logs/spring.log 文件。

**Comment by DavenAaron** [comment]
已经解决 ， 感谢

**Comment by DavenAaron** [comment]
程序没有问题
