### ISSUE TITLE
CORS跨域资源共享漏洞

### ISSUE THREAD

**Issue by HYWZ36** [halo-dev/halo#1361]

**Comment by ruibaby** [comment]
> 攻击者通过简易手段侦听捕捉管理员请求数据包，获得了Admin-Authorization字段信息是【ad9e7f0f160c4654a9e8b98e62e24b5d】

你好，我们已经对此问题详细讨论过了。我们想知道在真实场景下，攻击者如果简易的拿到 `Admin-Authorization`。

**Comment by ruibaby** [comment]
你好，还有后续补充吗？
