### ISSUE TITLE
feat: 使用 content api 开发主题增加非 hash 路由支持

### ISSUE THREAD

**Issue by zhixiangyuan** [halo-dev/halo#1362]
## 概述

使用 content api 开发主题增加非 hash 路由支持

## 动机

hash 会造成原生 hash 跳转功能不可用

## 解决方案

增加一个 url 前缀，将带有该前缀的 url 请求转发到 index.ftl 即可。

例如使用 front 当作前缀，主题实现者在设置前段路由时带上 front 前缀，那么访问的路径就是 /front/**

**Comment by ruibaby** [comment]
我不认为这是一个好的方案。

**Comment by zhixiangyuan** [comment]
> 我不认为这是一个好的方案。

那现在有没有比较好的解决方案，如果不解决这个问题前端实现 hash 跳转需要使用 js 实现，成本很高

**Comment by ruibaby** [comment]
不太明白你说的 hash 跳转是什么意思。

**Comment by zhixiangyuan** [comment]
> 不太明白你说的 hash 跳转是什么意思。

比如说实现点击目录跳转到指定位置的时候，就是在指定的标签上打上 id=“xxxx”，然后在目录上加上 url="#xxxx"，这样点击目录就会自动跳转到指定的位置，但是现在使用 ’#‘ 做为前端路由，那么点击目录就会跳转页面。

今天在集成 halo-comment 的时候同样发现有这个问题，评论模块本身使用 ‘#’ 来跳到指定的楼层，但是由于现在 ‘#’ 被路由占用了，所以点击就变成了跳转页面

**Comment by ruibaby** [comment]
明白了，我们考虑下这个问题，晚点给你回复。

**Comment by zhixiangyuan** [comment]
> 明白了，我们考虑下这个问题，晚点给你回复。

好的，感谢🙏

**Comment by ruibaby** [comment]
> @ruibaby 老哥，这个问题现在有结论了么

独立部署可能是目前最好的方案。
