### ISSUE TITLE
在MAC下面复制WORD的内容，粘贴会变成图片

### ISSUE THREAD

**Issue by zsinba** [halo-dev/halo#1363]
## 我的环境

![image](https://user-images.githubusercontent.com/890157/116582586-1b8e9280-a948-11eb-8c49-21f0ccafcf02.png)

---

## 错误日志

无
---

## 期望行为
从Word复制过来的内容，直接粘的时候，能恢复文本和图片。

## 当前行为
从WOrd复制过来的， CTRL+V的时候，整个WORD变成了图片。

**Comment by ruibaby** [comment]
目前的编辑器不足以支持你的需求。

**Comment by zsinba** [comment]
xiexie
