### ISSUE TITLE
后台管理界面菜单新窗口打开，链接错误，404

### ISSUE THREAD

**Issue by fyljp** [halo-dev/halo#1366]
## 我的环境

版本：1.4.8
数据库：H2 1.4.197 (2018-03-18)
运行模式：production
User Agent：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36

---

## 期望行为

新窗口中打开相对应管理页面

## 当前行为

跳转至网页前台，浏览器地址错误。

例如：点击仪表盘

本应前往： /后台目录/index.html#/dashboard

最终前往：/dashboard

**Comment by ruibaby** [comment]
可能是你 Nginx 加了路径重写导致的，可以检查一下。

**Comment by ruibaby** [comment]
> > 可能是你 Nginx 加了路径重写导致的，可以检查一下。
> 
> 鼠标左键点击本窗口打开没问题，中键点击新窗口打开就会出现问题，好神奇

我这边没有问题。
