### ISSUE TITLE
翻譯成西班牙文

### ISSUE THREAD

**Issue by jojeda-four-id** [halo-dev/halo#1367]
您好，我在拉丁美洲，我想使用您的CMS。 可以將其翻譯成西班牙語翻譯成西班牙語

Hola, me encuentro en latinoamérica y me gustaría utilizar su CMS. es posible traducirlo al idioma Español

**Comment by ruibaby** [comment]
We have plans to do localization support, but we haven't started development yet, we need to wait for a while.

https://github.com/halo-dev/halo/issues/546

**Comment by jojeda-four-id** [comment]
谢谢您的回复，我会很专心的。
问候和感谢

------------------------------------------------------

Thanks for your response, I will be attentive.
Greetings and thanks
