### ISSUE TITLE
feat: 提交评论取消对邮箱字段的非空验证

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#1369]
## 概述

RT

## 动机

对于评论者来说，邮箱确实不是必要的。目前邮箱也仅用于 Gravatar 头像和消息通知。

## 详细解释

无

**Comment by 1171-jpg** [comment]
您好，我查了下api是在 PostController.commetnst里。现有的RequestBody PostCommentParam是继承于BaseCommentParam的，我的修改思路是新建一个抽象类去实现接口，在实现时取消对@email的验证。然后让POSTCommentParam去继承这个新的抽象类。这样也不会对其他的api产生影响。不知道可不可以这样，谢谢！

**Comment by ruibaby** [comment]
> 您好，我查了下api是在 PostController.commetnst里。现有的RequestBody PostCommentParam是继承于BaseCommentParam的，我的修改思路是新建一个抽象类去实现接口，在实现时取消对@email的验证。然后让POSTCommentParam去继承这个新的抽象类。这样也不会对其他的api产生影响。不知道可不可以这样，谢谢！

其实都可以取消，我们需要讨论一下。

**Comment by 1171-jpg** [comment]
好的，如果都取消的话就不用这么麻烦了，在base里面取消@email就行了

**Comment by guqing** [comment]
> > 您好，我查了下api是在 PostController.commetnst里。现有的RequestBody PostCommentParam是继承于BaseCommentParam的，我的修改思路是新建一个抽象类去实现接口，在实现时取消对@email的验证。然后让POSTCommentParam去继承这个新的抽象类。这样也不会对其他的api产生影响。不知道可不可以这样，谢谢！
> 
> 其实都可以取消，我们需要讨论一下。@johnniang @LIlGG @guqing 

我感觉可以取消  如果为空默认生成称呼和头像

**Comment by Smart-Boy-me** [comment]
支持取消！

**Comment by JohnNiang** [comment]
如果有人能够有意愿提交 Pull Request 就更好了。: P

**Comment by jerry-shao** [comment]
PR: https://github.com/halo-dev/halo/pull/1535

**Comment by lijinghuatongxue** [comment]
但是前端不填写邮箱和昵称，依旧提交不了评论的？

**Comment by Smart-Boy-me** [comment]
您好，这里是王LT同学。您的来信我已收到，我会尽快回复！谢谢！

**Comment by JohnNiang** [comment]
> 但是前端不填写邮箱和昵称，依旧提交不了评论的？

目前官方评论组件还没有去除邮箱验证。不过可以试试非官方评论组件：<https://github.com/cetr/halo-comment-yu>。

**Comment by LAGQWQ** [comment]
> 您好，这里是王LT同学。您的来信我已收到，我会尽快回复！谢谢！

考古 2.0还不更新

**Comment by Smart-Boy-me** [comment]
您好，这里是王LT同学。您的来信我已收到，我会尽快回复！谢谢！
