### ISSUE TITLE
腾讯云 CloudBase

### ISSUE THREAD

**Issue by Stonewalling** [halo-dev/halo#1370]
- 我已经安装了最新版的 Halo
  - 我已经搜索了已有的 Issues 列表中有关的信息
  - 我已经搜索了论坛中有关的信息：https://bbs.halo.run
  - 我已经阅读了 Halo 的 FAQ：https://docs.halo.run/user-guide/faq

## 我的环境

版本：1.4.8
数据库：H2 1.4.197 (2018-03-18)
运行模式：production
User Agent：Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
---

## 错误日志

访问网址显示404，多刷几次它就又能正常访问，怀疑是腾讯云的问题，请求大佬给个方向，没用过腾讯云

---

## 当前行为

访问网址显示404，多刷几次它就又能正常访问，怀疑是腾讯云的问题，请求大佬给个方向，没用过腾讯云
![image](https://user-images.githubusercontent.com/21361701/117922339-e0ffff00-b324-11eb-9c49-b127003c6739.png)

**Comment by Stonewalling** [comment]
> 能提供一下访问地址吗？你可以用 `<!-- 你的链接 -->` 来隐藏你的网址。

`<!-- https://blog-7g6cwfvj29b55c90-1304973821.ap-guangzhou.app.tcloudbase.com/ -->`

**Comment by ruibaby** [comment]
好像没有出现你说的问题。

**Comment by Stonewalling** [comment]
> 好像没有出现你说的问题。
是这样的，如果长时间不访问，下次访问的时候就会404，感觉像是腾讯云睡眠了一样，刷新几次后，他就又正常了

**Comment by Stonewalling** [comment]
多次刷新，一开始显示404，再刷新几次变成400，最后再刷新几次就能看到页面了

**Comment by ruibaby** [comment]
> 多次刷新，一开始显示404，再刷新几次变成400，最后再刷新几次就能看到页面了

应该是有某种休眠机制，晚点我去看看。

**Comment by zuoercc** [comment]
我用的最简单的办法-让他一直保持有流量，就是每隔5分钟自动打开一次网页保持不休眠，然后腾讯云开发的cpu按量付费账单感动到我哭
