### ISSUE TITLE
拷贝整个.halo文件，在新的服务器启动后，第一天没报错，第二天打不开仪表盘

### ISSUE THREAD

**Issue by chenguod** [halo-dev/halo#1374]
我的环境版本：1.4.8
数据库：H2 1.4.197 (2018-03-18)
运行模式：production
User Agent：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36

**Comment by ruibaby** [comment]
应该是数据库文件被破坏了，这个我们暂时无能为力。建议备份整个文件夹的时候，停止运行再备份。

**Comment by ruibaby** [comment]
[spring.log](https://github.com/halo-dev/halo/files/6488636/spring.log)

**Comment by chenguod** [comment]
收到，谢谢大佬指导




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "halo-dev/halo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月16日(星期天) 中午11:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [halo-dev/halo] 拷贝整个.halo文件，在新的服务器启动后，第一天没报错，第二天打不开仪表盘 (#1374)





 
应该是数据库文件被破坏了，这个我们暂时无能为力。建议备份整个文件夹的时候，停止运行再备份。
