### ISSUE TITLE
由于目前正在着手开发 v1.0 版本,所以暂时不处理 issues .

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#138]
RT, 在新版本中,目前已知的问题都会解决.所以请诸位有老版本的问题暂时先不要提 issues 啦.

**Comment by PerseSniper** [comment]
老版本对中文路径的支持 不太友好，希望新版本能考虑 各个环境的中文处理问题。

**Comment by ruibaby** [comment]
@PerseSniper 有什么好的建议吗？

**Comment by PerseSniper** [comment]
> @PerseSniper有什么好的建议吗？

因为看到 老版本系统文件大多数对文件的处理是采取的硬编码的方式？ 这样其实造成很多冗余代码？我提供一种思路， 将文件中的必要信息提取出来封装到一个实体类 做一个工具，比如 该实体类中 包含文件的写入路径，文件流，文件 大小，等等信息， 再提供文件处理类。 你可以参考下，我的项目中就是这样做的方便统一处理。

**Comment by JerryDtj** [comment]
反馈几个问题：

1. gradle编译时lombok会产生警告
解决方法：在src->main->java下加入lombok.config
`# This file is generated by the 'io.freefair.lombok' Gradle plugin
config.stopBubbling = true
lombok.equalsAndHashCode.callSuper=call`

2. 登录过后，重启服务器，再次刷新登录页面，jwt提示token异常，不会自动跳转登录页

3. 发表文章时，内容字段只限制450个字。

4. 在注册时，填入密码过短前段不会动态提示，只是在后段报错提示

然后在说下我自己的想法，你的博客在功能上不是很满足我的需求，我自己不是很懂freemark，然后前段代码全部都加密处理过，造成我阅读你的源码很难受，所以我打算自己用springBoot+thymleaf重构下你的代码，但是css还是用你的，同时界面上只会加入Designed by CaiCai。还望你同意。

**Comment by JohnNiang** [comment]
@JerryDtj 您好，非常感谢您提出的这些问题！

- to 1: 这个警告在代码上确实无法消除，我相信你看了源码应该会清楚；

- to 2: 最新的测试版已经解决了这个问题；

- to 3: 这个我们去排查一下；

- to 4: 这个确实是我们没有处理好，后端是有完整错误信息返回的。

最后，您指的前段代码被加密这个问题：请查看另外一个项目 <https://github.com/halo-dev/halo-admin>。源码都在这个项目里面，halo 里面的前端代码是经过这个项目 build 出来的结果。

我们采用的 `freemarker` 仅仅用于主题的制作。

希望能够解除您的疑惑。

**Comment by ruibaby** [comment]
@JerryDtj 纠正一下，你所说的 `但是css还是用你的，同时界面上只会加入Designed by CaiCai`。你说的这个是我们移植的主题，原 repo：https://github.com/hi-caicai/farbox-theme-Anatole，感谢你的反馈。

**Comment by JerryDtj** [comment]
> @JerryDtj您好，非常感谢您提出的这些问题！
> 
> * 到1：这个警告在代码上确实无法消除，我相信您看了源码应该会清楚;
> * 到2：最新的测试版已经解决了这个问题;
> * 到3：这个我们去排查一下;
> * 到4：这个确实是我们没有处理好，后端是有完整错误信息返回的。
> 
> 最后，您指的前段代码被加密这个问题：请查看另外一个项目https://github.com/halo-dev/halo-admin。源码都在这个项目里面，晕里面的前端代码是经过这个项目构建出来的结果。
> 
> 采用我们的`freemarker`仅仅用于主题的制作。
> 
> 希望能够解除您的疑惑。

问题1我已经解决了，你可以在你的代码中加入一个名为lombok.config的配置文件，内容如下：
Gradle plugin config.stopBubbling = true 

lombok.equalsAndHashCode.callSuper=call

虽然看着很不爽，至少@data的警告没了。
[源码](https://github.com/halo-dev/halo-admin )我就不看了，因为我现在已经开始重构了。
等我重构完，样式应该可以通用的，到时候欢迎添加友链、互换样式拓展。

**Comment by JohnNiang** [comment]
@JerryDtj 期待大佬的重构版本:grin:

**Comment by ruibaby** [comment]
@JerryDtj 期待大佬的重构版本:grin:

**Comment by JerryDtj** [comment]
@ruibaby @JohnNiang 两位抬举了，我只是一个基层搬砖工罢了。然后重构速度没有这么快的，毕竟还有一些别的东西在弄。重构好了，会通知两位的。
