### ISSUE TITLE
【BUG】回收站的文章可以访问

### ISSUE THREAD

**Issue by mimajiushi** [halo-dev/halo#1381]
## 我的环境

版本：1.4.8
数据库：MySQL 5.7.33-log
运行模式：production
User Agent：Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36 Edg/90.0.818.56

---

## 错误日志

无

---

## 期望行为

- 回收站的文章不可访问

## 当前行为

- 回收站的文章可访问（已刷新缓存）
- 如果私密文章进入回收站，则不用密码也能访问
![image](https://user-images.githubusercontent.com/33995610/119072692-7fbfe600-ba1e-11eb-96a3-e9dc01a4a000.png)
![image](https://user-images.githubusercontent.com/33995610/119072717-89e1e480-ba1e-11eb-816b-034050d4349f.png)

**Comment by JohnNiang** [comment]
感谢您的反馈！如果可以的话，你可以提交 PR 帮助 halo 修复此问题。

**Comment by mimajiushi** [comment]
> 感谢您的反馈！如果可以的话，你可以提交 PR 帮助 halo 修复此问题。

提交PR了

**Comment by ruibaby** [comment]
@zhixiangyuan 这貌似是因为你之前的分类加密的 pr 导致的，你取消了我们原有的通过 token 访问的方式，但是并没有提供新的方式，导致目前回收站和草稿状态的文档都可以直接通过链接访问。希望能看看这个问题。

**Comment by zhixiangyuan** [comment]
> @zhixiangyuan 这貌似是因为你之前的分类加密的 pr 导致的，你取消了我们原有的通过 token 访问的方式，但是并没有提供新的方式，导致目前回收站和草稿状态的文档都可以直接通过链接访问。希望能看看这个问题。

这个我来解

**Comment by ruibaby** [comment]
> > @zhixiangyuan 这貌似是因为你之前的分类加密的 pr 导致的，你取消了我们原有的通过 token 访问的方式，但是并没有提供新的方式，导致目前回收站和草稿状态的文档都可以直接通过链接访问。希望能看看这个问题。
> 
> 后面我看下，如果前面的 pr 没修好我后面提个 pr

那个 pr 已经 close 了，只能麻烦你看看了。

**Comment by mimajiushi** [comment]
> > > @zhixiangyuan 这貌似是因为你之前的分类加密的 pr 导致的，你取消了我们原有的通过 token 访问的方式，但是并没有提供新的方式，导致目前回收站和草稿状态的文档都可以直接通过链接访问。希望能看看这个问题。
> > 
> > 
> > 后面我看下，如果前面的 pr 没修好我后面提个 pr
> 
> 那个 pr 已经 close 了，只能麻烦你看看了。

测试用例本地、自己服务器都能过，到github上就挂了，排查不出原因，只好放弃了😂

**Comment by gerayking** [comment]
请问现在要解决的是要求回收站的文章不能访问，而使用admin的时候能访问回收站的文章吗？

**Comment by zhixiangyuan** [comment]
> @zhixiangyuan 这貌似是因为你之前的分类加密的 pr 导致的，你取消了我们原有的通过 token 访问的方式，但是并没有提供新的方式，导致目前回收站和草稿状态的文档都可以直接通过链接访问。希望能看看这个问题。

确实是这个问题，我恢复了原来从 admin 跳转时的 token，现在对于 admin 页面的访问不再做校验，对于别的请求会校验所有非公开文章。
