### ISSUE TITLE
JPA entity use Lombok may cause performance and memory consumption issues. 

### ISSUE THREAD

**Issue by CraKeyBoy** [halo-dev/halo#1383]
When working with JPA and Lombok, remember these rules:

- Avoid using @EqualsAndHashCode and @Data with JPA entities;
- Always exclude lazy attributes when using @ToString;
- Don’t forget to add @NoArgsConstructor to entities with @Builder or @AllArgsConstructor.

Reference:
- [Lombok and JPA: What Could Go Wrong?](https://dzone.com/articles/lombok-and-jpa-what-may-go-wrong)
- [lombok-hibernate-how-to-avoid-common-pitfalls](https://thorben-janssen.com/lombok-hibernate-how-to-avoid-common-pitfalls/)

**Comment by JohnNiang** [comment]
That's a great suggestion. Currently, we haven't use `Lazy Attributes` feature of JPA, and our entities don't have any composited other entities, instead we use Lombok on simple entity only. So there is no need to follow those rules now. Thanks for your suggestion.

**Comment by CraKeyBoy** [comment]
OK.
