### ISSUE TITLE
feat: 页面灰色效果

### ISSUE THREAD

**Issue by YYplus** [halo-dev/halo#1384]
## 概述

  全站变为灰色页面

## 动机

 袁老去世，很伤心想把网页变成灰色的悼念一下，发现HALO并没有这个功能，我觉得有很多和我一样的小白会需要这个功能，

## 详细解释

  很多时候会用到这个功能吧，虽然自己的博客没啥访问量，但还是想尽自己的一片心意，虽然功能很小，但意义重大，希望Halo可以多一些这种很小但很人性化的小功能，变得更易于使用，希望Halo越来越好。

**Comment by ruibaby** [comment]
```
<style>
html{
filter: grayscale(100%);
-moz-filter: grayscale(100%);
-o-filter: grayscale(100%);
-webkit-filter: grayscale(1);
}
</style>
```

添加到博客设置的自定义 head 即可。

**Comment by JohnNiang** [comment]
这个功能希望通过社区来完善。

**Comment by guqing** [comment]
使用主题雪就有设置 像这样:  https://guqing.xyz
