### ISSUE TITLE
分类的问题

### ISSUE THREAD

**Issue by sunda-blog** [halo-dev/halo#1388]
我在一级分类下添加二级分类   但是打开一级分类 下的二级分类查询不到文章
<img width="668" alt="WX20210526-110307@2x" src="https://user-images.githubusercontent.com/59949673/119596605-153dea00-be12-11eb-945f-2b7bc39d0ab6.png">
<img width="520" alt="WX20210526-110237@2x" src="https://user-images.githubusercontent.com/59949673/119596608-1707ad80-be12-11eb-9927-fcabef26cc19.png">

**Comment by ruibaby** [comment]
确实有这个问题，目前分类的分级仅仅只是在分类渲染的时候能体现出层级，但是有些逻辑上还没有做处理。我们会在后续的版本优化此问题。

**Comment by ruibaby** [comment]
duplicate in https://github.com/halo-dev/halo/issues/1136
