### ISSUE TITLE
Halo 的后台 Dashboard 在ipadOS环境下中文全部乱码

### ISSUE THREAD

**Issue by senyucci** [halo-dev/halo#1397]
## 我的环境
版本：1.4.8
数据库：H2 1.4.197 (2018-03-18)
运行模式：production
User Agent：Mozilla/5.0 (iPad; CPU OS 14_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Mobile/15E148 Safari/604.1

---

## 错误日志

---

## 期望行为
后台不乱码

## 当前行为
IOS下所有浏览器打开网站后台均乱码

![image](https://user-images.githubusercontent.com/59790687/121689355-156b0480-caf7-11eb-8daf-19ff4b455b41.png)
![image](https://user-images.githubusercontent.com/59790687/121689384-1f8d0300-caf7-11eb-8d9b-5a0b509b33a4.png)

**Comment by ruibaby** [comment]
请问你的 iPadOS 版本是？

**Comment by senyucci** [comment]
是 14.4

**Comment by senyucci** [comment]
> 请问你的 iPadOS 版本是？

是 14.4（18D52）

**Comment by senyucci** [comment]
> 请问你的 iPadOS 版本是？

已排除浏览器缘故，测试了包括safari在内的五个浏览器，后台的静态导航均乱码，其他文字没有乱码现象

**Comment by ruibaby** [comment]
你好，我们没有 iPad 设备，所以无法进行测试。请问是否有对浏览器进行过一些特殊设置？ iOS 似乎没有出现过类似的情况。之前也在 iPadOS 测试过，均无类似问题。

**Comment by senyucci** [comment]
> 你好，我们没有 iPad 设备，所以无法进行测试。请问是否有对浏览器进行过一些特殊设置？ iOS 似乎没有出现过类似的情况。之前也在 iPadOS 测试过，均无类似问题。

这是一台新机器 😂 我稍后会恢复出厂设置并继续尝试一下

**Comment by ruibaby** [comment]
> 这是一台新机器 😂 我稍后会恢复出厂设置并继续尝试一下

应该没有必要恢复出厂设置，你可以先尝试搜索一下 iPad 有没有类似问题。

**Comment by senyucci** [comment]
> > 这是一台新机器 😂 我稍后会恢复出厂设置并继续尝试一下
> 
> 应该没有必要恢复出厂设置，你可以先尝试搜索一下 iPad 有没有类似问题。

好的，十分感谢

**Comment by senyucci** [comment]
> > 这是一台新机器 😂 我稍后会恢复出厂设置并继续尝试一下
> 
> 应该没有必要恢复出厂设置，你可以先尝试搜索一下 iPad 有没有类似问题。

已找到问题所在了，我开启了全站CDN，当直接用ip+端口进入后台时一切正常

**Comment by senyucci** [comment]
> > 这是一台新机器 😂 我稍后会恢复出厂设置并继续尝试一下
> 
> 应该没有必要恢复出厂设置，你可以先尝试搜索一下 iPad 有没有类似问题。

应该是cdn那边的编码问题

**Comment by ruibaby** [comment]
> 应该是cdn那边的编码问题

那么找到解决方法了吗

**Comment by senyucci** [comment]
> > 应该是cdn那边的编码问题
> 
> 那么找到解决方法了吗
目前没有很好的解决方式，不过后台一般是写文用的，也不会通过cdn加速的域名进入，因为预览会有延迟哈哈哈，目前并不影响使用

**Comment by ruibaby** [comment]
你可以尝试在 cdn 那边屏蔽掉 /admin 路径 和 /api/admin 接口路径试试。

**Comment by senyucci** [comment]
> > 应该是cdn那边的编码问题
> 
> 那么找到解决方法了吗

该现象应该是ios系共有的现象，在全站cdn下后台部分字体会乱码

**Comment by senyucci** [comment]
> 你可以尝试在 cdn 那边屏蔽掉 /admin 路径 和 /api/admin 接口路径试试。

之前已经屏蔽过了，并没有很大的成效

**Comment by ruibaby** [comment]
> 之前已经屏蔽过了，并没有很大的成效 

理论上会有效的，可以看看 cdn 那边的屏蔽规则。
