### ISSUE TITLE
Failed to backup halo

### ISSUE THREAD

**Issue by xiaofengjue** [halo-dev/halo#1398]
## 我的环境
阿里云 Centos7.7

---

## 错误日志

```
Caused by: java.nio.file.AccessDeniedException: /tmp/halo-backup/halo-backup-2021-06-17-23-15-16--337273462.zip
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[na:na]
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[na:na]
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[na:na]
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219) ~[na:na]
	at java.base/java.nio.file.Files.newByteChannel(Files.java:371) ~[na:na]
	at java.base/java.nio.file.Files.createFile(Files.java:648) ~[na:na]
	at run.halo.app.service.impl.BackupServiceImpl.backupWorkDirectory(BackupServiceImpl.java:231) ~[classes!/:1.4.8]
	... 118 common frames omitted
```
---

## 期望行为
成功的进行整站备份

## 当前行为
前辈好，我现在用的halo-1.4.8版本，使用root运行时时候可以整站备份，但是新建halo用户，以halo身份运行halo（按照官方教程），整站备份提示Failed to backup halo，还有就是导出文档为markdown时可以导出，但是进行下载的时候，提示失败-服务器出现问题

**Comment by xiaofengjue** [comment]
用halo用户的身份在/tmp新建一个halo-backup文件夹，再全站备份没问题了，但是下载全站备份的数据，提示失败-服务器出现问题

**Comment by ruibaby** [comment]
感谢反馈，晚点我们尝试复现一下。

**Comment by ruibaby** [comment]
你好，我根据文档使用新开的服务器测试了一遍，没有发现类似问题。

![image](https://user-images.githubusercontent.com/21301288/122512276-383b7280-d03b-11eb-987f-cd2328cd119e.png)
![image](https://user-images.githubusercontent.com/21301288/122512310-438e9e00-d03b-11eb-9478-a33c67fc0780.png)
![image](https://user-images.githubusercontent.com/21301288/122512372-543f1400-d03b-11eb-9350-dd6215c8f41c.png)

建议检查一下 halo 账户的权限。

**Comment by xiaofengjue** [comment]
> 你好，我根据文档使用新开的服务器测试了一遍，没有发现类似问题。
> 
> ![image](https://user-images.githubusercontent.com/21301288/122512276-383b7280-d03b-11eb-987f-cd2328cd119e.png)
> ![image](https://user-images.githubusercontent.com/21301288/122512310-438e9e00-d03b-11eb-9478-a33c67fc0780.png)
> ![image](https://user-images.githubusercontent.com/21301288/122512372-543f1400-d03b-11eb-9350-dd6215c8f41c.png)
> 
> 建议检查一下 halo 账户的权限。

您好，感谢您的热情恢复。我创建halo用户也是根据官方文档来的`usermod  -aG wheel halo`，这么一句将halo加入了wheel用户组，使用su，输入root密码就能以root身份登陆管理。下载整站备份的时候，域名访问和ip访问返回的信息不一样，域名是失败-服务器出现问题，ip是提示：{"status":400,"message":"The one-time token does not exist or has been expired","devMessage":null,"data":"XXXXXXXXXXXXXXXX"}，我还新发现了一个bug，当我按照官方文档`作为服务运行`( https://docs.halo.run/install/linux )，然后启动halo服务，发现之前配置文件里面修改的后台路径不生效了，又变回了admin，当我把`ExecStart=/usr/bin/java -server -Xms256m -Xmx256m -jar YOUR_JAR_PATH`改为`ExecStart=/usr/bin/java  -jar YOUR_JAR_PATH`后，后台路径变成了两个，一个admin，一个配置文件里面自己设置的路径，亲测都可以进行登陆管理

**Comment by xiaofengjue** [comment]
> 你好，我根据文档使用新开的服务器测试了一遍，没有发现类似问题。
> 
> ![image](https://user-images.githubusercontent.com/21301288/122512276-383b7280-d03b-11eb-987f-cd2328cd119e.png)
> ![image](https://user-images.githubusercontent.com/21301288/122512310-438e9e00-d03b-11eb-9478-a33c67fc0780.png)
> ![image](https://user-images.githubusercontent.com/21301288/122512372-543f1400-d03b-11eb-9350-dd6215c8f41c.png)
> 
> 建议检查一下 halo 账户的权限。

您好，感谢您的热情恢复。我创建halo用户也是根据官方文档来的`usermod  -aG wheel halo`，这么一句将halo加入了wheel用户组，使用su，输入root密码就能以root身份登陆管理。下载整站备份的时候，域名访问和ip访问返回的信息不一样，域名是失败-服务器出现问题，ip是提示：{"status":400,"message":"The one-time token does not exist or has been expired","devMessage":null,"data":"XXXXXXXXXXXXXXXX"}，我还新发现了一个bug，当我按照官方文档`作为服务运行`( https://docs.halo.run/install/linux )，然后启动halo服务，发现之前配置文件里面修改的后台路径不生效了，又变回了admin，当我把`ExecStart=/usr/bin/java -server -Xms256m -Xmx256m -jar YOUR_JAR_PATH`改为`ExecStart=/usr/bin/java  -jar YOUR_JAR_PATH`后，后台路径变成了两个，一个admin，一个配置文件里面自己设置的路径，亲测都可以进行登陆管理

**Comment by ruibaby** [comment]
@xiaofengjue 根据你提供的信息我们无法判断是不是 bug，你可以考虑联系我微信我远程看看 Wry2slp。

**Comment by ruibaby** [comment]
> @xiaofengjue 根据你提供的信息我们无法判断是不是 bug，你可以考虑联系我微信我远程看看 Wry2slp。

1. 无法下载的问题是因为是用了腾讯云的 CDN，无法判断是什么问题。
2. 后台路经与预期不符的问题是因为配置文件放错位置。

**Comment by xiaofengjue** [comment]
> > @xiaofengjue 根据你提供的信息我们无法判断是不是 bug，你可以考虑联系我微信我远程看看 Wry2slp。
> 
> 1. 无法下载的问题是因为是用了腾讯云的 CDN，无法判断是什么问题。
> 2. 后台路经与预期不符的问题是因为配置文件放错位置。

您好经过我后续的验证，发现使用了cdn之后，系统->博客设置处，博客地址设置为ip+端口的形式后，整站备份能够下载数据，唯一的问题就是在访问文章时会将真实ip和端口暴露出来（首页是域名形式）
取消cdn之后，博客地址设置为域名，下载全站备份不再出错

总结：我的猜想，应该是使用cdn后，halo服务无法找到真实ip，而halo是根据ip+端口进行请求下载服务的，所以导致出错。所以最后的解决方式就是不使用cdn，但是不使用cdn，也就根据域名轻而易举查到对应ip了。最后还是看个人需求吧，加个cdn，web不能下载备份也能接受，因为web端下载比较慢，还不如直接ftp传输备份包来的快
