### ISSUE TITLE
日志journal时间线问题

### ISSUE THREAD

**Issue by zzzgd** [halo-dev/halo#1399]
发现一个bug, 日志我15点发条消息, 数据库是8小时时区问题存的23点, 不知道这个正不正常, 然后前端页面F12点开看到里面的时间 journal.createTime 是03点.

实际时间: 11点, 数据库: 19点, journal.createTime: 11点
实际时间: 15点, 数据库: 23点, journal.createTime: 03点

这个给我看不懂了.

jdbc已经加上了 serverTimezone=Asia/Shanghai
数据库selectNow是正常时间.
11点那个我能理解是代码做了时区调整, 但是15点那个咋回事啊. 这两个数据是我同一天测的

**Comment by ruibaby** [comment]
只有日志有问题吗？

**Comment by zzzgd** [comment]
> 只有日志有问题吗？

目前是只发现这个, 我一开始以为主题js问题, 但是看他是取得数据就这样

**Comment by ruibaby** [comment]
看看和这个帖子是不是一样的问题。https://bbs.halo.run/d/1495-halo8

**Comment by zzzgd** [comment]
> 看看和这个帖子是不是一样的问题。https://bbs.halo.run/d/1495-halo8

应该不是, 你看我这最新的一条测试 https://zzzgd.info/journals , 日志中写的是实际发送时间, 差了12小时.

服务器
[root@10-9-95-174 ~]# date
Fri Jun 18 14:15:41 CST 2021

数据库在docker上
select now();
2021-06-18 14:15:26

然后数据库的记录是:
2021-06-18 22:06:27	2021-06-18 22:06:27	<p>试下现在时间 2021年6月18日14:06:25</p>


然后F12的时间是 2021年6月18日02:06:25 , 这个我看js是取的 journal.createTime

**Comment by ruibaby** [comment]
@zzzgd Halo 容器中的时间呢？

**Comment by zzzgd** [comment]
@ruibaby halo是在宿主机上的, 只有mysql放在docker

**Comment by ruibaby** [comment]
> @ruibaby halo是在宿主机上的, 只有mysql放在docker

好的，我们会根据你的环境尝试复现一下。

**Comment by zzzgd** [comment]
主题中 jounal.ftl代码:
`
                            <div class="ziyan-content">
                                <div class="ziyan-header">
                                    <span class="ziyan-username">${user.nickname!}</span>
                                    <span class="is-verified-badge"></span>
                                    <span class="ziyan-text">·</span>
                                    <span class="ziyan-date time-ago" time="${journal.createTime?string("yyyy-MM-dd hh:mm:ss")}"></span>
                                </div>

`

然后js代码

`
    if ($('#container').find('.ziyan').length > 0) {
        // 计算时间
        setTimeAgo();

        // 自言代码高亮
        hljsZiYanCode()

    }


....

/**
 * 设置时间
 */
function setTimeAgo() {
    $('.time-ago').each(function () {
        const time = $(this).attr('time');
        console.log('time1',time)
        const timeStr = timeAgo(new Date(time));
        $(this).html(timeStr);
    });
}

`
然后控制台time1打印出来的时间就是我上面说的F12异常时间. 所以我觉得应该不是主题这边的bug

**Comment by ruibaby** [comment]
@zzzgd 我想问一下，你后台的日志管理中显示的时间是否正常。

**Comment by zzzgd** [comment]
@ruibaby 我后台管理页面没看到日志管理啊, 只有发表. 旁边的操作记录倒是正常

**Comment by zzzgd** [comment]
版本：1.4.8
后台菜单: 仪表盘
文章
页面
附件
评论
外观
用户
系统

**Comment by zzzgd** [comment]
版本：1.4.8
后台菜单: 仪表盘
文章
页面
附件
评论
外观
用户
系统

**Comment by ruibaby** [comment]
页面->内置页面->日志

**Comment by zzzgd** [comment]
==  大佬你这页面藏的也太仔细了, 我昨天找了一天图库怎么设置, 最后直接在附件一个个点的

**Comment by ruibaby** [comment]
> ==  大佬你这页面藏的也太仔细了, 我昨天找了一天图库怎么设置, 最后直接在附件一个个点的

不是进入页面管理就可以看到的吗🙃

**Comment by zzzgd** [comment]
看了下, 后台日志时间正常 (插入数据库硬生生+8小时, 不过前端时间是对的就行), 那感情还是日志页面返回的journal.createTime不对

**Comment by ruibaby** [comment]
> 看了下, 后台日志时间正常 (插入数据库硬生生+8小时, 不过前端时间是对的就行), 那感情还是日志页面返回的journal.createTime不对

注意到了，主题的锅。

```diff
- ${journal.createTime?string("yyyy-MM-dd hh:mm:ss")}
+ ${journal.createTime?string("yyyy-MM-dd HH:mm:ss")}
```

应该是大写的 HH，你自己改了试试。

数据库中的时间有可能是 UTC 时间。

**Comment by zzzgd** [comment]
> > ==  大佬你这页面藏的也太仔细了, 我昨天找了一天图库怎么设置, 最后直接在附件一个个点的
> 
> 不是进入页面管理就可以看到的吗🙃

是 页面->所有页面->独立页面
一般人也联想不到日志管理和图库管理在这里面把. 毕竟以为这个是对游客的页面管理==

**Comment by zzzgd** [comment]
> 的时间有可能显示

惊了, 没发现, OK 解决了, 我去给这位提issue去

**Comment by ruibaby** [comment]
> 是 页面->所有页面->独立页面
> 一般人也联想不到日志管理和图库管理在这里面把. 毕竟以为这个是对游客的页面管理==

好吧，会将此问题纳入新版 admin 的考虑范围。

**Comment by idchangyifan** [comment]
NICE啊，同样的问题，修改主题已结局。
希望官方可以出个主题，现在主题都有bug
