### ISSUE TITLE
English Please

### ISSUE THREAD

**Issue by us** [halo-dev/halo#140]
### What is the problem with Chinese README's

Firstly, we congratulate you for getting so much star by sharing this repository with humanity.

But it is very disappointing for non-Chinese speakers when one couldn't understand what a trending repository is about.

When we see such a repo on trending, our minds are blurring like Gollum's.

![Gollum Image](https://media.giphy.com/media/V4uGHRgz0zi6Y/giphy-downsized-large.gif)

There is a way **you can help** to solve this disappointment which I believe is experienced by many people who want to know more about your valuable work and appreciate it.

### What we want:
 - Please add English translation of your README so you are sharing your work and knowledge with more people.

### How this will help you:
 - More feedback to fix and improve your project.
 - New ideas about your project.
 - Greater fame.
 - ![SungerBob Image](https://media.giphy.com/media/3o7absbD7PbTFQa0c8/source.gif)

---

_“Sharing knowledge is the most fundamental act of friendship. Because it is a way you can give something without loosing something.”_

_**— Richard Stallman**_

**Thank you!**	

 > This issue created by `us/english-please` script. Please report on any error. Thank you!

**Comment by us** [comment]
Thank you!

**Comment by dannkunt** [comment]
Still relevant tho, could understand description from tipi, but have no idea what is this. 
![изображение](https://user-images.githubusercontent.com/32395839/236813317-e739e695-3b1c-4efa-a166-09528b5363b7.png)
This app is unusable for non-Chinese users

**Comment by ruibaby** [comment]
Hi @dannkunt , starting from version 2.4, we have added i18n support on the Console side. You can switch the language at the bottom of the login page:

<img width="1052" alt="image" src="https://user-images.githubusercontent.com/21301288/236826801-2a714ef7-da29-445f-be2c-56a92edbd447.png">

However, there are still some places where dynamic data is not yet supported by i18n. You can track the progress at: https://github.com/halo-dev/halo/issues/3573
