### ISSUE TITLE
关于草稿文章的未授权访问

### ISSUE THREAD

**Issue by xiaofengjue** [halo-dev/halo#1400]
## 我的环境
阿里云Centos7

---

## 错误日志
无

---

## 期望行为
当我们保存文章为草稿时，那么应该只有用户在登陆状态下才能访问该文章链接，未登陆则无法显示文章内容

## 当前行为
在未登陆用户的状态下，可以访问到草稿状态的文章内容

**Comment by ruibaby** [comment]
Duplicate https://github.com/halo-dev/halo/issues/1381#issuecomment-845634598
