### ISSUE TITLE
启动报错，显示的信息是乱码，有人遇到这个错误码

### ISSUE THREAD

**Issue by s1084796293** [halo-dev/halo#1405]
idea 将代码拉下来以后，编译直接就失败了
<img width="881" alt="Snipaste_2021-06-25_16-05-42" src="https://user-images.githubusercontent.com/17758223/123392583-caa9bc00-d5cf-11eb-9604-c5f258552621.png">

**Comment by ruibaby** [comment]
JDK 的最低要求为 11

https://github.com/halo-dev/halo/blob/master/build.gradle#L11

**Comment by s1084796293** [comment]
不行，还是这个错误
<img width="1093" alt="Snipaste_2021-06-25_16-05-42" src="https://user-images.githubusercontent.com/17758223/123396239-ab149280-d5d3-11eb-8dce-a0bdb79c9b58.png">

**Comment by ruibaby** [comment]
那你可以先解决一下控制台乱码的问题再看看。

我们的 CI 都是通过的。

https://github.com/halo-dev/halo/actions

**Comment by s1084796293** [comment]
已解决，jdk问题，之前没用过gradle，没想到build里面还需要指定jdk版本
<img width="806" alt="Snipaste_2021-06-25_16-05-42" src="https://user-images.githubusercontent.com/17758223/123415217-875b4780-d5e7-11eb-94ad-0accaa50215b.png">

**Comment by lhqypp** [comment]
![1649580458(1)](https://user-images.githubusercontent.com/103261938/162610345-bb8ffe90-9862-495a-93f9-0f99944d8a3a.jpg)为啥运行后是这样的啊那个大佬帮我一下

**Comment by lhqypp** [comment]
![image](https://user-images.githubusercontent.com/103261938/162611619-01245092-7ec8-481e-a553-11132bbb2b47.png)

**Comment by JohnNiang** [comment]
@lhqypp 这个问题解决了么？如果解决了，我将关闭这个 issue。
