### ISSUE TITLE
feat:关于评论

### ISSUE THREAD

**Issue by DuQingsong2002** [halo-dev/halo#1407]
## 概述

评论时填网址的时候，没有http或者https的前缀就会校验错误，希望在网址输入框左边弄个下拉框选项，默认可以为http://

**Comment by DuQingsong2002** [comment]
> ## 概述
> 评论时填网址的时候，没有http或者https的前缀就会校验错误，希望在网址输入框左边弄个下拉框默认为http://那种

**Comment by JohnNiang** [comment]
感谢 @DuQingsong2002 提供反馈。

如果有兴趣的话，可以直接去 <https://github.com/halo-dev/halo-comment> 提交 Pull Request。

**Comment by DuQingsong2002** [comment]
只见 It is not required to merge💔

**Comment by ruibaby** [comment]
> 只见 It is not required to merge💔

你的意思是？

**Comment by DuQingsong2002** [comment]
> > 只见 It is not required to merge💔
> 
> 你的意思是？
没事没事，刚提了个pr然后就It is not required to merge,然后随便发发😂

**Comment by JohnNiang** [comment]
hi @DuQingsong2002 这个 issue 还没有修复之前，请不要关闭。
