### ISSUE TITLE
文章更新但首页显现的摘要没变

### ISSUE THREAD

**Issue by zhanglp92** [halo-dev/halo#1408]
## 我的环境

版本：1.4.8
数据库：H2 1.4.197 (2018-03-18)
运行模式：production
User Agent：Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36

---

## 错误日志

文章更新了(内容清空重写), 但首页显现的摘要还是之前的内容

---

## 期望行为

首页显示的摘要也同步更新

**Comment by ruibaby** [comment]
目前的策略是，保存文章的时候如果没有自定义摘要，那么会自动从文章截取。所以你更新的时候是已经有摘要了的，不会更新。你现在如果需要更新摘要，可以在保存文章的时候将原有的摘要删除。

**Comment by zhanglp92** [comment]
明白了，谢谢。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Ryan Wang ***@***.***&gt;
发送时间: 2021年6月29日 21:36
收件人: halo-dev/halo ***@***.***&gt;
抄送: lr ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[halo-dev/halo] 文章更新但首页显现的摘要没变 (#1408)





 
目前的策略是，保存文章的时候如果没有自定义摘要，那么会自动从文章截取。所以你更新的时候是已经有摘要了的，不会更新。你现在如果需要更新摘要，可以在保存文章的时候将原有的摘要删除。
