### ISSUE TITLE
七牛云上传附件提示成功，但失败了！

### ISSUE THREAD

**Issue by IsResultXaL** [halo-dev/halo#141]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://docs.halo.run/)
- [x] [Github Wiki 常见问题](https://github.com/ruibaby/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/ruibaby/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

这是我的七牛云配置
![image](https://user-images.githubusercontent.com/10142184/56706654-5d2c4780-6748-11e9-8622-8209c9cea533.png)

图片上传提示成功，但是缩略图都看不到，并且去七牛云空间也看不到图片
![image](https://user-images.githubusercontent.com/10142184/56706700-864cd800-6748-11e9-8b3a-32bbd7349a20.png)

我看到一个《七牛云上传附件失败》的issues，里面说要设置空间区域zone，是在处理策略那里设置吗，因为我是华南的，所以试过设置成z2，也失败了。

对了，是通过docker安装的halo，代码应该也是最新的吧

**Comment by ruibaby** [comment]
https://github.com/halo-dev/halo/issues/138

**Comment by hyq965672903** [comment]
我也遇见了这个问题。
