### ISSUE TITLE
我使用的是 雪 这个主题  但是 在写文章的时候写$符号会出现报错 不知道是什么原因 代码块里面写$也会报错 请问有什么解决办法嘛？

### ISSUE THREAD

**Issue by xq-soliton** [halo-dev/halo#1412]

**Comment by ruibaby** [comment]
Xue 是在前端渲染的 Markdown，我们也不知道是什么原因导致的，你可以向 https://github.com/xzhuz/halo-theme-xue 提交 issue。

**Comment by xq-soliton** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    
        
            
        
    
    
     
    
        
                    ***@***.***好的先先
        
    
    
        签名由网易邮箱大师定制
    
 

    在2021年7月2日 23:32，Ryan ***@***.***> 写道： 




Xue 是在前端渲染的 Markdown，我们也不知道是什么原因导致的，你可以向 https://github.com/xzhuz/halo-theme-xue 提交 issue。
