### ISSUE TITLE
feat: 支持自定义工作目录。

### ISSUE THREAD

**Issue by lzhbhlrPython** [halo-dev/halo#1413]
## 概述

令Halo可以生成、读取当前目录下的数据文件、主题文件等

## 动机

本人及团队目前使用自建Windows Server服务器搭建博客，由于经费问题，我们的系统盘仅仅是一块64GB M.2硬盘，而主要储存是一块4TB的机械硬盘，我们为了节约系统盘空间，需要将一些东西放在非系统盘下（跑的项目很多，而且有时候可能需要多个Halo并存，目前无法实现）。

## 详细解释

根据我们的需求，我希望可以在Halo安装时提供选项，来确定将博客中的图片、主题等文件存放位置，并且在启动时默认优先读取根目录下配置文件，并且真切的希望可以将原本需要在配置文件中调整的如数据库类型等问题在安装页面有所体现，感谢贵团队的项目，希望这些东西能够采纳！

（Java学的不精，不能自己写PR……）

**Comment by ruibaby** [comment]
会考虑自定义工作目录地址。但目前你可以通过 Docker 管理多个 Halo，并且可以将工作目录映射到你们 4TB 的机械硬盘。

**Comment by ruibaby** [comment]
https://docs.halo.run/install/docker

https://www.bilibili.com/video/BV1hE411L7bU

**Comment by lzhbhlrPython** [comment]
好的谢谢！毕竟docker不是很常用，希望早日更新（目前WP的速度着实不敢恭维）

**Comment by reednow** [comment]
你这个需求我感觉可以用软链接文件夹解决~

**Comment by Qiang156** [comment]
> 你这个需求我感觉可以用软链接文件夹解决~

He uses Windows as the production environment.

**Comment by lzhbhlrPython** [comment]
Yeah，you are right... But we are not good engineer... We couldn't set centos well .... I'm waiting for new version!

**Comment by Qiang156** [comment]
I am sorry if my words hurt you.
You can learn how to deploy it with Docker.
It would be easier.
Good luck!

**Comment by ruibaby** [comment]
目前 Halo 2 支持在配置文件中配置工作目录地址，详情可查阅：https://docs.halo.run/getting-started/install/jar-file#:~:text=cd%20~/.halo2-,%E5%88%9B%E5%BB%BA%20Halo%20%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6,-vim%20application.yaml

/close
