### ISSUE TITLE
feat: 希望可以添加对 UML渲染支持

### ISSUE THREAD

**Issue by ExplodingDragon** [halo-dev/halo#1419]
## 概述

在文章中展示UML图

## 动机

在文章中展示某些模型时用 UML 比文字更方便

## 详细解释

或许可以使用 [PlantUML](https://plantuml.com/zh/)

PlantUML 支持快速绘制：
- 时序图
- 用例图
- 类图
- 对象图
- 活动图 
- 组件图
- 部署图
- 状态图
- 定时图
同时还支持以下非UML图：
- JSON 数据
- YAML 数据
- 网络图 (nwdiag)
- 线框图形界面
- 架构图
- 规范和描述语言 (SDL)
- Ditaa 图
- 甘特图
- 思维导图
- WBS 工作分解图
- 以 AsciiMath 或 JLaTeXMath 符号的数学公式
- 实体关系图

**Comment by JohnNiang** [comment]
PlantUML 确实是非常优秀，如果有了插件机制，这个功能是非常容易地集成进去的。

**Comment by ExplodingFKL** [comment]
> PlantUML 确实是非常优秀，如果有了插件机制，这个功能是非常容易地集成进去的。

插件机制会对第三方开放吗？

**Comment by ruibaby** [comment]
> > PlantUML 确实是非常优秀，如果有了插件机制，这个功能是非常容易地集成进去的。
> 
> 
> 
> 插件机制会对第三方开放吗？

现在没有插件机制。你说的这个会在新的编辑器上考虑。

**Comment by ruibaby** [comment]
> > PlantUML 确实是非常优秀，如果有了插件机制，这个功能是非常容易地集成进去的。
> 
> 
> 
> 插件机制会对第三方开放吗？

现在没有插件机制。你说的这个会在新的编辑器上考虑。

**Comment by zhixiangyuan** [comment]
> > > PlantUML 确实是非常优秀，如果有了插件机制，这个功能是非常容易地集成进去的。
> > 
> > 
> > 插件机制会对第三方开放吗？
> 
> 现在没有插件机制。你说的这个会在新的编辑器上考虑。

新的编辑器什么时候能发出来使用？

**Comment by zhixiangyuan** [comment]
> > > PlantUML 确实是非常优秀，如果有了插件机制，这个功能是非常容易地集成进去的。
> > 
> > 
> > 插件机制会对第三方开放吗？
> 
> 现在没有插件机制。你说的这个会在新的编辑器上考虑。

关于新的编辑器有个建议，现在的编辑器能自动上传图片，但是我删除图片的时候不会自动删除附件，需要手动删除，这里希望能在新的编辑器上删除文章中的图片时自动删除附件。

**Comment by Wanxp** [comment]
可以考虑使用kroki 接口服务，kroki也是对一众的 可读语言 -> 图形(包括plantuml)进行了接口级别的封装，能够覆盖大多数的这种需求。不过这样相对应的需要 部署自己的服务kroki服务(步骤不是很复杂)，可以考虑预留使用kroki的扩展

**Comment by Menci** [comment]
#989

**Comment by 1379** [comment]
> PlantUML 确实是非常优秀，如果有了插件机制，这个功能是非常容易地集成进去的。

目前我们有设计插件机制吗，或者说插件有计划安排了吗？@JohnNiang

**Comment by ruibaby** [comment]
目前 Halo 2 已经提供了类似的插件：https://github.com/halo-sigs/plugin-text-diagram

/close
