### ISSUE TITLE
版本0.4.3 后台新增菜单，前端访问新增的菜单404，请问路径是有什么规则吗？

### ISSUE THREAD

**Issue by leejiliang** [halo-dev/halo#142]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x ] [Halo 使用文档](https://docs.halo.run/)
- [ x] [Github Wiki 常见问题](https://github.com/ruibaby/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [ x] [其他 Issues](https://github.com/ruibaby/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [x ] 请求技术支持

**Comment by trey-tao** [comment]
可以确认下，WebMvcAutoConfiguration.java类里的addInterceptors()方法。这个方法里面需要对于新增的接口URI进行注册配置。
看下 是不是这个问题？

**Comment by ruibaby** [comment]
...
