### ISSUE TITLE
部署问题

### ISSUE THREAD

**Issue by Pantyhose-X** [halo-dev/halo#1420]
怎么部署在
[freenet网络](https://freenetproject.org/)
[I2P匿名网络](https://geti2p.net/zh/)
[Beaker Browser IPFS 为分布式 Web](https://beakerbrowser.com/)
[ZeroNet网络](https://zeronet.io/zh)

**Comment by JohnNiang** [comment]
网络问题这里没办法解答你

**Comment by Pantyhose-X** [comment]
> /needsMoreInfo

![Capture](https://user-images.githubusercontent.com/42504385/125800040-4062e719-48af-4690-b6b0-1d765ceb985f.JPG)

**Comment by ruibaby** [comment]
抱歉我们没法提供这方面的教程，只能你自己研究研究了。我先关闭了，如果需要补充，你可以 reopen。
