### ISSUE TITLE
defect：后台日志管理页面，单行内容过长时，编辑和删除按钮不显示

### ISSUE THREAD

**Issue by abnormal01** [halo-dev/halo#1423]
### What is version of Halo has the issue?

1.4.8

### What database are you using?

MySQL 8.x

### What happened?

后台日志管理页面，单行内容过长时，编辑和删除按钮不显示

**Comment by ruibaby** [comment]
我刚刚已经将 issue 转移到了 halo-admin 项目，因为这属于 admin 的问题。

https://github.com/halo-dev/halo-admin/issues/345
