### ISSUE TITLE
test command

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#1424]
### What is version of Halo has the issue?

1.4.8

### What database are you using?

H2

### Your site address.

https://halo.run

### What happened?

test command

**Comment by ruibaby** [comment]
/*off-topic

**Comment by ruibaby** [comment]
感谢您报告了这个issue！遗憾的是，我们很难了解你看到的问题。 请提供一段屏幕录制来准确地展示不符合预期的情况。虽然`GitHub`支持很多标准格式，但尽量首选`.gif` 文件，因为它们在GitHub是内联展示。你可以使用基于浏览器的gif录制工具 https://gifcap.dev 来帮助您。

如果这个issue依赖键盘输入，您可以通过启用`screencast`模式来录制 (`Developer: Toggle Screencast Mode` in the command palette)。

**Comment by guqing** [comment]
@ruibaby /*question

**Comment by ruibaby** [comment]
/*out-of-scope
