### ISSUE TITLE
希望支持 github pages 和 cloudflare pages 等静态页面托管程序。

### ISSUE THREAD

**Issue by fengzhao** [halo-dev/halo#1428]
## 概述

希望支持 github pages 和 cloudflare pages 等静态页面托管程序。

## 动机

可以不占用自己的服务器资源。

**Comment by JohnNiang** [comment]
感谢提出宝贵的提议。关于静态页面的生成后续会考虑的。不过不会出现在 1.4.x 版本中。

**Comment by JohnNiang** [comment]
可以告诉我们关闭 issue 的原因么

**Comment by fengzhao** [comment]
> 可以告诉我们关闭 issue 的原因么

之前没看到是java应用，以为是纯前端静态页面的应用。
