### ISSUE TITLE
请问如何让这个项目运行起来？来自小白的提问

### ISSUE THREAD

**Issue by zuojunZzz** [halo-dev/halo#143]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://docs.halo.run/)
- [ ] [Github Wiki 常见问题](https://github.com/ruibaby/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [ ] [其他 Issues](https://github.com/ruibaby/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

**Comment by ruibaby** [comment]
@zuojunZzz 请问这个项目是什么?

**Comment by zuojunZzz** [comment]
> @zuojunZzz请问这个项目是什么？

就是halo这个项目，我想在Windows系统上跑起来，但不知道怎么跑，百度了也没用

**Comment by zuojunZzz** [comment]
halo项目，然后i是windows系统

**Comment by ruibaby** [comment]
[https://github.com/halo-dev/halo/issues](https://github.com/halo-dev/halo/issues)
[https://github.com/halo-dev/halo/wiki](https://github.com/halo-dev/halo/wiki)
[https://docs.halo.run/](https://docs.halo.run/)
[http://bbs.halo.run](http://bbs.halo.run)
[百度](https://www.baidu.com/s?wd=windows%20springboot&rsv_spt=1&rsv_iqid=0xe1ace6a800063dc2&issp=1&f=8&rsv_bp=1&rsv_idx=2&ie=utf-8&tn=baiduhome_pg&rsv_enter=1&rsv_sug3=26&rsv_sug1=31&rsv_sug7=101&rsv_t=c540WU4aJGMt3GO89MEwjB0q%2Bus8jXT8rYs2XVGhl%2BapL9lBA7VjAW57AW%2BTUqyLbJ4g&rsv_sug2=0&inputT=7219&rsv_sug4=7219)
[Google](https://www.google.com/search?safe=active&source=hp&ei=6djCXL73Dpid-gTIj4OIDQ&q=Windows+springboot&btnK=Google+%E6%90%9C%E7%B4%A2&oq=Windows+springboot&gs_l=psy-ab.3..0i10j0i10i30l2j0i8i10i30l5j0i8i30j0i5i30.12447.14322..15274...1.0..0.580.1518.2-1j1j1j1......0....1..gws-wiz.....6..35i39j0j0i203.srsMDf6EK9g)
