### ISSUE TITLE
昨天docker自动更新镜像后报错standard_init_linux.go:219: exec user process caused: exec format error

### ISSUE THREAD

**Issue by SoraKasvgano** [halo-dev/halo#1431]
### What is version of Halo has the issue?

RPI4 8G raspbian 64bit

### What database are you using?

MySQL 5.7

### What happened?

standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error
,standard_init_linux.go:219: exec user process caused: exec format error

**Comment by ruibaby** [comment]
重新更新，1.4.9 的镜像有问题。

**Comment by SoraKasvgano** [comment]
> 重新更新，1.4.9 的镜像有问题。

qs,更新完好了，谢谢
