### ISSUE TITLE
1.4.10 API更新导致WeHalo小程序无法获取文章列表

### ISSUE THREAD

**Issue by manction** [halo-dev/halo#1432]
### 是什么版本出现了此问题？

1.4.10

### 使用的什么数据库？

H2

### 在线站点地址

https://m.xiaobaipb.com

### 发生了什么？

更新：Content Api 中的获取文章列表支持传入关键字和分类 id 筛选项。halo-dev/halo#1373
问题：1.4.10 API 更新导致 WeHalo 小程序无法获取文章列表，需要新增关键字和分类 id 参数才能正常访问。

### 相关日志输出

```shell
org.springframework.web.bind.MissingServletRequestParameterException: Required request parameter 'keyword' for method parameter type String is not present
org.springframework.web.bind.MissingServletRequestParameterException: Required request parameter 'categoryId' for method parameter type String is not present
```

**Comment by ruibaby** [comment]
这两个参数确实不应该是必传，我们会在下一个版本修改。目前你可以考虑在文章列表的接口加上这两个参数并将值设置为 null。

/assign @ruibaby

**Comment by manction** [comment]
> 这两个参数确实不应该是必传，我们会在下一个版本修改。目前你可以考虑在文章列表的接口加上这两个参数并将值设置为 null。
> 
> /assign @ruibaby

好的。
