### ISSUE TITLE
希望开发图库点赞功能

### ISSUE THREAD

**Issue by YangDunYu** [halo-dev/halo#1433]
### 描述一下此特性

图库前台点赞，后台计数

**Comment by ruibaby** [comment]
目前感觉不是太有必要，但我们会考虑一下。

**Comment by dejavuwl** [comment]
感觉可以作为锦上添花的小功能，跟文章点赞类似了

**Comment by mimajiushi** [comment]
这个还跟主题有关，主题作者支持度是个问题，正如现在不是所有主题都支持日志评论一样
