### ISSUE TITLE
关于加密密码的方法

### ISSUE THREAD

**Issue by pppobear** [halo-dev/halo#144]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [ ] [Halo 使用文档](https://docs.halo.run/)
- [ ] [Github Wiki 常见问题](https://github.com/ruibaby/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/ruibaby/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] 添加新的特性或者功能
- [ ] BUG 反馈
- [ ] 请求技术支持

md5加密密码现在已经不再是安全的了，不如考虑改成BCrypt或者AES算法？

**Comment by ruibaby** [comment]
@pppobear 谢谢，已经改了。
