### ISSUE TITLE
脚注显示错误

### ISSUE THREAD

**Issue by weidongzhou1994** [halo-dev/halo#1443]
### What is version of Halo has the issue?

1.4.11

### What database are you using?

H2

### What happened?

脚注在编辑器中正常显示，但发布后无法查看

**Comment by weidongzhou1994** [comment]
这是示例的脚注文本显示结果
![Uploading image.png…]()

**Comment by guqing** [comment]
> 这是示例的脚注文本显示结果

图片还没上传完呢 等待上传完毕后再点击comment

**Comment by weidongzhou1994** [comment]
![image](https://user-images.githubusercontent.com/40510496/127475381-ced8ec29-3954-4b68-b229-88a68e36a9c0.png)

**Comment by weidongzhou1994** [comment]
这是脚注示例文本的显示结果：
![image](https://user-images.githubusercontent.com/40510496/127475882-1b35fca2-0ec6-434c-b66c-c5dc57b73445.png)

**Comment by weidongzhou1994** [comment]
这样可以了吗？

**Comment by guqing** [comment]
请问使用的什么主题呢

**Comment by weidongzhou1994** [comment]
https://halo.run/archives/theme-xue.html

**Comment by ruibaby** [comment]
> https://halo.run/archives/theme-xue.html

这是主题的问题，这个主题是在前端渲染的 Markdown。
