### ISSUE TITLE
增加整站使用备份文件一键还原功能

### ISSUE THREAD

**Issue by TravelEngineers** [halo-dev/halo#1447]
### 你当前使用的版本

1.4.11

### 描述一下此特性

目前Halo 已支持进行整站备份，但是在操作页面没有发现可以进行整站还原的功能。
建议增加使用备份包进行一键还原的功能，这样不用在恢复数据时一篇一篇文章进行导入。

### 附加信息

无

**Comment by ruibaby** [comment]
目前我们整站备份是打包的整个工作目录，无法支持在系统启动之后还原。你可以自行上传到对应路径解压。

工作目录的定义参考文档：https://docs.halo.run/install/prepare

**Comment by TravelEngineers** [comment]
> 目前我们整站备份是打包的整个工作目录，无法支持在系统启动之后还原。你可以自行上传到对应路径解压。
> 
> 工作目录的定义参考文档：https://docs.halo.run/install/prepare

那还是先备份docker数据目录吧，文章导入可以支持批量的不呀。

**Comment by ruibaby** [comment]
> > 目前我们整站备份是打包的整个工作目录，无法支持在系统启动之后还原。你可以自行上传到对应路径解压。
> 
> > 
> 
> > 工作目录的定义参考文档：https://docs.halo.run/install/prepare
> 
> 
> 
> 那还是先备份docker数据目录吧，文章导入可以支持批量的不呀。

docker 不应该将工作目录映射出来的吗？

**Comment by TravelEngineers** [comment]
> > > 目前我们整站备份是打包的整个工作目录，无法支持在系统启动之后还原。你可以自行上传到对应路径解压。
> > 
> > 
> > > 
> > 
> > 
> > > 工作目录的定义参考文档：https://docs.halo.run/install/prepare
> > 
> > 
> > 那还是先备份docker数据目录吧，文章导入可以支持批量的不呀。
> 
> docker 不应该将工作目录映射出来的吗？

现在是将工作目录映射出来的。

**Comment by ruibaby** [comment]
@TravelEngineers 那么你现在遇到的问题是？

**Comment by TravelEngineers** [comment]
> @TravelEngineers 那么你现在遇到的问题是？

没了，只是突然想起来，halo大都是个人站长，没有运营的概念。
