### ISSUE TITLE
SSRF vulnerability in Theme fetch interface which allow attacker to detect the intranet information

### ISSUE THREAD

**Issue by dylan1174** [halo-dev/halo#1448]
### What is version of Halo has the issue?

1.4.11

### What database are you using?

H2

### What happened?

In the theme page,there is an interface to fetch the remote theme file.Attacker can input the arbitrary intranet address, then by the corresponding response he can check whether port in enable.

For example,if the uri is http://127.0.0.1:8090/tt.zip and port 8090 is listening
![image](https://user-images.githubusercontent.com/57998952/128175542-87951adf-66c6-4c72-ba64-6f4010540de8.png)

the request is
```
POST /api/admin/themes/fetching?uri=http://127.0.0.1:8091/tt.zip HTTP/1.1
Host: 127.0.0.1:8090
Content-Length: 0
Admin-Authorization: 26784d19d941455bb6963c7742e881aa
Accept: application/json, text/plain, */*
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
Origin: http://127.0.0.1:8090
Referer: http://127.0.0.1:8090/admin/index.html
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7
Cookie: JSESSIONID=node018r63g1o6ttnhelrawa1zigae5.node0
Connection: close
```

it will return the response like
```
{"status":400,"message":"主题配置文件缺失！请确认后重试。","devMessage":null,"data":null}
```
but if the port is closed,the response is
```
{"status":500,"message":"Internal Server Error","devMessage":null,"data":null}
```
So the difference in reponse content will disclose the information about the intranet which helps attacker to do futher attack.

**Comment by ruibaby** [comment]
Sorry, we don't understand this issue.

/needsMoreInfo

**Comment by guqing** [comment]
This api can only be accessed by the administrator, and currently does not support multiple users, so I don’t think your question is valid.

**Comment by Clownsw** [comment]
这个位置目前只有管理员能访问

**Comment by JohnNiang** [comment]
这个操作等于在浏览器上输入  `http://127.0.0.1:8090/tt.zip` 链接后自动下载，然后手动解压缩文件。我们不认为这种情况我们能够解决，除非我们提供白名单，但这会缺失灵活性。
