### ISSUE TITLE
Reported a bug in huntr

### ISSUE THREAD

**Issue by B3EF** [halo-dev/halo#1451]
### What is version of Halo has the issue?

latest

### What database are you using?

MySQL 8.x

### Your site address.

run in localhost for testing

### What happened?

Blind XSS

### Additional information

https://huntr.dev/bounties/f53d6e67-5262-402d-9b3f-65002dee1bfa/
check huntr adversary page

**Comment by ruibaby** [comment]
Hi @B3EF , I can't view this page.

**Comment by B3EF** [comment]
hi @ruibaby  are you reviewing the security issue ? , basically only maintainers of the repo will be able to see the security issue's adversary page ? if you are the reviewer then i will ask huntr to add you to the adversary page.

**Comment by B3EF** [comment]
hi @ruibaby huntr have sorted out the issue you will be now able to view the adversary page.

**Comment by B3EF** [comment]
hi @ruibaby , can you validate the issue ,  it will not be published until you confirm a fix here , also it will help me grab a small bounty for the bug this month.

**Comment by B3EF** [comment]
hi @ruibaby , can you validate the adversary page, its has been one month since i have reported the issue

**Comment by ruibaby** [comment]
@B3EF hi B3EF, I have confirmed, but we are unable to determine when it will be repaired. I will close this issue first.

**Comment by B3EF** [comment]
ok
