### ISSUE TITLE
博主评论显示问题

### ISSUE THREAD

**Issue by GodApex** [halo-dev/halo#1453]
### 是什么版本出现了此问题？

1.4.11

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 在线站点地址

https://www.godapex.com

### 发生了什么？

en,似乎博主的回复无法在文章页看见

### 附加信息

![image](https://user-images.githubusercontent.com/52237591/129523129-2b9c3b17-fdd2-4d0a-a2d6-593b731df29b.png)
![image](https://user-images.githubusercontent.com/52237591/129523146-9297bd9f-64a3-450b-abef-6e148b100246.png)
如图

**Comment by GodApex** [comment]
不知道是不是这个主题的原因

**Comment by ruibaby** [comment]
点击更多。

**Comment by GodApex** [comment]
可不可以自行展开

**Comment by ruibaby** [comment]
那你可以换一个：https://github.com/halo-dev/halo-comment-normal

**Comment by GodApex** [comment]
谢谢
