### ISSUE TITLE
HaloMvcConfiguration's FileUpload

### ISSUE THREAD

**Issue by rsosor** [halo-dev/halo#1454]
### 是什么版本出现了此问题？

1.4.11

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

localhost

### 发生了什么？

The project was not built since its build path is incomplete. Cannot find the class file for org.apache.commons.fileupload.FileUpload. Fix the build path then try building this project

The type org.apache.commons.fileupload.FileUpload cannot be resolved. It is indirectly referenced from required .class files

IDE 是用 Eclipse 4.18.0 使用 Spring Boot 導入此專案
Google 有說是版本問題，確定使用 JDK 11，系統變數也是使用 JDK 11 路徑。
也有說是要去下載 FileUpload.jar 不過還是沒有用，而且 classpath 跟 build.gradle 本來就有導入這些包了。
我從 git clone 下來之後就沒有改動任何設定，而且我如果把上面的錯誤刪掉直接執行，會有一堆 Throwable (頭痛)。

**Comment by ruibaby** [comment]
我尝试使用 Eclipse 复现一下。

**Comment by rsosor** [comment]
> 我尝试使用 Eclipse 复现一下。

好的感恩

**Comment by ruibaby** [comment]
确实有这样的问题，没有能解决此问题。

![image](https://user-images.githubusercontent.com/21301288/129567537-456231cf-e1fc-48c9-aecf-cc1e7be3657f.png)

@rsosor 能尝试使用 idea community edition 吗？

**Comment by rsosor** [comment]
> 确实有这样的问题，没有能解决此问题。
> 
> ![image](https://user-images.githubusercontent.com/21301288/129567537-456231cf-e1fc-48c9-aecf-cc1e7be3657f.png)
> 
> @rsosor 能尝试使用 idea community edition 吗？

我再試試看Idea，感謝

**Comment by ruibaby** [comment]
是否有解决此问题呢？

**Comment by rsosor** [comment]
我轉 idea 就可以了！
