### ISSUE TITLE
希望增加自定义文章设置功能

### ISSUE THREAD

**Issue by xzyone** [halo-dev/halo#1459]
### 你当前使用的版本

1.4.11

### 描述一下此特性

建议主题theme.yaml的PostMetaField和sheetMetaField可以和settings.yaml一样设置不同的文本框、选择框之类的，然后这个设置会出现在文章设置处，这样对于不同主题开发者每篇文章或者页面都有不同的变量选择。

**Comment by ruibaby** [comment]
2.0 目前已经支持，请参考：https://docs.halo.run/developer-guide/annotations-form

/close
