### ISSUE TITLE
Potential Issues in CacheLock's timeout

### ISSUE THREAD

**Issue by project-concerto** [halo-dev/halo#1463]
### What is version of Halo has the issue?

master

### What database are you using?

MySQL 5.7

### What is your deployment method?

Fat Jar

### What happened?

CacheLock is used across halo to provide lock semantics. CacheLock has a default timeout set to 5 seconds. With this timeout, CacheLock actually has the semantics of a **lease**, leading to potential issues.

For example, when used in run.halo.app.controller.admin.api.ThemeController#saveSettingsBy or run.halo.app.controller.admin.api.InstallController#installBlog, CacheLock cannot prevent concurrent installation or setting themes if they took too long.

**Comment by guqing** [comment]
Hi @project-concerto, examples of using concurrent installation：If the controller uses `CacheLock` annotation, it just directly returns the results that already exist in the cache according to the same parameters, and executes the code logic without hitting the cache, so there is no concurrent installation problem. You can describe in detail how concurrent installations will occur.

**Comment by ruibaby** [comment]
I closed it , if you have any other questions, you can reopen it.
