### ISSUE TITLE
回收站文章抵达回收时间但是没有被回收

### ISSUE THREAD

**Issue by zhixiangyuan** [halo-dev/halo#1465]
### 是什么版本出现了此问题？

1.4.11

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Fat Jar

### 发生了什么？

回收站文章抵达回收时间但是没有被回收，我设置的 30 天后回收，但是实际没有效果

**Comment by zhixiangyuan** [comment]
补充两张图片

![image](https://user-images.githubusercontent.com/25138766/131436464-d08af3a5-3d8b-4685-83bf-6ba099e2a597.png)
![image](https://user-images.githubusercontent.com/25138766/131436491-64b892bc-768c-460c-a040-40f96947c687.png)

**Comment by guqing** [comment]
hi @zhixiangyuan, 回收站文章的自动清理时间=文章加入回收站的时间 + 回收站文章保留时长，也就是说文章加入回收站的时间并不等于发布时间，所以请查看一下文章的 updateTime 时间与当前时间的差值是否达到回收时间，如果确认自动清理功能的确有问题在给我们回复！
