### ISSUE TITLE
希望能暴露博客访问量和点赞接口

### ISSUE THREAD

**Issue by qinhua** [halo-dev/halo#1466]
### 你当前使用的版本

> JDK 11
> halo@1.4.11

### 描述一下此特性

1、希望模板中可以直接使用类似@viewCount这类获取到博客访问量数据用于展示；
2、希望能支持一个点赞功能；

### 附加信息

无，打算暂时用百度统计提供的接口

**Comment by ruibaby** [comment]
> 2、希望能支持一个点赞功能；

目前都是有接口的，但是需要视主题支持情况而定。

**Comment by qinhua** [comment]
> > 2、希望能支持一个点赞功能；
> 
> 目前都是有接口的，但是需要视主题支持情况而定。

ftl文件里可以获取到总访问量吗？

**Comment by qinhua** [comment]
@ruibaby 最近在完善相关主题，希望得到帮助，我要如何使用这个点赞接口呢

**Comment by ruibaby** [comment]
可以参考 https://github.com/cetr/halo-theme-sagiri

**Comment by qinhua** [comment]
@ruibaby 文章点赞接口 /api/content/posts/{postId}/likes 请求成功后，列表里的 likes 字段没更新，一直是0，我看日志的点赞接口是好的，这块是没有实现吗?

**Comment by ruibaby** [comment]
@qinhua 经过我们讨论，目前提供 @viewcount 这样的标签不是很好设计，暂时我们推荐使用 `/api/content/statistics` 接口来获取 `visitCount`。

**Comment by ruibaby** [comment]
目前 Halo 2.0 已经支持获取浏览量，文档：https://docs.halo.run/developer-guide/theme/finder-apis/site-stats

点赞接口：

URL：/apis/api.halo.run/v1alpha1/trackers/upvote

Request Body：

```
{
  "group": "string",
  "plural": "string",
  "name": "string"
}
```

/close
