### ISSUE TITLE
使用类似主题配置的配置项声明方式来编写主站配置

### ISSUE THREAD

**Issue by Menci** [halo-dev/halo#1476]
### 你当前使用的版本

1.4.11

### 描述一下此特性

当前 Halo 的 admin 系统采用了前后端分离的架构，在后端每次新增一个配置项需要同时更新前端代码和后端代码。如果能够将后端的各种配置以类似主题配置描述文件的形式提供给前端，让前端动态渲染这些配置项，便可以很大程度上减少前端代码修改/构建的频率。

**Comment by ruibaby** [comment]
可以这么做，但目前使用这种方式还有不少问题，比如目前的主题配置都还没做表单项验证。所以暂时不打算做这样的改动。

**Comment by ruibaby** [comment]
暂时先关闭了，如果有后续补充，可以 Reopen。

**Comment by ruibaby** [comment]
暂时先关闭了，如果有后续补充，可以 Reopen。
