### ISSUE TITLE
新建文章标签页xss漏洞

### ISSUE THREAD

**Issue by lostmaniac** [halo-dev/halo#1478]
### 是什么版本出现了此问题？

新建文章

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Fat Jar

### 发生了什么？

新建文章标签页xss漏洞
标签内容填写<script> alert(1) </script>

### 附加信息

![2b7f34cce97617bcb150922474786e2](https://user-images.githubusercontent.com/6057477/133402121-2f8f390d-499b-4eae-a863-15e9210bf109.png)

**Comment by lostmaniac** [comment]
![image](https://user-images.githubusercontent.com/6057477/133402450-1a1fc510-e225-4c37-9e9b-2a340a0e3ce2.png)

**Comment by guqing** [comment]
Hi @lostmaniac, 感谢你创建该 issue, 标签只有管理员可以创建，目前halo也不支持多用户因此不会发生 xss，如果后续版本支持多用户后我们会考虑该问题，但目前这不是bug
