### ISSUE TITLE
gravatar头像很容易打不开

### ISSUE THREAD

**Issue by jiashuai123** [halo-dev/halo#1480]
### 是什么版本出现了此问题？

1.4.11

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Fat Jar

### 在线站点地址

neojarvis.top

### 发生了什么？

评论区的gravatar经常显示不出（偶尔能加载），可能跟国内环境有关
![image](https://user-images.githubusercontent.com/20734746/133542374-ad14bf97-cc25-4e09-b17c-0187eb7615da.png)

**Comment by ruibaby** [comment]
https://bbs.halo.run/d/1455
