### ISSUE TITLE
希望评论接口可以支持保存头像url

### ISSUE THREAD

**Issue by qinhua** [halo-dev/halo#1482]
### Your current Halo version

1.4.11

### Describe this feature

现有的评论接口似乎只能保存用户名、邮箱、网址这些，没有提供用户头像的字段。使用gavatar又很慢，如果是qq头像，希望能直接保存下来下次展示

**Comment by ruibaby** [comment]
这相当于让评论者随意输入头像地址，我觉得可能会有一定安全风险，所以保持待定。

至于 Gravatar 慢的问题，你可以参考 https://bbs.halo.run/d/1455

**Comment by qinhua** [comment]
了解
