### ISSUE TITLE
服务器重启后halo.service无法自启

### ISSUE THREAD

**Issue by joson1205** [halo-dev/halo#1484]
### 是什么版本出现了此问题？

1.4.12

### 使用的什么数据库？

H2

### 发生了什么？

CentOS7.9环境，已将halo服务设为开机自启，查看服务状态显示报错。每次需要`systemctl restart halo`重启服务才能正常运行。

### 相关日志输出

```shell
[root@joson ~]# systemctl status halo
● halo.service - Halo Service
   Loaded: loaded (/etc/systemd/system/halo.service; disabled; vendor preset: disabled)
   Active: inactive (dead)
     Docs: https://halo.run

Sep 18 10:57:07 joson systemd[1]: [/etc/systemd/system/halo.service:12] Unknown lvalue 'StandOutput' in section 'Service'
Sep 18 10:57:07 joson systemd[1]: [/etc/systemd/system/halo.service:14] Unknown lvalue 'StandError' in section 'Service'
[root@joson ~]#
```

### 附加信息

![image](https://user-images.githubusercontent.com/21129878/133870334-b7edcd8d-0752-4215-99f2-10a810bd93b4.png)

**Comment by joson1205** [comment]
> 请提供你的 halo.service 配置。

配置与官方提供的模板配置一致的，未做修改，ExecStart项，单独执行正常。

**Comment by ruibaby** [comment]
那你再执行一下下面的命令试试吧：

```
systemctl daemon-reload
```

```
systemctl enable halo
```

**Comment by xdfbb** [comment]
StandOutput,StandError两个参数是不正确的，我这边用ubuntu类的系统也是同样的报错，删掉就好了
