### ISSUE TITLE
 希望能增加集成一个富文本编辑器

### ISSUE THREAD

**Issue by scdlyh** [halo-dev/halo#1486]
### Your current Halo version

1.4.12

### Describe this feature

**希望能增加增加集成一个富文本编辑器，halo的Markdown编辑器挺好的，使用过 wangEditor [https://www.wangeditor.com]富文本编辑器感觉不错，编辑内容时排版挺直观的，希望能增加集成 wangEditor 这样的富文本编辑器**

**Comment by ruibaby** [comment]
会支持一个富文本编辑器，1.5.x 的时候。

**Comment by ruibaby** [comment]
duplicate https://github.com/halo-dev/halo-admin/issues/303
