### ISSUE TITLE
后台菜单模块页面分组异常提示

### ISSUE THREAD

**Issue by fujieNo1** [halo-dev/halo#1487]
### 是什么版本出现了此问题？

最新版本

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker

### 发生了什么？

进入后台菜单页面提示错误信息，如图：
![image](https://user-images.githubusercontent.com/41049282/134605975-fd467298-e050-4ad7-8860-9a760ff341e3.png)
![image](https://user-images.githubusercontent.com/41049282/134606091-e25134d5-4078-4c9d-a574-c0e28a0fb157.png)

**Comment by ruibaby** [comment]
https://github.com/halo-dev/halo/issues/844

**Comment by fujieNo1** [comment]
> #844

感谢
