### ISSUE TITLE
多机部署后台管理登录Session混乱

### ISSUE THREAD

**Issue by jerry-shao** [halo-dev/halo#1505]
### 是什么版本出现了此问题？

1.4.11

### 使用的什么数据库？

MySQL 5.7

### 使用的哪种方式部署？

Fat Jar

### 在线站点地址

https://jerryshao.com

### 发生了什么？

网站目前部署在AWS的3台EC2上面，前面加了AWS Elastic LoadBalancer做负载均衡。

前端页面访问正常。

后端管理页面登录后，频繁提升需要重新登录。

通过服务器A登录之后的session，登录成功跳转到控制台页面可能被转到了服务器B或C。
不知道咱们对后端登录Session是怎么管理的？

**Comment by JohnNiang** [comment]
Thank you reaching out here!

目前 Halo 是有状态服务，即使是使用了 MySQL 也不适合多机部署。

我们不认为这是一个 bug，不过可以作为一个 improvement 来完善。

**Comment by jerry-shao** [comment]
同意，毕竟是还不支持的功能。

我有时间也看下代码，看能不能把这个问题解决。

**Comment by JohnNiang** [comment]
Hi @jerry-shao ，这不仅仅是 Session 的问题。还有三个问题需要考虑：

1. 多机部署不能使用 H2 数据库作为数据存储
2. 多级部署模式下，目前还没有办法同步主题文件
3. 多级部署模式下，目前还没有适配集中式缓存

**Comment by luoxmc** [comment]
针对当前版本的halo，我这边已经改造实现了集群部署，具体方案可以看我的博客 https://www.luoxx.top/archives/halo-distributed-deploy

**Comment by Zhoutzzz** [comment]
> 针对当前版本的halo，我这边已经改造实现了集群部署，具体方案可以看我的博客 https://www.luoxx.top/archives/halo-distributed-deploy

兄弟我正好也有这个需求你就弄了，赞

**Comment by luoxmc** [comment]
> > 针对当前版本的halo，我这边已经改造实现了集群部署，具体方案可以看我的博客 https://www.luoxx.top/archives/halo-distributed-deploy
> 
> 兄弟我正好也有这个需求你就弄了，赞

哈哈，确实是巧了，我也是这几天才搞的
