### ISSUE TITLE
数学公式前端显示不正常

### ISSUE THREAD

**Issue by FelicxFoster** [halo-dev/halo#1514]
### 是什么版本出现了此问题？

1.4.13

### 使用的什么数据库？

Other

### 使用的哪种方式部署？

Fat Jar

### 发生了什么？

编辑插入markdown语法矩阵，后端显示正常，前端只显示markdown代码，其他公式都显示正常

**Comment by ruibaby** [comment]
我们会在这个 issue 解决的同时解决  https://github.com/halo-dev/halo/issues/989
