### ISSUE TITLE
halo 源码里的Sheet是什么呢

### ISSUE THREAD

**Issue by 1379** [halo-dev/halo#1517]
### What is version of Halo has the issue?

-

### What database are you using?

MySQL 8.x

### What is your deployment method?

Fat Jar

### Your site address.

- 

### What happened?

我在阅读halo的源码，发现有post和sheet两种区别，想问一下，post和sheet的区别是什么啊

**Comment by 1379** [comment]
不好意思，issue类型好像只能选bug，但这并不是bug

**Comment by ruibaby** [comment]
自定义页面，和文章独立开的，你可以用来建立留言板，关于页面等。
