### ISSUE TITLE
加密文章更新后没有删除访问权限

### ISSUE THREAD

**Issue by 1379** [halo-dev/halo#1518]
### What is version of Halo has the issue?

latest

### What database are you using?

MySQL 8.x

### What is your deployment method?

Fat Jar

### Your site address.

no

### What happened?

代码在这里：https://github.com/halo-dev/halo/blob/c3536cb8ce3be22acb597f1c0ce413c316c4429b/src/main/java/run/halo/app/service/impl/PostServiceImpl.java#L897

这里似乎删除了个寂寞。文章更新后，只删除了当前更新文章的人的权限，也就是说删除了管理员的权限。期望的行为应该是删除所有人对这篇文章的权限吧

**Comment by ruibaby** [comment]
欢迎提交 pr。

**Comment by 1379** [comment]
@ruibaby 首先我要确定下，这是一个bug吗？我的判断是正确的吗

**Comment by ruibaby** [comment]
已确认可以复现。

**Comment by JohnNiang** [comment]
@1379 建议提供一个复现步骤，我们好确定问题是一样的。

**Comment by 1379** [comment]
@JohnNiang 打开两个浏览器。其中一个加密文章，输入密码，可以访问。在另一个浏览器里使用管理员登录，修改加密文章的密码，然后回到刚才的浏览器，访问加密文章，不需要输入密码就可以访问。

**Comment by 1379** [comment]
这是我在看源码时发现的问题

**Comment by 1379** [comment]
有人正在修复这个问题吗，我可以提个pr

**Comment by ruibaby** [comment]
> 有人正在修复这个问题吗，我可以提个pr

没有

**Comment by 1379** [comment]
你们有开发者交流群组吗，我可以加入吗。最近看源码有一些自己的思考想交流下

**Comment by ruibaby** [comment]
> 你们有开发者交流群组吗，我可以加入吗。最近看源码有一些自己的思考想交流下

在 issue 交流即可。

**Comment by JohnNiang** [comment]
> 你们有开发者交流群组吗，我可以加入吗。最近看源码有一些自己的思考想交流下

建议公开交流，这样也能留下讨论记录，更多人能够看到你的想法，有机会和你探讨。

建议在留言的时候把观点或者问题描述清楚，给对方足够多的信息，这样能避免一些反复来回沟通。

**Comment by 1379** [comment]
我发先这个问题有些麻烦

诉求是在更新加密文章时删除所有人对这篇文章的权限。
现在权限是存储在缓存里的 key:sessionID -> value:postID 。
怎么根据postID 来反查 sessionID 呢？
如果把postID 作为key，value是HashSet，set里面存储sessionID，这样确实可以根据postID 反查到 sessionID，但是也引来了新的问题，因为不能对HashSet里的子项设置过期时间，这个HashSet可能会越来越大。。
有人有好的解决办法吗

**Comment by ruibaby** [comment]
cc @zhixiangyuan
