### ISSUE TITLE
Arbitrary file upload in the backend could cause a stored XSS vulnerability.

### ISSUE THREAD

**Issue by 1979139113** [halo-dev/halo#1522]
### What is version of Halo has the issue?

1.4.13

### What database are you using?

Other

### What is your deployment method?

Fat Jar

### What happened?

At the function point of uploading the avatar, any file can be uploaded, such as uploading an HTML file, which will cause a stored XSS vulnerability.

the file upload function points.

<img width="1545" alt="image" src="https://user-images.githubusercontent.com/24983597/140877494-781922ee-d1a7-4c51-afa3-de6e55bbbc17.png">

upload HTML file, show success.

<img width="1520" alt="image" src="https://user-images.githubusercontent.com/24983597/140877668-45aa7fa3-0ceb-4144-a79c-4b4080b60046.png">

access the HTML file, you can see that it is parsed by the browser.

<img width="995" alt="image" src="https://user-images.githubusercontent.com/24983597/140877908-7e50fb3d-7673-4ff5-999c-9f868d036d90.png">

If you upload malicious XSS code, you will get the user's token, like this

Payload

```html
<script>
	document.write(localStorage.getItem("halo__Access-Token"));
	document.write("</br></br>")
	document.write(localStorage.getItem("halo__USER"));
</script>
```

![image](https://user-images.githubusercontent.com/24983597/140878341-f16a567d-2225-4b12-abd8-dc81ea8597d5.png)

<img width="1175" alt="image" src="https://user-images.githubusercontent.com/24983597/140878445-9e41fa9c-6292-4ff6-b293-c59fc9fce694.png">

---
Analyzing the code, it can be seen that all suffixes can be uploaded, and there is no restriction on the suffix name of the file

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/24983597/140878939-e0f20b8d-ad31-47a1-abb9-a268c68c69e2.png">

Its recommended to only allow the parameter `extension` to be png.jpeg.jpg.gif.bmp or other image suffixes

<img width="1406" alt="图片" src="https://user-images.githubusercontent.com/24983597/140879209-00872904-4453-49d0-800d-f15a2d0ff168.png">

**Comment by ruibaby** [comment]
你好，目前此项目仅为单管理员设计，也就意味着目前只有管理员能操作后台。所以目前即便存在这样的问题，暂时我们也不会将优先级提高。

另外，您是否有阅读 https://github.com/halo-dev/halo/blob/master/SECURITY.md
