### ISSUE TITLE
Windows 下上传的图片路径不对

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#153]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [ ] [Halo 使用文档](https://docs.halo.run/)
- [ ] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [ ] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

RT

![50902DCACF250B7D0C32E630404D83DA](https://user-images.githubusercontent.com/21301288/57570350-6baa7c80-7433-11e9-86b0-aaa90b7cff2e.jpg)

**Comment by JohnNiang** [comment]
好的，知道问题所在，将尽快解决。
