### ISSUE TITLE
feat: 后台显示评论 MarkDown 源码，用评论来投稿 

### ISSUE THREAD

**Issue by JOCK-ONE** [halo-dev/halo#1532]
### 你当前使用的版本

v1.14.12

### 缘由
因为准备用 halo 搭建一个团队博客网站，发现还不支持多用户，有人提过了，但是还没有加，所以想到一个临时解决的办法，我创建一个专门的页面，其他人通过评论来投稿，但是还是需要我拿过来去文章里发布。

### 问题
现在的评论，在后台显示的渲染后的样子，我没有办法直接拿到文章里进行发布，希望可以增加一个查看评论原内容的按钮。

### 另一个想法
评论也增加一个转换为文章的按钮，直接把评论的内容复制或转化为文章，现成的文章审核功能

**Comment by JOCK-ONE** [comment]
![image](https://user-images.githubusercontent.com/63354237/141946828-cb4538eb-826c-48f2-9c62-de1409e7a331.png)

**Comment by JohnNiang** [comment]
Thanks for sharing your idea. This could be implemented in https://github.com/halo-dev/halo-admin. What do @ruibaby reckon?

**Comment by ruibaby** [comment]
可以考虑在后台支持编辑评论内容。

**Comment by jerry-shao** [comment]
I can help on the implementation of this feature if it's not assigned to anyone :)
