### ISSUE TITLE
前台search功能存在xss漏洞

### ISSUE THREAD

**Issue by lvyyevd** [halo-dev/halo#1533]
### 是什么版本出现了此问题？

最新版本

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Fat Jar

### 1、前台search存在xss
在java/run/halo/app/controller/content/ContentSearchController.java
![image](https://user-images.githubusercontent.com/46083201/141956813-23452e48-b5e2-4eaa-a98b-f88600d56d2d.png)
对keyword 没有任何过滤 访问
http://127.0.0.1:8090/search/page/1?keyword=%3C/title%3E%3Cscript%3Ealert(1)%3C/script%3E
![image](https://user-images.githubusercontent.com/46083201/141957123-b8f4860a-249f-4a79-b143-22fa1940b1a7.png)

希望可以早点修复

**Comment by guqing** [comment]
Hi @lvyyevd, thank you for your proposal, we will fix it right away.
