### ISSUE TITLE
云存储的上传方式改为客户端上传

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#1539]
### 你当前使用的版本

1.4.13

### 描述一下此特性

云存储的上传方式改为客户端上传，目前采用的服务端上传方式，会受限于服务器的带宽。

**Comment by kecikeci** [comment]
刚想提这个单子呢，哈哈哈。
建议配置为可选，服务端上传和客户端上传，且把上传地址和下载地址分开配置。
用公有云的对象存储，就可以用客户端直传上传方式。
用自建minio，可以使用服务端上传或客户端上传，在使用服务端上传时，可以走配置的内网上传地址。
这样更灵活些，且不影响老版本。大佬考虑下~

**Comment by ruibaby** [comment]
@kecikeci 感谢提供建议，非常值得参考。目前我们也只是提出这个问题，具体实现还得好好讨论下。

**Comment by kecikeci** [comment]
> @kecikeci 感谢提供建议，非常值得参考。目前我们也只是提出这个问题，具体实现还得好好讨论下。

感谢采纳！
还有上次提到的，希望对象存储上传能支持多级目录配置，现在都在一个文件夹下。可以采用固定的几个变量来配置，如{yyyy}/{MM}/{dd} 或 {yyyy}/{MM}，或直接写死按年月日上传

**Comment by gongjing666** [comment]
参考一下Cloudreve这个就好了，onedrive空间很足

**Comment by ruibaby** [comment]
此 issue 已过时，当前 Halo 2 采用的是 https://github.com/halo-dev/plugin-s3 插件，所以我将关闭此 issue。

/close
