### ISSUE TITLE
评论UA 未兼容window11的识别

### ISSUE THREAD

**Issue by Zinyan-Z** [halo-dev/halo#1543]
### 是什么版本出现了此问题？

1.4.12

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Fat Jar

### 在线站点地址

https://zinyan.com

### 发生了什么？

评论时，用户windwos 11的电脑发的信息，识别成了window10.

现在window 11 已经正式上线了一段时间了。

希望能够正确的显示客户端的版本信息。

### 附加信息

https://docs.microsoft.com/zh-cn/microsoft-edge/web-platform/how-to-detect-win11
 这是微软官网 针对UA 识别的参考文档。 
 
 User-Agent字符串不会进行更新以区分Windows 11和Windows 10。 我们不建议使用字符串User-Agent检索用户代理数据。 
 
 希望能够进行更新

**Comment by JohnNiang** [comment]
Good catch!

We will investigate it later.

![image](https://user-images.githubusercontent.com/16865714/142799765-1527ec5e-45e1-47f4-8879-847b24bbe31a.png)

**Comment by TimberKito** [comment]
Maybe can be used "sec-ch-ua-platform-version" to match the user's OS
refer: https://wicg.github.io/ua-client-hints/#sec-ch-ua-platform-version

**Comment by ruibaby** [comment]
> Maybe can be used "sec-ch-ua-platform-version" to match the user's OS refer: https://wicg.github.io/ua-client-hints/#sec-ch-ua-platform-version

pr welcome 😄

**Comment by TimberKito** [comment]
### 想确认一下，目前前端用户评论中关于用户信息渲染是基于comments表中的user_agent字段吗？
https://github.com/halo-dev/halo/blob/d965b6c3e785d5d850e27d949e150943e0015812/src/main/java/run/halo/app/model/entity/BaseComment.java#L92
![1637647167413](https://user-images.githubusercontent.com/57060551/142977597-4b088e7a-43ce-482d-8887-a0938e51cb39.png)

![1637647194849](https://user-images.githubusercontent.com/57060551/142977650-8eccbdc9-1ba8-4425-8ab9-f3e29195975e.png)

---

### 我目前有两个思路：

- 不弃用user-agent，拼接新的user-agent
因为弃用user-agent后会影响很多前端主题，也许我们可以在后端获取详细的用户操作系统如 "sec-ch-ua-platform-version"  然后拼接成一个新的user-agent传到数据库。

- 不弃用user-agent，新增sec-ch-ua-platform和sec-ch-ua-platform-version两个字段并提供相应的API给前端主题调用。

**Comment by ruibaby** [comment]
@TimberKito 似乎可以在前端解决此问题。

https://github.com/faisalman/ua-parser-js/pull/553

**Comment by TimberKito** [comment]
> @TimberKito 似乎可以在前端解决此问题。
> 
> [faisalman/ua-parser-js#553](https://github.com/faisalman/ua-parser-js/pull/553)

This item is so cool

**Comment by Bbqbbq123** [comment]
兄弟们这个配置怎么样

腾讯云 2核4g8m，才198元/3年
香港机器  2核4G30M  522元/1年

[https://curl.qcloud.com/lOaK729o](https://curl.qcloud.com/lOaK729o)


![输入图片说明](https://static.cnodejs.org/FlaOHQeotV-IPSFDVe17Q_xT4f7d)
