### ISSUE TITLE
如何自定义排序

### ISSUE THREAD

**Issue by 1379** [halo-dev/halo#1544]
### What is version of Halo has the issue?

latest

### What database are you using?

MySQL 8.x

### What is your deployment method?

Fat Jar

### Your site address.

no

### What happened?

这不是一个bug，我只是想请教个问题，但是issue类型只有bug report类型
问题如下：
`@GetMapping
    @ApiOperation("Lists links")
    public List<LinkDTO> listLinks(@SortDefault(sort = "team", direction = DESC) Sort sort) {
        return linkService.listDtos(sort.and(Sort.by(ASC, "priority")));
    }`
对于如上接口，如果我想通过请求参数自定义排序，比如根据create_time降序排列，该如何构造请求参数呢。目前我看halo的api文档，好像是不能自定义升降序是吗？

**Comment by ruibaby** [comment]
https://bbs.halo.run/d/1787-contentapi/13

**Comment by 1379** [comment]
对sort进行反序列化的源码在哪里，大佬清楚吗，我比较好奇spring boot对这里是如何处理的。我看了下Sort的源码，并没有找到这里的逻辑

**Comment by JohnNiang** [comment]
> 对sort进行反序列化的源码在哪里，大佬清楚吗，我比较好奇spring boot对这里是如何处理的。我看了下Sort的源码，并没有找到这里的逻辑

https://github.com/spring-projects/spring-data-commons/blob/main/src/main/java/org/springframework/data/web/PageableHandlerMethodArgumentResolver.java

**Comment by 1379** [comment]
@JohnNiang 非常感谢，我找了半天没看到spring 是在哪里处理参数的
