### ISSUE TITLE
支持文章搜索选项配置（搜索引擎）

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#1545]
### 你当前使用的版本

1.4.13

### 描述一下此特性

支持配置搜索引擎：

1. SQL(默认)
2. Algolia
3. ES
4. Solr
5. ...

参考：https://docs.requarks.io/search

**Comment by ruibaby** [comment]
我们预计在 2.0 首先提供基于 Meilisearch 的全文搜索方案。

https://github.com/halo-sigs/plugin-meilisearch

**Comment by Rainsheep** [comment]
期待大小写都能搜索&分词功能 | 模糊搜索。
其实对于一个博客来说，我们希望的是能搜索出包含自己所需文章的列表，然后自己点击查看想看的文章。
我们对于搜索准确度的要求没那么高。相关性低点也没关系。
但是我们搜索一个关键词，搜索不到(比如因为大小写原因)，就比较**了。

**Comment by ruibaby** [comment]
使用 https://github.com/halo-dev/halo/issues/2637 替代。

/close
