### ISSUE TITLE
主题无法正常更新

### ISSUE THREAD

**Issue by qinweizhao** [halo-dev/halo#1546]
### What is version of Halo has the issue?

1.4.13

### What database are you using?

MySQL 8.x

### What is your deployment method?

Docker

### What happened?

- 无法在线更新主题（网络异常）
 
![image](https://user-images.githubusercontent.com/65989648/143734479-0b47bffc-724d-4620-b949-71564b1d8902.png)

- 无法从主题包更新主题（上传错误）
 
![image](https://user-images.githubusercontent.com/65989648/143734498-4561b86e-b579-4b60-9087-5cc7c769adf6.png)

**Comment by JohnNiang** [comment]
请提供出现错误的时候，Halo 的错误日志。

**Comment by qinweizhao** [comment]
[log.txt](https://github.com/halo-dev/halo/files/7613588/log.txt)

**Comment by ruibaby** [comment]
@qinweizhao 看日志因为是你服务器无法正常连接到 Github 导致的，至于上传更新主题没有相关日志，所以我猜测是 Nginx 的上传大小限制的，你可以查看浏览器控制台的日志，看看是否是 Nginx 抛出的 413 错误。

**Comment by qinweizhao** [comment]
@ruibaby 我刚刚试了一下，又可以正常更新了。之前我试过几次（不是同一天)，都是失败的。

**Comment by ruibaby** [comment]
> @ruibaby 我刚刚试了一下，又可以正常更新了。之前我试过几次（不是同一天)，都是失败的。

在线吗？这个和你服务器是否可以正常和 Github 连接有很大关系。

**Comment by qinweizhao** [comment]
@ruibaby 可能是我的网络原因吧

**Comment by qinweizhao** [comment]
对的，在线更新

**Comment by ruibaby** [comment]
> 对的，在线更新

建议再看看本地上传更新

**Comment by qinweizhao** [comment]
@ruibaby 好的 我再观察观察

**Comment by ruibaby** [comment]
> @ruibaby 好的 我再观察观察

先关闭了，有问题可以再打开。

**Comment by qinweizhao** [comment]
@ruibaby 好
