### ISSUE TITLE
主题更新后部分功能失效

### ISSUE THREAD

**Issue by KingOfGitH** [halo-dev/halo#1547]
### 是什么版本出现了此问题？

1.4.12

### 使用的什么数据库？

MySQL 5.7

### 使用的哪种方式部署？

Docker

### 在线站点地址

https://halo.zhangsaner.com/

### 发生了什么？

首先在后台管理界面-》外观-》主题，点击默认主题的更多-》在线更新
![image](https://user-images.githubusercontent.com/45121245/143762803-76e89cee-514c-4dbc-b2b5-a74d09a05216.png)

此时提示更新成功

然后点击页面-》所有页面，会提示“你没有权限访问 /root/.halo/templates/themes/anatole/links.ftl”
![image](https://user-images.githubusercontent.com/45121245/143762840-b63a4846-eb97-4187-8884-33067b4d6083.png)

定位到服务器的相关目录，发现如下内容
![image](https://user-images.githubusercontent.com/45121245/143762914-1bcc25ee-c569-4a16-b7b0-c5336d48a11c.png)

可以发现更新后的目录变为caicai_anatole，但找的仍是anatole，我经过截图上的操作后恢复正常后，可再次复现

**Comment by ruibaby** [comment]
确实存在这样的问题，是因为首次初始化的时候，文件夹为 anatole，更新之后变成了主题的 id，目前你可以下载另外一个主题，切换到新的主题，然后重新启用默认的主题即可。
