### ISSUE TITLE
更改Halo默认主题为halo-theme-default

### ISSUE THREAD

**Issue by guqing** [halo-dev/halo#1548]
### 描述一下此特性

1. 更改halo的默认主题为`halo-theme-default `
2. 同时将 `resources/themes/anatole` 目录为`resources/themes/default`
3. 更改`HaloConst.DEFAULT_THEME_ID`的值为`default`

**Comment by LIlGG** [comment]
这个问题是否与 PR #1549 关联？？

**Comment by ruibaby** [comment]
我们现在已经有了 <https://github.com/halo-sigs/theme-default> 默认主题。
