### ISSUE TITLE
文章目录一级和二级目录问题

### ISSUE THREAD

**Issue by NSPlankton** [halo-dev/halo#1550]
### 是什么版本出现了此问题？

1.4.13

### 使用的什么数据库？

MySQL 5.7

### 使用的哪种方式部署？

Fat Jar

### 发生了什么？

在发布文章选择目录时，选择一个二级目录，对应一级目录不会添加该文章。我以为的正常逻辑应该是一级目录包含二级目录下的全部文章和一级目录下自身的文章。如果二级目录和一级目录的文章独立，那么目录级别的设置没有意义。
如下图所示：
![image](https://user-images.githubusercontent.com/81543669/144002010-06e563ee-d64d-40f3-831b-aff9ee5102ef.png)
一级目录是Java 二级目录是设计模式， 二级目录的文章并没有包含在一级目录中。
我尝试在编写文章保存目录设置时抓包，发现前端没有将一级目录的id传回。建议将父目录id一并传回。（即categoryIds 添加父目录id 传回服务器。）

这是我在使用halo过程中发现的问题，希望可以得到解答。辛苦了，开发大佬！

**Comment by NSPlankton** [comment]
我是一个编程小白，目前我能做到的解决办法是根据传入的二级目录id后台查到parentId然后加到categoryIds 中。虽然能够达到我的目的，但是感觉有点鸡肋~

**Comment by ruibaby** [comment]
目前确实没有做好这一块，我们后续会优化这个问题。
