### ISSUE TITLE
搜索功能增强

### ISSUE THREAD

**Issue by huasio** [halo-dev/halo#1551]
### 你当前使用的版本

1.4.13

### 描述一下此特性

是否可以给搜索功能加上高亮显示，目前的版本没有支持这个特性。

例如说，搜索关键词：java，那么在出现的搜索结果中，只要是匹配关键词的都加上颜色显示，这就是文字高亮显示。

**Comment by ruibaby** [comment]
感谢建议，我们会在这个 issue 开始开发的时候考虑此特性。https://github.com/halo-dev/halo/issues/1545

**Comment by huasio** [comment]
> 感谢建议，我们会在这个 issue 开始开发的时候考虑此特性。#1545

好的，感谢大佬。

**Comment by ruibaby** [comment]
see https://github.com/halo-dev/halo/issues/1545
