### ISSUE TITLE
整站备份再恢复后，博客地址无法修改，提示internal server error

### ISSUE THREAD

**Issue by xiaofengjue** [halo-dev/halo#1552]
### What is version of Halo has the issue?

1.4.8

### What database are you using?

H2

### What is your deployment method?

Fat Jar

### Your site address.

https://sillage.wang

### What happened?

整站备份迁移的时候，恢复后，访问登录，然后在后台修改博客地址时提示internal server error
希望能提供远程帮助

**Comment by JohnNiang** [comment]
希望能够提供详细的错误日志。

**Comment by xiaofengjue** [comment]
> 希望能够提供详细的错误日志。

查看哪的日志

**Comment by ruibaby** [comment]
> > 希望能够提供详细的错误日志。
> 
> 查看哪的日志

在工作目录有一个 logs 文件夹，提供 spring.log 的关键日志就行了。

**Comment by xiaofengjue** [comment]
> > > 希望能够提供详细的错误日志。
> > 
> > 
> > 查看哪的日志
> 
> 在工作目录有一个 logs 文件夹，提供 spring.log 的关键日志就行了。
方便远程一下吗，这个spring.log我看不出什么来

**Comment by ruibaby** [comment]
建议你停掉 Halo 服务，然后重新恢复备份试试。
