### ISSUE TITLE
考虑添加背景动图

### ISSUE THREAD

**Issue by ZYyyh-cool** [halo-dev/halo#1555]
### 你当前使用的版本

1.4.13

### 描述一下此特性

用户想要自定义添加背景动画图片比如彩带、樱花等特效

### 附加信息

参考 
vuepress-plugin-ribbon-animation

**Comment by guqing** [comment]
@ZYyyh-cool Hi @ZYyyh-cool, 非常抱歉， 我认为你应该找主题开发者来处理此事
