### ISSUE TITLE
标签支持默认随机颜色和自定义颜色

### ISSUE THREAD

**Issue by guqing** [halo-dev/halo#1559]
### 你当前使用的版本

1.4.3

### 描述一下此特性

现在的标签都是统一颜色， 当文章太多时在文章列表并不能很快区分文章的分类，就没有凸显出标签的作用，如果标签支持默认随机颜色和自定义颜色就可以优化这一点

**Comment by ruibaby** [comment]
非常好的建议，但是不建议支持随机颜色。

**Comment by guqing** [comment]
> 非常好的建议，但是不建议支持随机颜色。

可能我描述的不是很清楚，我说的随机颜色是指在标签新建时可以不指定颜色而默认一个颜色 并非在在文章列表展示时颜色随机

**Comment by JohnNiang** [comment]
> > 非常好的建议，但是不建议支持随机颜色。
> 
> 可能我描述的不是很清楚，我说的随机颜色是指在标签新建时可以不指定颜色而默认一个颜色 并非在在文章列表展示时颜色随机

+1

**Comment by ruibaby** [comment]
> > 非常好的建议，但是不建议支持随机颜色。
> 
> 可能我描述的不是很清楚，我说的随机颜色是指在标签新建时可以不指定颜色而默认一个颜色 并非在在文章列表展示时颜色随机

+1
