### ISSUE TITLE
前端渲染不了数据

### ISSUE THREAD

**Issue by zzc0309** [halo-dev/halo#1576]
### 是什么版本出现了此问题？

1.4.12

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Fat Jar

### 在线站点地址

https://zzc0309.top/archives/%E4%BB%BFgin%E6%A1%86%E6%9E%B6

### 发生了什么？

就是后台有返回数据,但是前端没有显示数据

有数据:
![image](https://user-images.githubusercontent.com/57063022/144865004-ec0eeca9-c229-45e5-a0e6-025e00b8fadb.png)

数据无显示:
![image](https://user-images.githubusercontent.com/57063022/144865128-e7957a31-a9d9-448d-9af7-db03e67c4862.png)

**Comment by ruibaby** [comment]
@zzc0309 在最新的 xue 主题版本已经修复，更新即可。https://github.com/xzhuz/halo-theme-xue/releases/tag/v1.3.0

**Comment by zzc0309** [comment]
solved
