### ISSUE TITLE
导出文章为 Markdown 文档失败,可能是由于文件名过长

### ISSUE THREAD

**Issue by Blackmesa-Canteen** [halo-dev/halo#1577]
### 是什么版本出现了此问题？

1.4.15

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Fat Jar

### 在线站点地址

https://www.996workers.icu

### 发生了什么？

尝试从Halo后台->小工具->博客备份->导出文章为 Markdown 文档, 网页UI说失败,浏览器控制台报500错误.

查看服务器后台日志,发现`Caused by: java.nio.file.FileSystemException: File name too long`异常.

可能是我有篇博客的标题有点长了,将近40个汉字,生成的`.md`文件名除了有中文名后面还跟了一长串拼音字符.

*另外,虽然网页UI提示说失败了,但是进入到tmp/halo-backup-markdown里,除了那个长标题的博文没有备份,其余的博文已经成功备份.*

### 附加信息

个人建议可以考虑博客标题输入限长; 对于已经存在的博客记录,可能截短下文件名会好点?

**Comment by ruibaby** [comment]
> 另外,虽然网页UI提示说失败了,但是进入到tmp/halo-backup-markdown里,除了那个长标题的博文没有备份,其余的博文已经成功备份.

或许针对这种情况进行优化会更好，也就是在前端提示哪些文章备份失败。

**Comment by JohnNiang** [comment]
> > 另外,虽然网页UI提示说失败了,但是进入到tmp/halo-backup-markdown里,除了那个长标题的博文没有备份,其余的博文已经成功备份.
> 
> 或许针对这种情况进行优化会更好，也就是在前端提示哪些文章备份失败。

备份的操作建议弄成异步的方式，这样也好同步每次备份的状态。
