### ISSUE TITLE
考虑独立 halo-admin 构建的文件

### ISSUE THREAD

**Issue by JohnNiang** [halo-dev/halo#158]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://docs.halo.run/)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [x] 添加新的特性或者功能
- [ ] 请求技术支持
---
考虑独立 `halo-admin` 构建的文件，利用 travis-ci 进行构建 `halo-admin`，然后将文件复制到相应的位置，最后完成打包。

**Comment by JohnNiang** [comment]
希望能够尽快完成这个功能，相关的测试基本上已经搞定了的。

**Comment by ruibaby** [comment]
@JohnNiang OJBK

**Comment by m1234ilu** [comment]
666

**Comment by JohnNiang** [comment]
初步独立出来了。等未来版本迭代之后就删除项目中已经构建好的 `halo-admin`。
