### ISSUE TITLE
希望增加钉钉接收评论通知的相关功能

### ISSUE THREAD

**Issue by HAHH9527** [halo-dev/halo#1585]
### 你当前使用的版本

1.4.13

### 描述一下此特性

通过钉钉的自定义webhook机器人推送新评论的通知
也可以做一些后台登录/危险操作的通知

或者暴露管理面板产生操作记录时，将通知发送至特定url中，事件发送到端由用户可以自定义处理。
这样用户可以按需发送到不同的机器人或者其他地方。

**Comment by ruibaby** [comment]
感谢你的建议，但是目前不考虑添加。自定义 Webhook 我们会在后面的版本中提供。

**Comment by HAHH9527** [comment]
> 感谢你的建议，但是目前不考虑添加。自定义 Webhook 我们会在后面的版本中提供。

感谢回复。
自定义webhook也是可以的，可以达成一样的效果。
主要是因为邮箱相比与IM软件打开和使用的频次更低，宝塔面板上也有钉钉的相关通知的设置，然后才有了这个想法。

**Comment by ruibaby** [comment]
@HAHH9527 等我们把多用户权限这块完成之后可能就会考虑此特性了。

**Comment by savingrun** [comment]
可以往多渠道自定义格式webhook思路想，配合事件中心（每个事件对应几个关键字的形式拖拉对应关键字）触发webhook，哈哈帮公司做消息中心的时候想到的方案，可以考虑一波，不止发webhook（这只是一个渠道而已）还可以发短信/微信模板消息/邮件都统一起来 dog.jpg

**Comment by ruibaby** [comment]
目前社区已经提供了类似的插件：

- https://github.com/wxyShine/plugin-webhook
- https://github.com/monyuan/notify-me

/close
