### ISSUE TITLE
非根目录下部署问题

### ISSUE THREAD

**Issue by ivicel** [halo-dev/halo#159]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://docs.halo.run/)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

/admin/index.html 打包后代码

```html
<title>Halo Dashboard</title>
<link href=/css/chunk-13e4f411.8481e8b4.css rel=prefetch>
<link href=/css/chunk-14e8932a.b6783003.css rel=prefetch>
<link href=/css/chunk-1a112dee.45475c5a.css rel=prefetch>
```

后台 halo-admin 打包时使用绝对路径, 这样会导致如果部署在非根目录下时, 访问后台页面时变成空白. 比如在 `application.yml` 设置 `context-path` 来测试

```
server:
    servlet:
        context-path: /halo
```

ftl 模版中也存在这样的问题, 比如 `install.ftl`

```html
<link rel="stylesheet" href="/static/halo-admin/plugins/bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" href="/static/halo-admin/css/AdminLTE.min.css">
<link rel="stylesheet" href="/static/halo-admin/plugins/animate/animate.min.css">
<link rel="stylesheet" href="/static/halo-admin/plugins/bootstrapvalidator/css/">
```

**Comment by ruibaby** [comment]
所以你的需求是什么？

**Comment by ivicel** [comment]
@ruibaby 
如果把博客部署在非根目录下, 比如 http://localhost:8087/blog 
那么博客是不可访问的

**Comment by ruibaby** [comment]
@ivicel 哦哦，好的。

**Comment by JohnNiang** [comment]
@ivicel 这种需求其实可以通过 nginx 反向代理来实现。halo 默认使用的嵌入式服务器，所以设置 context-path 的意义并不大。

另外，halo-admin 实际上是可以独立部署的。

**Comment by ruibaby** [comment]
@JohnNiang 嗯，请考虑所谓的小白，我只是想尽可能减少部署成本。如果你想那样独立部署或是其他的方案，是可以自己动手操作的。

**Comment by ivicel** [comment]
如果你把这个打个一个 war 包直接扔进一个 tomcat 也是会产生路径问题的
像 ftl 模版应该使用 `@spring.url` 这样 macro 来处理 链接, 这是考虑程序的健壮性

**Comment by ruibaby** [comment]
@ivicel 好的哦，非常感谢你的建议。

**Comment by ruibaby** [comment]
@ivicel 如果你有时间的话，可以参与一下完善哦，目前需要开发的东西太多，有些东西可能顾忌不上。

**Comment by JohnNiang** [comment]
为了提供一个部署的便捷性，我们打包了 `halo-admin` 到 `halo` 中，`admin/index.html` 无法感知用户配置的 `server.servlet.context-path`。再者，主题文件中需要修改的地方太多，也是给主题创作者增加相应的负担。

在`程序的健壮性`和`便捷性`的权衡之下，我们可能以不提供 `war` 包来避免这个问题。

**Comment by JohnNiang** [comment]
@ivicel **halo-admin** 我们无能为力，但是**主题部分**，我们可以考虑修复这个问题。
