### ISSUE TITLE
请问部署在docker中怎么调整-Xmx

### ISSUE THREAD

**Issue by wcccWT** [halo-dev/halo#1590]
### 是什么版本出现了此问题？

1.4.15

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

请问部署在docker中怎么调整-Xmx,已经翻过官方文档以及issue,再百度后均没有找到答案,,镜像是从仓库pull的latest版本

**Comment by ruibaby** [comment]
@wcccWT https://bbs.halo.run/d/1956-docker-xmx/2

**Comment by wcccWT** [comment]
> @wcccWT https://bbs.halo.run/d/1956-docker-xmx/2

由于给出了Dockerfile地址,以为让自己构建镜像的时候修改,,,根据你给的参数加上,已经可以了,感谢
