### ISSUE TITLE
用IDEA docker插件打包，报错no main manifest attribute, in application.jar

### ISSUE THREAD

**Issue by alun1** [halo-dev/halo#1591]
### 是什么版本出现了此问题？

1.4.13

### 使用的什么数据库？

MySQL 5.7

### 使用的哪种方式部署？

Docker

### 发生了什么？

用IDEA docker插件打包，报错no main manifest attribute, in application.jar

### 相关日志输出

```shell
no main manifest attribute, in application.jar
Error response from daemon: The command '/bin/sh -c java -Djarmode=layertools -jar application.jar extract' returned a non-zero code: 1
Failed to deploy 'halo Dockerfile: Dockerfile': Can't retrieve image ID from build stream
```

**Comment by alun1** [comment]
Execution failed for task ':bootBuildImage'.
> assert System.getenv("DOCKER_USERNAME") != null
                |                         |
                null                      false

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by JohnNiang** [comment]
需要提前构建 Jar 包才能够使用 Dockerfile 打包：

```bash
./gradlew clean build
```

**Comment by alun1** [comment]
`Execution failed for task ':checkstyleMain'.
> Checkstyle rule violations were found. See the report at: file:///C:/Users/Administrator/IdeaProjects/halo/build/reports/checkstyle/main.html
  Checkstyle files with violations: 281
  Checkstyle violations by severity: [warning:785, error:12]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

`
已经导入插件和风格设置了
