### ISSUE TITLE
什么情况进去了能发表文章，但查看不了文章？是不是要去下个主题

### ISSUE THREAD

**Issue by tanyixiao** [halo-dev/halo#1594]
### What is version of Halo has the issue?

1

### What database are you using?

H2

### What is your deployment method?

Fat Jar

### What happened?

HTTP ERROR 400 Default theme: caicai_anatole was not found! URI:	/ STATUS:	400 MESSAGE:	Default theme: caicai_anatole was not found! SERVLET:	dispatcherServlet CAUSED BY:	run.halo.app.exception.ThemeNotFoundException: Default theme: caicai_anatole was not found! Caused by:

### Relevant log output

```shell
HTTP ERROR 400 Default theme: caicai_anatole was not found! URI:	/ STATUS:	400 MESSAGE:	Default theme: caicai_anatole was not found! SERVLET:	dispatcherServlet CAUSED BY:	run.halo.app.exception.ThemeNotFoundException: Default theme: caicai_anatole was not found! Caused by:
```

**Comment by ruibaby** [comment]
是否是通过下载的构建的 Jar 部署的？

**Comment by tanyixiao** [comment]
idea 本地运行还没部署






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ryan ***@***.***&gt;; 
发送时间: 2021年12月12日(星期天) 晚上10:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [halo-dev/halo] 什么情况进去了能发表文章，但查看不了文章？是不是要去下个主题 (Issue #1594)





 
是否是通过下载的构建的 Jar 部署的？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ruibaby** [comment]
没有 init submodule，本地克隆源码运行建议看看开发文档。https://docs.halo.run/developer-guide/core/prepare#%E5%85%8B%E9%9A%86%E9%A1%B9%E7%9B%AEoptional

**Comment by tanyixiao** [comment]
1.git clone https://github.com/halo-dev/halo
2.git submodule init
3.git submodule update
4.在IDE中重新打开halo项目, 正常启动项目,。
