### ISSUE TITLE
建议给菜单添加排序功能

### ISSUE THREAD

**Issue by NGLSL** [halo-dev/halo#1596]
### 你当前使用的版本

1.4.15

### 描述一下此特性

菜单只能编辑一些基本信息，它的默认排序不是我想要的，建议增加一个排序，指定排序大小，能正序或者逆序。

### 附加信息

![image](https://user-images.githubusercontent.com/40338580/146015326-0c7b57b8-9178-4e70-96cf-1274fb8c58bd.png)

**Comment by ruibaby** [comment]
当前菜单是支持拖动排序的，按住名称左边那个图标就可以拖动了，拖动完成排序之后点击右上角保存即可。

**Comment by NGLSL** [comment]
好的，暂无其他问题。
