### ISSUE TITLE
附件上传失败，希望可以帮忙分析下问题

### ISSUE THREAD

**Issue by BennettChina** [halo-dev/halo#1597]
### 是什么版本出现了此问题？

1.4.16

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 在线站点地址

https://hibennett.cn

### 发生了什么？

附件上传时传输时间大于10s就会失败，返回的504 Gateway Timeout。我在网上搜索了一些nginx的超时配置，但没有效果。希望可以帮忙看看我的nginx配置问题出在哪里。

- `nginx.conf`

```conf
user  nginx;
worker_processes  1;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  180;
    send_timeout  180;

    gzip  on;
    gzip_min_length  1k;
    gzip_buffers     16 8k;
    gzip_http_version 1.1;
    gzip_comp_level 6;
    gzip_types       text/plain application/x-javascript text/css application/xml text/javascript application/x-httpd-php application/javascript application/json;
    gzip_disable "MSIE [1-6]\.";
    gzip_vary on;

    include /etc/nginx/conf.d/*.conf;


    server {
  	listen   80;
	
	server_name hibennett.cn www.hibennett.cn;

	client_max_body_size 100m;

	root html;
	index index.html index.htm;
	
	location / {
	    proxy_pass  http://halo:8090/;
	    proxy_redirect off;
	    proxy_set_header   Host   $host;
	    proxy_set_header X-Real-IP $remote_addr;
	    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
           
            client_body_timeout 3m;
            proxy_connect_timeout     180s;
            proxy_read_timeout      3m;
            proxy_send_timeout      3m;
	}
    }
```

`halo`与`nginx`都是通过`docker`启动的，放在同一个网络内。

附件上传提示超时失败后重新刷新页面刚上传失败的文件也可以加载出来，可以看出是在halo服务内上传成功了的。

### 相关日志输出

```shell
halo服务无日志输出，开启debug级后日志刷的很快，也并无看到异常日志。
```

### 附加信息

前端的响应头是下面的这些

```
content-length: 568
content-type: text/html
date: Fri, 17 Dec 2021 07:14:55 GMT
server: JSP3/2.0.14
x-error-info: Internal_Read_Timeout
```

**Comment by BennettChina** [comment]
上传的是一个10M以内的图片，在我测试时一个1.5M的图片也会上传超时。

**Comment by BennettChina** [comment]
我突然发现似乎是前端封装的http-client设置的超时时间，应该我刚才刷新附件列表页面时也返回网络异常，查看控制台发现打印的日志里刚好有个10000ms的值。

![image](https://user-images.githubusercontent.com/48208644/146506687-6f65bbc8-9009-450a-abc1-2418f1db858d.png)

**Comment by ruibaby** [comment]
@BennettChina 请问是自己构建的 Docker Image 吗？

**Comment by BennettChina** [comment]
> @BennettChina 请问是自己构建的 Docker Image 吗？

不是的

**Comment by ruibaby** [comment]
@BennettChina 你可以先在 Console 的 Network 看具体请求返回的 Response，看看是 Nginx 返回的还是后端返回的内容。

**Comment by BennettChina** [comment]
code为-1时网络请求是下面这样的，直接就取消了。
![image](https://user-images.githubusercontent.com/48208644/146508096-3ce80608-a67d-4a16-99e7-19243ee642ba.png)
![image](https://user-images.githubusercontent.com/48208644/146508124-6a54d1f3-f99d-42c3-b1e6-f3d918ea7cf4.png)

上传的504应该是Nginx返回的，应该不是后端返回的，如果后端返回504那应该会输出ERROR级日志吧？但是并没有在halo的日志中看到任何日志。

**Comment by ruibaby** [comment]
那你可以先看看 nginx 的 access log

**Comment by BennettChina** [comment]
> 那你可以先看看 nginx 的 access log

我更倾向于是前端的这个10s超时设置导致的，因为所有的图片上传时间都在10s左右，无论是1.5M还是4、5M的图片，太巧合了。

**Comment by ruibaby** [comment]
> > 那你可以先看看 nginx 的 access log
> 
> 我更倾向于是前端的这个10s超时设置导致的，因为所有的图片上传时间都在10s左右，无论是1.5M还是4、5M的图片，太巧合了。

我们设置的 24h，刚刚我也测试了，并不会出现这种问题。这个情况你只需要通过 ip 和端口访问进行测试即可。

**Comment by BennettChina** [comment]
> > > 那你可以先看看 nginx 的 access log
> > 
> > 
> > 我更倾向于是前端的这个10s超时设置导致的，因为所有的图片上传时间都在10s左右，无论是1.5M还是4、5M的图片，太巧合了。
> 
> 我们设置的 24h，刚刚我也测试了，并不会出现这种问题。这个情况你只需要通过 ip 和端口访问进行测试即可。

我用IP直连测试了下确实没有再出现超时，看来还是Nginx的配置问题。😩

**Comment by BennettChina** [comment]
Nginx的`access.log`中上传接口：

[17/Dec/2021:07:48:10 +0000] "POST /api/admin/attachments/upload HTTP/1.1" 499 0 "https://hibennett.cn/manage/index.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"

**Comment by BennettChina** [comment]
找到问题了，是我用的七牛云的全站加速导致的，我直接把域名解析到我自己服务器不走七牛云就不会超时了。

**Comment by ruibaby** [comment]
> 找到问题了，是我用的七牛云的全站加速导致的，我直接把域名解析到我自己服务器不走七牛云就不会超时了。

你可以配置过滤掉 /api/admin/*

**Comment by BennettChina** [comment]
> > 找到问题了，是我用的七牛云的全站加速导致的，我直接把域名解析到我自己服务器不走七牛云就不会超时了。
> 
> 你可以配置过滤掉 /api/admin/*

七牛云好像没有这种配置方式，之前我就找过了。现在配置的是全站不缓存，只缓存指定的文件格式（七牛默认配置会导致任何借口都调用到缓存）。我准备新加一个域名的解析去处理这个问题。
