### ISSUE TITLE
本地图库 突然无法识别

### ISSUE THREAD

**Issue by Rebooti** [halo-dev/halo#1598]
### What is version of Halo has the issue?

1.48

### What database are you using?

H2

### What is your deployment method?

Docker

### Your site address.

849052352.xyz

### What happened?

本地图库 突然无法显示，图片丢失

### Additional information

![Uploading 20211217181621.jpg…]()

**Comment by Rebooti** [comment]
首页/附件 上传到本地数据库的图片，无法显示，照片丢
![20211217181621](https://user-images.githubusercontent.com/84120847/146530302-edd3fefd-f0d2-4821-bfa8-8948a65b4ff9.jpg)
失

**Comment by ruibaby** [comment]
工作目录的 upload 目录里面是否有文件？

**Comment by Rebooti** [comment]
没有文件 主服务器和备份的服务器很久没有动数据了

**Comment by ruibaby** [comment]
@Rebooti 那我们也无法排查了，程序内是不会对这个目录做清空的。建议查查是否有其他操作。
