### ISSUE TITLE
主站为80，分类文章密码验证跳8090端口

### ISSUE THREAD

**Issue by MinisterZ** [halo-dev/halo#1599]
### 是什么版本出现了此问题？

1.4.16

### 使用的什么数据库？

MySQL 5.7

### 使用的哪种方式部署？

Docker

### 在线站点地址

http://150.158.96.40/

### 发生了什么？

主站为80端口，文章分类“随想录”，验证密码时跳8090端口

**Comment by ruibaby** [comment]
在博客设置的博客地址修改为实际访问地址即可。

**Comment by MinisterZ** [comment]
感谢您，已解决！
