### ISSUE TITLE
cdn.jsdelivr.net这个地址资源加载 有些地方无法打开

### ISSUE THREAD

**Issue by stevenliuit** [halo-dev/halo#1600]
### 你当前使用的版本

1.4.16

### 描述一下此特性

在本地打开网页无法加载cdn.jsdelivr.net对应的文件 有其他方式嘛？

**Comment by ruibaby** [comment]
https://github.com/jsdelivr/jsdelivr/issues/18348

jsdelivr 中国区的 SSL 证书出问题了，目前只能等待修复了。

**Comment by HAHH9527** [comment]
> [jsdelivr/jsdelivr#18348](https://github.com/jsdelivr/jsdelivr/issues/18348)
> 
> https://status.jsdelivr.com
> 
> jsdelivr 中国区的 SSL 证书出问题了，目前只能等待修复了。

一个想法：
是否可以在后续版本加个安全模式呢(不采用CDN加速打开admin页面的入口)，防止这样的情况再次出现，导致后台面板进不去

**Comment by ruibaby** [comment]
@HAHH9527 我们后续会提供可选配置（使用本地资源还是 CDN），或者取消使用 CDN。

**Comment by ruibaby** [comment]
似乎已经好了，大家可以试试。

**Comment by JohnNiang** [comment]
> 似乎已经好了，大家可以试试。

Not yet.

![image](https://user-images.githubusercontent.com/16865714/146745597-b2a49d44-3e23-4bcd-baaa-e6129793caff.png)

**Comment by JohnNiang** [comment]
> 似乎已经好了，大家可以试试。

Work very well currently.
