### ISSUE TITLE
后台管理会考虑加入对图库的管理吗？/photos

### ISSUE THREAD

**Issue by MinisterZ** [halo-dev/halo#1603]
### 你当前使用的版本

1.4.16

### 描述一下此特性

现在附件能添加到图库，但后台管理系统没有图库入口，看API文档试了试是/photos，目前只能查看不能删改。希望在文档能增加一些直接暴露的接口信息包括/about,/archives,/photos,/links之内的说明。希望增加对图库的管理，后续增加接口升级为图床。

**Comment by ruibaby** [comment]
![image](https://user-images.githubusercontent.com/21301288/147033691-23757395-f3fd-4fd8-8811-66e506d79e88.png)
