### ISSUE TITLE
文章内容不显示

### ISSUE THREAD

**Issue by Jxinx** [halo-dev/halo#1607]
### 是什么版本出现了此问题？

1.4.2

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Fat Jar

### 在线站点地址

https://jxinx.tech

### 发生了什么？

文章详情页，文章内容不显示，被加上了display:none，控制台报错如下：
![image](https://user-images.githubusercontent.com/29894400/147112799-d5d32317-1cec-437a-a02a-7674dfdec37c.png)

**Comment by ruibaby** [comment]
升级主题。https://github.com/xzhuz/halo-theme-xue/releases

**Comment by Jxinx** [comment]
升级v1.3.0已解决。https://github.com/xzhuz/halo-theme-xue/releases
