### ISSUE TITLE
按照升级说明中升级系统到 1.4.16 后，在『关于』页面显示的依然是1.4.15版本

### ISSUE THREAD

**Issue by brucewu** [halo-dev/halo#1612]
### 是什么版本出现了此问题？

1.4.15

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Fat Jar

### 发生了什么？

按照升级说明中升级系统到 1.4.16 后，在『关于』页面显示的依然是1.4.15版本
已经重启了系统，升级也是移除原有jar文件后重新下载的
浏览器测试时使用的是打开开发者工具，并且停用缓存
api/admin/environments  这里返回的json数据也显示是 1.4.15 版本

**Comment by ruibaby** [comment]
请提供一下站点地址。

**Comment by brucewu** [comment]
好了，可能是缓存
