### ISSUE TITLE
gravatar.com 被墙，头像显示问题

### ISSUE THREAD

**Issue by v587xpt** [halo-dev/halo#1616]
### What is version of Halo has the issue?

halo-1.4.10.jar

### What database are you using?

MySQL 8.x

### What is your deployment method?

Fat Jar

### Your site address.

http://blog.v587xpt.top/

### What happened?

![image](https://user-images.githubusercontent.com/37898515/148518978-65f41645-4b38-4e90-a2f9-705204b53491.png)
显示超时

### Additional information

查询 gravatar.com  后，发现是全球头像服务，并且在文章的最后可以看到，头像没有显示，判断是头像请求出错了；
搜索后，网上给出了答案，gravatar.com 头像服务因为在国外，被限制了；
不知道有没有好的解决办法；

**Comment by ruibaby** [comment]
评论的头像可以按照这个帖子修改。https://bbs.halo.run/d/1455

管理员的头像可以去个人资料修改。

**Comment by v587xpt** [comment]
非常感谢，就在提交问题后，找到了您说的这个链接，并解决了问题；
现在我的博客在优化后，访问速度提高了很过；
