### ISSUE TITLE
内部资源取消使用 jsDelivr CDN

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#1619]
### 你当前使用的版本

1.4.16

### 描述一下此特性

内部资源取消使用 jsDelivr CDN，所有静态资源均由服务器提供，可以离线使用，也可以让使用者有自行优化的空间。

包括以下两个部分：

- admin
- anatole 默认主题

**Comment by niujinkai** [comment]
支持~
希望能够尽快拜托打开三分钟的困扰 ~

**Comment by niujinkai** [comment]
同时希望能够添加自定义cdn地址，可以自行将js上传至自己的cdn 博客只需要配置地址进行加速就行 ~

**Comment by ruibaby** [comment]
> 同时希望能够添加自定义cdn地址，可以自行将js上传至自己的cdn 博客只需要配置地址进行加速就行 ~

目前后台无法很方便做到自定义，CDN 地址需要在打包阶段就配置。如果我们改为了本地资源，你可以考虑配置全站 CDN。

**Comment by ruibaby** [comment]
1.4.17 已经取消使用 jsDelivr CDN，https://github.com/halo-dev/halo/releases/tag/v1.4.17

在此感谢 jsDelivr 以往的贡献。
