### ISSUE TITLE
cdn.jsdelivr.net网络已经出现问题，能否将静态资源文件本地化？

### ISSUE THREAD

**Issue by niujinkai** [halo-dev/halo#1626]
### 是什么版本出现了此问题？

版本：1.4.17 数据库：MySQL 5.7.18-txsql-log 运行模式：production User Agent：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36 Edg/97.0.1072.55

### 使用的什么数据库？

MySQL 5.7

### 使用的哪种方式部署？

Docker

### 在线站点地址

www.niujinkai.com

### 发生了什么？

cdn.jsdelivr.net网络已经出现问题，能否将静态资源文件本地化
静态资源加载很慢~

### 相关日志输出

```shell
38 次请求
已传输2.7 MB
3.6 MB 条资源
完成：30.02 秒
DOMContentLoaded：29.99 秒
加载：30.01 秒
```

### 附加信息

![image](https://user-images.githubusercontent.com/97371434/148951063-d673a8bb-1465-4761-8877-811808b5db50.png)
![Uploading image.png…]()

**Comment by ruibaby** [comment]
@niujinkai 你好，请向你所使用的主题提交 issue。

**Comment by niujinkai** [comment]
@ruibaby 抱歉 提交失误了 已经向主题提交了 已经关闭了 或者可以删除不 这个作废 实在抱歉
