### ISSUE TITLE
备份无法下载

### ISSUE THREAD

**Issue by ZONGQUAN-HU** [halo-dev/halo#1627]
### 是什么版本出现了此问题？

1.4.11

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Fat Jar

### 在线站点地址

quanquan.org.cn

### 发生了什么？

- 情况1：使用域名登录后台，在后台备份成功后，点击文件名称下载，提示：
![image](https://user-images.githubusercontent.com/36360150/148957459-c304baf3-3370-4279-a4f8-6233aa7962da.png)

- 情况2：使用IP地址直接登录后台，点击文件名称下载，转跳结果如下：
```
{"status":401,"message":"未登录，请登录后访问","devMessage":null,"data":null}
```

**Comment by ruibaby** [comment]
又拍云需要开启参数跟随。

**Comment by ZONGQUAN-HU** [comment]
那直接用IP地址访问出现这个问题是什么情况？

**Comment by guqing** [comment]
@ZONGQUAN-HU 因为没有在请求头带上token

**Comment by ruibaby** [comment]
> 那直接用IP地址访问出现这个问题是什么情况？

是通过点击备份名称下载的吗？

**Comment by ZONGQUAN-HU** [comment]
@guqing 在后台点击为什么不自己带token？

**Comment by ZONGQUAN-HU** [comment]
@ruibaby 是

**Comment by ruibaby** [comment]
@ZONGQUAN-HU 可能是因为最终的下载文件路径是根据你所填的博客地址生成的（这样就是直接访问的域名链接），你目前只需要解决第一个问题即可。

**Comment by ruibaby** [comment]
这可能就是你使用的全站 CDN 带来的问题了，建议 CDN 排除掉 /api/admin 下的所有请求。

**Comment by ZONGQUAN-HU** [comment]
好艰难啊，吐了

**Comment by ZONGQUAN-HU** [comment]
强改后台域名url为IP地址。且加端口，直接下载成功
