### ISSUE TITLE
考虑集成 更完善的markdown编辑器么

### ISSUE THREAD

**Issue by alangong114** [halo-dev/halo#163]
是否考虑集成 这个markdown编辑器 支持流程图之类的。

https://pandao.github.io/editor.md/
 
----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] 添加新的特性或者功能

**Comment by ruibaby** [comment]
@alangong114 抱歉哦，这个编辑器已经非常久没有更新了，问题很多。我们暂时不能考虑集成这个editor。目前我们所使用的这个编辑器其实已经满足大部分需求了。
