### ISSUE TITLE
请求首页时候,发现了一个非常慢的请求http://cn.gravatar.com/ 速度特别慢，有时候打不开。

### ISSUE THREAD

**Issue by zhangqiangeek** [halo-dev/halo#1631]
### 是什么版本出现了此问题？

1.4.17

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Fat Jar

### 在线站点地址

evilhex.com

### 发生了什么？

![image](https://user-images.githubusercontent.com/13536014/149504011-f41a4ce2-3a93-4c8a-8da9-fbed6a2daf4e.png)

**Comment by ruibaby** [comment]
你可以在后台个人资料中点击头像手动上传头像。评论头像你可以在评论设置中设置 Gravatar 源，参考 https://bbs.halo.run/d/1455

**Comment by zhangqiangeek** [comment]
> 

这个地方，加载的时间特别长。Favicon的图标已经是自己手动上传的。但是访问了这个链接http://cn.gravatar.com/avatar/1e4ac2ee5ad4505831fbc2d5c8d3d6fa?s=256&d=mm。替换源之后，加载的时间仍然比较长。
![image](https://user-images.githubusercontent.com/13536014/149508693-f68a89ae-e6d5-45cf-a88e-e6971384291e.png)

**Comment by ruibaby** [comment]
@zhangqiangeek 你需要去后台的个人资料修改修改，我们默认使用的 Gravatar 公共头像服务，但目前在国内几乎已经无法正常访问。

<img width="570" alt="Screen Shot 2022-01-14 at 11 36 38 PM" src="https://user-images.githubusercontent.com/21301288/149542214-2006da91-0c38-4b6e-92d0-fa214f285dbd.png">

**Comment by ruibaby** [comment]
@zhangqiangeek 你好，请问此问题是否已经解决呢？

**Comment by ruibaby** [comment]
先关闭了，后续有问题可以 reopen 或者新开 issue。
