### ISSUE TITLE
cdn.jsdelivr.net 不稳定，1.4.17说是取消了，但是我下载源代码编译，还是有呢？

### ISSUE THREAD

**Issue by alun1** [halo-dev/halo#1633]
### 是什么版本出现了此问题？

1.7

### 使用的什么数据库？

MySQL 5.7

### 使用的哪种方式部署？

Fat Jar

### 发生了什么？

cdn.jsdelivr.net 不稳定，1.4.17说是取消了，但是我下载源代码编译，还是有呢？我感觉这太危险了，当是我不是web程序员，不知道该怎么办

**Comment by JohnNiang** [comment]
我们没有发布过 1.7 版本，再次确认一下你的版本呢。

**Comment by alun1** [comment]
不好意思，是1.4.17

**Comment by ruibaby** [comment]
自行编译请切换到对应 tag 进行编译，https://github.com/halo-dev/halo/tags

master 是我们的开发分支。
