### ISSUE TITLE
页面当中的发表日志的附件库问题

### ISSUE THREAD

**Issue by niujinkai** [halo-dev/halo#1634]
### 是什么版本出现了此问题？

版本：1.4.17 数据库：MySQL 5.7.18-txsql-log 运行模式：production User Agent：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36 Edg/97.0.1072.62

### 使用的什么数据库？

MySQL 5.7

### 使用的哪种方式部署？

Docker

### 在线站点地址

https://www.niujinkai.com

### 发生了什么？

在使用博客后台当中的 页面 - 所有页面 - 日志页面 进行日志发表的时候 发表日志可以点击附件库 正常理解应为插入图片 但是点击附件库 选择对应的图片之后 无法插入图片 只有查看附件信息和删除附件的选项 。不知道是逻辑如此 还是功能问题 希望予以查看 感谢 ！

### 相关日志输出

```shell
null 未报异常 故无日志输出
```

### 附加信息

![image](https://user-images.githubusercontent.com/97371434/150611950-5b4d3a45-708a-432b-b165-e541d1f2ac6b.png)

**Comment by ruibaby** [comment]
你好，目前逻辑确实是这样，你可以在列表右键附件复制 Markdown 格式的链接也可以在详情里复制，但不支持点击选择。已经计划重构，请关注 https://github.com/halo-dev/halo-admin/issues/373#issuecomment-973967707

**Comment by ruibaby** [comment]
正在重构，如有需要请关注此 PR：https://github.com/halo-dev/halo-admin/pull/420
