### ISSUE TITLE
java1.8不香吗？ 为什么要升级到11呢？

### ISSUE THREAD

**Issue by wajncn** [halo-dev/halo#1637]
### What is version of Halo has the issue?

ff

### What database are you using?

H2

### What is your deployment method?

Fat Jar

### What happened?

java1.8不香吗？ 为什么要升级到11呢？java1.8不香吗？ 为什么要升级到11呢？

**Comment by ruibaby** [comment]
你好，请问你是想单纯的过来口嗨呢还是想交流，我在你的文字中没有看出任何交流的意思。这里是 issues，请不要乱提交无关的东西。

如果你是想交流，请参见我们之前的讨论：https://bbs.halo.run/d/1208-jdk811/5 。补充一句：你也可以完全把 Halo 停留在 1.4.2，就像你对 Java 升级的态度一样。

如果你只是想口嗨，再次提醒不要来 GitHub issues，谢谢。

**Comment by wajncn** [comment]
大哥， 我就是口嗨的。
在 2022年1月27日 +0800 16:25，Ryan Wang ***@***.***>，写道：

**Comment by guqing** [comment]
> 大哥， 我就是口嗨的。
> 在 2022年1月27日 +0800 16:25，Ryan Wang ***@***.***>，写道：
> > Closed #1637.
> > —
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> > Triage notifications on the go with GitHub Mobile for iOS or Android.
> > You are receiving this because you authored the thread.Message ID: ***@***.***>
> 

那挺音容犹在的 整的

**Comment by wajncn** [comment]
大哥你这么说 我等会还得提10个issues 纪念下你
在 2022年1月27日 +0800 16:30，王进 ***@***.***>，写道：
