### ISSUE TITLE
AttachmentService Exception

### ISSUE THREAD

**Issue by wajncn** [halo-dev/halo#1638]
### 是什么版本出现了此问题？

1.4.17

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker

### 发生了什么？

启动报错

**Comment by ruibaby** [comment]
请提供完整日志。

**Comment by guqing** [comment]
相鼠有皮，人而无仪，人而无仪，不死何为
相鼠有齿，人而无止，人而无止，不死何俟

**Comment by wajncn** [comment]
大哥说的好， 老子等会在给奖励10个issues
在 2022年1月27日 +0800 16:42，Ryan Wang ***@***.***>，写道：
