### ISSUE TITLE
备份成功，下载失败的bug

### ISSUE THREAD

**Issue by Memoryeva** [halo-dev/halo#1641]
### What is version of Halo has the issue?

1.4.13

### What database are you using?

MySQL 8.x

### What is your deployment method?

Docker

### Your site address.

https://notestbug.top/halo

### What happened?

备份文件备份正常，但是下载失败，提示没有权限

### Relevant log output

```shell
2022-01-31 00:11:35.600 ERROR 7 --- [qtp1962049725-47694] .s.h.DefaultAuthenticationFailureHandler : Authentication failure: [The one-time token does not correspond the request uri], status: [403 FORBIDDEN], data: [e8a24e4026fc42a7a2e3574dafff3692]
```

### Additional information

看了代码 在src/main/java/run/halo/app/model/support/HaloConst.java 中，设置的默认的备份目录是 tmp
这就导致了文件备份在 docker 容器中的 tmp/halo-backup 文件夹下
由于我的主机没有访问容器内文件的权限导致下载失败
目前是手动 docker cp 到主机下了，有没有其他的解决方案

**Comment by LemonLmNan** [comment]
我也出现同样的问题, 备份陈工, 但是下载不下来, 请问是否已经解决了?

**Comment by Memoryeva** [comment]
> 我也出现同样的问题, 备份成功, 但是下载不下来, 请问是否已经解决了? 环境(均为docker运行): halo:1.4.17, mysql:8.0, nginx: latest @Memoryeva

您好，如果是docker 部署的，进入容器内复制出来即可

**Comment by Qxin-X** [comment]
> 我也出现同样的问题, 备份成功, 但是下载不下来, 请问是否已经解决了? 环境(均为docker运行): halo:1.4.17, mysql:8.0, nginx: latest @Memoryeva

不需要进入容器，在服务器用 docker scp 命令把对应路径备份从容器复制出来指定位置即可。

**Comment by JohnNiang** [comment]
目前 Halo 团队已经不再积极维护 Halo 1.x 了，如果遇到无法下载备份，建议尝试 https://github.com/halo-dev/halo/issues/1641#issuecomment-1041912001 和 https://github.com/halo-dev/halo/issues/1641#issuecomment-1055403639 提供的方法。

当前 Issue 即将被关闭。如果有任何问题，可随时重新打开。

/close
/unassign
