### ISSUE TITLE
如图启动失败

### ISSUE THREAD

**Issue by 10823** [halo-dev/halo#1643]
### What is version of Halo has the issue?

1.4.17

### What database are you using?

MySQL 8.x

### What is your deployment method?

Fat Jar

### What happened?

![image](https://user-images.githubusercontent.com/62325709/152921935-aee245a9-538f-4fb6-a8b6-1daea94811cc.png)

**Comment by ruibaby** [comment]
需要 JRE 11 或以上版本。

https://docs.halo.run/getting-started/prepare#jrejava-runtime-environment

**Comment by 10823** [comment]
thanks

**Comment by ailang323** [comment]
unsubscribe
















在 2022-02-08 16:47:10，"a" ***@***.***> 写道：

Closed #1643.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
