### ISSUE TITLE
halo整站导出和数据导出失败

### ISSUE THREAD

**Issue by shuaipotian-joke** [halo-dev/halo#1644]
### 是什么版本出现了此问题？

1.4.17

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Fat Jar

### 在线站点地址

www.cwl.asia

### 发生了什么？

整站备份文件
![image](https://user-images.githubusercontent.com/60846491/153190366-b7e9b117-812f-4aef-b866-9e2e6b7c2d85.png)
点击备份出现异常
![image](https://user-images.githubusercontent.com/60846491/153191176-5e67b37d-54ec-4252-a517-d845cf44e36c.png)
数据导出也是一样的
![image](https://user-images.githubusercontent.com/60846491/153192532-41894261-0348-4608-a2a1-98ecb8af25f8.png)

值得注意的是，我在备份失败后将.halo文件备份了一份到新服务器上启动，然后再尝试了一下备份数据又成功了
以下为日志文件
[spring.log](https://github.com/halo-dev/halo/files/8032280/spring.log)

**Comment by 3293172751** [comment]
【me too】 你解决了吗，我也是这样的问题， 今天就要迁移了，但是数据没办法导出~

**Comment by JohnNiang** [comment]
> Caused by: java.nio.file.AccessDeniedException: /tmp/halo-backup/halo-backup-2022-02-09-19-37-02--1026353164.zip

从日志中看到是系统无法创建 `/tmp/halo-backup/halo-backup-2022-02-09-19-37-02--1026353164.zip` 文件。建议检查一下 /tmp 的目录权限。
