### ISSUE TITLE
文章选择分类时无法只选择父分类

### ISSUE THREAD

**Issue by thetbw** [halo-dev/halo#1646]
### 是什么版本出现了此问题？

1.4.17

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Fat Jar

### 发生了什么？

![image](https://user-images.githubusercontent.com/31307256/153713877-d6608ab5-43df-42b8-a663-4a21395f2b55.png)
分类选择的这个地方，我无法只选择个人总结（只选择父节点），当我选择个人总结的时候，开发总结 (子节点)也会被也会被勾选。

子节点是我最近新增的，目前的结果导致我无法只在父节点目录发布文章,我后续发布的文章都会展示在开发总结中了
![image](https://user-images.githubusercontent.com/31307256/153714015-20de1c8a-27ec-4a6d-abe2-73ac308df114.png)

**Comment by ruibaby** [comment]
已经在 https://github.com/halo-dev/halo-admin/pull/367 中修复，请等待下个版本的发布，感谢反馈。
