### ISSUE TITLE
模版变量${post. categories!}无法取得多级分类名称

### ISSUE THREAD

**Issue by mqllin** [halo-dev/halo#1647]
### 是什么版本出现了此问题？

1.4.17

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Fat Jar

### 发生了什么？

在post.ftl模版页中调用模版变量${post!}，通过多次反复设置文章的分类发现，${post. categories!}返回的数组中不会包含含有子节点的分类名称。比如设置分类“日记”，设置子分类“大学日记”，给一篇文章设置分类“大学日记”，此时在页面的模版变量${post. categories!}返回的数据为[] 空数组。

如果同时设置了一级节点和多级节点的分类，则${post. categories!}返回的数组中只包含一级节点的分类

### 附加信息

![image](https://user-images.githubusercontent.com/24357436/153748676-a4acaeb1-9f33-41cf-afd3-51ab8b8809a2.png)
![image](https://user-images.githubusercontent.com/24357436/153748696-50a6479a-069b-4a1f-9f5c-17d43985e3a0.png)

**Comment by ruibaby** [comment]
文章中的分类目前确实没有生成树的结构，我们会在未来支持。

**Comment by mqllin** [comment]
补充：如果文章只选择了一个多级分类，并且文章页面模版代码中调用了 ${post. categories!},会导致获取不到数据从而整个页面无法生成html模版（浏览器报错且全屏空白）

**Comment by mqllin** [comment]
我认为这应该属于一个BUG

**Comment by ruibaby** [comment]
> 补充：如果文章只选择了一个多级分类，并且文章页面模版代码中直接调用了categories属性： ${post. categories!},会导致获取不到数据从而服务端无法生成html模版（浏览器报错且全屏空白）

可不可以提供一个示例代码呢

**Comment by ruibaby** [comment]
Halo 1.x 已停止维护，此 issue 可能不再有效，我将关闭此 issue。如果后续有新的问题，欢迎提出新的 issue。

https://www.halo.run/archives/halo-1.x-eol

/close
