### ISSUE TITLE
初始启动很慢，要加载很久才能打开

### ISSUE THREAD

**Issue by xianweibo** [halo-dev/halo#1649]
### 是什么版本出现了此问题？

1.4.17

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 在线站点地址

http://www.zhuhongshengshi.com/

### 发生了什么？

第一次加载的时候非常慢，可以用手机测试一下。
电脑上IE每次加载都很慢， chrome和edge第一次加载很慢才打开，后面二次打开就很快了（IE每次都很慢）

**Comment by ruibaby** [comment]
Disable Cache 的情况下并不是很慢呀。

<img width="945" alt="image" src="https://user-images.githubusercontent.com/21301288/153762392-1bdadc4b-172f-458c-a7e7-a082718396f7.png">

<img width="942" alt="image" src="https://user-images.githubusercontent.com/21301288/153762411-43b8d7a6-f933-479a-b0b3-7e6ec344e08d.png">

IE 不在我们的考虑范围。
