### ISSUE TITLE
根据分类 slug 获取文章模版标签输出报错

### ISSUE THREAD

**Issue by mqllin** [halo-dev/halo#1652]
### 是什么版本出现了此问题？

1.4.17

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Fat Jar

### 发生了什么？

我在尝试使用 模版标签“[根据分类 slug 获取文章（listByCategorySlug）](https://docs.halo.run/developer-guide/theme/template-tag#%E6%A0%B9%E6%8D%AE%E5%88%86%E7%B1%BB-slug-%E8%8E%B7%E5%8F%96%E6%96%87%E7%AB%A0listbycategoryslug)”时候发现文档中给出的方法无法正确返回内容。加上这段代码后模版会报错无法输出内容。详情见下图：

补充：在使用“[根据标签 id 获取文章（listByTagId）](https://docs.halo.run/developer-guide/theme/template-tag#%E6%A0%B9%E6%8D%AE%E6%A0%87%E7%AD%BE-id-%E8%8E%B7%E5%8F%96%E6%96%87%E7%AB%A0listbytagid)”时 tagId传入一个数字例如“1”，模版同样无法渲染

我现在正想通过指定的标签筛选出用于在首页轮播展示的文章

### 附加信息

![indexftl](https://user-images.githubusercontent.com/24357436/153979310-2603a0a0-a8a7-4613-b345-a1a8b3cf2e77.png)

**Comment by ruibaby** [comment]
可能是 `listByTagSlug` 返回的 `posts` 参数与首页的 `posts` 参数冲突导致的。可以使用 freemarker 的 import 语法来解决。

如：

macro.ftl

```
<#macro swiper_tag>
    <@postTag method="listByTagSlug" tagSlug="swiper">
        <#list posts as post>
            <a href="${post.fullPath!}">${post.title!}</a>
        </#list>
    </@postTag>
</#macro>
```

index.ftl

```
<#import "swiper-tag.ftl" as custom_macro />
<@custom_macro.swiper_tag />
```
