### ISSUE TITLE
希望提供一个编辑器设置页以实现对编辑器的个性化配置

### ISSUE THREAD

**Issue by guqing** [halo-dev/halo#1653]
### 描述

提供一个编辑器设置页面以实现用户对编辑器的个性化定制配置，例如
1. 配置编辑器使用的快捷键风格
2. 配置编辑器高亮代码样式
3. 配置编辑器快捷toolbar条目

此功能的出现可以减少用户的重复设置次数，让编辑器更加符合用户操作习惯

**Comment by ruibaby** [comment]
针对前端的设置我觉得可以不改动后端，是否可以在 options 提供一个针对 admin 的字段来保存设置，格式为 JSON。

**Comment by guqing** [comment]
@JohnNiang 你怎么看

**Comment by ruibaby** [comment]
> > 针对前端的设置我觉得可以不改动后端，是否可以在 options 表提供一个针对 admin 的字段来保存设置，格式为 JSON。
> 
> 
> 
> 我认为可行 个性化配置及设置使用 options 表来存储即可, 需要后端提供一条初始化数据的migrate脚本对吧

不需要，可以通过接口创建。数据其实可以通过 TypeScript 来规定。

**Comment by guqing** [comment]
> > > 针对前端的设置我觉得可以不改动后端，是否可以在 options 表提供一个针对 admin 的字段来保存设置，格式为 JSON。
> > 
> > 
> > 
> > 我认为可行 个性化配置及设置使用 options 表来存储即可, 需要后端提供一条初始化数据的migrate脚本对吧
> 
> 不需要，可以通过接口创建。数据其实可以通过 TypeScript 来规定。

好的

**Comment by ruibaby** [comment]
已过时，我将关闭此 issue。

/close
