### ISSUE TITLE
一切正常，但是想请教个问题

### ISSUE THREAD

**Issue by chao325** [halo-dev/halo#1655]
### 你当前使用的版本

版本：1.4.17

### 描述一下此特性

我根据咱们这个仓库，顺利了安装Halo。但是我想修改后台的登陆逻辑啊，请求地址啊，，各种各种的，大修改。然后我看见了另一个仓库，Halo-admin。请问我如何自定义修改后台呀。【第一次提问，格式不对请多包涵】

**Comment by ruibaby** [comment]
接口请求我们封装了请求库 https://github.com/halo-dev/js-sdk/tree/master/packages/admin-api

**Comment by chao325** [comment]
> 接口请求我们封装了请求库https://github.com/halo-dev/js-sdk/tree/master/packages/admin-api

谢谢。但是您可能没理解我的意思，我是想整体的修改后台布局页面。不只是接口，也可能是90%的内容

**Comment by JohnNiang** [comment]
可以细说为什么会有修改登录逻辑的需求。

**Comment by chao325** [comment]
> 可以细说为什么会有修改登录逻辑的需求。

也可能不是，我只是举个例子。我想修改页面的全部 内容。

**Comment by JohnNiang** [comment]
> > 可以细说为什么会有修改登录逻辑的需求。
> 
> 也可能不是，我只是举个例子。我想修改页面的全部 内容。

你可以自己 fork 项目：https://github.com/halo-dev/halo-admin ，可修改你想要修改的任何内容。

**Comment by ruibaby** [comment]
编译之后将 dist 的内容放到主项目的 `src/main/resources/admin` 即可。

**Comment by chao325** [comment]
> > > 可以细说为什么会有修改登录逻辑的需求。
> > 
> > 
> > 也可能不是，我只是举个例子。我想修改页面的全部 内容。
> 
> 你可以自己 fork 项目：https://github.com/halo-dev/halo-admin ，可修改你想要修改的任何内容。

非常感谢！！！我刚刚就是这样做的，可是打包完成后。我并不知道应该放在那里。怎样的运行她。。。我是宝塔页面 Linux

**Comment by chao325** [comment]
> 编译之后将 dist 的内容放到主项目的 `src/main/resources/admin` 即可。

非常感谢！！！！！！我现在就去试试。。我刚刚申请加入了微信群，希望能帮助到Linux部署有困难的朋友

**Comment by chao325** [comment]
> 

您好，我的启动目录是 /home/ChaoCMS/app  我翻遍了其余的目录都没有看见 src/main/resources/admin

**Comment by ruibaby** [comment]
https://github.com/halo-dev/halo/tree/master/src/main/resources/admin

修改后台资源之后需要重新编译。

**Comment by chao325** [comment]
> https://github.com/halo-dev/halo/tree/master/src/main/resources/admin
> 
> 修改后台资源之后需要重新编译。

抱歉，，我是按照咱们文档一键部署的，， 我并没有拉去 halo-dev的代码。。。所以我Linux服务器里面，也并没有这个目录呀

**Comment by ruibaby** [comment]
目前我们只有一个运行包(halo.jar)，而编译后的 admin 资源又包含在运行包，你修改 admin 重新编译资源之后肯定也需要重新编译 halo-dev/halo 项目得到最终运行包产物。

**Comment by ruibaby** [comment]
可以查看我们发布版本的 commit 变更。https://github.com/halo-dev/halo/commit/a79211c43e42f866f6e929e21de8c0a4f949ce3e

另外，当前不推荐直接使用 master 分支进行编译使用，请使用最新的 tag 进行编译。https://github.com/halo-dev/halo/tags

**Comment by chao325** [comment]
> 可以查看我们发布版本的 commit 变更。[a79211c](https://github.com/halo-dev/halo/commit/a79211c43e42f866f6e929e21de8c0a4f949ce3e)
> 
> 另外，当前不推荐直接使用 master 分支进行编译使用，请使用最新的 tag 进行编译。https://github.com/halo-dev/halo/tags

非常感谢
