### ISSUE TITLE
配置云存储后列出存储桶中的全部图片

### ISSUE THREAD

**Issue by AKmoex** [halo-dev/halo#1658]
### 你当前使用的版本

1.4.17

### 描述一下此特性

配置好云存储后，系统首次并不会拉取存储桶中的所有图片，只是会列出我们配置云存储之后通过该系统上传的图片。希望在首次配置好云存储后，能够单独拉取以下存储桶中的所有文件。

### 附加信息

以腾讯云cos为例，我这边发现文档中是提供了列出存储桶中所有文件的接口：[GET Bucket（List Objects）](https://cloud.tencent.com/document/product/436/7734)

**Comment by ruibaby** [comment]
你好，目前设计就是如此，只会存储你在后台上传的文件。且在当前版本已经不是很好做你说的这种特性了。我们会在 2.0 的时候考虑此特性。

**Comment by oliverwu-cn** [comment]
请问是否可以提供一下详细的指导？ 我这边尝试配置腾讯云的 COS 存储，一直失败。。。。
附件策略 配置为：

Endpoint协议 ： HTTPS
Endpoint :   cos.na-toronto.myqcloud.com   因为 服务器买的米国的，所以也在北美区域创建了存储桶
Region:  na-toronto
绑定域名协议 HTTPS
自定义CDN 加速域名： 无论填还是不填写都不行

Access Key/ID 按照文档已经开启了， 另外存储也开启了 公有读私有写权限。

当时当尝试上传附件时，会遇到报错

Internal Server Error: null (Service: S3, Status Code: 403, Request ID: NjQzYTk5MWZfOWI1NTA2MDlfODcyXzJjNTc1Njc=)


请问怎么回事，有没有大佬可以提供一下详细的配置步骤，本人小白用户，谢谢 ！

**Comment by JohnNiang** [comment]
@oliverwu-cn 从错误上看，可能是对应的 key 和 secret 没有足够的上传权限。

**Comment by ruibaby** [comment]
Halo 2 的 [S3 插件](https://github.com/halo-dev/plugin-s3)目前已经支持列出存储桶的文件并和 Halo 建立关联，所以我将关闭此 issue。

/close
