### ISSUE TITLE
希望在Content API中提供通过themeId查询主题信息及配置的接口

### ISSUE THREAD

**Issue by fuzui** [halo-dev/halo#1659]
### Your current Halo version

1.4.17

### Describe this feature

目前Content API中仅能够查询当前使用的主题的信息及配置。
因如果我想在其他端（例如APP、小程序）中能够通过后台灵活配置一些参数，但我仍不想放弃我当前在web端正在使用的主题。
目前能想到的便是通过拉取一个特有主题来获取其配置，但在后台仅仅只是配置它，并不启用它。

**Comment by JohnNiang** [comment]
@fuzui Thanks for reaching out here. We will consider your request in Halo 1.5.x.

/kind feature

**Comment by JohnNiang** [comment]
这里我提供一下实现思路，希望有兴趣的朋友能够根据该思路达成参与 Halo 的成就。

### 思路

实现“根据 themeId 获取主题信息及配置信息”接口

https://github.com/halo-dev/halo/blob/d961a5e8a5c0deb889da4a447542fb098bbad03f/src/main/java/run/halo/app/controller/content/api/ThemeController.java#L19-L42

实现过程中，可能需要通过以下服务来获取主题详情：

https://github.com/halo-dev/halo/blob/d961a5e8a5c0deb889da4a447542fb098bbad03f/src/main/java/run/halo/app/service/ThemeService.java#L61
