### ISSUE TITLE
测试 GitHub Actions 发布流程

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#1661]
发布 1.5.0 的时候需要首先发布 alpha 版本，所以需要测试一下 GitHub Actions 流程是否兼容 `1.5.0-alpha.1` 这种形式。

期望：

1. 构建出 `halo-1.5.0-alpha.1.jar` 的运行包，并且功能正常，主要测试安装主题时，版本校验是否正常。
2. 构建 tag 为 `1.5.0-alpha.1` 的 Docker 镜像，如 `halohub/halo:1.5.0-alpha.1`。

**Comment by JohnNiang** [comment]
明天将进行完整的测试。
