### ISSUE TITLE
希望增加Token缓存持久化机制

### ISSUE THREAD

**Issue by guqing** [halo-dev/halo#1662]
### Describe this feature

由于目前token缓存没有持久化机制开发时经常需要重启，而重启项目就需要重新登陆获取token才能继续测试接口非常不方便，如果能增加token持久化机制将缓存中的token在停止时持久化到磁盘，启动时恢复到内存即可不用每次重启后都重新获取token（像session持久化那样）

**Comment by zhangzhongxing-sudo** [comment]
缓存如果选取的是level，Token是会缓存到磁盘的？
![image](https://user-images.githubusercontent.com/20938747/155938092-e2039014-2240-4118-b521-d4ebaa17e036.png)

**Comment by guqing** [comment]
> 缓存如果选取的是level，Token是会缓存到磁盘的？
> ![image](https://user-images.githubusercontent.com/20938747/155938092-e2039014-2240-4118-b521-d4ebaa17e036.png)
> 

是的

**Comment by guqing** [comment]
> > 缓存如果选取的是level，Token是会缓存到磁盘的？
> > ![image](https://user-images.githubusercontent.com/20938747/155938092-e2039014-2240-4118-b521-d4ebaa17e036.png)
> > 
> 
> 是的

不过memory没有提供持久化

**Comment by ruibaby** [comment]
此问题已过时。

/close
