### ISSUE TITLE
https协议访问时，图床协议变为https 

### ISSUE THREAD

**Issue by DongTL** [halo-dev/halo#1667]
### 是什么版本出现了此问题？

1.4.17

### 使用的什么数据库？

MySQL 5.7

### 使用的哪种方式部署？

Docker

### 在线站点地址

https://www.coolcode.fun/

### 发生了什么？

最初我使用http协议访问，使用七牛云存储附件，七牛云也是http协议访问，图片地址是这样的：http://image.coolcode.fun......，一切正常。
今天我配置了https协议，可以进入页面，但图片加载不出来，控制台看到图片地址变为了https://image.coolcode.fun......，然而我的七牛云是http协议的，我看了博客设置里面的附件设置，我选的是http协议呀，为什么会自动变成https协议？

**Comment by JohnNiang** [comment]
![image](https://user-images.githubusercontent.com/16865714/154897415-02ab04a9-391f-4b58-9a21-65245b122683.png)

**Comment by ruibaby** [comment]
这是 Chrome 早前的新特性，会自动将 https 站点的 http 转为 https 进行访问，相关信息可以在搜索引擎搜索到。你可以尝试一下其他浏览器比如 Firefox 是否有此问题。
