### ISSUE TITLE
附件设置的存储位置支持webdav选项

### ISSUE THREAD

**Issue by karma-sun** [halo-dev/halo#1672]
### Your current Halo version

1.4.17

### Describe this feature

附件设置的存储位置增加一个webdav选项，可以使用webdav服务器

**Comment by ruibaby** [comment]
目前 2.0 已经支持通过插件提供外部存储策略，可参考以下插件来实现对 webdav 的支持：

- https://github.com/halo-sigs/plugin-alioss
- https://github.com/halo-sigs/plugin-unsplash

> 我们期望由社区来提供这样的插件。

**Comment by JohnNiang** [comment]
当前 Issue 暂未解决，我将重新开启。

/reopen
/milestone clear

**Comment by ruibaby** [comment]
目前社区已经有了支持 Webhook 的插件：https://github.com/halo-sigs/plugin-alist

/close
