### ISSUE TITLE
表格无法显示

### ISSUE THREAD

**Issue by zerodayZHOUXUTIAN** [halo-dev/halo#1674]
### 是什么版本出现了此问题？

1.4.16

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 在线站点地址

http://yoysh.cn/archives/%E6%8A%A5%E8%A1%A8%E6%A8%A1%E5%9D%97%E7%9A%84%E8%AE%BE%E8%AE%A1

### 发生了什么？

markdown的表格无法正常显示，在编辑预览中可以正常显示

**Comment by ruibaby** [comment]
可能是 1.4 当中前后端 Markdown 渲染规则不一致导致的，你可以尝试在表格语法前后加上空行。

PS：目前在 1.5 alpha 已经默认保存编辑器渲染的 html，完全保证编辑时预览效果和最终效果一致。

欢迎测试：https://github.com/halo-dev/halo/releases/tag/v1.5.0-alpha.1

**Comment by zerodayZHOUXUTIAN** [comment]
表格前后加上空行可以解决问题
