### ISSUE TITLE
拉取主题的时候自动添加 .git 后缀

### ISSUE THREAD

**Issue by JohnNiang** [halo-dev/halo#168]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [ ] [Halo 使用文档](https://docs.halo.run/)
- [ ] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [ ] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [x] 请求技术支持

---
如果用户提供的地址不是以 `.git` 结尾的后缀，系统将自动添加上该后缀。

**Comment by daofeng2015** [comment]
我用docker直接拉取的.用远程安装主题提示没有git工具呢?(docker镜像里没装git工具吗?

**Comment by JohnNiang** [comment]
> 我用docker直接拉取的.用远程安装主题提示没有git工具呢?(docker镜像里没装git工具吗?

可以提供详细信息么？这样模糊的描述，我们没办法定位问题。
