### ISSUE TITLE
是否可以提供文章在首页隐藏的功能？

### ISSUE THREAD

**Issue by Sivan757** [halo-dev/halo#1687]
### 你当前使用的版本

1.4.13

### 描述一下此特性

目前做技术博客有个想法，将代码片段单独做一个分类，在顶部显示独立链接，但并不希望代码片段展示在首页。目前对分类设置密码，达到相同的效果，但进入分类始终需要输入密码感觉不是很方便，所以提出这个问题，是否能允许单独控制文章是否在首页显示，或者控制分类是否在首页显示？

**Comment by ruibaby** [comment]
有这个计划，将在后续大版本提供。

**Comment by 20844** [comment]
顶      大佬辛苦了  赶紧出新版本  支持前台显示加密文章   大佬666

**Comment by Cyiming** [comment]
支持该功能 顶一下 方便收到提醒

**Comment by ruibaby** [comment]
已经在 [next](https://github.com/halo-dev/halo/tree/next) 分支支持，将在 2.0 发布。

/close

**Comment by xiejuntao** [comment]
> 已经在 [next](https://github.com/halo-dev/halo/tree/next) 分支支持，将在 2.0 发布。
> 
> /close

@ruibaby 最新的2.7版本，没见这个首页隐藏文章或设置要显示哪些文章的功能 啊。别最好期望能支持首页文章的排序。辛苦，望解答，感谢。
