### ISSUE TITLE
系统 Properties 中默认值如果为空字符串不会返回查询结果

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#1689]
### 是什么版本出现了此问题？

 1.5.0-alpha.1

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Fat Jar

### 在线站点地址

https://halo.run

### 发生了什么？

比如 [CommentProperties](https://github.com/halo-dev/halo/blob/master/src/main/java/run/halo/app/model/properties/CommentProperties.java#L15) 中的 `GRAVATAR_DEFAULT` 属性的默认值为空字符串，那么在查询接口中不会返回此字段，期望返回此字段，因为在某些情况下空字符串是有意义的。

比如初始化系统之后：

<img width="571" alt="image" src="https://user-images.githubusercontent.com/21301288/156097975-0d96b950-6918-4c27-a62e-44ebff1099ee.png">

此设置项没有绑定属性。

<img width="1079" alt="image" src="https://user-images.githubusercontent.com/21301288/156098047-a859e645-f6ae-4c8d-89a2-7bcd638a2135.png">

前台评论框因为没有这个字段所以无法加载头像。

**Comment by ruibaby** [comment]
@JohnNiang 还记得当初这里是处于什么考虑需要过滤掉空字符串的属性吗？

https://github.com/halo-dev/halo/blob/master/src/main/java/run/halo/app/service/impl/OptionServiceImpl.java#L216

**Comment by JohnNiang** [comment]
> @JohnNiang 还记得当初这里是处于什么考虑需要过滤掉空字符串的属性吗？
> 
> https://github.com/halo-dev/halo/blob/master/src/main/java/run/halo/app/service/impl/OptionServiceImpl.java#L216

忘记了当初为什么要过滤掉空串的属性。不过现在有对应的需求，建议移除这样的过滤条件。

**Comment by lan-yonghui** [comment]
> > @JohnNiang还记得当初这里是什么考虑需要过滤掉空字符串的吗？
> > https://github.com/halo-dev/halo/blob/master/src/main/java/run/halo/app/service/impl/OptionServiceImpl.java#L216
> 
> 忘记了最初为什么要过滤掉空串的属性。不过有十五条需求，建议现在去掉这样的过滤条件。

这个位置我看了代码，应该是给前端请求返回值的时候，把默认配置值为0的去掉，前端其他参数不会影响，头像那个位置因为没有comment_gravatar_default这个参数了，js默认给了undefined，在gravatar源中没有undefined对应的头像！
