### ISSUE TITLE
首页报错API has been disabled by blogger currently，不展示最近写的文章

### ISSUE THREAD

**Issue by mojerro** [halo-dev/halo#1693]
### 是什么版本出现了此问题？

1.4.17

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 在线站点地址

mojerro.wang

### 发生了什么？

首页进入直接报错，API has been disabled by blogger currently，接口展示403，无法展示最近的博文

### 附加信息

主题使用的是Joe2.0

**Comment by guqing** [comment]
应该是主题需要，请在后台开启api key

**Comment by ruibaby** [comment]
https://github.com/qinhua/halo-theme-joe2.0#%EF%B8%8F-必读

**Comment by mojerro** [comment]
抱歉读的不够仔细，感谢大佬
