### ISSUE TITLE
PrimaryProperties中的BIRTHDAY初始值为0导致刚初始化的博客建立天数就为19053天

### ISSUE THREAD

**Issue by guqing** [halo-dev/halo#1696]
### What is version of Halo has the issue?

latest

### What database are you using?

H2

### What is your deployment method?

Fat Jar

### What happened?

需要在 run.halo.app.service.impl.OptionServiceImpl#getBirthday 中针对值为0的情况做判断

**Comment by JohnNiang** [comment]
@guqing 建议关联一下对应的 PR 或者 issue。

**Comment by guqing** [comment]
> @guqing 建议关联一下对应的 PR 或者 issue。

ok

**Comment by guqing** [comment]
> 默认值设置为：BIRTHDAY("birthday", Long.class, String.valueOf(System.currentTimeMillis()))是不是更好一些呢？0本身是一个有意义的值。run.halo.app.service.impl.OptionServiceImpl#getBirthday 方法中获取默认值处理不太合理！！

可以，改完以后记得提供单元测试👏

**Comment by guqing** [comment]
枚举类的特性和声明为static final一样在系统初始化时就加载好了，所以你的期望是设置值为当前时间戳，但实际这个当前只是代表了系统启动时，容易让人引起困惑

**Comment by ruibaby** [comment]
> run.halo.app.service.impl.OptionServiceImpl#getBirthday 方法中获取默认值处理不太合理

是这样的，确实不合理，你可以修改这个方法的实现。可以看到在 https://github.com/halo-dev/halo/blob/master/src/main/java/run/halo/app/service/impl/OptionServiceImpl.java#L375 里面判断到数据库中的 birthday 这个值为空的话会去重新设置值，是因为我们在系统初始化的时候会设置当前的时间，如果你这里只修改了 `BIRTHDAY ` 的默认值为 `String.valueOf(System.currentTimeMillis())` ，会造成用户在初始化系统的时候不会去将当前时间存到数据库，那么这时候建站时间就会变为每次启动的时间，因为 @guqing 在上面提到【枚举类的特性和声明为static final一样在系统初始化时就加载好了】

https://github.com/halo-dev/halo/blob/master/src/main/java/run/halo/app/controller/admin/api/InstallController.java

**Comment by lan-yonghui** [comment]
> > run.halo.app.service.impl.OptionServiceImpl#getBirthday 方法中获取默认值处理不太合理
> 
> 是这样的，确实不合理，你可以修改这个方法的实现。可以看到在 https://github.com/halo-dev/halo/blob/master/src/main/java/run/halo/app/service/impl/OptionServiceImpl.java#L375 里面判断到数据库中的 birthday 这个值为空的话会去重新设置值，是因为我们在系统初始化的时候会设置当前的时间，如果你这里只修改了 `BIRTHDAY` 的默认值为 `String.valueOf(System.currentTimeMillis())` ，会造成用户在初始化系统的时候不会去将当前时间存到数据库，那么这时候建站时间就会变为每次启动的时间，因为 @guqing 在上面提到【枚举类的特性和声明为static final一样在系统初始化时就加载好了】
> 
> https://github.com/halo-dev/halo/blob/master/src/main/java/run/halo/app/controller/admin/api/InstallController.java

en.  了解。我准备这样处理，不知道会不会有其他影响：
 @Override
    public long getBirthday() {
        long birthdayTime = DateUtils.now().getTime();
        if (StringUtils.isNotBlank(PrimaryProperties.BIRTHDAY.defaultValue())) {
            birthdayTime = Long.parseLong(getByPropertyOrDefault(PrimaryProperties.BIRTHDAY,
                String.class, PrimaryProperties.BIRTHDAY.defaultValue()));
        }

        saveProperty(PrimaryProperties.BIRTHDAY, String.valueOf(birthdayTime));
        return birthdayTime;
    }
