### ISSUE TITLE
后台的菜单栏点击跳转没有走路由

### ISSUE THREAD

**Issue by vivtoum** [halo-dev/halo#1700]
### 是什么版本出现了此问题？

最新版

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker

### 发生了什么？

如果直接点击菜单栏跳转
![image](https://user-images.githubusercontent.com/20490688/156705367-072622e0-b3f6-49a7-ac56-5af6228fc77f.png)
地址会变成http://localhost:8090/dashboard
这个地址是访问不到的
需要改成http://localhost:8090/admin/index.html#/dashboard 这种模式才能走路由
换言之，菜单栏不起作用

![image](https://user-images.githubusercontent.com/20490688/156705195-e1f58d3c-996d-457d-ab0a-4d2d8d3de08e.png)

**Comment by ruibaby** [comment]
你好，请提供更详细的信息，包括部署方式，Nginx 配置，是否使用某种 CDN 等。

**Comment by vivtoum** [comment]
> 你好，请提供更详细的信息，包括部署方式，Nginx 配置，是否使用某种 CDN 等。目前我们没有复现出这种情况。

我服务器是用腾讯云，宝塔镜像
nginx跟官网给出的例子一样，加在配置里。
CDN没有使用
docker的部署方式

部署步骤基本和文档一样
![image](https://user-images.githubusercontent.com/20490688/156735420-1b054c4d-23c9-42a5-bebc-88843e8639e4.png)

改动了数据库连接，用MySQL连接

**Comment by ruibaby** [comment]
> nginx跟官网给出的例子一样，加在配置里。

能否提供完整的 Nginx 配置呢

**Comment by vivtoum** [comment]
> > nginx跟官网给出的例子一样，加在配置里。
> 
> 能否提供完整的 Nginx 配置呢
[配置.txt](https://github.com/halo-dev/halo/files/8184720/default.txt)

在这，我感觉与ng不太相关。启动完成以后，我用8090登录后台已经出现这个问题
以下是录屏
[操作录屏.zip](https://github.com/halo-dev/halo/files/8184730/default.zip)

**Comment by ruibaby** [comment]
@vivtoum 可以提供你后台访问权限给我们测试一下吗？我们从发布至今都没有遇到这个问题，想知道是什么问题导致的。

你可以将相关信息发送到 hi@halo.run 邮箱。

**Comment by ruibaby** [comment]
> @vivtoum 可以提供你后台访问权限给我们测试一下吗？我们从发布至今都没有遇到这个问题，想知道是什么问题导致的。
> 
> 你可以将相关信息发送到 [hi@halo.run](mailto:hi@halo.run) 邮箱。

如果不方便，你可以验证一下我的猜测：从你的视频中可以看到浏览器开启了 3 个油猴脚本，所以可能是某个脚本影响到了这个表现。建议换一个没有油猴插件的浏览器测试一下。

**Comment by ruibaby** [comment]
@vivtoum 你好，请问此问题有后续有解决吗？

**Comment by vivtoum** [comment]
> > @vivtoum 可以提供你后台访问权限给我们测试一下吗？我们从发布至今都没有遇到这个问题，想知道是什么问题导致的。
> > 你可以将相关信息发送到 [hi@halo.run](mailto:hi@halo.run) 邮箱。
> 
> 如果不方便，你可以验证一下我的猜测：从你的视频中可以看到浏览器开启了 3 个油猴脚本，所以可能是某个脚本影响到了这个表现。建议换一个没有油猴插件的浏览器测试一下。

您好，感谢指导。周末不在电脑前，今天按指导在edge测试了一下，正常了。我再试试关闭油猴脚本在谷歌浏览器尝试。

**Comment by vivtoum** [comment]
![image](https://user-images.githubusercontent.com/20490688/157184353-e6758d30-2ea7-4641-b2c1-fc4378c404b1.png)
经过排除，发现是油猴这一个脚本影响。排除域名以后正常

**Comment by ruibaby** [comment]
> 经过排除，发现是油猴这一个脚本影响。排除域名以后正常

那我们就先 Close 这个 issue 了。
