### ISSUE TITLE
Halo Blog CMS1.4.17 Fileupload without file type authentication

### ISSUE THREAD

**Issue by ziping21** [halo-dev/halo#1702]
### 是什么版本出现了此问题？

1.4.17

### 使用的什么数据库？

MySQL 5.7

### 使用的哪种方式部署？

Fat Jar

### 在线站点地址

https://demo.halo.run/admin/index.html#/comments

### 发生了什么？

The vulnerability can lead to the upload of arbitrary malicious script files.

### 相关日志输出

```shell
no
```

### 附加信息

Black-box penetration：
1.	Use (demo:P@ssw0rd123...) to login in https://demo.halo.run/admin ,and then find the 
attachment upload feature ,try to upload a random image.
 
![图片](https://user-images.githubusercontent.com/63443757/156746391-9308664e-4a0f-481d-a123-c7441cf32769.png)

2.	While uploading a random image, use burp suite to catch the request packet and forward it to the Repeater module.
 
![图片](https://user-images.githubusercontent.com/63443757/156746407-bb1dd699-9ca8-4553-958c-164af36173d9.png)

3.	You can tell we successfully uploaded the image from the screenshot below . And we can also get the path of the image accordding to the response.
 
![图片](https://user-images.githubusercontent.com/63443757/156746420-ebe7c2e6-0d00-491c-85e2-a1885c9c198c.png)

4.	Now we want to use the feature again. This time ,try to change the file suffix and modify the file content at the same time. After doing that , send the request again. And the upload is still successful , the file path is also returned.
 
![图片](https://user-images.githubusercontent.com/63443757/156746430-b8d6548e-65bd-4c9d-b27e-e6c6838004ca.png)

5.	Now try to access the file path within the url below,and our xss payload successfully executed 
 
![图片](https://user-images.githubusercontent.com/63443757/156746443-6d9ee71d-a7a5-43e2-9d45-715e13104276.png)

6.	Screenshots of other file types uploaded are as follows：
 
![图片](https://user-images.githubusercontent.com/63443757/156746458-b35a4df8-6bf8-4330-9a4c-eb22aa994da5.png)

 
![图片](https://user-images.githubusercontent.com/63443757/156746467-86e3b944-538c-49f4-8edb-e899057ae513.png)

Source code review：
Try to download the source code for source code security analysis 
https://github.com/halo-dev/halo/releases/tag/v1.4.17（Latest version 1.4.17）
 
![图片](https://user-images.githubusercontent.com/63443757/156746509-1706562c-f7bf-4afb-9622-796aec75c324.png)

7.	Check the source code and locate the class src\main\java\run\halo\app\controller\admin\api\AttachmentController.java 
According to the annotations of this class, you can find that all requests to the 	path /api/admin/attachments will access this class.
 
![图片](https://user-images.githubusercontent.com/63443757/156746523-473c4010-9ff8-4509-bd7f-f80988be40f4.png)

8.	The /upload path accessed by the upload interface will access the uploadAttachment method of this class.
 
![图片](https://user-images.githubusercontent.com/63443757/156746532-a57e34cd-1627-4bb5-bd34-5b65e0e90a71.png)

9.	As you can see, this method receives the file from the client side, then passes the file object as an argument to the upload() method of the AttachmentServiceImpl class and executes it, and then executes the result as an argument to the convertToDto() method of the AttachmentServiceImpl class.
10.	So let's follow up on the upload() method first after locating the src\main\java\run\halo\app\service\impl\AttachmentServiceImpl.java class and dive into the upload() method
 
![图片](https://user-images.githubusercontent.com/63443757/156746551-998eb7d5-af12-4d6d-9768-09b8b1c0f82d.png)

11.	You can see that the code does not have any file suffix checksum, and finally the upload() method will return a create(attachment) object, continue to follow up to the create() method, you can see that an Attachment class object is returned, and there is no file checksum.
 
![图片](https://user-images.githubusercontent.com/63443757/156746569-4053afc0-e4fa-436e-9bf3-2b394389e249.png)

12.	The returned object is entered as an argument to the convertToDto() method of  the src\main\java\run\halo\app\service\impl\AttachmentServiceImpl.java class, in   which you can see that the code writes the path of the uploaded file to the    AttachmentDTO instance object, and it can be found that there is no logic of    permission checking, and finally the method returns an AttachmentDTO instance  object.  
 
![图片](https://user-images.githubusercontent.com/63443757/156746581-00a7ff3b-9d56-4a2a-ad3a-c1edec819a9d.png)

13.	When the file path is set, this information will be brought into the response packet and eventually fed back to the client, so we can successfully access the uploaded file in the response packet based on this path information。
14.	According to the analysis of the above code, we can see that there is no logic in the code to check the file suffix, file content and file format, so it can lead to arbitrary file upload。

**Comment by ruibaby** [comment]
We will provide the setting to allow file extensions to be uploaded in 2.0, thank you for your feedback.
