### ISSUE TITLE
建议增加 Markdown 导入的接口

### ISSUE THREAD

**Issue by chenlip** [halo-dev/halo#1708]
### Your current Halo version

V1.4.17

### Describe this feature

建议增加Markdown导入的接口
我看到后台管理中有个小工具的，我觉得这个工具挺好用的，我将原来的MD日志全部直接导入下来了

如果这个导入功能有接口，我是否就可以直接写个小脚本自动导入了啊

**Comment by ruibaby** [comment]
REST API：https://api.halo.run/admin-api.html#operation/getMarkdownBackupUsingGET

你也可以使用我们的 sdk：https://github.com/halo-dev/js-sdk

可以参考：https://github.com/halo-dev/halo-admin/blob/master/src/views/system/ToolList.vue#L83

**Comment by chenlip** [comment]
> REST API：https://api.halo.run/admin-api.html#operation/getMarkdownBackupUsingGET
> 
> 你也可以使用我们的 sdk：https://github.com/halo-dev/js-sdk
> 
> 可以参考：https://github.com/halo-dev/halo-admin/blob/master/src/views/system/ToolList.vue#L83

**太牛了。**

**Comment by ruibaby** [comment]
@chenlip 如果没有其他问题，我们就先关闭此 issue 了，如果有后续问题可以 reopen。
