### ISSUE TITLE
附件链接复制使用时会变成乱码链接

### ISSUE THREAD

**Issue by zihanla** [halo-dev/halo#1711]
### 是什么版本出现了此问题？

1.5.0-alpha.1

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 在线站点地址

https://hxcpl.cn

### 发生了什么？

比如我正常情况 应该是如下情况链接:https://hxcpl.cn/upload/2022/03/附件链接复制使用乱码.png
而实际情况确是:
https://hxcpl.cn/upload/2022/03/%E6%BC%82%E4%BA%AE%E5%A7%90%E5%A7%90.jpg

**Comment by ruibaby** [comment]
你好，这只是进行了 URL encode 操作，不会影响实际访问，而且在某些情况，链接如果不进行 URL encode 会无法访问。
