### ISSUE TITLE
提供单元测试规范

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#1717]
### 你当前使用的版本

1.5.0-alpha.2

### 描述一下此特性

1. 2.0 需要规范单元测试。
2. 确定单元测试框架。
3. 提供基础的 `service` `util` `controller` 等的示例。
4. 提供 code coverage 统计。

/cc @halo-dev/sig-halo

**Comment by JohnNiang** [comment]
References:
- https://docs.spring.io/spring-boot/docs/2.7.0-M1/reference/html/howto.html#howto.testing

**Comment by JohnNiang** [comment]
Please refer to https://github.com/halo-dev/halo/tree/next/src/test/java/run/halo/app

**Comment by ruibaby** [comment]
> Please refer to https://github.com/halo-dev/halo/tree/next/src/test/java/run/halo/app

/close
