### ISSUE TITLE
提供 Pull Request 模板

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#1718]
### 你当前使用的版本

1.5.0-alpha.2

### 描述一下此特性

RT，需要在里面描述一下内容：

1. 这个 PR 做了什么。
2. 如何测试这个改动。
3. 对应的 issue。
4. 提示需要编写单元测试。
5. ...

/cc @halo-dev/sig-halo

**Comment by JohnNiang** [comment]
Pull Request 模板中需要添加 checklist，如：

- [ ] task a
- [ ] task b
