### ISSUE TITLE
使用了https加载Favicon失败

### ISSUE THREAD

**Issue by Soulballad** [halo-dev/halo#1719]
### 是什么版本出现了此问题？

1.4.17

### 使用的什么数据库？

MySQL 5.7

### 使用的哪种方式部署？

Docker

### 发生了什么？

站点使用了https，favicon图片使用了手动上传的图片，出现跨域问题，无法正常加载

![image](https://user-images.githubusercontent.com/19262272/157054685-202f101d-657c-4dea-907e-689282ac6fc9.png)

![image](https://user-images.githubusercontent.com/19262272/157054578-7cf2178a-4598-451b-bb65-1a0edc5c4bce.png)

### 相关日志输出

```shell
Mixed Content: The page at 'https://www.soulballad.top/admin/index.html#/system/options' was loaded over HTTPS, but requested an insecure favicon 'http://www.soulballad.top/upload/2022/03/tiger-4904e73e29d04fd5abcf1e4a9f3226bf.png'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by ruibaby** [comment]
你好，目前我们没能复现这个问题，你可以先尝试补全 Favicon 地址看看有没有这种问题。

**Comment by ruibaby** [comment]
PS：这个 favicon.ico 应该是后台用的。

**Comment by Soulballad** [comment]
使用了https全路径之后，就没有这个问题了。
这里是管理后台界面
