### ISSUE TITLE
希望上传图片时可以抹除EXIF信息

### ISSUE THREAD

**Issue by 52lemon6** [halo-dev/halo#1720]
### 你当前使用的版本

1.4.17

### 描述一下此特性

希望上传图片时可以抹除EXIF信息，在电脑上还好说，挨个压缩一遍EXIF信息就都没了，但是手机上就难搞了，没啥软件能批量压缩和去除exif信息

**Comment by HenMie** [comment]
比较需要的话，目前也有处理方案，对象储存一般有图片处理策略，可以在处理策略自己设置压缩/转换格式/去除EXIF等功能。如果你用的是对象储存的话可以试一下。

**Comment by SladeGranger** [comment]
可以使用apache commons imaging库提供的方法去除EXIF信息，如果有需要的话我可以发起一个pr

**Comment by ruibaby** [comment]
> 可以使用apache commons imaging库提供的方法去除EXIF信息，如果有需要的话我可以发起一个pr

欢迎贡献，但建议讨论一下具体的思路，如：是否需要在附件设置添加是否去除 EXIF 信息的选项。

**Comment by SladeGranger** [comment]
> 欢迎贡献，但建议讨论一下具体的方案，如：是否需要在附件设置添加是否去除 EXIF 信息的选项。

个人觉得EXIF信息里大部分内容都比较隐私，在公开的界面展示是不好的。我倾向于只留下orientation这种对图片展示有影响的EXIF字段，隐私类的删除。

**Comment by ruibaby** [comment]
> 

但还是建议保留一个系统设置让使用者来决定。因为在某些场景下，使用者可能需要展示这些信息，比如在相册的场景下，使用者希望展示拍摄地、相机相关信息、ISO 等数据。

**Comment by SladeGranger** [comment]
> 个人觉得EXIF信息里大部分内容都比较隐私，在公开的界面展示是不好的。我倾向于只留下orientation这种对图片展示有影响的EXIF字段，隐私类的删除。

我可以先在fileHandler里提供一个方法，输入一个图片文件，返回去除EXIF的图片文件。如果可以的话先暂定删除EXIF，后续如果加上系统设置，也可以加一个判断来决定是否调用这个方法处理图片。
如果暂时不需要删除EXIF， 我也可以先将这个方法上传，以后有需求的时候调用。

**Comment by SladeGranger** [comment]
已经实现了去除图片EXIF的功能，并在附件设置里留了一个开关让使用者决定是否在上传图片时删除EXIF信息。
![ui](https://user-images.githubusercontent.com/43343180/164966241-785bbad7-7080-42f5-b213-936cd5a49d1f.JPG)

在阿里云，七牛云和本地都做了测试，今天晚些会发布一个pr。

**Comment by chmdir** [comment]
1.5.3有这个功能没， 怎么加上去

**Comment by eziosudo** [comment]
> > 1.5.3有这个功能没， 怎么加上去
> 
> 还没有🙋，可以关注一下 PR #1889 的进展，只有等待这个 PR 合并后的版本发了版才会有

话说这个PR要是一直不合怎么办？

**Comment by JohnNiang** [comment]
Hi @eziosudo ，我们尝试 ping 过作者，似乎没有得到回应，可能该作者最近有些忙无法继续完成此功能。请参考：<https://github.com/halo-dev/halo/pull/1889#issuecomment-1129493299>。

近期我们将再次 ping 以下该 PR 作者，如果还未得到回应，且你感兴趣的话，可以根据 https://github.com/halo-dev/halo/pull/1889#pullrequestreview-964161428 提交一个新的 PR 来尽快修复此功能。

**Comment by JohnNiang** [comment]
期待 @eziosudo 的又一个 Contribution :heart:，关于此 Issue 的问题，我们会积极回复。

**Comment by eziosudo** [comment]
> 期待 @eziosudo 的又一个 Contribution ❤️，关于此 Issue 的问题，我们会积极回复。

谢谢。我很喜欢halo和halo的团队，愿尽绵薄之力。

**Comment by ruibaby** [comment]
@eziosudo 管理端已经有了一个添加移除 EXIF 信息设置选项的 PR，你可以用这个 PR 进行测试。

**Comment by eziosudo** [comment]
> @eziosudo 管理端已经有了一个添加移除 EXIF 信息设置选项的 PR，你可以用这个 PR 进行测试。[halo-dev/halo-admin#554](https://github.com/halo-dev/halo-admin/pull/554)

好的。
