### ISSUE TITLE
接口性能问题

### ISSUE THREAD

**Issue by yuanzhixiang** [halo-dev/halo#1723]
### 是什么版本出现了此问题？

1.5.0-alpha.2

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Fat Jar

### 发生了什么？

下面这三个接口有时候很慢，会导致在写文章与编辑文章时界面卡住的情况，例如在我下面这个截图中，三个接口调用分别用了 1 秒多，但是当我等他们加载出来之后，第二次访问的时候便只有 20 毫秒左右，效果见下面第二张图，这个问题有没有什么办法优化一下。

### 附加信息

![第一次访问](https://user-images.githubusercontent.com/25138766/157201902-650d37aa-2fed-4cbc-961f-b7c091bb65dd.png)

![第二次访问](https://user-images.githubusercontent.com/25138766/157202411-689a404d-525e-4d72-8168-fe15dba5d211.png)

**Comment by ruibaby** [comment]
这个可能会和很多因素有关，估计不是很好确定问题所在。

**Comment by JohnNiang** [comment]
如果连 favicon.ico 都能卡 1.5s 左右，建议排查一下是不是网络的问题，或者监测一下服务器的资源占用。

**Comment by yuanzhixiang** [comment]
@ruibaby @JohnNiang 我想确认两个问题
1. 你们在使用的时候有遇到过点击写文章或者编辑文章时需要等几秒才能进去的情况么？
2. is_installed 和 post 这两个接口内部有直接或者间接调到缓存么？

**Comment by ruibaby** [comment]
1. 1.5 因为编辑器组件资源略大，首次加载此页面慢是正常的，但不会每次进去都加载。
2. is_installed 有，post 没有。

已经测试到每次调用接口都会调用 is_installed ，这应该属于这个版本的 bug，期望应该是页面刷新才会。

**Comment by yuanzhixiang** [comment]
> 1. 1.5 因为编辑器组件资源略大，首次加载此页面慢是正常的，但不会每次进去都加载。
> 2. is_installed 有，post 没有。
> 
> 已经测试到每次调用接口都会调用 is_installed ，这应该属于这个版本的 bug，期望应该是页面刷新才会。

如果这样说的话那应该就是编辑器资源加载把请求拖慢了，因为我服务器带宽很小，所以加载大的资源时会占满带宽，下面这个截图能看到加载编辑器资源确实非常耗时

![image](https://user-images.githubusercontent.com/25138766/157363466-da28c9d8-df95-4f8b-a379-0abd52b77502.png)

**Comment by yuanzhixiang** [comment]
这种场景是不是有两个优化方向，一种是减少编辑器资源，但是这个可能没那么好改，另一种是在写文章的页面增加 loading 动画。

我看 notion 的编辑器也很大，加载很慢，他的做法就是在编辑器的页面增加等待动画，至少进页面之后我知道他在加载资源，那我就等它一会儿，目前 halo 出现这个情况点击按钮没反应，我以为浏览器卡住了😂，然后就会多点几次或者刷新页面。

**Comment by ruibaby** [comment]
> 如果这样说的话那应该就是编辑器资源加载把请求拖慢了，因为我服务器带宽很小，所以加载大的资源时会占满带宽，下面这个截图能看到加载编辑器资源确实非常耗时
> 
> ![image](https://user-images.githubusercontent.com/25138766/157363466-da28c9d8-df95-4f8b-a379-0abd52b77502.png)

你应该开启 gzip 的，开启 gzip 之后会小很多。

**Comment by yuanzhixiang** [comment]
> 你应该开启 gzip 的，开启 gzip 之后会小很多。

Halo 是在哪儿有个配置项能打开 gzip 么，我之前不知道有这个配置

**Comment by ruibaby** [comment]
> Halo 是在哪儿有个配置项能打开 gzip 么，我之前不知道有这个配置

有用 Nginx 吗？有的话在 Nginx 配置就好了。没有请参考 https://docs.halo.run/getting-started/config#%E5%8E%8B%E7%BC%A9

**Comment by yuanzhixiang** [comment]
> > Halo 是在哪儿有个配置项能打开 gzip 么，我之前不知道有这个配置
> 
> 有用 Nginx 吗？有的话在 Nginx 配置就好了。没有请参考 https://docs.halo.run/getting-started/config#%E5%8E%8B%E7%BC%A9

666，开了之后速度快了一倍

![image](https://user-images.githubusercontent.com/25138766/157365463-abda352b-f823-490e-ae42-05088bca368d.png)
