### ISSUE TITLE
找不到如何将附件中的图片加入到图库

### ISSUE THREAD

**Issue by chenlip** [halo-dev/halo#1725]
### 是什么版本出现了此问题？

V1.5 alpha2 版本

### 使用的什么数据库？

MySQL 5.7

### 使用的哪种方式部署？

Fat Jar

### 发生了什么？

找不到如何将附件中的图片加入到图库 ( /photos ) 中。

**Comment by guqing** [comment]
see https://github.com/halo-dev/halo-admin/pull/468
