### ISSUE TITLE
建议增加API调用白名单

### ISSUE THREAD

**Issue by cnskis** [halo-dev/halo#1728]
### 你当前使用的版本

1.4.17

### 描述一下此特性

目前主题会暴露Access key，采集站或其他人可以通过API进行采集或者提交恶意评论等，建议增加API调用白名单，仅仅只有Access key无法阻止恶意操作。增加白名单功能只允许白名单内的域名或IP访问API。

**Comment by ruibaby** [comment]
这个需求暂时你可以在 Nginx 层面就做限制，在 1.4 版本我们暂无计划。 下一个 major 版本我们会考虑是否需要加这个特性。

**Comment by cnskis** [comment]
> 这个需求暂时你可以在 Nginx 层面就做限制，在 1.4 版本我们暂无计划。 下一个 major 版本我们会考虑是否需要加这个特性。

好的，祝愿越来越好
