### ISSUE TITLE
域名更换引起文章中某些图片丢失

### ISSUE THREAD

**Issue by WaterSunMount** [halo-dev/halo#1732]
### 是什么版本出现了此问题？

1.4.17

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 在线站点地址

https://blog.peakliu.top/

## 域名更换,文章内容的图片没更新
主要涉及到文章内部图片和文章发布时候的图片
看到数据库保存的时候使用的老域名,所以在更换域名后图片信息展示出错

**Comment by WaterSunMount** [comment]
博客设置->博客应已修改为新域名,数据库数据还没更改

**Comment by ruibaby** [comment]
https://bbs.halo.run/d/153
