### ISSUE TITLE
主题的获取最新评论模板标签

### ISSUE THREAD

**Issue by cetr** [halo-dev/halo#1733]
### 描述一下此特性

目前只能获取post页面
提供：
1. sheet页面评论
2. post与sheet一起获得

**Comment by ruibaby** [comment]
1.4 暂时无法做到，下个 major 版本会考虑。

**Comment by ruibaby** [comment]
Halo 2目前已经支持。

https://docs.halo.run/developer-guide/theme/finder-apis/comment#listrefpagesize

/close
