### ISSUE TITLE
后台的博客地址设置是否可以去掉，让系统直接使用当前地址

### ISSUE THREAD

**Issue by cetr** [halo-dev/halo#1734]
### 描述一下此特性

系统-博客设置-常规设置-博客地址

这里的地址是否可以去掉？让系统自动调用当前地址，不要存进数据库，因为正常来说不需要修改这里的地址，也不应该，而且也会造成用户更换域名后或修改ssl后网站链接异常

**Comment by ruibaby** [comment]
系统内部如何知道实际访问地址？

**Comment by cetr** [comment]
admin和前端不是一个整体吗，现在又不提供单独部署后台了，访问链接的根域名就是实际访问地址啊

**Comment by cetr** [comment]
这个设计是为了之前单独部署admin的吧

**Comment by ruibaby** [comment]
我们并不打算不提供单独部署后台，只是目前有些问题无法解决。而且域名的用处也不仅仅在于此。

**Comment by guqing** [comment]
后台需要使用到博客地址用来返回绝对路径 不仅仅是为了前端使用

**Comment by cetr** [comment]
好的，明白了

**Comment by JohnNiang** [comment]
关于域名设置的影响，建议后期设计的时候可以好好考虑一下。比如：域名变更后，系统中有用到域名的地方，尽量同步变更。

**Comment by ruibaby** [comment]
再稍微补充一点，我认为更换域名或者配置 SSL 是一个非常低频的操作，我们没有必要对这种低频操作做代码层面的适配，往往是得不偿失的。而且即便是需要修改域名，也有无损的解决方案。
