### ISSUE TITLE
附件图片质量太高，缩略图无法正常显示问题

### ISSUE THREAD

**Issue by zihanla** [halo-dev/halo#1735]
### 是什么版本出现了此问题？

1.5.0-alpha.1

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 在线站点地址

https://hxcpl.cn

### 发生了什么？

附件图片质量太高，缩略图无法正常显示问题，点开附件,一些几Mb的图片，在附件的缩略图中是空白，要么就是 几张图片一个羊

**Comment by ruibaby** [comment]
你好，你指的是后台附件管理吗？ alpha.1 存在一些问题，建议升级到 alpha.3 再测试一下是否还有这样的问题。

**Comment by zihanla** [comment]
> 你好，你指的是后台附件管理吗？ alpha.1 存在一些问题，建议升级到 alpha.3 再测试一下是否还有这样的问题。
啊这 都alpha.3了 马上 升级

**Comment by ruibaby** [comment]
> 啊这 都alpha.3了 马上 升级

可以先看一下 2 和 3 的改动。https://github.com/halo-dev/halo/releases

**Comment by zihanla** [comment]
> > 啊这 都alpha.3了 马上 升级
> 
> 可以先看一下 2 和 3 的改动。https://github.com/halo-dev/halo/releases

看了 里面刚好 有我提出的问题的修复  已经升级了 附件 重复上一页图片的问题 已经解决了 大大加油！
