### ISSUE TITLE
删除文章后，未审核的评论无法处理

### ISSUE THREAD

**Issue by Alex-Shen1121** [halo-dev/halo#1736]
### 是什么版本出现了此问题？

1.4.17

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Fat Jar

### 在线站点地址

http://106.13.192.248/

### 发生了什么？

原来的文章界面被删除了 但是仍然有未审核的评论没有处理，导致后台管理右上角小红点提示始终无法删除。
<img width="376" alt="image" src="https://user-images.githubusercontent.com/73343630/157726290-81f7244e-8122-4258-ba19-a9be97e376e8.png">
还请开发大佬告知一个解决方法，谢谢

**Comment by JohnNiang** [comment]
@Alex-Shen1121 感谢反馈这个问题。文章被放入回收站之后，是不会删除评论的。只有彻底删除文章后，才会删除评论，右上角的提示才会消失。
