### ISSUE TITLE
编辑文章时，Ctrl + Backspace 会删除全部内容

### ISSUE THREAD

**Issue by AnotiaWang** [halo-dev/halo#1740]
### 是什么版本出现了此问题？

1.4.17

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Fat Jar

#### 问题描述
如题。

#### 复现步骤
1. 在后台中，选择一篇文章，进入编辑模式；输入一些内容。
2. 按 Ctrl + Backspace 。

#### 预期现象
应当删除一个词。

#### 实际现象
文章的全部内容被删除。

#### 系统信息
平台：Windows
版本：Windows 11 Build 22000.556
浏览器：Google Chrome 98.0.4758.102

**Comment by ruibaby** [comment]
你好，经过测试，在 1.5.0-alpha.3 中没有发现此问题。Windows 下 <kbd>Ctrl</kbd> + <kbd>Backspace</kbd>，macOS 下 <kbd>Option</kbd> + <kbd>Backspace</kbd> 都可以实现删除一个词。这应该是 1.4.17 编辑器的问题，你可以在本地测试一下 1.5.0。如果没有此问题，我们可能不再会在 1.4.x 修复。

**Comment by ruibaby** [comment]
可以用 Demo 站点测试下。https://docs.halo.run/#%E5%9C%A8%E7%BA%BF%E4%BD%93%E9%AA%8C

**Comment by AnotiaWang** [comment]
> 可以用 Demo 站点测试下。https://docs.halo.run/#%E5%9C%A8%E7%BA%BF%E4%BD%93%E9%AA%8C

我试了一下 1.5.0-alpha3 版本和 Demo 站点，确实没有这个问题了，谢谢。不过 `Ctrl` + `Backspace` 对于中文似乎会一直删除到标点符号位置。

比如文本 `此站点为 Halo 官方的演示站点，目的是为了让大家能够更|方便快速地体验 Halo。`（`|` 为光标）

执行 `Ctrl` + `Backspace` 之后，会变成 `此站点为 Halo 官方的演示站点，方便快速地体验 Halo。`

理想情况下应该是只删除 “更” 这个单字的，请问有解决办法吗？

**Comment by ruibaby** [comment]
> 理想情况下应该是只删除 “更” 这个单字的，请问有解决办法吗？ 

这个可能得修改 Codemirror 的表现了，估计不会太好修改。

**Comment by AnotiaWang** [comment]
> 这个可能得修改 Codemirror 的表现了，估计不会太好修改。

好的
