### ISSUE TITLE
开发者选项里的静态存储

### ISSUE THREAD

**Issue by cetr** [halo-dev/halo#1746]
### 描述一下此特性

1.建议开发者选项里的静态存储里的文件可以移动文件夹

2.建议开发者选项里的静态存储里的文件非文本类型时不可编辑，比如txt、json、md格式则可以编辑，而exe、apk格式可执行文件不应该可以编辑

**Comment by ruibaby** [comment]
1.x 我们已经不计划添加新的特性。如有必要，我们将在下一个 major 版本提供。

**Comment by JohnNiang** [comment]
Close in favor of <https://github.com/halo-dev/halo/issues/2785>.

/close
