### ISSUE TITLE
编辑的文章在预览显示和实际访问文章，布局不一致

### ISSUE THREAD

**Issue by zihanla** [halo-dev/halo#1753]
### 是什么版本出现了此问题？

1.5.0-alpha.2

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 在线站点地址

https://hxcpl.cn

### 发生了什么？

如图：
[预览1](https://p0.ssl.qhimg.com/t010db1184223a3c8b2.png)
[实际](https://p0.ssl.qhimg.com/t01ccdbd1b1ec275d0e.png)
有点小小的强迫症emmmmm

**Comment by ruibaby** [comment]
这属于主题的表现，我们没有办法保证主题的渲染效果也一直。
