### ISSUE TITLE
新建任意页面访问正常但弹窗报 404

### ISSUE THREAD

**Issue by Qxin-X** [halo-dev/halo#1755]
### 是什么版本出现了此问题？

1.4.17

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Fat Jar

### 在线站点地址

https://blog.xieqingxin.com/test

### 发生了什么？

![屏幕截图 2022-03-17 145319](https://user-images.githubusercontent.com/66522154/158756537-8fd4b185-405a-47a6-868a-5b6326d68a2b.png)

![屏幕截图 2022-03-17 151815](https://user-images.githubusercontent.com/66522154/158757328-b25c87f3-72ad-4ab1-abcf-6dce32c99941.png)

![屏幕截图 2022-03-17 152012](https://user-images.githubusercontent.com/66522154/158757361-b78d22ba-c3d6-4ba4-9149-ec9d1cf8bc01.png)

新建任意页面访问正常但弹窗报 404，检查后发现这个请求路径 404，halo后台日志无相关报错，服务器网站日志相关报错。

**Comment by ruibaby** [comment]
这个你可能需要去 https://github.com/qinhua/halo-theme-joe2.0 仓库提交 issue。这是因为在数字过 1000 之后会自动加逗号导致的。目前需要主题这样写：

```
${post.id?c}
```

**Comment by Qxin-X** [comment]
> 这个你可能需要去 https://github.com/qinhua/halo-theme-joe2.0 仓库提交 issue。这是因为在数字过 1000 之后会自动加逗号导致的。目前需要主题这样写：
> 
> ```
> ${post.id?c}
> ```

好的谢谢
