### ISSUE TITLE
开启ssl后不显示图片

### ISSUE THREAD

**Issue by authon** [halo-dev/halo#1757]
### 是什么版本出现了此问题？

1.4.17

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Fat Jar

### 在线站点地址

https://wentbin.top

### 发生了什么？

<img width="952" alt="image" src="https://user-images.githubusercontent.com/23072698/158894441-a00ee634-7874-4d16-957c-e4485b5bc070.png">
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/23072698/158894487-0db81f7c-2731-4f17-b3f2-29fc32c8ac31.png">
如图，按官方教程使用OneinStack开启ssl后图片不显示，传了一张图片在图库，站点也无法显示，哪位大佬可以帮忙解惑，不使用域名访问没事

**Comment by ruibaby** [comment]
https://docs.halo.run/user-guide/faq#前台样式丢失如何解决

**Comment by authon** [comment]
> [https://docs.halo.run/user-guide/faq#前台样式丢失如何解决](https://docs.halo.run/user-guide/faq#%E5%89%8D%E5%8F%B0%E6%A0%B7%E5%BC%8F%E4%B8%A2%E5%A4%B1%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3)

里面写的两项都有设置，样式貌似都没问题，就是服务器本机的图片不行

**Comment by ruibaby** [comment]
@authon 提供一下 Nginx 配置吧。

**Comment by authon** [comment]
nginx:`user www www;
worker_processes auto;

error_log /data/wwwlogs/error_nginx.log crit;
pid /var/run/nginx.pid;
worker_rlimit_nofile 51200;

events {
  use epoll;
  worker_connections 51200;
  multi_accept on;
}

http {
  include mime.types;
  default_type application/octet-stream;
  server_names_hash_bucket_size 128;
  client_header_buffer_size 32k;
  large_client_header_buffers 4 32k;
  client_max_body_size 1024m;
  client_body_buffer_size 10m;
  sendfile on;
  tcp_nopush on;
  keepalive_timeout 120;
  server_tokens off;
  tcp_nodelay on;

  fastcgi_connect_timeout 300;
  fastcgi_send_timeout 300;
  fastcgi_read_timeout 300;
  fastcgi_buffer_size 64k;
  fastcgi_buffers 4 64k;
  fastcgi_busy_buffers_size 128k;
  fastcgi_temp_file_write_size 128k;
  fastcgi_intercept_errors on;

  #Gzip Compression
  gzip on;
  gzip_buffers 16 8k;
  gzip_comp_level 6;
  gzip_http_version 1.1;
  gzip_min_length 256;
  gzip_proxied any;
  gzip_vary on;
  gzip_types
    text/xml application/xml application/atom+xml application/rss+xml application/xhtml+xml image/svg+xml
    text/javascript application/javascript application/x-javascript
    text/x-json application/json application/x-web-app-manifest+json
    text/css text/plain text/x-component
    font/opentype application/x-font-ttf application/vnd.ms-fontobject
    image/x-icon;
  gzip_disable "MSIE [1-6]\.(?!.*SV1)";

  ##Brotli Compression
  #brotli on;
  #brotli_comp_level 6;
  #brotli_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript application/javascript image/svg+xml;

  ##If you have a lot of static files to serve through Nginx then caching of the files' metadata (not the actual files' contents) can save some latency.
  #open_file_cache max=1000 inactive=20s;
  #open_file_cache_valid 30s;
  #open_file_cache_min_uses 2;
  #open_file_cache_errors on;

  log_format json escape=json '{"@timestamp":"$time_iso8601",'
                      '"server_addr":"$server_addr",'
                      '"remote_addr":"$remote_addr",'
                      '"scheme":"$scheme",'
                      '"request_method":"$request_method",'
                      '"request_uri": "$request_uri",'
                      '"request_length": "$request_length",'
                      '"uri": "$uri", '
                      '"request_time":$request_time,'
                      '"body_bytes_sent":$body_bytes_sent,'
                      '"bytes_sent":$bytes_sent,'
                      '"status":"$status",'
                      '"upstream_time":"$upstream_response_time",'
                      '"upstream_host":"$upstream_addr",'
                      '"upstream_status":"$upstream_status",'
                      '"host":"$host",'
                      '"http_referer":"$http_referer",'
                      '"http_user_agent":"$http_user_agent"'
                      '}';

######################## default ############################
  server {
    listen 80;
    server_name _;
    access_log /data/wwwlogs/access_nginx.log combined;
    root /data/wwwroot/default;
    index index.html index.htm index.php;
    #error_page 404 /404.html;
    #error_page 502 /502.html;
    location /nginx_status {
      stub_status on;
      access_log off;
      allow 127.0.0.1;
      deny all;
    }
    location ~ [^/]\.php(/|$) {
      #fastcgi_pass remote_php_ip:9000;
      fastcgi_pass unix:/dev/shm/php-cgi.sock;
      fastcgi_index index.php;
      include fastcgi.conf;
    }
    location ~ .*\.(gif|jpg|jpeg|png|bmp|swf|flv|mp4|ico)$ {
      proxy_pass http://halo;
      expires 30d;
      access_log off;
    }
    location ~ .*\.(js|css)?$ {
      proxy_pass http://halo;
      expires 7d;
      access_log off;
    }
    location ~ ^/(\.user.ini|\.ht|\.git|\.svn|\.project|LICENSE|README.md) {
      deny all;
    }
    location /.well-known {
      allow all;
    }
  }
########################## vhost #############################
  include vhost/*.conf;
}
`

**Comment by authon** [comment]
wentbin.top:
upstream halo {
  server 127.0.0.1:8090;
}
server {
  listen 80;
  listen [::]:80;
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  client_max_body_size 10240m;
  ssl_certificate /usr/local/nginx/conf/ssl/7361694_wentbin.top.pem;
  ssl_certificate_key /usr/local/nginx/conf/ssl/7361694_wentbin.top.key;
  ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
  ssl_ciphers TLS13-AES-256-GCM-SHA384:TLS13-CHACHA20-POLY1305-SHA256:TLS13-AES-128-GCM-SHA256:TLS13-AES-128-CCM-8-SHA256:TLS13-AES-128-CCM-SHA256:EECDH+CHACHA20:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5;
  ssl_prefer_server_ciphers on;
  ssl_session_timeout 10m;
  ssl_session_cache builtin:1000 shared:SSL:10m;
  ssl_buffer_size 1400;
  add_header Strict-Transport-Security max-age=15768000;
  ssl_stapling on;
  ssl_stapling_verify on;
  server_name wentbin.top;
  access_log /data/wwwlogs/wentbin.top_nginx.log combined;
  index index.html index.htm index.php;
  root /data/wwwroot/wentbin.top;
  if ($ssl_protocol = "") { return 301 https://$host$request_uri; }
  
  include /usr/local/nginx/conf/rewrite/none.conf;
  #error_page 404 /404.html;
  #error_page 502 /502.html;
  location ~ .*\.(wma|wmv|asf|mp3|mmf|zip|rar|jpg|gif|png|swf|flv|mp4)$ {
    valid_referers none blocked *.wentbin.top wentbin.top;
    if ($invalid_referer) {
        return 403;
    }
  }

location ~ .*\.(gif|jpg|jpeg|png|bmp|swf|flv|mp4|ico)$ {
  proxy_pass http://halo;
  expires 30d;
  access_log off;
}
location ~ .*\.(js|css)?$ {
  proxy_pass http://halo;
  expires 7d;
  access_log off;
}
  location ~ /(\.user\.ini|\.ht|\.git|\.svn|\.project|LICENSE|README\.md) {
    deny all;
  }
  location / {
  proxy_set_header HOST $host;
  proxy_set_header X-Forwarded-Proto $scheme;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_pass http://halo;
}
  location /.well-known {
    allow all;
  }
}

**Comment by ruibaby** [comment]
```nginx
  location ~ .*\.(wma|wmv|asf|mp3|mmf|zip|rar|jpg|gif|png|swf|flv|mp4)$ {
    valid_referers none blocked *.wentbin.top wentbin.top;
    if ($invalid_referer) {
        return 403;
    }
  }
```

尝试去掉这一段再重启试试。

**Comment by authon** [comment]
> ```nginx
>   location ~ .*\.(wma|wmv|asf|mp3|mmf|zip|rar|jpg|gif|png|swf|flv|mp4)$ {
>     valid_referers none blocked *.wentbin.top wentbin.top;
>     if ($invalid_referer) {
>         return 403;
>     }
>   }
> ```
> 
> 尝试去掉这一段再重启试试。

去掉之后无法启动nginx

**Comment by authon** [comment]
> ```nginx
>   location ~ .*\.(wma|wmv|asf|mp3|mmf|zip|rar|jpg|gif|png|swf|flv|mp4)$ {
>     valid_referers none blocked *.wentbin.top wentbin.top;
>     if ($invalid_referer) {
>         return 403;
>     }
>   }
> ```
> 
> 尝试去掉这一段再重启试试。

可以了，就是这段代码的问题

**Comment by neetcoder17** [comment]
同样出现这个问题。采用的是 `oneinstack` 安装 `Nginx`。使用 `vhost.sh` 配置的时候开启了防盗链处理会出现 `blocked` 掉域名相关图片资源的这段代码。请问可否考虑在官方文档中注明一下呢，文档中对防盗链的说明是根据需要是否开启，如果类似我这样对盗链有所了解，但对防盗链的实现不太了解的人，可能会选择开启，就会出现类似问题。
