### ISSUE TITLE
升级之后，之前的一些文章数据不见了

### ISSUE THREAD

**Issue by Zhang-BigSmart** [halo-dev/halo#1758]
### 是什么版本出现了此问题？

升级到1.4.17

### 使用的什么数据库？

MySQL 5.7

### 使用的哪种方式部署？

Docker

### 发生了什么？

文章数据少了很多

**Comment by Edisonboy** [comment]
之前是用docker启动的 版本是两年前的
<img width="994" alt="image" src="https://user-images.githubusercontent.com/19949495/159125102-fd4c9e93-15e9-4fd6-af5a-4efccd9757fe.png">
刚按照docker 的升级步骤，升级到1.4.17的镜像。
发现文章数据只有两年前的，这中间的数据都不见了

**Comment by ruibaby** [comment]
MySQL 中的数据正常？

**Comment by Edisonboy** [comment]
文章的数据库是在哪个表

**Comment by Edisonboy** [comment]
可以将之前旧版本的数据覆盖过去吗

**Comment by ruibaby** [comment]
> 文章的数据库是在哪个表

posts

**Comment by ruibaby** [comment]
> 可以将之前旧版本的数据覆盖过去吗
> 
> 

我们无法什么操作步骤会导致这样的问题，目前你得先确认你的数据是否在数据库中还存在。

**Comment by Edisonboy** [comment]
数据库是有的

**Comment by ruibaby** [comment]
> 数据库是有的

那就确认创建容器内是否使用了你这个 MySQL 的库。

建议先确保是否是使用的 MySQL，可以在后台关于页面看到。

**Comment by JohnNiang** [comment]
请问升级之前的版本是什么呢？

**Comment by Edisonboy** [comment]
> 请问升级之前的版本是什么呢？

1.2.0

**Comment by Edisonboy** [comment]
> > 数据库是有的
> 
> 那就确认创建容器内是否使用了你这个 MySQL 的库。
> 
> 建议先确保是否是使用的 MySQL，可以在后台关于页面看到。

确定使用的，不然账号密码登陆不进去

**Comment by ruibaby** [comment]
@Edisonboy 根据目前现有条件，我们无法判断是什么原因导致的，如果如你所说确认是使用了这个数据正确的 MySQL 库。

**Comment by hapke24** [comment]
看一下新增文章表中的数据会不会增加

**Comment by ruibaby** [comment]
如果没有后续反馈，我们将关闭此 issue。
