### ISSUE TITLE
一个关于个人资料的建议

### ISSUE THREAD

**Issue by Liner03** [halo-dev/halo#1768]
### 你当前使用的版本

1.5

### 描述一下此特性

希望在后台个人资料设置里能支持下面这个语法。[https://img30.360buyimg.com/pop/jfs/t1/105041/26/25831/6915/623c0b83Ef81dc383/816c6dd24c73b039.png](https://img30.360buyimg.com/pop/jfs/t1/105041/26/25831/6915/623c0b83Ef81dc383/816c6dd24c73b039.png)
图片链接

**Comment by ruibaby** [comment]
你好，现在应该是支持保存 html，但后台没有支持直接显示 html，而且主题调用可能需要做适配。我认为后台不应该为这种写法做适配。
