### ISSUE TITLE
博客文章里面评论下方一直在转圈

### ISSUE THREAD

**Issue by AlexMahao** [halo-dev/halo#177]
![image](https://user-images.githubusercontent.com/15081212/58776031-237a1680-85fb-11e9-80a8-b8af101f287a.png)

**Comment by JohnNiang** [comment]
请问在管理端设置好了博客地址么？

**Comment by AlexMahao** [comment]
![image](https://user-images.githubusercontent.com/15081212/58776955-d730d580-85fe-11e9-8aef-88db01f11b79.png)
您说的管理端是指?

**Comment by AlexMahao** [comment]
![image](https://user-images.githubusercontent.com/15081212/58777042-f7609480-85fe-11e9-8de3-9fced488abd1.png)

**Comment by JohnNiang** [comment]
这就是管理端，请在 系统 | 系统设置 | 查看一下博客地址是否设置正确。

**Comment by AlexMahao** [comment]
已经设置了。而且该地址也可以访问。

**Comment by AlexMahao** [comment]
http://spearbothy.com

**Comment by AlexMahao** [comment]
![image](https://user-images.githubusercontent.com/15081212/58777159-94bbc880-85ff-11e9-896c-5fbba3f5722b.png)
貌似是我们没有通过的原因。通过之后就好了。

**Comment by JohnNiang** [comment]
您好！后台似乎出错了，可以提供一下日志么？

> 日志默认目录在：`~/.halo/logs/spring.log`

**Comment by AlexMahao** [comment]
[spring.log](https://github.com/halo-dev/halo/files/3245920/spring.log)

**Comment by JohnNiang** [comment]
好的，非常感谢您提供详细的日志，已经保存至本地。

> 由于日志中包含有敏感信息，我这里就为你删除了。

**Comment by AlexMahao** [comment]
好的，麻烦了。

**Comment by JohnNiang** [comment]
问题已经修复，谢谢您的反馈！

<https://github.com/halo-dev/halo/commit/9b92867ea38b3d891ec48e916d581e993097edb7>
