### ISSUE TITLE
编辑文章保存功能页面优化

### ISSUE THREAD

**Issue by bxbdba** [halo-dev/halo#1772]
### Your current Halo version

1.5.0

### Describe this feature

当前情况是页面修改文章保存后，提示：“当前内容已保存，但还未发布。”，但继续修改文章，还是会有该提示，建议是能够实时显示当前文章是否已保存

**Comment by ruibaby** [comment]
你好，当前设计就是这样的，这个提示仅仅针对内容，也就是用于提示是否有未发布的内容。只要文章被发布或者更新这个提示就没有了。

**Comment by ruibaby** [comment]
> 你好，当前设计就是这样的，这个提示仅仅针对内容，也就是用于提示是否有未发布的内容。只要文章被发布或者更新这个提示就没有了。

因为我们现在在后台编辑内容，前台是不会实时更新的，所以有这样的设计。

**Comment by ruibaby** [comment]
@bxbdba 你好，目前还有这样的疑问吗？

**Comment by bxbdba** [comment]
没有了。谢谢大佬。
