### ISSUE TITLE
导入markdown文章，分类标签解析错误

### ISSUE THREAD

**Issue by Alex-Shen1121** [halo-dev/halo#1773]
### 是什么版本出现了此问题？

1.5.0

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Fat Jar

### 在线站点地址

http://106.13.192.248/

### 发生了什么？

我首先通过后台关系界面的markdown导出功能，导出了md文章。
文章中自动生成了部分的信息
<img width="475" alt="image" src="https://user-images.githubusercontent.com/73343630/160231235-a57d2ace-1128-46de-b4d7-75702dbcb321.png">
然后在使用导入功能时，不会根据 | 对于标签、分类进行分割。即原来属于多个分类、标签，一并合并到了一起。
![image](https://user-images.githubusercontent.com/73343630/160231349-d61b1878-472f-4a28-b6d2-09133c21aa63.png)
希望作者可以在下个版本 修改这个bug。辛苦了

**Comment by JohnNiang** [comment]
@Alex-Shen1121 请问你使用的是什么平台的 Markdown FrontMatter 语法呢？我这边找到几个常见的语法中没有包含 `|` 作为分隔符的 tag，请参考：

- https://gohugo.io/content-management/front-matter/
- https://jekyllrb.com/docs/front-matter/
- https://hexo.io/docs/front-matter.html

**Comment by Alex-Shen1121** [comment]
> @Alex-Shen1121 请问你使用的是什么平台的 Markdown FrontMatter 语法呢？我这边找到几个常见的语法中没有包含 `|` 作为分隔符的 tag，请参考：
> 
> * https://gohugo.io/content-management/front-matter/
> * https://jekyllrb.com/docs/front-matter/
> * https://hexo.io/docs/front-matter.html

我是先利用后台管理系统中的 系统——小工具——博客备份markdown 导出文章。（文章的分类、标签包含多个）。然后直接将该文章通过 系统——Markdown 文章导入 就会出现描述的问题。

**Comment by JohnNiang** [comment]
![image](https://user-images.githubusercontent.com/16865714/160282109-d1e18978-8421-4609-9f7b-6e8c90de74b4.png)

请问这个图片中的 tags 和 categories 的语法是参考过什么文档么？

**Comment by LIlGG** [comment]
> ![image](https://user-images.githubusercontent.com/16865714/160282109-d1e18978-8421-4609-9f7b-6e8c90de74b4.png)
> 
> 请问这个图片中的 tags 和 categories 的语法是参考过什么文档么？

这个语法是我们系统的 `小工具 - 导出 markdown 文档` 导出的 md 文件语法。 应该是在导出时处理多个标签/分类的语法有误。 这块应该在导出的时候进行处理。

**Comment by Alex-Shen1121** [comment]
> ![image](https://user-images.githubusercontent.com/16865714/160282109-d1e18978-8421-4609-9f7b-6e8c90de74b4.png)
> 
> 请问这个图片中的 tags 和 categories 的语法是参考过什么文档么？

不好意思，我没有太理解。我是直接解压缩，然后从typora中打开markdown文件后截图的。没有进行过任何操作
