### ISSUE TITLE
文章访问量在某些还不确定情况下访问一次会加2

### ISSUE THREAD

**Issue by cetr** [halo-dev/halo#1774]
### What is version of Halo has the issue?

1.5

### What database are you using?

MySQL 8.x

### What is your deployment method?

Fat Jar

### What happened?

文章访问量在部分主题下访问一次会加2或3
docker和jar方式启动都有问题
数据库H2或MySQL都会

**Comment by cetr** [comment]
目前定位到是评论组件的原因，还未具体查清楚

**Comment by cetr** [comment]
已确认问题并已修复评论组件

**Comment by JohnNiang** [comment]
> 已确认问题并已修复评论组件

太棒了！可以贴一下修复的链接么😌

**Comment by ruibaby** [comment]
> > 已确认问题并已修复评论组件
> 
> 太棒了！可以贴一下修复的链接么😌

maybe https://github.com/cetr/halo-comment-yu/commit/9019410ac863f4ece66347016f4ad71405c5256a

**Comment by ruibaby** [comment]
@cetr 其实我根据这个提交没看明白是什么问题导致的，方便简单说说吗？

https://github.com/cetr/halo-comment-yu/commit/9019410ac863f4ece66347016f4ad71405c5256a

**Comment by cetr** [comment]
> @cetr 其实我根据这个提交没看明白是什么问题导致的，方便简单说说吗？
> 
> [cetr/halo-comment-yu@9019410](https://github.com/cetr/halo-comment-yu/commit/9019410ac863f4ece66347016f4ad71405c5256a)

是的，就是这里的原因

`const gravatarSource = this.options.gravatar_source || '//cn.gravatar.com/avatar/';`

因为之前我看avatar会加载两次，而第一次总会把 gravatarSource 先赋值为 `//cn.gravatar.com/avatar/` 
从而导致浏览器Network里一片avatar加载失败的请求，所以在前段时间我把avatar第一次强制return ‘#’
结果就是导致第一次加载时返回了 `#`，页面会去再请求一遍服务器

**Comment by ruibaby** [comment]
> 所以在前段时间我把avatar第一次强制return ‘#’
结果就是导致第一次加载时返回了 #，页面会去再请求一遍服务器

明白了。
