### ISSUE TITLE
文章发布设置的置顶选项第一次打开无法关闭

### ISSUE THREAD

**Issue by A13437858** [halo-dev/halo#1776]
### 是什么版本出现了此问题？

1.5.0

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 在线站点地址

www.wchh.xyz

### 发生了什么？

后台发布文章设置界面，自动打开置顶选项且无法关闭，但点击返回再次打开发布设置又可以正常开关了，换浏览器和手机也没有变化。

### 附加信息

![image](https://user-images.githubusercontent.com/84067985/160283507-337ea272-5d0a-4554-9cf9-7d53ced697c4.png)

**Comment by ruibaby** [comment]
在 https://github.com/halo-dev/halo-admin/pull/525 中已修复。
