### ISSUE TITLE
回收站的文章无法删除，提示“content was not found or has been deleted”，同时还原文章显示“Internal Server Error”

### ISSUE THREAD

**Issue by RalstonLiu** [halo-dev/halo#1780]
### 是什么版本出现了此问题？

1.5.0

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 在线站点地址

https://blog.laoda.de/

### 发生了什么？

回收站的文章无法删除，提示“content was not found or has been deleted”，同时还原文章显示“Internal Server Error”

![image-20220328111715339](https://img.laoda.de/i/2022/03/28/ih50pi_7.webp)
![image-20220328111809871](https://img.laoda.de/i/2022/03/28/ihqtl4_7.webp)
![image-20220328111829732](https://img.laoda.de/i/2022/03/28/ihym7q_7.webp)

### 附加信息

环境信息：
版本：1.5.0
数据库：H2 1.4.199 (2019-03-13)
运行模式：production
启用主题：Joe2.0
User Agent：Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15

**Comment by ruibaby** [comment]
原因是升级或者降级之后导致的，数据库的表数据缺失。但经过重新升级之后一切正常，所以暂时无法确定是否是升级带来的问题。
