### ISSUE TITLE
1.5.0  不支持文章快速定位，不支持一键复制

### ISSUE THREAD

**Issue by hotspring-zwb** [halo-dev/halo#1782]
### 是什么版本出现了此问题？

1.5.0

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Fat Jar

### 1.4.5 文章预览页面 
![image](https://user-images.githubusercontent.com/14340226/160372496-a22bb5cb-0ecf-4247-800b-5c7d0e06f948.png)
### 1.5.0 文章预览
![QQ截图20220328174211](https://user-images.githubusercontent.com/14340226/160372601-1a83fefa-765f-4917-bb3e-411a29ed08ce.png)

**Comment by ruibaby** [comment]
你好，明白你的意思，可是你提供的这两个预览都不是同一个主题呀。

**Comment by hotspring-zwb** [comment]
能配置成之前那样的么？或者能不能有个预览页面的主题样式选择，或者指导下怎么改，想升级到1.5.0 获取新功能，看到这个预览效果，犹豫了

**Comment by ruibaby** [comment]
你 1.4.5 的截图是这个主题：https://halo.run/archives/theme-simple-bootstrap.html
你 1.5.0 的截图是这个：https://halo.run/archives/theme-anatole.html

主题都不一样效果怎么会一样呢，你可以尝试启用你在 1.4.5 截图的那个主题再看看。
