### ISSUE TITLE
邮箱发送测试提示的BUG

### ISSUE THREAD

**Issue by hapke24** [halo-dev/halo#1788]
### 是什么版本出现了此问题？

1.5.0

### 使用的什么数据库？

MySQL 5.7

### 使用的哪种方式部署？

Fat Jar

### 发生了什么？

发送成功了，但是提示信息只有一个图标：
![1648548788(1)](https://user-images.githubusercontent.com/49407099/160589277-0f274c9c-e3f7-4f1c-becf-8293dbf1c656.jpg)

### 附加信息

套了一层cloudflare，并且开了缓存
经过测试，删除评论时的提示正常显示
![image](https://user-images.githubusercontent.com/49407099/160590457-030b408b-168e-4376-80f4-ffe10bc23be6.png)

**Comment by ruibaby** [comment]
你好 @hapke24 ，可以提供一下浏览器控制台日志和 Halo 的日志吗

**Comment by hapke24** [comment]
Halo 日志
```
2022-03-29 18:27:17.257  INFO 26920 --- [pool-4-thread-3] run.halo.app.mail.AbstractMailService    : Sent an email to [[root@hapke.cn]] successfully, subject: [测试], sent date: [Tue Mar 29 18:27:16 CST 2022]
```
浏览器控制台日志为空
![image](https://user-images.githubusercontent.com/49407099/160592099-7670ece5-4be5-46bd-9ce7-026aa4b4ac6c.png)
浏览器网络详情
![image](https://user-images.githubusercontent.com/49407099/160592361-f326d4aa-8ae9-4a3b-a478-40d4c7ebaa3e.png)
