### ISSUE TITLE
文章别名自动生成建议

### ISSUE THREAD

**Issue by DAMYSDS** [halo-dev/halo#1790]
### Your current Halo version

1.5.0

### Describe this feature

文章别名即为文章链接后缀，建议自动生成引入发布时间，以发布时间为链接后缀，避免了中文

### Additional information

![QQ图片20220329213618](https://user-images.githubusercontent.com/40637253/160623790-d2d9dc23-4de1-4deb-b470-6c0ad3e51de3.png)
![QQ图片20220329213655](https://user-images.githubusercontent.com/40637253/160623923-831ddf89-35ba-4d8e-8787-1f0cdf2adbb3.png)
![QQ图片20220329213732](https://user-images.githubusercontent.com/40637253/160623998-652730b0-f565-43ca-a28a-2310d05edb59.png)

**Comment by ruibaby** [comment]
早期确实是时间戳，但大部分使用者反馈时间戳看不懂，才改成这样的方式。这其实也是大部分 slug 生成主流的方式。所以，既然有这样的分歧，在后续 2.0 我们会考虑多种生成规则以供选择，但目前 1.x 不打算做此修改。

/kind feature

**Comment by skyls03** [comment]
可以将文章的CRC32或者UUID等 生成唯一标识，取前8位或者更多，然后将其作为文章的Permalink

Hexo中有个插件[hexo-abbrlink](https://github.com/rozbo/hexo-abbrlink)、[hexo-abbrlink2](https://github.com/rozbo/hexo-abbrlink2)，就是这种

**Comment by wanglichao6888** [comment]
期待文章别名有多种生成规则

**Comment by wanglichao6888** [comment]
期待文章别名有多种生成规则，感谢！

**Comment by GodlessLiu** [comment]
可以在文章设置下面提供一个配置来给用户进行选择使用哪种模式，然后在生成文章链接的地方拿到这个配置，对这个配置进行判断用来生成对应链接。
<img width="1176" alt="image" src="https://github.com/halo-dev/halo/assets/110895612/5f4cdec6-61c1-4ce7-9e9a-3dc323b79157">
