### ISSUE TITLE
进不去主页 显示500

### ISSUE THREAD

**Issue by WangTsaiboy** [halo-dev/halo#1799]
### What is version of Halo has the issue?

1.5.1

### What database are you using?

MySQL 5.7

### What is your deployment method?

Docker

### What happened?

访问主页的时候出现500
Internal Server Error.
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.IllegalArgumentException: Top number must not be less than 0

### Relevant log output

```shell
500
Internal Server Error.
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.IllegalArgumentException: Top number must not be less than 0
```

**Comment by ruibaby** [comment]
你好 @WangTsaiboy ，可以提供一下 spring.log 中更完整的日志吗？

**Comment by WangTsaiboy** [comment]
在哪可以看见啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "halo-dev/halo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月31日(星期四) 晚上9:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [halo-dev/halo] 进不去主页 显示500 (Issue #1799)





 
你好 @WangTsaiboy ，可以提供一下 spring.log 中更完整的日志吗？

**Comment by ruibaby** [comment]
> 在哪可以看见啊

https://docs.halo.run/user-guide/faq#%E5%A6%82%E4%BD%95%E6%9F%A5%E7%9C%8B%E8%BF%90%E8%A1%8C%E6%97%A5%E5%BF%97

**Comment by WangTsaiboy** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "halo-dev/halo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月31日(星期四) 晚上10:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [halo-dev/halo] 进不去主页 显示500 (Issue #1799)





  
在哪可以看见啊
  
https://docs.halo.run/user-guide/faq#%E5%A6%82%E4%BD%95%E6%9F%A5%E7%9C%8B%E8%BF%90%E8%A1%8C%E6%97%A5%E5%BF%97

**Comment by WangTsaiboy** [comment]
解决了吗

**Comment by ruibaby** [comment]
> 解决了吗

什么解决了吗？

**Comment by WangTsaiboy** [comment]
进不去啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "halo-dev/halo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月1日(星期五) 晚上9:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [halo-dev/halo] 进不去主页 显示500 (Issue #1799)





  
解决了吗
  
什么解决了吗？

**Comment by ruibaby** [comment]
> 进不去啊

请提供日志以便让我们排查。

**Comment by IILee5** [comment]
你但凡使用docker logs halo 截图出来你所看到的东西，都比你现在这样粘贴一大堆没用的东西要好。

**Comment by ruibaby** [comment]
> 我发了附件啊
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 
> 发件人:                                                                                                                        "halo-dev/halo"                                                                                    ***@***.***&gt;;
> 
> 发送时间:&nbsp;2022年4月1日(星期五) 晚上9:52
> 
> ***@***.***&gt;;
> 
> ***@***.******@***.***&gt;;
> 
> 主题:&nbsp;Re: [halo-dev/halo] 进不去主页 显示500 (Issue #1799)
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
>   
> 
> 进不去啊
> 
>   
> 
> 请提供日志以便让我们排查。
> 
>  
> 
> —
> 
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

你上 GitHub看看这个 issue

**Comment by linshenkx** [comment]
## docker下由1.5.0升级到1.5.1遇到类似问题
网页显示500错误：org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.IllegalArgumentException: html content must not be null。
## 日志正常，无报错。见附件

## 无法正常回滚
SQL State  : 23000
Error Code : 1062
Message    : Duplicate entry '2' for key 'PRIMARY'
Location   : migration/V6__migrate_create_contents_table.sql (/application/BOOT-INF/classes/migration/V6__migrate_create_conten
Line       : 2
Statement  : -- Migrate post content to contents table
INSERT INTO contents(post_id, status, patch_log_id, head_patch_log_id, content, original_content, create_time,
                     update_time)
SELECT id,
       status,
       id,
       id,
       format_content,
       original_content,
       create_time,
       update_time
FROM posts
## 个人临时解决方法
用前一天的数据库备份文件重新部署一套，并使用1.5.0版本镜像（另外需要重新选择主题，不知道是不是bug）
## 参考测试网址：
1.5.0（正常）：https://linshenkx.cn
1.5.1（500）：https://bug.linshenkx.cn

**Comment by ruibaby** [comment]
@linshenkx 看看是不是和这个类似 https://github.com/halo-dev/halo/issues/1765

**Comment by linshenkx** [comment]
> @linshenkx 看看是不是和这个类似 #1765

应该不是。升级过程是正常的，也没有任何报错。只是我要从1.5.1回滚到1.5.0才出现了上面的数据库异常。重点是页面的500，这个没解决就一直不能升级了。

**Comment by ruibaby** [comment]
> > @linshenkx 看看是不是和这个类似 #1765
> 
> 
> 
> 应该不是。升级过程是正常的，也没有任何报错。只是我要从1.5.1回滚到1.5.0才出现了上面的数据库异常。重点是页面的500，这个没解决就一直不能升级了。

你的日志里包含 `Starting Application v1.4.16`，就是和那个 issue 一样的问题。至于 `html content must not be null` 的问题，晚点我们构建一个 master 分支的包，麻烦帮我们测试一下。

**Comment by ruibaby** [comment]
@linshenkx 如果可以，请帮我们测试一下，这个问题应该已经被修复。https://ryanc.cc/upload/2022/04/halo-1.5.2.jar

**Comment by linshenkx** [comment]
> @linshenkx 如果可以，请帮我们测试一下，这个问题应该已经被修复。https://ryanc.cc/upload/2022/04/halo-1.5.2.jar

经测试，500的问题已修复，但数据库的问题还存在。我暂时通过回滚flyway_schema_history表解决。
日志：[spring.log](https://github.com/halo-dev/halo/files/8448364/spring.log)
回滚sql：[flyway.sql.txt](https://github.com/halo-dev/halo/files/8448370/flyway.sql.txt)

**Comment by ruibaby** [comment]
> > @linshenkx 如果可以，请帮我们测试一下，这个问题应该已经被修复。https://ryanc.cc/upload/2022/04/halo-1.5.2.jar
> 
> 
> 
> 经测试，500的问题已修复，但数据库的问题还存在。我暂时通过回滚flyway_schema_history表解决。
> 
> 日志：[spring.log](https://github.com/halo-dev/halo/files/8448364/spring.log)
> 
> 回滚sql：[flyway.sql.txt](https://github.com/halo-dev/halo/files/8448370/flyway.sql.txt)
> 
> 

手动降级导致的这个问题已经没有办法修复了，只能按照那个 issue 给出的方案解决。

**Comment by WangTsaiboy** [comment]
你自己要的spring.log




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "halo-dev/halo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月1日(星期五) 晚上9:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [halo-dev/halo] 进不去主页 显示500 (Issue #1799)





 
你但凡使用docker logs halo 截图出来你所看到的东西，都比你现在这样粘贴一大堆没用的东西要好。
