### ISSUE TITLE
1.4.5 升级 1.5.0 图片本地上创 markdown 链接问题

### ISSUE THREAD

**Issue by hotspring-zwb** [halo-dev/halo#1800]
### 是什么版本出现了此问题？

1.5.0

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Fat Jar

### 拖拽图标到编辑器，路径有前缀，upload 路径中多了斜杠

![QQ截图20220331222019](https://user-images.githubusercontent.com/14340226/161077685-9d2cb4f6-292c-434a-a81f-cab1ad0bcbfd.png)

### 试了下，1.5.0 新包直接部署，没有带域名前缀, 03 后面多了斜杠
![QQ截图20220331223011](https://user-images.githubusercontent.com/14340226/161079703-d38aec8f-4b27-4c46-8982-96108ef80b2d.png)

```
![test-1648735837488](/upload/2022/03//test-1648735837488.png)
```
期望： 如何让上传图片不带上 域名前缀，路径去除多余斜杠，方便以后域名切换

**Comment by ruibaby** [comment]
你好 @hotspring-zwb ，没能复现这个问题，能提供一下这个图片吗？

**Comment by ruibaby** [comment]
> 我是 windows 机器部署

那可能和 Windows 有关。

/cc @halo-dev/sig-halo 需要测试一下

**Comment by ruibaby** [comment]
> 1.4.5 升级到 1.5.0 图片路径是 http://xxx.com/upload...

这个可能是你在后台打开了全局绝对路径。

<img width="2269" alt="image" src="https://user-images.githubusercontent.com/21301288/161085003-c1cf8efe-b87e-467a-8645-a09c29984d65.png">

**Comment by ruibaby** [comment]
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/21301288/161085356-397a3eda-baee-48fc-8248-2ed452881895.png">

demo 服务也是从 1.4 升到 1.5 的，没有发现这样的问题。

**Comment by hotspring-zwb** [comment]
确实是绝地路径的问题，但是多出来的 / 还是在
![image](https://user-images.githubusercontent.com/14340226/161086444-c1c4aaa1-7bee-4783-b8ac-2b80dca3aa5d.png)
