### ISSUE TITLE
MySQL 与 Halo 服务不在同一地区，导致查询速度慢。

### ISSUE THREAD

**Issue by VicoHu** [halo-dev/halo#1801]
### 是什么版本出现了此问题？

1.5.1

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker

### 发生了什么？

页面document加载时间超级长，换过几个主题了，默认的也用了，一样的时间很长
在服务器访问数据库的速度也很快，基本都是毫秒级的
![image](https://user-images.githubusercontent.com/46861221/161111260-26c50177-bb02-48d0-b542-43a7d9654a11.png)

### 相关日志输出

```shell
无报错日志
```

**Comment by ruibaby** [comment]
你好 @VicoHu ，你的 MySQL 服务在哪个位置呢？

**Comment by VicoHu** [comment]
> 你好 @VicoHu ，你的 MySQL 服务在哪个位置呢？

服务器用的华为云的，在北京。mysql用的阿里云的，在杭州

**Comment by ruibaby** [comment]
> 服务器用的华为云的，在北京。mysql用的阿里云的，在杭州

应该就是地域原因。建议使用同地域的服务器，或者部署在同一台服务器。

**Comment by VicoHu** [comment]
> > 服务器用的华为云的，在北京。mysql用的阿里云的，在杭州
> 
> 应该就是地域原因。建议使用同地域的服务器，或者部署在同一台服务器。

好的，我晚点试试使用本地mysql，看看是否还能复现这个问题

**Comment by ruibaby** [comment]
> 好的，我晚点试试使用本地mysql，看看是否还能复现这个问题

你好 @VicoHu ，有复现这个问题吗？

**Comment by VicoHu** [comment]
用了本地mysql后，问题解决了，没有复现

**Comment by VicoHu** [comment]
> > 好的，我晚点试试使用本地mysql，看看是否还能复现这个问题
> 
> 你好 @VicoHu ，有复现这个问题吗？

用了本地mysql后，问题解决了，没有复现
