### ISSUE TITLE
建议优化内存

### ISSUE THREAD

**Issue by bigbugcc** [halo-dev/halo#1809]
### 你当前使用的版本

latest

### 描述一下此特性

Docker运行
闲时无访问的情况大概吃400M内存，这个对小鸡不太友好😭

**Comment by ruibaby** [comment]
你好，这其实已经是一个正常的水平了。不过你可以尝试修改一下这个环境变量。https://github.com/halo-dev/halo/blob/438b977f05fda8d4a650f6868bdaa24933263259/Dockerfile#L18

**Comment by ruibaby** [comment]
```bash
docker run -it -d --name halo -p 8090:8090 -v ~/.halo:/root/.halo --restart=unless-stopped -e JVM_OPTS="-Xmx128m -Xms128m" halohub/halo:1.5.1
```

**Comment by bigbugcc** [comment]
> ```shell
> docker run -it -d --name halo -p 8090:8090 -v ~/.halo:/root/.halo --restart=unless-stopped -e JVM_OPTS="-Xmx128m -Xms128m" halohub/halo:1.5.1
> ```

这个过于压缩jvm会不会导致性能有所牺牲

**Comment by guqing** [comment]
> 

那你可以根据你服务器的资源来决定给jvm分配多少内存，通过jvisualvm之类的工具看看jvm内存占用情况 取一个合适的内存大小

**Comment by guqing** [comment]
<img width="698" alt="image" src="https://user-images.githubusercontent.com/38999863/161376606-d29c8713-4948-4b39-9b78-31569001a624.png">
<img width="1898" alt="image" src="https://user-images.githubusercontent.com/38999863/161377443-1d7d68b3-d02f-4c9c-a670-9db55d325988.png">

建议你内存不要限制太低，可以设置300M 最低不要低于250M, 否则gc会频繁导致变慢

**Comment by ruibaby** [comment]
> 这个过于压缩jvm会不会导致性能有所牺牲

是的，可能会导致频繁 GC。

**Comment by bigbugcc** [comment]
> <img alt="image" width="698" src="https://user-images.githubusercontent.com/38999863/161376606-d29c8713-4948-4b39-9b78-31569001a624.png">
> 
> <img alt="image" width="1898" src="https://user-images.githubusercontent.com/38999863/161377443-1d7d68b3-d02f-4c9c-a670-9db55d325988.png">
> 
> 建议你内存不要限制太低，可以设置300M 最低不要低于250M, 否则gc会频繁导致变慢
> 
> > 附上我博客的gc日志，50多篇文章
> > 设置JVM_OPTS="-Xmx256m -Xms256m" 就足够了
> > [gc.log](https://github.com/halo-dev/halo/files/8402290/gc.log)

好的 谢谢🎉

**Comment by zyy247796143** [comment]
> ```shell
> docker run -it -d --name halo -p 8090:8090 -v ~/.halo:/root/.halo --restart=unless-stopped -e JVM_OPTS="-Xmx128m -Xms128m" halohub/halo:1.5.1
> ```
你好，我同样使用128m 的的内存限制，好像都不生效。内存同样会升到400m左右。是halo:1.5.2版本的。而且进程上会看到两个`-Xms -Xmx`，这是正常的吗？
```
[root@hecs-399460 halo]# docker exec -it halo ps -elf
F S UID        PID  PPID  C PRI  NI ADDR SZ WCHAN  STIME TTY          TIME CMD
4 S root         1     0  0  80   0 -   650 do_wai 17:42 ?        00:00:00 /bin/sh -c java -Xms${JVM_XMS} -Xmx${JVM_XMX} ${JVM_OPTS} -Djava.security.egd=file:/dev/./urandom org.springframework.boot.loa
4 S root         6     1 72  80   0 - 556668 futex_ 17:42 ?       00:00:34 java -Xms256m -Xmx256m -Xmx128m -Xms128m -Djava.security.egd=file:/dev/./urandom org.springframework.boot.loader.JarLauncher
4 R root        36     0  0  80   0 -  2221 -      17:43 pts/0    00:00:00 ps -elf
[root@hecs-399460 halo]# docker stats

CONTAINER ID   NAME          CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O         PIDS
99a8109630b8   halo          0.00%     361.1MiB / 1.794GiB   19.65%    304kB / 351kB     212MB / 24.6kB    32
```
