### ISSUE TITLE
阿里云OSS，上传附件失败

### ISSUE THREAD

**Issue by NGLSL** [halo-dev/halo#181]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [ ] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [ ] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

配置好了阿里云OSS，但上传时是失败的。
![image](https://user-images.githubusercontent.com/40338580/58934037-cff2fe80-879b-11e9-91c1-7d3cd72ecec6.png)

**Comment by JohnNiang** [comment]
好的，我们排查一下。

> 谢谢反馈！

**Comment by ruibaby** [comment]
@NGLSL 能看看你的配置吗？（隐藏隐私信息）

**Comment by NGLSL** [comment]
> @NGLSL 能看看你的配置吗？（隐藏隐私信息）

![image](https://user-images.githubusercontent.com/40338580/58940492-29632980-87ac-11e9-9245-8a7c53b9993e.png)


这是我的配置

**Comment by ruibaby** [comment]
@NGLSL 1. Bucket不应该有后面的 EndPoint，应该为codedreamxxx
2. 缩略图处理策略应该为：?x-oss-process=style/stylename，stylename为规则名称。

**Comment by NGLSL** [comment]
> @NGLSL 1. Bucket不应该有后面的 EndPoint，应该为codedreamxxx
> 2. 缩略图处理策略应该为：?x-oss-process=style/stylename，stylename为规则名称。

你说的，不应该有后面的EndPoint指的是？
![image](https://user-images.githubusercontent.com/40338580/58941479-747e3c00-87ae-11e9-9e0f-0d15a40ab5aa.png)

**Comment by ruibaby** [comment]
@NGLSL 地域节点

**Comment by NGLSL** [comment]
> @NGLSL 地域节点

我填了Bucket，那就不应该填EndPoint?

**Comment by ruibaby** [comment]
@NGLSL 假设我的Bucket为blog-attachments，则：
![TIM截图20190605163239](https://user-images.githubusercontent.com/21301288/58942091-ae037700-87af-11e9-9f26-49f78291c725.png)

**Comment by NGLSL** [comment]
> @NGLSL 假设我的Bucket为blog-attachments，则：
> ![TIM截图20190605163239](https://user-images.githubusercontent.com/21301288/58942091-ae037700-87af-11e9-9f26-49f78291c725.png)

懂了，我再试试

**Comment by NGLSL** [comment]
> @NGLSL 假设我的Bucket为blog-attachments，则：
> ![TIM截图20190605163239](https://user-images.githubusercontent.com/21301288/58942091-ae037700-87af-11e9-9f26-49f78291c725.png)

可以上传了，但是展示好想有点问题.

![image](https://user-images.githubusercontent.com/40338580/58943467-5c102080-87b2-11e9-8439-b627e9ebe715.png)

**Comment by ruibaby** [comment]
@NGLSL 看一下浏览器控制台的报错信息

**Comment by NGLSL** [comment]
> @NGLSL 看一下浏览器控制台的报错信息

![image](https://user-images.githubusercontent.com/40338580/58943765-07b97080-87b3-11e9-967e-1b9030e25fc1.png)


看了公共读的权限，还需要配置说明地方？

**Comment by JohnNiang** [comment]
在附件详情那里复制一下图片的地址呢。

**Comment by NGLSL** [comment]
> 在附件详情那里复制一下图片的地址呢。

https://codedream-blog.oss-cn-beijing.aliyuncs.com/abstract-aerial-art-2307731_1559724646178.jpg

**Comment by ruibaby** [comment]
@NGLSL 都访问不了呀，你看看你oss的配置

**Comment by NGLSL** [comment]
> @NGLSL 都访问不了呀，你看看你oss的配置

可以了，我关闭了原图保护

**Comment by NGLSL** [comment]
> @NGLSL 都访问不了呀，你看看你oss的配置

能否，新增一个附件迁移功能？一键迁移到阿里云、七牛云等等

**Comment by ruibaby** [comment]
@NGLSL 可以列入计划。
