### ISSUE TITLE
页面打开非常慢

### ISSUE THREAD

**Issue by arcticfox1919** [halo-dev/halo#1829]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

1.4.13

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Fat Jar

### 发生了什么？

![](https://picturehost.oss-cn-shenzhen.aliyuncs.com/img/2022-04-09-001.png)

发现是 cdn.jsdelivr.net 这个地址经常访问不了，或者访问缓慢，请问有什么优化方案？

**Comment by ruibaby** [comment]
see https://github.com/halo-dev/halo/issues?q=is%3Aissue+jsdelivr+is%3Aclosed
