### ISSUE TITLE
使用nginx二级路由代理hola服务后，主题的js等静态资源无法访问到的bug

### ISSUE THREAD

**Issue by makexiao113** [halo-dev/halo#1830]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

1.5.2

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Fat Jar

### 在线站点地址

http://8.136.242.15/blog

### 发生了什么？

由于鄙人比较穷，在一台服务器上部署了多个服务，所以使用了nginx来做了代理，想使用一个端口多代理几个服务，所以加了个二级路由想将/blog路由在halo服务上，但是出现了主题无法正常加载的情况，查看控制台获取的主题js地址并不正确，丢失了二级路由，切换了多个主题都是如此，故判断是halo的bug获取站点地址不正确导致无法访问到js文件
![image](https://user-images.githubusercontent.com/63517007/162565096-bf1f4079-71ac-41f9-a731-93a4b06b56ba.png)

**Comment by ruibaby** [comment]
你好，目前不支持设置 context path 的形式访问。如果有此需求，可以追踪这个 issue https://github.com/halo-dev/halo/issues/702

**Comment by ruibaby** [comment]
个人还是建议使用二级域名。

**Comment by makexiao113** [comment]
> 个人还是建议使用二级域名。

谢谢，我去尝试一下

**Comment by ruibaby** [comment]
/retitle 使用 nginx 二级路由代理 halo 服务后，主题的 js 等静态资源无法访问到的 bug
