### ISSUE TITLE
 a Stored XSS  vulnerability via Markdown Editor

### ISSUE THREAD

**Issue by fuzzyap1** [halo-dev/halo#1831]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

posts edit

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Fat Jar

### 在线站点地址

https://demo.halo.run

### 发生了什么？

At the function point of posts edit,Markdown Editor don't effective security filtering of the markdown syntax entered by the user, resulting in an attacker being able to enter malicious javascript code ,which will cause a Stored XSS  vulnerability via Markdown Editor  .
put the payload:` <a href="javascript:alert(document.cookie)">Click Me</a>` to posts
![image-20220409175831104](https://user-images.githubusercontent.com/95869214/162580853-e6456e20-88bf-43c3-b478-dc511088f0ae.png)
open the posts and click 'Click me'  xss will be triggered,  you will get the user's token:
![image-20220409175921784](https://user-images.githubusercontent.com/95869214/162580882-1d16e9e8-ea20-4ce7-8666-1e677514e899.png)

**Comment by ruibaby** [comment]
Hi, thank you for your feedback. However, this is currently a single-admin system, and we do not consider this to be a security issue for now.

**Comment by JohnNiang** [comment]
如果没有更多的反馈，我们将关闭这个 issue。
