### ISSUE TITLE
希望对前端编译生成静态gzip资源

### ISSUE THREAD

**Issue by 2211898719** [halo-dev/halo#1833]
### 你当前使用的版本

1.5.1

### 描述一下此特性

直接在编译时生成静态gz文件不用动态压缩
只需要在build节点下配置
productionGzip: true,

**Comment by ruibaby** [comment]
/area admin
/kind feature

好建议，你愿意贡献此特性吗？

**Comment by 2211898719** [comment]
> /area admin /kind feature
> 
> 好建议，你愿意贡献此特性吗？
> 
> https://github.com/halo-dev/halo-admin

可以的
