### ISSUE TITLE
支持 Hexo、Hugo 的主题

### ISSUE THREAD

**Issue by yuanzhixiang** [halo-dev/halo#1835]
### 你当前使用的版本

1.5.1

### 描述一下此特性

Halo 主题比较少，如果能支持将文章使用 Hexo 这类静态博客生成工具的主题进行渲染，那么 Halo 的主题库能得到很大的扩展

**Comment by ruibaby** [comment]
对于主题少的问题，我们大概会在 2.0 考虑更换对开发更加友好的 Thymeleaf，同时重构主题的 API，在最大程度上提供更加友好的开发体验。届时我们也会着力于主题生态。

**Comment by ruibaby** [comment]
我将关闭此 issue，可以跟踪这个 issue：https://github.com/halo-dev/halo/issues/1291

/close
