### ISSUE TITLE
分类目录中设置分类列表并保存设置，整个博客的文章都变成草稿状态

### ISSUE THREAD

**Issue by Blusand** [halo-dev/halo#1839]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

1.5.2

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

在文章->分类目录中设置分类列表并保存设置，这会导致整个博客的文章都变成草稿状态，需要全部手动发布

**Comment by ruibaby** [comment]
你好，确定是使用的 1.5.2 吗？

**Comment by Blusand** [comment]
> 你好，确定是使用的 1.5.2 吗？

抱歉，我的，这是1.5.0版本的问题，刚刚升级了1.5.2已经解决了
