### ISSUE TITLE
文章搜索时关联内容进行搜索

### ISSUE THREAD

**Issue by guqing** [halo-dev/halo#1842]
### Checklist

- [X] The issue has been searched in [GitHub Issues](https://github.com/halo-dev/halo/issues)
- [X] The issue has been searched in the [bbs.halo.run](https://bbs.halo.run/)
- [X] Already consulted [document](https://docs.halo.run/)

### What is version of Halo has the issue?

1.5.2

### What database are you using?

H2

### What is your deployment method?

Docker

### What happened?

拆分了内容表后，文章搜索没有同步修改内容搜索字段，导致根据关键字搜索文章内容失效
需要修改如下代码关联到 contents 表查询内容
https://github.com/halo-dev/halo/blob/63e8cd0cd53b92c3571981bcb81454f23b8ae34a/src/main/java/run/halo/app/service/impl/PostServiceImpl.java#L574

**Comment by ruibaby** [comment]
可以参考根据 category 去关联查询的方式去关联 contents 表进行查询。

https://github.com/halo-dev/halo/blob/63e8cd0cd53b92c3571981bcb81454f23b8ae34a/src/main/java/run/halo/app/service/impl/PostServiceImpl.java#L559-L572

**Comment by Yhcrown** [comment]
由于课程原因需要积极参与到开源项目的贡献中，这个issue提到的问题的相关的修复我大概有了思路。今天稍晚的时候我会提个pr。
