### ISSUE TITLE
markdown批注功能

### ISSUE THREAD

**Issue by HWalkingMan** [halo-dev/halo#1847]
### 你当前使用的版本

1.5.1

### 描述一下此特性

希望可以实现一个基于markdown的批注功能，便于对文章中的内容进行批注解释。
具体效果，类似于
![image](https://user-images.githubusercontent.com/47980785/163606126-93cf09ad-945d-475b-97d2-19d49a42241e.png)

@ [here](https://lernapparat.de/selective-excursion-into-pytorch-internals/ ) 
sidenote

**Comment by ruibaby** [comment]
你好 @HWalkingMan，可以脚注是否能满足要求。

https://docs.halo.run/user-guide/markdown#脚注footnote

**Comment by ruibaby** [comment]
如果没有后续反馈，我们将关闭此 issue，有补充内容可以 reopen。

/close
