### ISSUE TITLE
附件设置中部分表单没有去除域名的前后空格

### ISSUE THREAD

**Issue by wangxiaoerYah** [halo-dev/halo#1850]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

1.5.2

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Fat Jar

### 在线站点地址

https://www.wangxiaoer.site

### 发生了什么？

附件设置 -> 绑定域名

如果这里不小心多填了个空格，halo不会自动除去空格
将会导致无法访问附件

复现步骤:
附件设置 - 又拍云(只用了又拍云) -> 绑定域名
末尾添加一个空格
然后上传附件
然后随便新建文章，把附件添加进去。会发现没有图片，然后会在markdown链接里面发现halo自动给添加了'%20'应该是url转码，把它删除可以正常访问。

但是在附件里面
你通过这个设置上传的所有文件，都会在属性里面看到链接域名后面有'%20'

ps:话说既然上传过得文件，改了附件储存位置，任然可以访问，那为什么不支持上传的时候选择使用那个云储存呢？同时设置多个云储存。🌝

**Comment by ruibaby** [comment]
/kind bug
/good-first-issue

> ps:话说既然上传过得文件，改了附件储存位置，任然可以访问，那为什么不支持上传的时候选择使用那个云储存呢？同时设置多个云储存。🌝

我们会在 2.0 考虑支持通过云存储或者本地存储创建存储策略。目前 1.5 不打算添加新特性。

**Comment by ruibaby** [comment]
/area admin

@halo-dev/sig-halo 是否需要在后端 trim 一下？

**Comment by JohnNiang** [comment]
个人认为这不算是一个问题，而是需要改进的地方。当然，如果能够在后端处理一下这些数据会更好。

**Comment by FanZeros** [comment]
> 个人认为这不算是一个问题，而是需要改进的地方。当然，如果能够在后端处理一下这些数据会更好。

请问这部分（除了前端之外）还需要后端再处理一下么
