### ISSUE TITLE
关于 文章固定链接类型为 "ID" 模式时的疑惑 

### ISSUE THREAD

**Issue by 1379** [halo-dev/halo#1851]
### Describe this feature

![image](https://user-images.githubusercontent.com/34785043/163670150-a2ea81ed-8208-469a-a26e-c7fc94579e2a.png)
比如选择了ID
那么文章的固定链接就编成了 http://example.com/?p=1
因此我有个疑惑，为什么要把文章id作为query的参数，而不是作为路径呢。比如 http://example.com/posts/1

**Comment by ruibaby** [comment]
<img width="825" alt="image" src="https://user-images.githubusercontent.com/21301288/163670516-b5ba3e26-1d4a-498a-8451-aa8f40950537.png">

这样设置即可。

/help

**Comment by 1379** [comment]
@ruibaby 
这样设置似乎没有作用。我在首页点进去的文章，url依然是http://example.com/?p=1

**Comment by ruibaby** [comment]
@1379 我这边似乎无法复现，是否和某种缓存有关？

<img width="488" alt="image" src="https://user-images.githubusercontent.com/21301288/163676619-f41d65fa-b059-44b1-83b9-37fe0b13b3ec.png">

**Comment by 1379** [comment]
我找到问题了。我选择的是“ID”，你选择的是“ID别名型” 。“ID别名型” 理解起来有些困难，什么是ID的别名呢，是不是和文章的别名有些冲突了

**Comment by ruibaby** [comment]
> 什么是ID的别名呢，是不是和文章的别名有些冲突了

意思就是把 id 当做 slug（别名字段） 用。
