### ISSUE TITLE
404 请求被重定向至 /404

### ISSUE THREAD

**Issue by GalvinGao** [halo-dev/halo#186]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

----

Expected：根据 HTTP 规范，404 请求应直接返回 `404` 状态码，同时返回 HTML Body。
现情况：所有 404 请求将会被返回 `302` 状态码并被重定向至 `/404`
解决方案：所有 404 请求应直接返回 `404` 状态码，直接渲染并返回主题目录下的 `/404.ftl`

PS: 500 请求的情况也是一样

**Comment by JohnNiang** [comment]
谢谢您的反馈！

我们将尝试按照您所说的方案进行修改。

**Comment by JohnNiang** [comment]
已经修复此 bug，将于 `v1.0.2` 见面 ：P
