### ISSUE TITLE
关于多级分类的展示问题

### ISSUE THREAD

**Issue by HJHY** [halo-dev/halo#1875]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

1.5.2 1.5.1

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Fat Jar

### 发生了什么？

请问一下分类问题目前已经解决了吗，1.5.2版本好像还是存在无法多级分类的问题？
![Snipaste_2022-04-22_01-09-08](https://user-images.githubusercontent.com/62489863/164514466-c1866ffa-eed8-4980-a802-fe1f42bbff77.png)
![Snipaste_2022-04-22_01-09-29](https://user-images.githubusercontent.com/62489863/164514485-72fb660d-46d2-4ec2-a1b5-5ef7d44924bf.png)

**Comment by ruibaby** [comment]
前台以多级展示分类需要主题适配，你可以向对应的主题提交 issue。

**Comment by HJHY** [comment]
了解，谢谢
