### ISSUE TITLE
搜索文章标题大小写敏感，希望能做到大小写不敏感查询

### ISSUE THREAD

**Issue by CodeSheepX** [halo-dev/halo#1879]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

1.5.1

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker

### 在线站点地址

https://blog.xugenwen.cn/

### 发生了什么？

全站搜索时，希望关键字大小写不敏感

**Comment by ruibaby** [comment]
/triage duplicate

https://github.com/halo-dev/halo/issues/1545
