### ISSUE TITLE
增强static静态储存的便捷性

### ISSUE THREAD

**Issue by muyunil** [halo-dev/halo#1880]
### Your current Halo version

v1.5.2

### Describe this feature

通过后台上传的文件可以访问，服务端本地在static目录创建的文件目录可以识别到但无法访问因为没有对其创建映射。
希望后续版本可以优化，监听static目录中的目录文件自动创建映射或者提供手动的创建开关让其可以正常访问。

**Comment by Yhcrown** [comment]
正好想学习一下，这个static下的文件为什么没有和upload下的文件一样直接全部创建映射，而是要用事件监听的方式创建。者是出于什么一种考虑。

**Comment by Yhcrown** [comment]
目前想到有三种解决方案。一种是可以在刷新页面的时候加一个onChange事件通知更新映射，每次点过刷新之后就可以正常访问服务端本地上传的文件。一种就是暴力的把static下的目录全部映射（可以加个开关）。还有就是写一个文件监听器去检测变化，就是可能有点浪费资源。

**Comment by ruibaby** [comment]
> 一种是可以在刷新页面的时候加一个onChange事件通知更新映射，每次点过刷新之后就可以正常访问服务端本地上传的文件

我觉得这种方式目前可能更好。
