### ISSUE TITLE
上传HEIC格式的图片不能被渲染，能否增加一个自动转为可渲染格式图片的功能？

### ISSUE THREAD

**Issue by hustnzj** [halo-dev/halo#1884]
### 你当前使用的版本

1.5.1

### 描述一下此特性

上传HEIC格式的图片不能被渲染。希望能增加一个可自动转换图片格式的功能。

### 附加信息

<img width="1306" alt="image" src="https://user-images.githubusercontent.com/27875723/164891552-661acfcd-215b-4b30-b534-69276d979fb8.png">

**Comment by ruibaby** [comment]
这种情况还是更建议在本地处理。

**Comment by hustnzj** [comment]
好的。
