### ISSUE TITLE
百度云(BOS)链接处理问题

### ISSUE THREAD

**Issue by KenRouKoro** [halo-dev/halo#1885]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

1.5.2

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Fat Jar

### 在线站点地址

https://korostudio.cn

### 发生了什么？

部署方式：docker/腾讯云Cloudbase/jar包
版本：1.5.2
错误内容：在更新到1.5.2后，上传附件后百度云连接的处理出现问题，具体表现为，https://file.korostudio.cn/https://koroblog.gz.bcebos.com/blhx-background_and_shouhou.png

以下是我的百度云配置
绑定域名：
file.korostudio.cn
Bucket：
koroblog
EndPoint（地域节点）：
gz.bcebos.com

这个问题在三种部署方式都存在，附加信息里有上传后的截图。

### 附加信息

![image](https://user-images.githubusercontent.com/21196863/164916904-55f32435-03a4-43c8-973e-5f9af20abce0.png)
![image](https://user-images.githubusercontent.com/21196863/164916911-46f98785-0011-4b16-bf5e-fa89f1339a46.png)

**Comment by ruibaby** [comment]
/triage duplicate

https://github.com/halo-dev/halo/issues/1886
