### ISSUE TITLE
完善 CONTRIBUTION.md 

### ISSUE THREAD

**Issue by JohnNiang** [halo-dev/halo#1888]
### 你当前使用的版本

latest

### 描述一下此特性

最近我们收到一些非常棒的 PR，例如：

- https://github.com/halo-dev/halo/pull/1865
- https://github.com/halo-dev/halo/pull/1874
- https://github.com/halo-dev/halo/pull/1882
- https://github.com/halo-dev/halo/pull/1883
- https://github.com/halo-dev/halo/pull/1887

部分作者可能第一次参与开源，缺乏一些经验。与此同时，我们的 [CONTRIBUTION.md](https://github.com/halo-dev/halo/blob/1f75ba09f8c1f3ad6b3514299508bcd8ab1270d6/CONTRIBUTING.md) 也相对比较简陋。

因此，我们非常有必要丰富 CONTRIBUTION.md 文档来帮助 PR 作者更好地参与开源。

**Comment by ruibaby** [comment]
需要同步修改一下 https://github.com/halo-dev/docs
