### ISSUE TITLE
文章 markdown 语法分割线显示问题

### ISSUE THREAD

**Issue by llwmeme** [halo-dev/halo#1894]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

1.5.2

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker

### 在线站点地址

https://blog.liulewei.site/archives/java%E5%A4%9A%E7%BA%BF%E7%A8%8B%E7%BC%96%E7%A8%8B%E4%B8%89%E5%A4%A7%E7%89%B9%E6%80%A7

### 发生了什么？

markdown 分割线语法(-------/***********)渲染问题
这个是编辑时预览的样式
![image](https://user-images.githubusercontent.com/26084140/165221597-1a3da9cd-f8b8-4c7b-a0b9-4da07f66091a.png)
这个是实际的样式
![image](https://user-images.githubusercontent.com/26084140/165221654-bf439106-9abd-454b-ae05-ab492a34c13b.png)
请问下这个样式能否改成一条直线而非三个-

**Comment by ruibaby** [comment]
这是主题的表现，请向对应主题的仓库提交 issue。

/support

**Comment by llwmeme** [comment]
好的多谢！
