### ISSUE TITLE
能否在文章中添加自定义代码块

### ISSUE THREAD

**Issue by llwmeme** [halo-dev/halo#1896]
### 你当前使用的版本

1.5.2

### 描述一下此特性

目前的 文章编写是基于markdown的，
markdown 其实是支持html 嵌入的，某些html 书写起来可能有些复杂，后期版本 可否计划提供配置指令的功能（这个叫宏？）,
例如
```html
 <div color = '' style=''></div>
```
，通过后台的配置

**Comment by WenyinWei** [comment]
我想借助 [loud-links](https://github.com/MahdiF/loud-links) 这一插件实现鼠标滑过喇叭图标的时候发出声音，但我没能在 halo 里用得上 loud-links。我暂时的权宜之计直接把声音 MP3 当做超链接插入，但没办法实现鼠标 hover 就发出声音。例子见下

<ruby>声<rt>sh&emacr;ng</rt></ruby>[:loud_sound:](https://i1.hao86.com/mp3/sheng1.mp3) <ruby>音<rt>y&imacr;n</rt></ruby>[:loud_sound:](https://i1.hao86.com/mp3/yin1.mp3)
```html
<ruby>声<rt>sh&emacr;ng</rt></ruby>[:loud_sound:](https://i1.hao86.com/mp3/sheng1.mp3) <ruby>音<rt>y&imacr;n</rt></ruby>[:loud_sound:](https://i1.hao86.com/mp3/yin1.mp3)
```

**Comment by ruibaby** [comment]
当前 issue 已经过时，目前 Halo 2 的编辑器支持通过插件扩展功能，且提供了[嵌入 HTML 的插件](https://www.halo.run/store/apps/app-NgHnY)。

/close
