### ISSUE TITLE
halo可访问性"疑问"

### ISSUE THREAD

**Issue by littlesleep** [halo-dev/halo#1898]
### 你当前使用的版本

1.5.2

### 描述一下此特性

你好:
今天下午在本地进行halo开发测试的时候发现以下疑问(第一次使用)，我不知道这个问题是属于哪个体系
故此在新特性提出“疑问”：

已有配置功能：
halo:
  admin-path:  xxxxx
这一个配置只是进行个性化定制吗？还是说暴露不暴露无所谓？

如果是： 我会进行issue 关闭。
如果不是：请看下面 ↓

* Controller 部分(不限于)接口可访问性"疑问":
例如：MainController 中的 install 、version 、······
         AdminController : {yousite}/api/admin/is_installed ······等等

是否可以进行登陆用户判断操作呢？
目前我本地用的生产环境配置，version为unkonown
https://bbs.halo.run/d/2078/2  论坛友链分享用户基本全可见后台登陆

### 附加信息

![image](https://user-images.githubusercontent.com/8597130/165479005-e647e042-6321-49d7-a8af-4473ac28bc53.png)

![image](https://user-images.githubusercontent.com/8597130/165479671-ae186a6a-73da-4cbc-b05a-800051c39008.png)

![image](https://user-images.githubusercontent.com/8597130/165479779-258a1e91-9262-4dcb-a81c-5b5952e318f8.png)

![image](https://user-images.githubusercontent.com/8597130/165479903-06cc1ba5-04d2-44cc-a080-fd2dc0527a9a.png)

![image](https://user-images.githubusercontent.com/8597130/165480350-3b56bd22-1321-4c64-8ded-d53947830981.png)

**Comment by ruibaby** [comment]
你好 @littlesleep ，我没有很明白你说的意思。我猜测的回答一下。

1. 你所说的 /version /api/admin/is_installed 都在白名单内，无需鉴权。
2. `admin-path` 只是后台登录入口自定义，与接口的 /api/admin 无关。 
3. `https://bbs.halo.run/d/2078/2 论坛友链分享用户基本全可见后台登陆`，只是他们没有改 `admin-path` 而已。

/kind support

**Comment by littlesleep** [comment]
谢谢回答。

admin path改了也是可以通过访问install到后台登录页面的不管是你换了什么。version接口也直接暴露了你使用的版本。有点不安全。如果有漏洞，扫描机可以直接访问域名＋install接口和version 查看是不是对应版本漏洞，精准注入。

**Comment by ruibaby** [comment]
@littlesleep 确实可以复现这个问题，感谢反馈。 不知道你是否愿意修改这个问题。可以在 /install 路由判断是否已经初始化，如果已经初始化，可以不做任何处理。

https://github.com/halo-dev/halo/blob/master/src/main/java/run/halo/app/controller/content/MainController.java#L66-L69

/remove-kind support
/kind bug
/good-first-issue

**Comment by ruibaby** [comment]
再补充一点，这个 admin-path 可以修改本身就是意义不大的，因为我们的 API 都是公开的，攻击者无需通过这个入口。我们只需要保证 API 的安全性。至于 /version 暴露版本信息，目前我们没有发现因为版本信息被攻击的案例。而且 1.x 版本不考虑对此作修改。

**Comment by littlesleep** [comment]
> @littlesleep 确实可以复现这个问题，感谢反馈。 不知道你是否愿意修改这个问题。可以在 /install 路由判断是否已经初始化，如果已经初始化，可以不做任何处理。
> 
> https://github.com/halo-dev/halo/blob/master/src/main/java/run/halo/app/controller/content/MainController.java#L66-L69
> 
> /remove-kind support /kind bug /good-first-issue

谢谢邀请。我是一个JAVA开发者。你也看到了，对于halo整体还不熟悉(技术架构,编码规范等),或许还有更优的解决方案。
我会持续关注halo的情况，熟悉后有好的建议，想法会按照halo的规定进行。

以下链接是否可以作为规定参考：
https://docs.halo.run/contribution/issues
https://docs.halo.run/contribution/pr

**Comment by guqing** [comment]
> > > @littlesleep 确实可以复现这个问题，感谢反馈。 不知道你是否愿意修改这个问题。可以在 /install 路由判断是否已经初始化，如果已经初始化，可以不做任何处理。
> > > https://github.com/halo-dev/halo/blob/master/src/main/java/run/halo/app/controller/content/MainController.java#L66-L69
> > > /remove-kind support /kind bug /good-first-issue
> > 
> > 谢谢邀请。我是一个JAVA开发者。你也看到了，对于halo整体还不熟悉(技术架构,编码规范等),或许还有更优的解决方案。 我会持续关注halo的情况，熟悉后有好的建议，想法会按照halo的规定进行。
> > 
> > 以下链接是否可以作为规定参考： https://docs.halo.run/contribution/issues https://docs.halo.run/contribution/pr
> 
> 您好，我由于课程的原因，需要为开源社区贡献代码，所以我在本地尝试修复，并且经测试符合预期，我看您暂时没有修复这个bug，您介意不介意把这个修复的机会让给我？

可以的 先在此 Issue 描述你的解决思路 讨论过后在开始编码 
/assign @Ljfanny

**Comment by Ljfanny** [comment]
> > > > @littlesleep 确实可以复现这个问题，感谢反馈。 不知道你是否愿意修改这个问题。可以在 /install 路由判断是否已经初始化，如果已经初始化，可以不做任何处理。
> > > > https://github.com/halo-dev/halo/blob/master/src/main/java/run/halo/app/controller/content/MainController.java#L66-L69
> > > > /remove-kind support /kind bug /good-first-issue
> > > 
> > > 
> > > 谢谢邀请。我是一个JAVA开发者。你也看到了，对于halo整体还不熟悉(技术架构,编码规范等),或许还有更优的解决方案。 我会持续关注halo的情况，熟悉后有好的建议，想法会按照halo的规定进行。
> > > 以下链接是否可以作为规定参考： https://docs.halo.run/contribution/issues https://docs.halo.run/contribution/pr
> > 
> > 
> > 您好，我由于课程的原因，需要为开源社区贡献代码，所以我在本地尝试修复，并且经测试符合预期，我看您暂时没有修复这个bug，您介意不介意把这个修复的机会让给我？
> 
> 可以的 先在此 Issue 描述你的解决思路 讨论过后在开始编码 /assign @Ljfanny

您好，我更改的代码部分如下：
![image](https://user-images.githubusercontent.com/84827635/166108153-2dcfacd7-5093-4646-b594-b7e6f8dcb5e9.png)
您看是否有其他的考虑？

**Comment by ruibaby** [comment]
我不确定一个 mapping 不做响应是否会带来其他问题。

/cc @halo-dev/sig-halo

**Comment by ruibaby** [comment]
@Ljfanny 可以先直接提交 PR。
