### ISSUE TITLE
相册页面选择上传后的图片, 略缩图会进行二次编码/转义

### ISSUE THREAD

**Issue by qaiu** [halo-dev/halo#1899]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

1.5.2

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Fat Jar

### 在线站点地址

https://blog.qaiu.top

### 发生了什么？

![image](https://user-images.githubusercontent.com/29825328/165625264-c336f59f-3dac-4210-91d5-03ae6f7ab0c7.png)
如图所示
1. 如果上传的图片含有中文上传后会自动URLencode转义这一步没问题
2. 然而如果在相册页面选择这张图片会对已经转义的URL进行二次编码导致图片无法正常加载
3. 对于前台展示没有任何影响, 只是后台在相册页面看不到上传的图片

**Comment by qaiu** [comment]
图片实际地址是: https://blog.qaiu.top/upload/2022/04/%E8%90%8C%E5%A8%9803.jpg
缩略图实际指向的地址: https://blog.qaiu.top/upload/2022/04/%E8%90%8C%E5%A8%9803-thumbnail.jpg
列表里缩略图指向的地址: https://blog.qaiu.top/upload/2022/04/%25E8%2590%258C%25E5%25A8%259803-thumbnail.jpg

**Comment by JohnNiang** [comment]
Hi @FanZeros，请问有意愿修复这个问题么？

**Comment by FanZeros** [comment]
> Hi @FanZeros，请问有意愿修复这个问题么？

好
