### ISSUE TITLE
[建议] 为所有 post 项增加额外的 metadata

### ISSUE THREAD

**Issue by GalvinGao** [halo-dev/halo#190]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [x] 添加新的特性或者功能
- [ ] 请求技术支持

----

RT；可以为文章或页面添加其他`metadata`；使用场景如：

- 为各个文章添加预计阅读所需时间 `readingTime`，然后可以在模板中使用
- 为文章添加 `authorizedMedias`，代表当前内容已授权给的主体，可在模板内渲染出来做成一个modal
- [...]

若可添加`metadata`则理论上的应用是无限的（但也不能过于超出‘个人博客’的范畴 - 参考WordPress，其已被更多地认可为CRM的体现，导致妥协兼容性的情况下很多地方的统一性出现了问题；个人认为`metadata` + 可自行修改的模板 这样的设计，可以适当地平衡两者 - 即，在不超出项目定义范畴内，高度可自行定制）

**Comment by ruibaby** [comment]
已有该计划，参考https://github.com/halo-dev/halo/issues/95。

**Comment by GalvinGao** [comment]
没有看到；抱歉啦~
Close: duplicated

**Comment by ruibaby** [comment]
@GalvinGao 还是非常感谢你的建议。
