### ISSUE TITLE
希望可以对友链”分组“进行排序

### ISSUE THREAD

**Issue by daifiyum** [halo-dev/halo#1905]
### Your current Halo version

1.5.2

### Describe this feature

目前，链接（友链）的分组还无法排序，有多个分组时，无法将重要分组放在满意的位置

**Comment by ruibaby** [comment]
感谢反馈，目前由于分组字段是存在友链的表当中的，所以要对分组排序也就意味着对分组下的所有友链进行排序。所以目前问题就变成了对所有友链的排序。

对此提供一种方案：

对于后端：

1. 提供批量更新友链的接口。在 [LinkController](https://github.com/halo-dev/halo/blob/master/src/main/java/run/halo/app/controller/admin/api/LinkController.java) 当中提供类似 [MenuController#updateBatchBy](https://github.com/halo-dev/halo/blob/master/src/main/java/run/halo/app/controller/admin/api/MenuController.java#L104) 的接口。
2. 获取分组友链的接口可能需要改为同时根据 priority 和 team 字段进行排序。

对于前端：

1. 重构整个管理友链的功能，目前表格的形式无法方便的完成排序。
2. 需要改为以分组的形式展示。
3. 可以参考菜单和文章分类的排序实现，但得支持整个分组的排序。
4. 排序完成后使用批量更新接口进行所有友链的更新。

最终所呈现的效果可能是这样：

<img width="1533" alt="image" src="https://user-images.githubusercontent.com/21301288/165772857-341a475c-ece5-4772-b56f-18e526fa6171.png">

由于目前我们正在进行 2.0 版本的开发，所以可能并没有时间来增加 1.x 的功能，期待大家来实现这个特性。

/kind feature

**Comment by jiazhiyuans** [comment]
ok

**Comment by ruibaby** [comment]
> ok
> 
> 

如果有兴趣，可以评论 `/assign` 来指派。

**Comment by Camsyn** [comment]
在不修改数据库表的前提下对分组进行排序，我认为分组排序和组内友链的排序可以共用一个priority字段（team字段不做排序）。即将分组内最大的友链priority作为该分组的priority。

- 后端：`List<LinkTeamVO> listTeamVos(Sort sort) ` api 可以先默认按分组的priority对分组进行排序，再对组内的友链进行排序。
- 前端：修改 管理友链的页面，不再显式的提供修改友链priority的方法，而是采用可视化的拖拽来对分组或分组内的友链进行排序，并在前端按照最终的次序(从上到下，从左到右)对各个友链的priority进行递增/递减，配合后端提供的批量更新接口，完成对分组排序，组内友链排序的可视化调整。
