### ISSUE TITLE
halo后台编辑文章区域出现两个

### ISSUE THREAD

**Issue by zyy247796143** [halo-dev/halo#1906]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

1.5.2

### 使用的什么数据库？

MySQL 5.7

### 使用的哪种方式部署？

Docker

### 发生了什么？

在管理后台编辑文章的时候，文章编辑区有时候会出现两个。鼠标滚轮上下滚动几次就没了，有时候又突然出现。截图如下：

### 附加信息

![image](https://user-images.githubusercontent.com/23225911/165877091-9f0839fb-2598-4c4d-bdac-b2da2d673de7.png)

**Comment by ruibaby** [comment]
感谢反馈，能提供一个复现步骤吗？

**Comment by zyy247796143** [comment]
编辑一篇之前保存过的 草稿 文章，打开 单栏 编辑模式，然后上下滚鼠标轮就出现了。刚刚又试了两篇 草稿 文章都会这样。

**Comment by ruibaby** [comment]
@zyy247796143 可以复现，应该是切换的时候又实例化了一次编辑器。

/kind bug
/milestone 1.5.x
