### ISSUE TITLE
批量导入markdown文件时，有同分类的文章会报错导入不成功

### ISSUE THREAD

**Issue by wuzhi1234** [halo-dev/halo#191]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

批量导入markdown文件的时候，如果有文章处于同一类，会有部分导入失败。
查看代码发现是在查询分类的时候
```java
Category category = categoryService.getByName(ele);
```
如果数据库中有多个同名的分类，则会报错。
按理说如果正常调用批量插入是不会有同名分类的，所以怀疑前端是不是并行调用这个接口导致的。总之数据库中确实有重名的分类。

**Comment by JohnNiang** [comment]
好的，我们将尽快排查。


> 谢谢您的反馈！

**Comment by JohnNiang** [comment]
经排查发现，原因确实是您所描述的`并行调用`。

我们将尽快解决这个问题。

**Comment by JohnNiang** [comment]
但是问题应该出在 `halo-admin` 调用上。

**Comment by wuzhi1234** [comment]
可以考虑在接口上做个并发控制，再在数据库里建些唯一索引防止脏数据

**Comment by JohnNiang** [comment]
> 可以考虑在接口上做个并发控制，再在数据库里建些唯一索引防止脏数据

这里确实应该考虑用一个`消息队列`进行处理。

为了减少外部依赖，只能自己写一个简单的`队列处理器`了。

**Comment by ruibaby** [comment]
已解决
