### ISSUE TITLE
数据库远程连接

### ISSUE THREAD

**Issue by wangxiaoerYah** [halo-dev/halo#1910]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

1.5.2

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Fat Jar

### 在线站点地址

https://www.wangxiaoer.site

### 发生了什么？

数据库访问频繁出现' No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value. '

描述:

我的数据库是基于mariadb搭建的galera多主集群，通过MaxScale的read write split 实现的读写分离，端口4006。

经过测试发现我的数据库是没有问题的包括网上搜索maxLifetime，查到要修改wait_timeout。

在访问后台admin页面可以比较快的加载出来页面。
但是现在访问我的首页时就会很卡很慢。

文章只有一个helloworld，但是加载很慢。

现在我的日志输出和 #910 的一致。

我同样的数据库上还有cloudreve和Bitwarden，数据库都没有出现问题。
所以排除数据库本身就是Halo自身的Hikari问题了。

期间有试过haproxy，也是同样的问题。
但是如果使用本地连接到mariadb，就没有问题。

嗯，因为我多台服务器需要同步数据库，所以必须要通过MaxScale或者haproxy实现高可用，不然本地数据库在galera同步的时候，会出现1047 wsrep has not yet，故不能使用本地直连数据库。

希望可以适配下。
🥺真的很喜欢Halo

**Comment by JohnNiang** [comment]
Hi @wangxiaoerYah ，感谢反馈这个详细的问题。由于我们现在不是很方便去测试数据库集群的情况，所以我这里给出一个可能的办法，希望能够帮忙多试试，一起寻找解决方案：

首先，你使用的是 MySQL 8.0，每 8hours 就会断掉数据库连接，但是 Halo 的 Hikari 连接池并不知道数据库连接已经断掉了，那么再次使用该数据库连接的地方就会报错：` No operations allowed after connection closed`。可以根据提示 `Possibly consider using a shorter maxLifetime value` 更改一下 `maxLieftime`：

```yaml
spring:
  datasource:
    hikari:
      max-lifetime: 1800000ms
```

参考：

- https://dev.mysql.com/doc/refman/8.0/en/gone-away.html
- https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.data.spring.datasource.hikari
- https://cloud.tencent.com/developer/article/1707872

**Comment by wangxiaoerYah** [comment]
> Hi @wangxiaoerYah ，感谢反馈这个详细的问题。由于我们现在不是很方便去测试数据库集群的情况，所以我这里给出一个可能的办法，希望能够帮忙多试试，一起寻找解决方案：
> 
> 首先，你使用的是 MySQL 8.0，每 8hours 就会断掉数据库连接，但是 Halo 的 Hikari 连接池并不知道数据库连接已经断掉了，那么再次使用该数据库连接的地方就会报错：` No operations allowed after connection closed`。可以根据提示 `Possibly consider using a shorter maxLifetime value` 更改一下 `maxLieftime`：
> 
> ```yaml
> spring:
>   datasource:
>     hikari:
>       max-lifetime: 1800000ms
> ```
> 
> 参考：
> 
> - https://dev.mysql.com/doc/refman/8.0/en/gone-away.html
> - https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.data.spring.datasource.hikari
> - https://cloud.tencent.com/developer/article/1707872

测试了一下，我把maxlifetime设置成300000ms即5分钟 和 idle-timeout: 300000
现在没有出现maxlifetime报错了，但是访问任然会慢。

我刚刚翻到mxscale 路由模块文档，发现是readwritesplit 不支持jdbc的批量查询，因为他要跟踪每条读取写入的返回值。
[readwritesplit](https://mariadb.com/kb/en/mariadb-maxscale-25-readwritesplit/#optimistic_trx)

有没有可能将查询改成一条多次查询?这样与批量查询有什么速度差距没?

然后就是和 #910 这个问题里出现的，使用远程数据库卡顿问题是不是也是批量查询，然后关联条数太多，数据库端tcp缓存不足，造成的?

**Comment by JohnNiang** [comment]
我们测试发现，如果数据库和 Halo 所在的服务器网络延迟过高，确实会造成较大的延迟（比如：数据库在 HK，Halo 所在服务器处于北京，则访问首页的延迟高达 1s+）。目前我能想到两种方案：

1. 在 Halo 侧添加数据缓存
2. 并发执行没有关联的查询

我更倾向第一种方式，相对第二种方式更简单，无需大量修改已有的代码。
