### ISSUE TITLE
后台部分表单中如果是 URL 类型的输入框，需要做 trim 处理

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#1921]
### 你当前使用的版本

1.5.2

### 描述一下此特性

后台部分表单中，如果有 URL 类型的输入框，需要去掉字符串前后空格。

如：

- 系统设置中博客地址、Logo、Favicon
- 附件设置的 entrypoint、自定义域名。
- SMTP 设置中的 SMTP 地址。

see https://github.com/halo-dev/halo/issues/1850

/kind feature
/cc @halo-dev/sig-halo-admin 
/milestone 1.5.x

**Comment by JohnNiang** [comment]
Hi @FanZeros ，这个 issue 已经被 https://github.com/halo-dev/halo/issues/1921#issuecomment-1119242674 认领了，可能 @Have-an-flower 已经在做这个事情了。为了避免重复做同一件事情，建议不要重复认领，谢谢！

**Comment by FanZeros** [comment]
好的，/unassign

**Comment by Have-an-flower** [comment]
您好  由于自身水平有限（基础不牢）  暂时搞不出来  抱歉
