### ISSUE TITLE
图片提供了预览图，音频视频能不能提供播放功能？

### ISSUE THREAD

**Issue by laijinyou** [halo-dev/halo#1923]
### Your current Halo version

1.5.1

### Describe this feature

我的网站上传了大量音频和视频，它们的命名都是无规则的。因为我无法播放试听试看，我不能在网页上知道它是什么内容，我只能在电脑本地一个个试听试播。
<img width="2238" alt="image" src="https://user-images.githubusercontent.com/53654005/161374824-79ecc3f9-3452-4e75-9510-75721bd1c678.png">

**Comment by ruibaby** [comment]
将在 2.3.0 通过原生 audio 和 video 标签实现音视频的预览。
