### ISSUE TITLE
后台文章预览链接跳转问题

### ISSUE THREAD

**Issue by bynowi** [halo-dev/halo#1927]
### 你当前使用的版本

1.4.17

### 描述一下此特性

当后台管理页面独立部署，和站点使用两个不相同的三级域名时，文章访问、独立页面访问链接会是后台的的域名，建议使用blog_url这个前缀
![t1](https://user-images.githubusercontent.com/20673319/153329871-bfb23862-82c3-4b25-9c5c-9e0f6e3b07ff.png)

**Comment by ruibaby** [comment]
目前 2.0 不考虑支持独立部署 Console，1.x 目前也不打算再进行功能增加或者修改，所以这个 issue 就先关闭了。
