### ISSUE TITLE
建议把附件管理细化一些--文件分类

### ISSUE THREAD

**Issue by zsinba** [halo-dev/halo#1930]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 文档](https://docs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo-admin/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [x] 添加新的特性或者功能
- [ ] 请求技术支持

目前后台的附件管理，内容秒多时，无法进行管理了。 因为多而乱。
建议：
1。设置里增加上传附件是类型，如果设置png,jpg,bmp等类型， 也可上传zip，word，mp4等设置
2。在附件管理里， 根据文件类型、上传日期等类型进行分类一下，这样方便查看和调整。
3。 文章内带有下载文件，如下载excel，word，zip等文件时，这类文件的管理应该单独出来 ，不应该和图片放在一起， 
把所以文件都当成一个附件管理来管理，这样文件稍多时，不敢删，也无法继续 保留了。
4。在生成图片的缩略图的时候，考虑设置通过文件的中心来生成缩略图，现在在列表里生成的缩略图，就只有上半部分，把主要内容给挡住了，特别是图片里如果 有人头的时候，就只显示 人头了。下面的主要内容被 隐藏了。

**Comment by ruibaby** [comment]
目前 2.0 已经重新设计了附件系统，目前支持分组+多策略，欢迎体验：https://github.com/halo-dev/halo/releases/tag/v2.0.0

/close
