### ISSUE TITLE
提供富文本编辑器

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#1933]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/guide)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo-admin/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [x] 添加新的特性或者功能
- [ ] 请求技术支持

RT，支持富文本编辑器，考虑到某些类型的文章编辑使用 Markdown 比较难受，所以提供可提供一个 富文本编辑器，在文章编辑页面可随意切换。

~~有好的富文本编辑器可以推荐一下。~~

**Comment by dysf888** [comment]
好像没有找到在编辑的时候可以直接上传附件并且插入文章中的 转halo之前typecho上这个功能很实用

**Comment by ruibaby** [comment]
> 好像没有找到在编辑的时候可以直接上传附件并且插入文章中的 转halo之前typecho上这个功能很实用

目前编辑器支持拖拽上传和粘贴上传。

**Comment by dysf888** [comment]
> > 好像没有找到在编辑的时候可以直接上传附件并且插入文章中的 转halo之前typecho上这个功能很实用
> 
> 目前编辑器支持拖拽上传和粘贴上传。

emmm俺的意思是非图片类型的附件,有时候提供 .zip 什么的文件下载什么的

**Comment by ruibaby** [comment]
> emmm俺的意思是非图片类型的附件,有时候提供 .zip 什么的文件下载什么的

PR welcome

**Comment by ruibaby** [comment]
已经在 2.0.0-alpha.1 默认提供。https://github.com/halo-dev/halo/releases/tag/v2.0.0-alpha.1

/close
