### ISSUE TITLE
关于架构问题

### ISSUE THREAD

**Issue by lnsane** [halo-dev/halo#194]
我自己也在尝试用servlet + vue 写一个轻量级blog系统，但是我遇到好多问题。。。比如前后端的交换问题，网页的排版问题。数据库的设计问题，我发现好多时候刚开始想到，但是后面会发现很多其他的问题，就比如说文章的标签，我刚开始就没有想到，标签是一对多的关系，导致后面还要改。。。。。不知道你的思路是这么样的呢？主要是网页的设计问题，还有数据库的设计方面。我想了解下。

**Comment by JohnNiang** [comment]
这些都是在不断地摸爬滚打中得出来的。

在开始 coding 前，把需求定好，原型设计好，数据库设计好。而不是一上来就开始写代码，中途发现这里不合理那里不合理。

建议去看看 《软件工程》。

关于数据库设计，可以看看 halo 的实体类。

关于网页设计，这个要去看各个主题了。

**Comment by lnsane** [comment]
@JohnNiang 谢谢
