### ISSUE TITLE
文章自动输出摘要问题。

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#196]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

文章自动输出的摘要有问题，有时候会导致样式错乱。

**Comment by hd2y** [comment]
希望自动输出的摘要信息是针对html的text截取的，现在好像直接将markdown的内容前一部分截取？

**Comment by ruibaby** [comment]
@hd2y 已知问题，下个版本修改。

**Comment by ruibaby** [comment]
已修复
