### ISSUE TITLE
vue.$log哪里来的？

### ISSUE THREAD

**Issue by lnsane** [halo-dev/halo#197]
https://cn.vuejs.org/v2/guide/migration.html#Array-prototype-remove-%E7%A7%BB%E9%99%A4

**Comment by JohnNiang** [comment]
<https://github.com/halo-dev/halo-admin/blob/09732030a4ef5ea983c93c7703fff20a7ecafa8c/package.json#L27>

<https://github.com/halo-dev/halo-admin/blob/master/src/logger.js>
