### ISSUE TITLE
全局变量是什么时候作为 model 传给 ftl 的？

### ISSUE THREAD

**Issue by sfyumi** [halo-dev/halo#200]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [x] 请求技术支持

RT
[全局变量-文档](https://halo.run/develop/theme/global-variable.html#%E5%85%A8%E5%B1%80%E5%8F%98%E9%87%8F)
* 博客地址：${context!}
* 主题根路径：${static!}
* 博客标题：${options.blog_title!}
* ...
我只在代码里找到了 
```
        model.addAttribute("is_index", true);
        model.addAttribute("posts", posts);
        model.addAttribute("rainbow", rainbow);
```

**没有找到向 `model` 添加  `options`  的代码。**

**Comment by ruibaby** [comment]
https://github.com/halo-dev/halo/blob/master/src/main/java/run/halo/app/event/freemarker/FreemarkerConfigAwareListener.java

**Comment by sfyumi** [comment]
> https://github.com/halo-dev/halo/blob/master/src/main/java/run/halo/app/event/freemarker/FreemarkerConfigAwareListener.java

多谢
