### ISSUE TITLE
第一次导入到IDEA里，找不到javax.annotation.meta.When的类文件

### ISSUE THREAD

**Issue by AutumnLAN** [halo-dev/halo#201]
Information:java: Errors occurred while compiling module 'run.halo.app.halo.main'
Information:javac 1.8.0_162 was used to compile java sources
Information:2019/6/16 8:05 - Compilation completed with 100 errors and 1 warning in 21 s 876 ms
Warning:java: 未知的枚举常量 javax.annotation.meta.When.MAYBE
  原因: 找不到javax.annotation.meta.When的类文件

新手小白，解决不了。。

**Comment by JohnNiang** [comment]
请提供更详细的错误信息。我猜测是没有安装 Lombok 插件。

**Comment by AutumnLAN** [comment]
![U1THM8@)5{A{TE5K${GGF}E](https://user-images.githubusercontent.com/51471513/59557715-5f59a680-9013-11e9-8245-0e182a5dbc24.png)
已经安装了lombok。

**Comment by AutumnLAN** [comment]
![image](https://user-images.githubusercontent.com/51471513/59557720-8a43fa80-9013-11e9-90da-acc96befdc94.png)
然后这是报错

**Comment by JohnNiang** [comment]
https://halo.run/docs/faq.html#q2-%E5%AF%BC%E5%85%A5%E9%A1%B9%E7%9B%AE%E5%88%B0-idea-%E6%88%96%E8%80%85-eclipse-%E5%90%8E%E5%A4%A7%E9%87%8F%E6%8A%A5%E9%94%99%EF%BC%9F

**Comment by AutumnLAN** [comment]
![image](https://user-images.githubusercontent.com/51471513/59557753-819ff400-9014-11e9-972b-a178ae4eccfa.png)
非常感谢，问题解决了

**Comment by bw2016y** [comment]
mark

**Comment by Ronzhen** [comment]
大佬们，问题怎么解决的啊，上面的链接怎么打不开呀

**Comment by JohnNiang** [comment]
这只是警告，不是错误。
