### ISSUE TITLE
静态资源获取不到

### ISSUE THREAD

**Issue by Dawn-Oy** [halo-dev/halo#202]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [x] 请求技术支持

**Comment by ruibaby** [comment]
@Dawn-Oy https://www.halo.run/docs/faq.html#q1-halo-%E6%98%AF%E4%BB%80%E4%B9%88%EF%BC%9F

**Comment by Dawn-Oy** [comment]
[
![image](https://user-images.githubusercontent.com/49439195/59561341-ca29d280-9051-11e9-9495-61658bfc8c84.png)
](url)[
![image](https://user-images.githubusercontent.com/49439195/59561355-e9c0fb00-9051-11e9-98d7-2e95c6e2d0fb.png)
](url)[
![image](https://user-images.githubusercontent.com/49439195/59561360-052c0600-9052-11e9-804e-7800546049bb.png)
](url)
[
![image](https://user-images.githubusercontent.com/49439195/59561369-27be1f00-9052-11e9-9c89-cdcdc1f831b4.png)
](url)
我按照文档的步骤配置的，然后这些静态资源获取不到。
nginx配置的80端口，静态资源还是8090端口，我不知道该怎么配置才能获取到这些静态资源。

**Comment by Dawn-Oy** [comment]
我配置好nginx后，去腾讯云配置安全组把8090端口关了，然后静态资源就获取不到了，然后我想着静态资源也让nginx代理，但是我不会配，百度到的我不知道怎么应用到这个项目上。然后我就放开了8090端口，然后去赔了证书，然后就是上面的图那样的，静态资源都是http而且还拿不到，就跟8090端口关了一样。（第一次把项目部署到云上，菜鸟求助）

**Comment by JohnNiang** [comment]
https://halo.run/guide/faq.html#q6-%E4%B8%BA%E4%BB%80%E4%B9%88%E6%9C%89%E4%BA%9B%E9%A1%B5%E9%9D%A2%E8%AE%BF%E9%97%AE-404%EF%BC%9F

**Comment by JohnNiang** [comment]
请先去管理端进行配置博客地址。

**Comment by Dawn-Oy** [comment]
谢谢，原来是这个原因，我解决了
