### ISSUE TITLE
文章路径自动生成问题

### ISSUE THREAD

**Issue by sxhjhf** [halo-dev/halo#203]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

版本： 1.0.2
数据库： H2
运行模式： production

重现：
1. 写一篇以英文标题开头的文章，发布，路径自动生成。（eg: java 学习记录一）
2. 再写一篇以同样英文标题开头的文章（eg: java 学习记录二），发布。
3. 此时报错如下
![image](https://user-images.githubusercontent.com/8285257/59561952-a6b65600-9058-11e9-880d-abc1ae876bec.png)

分析：
路径自动生成策略可能是根据标题的内容获取英文字符来自动创建，但是某些情况下（eg: 写一些系列日志文章），就会出现路径重复的问题。

建议：
取消标题参照策略，或者设置可选项功能。谢谢。

**Comment by JohnNiang** [comment]
您好，关于文章的路径是可以自己主动设置的。

**Comment by 565785929** [comment]
> 您好，关于文章的路径是可以自己主动设置的。

没看代码，创建文章测试了一下， 
如果是纯中文的，路径就是时间戳；
如果是纯英文的，路径就是标题；
如果是中英混合，路径就是标题中的英文；
这样会带来一个问题，有时路径会已存在。不如默认都是时间戳。有特殊需求再主动设置。更方便不是吗？
