### ISSUE TITLE
上传文章

### ISSUE THREAD

**Issue by nbutGit** [halo-dev/halo#206]
halo博客可以上传在本地写好的md文件吗

**Comment by ruibaby** [comment]
@nbutGit 系统管理 -> 小工具，有 Markdown 文件导入。

**Comment by nbutGit** [comment]
@ruibaby 上传带有本地图片路径那种的markdown  是需要先将图片上传到附件库   然后更改markdown里的图片路径吗

**Comment by JohnNiang** [comment]
目前只能这样解决图片这个问题。

**Comment by nbutGit** [comment]
@ruibaby 好滴，谢谢。要是我服务器上的博客系统需要重装，原有的数据要怎么导出呀

**Comment by JohnNiang** [comment]
不好意思，目前还没有导出数据的功能。后续将不断迭代。

为什么需要重装呢？

**Comment by nbutGit** [comment]
@ruibaby 就比如更换了服务器之类的

**Comment by nbutGit** [comment]
@JohnNiang 就比如更换了服务器之类的

**Comment by JohnNiang** [comment]
把 `~/.halo` 打包带走就好了。

**Comment by nbutGit** [comment]
@JohnNiang 好滴好滴  非常感谢
