### ISSUE TITLE
博文增加代码块高亮强调某几行的效果

### ISSUE THREAD

**Issue by stars-one** [halo-dev/halo#2072]
### 你当前使用的版本

1.4.2

### 描述一下此特性

看到了之前的Vue文档，可以实现代码块里的高亮某行的效果，阅读体验比较好，是否考虑增加此功能？

效果如下图所示：

![](https://img2022.cnblogs.com/blog/1210268/202205/1210268-20220506180813845-736799313.png)

参考的链接：

[Markdown 拓展 | VuePress 中文文档 | VuePress 中文网](https://www.vuepress.cn/guide/markdown.html#%E4%BB%A3%E7%A0%81%E5%9D%97%E4%B8%AD%E7%9A%84%E8%A1%8C%E9%AB%98%E4%BA%AE)

有个开源库链接：
[egoist/markdown-it-highlight-lines: Highlight specific lines in code blocks.](https://github.com/egoist/markdown-it-highlight-lines)

### 附加信息

目前的想法通过自定义主题实现，由前端获取原始md格式数据，进行md的渲染

**Comment by stars-one** [comment]
心有余力不足，前端这块不是很懂，我只是初级入门 :joy:

**Comment by ruibaby** [comment]
> 心有余力不足，前端这块不是很懂，我只是初级入门 😂

Okay，晚点我会尝试一下。

/area admin

**Comment by ruibaby** [comment]
这个特性我尝试了一下，似乎不是很好处理。因为目前关于代码块我们是直接保存的原格式，没有保存经过高亮渲染引擎（PrismJS、highlight.js 等）后的内容。如果要使用 https://github.com/egoist/markdown-it-highlight-lines 这个插件的话，那么就需要保存代码高亮渲染后的内容，否则在前台文章中也需要各个主题去处理。所以目前可能不会考虑去做这个修改，但不排除在后续大版本中会做这个改动（直接存储高亮渲染的代码块结构）。

/milestone 2.0

**Comment by ruibaby** [comment]
> 有点不太明确，目前版本，库中的数据是markdown格式还是html的格式？

@stars-one 目前都是保存了的，在 contents 表。

**Comment by ruibaby** [comment]
在 https://github.com/halo-dev/halo/pull/6428 中已经支持完全通过插件扩展编辑器代码快的高亮渲染方式，所以后续期望是在插件中实现。

/close
