### ISSUE TITLE
关于【系统-小工具-博客备份-整站备份】的问题咨询

### ISSUE THREAD

**Issue by ChunelFeng** [halo-dev/halo#2073]
### Your current Halo version

docker latest版本

### Describe this feature

【背景】
大佬您好，我自己的ecs快要到期了，结束的时候，应该回去淘宝上用朋友的账号买收购充值，机器肯定是要换的了。
我在现在在阿里云的ecs上通过 docker 部署了 halo 版本的博客。
里面也写了不少内容：[个人博客 地址](http://www.chunel.cn/)

【问题】
1，我刚才通过【整站备份】功能，下载了 *.zip包到本地，如果我今后要换 ecs的话，通过找个zip就可以一键恢复么？有具体使用方法的文档么？

2，【系统-博客设置-SMTP服务】这里的功能，有什么作用？ 能帮我一键生成一个 自己域名结尾的邮箱么？

**Comment by ruibaby** [comment]
1. 如果是使用的默认的 h2 数据库，那么所有的数据都在这个压缩包，这个压缩包包含整个工作目录，参考 https://docs.halo.run/getting-started/prepare#%E5%B7%A5%E4%BD%9C%E7%9B%AE%E5%BD%95 。
2. 目前用在评论发信和重置密码，需要用到三方邮件服务商。

/kind support

**Comment by ChunelFeng** [comment]
1，哈哈，我打开zip文件，里面就是 ~/.halo 这一批内容。保存到本地，就放心了

**Comment by JohnNiang** [comment]
A2： 目前我所知道的邮件服务商有：https://www.fastmail.com/ ，不过它需要收费才能够创建以自己域名结尾的邮箱。

**Comment by ruibaby** [comment]
@ChunelFeng 如果没有其他问题，这个 issue 就先关闭了。

/close

**Comment by ChunelFeng** [comment]
没有了，非常感谢
