### ISSUE TITLE
网站从http改成https，部分之前上传的图片加载不出来

### ISSUE THREAD

**Issue by letdosomething** [halo-dev/halo#2074]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

1.5.2

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker

### 在线站点地址

https://gaodongfei.com

### 发生了什么？

网站使用http运行了一段时间，也写了几篇文章，尝试将网站配成https之后，页面上的css样式加载不出来，报错显示是上传的图片是http的有跨域问题

### 附加信息

<img width="899" alt="image" src="https://user-images.githubusercontent.com/57476984/167279961-0d08f199-cfaa-4618-91ec-f3f333c569f8.png">

**Comment by ruibaby** [comment]
https://docs.halo.run/user-guide/faq#前台样式丢失如何解决

对于部分已经保存的内容，可以参考 https://bbs.halo.run/d/153 解决。

**Comment by letdosomething** [comment]
thanks, 直接修改数据库生效了

**Comment by ruibaby** [comment]
> thanks, 直接修改数据库生效了

Okay，那我先关闭此 issue 了。


/close
