### ISSUE TITLE
基于宝塔 supervisor 更新版本

### ISSUE THREAD

**Issue by qq240** [halo-dev/halo#2079]
### Your current Halo version

1.5.2

### Describe this feature

我用的宝塔supervisord守护程序搭建，我想问下更新的化是直接下载到运行包目录改名就行吗？

**Comment by ruibaby** [comment]
和这个教程的差别是不大的。https://docs.halo.run/getting-started/upgrade

1. 在 supervisor 停止 Halo 进程。
2. 备份。
3. 替换最新的 Jar，然后去 supervisor 启动 Halo 进程。

/retitle 基于宝塔 supervisor 更新版本
/kind support

**Comment by qq240** [comment]
ok已经解决了
