### ISSUE TITLE
sm.sm图床也无法上传

### ISSUE THREAD

**Issue by UvDream** [halo-dev/halo#2080]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

设置sm.sm图床

### 使用的什么数据库？

MySQL 5.7

### 使用的哪种方式部署？

Docker

### 在线站点地址

www.uvdream.cn

### 发生了什么？

后台设置了sm.sm图床也是无法上传
[halo-log-2022-05-10-15-48-00.log](https://github.com/halo-dev/halo/files/8659445/halo-log-2022-05-10-15-48-00.log)
的

**Comment by ruibaby** [comment]
> org.springframework.web.client.ResourceAccessException: I/O error on POST request for "https://sm.ms/api/v2/upload": sm.ms; nested exception is java.net.UnknownHostException: sm.ms

可以尝试在服务器 `ping sm.ms`，或者 `dig sm.ms`。查看是否输出正常。

**Comment by JohnNiang** [comment]
@UvDream 你的服务器的网络似乎有些问题，之前你似乎也遇到过无法连接 qiniu 的域名：https://github.com/halo-dev/halo/issues/1893

**Comment by UvDream** [comment]
> @UvDream 你的服务器的网络似乎有些问题，之前你似乎也遇到过无法连接 qiniu 的域名：#1893

我ping过都是可以的
<img width="759" alt="image" src="https://user-images.githubusercontent.com/33121872/167578408-3e86390c-2221-4176-9314-6c0ff7c4eccc.png">
七牛云那个至今没解决,所以我尝试了下其它的

**Comment by UvDream** [comment]
> > org.springframework.web.client.ResourceAccessException: I/O error on POST request for "https://sm.ms/api/v2/upload": sm.ms; nested exception is java.net.UnknownHostException: sm.ms
> 
> 可以尝试在服务器 `ping sm.ms`，或者 `dig sm.ms`。查看是否输出正常。

<img width="717" alt="image" src="https://user-images.githubusercontent.com/33121872/167578610-d6ccdb54-e03b-4a19-882e-b5657ee8a8f8.png">

**Comment by JohnNiang** [comment]
@UvDream 试试在容器内执行以上命令，还能得到相同的结果么？

**Comment by UvDream** [comment]
> @UvDream 试试在容器内执行以上命令，还能得到相同的结果么？

你们的容器没装ping😭,我自己装一个吗

**Comment by JohnNiang** [comment]
> > @UvDream 试试在容器内执行以上命令，还能得到相同的结果么？
> 
> 你们的容器没装ping😭,我自己装一个吗

试试：`curl -vL sm.ms` 或者 `wget sm.ms`。

**Comment by UvDream** [comment]
> 



> > > @UvDream 试试在容器内执行以上命令，还能得到相同的结果么？
> > 
> > 
> > 你们的容器没装ping😭,我自己装一个吗
> 
> 试试：`curl -vL sm.ms` 或者 `wget sm.ms`。

我的服务器是不是需要放行一些端口出去,让halo容器访问外网?

**Comment by UvDream** [comment]
> curl -vL sm.ms

<img width="433" alt="image" src="https://user-images.githubusercontent.com/33121872/167583435-c4f70659-0145-44c8-b2cc-d5a4df9248f3.png">

**Comment by ruibaby** [comment]
@UvDream 你好，请问这个问题已经得到解决了吗？

**Comment by JohnNiang** [comment]
Hi @UvDream，请问这个问题有解决么？如果确实解决了，可以提供一下解决方案么。

**Comment by UvDream** [comment]
> @UvDream 你好，请问这个问题已经得到解决了吗？



> Hi @UvDream，请问这个问题有解决么？如果确实解决了，可以提供一下解决方案么。

网桥挂了,
```
yum install bridge-utils
pkill docker
iptables -t nat -F
ifconfig docker0 down
brctl delbr docker0
service docker restart
```

**Comment by sweetwisdom** [comment]
https://smms.app/
官网换了,改下域名就可以了

>> Due to network issues, users from China Mainland are unable to access SM.MS, we have added an alternate domain name smms.app.
