### ISSUE TITLE
希望邮件通知模板中的参数可以丰富一点~

### ISSUE THREAD

**Issue by iRoZhi** [halo-dev/halo#2084]
### Your current Halo version

1.5.3

### Describe this feature

看了一下，目前可供调用的参数有点少，希望可增加以下参数
mail_notice：
{评论者邮箱地址}、{评论者ip地址}、{该评论状态}、{评论时间}
mail_reply：
{双方邮箱地址}、{回复时间}

**Comment by JohnNiang** [comment]
Hi @ruibaby ，建议指出具体需要修改什么地方，这样第一次参与贡献的朋友更容易上手。

**Comment by ruibaby** [comment]
https://github.com/halo-dev/halo/blob/0e3890ada48451ecb51fcd36a5a2ca6cd127e26f/src/main/java/run/halo/app/listener/comment/CommentEventListener.java#L228-L232

在这个位置添加必要的参数即可。
