### ISSUE TITLE
写文章时添加的图片不显示

### ISSUE THREAD

**Issue by carolin-violet** [halo-dev/halo#2089]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

1.5.3

### 使用的什么数据库？

Other

### 使用的哪种方式部署？

Fat Jar

### 在线站点地址

http://82.157.183.73:8090/archives/python%E8%B0%83%E7%94%A8qq%E9%82%AE%E7%AE%B1%E6%8E%A5%E5%8F%A3%E5%8F%91%E9%80%81%E9%82%AE%E4%BB%B6

### 发生了什么？

文章中的图片不惜那是

**Comment by Yhcrown** [comment]
似乎是文件名的问题 见#1205，应该快修复了。

**Comment by JohnNiang** [comment]
> 似乎是文件名的问题 见#1205，应该快修复了。

是的，具体修复请参考：https://github.com/halo-dev/halo/issues/1205
