### ISSUE TITLE
访问量统计

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#209]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [x] 添加新的特性或者功能
- [ ] 请求技术支持

RT

**Comment by JohnNiang** [comment]
希望能够统计今日访问量，昨日访问量，最近一个星期的访问量，最近一个月，最近三个月，最近半年，最近一年。( You feel me ~.  :rofl:

**Comment by ruibaby** [comment]
@JohnNiang 呵，偏不

**Comment by ruibaby** [comment]
其实这个我更想用插件实现。

**Comment by chao19991005** [comment]
您好，请问我是否可以尝试做一下这个功能

**Comment by ruibaby** [comment]
@chao19991005 当然，欢迎尝试。

**Comment by chao19991005** [comment]
@ruibaby 好的谢谢 请问是否可以将问题分配给我

**Comment by chao19991005** [comment]
@ruibaby 你好 好像访问量统计已经在目前的代码中实现了 此外这个issue还需要做些什么呢
