### ISSUE TITLE
后台小工具中的 Markdown 导入可以选择任意文件

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#2090]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

1.5.3

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 在线站点地址

https://halo.run

### 发生了什么？

see https://github.com/halo-dev/halo/issues/2088#issuecomment-1127756950

可以限定部分后缀格式的文件，如：`.markdown` `.md` `.txt`。

在 admin 的上传组件中已经提供了 accepts 参数。

https://github.com/halo-dev/halo-admin/blob/dfd445f9769c36783436598082825ec150895a11/src/components/Upload/FilePondUpload.vue#L63-L69

/kind bug
/milestone 1.6.x
/area admin

**Comment by JohnNiang** [comment]
出现 OOM 的关键在于这里直接读取了文件：

https://github.com/halo-dev/halo/blob/0e3890ada48451ecb51fcd36a5a2ca6cd127e26f/src/main/java/run/halo/app/service/impl/BackupServiceImpl.java#L235

建议在后端也限制一下文件的大小和类型。

**Comment by ETLAN666** [comment]
因为课程要求，我需要积极参与到开源项目的开发，关于这个问题，我可以帮着做一些改进，大概周末提个pr

**Comment by ETLAN666** [comment]
我之前处理过类似的问题，我可以帮忙做一些改进吗？大概周末pr

**Comment by ETLAN666** [comment]
> /assign @ETLAN666
thx

**Comment by JohnNiang** [comment]
> > /assign @ETLAN666
> > thx

建议不要随意删除评论。

**Comment by ETLAN666** [comment]
> > > /assign @ETLAN666
> > > thx
> 
> 建议不要随意删除评论。❤️

谢谢提醒，没想到回复这么快，本来是想重新补充一下改进思路
