### ISSUE TITLE
增加文档形式功能页面

### ISSUE THREAD

**Issue by Foundation-Maker** [halo-dev/halo#2096]
### 你当前使用的版本

1.5.2

### 描述一下此特性

我最近在构建自己博客笔记，想采用页面进行组织，但实现起来不够灵活；我查看了有几种静态博客的支持此功能；只是提一个建议，如果不会支持，可以讨论一下；
<img width="1385" alt="image" src="https://user-images.githubusercontent.com/46839690/168996383-680781ab-5208-47d3-b626-934e531c139a.png">
<img width="1367" alt="image" src="https://user-images.githubusercontent.com/46839690/168996595-85a38b4f-1a7b-441d-a41e-9855fb1c02dd.png">

**Comment by ruibaby** [comment]
其实目前的主题 API 应该是可以满足这个效果的，但可能不太方便实现。后续我们会考虑如何让分类/菜单和文章更加结构化。感谢你的建议。

/kind feature
/milestone 2.0

**Comment by ruibaby** [comment]
目前 Halo 2 已经有一个插件支持文档管理，我将关闭此 issue。

https://www.halo.run/store/apps/app-yffxw

/close
