### ISSUE TITLE
默认主题的 jsDelivr 资源无法正常访问。

### ISSUE THREAD

**Issue by dingtianlu** [halo-dev/halo#2100]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

被墙 js加载不了

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker

### 发生了什么？

未知问题

**Comment by ruibaby** [comment]
> 是什么版本出现了此问题？

请问你使用的版本是？还有具体是哪个位置无法正常加载（后台、评论、前台）

**Comment by dingtianlu** [comment]
拉取docker hub 的最新版 halohub/halo:latest，进入首页[jquery js js](https://cdn.jsdelivr.net/npm/jquery@1.9.1/jquery.min.js)加载不了

**Comment by JohnNiang** [comment]
> 拉取docker hub 的最新版 halohub/halo:latest，进入首页[jquery js js](https://cdn.jsdelivr.net/npm/jquery@1.9.1/jquery.min.js)加载不了

/triage needs-information

建议提供一下具体是使用的哪个主题。如果确认是主题中引入了该 js，请尝试向主题作者反馈此问题。

**Comment by dingtianlu** [comment]
![image](https://user-images.githubusercontent.com/25783998/169432132-4a632d96-4506-4703-855a-7c1ee0c6e1b8.png)

**Comment by guqing** [comment]
> ![image](https://user-images.githubusercontent.com/25783998/169432132-4a632d96-4506-4703-855a-7c1ee0c6e1b8.png)
> 

使用的halo哪个版本，你可以到 https://github.com/halo-dev/halo-theme-anatole 下载最新的更新一下主题

**Comment by JohnNiang** [comment]
> 使用的halo哪个版本

Hi @guqing ，@dingtianlu 使用的应该是最新版。建议 @dingtianlu 更新一下默认主题，我们最近优化了默认主题。

**Comment by ruibaby** [comment]
可以直接下载 master 分支的版本：https://github.com/halo-dev/halo-theme-anatole/archive/refs/heads/master.zip

另外，在这一个 https://github.com/halo-dev/halo/pull/1621/files PR 中，应该就已经将 jsDelivr 的资源改为了本地资源，不知道你的 latest tag 是什么时候的版本。

**Comment by dingtianlu** [comment]
好的 我已经该到本地资源了谢谢

**Comment by ruibaby** [comment]
/retitle 默认主题的 jsDelivr 资源无法正常访问。

@dingtianlu 如果问题已经解决，我将关闭此 PR。

/close
