### ISSUE TITLE
最新文章、热门文章、最近更新、最多点赞无法显示，在点击的同时，首页会出现错误信息提示

### ISSUE THREAD

**Issue by TheShyzzcy** [halo-dev/halo#2106]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

1.5.3

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker

### 在线站点地址

http://124.220.170.34:8090/

### 发生了什么？

看着难受什么都不显示的话，影响美观

### 附加信息

![image](https://user-images.githubusercontent.com/105832208/169737745-7ec1753e-5728-4c73-be56-ce6ebffc26a4.png)
![2222222](https://user-images.githubusercontent.com/105832208/169737871-4a5bce8b-c6eb-4c23-b193-df412fb1ecc9.png)

**Comment by JohnNiang** [comment]
这里有启用 API 服务么？

![image](https://user-images.githubusercontent.com/16865714/169738086-f71b9d4f-aa88-417a-a65a-de1c78126d77.png)

/kind support

**Comment by TheShyzzcy** [comment]
> 这里有启用 API 服务么？
> 
> ![图片](https://user-images.githubusercontent.com/16865714/169738086-f71b9d4f-aa88-417a-a65a-de1c78126d77.png)
> 
> /善良的支持

![image](https://user-images.githubusercontent.com/105832208/169738298-49993dd8-353c-43c0-8beb-91b36e3ce35a.png)
这边好像没有这个选项

**Comment by ruibaby** [comment]
这属于主题的 issue，请看主题的文档：https://github.com/qinhua/halo-theme-joe2.0#%EF%B8%8F-%E5%BF%85%E8%AF%BB

**Comment by TheShyzzcy** [comment]
> 这个属于主题的问题，请看主题的文档：https://github.com/qinhua/halo-theme-joe2.0#%EF%B8%8F-%E5%BF%85%E8%AF%BB

已解决，感谢大佬
