### ISSUE TITLE
Version中正则表达式与gradle.properties中版本不匹配

### ISSUE THREAD

**Issue by shenmuegit** [halo-dev/halo#2107]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

1.5.3

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

Version中正则表达式与gradle.properties中版本不匹配
导致ThemeRepositoryImpl类中checkThemePropertyCompatibility永远为false
正则: ^(?<major>0|[1-9]\d*)\.(?<minor>0|[1-9]\d*)\.(?<patch>0|[1-9]\d*)(?:-(?<preRelease>beta|alpha|rc)\.(?<preReleaseMajor>0|[1-9]\d*))?$
版本: 1.5.3-SNAPSHOT

**Comment by JohnNiang** [comment]
Hi @shenmuegit ，感谢发现了这个问题。

- 每次发版前，我们都会去掉 SNAPSHOT
- 开发调试的时候，版本会变成 UNKNOWN

详情请看：

https://github.com/halo-dev/halo/blob/6d4ac6b79f1c3170352b21df2f0081affc794bf4/.github/workflows/halo.yml#L54

如果确实要针对当前版本进行打包，请尝试修改版本号。
如果想要完善这个版本问题，欢迎提交 PR 适配 `1.5.3-SNAPSHOT` 这种版本。

**Comment by ruibaby** [comment]
此问题目前在 Halo 2.0 应该不会存在，1.x 我们已经计划不打算添加或者修改功能，所以关闭此 issue。

/close
