### ISSUE TITLE
当前主题仅支持 Halo 1.3.0 及以上的版本

### ISSUE THREAD

**Issue by dhljoingithub** [halo-dev/halo#2114]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

主题远程下载出现 “当前主题仅支持 Halo 1.3.0 及以上的版本”

### 使用的什么数据库？

MySQL 5.7

### 使用的哪种方式部署？

Fat Jar

### 发生了什么？

远程下载主题出现“当前主题仅支持 Halo 1.3.0 及以上的版本”，本地运行没问题，部署到linux 上出现此问题

**Comment by ruibaby** [comment]
> 是什么版本出现了此问题？
主题远程下载出现 “当前主题仅支持 Halo 1.3.0 及以上的版本”

你服务器上的 Halo 版本是？

**Comment by ruibaby** [comment]
请问此问题还有后续补充吗？

**Comment by Xuer123** [comment]
题主解决了嘛？？

**Comment by 11yh** [comment]
题主解决了吗

**Comment by LANGJIALINGBOJUE** [comment]
我也遇到了这个问题。我自定义的版本号是”v1.6.2“，注意**这种版本号命名是不可以的，必须得是”1.6.2“这种格式**。

另外还有一种方法就是注释掉版本校验的代码：找到这个类ThemeRepositoryImpl，
if (false) {
throw new ThemeNotSupportException(
"当前主题仅支持 Halo " + newProperty.getRequire() + " 及以上的版本");
}
