### ISSUE TITLE
小工具上传文件不一致

### ISSUE THREAD

**Issue by MarmaladeCat** [halo-dev/halo#2115]
### Checklist

- [X] The issue has been searched in [GitHub Issues](https://github.com/halo-dev/halo/issues)
- [X] The issue has been searched in the [bbs.halo.run](https://bbs.halo.run/)
- [X] Already consulted [document](https://docs.halo.run/)

### What is version of Halo has the issue?

docker halo:1.5.3

### What database are you using?

H2

### What is your deployment method?

Docker

### What happened?

使用小工具上传markdown文件，再到全部文章中，发现内容不一致，第一个表格的前面部分丢失，文件内容如附件，或者也可以从如下网址https://gitee.com/openeuler-competition/summer2021-101/blob/master/doc/overview.md

[overview.md](https://github.com/halo-dev/halo/files/8769588/overview.md)

### Additional information

上传后的样子，可见缺少了前面部分内容

![4044435345DAC3B049094B1FF257518B](https://user-images.githubusercontent.com/33780699/170227995-7ba29ea7-d71b-4e41-bb26-7d48726cfb45.jpg)

**Comment by MarmaladeCat** [comment]
日志spring.log没有找到相关的日志，故没上传

**Comment by ruibaby** [comment]
可以复现，可能与这里有关 https://github.com/halo-dev/halo/blob/c2e477fcabb0a93f5c7aa3fffee17f0a1a21ccd1/src/main/java/run/halo/app/service/impl/PostServiceImpl.java#L339-L341

将表格的语法当做 FrontMatter 给移除了。

/kind bug
