### ISSUE TITLE
any file upload vuln 

### ISSUE THREAD

**Issue by lanfei-4** [halo-dev/halo#2118]
### Your current Halo version

v1.5.3

### Describe this feature

Any file has been uploaded. Procedure
![image](https://user-images.githubusercontent.com/43632720/170622316-28a10f89-f345-4ba5-8e2a-d04d2973198d.png)
question code
![image](https://user-images.githubusercontent.com/43632720/170622295-e50f2f5a-c8ce-4943-ba98-93fb0f6cb7f6.png)
verify vuln
![image](https://user-images.githubusercontent.com/43632720/170622385-93e5340c-2df9-4be6-a0b3-cee41354316b.png)
Access parsing HTML
![image](https://user-images.githubusercontent.com/43632720/170622448-26941573-ffda-4b66-8990-2799d4c54ae0.png)

#

### Additional information

Dynamic script access performs the download

**Comment by JohnNiang** [comment]
This is not a vulnerability. On the contrary, this is designed for administrator users who want to upload any files into their server.

**Comment by ruibaby** [comment]
/triage duplicate 

https://github.com/halo-dev/halo/issues/1575

**Comment by ruibaby** [comment]
I will close this issue and reopen if there are follow-up questions.

/close
