### ISSUE TITLE
markdown代码块样式渲染过慢

### ISSUE THREAD

**Issue by SwordMasterJS** [halo-dev/halo#2123]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

1.5.3

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 在线站点地址

https://blog.luckgirl.top/archives/mybatisplus

### 发生了什么？

进入时
![N_HRE6OEBP8G}S__3`FN3O4](https://user-images.githubusercontent.com/32394118/170807168-f94eb7c5-5a1b-480d-8983-7e8d3b00c0f3.png)
大概1分钟才会加载出来
![RV}IV0LN8PKC2MHX3CGW3RW](https://user-images.githubusercontent.com/32394118/170807182-77064a22-1a83-4731-9dac-e6dd3461fa2a.png)

使用 [docker默认](https://docs.halo.run/getting-started/install/docker) dicker默认安装halo，没有进行任何额外配置，仅仅添加了两篇文章，但代码块样式渲染非常慢
附上服务器配置
![H~_H%H)LT5O ~HGUHTOZTG6](https://user-images.githubusercontent.com/32394118/170807272-f525ffe2-1bb8-4323-bb9a-971f2fcda579.png)
图片也是秒加载出来

浏览器日志：
网络
![QUF77`A8AWJ$H M3 4 U8JB](https://user-images.githubusercontent.com/32394118/170807356-f0abdc04-1019-4fd1-b224-fc778ea4021d.png)
控制台
![IXG@UU YCZ61N4F(TXB9G_W](https://user-images.githubusercontent.com/32394118/170807402-1e0e78e7-dc5f-43ba-9166-c1585b505197.png)

判断是引用了jsdelivr，最近jsdelivr国内挂了，还是其他原因？求助如何优化

**Comment by SwordMasterJS** [comment]
又查询了一下，最新版已经不使用  jsDelivr CDN ，我先去尝试一下docker安装最新版本，或者有推荐哪个更新的版本比较稳定吗？

**Comment by SwordMasterJS** [comment]
已自行解决，不知道为什么重装了一次后，过了一会儿就没这个问题了。。。。

**Comment by JohnNiang** [comment]
/kind support

这个问题已经在 https://github.com/halo-dev/halo/pull/2098 修复。

/triage duplicate

请参考：<https://github.com/halo-dev/halo/issues/2097>。

**Comment by ruibaby** [comment]
代码块渲染慢似乎和你截图的资源无关，评论组件可以参考 https://bbs.halo.run/d/2488-guan-yu-yin-wei-jsdelivr-cdn-wu-fa-zheng-chang-fang-wen-ye-mian-de-wen-ti 更换源。

**Comment by ruibaby** [comment]
如果没有后续问题，我将关闭此 issue。

/close
