### ISSUE TITLE
502 Bad Gateway问题

### ISSUE THREAD

**Issue by yikexiaoyao** [halo-dev/halo#2129]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

1.5.3

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Fat Jar

### 在线站点地址

https://www.tingyuxuan.tk/

### 发生了什么？

半个月前开始，网站打开一直502，刷新无效，每次隔天刷新或者重启依然没有好转

**Comment by ruibaby** [comment]
应该是 Halo 进程被终止，可以提供一下运行日志。

**Comment by ruibaby** [comment]
如果没有后续动态，我将关闭此 issue。

/close
