### ISSUE TITLE
连接重置

### ISSUE THREAD

**Issue by zhouligang** [halo-dev/halo#213]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [ ] [Halo 论坛](https://bbs.halo.run)
- [ ] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [ ] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [x] 请求技术支持

**Comment by ruibaby** [comment]
@zhouligang 这是？方便给出详细问题吗？

**Comment by zhouligang** [comment]
为什么cerbot安装证书以后，请求地址动不动就出现连接重置，这是为什么呢，谁知道？如果多刷几次又能刷出来，再刷又是报错
![image](https://user-images.githubusercontent.com/33013031/59923934-326c2000-9467-11e9-8c38-7dab4bfd64df.png)

**Comment by zhouligang** [comment]
@ruibaby 我刚刚不知道开启问题了，问题都没描述都放出来了，不好意思

**Comment by ruibaby** [comment]
@zhouligang 建议看看 Caddy 的日志哦，看看有没有运行异常。

**Comment by zhouligang** [comment]
@ruibaby 我用的nginx，第一次装的就是caddy，按照步骤装的，装完后没有代理成功。我又装了nginx，结果这样了

**Comment by zhouligang** [comment]
@ruibaby 而且刚装上的前两天都是正常的，后面突然不正常了

**Comment by ruibaby** [comment]
@zhouligang nginx的日志呢，检查一下

**Comment by zhouligang** [comment]
@ruibaby 我刚才看了下日志，我发现只有请求成功的时候nginx才有日志，说明好像失败的时候压根没经过nginx

**Comment by ruibaby** [comment]
@zhouligang 那有点不好排查呀😂

**Comment by zhouligang** [comment]
@ruibaby 没事，那我再看看，谢谢了哈

**Comment by 565785929** [comment]
一样的问题，请问怎么解决的

**Comment by zhouligang** [comment]
> 一样的问题，请问怎么解决的

我是多刷新几次又会正常，过一会儿又不正常，你是这样的吗

**Comment by 565785929** [comment]
我怎么刷新都没反应，应该是nginx的问题，因为我按照ip打开的话是可以的，域名就不得行。

> 在 2019年7月1日，下午7:35，zhouligang <notifications@github.com> 写道：
> 
> 我是多刷新几次又会正常，过一会儿又不正常，你是这样的吗
> 
>

**Comment by zhouligang** [comment]
你那个估计是nginx没配置好，我这个现在不确定，我得等域名备案好了再测试下

**Comment by 565785929** [comment]
你的用ip可以访问吗， 还有你的nginx有这个错误吗。
signal process started

PS：买国外域名吧，方便。

**Comment by zhouligang** [comment]
@565785929 
 我没有那个错。国外域名啥时候也可以弄一个，国内也要一个，嘿嘿
