### ISSUE TITLE
2022年6月1日 都有1.5.3tag了为什么master分支启动的版本1.5.2比tag还老

### ISSUE THREAD

**Issue by wuxiongwei** [halo-dev/halo#2130]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

略

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Fat Jar

### 发生了什么？

2022年6月1日 都有1.5.3tag了为什么master分支启动的版本1.5.2比tag还老
<img width="900" alt="WX20220601-145357@2x" src="https://user-images.githubusercontent.com/4928711/171345409-d8978f37-fe12-4ce0-b922-d9a0f7818d35.png">

**Comment by JohnNiang** [comment]
想要运行 1.5.x 最新代码，请切换至 release-1.5 分支：https://github.com/halo-dev/halo/tree/release-1.5

**Comment by wuxiongwei** [comment]
好嘞
