### ISSUE TITLE
使用Serverless Devs部署至腾讯云SCF等类似的云服务

### ISSUE THREAD

**Issue by ffha** [halo-dev/halo#2142]
### 你当前使用的版本

1.5.3

### 当前情况
阿里云函数计算使用容器镜像创建不能实现持久化存储。
其他暂未测试。
Serverless Devs可以使得Halo可以部署至包括但不限于:
* 阿里云函数计算
* 腾讯云SCF

**Comment by ruibaby** [comment]
如果是通过容器来实现这样的产品的话，那么应该与应用无关。尝试找找是否有 Volume 之类的功能。挂载一下工作目录就可以了。

比如腾讯云托管：https://github.com/halo-dev/tencent-cloudbase-halo/blob/master/cloudbaserc.json#L17

**Comment by ffha** [comment]
阿里云可以挂载NAS,但是只能挂载至/home或者/mnt的子目录

**Comment by ruibaby** [comment]
> 

挂载位置应该是不会做限制的。

**Comment by ruibaby** [comment]
> https://github.com/devsapp/start-web-framework/tree/master/web-framework/php/wordpress/src/code/wordpress

可以看到，即便是 WordPress 这种公开发行的版本都是直接将原始代码放进去。甚至无法很好的得知代码来源和版本。
