### ISSUE TITLE
无法正常保存为中文的设置，显示乱码

### ISSUE THREAD

**Issue by xiaodu33603** [halo-dev/halo#2147]
### 检查清单

- [x] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

1.5.3

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Fat Jar

### 在线站点地址

https://xiaodu33603.com/

### 发生了什么？

版本：1.5.3
数据库：H2 1.4.199 (2019-03-13)
运行模式：production
启用主题：Anatole
启动时间：2022-06-08 17:05

系统设置里存储的中文无法正常显示，显示问号，不知道什么问题，文章可以正常显示

![QQ截图20220609155332](https://user-images.githubusercontent.com/68016007/172795506-1a5d4d79-3414-4b61-8e56-55f86d50e2e7.png)
![QQ图片20220609155836](https://user-images.githubusercontent.com/68016007/172795833-32ea55c0-544c-4be3-b1b0-e80a9c8a5502.png)

**Comment by xiaodu33603** [comment]
用的服务运行

**Comment by xiaodu33603** [comment]
好像是主题原因，换了一个主题就好了

**Comment by ruibaby** [comment]
建议提供一下服务器环境等信息，目前无法判断是什么原因导致的乱码。

/retitle 无法正常保存为中文的设置，显示乱码

**Comment by xiaodu33603** [comment]
好了，系统语言的原因

**Comment by zw-space** [comment]
> 好了，系统语言的原因

请问一下解决办法，我更改了系统语言，并没有奏效

**Comment by xiaodu33603** [comment]
> > 好了，系统语言的原因
> 
> 请问一下解决办法，我更改了系统语言，并没有奏效

改成英文系统
