### ISSUE TITLE
没法单独下载markdown笔记，markdown笔记备份的时候也没法单独将笔记所用的图片备份

### ISSUE THREAD

**Issue by carolin-violet** [halo-dev/halo#2148]
### 你当前使用的版本

1.5.3

### 描述一下此特性

没法单独下载markdown笔记，markdown笔记备份的时候也没法单独将笔记所用的图片备份

**Comment by ruibaby** [comment]
/kind feature

建议提供一下具体的用途，以及这个功能应该是怎样的。

**Comment by yikexiaoyao** [comment]
我这边遇到网站备份无法下载的问题
![Snipaste_2022-06-20_15-17-23](https://user-images.githubusercontent.com/36374114/174546280-8a9e25a7-d478-4df3-b71c-ca588789560a.png)
所有能用的下载工具都无法下载备份的压缩文件

**Comment by carolin-violet** [comment]
你好，就是关于博客的备份问题，那个备份数据的一下就备份了所有图片下了，有时候想备份下数据就有点麻烦，希望能单独开个备份markdown文档笔记的功能，当然备份markdown文档的时候顺便能把关联的图片也放一个单独的文件夹备份下来最好了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "halo-dev/halo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月10日(星期五) 下午4:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [halo-dev/halo] 没法单独下载markdown笔记，markdown笔记备份的时候也没法单独将笔记所用的图片备份 (Issue #2148)





 
/kind feature
 
建议提供一下具体的用途，以及这个功能应该是怎样的。

**Comment by ruibaby** [comment]
1.x 已经停止维护，我将关闭此 issue。

详情可看：https://www.halo.run/archives/halo-1.x-eol

/close
