### ISSUE TITLE
html 内容不一致

### ISSUE THREAD

**Issue by daichangya** [halo-dev/halo#215]
html 内容不一致
在文章中添加图片链接以后，mavonEditor中看到的html代码是
`<br><img src=xxx><br>`
但是数据库中是
`<img src=xxx>`
原因估计是mavonEditor 中的md 转html 逻辑和后台commonmark中的md转html逻辑不一致

**Comment by JohnNiang** [comment]
你的猜测是正确的。

**Comment by daichangya** [comment]
> 你的猜测是正确的。

这块有修改计划,目前感觉写文章很不爽,编辑界面明明看着格式没有问题.
发不完以后格式乱了

**Comment by ruibaby** [comment]
@daichangya 你暂时注意一下 markdown 的格式就好了，commonmark 的格式要求比较高，比如 空格，换行等。

**Comment by 88250** [comment]
> @daichangya 你暂时注意一下 markdown 的格式就好了，commonmark 的格式要求比较高，比如 空格，换行等。

Java 的 Markdown 处理器建议用 https://github.com/vsch/flexmark-java 这个项目扩展比较多，对文本的兼容性要求也比较好。

**Comment by ruibaby** [comment]
@88250 嗯，是有这个计划的，感谢反馈。

**Comment by ruibaby** [comment]
已切换为 https://github.com/vsch/flexmark-java
