### ISSUE TITLE
跨域问题，在新版谷歌浏览器环境下会出现跨域问题

### ISSUE THREAD

**Issue by wx1458084829** [halo-dev/halo#2155]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

1.5.3

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker

### 在线站点地址

http://www.007namo.com

### 发生了什么？

在新版本谷歌浏览器环境下，会出现跨域问题，已经找到答案。
部署环境： docker+mysql8.0
部署服务商：腾讯云+轻量云服务器
部署域名：http://www.007namo.com/ （没有使用https）

错误问题：出现一系列跨域资源错误
![image](https://user-images.githubusercontent.com/49525907/173504736-07ed9047-8bf8-40bd-bb6d-8d8f7a3fa9b8.png)

解决方法：1. 使用https域名。 2.在浏览器中直接执行chrome://flags/#block-insecure-private-network-requests ，选中Disabled ，relaunch 后就可以恢复正常了。

> 参见文章：https://blog.csdn.net/xiaoyuer_2020/article/details/125184448

**Comment by ruibaby** [comment]
https://docs.halo.run/user-guide/faq#%E5%89%8D%E5%8F%B0%E6%A0%B7%E5%BC%8F%E4%B8%A2%E5%A4%B1%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3

/triage duplicate
/kind support

**Comment by wx1458084829** [comment]
get it,thanks。下次提issues应该再搜索一下文档确认一下。
