### ISSUE TITLE
Markdown标题生成HTML的时候被URLEncode导致锚点无法使用

### ISSUE THREAD

**Issue by sppan24** [halo-dev/halo#2157]
### 检查清单

- [x] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

1.5.3

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Fat Jar

### 在线站点地址

https://sppan24.cn/archives/docker-dev-1.html

### 发生了什么？

Markdown标题生成HTML发生的时候，中文会被进行URLEncode，导致锚点无法定位，最终导致文章目录无法跳转对应的位置。

### 附加信息

<img width="1476" alt="image" src="https://user-images.githubusercontent.com/15795173/173796564-d4a89a8f-af56-45fd-8c57-845ffdb94b28.png">

**Comment by JohnNiang** [comment]
试试自定义锚点：

```markdown
### <a name="create-network"></a>创建网络

前往自定义锚点：[创建网络](#create-network)
```

**Comment by sppan24** [comment]
> 试试自定义锚点：
> 
> ```gfm
> ### <a name="create-network"></a>创建网络
> 
> 前往自定义锚点：[创建网络](#create-network)
> ```

好的 谢谢

**Comment by sppan24** [comment]
> https://bbs.halo.run/d/2486-guan-li-hou-tai-da-bu-kai-liao/16
> 
> 已经给主题提交了一个 PR，[CodeLunatic/halo-theme-simple-bootstrap#41](https://github.com/CodeLunatic/halo-theme-simple-bootstrap/pull/41)，包含了目录跳转的修复。
> 
> 也可以进入 https://github.com/ruibaby/halo-theme-simple-bootstrap/tree/refactor/remove-jsdelivr-cdn 下载 ZIP。
> 
> /kind support

这个我觉得应该和主题没关系吧，我去看过了，现在数据库里面的标题也是被编码了的，我之前的文章数据库里面标题就没有被编码，所以我觉得应该是服务端某个版本导致的。

**Comment by ruibaby** [comment]
> 这个我觉得应该和主题没关系吧，我去看过了，现在数据库里面的标题也是被编码了的，我之前的文章数据库里面标题就没有被编码，所以我觉得应该是服务端某个版本导致的。

对于浏览器来说，中文或者其他特殊字符被 URLEncode 处理是不会影响锚定位的，是符合预期的表现。这个问题就是主题所用的目录生成插件导致的。这个问题被 tocbot 这个插件定义为 bug，详情见：https://bbs.halo.run/d/2288/7

**Comment by ruibaby** [comment]
如果没有后续动态，我们将关闭此 issue。

/close

**Comment by huanglian666** [comment]
> 试试自定义锚点：
> 
> ```
> ### <a name="create-network"></a>创建网络
> 
> 前往自定义锚点：[创建网络](#create-network)
> ```

您好，麻烦问一下如何自定义锚点呢？我按照您的方式编辑了，默认的编辑器把我的a标签解析为标题内容了，没有当成html语言处理呢
