### ISSUE TITLE
重构管理端附件管理/附件选择/图库管理的文件排列方式

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#2159]
### 你当前使用的版本

1.5.3

### 描述一下此特性

采用 TailwindCSS 官方的 [aspect-ratio](https://github.com/tailwindlabs/tailwindcss-aspect-ratio) 插件来固定每项的长宽比，防止图片变形。

另外，目前图片的显示是采用的设置 background，而不是使用 img 标签。会导致图片无法加载的时候，导致空白。

/assign
/kind feature
/milestone 1.6.x

**Comment by WenyinWei** [comment]
文章封面图的长宽比面临复杂场景（PC 端目录/文章页、手机端目录/文章页）挑战， 可能需要自动在长宽比不合适时缩小图片尺寸，空白地方用透明替代。看看有没有其他好的解决方案？

**Comment by ruibaby** [comment]
> 文章封面图的长宽比面临复杂场景（PC 端目录/文章页、手机端目录/文章页）挑战， 可能需要自动在长宽比不合适时缩小图片尺寸，空白地方用透明替代。看看有没有其他好的解决方案？

用透明代替可能效果不是特别好。可以看看这个 issue 对应的解决方案。https://github.com/halo-dev/halo-admin/pull/580
