### ISSUE TITLE
建议仪表盘新增一些排序统计功能

### ISSUE THREAD

**Issue by liaocp666** [halo-dev/halo#2171]
### 你当前使用的版本

1.5.3

### 描述一下此特性

希望仪表盘中新增针对这两种的数据的文章排序功能：最多评论、最多浏览。

类似新动态卡片中的标签页，切换这两种排序

**Comment by Raremaa** [comment]
我打算先简单做，这里加2个标签 各位觉得如何

<img width="448" alt="image" src="https://user-images.githubusercontent.com/37170921/174709405-f0f2e985-0eaa-43d8-a250-604c132e0669.png">

**Comment by ruibaby** [comment]
> 我打算先简单做，这里加2个标签 各位觉得如何

我觉得可以。

/milestone 1.6.x
/kind feature

**Comment by Raremaa** [comment]
好滴 那我这周就发一下PR～

**Comment by JohnNiang** [comment]
> 好滴 那我这周就发一下PR～

非常期待~

/area admin

**Comment by liaocp666** [comment]
建议把最近评论放到第一个标签页，或者默认激活这个标签页。最近文章这个感觉可有可无
@Raremaa

**Comment by Raremaa** [comment]
> 建议把最近评论放到第一个标签页，或者默认激活这个标签页。最近文章这个感觉可有可无 @Raremaa

我感觉放第一个还比较合理，我目前感觉这个“最近文章”意义好像也不是很大。

其他小伙伴们怎么看

**Comment by ruibaby** [comment]
@liaocp666 @Raremaa 

其实可以把之前的 `最新文章` 这个 Tab 项做成一个下拉框，通过下拉框来选择 **最多评论、最多浏览**。

不知道好不好实现。

**Comment by Raremaa** [comment]
> @liaocp666 @Raremaa
> 
> 其实可以把之前的 `最新文章` 这个 Tab 项做成一个下拉框，通过下拉框来选择 **最多评论、最多浏览**。
> 
> 不知道好不好实现。

主要我感觉那个“新动态”卡片，里面的标签页是比较空的，放4个感觉刚刚好填满。（不考虑特别小屏的情况）
然后我这边想着就是改变一下顺序：最多评论、最多浏览、最近文章、最近评论

然后就是后续可能”新动态卡片“会放更多的标签，之后有这方面需求的时候，再改下拉框满足更多信息流展示的需求。

**Comment by Raremaa** [comment]
> @liaocp666 @Raremaa
> 
> 其实可以把之前的 `最新文章` 这个 Tab 项做成一个下拉框，通过下拉框来选择 **最多评论、最多浏览**。
> 
> 不知道好不好实现。

就我感觉下拉框的操作路径 是要比直接标签页要长的 实际使用上体验怪怪的

不过从业务分类角度看，其实最多评论，最多浏览，最新文章都是对“文章”这个实体做不同维度的排序和展示

从这方面考虑也合理。

我个人还是倾向于四个标签页平铺简单做😹

**Comment by Raremaa** [comment]
@JohnNiang @ruibaby @liaocp666  各位小伙伴怎么看这个问题

**Comment by liaocp666** [comment]
> 然后我这边想着就是改变一下顺序：最多评论、最多浏览、最近文章、最近评论

我感觉也可以，`新动态` 可以换成 `文章排名` ？@ruibaby @Raremaa

**Comment by ruibaby** [comment]
> 我感觉也可以，新动态 可以换成 文章排名 ？@ruibaby @Raremaa

但是还有一个 `最近评论` 的标签。

**Comment by ruibaby** [comment]
> > 但是还有一个 `最近评论` 的标签。
> 
> 排行榜？

我觉得可以叫做 **概览**

**Comment by Raremaa** [comment]
> 

极好！ 就改这个吧！

**Comment by liaocp666** [comment]
> > > 但是还有一个 `最近评论` 的标签。
> > 
> > 
> > 排行榜？
> 
> 我觉得可以叫做 **概览**

不错

**Comment by ruibaby** [comment]
目前仪表盘是不可以由使用者自定义的，所以尽可能做的通用一点。在 2.0 我们可能会做成这样的形态：

<img width="1511" alt="image" src="https://user-images.githubusercontent.com/21301288/174816546-621d1b60-2313-4719-8fb0-c3279d3e1d23.png">
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/21301288/174816743-70971d4e-5c2d-4e2c-9e16-f274745016db.png">
<img width="1549" alt="image" src="https://user-images.githubusercontent.com/21301288/174816808-37f9282f-f461-4c9c-a267-caca4b349a04.png">

**Comment by Raremaa** [comment]
我这一期接口的计划是会围绕“文章”这个实体
开放一个排序接口，支持按照时间，访问量，评论数进行排序

目前看起来后端api是兼容的

前端新加的两个标签加上之前的最新文章三个标签会做成一个独立组件

**Comment by Raremaa** [comment]
> 我这一期接口的计划是会围绕“文章”这个实体 开放一个排序接口，支持按照时间，访问量，评论数进行排序
> 
> 目前看起来后端api是兼容的
> 
> 前端新加的两个标签加上之前的最新文章三个标签会做成一个独立组件

这样能满足2.0的兼容吗

**Comment by JohnNiang** [comment]
> 这样能满足2.0的兼容吗

Hi @Raremaa ，目前可不考虑兼容 2.0。毕竟 2.0 本身就还没有 Release。

**Comment by ruibaby** [comment]
Halo 1.x 已停止维护，此 issue 可能不再有效，我将关闭此 issue。

https://www.halo.run/archives/halo-1.x-eol

/close
