### ISSUE TITLE
附件上传图片后缩略图方向错误

### ISSUE THREAD

**Issue by eziosudo** [halo-dev/halo#2173]
### 检查清单

- [X] 已经查阅过[文档](https://docs.halo.run/)
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题

### 是什么版本出现了此问题？

1.5.3

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

本地启动，仅后台

### 发生了什么？

部分图片上传后，缩略图方向错误。

原因在这里：
```
run.halo.app.handler.file.LocalFileHandler#generateThumbnail(BufferedImage originalImage, Path thumbPath,
        String extension)

Thumbnails.of(originalImage).size(THUMB_WIDTH, THUMB_HEIGHT).keepAspectRatio(true)
                .toFile(thumbPath.toFile());
```
[Thumbnail - issue 159](https://github.com/coobird/thumbnailator/issues/159)

是否考虑调整？

### 附加信息

<img width="700" alt="Screen Shot 2022-06-21 at 09 33 59" src="https://user-images.githubusercontent.com/54128896/174698067-2de613a8-c69b-4bc3-ad6c-b74e5dcb98a0.png">
<img width="326" alt="Screen Shot 2022-06-21 at 09 34 05" src="https://user-images.githubusercontent.com/54128896/174698071-9576fa07-f0e2-4c63-bddf-eac2c8f51a61.png">

**Comment by eziosudo** [comment]
我是本地启动的服务，直接调用后端接口做测测试。

个别手机拍的原图上传的时候会出现这个问题，并且这个图片在编辑压缩后上传又正常了
![Screenshot2022_06_21_122433](https://user-images.githubusercontent.com/54128896/174716205-b8618089-8cf2-4563-aa2d-f36c06273ea7.jpg)

https://github.com/coobird/thumbnailator/issues/159#issue-704448059 这个测试图片上传后方向也不正确
。
![image](https://user-images.githubusercontent.com/54128896/174716348-0f240e6f-f3ff-48a5-ad57-a436d783977c.png)

难道是我本地测试的原因？

**Comment by ruibaby** [comment]
@eziosudo 中文名称无法显示的问题与 https://github.com/halo-dev/halo/pull/1874 这个 PR 有关，因为这个 PR 的修改涉及到管理端项目的修改，所以你可能需要在本地同时启动一个 halo-dev/halo-admin 项目。因为目前的版本发布流程是在发布的时候才会编译 halo-admin 项目到 halo-dev/halo 主项目。

**Comment by eziosudo** [comment]
> @eziosudo 中文名称无法显示的问题与 #1874 这个 PR 有关，因为这个 PR 的修改涉及到管理端项目的修改，目前的版本发布流程是在发布的时候才会编译 halo-admin 项目到 halo-dev/halo 主项目。所以你可能需要在本地同时启动一个 halo-dev/halo-admin 项目。

好的，这个issue麻烦先别关，我想再研究下原因。

**Comment by ruibaby** [comment]
Any updates?
