### ISSUE TITLE
为什么@Entity,@Table同时设置name?

### ISSUE THREAD

**Issue by lnsane** [halo-dev/halo#218]
https://github.com/halo-dev/halo/blob/d4f3850cb2c1ac27681a9e91f65280708755a5c0/src/main/java/run/halo/app/model/entity/BaseComment.java#L17-L18

新手没有用过spring-boot

**Comment by JohnNiang** [comment]
因为有继承关系。

在编写 `JPQL` 的时候，需要用到这个 `Entity#name`。
