### ISSUE TITLE
后台发布文章页面预览按钮的提示语优化

### ISSUE THREAD

**Issue by manction** [halo-dev/halo#2182]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

1.5.3

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Fat Jar

### 在线站点地址

https://www.manction.com

### 发生了什么？

![Snap1](https://user-images.githubusercontent.com/9378928/174988865-03603b6a-e85b-4087-8650-d740ca45e491.png)

发布文章页面，这个按钮的提示应该是“预览”，目前是显示“编辑” ，是否改为：开启预览/关闭预览，类似于密码输入框的“显示密码”“隐藏密码”提示语，编辑这个提示不太清晰。

### 附加信息

月光海岸，用心创造快乐！
https://www.manction.com

**Comment by ruibaby** [comment]
/good-first-issue
/area admin
/milestone 1.6.x

需要修改 https://github.com/halo-dev/editor

**Comment by ruibaby** [comment]
Fixed at https://github.com/halo-dev/editor/pull/4
