### ISSUE TITLE
关于halo源码的问题

### ISSUE THREAD

**Issue by whoami1231** [halo-dev/halo#219]
请问如何打开swagger的api文档页面？

**Comment by ruibaby** [comment]
@whoami1231 具体请看：https://halo.run/develop/application/structure.html

**Comment by JohnNiang** [comment]
@whoami1231 https://halo.run/develop/application/start.html#%E9%AB%98%E7%BA%A7%E9%85%8D%E7%BD%AE

**Comment by whoami1231** [comment]
感谢
