### ISSUE TITLE
文章更新时间 逻辑优化

### ISSUE THREAD

**Issue by NullPointX** [halo-dev/halo#2193]
### Halo版本

`1.5.3`

### 我的建议：
对于读者而言，文章的更新时间应该是文章 **内容** 的「实际修改时间」，而不是文章除 **内容** 字段以外的修改时间。

### 目前文章更新时间的逻辑：
对文章内容以外的数据进行修改（比如：修改文章的SEO关键词），保存后，数据库中 `posts`表的 `update_time`和`edit_time` 以及 `contents`表的 `update_time` 都会以这次修改的时间为准。

**Comment by wxyShine** [comment]
只有当修改文章标题 或文章内容时 去更新posts表的edit_time字段 ，posts和contents表的update_time 保持上面的逻辑不变。可否？

**Comment by skyls03** [comment]
> 只有当修改文章标题 或文章内容时 去更新posts表的edit_time字段 ，posts和contents表的update_time 保持上面的逻辑不变。可否？

我觉得可以。

另外问一下，有了`edit_time` 为什么还要有 `update_time`？是历史遗留原因吗？

**Comment by wxyShine** [comment]
`create_time`和`update_time`好像是每个表都有的基础字段
