### ISSUE TITLE
博主发评论 优化建议

### ISSUE THREAD

**Issue by ListenV** [halo-dev/halo#2199]
### 你当前使用的版本

`1.5.3`

#### 评论现状

博主无法直接对文章发出评论，只能对别人评论进行回复。

#### 改善步骤

1. 允许博主直接在文章页进行评论和回复，评论和回复更直观
2. 评论时填写的邮箱必须与后台博主的邮箱一致
3. 为了确定是博主本人在评论，可以使用后台登录后的AccessToken进行鉴权

不知是否可行，讨论一下

**Comment by JohnNiang** [comment]
Halo 1.x 上暂时没有精力实现这个直接“直接在文章页面进行评论和回复”，这会涉及太多的改造。不过会在实现 Halo 2.x 的时候会考虑到这个问题。

尤其是 Halo 2.x 的认证体系和之前会有所不同。Halo 1.x 的认证体系比较简单，目前有以下缺点：

- 认证逻辑比较简单，没有利用 Session 机制来判断用户是否登录。
- 没有 PersonalAccessToken 机制，目前只支持创建一个用户自定义的 Token，且该 Token 的 Scope 还无法自定义。

Halo 2.x 我们打算实现：

- 利用 Session 机制判断用户是否登录。
- 完备的 PersonalAccessToken 机制，可针对不同 Scope 申请不同的 Token。
- 改造评论组件，允许登录用户直接评论和回复。

/kind improvement
/milestone 2.0

**Comment by ruibaby** [comment]
@NullPointX 目前可以在后台的文章管理列表打开评论弹框，其中有创建评论的功能。

<img width="1326" alt="image" src="https://user-images.githubusercontent.com/21301288/176338171-1e37afc3-58bd-4f4f-bfe1-b40faf2c3d64.png">

**Comment by ruibaby** [comment]
目前 2.0.0-alpha.1 已经支持在文章页面直接进行评论。 https://github.com/halo-dev/halo/releases/tag/v2.0.0-alpha.1

/close
