### ISSUE TITLE
删除对应post时,可以将其单独关联的tag(标签)删除

### ISSUE THREAD

**Issue by chenlip** [halo-dev/halo#2203]
### Your current Halo version

V1.5.2

### Describe this feature

每次批量删除post时, 发现该post的对应的标签并没有删除, 产生很多tag的冗余数据

**Comment by JohnNiang** [comment]
目前标签（tag）是单独管理的。且一个标签可能对应多个文章，所以对于文章的级联删除标签的做法可能不太合适。

但是是可以出一个删除孤儿（Orphan）标签的功能。

/kind improvement
/priority awaiting-more-evidence

**Comment by ruibaby** [comment]
我觉得可以在标签管理加一个清理无用标签的功能，目前可以完全在前端实现这个功能。

**Comment by ruibaby** [comment]
我将尝试在前端提供清理无用标签的功能。
