### ISSUE TITLE
实现菜单与系统内置模块的链接关联

### ISSUE THREAD

**Issue by cetr** [halo-dev/halo#2205]
### 检查清单

- [x] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

1.5.3

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker

### 发生了什么？

后台已设置固定链接路径后缀，独立页面管理页和菜单的从系统预设链接添加菜单的地址没有同步

![image](https://user-images.githubusercontent.com/49756728/177045272-63daf902-6260-48e0-9ff6-e92c6b0486bd.png)
![image](https://user-images.githubusercontent.com/49756728/177045306-1d4d5d93-0895-4037-b811-d896ac16e013.png)

**Comment by ruibaby** [comment]
/kind feature
/milestone 2.0

会在 2.0 考虑菜单与内置模块链接的关联。

**Comment by ruibaby** [comment]
目前菜单已经支持文章、自定义页面、分类、标签的关联。
