### ISSUE TITLE
附件“Markdown 格式”图片无法被编辑器解析

### ISSUE THREAD

**Issue by hd2y** [halo-dev/halo#221]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

**BUG：**
复制的“Markdown 格式”文本，如果图片链接存在特殊字符，例如空格等，无法正常被编辑器解析。

**修改建议：**
建议将“Markdown 格式”内容中链接部分进行 URI 转义。

**Comment by ruibaby** [comment]
@hd2y 嗯 感谢你的建议，确实有这个问题

**Comment by ruibaby** [comment]
已修复。https://github.com/halo-dev/halo-admin/commit/11b9e2c119150f06d50ca28d542cbe9b6565feab
