### ISSUE TITLE
建议加入Markdown的文件的导入导出

### ISSUE THREAD

**Issue by Mr-Jies** [halo-dev/halo#2210]
### Describe this feature

建议加入Markdown的文件的导入导出，这样可以用于本地的文件备份，有利于用户在系统出问题的情况下也能观看文件内容

**Comment by wxyShine** [comment]
![](https://www.helloimg.com/images/2022/07/05/Z2QFzX.png)

**Comment by wxyShine** [comment]
> ### Your current Halo version
> _No response_
> 
> ### Describe this feature
> 建议加入Markdown的文件的导入导出，这样可以用于本地的文件备份，有利于用户在系统出问题的情况下也能观看文件内容
> 
> ### Additional information
> _No response_
菜单> 系统 > 小工具

**Comment by JohnNiang** [comment]
/close

Please feel free to reopen this issue if you have any problems.

**Comment by yxy961112** [comment]
我的系统中没有小工具
![image](https://user-images.githubusercontent.com/49674927/223301026-b3b27ba0-7a42-4a03-916a-4cb7e494ba00.png)

**Comment by JohnNiang** [comment]
Hi @yxy961112 ，目前，该功能只在 Halo 1.x 中存在，Halo 2.x 暂时还没有这个功能。如果有兴趣的话，可以考虑用插件的方式实现一个。
