### ISSUE TITLE
开发者选项-系统变量，增加备注字段

### ISSUE THREAD

**Issue by cetr** [halo-dev/halo#2215]
### 描述一下此特性

开发者选项-系统变量，增加备注字段

**Comment by JohnNiang** [comment]
/kind feature
/area core
/milestone 2.0

Halo 1.x 我们暂时不考虑增加此功能。我们在 Halo 2.0 的设计中会考虑完善它。

**Comment by ruibaby** [comment]
现在对于 2.0 来说，这个应该已经过时了。
