### ISSUE TITLE
在非首次安装系统后访问install路径返回空白页面

### ISSUE THREAD

**Issue by cetr** [halo-dev/halo#2224]
### 你当前使用的版本

1.5.4

### 描述一下此特性

在非首次安装系统后访问install路径返回空白页面，应该改为返回404页面

**Comment by cetr** [comment]
#2225

**Comment by JohnNiang** [comment]
直接重定向至首页会不会更好呢。

**Comment by cetr** [comment]
> 直接重定向至首页会不会更好呢。

在安装完成后就用不上这个路径了，重定向到首页就给人一种这个路径有意义，我个人觉得应该让他的作用完全消失，就像访问到了一个从未存在过的资源
