### ISSUE TITLE
写文章如何录入摘要，背景图片

### ISSUE THREAD

**Issue by wuxiongwei** [halo-dev/halo#223]
写文章如何录入摘要，背景图片？
我尝试了halo和后台和halo-admin的后台，写文章时是有标题和正文（markdown）两个字段，请问post的其他字段要如何录入，比如摘要，图片（缩略图）等等。

<img width="468" alt="2222222" src="https://user-images.githubusercontent.com/4928711/60329659-6396a400-99c3-11e9-917b-9e8f08d296b5.png">
<img width="610" alt="11111111" src="https://user-images.githubusercontent.com/4928711/60329660-642f3a80-99c3-11e9-865c-c1d000a56a67.png">

**Comment by ruibaby** [comment]
@wuxiongwei 你还没有发表过吧，你点击右下角的发布按钮会有这些信息给你填写的。

**Comment by wuxiongwei** [comment]
哦，看到了，谢谢。
