### ISSUE TITLE
Halo后台编辑文章临时保存。

### ISSUE THREAD

**Issue by zyy247796143** [halo-dev/halo#2237]
### 你当前使用的版本

1.5.4

### 描述一下此特性

现在的版本貌似在后台编辑的文章的时候，不会主动临时保存。花大半个小时编辑了一大堆内容，浏览器突然崩掉啥都没了。可以的话，每隔5分钟或者几分钟，临时保存在redis里，或者内存里临时放着。浏览器崩掉的话，重新打开编辑器的时候读取缓存内容，即使内容没这么完整，也不至于这么崩溃。。

**Comment by ruibaby** [comment]
建议在编辑的时候手动 Ctrl + S（Mac：Command + S），这样保存就是暂存文章内容。

**Comment by zyy247796143** [comment]
手动Ctrl + S，是把数据直接写在数据库的吗？之前翻过数据库看了一下，貌似之前文章编辑过的历史记录也保留在里面。如果Ctrl + S保存比较多的话，数据库是不是也会堆积很多？

**Comment by ruibaby** [comment]
> 手动Ctrl + S，是把数据直接写在数据库的吗？之前翻过数据库看了一下，貌似之前文章编辑过的历史记录也保留在里面。如果Ctrl + S保存比较多的话，数据库是不是也会堆积很多？

是会写入到数据库，但是 Ctrl + S 保存只会对当前版本的**内容**进行更新，只有在手动发布的时候才会创建新的版本。

**Comment by zyy247796143** [comment]
了解。所以目前也是要有  Ctrl + S 的习惯才行。

**Comment by zyy247796143** [comment]
最近一段时间，我的浏览器不知道为啥老容易崩。所以发布的话，我都在其他地方编辑好后，再一次把markdown粘贴过去。。
