### ISSUE TITLE
尝试build时出现lombok报错

### ISSUE THREAD

**Issue by Aslower** [halo-dev/halo#224]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [ ] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [x] 请求技术支持

'''
> Configure project : 
Evaluating root project 'halo' using build file '/root/blog/halo/build.gradle'.
Creating new cache for metadata-1.1/results, path /root/.gradle/caches/transforms-1/metadata-1.1/results.bin, access org.gradle.cache.internal.DefaultCacheAccess@45032a85
Creating new cache for metadata-2.36/module-metadata, path /root/.gradle/caches/modules-2/metadata-2.36/module-metadata.bin, access org.gradle.cache.internal.DefaultCacheAccess@28c717bc
Creating new cache for metadata-2.36/module-artifacts, path /root/.gradle/caches/modules-2/metadata-2.36/module-artifacts.bin, access org.gradle.cache.internal.DefaultCacheAccess@28c717bc
Creating new cache for metadata-2.36/module-artifact, path /root/.gradle/caches/modules-2/metadata-2.36/module-artifact.bin, access org.gradle.cache.internal.DefaultCacheAccess@28c717bc

> FAILURE: Build failed with an exception.
Where:
Build file '/root/blog/halo/build.gradle' line: 3
 What went wrong:
An exception occurred applying plugin request [id: 'io.freefair.lombok', version: '3.7.5']
> Failed to apply plugin [class 'io.freefair.gradle.plugins.lombok.LombokBasePlugin']
> Could not generate a proxy class for class io.freefair.gradle.plugins.lombok.LombokExtension.

**Comment by JohnNiang** [comment]
请尝试使用 `./gradlew build` 命令构建。
