### ISSUE TITLE
数据迁移导入失败

### ISSUE THREAD

**Issue by ldt0621** [halo-dev/halo#2245]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

1.5.4

### 使用的什么数据库？

MySQL 5.7

### 使用的哪种方式部署？

Fat Jar

### 在线站点地址

47.101.212.29:80

### 发生了什么？

原先本地docker安装，转服务器，使用mysql数据库，在数据迁移，点击导入后显示 `内部服务器错误` `Internal Server Error`
![image](https://user-images.githubusercontent.com/68332968/179124104-3db58c24-0006-449d-aed5-3f266de5acef.png)
![image](https://user-images.githubusercontent.com/68332968/179124150-bba60cf9-5d59-49a3-95ce-c7ba4f3d0339.png)

**Comment by JohnNiang** [comment]
建议提供一下错误日志，方便我们排查具体是什么错误。如果可以的话，建议提供一份可复现的”导入数据“。

**Comment by ldt0621** [comment]
已经解决了，是MySQL数据库端口的问题
