### ISSUE TITLE
建议允许文章标记转载并为原作者署名

### ISSUE THREAD

**Issue by hd2y** [halo-dev/halo#225]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [x] 添加新的特性或者功能
- [ ] 请求技术支持

因为博客基本都会转载一些其他博客的文章，所以希望可以在发布文章的时候标记文章内容是否为原创。

并希望在非原创的情况下，可以编辑包括原文作者的信息以及原文链接的信息。

一方面可以为转载类文章的原作者署名，另外方便在文章列表展示的时候，体现文章类型是原创还是转载。另外后期也可以统计转载自不同作者的文章数量以及原创博文数量。

**Comment by ruibaby** [comment]
@hd2y 好的，我们会考虑的。

**Comment by ruibaby** [comment]
暂时应该不会加入该功能了，我们现在需要让 halo 更加稳定，后续再考虑其他特性。感谢你的建议。
