### ISSUE TITLE
BlogProperties.BLOG_URL 不更新

### ISSUE THREAD

**Issue by Rainsheep** [halo-dev/halo#2251]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

1.5.4

### 使用的什么数据库？

MySQL 5.7

### 使用的哪种方式部署？

Docker

### 发生了什么？

我在博客设置中更新博客地址，然后访问加密博文，发现访问的 url 为更新前的 url。
阅读代码发现 ftl 中的 blog_url 来自 initSettings 方法 中 
properties.put(BlogProperties.BLOG_URL, StringUtils.isBlank(installParam.getUrl()) ? optionService.getBlogBaseUrl() : installParam.getUrl());

重启容器后正常，猜测更新博客地址的时候， 内存中的 blog_url 忘记更新了。

**Comment by ruibaby** [comment]
/triage needs-information

没有复现该问题，建议先使用 IP 的形式测试一下，排除 Nginx 等代理的缓存问题。

**Comment by Rainsheep** [comment]
无法复现 close, thanks
