### ISSUE TITLE
文章编辑器会自动在图片后面加换行标签

### ISSUE THREAD

**Issue by manction** [halo-dev/halo#2252]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

1.5.4

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Fat Jar

### 在线站点地址

https://www.manction.com

### 发生了什么？

编辑器中，图片和文字明明没有换行，可是最终发布，代码中会自动有 br 换行，导致无法调整文章样式。

![e2936a55e0f5f32d448964802567854](https://user-images.githubusercontent.com/9378928/179247777-0fd8f730-bd3a-4e5f-8f8c-71bde1e4db3e.png)

![a0c91effdf085114cd39e954fa3951d](https://user-images.githubusercontent.com/9378928/179247802-81da6a79-a54c-4ab7-b4b5-addca5ce78af.png)

![0dc9d6a6728a5818a67af18d5f6acb9](https://user-images.githubusercontent.com/9378928/179247830-21a4b089-36cd-472c-b535-fdef65ccf856.png)

### 附加信息

月光海岸，用心创造快乐！
https://www.manction.com

**Comment by ruibaby** [comment]
/remove-kind bug
/kind support

这属于 Markdown 渲染的行为，建议在检查主题的样式。
