### ISSUE TITLE
后台日志页面，代码块没有渲染

### ISSUE THREAD

**Issue by cetr** [halo-dev/halo#2253]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [x] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

1.5.4

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker

### 发生了什么？

后台日志管理页面，第一次进页面没打开过编辑器时，不能渲染代码块

未渲染时：

![image](https://user-images.githubusercontent.com/49756728/179324394-d73a4594-7175-4cd4-8778-0f33654b38bf.png)

编辑器里的内容：

![image](https://user-images.githubusercontent.com/49756728/179324638-35b906eb-180a-489d-b23d-c43935dbf62b.png)

点开过一次编辑器后渲染完时：

![image](https://user-images.githubusercontent.com/49756728/179324509-dae71555-035d-421a-a642-65284082cefe.png)

**Comment by ruibaby** [comment]
日志本身是不支持代码块高亮渲染的，打开编辑器之后可能因为编辑器的高亮插件影响到了列表的代码块渲染。

/kind improvement
/milestone 1.6.x

**Comment by wxyShine** [comment]
> 日志本身是不支持代码块高亮渲染的，打开编辑器之后可能因为编辑器的高亮插件影响到了列表的代码块渲染。
> 
> /kind improvement /milestone 1.6.x

有啥修改思路没，我看看了代码  没找到啥原因。

**Comment by ruibaby** [comment]
目前 2.0 的 Moments 插件已经支持代码高亮，1.x 不再进行功能修改，所以 close。

https://github.com/halo-sigs/plugin-moments

/close
