### ISSUE TITLE
Nginx 请求头配置导致的 admin 页面重定向错误

### ISSUE THREAD

**Issue by viticis** [halo-dev/halo#2254]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

1.4.16

### 使用的什么数据库？

MySQL 5.7

### 使用的哪种方式部署？

Docker

### 背景
nginx 与 halo 在 docker 的同一网桥中，并且 nginx 配置为：
```
add_header       X-Served-By $host;
proxy_set_header Host $host;
proxy_set_header X-Forwarded-Scheme $scheme;
proxy_set_header X-Forwarded-Proto  $scheme;
proxy_set_header X-Forwarded-Host   $host;
proxy_set_header X-Forwarded-Port   $port;
proxy_set_header X-Forwarded-For    $remote_addr;
proxy_set_header X-Real-IP          $remote_addr;
proxy_pass       $forward_scheme://$server:$port$request_uri;
```
其中，`$server` 配置为 halo 的容器名字，`$port` 配置为 halo 应用及容器对外暴露的端口号8090。

安装完成后，访问 `example.com` 没问题，但登录后台时候，`example.com/admin` 会跳转到 `example.com:8090/admin/index.html`。
多了个端口号`8090`，导致访问失败，但访问其他任何地址均无此问题。
根据后续排查，发现是 nginx 中带有 `proxy_set_header X-Forwarded-Port   $port;`，去掉后可以解决该问题。

但在 #909 中，有部分用户由于使用非80端口则需要加上该配置。

### 解决
综上，于是去排查代码，定位到该问题是由于访问后台管理时的重定向导致。

```java
@GetMapping("${halo.admin-path:admin}")
public void admin(HttpServletResponse response) throws IOException {
    String adminIndexRedirectUri =
            HaloUtils.ensureBoth(haloProperties.getAdminPath(), HaloUtils.URL_SEPARATOR)
                + INDEX_REDIRECT_URI;
    response.sendRedirect(adminIndexRedirectUri);
}
``` 
此处重定向中，仅重定向至目录，所以重定向到的域名默认为当前请求中的域名。
但在使用反向代理时候，halo 能获取到的域名是由网关（在上文中为 nginx 的配置决定的），导致没有带入端口号或者带入错误的端口号，重定向到了错误的地址。
为减少用户在 nginx 配置上的心智负担和错误成本，建议可以在重定向时候，获取当前博客的配置域名进行完整域名的重定向。
~~稍后我会提交PR，以解决此问题。~~

**Comment by ruibaby** [comment]
> 建议可以在重定向时候，获取当前博客的配置域名进行完整域名的重定向。稍后我会提交PR，以解决此问题。

但需要注意的是，如果使用者配置的域名无法访问（比如 https 证书失效），使用者想通过 IP:端口/admin 进入后台的话，这个时候可能也无法正常跳转到后台。必须直接访问 IP:端口/admin/index.html 才可以。

**Comment by viticis** [comment]
> > 建议可以在重定向时候，获取当前博客的配置域名进行完整域名的重定向。稍后我会提交PR，以解决此问题。
> 
> 但需要注意的是，如果使用者配置的域名无法访问（比如 https 证书失效），使用者想通过 IP:端口/admin 进入后台的话，这个时候可能也无法正常跳转到后台。必须直接访问 IP:端口/admin/index.html 才可以。

是我考虑不周了😂，既然如此就不修改代码了，该 issue 可以关闭留待后人有类似问题时候能搜索到吧。

**Comment by viticis** [comment]
不过我又想到一个问题，为什么不直接返回页面，而是用重定向呢？

```java
@GetMapping("${halo.admin-path:admin}")
public String admin(HttpServletResponse response) throws IOException {
    String adminIndexRedirectUri =
            HaloUtils.ensureBoth(haloProperties.getAdminPath(), HaloUtils.URL_SEPARATOR)
                + INDEX_REDIRECT_URI;
        // response.sendRedirect(adminIndexRedirectUri);
    return adminIndexRedirectUri;
}
```

**Comment by ruibaby** [comment]
> 不过我又想到一个问题，为什么不直接返回页面，而是用重定向呢？

因为目前的方法是通过静态资源代理的方式代理到 admin 的构建资源目录。不是模板渲染，SpringMVC 的 Controller 返回 String 类型的数据应该是需要对应一个模板文件。

**Comment by ruibaby** [comment]
@viticis 不过也欢迎大家讨论一个更加好的方案。

**Comment by viticis** [comment]
> > 不过我又想到一个问题，为什么不直接返回页面，而是用重定向呢？
> 
> 因为目前的方法是通过静态资源代理的方式代理到 admin 的构建资源目录，不是模板渲染。SpringMVC 的 Controller 返回 String 类型的数据应该是需要对应一个模板文件。

我改成如上代码后是可以正常访问的，路径是 `localhost:8090/admin#install`，有时间我再具体测试下有没有问题，理论来说模板文件也是html🤣

**Comment by robinoneway** [comment]
@ruibaby  请问一下，我在内网使用IP:8090访问前端页面和后台都没问题，当我用花生壳做内网穿透，使用域名可以访问到前端页面，但是访问admin后台，就提示“该网页无法正常运作，xxx.com未发送任何数据”，不知道是花生壳的问题，还是我配置有问题？
