### ISSUE TITLE
建议增强模糊搜索功能

### ISSUE THREAD

**Issue by hash070** [halo-dev/halo#2256]
### 你当前使用的版本

1.5.3

### 描述一下此特性

在最新的Halo博客中，不论是前台还是后台搜索，只要有一个字母的大小写对不上就无法返回相应的结果。
例如我有一篇文章名称为`Typora激活`
那么如果我在右上角的搜索框中填写并搜索关键字`typora`，将不会得到相关的结果，因为第一个字母t的大小写对不上
![image](https://user-images.githubusercontent.com/62081013/179347607-32ba01b6-812d-45df-ab39-1f456d58ed8b.png)
除非将搜索关键词替换为`Typora`才能搜索到相关结果
![image](https://user-images.githubusercontent.com/62081013/179347634-fd57677e-13a8-4d03-a451-c6938ed2738e.png)
后台的文章管理界面也是如此，体验不是很好，因此希望改进搜索功能。

**Comment by ruibaby** [comment]
/triage duplicate https://github.com/halo-dev/halo/issues/2218

我们将在 2.0 的时候提供全文搜索的插件。目前 SQL 模糊查询并不能太好地解决搜索问题。

<img width="591" alt="image" src="https://user-images.githubusercontent.com/21301288/179356394-2f89a834-e727-4ebb-9096-f12a2b8f0a07.png">
