### ISSUE TITLE
可否自定义文章Markdown编辑器

### ISSUE THREAD

**Issue by ldt0621** [halo-dev/halo#2258]
### 你当前使用的版本

1.5.4

### 描述一下此特性

> 现在的文章编辑器很简单，能否自定义编辑成隔壁 `Typecho` 里Joe主题自带的那种编辑器？

![编辑器](https://cdn.jsdelivr.net/gh/HaoOuBa/BlogStatic/usr/uploads/2021/04/2867183119.png)
![编辑器](https://cdn.jsdelivr.net/gh/HaoOuBa/BlogStatic/usr/uploads/2021/04/842014622.png)

> 真的超爱这个编辑器，让写文章变的特别方便，不用记代码
> 希望官方能出个类似功能的编辑器，或者让主题可以自定义

**Comment by ruibaby** [comment]
Halo 本身并不打算支持这样的非标准 Markdown 语法，个人认为这属于在扰乱 Markdown 的语法规范，会让 Markdown 越来越割裂。这种需求建议使用富文本编辑器实现。我们也会在 2.0 提供插件扩展功能，届时你可以接入你想支持的任何编辑器。

**Comment by ldt0621** [comment]
赞同支持markdown标准化，期待2.0大版本能早日到来

发自我的iPhone

**Comment by mcsfsoft** [comment]
附议: 我觉得用命令写md文档是件很浪漫的事,多了一堆附加的操作是在抛弃md的特性

**Comment by ruibaby** [comment]
目前 Halo 2.1.0-rc.1 已经支持集成外部的编辑器，应该可以满足此需求，请参考：

- https://github.com/halo-dev/halo/releases/tag/v2.1.0-rc.1
- https://github.com/halo-dev/console/pull/781

/close
