### ISSUE TITLE
markdown编辑器，复制图片，自动上传

### ISSUE THREAD

**Issue by LuanLouis** [halo-dev/halo#226]
目前halo需要先上传图片，然后再编辑mardown文章，这个在操作上不是很方便，是否可以在编辑器  ctrl+v的时候，将剪切板的图片自动上传，并返回插入的markdown语句？
当前的主流markdown都支持，期待此功能。
当前只实现了客户端的预览，期待改成服务端!
![image](https://user-images.githubusercontent.com/7589877/60422768-4a8a2f00-9c1f-11e9-9820-5f38a72d4bc6.png)

**Comment by ruibaby** [comment]
@LuanLouis 嗯，已在计划内。

**Comment by zzcv** [comment]
推荐个神器，**[iPic](https://toolinbox.net/iPic/)** ，

**Comment by ruibaby** [comment]
已解决 https://github.com/halo-dev/halo-admin/commit/f0192844f2adb5a2d37de8dcee42f31c93d85951
