### ISSUE TITLE
可否增加批量为文章添加标签以及目录归档的功能

### ISSUE THREAD

**Issue by psc1453** [halo-dev/halo#2263]
### 你当前使用的版本

1.5.4

### 描述一下此特性

在后台管理页面的“所有文章”选项卡下，目前的版本可以多选文章然后在批量操作的下拉菜单内设置文章的发布状态。
在我近期整理博客时，新增了几个标签和目录，想把现有的一些博客放进新目录并打上新标签，可是只能一篇一篇文章的单独设置，因此希望能够添加多选文章后，在批量操作的下拉菜单中或是其他某个位置添加批量为文章添加标签以及目录归档的功能。
非常感谢。

**Comment by ruibaby** [comment]
非常好的建议，但目前我们可能没有精力在 1.x 来支持这个功能。现在我们的主要精力放在 [2.0](https://github.com/halo-dev/halo/tree/next) 的开发上，做文章相关功能的时候会考虑这个功能的。不过，1.x 也欢迎大家参与贡献。

**Comment by ruibaby** [comment]
[2.17](https://github.com/halo-dev/halo/releases/tag/v2.17.0) 已经支持批量为文章设置标签、分类等。

/close
