### ISSUE TITLE
配置了作为服务运行后，开机时服务启动失败，服务器就一直阻塞在开机流程了了，开不了机

### ISSUE THREAD

**Issue by TU-RUI** [halo-dev/halo#2265]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

服务器启动不了，看不到

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Fat Jar

### 在线站点地址

eriri.cn:8009，但是现在服务器挂了，打不开

### 发生了什么？

我按照指南，配置了服务器启动时会启动halo服务，(systemctl enable halo)，配置后一直能正常开机启动。
今天上服务器上调整了一些配置，手动启动服务报错了，尝试几次后都无法启动，于是我就重启了一下服务器，结果现在服务器重启的时候重启halo服务，也一直起不来，导致服务器开不了机了，ssh命令都连不上我的服务器(我只能远程登录服务器)，现在无法登录，服务器完全处于宕机状态。

问题是：由于配置了halo自动启动后，如果服务启动时halo自动启动失败，会导致服务器后续的ssh服务也启动不了，ssh服务启动不了导致无法登录服务器，也无法修复这个问题，因此完全不知道改怎么办了

**Comment by ruibaby** [comment]
本质上这并不属于 Halo 的问题，建议看看或者问服务商客服，能否通过其他方式登录（比如 VNC）服务器。

/kind support
/triage needs-information

**Comment by JohnNiang** [comment]
如果按照我们的文档配置 Halo Service，是不会影响 sshd 服务启动的。即使启动失败。

建议监测一下服务器运行状态，是不是资源不足导致无法启动。

**Comment by TU-RUI** [comment]
确实不是halo定时任务的问题，再次物理重启服务器后，halo服务虽然开启启动失败，但是ssh服务能启动，这个问题已经修复，谢谢
