### ISSUE TITLE
halo 后台文章编辑区界面容易出现错位

### ISSUE THREAD

**Issue by zyy247796143** [halo-dev/halo#2268]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

1.5.4

### 使用的什么数据库？

MySQL 5.7

### 使用的哪种方式部署？

Docker

### 发生了什么？

halo 后台文章编辑区界面容易出现错位。
比如我下面提供的视频所示，我编辑一大堆内容到80行还没进行大量删除的时候，鼠标滚轮上下滑动界面是不会出现问题的。到后面进行大量删除行后，鼠标滚轮再上下滑动界面就会出现整个界面一起上下滑动。

### 附加信息

https://user-images.githubusercontent.com/23225911/180156249-bb74d8c2-5289-416d-bda4-c4152b181df5.mp4

**Comment by cetr** [comment]
左边是markdown文本，右边是html，肯定会错开啊

**Comment by zyy247796143** [comment]
我意思是上下滚轮，会带着整个整个窗口一起滑动，不止是编辑区

**Comment by cetr** [comment]
明白了，不过之前这问题不是修复了吗，怎么又出现了 @ruibaby

**Comment by zyy247796143** [comment]
1.6版本都来了，这个bug还有机会修复吗:sob:

**Comment by JohnNiang** [comment]
> 1.6版本都来了，这个问题还在，还有机会修复吗😭

还是有机会的，毕竟我们还会持续维护 1.6 一段时间。主要看社区是否有人有兴趣修复这个问题。

**Comment by AirboZH** [comment]
我注意到页面高度的变长是从视频中15秒向上复制开始的
我这面使用console `master分支` https://github.com/halo-dev/console/commit/acfc86f9f3c52a137ab4ae0cff87f3eaf07914ef 以及 halo `master分支` https://github.com/halo-dev/halo/commit/d43190d74c869fb941de112b276968736976d4a0 无
法复现该问题

https://github.com/halo-dev/halo/assets/50261327/dd41caf8-f129-48c2-ad00-dfce397d14c1

**Comment by zyy247796143** [comment]
> 我注意到页面高度的变长是从视频中15秒向上复制开始的 我这面使用console `master分支` [halo-dev/console@acfc86f](https://github.com/halo-dev/console/commit/acfc86f9f3c52a137ab4ae0cff87f3eaf07914ef) 以及 halo `master分支` [d43190d](https://github.com/halo-dev/halo/commit/d43190d74c869fb941de112b276968736976d4a0) 无法复现该问题
> 
>  QQ.20230516235025.mp4

1.6.1版本的halo，这个问题在edge浏览器很容易出现，edge浏览器很多个版本都有这个问题。chrome浏览器貌似没怎么会出现这个问题。。

**Comment by AirboZH** [comment]
> 1.6.1版本的halo，这个问题在edge浏览器很容易出现，edge浏览器很多个版本都有这个问题。chrome浏览器貌似没怎么会出现这个问题。。  

我又尝试使用发布 1.6.1版本的两次commit https://github.com/halo-dev/halo/commit/72f6a08987073f5120256fa55d11dbe9dea64062 和 https://github.com/halo-dev/console/commit/90f18c6a71d121efa2d3d5360ce705a496dd9fb5
以及浏览器`Microsoft Edge 版本 113.0.1774.42 (正式版本) (64 位)` & `Google Chrome 版本 113.0.5672.127（正式版本） （64 位）`

还是无法复现，如果方便的话您可以再尝试一下

https://github.com/halo-dev/halo/assets/50261327/cf091cab-44f7-4bdb-adff-24ad1b7b6a12
