### ISSUE TITLE
附件库路径

### ISSUE THREAD

**Issue by 565785929** [halo-dev/halo#227]
附件库的路径是带host的，写好的文章直接使用的话， 如果之后更改博客地址。就无法加载了。

**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [ ] [Halo 使用文档](https://halo.run/docs)
- [ ] [Halo 论坛](https://bbs.halo.run)
- [ ] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [ ] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [X] 添加新的特性或者功能
- [ ] 请求技术支持

**Comment by ruibaby** [comment]
@565785929 那你用绝对路径就好了。

**Comment by 565785929** [comment]
建议把附件库里的链接地址改一下。host地址去掉。

**Comment by JohnNiang** [comment]
> 建议把附件库里的链接地址改一下。host地址去掉。
有道理啊。

**Comment by 565785929** [comment]
> > 建议把附件库里的链接地址改一下。host地址去掉。
> 
> 有道理啊。但是可能会引发其他的问题。

例如什么问题？
在解析md中链接时主动添加上用户手动设置”博客地址“的部分。
或者像主题一样使用静态资源？

**Comment by JohnNiang** [comment]
@565785929 嗯嗯，我们尝试想办法来解决 md 的链接解析。

**Comment by watermelon1135** [comment]
发布文章的时候，如果修改了文章路径，显示发布成功，当时在访问的时候会报404

**Comment by JohnNiang** [comment]
@watermelon1135 修改了路径之后，访问之前需要刷新文章列表才行。

**Comment by watermelon1135** [comment]
> @watermelon1135 修改了路径之后，访问之前需要刷新文章列表才行。

尝试过了没有用，  之前地址是 xxx.com/archives/文章标题  改成 xxx.com/archives/**aaaa**/文章标题 之后就提示404

**Comment by JohnNiang** [comment]
@watermelon1135 路径中不能添加 / ，如果添加了，后台是无法匹配这个 URL 的，也就找不到这个路径，最后就是 404。后面我们考虑转义自己设定的路径。
