### ISSUE TITLE
菜单列表管理

### ISSUE THREAD

**Issue by cetr** [halo-dev/halo#2275]
### 你当前使用的版本

1.5.4

### 描述一下此特性

目前菜单的管理方案在列表内容过多时，增加内容时不太方便，新建一个链接后需要一直挪到最后面，我有两个建议

1. 点列表什么位置，就在什么位置新建一条链接，而不是新建后生成在顶部
2. 改成思维导图的一样，更方便可视化管理，方便管理内容较多的场景

需求原因是我使用目前的菜单功能做的网址导航，需要管理很多链接，一旦需要新增，就要挪动半天
预览地址：https://hao.coor.top

**Comment by ruibaby** [comment]
/kind improvement

PR welcome :)
