### ISSUE TITLE
halo 后台markdown编辑区滚动，及目录定位问题

### ISSUE THREAD

**Issue by zyy247796143** [halo-dev/halo#2277]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

1.5.4

### 使用的什么数据库？

MySQL 5.7

### 使用的哪种方式部署？

Docker

### 发生了什么？

有两个小问题，不知道是不是bug。
1. 在编辑文章的左边源码编辑区里面进行上下滚动，右边的html预览区可以跟着上下滚动。但在右边的html预览区里上下滚动，左边源码区就不可以跟着上下滚动。。
2. 编辑文章的 导航目录 里点击目录，右边的 html 预览区可以滚动页面定位里面的内容，但是左边源码区就不可以跟着定位。

具体看上传视频，我在CSDN试了上面两个操作，没有出现这个现象。

https://user-images.githubusercontent.com/23225911/181177657-01623f26-e41a-4b52-966c-a210fda066e3.mp4

**Comment by ruibaby** [comment]
不是 bug，当前没有实现编辑区域随着预览区域的滚动，属于可以优化的地方。

不过 PR welcome :)

/kind improvement
/area admin
