### ISSUE TITLE
您好，关于文章的路径是可以自己主动设置的。

### ISSUE THREAD

**Issue by 565785929** [halo-dev/halo#228]
您好，关于文章的路径是可以自己主动设置的。

没看代码，创建文章测试了一下，
如果是纯中文的，路径就是时间戳；
如果是纯英文的，路径就是标题；
如果是中英混合，路径就是标题中的英文；
这样会带来一个问题，有时路径会已存在。不如默认都是时间戳。有特殊需求再主动设置。更方便不是吗？

_Originally posted by @JohnNiang in https://github.com/halo-dev/halo/issues/203#issuecomment-502439123_

**Comment by JohnNiang** [comment]
针对文章路径-问题，我们已经更改为了默认使用时间戳来作为文章标题。

敬请期待 `v1.0.3`。

**Comment by ruibaby** [comment]
@565785929 同时会支持在文章列表中修改文章数据，不用在文章编辑页面修改，会更方便。
