### ISSUE TITLE
附件中无法删除云端已经失效的附件

### ISSUE THREAD

**Issue by 129duckflew** [halo-dev/halo#2283]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

1.5.3

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Fat Jar

### 在线站点地址

https://duckflew.cn

### 发生了什么？

我使用又拍云做对象存储服务，当我使用其他途径删除又拍云中与Halo相关的附件时， 在Halo中仍然会加载失效的附件，并且无法删除

### 附加信息

![image](https://user-images.githubusercontent.com/62204325/181665196-e51e829b-03ed-485f-84ca-d711760a45c8.png)

**Comment by ruibaby** [comment]
云存储的文件并不是实时同步，而是在 Halo 这边上传之后保存了图片的信息。至于删除失败可能是因为在删除云存储资源的时候因为文件已经被删除，所以抛出异常。

/kind bug
/good-first-issue

**Comment by JustinLiang522** [comment]
@129duckflew 我尝试先在又拍云中删除文件，然后再从Halo删除该关联附件，虽然Halo提示删除失败，但该文件随后会从附件列表里消失，Halo也无法再加载该文件。请问你是用的什么途径删除关联附件的？

**Comment by 129duckflew** [comment]
> @129duckflew 我尝试先在又拍云中删除文件，然后再从Halo删除该关联附件，虽然Halo提示删除失败，但该文件随后会从附件列表里消失，Halo也无法再加载该文件。请问你是用的什么途径删除关联附件的？

我是通过halo admin端上传到又拍云，然后在又拍云中删除了文件，回到admin端  对应的附件已经无法删除了

**Comment by JustinLiang522** [comment]
@129duckflew 谢谢你的回复，刚刚我又试了一下，在删除单个文件时，对应文件会在halo消失，但是同时删除多个文件时因为在删除第一个文件时抛出了异常，其它文件就不能正常删除。删除抛出异常的代码可以解决该问题，但是不知道这样修改的话是否合理？

**Comment by JustinLiang522** [comment]
还有一种方法是根据status_code的值处理，如果返回status_code值为404则提示附件不存在或已经被删除。我想尝试用这种方案来修这个bug，请问是否可行？@ruibaby

**Comment by ruibaby** [comment]
@JustinLiang522 可以，但是需要考虑一下批量删除的情况。另外，可能也得处理一下其他云存储。
