### ISSUE TITLE
希望能提供写作界面直接拖入文件并且上传的功能

### ISSUE THREAD

**Issue by 129duckflew** [halo-dev/halo#2284]
### 你当前使用的版本

1.5.3

### 描述一下此特性

希望能提供写作界面直接拖入文件并且上传到云端(服务器或者云存储服务器) 的功能,类似上传图片一样，不过可能需要考虑到文件太大中途由于网络问题上传失败这些等等因素，也许需要做一些文件大小的限制

**Comment by ruibaby** [comment]
PR welcome :)

https://github.com/halo-dev/editor

/kind feature
