### ISSUE TITLE
文章编辑页面出现 sql 关键字时无法提交

### ISSUE THREAD

**Issue by gzwrrr** [halo-dev/halo#2286]
### Checklist

- [X] The issue has been searched in [GitHub Issues](https://github.com/halo-dev/halo/issues)
- [X] The issue has been searched in the [bbs.halo.run](https://bbs.halo.run/)
- [X] Already consulted [document](https://docs.halo.run/)

### What is version of Halo has the issue?

1.5.4

### What database are you using?

H2

### What is your deployment method?

Docker

### What happened?

当我在编写与性能优化相关的文章时，加入 SQL 关键字，如：limit、group by、join，结果无法保存，提示服务器错误，打开查看网络请求发现报 403 Forbidden。  

请问这是为了防止 SQL 注入吗? 如果是，能否提供关闭的选项？

### Relevant log output

```shell
无
```

### Additional information

无

**Comment by ruibaby** [comment]
看看是不是同一个问题：https://github.com/halo-dev/halo/issues/2178

/kind support
/triage duplicate

**Comment by gzwrrr** [comment]
是同一个问题，谢谢大佬！
