### ISSUE TITLE
是否考虑多用户特性，即允许新用户注册与使用

### ISSUE THREAD

**Issue by xiuyuanjun** [halo-dev/halo#2289]
### 你当前使用的版本

1.5.4

### 描述一下此特性

允许新用户注册

**Comment by guqing** [comment]
1.x不会支持，2.0版本会考虑，可以关注一下 [milestone 2.0](https://github.com/halo-dev/halo/milestone/19)

**Comment by ruibaby** [comment]
/triage duplicate https://github.com/halo-dev/halo/issues/1251

**Comment by JohnNiang** [comment]
/triage duplicate
Refer to #1251

**Comment by ruibaby** [comment]
我将关闭此 issue，后续请跟踪 https://github.com/halo-dev/halo/issues/1251
