### ISSUE TITLE
主题安装功能

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#2291]
### 你当前使用的版本

next

### 描述一下此特性

/kind feature
/milestone 2.0

支持主题安装功能。

1. 本地上传安装
2. 远程在线安装（支持 Git、ZIP 等）

安装主题的操作可能需要在上传之后读取资源文件（theme.yaml），在前端进行 apply 操作。

**Comment by ruibaby** [comment]
已经在 https://github.com/halo-dev/halo-admin/pull/594 和 https://github.com/halo-dev/halo/pull/2302 中实现。

/close

**Comment by JohnNiang** [comment]
目前仅完成了本地文件上传的方式进行主题安装吧，远程链接下载方式安装还未实现。

**Comment by ruibaby** [comment]
> 目前仅完成了本地文件上传的方式进行主题安装吧，远程链接下载方式安装还未实现。

确实，先 reopen。远程下载的方式需要讨论一下

/reopen
