### ISSUE TITLE
导航菜单管理功能

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#2295]
### 你当前使用的版本

next

### 描述一下此特性

/kind feature
/milestone 2.0
/area core
/area admin

2.0 重构导航菜单管理功能，相较于 1.x：

1. 支持与 Core 中各个模块（文章、文章分类、自定义页面等）的资源关联，如果被关联资源如果有更新，那么最终菜单项会随着更改。
2. 模型分为 Menu 和 MenuItem，其中 Menu 相当于 1.x 中的 team 字段。

/assign
/assign @JohnNiang

**Comment by qq547176052** [comment]
后台菜单管理功能 可以安排上不

**Comment by ruibaby** [comment]
> 后台菜单管理功能 可以安排上不

如果你指的是后台侧边菜单的管理功能，那么我们是没有计划支持的。后台菜单可通过插件添加，也可以通过用户组动态配置。

**Comment by ruibaby** [comment]
当前已经在 https://github.com/halo-dev/halo/pull/2303 和 https://github.com/halo-dev/halo-admin/pull/595 中完成普通链接类型的菜单管理。等待 https://github.com/halo-dev/halo/pull/2326 和 https://github.com/halo-dev/halo-admin/pull/599 完成之后将对关联类型的菜单做适配。

**Comment by ruibaby** [comment]
/close 

see https://github.com/halo-dev/halo/pull/2303 https://github.com/halo-dev/halo/pull/2380 https://github.com/halo-dev/halo/pull/2395 https://github.com/halo-dev/halo-admin/pull/595 https://github.com/halo-dev/halo-admin/pull/604 https://github.com/halo-dev/halo-admin/pull/608
