### ISSUE TITLE
name 为 system 的 configMap 在系统重启之后会被重置

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#2304]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

next

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Fat Jar

### 在线站点地址

None

### 发生了什么？

重现步骤：

1. 启动 Halo 之后更新 name 为 system 的 configMap 资源。
    ```curl
    curl -X 'PUT' \
      'http://localhost:8090/api/v1alpha1/configmaps/system' \
      -H 'accept: */*' \
      -H 'Content-Type: */*' \
      -d '{
      "data": {
        "theme": "{\"active\":\"theme-astro-starter\"}"
      },
      "apiVersion": "v1alpha1",
      "kind": "ConfigMap",
      "metadata": {
        "name": "system",
        "version": 59
      }
    }'
    ```

2. 重启 Halo，查询 system 的 configMap

    ```json
    {
      "data": {
        "theme": "{\"active\":\"default\"}"
      },
      "apiVersion": "v1alpha1",
      "kind": "ConfigMap",
      "metadata": {
        "name": "system",
        "version": 61
      }
    }
    ```

/kind improvement
/milestone 2.0
/area core
/assign @guqing

**Comment by JohnNiang** [comment]
系统默认配置建议不做任何变更，即使变更了也会被重置。建议系统默认配置 ConfigMap name 设置为 system-default。如果用户需要修改系统配置，则新创建一个名为 system 的 ConfigMap 来存储用户自定义配置。系统最终配置为用户自定义配置 Merge Patch 系统默认配置的结果。

**Comment by JohnNiang** [comment]
目前可优先考虑采用 https://github.com/java-json-tools/json-patch 作为 JSON Patch 的库，用于合并 ConfigMap 的值，理由如下：

1. 它默认集成了 Jackson JSON
2. 它同时支持 JSON Patch 和 JSON Merge Patch

**Comment by ruibaby** [comment]
/close 

https://github.com/halo-dev/halo/pull/2415
