### ISSUE TITLE
优化：简化 Reconciler 注册逻辑

### ISSUE THREAD

**Issue by JohnNiang** [halo-dev/halo#2305]
### 你当前使用的版本

2.0.0-SNAPSHOT

### 描述一下此特性

目前我们每写一个 Reconciler，都需要在 ExtensionControllerConfiguration 中注册对应的 Controller Bean，这样会导致该配置文件随 Reconciler 的增加不断增长。

https://github.com/halo-dev/halo/blob/ebecef89c651fa1e7fddc0d0852cfc477f0c4d8a/src/main/java/run/halo/app/config/ExtensionConfiguration.java#L63-L102

我的方案：
- 通过 `@Component` 注解将需要运行的 Reconciler 标记为 Bean
- 在 ExtensionControllerConfiguration 获取所有的 Reconciler 并创建对应的 Controller
- 运行所有的 Controller

### 附加信息

/area core
/kind improvement
/milestone 2.0
/priority important-longterm

**Comment by JohnNiang** [comment]
/assign

当前优化需尽快实现，保证允许插件顺利注册 reconciler 到 core 中。

**Comment by guqing** [comment]
需要考虑插件停止和卸载时能够有方法可以停用和清理插件注册进来的 Controller

**Comment by JohnNiang** [comment]
> 需要考虑插件停止和卸载时能够有方法可以停用和清理插件注册进来的 Controller

PR https://github.com/halo-dev/halo/pull/2737 提供了 reconciler 生命周期管理的可能，接下来需要插件相关开发者来适配管理插件中的 reconciler。
