### ISSUE TITLE
新增主题卸载功能

### ISSUE THREAD

**Issue by guqing** [halo-dev/halo#2306]
### Your current Halo version

2.0.0

### Describe this feature

新增主题卸载功能
卸载时：
1. 清理主题相关自定义模型资源
2. 删除主题目录

/milestone 2.0
/kind feature
/assign

**Comment by ruibaby** [comment]
/close

see https://github.com/halo-dev/halo/pull/2315 https://github.com/halo-dev/halo-admin/pull/596
