### ISSUE TITLE
点击进入文章，评论者的头像会访问https://cn.gravatar.com/avatar/426c255c998f48826b93e8e83203a889/?s=256&d=undefined,然后跳转http://i1.wp.com/，进而导致https网站提示不安全

### ISSUE THREAD

**Issue by liufangpu** [halo-dev/halo#231]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [ ] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

**Comment by liufangpu** [comment]
https://www.guqing.xyz这个是实例网站

**Comment by ruibaby** [comment]
好的，下个版本修复。

**Comment by ruibaby** [comment]
已修复，等待 1.0.3 发布。

**Comment by zhangzhaoyu** [comment]
@ruibaby 该功能在切换为其他模板的时候依然存在，请问要如何修改模板？

**Comment by saxingz** [comment]
这个问题还有，你看一下自己的网站哈。https://ryanc.cc/archives/halo-docker

**Comment by zhangzhaoyu** [comment]
@saxingz 在管理端升级一下模板。
