### ISSUE TITLE
提供 Reconciler 淘汰策略机制

### ISSUE THREAD

**Issue by guqing** [halo-dev/halo#2310]
### Your current Halo version

2.0.0

### Describe this feature

目前 Reconciler 注册到 DefaultDelayQueue 中，执行失败会重新入 queue，当一个 Reconciler 执行几次都失败后会延长下次执行的时间，如果当失败的 Reconciler 多起来会导致积压，或许可以提供淘汰策略来减轻内存压力，比如失败一定次数就从 queue 中淘汰之类

### Additional information

/kind improvement
/milestone 2.0
/area core
/assign @JohnNiang

**Comment by JohnNiang** [comment]
如果直接淘汰失败的 Request，可能无法完成”最终一致性“的特性。

比如未来我们可能会提供定时任务的功能，Request 可能会长时间堆积在 Controller 的 Queue 中，知道时间到了才会触发。

**Comment by guqing** [comment]
有道理

**Comment by JohnNiang** [comment]
为保证“最终一致性”，不会提供 Reconciler 的 request 的淘汰策略。

不过需要注意的是：在 Reconciler 的 reconcile 逻辑中尽量不做耗时的操作，否则可能会影响队列中其他元素的 reconciliation。

当前 Issue 即将被关闭。如果有任何问题可随时重新打开。

/close
