### ISSUE TITLE
数据从H2迁移到Mysql后，使用Mysql作为数据库，重新打开博客文章数据都不见了

### ISSUE THREAD

**Issue by 1456858781** [halo-dev/halo#2312]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

1.5.4

### 使用的什么数据库？

MySQL 5.7

### 使用的哪种方式部署？

Docker

### 发生了什么？

就是我想把H2数据库转为Mysql数据库，作为后续数据存储，但是重新部署后，一些配置数据保存了，但是文章数据不见了，但是数据库里面存在。

**Comment by ruibaby** [comment]
请提供完整复现步骤，根据当前的信息无法判断出是哪里出了问题。

/kind support
/triage needs-information

**Comment by 1456858781** [comment]
找到问题了，数据迁移时，posts表遗漏了






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "halo-dev/halo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月4日(星期四) 晚上6:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [halo-dev/halo] 数据从H2迁移到Mysql后，使用Mysql作为数据库，重新打开博客文章数据都不见了 (Issue #2312)





 
请提供完整复现步骤，根据当前的信息无法判断出是哪里出了问题。
 
/kind support
 /triage needs-information
