### ISSUE TITLE
图片能支持分类不？

### ISSUE THREAD

**Issue by rookiehander** [halo-dev/halo#2314]
### 描述一下此特性

图片支持分类，不仅仅根据后缀来分。
比如：我的图片和平时的博客分开。

**Comment by ruibaby** [comment]
你说的应该是附件。可以跟踪一下这个 issue：https://github.com/halo-dev/halo/issues/1712

/kind feature
/triage duplicate

**Comment by ruibaby** [comment]
如果没有后续动态，我将关闭此 issue。

/close
