### ISSUE TITLE
存在远程命令执行漏洞

### ISSUE THREAD

**Issue by FyHoly123** [halo-dev/halo#2318]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

只测试了一个版本

### 使用的什么数据库？

Other

### 使用的哪种方式部署？

Docker

### 发生了什么？

在Halo后台登录后可通过某接口在固定目录上传任意文件，之后通过某接口将文件移动到系统其他位置。之例如覆盖Linux crontab用户文件获取服务器权限。

**Comment by ruibaby** [comment]
感谢反馈，但根据你提供的信息（`只测试了一个版本`、`某接口`），我们无法得知这个漏洞的具体版本和具体接口。如果是为了防止提前披露漏洞信息，请根据我们的 [SECURITY.md](https://github.com/halo-dev/halo/blob/master/SECURITY.md) 说明提交。

**Comment by FyHoly123** [comment]
相关漏洞信息已发送邮件，期待halo官方的尽快回复

**Comment by ruibaby** [comment]
如果没有后续动态，我将关闭此 issue。

> PS: @FyHoly123 邮件中提到的接口此前已在 https://github.com/halo-dev/halo/releases/tag/v1.5.4 中修复。

/close
