### ISSUE TITLE
bug提交

### ISSUE THREAD

**Issue by 565785929** [halo-dev/halo#232]
回收站的文章。在选择标签显示的时候（tags/xx）。会展示出来。但是不能打开。

**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [ ] [Halo 使用文档](https://halo.run/docs)
- [ ] [Halo 论坛](https://bbs.halo.run)
- [ ] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [ ] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

**Comment by ruibaby** [comment]
@565785929 好的，感谢反馈。

**Comment by ruibaby** [comment]
1.0.3 已修复
