### ISSUE TITLE
halo迁移后的数据咨询

### ISSUE THREAD

**Issue by ChunelFeng** [halo-dev/halo#2323]
### Your current Halo version

docker latest版本

### Describe this feature

您好，我通过 迁移工具，把原先的内容导出成 *.json文件，然后在另外一台ecs上开启新的 halo docker 。直接导入 *.json 文件后，工作正常。

```
docker run --rm -it -d --name myHalo -p 80:8090  -v ~/.halo:/home/chunel/file/.halo halohub/halo:latest
```

但是有个问题，我没有在我本地指定的  /home/chunel/file/.halo 位置，没有生成对应的 .halo文件。

不确定这样下去，如果一周后docker异常重启，是否会保留这周更新的内容？

![image](https://user-images.githubusercontent.com/37905059/184539404-5f2d24cc-fd8a-47b3-9872-3f61e744a68b.png)

**Comment by JohnNiang** [comment]
默认情况下，在 Halo 容器中，Halo 的工作空间目录应该设置为：`/root/.halo`。从你上面的指令来看应该是没有自定义工作空间。

```bash
docker run --rm -it -d --name myHalo -p 80:8090  -v ~/.halo:/home/chunel/file/.halo halohub/halo:latest
```

上面这条命令没有正确映射工作空间目录，如果容器卷被删除后，数据将丢失。不过可以试试下面的命令：

```diff
- docker run --rm -it -d --name myHalo -p 80:8090  -v ~/.halo:/home/chunel/file/.halo halohub/halo:latest
+ docker run --rm -it -d --name myHalo -p 80:8090  -v ~/.halo:/root/.halo halohub/halo:latest
```

可参考：
- https://docs.halo.run/getting-started/install/docker

**Comment by ChunelFeng** [comment]
已经将本地位置修改为 /root/.halo，并且确认对应位置有该文件的。

这样的话，重启docker，最近的改动就不会丢失了是吧

**Comment by JohnNiang** [comment]
只要你保证本地文件夹：`~/.halo` 中有最新的文件内容，即使删除数据卷后，数据也不会丢。

**Comment by ChunelFeng** [comment]
好的哈，感谢。thx
