### ISSUE TITLE
菜单嵌套问题

### ISSUE THREAD

**Issue by 565785929** [halo-dev/halo#233]
这个的意思是菜单嵌套了吧。但实际并没有，是并列的。
![image](https://user-images.githubusercontent.com/24430884/60728322-9c5dec80-9f72-11e9-8d4b-b1c3474be9fa.png)

**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [ ] [Halo 使用文档](https://halo.run/docs)
- [ ] [Halo 论坛](https://bbs.halo.run)
- [ ] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [ ] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

**Comment by 565785929** [comment]
抱歉这么晚提俩bug，会不会挨打😆

**Comment by DarrenGu** [comment]
我们会尽快检查修复  感谢你反馈

**Comment by ruibaby** [comment]
@565785929 这个要看主题支持的哦，暂时还没有主题支持多级菜单，会尽快有的。

**Comment by 565785929** [comment]
![image](https://user-images.githubusercontent.com/24430884/60732679-3cb90e80-9f7d-11e9-9634-c64925573c83.png)
主题的logo没了，怎么排查啊，还有主题如果想重装，怎么操作，删掉重新下载吗？主题文件和附件在服务器什么地方啊，路径是？

**Comment by 565785929** [comment]
还有首页的文章，突然变成一个了。但是归档，还是好的。怎么排查错误。。头大。
![image](https://user-images.githubusercontent.com/24430884/60732806-94f01080-9f7d-11e9-894b-7da94dde3adb.png)

**Comment by ruibaby** [comment]
@565785929 后台有设置logo的地方呀

**Comment by ruibaby** [comment]
@565785929 这个是已知bug，自动生成摘要的问题，你可以手动给文章设置摘要，就行了。

**Comment by 565785929** [comment]
这个是，默认主题 的 默认logo，切换主题的时候突然就404了。

发自我的 iPhone

**Comment by ruibaby** [comment]
@565785929 你在博客设置里面主动设置一下呢？

**Comment by 565785929** [comment]
改不了，默认主题的作者应该知道我在说什么。。。

发自我的 iPhone

**Comment by ruibaby** [comment]
![Snipaste_2019-07-05_23-50-24](https://user-images.githubusercontent.com/21301288/60733630-fb762e00-9f7f-11e9-86ee-c2d826cad81b.jpg)

你确定这里改了没用？

**Comment by 565785929** [comment]
重点是，切换了主题后，logo404了。

**Comment by ruibaby** [comment]
@565785929 哪个主题？

**Comment by chy9002** [comment]
我在菜单嵌套上遇到个问题，如果设置了嵌套，然后删除了上级菜单，下级菜单也会消失，而且无法在设置已经添加过的下级菜单

**Comment by ruibaby** [comment]
> 我在菜单嵌套上遇到个问题，如果设置了嵌套，然后删除了上级菜单，下级菜单也会消失，而且无法在设置已经添加过的下级菜单

好的，我排查下。

**Comment by ruibaby** [comment]
@chy9002 这个问题已修复。
