### ISSUE TITLE
对象存储内的文件在控制台删除后，halo后台已在腾讯云删除附件不会同步删除，且无法手动删除

### ISSUE THREAD

**Issue by daifiyum** [halo-dev/halo#2338]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

任意版本

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

在halo后台采用了腾讯云的对象存储作为附件的存储位置，但如果在腾讯的控制面板上删除了这个存储桶或桶内图片，那么在halo后台的附件管理里还会有对象存储的文件，只不过都无法显示或打开，这些已在腾讯控制面板删除的文件在halo附件管理内无法删除

**Comment by ruibaby** [comment]
/kind bug

https://github.com/halo-dev/halo/issues/2283

无法删除的问题应该在 https://github.com/halo-dev/halo/pull/2317 中处理了七牛云和又拍云，可以提供一下删除失败的日志吗？

**Comment by JohnNiang** [comment]
可参考 
- https://github.com/halo-dev/halo/issues/2283
- https://github.com/halo-dev/halo/pull/2317
- https://cloud.tencent.com/document/product/436/7730 

修复此问题。

**Comment by ruibaby** [comment]
1.x 已经停止维护，我将关闭此 issue。

详情可看：https://www.halo.run/archives/halo-1.x-eol

/close
