### ISSUE TITLE
可以导出所有的文章数据吗

### ISSUE THREAD

**Issue by liufangpu** [halo-dev/halo#234]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [ ] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [ ] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [x] 添加新的特性或者功能
- [x] 请求技术支持

**Comment by liufangpu** [comment]
比如我要换一台服务器，我如何把之前的数据拷贝出来

**Comment by ruibaby** [comment]
@liufangpu 直接备份用户目录下的 .halo 文件夹到新服务器就好了。

**Comment by ruibaby** [comment]
https://bbs.halo.run/d/111

**Comment by liufangpu** [comment]
> https://bbs.halo.run/d/111

谢谢
