### ISSUE TITLE
新增主题端业务数据查询模型

### ISSUE THREAD

**Issue by guqing** [halo-dev/halo#2346]
### Your current Halo version

2.0.0

### Describe this feature

新增主题端业务数据查询支持，例如：
```html
<p th:each="post : ${postFinder.list(1, 10)}">
  <span th:text="${post.name}">Onions</span>
</p>
```
https://github.com/halo-dev/rfcs/tree/main/theme#%E4%B8%BB%E9%A2%98%E6%B8%B2%E6%9F%93

### Additional information

/area core
/milestone 2.0
/kind feature
/assign

**Comment by ruibaby** [comment]
似乎还缺少 Menu 模型的查询模型。

**Comment by ruibaby** [comment]
/close 

see https://github.com/halo-dev/halo/pull/2347
