### ISSUE TITLE
文章预览功能

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#2349]
### 你当前使用的版本

next

### 描述一下此特性

提供生成文章预览链接的功能。

/area core
/area admin
/milestone 2.0
/kind feature

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/21301288/186605705-8a772e6f-5e39-44ae-892b-a26e965c8e07.png">
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/21301288/186605766-c4a9fefa-00cd-45de-8f36-368bd3935a11.png">

**Comment by A602247590** [comment]
你好，可以在编辑文章的窗口添加一个段后距和行间距的功能吗？

**Comment by A602247590** [comment]
还有字体大小，格式等的修改功能，Markdown适合会代码的人用，博客写文就是需要简单。感谢。

**Comment by ruibaby** [comment]
@A602247590 建议单独提交 issue。

**Comment by JohnNiang** [comment]
如果能够支持在不创建“文章”的前提下也能预览就好了。

我的思路：先将文章内容（HTML）保存在 LocalStorage 里面（例如：post-1: xyz...HTML...），然后再生成一个临时链接（例如：`localhost:8090/_preview/archives/post-1`），后端可以识别该路由并返回空的文章内容，同时在 header 中添加一段可以读取 LocalStorage 的文章内容并设置到对应位置的 JS 代码。

**Comment by guqing** [comment]
> 如果能够支持在不创建“文章”的前提下也能预览就好了。
> 
> 我的思路：先将文章内容（HTML）保存在 LocalStorage 里面（例如：post-1: xyz...HTML...），然后再生成一个临时链接（例如：`localhost:8090/_preview/archives/post-1`），后端可以识别该路由并返回空的文章内容，同时在 header 中添加一段可以读取 LocalStorage 的文章内容并设置到对应位置的 JS 代码。

是否需要考虑分享文章预览链接的场景

**Comment by JohnNiang** [comment]
> > 如果能够支持在不创建“文章”的前提下也能预览就好了。
> > 我的思路：先将文章内容（HTML）保存在 LocalStorage 里面（例如：post-1: xyz...HTML...），然后再生成一个临时链接（例如：`localhost:8090/_preview/archives/post-1`），后端可以识别该路由并返回空的文章内容，同时在 header 中添加一段可以读取 LocalStorage 的文章内容并设置到对应位置的 JS 代码。
> 
> 是否需要考虑分享文章预览链接的场景

IMO，这应该是另外的一个场景，实现方式也有所不同。如果生成的预览链接需要分享，则需要创建好文章，并且创建好内容的 snapshot。如果只是在写文章的时候预览，可以不需要创建好文章。

**Comment by guqing** [comment]
> IMO，这应该是另外的一个场景，实现方式也有所不同。如果生成的预览链接需要分享，则需要创建好文章，并且创建好内容的 snapshot。如果只是在写文章的时候预览，可以不需要创建好文章。

sounds good

**Comment by ruibaby** [comment]
> 如果能够支持在不创建“文章”的前提下也能预览就好了。
> 
> 我的思路：先将文章内容（HTML）保存在 LocalStorage 里面（例如：post-1: xyz...HTML...），然后再生成一个临时链接（例如：`localhost:8090/_preview/archives/post-1`），后端可以识别该路由并返回空的文章内容，同时在 header 中添加一段可以读取 LocalStorage 的文章内容并设置到对应位置的 JS 代码。

这种方式有两个问题：

1. 通过 JS 代码如何得知需要将内容插入到什么地方。
2. 这只是针对内容，如果需要预览最终文章页面的效果怎么办，比如封面图、标题等。

**Comment by guqing** [comment]
> > 如果能够支持在不创建“文章”的前提下也能预览就好了。
> > 我的思路：先将文章内容（HTML）保存在 LocalStorage 里面（例如：post-1: xyz...HTML...），然后再生成一个临时链接（例如：`localhost:8090/_preview/archives/post-1`），后端可以识别该路由并返回空的文章内容，同时在 header 中添加一段可以读取 LocalStorage 的文章内容并设置到对应位置的 JS 代码。
> 
> 这种方式有两个问题：
> 
> 1. 通过 JS 代码如何得知需要将内容插入到什么地方。
> 2. 这只是针对内容，如果需要预览最终文章页面的效果怎么办，比如封面图、标题等。

可以通过先定义一个例如 /preview/archives/{post-name} 的路由，然后将参数带到这个路由上比如文章信息，然后在此路由将参数作为视图数据填充再转发到文章详情页视图来解决数据问题

**Comment by ruibaby** [comment]
> 可以通过先定义一个例如 /preview/archives/{post-name} 的路由，然后将参数带到这个路由上比如文章信息，然后在此路由将参数作为视图数据填充再转发到文章详情页视图来解决数据问题

既然都提供 `/preview/archives/{post-name}` 路由了，是否可以为它设置一个权限或者说已登录的用户才能访问，然后直接根据 postName 查询到最新的数据（内容需要查询 head content）。1.x 为什么需要生成一个 OTT 来访问预览文章是因为当时使用了 JWT 来做登录鉴权，目前使用 Session 似乎也不在有这个问题。
