### ISSUE TITLE
QQ邮箱SMTP的账号为QQ号码而非QQ邮箱地址，前端表单邮箱格式验证无法通过

### ISSUE THREAD

**Issue by itlubber** [halo-dev/halo#2358]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

halo 1.5.4 首页/系统/博客设置 页面中的 SMTP服务 发信设置 表单中的 邮箱账号

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

smtp邮箱账号无法设置为qq号码，前端表单验证为邮箱格式，无法通过格式验证提交表单

**Comment by JohnNiang** [comment]
你可以试试 `xyz@qq.com`。而不是 `xyz`。

参考：
- https://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=334
