### ISSUE TITLE
主题模板文件支持动态路由规则

### ISSUE THREAD

**Issue by guqing** [halo-dev/halo#2364]
### Your current Halo version

2.0.0

### Describe this feature

允许通过配置修改主题模板路由规则
例如，允许文章详情模板 post.html 路由为以下几种访问规则
/archives/{slug}
/archives/{name}
/?p={name}
/{year}/{month}/{slug}
/{year}/{slug}
/{year}/{month}/{day}/{slug}

### Additional information

/kind feature
/milestone 2.0
/area core
/assign

**Comment by ruibaby** [comment]
/close 

see https://github.com/halo-dev/halo/pull/2365
