### ISSUE TITLE
无法设置日志页面每页显示条数

### ISSUE THREAD

**Issue by JustinLiang522** [halo-dev/halo#2366]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

latest master

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Fat Jar

### 在线站点地址

http://jiayuanliang.xyz

### 发生了什么？

页面->所有页面->独立页面->日志页面->管理->页面设置 
![image](https://user-images.githubusercontent.com/73240868/187438791-a40c073a-9ff6-4955-a596-35998bd7ed79.png)
修改日志每页显示条数，修改后没有效果。

**Comment by ruibaby** [comment]
/triage duplicate

https://github.com/halo-dev/halo/issues/2339

**Comment by JustinLiang522** [comment]
抱歉可能是我没有描述清楚。我在issue里指的是，在设置显示了条数并保存后没有效果，也就是修改成每页5条后，显示还是按照每页10条显示，并没有改成每页5条。[#2339](https://github.com/halo-dev/halo/issues/2339) 里提到的是设置时没有回显的这个功能，两者应该不能算同一个问题。

**Comment by JustinLiang522** [comment]
我发现导致问题的原因是，代码中通过`options.journals_page_size`对页面大小赋值，然而`options`是数组类型，所以无法这样进行赋值。我想到了两种修改方法：
第一种是将`options.journals_page_size`替换成`options.find(item=>item.key=='journals_page_size').value`；
第二种是将获取`options`的方法由`listAll()`替换成`listAllWithMapView()`
不知道那种方法更合适，或者说是否还有其它更好的方法？

**Comment by ruibaby** [comment]
@JustinLiang522 可以考虑使用 `apiClient.option.listAsMapViewByKeys` 方法，仅获取 `journals_page_size` 和 `journals_title` 设置项的值。这个方法返回的是一个对象，可以直接和表单绑定。

PR welcome~

**Comment by ruibaby** [comment]
> 可以考虑使用 apiClient.option.listAsMapViewByKeys 方法

可以参考：https://github.com/halo-dev/halo-admin/blob/bbd810d308358acab12c15b6209a71caa4f13345/src/store/modules/option.js#L33
