### ISSUE TITLE
无法通过 CategoryFinder 获取分类数据

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#2367]
### 你当前使用的版本

next

### 描述一下此特性

<img width="1277" alt="image" src="https://user-images.githubusercontent.com/21301288/187573360-9c3a9108-69ec-4be7-afc4-2bf68b771123.png">

模板语法：

```html
<pre th:text="${categoryFinder.list(1,10)}"></pre>
<pre th:text="${categoryFinder.listAll()}"></pre>
```

结果：

```
ListResult(page=1, size=10, total=2, items=[CategoryVo(children=[]), CategoryVo(children=[])])
[CategoryVo(children=[]), CategoryVo(children=[])]
```

<img width="906" alt="image" src="https://user-images.githubusercontent.com/21301288/187573391-a0d3ac57-9d14-4628-92af-37a900bf82eb.png">

/kind bug
/milestone 2.0

**Comment by guqing** [comment]
你图片所示都是一级分类吗
应该并不是没有数据，而是CategoryVo没有toString方法所以显示不出属性来，可以取值试一下

**Comment by guqing** [comment]
我添加了 `toString` 注解后显示都正常，之前没加和你图示一样，应该不是功能问题
<img width="1698" alt="image" src="https://user-images.githubusercontent.com/38999863/187576425-674bc8df-87df-40fa-a95a-59544b46174a.png">
可先在 run.halo.app.theme.finders.vo 包下对所有 vo 添加 `@ToString` 注解 继承了 父类的则添加 `@ToString(callSuper = true)` 然后继续推进

**Comment by ruibaby** [comment]
> 你图片所示都是一级分类吗
应该并不是没有数据，而是CategoryVo没有toString方法所以显示不出属性来，可以取值试一下

直接遍历确实没有问题。

/remove-kind bug
