### ISSUE TITLE
博客地址配置失效

### ISSUE THREAD

**Issue by fyhkimyon** [halo-dev/halo#2369]
### 检查清单

- [x] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

1.4.13

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

我在使用nginx配置路径转发时将 `http://xxx.com/halo/` 映射到 `http://xxx.xxx.xxx.xxx:8090` 出现了问题
前端使用的是相对路径，除主页外其它资源都访问不到了，于是我尝试在设置中配置路由前缀
在 **系统->博客设置->常规设置->博客地址** 中，我设置了地址为 `http://xxx.com/halo/` 
同时在 **系统->博客设置->常规设置->博客地址->切换到高级选项->固定链接** 中，已经显示所有路由前缀已更改为 `http://xxx.com/halo/xxx/`
但经过我的测试，**系统->博客设置->常规设置->博客地址** 的设置对顶部的导航栏是无效的，如：
期望访问的url为 `http://xxx.com/halo/archives/`
实际访问的url为 `http://xxx.com/archives/`
对于themes和upload文件夹下的静态资源也是无法加载的（不过这个可以单独映射这两个文件夹解决）

**Comment by ruibaby** [comment]
目前不支持域名子目录的形式进行代理，推荐使用子域名。

/kind support

**Comment by ruibaby** [comment]
请参考：https://docs.halo.run/getting-started/prepare#web-%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%8F%AF%E9%80%89

/close
