### ISSUE TITLE
优化后台的数据交互相关体验

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#2370]
### 你当前使用的版本

next

### 描述一下此特性

/kind improvement
/milestone 2.0
/assign
/area admin

目前各个页面的列表数据是没有加载状态的，仅仅只有空状态。期望得到以下优化：

1. 提供体验良好数据加载状态。
2. 优化 CLS 问题。
3. 异常处理。

**Comment by JohnNiang** [comment]
About 3, please see https://github.com/halo-dev/halo/issues/2732 for more.
