### ISSUE TITLE
admin 上传插件建议提供同时生成压缩图的功能 ， 否则多图情况下体验不好

### ISSUE THREAD

**Issue by Elvin-zl** [halo-dev/halo#2372]
### 你当前使用的版本

1.4.5

### 描述一下此特性

上传插件建议提供同时生成压缩图的功能

**Comment by ruibaby** [comment]
你指的是我们 2.0 版本吗？1.x 我们目前是有压缩图的。

**Comment by Elvin-zl** [comment]
嗯 我看到服务器上是有缩略图的,但是有一些问题

目前的使用场景是我平时写技术文章还好，但写游记之类的多图 （40+张图片）文章,对图片的要求是不大幅降低图片质量的情况下对体积进行压缩

遇到的问题是 : 缩略图不能直接使用在文章中，因为缩略图的质量太差了
 
我目前解决方案是 : 自己写了个静态页面,先把图片批量压缩好,再进行上传(地址 : http://image-compress.buukle.top/image-compress/index.html)
这样一张图片压缩完后从4m到300K,质量影响不大,加了cdn后,基本满足手机用户查看的需求 (文章地址 : https://i.buukle.top/archives/gubeishuizhen)

目标效果是 : 在halo后台设置中有一个或几个配置参数,能让用户配置直接上传图片时的压缩参数,是否压缩,
这样用户直接上传图片的时候自动回填到markdown编辑栏的地址就能直接使用了

**Comment by Elvin-zl** [comment]
本来想down下前端代码自己引入一下compress , 又担心和主版本差太远,不好跟着进行升级 ,寻思能否在官方支持一下这种需求

**Comment by ruibaby** [comment]
1.x 暂时不打算支持这样的功能了。可以关注一下 2.0，我们会考虑是否提供图片上传的前置处理器，这种需求就可以交给插件来实现了。目前建议参考 https://halo.run/archives/halo-and-webp.html 搭建一个 webp 服务器，可以得到非常好的效果。

**Comment by Elvin-zl** [comment]
> 1.x 暂时不打算支持这样的功能了。可以关注一下 2.0，我们会考虑是否提供图片上传的前置处理器，这种需求就可以交给插件来实现了。目前建议参考 https://halo.run/archives/halo-and-webp.html 搭建一个 webp 服务器，可以得到非常好的效果。

嗯 希望2.0支持类似功能 能够让用户 在创作的时候用起来更方便 ~
另外ps下 填了问卷 申请加vx没有通过  想加入组织参与一些contribute ,辛苦相关人员查看下申请哈  希望一起参与halo的发展 为halo更好用做贡献~
