### ISSUE TITLE
主题模板代码片段注入

### ISSUE THREAD

**Issue by guqing** [halo-dev/halo#2376]
### Your current Halo version

2.0.0

### Describe this feature

主题模板渲染时
- 需要注入全局head
- 内容页 head
- 全局 footer
- 文章页需要注入文章关键词等seo meta

### Additional information

/area core
/milestone 2.0
/kind feature
/assign

**Comment by ruibaby** [comment]
`全局 footer` 可能不能通过这种方式注入，得主题作者自行调用，因为我们不知道具体放在哪个位置。一般我们对 head 标签部分进行注入即可。

**Comment by guqing** [comment]
> 

是的，需要一个自定义标签，比如<halo:footer/>

**Comment by ruibaby** [comment]
/close 

see https://github.com/halo-dev/halo/pull/2377
