### ISSUE TITLE
新增自定义页面功能

### ISSUE THREAD

**Issue by guqing** [halo-dev/halo#2379]
### Your current Halo version

2.0.0

### Describe this feature

自定义页面同 1.x 相仿，但需要将访问路由根据 slug 挂载到根即没有路由前缀
自定义页面与文章不同，它没有分类和标签

### Additional information

/kind feature
/milestone 2.0
/area core
/assign

**Comment by ruibaby** [comment]
/close 

see https://github.com/halo-dev/halo/pull/2381
see https://github.com/halo-dev/halo-admin/pull/606
