### ISSUE TITLE
服务器启动halo报错  ： 无权限使用java

### ISSUE THREAD

**Issue by ZHJIAB** [halo-dev/halo#238]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [ ] [Halo 使用文档](https://halo.run/docs)
- [ ] [Halo 论坛](https://bbs.halo.run)
- [ ] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [x] 请求技术支持
 想请问修改完配置文件halo.service（已经修改了java路径和jar包路径之后），在启动halo服务的时候报错： Failed at step EXEC spawning /usr/java: Permission denied
无权限使用java怎么解决问题啊？

**Comment by ruibaby** [comment]
请问你服务器环境是？
