### ISSUE TITLE
后台文章的访问量数据异常

### ISSUE THREAD

**Issue by xiaoqin-xjc** [halo-dev/halo#2386]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

1.0

### 使用的什么数据库？

Other

### 使用的哪种方式部署？

Fat Jar

### 在线站点地址

http://blog.xjc.vin

### 发生了什么？

后台文章的访问量数据异常，奇怪的9999+

### 附加信息

![67270f01e61b5764f1f9d19d2150a36](https://user-images.githubusercontent.com/83749831/188778671-aeeb2b50-df17-4151-b9b5-f7060b082db2.jpg)

**Comment by ruibaby** [comment]
/kind support

这应该是有人恶意访问文章，目前文章访问量的统计策略没有去重机制，访问一次就计算一次。建议根据 Nginx 的 access log 检查是否有 IP 在恶意访问文章。
