### ISSUE TITLE
希望 Halo 支持附件缩略图功能

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#2387]
### 你当前使用的版本

next

### 描述一下此特性

目前 2.0 的附件如果是图片的话，仅有原图的访问地址（status.permalink），但目前会带来的问题是在后台展示或者选择图片的时候列表所加载的图片是原图，如果达到一定数量较大的原图，会导致页面卡顿。期望改进如下：

1. 默认本地存储策略支持生成缩略图。
2. `status.permalink` 改为 `status.urls`，其中 urls 包含一系列不同格式的图片。必须包含 `raw` 和 `thumbnail`。
3. 外部存储策略如阿里云 OSS 支持设置 thumbnail 的图片处理规则名称，那么这时候 OSS 的 `status.urls.thumbnail` 就形如 `
https://foo.oss-cn-shenzhen.aliyuncs.com/bar.jpg?x-oss-process=style/thumbnail`，其中 `x-oss-process=style/thumbnail` 即规则名称。

未来可考虑支持：

1. 除了 thumbnail 必须设置之外，外部存储可设置多种图片处理规则，参考阿里云 OSS 的图片处理规则，可在需要使用的时候选择规则。
2. 附件选择组件在选择图片的时候可以选择 `status.urls` 中的任意一个。
3. 提供插件扩展点，插件可在上传的时候对图片做处理，生成类似 `status.urls.webp` 等图片类型。

**Comment by wan92hen** [comment]
听起来这个改动会有兼容性问题呢

**Comment by guqing** [comment]
> 听起来这个改动会有兼容性问题呢

稍后会有 RFC 被提上来在进行讨论，issue 的描述只是功能参考和需求

**Comment by ruibaby** [comment]
@guqing 需不需要写一下文章内容中的图片处理，在 [#缩略图使用](#缩略图使用) 中只提到了主题开发的时候可以使用 srcset，但文章内容在主题中是无法干预的。

**Comment by ruibaby** [comment]
另外，这个可以直接提到 https://github.com/halo-dev/rfcs

**Comment by guqing** [comment]
> @guqing 需不需要写一下文章内容中的图片处理，在 [#缩略图使用](#%E7%BC%A9%E7%95%A5%E5%9B%BE%E4%BD%BF%E7%94%A8) 中只提到了主题开发的时候可以使用 srcset，但文章内容在主题中是无法干预的。

已经在最新的内容中补充：https://github.com/halo-dev/rfcs/pull/24
