### ISSUE TITLE
.

### ISSUE THREAD

**Issue by LemonMan888** [halo-dev/halo#2388]

**Comment by LemonMan888** [comment]
同时，部分版本在评论&文章编辑处，预览情况下都存在js代码执行的情况
![image](https://user-images.githubusercontent.com/97210674/188804885-e8091101-b54a-422b-ae6c-6f03f83a3079.png)
![image](https://user-images.githubusercontent.com/97210674/188805008-4fa93f25-58b6-4c64-9dc2-422ef3f873e7.png)

**Comment by ruibaby** [comment]
> 同时，部分版本在评论&文章编辑处，预览情况下都存在js代码执行的情况

目前文章编辑不限制使用代码注入。另外，提交安全报告请参考 https://github.com/halo-dev/halo/blob/master/SECURITY.md
