### ISSUE TITLE
在主题端提供主题设置和部分系统设置的变量

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#2389]
### 你当前使用的版本

next

### 描述一下此特性

提供当前激活主题的 configMap 变量和部分系统设置等变量。期望提供以下变量：

1. theme：当前主题的信息，theme.yaml
2. config：当前主题的设置项。
3. 部分系统变量，不能直接提供 system 的 configMap。我们需要按需提供，比如：`{site_title}` `{site_url}` `{site_subtitle}`

**Comment by guqing** [comment]
/close
see https://github.com/halo-dev/halo/pull/2406
