### ISSUE TITLE
主题更新失败

### ISSUE THREAD

**Issue by NGLSL** [halo-dev/halo#239]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [ ] [Halo 论坛](https://bbs.halo.run)
- [ ] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [ ] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [x] 请求技术支持

![image](https://user-images.githubusercontent.com/40338580/61133054-3c75c180-a4ef-11e9-84c5-51b91140c779.png)

**Comment by NGLSL** [comment]
我尝试过，将后台下载下来并将templates中的admin删除并替换，但版本中显示的依旧是1.0.2

**Comment by ruibaby** [comment]
@NGLSL 你是不是用了全站cdn？

**Comment by NGLSL** [comment]
> @NGLSL 你是不是用了全站cdn？

是的，我刷新了之后就好啦
