### ISSUE TITLE
主题模板渲染时默认填充必要数据

### ISSUE THREAD

**Issue by guqing** [halo-dev/halo#2390]
### Your current Halo version

2.0.0

### Describe this feature

主题端渲染时默认填充必要数据，如针对 tag.html 填充路由对应 tag 的 详情数据，tags.html 填充文章列表数据及获取上下页的url

### Additional information

/kind feature
/area core
/milestone 2.0
/assign

**Comment by ruibaby** [comment]
/close 

see https://github.com/halo-dev/halo/pull/2393
