### ISSUE TITLE
偶发文章重复或文章分类与标签重复

### ISSUE THREAD

**Issue by hd2y** [halo-dev/halo#240]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

文章重复的情况，查询数据发现除ID外所有字段内容相同，当重复时管理后台不能删除重复的文章，只能在数据库中删除。

标签和分类重复的文章，更新文章后，标签和分类仍然重复。

希望修复该问题，或者在问题发生后允许对这些数据进行调整。例如允许删除重复的文章；在更新文章时对标签和分类信息进行排重。

**Comment by ruibaby** [comment]
@hd2y 好的，我们测试之后将会修复

**Comment by ruibaby** [comment]
标签和分类重复的问题已修复，至于文章重复的问题还需要测试一下。

**Comment by ruibaby** [comment]
@hd2y 你能否帮忙测试一下最新的 [beta](https://github.com/halo-dev/halo/releases) 版 是否还有该问题呢？我们暂时没有复现出来重复文章的情况。

**Comment by hd2y** [comment]
> @hd2y 你能否帮忙测试一下最新的 [beta](https://github.com/halo-dev/halo/releases) 版 是否还有该问题呢？我们暂时没有复现出来重复文章的情况。

我也只重现过一次，不知道后端我们怎么设计的，有没有做过压测，会不会存在并发。如果一篇内容被重复提交，我们后端的逻辑是怎么样的，后端提交这篇文章的时候，事务怎么处理？

我们有没有进行排重处理，重复文章不允许提交。而一篇在数据库中没有记录的数据，如果重复提交两次，在两个事务中提交，我们进行文章排重处理中，处理的有没有可能是脏数据，建议按照这个方向去排查一下我们的代码。

**Comment by ruibaby** [comment]
@hd2y 目前所做的限制是url必须唯一，我们会按照你的建议去排查一下，感谢！另外，如果你有时间，也欢迎一起完善。

**Comment by hd2y** [comment]
> @hd2y 你能否帮忙测试一下最新的 [beta](https://github.com/halo-dev/halo/releases) 版 是否还有该问题呢？我们暂时没有复现出来重复文章的情况。

因为我修的不是Java，可能给不到更多的帮助，如果实在排查不出来，因为触发的概率太小，我这边建议至少在ID非重复的时候，我能删除掉其中一篇文章，然后将该问题关闭。

**Comment by JohnNiang** [comment]
> > @hd2y 你能否帮忙测试一下最新的 [beta](https://github.com/halo-dev/halo/releases) 版 是否还有该问题呢？我们暂时没有复现出来重复文章的情况。
> 
> 因为我修的不是Java，可能给不到更多的帮助，如果实在排查不出来，因为触发的概率太小，我这边建议至少在ID非重复的时候，我能删除掉其中一篇文章，然后将该问题关闭。

理论上根据 id 删除文章是不存在问题的。

**Comment by ruibaby** [comment]
@JohnNiang 好的👌因为最近重构了发文章的部分，所以暂不清楚还有没有这个问题。

**Comment by JohnNiang** [comment]
问题应该存在将已经发布的文章变成为回收站，然后再删除。

**Comment by hd2y** [comment]
> @JohnNiang 好的👌因为最近重构了发文章的部分，所以暂不清楚还有没有这个问题。

我印象中旧版好像不可以，操作好像两篇文章状态都会变化，新版不知道是否有问题，可以后台添加类似数据做一个测试，如果没有问题，那就把这个问题关掉吧。🤭

**Comment by JohnNiang** [comment]
也就是说，如果文章处于发布状态，也是能够直接删除的，这里需要改造一下 [`halo-admin`](https://github.com/halo-dev/halo-admin) @ruibaby

**Comment by ruibaby** [comment]
@JohnNiang 行

**Comment by JohnNiang** [comment]
临时解决方案：

1. 编辑重复文章，修改文章的 url；
2. 回到文章列表中，将重复文章更改为回收站；
3. 删除该文章。

@hd2y
