### ISSUE TITLE
统计分类及标签下所属文章功能

### ISSUE THREAD

**Issue by guqing** [halo-dev/halo#2401]
### Your current Halo version

2.0.0

### Describe this feature

统计分类下所属文章，并更新到 category.status.posts，查询分类时带上文章数量及子分类文章数量，标签亦如是

### Additional information

/kind feature
/milestone 2.0
/area core
/assign

**Comment by ruibaby** [comment]
/close 

see https://github.com/halo-dev/halo/pull/2402
