### ISSUE TITLE
Halo 2.0 Alpha.1 发布核对清单

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#2410]
Halo 预计在 2022 年 9 月 30 日发布第一个 2.0 Alpha 版本，以下是发布前的核对清单。

## 核对清单

- [x] 从 master 分支创建 release-1.6 分支（[halo-dev/halo](https://github.com/halo-dev/halo) [halo-dev/halo-admin](https://github.com/halo-dev/halo-admin)）。
- [x] 合并 next 分支到 main 分支（[halo-dev/halo](https://github.com/halo-dev/halo) [halo-dev/halo-admin](https://github.com/halo-dev/halo-admin)）。
- [x] [halo-dev/halo-admin](https://github.com/halo-dev/halo-admin) 重命名为 `halo-dev/console`。
- [x] 更新 main 分支的 README，提醒当前分支为 2.0 开发分支。
- [ ] 更新插件和主题快速开始模板的文档。
    - [ ] https://github.com/halo-sigs/theme-starter
    - [ ] https://github.com/halo-sigs/plugin-starter
- [ ] 移动 https://github.com/halo-sigs 组织中比较重要的库（如 [theme-starter](https://github.com/halo-sigs/theme-starter) [plugin-starter](https://github.com/halo-sigs/plugin-starter)）到 https://github.com/halo-dev 组织中托管。
- [x] 完善 https://github.com/halo-sigs/awesome-halo 库，列出 2.0 支持的插件和主题。
- [x] 编写发布文案。
- [x] 编写 2.0 的文档。
- [ ] ...

**Comment by liuzhihang** [comment]
https://github.com/halo-sigs/theme-astro-starter

这个文档也需要出一下，应该可以结合 React 组件写主题。

**Comment by ruibaby** [comment]
## README

<p align="center">
    <a href="https://halo.run" target="_blank" rel="noopener noreferrer">
        <img width="100" src="https://halo.run/logo" alt="Halo logo" />
    </a>
</p>

<p align="center"><b>Halo</b> [ˈheɪloʊ]，一款现代化的开源博客/CMS系统，值得一试。</p>

<p align="center">
<a href="https://github.com/halo-dev/halo/releases"><img alt="GitHub release" src="https://img.shields.io/github/release/halo-dev/halo.svg?style=flat-square&include_prereleases" /></a>
<a href="https://github.com/halo-dev/halo/releases"><img alt="GitHub All Releases" src="https://img.shields.io/github/downloads/halo-dev/halo/total.svg?style=flat-square" /></a>
<a href="https://hub.docker.com/r/halohub/halo"><img alt="Docker pulls" src="https://img.shields.io/docker/pulls/halohub/halo?style=flat-square" /></a>
<a href="https://github.com/halo-dev/halo/commits"><img alt="GitHub last commit" src="https://img.shields.io/github/last-commit/halo-dev/halo.svg?style=flat-square" /></a>
<a href="https://github.com/halo-dev/halo/actions"><img alt="GitHub Workflow Status" src="https://img.shields.io/github/workflow/status/halo-dev/halo/Halo%20CI?style=flat-square" /></a>
<br />
<a href="https://halo.run">官网</a>
<a href="https://docs.halo.run/next">文档（2.0 Alpha）</a>
<a href="https://bbs.halo.run">社区</a>
<a href="https://gitee.com/halo-dev">Gitee</a>
<a href="https://t.me/halo_dev">Telegram 频道</a>
</p>

------------------------------

## 注意

当前分支为 Halo 2.0 的开发分支，目前 Halo 2.0 处于 Alpha 测试阶段，不建议从 1.5 直接升级，也不建议在生产环境使用。稳定版本（Halo 1.5）请查阅以下地址：

- 1.5 分支：<https://github.com/halo-dev/halo/tree/release-1.5>
- 1.6 分支：<https://github.com/halo-dev/halo/tree/release-1.6>
- 1.5 文档：<https://docs.halo.run>

## 快速开始

### Fat Jar

下载最新的 Halo 运行包：

```bash
curl -L https://github.com/halo-dev/halo/releases/download/v2.0.0-alpha.1/halo-2.0.0-alpha.1.jar --output halo-next.jar
```

其他地址：<https://docs.halo.run/next/getting-started/downloads>

```bash
java -jar halo-next.jar
```

### Docker

```bash
docker run -it -d --name halo-next -p 8090:8090 -v ~/halo-next:/root/halo-next --restart=unless-stopped halohub/halo-dev:next
```

详细部署文档请查阅：<https://docs.halo.run/next/getting-started/install/linux>

## 生态

可访问 [awesome-halo](https://github.com/halo-sigs/awesome-halo) 查看已经适用于 Halo 2.0 的主题和插件，以及适用于 Halo 1.x 的相关仓库。

## 许可证

[![license](https://img.shields.io/github/license/halo-dev/halo.svg?style=flat-square)](https://github.com/halo-dev/halo/blob/master/LICENSE)

Halo 使用 GPL-v3.0 协议开源，请遵守开源协议。

## 贡献

参考 [CONTRIBUTING](https://github.com/halo-dev/halo/blob/master/CONTRIBUTING.md)。

<a href="https://github.com/halo-dev/halo/graphs/contributors"><img src="https://opencollective.com/halo/contributors.svg?width=890&button=false" /></a>

## 状态

![Repobeats analytics](https://repobeats.axiom.co/api/embed/ad008b2151c22e7cf734d2688befaa795d593b95.svg "Repobeats analytics image")

**Comment by ruibaby** [comment]
## Console README

<p align="center">
    <a href="https://halo.run" target="_blank" rel="noopener noreferrer">
        <img width="100" src="https://halo.run/logo" alt="Halo logo" />
    </a>
</p>

> Halo 2.0 的管理端项目（原 halo-admin）

<p align="center">
<a href="https://github.com/halo-dev/console/releases"><img alt="GitHub release" src="https://img.shields.io/github/release/halo-dev/console.svg?style=flat-square" /></a>
<a href="https://github.com/halo-dev/console/blob/master/LICENSE"><img alt="GitHub" src="https://img.shields.io/github/license/halo-dev/console?style=flat-square"></a>
<a href="https://github.com/halo-dev/console/commits"><img alt="GitHub last commit" src="https://img.shields.io/github/last-commit/halo-dev/console.svg?style=flat-square"></a>
<a href="https://github.com/halo-dev/console/actions"><img alt="GitHub Workflow Status" src="https://img.shields.io/github/workflow/status/halo-dev/console/Halo%20Admin%20CI?style=flat-square"/></a>
<a href="https://gitpod.io/#https://github.com/halo-dev/console"><img alt="Gitpod ready-to-code" src="https://img.shields.io/badge/Gitpod-ready--to--code-blue?logo=gitpod&style=flat-square"/></a>
</p>

------------------------------

## 注意

当前分支为 Halo 2.0 的 Console 端开发分支，目前 Halo 2.0 处于 Alpha 测试阶段，不建议从 1.5 直接升级，也不建议在生产环境使用。Console 端稳定版本（Halo 1.5）请查阅以下地址：

- 1.5 分支：<https://github.com/halo-dev/console/tree/release-1.5>
- 1.6 分支：<https://github.com/halo-dev/console/tree/release-1.6>

> 当前仓库已经将 `halo-admin` 改为了 `console`。但对于 Halo 1.x 版本，依旧保持 halo-admin 的概念。

## 开发环境运行

```bash
# pnpm@7.0.0+
npm install -g pnpm
```

```bash
pnpm install 
```

```bash
# build packages
pnpm build:packages
```

```bash
pnpm dev
```

## 生产构建

```bash
pnpm build
```

## 状态

![Repobeats analytics](https://repobeats.axiom.co/api/embed/9ae12e8e0b9ed7df1b5364169186544d89c1c6bc.svg "Repobeats analytics image")
