### ISSUE TITLE
加密文章查阅建议

### ISSUE THREAD

**Issue by Rainsheep** [halo-dev/halo#2413]
### 你当前使用的版本

1.5.4

### 描述一下此特性

对于加密文章，目前有以下两种查阅方式。
1. 从后台管理界面进入 并输入密码后，才能查阅。
2. 拿到文章链接后，打开链接 并输入密码，才能查询。

疑问：
1. 不是很理解，为什么我的加密文章在前台搜不到，每次看都得进入后台。
2. 假设第一点是合理的，毕竟加密。   我都从后台查阅了, 那我肯定是管理员呀，为啥还需要再次输入文章密码，感觉设计很不合理。

建议如下：
1. 在前台界面能搜索到界面文章，点击 并输入密码能够查阅。
2. 从后台管理界面进入，不需要输入密码就能查阅。

**Comment by ruibaby** [comment]
/triage duplicate


https://github.com/halo-dev/halo/issues/561
https://github.com/halo-dev/halo/issues/2362#issuecomment-1242906508

**Comment by ruibaby** [comment]
当前 1.x 不打算修改这个行为。如 https://github.com/halo-dev/halo/issues/2362#issuecomment-1242906508 所说，我们 2.0 版本针对文章是否显示在访问端提供了设置，但 2.0 可能暂时不打算做加密的功能。

当前 1.x 最好的解决方案也是增加一个是否显示在文章列表的字段，而不受限于文章是否加密。 PR welcome :)
