### ISSUE TITLE
Hook支持

### ISSUE THREAD

**Issue by wangxiaoerYah** [halo-dev/halo#2416]
### Your current Halo version

1.5.4

### Describe this feature

Halo 能否支持一个入口为主题支持自定义运行hooks。

类似于hexo那种在提交时执行js，提交链接给bing或者baidu的那种功能。不用Halo支持，只要支持在添加文章或者更新文章的时候执行主题里的自定义js文件或者脚本即可。

这样可以实现很多可玩性。比如支持订阅之类的，用户输入它的邮箱，我后台每次更新或者发布文章时，hook将通过邮箱发给订阅者。等等功能。

就是我还不确定Halo是提前生成页面的还是等到有请求再生成页面的。Hooks这个功能怎么个实现也没有思路，你们一定知道😏😏

**Comment by ruibaby** [comment]
> 类似于hexo那种在提交时执行js，提交链接给bing或者baidu的那种功能。不用Halo支持，只要支持在添加文章或者更新文章的时候执行主题里的自定义js文件或者脚本即可。

目前你这个需求在博客设置内容页 head 的设置项设置对应的 JS 脚本即可。

> 我后台每次更新或者发布文章时，hook将通过邮箱发给订阅者。等等功能。

这种就是我们 2.0 需要做的了，目前我们 2.0 实现了插件机制，只需要在对应的地方设置扩展点，然后交给对应的插件实现即可。可以参考 https://github.com/halo-dev/rfcs/blob/main/plugin/pluggable-design.md#%E5%AE%9A%E4%B9%89-extension-point

/kind feature

**Comment by wangxiaoerYah** [comment]
那就很期待2.0了🥺
