### ISSUE TITLE
修改自定义 API 的 group

### ISSUE THREAD

**Issue by guqing** [halo-dev/halo#2418]
### Your current Halo version

2.0.0

### Describe this feature

- 修改管理后台使用的自定义 API 的 group 为 `api.console.halo.run`
- 面向三方应用的自定义 API 的 group 为 `api.halo.run`
- 插件的自定义 API 的 group 为 `api.plugin.halo.run`

### Additional information

/area core
/milestone 2.0
/kind improvement
/assign

**Comment by JohnNiang** [comment]
`console.api.halo.run` -> `api.console.halo.run`。

**Comment by guqing** [comment]
> `console.api.halo.run` -> `api.console.halo.run`。

改了，聊天记录复制错了

**Comment by guqing** [comment]
/close
see also https://github.com/halo-dev/halo/pull/2419 and https://github.com/halo-dev/halo-admin/pull/613
