### ISSUE TITLE
文章内跳转建立增加一个相对路径

### ISSUE THREAD

**Issue by szgacsaftop** [halo-dev/halo#2420]
### 你当前使用的版本

1.53

### 描述一下此特性

1.目前我们使用的编辑页面链接的语法是  [超链接显示名](超链接地址 "超链接title")
2.是否增加一种在页面间跳转的时候使用相对路径

**Comment by ruibaby** [comment]
@szgacsaftop Hello, 能再详细描述一下这个特性吗？当前描述我不是很明白。
