### ISSUE TITLE
为主题和插件提供更新/清空设置项的功能

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#2426]
### 你当前使用的版本

2.0.0-prerelease

### 描述一下此特性

目前主题和插件的设置部分使用了 Setting（设置表单 UI） 和 ConfigMap（设置存储） 模型，但在开发主题和插件过程中，可能会频繁修改 Setting 的内容，目前唯一能做的就是调用 Setting 的 Extension API 手动更新 Setting 的 FormSchema  定义。期望提供更新 Setting 的功能。

/kind feature
/milestone 2.0
/area core

/cc @halo-dev/sig-halo any idea?

**Comment by guqing** [comment]
插件不需要此功能，配置了 `fixedPluginPath` 后每次重启都会加载新的配置项

**Comment by ruibaby** [comment]
/close

See https://github.com/halo-dev/halo/pull/2456 https://github.com/halo-dev/console/pull/620 https://github.com/halo-dev/halo/pull/2486 for more
