### ISSUE TITLE
文章支持统计浏览量/评论量等数据

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#2430]
### 你当前使用的版本

2.0.0-prerelease

### 描述一下此特性

文章支持统计浏览量、评论量等数据。

/kind feature
/milestone 2.0
/area core

**Comment by guqing** [comment]
我将通过在模板页面插入 Javascript 来上报数据给一个 endpoint 然后 counter 数据到 metrics，定期刷新数据到自定义模型持久化

**Comment by ruibaby** [comment]
/close

See https://github.com/halo-dev/halo/pull/2476 and https://github.com/halo-dev/console/pull/624 for more.
