### ISSUE TITLE
类似这样的图片名【book (1).jpg】，上传后无法使用

### ISSUE THREAD

**Issue by saxingz** [halo-dev/halo#244]
猜测是由于括号，或者是空格导致的

html里看代码是这样的：
style="background-image: url(/upload/2019/7/book (1)-73b8249fbff54f7f916be01e007a9880.jpg)

这样就显示不出来了。

这种文件名是由于复制时自动带上去的。 用户是可以自己把关的。

作者看一下，要是没必要修改， 直接close吧。

**Comment by ruibaby** [comment]
你用的 Halo 是哪个版本？

**Comment by saxingz** [comment]
> 你用的 Halo 是哪个版本？

最新的版本，昨天从源码上拉下来跑的。

**Comment by ruibaby** [comment]
@saxingz 在附件详情复制图片地址的话会编码的，你尝试一下。

**Comment by saxingz** [comment]
> @saxingz 在附件详情复制图片地址的话会编码的，你尝试一下。

手动复制是会编码，但是在发布文章时，直接从附件库里选择图片，应该是没有编码的。

**Comment by ruibaby** [comment]
@saxingz 你说的是选择文章缩略图吧。

**Comment by saxingz** [comment]
> @saxingz 你说的是选择文章缩略图吧。

是的。你回复好快。~~

**Comment by ruibaby** [comment]
@saxingz 哦，这里确实忘了编码url，下个版本加上去。ps：tg回复

**Comment by a1105013796** [comment]
同样的问题，直接复制上去的图片发布以后就无法显示

**Comment by ruibaby** [comment]
@a1105013796 https://bbs.halo.run/d/138-1-0-4/10

**Comment by ruibaby** [comment]
已修复。
