### ISSUE TITLE
仪表盘删除组件后不能立即生效

### ISSUE THREAD

**Issue by wan92hen** [halo-dev/halo#2444]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

2.0

### 使用的什么数据库？

Other

### 使用的哪种方式部署？

Docker

### 发生了什么？

在仪表盘中点击设置，删除组件后不能立即生效，被删除的组件仍然显示在页面上，需要点击完成组件才会消失。

**Comment by ruibaby** [comment]
/close 

See https://github.com/halo-dev/console/commit/33c9399d0ef1c1ccfa20c1215919fe7c7d7c0376 for more
