### ISSUE TITLE
文章大纲未按层级展示

### ISSUE THREAD

**Issue by wan92hen** [halo-dev/halo#2445]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

2.0

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

文章编辑页面右侧的大纲中，添加的各级标题均进行了平铺展示，无法体现标题间的层级关系。
建议不同级别的标题使用不同宽度的缩进以进行区分。
![image](https://user-images.githubusercontent.com/27671436/191647372-571e8ada-7df6-4f6a-99c2-51bece8b6ec8.png)

**Comment by ruibaby** [comment]
/close 

目前已经支持体现层级关系，也已支持点击滚动到具体位置。 https://github.com/halo-dev/console/commit/831e3fd6ca63fb5839790f5cb3c18b9be885ecbc
