### ISSUE TITLE
上传附件弹框存储策略名较长时存在样式问题

### ISSUE THREAD

**Issue by wan92hen** [halo-dev/halo#2447]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

2.0

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

新建一个名字比较长的存储策略，或无存储策略时，上传附件弹窗右上角策略名存在样式问题。
![image](https://user-images.githubusercontent.com/27671436/191652661-9fa737f4-39f3-4f10-b102-9a68d8452c87.png)

**Comment by ruibaby** [comment]
/close

See https://github.com/halo-dev/console/commit/bdd863264778f9d2d90123233ae16263c4026429 for more
