### ISSUE TITLE
最近登录组件数据不正确

### ISSUE THREAD

**Issue by wan92hen** [halo-dev/halo#2449]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

2.0

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

仪表盘中的 `最近登录` 组件展示的内容与实际最近登录用户及登录时间不符。

**Comment by ruibaby** [comment]
已过时 issue，目前没有相关功能。

/close
