### ISSUE TITLE
建议订阅功能和统计字数

### ISSUE THREAD

**Issue by wdragondragon** [halo-dev/halo#245]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [x] 添加新的特性或者功能
- [ ] 请求技术支持

建议增加一个订阅功能，与评论回复功能类似，增加新文章或更新已有文章时通知关注该博客的邮箱。

建议增加一个统计文章字数功能，能在主页显示博主已写总字数和能在文章内看到该文章总字数。

**Comment by 565785929** [comment]
建议Markdown支持公式

**Comment by ruibaby** [comment]
> 建议Markdown支持公式

本身就支持，你应该说的是主题端，这个需要自行引入插件。

**Comment by ruibaby** [comment]
你好，感谢提出这个功能，但是目前我们可能还不会去实现。因为我们暂时还没有想到好的解决方案。
