### ISSUE TITLE
个人资料修改头像

### ISSUE THREAD

**Issue by wxyShine** [halo-dev/halo#2450]
### 检查清单

- [x] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

1.5.4

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

个人资料修改头像时，如不点保存按钮 ， 修改的头像 刷新后就变回旧头像了。

**Comment by wxyShine** [comment]
增加一个更新头像接口，修改头像确定时，去调用更新头像接口。如何？

**Comment by ruibaby** [comment]
> 增加一个更新头像接口，修改头像确定时，去调用更新头像接口。如何？

不用，直接调用更新个人资料的接口即可。但是需要注意，修改头像的时候只能更新 avatar 这个字段，不要将正在编辑的表单也同时提交了。

**Comment by wxyShine** [comment]
> > 增加一个更新头像接口，修改头像确定时，去调用更新头像接口。如何？
> 
> 不用，直接调用更新个人资料的接口即可。但是需要注意，修改头像的时候只能更新 avatar 这个字段，不要将正在编辑的表单也同时提交了。

好的

**Comment by wxyShine** [comment]
> > 增加一个更新头像接口，修改头像确定时，去调用更新头像接口。如何？
> 
> 不用，直接调用更新个人资料的接口即可。但是需要注意，修改头像的时候只能更新 avatar 这个字段，不要将正在编辑的表单也同时提交了。

在halo-admin  [master分支](https://github.com/halo-dev/halo-admin)基础上改吗？

**Comment by ruibaby** [comment]
> 在halo-admin [master分支](https://github.com/halo-dev/halo-admin)基础上改吗？

是的。

**Comment by ruibaby** [comment]
/close

See https://github.com/halo-dev/console/pull/619 for more.
