### ISSUE TITLE
新增附件分组快捷键提示不正确

### ISSUE THREAD

**Issue by wan92hen** [halo-dev/halo#2455]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

2.0

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

![image](https://user-images.githubusercontent.com/27671436/191691040-1ffd8830-41ca-49b6-9b86-63cac816db89.png)
新增分组弹框中，保存按钮提示的快捷键为 `command/ctrl + enter`，实际使用 Win11 + Edge 浏览器时，`ctrl + enter` 无法保存，只按回车键可以保存。

操作系统：Windows 11 22621.521
浏览器：Microsoft Edge 版本 105.0.1343.42 (正式版本) (64 位)

**Comment by ruibaby** [comment]
将修改为 Linux/Windows 显示 **Ctrl + Enter**，Mac 显示 **Command + Enter**

**Comment by ruibaby** [comment]
/close

See https://github.com/halo-dev/console/commit/2c7d8551fb4efc7725ae486834ba57b1c6fc3327 for more
