### ISSUE TITLE
设置文章分类时展示分类层级

### ISSUE THREAD

**Issue by wan92hen** [halo-dev/halo#2485]
### 你当前使用的版本

2.0

### 描述一下此特性

目前设置文章分类时分类目录没有展示出层级关系，如果在不同的父分类下存在同名分类，在设置时难以区分具体是选择了哪个子分类。

![image](https://user-images.githubusercontent.com/27671436/192718497-004b0c6e-2a65-47af-ad73-ce2f79a209fc.png)

![image](https://user-images.githubusercontent.com/27671436/192718439-e7571f68-e4fa-456c-98d7-255f28273c8d.png)

建议在设置文章分类时，使用不同的缩进量来表现分类层级关系。

**Comment by ruibaby** [comment]
我将尝试在 2.1.0 发布前来解决此问题。

/milestone 2.1.x
