### ISSUE TITLE
图库后台批量添加图片，图片的顺序倒序

### ISSUE THREAD

**Issue by zyy247796143** [halo-dev/halo#2487]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

1.5.4

### 使用的什么数据库？

MySQL 5.7

### 使用的哪种方式部署？

Docker

### 发生了什么？

在后台的图库页，当选择批量添加已经存在的附件照片时，会发生倒序添加现象。
比如说我在图库页，选择批量添加，然后选择已经存在的早、中、晚，3个时间的图片附件，点击确定后，在图库页里看到刚刚添加照片的顺序发生了倒序，即看到的是晚、中、早的顺序，导致在前端主题上显示的也是倒序的图片。

**Comment by ruibaby** [comment]
PR Welcome :)

/good-first-issue
/kind improvement
/area admin

**Comment by ruibaby** [comment]
/close 

See https://github.com/halo-dev/console/pull/631 for more
