### ISSUE TITLE
个人信息，主题配置信息，文章缩略图，这三者里边保存的图片可以改为相对路径吗？

### ISSUE THREAD

**Issue by saxingz** [halo-dev/halo#249]
如题哈

**Comment by ruibaby** [comment]
你好，请问这样做有什么特别的要求吗？

**Comment by saxingz** [comment]
> 你好，请问这样做有什么特别的要求吗？

切换域名，简直了

**Comment by ruibaby** [comment]
@saxingz 好吧，我们正在考虑怎样改善图片路径的问题。暂时推荐你直接去数据库全局替换一下域名。

**Comment by saxingz** [comment]
> 你好，请问这样做有什么特别的要求吗？

如果你们有这个打算，又没时间，我可以 push ~~

**Comment by saxingz** [comment]
> @saxingz 好吧，我们正在考虑怎样改善图片路径的问题。暂时推荐你直接去数据库全局替换一下域名。

好的~那就由你们统一弄吧

**Comment by ruibaby** [comment]
@saxingz 嗯

**Comment by ruibaby** [comment]
@saxingz 哦？你是怎样处理的呢？

**Comment by watermelon1135** [comment]
为什么引用互联网的图片会报403错误啊

**Comment by JohnNiang** [comment]
@watermelon1135 可以详细一点儿么？无法理解你的 403 错误。

**Comment by JohnNiang** [comment]
@watermelon1135 

根据 ruibaby 的解释：跨域了，其他平台的图片地址做了防盗链。

我们暂时没有办法。

**Comment by watermelon1135** [comment]
> @watermelon1135
> 
> 根据 ruibaby 的解释：跨域了，其他平台的图片地址做了防盗链。
> 
> 我们暂时没有办法。

嗯嗯

**Comment by watermelon1135** [comment]
还有一个问题，后台修改logo图片的地址，前端about me图片还是引用之前的图片的地址

**Comment by JohnNiang** [comment]
@watermelon1135 具体是什么主题呢？

**Comment by watermelon1135** [comment]
> @watermelon1135 具体是什么主题呢？
这是logo不是在博客设置里面的设置吗？好像和主题没有关系吧？主题用的是：[hux](https://github.com/halo-dev/halo-theme-hux)

**Comment by ruibaby** [comment]
> > @watermelon1135 具体是什么主题呢？
> > 这是logo不是在博客设置里面的设置吗？好像和主题没有关系吧？主题用的是：[hux](https://github.com/halo-dev/halo-theme-hux)

Hux 侧边栏的“logo”取的是头像。

**Comment by watermelon1135** [comment]
> > > @watermelon1135 具体是什么主题呢？
> > > 这是logo不是在博客设置里面的设置吗？好像和主题没有关系吧？主题用的是：[hux](https://github.com/halo-dev/halo-theme-hux)
> 
> Hux 侧边栏的“logo”取的是头像。

哦哦，多谢，那请问那个logo设置是在哪体现的？
