### ISSUE TITLE
优化登录相关逻辑

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#2506]
### 你当前使用的版本

2.0.0-alpha.1

### 描述一下此特性

目前存在的问题：

1. 目前在登录异常的时候，在前端无法得知具体异常（比如用户名密码错误）。原因是 Console 端使用 fetch 接口调用了 Spring Security 提供的 `/login <POST>` 接口，但这个接口需要 form 提交，暂时不是特别方便在 Console 端得到异常。
2. 如果使用后端提供的登录入口（/login），登录之后无法跳转到先前的页面。

可商讨的方案：

1. 单独提供登录接口，或者改造 /login 的默认行为。
2. 直接使用 Spring Security 提供的登录入口，但需要处理好重定向的问题。而且需要考虑到后续通过插件扩展登录方式。

/kind improvement
/milestone 2.0

**Comment by JohnNiang** [comment]
这里需要改造以下登录成功和失败的处理器，尤其是需要对 XHR 和浏览器请求做区分。 

/assign

**Comment by JohnNiang** [comment]
请参考：<https://github.com/halo-dev/halo/blob/af8860ffb69245e7dae434ff95f7959823bc2beb/docs/authentication/README.md>。
