### ISSUE TITLE
特性提议：支持将某个分类下的文章设置为不进入“最新文章”列表

### ISSUE THREAD

**Issue by AsakusaRinne** [halo-dev/halo#2508]
### 你当前使用的版本

1.5.4

### 描述一下此特性

支持将某个分类下的文章设置为不进入“最新文章”列表。

比如我用halo给自己搭建了一个技术博客分享网站，但是里面也有一些自己日常非技术类的文章，虽然这些非技术类文章也是公开的，但是不希望作为“最新文章”列表中的一个出现在首页喧宾夺主，能否将某个分类设置成不参与“最新文章”列表的收录呢？

很抱歉因为我不怎么用JAVA和FreeMaker，很难直接自己实现并进行PR，不过如果能帮忙指出在哪几个文件修改可以实现这个的话，我很乐意学习一下并针对这个提一个PR。

国庆快乐！:)

**Comment by ruibaby** [comment]
这个特性提议不错，其实不仅仅是你提到的这种场景。像 Halo 官网这种，主题仓库也是通过文章发布的，那么在博客列表里面肯定就是不希望出现主题内容的，这个时候就需要排除特定的分类。

如果你想尝试一下修改，你可以看一下这个查询构建筛选条件的部分：<https://github.com/halo-dev/halo/blob/ce1ce585f018e5a2d4798b380f969c4967fec85c/src/main/java/run/halo/app/service/impl/PostServiceImpl.java#L144>，如果要在 1.5 支持该特性，可能需要考虑较多的地方。我们也会在 2.0 考虑是否要支持该特性。

/kind feature

**Comment by AsakusaRinne** [comment]
感谢回答，期待2.0可以支持这个特性。

仔细看了一下这部分代码，感觉可能还是要交给专业的人去做这个事情哈哈，我的技术栈实在跟JAVA以及Web应用不太搭边🤣恐怕短时间内搞不定这个

**Comment by ruibaby** [comment]
已经在 https://github.com/halo-dev/halo/pull/6116 中支持，将发布在 2.17.0。

/close
