### ISSUE TITLE
markdown解析后段落标题如果为中文会被url编码，无法使用tocbot目录进行跳转

### ISSUE THREAD

**Issue by MaxnRain** [halo-dev/halo#2515]
### 是什么版本出现了此问题？

1.5.4

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Fat Jar

### 在线站点地址

http://ra1n.top:8088/

### 发生了什么？

在使用tocbot生成目录时，发现中文标题无法进行快速的跳转位置，查明原因发现为markdown解析将中文标题解析为url编码，但是tocbot使用中文进行跳转，导致找不到编码后的h标签id

### 附加信息

![image](https://user-images.githubusercontent.com/79247041/194467596-cc0856ce-d1b1-4c09-8b25-f75e08e38a32.png)
![image](https://user-images.githubusercontent.com/79247041/194467627-ac9125bb-8433-48ac-930b-31284b82b057.png)
![image](https://user-images.githubusercontent.com/79247041/194467642-2bde120c-e242-4625-bac4-a4fa3e5b6a4b.png)

**Comment by ruibaby** [comment]
你需要使用最新的 tocbot，请参考：https://bbs.halo.run/d/2288/7

**Comment by ruibaby** [comment]
/triage duplicate

https://github.com/halo-dev/halo/issues/2157
