### ISSUE TITLE
群晖Docker安装今天突然无法启动了

### ISSUE THREAD

**Issue by BoWang816** [halo-dev/halo#2516]
### 是什么版本出现了此问题？

1.5.4

### 使用的什么数据库？

Other

### 使用的哪种方式部署？

Docker

### 在线站点地址

https://blog.wangboweb.site

### 发生了什么？

容器无法启动一直提示以下错误，是突然出现了，然后数据都丢了，在db文件夹下面的两个db文件无法打开，不知道有么有什么解决的办法呢？
![WechatIMG538.jpeg](https://s2.loli.net/2022/10/07/qHoD9FZ3psaPnQx.jpg)

### 相关日志输出

```shell
![WechatIMG538.jpeg](https://s2.loli.net/2022/10/07/qHoD9FZ3psaPnQx.jpg)
```

**Comment by BoWang816** [comment]
额，解决了，通过idea将halo.mv.db打开，将数据导出转换为sql，再导进mysql数据库了，改用mysql进行存储了。

不过还是很疑惑，为什么会突然出现这种问题

**Comment by JohnNiang** [comment]
看样子是数据库迁移工具报的错误，建议提供一下完整的错误日志。

/kind support

**Comment by BoWang816** [comment]
> 看样子是数据库迁移工具报的错误，建议提供一下完整的错误日志。
> 
> /kind support

额，完整的错误日志已经没有了，我已经将原来的容器删除，并使用mysql进行存储，现在都已经恢复了，如果后续再碰到了再看吧，感谢🙏
