### ISSUE TITLE
自动保存导致修改被覆盖

### ISSUE THREAD

**Issue by JackyLeeCS** [halo-dev/halo#252]
我在一台机器上打开了一篇文章的编辑界面并保持打开状态，然后在另外一台机器上编辑这篇文章并发布。这时候原先机器上编辑界面的自动保存功能会导致修改被覆盖。

**Comment by JackyLeeInChina** [comment]
希望编辑界面的自动保存功能能加一个开关，保留ctrl+s的手动保存功能

**Comment by JohnNiang** [comment]
@JackyLeeInChina 自动保存确实存在很多问题。我们会考虑您的提议。

**Comment by ruibaby** [comment]
现已经移除自动保存这个特性，代替方案为https://github.com/halo-dev/halo/releases/tag/v1.1.0-beta.1
