### ISSUE TITLE
console 菜单设置支持其他字段以及右键创建子菜单

### ISSUE THREAD

**Issue by liuzhihang** [halo-dev/halo#2525]
### 你当前使用的版本

halo 2.0

### 描述一下此特性

1. 新增 icon 字段以及扩展字段

icon 字段作用：前端菜单栏用来显示 icon
扩展字段：以备不时之需

一个字段也行。

<img width="721" alt="image" src="https://user-images.githubusercontent.com/26057042/194764724-ab337eaa-d380-49e7-bacb-da0b8200dd11.png">

2. 右键新增创建子菜单

当前父子菜单依靠的是拖动，也很好使用，不过不是很明显，可以增加提示，或者是在右键那里增加`创建子菜单选项`

<img width="236" alt="image" src="https://user-images.githubusercontent.com/26057042/194764790-173e9d6c-3d92-4c9a-ba4b-7db9ab3e834f.png">

**Comment by ruibaby** [comment]
/close

see https://github.com/halo-dev/halo/issues/2878#issuecomment-1366422903 for more
