### ISSUE TITLE
menuFinder.getByName 获取不到结果

### ISSUE THREAD

**Issue by liuzhihang** [halo-dev/halo#2526]
### 是什么版本出现了此问题？

halo 2.0

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 在线站点地址

本地部署

### 发生了什么？

在 console 配置菜单栏，然后使用 th:text="${menuFinder.getByName('xxx')}" 获取不到结果。

<img width="619" alt="image" src="https://user-images.githubusercontent.com/26057042/194768661-c1fe6939-ae7c-4f4d-88f8-34829626a39b.png">

查看代码中使用的是 `menu.getMetadata().getName()`

<img width="1115" alt="image" src="https://user-images.githubusercontent.com/26057042/194768725-8aef6173-a3d6-43f5-b169-dbee275bb22b.png">

最终通过这一串类似 UUID 的字符串获取到菜单

<img width="1239" alt="image" src="https://user-images.githubusercontent.com/26057042/194768789-16856f76-7165-4cda-a244-53b8df808fef.png">

不确定是否是 bug，不过需要看一下。

**Comment by guqing** [comment]
可以把你这个菜单 api 的 response body 贴出来吗 我用你的数据试一下，我没复现

**Comment by guqing** [comment]
> 可以把你这个菜单 api 的 response body 贴出来吗 我用你的数据试一下，我没复现

哦 我理解错了 你是想通过你填写的名称来获取菜单

**Comment by guqing** [comment]
后续我们会提供一个系统设置用于配置主菜单，目前主菜单默认使用的第一个

**Comment by liuzhihang** [comment]
> 后续我们会提供一个系统设置用于配置主菜单

@guqing @ruibaby 

不是自定义默认菜单，有这么一个场景，比如在 footer 放置一些相关链接，这时候就需要一个树状结构的列表，这种情况我可以有两个选择：

1. 在 settings 添加配置，让用户配置指定格式的 json 或者 yaml 等等，我解析那块
2. 复用菜单，但是用户需要创建一个我指定名称的菜单，我按照名称去取这个树状结构，然后展示出来。

明显复用 menu 菜单比较合适，这时候就缺少一个根据用户填写的`菜单名获取菜单树` 接口。

当前也可以这么弄，让用户 f12 去获取那个自定义菜单 metadata 的 name，配置在 settings 中，我从 settings 中获取到那个指定菜单，然后遍历展示。

图的话可以参考 halo 官网的 footer

<img width="1286" alt="image" src="https://user-images.githubusercontent.com/26057042/194841912-3df2c7ab-484d-4719-90f0-fedc61500352.png">

**Comment by ruibaby** [comment]
@liuzhihang 

@guqing 在 https://github.com/halo-dev/halo/issues/2526#issuecomment-1272729965 中所说的就是为了支持你说的这种场景。我们会提供一个自定义的 formkit input，使用方式大致如下：

settings.yaml

```yaml
formSchema:
  - $formkit: menu
    name: footer_menu
    label: 页脚菜单
  - $formkit: multiple_menu
    name: footer_menus
    label: 页脚菜单组
```

如上所示，如果使用了 `menu` 类型的 input，那么 `footer_menu` 所得到的值就是 `menu.metadata.name`，如果使用了 `multiple_menu`，那么 `footer_menus` 得到的就是 `menu.metadata.name` 的集合。

那么主题就可以这样使用：

```
<ul th:with="menu=menuFinder.getByName(theme.config.group.footer_menu)">
    <li th:each="menuItem : menu.menuItems">
        // do something
    </li>
</ul>
```

`multiple_menu` 类型同理，你可以遍历这个值然后再用 `menuFinder.getByName`。

这种方式对于用户来讲，完全不需要接触到 menu 的 `metadata.name`

**Comment by liuzhihang** [comment]
我也想的这种方式，只不过需要用户获取到 metadata.name 配置到 $formkit: text 中，不过 formkit input 直接支持 menu 那就最好不过了。

👍
