### ISSUE TITLE
Markdown转换问题

### ISSUE THREAD

**Issue by rxc-team** [halo-dev/halo#253]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [ ] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [ ] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

目前使用来看，对我最大的影响在于markdown解析问题：
admin端markdown编辑器编辑好了的内容，和发布之后的博客端显示出来的内容不一致。
尝试过使用完全使用HTML编辑内容，如果没有固定样式的话，还是会出现这个问题，如图片默认居中了，默认加了边框等，也可能是主题的问题（目前使用NEXT）。没有更换主题尝试！另外在admin端预览解析出来的结果是符合我的理想。

**Comment by JohnNiang** [comment]
确实不同的主题有不同的样式。这是造成差异的最主要的原因。

后台采用 flexmark 解析的 markdown 源格式的内容，而 halo-admin 端则是直接用的 markdown 编辑器，估计是用的 marked。

**Comment by rxc-team** [comment]
> 确实不同的主题有不同的样式。这是造成差异的最主要的原因。
> 
> 后台采用 flexmark 解析的 markdown 源格式的内容，而 halo-admin 端则是直接用的 markdown 编辑器，估计是用的 marked。

希望能够统一下，不然编辑了半天的文章，结果出来的效果完全不一样，还得花更多的时间去解决格式问题，我觉得体验来讲不是很好。

**Comment by JohnNiang** [comment]
样式问题可能无法得到统一。毕竟每个主题开发者所引用的 markdown 渲染样式是不同的。

**Comment by rxc-team** [comment]
> 样式问题可能无法得到统一。毕竟每个主题开发者所引用的 markdown 渲染样式是不同的。

是否可以尝试使用admin端的解析成HTML文件后存入到DB中，然后后台直接使用呢？

**Comment by JohnNiang** [comment]
> > 样式问题可能无法得到统一。毕竟每个主题开发者所引用的 markdown 渲染样式是不同的。
> 
> 是否可以尝试使用admin端的解析成HTML格式存入到DB中，然后后台直接使用呢？

这可能会造成和主题本身的样式的不协调。

而且 halo-admin 仅仅是一个客户端，未来可能还有其他客户端，综合起来看后端渲染（仅仅是将 md 源格式 转换为单纯的 html，这样主题开发者对样式的控制的把控会更好）是一个折中的方案。

**Comment by rxc-team** [comment]
> 而且 halo-admin 仅仅是一个客户端，未来可能还有其他客户端，综合起来看后端渲染（仅仅是将 md 源格式 转换为单纯的 html，这样主题开发者对样式的控制的把控会更好）是一个折中的方案。

好吧。

**Comment by JohnNiang** [comment]
每个主题有着自己的样式，这其实是合理的，你只需要挑选一个你认为最心仪一个主题来应用到自己的博客。最后，只要你的 markdown 的语法没问题，渲染的结果还是可以接受的。

**Comment by watermelon1135** [comment]
markdown无法粘贴图片啊

**Comment by JohnNiang** [comment]
> markdown无法粘贴图片啊

这个功能已经开发好了，但是还没有发布。

**Comment by watermelon1135** [comment]
> > markdown无法粘贴图片啊
> 
> 这个功能已经开发好了，但是还没有发布。

哦哦好的
