### ISSUE TITLE
Pinghsu模板无法显示文章tag

### ISSUE THREAD

**Issue by rayeaster** [halo-dev/halo#254]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [ ] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

**Comment by rayeaster** [comment]
确认文章已添加tag，但是页面无法显示。默认的Anatole模板可以正确显示

**Comment by JohnNiang** [comment]
好的，我们去排查一下。

**Comment by rayeaster** [comment]
https://github.com/halo-dev/halo-theme-pinghsu/pull/7

**Comment by JohnNiang** [comment]
Merged. Thanks a million!
