### ISSUE TITLE
提供主题更新的功能

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#2550]
### 你当前使用的版本

2.0.0-alpha.2

### 描述一下此特性

目前仅支持安装主题，但无法很方便的更新主题。所以期望提供专门更新主题的功能。

/kind feature
/area core
/area console
/priority critical-urgent
/milestone 2.0

**Comment by JohnNiang** [comment]
主题更新设计讨论：

主题更新功能也会涉及到主题撤回。所以我们可能需要
1. 保存每次更新前的主题的快照（Snapshot）
2. 主题更新时，不会覆盖旧主题目录，而是创建以主题名为前缀的文件夹来保存新的主题

回滚主题时，和更新主题过程类似，不过没有主题文件上传的流程。

**Comment by JohnNiang** [comment]
目前，考虑到上述实现比较复杂，最终采用比较简单的实现替代：

1. 上传新主题
2. 检查主题是否合法
3. 删除已经存在的主题并等待删除完毕
4. 安装当新主题
5. 更新完毕
