### ISSUE TITLE
点击文章发布不生效

### ISSUE THREAD

**Issue by xueqidove** [halo-dev/halo#2557]
### 是什么版本出现了此问题？

2.0.0的alpha.2

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Fat Jar

### 在线站点地址

官网demo

### 发生了什么？

![image](https://user-images.githubusercontent.com/60059766/195523367-fa7ef54f-c908-4b4f-aefc-e960b6a7cc4c.png)

发布文章时，点击发布或者重新发布，经常会很快发布完成，但是实际并未发布，大概概率在50%左右。

### 相关日志输出

```shell
暂无
```

### 附加信息

暂无

**Comment by ruibaby** [comment]
我们会尝试复现一下。

/kind bug

**Comment by JohnNiang** [comment]
建议观测一下网络请求，检查发布接口是否有报错。目前我们还缺少：

1. 统一错误处理
2. 前端显示错误信息（目前是静默了所有的错误）

**Comment by ruibaby** [comment]
目前 2.0.0-beta.1 已经优化了文章的发布流程，可以再次尝试一下：https://github.com/halo-dev/halo/releases/tag/v2.0.0-beta.1

**Comment by ruibaby** [comment]
> 建议观测一下网络请求，检查发布接口是否有报错。目前我们还缺少：
> 
> 1. 统一错误处理
> 2. 前端显示错误信息（目前是静默了所有的错误）

https://github.com/halo-dev/console/pull/732
