### ISSUE TITLE
建议支持文章发布、用户头像设置等支持直接选择或者上传附件图片

### ISSUE THREAD

**Issue by xueqidove** [halo-dev/halo#2558]
### Your current Halo version

2.0.0的alpha.2

### Describe this feature

希望在以下区域增加直接选择已有附件或者上传图片功能：
文章发布设置：
![image](https://user-images.githubusercontent.com/60059766/195524295-7b587089-02c7-4c72-a0ef-9535226491a7.png)
用户头像设置：
<img width="737" alt="image" src="https://user-images.githubusercontent.com/60059766/195524478-c229edba-a115-4886-926d-57e88b0d412e.png">
系统基础设置：
<img width="819" alt="image" src="https://user-images.githubusercontent.com/60059766/195524787-3a75d42c-01f9-4ac6-92ff-ae86a3f9fe0a.png">

### Additional information

暂无

**Comment by ruibaby** [comment]
很好的建议。这个我们后续会统一提供一系列的 input 选择器，基于 formkit 的自定义 input。https://formkit.com/advanced/custom-inputs

/kind feature
/milestone 2.0
/area console
/assign

**Comment by ruibaby** [comment]
类似于：https://github.com/halo-dev/halo/issues/2526#issuecomment-1273094868
