### ISSUE TITLE
建议文章编辑界面的工具栏能固定下来

### ISSUE THREAD

**Issue by JackyLeeCS** [halo-dev/halo#256]
现在文章编辑界面的工具栏是随界面滚动，只要文章稍微长一点，这个编辑工具栏基本就用不上了，只能手敲markdown语法。

还有一个问题是markdown的表格语法好像在发布后的界面无法正常显示，试了几个主题都不行，在编辑界面预览的时候是可以正常显示的。

**Comment by JohnNiang** [comment]
表格问题确实存在，我们正在尝试修复。

**Comment by ruibaby** [comment]
1：你点击右上角的全屏编辑，即可满足你的需求。
2：已修复。
