### ISSUE TITLE
建议增加按照文章目录所以快速浏览文章

### ISSUE THREAD

**Issue by xueqidove** [halo-dev/halo#2560]
### Your current Halo version

2.0.0的alpha.2

### Describe this feature

如下图所示，在文章内容查看的时候支持按照文章目录进行文章查看
<img width="1660" alt="image" src="https://user-images.githubusercontent.com/60059766/195527613-fbcfb2d4-2f04-41bf-a4f5-f18a77f10359.png">

### Additional information

无

**Comment by ruibaby** [comment]
这个需要主题支持，我们将在 https://github.com/halo-sigs/theme-default 默认主题提供这个功能。

/assign
/kind feature
/milestone 2.0

**Comment by ruibaby** [comment]
theme-default 已经在 https://github.com/halo-sigs/theme-default/commit/bf574b7aebe991881b7f96c575cdbb89c8899dc7 中支持。

/close
