### ISSUE TITLE
后台管理中的菜单项数据统计错误

### ISSUE THREAD

**Issue by xueqidove** [halo-dev/halo#2561]
### What is version of Halo has the issue?

2.0.0的alpha.2

### What database are you using?

H2

### What is your deployment method?

Fat Jar

### Your site address.

公网demo环境地址

### What happened?

如下图所示：页面中有6个页面，但是统计出10个菜单项，初步怀疑是因为历史已经删除的菜单项也统计在内了。
<img width="1302" alt="image" src="https://user-images.githubusercontent.com/60059766/195530722-e52bc895-bea5-4170-9610-aa166d028d42.png">

**Comment by ruibaby** [comment]
应该是没有及时更新菜单的 menuItems。

/kind bug
/milestone 2.0
/area console
/assign
