### ISSUE TITLE
添加子菜单后在用户端无处可点击进入

### ISSUE THREAD

**Issue by xueqidove** [halo-dev/halo#2562]
### What is version of Halo has the issue?

2.0.0的alpha.2

### What database are you using?

H2

### What is your deployment method?

Fat Jar

### Your site address.

公网demo环境地址

### What happened?

菜单中添加二级主题后，无处可访问

<img width="893" alt="image" src="https://user-images.githubusercontent.com/60059766/195532499-74d8b92b-4bc9-4079-b917-aa4a12a811dd.png">

**Comment by ruibaby** [comment]
这个需要主题支持，我们将在 https://github.com/halo-sigs/theme-default 默认主题提供这个功能。

/assign
/kind feature
/milestone 2.0

**Comment by ruibaby** [comment]
已经在 https://github.com/halo-sigs/theme-default/commit/e41535784d02a713a9e3d6c16c3ef95a4a0cb315 支持二级菜单，可以尝试一下。其他主题需要对应的支持。

/close
