### ISSUE TITLE
markdown表格在前端没有被正确的解析

### ISSUE THREAD

**Issue by a1105013796** [halo-dev/halo#257]
编辑时的预览显示
![image](https://user-images.githubusercontent.com/32124539/61717930-90589400-ad94-11e9-83c5-b4243fb841c0.png)

发布后的显示
![image](https://user-images.githubusercontent.com/32124539/61717951-99496580-ad94-11e9-8cd8-2a66321d9339.png)

问题点：markdown表格在前端没有被正确的解析
使用多款主题遇到同样的问题，目前怀疑是渲染器的问题

**Comment by JohnNiang** [comment]
极有可能是后端渲染的问题。

后端采用 flexmark 渲染的，我们后续将会测试一下表格渲染。

**Comment by a1105013796** [comment]
好的

**Comment by ruibaby** [comment]
已修复。
