### ISSUE TITLE
随机文章 随机友链

### ISSUE THREAD

**Issue by liuzhihang** [halo-dev/halo#2570]
### 你当前使用的版本

halo 2.0

### 描述一下此特性

调用接口获得 N 个文章，N 个友链，N 为传入数字。随机获取即可。

**Comment by ruibaby** [comment]
/triage needs-information

可以简单讲一下这个接口的使用场景吗？

**Comment by guqing** [comment]
可以通过插件去做

**Comment by liuzhihang** [comment]
@ruibaby  我在移植博客过程中，发现很多 butterfly 魔改文章，都有一个随机前往友链的功能，我看他们都是使用 random.js 实现的，我在想 友链插件 和 文章的接口是否可以新增获取随机文章的能力。

<img width="745" alt="image" src="https://user-images.githubusercontent.com/26057042/195779672-7e73e2d0-fda7-45ba-9747-379ff1e04ace.png">

**Comment by ruibaby** [comment]
个人认为这种需求过于客制化，并不适合在 Core 中提供。而且这种需求可以有很多方式来实现，比如通过在前端请求 `/sitemap.xml` 得到文章链接的列表，再去随机跳转。
