### ISSUE TITLE
后台文章标签多余括号

### ISSUE THREAD

**Issue by shiker1996** [halo-dev/halo#2575]
### 是什么版本出现了此问题？

1.6.0

### 使用的什么数据库？

MySQL 5.7

### 使用的哪种方式部署？

Fat Jar

### 在线站点地址

shiker.tech

### 发生了什么？

![image](https://user-images.githubusercontent.com/32234876/195901001-89ed101d-a59e-4aa2-b0d5-d119fde9c962.png)
后台文章页标签文章数量没有显示，或者直接去掉标签对应括号

### 相关日志输出

```shell
请求接口为：/admin/index.html#/posts/list?page=0&size=10&statuses=PUBLISHED&statuses=DRAFT&statuses=INTIMATE
```

**Comment by Own-lin** [comment]
初步分析应该是前端的问题，由于不会前端所以需要其他人帮忙解决一下

> 分析依据：
后台返回的标签是没有带括号的，而页面展示出来就带上括号了

![image](https://user-images.githubusercontent.com/58496860/197334579-0eb5e968-6f17-4a7e-ac9b-b1eab078247d.png)

**Comment by ruibaby** [comment]
See https://github.com/halo-dev/console/pull/650

/close
