### ISSUE TITLE
console后台文章列表查询不出数据

### ISSUE THREAD

**Issue by zzulpf** [halo-dev/halo#2578]
### 是什么版本出现了此问题？

2.0.0-alpha.1

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 在线站点地址

http://114.115.209.105:8090/

### 发生了什么？

![image](https://user-images.githubusercontent.com/35823696/196013160-8d0e520f-a88b-4f88-8039-6e8184781562.png)

### 相关日志输出

```shell
2022-10-15T17:04:29.397+08:00 ERROR 6 --- [or-http-epoll-3] a.w.r.e.AbstractErrorWebExceptionHandler : [3750f91c-2226]  500 Server Error for HTTP GET "/apis/api.console.halo.run/v1alpha1/posts?keyword=&size=20&page=1"

java.lang.ClassCastException: null
```

**Comment by ruibaby** [comment]
可以提供一下更完整的日志，目前的日志无法判断具体原因。

/triage needs-information

**Comment by zzulpf** [comment]
![image](https://user-images.githubusercontent.com/35823696/196068454-872d8c44-a096-40c9-acca-fd6b9544f9bd.png)
日志里面只有这种异常，现在问题是后台看不到文章前台可以看到

**Comment by JohnNiang** [comment]
可能需要提供一下完整的复现步骤，我这里还从来没遇到过类似的错误，从图中提供的错误来看，无法定位具体问题。

**Comment by ruibaby** [comment]
建议使用最新的版本再试一下。如果没有后续反馈，我将关闭此 issue。

/close
