### ISSUE TITLE
可自定义扩展文章显示类型

### ISSUE THREAD

**Issue by cetr** [halo-dev/halo#2579]
### 你当前使用的版本

2.0-SNAPSHOT_alpha.2

### 描述一下此特性

此特性效果和文章置顶一样，但可以自己扩展，用于丰富页面内容

用处：看的部分主题有轮播图模块，之前轮播图的文章都是用置顶文章来设置的，导致设置混乱，词不达意，不能分开设置

期望：可设置多个展示类型在页面上展示在不同区域，不止轮播图，可能还有其他地方要用，让轮播图和置顶文章这种区分开来

**Comment by ruibaby** [comment]
这大概属于那种 **推荐文章** 之类的设置吗？那么能否通过标签来做区分呢？或者通过 annotations 来做标识，但得支持通过 annotations 做筛选。

**Comment by cetr** [comment]
确实和标签差不多，但还是希望单独出来，不要和文章标签混在一起

**Comment by ruibaby** [comment]
@cetr 可不可以在主题设置选择一批文章？参考：https://github.com/halo-dev/console/pull/643

**Comment by ruibaby** [comment]
> @cetr 可不可以在主题设置选择一批文章？参考：[halo-dev/console#643](https://github.com/halo-dev/console/pull/643)

当然，这个 PR 暂时只可以选单篇文章，后续如果有需要可以支持选择多篇文章。

**Comment by ruibaby** [comment]
当前 Halo 最新版本（2.18）已经支持隐藏分类和其下文章，所以我认为此功能可以让主题在设置中加一个选择分类的选项来实现。

/close
