### ISSUE TITLE
请支持腾讯云CDN存储图片等

### ISSUE THREAD

**Issue by EricLiu** [halo-dev/halo#258]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x ] [Halo 使用文档](https://halo.run/docs)
- [ x] [Halo 论坛](https://bbs.halo.run)
- [x ] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x ] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [x] 添加新的特性或者功能
- [ ] 请求技术支持

**Comment by JohnNiang** [comment]
好的，我们会考虑的。

如果你有兴趣的话，可以参考：https://github.com/halo-dev/halo/pull/251

**Comment by EricLiu** [comment]
> 好的，我们会考虑的。
> 
> 如果你有兴趣的话，可以参考：#251

好的，晚上回去我看下增加加百度云的

**Comment by JohnNiang** [comment]
@EricLiu https://github.com/halo-dev/halo/pull/260

**Comment by EricLiu** [comment]
> @EricLiu #260

非常感谢！

**Comment by JohnNiang** [comment]
希望届时你可以抽空帮忙测试一下，谢谢！
