### ISSUE TITLE
本地开发环境 http://127.0.0.1:8090/console#/login 无法正常登录

### ISSUE THREAD

**Issue by Simple-Stark** [halo-dev/halo#2588]
### 是什么版本出现了此问题？

2.0.0-alpha.2

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Fat Jar

### 在线站点地址

本地

### 发生了什么？

本地搭建环境 使用 http://127.0.0.1:8090/console#/login 无法正确登录
使用http://localhost:8090/console#/login  能够正常登录

![image](https://user-images.githubusercontent.com/61400566/196186881-bbf09828-fcfb-45e9-99f4-c3db8cdb875d.png)

![image](https://user-images.githubusercontent.com/61400566/196186903-4cff5bc0-4deb-4613-9355-63a1d992ce40.png)

### 附加信息

/kind bug

**Comment by ruibaby** [comment]
你需要修改一下 `.env.development` 的 `VITE_API_URL` 为 `http://127.0.0.1:8090`，需要保证登录访问的页面和请求的接口同域。

/remove-kind bug
/kind support

**Comment by JohnNiang** [comment]
最新的提交（<https://github.com/halo-dev/halo/commit/2527eb42e2235637b573659a6ccb37c9948e31f2>）已经添加了 /login 和 /logout 接口的 CORS 限制。所以 console 端如果使用 localhost 作为域名调用接口会造成 CORS 错误。

/close
