### ISSUE TITLE
使用CDN后，后台的评论管理功能异常

### ISSUE THREAD

**Issue by lukeewin** [halo-dev/halo#2589]
### 是什么版本出现了此问题？

版本：1.5.3 数据库：H2 1.4.199 (2019-03-13) 运行模式：production 启用主题：Sakura User Agent：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker

### 在线站点地址

https://blog.lukeewin.top/

### 发生了什么？

配置CDN之后，后台评论的查询功能无效
如图所示
![QQ截图20221017223654](https://user-images.githubusercontent.com/41370685/196206116-f2a213c1-b45c-49c5-8bcb-f295b5976cc6.png)

### 附加信息

https://user-images.githubusercontent.com/41370685/196207276-78c21822-4cb8-4192-8720-02b79d763a81.mp4

**Comment by ruibaby** [comment]
/triage duplicate

- https://github.com/halo-dev/halo/issues/844
- https://docs.halo.run/user-guide/faq#%E7%BD%91%E7%AB%99%E9%85%8D%E7%BD%AE%E4%BA%86%E5%85%A8%E7%AB%99-cdn-%E5%AF%BC%E8%87%B4%E5%90%8E%E5%8F%B0%E9%83%A8%E5%88%86%E5%8A%9F%E8%83%BD%E5%BC%82%E5%B8%B8%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3
