### ISSUE TITLE
除了默认主题其他主题评论图标不显示

### ISSUE THREAD

**Issue by zhangzhaoyu** [halo-dev/halo#259]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [ ] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

如图：
![Screenshot from 2019-07-24 22-28-59](https://user-images.githubusercontent.com/5105709/61802088-7be2cd00-ae62-11e9-8ea9-9aa5fc6c88ea.png)

**Comment by JohnNiang** [comment]
这个问题是因为在 `halo v1.0.3` 版中修改了字段：gavatar -> gravatar 导致的，问题似乎已经修复了，请期待 `halo v1.0.4`。

**Comment by java-aodeng** [comment]
更新就好了

**Comment by zhangzhaoyu** [comment]
@JohnNiang 如果我自己项修正一下，应该改那个地方？还是直接拉取master 分支，自己构建一下？

**Comment by JohnNiang** [comment]
@java-aodeng 具体应该如何更新呢？

**Comment by zhangzhaoyu** [comment]
我当前用的是1.0.3 版本。

**Comment by JohnNiang** [comment]
@zhangzhaoyu 你看看当前主题引用的 halo-comment 的版本是什么？

**Comment by JohnNiang** [comment]
@zhangzhaoyu 请尝试更新主题，或者进入主题修改，找到 comment.ftl，修改版本为 halo-comment 的最新版本(目前最新版为 1.0.5)。

**Comment by zhangzhaoyu** [comment]
> @zhangzhaoyu 请尝试更新主题，或者进入主题修改，找到 comment.ftl，修改版本为 halo-comment 的最新版本(目前最新版为 1.0.5)。

@JohnNiang 在管理端更新了主题，评论图标问题已解决。当前使用的material 主题。发现该主题存在几个问题：
- 搜索功能，输入关键词搜索后，页面点击不了
- 增加不了评论

**Comment by JohnNiang** [comment]
好的，这两个问题我们记录一下。
