### ISSUE TITLE
跳转指定页数 & 文章默认发表时间

### ISSUE THREAD

**Issue by liuzhihang** [halo-dev/halo#2606]
### 你当前使用的版本

2.0.0-alpha.2

### 描述一下此特性

1. 分页查询当前支持上一页，下一页跳转，需要支持点击跳转到指定页面的 href。

<img width="298" alt="image" src="https://user-images.githubusercontent.com/26057042/196694119-6ddbf49e-815c-49c7-8131-16eb3d8989e8.png">

2. 默认文章发表时间是 1970 年，希望可以设置为当前时间

<img width="558" alt="image" src="https://user-images.githubusercontent.com/26057042/196694284-a3b83950-e110-4116-9e01-6776c2c84aff.png">

**Comment by ruibaby** [comment]
目前 Halo 已经支持上述功能。

/close
