### ISSUE TITLE
2.0 编辑器支持扩展自定义指令

### ISSUE THREAD

**Issue by guqing** [halo-dev/halo#2611]
### Your current Halo version

2.0.0-alpha.2

### Describe this feature

目前编辑器可以通过 `/` 触发指令，希望可以扩展指令名。

例如 `/randomImage` 时触发调用对应的指令处理器获得结果为一张随机图片的链接，然后自动填充到编辑器
指令处理器可以是通过 API 调用获得结果也可以是 Javascript 执行的结果（例如 `/time` 自动填充当前时间）

有了这样的功能后甚至可以通过扩展一个 `/pic [image name]` 来搜索附件库或互联网图片并插入到文章， `/attach [file name]` 来插入附件等功能
<img width="401" alt="image" src="https://user-images.githubusercontent.com/38999863/196871765-aa584b8e-4edc-487b-a494-16413efcfa12.png">

具体能做什么事情取决于生态，Halo 只需要提供扩展能力即可

### Additional information

/kind feature

**Comment by LIlGG** [comment]
已经在 https://github.com/halo-sigs/richtext-editor/pull/16 中支持了对默认编辑器自定义指令的扩展

/close
