### ISSUE TITLE
Console 端文章和评论管理的列表排序不固定

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#2622]
### 你当前使用的版本

2.0.0-alpha.2

### 描述一下此特性

在文章和评论管理页面，选择排序方式，多次获取数据的排序不一致，具体复现步骤：

1. 连续创建多篇文章。
2. 选择任意一个排序方式，或者不选择。
3. 点击列表右上角的刷新。
4. 可以观察到每次获取到的数据排序不一致。

/kind bug
/area core
/assign @guqing

**Comment by JohnNiang** [comment]
可能是因为 flatMap 的结果不保证顺序导致的。

https://github.com/halo-dev/halo/blob/7b4dd59c58b0db0367544b9fe5e988dfcf081b9c/src/main/java/run/halo/app/content/impl/PostServiceImpl.java#L72

可参考：<https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html#flatMap-java.util.function.Function->
