### ISSUE TITLE
查看标签页面报错

### ISSUE THREAD

**Issue by JackyLeeCS** [halo-dev/halo#263]
部分标签页面查看时报错：
Request processing failed; nested exception is org.springframework.dao.IncorrectResultSizeDataAccessException: query did not return a unique result: 2; nested exception is javax.persistence.NonUniqueResultException: query did not return a unique result: 2

**Comment by JohnNiang** [comment]
可能产生了脏数据。

**Comment by xuzhougeng** [comment]
@JohnNiang  我在部分主题出现了这问题，例如Next， 但是在Destiny主题中却没有问题，请请教下，什么是脏数据吗？能否提示下如何去检测脏数据呢？

**Comment by JohnNiang** [comment]
@xuzhougeng 需要您提供一个`详细`的日志信息。

**Comment by xuzhougeng** [comment]
@JohnNiang 感谢您的回复， 我这边直接把出错的标签给删了，先暂时避过了这个问题，姑且算是一种解决报错的方法吧，虽然治标不治本。

**Comment by BaoCheng-Zhang** [comment]
部署时候出现 ：2019-10-16 20:48:14.725  INFO 1976 --- [ main] run.halo.app.Application : No active profile set, falling back to default profiles: default

**Comment by ruibaby** [comment]
@BaoCheng-Zhang 正常日志，并非异常日志。
