### ISSUE TITLE
期望主题端支持全文搜索

### ISSUE THREAD

**Issue by JohnNiang** [halo-dev/halo#2637]
### 你当前使用的版本

2.0-SNAPSHOT

### 描述一下此特性

此前，Halo 主题端的文章搜索功能实现是基于数据库的字符串匹配实现的，无法完成全文搜索（模糊搜索和搜索结果高亮等功能），且搜索效率较低。

目前社区里有非常多的全文搜索引擎，例如：

- https://github.com/apache/lucene
- https://github.com/elastic/elasticsearch
- https://www.meilisearch.com/

我们期望 Halo 2.0 能够实现一个基础的全文搜索引擎。由于其他搜索引擎需要额外部署，我们可以考虑实现对应的插件去和搜索引擎集成。

因为 lucene 可作为库引入 Halo，所以我们可以考虑将 lucene 作为 Halo 默认全文搜索的实现。

### 附加信息

/kind feature
/area core
/milestone 2.0

**Comment by ruibaby** [comment]
Ref https://github.com/halo-dev/halo/issues/2425

**Comment by ruibaby** [comment]
已经为主题端创建了插件：https://github.com/halo-sigs/plugin-search-widget

届时，主题开发者只需要使用 JavaScript 调用 `SearchWidget.open()` 即可。可以保证所有适配了此插件的主题搜索表现一致，也无需单独实现搜索功能。

**Comment by ruibaby** [comment]
Halo 已经在后端使用 Lucene 支持了全文搜索，https://github.com/halo-dev/halo/pull/2675

主题端可使用 <https://github.com/halo-sigs/plugin-search-widget>

/close
