### ISSUE TITLE
完善系统提供的 Console 仪表盘小组件

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#2649]
### 你当前使用的版本

2.0.0-alpha.3

### 描述一下此特性

目前系统提供的功能已经基本完善，期望完善仪表盘小组件的功能和优化样式，以及为系统核心资源提供必要的小组件。

/area console
/kind improvement
/assign

**Comment by ruibaby** [comment]
计划内置以下组件：

1. 文章
    -  已发布数量
    - 近期发布文章列表
    - 当前登录用户的发布（我的发布）
2. 评论
    - 已发布数量
    - 新评论列表
3. 用户
    - 注册用户数
    - 最近登录用户
4. 其他
    - 整站浏览量
    - 快捷访问组件
5. ...

**Comment by JohnNiang** [comment]
需要注意的是：最近文章仪表显示的数据包含了已删除的文章数据。建议再优化的时候过滤已删除的文章。
