### ISSUE TITLE
maven  gradle 

### ISSUE THREAD

**Issue by whbq** [halo-dev/halo#265]
之前的maven 版本还在吗

**Comment by JohnNiang** [comment]
虽然能够回溯到使用 Maven 的版本，但是会缺失很多功能。

请问使用 gradle 遇到了什么问题了么？

**Comment by whbq** [comment]
ok,没有什么关系，只是由于工作的原因，对于gradle不那么熟练。当然这个没有任何关系。

**Comment by JohnNiang** [comment]
Gradle 使用起来和 Maven 很类似，本项目中 Gradle 的复杂度很小，开发的时候最经常使用：

1. ./gradlew bootRun 启动项目
2. ./gradlew clean build 构建项目
3. ./gradlwe check 或者 test 测试项目

一般来讲都会高度依赖 IDE 的，不会手动执行它们。
