### ISSUE TITLE
gardle 构建失败

### ISSUE THREAD

**Issue by PeiRunWu** [halo-dev/halo#2664]
### Your current Halo version

1.6

### Describe this feature

![image](https://user-images.githubusercontent.com/42695882/200216345-f8ad77d5-f543-4195-b939-f1eea57cb9fb.png)

**Comment by guqing** [comment]
你应该是下载错了源码，1.6的源码位于分支 release-1.6 https://github.com/halo-dev/halo/tree/release-1.6
从日志可以看出依赖的spring boot 版本是 3.0.0-RC1，这是 2.0 的源码，它最低要求 jdk 17 才能运行

**Comment by JohnNiang** [comment]
/close 

Please feel free to reopen this issue if you have any problems.
