### ISSUE TITLE
Markdown编辑器支持非图片附件

### ISSUE THREAD

**Issue by FynnFbc** [halo-dev/halo#2673]
### 你当前使用的版本

Halo 1.6

### 描述一下此特性

希望能在编辑器中添加非图片的附件支持
上传文件到云存储平台，添加附件后的链接能直接下载

**Comment by ruibaby** [comment]
相关的需求：https://bbs.halo.run/d/3096-好久不见我来踩20的雷了/14

**Comment by ruibaby** [comment]
/assign

我将实现从附件库选择附件之后自动以超链接的方式显示。

**Comment by knightbreeze1** [comment]
123456789
