### ISSUE TITLE
期望支持文章类型和标签的复合筛选

### ISSUE THREAD

**Issue by intoyang** [halo-dev/halo#2679]
### 你当前使用的版本

2.0 alpha.4

### 描述一下此特性

目前仅支持文章类型和标签的单一维度筛选，希望支持复合筛选提高查找精度。
如，选择 A 类型后，支持进一步选择一个或多个标签。

进一步考虑：
类型栏无论何时都需要完整显示；但点击选中某类型后，标签栏可以只显示当前类型下的标签而非全部；
可以对选中的类型或标签应用不同的样式，如添加背景色，区分于未选中的项目。

### 附加信息

/kind feature

**Comment by ruibaby** [comment]
你指的是 Console 端还是主题端？

主题端有一个一样的讨论：https://github.com/halo-dev/halo/issues/2559

**Comment by intoyang** [comment]
主题端。

**Comment by intoyang** [comment]
> 你指的是 Console 端还是主题端？
> 
> 主题端有一个一样的讨论：#2559

主题端。

**Comment by intoyang** [comment]
抱歉，获取可以关闭本条，后续会在 #2559 中关注进展。
