### ISSUE TITLE
问题231还是存在，作者可以看一下自己的博客。

### ISSUE THREAD

**Issue by saxingz** [halo-dev/halo#268]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

#231  这个问题还有的。作者看一下自己的博客： https://ryanc.cc/archives/halo-docker

**Comment by JohnNiang** [comment]
作者的这个似乎没有问题了。

**Comment by saxingz** [comment]
> 作者的这个似乎没有问题了。

有问题的，我又确认了一下，你在QQ群里吗？我发图给你看

**Comment by JohnNiang** [comment]
我用手机测试的，晚上用电脑端的浏览器测试一下。

**Comment by JackyLee-CS** [comment]
可以通过meta标签解决，在 系统-博客设置-其他设置 的自定义head中加入 `<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">`

**Comment by saxingz** [comment]
> 可以通过meta标签解决，在 系统-博客设置-其他设置 的自定义head中加入 `<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">`

这是绕过了问题。。。请求失败的问题本身没有被解决。

**Comment by JohnNiang** [comment]
已经确定是 `halo-comment` 的问题。

我将尽力排查问题，尽快修复这个问题。

**Comment by JohnNiang** [comment]
@saxingz @JackyLee-CS 问题已经解决，等待发布 `halo-comment`。

https://github.com/halo-dev/halo-comment/issues/14

**Comment by JohnNiang** [comment]
请手动更新 halo-comment 至 1.0.6

**Comment by saxingz** [comment]
> 请手动更新 halo-comment 至 1.0.6

<#macro comment post,type>
    <#if !post.disallowComment!false>
        <script src="//cdn.jsdelivr.net/npm/vue@2.6.10/dist/vue.min.js"></script>
        <script src="//cdn.jsdelivr.net/gh/halo-dev/halo-comment@1.0.6/dist/halo-comment.min.js"></script>
        <halo-comment id="${post.id}" type="${type}"/>
    </#if>
</#macro>

汗，更新了这个，重新打包一点也不生效。 都过了好几天了， curl localhost也试过 - -，一直是1.0.5
