### ISSUE TITLE
期望可以在文章中插入视频/音频内容

### ISSUE THREAD

**Issue by intoyang** [halo-dev/halo#2684]
### 你当前使用的版本

2.0 alpha.4

### 描述一下此特性

目前支持插入图片，虽然可以上传视频/音频附件，但插入文章中未能识别。
同时希望支持在附件库预览这些文档，参考 #1923 。

### 附加信息

/kind feature

**Comment by jiangmiemie** [comment]
刚升级halo2，同求视频/音频附件
