### ISSUE TITLE
期望设置头像或站点背景图片时支持裁剪及预览

### ISSUE THREAD

**Issue by intoyang** [halo-dev/halo#2688]
### 你当前使用的版本

2.0 alpha.4

### 描述一下此特性

当上传图片并非默认规格时，会造成头像被拉伸或背景图片局部显示。

1. 期望在自定义图片时，提供裁剪框，固定长宽比（如当前 2.0 背景图比例为 5:1 ）且有最小尺寸限制，以防图片扭曲或模糊；
2. 裁剪完成后支持进行头像/背景预览，点击确认后生效，支持重新裁剪。

### 附加信息

/kind improvement

**Comment by ruibaby** [comment]
我建议使用以下解决方案：

1. 上传组件需要支持图片的基本编辑。
2. 至于用户头像，我建议不要直接从附件库选择，因为某些用户可能并没有附件库的权限，可以提供单独的接口上传头像。此外，或许可以专门建立一个头像的附件库分组。

/cc @halo-dev/sig-halo

**Comment by ruibaby** [comment]
@halo-dev/sig-halo cc
