### ISSUE TITLE
主题端支持异常页面模板

### ISSUE THREAD

**Issue by wan92hen** [halo-dev/halo#2690]
### 你当前使用的版本

2.0.0-alpha.4

### 描述一下此特性

当访问站点出现 404、500 等错误时，可以使用主题中提供的错误页面模板，如 1.x 版本中的 `404.ftl`、`500.ftl`。

**Comment by JohnNiang** [comment]
Hi @guqing, are you still working on it? If you don't have enough time, I'm willing to save your time : P

**Comment by guqing** [comment]
> Hi @guqing, are you still working on it? If you don't have enough time, I'm willing to save your time : P

help me⛹️‍♀️
