### ISSUE TITLE
halo删除又拍云附件报错

### ISSUE THREAD

**Issue by yaoggwork** [halo-dev/halo#2691]
### 是什么版本出现了此问题？

1.6.0

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

使用了又拍云存储上传附件，附件可以在博客正常使用，在云存储也可以正常查看图片，但是在博客后台删除附件就会报错，Attachment was not found or has been deleted，但是呢刷新云存储文件管理会发现附件也删除了，不知道大家有没有遇到这个问题
右键删除/api/admin/attachments报404
![image](https://user-images.githubusercontent.com/117552593/201238201-222186b1-b02c-4957-9923-fea4f0e1219a.png)
通过批量的加号删除当个附件/api/admin/attachments报500
![image](https://user-images.githubusercontent.com/117552593/201238798-19e39200-f866-43e3-a59d-43ff236da9b3.png)

**Comment by JohnNiang** [comment]
/triage duplicate

Please see https://github.com/halo-dev/halo/issues/2603 for more.

顺便说一下，该问题已经被修复，将会在 Halo 1.6.1 和 Halo 1.5.6 中发布。

**Comment by JohnNiang** [comment]
Please see the latest releases:
- https://github.com/halo-dev/halo/releases/tag/v1.5.6
- https://github.com/halo-dev/halo/releases/tag/v1.6.1

/close
