### ISSUE TITLE
增加附件本地存储位置的配置

### ISSUE THREAD

**Issue by JackieDark** [halo-dev/halo#2703]
### 你当前使用的版本

1.6.0

### 描述一下此特性

选择附件为本地存储后可以支持配置存储位置，或者通过docker启动配置变量实现。这样可以支持单独挂载的盘存储附件

**Comment by ruibaby** [comment]
目前 1.x 暂不考虑支持这个特性，建议自建 minio 来实现这样的需求。

/kind feature
