### ISSUE TITLE
希望加入专题功能

### ISSUE THREAD

**Issue by RiverChu0** [halo-dev/halo#2713]
### 你当前使用的版本

1.6.0

### 描述一下此特性

希望加入专题功能。
有时候写一些系列教程，或者需要日积月累记录的一类信息。这很有用。
比如：xx从入门到精通。这样可以起一个专题，不断地往此专题添加文章。查看此专题就可以查看所有与之相关的文章。妙哉

**Comment by JohnNiang** [comment]
/kind feature

非常好的建议！不过可以提供一些参考么。详细的功能细节可以帮大家理解这个功能，更有助于快速推进。

顺便提一下，我们可能不会在 1.x 上添加新功能了，但是在 2.x 上添加新功能的。

**Comment by RiverChu0** [comment]
> /kind feature
> 
> 非常好的建议！不过可以提供一些参考么。详细的功能细节可以帮大家理解这个功能，更有助于快速推进。
> 
> 顺便提一下，我们可能不会在 1.x 上添加新功能了，但是在 2.x 上添加新功能的。

咋说呢，其实我觉得可以类似csdn的专栏功能。功能可以是一开始想写一系列相关的文章而建一个专题，是一个长期持续的写作，这样可以方便查看这个专题下所有的文章。也可以是新建，把一些现有的有关的文章加入，形成一个专题。这样看起来会方便许多。我经常记着相关的东西，记得多了，甚至不记得前面已经记过，等发现的时候，可以重新整理。

我的写作可能是自己有时心血来潮认真的写，也有可能是看到别人好的文章知识，快速复制进自己的博客。

比如ps、idea等各种软件的用法及技巧，又或者是一些有用的代码，这些都是需要日积月累的，我经常可能看到或者无意中发现软件的某个功能或者做了一个实例，就想快速记录下来方便日后查看。因为这些知识是零碎的，有用的，也容易忘记的。随着时间的增长，我们写了太多零碎的东西，等日后想起来再用的时候，可能就记得一个模糊的印象，如果仅仅单靠记忆中的关键词去搜索，效果不是很好。

这时我希望养成一个习惯，比如最近在学Ps教程，当我看到有用的Ps知识时，就想把它记录。起一个名字：ps知识收集、ps实例收集，这样的名字(专题)，写完后快速把它添加进去。日后有时间可以回来慢慢细品，温故而知新。

根据目前的版本，本来想通过标签来做这个事情，但发现后台文章搜索并不支持按标签搜索文章。所以产生一个专题功能的想法。我觉得可以做，类似于分类功能，但又比分类随意，也可以隐藏或者公开。

这就是我脑中的想法啦，这也是零碎的。如果开发要实现这样的功能，开发者也会有自己的理解。

**Comment by liuzhihang** [comment]
用分类不能解决么，我都是分类

**Comment by ruibaby** [comment]
Halo 2.17 已经支持将分类隐藏或者设置单独的渲染模板，可以利用这个特性配合主题抽象出一些文章集合。

https://github.com/halo-dev/halo/releases/tag/v2.17.0

/close
