### ISSUE TITLE
群晖docker安装后不能打开ip:端口号

### ISSUE THREAD

**Issue by FlatwormUnique** [halo-dev/halo#2717]
### What is version of Halo has the issue?

2.0 beta

### What database are you using?

H2

### What is your deployment method?

Docker

### Your site address.

https://nas.chiphello.com:65003/

### What happened?

不能打开“ip:端口号”，但是可以进入“ip:端口号/console/”，错误提示如图：
![屏幕截图 2022-11-17 190503](https://user-images.githubusercontent.com/85718974/202590746-e5437a2e-2dcb-4d7d-969a-0828b6eb2ec2.jpg)

![屏幕截图 2022-11-18 085301](https://user-images.githubusercontent.com/85718974/202591406-08a40578-2f55-4ed4-a451-2daa639ab584.jpg)

**Comment by guqing** [comment]
登陆到console安装一个主题并启用它就行了，beta.1版本目前没有默认内置主题，下个版本就不需要此步骤了🦍

**Comment by FlatwormUnique** [comment]
> 

您好，谢谢您的回复，可是，console页面虽然能打开，但是没办法登录

**Comment by JohnNiang** [comment]
> 您好，谢谢您的回复，可是，console页面虽然能打开，但是没办法登录

- 点击”登录“之后出现什么错误？
- 以及查看错误日志

**Comment by FlatwormUnique** [comment]
> > 您好，谢谢您的回复，可是，console页面虽然能打开，但是没办法登录
> 
> * 点击”登录“之后出现什么错误？
> * 以及查看错误日志

![屏幕截图 2022-11-18 202731](https://user-images.githubusercontent.com/85718974/202705231-3b360c79-f3cc-47dd-a641-15da6daa40a9.jpg)
环境变量里面添加了yong'h用户名和密码，登录时，终端机不显示任何错误，只是提示密码不对。

**Comment by FlatwormUnique** [comment]
不好意思，见笑了，重新认真看了下文档，在日志中找到了password，谢谢老大的回复

**Comment by JohnNiang** [comment]
/close

我将关闭当前 issue。如果有任何问题可随时重新打开 issue。
