### ISSUE TITLE
Console 的文章编辑页面支持 returnTo 参数

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#2724]
### 你当前使用的版本

2.0.0-beta.2

### 描述一下此特性

在 Console 的文章编辑页面支持添加 returnTo 参数，作用为指定发布完成后的跳转位置，默认为 Console 的文章管理列表。此功能的场景主要是提供给主题端在文章详情页面添加编辑入口，编辑完成之后可以跳转回文章详情页面，大致流程为：

1. 主题端构造一个 Console 文章编辑页面的链接按钮，如：`/console#/posts/editor?name=7826ac16-98b2-4456-a475-7a30cb203fe0&returnTo=http://localhost:8090/archives/hello`
2. 发布完成之后需要判断是否带有 `returnTo` 参数，如果有则重定向到 `returnTo` 参数提供的地址。否则跳转到文章管理页面。

/kind feature
/area console
/assign

**Comment by ruibaby** [comment]
此场景满足的条件需要完成 https://github.com/halo-dev/halo/issues/2676。但 Console 端可以先实现

**Comment by JohnNiang** [comment]
我记得 post.status 中保存了 permalink，建议添加参数：returnTo=true | false，让 console 决定是否跳转到 permalink。

如果 returnTo 可随意设置跳转 URL，可能会跳转到伪造页面。

**Comment by ruibaby** [comment]
> 我记得 post.status 中保存了 permalink，建议添加参数：returnTo=true | false，让 console 决定是否跳转到 permalink。
> 
> 如果 returnTo 可随意设置跳转 URL，可能会跳转到伪造页面。

好！那么这个名字我将改为 returnToView
