### ISSUE TITLE
管理系统增加一个记住密码功能

### ISSUE THREAD

**Issue by betwowt** [halo-dev/halo#2725]
### 描述一下此特性

在常用设备上无需再次登陆

**Comment by it985** [comment]
浏览器都有保存号密自动填充吧

**Comment by JohnNiang** [comment]
/triage duplicate

See https://github.com/halo-dev/halo/issues/2362 for more.

**Comment by ruibaby** [comment]
> 浏览器都有保存号密自动填充吧

他的意思是保持登陆会话。

/close

**Comment by it985** [comment]
sogo，懂了
