### ISSUE TITLE
将 Halo 的 bootJar 和 plainJar 发布到 maven 中央仓库

### ISSUE THREAD

**Issue by guqing** [halo-dev/halo#2730]
### Your current Halo version

2.0.0-alpha.4

### Describe this feature

将 Halo 的 plain jar 发布到 maven 中央仓库 使插件能在 build.gralde 中引用以替代现在的 jar 包依赖方式
将 bootJar 也发布到仓库可以使用 https://github.com/guqing/gradle-plugin-halo 的 `gralde halo server` 命令来调试和运行插件

### Additional information

/kind feature
/area core
/priority critical-urgent

**Comment by JohnNiang** [comment]
建议提前规划一下：
- 公共依赖
- 公共模块

目前，我们应该只需要发布这两者至 Maven 仓库。

**Comment by guqing** [comment]
bom 项目 https://github.com/halo-sigs/halo-dependencies

**Comment by guqing** [comment]
目前 bootJar 已不需要再发布到 maven了，插件开发时使用 docker 启动 halo 即可，不再依赖 bootJar
