### ISSUE TITLE
主题端文章列表排序不固定

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#2734]
### 是什么版本出现了此问题？

2.0.0-beta.2

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Fat Jar

### 发生了什么？

主题端首页 / 分类归档页 / 标签归档页的文章列表的排序不固定，多次刷新可以观测到顺序不一致。

/kind bug
/area core

**Comment by guqing** [comment]
/assign
需要将列表查询时的 flatMap 替换为 concatMap
