### ISSUE TITLE
手动刷新主题资源（/reload-setting），在没有设置 settingName 的时候无法刷新成功

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#2735]
### 是什么版本出现了此问题？

2.0.0-beta.2

### 使用的什么数据库？

Other

### 使用的哪种方式部署？

Docker

### 发生了什么？

详细复现方式：

1. 创建一个主题资源，但不设置 `settingName` 字段。
2. 设置 `settingName`，和创建 `settings.yaml`，然后在 Console 端的主题设置手动点击 `刷新设置表单` 按钮。
3. 检查是否出现表单设置项。

Ref #https://github.com/halo-dev/halo/pull/2456

此外，目前 `/apis/api.console.halo.run/v1alpha1/themes/{name}/reload-setting` 接口不仅可以刷新表单设置项，可会同时更新主题配置文件定义。那么建议将 `reload-setting` 改为 `reload`，逻辑改为先更新主题配置文件资源，再更新设置表单资源。

/kind improvement
/area core

**Comment by guqing** [comment]
先根据主题名称获取数据库 Theme 然后判断是否更改了 settingName 和 configmapName ，是则删除它们，然后重新获取 settings.yaml 创建/更新到数据库
