### ISSUE TITLE
图片上传错误，不是Ngnix的问题

### ISSUE THREAD

**Issue by Undividedhl** [halo-dev/halo#274]
当我上传10张以内的图片时，该情况并没有发生，我还没有配置Ngnix，是通过IP访问的；当我一次性选择了20多张图片时，会有三四张图片上传错误，也许是我太小白搞不定，在我翻看了论坛和文档后，发现只有Ngnix问题的解答，我还是决定在这里提一下

**Comment by JohnNiang** [comment]
一次性上传文件的数量可能视你的服务器配置而定。
