### ISSUE TITLE
如何从wordpress移植到halo

### ISSUE THREAD

**Issue by kaigu1990** [halo-dev/halo#277]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [x] 请求技术支持

你好，请教个问题：

我想从wordpress移植到halo，我可以处理好wordpress的xml文件并生成一个个md文档和各个文章的信息，然后手动加到halo上；但是现在有个问题是如何能自定义我上传文章的时间呢，我想保证日期和之前在wordpress
一样，同时发布的文章能设定url链接保持跟原来在wordpress一样吗？

谢谢

**Comment by JohnNiang** [comment]
目前暂时没有适配 WP 的迁移。

只能手动迁移，至于自定义文章时间，我们会尽快处理这个问题。

**Comment by kaigu1990** [comment]
谢谢，另外再请教下，能否支持文章URL自定义，在迁移的时候，手动更改URL保持跟原来一致呢？

**Comment by JohnNiang** [comment]
目前是支持自定义 URL 的。理论上文章的数据都是支持自定义的，只是管理端暂时没有提供这样的选项。

**Comment by kaigu1990** [comment]
那能否简单告知下如何在服务器上修改，如果有规律的话，可以用脚本批量替换下；我对halo非常感兴趣，如能解决迁移的问题，我打算加入halo组织啦

**Comment by JohnNiang** [comment]
你能提供一下 WP 导出的部分数据（脱敏）么？我考虑做一个迁移 WP 的功能。

**Comment by kaigu1990** [comment]
WP导出的xml文件可以吗？里面有文章的所有信息，其他还要啥吗？

**Comment by JohnNiang** [comment]
包含文章信息，分类以及标签的文件，我只需要样例数据即可，你可以精简。

> 建议发送到我的邮箱。

**Comment by kaigu1990** [comment]
好的OK，我精简下发你，如有问题或者缺信息的，可以再问我

**Comment by kaigu1990** [comment]
不好意思，我在你Github上没找到邮箱地址，能方便提供下吗？我已整理好了，可以发你WP导出的数据

**Comment by JohnNiang** [comment]
johnniang@riseup.net

**Comment by kaigu1990** [comment]
已发送邮箱，麻烦你了~多谢

**Comment by JohnNiang** [comment]
@kaigu1990 不好意思，我并没有收到你的邮件（检查过垃圾邮件目录）。

**Comment by kaigu1990** [comment]
@JohnNiang ，邮件提示这个：
![image](https://user-images.githubusercontent.com/22772592/63037648-0e224200-bef2-11e9-9efc-8ec797a8e510.png)
不确定何时能发送
要不我直接在Github上发个链接吧，你下载后我再删了也行
[http://www.bioinfo-scrounger.com/data/wordpress.2019-08-15.xml](http://www.bioinfo-scrounger.com/data/wordpress.2019-08-15.xml)

**Comment by JohnNiang** [comment]
已经下载好了，也已经删除了该链接。

**Comment by JohnNiang** [comment]
你好！你发给我的是你的 rss.xml，这个是用于订阅用的。对于我们开发者来说是没有用的。

**Comment by kaigu1990** [comment]
不好意思，我对于这方面不是很懂，我看里面有文章信息以为可以用；那样例数据需要的是WP里哪种类型的文件呢，我暂时在后台界面里只找到这个~

**Comment by ruibaby** [comment]
@kaigu1990 有个导出功能

**Comment by kaigu1990** [comment]
@ruibaby ，你好，我点击导出的是WP后台管理中的导出功能，你看看是不是下面截图所示的呢
![image](https://user-images.githubusercontent.com/22772592/63067520-f5417d00-bf41-11e9-867e-a292d0696f30.png)
如果不是的话，你说的导出是导出sql数据库吗

**Comment by ruibaby** [comment]
@kaigu1990 没错就是这个，导出所有内容

**Comment by kaigu1990** [comment]
@ruibaby ，这个大致跟昨晚的一样，我刚导出了下，把文件链接直接在这里发啦
[http://www.bioinfo-scrounger.com/data/wordpress.2019-08-15.xml](http://www.bioinfo-scrounger.com/data/wordpress.2019-08-15.xml)
PS. 我做了一部分的删减

**Comment by wszf** [comment]
@kaigu1990 试试这种方式https://www.wszf.me/archives/wordpress%E6%95%B0%E6%8D%AE%E8%BF%81%E7%A7%BB%E5%88%B0Halo

**Comment by kaigu1990** [comment]
你好；我刚刚试下了，我把wordpress的数据库存入了服务器的mysql中，并且也运行了上述网站内的代码，也在mysql中确定了post表确实有文章内容；但是我的后台管理中打开其中任意某篇文章或者编辑文章都是空的，显示：The page you are looking for is missing提示信息；请问下这是什么原因呢？

**Comment by wszf** [comment]
@kaigu1990 把`concat('/wp/',year(wpost.post_date),'/',LPAD(month(wpost.post_date), 2, 0),'/',LPAD(DAY(wpost.post_date),2,0),'/',wpost.id,'.html') AS url`
改为`concat('/wp-',year(wpost.post_date),'-',LPAD(month(wpost.post_date), 2, 0),'-',LPAD(DAY(wpost.post_date),2,0),'-',wpost.id) AS url`就可以了，该项目不支持多级目录,如果想用多级目录，请参考https://github.com/wszf/halo/commit/b1d6dcbb4122bc2aa126189d559438dfec973f8f

**Comment by kaigu1990** [comment]
@wszf ，我按照你的修改了导入文章数据代码，如下：
`INSERT INTO posts
SELECT
	0 AS `type`	-- 类型
	,wpost.id AS id
	,wpost.post_date AS create_time	-- 文章创建时间
	,0 AS deleted
	,wpost.post_modified AS update_time	-- 文章更新时间
	,0 AS create_from
	,0 AS disallow_comment	-- 评论状态
	,CURRENT_TIMESTAMP AS edit_time	-- 文章编辑时间
	,wpost.post_content AS format_content	-- 格式化后内容
	,0 AS likes
	,'' AS original_content	-- markdown源
	,'' AS password
	,(CASE WHEN wpost.post_status = 'publish' THEN 0 ELSE 1 END) AS status	-- 文章状态
	,'' AS summary	-- 摘要
	,'' AS template	-- 模板
	,'' AS thumbnail
	,wpost.post_title AS title
	,0 AS top_priority	-- 置顶
	,concat('/wp-',year(wpost.post_date),'-',LPAD(month(wpost.post_date), 2, 0),'-',LPAD(DAY(wpost.post_date),2,0),'-',wpost.id) AS url	-- 文章URL
	,0 AS visits
FROM
	wp.wp_posts wpost
WHERE wpost.post_parent = 0
AND wpost.post_type != 'nav_menu_item'
AND wpost.post_type != 'page'
`
然后delete posts表，重新导入文章数据

结果还是打不开网址，网址显示的是：http://192.168.1.3:8090/archives//wp-2019-10-04-858，报错信息还是：The page you are looking for is error

请问下这是什么原因呢？谢谢

**Comment by JohnNiang** [comment]
@kaigu1990 建议看看后台有无错误日志信息。

**Comment by kaigu1990** [comment]
@JohnNiang Hi，我看了下log文件，看不太懂，能帮我瞧瞧嘛？
[spring.log](https://github.com/halo-dev/halo/files/3744742/spring.log)

**Comment by JohnNiang** [comment]
你应该用 wpid 访问文章

**Comment by JohnNiang** [comment]
```sql
INSERT INTO posts
SELECT
	0 AS `type`	-- 类型
	,wpost.id AS id
	,wpost.post_date AS create_time	-- 文章创建时间
	,0 AS deleted
	,wpost.post_modified AS update_time	-- 文章更新时间
	,0 AS create_from
	,0 AS disallow_comment	-- 评论状态
	,CURRENT_TIMESTAMP AS edit_time	-- 文章编辑时间
	,wpost.post_content AS format_content	-- 格式化后内容
	,0 AS likes
	,'' AS original_content	-- markdown源
	,'' AS password
	,(CASE WHEN wpost.post_status = 'publish' THEN 0 ELSE 1 END) AS status	-- 文章状态
	,'' AS summary	-- 摘要
	,'' AS template	-- 模板
	,'' AS thumbnail
	,wpost.post_title AS title
	,0 AS top_priority	-- 置顶
	,concat('wp-',year(wpost.post_date),'-',LPAD(month(wpost.post_date), 2, 0),'-',LPAD(DAY(wpost.post_date),2,0),'-',wpost.id) AS url	-- 文章URL
	,0 AS visits
FROM
	wp.wp_posts wpost
WHERE wpost.post_parent = 0
AND wpost.post_type != 'nav_menu_item'
AND wpost.post_type != 'page'
```

**Comment by kaigu1990** [comment]
Hi，wpid访问文章是什么意思呢，我不太懂诶；你刚发的sql脚本，是要让我重新到如下wp的数据库嘛

**Comment by kaigu1990** [comment]
@JohnNiang  Hi，我试了下；还是上述一样的报错哈

**Comment by JohnNiang** [comment]
因为拼接 url 的时候，多了一个 / 符号

**Comment by kaigu1990** [comment]
@JohnNiang 嗯，我也发现这个问题，所以我在打开网页的时候删掉了下那个/符号；但是还是提示The page you are looking for is error；还是说要在数据库里修改？

**Comment by JohnNiang** [comment]
或者，提供一些 post 表的数据呢。

**Comment by kaigu1990** [comment]
@JohnNiang 嗯，好的；我刚好有个test.sql文件（截了一部分post的数据），我发你哈（改了下文件的后缀）；[test.txt](https://github.com/halo-dev/halo/files/3744875/test.txt)

**Comment by JohnNiang** [comment]
可以给我一个截图么？halo.posts

**Comment by kaigu1990** [comment]
这是什么文件呢，是在mysql数据库中的posts表嘛？

**Comment by JohnNiang** [comment]
@kaigu1990 是的，转换之后的数据。

**Comment by kaigu1990** [comment]
![image](https://user-images.githubusercontent.com/22772592/67112253-5c610380-f209-11e9-8a96-22b63f77bc23.png)
![image](https://user-images.githubusercontent.com/22772592/67112273-671b9880-f209-11e9-89c8-d2dc938d501d.png)

**Comment by JohnNiang** [comment]
select url from posts

**Comment by kaigu1990** [comment]
好的，![image](https://user-images.githubusercontent.com/22772592/67113419-0b064380-f20c-11e9-9b8d-0c3ceb3f52cf.png)

**Comment by JohnNiang** [comment]
你看，url 仍然有 /，你需要去除这个字符才行，或者执行我提供的那个 sql

**Comment by kaigu1990** [comment]
Hi，不好意思，又来打扰下了；请问下，迁移过来的文章能在后台管理系统中再次编辑的嘛？我编辑某个文章，发现里面是空的，所以来请教下~

**Comment by ruibaby** [comment]
@kaigu1990 并不建议用这种方式迁移。因为语法把 html 文档转换为 markdown 文档。所以 markdown 文档为空，你编辑的时候就没有数据了。

**Comment by ruibaby** [comment]
@kaigu1990 建议找个导出 markdown 的插件，先在 wp 上导出为 markdown 文档，然后再导入到 halo。

**Comment by kaigu1990** [comment]
@ruibaby Hi，意思是：我先用wp上导出每个文章markdown格式的内容，然后再逐一复制黏贴到每篇对应的文章中嘛

**Comment by ruibaby** [comment]
@kaigu1990 halo 提供导入markdown

**Comment by kaigu1990** [comment]
@ruibaby 嗯嗯，我刚试了下，导入后是生成一篇新发布的文章；那我如果想保持跟原来博客中的相同发布日期、标签分类以及URL等，我需要再将每篇文章再手动改动下是吗？

**Comment by ruibaby** [comment]
@kaigu1990 如果没有类似 hexo 那种源信息的话，只能自己改了。
我们后面会提供 wp 的迁移工具，会方便很多。

**Comment by kaigu1990** [comment]
@ruibaby 好的，非常感谢，Halo越来越完善啦，我再琢磨琢磨哈

**Comment by AlexVincent525** [comment]
有新消息吗 😃

**Comment by ruibaby** [comment]
> 有新消息吗 😃

新版本做了迁移工具，请等待发布。

**Comment by AlexVincent525** [comment]
是否已发布相关工具？

**Comment by ruibaby** [comment]
> 是否已发布相关工具？

很遗憾，这功能夭折了。后续如果 Halo 出了插件机制，那么会第一时间开发。另外，或许可以从 wp 插件入手。

**Comment by JohnNiang** [comment]
@AlexV525 可以试试这个工具：https://github.com/wangzhen-fit2cloud/wp2halo
