### ISSUE TITLE
Upgrade to PF4J 3.8.0

### ISSUE THREAD

**Issue by JohnNiang** [halo-dev/halo#2771]
### Your current Halo version

2.0.0-SNAPSHOT

### Describe this feature

PF4J has released [3.8.0](https://github.com/pf4j/pf4j/releases/tag/release-3.8.0) for a while, please @guqing help us to see if it is suitable for upgrading.

### Additional information

/kind improvement
/area core

**Comment by guqing** [comment]
可以直接升级，参考 https://github.com/pf4j/pf4j/compare/release-3.7.0...release-3.8.0
