### ISSUE TITLE
匿名用户需要限制部分编辑功能

### ISSUE THREAD

**Issue by wan92hen** [halo-dev/halo#2775]
### 你当前使用的版本

2.0.0-rc.1

### 描述一下此特性

在 rc.1 版本中，匿名用户会出现用户列表中，并且该用户能进行的操作与其他用户相同。作为系统内置的特殊用户，应当对其进行特殊处理。

可参考的处理方式有：
1. 控制台隐藏该用户；
2. 限制对该用户的部分操作，包括修改密码、删除；

**Comment by JohnNiang** [comment]
1. 修改匿名用户的密码不影响匿名用户的功能。
2. 删除匿名用户后，可能会导致公开资源无法访问。
3. 重启 Halo 后会自动重置匿名用户信息。
4. 建议不隐藏匿名用户，未来方便给匿名用户分配更多的权限，或者直接禁用匿名用户。

**Comment by guqing** [comment]
关于第二点，匿名用户的密码是否被修改或清空都不会对此用户产生影响，匿名用户不需要绑定任何用户也具有 anoymous 角色
匿名用户不允许登录，但可以为其分配角色，如果分配了角色则任何用户都将拥有匿名用户拥有的所有权限

**Comment by wan92hen** [comment]
> 关于第二点，匿名用户的密码是否被修改或清空都不会对此用户产生影响，匿名用户不需要绑定任何用户也具有 anoymous 角色 匿名用户不允许登录，但可以为其分配角色，如果分配了角色则任何用户都将拥有匿名用户拥有的所有权限

密码实际不起作用的情况下，不是更应该把修改密码功能在控制台屏蔽掉吗？

**Comment by guqing** [comment]
> > 关于第二点，匿名用户的密码是否被修改或清空都不会对此用户产生影响，匿名用户不需要绑定任何用户也具有 anoymous 角色 匿名用户不允许登录，但可以为其分配角色，如果分配了角色则任何用户都将拥有匿名用户拥有的所有权限
> 
> 密码实际不起作用的情况下，不是更应该把修改密码功能在控制台屏蔽掉吗？

这就要看怎么理解了，站在一个 User 模型的角度上，它是具有密码属性的，但是站在系统的角度上，每个人都是 annomousUser 是不允许登录到后台的

**Comment by chengfeiyue** [comment]
Anonymous User用户被删除之后，导致访问控制台页面报“资源不存在”。F12查看结果：
<img width="1340" alt="image" src="https://user-images.githubusercontent.com/49852751/217988937-4d3a6ba1-7cd6-4a14-bcdf-beb0ee681705.png">

![image](https://user-images.githubusercontent.com/49852751/217988887-a6a22bac-ebe7-4f50-9f8e-c66d59ac56f8.png)
建议屏蔽“资源不存在”

**Comment by ruibaby** [comment]
我将在 Console 端屏蔽 annomousUser 这个账户。

/assign

**Comment by wan92hen** [comment]
> 我将在 Console 端屏蔽 annomousUser 这个账户。
> 
> /assign

这样的话之前讨论过的自定义匿名用户的权限场景该如何处理？

**Comment by ruibaby** [comment]
> > 我将在 Console 端屏蔽 annomousUser 这个账户。
> 
> > 
> 
> > /assign
> 
> 
> 
> 这样的话之前讨论过的自定义匿名用户的权限场景该如何处理？

暂不考虑，当前这个匿名用户并没有实际的用途。
