### ISSUE TITLE
保存用户名重复的用户前端无报错提示

### ISSUE THREAD

**Issue by wan92hen** [halo-dev/halo#2776]
### 是什么版本出现了此问题？

2.0.0-rc.1

### 使用的什么数据库？

Other

### 使用的哪种方式部署？

Docker

### 发生了什么？

新建用户使用已经存在的用户名时，创建用户请求后端返回 `500` 错误，但是控制台页面没有对应的报错提示。

**Comment by ruibaby** [comment]
/kind improvement
/area console

等待 Console 配置这个特性 https://github.com/halo-dev/halo/pull/2741

**Comment by ruibaby** [comment]
已经在 https://github.com/halo-dev/console/pull/732 中支持。

/close
