### ISSUE TITLE
编辑角色信息未回显且不能正常提交

### ISSUE THREAD

**Issue by wan92hen** [halo-dev/halo#2778]
### 你当前使用的版本

2.0.0-rc.1

### 描述一下此特性

对 `super-role`、`guest` 两个内置角色进行编辑时，角色名及角色权限信息未回显到表单中。

同时修改一个已有角色时，如果只修改名称信息，可以正常提交并修改成功。如果同时修改了角色的权限信息，则不能正常提交，查看开发者工具无网络请求发出，控制台出现下面的 warning。
![image](https://user-images.githubusercontent.com/27671436/203959731-7e2316f5-a381-4e8d-839e-10cd501f9185.png)

**Comment by ruibaby** [comment]
应该是 `VTabs` 组件在切换标签之后销毁掉了其他标签的内容。导致在提交的时候 Form 组件不存在，所以无法提交。

/kind bug
/area console
/assign

**Comment by ruibaby** [comment]
此外，内置角色应该是不允许被编译的，可能需要在初始化这两个资源的时候加一个标识。

**Comment by wan92hen** [comment]
> 此外，内置角色应该是不允许被编辑的，可能需要在初始化这两个资源的时候加一个标识。

是的，类似 #2775 中的问题。本来是想提这个问题的，后面又发现非内置用户编辑也有问题就写到一起了。
