### ISSUE TITLE
文章设置中移除缩略图失效

### ISSUE THREAD

**Issue by lushwe** [halo-dev/halo#278]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

----

后台管理页面，文章设置中，有缩略图的文章，移除缩略图，保存不生效（缩略图删不了）
猜测：移除后，传的字段为 `null`，后台更新的时候忽略了该字段

**Comment by JohnNiang** [comment]
应该是这个原因。

**Comment by ruibaby** [comment]
已修复。
