### ISSUE TITLE
部署到云服务器访问异常

### ISSUE THREAD

**Issue by youngledo** [halo-dev/halo#2781]
### 是什么版本出现了此问题？

2.0

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

<img width="689" alt="1" src="https://user-images.githubusercontent.com/68590897/203983684-d3b97ed7-26c8-47be-9bcd-42d3805e7b92.png">
我部署在云服务器，使用内置的菜单连接发现跳转到http://localhost:8090/的地址，但实际我的云服务器肯定不是这个。相当于访问到我本机了。

**Comment by ruibaby** [comment]
请检查是否有提供 `HALO_EXTERNAL_URL` 环境变量。 https://docs.halo.run/2.0.0-SNAPSHOT/getting-started/install/docker

/kind support

**Comment by ruibaby** [comment]
@youngledo README 的快速开始是为了让大家可以在本地快速启动体验，正式安装文档请参考  https://docs.halo.run/2.0.0-SNAPSHOT/category/%E5%AE%89%E8%A3%85%E6%8C%87%E5%8D%97

> 是不是默认用了localhost导致的

没有提供 `HALO_EXTERNAL_URL` 变量的话，那就是 localhost。
