### ISSUE TITLE
向网站添加自定义资源、文件

### ISSUE THREAD

**Issue by LeviMarvin** [halo-dev/halo#2785]
### 你当前使用的版本

2.0.0-rc.1

### 描述一下此特性

直接在 halo 目录或指定目录放置自定义文件，访问http://<url>/<FILE>会自动返回/响应该自定义文件，这样可以实现 robots.txt，sitemap.xml 等功能

**Comment by guqing** [comment]
https://github.com/halo-sigs/plugin-sitemap

sitemap 可以用此插件自动生成，还有更多使用场景可以参考吗，如果不是大部分用户都需要的功能可以用插件实现

**Comment by ruibaby** [comment]
类似于 1.x 的静态存储。2.0 暂时确实没有考虑到此功能。

/kind feature

**Comment by LeviMarvin** [comment]
@guqing 比如用户可以通过添加自定义php文件实现API功能，亦或者做简单文件直链

**Comment by LeviMarvin** [comment]
> https://github.com/halo-sigs/plugin-sitemap
> 
> sitemap 可以用此插件自动生成，还有更多使用场景可以参考吗，如果不是大部分用户都需要的功能可以用插件实现

此插件通过上传安装时提示错误`Upload error`，后台日志很长，上面一部分没有记录：https://pastebin.com/Za9BhK3j

**Comment by guqing** [comment]
> 

到此连接重新下载安装即可 https://github.com/halo-sigs/plugin-sitemap/releases/tag/v1.0.0-alpha.3，已知问题一直没有发布版本导致

**Comment by JohnNiang** [comment]
Close in favor of <https://github.com/halo-dev/halo/issues/2785>.

/close
