### ISSUE TITLE
为主题和插件提供重置设置项（ConfigMap）的功能。

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#2789]
### 你当前使用的版本

2.0.0-rc.1

### 描述一下此特性

目前主题设置项某个字段发生了数据结构的变更，会导致前台异常，也会导致 Console 端的表单渲染异常 (FormKit Schema)，这个时候使用者无法进行下一步的操作，所以目前可以考虑提供一个重置的入口，用于删除 ConfigMap。

<img width="357" alt="image" src="https://user-images.githubusercontent.com/21301288/204181467-8b143729-4316-4412-ac2e-55790b5441ff.png">

/kind feature
/area console

**Comment by JohnNiang** [comment]
建议用 formkit 的默认值覆盖 ConfigMap 的值。

**Comment by ruibaby** [comment]
> 

现在不知道什么情况下要覆盖 ConfigMap 的值。

**Comment by JohnNiang** [comment]
可以专门为插件和主题提供重置（reset）接口。

主要流程：
1. 通过 formkit 获取默认值
2. 将获取到的默认值完全覆盖 ConfigMap 的 data 字段
3. 完成重置功能
