### ISSUE TITLE
Menu items from other menus appear in parent menu list

### ISSUE THREAD

**Issue by JohnNiang** [halo-dev/halo#2792]
### What is version of Halo has the issue?

2.0.0-SNAPSHOT

### What database are you using?

H2

### What is your deployment method?

Docker

### What happened?

As I mentioned in the title, here should not appear menu items from other menus.

![image](https://user-images.githubusercontent.com/16865714/204252534-a2046cc6-c500-44a9-bb69-95202184d954.png)

### Additional information

/kind bug
/area console

**Comment by ruibaby** [comment]
在最新版本（2.5.2）中没有复现此问题，可能在 2.0.0 之后的某个版本已经进行了修复。

/close
