### ISSUE TITLE
文章标题不能带有英文句号.

### ISSUE THREAD

**Issue by zql001** [halo-dev/halo#280]
文章标题不能带有英文句号.,如果有一个或者多个,会报错404,估计原因是数据库用了.作为层级分割,来自http://www.lt8.top      的博客

**Comment by jiangkang** [comment]
+1

**Comment by ruibaby** [comment]
@jiangkang 我们会在下一个版本解决这个问题。

**Comment by ruibaby** [comment]
已修复
