### ISSUE TITLE
系统启动时检查是否有 Jwt private 和 public key 没有需要生成

### ISSUE THREAD

**Issue by guqing** [halo-dev/halo#2803]
### Your current Halo version

2.0.0

### Describe this feature

现在 Jwt public 和 private key 是系统默认的读取 classpath， 应该修改为 `${halo.work-dir}`，并 JwtProperties 中检查是否存在，不存在则需要生成，或者如果能知道系统是首次初始化则只在首次初始化时生成。
这非常重要！

### Additional information

/area core
/kind improvement
/priority critical-urgent

**Comment by JohnNiang** [comment]
目前我们暂时没有使用到这两个 key，建议等 2.0 发布之后和个人令牌功能一起完成。

**Comment by JohnNiang** [comment]
暂时禁用掉 JWT 相关的功能来规避次问题。请参考：<https://github.com/halo-dev/halo/pull/2804>。
