### ISSUE TITLE
希望添加新特性

### ISSUE THREAD

**Issue by Guozht** [halo-dev/halo#281]
使用了一段时间Halo之后，感觉添加以下功能，应该可以有更好的体验。
1、添加文章置顶功能。
2、添加百度API推送功能，将文章单个或批量推送到百度搜索引擎。
3、添加数据导出功能，方便换服务器时数据的迁移。
- [ ] BUG 反馈
- [x] 添加新的特性或者功能
- [ ] 请求技术支持

**Comment by ruibaby** [comment]
@Guozht 1. 这个简单，已经预留了字段。2. 考虑考虑，这个本身在页面加段js就可以的，感觉不是有必要在代码中实现。3. 会有，但是貌似直接备份 .halo 文件夹更简单粗暴，参考https://bbs.halo.run/d/111

**Comment by ruibaby** [comment]
文章置顶已支持
