### ISSUE TITLE
为2.0添加用户注册功能

### ISSUE THREAD

**Issue by Hikz8** [halo-dev/halo#2813]
### 你当前使用的版本

2.0

### 描述一下此特性

目前除super-role外，只能通过super-role权限，后台创建角色，并修改密码

**Comment by JohnNiang** [comment]
目前仅收集到两个注册后的场景：

1. 方便用户评论。
2. 允许用户能够控制独立的资源，例如“多人上传模板和主题”。

可能无法完整地在 Halo 2.2.x 中实现。如果有任何新的想法，欢迎评论。

/milestone clear
