### ISSUE TITLE
访客角色后台点击个人资料弹窗无权限

### ISSUE THREAD

**Issue by Hikz8** [halo-dev/halo#2814]
### 是什么版本出现了此问题？

2.0

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker Compose

### 发生了什么？

创建访客角色后，登录并点击个人资料，个人资料可以正常修改，功能正常，但会弹窗无权限，弹窗或许多余了

**Comment by ruibaby** [comment]
这个问题似乎在 https://github.com/halo-dev/halo/pull/3067 和 https://github.com/halo-dev/console/pull/796 中已经修复了。

/close
