### ISSUE TITLE
前台回复留言

### ISSUE THREAD

**Issue by it985** [halo-dev/halo#2815]
### 你当前使用的版本

1.6

### 描述一下此特性

当前halo系统的回复功能，我觉得较弱，只能在后台回复评论。
在前台回复会提示 :`不能使用博主邮箱，如果你是博主，请登录管理端进行回复`
期望：可以给主题一个接口，使其在前端登录，然后进行回复功能
理由：回复评论登录管理端，个人觉得有点麻烦

**Comment by ruibaby** [comment]
目前 2.0 已经在评论支持登录访问，1.x 不打算再做新功能和变更。

https://github.com/halo-dev/halo/releases/tag/v2.0.0

/kind support

**Comment by it985** [comment]
> 目前 2.0 已经在评论支持登录访问，1.x 不打算再做新功能和变更。
> 
> https://github.com/halo-dev/halo/releases/tag/v2.0.0
> 
> /kind support

通过demo站，已知晓，此issue关闭，谢谢告知，愿halo越走越远
