### ISSUE TITLE
插件安装出现问题

### ISSUE THREAD

**Issue by MDQ0512** [halo-dev/halo#2817]
### 是什么版本出现了此问题？

2.0

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 在线站点地址

https://docs.mengorg.cn/

### 发生了什么？

安装https://github.com/halo-sigs/awesome-halo提供的插件时，使用拖拽插件会导致页面崩溃，使用资源管理器选择插件上传会提示上传错误，upload error。
已经安装的插件即使已经启用了，但是有的插件会在其他插件上传失败时，自动消失，10个插件仅有3个可以安装成功![image](https://user-images.githubusercontent.com/57866775/205031034-8a248175-70ce-4f49-aff5-9c5ff6cceb1d.png)

### 相关日志输出

```shell
日志文件下载地址https://cdn.flightadsb.mengorg.cn/_halo2_logs.txt
```

**Comment by ruibaby** [comment]
目前在 awesome-halo 维护的官方插件均已完成对 2.0 正式版的适配，如果有无法安装的，可以具体说明。社区提供的插件可能并未完成适配。具体原因可能是 https://github.com/halo-dev/halo/pull/2806

/triage needs-information

**Comment by ruibaby** [comment]
@MDQ0512 请问此问题有得到解决吗？

**Comment by ruibaby** [comment]
如果没有后续动态，我将关闭此 issue。

/close
