### ISSUE TITLE
后台添加博客地址修改功能

### ISSUE THREAD

**Issue by MDQ0512** [halo-dev/halo#2818]
### 你当前使用的版本

2.0

### 描述一下此特性

2.0以前的版本在博客设置--常规设置中一直都有修改博客地址的功能，可以根据需要随时修改域名
但是在2.0版本中。并没有此功能，一旦初始化以后域名就固定了，无法修改

**Comment by JohnNiang** [comment]
启动时配置环境变量可以随时更改，不过需要重启才能生效。

**Comment by ruibaby** [comment]
你可以重置容器并修改参数，只要挂载了 Halo 的工作目录和数据库的存储目录也不会导致数据丢失。相对于 1.x 的改动，这种方式更有利于 Halo 监听此 URL 的变化，然后对系统内的资源同步固定链接（文章、分类、标签等，内容中已保存的链接除外）。而且修改域名并不是经常性的行为。

/kind support

**Comment by JohnNiang** [comment]
- 通过 Docker 安装
    ![image](https://user-images.githubusercontent.com/16865714/205688067-38758de2-630b-4880-a44e-05ae50626602.png)
- 通过 Docker Compose 安装
    ![image](https://user-images.githubusercontent.com/16865714/205688198-3f78591e-9fb5-4449-9c89-024d5878bd9b.png)

**Comment by Hanze-Li** [comment]
@MDQ0512 你别听JohnNiang瞎说，其实只要把docker-compose.yaml的地址修改一下，再次docker-compose up -d就可以了
