### ISSUE TITLE
迁移功能不能使用

### ISSUE THREAD

**Issue by guliacer** [halo-dev/halo#2819]
### 是什么版本出现了此问题？

2.0

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

迁移数据的时候，我点击“选择文件”，还没选择到文件，就直接说文件不符合了

### 附加信息

![image](https://user-images.githubusercontent.com/57098398/205041157-fac1893c-2595-4092-852a-4cba0066c2fe.png)

**Comment by it985** [comment]
用谷歌浏览器试过吗，我也是这样的情况

**Comment by ruibaby** [comment]
/traige duplicate

https://github.com/halo-dev/halo/issues/2810

目前此插件所需的要求：

1. 需要是 Chrome 内核 86 以上。
2. 需要站点使用了 https。

后续会修改为通过后端读取文件的方式来解决这个问题。

**Comment by xiuyuanjun** [comment]
这个问题什么时候可以解决呢？急等。

**Comment by ruibaby** [comment]
请关注：

- https://github.com/halo-sigs/plugin-migrate/issues/4
- https://github.com/halo-dev/halo/issues/2810

/close
