### ISSUE TITLE
2.0.0 文章visits无法迁移

### ISSUE THREAD

**Issue by sakuradon99** [halo-dev/halo#2820]
### 是什么版本出现了此问题？

2.0.0

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式部署？

Docker Compose

### 发生了什么？

本地测试迁移，从线上环境导出json数据，导出的数据中是包含visits字段的，但是通过迁移插件导入后的文章丢失了浏览数。

尝试进数据库手动更新，发现数据库完全变了，只有一张表且数据都为二进制，看了眼代码确实架构完全变更了。这是否意味着用户无法再控制他们的数据库，或者只能通过halo提供的API进行更改。

**Comment by JohnNiang** [comment]
/kind bug

1. 关于文章访问量的问题，我们还在排查中。
2. 我们不推荐直接修改数据库。并且现在的访问量是单独存储的，可能不在 Post 实体上。

@guqing ，请问有没有对应的 workaround 修改文章的访问量呢？

**Comment by guqing** [comment]
确实有点问题，会尽快解决
