### ISSUE TITLE
支持静态页面缓存

### ISSUE THREAD

**Issue by ifuture-pro** [halo-dev/halo#2827]
### 你当前使用的版本

2.0

### 描述一下此特性

对于内容发布系统，页面静态化的功能可以让网站访问速度更快，并大大减少服务器数据库的压力。
也就是后台编辑内容后，一旦发布就生成静态页面，前端访问的时候都只访问静态页面，不走数据库

**Comment by ruibaby** [comment]
这个功能我也认为有必要，可以考虑一下实现方案和版本规划。

/cc @halo-dev/sig-halo

**Comment by zhang-ykun** [comment]
啥时候加上，我觉得十分必要啊

**Comment by zhang-ykun** [comment]
目前没看到静态化得功能

**Comment by JohnNiang** [comment]
前期我将实现页面的缓存，来减少数据库的访问，加快访问速度。

**Comment by huasio** [comment]
这个功能倒是可以通过插件来实现，因为不是halo的核心功能，没必要通过大改来实现。

**Comment by JohnNiang** [comment]
> 这个功能倒是可以通过插件来实现，因为不是halo的核心功能，没必要通过大改来实现。

确实是可以。后续可以试试。
