### ISSUE TITLE
文章页面添加图片、附件极不方便

### ISSUE THREAD

**Issue by Jeffreyone** [halo-dev/halo#2828]
### 你当前使用的版本

 2.0

### 描述一下此特性

1、建议给本地默认项或者让用户选择设置默认，不然每次上传东西都多一次交互点击。
<img width="1238" alt="image" src="https://user-images.githubusercontent.com/49830396/205297639-eef1bf4f-6654-43d6-82e3-8bfc7882a5ef.png">

2、上传按钮位置不合理
<img width="1241" alt="image" src="https://user-images.githubusercontent.com/49830396/205297928-7376fc40-2b7d-40ea-b73f-e6880f1cb843.png">

**Comment by JohnNiang** [comment]
@ruibaby 我的建议：浏览器侧记住上一次选择的附件策略。

**Comment by llllike** [comment]
可以一次上传多张
