### ISSUE TITLE
docker-compose启动pg版本，halo容器无法运行

### ISSUE THREAD

**Issue by ZTfred** [halo-dev/halo#2831]
### 是什么版本出现了此问题？

2.0

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式部署？

Docker Compose

### 在线站点地址

https://test.alialili.cn

### 发生了什么？

![image](https://user-images.githubusercontent.com/53425107/205449604-233e41d0-75d6-4cdb-b856-75ca60d11d79.png)
![image](https://user-images.githubusercontent.com/53425107/205449618-9d1996c4-23e0-4334-b250-d5ec75ac8c52.png)
![image](https://user-images.githubusercontent.com/53425107/205449626-bac18ffe-76eb-4be8-8c3e-ec7cd52cfef2.png)
![image](https://user-images.githubusercontent.com/53425107/205449637-fe0511bc-19d1-49bb-bfcb-51a0e8193c4f.png)
![image](https://user-images.githubusercontent.com/53425107/205449692-1eca2580-370b-456b-8583-f855b997121c.png)
![image](https://user-images.githubusercontent.com/53425107/205449701-091093a4-2835-4ab3-b177-1942412ac38b.png)

阿里云1C2G服务器启动docker-compose版本，halo容器无法启动，看信息是内存溢出了，实际内存空闲很多，且配置后swap。
这块如何修复

### 相关日志输出

```shell
[0.122s][warning][os,thread] Failed to start thread "VM Thread" - pthread_create failed (EPERM) for attributes: stacksize: 1024k, guardsize: 4k, detached.
Error occurred during initialization of VM
Cannot create VM thread. Out of system resources.
[0.013s][warning][os,thread] Failed to start thread "VM Thread" - pthread_create failed (EPERM) for attributes: stacksize: 1024k, guardsize: 4k, detached.
Error occurred during initialization of VM
Cannot create VM thread. Out of system resources.
[0.015s][warning][os,thread] Failed to start thread "VM Thread" - pthread_create failed (EPERM) for attributes: stacksize: 1024k, guardsize: 4k, detached.
Error occurred during initialization of VM
Cannot create VM thread. Out of system resources.
[0.014s][warning][os,thread] Failed to start thread "VM Thread" - pthread_create failed (EPERM) for attributes: stacksize: 1024k, guardsize: 4k, detached.
Error occurred during initialization of VM
Cannot create VM thread. Out of system resources.
```

**Comment by ruibaby** [comment]
Docker 的版本是？似乎和这个问题是一样的：https://github.com/halo-dev/halo/issues/2503

/support

**Comment by ZTfred** [comment]
> Docker 的版本是？似乎和这个问题是一样的：#2503
> 
> /support

Docker version 20.10.9, build c2ea9bc

**Comment by ZTfred** [comment]
> Docker 的版本是？似乎和这个问题是一样的：#2503
> 
> /support

![image](https://user-images.githubusercontent.com/53425107/205450385-ddeb80c9-5705-4eb0-9792-19ef8e437526.png)
全都升级至最新版了，且重启了docker服务，还是相同报错

**Comment by ruibaby** [comment]
@ZTfred 这个版本似乎并不是最新的版本，请参考 https://github.com/adoptium/containers/issues/215#issuecomment-1142046045 这个回复，他升级到了 20.10.16。

**Comment by ruibaby** [comment]
如果你尝试在系统升级 Docker 但提示已经是最新的版本，那么可能是你服务器 Linux 发行版的软件源导致的。推荐通过官方文档来安装 Docker：https://docs.docker.com/get-docker

**Comment by ruibaby** [comment]
@ZTfred 请问此问题得到解决了吗？

**Comment by ruibaby** [comment]
如果没有后续动态，我将关闭此 issue。

/close
