### ISSUE TITLE
期望为主题端添加作者页面

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#2837]
### 你当前使用的版本

2.0.0

### 描述一下此特性

目前 Halo 2.0.0 已经支持了多用户，所以期望可以在主题端支持作者页面。

- 路由：/authors/{author}
- 模板：author.html

这个模板提供的数据除了 author 外，和 `/tags/{slug}`、`/categories/{slug}` 一样，也需要对应的文章数据。类似一种通过作者来归档文章的页面。
 
此外，如果支持了这个特性，也可以在 user 添加一个 permalink 字段，方便主题使用。

/kind feature
/area core

**Comment by ruibaby** [comment]
@guqing 你对主题路由这块逻辑比较熟悉，我先 assign 给你。

/assign @guqing

**Comment by guqing** [comment]
> @guqing 你对主题路由这块逻辑比较熟悉，我先 assign 给你。
> 
> 
> 
> /assign @guqing 

OK

**Comment by ruibaby** [comment]
如果支持了这个路由，似乎 Contributor 的 VO 应该加上 permalink 字段以方便主题使用，比如：

```html
<!-- http://localhost:8090/authors/ryanwang -->
<a th:href="${contributor.status.permalink}">
   <img th:src="${contributor.avatar}" th:alt="${contributor.displayName}" />
</a>
```
