### ISSUE TITLE
请求上传halo到maven central repository

### ISSUE THREAD

**Issue by minliacom** [halo-dev/halo#2845]
### Your current Halo version

2.0.0

### Describe this feature

当前将halo-plain.jar分散在了每个插件项目里面，有些不太合理，可否计划一下上传到中央库呢。

这样在插件项目里可以没有 halo.jar和halo-plain.jar文件，直接在插件项目里面从网络下载这2个文件下来就可以了。 

不知道这样理解有没有问题，望指正哈。

**Comment by ruibaby** [comment]
是的，确实需要这样做，我们已经在进行当中。请关注：https://github.com/halo-dev/halo/issues/2730

/triage duplicate 
/kind support

**Comment by JohnNiang** [comment]
I'm going to close this issue as it is a duplicate of <https://github.com/halo-dev/halo/issues/2730>.

/close
