### ISSUE TITLE
阿里云OSS文件上传路径不对（忽略了绑定域名）

### ISSUE THREAD

**Issue by git-kings** [halo-dev/halo#2846]
### 是什么版本出现了此问题？

2.0

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式部署？

Docker Compose

### 在线站点地址

ihxx.cc

### 发生了什么？

![image](https://user-images.githubusercontent.com/66518019/205657324-d93c1a94-2d97-4a81-bee7-059e948fbcb2.png)
绑定域名这一项设置不设置 最后文件上传后的路径都是Bucket+End Point拼接的路径 导致点击路径不能直接访问图片 变成了保存图片

**Comment by JohnNiang** [comment]
Thanks for reaching out here!

晚点儿我确认一下这个功能是否正常。

**Comment by llllike** [comment]
endPoints不能带https://哦

**Comment by git-kings** [comment]
> 

endPoints没有https  endPoints是oss-xxxxx.aliyuncs.com

**Comment by JohnNiang** [comment]
/kind bug

Hi @git-kings ，确实是插件这边没有适配”绑定域名“这个功能。

**Comment by longjuan** [comment]
我这边改了一下https://github.com/longjuan/halo-plugin-s3os/commit/84334b8138d69b6997545c5df74b428941019d10
@JohnNiang 需要我这个吗

**Comment by JohnNiang** [comment]
> 我这边改了一下[longjuan/halo-plugin-s3os@84334b8](https://github.com/longjuan/halo-plugin-s3os/commit/84334b8138d69b6997545c5df74b428941019d10) @JohnNiang 需要我这个吗

非常欢迎针对这个问题提交 PR。

/assign @longjuan

**Comment by git-kings** [comment]
感谢 需要的
&nbsp;


xx
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "John ***@***.***&gt;; 
发送时间: 2022年12月16日(星期五) 下午3:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [halo-dev/halo] 阿里云OSS文件上传路径不对（忽略了绑定域名） (Issue #2846)





  
***@***.*** @JohnNiang 需要我这个吗
  
非常欢迎针对这个问题提交 PR。
 
/assign @longjuan
 
&mdash;

**Comment by JohnNiang** [comment]
Hi @git-kings , 刚刚发布了 [plugin-alioss 1.0.1](https://github.com/halo-sigs/plugin-alioss/releases/tag/v1.0.1)，可以测试测试。

/close
