### ISSUE TITLE
汉化角色权限

### ISSUE THREAD

**Issue by cetr** [halo-dev/halo#2848]
### 你当前使用的版本

2.0.0

### 描述一下此特性

角色权限所有内容进行汉化

**Comment by JohnNiang** [comment]
/kind improvement
/area core

这个问题涉及到 Halo 的国际化，可参考：<https://github.com/halo-dev/rfcs/issues/6>。

**Comment by ruibaby** [comment]
我将临时支持 Console 的 i18n，并将所有角色模板添加中文翻译。
