### ISSUE TITLE
系统预设角色权限未初始化权限

### ISSUE THREAD

**Issue by cetr** [halo-dev/halo#2849]
### 描述一下此特性

系统预设的两个角色都是包含0个权限，例如super-role应该勾选所有权限

**Comment by JohnNiang** [comment]
实际上 console 端所列出的所有权限列表并没有覆盖完 Halo 系统的 API，所以 `super-role` 角色目前只是简单用了 `*` 来表示包含所有权限。

不过这也算是需要优化的地方，`super-role` 角色应该勾选所有已列举的权限。

/kind improvement
/area core

**Comment by ruibaby** [comment]
这个问题应该已经在 https://github.com/halo-dev/console/pull/749 中修复，也已经在 [2.0.1](https://github.com/halo-dev/halo/releases/tag/v2.0.1) 发布。

/close
