### ISSUE TITLE
console端切换主题时点启用页面没有重载

### ISSUE THREAD

**Issue by cetr** [halo-dev/halo#2850]
### 你当前使用的版本

2.0.0

### 描述一下此特性

切换主题后页面没有重载，启用按钮没有切换成已启用

**Comment by JohnNiang** [comment]
没有太理解，建议提供更多的信息，例如：截图。

/triage needs-information

**Comment by cetr** [comment]
> 没有太理解，建议提供更多的信息，例如：截图。
> 
> /triage needs-information


https://user-images.githubusercontent.com/49756728/205807928-c04ca43c-24ba-44e3-ae56-4195fbace193.mp4
