### ISSUE TITLE
console端个人资料编辑页面顶部背景不能自定义

### ISSUE THREAD

**Issue by cetr** [halo-dev/halo#2851]
### 你当前使用的版本

2.0.0

### 描述一下此特性

console端个人资料编辑页面顶部背景不能自定义

**Comment by JohnNiang** [comment]
/ping @ruibaby 

当前 Issue 有实现思路了么？

**Comment by ruibaby** [comment]
> /ping @ruibaby
> 
> 当前 Issue 有实现思路了么？

没有，和头像一样，我不建议直接从附件库选择背景。可能我会先取消当前的背景色，并重新布局个人资料页面。
