### ISSUE TITLE
新建用户不能同时设置用户密码和分配角色

### ISSUE THREAD

**Issue by cetr** [halo-dev/halo#2852]
### 你当前使用的版本

2.0.0

### 描述一下此特性

新建用户不能同时设置用户密码和分配角色

**Comment by ruibaby** [comment]
ping @halo-dev/sig-halo

**Comment by guqing** [comment]
@JohnNiang 有时间处理这个 issue 吗，我可以帮忙

**Comment by JohnNiang** [comment]
> @JohnNiang 有时间处理这个 issue 吗，我可以帮忙

Just do it.

/assign @guqing
