### ISSUE TITLE
增加基于路由的全文搜索插件

### ISSUE THREAD

**Issue by LIlGG** [halo-dev/halo#2862]
### Your current Halo version

2.0.0

## 缘由
Halo 1.0 版本主题搜索功能为单独路由功能，且主题可以定制化搜索界面。 而 2.0 版本需要使用搜索插件 https://github.com/halo-sigs/plugin-search-widget 。该插件虽然实现了全文搜索功能，但其工作原理为自定义 DOM，主题无法充分扩展搜索功能。

## 尝试办法
起初尝试使用接口 /apis/api.halo.run/v1alpha1/indices/post?keyword=Halod&highlightPreTag=<mark>&highlightPostTag=</mark> 配合 JS 来实现自定义搜索界面，但对于 Halo 来说并无搜索路由，数据也仅能以弹窗的方式呈现，这与 plugin-search-widget 的工作原理相吻合且达不到想要的需求。

## 建议
开发一个新的搜索插件，使用单独的路由（例如 /search） 封装并返回全文搜索内容。即开发后端模板引擎驱动的搜索插件，而不是基于 JS。

## 示例
参考 https://lixingyong.com/search?keyword=hello

**Comment by ruibaby** [comment]
或许也可以由 Halo 核心来提供这个路由，因为毕竟现在是内置了搜索引擎。

**Comment by JohnNiang** [comment]
我认为还是可以提供这样的路由，并由主题自由发挥展示样式。目前我们仅支持搜索文章，后续看能否支持搜索标签，分类，页面等。

**Comment by ruibaby** [comment]
已经在 https://github.com/halo-dev/plugin-search-widget/pull/35 中完成。

/close
