### ISSUE TITLE
Suggest removing the description of each role first

### ISSUE THREAD

**Issue by JohnNiang** [halo-dev/halo#2864]
### What is version of Halo has the issue?

2.0.1-SNAPSHOT

### What database are you using?

H2

### What is your deployment method?

Docker

### Your site address.

localhost

### What happened?

The description of each role is the same(`超级管理员`), and see the screenshot below for more

![image](https://user-images.githubusercontent.com/16865714/205934321-218423b7-b486-43df-b708-999b62c64014.png)

So I suggest removing this description first.

### Additional information

/kind bug
/area console
/milestone 2.0.x

**Comment by ruibaby** [comment]
已经在 https://github.com/halo-dev/console/pull/749 中移除。

/close
