### ISSUE TITLE
当插件禁用时出现404错误

### ISSUE THREAD

**Issue by minliacom** [halo-dev/halo#2866]
### 是什么版本出现了此问题？

2.0.1-SNAPSHOT

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

当插件在详情页面禁用时出现了资源不存在的问题

从现象来看禁用之后多调用了一次详情接口

<img width="783" alt="image" src="https://user-images.githubusercontent.com/10692860/205945481-4b07027f-a3ea-443b-9354-6f952beb687a.png">

**Comment by ruibaby** [comment]
/cc @halo-dev/sig-halo 当插件未启用时，访问插件的 setting 资源 404 是符合预期的表现吗？

<img width="1663" alt="image" src="https://user-images.githubusercontent.com/21301288/205967169-32cdcc08-69bb-43e7-9c86-ff822f3dfe93.png">

**Comment by minliacom** [comment]
主题也存在此情况

**Comment by minliacom** [comment]
2.0.1修复成功，验证通过，禁用后没有了404请求。

<img width="1363" alt="image" src="https://user-images.githubusercontent.com/10692860/206146287-4898934e-b6a8-4300-8bab-4d3c7482fe9a.png">
