### ISSUE TITLE
插件详情页面排版与优化建议

### ISSUE THREAD

**Issue by minliacom** [halo-dev/halo#2867]
### 你当前使用的版本

2.0.1-SNAPSHOT

#### 问题

描述栏目排版出现问题，这点字数应该不需要换行

#### 优化建议

描述栏想加入更多的该插件的指导文档，考虑优化一下排版与位置

### 附加信息

<img width="793" alt="image" src="https://user-images.githubusercontent.com/10692860/205947661-23d329e7-4dab-4ca3-90a6-3a2740a1ee87.png">

**Comment by minliacom** [comment]
嗯，文档说明可以到插件提供方的网看里面看到。

**Comment by ruibaby** [comment]
> 后续或许可以提供一个类似于 Summary tab 这样的，描述最多只是一段话，不适合放太多字

确实可以读取 README 来进行暂时。

**Comment by ruibaby** [comment]
1. 换行的问题应该已经解决。
2. 至于放置 README 目前似乎可以在内置的应用市场中查看。
3. 如果要在插件详情页面放置文档，似乎也可以扩展一个 Tab，参考文档：https://github.com/halo-dev/halo/blob/main/console/docs/extension-points/plugin-self-tabs.md

所以此 issue 已经过时，我将关闭它。

/close
