### ISSUE TITLE
自己实现一个轻量级的搜索引擎？

### ISSUE THREAD

**Issue by JohnNiang** [halo-dev/halo#287]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [x] 添加新的特性或者功能
- [ ] 请求技术支持

---
使用其他搜索引擎会增加部署成本和复杂度，带来的效益并不大。

所以是否考虑自己实现一个轻量级，且适合 halo 的搜索引擎？

**Comment by ruibaby** [comment]
how

**Comment by JohnNiang** [comment]
不知道，这个就是一个小挑战了，加入未来的计划当中。

**Comment by ruibaby** [comment]
我们现在的挑战应该是 `插件`
