### ISSUE TITLE
菜单名称有符号会显示异常

### ISSUE THREAD

**Issue by daifiyum** [halo-dev/halo#2875]
### 是什么版本出现了此问题？

halo2.0正式版

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

后台菜单新加菜单项，如果命名有符号（#、_、*等等），就不会显示名称，但菜单项还在
![image](https://user-images.githubusercontent.com/39544944/206136041-21e2757c-ee7a-48a3-b92f-1caef653960d.png)

![image](https://user-images.githubusercontent.com/39544944/206135867-ebb1f7ab-94d4-43af-adc9-ffc0aa8b628b.png)

### 附加信息

希望能在添加菜单表单项里加入图标表单，这样就不用这么麻烦的给菜单名做分割取图标字段了

**Comment by ruibaby** [comment]
可能和 https://github.com/halo-dev/halo/issues/2816 原因一样。

可以使用 2.0.1 再尝试一下：https://github.com/halo-dev/halo/releases/tag/v2.0.1

> 希望能在添加菜单表单项里加入图标表单，这样就不用这么麻烦的给菜单名做分割取图标字段了

建议单独提交 issue。

**Comment by daifiyum** [comment]
> 可能和 #2816 原因一样。
> 
> 可以使用 2.0.1 再尝试一下：https://github.com/halo-dev/halo/releases/tag/v2.0.1
> 
> > 希望能在添加菜单表单项里加入图标表单，这样就不用这么麻烦的给菜单名做分割取图标字段了
> 
> 建议单独提交 issue。

这个版本没问题了
