### ISSUE TITLE
希望halo2可以在新加菜单表单里加入菜单图标表单

### ISSUE THREAD

**Issue by daifiyum** [halo-dev/halo#2878]
### 你当前使用的版本

halo2.0

### 描述一下此特性

halo2.0新加菜单里没用菜单图标的输入框

**Comment by it985** [comment]
+1 但是应该是主题的功能吧

**Comment by daifiyum** [comment]
> +1 但是应该是主题的功能吧

主题的确可以通过一些手段实现但都不够优雅，例如我用新模板引擎提供的substringAfter()方法对标题截取特定字符来获得图标，但这种方式哪有在后台加入一个图标表单来的优雅？

**Comment by ruibaby** [comment]
@it985 @daifiyum 这个是计划要支持的，不过得等 https://github.com/halo-dev/halo/issues/2858 完成。

**Comment by ruibaby** [comment]
目前 2.1.0-rc.1 已经支持为菜单项设置元数据表单，所以主题开发的时候如果需要在菜单支持显示图标，那么就可以定义一个 AnnotationSetting 模型。

具体文档可以关注：https://github.com/halo-dev/docs/issues/154
定义方式可以参考：https://github.com/halo-dev/console/pull/801 https://github.com/halo-dev/console/pull/770
