### ISSUE TITLE
1.1.0-beat版提示更新1.0.3版本，存在错误提示更新

### ISSUE THREAD

**Issue by a1105013796** [halo-dev/halo#288]
![image](https://user-images.githubusercontent.com/32124539/64258528-00dcfe00-cf5a-11e9-8f1f-8d4da0220719.png)
如图。。。貌似还能点那个下载按钮更新- -

**Comment by JohnNiang** [comment]
是的，这个问题仅仅存在测试版本，正式版是会正确提示的。不过我们最近也在考虑讲检查版本的工作放在后端进行。

**Comment by a1105013796** [comment]
有点好奇，你们现在版本检查的工作是怎么完成的？之前没弄过这种，想学习一下

**Comment by JohnNiang** [comment]
https://github.com/halo-dev/halo-admin/commit/c8b2c41382aa1467cae0d939eb009fe4d7d75df4

**Comment by a1105013796** [comment]
好的，谢谢
