### ISSUE TITLE
Arm(Aarch64)无法使用docker-compose构建

### ISSUE THREAD

**Issue by ShermanQ** [halo-dev/halo#2880]
### 是什么版本出现了此问题？

2.0

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker

### 发生了什么？

docker-compose构建失败

### 相关日志输出

```shell
halodb | exec /usr/local/bin/docker-entrypoint.sh: exec format error
halodb | exec /usr/local/bin/docker-entrypoint.sh: exec format error
halodb | exec /usr/local/bin/docker-entrypoint.sh: exec format error
halodb | exec /usr/local/bin/docker-entrypoint.sh: exec format error
halodb | exec /usr/local/bin/docker-entrypoint.sh: exec format error
```

### 附加信息

```bash
**_cat /proc/version_**
Linux version 5.15.0-1017-oracle (buildd@bos02-arm64-064) (gcc (Ubuntu 9.4.0-1ubuntu120.04.1) 9.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #2220.04.1-Ubuntu SMP Wed Aug 24 11:13:15 UTC 2022
**_uname -a_**
Linux instance-20220705-2056 5.15.0-1017-oracle #2220.04.1-Ubuntu SMP Wed Aug 24 11:13:15 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
**_uname -r_**
5.15.0-1017-oracle
**_arch_**
aarch64
```

**Comment by JohnNiang** [comment]
/triage needs-information

建议提供一下 Docker 版本。

**Comment by ShermanQ** [comment]
> 
dokcer version 20.10.21
docker-compose version 2.1.1

**Comment by JohnNiang** [comment]
我也得到类似的错误：

```bash
johnniang@manjaro-arm:~/halo2 $ docker-compose up
[+] Running 0/1
 ⠧ halodb Pulling                                                                                                                                                                                                     22.6s
no matching manifest for linux/arm64/v8 in the manifest list entries
```

我发现镜像 [mysql:8.0.27](https://hub.docker.com/layers/library/mysql/8.0.27/images/sha256-238cf050a7270dd6940602e70f1e5a11eeaf4e02035f445b7f613ff5e0641f7d?context=explore) 还没有 arm 架构，不过 [mysql:8.0.31](https://hub.docker.com/layers/library/mysql/8.0.31/images/sha256-abd7d1e4a42b96a58c702db2633df611d201789b07c01749dac1aff97b83ba8f?context=explore) 已经有了。

最终建议修改 `docker-compose.yaml` 中的 MySQL 镜像 tag 为 `mysql:8.0.31`。

**Comment by ShermanQ** [comment]
这个我通过在  docker-compose.yaml   增加 platform参数解决了，如下所示
       platform: linux/x86_64

    image: mysql:8.0.27
<https://hub.docker.com/layers/library/mysql/8.0.27/images/sha256-238cf050a7270dd6940602e70f1e5a11eeaf4e02035f445b7f613ff5e0641f7d?context=explore>

是MySQL 版本的问题吗？


John Niang ***@***.***> 于2022年12月8日周四 15:52写道：

**Comment by JohnNiang** [comment]
是的，可以按照我上面提到的方法试试。

**Comment by ShermanQ** [comment]
感谢，确认是MySQL架构的问题，按照您的方法已经成功构建Halo。

John Niang ***@***.***> 于2022年12月8日周四 15:59写道：
