### ISSUE TITLE
Console 端期望支持独立编辑器扩展

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#2881]
### 你当前使用的版本

2.0.1

### 描述一下此特性

目前 Halo 2.0 默认包含一个富文本编辑器，对于习惯使用 Markdown 编辑器的用户来说可能不太友好，期望可以通过插件的方式直接集成现有的任何编辑器。

> 注意，这里说的不是去扩展自带的编辑器。

需要考虑的点：

1. 是否需要支持在编辑的时候切换编辑器。
2. 是否需要一个全局的配置（默认编辑器），毕竟可能同时存在 N 个编辑器插件。

/kind feature
/area console
/milestone 2.1.x

**Comment by li-guohao** [comment]
我就我个人的体验说下我的看法：
1. 不需要支持在编辑的时候切换编辑器，没必要，而且感觉对在编辑的内容处理比如转化有点麻烦
2. 需要一个全局的配置，比如默认配置成Markdown，这样编辑文章就不用再切换了

打算等支持了Markdown再升级到2，加油

**Comment by sxh705** [comment]
建议增加一个文章编辑插件, 引入stackedit.js, 这个开源js编辑器体验很好

**Comment by sxh705** [comment]
https://github.com/sxh705/halo_markdown
写个个油猴脚本可以试试.

**Comment by sxh705** [comment]
写了个适用于1.x的油猴脚本:smile:
因为2.0的markdown语法不全面..
https://github.com/sxh705/halo_markdown

**Comment by ruibaby** [comment]
> 建议增加一个文章编辑插件, 引入stackedit.js, 这个开源js编辑器体验很好

<img width="336" alt="image" src="https://user-images.githubusercontent.com/21301288/208373140-b80118fb-bcc9-47f1-99d7-d457588eda01.png">
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/21301288/208373177-1333d973-f859-4f76-be4b-c07e3af548d6.png">

**Comment by ruibaby** [comment]
> 我就我个人的体验说下我的看法：
> 
> 1. 不需要支持在编辑的时候切换编辑器，没必要，而且感觉对在编辑的内容处理比如转化有点麻烦
> 2. 需要一个全局的配置，比如默认配置成Markdown，这样编辑文章就不用再切换了
> 
> 打算等支持了Markdown再升级到2，加油

嗯，暂时不考虑在编辑过程切换编辑器，当一篇文章确认一个编辑器之后就不再允许修改。全局的默认编辑器配置可能暂时不会加，会在进入编辑页面的入口添加选择编辑器的菜单。
