### ISSUE TITLE
无法正确的给用户分配自定义角色

### ISSUE THREAD

**Issue by cetr** [halo-dev/halo#2882]
### 是什么版本出现了此问题？

2.0.1

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式部署？

Docker Compose

### 发生了什么？

分配自定义角色后用户的角色和自定义角色不一致，且无法修改为正确的

修改完页面没有重载，需要手动刷新页面

**Comment by cetr** [comment]
然后建议系统保留的角色设置为置顶显示

**Comment by JohnNiang** [comment]
目前在 Halo 2.10.x 中已无法复现该问题。

当前 Issue 即将被关闭。如果有任何问题可随时重新打开。

/close
