### ISSUE TITLE
【重要】回复时间的建议，目前的逻辑不太对

### ISSUE THREAD

**Issue by FlatwormUnique** [halo-dev/halo#2889]
### 你当前使用的版本

2.0

### 描述一下此特性

我在生产环境用了2.0，一个公益性质的小孩子读书会，早几天有个线上抢名额的活动，取回复最早时间报名的，现在反馈问题：
https://snail.chiphello.com:65003/archives/251-221217 

1.提交评论后，没任何提示，用户以为没成功，多次提交
2.后台审核，看不到评论时间，放出评论后，显示的是审核的时间，我觉得这个逻辑是不对的
3.评论的时间格式不是精确的时间，希望能有地方选择时间格式

### 附加信息

<img width="281" alt="1670471794810" src="https://user-images.githubusercontent.com/85718974/206353146-11b8bdf3-fe22-4349-b38d-05e2100f16b2.png">

**Comment by wan92hen** [comment]
第一个问题可以关注下这个 issue #2731

**Comment by ruibaby** [comment]
2. 这个问题暂时可能不是太好解决，添加这个审核时间是为了从 1.x 迁移的时候方便设置时间（因为创建时间是不能设置的）。但你可以尝试在系统设置里面取消掉 `新评论审核` 选项。
3.目前显示的是相对时间，对于这种时间线类型的列表显示，使用相对时间可能更加直观。但可以考虑提供配置，提供完整时间显示。

**Comment by ruibaby** [comment]
此外，您这个需求似乎可以考虑开发一个表单收集的插件。

**Comment by FlatwormUnique** [comment]
> 

首先谢谢回复
第三点，因为我们的报名人数是有限制的，所以是选择一个时间开放，取开放后的前xx位报名的，所以，完整时间利于参与者自查。
确实可以设计成表单，我没能力做，不过会密切关注的。
暂时打算取消掉评论审核来实现功能。

**Comment by ruibaby** [comment]
1. 第一个问题已经在 2.2.0 中支持，可以升级最新的评论插件和 Halo 版本再尝试。
2. 第二个问题已经在 https://github.com/halo-dev/halo/pull/3341 优化。

显示完整时间请关注：https://github.com/halo-sigs/plugin-comment-widget/issues/18

/close
