### ISSUE TITLE
Console 端的部分确认弹框操作路径过长，需要优化

### ISSUE THREAD

**Issue by minliacom** [halo-dev/halo#2892]
### 你当前使用的版本

2.0.1-SNAPSHOT

### 描述一下此特性

这个UX有点费右手，要移动好多次才能完成操作，可以做成在当前操作区域的上下文完成确认按钮的点击吗，就不用移那么远的鼠标了

<img width="790" alt="image" src="https://user-images.githubusercontent.com/10692860/206434144-70871857-77a9-41b9-9d5e-8c2826a9db71.png">

**Comment by ruibaby** [comment]
现在可以使用 `@halo-dev/components` 的 VDropdown 实现。

/assign

**Comment by ruibaby** [comment]
已经在 https://github.com/halo-dev/halo/pull/4472 中移除确定框。

/close
