### ISSUE TITLE
回车确认操作习惯不同步的问题

### ISSUE THREAD

**Issue by minliacom** [halo-dev/halo#2893]
### 是什么版本出现了此问题？

2.0.1-SNAPSHOT

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

第一个图可以使用回车确认，第二个图不可以，可以都加上使用回车确认的彩蛋吗？

<img width="799" alt="image" src="https://user-images.githubusercontent.com/10692860/206435594-cfdc7ab3-0b64-4b84-bed0-622dea637264.png">

<img width="805" alt="image" src="https://user-images.githubusercontent.com/10692860/206435489-598fec3d-a70a-4040-b51d-955476ba25e8.png">

**Comment by wzrove** [comment]
> 之前没有理解正确题主的意思，这实际上是一个符合预期的表现。第一个截图因为只有一个输入框，所以但使用 Enter 就提交表单应该是没有什么问题的。但是第二个截图包含多个输入框时，如果可以使用 Enter 就提交了表单，那么是非常容易误操作的。
> 
> 如果一定要优化，那么应该是优化仅有一个输入框的表单。应该要禁止使用 Enter 提交，需要使用组合键（Ctrl + Enter）。

雀氏，哈哈哈 把`enter`优化掉，统一`组合键（Ctrl + Enter）`

**Comment by ruibaby** [comment]
> 雀氏，哈哈哈 把enter优化掉，统一组合键（Ctrl + Enter）

@wzrove 我之前写的时候也尝试屏蔽掉一个输入框时的 Enter 事件，但是没有成功，这可能是 FormKit 的表现，你有兴趣可以研究下。

**Comment by wzrove** [comment]
> > 雀氏，哈哈哈 把enter优化掉，统一组合键（Ctrl + Enter）
> 
> @wzrove 我之前写的时候也尝试屏蔽掉一个输入框时的 Enter 事件，但是没有成功，这可能是 FormKit 的表现，你有兴趣可以研究下。

好滴
