### ISSUE TITLE
前端Earth官方模板Logo不正常显示

### ISSUE THREAD

**Issue by minliacom** [halo-dev/halo#2894]
### 是什么版本出现了此问题？

2.0.1-SNAPSHOT

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

已设置好LOGO显示有问题，看起来取错了字段。

<img width="733" alt="image" src="https://user-images.githubusercontent.com/10692860/206437212-18b7038b-1836-4a06-9318-a3422404b347.png">

<img width="1592" alt="image" src="https://user-images.githubusercontent.com/10692860/206436857-a652fd7d-d072-423c-b904-2b26c01174d0.png">

**Comment by ruibaby** [comment]
这里并不是使用的系统设置中的 Logo 设置，应该是主题设置中的页脚设置里面，请问你这里面设置的是正确的吗？

<img width="830" alt="image" src="https://user-images.githubusercontent.com/21301288/206616654-443173f2-b40f-4405-ae16-5977ad173470.png">

**Comment by minliacom** [comment]
哦哦哦 那就没问题 看了是主题里面没设置 关了

**Comment by ruibaby** [comment]
/kind bug
/remove-kind support 
/reopen
/area theme
/good-first-issue

这确实是一个 bug，请看：

https://github.com/halo-dev/theme-earth/blob/6c5c68bd7bb912dfe66c773826fbaeaa6cbc3a48/templates/modules/footer.html#L6
