### ISSUE TITLE
console端有没有一个扩展点清单

### ISSUE THREAD

**Issue by minliacom** [halo-dev/halo#2895]
### 你当前使用的版本

2.0.1-SNAPSHOT

### 描述一下此特性

我想开发一个插件，比如下图，应该去哪里参考扩展点呢

<img width="1218" alt="image" src="https://user-images.githubusercontent.com/10692860/206445632-ae6d8153-e4bb-4996-8e92-a5fe835814b3.png">

**Comment by ruibaby** [comment]
目前仅提供了功能页面和附件选择组件的扩展点，后续会按需求添加。

/kind feature
/area console
/priority important-longterm

**Comment by ruibaby** [comment]
后续可关注：https://github.com/halo-dev/docs/pull/291

/remove-kind feature
/kind documentation
/close
