### ISSUE TITLE
Hope support define anonymous interface access permissions for extension Halo Plugin

### ISSUE THREAD

**Issue by liuchangfitcloud** [halo-dev/halo#2904]
### Your current Halo version

2.0.0

### Describe this feature

希望在扩展插件的过程中支持创建可匿名访问的接口权限控制

### Additional information

尝试通过RoleTemplate中RoleBinding绑定匿名用户的方式无法将接口的权限开放，如果全部定义给api.halo.run这个ApiGroup又不太可控！

**Comment by guqing** [comment]
/triage duplicate
see #3560 for more details
/close
