### ISSUE TITLE
建议支持外部用户账户登录比如 OIDC

### ISSUE THREAD

**Issue by LeonDevLifeLog** [halo-dev/halo#2909]
### 你当前使用的版本

2.0

### 描述一下此特性

目前是系统内独立的用户体系，无法与外部已有用户系统对接。建议支持 OIDC（gitlab），OAuth（标准，以及第三方企业微信，钉钉，飞书等）。

可以参考 [JustAuth](https://github.com/justauth/JustAuth)

**Comment by ruibaby** [comment]
目前社区已经有一些和认证相关的插件：https://www.halo.run/store/apps?tag=authentication

也完全可以通过为插件暴露的 API 构建符合自己需求的插件：https://docs.halo.run/developer-guide/plugin/api-reference/server/extension-points/authentication-webfilter

/close
