### ISSUE TITLE
Markdown文章导入不支持拖拽操作

### ISSUE THREAD

**Issue by ShutaoTang** [halo-dev/halo#291]
**我确定我已经查看了** 

- [x] [Halo 使用文档](https://halo.run/docs)
- [ ] [Halo 论坛](https://bbs.halo.run)
- [ ] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

**Description**

`系统` -> `小工具`

`Markdown文章导入`不支持拖拽操作

**Comment by ruibaby** [comment]
@ShutaoTang 下个版本会更改上传组件，以后不仅支持拖拽，还支持粘贴

**Comment by ShutaoTang** [comment]
@ruibaby 谢谢，我是做后端的，最近也想看看学前端，这个代码写得很好，特别是johnniang的风格，注释也好

**Comment by ruibaby** [comment]
@ShutaoTang @johnniang

**Comment by ruibaby** [comment]
@ShutaoTang 对了，如果你愿意，欢迎参与开发哦。

**Comment by ShutaoTang** [comment]
哈哈，我在互联网公司，加班多，平时确实很忙，几乎没有时间。:)

**Comment by ruibaby** [comment]
@ShutaoTang 12127🌚

**Comment by ruibaby** [comment]
已支持
