### ISSUE TITLE
加入其他导入的功能

### ISSUE THREAD

**Issue by xyhcode** [halo-dev/halo#2911]
### 你当前使用的版本

2.0

### 描述一下此特性

比如把hexo的文章导入到halo中 。
文章编辑器的插入代码希望支持更多语言 如：html vue...

**Comment by ruibaby** [comment]
/kind feature
/area plugin

可以考虑实现一个导入 markdown 文件的插件。

代码块应该是支持 html 的，不过 highlight.js 似乎没有 Vue 的高亮语言。

**Comment by ruibaby** [comment]
@xyhcode 如果可以请再提交一个 issue 来记录这个高亮语言的问题。

**Comment by xyhcode** [comment]
是否会考虑出一个友链管理的功能呢？

**Comment by ruibaby** [comment]
> 是否会考虑出一个友链管理的功能呢？

https://github.com/halo-sigs/plugin-links

**Comment by JohnNiang** [comment]
See https://github.com/halo-sigs/plugin-migrate/issues/2 for more.

/triage duplicate
