### ISSUE TITLE
发现后台配置得自定义页面，不会统计阅读量

### ISSUE THREAD

**Issue by SimpleDays** [halo-dev/halo#2912]
### 是什么版本出现了此问题？

2.0.1

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

后台配置自定义页面，比如“关于”页面，前台阅读访问之后，并未统计阅读量

**Comment by ruibaby** [comment]
可以复现，原因是请求 counter 接口的时候，name 为 null：

<img width="1071" alt="image" src="https://user-images.githubusercontent.com/21301288/206912527-ae7bd65d-b62c-4f5d-a215-51cdf5765fe7.png">
<img width="922" alt="image" src="https://user-images.githubusercontent.com/21301288/206912546-54ce4d85-c9aa-4a6d-8afe-970ff491f09d.png">

/kind bug
/area core
/milestone 2.1.x

**Comment by JohnNiang** [comment]
Hi @halo-dev/sig-halo，这个 issue 应该放到 2.0.x milestone 吧。
