### ISSUE TITLE
适配更多的高亮语言

### ISSUE THREAD

**Issue by xyhcode** [halo-dev/halo#2913]
### 你当前使用的版本

2.0

### 描述一下此特性

文章编写时插入代码希望支持更多的语言高亮 如html...

### 附加信息

<img width="845" alt="image" src="https://user-images.githubusercontent.com/64968400/206889798-058681d4-5c6a-4f27-b38e-5ce7d3ce50a8.png">

**Comment by ruibaby** [comment]
/kind feature
/area console
/good-first-issue

需要在 https://github.com/halo-sigs/richtext-editor 中支持。
