### ISSUE TITLE
主页文章排序方式

### ISSUE THREAD

**Issue by ziceky** [halo-dev/halo#2915]
### 是什么版本出现了此问题？

主页文章顺序乱序，既不是按照时间排序，也不是标题字母。

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 在线站点地址

iceky.eu.org

### 发生了什么？

应该是最新的在最上面，整个顺序都是乱的，最近的在最上面，次久的又到了最下面，请问这样该怎么调整

**Comment by ruibaby** [comment]
请按照 issue 模板填写你使用的版本。

/triage needs-information

**Comment by JohnNiang** [comment]
请修改一下描述，我们不知道当前使用的版本是多少。

建议升级到最新版（2.0.1）后再试试该问题是否仍然存在。
