### ISSUE TITLE
文章地址等处建议采用相对路径

### ISSUE THREAD

**Issue by woshiaxie** [halo-dev/halo#2917]
![issue](https://user-images.githubusercontent.com/4527636/206826177-9f82d69c-51ea-464c-80e8-f6201d8215d7.png)
RT，如果带有host，那么对于内网穿透部署网站的用户来说，相当部分的页面就不可访问了。

**Comment by JohnNiang** [comment]
对外访问地址可随时更改，不过需要重启，可参考：<https://github.com/halo-dev/halo/issues/2917#issuecomment-1345790134>。

/close
