### ISSUE TITLE
申请思维导图功能，类似百度脑图

### ISSUE THREAD

**Issue by ShawYore** [halo-dev/halo#292]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x[Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [x] 添加新的特性或者功能
- [ ] 请求技术支持

**Comment by ShawYore** [comment]
个人博客除了记录一些知识散点，更希望能用一个思维导图来把这些知识散点系统的联系起来，因此希望加入简单的思维导图的功能。类似下图
块---->块
 |---------->块

**Comment by ruibaby** [comment]
@ShawYore 这个我们会尝试实现一下，但是不一定会很快

**Comment by ShawYore** [comment]
@ruibaby 收到，感谢，大佬辛苦了！

Markdown支持mermaid插件、flowchart.js插件流程图
mermaid插件流程图：
用关键字graph表示一个流程图的开始，同时指定该图的方向,例如

```
graph LR
 A --> B
```

**Comment by ruibaby** [comment]
@ShawYore 好的，感谢提示。

**Comment by yu902650** [comment]
这个实现要花时间，辛苦大佬

**Comment by ruibaby** [comment]
@yu902650 嗯。要修改编辑器。

**Comment by ruibaby** [comment]
这个已经支持了，等待发布 1.2.0 。
