### ISSUE TITLE
halo支持一键式部署在公有云容器服务

### ISSUE THREAD

**Issue by AlexGeekMa** [halo-dev/halo#2922]
### 描述一下此特性

计划基于halo构建个人网站，halo支持容器镜像的方式运行。目前AWS、Aliyun、华为云等都提供了基于Kubernetes的Serverless容器服务，考虑在这些云服务上面运行halo。
halo是否可以通过插件的机制，支持一键式部署在公有云容器服务，并支持在多个云厂商之间灵活选择。社区如果有类似规划，我有兴趣参与进来一起贡献。

**Comment by wan92hen** [comment]
如果都是 Kubernetes 集群的话，通过 Helm 来统一部署更合适吧。
https://github.com/halo-sigs/charts

**Comment by JohnNiang** [comment]
我们曾在腾讯云上支持过[一键部署](https://github.com/halo-dev/tencent-cloudbase-halo)，但是最后在没有任何理由和通知的情况下下架了。

**Comment by AlexGeekMa** [comment]
> 我们曾在腾讯云上支持过[一键部署](https://github.com/halo-dev/tencent-cloudbase-halo)，但是最后在没有任何理由和通知的情况下下架了。

你说的下架是啥意思？腾讯云服务下架了还是插件下架了？

**Comment by JohnNiang** [comment]
@AlexGeekMa ，是被对方下架了。

**Comment by guqing** [comment]
腾讯云自己搞了个 CMS
