### ISSUE TITLE
文章页面因过多的标签导致文章名称被隐藏

### ISSUE THREAD

**Issue by MDQ0512** [halo-dev/halo#2926]
### 是什么版本出现了此问题？

2.0

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式部署？

Docker

### 发生了什么？

文章页面因过多的标签导致文章名称被隐藏
我的一篇文章因为添加了8个标签，导致文章的名称被隐藏，无法修改
同时其他文章也因为文章标签的数量，导致名称或多或少的被隐藏，很不美观

**Comment by MDQ0512** [comment]
![image](https://user-images.githubusercontent.com/57866775/207620666-42204439-1e7c-471a-9d93-bae4d30df51a.png)

**Comment by MDQ0512** [comment]
如果文章标签可以后移或者双层显示，可能会比较美观一些

**Comment by ruibaby** [comment]
> 如果文章标签可以后移或者双层显示，可能会比较美观一些

可以考虑单独占用一行。
