### ISSUE TITLE
插件安装如果异常提示不明确

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#2932]
### 是什么版本出现了此问题？

2.0.1

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式部署？

Docker Compose

### 在线站点地址

https://demo.halo.run

### 发生了什么？

如图，当插件上传安装异常，仅会提示异常，没有明确原因，且接口返回内容为空。

<img width="1714" alt="image" src="https://user-images.githubusercontent.com/21301288/207256923-c43dfd51-b43a-4019-a933-4539ace9450e.png">

升级会返回异常原因，但前端没有输出：

<img width="1719" alt="image" src="https://user-images.githubusercontent.com/21301288/207257103-abe70f83-968f-441e-8b10-9509b5b9c96a.png">

/area core
/area console
/kind improvement
/milstone 2.1.x

**Comment by JohnNiang** [comment]
在我看来，这个问题已经被 https://github.com/halo-dev/console/pull/769 修复了。@ruibaby

**Comment by ruibaby** [comment]
> 如图，当插件上传安装异常，仅会提示异常，没有明确原因，且接口返回内容为空。

@JohnNiang

**Comment by ruibaby** [comment]
<img width="1683" alt="image" src="https://user-images.githubusercontent.com/21301288/208613392-4e0a6289-188b-4831-846f-0e4e9763cb68.png">

确实可以正确提示，但是浏览器的 Response 为空，不太明白为什么。

**Comment by ruibaby** [comment]
/assign

see https://github.com/halo-dev/console/pull/769

/close
