### ISSUE TITLE
图片上传问题

### ISSUE THREAD

**Issue by betwowt** [halo-dev/halo#2945]
### 是什么版本出现了此问题？

v2.0.1

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式部署？

Docker

### 发生了什么？

使用阿里云oss插件，通过粘贴板先后粘贴三张图片上传，实际结果只有一张图片被上传了，可能原因是三张图片默认粘贴到系统都叫image.png
<img width="644" alt="image" src="https://user-images.githubusercontent.com/16661764/207512189-4ed8151a-84d9-4199-ac0b-3d2763f57db7.png">
<img width="478" alt="image" src="https://user-images.githubusercontent.com/16661764/207512397-a4d108c3-57cd-441f-bec9-af6659d6e72a.png">
<img width="909" alt="image" src="https://user-images.githubusercontent.com/16661764/207512433-458d7086-fe1d-45a3-bf36-d849df6778b6.png">

**Comment by betwowt** [comment]
macos monterey
m1 芯片

**Comment by longjuan** [comment]
> 可能原因是三张图片默认粘贴到系统都叫image.png

本地存储的已经在https://github.com/halo-dev/halo/pull/3042 中修复了
https://github.com/halo-sigs/plugin-alioss 和 https://github.com/halo-sigs/plugin-s3 都没有对同名文件进行处理，导致同名文件只保留第一张或最后一张

这个问题可以通过先headobject查看是否存在同名文件，若同名可与本地存储一样报同名文件已存在错误
另外需不需要增加文件重命名功能，类似：
![image](https://user-images.githubusercontent.com/28662535/211285155-32d30196-043a-4dfa-924f-5cb512ab4dec.png)
@JohnNiang @ruibaby

**Comment by JohnNiang** [comment]
Hi @longjuan ，

IMO，建议暂时和本地上传的逻辑保持一致，通过 S3 上传的图片判断一下 object name 是否重复，如果重复则友好提示用户即可。

**Comment by longjuan** [comment]
> IMO，建议暂时和本地上传的逻辑保持一致，通过 S3 上传的图片判断一下 object name 是否重复，如果重复则友好提示用户即可。

好的
/assign

**Comment by longjuan** [comment]
> Hi @longjuan ，这个问题还需要在 console 端的上传组件还需要优化一下，对于直接粘贴的图片，需要用 `$UUID.png` 替换 `image.png`。

好的，我研究一下

**Comment by longjuan** [comment]
> Hi @longjuan ，这个问题还需要在 console 端的上传组件还需要优化一下，对于直接粘贴的图片，需要用 `$UUID.png` 替换 `image.png`。

我看了一下，被命名为`image.png`似乎是浏览器行为。
在截图后或者其他地方复制一张图片（非本地文件），粘贴到uppy，捕获paste事件发现他name就是`image.png`
![image](https://user-images.githubusercontent.com/28662535/211713831-73c480b4-bfef-4a21-a970-17fd64258c55.png)

而在Firefox中会被命名为`图片.png`
![image](https://user-images.githubusercontent.com/28662535/211714091-a505d519-dd50-4fa1-9205-ccdb6a3ecefd.png)

在复制本地文件然后粘贴时，name就是本地文件名
![image](https://user-images.githubusercontent.com/28662535/211714496-208dff7c-4afe-434d-93dc-b47b2e605769.png)

我想不到有什么好的办法处理不同浏览器的行为，大佬来看看吧 @ruibaby

**Comment by ruibaby** [comment]
> 我想不到有什么好的办法处理不同浏览器的行为，大佬来看看吧 @ruibaby

OK，我会抽时间研究一下。

/assign

**Comment by JohnNiang** [comment]
可能还是得在后端兼容同名的附件上传。无论是本地上传还是 OSS 上传。

**Comment by longjuan** [comment]
> 可能还是得在后端兼容同名的附件上传。无论是本地上传还是 OSS 上传。

什么策略，全部都要重命名还是重复了才重命名，是拼接时间戳吗？

**Comment by lixuejun725** [comment]
> 

项目同样遇到这样的问题，这边觉得可以加上时间戳，毕竟是复制上来的附件一般只在本篇文章使用。复用率很低

**Comment by ruibaby** [comment]
已经在 https://github.com/halo-dev/halo/pull/3305 中支持自动重命名。

/close

**Comment by huanglian666** [comment]
可以麻烦问一下，本地上传方式，上传的图片去哪里呢？
