### ISSUE TITLE
【权限管控】DataEase 模板应用市场关于用户投稿层面的权限需求

### ISSUE THREAD

**Issue by AndroidBaby1** [halo-dev/halo#2947]
### Your current Halo version

2.0

### Describe this feature

1 用户注册
用户端：可以在 halo 上面注册账号，系统默认分配【普通用户】角色给到用户。
管理端：系统有地方可以给【管理员】去配置注册用户的默认角色。

2 文章模块
用户端：
文章状态增加【待审核】状态，用户将自己【已发布】状态的文章提交审核，变为【待审核】状态。
增加【个人中心】页面，个人中心展示用户创作的文章，【普通用户】可以编辑非【已审核】状态的文章。
文章模块主界面显示所有已审核通过的文章，【普通用户】只有查看权限。
管理端：
文章状态增加【已审核】状态，以及文章模板增加【管理中心】页面，【管理中心】所有状态文章，另外有状态刷选给管理员去审核【待审核】状态的文章。
系统有地方可以给管理员去限定只有【已审核】状态的文章可显示在前台。

3  附件模块
用户端：【普通用户】只能查看和编辑自己上传的附件。
管理端：无特殊需求；

**Comment by ruibaby** [comment]
已经在 2.11 中支持。

https://github.com/halo-dev/halo/releases/tag/v2.11.0

/close
