### ISSUE TITLE
Wish the theme upgrade button could be more visible

### ISSUE THREAD

**Issue by JohnNiang** [halo-dev/halo#2948]
### Your current Halo version

2.1.0-SNAPSHOT

### Describe this feature

When I want to upgrade my theme, but it's not easy to find the upgrade button. Because the button is hidden here:

![image](https://user-images.githubusercontent.com/16865714/207533850-cf377509-8073-4b4f-93bf-03dc7acff078.png)

So, I wish the button could be more visible for end users.

### Additional information

/kind improvement
/area console

**Comment by ruibaby** [comment]
我将尝试优化升级、选择主题、激活主题的 UI 和逻辑。
