### ISSUE TITLE
前端无法显示评论回复

### ISSUE THREAD

**Issue by xyhcode** [halo-dev/halo#2951]
### 是什么版本出现了此问题？

2.0.1

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

前台无法显示开启审核后的评论。

### 附加信息

解决： [解决方案来源](https://github.com/halo-sigs/plugin-comment-widget/issues/3#issuecomment-1351387539)
只需要将 `run.halo.app.content.comment.ReplyServiceImpl `的 `reply.getSpec().setHidden(!reply.getSpec().getApproved())`; 修改为初始值 `false` 即可

https://github.com/halo-dev/halo/blob/7a2f5d0a99575e70942dac7a13600650a2ae2b1f/src/main/java/run/halo/app/content/comment/ReplyServiceImpl.java#L65

刚开始使用halo，修改还是各位大佬修改

**Comment by minliacom** [comment]
@xyhcode 这个你要修复吗？如果不修的话我想来尝试提个PR。

**Comment by xyhcode** [comment]
可以 你提交PR吧

**Comment by xyhcode** [comment]
> @xyhcode 这个你要修复吗？如果不修的话我想来尝试提个PR。

可以的 你提交吧
