### ISSUE TITLE
生产环境更新主题没有清理掉模板缓存

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#2953]
### 是什么版本出现了此问题？

2.0.1

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式部署？

Docker Compose

### 在线站点地址

https://techman.run

### 发生了什么？

复现步骤：

1. 任意使用一个主题安装，比如 https://github.com/halo-dev/theme-earth
2. 手动在本地修改此主题的模板。
3. 在后台升级主题。
4. 观察修改的改动是否生效。

我这里是将下面的部分直接删除掉，可以看见更新之后依然存在。

<img width="784" alt="image" src="https://user-images.githubusercontent.com/21301288/207761080-4fd2a305-29b8-4d0e-9c3a-7d6bfc129cff.png">

但去服务器查看主题文件，确实是更新成功的。

<img width="985" alt="image" src="https://user-images.githubusercontent.com/21301288/207761185-50ffbc5f-d22c-4dcb-98e2-04fa23e19bce.png">

/kind bug
/area core
/milestone 2.1.x
/priority critical-urgent

**Comment by guqing** [comment]
更新主题之后可以通过 ThemeResolver 得到 ThemeContext 然后依赖注入 TemplateEngineManager 通过 themeContext 
 得到TemplateEngine，调用 clearTemplateCache 即可

**Comment by minliacom** [comment]
我来试着修复一下吧看看能不能搞定

**Comment by guqing** [comment]
建议在 TemplateEngineManager 添加一个清除模板引擎缓存的方法，更新主题后调用它
