### ISSUE TITLE
归档页面数据，未按月份倒序

### ISSUE THREAD

**Issue by liaocp666** [halo-dev/halo#2958]
### 是什么版本出现了此问题？

2.0.1

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

访问 /archives 地址，目前月份数据升序返回。此处建议月份降序返回。

因为年份是降序，月份升序，月份里的文章是降序。有点错乱。同时如果月份数据降序，对于主题制作时间轴等效果更加友好。

**Comment by minliacom** [comment]
是说要所有都降序吗年月日？

**Comment by ruibaby** [comment]
> 是说要所有都降序吗年月日？

理论上是的。最新的排前面。

**Comment by JohnNiang** [comment]
我的理解，这应该算是一个 bug 吧，并且应该在 2.0.x 也修复掉。 @halo-dev/sig-halo

**Comment by ruibaby** [comment]
> 我的理解：这应该算是一个 bug 吧，并且应该在 2.0.x 也修复掉。 @halo-dev/sig-halo

可以。
