### ISSUE TITLE
CategoryFinder 需要提供根据一个分类查询其下子分类树状结构的方法

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#2960]
### 你当前使用的版本

 2.0.1

### 描述一下此特性

目前虽然有 listAsTree 方法查询所有分类的树状结构，但无法满足根据某一个分类查询下面所有子分类的需求，所以期望提供一个类似 `listAsTreeByName` 的方法。

/kind feature
/area core
/milestone 2.1.x

**Comment by wan92hen** [comment]
> /assign

@Joydevelop  哈喽，现在已经有一个 PR #2962 来解决这个问题了，可以一起 review 下。

**Comment by Joydevelop** [comment]
> > /assign
> 
> @Joydevelop 哈喽，现在已经有一个 PR #2962 来解决这个问题了，可以一起 review 下。

没看到这个pr sry
