### ISSUE TITLE
文章成功导入，但是默认的排序不正确

### ISSUE THREAD

**Issue by jiangmiemie** [halo-dev/halo#2961]
### 是什么版本出现了此问题？

2.0.1

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 在线站点地址

https://www.jiangmiemie.com/

### 发生了什么？

文章成功导入，但是默认的排序不正确（前后端都是如此）

https://www.jiangmiemie.com/upload/debug.png
https://www.jiangmiemie.com/upload/debug2.png

之前是默认按照创建的时间的顺序由近到远

### 附加信息

补充说明：因为文章是长期更新，会有隔段时间回头再次编辑的情况。

**Comment by jiangmiemie** [comment]
找到了一点规律了，他是按照文章的创建时间来排序的，由于导入的过程是乱序的，所以展现的也是乱序的

**Comment by jiangmiemie** [comment]
我查看了一下源码包，我觉得比较好的解决思路是：
1.后台自动同步【发布时间】和【创建时间】
2.用户可以手动修改【创建时间】

**Comment by jiangmiemie** [comment]
临时方案可以是：开放一下H2数据库，提供一下数据库语法，查库改库 同步 createTime 和 updateTime

望采纳

**Comment by ruibaby** [comment]
确实有这样的问题，需要修改一下 https://github.com/halo-sigs/plugin-migrate。

/kind improvement
/area plugin

**Comment by ruibaby** [comment]
> 我查看了一下源码包，我觉得比较好的解决思路是： 1.后台自动同步【发布时间】和【创建时间】 2.用户可以手动修改【创建时间】

资源创建时间无法被修改，只能手动修改发布时间。而且目前默认排序方案应该是按照发布时间的。

**Comment by ruibaby** [comment]
目前已优化这个问题：https://github.com/halo-dev/halo/pull/3148

升级到 2.2.0 即可：https://github.com/halo-dev/halo/releases/tag/v2.2.0

/close
