### ISSUE TITLE
主题错误报出了敏感目录信息

### ISSUE THREAD

**Issue by minliacom** [halo-dev/halo#2969]
### 是什么版本出现了此问题？

2.0.1-SNAPSHOT

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

一个误修改模板，导致模板解析错误，系统报出了服务端目录，有安全风险，望修复

<img width="2055" alt="image" src="https://user-images.githubusercontent.com/10692860/207823189-55ff7831-eb42-4a25-a5b8-0fcd2df20037.png">

**Comment by JohnNiang** [comment]
Halo 目前只支持 Docker 部署，且默认的工作目录是：`/root/.halo2/`，不用显示都能猜到具体的目录位置。

**Comment by minliacom** [comment]
ok 关了
