### ISSUE TITLE
删除主题的时候接口暴露了服务端地址

### ISSUE THREAD

**Issue by minliacom** [halo-dev/halo#2973]
### 是什么版本出现了此问题？

2.0.1-SNAPSHOT

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

删除主题的时候接口暴露了服务端地址

<img width="1928" alt="image" src="https://user-images.githubusercontent.com/10692860/207914069-8319b35b-f439-4146-8866-c333ec59e082.png">

<img width="893" alt="image" src="https://user-images.githubusercontent.com/10692860/207914137-2123918c-641a-435c-8ec6-9908c1f99289.png">

**Comment by JohnNiang** [comment]
没太理解具体暴露了什么重要的地址？如果是暴露了主题存放的位置，我在[这里](https://github.com/halo-dev/halo/issues/2969#issuecomment-1353206790)已经解释过这个问题了。

**Comment by minliacom** [comment]
是的 指的 location 如果不重要就忽略了
