### ISSUE TITLE
关于2.0博客地址问题

### ISSUE THREAD

**Issue by li-ruida** [halo-dev/halo#2983]
### 你当前使用的版本

2.0.1

### 描述一下此特性

我原版本是1.5.3,今天下午尝试了升级到2.0.1,感觉2.0.1很丝滑,但是感觉只能从部署容器前设置博客地址没有1.x版本的后台设置合理,重新部署了好几次打不开文章才发现这个问题,然后我docker-compose.yml文件的外部访问地址修改成我https的域名后打不开了,期待后续版本能像1.x版本一样后台设置链接

**Comment by ruibaby** [comment]
/triage needs-information

可以参考一下这里面的讨论：https://github.com/halo-dev/halo/issues/2818

> 然后我docker-compose.yml文件的外部访问地址修改成我https的域名后打不开了

可以确认已经反向代理正常以及 SSL 配置正常吗？

**Comment by li-ruida** [comment]
反向代理正常以及 SSL 配置是没问题的,我再试试

**Comment by ruibaby** [comment]
@li-ruida 此问题有得到解决吗？

**Comment by li-ruida** [comment]
> @li-ruida 此问题有得到解决吗？

解决了
