### ISSUE TITLE
文章编辑器嵌入网页支持配置宽高等参数

### ISSUE THREAD

**Issue by wan92hen** [halo-dev/halo#2985]
### 你当前使用的版本

2.0.2

### 描述一下此特性

在文章中嵌入网页时只能输入 URL 地址，不能调整宽度、高度及其他 iframe 参数，自动生成的页面高度大部分情况下都不太合适。
![image](https://user-images.githubusercontent.com/27671436/208059561-9243d0b9-9318-43bc-b92f-dbf41dbc522d.png)

希望可以有对应配置手动指定高度、宽度等参数，或者能够根据页面内容自动设置合适的高度。

**Comment by ruibaby** [comment]
> 在文章中嵌入网页时只能输入 URL 地址，不能调整宽度、高度及其他 iframe 参数

目前已经在 https://github.com/halo-sigs/richtext-editor/pull/2 中实现了预设的宽高+自定义宽高设置。这里说的其他 iframe 可以举一些例子吗？ MDN 关于 iframe 的文档中提到，似乎很多参数已经不被推荐使用：https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/iframe#%E4%B8%8D%E8%B5%9E%E6%88%90%E4%BD%BF%E7%94%A8%E7%9A%84%E5%B1%9E%E6%80%A7

**Comment by wan92hen** [comment]
```
<iframe src="//player.bilibili.com/player.html?aid=434483618&bvid=BV1h3411D76J&cid=949353264&page=1" scrolling="no" border="0" frameborder="no" framespacing="0" allowfullscreen="false"> </iframe>
```
iframe 的其他属性可能确实不那么常用了，这里考虑的可能是另一个问题。

**Comment by ruibaby** [comment]
> 这里是不是可以考虑允许直接粘贴 iframe，编辑器自动给处理一把呢？

已在 https://github.com/halo-sigs/richtext-editor/pull/2 的最新提交中实现。
