### ISSUE TITLE
页面亮色、暗色模式可以直接点击按钮进行自动切换，而不需要手动选择

### ISSUE THREAD

**Issue by 2938137849** [halo-dev/halo#2993]
### 你当前使用的版本

2.0.1

### 描述一下此特性

前端页面中，现在右上角的亮色、暗色按钮的功能是鼠标移动上去之后自动显示所有模式的列表，然后还要去列表里面选择具体的模式才能切换。
期望做成直接点击按钮之后就可以自动切换为列表中当前模式的另一个模式（不包括跟随系统）。

### 附加信息

比如现在列表中总共有3项：暗色、亮色、跟随系统。目前为跟随系统，判定为暗色。
点击模式按钮后切换到亮色。再次点击后切换到暗色（跳过了跟随系统）。

**Comment by ruibaby** [comment]
很好的建议。

/kind improvement
