### ISSUE TITLE
状态点(status dot)的悬浮提示跟着闪，需要提升体验

### ISSUE THREAD

**Issue by longjuan** [halo-dev/halo#2994]
### 是什么版本出现了此问题？

2.0.1

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

![ezgif-2-3a85f41723](https://user-images.githubusercontent.com/28662535/208296150-7a54ab7d-b56c-4931-abea-f4d4126f2bad.gif)
鼠标如果没有移到红点正中心，会因为动画改变组件尺寸的原因导致悬浮提示也会闪。

### 相关日志输出

```shell
None
```

**Comment by ruibaby** [comment]
/kind bug
/area console

@longjuan 有兴趣优化一下吗？

**Comment by longjuan** [comment]
这问题似乎不是动画引起的，我把动画关闭了仍然出现此问题

我总结了一下规律：
* 鼠标在点的上半部分大概率触发
* 当我打开浏览器开发者工具，并展开到status dot的层级时触发几率变得很小

同时我搜索了一下，发现gitlab官方也遇到过这个问题，但我看不懂他们怎么把它修复的
https://gitlab.com/gitlab-org/gitlab-foss/-/issues/42228

我前端不太行，搞不定这个问题 @ruibaby

**Comment by JohnNiang** [comment]
从 GitLab issue 中找到一段话，或许是解决方案：
![image](https://user-images.githubusercontent.com/16865714/208397108-f08d95f6-e9e8-4343-a8a6-6501409f689e.png)

**Comment by ruibaby** [comment]
@longjuan OK，我来研究一下。

/milestone 2.1.x

**Comment by ruibaby** [comment]
已经在 https://github.com/halo-dev/console/pull/782 中修复。解决办法是参考了 https://stackoverflow.com/a/52864813

> 但我依然不明白为什么会出现这个问题，以及为什么给 Tooltip 添加 `pointer-events: none;` 样式就可以解决。
