### ISSUE TITLE
在ARM架构服务器上部署时，遇到镜像拉取错误。

### ISSUE THREAD

**Issue by scdlyh** [halo-dev/halo#2997]
### 是什么版本出现了此问题？

halo:2.0.2

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker Compose

### 发生了什么？

服务器为甲骨文Oracle ARM 架构服务器
创建 Halo + MySQL 的实例配置文件 docker-compose.yaml 后，
使用 docker-compose up -d 启动 Halo 服务时，出现以下提示

root@21-4-200537:/usr/local/halos# docker-compose up -d
Pulling halodb (mysql:8.0.27)...
8.0.27: Pulling from library/mysql
ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries

**Comment by ruibaby** [comment]
/triage duplicate

https://github.com/halo-dev/halo/issues/2880
