### ISSUE TITLE
文章展示表格出现问题

### ISSUE THREAD

**Issue by LIU-LIU-LIU** [halo-dev/halo#300]
![image](https://user-images.githubusercontent.com/34854930/65007279-37dae880-d938-11e9-8493-5c97827f24f2.png)
编辑的时候是这样写的，预览也是正常的，发布后就变成下面这个样子  
![image](https://user-images.githubusercontent.com/34854930/65007346-6a84e100-d938-11e9-8c42-956e2066bc96.png)
  
当我手动换行后就会变成这个样子。  
![image](https://user-images.githubusercontent.com/34854930/65007382-8b4d3680-d938-11e9-947b-cca6cbd5ad47.png)
  
环境：
Server 版本：1.0.3
Admin 版本：1.0.3
数据库：MySQL
运行模式：production

**Comment by ruibaby** [comment]
@LIU-LIU-LIU 升级最新版，已解决

**Comment by LIU-LIU-LIU** [comment]
> @刘-LIU-LIU升级最新版，已解决

好的，谢谢，我试一下。
