### ISSUE TITLE
页面无反应

### ISSUE THREAD

**Issue by Jimecc** [halo-dev/halo#3001]
### 是什么版本出现了此问题？

2.0.1

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 在线站点地址

http://blog.shary.cc

### 发生了什么？

# 问题描述
在`/控制台/设置`中点击“基本设置、文章设置、SEO 设置、评论设置、主题路由设置、代码注入”无响应，日志中无报错反应，但是地址栏中的地址会发生变化，此时刷新页面后才会跳转到相应的设置页面。

### 相关日志输出

```shell
无日志产生
```

**Comment by Jimecc** [comment]
# 跟进
抱歉，这可能是一次无效的提交
期初刷新页面后内容无响应，在等待一会儿后刷新页面后好了，可能是浏览器问题（Google Chrome），也可能是前端代码的问题，非常感谢您的阅读。

**Comment by ruibaby** [comment]
可能是这个问题：https://github.com/halo-dev/console/pull/748#pullrequestreview-1206805414

能测试一下我们的 demo 环境是否有此问题吗？ 

https://docs.halo.run/#%E5%9C%A8%E7%BA%BF%E4%BD%93%E9%AA%8C

/kind improvement
/area console

**Comment by Jimecc** [comment]
您好！感谢回复
经测试，Demo环境在此电脑中运行也存在该问题，我同时测试了Safari与Google Chrome，发现这两个浏览器都存在这样的问题，同时发现在Safari中存在登录不进去的问题（Demo环境点击后无响应），Google Chrome存在退出失败问题（个人博客退出无响应）。

**Comment by ruibaby** [comment]
除了 Safari 登录没有反应，其他问题我这里似乎都没有复现，你 Chrome 的版本是多少呢？能否录制一个视频或者 gif 来说明一下这个问题。

> 关于 Safari 登录没有反应的问题，稍后我会提交一个新的 issue。

**Comment by Jimecc** [comment]
# Chrome 版本
Chrome 已是最新版本
版本 108.0.5359.124（正式版本） (arm64)

# 录屏信息
可以点击该链接查看：http://down.shary.cc/directlink/down/bin/08.mov

**Comment by ruibaby** [comment]
@Jimecc 浏览器的控制台也没有任何异常日志吗？
