### ISSUE TITLE
期望系统设置中的 Favicon 设置对 Console 端也生效

### ISSUE THREAD

**Issue by chengfeiyue** [halo-dev/halo#3010]
### Your current Halo version

2.0.1

### Describe this feature

![image](https://user-images.githubusercontent.com/49852751/208601100-fd69358b-810b-4ffa-be44-31bafd79299a.png)
（能改logo就行）

**Comment by ruibaby** [comment]
/area console
/milestone 2.1.x

可以考虑使用 VueUse 的 https://vueuse.org/core/usefavicon/#usefavicon 来实现。
