### ISSUE TITLE
Console 端的文件上传组件在非 https 环境下使用拖拽上传会导致浏览器崩溃

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#3017]
### 是什么版本出现了此问题？

2.0.2

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式部署？

Docker Compose

### 在线站点地址

https://demo.halo.run

### 发生了什么？

目前我们使用了 [transloadit/uppy](https://github.com/transloadit/uppy) 作为上传组件。目前发现在非 HTTPS 协议的网站上拖拽文件上传会导致浏览器崩溃。根据 uppy 维护者所说，这可能是 Chrome 的问题，请参考：

- https://github.com/transloadit/uppy/issues/976
- https://github.com/transloadit/uppy/issues/4133
- https://bugs.chromium.org/p/chromium/issues/detail?id=388661

**Comment by ruibaby** [comment]
我将尝试判断当前站点是否是 https 协议，如果不是，将禁用拖拽上传，仅能选择文件。

**Comment by AlanWZHU** [comment]
应该是浏览器问题 我用了firefox 没有问题 用了chrome 会崩溃

**Comment by ruibaby** [comment]
Uppy 似乎对此有了一个修复：https://github.com/transloadit/uppy/pull/4310

等待合并和发版本。
