### ISSUE TITLE
Halo2 打开文章详情页很慢

### ISSUE THREAD

**Issue by Uyouii** [halo-dev/halo#3019]
### What is version of Halo has the issue?

2.02

### What database are you using?

MySQL 8.x

### What is your deployment method?

Docker Compose

### Your site address.

https://uyouii.cool

### What happened?

云服务器操作系统：Ubuntu 22.04 LTS
机器：4核8G
每次打开文章，服务器需要响应 8s左右，十分影响体验
发现cpu并没有被跑满，4核大概占用50%的cpu，是halo2性能问题还是bug？

**Comment by guqing** [comment]
服务器带宽是多大的呢

**Comment by Uyouii** [comment]
带宽是2M😂，但是看上去不是带宽的原因， 主要耗时在等待服务器响应，但是性能又没跑满，不知道是什么原因。
<img width="610" alt="截屏2022-12-21 15 38 01" src="https://user-images.githubusercontent.com/25459212/208847687-36421390-220a-46a3-af55-76ae07e6cb09.png">

**Comment by Uyouii** [comment]
服务端资源占用：
<img width="858" alt="截屏2022-12-21 15 42 16" src="https://user-images.githubusercontent.com/25459212/208848461-f8b5eb1a-4a9f-4e42-b9dd-c6fdafab4060.png">

**Comment by JohnNiang** [comment]
建议更换一个主题后再试试。

**Comment by Uyouii** [comment]
> 建议更换一个主题后再试试。

用默认的eath主题，测试发现效果是一样的，首页加载很快，但是文章详情页很慢

**Comment by Uyouii** [comment]
重装下系统试试

**Comment by ruibaby** [comment]
> 这次安装到了root用户下，反应就很快，也许是这个问题

这似乎没有什么必然的联系。

**Comment by Uyouii** [comment]
> > 这次安装到了root用户下，反应就很快，也许是这个问题
> 
> 这似乎没有什么必然的联系。

但是确实重装一些就好了，而且两次的区别只有安装的用户不通，会不会是因为docker里的某些操作限制了root用户？

**Comment by JohnNiang** [comment]
没有具体的环境，无法分析具体的原因。

**Comment by Uyouii** [comment]
maybe another reason
