### ISSUE TITLE
Halo2 随着文章数量增加，打开文章详情页面时间 线性增长。

### ISSUE THREAD

**Issue by Uyouii** [halo-dev/halo#3026]
### What is version of Halo has the issue?

2.02

### What database are you using?

MySQL 8.x

### What is your deployment method?

Docker Compose

### Your site address.

https://uyouii.cool

### What happened?

发现随着添加文章的增多，打开文章详情页时等待服务器响应时间会不断增加。（按道理应该没有关系？）
亲测和主题无关。
只添加一篇文章时，大概只有< 100ms的响应时间，
到添加到第10篇文章时，会有> 1s的响应时间。

**Comment by Uyouii** [comment]
<img width="778" alt="截屏2022-12-22 01 14 42" src="https://user-images.githubusercontent.com/25459212/208964933-f6e8015c-f870-4282-bab8-d0e0d66e4012.png">

**Comment by Uyouii** [comment]
发现有类似issue：https://github.com/halo-dev/halo/issues/2863

**Comment by JohnNiang** [comment]
/triage duplicate

Hi @Uyouii ，感谢反馈这个问题。我最近会着手排查具体的原因并尝试优化，建议持续跟进 <https://github.com/halo-dev/halo/issues/2863>。

**Comment by Uyouii** [comment]
> /triage duplicate
> 
> Hi @Uyouii ，感谢反馈这个问题。我最近会着手排查具体的原因并尝试优化，建议持续跟进 #2863。

感谢答复～，不过两个issue还有一点点区别，https://github.com/halo-dev/halo/issues/2863 看上去是说文章较多时刚启动后运行缓慢，这里是发现无论启动多久，打开文章的等待服务器响应时间和会随着文章总数增长。

**Comment by Uyouii** [comment]
暂时先切换回 halo 1.6版本了

**Comment by chengfeiyue** [comment]
遇到了同样的问题
镜像版本：2.1.0-RC1
数据库：postgresql
部署方式：Docker Compose（K8s）

**Comment by JohnNiang** [comment]
@chengfeiyue 可参考 <https://github.com/halo-dev/halo/issues/2863#issuecomment-1376664008>。

**Comment by Uyouii** [comment]
@chengfeiyue 紧急的话可以先切换为halo1.6版本，我目前切换成了1.6版本没有这个问题，我想等2.x版本稳定后用官方的升级工具再切换到2.x版本

**Comment by chengfeiyue** [comment]
不能切换为1.6版本的，我们给使用客户基于2.x 版本开发了一个主题，和几个插件，那就等咱们这边优化这个问题吧
