### ISSUE TITLE
无用户查看权限角色的用户无法在 Console 端访问个人资料页面

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#3027]
### 是什么版本出现了此问题？

2.0.2

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式部署？

Docker Compose

### 在线站点地址

https://demo.halo.run

### 发生了什么？

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/21301288/209046340-5eae1fd3-d397-4b47-82ee-f30e300b1248.png">

可以看到，访问个人资料页面请求的接口是 `/api/v1alpha1/users/{username}`，理论上自己查看自己的个人资料应该是访问 `/apis/api.console.halo.run/v1alpha1/users/-`。

这里需要区分一下：

1. 有用户管理权限的用户访问其他用户的资料。
2. 已登录用户访问自己的资料。

/kind bug
/area console
/milestone 2.1.x

**Comment by ruibaby** [comment]
后续的最佳做法应该是有一个个人中心，可以考虑将管理端和个人中心区分开。

**Comment by JohnNiang** [comment]
非常赞同在 console 端做一个个人中心。

**Comment by ruibaby** [comment]
> 非常赞同在 console 端做一个个人中心。

可以考虑将上面那个 issue 规划到 2.2.0，这个 issue 主要解决当前的问题。
