### ISSUE TITLE
halo-sigs多个库中的plugin.yaml中license与仓库中LICENSE不同

### ISSUE THREAD

**Issue by longjuan** [halo-dev/halo#3034]
### 你当前使用的版本

None

### 描述一下此特性

https://github.com/halo-sigs/plugin-alioss/blob/main/src/main/resources/plugin.yaml
https://github.com/halo-sigs/plugin-alioss/blob/main/LICENSE
https://github.com/halo-sigs/plugin-s3/blob/main/src/main/resources/plugin.yaml
https://github.com/halo-sigs/plugin-s3/blob/main/LICENSE
plugin.yaml中的是MIT
LICENSE中的是GPLv3

**Comment by longjuan** [comment]
留GPLv3还是MIT？ @ruibaby

**Comment by ruibaby** [comment]
> 留GPLv3还是MIT？ @ruibaby

GPL v3

**Comment by longjuan** [comment]
https://github.com/halo-sigs/plugin-s3
https://github.com/halo-sigs/plugin-alioss
https://github.com/halo-sigs/plugin-sitemap
https://github.com/halo-sigs/plugin-migrate
https://github.com/halo-sigs/plugin-highlightjs
https://github.com/halo-sigs/plugin-lightgallery
https://github.com/halo-sigs/plugin-links
https://github.com/halo-sigs/plugin-comment-widget
https://github.com/halo-sigs/plugin-search-widget
https://github.com/halo-sigs/plugin-umami (WIP)
https://github.com/halo-sigs/plugin-unsplash
https://github.com/halo-sigs/plugin-moments (WIP)
https://github.com/halo-sigs/plugin-photos (WIP)
https://github.com/halo-sigs/plugin-qiniu-kodo (WIP)
https://github.com/halo-sigs/plugin-feed (WIP)
https://github.com/halo-sigs/plugin-meilisearch (WIP)
均有这个问题，有空再弄吧，我这几天赶个论文初稿
/unassign

**Comment by ruibaby** [comment]
halo-sigs 组织下的仓库都已经提交 PR 更新 plugin.yaml 中的 License 信息。

/close
