### ISSUE TITLE
期望提供一个修改当前登录用户资料的接口

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#3035]
### 你当前使用的版本

2.0.2

### 描述一下此特性

目前已登录用户无法修改自己的个人资料，仅能修改密码。期望提供一个类似 `/apis/api.console.halo.run/v1alpha1/users/-/password` 的接口来修改个人资料。

<img width="1721" alt="image" src="https://user-images.githubusercontent.com/21301288/209286689-4ea0e96a-b29c-4b4d-b8a0-6f50e7df6b7b.png">

/kind feature
/area core

**Comment by JohnNiang** [comment]
”个人资料“页面似乎也无法获取当前用户信息。
