### ISSUE TITLE
halo1.5最新版本目录设置密码以及文章设置密码不跳转问题反馈

### ISSUE THREAD

**Issue by qgx66** [halo-dev/halo#3037]
### 是什么版本出现了此问题？

1.5最新版

### 使用的什么数据库？

Other

### 使用的哪种方式部署？

Docker

### 在线站点地址

http://www.qigx.love:1314/categories/message

### 发生了什么？

密码：123456，输入之后页面不认证跳转，

**Comment by ruibaby** [comment]
<img width="1494" alt="image" src="https://user-images.githubusercontent.com/21301288/209318926-f4654977-9c0a-4676-afd0-030262bcc82e.png">

你后台的博客设置中的博客地址带了 `http://` 了吗？

/kind support

**Comment by qgx66** [comment]
> <img alt="图像" width="1494" src="https://user-images.githubusercontent.com/21301288/209318926-f4654977-9c0a-4676-afd0-030262bcc82e.png">
> 
> 你后台的博客设置中的博客地址带了 了吗？`http://`
> 
> /亲切的支持
感谢您的热心回复，果然是这个问题，博客设置加了Http://访问跳转正常了
