### ISSUE TITLE
升级到https后，头像没有更新地址

### ISSUE THREAD

**Issue by Uyuhz** [halo-dev/halo#304]
我看改完博客地址变为https后，附件已经自动改了地址，但是头像请求地址没有自动更新依然使用http，这里是不是应该自动更新的呢？

**Comment by JohnNiang** [comment]
是的，因为当初添加头像的地址为绝对地址，所以造成了这个问题。

**Comment by JohnNiang** [comment]
关于自动更新的问题，我们会好好考虑的。

**Comment by Uyuhz** [comment]
@JohnNiang 顺便问一下，我打开了新评论通知和回复评论通知对方，并且设置了smtp服务，但是我增加一个评论收不到邮件，而回复评论可以收到，请问可能是什么原因呢？我使用的163邮箱

**Comment by JohnNiang** [comment]
请问查询一下日志是否有报错呢？

日志位置：~/.halo/logs/spring.log

**Comment by Uyuhz** [comment]
@JohnNiang 没有报错

**Comment by JohnNiang** [comment]
好的，我们测试一下这个问题。

谢谢反馈！

**Comment by Uyuhz** [comment]
@JohnNiang 
sorry，我发现是我理解错了...我以为邮件通知是发送给我设置的smtp服务的邮箱，实际上是直接发给我的个人资料里设置的邮箱了。但是我感觉我好像被开启评论通知的提示误导了....我还好奇了半天评论通知的发件人应该是谁.....刚才去瞄了眼谷歌邮箱才发现.....

**Comment by JohnNiang** [comment]
没事，知道原因就好了。
