### ISSUE TITLE
附件上传完成后，链接地址跳转问题

### ISSUE THREAD

**Issue by ShermanQ** [halo-dev/halo#3040]
### 是什么版本出现了此问题？

2.0.2

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker Compose

### 发生了什么？

![image](https://user-images.githubusercontent.com/25702506/209430983-2e93b89e-7de4-4d51-8cf2-a3138719ea25.png)
附件上传完成之后，附件地址被错误加上了console前缀，导致附件地址错误

**Comment by ruibaby** [comment]
是否有正确设置 `HALO_EXTERNAL_URL`？

https://docs.halo.run/getting-started/install/docker-compose

/kind support
/triage needs-information

**Comment by ShermanQ** [comment]
感谢， HALO_EXTERNAL_URL地址需要加入Https前缀

Ryan Wang ***@***.***> 于2022年12月26日周一 11:38写道：
