### ISSUE TITLE
文章可见性控制

### ISSUE THREAD

**Issue by Alanrah** [halo-dev/halo#3048]
### 是什么版本出现了此问题？

2.0

### 使用的什么数据库？

Other

### 使用的哪种方式部署？

Docker

### 在线站点地址

https://docs.halo.run/user-guide/posts, https://demo.halo.run/console/#/posts

### 发生了什么？

文档 https://docs.halo.run/user-guide/posts 里面写，文章的可见性分为三种，“公开/内部成员可访问/私有”，但是demo里面 只有公开和私有两种 https://demo.halo.run/console/#/posts ，是有其他权限配置控制“内部成员可访问”这个权限么？

**Comment by ruibaby** [comment]
/triage duplicate

see https://github.com/halo-dev/halo/issues/2934 https://github.com/halo-dev/halo/issues/3016
