### ISSUE TITLE
增加管理台评论日志Journals Tab

### ISSUE THREAD

**Issue by Uyuhz** [halo-dev/halo#305]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [x] 添加新的特性或者功能
- [x] 请求技术支持

---

1. 打开了评论审核后，对日志的评论没有入口去审核，而且在日志页面挨个点进去看才能看到评论列表也有些不便。
2. 管理台日志页面评论数量把未通过的评论也算在内，但是点进去却不显示未通过的。
3. 日志的评论通知标题使用的是创建时间，进邮箱一看一头雾水。

看了下代码，后台日志评论/审核等功能是已经有了的，但是`halo-admin`里评论页代码只有对tab页类型journal的判断却没有相关的代码，于是想问下是在做还是有什么别的考虑呢？

~~翻了下社区和issues，好像基本没啥人用journals这个功能，是不是halo里用的最少的页面了😂~~

**Comment by ruibaby** [comment]
@Uyuhz 关于日志这块我们暂时只提出了这个方法，可能可用程度还不够，而且支持的主题也很少，目前也就一个主题支持。后续我们会让它更好用的。

**Comment by JohnNiang** [comment]
You got it.

日志方面确实还很脆弱，很少有主题适配了日志模板。

你说的两个问题确实存在，我们会好好处理的。

1. 评论数量包含已删除或未审核的评论；
2. 日志评论 Tab。

**Comment by lsh1358046425** [comment]
现在这个问题有解决吗？日志的评论只能在日志管理页面查看，也看不见评论人的详细信息，邮件通知标题还是日期.......

**Comment by ruibaby** [comment]
> @JohnNiang 现在这个问题有解决吗？日志的评论只能在日志管理页面查看，也看不见评论人的详细信息，邮件通知标题还是日期.......

目前是这样的，我们打算在 1.5.x 重新设计此功能。
