### ISSUE TITLE
文章分类树形结构展示

### ISSUE THREAD

**Issue by chengfeiyue** [halo-dev/halo#3054]
### 你当前使用的版本

2.1.0-rc.1

### 描述一下此特性

当文章所属的分类具有层级关系时，没有树形结构展示
<img width="687" alt="image" src="https://user-images.githubusercontent.com/49852751/209607181-d6108b92-b981-4c93-ac53-f6ff16613dd4.png">

**Comment by wan92hen** [comment]
#2485

**Comment by chengfeiyue** [comment]
OK,刚搜索issue时没搜到，误以为没这个issue。
