### ISSUE TITLE
添加修改文章作者功能

### ISSUE THREAD

**Issue by CosmoGao** [halo-dev/halo#3056]
### 你当前使用的版本

2.1.0-rc.1

### 描述一下此特性

2.0以后，halo已经支持多用户，期待可以修改已发布文章的作者，目前和账号是强绑定的，无法代发文章，导入的文章也都是归为导入者的名下。

**Comment by ruibaby** [comment]
2.0 的 RSS 订阅功能将使用插件实现。

- https://github.com/halo-sigs/plugin-feed
- https://github.com/halo-sigs/plugin-feed/issues/1

/area plugin
/kind feature
