### ISSUE TITLE
建议增加RSS订阅功能

### ISSUE THREAD

**Issue by CosmoGao** [halo-dev/halo#3057]
### 你当前使用的版本

2.1.0-rc.1

### 描述一下此特性

1.x时支持rss订阅 rss.xml/atom.xml，升级2.0后没有了这个功能，建议增加或通过插件支持

**Comment by ruibaby** [comment]
2.0 的 RSS 订阅功能将使用插件实现。

- https://github.com/halo-sigs/plugin-feed
- https://github.com/halo-sigs/plugin-feed/issues/1

/area plugin
/kind feature

**Comment by ruibaby** [comment]
see https://github.com/halo-sigs/plugin-feed

/close
