### ISSUE TITLE
用户端标签没有正确应用后台设置的颜色

### ISSUE THREAD

**Issue by minliacom** [halo-dev/halo#3058]
### 是什么版本出现了此问题？

2.1.0-rc.1

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

在后台设置了标签的颜色，用户端没有显示正确的颜色

<img width="547" alt="image" src="https://user-images.githubusercontent.com/10692860/209611145-f7516527-4f09-4949-824a-bdd66e1729a2.png">

<img width="1428" alt="image" src="https://user-images.githubusercontent.com/10692860/209611156-b54ef3fc-a118-4c78-bbfe-143f9eeb2b3f.png">

**Comment by minliacom** [comment]
我理解错了，颜色是拿来给后端看的，不是前台看的，关了，关了。

**Comment by JohnNiang** [comment]
标签的颜色是否适配，取决于主题是否适合渲染颜色。
