### ISSUE TITLE
针对当前启用主题屏蔽启用选项

### ISSUE THREAD

**Issue by wan92hen** [halo-dev/halo#3059]
### 你当前使用的版本

2.1.0-rc.1

### 描述一下此特性

屏蔽当前启用主题更多操作中的启用选项
![image](https://user-images.githubusercontent.com/27671436/209638663-553635cb-2cfc-4a41-82db-afd1bd95846a.png)

**Comment by JohnNiang** [comment]
IMO，可以直接移除该选项。主题详情页面是有启用主题的功能的，这里若是再包含”启用“选项，显得有些多余。
