### ISSUE TITLE
多个编辑器选择不方便

### ISSUE THREAD

**Issue by muyunil** [halo-dev/halo#3060]
### 是什么版本出现了此问题？

2.1.0-rc.1

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

安装bytemd编辑器插件之后，文章编辑正常，但独立界面例如 “关于” 默认没有选择编辑器提示，直接用默认的富文本编辑器打开，目前解决办法是：手动修改独立页面元数据添加编辑器kv，并且将编辑器kv置顶，否则可以编辑但发布后没办法渲染，显示空白。
建议是用一个变量设置全局编辑器（比如只能
启用一个编辑器），而不是每次都要选择编辑器打开。

**Comment by ruibaby** [comment]
没有复现这个问题。

<img width="1662" alt="image" src="https://user-images.githubusercontent.com/21301288/209746765-a10051cc-4917-4a34-8578-b330487d0734.png">
<img width="1665" alt="image" src="https://user-images.githubusercontent.com/21301288/209746794-61acae57-98cc-44e2-ba3d-abf015d27093.png">
<img width="707" alt="image" src="https://user-images.githubusercontent.com/21301288/209746817-0c19ce3d-213c-4586-90b5-8433427988e1.png">

**Comment by ruibaby** [comment]
至于编辑器选择的问题，我将尝试做以下修改：

1. 取消新建入口的编辑器选择。
2. 改为在编辑页面选择，首次使用默认编辑器。
3. 但修改为其他编辑器之后会在本地建立缓存，下次再进入会使用之前选择的编辑器。
4. 目前不打算支持在全局提供一个设置，后续我们会提供一个集成的模块（可能包括搜索引擎、评论模块、编辑器等的设置）

**Comment by muyunil** [comment]
> 没有复现这个问题。
> 
> <img alt=" Image" width="1662" src="https://user-images.githubusercontent.com/21301288/209746765-a10051cc-4917-4a34-8578-b330487d0734.png">
> 
> <img alt=" image" width="1665" src="https://user-images.githubusercontent.com/21301288/209746794-61acae57-98cc-44e2-ba3d-abf015d27093.png">
> 
> <img alt=" image" width="707" src="https://user-images.githubusercontent.com/21301288/209746817-0c19ce3d-213c-4586-90b5-8433427988e1.png">

看了下新建是正常的，准确来说是插件启用前已有的页面默认不启用其他编辑器，不过这到也不是啥bug了。

**Comment by ruibaby** [comment]
@muyunil 目前不支持发布后再切换其他编辑器，因为这可能涉及到格式转换。
