### ISSUE TITLE
初始化完成只有一张表

### ISSUE THREAD

**Issue by zj-dreamly** [halo-dev/halo#3061]
### 是什么版本出现了此问题？

2.0.2

### 使用的什么数据库？

MySQL 5.7

### 使用的哪种方式部署？

Docker Compose

### 发生了什么？

![image](https://user-images.githubusercontent.com/33167831/209672823-45a0bfc5-74e9-410c-8ef2-4f7cfd0b7aa7.png)
但是我看功能都正常的，上传了一个附件，是成功的

因为我想用自己本地的一个数据库，所以没用它内部构建的数据库，这么配置是有问题吗

![image](https://user-images.githubusercontent.com/33167831/209673096-0cf87154-af97-4e30-8e65-4151c88b5df0.png)

**Comment by JohnNiang** [comment]
Halo 确实只创建了一张表，当时就是这么设计的。

参考：
- https://github.com/halo-dev/rfcs/tree/main/extension

**Comment by zj-dreamly** [comment]
哦哦，谢谢

**Comment by JohnNiang** [comment]
我将关闭这个 issue，有任何问题可随时打开。

/close
