### ISSUE TITLE
主题自定义的错误页面不生效

### ISSUE THREAD

**Issue by guqing** [halo-dev/halo#3062]
### 是什么版本出现了此问题？

latest

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

主题定义了错误页面
<img width="331" alt="image" src="https://user-images.githubusercontent.com/38999863/209771502-ee5e0535-0e95-49b3-b6f9-ff94283aaa83.png">

但还是使用的默认页面错误
<img width="691" alt="image" src="https://user-images.githubusercontent.com/38999863/209771471-d81cfde0-6aae-45a5-a5a5-a28ccd155e03.png">

此为PR https://github.com/halo-dev/halo/pull/3042 新引入问题

### 附加信息

/kind bug
/milestone 2.1.x
/assign @JohnNiang

**Comment by JohnNiang** [comment]
建议提供一下测试的主题文件。

**Comment by guqing** [comment]
> 建议提供一下测试的主题文件。

https://github.com/guqing/halo-theme-higan/archive/refs/tags/v2.0.0.zip
