### ISSUE TITLE
关于增加referrer开关的需求

### ISSUE THREAD

**Issue by cuiyanjie** [halo-dev/halo#3064]
### 你当前使用的版本

2.1.0-rc.1

### 描述一下此特性

2.0.2及以前的版本一直会复制粘贴语雀App写的文章，图片一直显示正常，更新到2.1.0-rc.1之后图片都错误了。在telegram上与John Niang 朋友沟通后，判断是referer功能的问题。于是设想在正式版增加referer开关功能，如果放弃访问分析工具就可以关闭referer

**Comment by ruibaby** [comment]
我认为这是一个非常规的需求，问题的本质是语雀的防盗链。如果一定要支持，两个方案：

1. 在网页 head 部分添加 `<meta name="referrer" content="no-referrer" />`

<img width="732" alt="image" src="https://user-images.githubusercontent.com/21301288/209775871-b2d85711-7f9d-4d25-8328-2d3e42904521.png">

2. 在 Nginx 隐藏或者覆盖掉 `Referrer-Policy` 的 header 参数。

解决这个问题的正确方式应该是转存外部的图片。

/kind support

**Comment by JohnNiang** [comment]
Hi @cuiyanjie ，方便测试一下 https://github.com/halo-dev/halo/issues/3064#issuecomment-1366434677 提到的方法么？

**Comment by cuiyanjie** [comment]
抱歉，上游服务器pdu坏了，目前正在维护

**Comment by ruibaby** [comment]
很抱歉，之前只是根据经验来主观判断，并未实际测试，刚实际测试确实发现有问题，请看：

- Halo 2.1：https://techman.run/archives/1673448837623
- Halo 1.6.1：https://ryanc.cc/moments.html
- Wiki.js：https://wiki.demo.ryanc.cc/zh/home

**Comment by JohnNiang** [comment]
还是提供一个配置来决定是否开启 Referer 吧。

**Comment by ruibaby** [comment]
> 还是提供一个配置来决定是否开启 Referer 吧。

<img width="1657" alt="image" src="https://user-images.githubusercontent.com/21301288/211999750-fb7088e4-107d-429d-bc0d-b35766171001.png">
 
Wiki.js 的请求头。

**Comment by JohnNiang** [comment]
Halo 的 Referer 策略：

https://github.com/halo-dev/halo/blob/ca4e93d4bbfa849a91c7e4acca231bb1c8ffd10d/src/main/java/run/halo/app/config/WebServerSecurityConfig.java#L85

**Comment by DarkWayne** [comment]
@JohnNiang @ruibaby  请问上面有提到支持referrer开关 的能力，问一下目前是什么状态及如何使用，感谢两位！~

**Comment by ruibaby** [comment]
> @JohnNiang @ruibaby 请问上面有提到支持referrer开关 的能力，问一下目前是什么状态及如何使用，感谢两位！~

你暂时可以参考：https://github.com/halo-dev/halo/pull/3614#issue-1644951948

对应到 Docker 的启动参数配置为：`--halo.security.referrer-options.policy=no-referrer`
