### ISSUE TITLE
 移除自定义的 SpringTemplateEngine

### ISSUE THREAD

**Issue by guqing** [halo-dev/halo#3070]
### Your current Halo version

latest

### Describe this feature

之前由于 thymeleaf 限制，无法使用自定义的 MessageResolver 配置，因此不得不使用 copy 源码修改的方式实现。
目前 thymeleaf 已经修改了 SpringTemplateEngine#initializeSpecific 方法的实现，并且 springboot 3.0.1 已经升级到应用了此修改的 thymeleaf 3.1.1 版本 
https://github.com/thymeleaf/thymeleaf/commit/47c95be4fc4eeea416853d923da485a737ea1062

是时候优化它了

### Additional information

/kind improvement
/area core
/milestone 2.2.x

**Comment by JohnNiang** [comment]
为了排除自定义的 TemplateEngine 对错误模板渲染的影响，我将尝试修复这个问题。
