### ISSUE TITLE
主题端调用资源的 Annotations 不方便

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#3073]
### 你当前使用的版本

2.1.0-rc.1

### 描述一下此特性

目前 2.1.0-rc.1 支持了对模型的 Annotations 进行表单定义，目的是为了让插件和主题可以扩展元数据（字段），但目前在主题端调用和判断不是特别方便，请看：

```
<div
  th:style="|background:${categoryItem.metadata.annotations != null ? (categoryItem.metadata.annotations['bgColor'] ?: '#fff') : ''}|"
></div>
```

1. 无法得知 `annotations` 是否为 null，所以需要判断，防止模板渲染异常。
2. 调用链过长。

希望针对主题的调用进行优化。

/kind improvement
/area core
/milestone 2.1.x

**Comment by guqing** [comment]
提供对象表达式 `${#annotations.get(some-extension, 'halo.run/icon')}` 等来获取 annotation
