### ISSUE TITLE
发布 2.0.3

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#3078]
### 你当前使用的版本

2.1.0-rc.1

### 描述一下此特性

希望在发布 [2.1.0](https://github.com/halo-dev/halo/issues/3077) 之前发布 2.0.3。

/kind improvement
/milestone 2.0.3

**Comment by JohnNiang** [comment]
See https://github.com/halo-dev/halo/releases/tag/v2.0.3 for more.
/close
