### ISSUE TITLE
打开文章设置导致发布时间丢失

### ISSUE THREAD

**Issue by cuiyanjie** [halo-dev/halo#3080]
### 是什么版本出现了此问题？

2.1.0-rc.1

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式部署？

Docker Compose

### 发生了什么？

问题一：已发表的文章，重新编辑时，进入设置菜单会默认增加一条元数据，发布时间也不显示了。
![telegram-cloud-photo-size-1-5003637694865189742-y](https://pic-1255454601.cos.ap-beijing.myqcloud.com/picgo/202212291934161.webp)
![telegram-cloud-photo-size-1-5003637694865189743-y](https://pic-1255454601.cos.ap-beijing.myqcloud.com/picgo/telegram-cloud-photo-size-1-5003637694865189743-y.webp)
问题二：2.0开始，文章中图片居中发布后，无效果，仍然居左

**Comment by ruibaby** [comment]
> 问题二：2.0开始，文章中图片居中发布后，无效果，仍然居左

请单独提交 issue，此 issue 仅用于跟踪设置的问题。

/kind bug
/area console
/assign
/milestone 2.1.x
