### ISSUE TITLE
标签过多时文章 title 无法显示

### ISSUE THREAD

**Issue by guqing** [halo-dev/halo#3081]
### 是什么版本出现了此问题？

latest

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

13英寸屏幕
当标签多且有内容未发布时只能显示一个绿点而无法显示标题
<img width="1373" alt="image" src="https://user-images.githubusercontent.com/38999863/209957360-fb1a3734-eff8-407d-a61f-e4287a414fc5.png">
当处于发布状态时
![Kapture 2022-12-29 at 21 20 55](https://user-images.githubusercontent.com/38999863/209958551-2b77bdbd-ea2e-495b-8e56-3624aa5cc31f.gif)

### 附加信息

/kind improvement
/area console

**Comment by ruibaby** [comment]
/triage duplicate

see https://github.com/halo-dev/halo/issues/2926

/close
