### ISSUE TITLE
halo在2.1.0版本中取消了 文章的最后更新时间 这一属性吗？

### ISSUE THREAD

**Issue by AKmoex** [halo-dev/halo#3090]
### 你当前使用的版本

2.1.0

### 描述一下此特性

2.1.0不支持文章的最后更新时间吗？我通过1.x版本中导出文章发现1.x中是支持文章的最后更新时间这一属性的，而在2.1.0版本中却没有发现这一属性

**Comment by ruibaby** [comment]
/kind feature
/milestone 2.2.x

目前确实没有，需要添加。
