### ISSUE TITLE
文章评论按钮无反应

### ISSUE THREAD

**Issue by LDYang694** [halo-dev/halo#3094]
### 是什么版本出现了此问题？

halo:2.0.2

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker Compose

### 在线站点地址

https://server.szhhh.top/archives/hello-halo

### 发生了什么？

文章点击评论按钮无反应，好像是评论区没有显示?
评论已经打开，但并没有找到评论区在那里

### 相关日志输出

```shell
docker里面并没有相关的日志输出
```

### 附加信息

![image](https://user-images.githubusercontent.com/62846124/210161111-84f6e7ef-9bbe-4b79-80f9-997876cc2a88.png)
![image](https://user-images.githubusercontent.com/62846124/210161126-ecebfb98-3c51-4f8a-9959-0541b9fcce71.png)

**Comment by ruibaby** [comment]
是否有安装 https://github.com/halo-sigs/plugin-comment-widget 插件。目前还没有预设插件的功能，所以如果需要评论组件需要手动安装插件。

/triage needs-information

**Comment by LDYang694** [comment]
抱歉 没有安装评论插件，安装后可以正常评论了，建议如果没有安装评论插件可以将评论按钮默认隐藏，避免造成误解？

**Comment by ruibaby** [comment]
> 抱歉 没有安装评论插件，安装后可以正常评论了，建议如果没有安装评论插件可以将评论按钮默认隐藏，避免造成误解？

很好的建议，issue 已创建：https://github.com/halo-dev/theme-earth/issues/38
