### ISSUE TITLE
自动生成的sitemap中部分链接不正确

### ISSUE THREAD

**Issue by XuCpeng** [halo-dev/halo#310]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

今天google发邮件说有5个链接出现了错误，我查看了一下sitemap.xml，其中的部分网址的确无法访问。
简单的测试了一下，好像只要链接中含有空格时就会出现这个问题，sitemap会用```+```代替，而实际的网址是用```%20```。

例如：
sitemap中的描述：
- https://x.medemede.cn/archives/sitmap+test
- https://x.medemede.cn/archives/Win10%E4%B8%8B%E4%BD%BF%E7%94%A8Visual+Studio2019%E7%BC%96%E8%AF%91Darknet
- https://x.medemede.cn/archives/YOLOv3%E5%AE%89%E8%A3%85with+cuda+opencv%EF%BC%8C%E8%A7%A3%E5%86%B3out+of+memory

实际网址：
- https://x.medemede.cn/archives/sitmap%20test
- https://x.medemede.cn/archives/Win10%E4%B8%8B%E4%BD%BF%E7%94%A8Visual%20Studio2019%E7%BC%96%E8%AF%91Darknet
- https://x.medemede.cn/archives/YOLOv3%E5%AE%89%E8%A3%85with%20cuda%20opencv%EF%BC%8C%E8%A7%A3%E5%86%B3out%20of%20memory

sitemap.xml地址：https://x.medemede.cn/sitemap.xml

**Comment by ruibaby** [comment]
嗯 应该是 URLEncode 把空格转成了+号。

**Comment by ruibaby** [comment]
这个问题已解决：https://github.com/halo-dev/halo/commit/cd2c3a17b37c2a71d96342fee5ee7ab05eed8d66
