### ISSUE TITLE
打开已保存的StackEdit编辑器编辑的文章内容空白

### ISSUE THREAD

**Issue by wan92hen** [halo-dev/halo#3105]
### 是什么版本出现了此问题？

2.1.0

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式部署？

Docker

### 发生了什么？

打开一篇已保存的使用StackEdit编辑器编辑的文章，提示 `已从缓存中恢复未保存的内容`，文章内容变为空白。

复现步骤：
1. 新建文章，切换为 StackEdit 编辑器
2. 输入一些内容保存/发布文章
3. 回到文章列表，重新点进刚才的文章
4. 重复步骤3，文章内容会概率性变空白

**Comment by ruibaby** [comment]
可能和插件的内容更新时机有关：https://github.com/halo-sigs/plugin-stackedit

/good-first-issue

**Comment by ruibaby** [comment]
已经在 https://github.com/halo-dev/halo/pull/3468 中修复。

/close
