### ISSUE TITLE
默认编辑器支持拖拽/粘贴图片之后上传到附件库

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#3109]
### 你当前使用的版本

2.1.0

### 描述一下此特性

期望默认编辑器支持通过拖拽或者粘贴图片上传到附件库。目前编辑器的默认方案是将图片转为 base64，这样虽然可以实现粘贴图片的需求，但可能会导致内容体积变大，从而导致性能问题。

/area editor
/kind feature

**Comment by Alanrah** [comment]
原来如此，怪不得我刚才publish 413😂
