### ISSUE TITLE
postFinder 中的 listByCategory 支持仅查询当前级别的文章

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#3110]
### 你当前使用的版本

2.1.0

### 描述一下此特性

假设当前有这样的结构：

- 分类 1
  - 分类 2
  - 分类 3
    - 分类 4

那么根据 `listByCategory` 方法查询 `分类 1` 的文章时，会查询出其下所有的文章，并不是仅查询设置了 `分类 1` 的文章。所以期望可以添加参数或者提供一个新的方法用于仅查询当前分类下的文章。

/area core
/kind feature

**Comment by guqing** [comment]
目前 PostFinder 提供的 listByCategory 方法就是只查询的当前分类的文章并不包含子分类
<img width="1419" alt="image" src="https://user-images.githubusercontent.com/38999863/215664169-a3d11d7e-a1a2-47c7-8c59-26f34bb4c57d.png">
此 PR 是否需要的是查询分类包含其子分类的所有文章，或者是使用方式不对
/kind needs-more-info

**Comment by hugeleaf** [comment]
> 目前 PostFinder 提供的 listByCategory 方法就是只查询的当前分类的文章并不包含子分类 <img alt="image" width="1419" src="https://user-images.githubusercontent.com/38999863/215664169-a3d11d7e-a1a2-47c7-8c59-26f34bb4c57d.png"> 此 PR 是否需要的是查询分类包含其子分类的所有文章，或者是使用方式不对 /kind needs-more-info

@guqing 目前模板变量和finderAPI都没有拿到包括子类posts的能力吧。如果通过遍历子分类再查找posts，对于使用者来说逻辑太重了，还要做混合数据的分页，后面会实现问题描述中“通过参数控制是否返回子类文章”能力吗？

**Comment by ruibaby** [comment]
已经在 [2.17](https://github.com/halo-dev/halo/releases/tag/v2.17.0) 中支持。

/close
