### ISSUE TITLE
对于匿名评论的一些建议

### ISSUE THREAD

**Issue by Jimecc** [halo-dev/halo#3116]
### 你当前使用的版本

2.0.2

### 描述一下此特性

在1.x版本中，评论均为匿名，且评论的时候可以填写邮箱，来达到博主进行回复的时候邮件通知的效果，但是2.x的版本中取消了这一功能，一律更改为匿名用户，考虑到可能大部分人并不会有回头阅读一篇博客并查看自己的提问的情况，因此请问是否可以将1.x的这个功能重新加回来呢？感觉这个功能还挺不错的。

**Comment by JohnNiang** [comment]
评论时本来是可以填写名称和邮箱，后面增加了匿名评论后，该功能可能被隐藏了。此前已经有相关的讨论了：<https://github.com/halo-sigs/plugin-comment-widget/issues/2#issuecomment-1345853278>。

**Comment by Jimecc** [comment]
好的，谢谢

**Comment by ruibaby** [comment]
在 https://github.com/halo-sigs/plugin-comment-widget/pull/9 中已经优化这个问题，欢迎测试。

**Comment by ruibaby** [comment]
目前已支持，同步更新 Halo 2.2.0 和评论插件即可。

- https://github.com/halo-sigs/plugin-comment-widget/releases/tag/v1.1.0 
- https://github.com/halo-dev/aloh/releases/tag/v2.2.0

/close
