### ISSUE TITLE
目前评论插件无法得知 <仅允许注册用户评论> 这个设置选项

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#3117]
### 你当前使用的版本

2.1.0

### 描述一下此特性

目前评论者信息的方式为：

1. 注册
2. 手动填写个人信息

但目前评论组件无法得知 `仅允许注册用户评论` 这个系统设置选项，所以无法在前端区分是否可以不注册就评论。

相关  issue：

- https://github.com/halo-dev/halo/issues/3116
- https://github.com/halo-sigs/plugin-comment-widget/issues/2
- https://github.com/halo-sigs/plugin-comment-widget/issues/6

/area core
/kind improvement

**Comment by JohnNiang** [comment]
我的建议是：专门提供一个接口获取评论相关的设置，并配置好权限。这样评论组件就能够知晓系统设置，并适配对应的逻辑。

**Comment by guqing** [comment]
> 我的建议是：专门提供一个接口获取评论相关的设置，并配置好权限。这样评论组件就能够知晓系统设置，并适配对应的逻辑。

是否应该还需要暴露一些 Interface 方法给插件使用，比如获取系统的标题等设置，可能插件会用到

**Comment by JohnNiang** [comment]
> 是否应该还需要暴露一些 Interface 方法给插件使用，比如获取系统的标题等设置，可能插件会用到

目前 SystemFetcher 似乎可以完成这件事情。

**Comment by guqing** [comment]
> > 是否应该还需要暴露一些 Interface 方法给插件使用，比如获取系统的标题等设置，可能插件会用到
> 
> 目前 SystemFetcher 似乎可以完成这件事情。

也就是插件允许查询 system configMap 吗

**Comment by ruibaby** [comment]
已经在 https://github.com/halo-sigs/comment-widget/pull/4 中实现，使用的是 actuator 对外暴露的端口。

/close
