### ISSUE TITLE
细化角色模板

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#3123]
### 你当前使用的版本

2.1.0

### 描述一下此特性

目前系统提供的角色模板基本上只分为 **管理** 和 **查看**，对于一些特定的操作可能无法满足需求，比如：

1. 发布文章，有些场景为用户可以创建，但是发布操作需要更高级的权限。
2. 评论审核，目前没有单独的接口可以进行操作。
3. 附件，可能有允许上传，但不允许管理的情况。

/cc @halo-dev/sig-halo 可以讨论一下具体改善方式。

相关 issue：

- https://github.com/halo-dev/halo/issues/2947

可能在 2.2.0 无法完成个人中心的功能，但可以优化一下权限相关的逻辑。

/kind improvement
/area core
/area console

**Comment by JohnNiang** [comment]
Hi @guqing ，是否有兴趣解决当前问题。我现在正着手解决 https://github.com/halo-dev/halo/issues/2860 ，暂时没有时间解决这个问题了。

**Comment by ruibaby** [comment]
@JohnNiang @guqing 优先考虑文章，其他的等后续是否有这样的需求。

文章目前需要将创建和发布隔离开，就是说一般角色允许创建，但是不能发布。如果包含文章管理的角色模板，才能发布文章。

**Comment by guqing** [comment]
> Hi @guqing ，是否有兴趣解决当前问题。我现在正着手解决 https://github.com/halo-dev/halo/issues/2860 ，暂时没有时间解决这个问题了。

可以的 /assign

**Comment by guqing** [comment]
当给文章分配 create 权限时用户只能创建而不能更新，如果给了 update 权限则能修改发布状态和编辑以前的文章，并没有真正达到控制，因此这个细化角色模板感觉意义不大
@halo-dev/sig-halo

**Comment by JohnNiang** [comment]
@guqing ，建议把文章发布权限区分开来。

**Comment by guqing** [comment]
> @guqing ，建议把文章发布权限区分开来。

那用户可以编辑别人创建的文章需要管吗

**Comment by guqing** [comment]
发布权限提出来那可能需要版本对比才行，否则管理员去发布时不知道用户改了什么

**Comment by JohnNiang** [comment]
从目前来看，区分发布权限和以上提到的功能（版本对比，编辑别人创建的文章）似乎没有依赖关系。

区分发布权限后，在当前的体系下，管理员能够精准控制谁能够发布文章。

**Comment by guqing** [comment]
> 从目前来看，区分发布权限和以上提到的功能（版本对比，编辑别人创建的文章）似乎没有依赖关系。
> 
> 区分发布权限后，在当前的体系下，管理员能够精准控制谁能够发布文章。

那文章模块区分出来应该有四种权限：文章查看，文章编辑（create/update）、文章删除、文章发布，删除和发布会影响到前台文章的展示感觉要独立出来

**Comment by guqing** [comment]
/triage needs-information
/priority awaiting-more-evidence
/milestone clear
需要更多的场景来决定到底是不是要将权限拆分的更细如 查看、修改、删除以及其他操作（上传/发布）等

**Comment by ruibaby** [comment]
此问题已经在 2.11 上得到优化，针对文章管理提供了关于个人使用的角色模板。

/close
