### ISSUE TITLE
取消功能页面的概念

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#3124]
### 你当前使用的版本

2.1.0

### 描述一下此特性

为了保证和 1.x 的设计一致，2.0 保留了功能页面的概念，并由插件提供（比如 1.x 的友情链接管理、图库管理）。

如图：

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/21301288/211451884-e6f0a49b-7c65-496c-80f2-4857eb270bf9.png">

这样会带来几个问题：

1. 无法控制 UI 权限，因为各个功能页面由插件控制权限，所以即便没有插件的权限，左侧菜单还是会显示页面的菜单。
2. 不方便管理自定义页面。
3. 操作繁琐，进入相关管理页面步骤过多。

改进方式：

1. 功能页面几乎和内容管理无异，都是管理数据并提供前台渲染的路由。所以可以由插件接入菜单的扩展点，并放置在左侧菜单的内容分组。
2. 左侧菜单的页面直接对自定义页面进行管理，且 UI 权限绑定为自定义页面的权限。

注意：这是一个 braking change，虽然不会带来数据上的问题。但如果要进行这个修改，那么旧版本插件可能没有功能页面的对应入口。

/area console
/kind improvement

**Comment by JohnNiang** [comment]
支持改进。

我们在正式发布 2.x.0 的时候，提示”升级友情链接插件“即可。

**Comment by wan92hen** [comment]
> 1. 功能页面几乎和内容管理无异，都是管理数据并提供前台渲染的路由。所以可以由插件接入菜单的扩展点，并放置在左侧菜单的内容分组。

关于这个，我觉得可以一步到位，按照之前讨论过的提供通用的自定义模型的管理入口。
对于基础管理需求，插件中只需要定义自定义模型，不再需要自己提供对应的管理页面。可以采用类似设置的处理自动生成编辑表单；
对于涉及到复杂交互的管理需求，也保留插件自己提供管理页面的能力。

**Comment by ruibaby** [comment]
> 关于这个，我觉得可以一步到位，按照之前讨论过的提供通用的自定义模型的管理入口。
对于基础管理需求，插件中只需要定义自定义模型，不再需要自己提供对应的管理页面。可以采用类似设置的处理自动生成编辑表单；
对于涉及到复杂交互的管理需求，也保留插件自己提供管理页面的能力。

这个 issue 的改动应该和这个特性不冲突，已经创建了新的 issue：https://github.com/halo-dev/halo/issues/3125
