### ISSUE TITLE
新建文章时选择默认编辑器添加任务列表，给任务项打钩报错

### ISSUE THREAD

**Issue by yonglinzhu** [halo-dev/halo#3128]
### 是什么版本出现了此问题？

2.1.0

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker

### 发生了什么？

操作：新建文章选择默认编辑器，新增任务列表时给任务**打勾**报错。

### 相关日志输出

```shell
Uncaught RangeError: Index 1 out of range for <taskList(taskItem(paragraph("23")), taskItem(paragraph("32")))>
    at k.child (DefaultEditor.840b38f3.js:1:5538)
    at k.findIndex (DefaultEditor.840b38f3.js:1:6053)
    at gn.nodeAt (DefaultEditor.840b38f3.js:1:17302)
    at DefaultEditor.840b38f3.js:92:17008
    at DefaultEditor.840b38f3.js:12:1520
    at Object.command (DefaultEditor.840b38f3.js:9:7442)
    at HTMLInputElement.<anonymous> (DefaultEditor.840b38f3.js:92:16969)
```

### 附加信息

![image](https://user-images.githubusercontent.com/26948420/211482491-e5bf2b19-ed3a-4cc2-a87e-be538247c691.png)

**Comment by ruibaby** [comment]
有稳定复现的方式吗？我这里似乎没有办法复现。

<img width="1130" alt="image" src="https://user-images.githubusercontent.com/21301288/211484762-96f405a6-9a1a-4e92-9655-e6acc4d227f7.png">

/triage needs-information

**Comment by yonglinzhu** [comment]
换为 Safari 浏览器或Google Chrome 开无痕浏览器时测试无复现。

报错前操作过多次切换编辑器并进行编辑操作，可能是某些操作下的兼容问题，暂时无法稳定复现。

**Comment by ruibaby** [comment]
@yonglinzhu 好的，我会持续关注这个问题，也欢迎后续反馈。

**Comment by ruibaby** [comment]
没有再收到相关反馈，我们也没能复现，我将关闭此 issue，后续有补充可以随时提交新 issue。

/close
