### ISSUE TITLE
我想新增一个DownloadRestTemplate

### ISSUE THREAD

**Issue by NGLSL** [halo-dev/halo#313]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [ ] [Halo 论坛](https://bbs.halo.run)
- [ ] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [ ] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [x] 添加新的特性或者功能
- [ ] 请求技术支持

我想新增一个DownloadRestTemplate，其中的超时时间可以自定义配置，可HaloConfiguration中无法把HaloProperties注入进来。只能在HaloConfiguration中写死120s的超时时间。使用起来，感觉不够灵活。

**Comment by JohnNiang** [comment]
理论上是可行的，你再仔细检查和调试一下。

**Comment by NGLSL** [comment]
> 理论上是可行的，你再仔细检查和调试一下。

是的，可以我刚刚检查了一下代码，发现需要指定RestTemplate的名字

**Comment by NGLSL** [comment]
> 理论上是可行的，你再仔细检查和调试一下。

我是否可以提交，我修改之后的代码？

**Comment by JohnNiang** [comment]
你可以向 dev 分支提交请求，我们 review 之后会合并代码的。

**Comment by NGLSL** [comment]
> 你可以向 dev 分支提交请求，我们 review 之后会合并代码的。

那我先暂时不提，关于摸板下载都是通过github提供的api进行更新，是否可以更具国内外ip来区分一下？如果是国内的服务器ip，更新摸板则是通过gitee之类进行更新，如果是国外则通过github？我发现，即使我新增了自定义配置请求超时的时间，也不能解决这个问题。

**Comment by JohnNiang** [comment]
模板下载实际上可以是其他平台的链接，你也可以自己上传模板文件。

后台拉取模板文件是采用的 jGit，并没有使用 RestTemplate，所以你配置的内容是不起作用的。

**Comment by NGLSL** [comment]
> 模板下载实际上可以是其他平台的链接，你也可以自己上传模板文件。
> 
> 后台拉取模板文件是采用的 jGit，并没有使用 RestTemplate，所以你配置的内容是不起作用的。

那，代码中的resttemplate是?后台模板。

**Comment by JohnNiang** [comment]
> > 模板下载实际上可以是其他平台的链接，你也可以自己上传模板文件。
> > 后台拉取模板文件是采用的 jGit，并没有使用 RestTemplate，所以你配置的内容是不起作用的。
> 
> 那，代码中的resttemplate是?后台模板。

一般是用于请求外部资源（除 Git 外）的时候会用到。

**Comment by NGLSL** [comment]
> > > 模板下载实际上可以是其他平台的链接，你也可以自己上传模板文件。
> > > 后台拉取模板文件是采用的 jGit，并没有使用 RestTemplate，所以你配置的内容是不起作用的。
> > 
> > 
> > 那，代码中的resttemplate是?后台模板。
> 
> 一般是用于请求外部资源（除 Git 外）的时候会用到。

国内的服务器想要下载Github的资源，还是比较慢的，感觉这个功能用处就不大了。

**Comment by JohnNiang** [comment]
建议首次的时候使用浏览器下载好压缩包，然后上传就好了，未来更新会很快的。

**Comment by NGLSL** [comment]
> 建议首次的时候使用浏览器下载好压缩包，然后上传就好了，未来更新会很快的。

目前看起来，只能是通过手动下载包，再上传。现在可以关闭这个issue了，我在研究研究代码，看看哪儿还可以改进。

**Comment by JohnNiang** [comment]
主要是现在没有太多国内资源支撑主题的托管。
