### ISSUE TITLE
使用local存储时，后台无法正常预览图片

### ISSUE THREAD

**Issue by JeffeyShaw** [halo-dev/halo#3131]
### What is version of Halo has the issue?

2.1.0 

### What database are you using?

MySQL 8.x

### What is your deployment method?

Docker

### Your site address.

https://cmboo.com

### What happened?

在我使用local存储时，上传的图片会显示无法预览，且它的显示的原始链接是：http://localhost:8090/upload/welcome.png；
![image](https://user-images.githubusercontent.com/69669504/211503198-caca4396-978b-4de8-b79c-caa698f31c6f.png)

同时前台的图片地址，我似乎只能手动修改后才能正常预览。
![image](https://user-images.githubusercontent.com/69669504/211503710-ded35b95-5700-4ef9-ac1d-891dfd6d15bc.png)

是否有设置可以根据我的站点域名，在后台附件处正常预览呢

**Comment by JohnNiang** [comment]
/triage duplicate

可参考 https://github.com/halo-dev/halo/issues/2818 解决此问题。

**Comment by JeffeyShaw** [comment]
> /分类重复
> 
> 可参考#2818解决此问题。
感谢，已成功解决
