### ISSUE TITLE
同时修改一篇文章的标题和分类时报500（非必现）

### ISSUE THREAD

**Issue by chengfeiyue** [halo-dev/halo#3132]
### What is version of Halo has the issue?

2.1.0-RC1

### What database are you using?

PostgreSQL

### What is your deployment method?

Docker

### What happened?

操作步骤：同时修改文章名称，分类，
现象(非必现):
<img width="654" alt="image" src="https://user-images.githubusercontent.com/49852751/211533018-311c74ac-2f63-49c7-9bba-c0d8154b920f.png">
日志截图：
<img width="1344" alt="image" src="https://user-images.githubusercontent.com/49852751/211533204-6250eeaa-6ef4-45b6-ab6b-43a1e27bebc2.png">

**Comment by ruibaby** [comment]
已经在 https://github.com/halo-dev/halo/pull/3210 中修复。
