### ISSUE TITLE
404页面右上角登录功能不可用

### ISSUE THREAD

**Issue by zzudongxiang** [halo-dev/halo#3133]
### 是什么版本出现了此问题？

2.1.0

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

404页面的右上角登陆按键无法点击
![image](https://user-images.githubusercontent.com/33760061/211637896-de6f9c16-b1bd-49ca-859b-01c0482ea738.png)

500页面上的右上角登陆功能是正常的
![image](https://user-images.githubusercontent.com/33760061/211637946-74887fc9-d614-49f0-88cf-7d93b2d0cd09.png)

**Comment by ruibaby** [comment]
可能和这个问题有关：https://github.com/halo-dev/halo/issues/3062

需要进一步排查。

/kind bug
/area core

**Comment by JohnNiang** [comment]
/assign

当前的问题和 #3062 属于两个不同的问题。

已经有对应的解决方案，稍后提交 PR 修复它。
