### ISSUE TITLE
期望在 Console 添加外部访问链接配置不正确的提示

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#3136]
### 你当前使用的版本

2.1.0

### 描述一下此特性

根据部署文档 <https://docs.halo.run/getting-started/install/docker-compose>，目前 Halo 系统内的 permalink 域名需要配置 `--halo.external-url`，但使用者可能会遗忘此配置，所以期望在 Console 侧添加一个提示，当访问的地址与 `--halo.external-url` 所配置的地址不一致的时候。

需要解决的问题：

1. Console 前端目前无法得到 `--halo.external-url` 配置。

> 此 issue 仅仅是一个想法，并不一定要实现。如果有其他建议，欢迎回复。

/area core
/area console
/kind improvement

**Comment by wan92hen** [comment]
看起来跟这个 issue #3055 有点关系，可以在站点信息的接口中包含 external url 的配置信息。

**Comment by ruibaby** [comment]
已经在 https://github.com/halo-dev/console/pull/832 中支持。

/close
