### ISSUE TITLE
需要优化 Console 端评论的默认排序规则

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#3138]
### 是什么版本出现了此问题？

2.1.0

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式部署？

Docker Compose

### 在线站点地址

https://halo.run

### 发生了什么？

目前在 Console 端的评论管理的默认排序为最后回复时间，意思就是如果某一条评论新增了回复，那么会放在最前面以提示管理者有新的回复，这是符合预期的。但是目前无法将最新创建的评论放在最前面，导致无法及时知道有新的评论。

默认情况下：

<img width="1647" alt="image" src="https://user-images.githubusercontent.com/21301288/211982715-82e89534-63cd-4cd3-99a1-70266df58405.png">

手动排序：

<img width="1678" alt="image" src="https://user-images.githubusercontent.com/21301288/211982654-85c1a16b-257c-4193-b47c-ce0db48ecda5.png">

/kind improvement
/area core
/milestone 2.2.x

**Comment by vayci** [comment]
修改默认排序规则，调整为以最后回复时间及评论创建时间两个字段作为排序依据，进行倒序排序。

实现方法：评论存在回复，存在最后回复时间，则取最后回复时间；不存在最后回复时间，则取创建时间。以这个规则获取的时间作为默认排序规则，是否满足预期？

另外由于修改了默认排序方式，console评论排序规则可以在此基础上添加以“最后回复时间”排序条件
