### ISSUE TITLE
Console 端文章管理的标签排序不固定

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#3139]
### 是什么版本出现了此问题？

2.1.0

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式部署？

Docker Compose

### 在线站点地址

https://halo.run

### 发生了什么？

如图：

<img width="872" alt="image" src="https://user-images.githubusercontent.com/21301288/211983771-493182b4-a531-4dd5-a1ca-e0bff3e26d9e.png">
<img width="760" alt="image" src="https://user-images.githubusercontent.com/21301288/211983798-aa4a5af4-bfeb-48bc-97ef-efa9b9f956dd.png">

注意：并不是每一次都会变。

可能是由于 https://github.com/halo-dev/halo/pull/2854 的改动导致的。

/kind bug
/area core

**Comment by guqing** [comment]
![Kapture 2023-01-12 at 14 26 12](https://user-images.githubusercontent.com/38999863/211994587-12806696-a683-468c-a031-3c3d5eda25e8.gif)
目前并不是稳定复现，不过确实存在这个问题 ，但还没有排查出原因

**Comment by JohnNiang** [comment]
主要是因为使用了 flatmap 造成最终的排序不稳定。建议使用 concatMap 或者 flatmapSequential。

https://github.com/halo-dev/halo/blob/ca4e93d4bbfa849a91c7e4acca231bb1c8ffd10d/src/main/java/run/halo/app/content/impl/PostServiceImpl.java#L211

https://github.com/halo-dev/halo/blob/ca4e93d4bbfa849a91c7e4acca231bb1c8ffd10d/src/main/java/run/halo/app/content/impl/PostServiceImpl.java#L219
