### ISSUE TITLE
访客侧文章优先以发布时间排序

### ISSUE THREAD

**Issue by longjuan** [halo-dev/halo#3143]
### 你当前使用的版本

2.1.0

### 描述一下此特性

目前Halo首页、分类页、标签页等的文章排序是按文章创建时间排序的。
用户无法修改文章创建时间，只能修改发布时间，导致用户无法对首页、分类页、标签页的文章顺序进行调整。
是否应该优先以发布时间排序再以文章创建时间排序？

目前是没有根据发布时间排序：
![image](https://user-images.githubusercontent.com/28662535/212066483-a07e172a-9f66-4278-8e85-4b079109c77d.png)

### 附加信息

![image](https://user-images.githubusercontent.com/28662535/212067156-0dea209c-e04c-4e5c-ab9f-4146a36c09a3.png)
![image](https://user-images.githubusercontent.com/28662535/212066742-4580887a-8857-48b4-87a8-1b6a04a2502b.png)
![image](https://user-images.githubusercontent.com/28662535/212066881-4416cfd9-c703-41e2-a104-04c52c4d2723.png)
![image](https://user-images.githubusercontent.com/28662535/212066808-d5bb3b40-b689-4c45-8bbe-573637b7eb7d.png)

相关issues：https://github.com/halo-dev/halo/issues/3113 https://github.com/halo-dev/halo/issues/2961

**Comment by longjuan** [comment]
Hi, @JohnNiang 
https://github.com/halo-dev/halo/issues/3113 中有提到 *允许站长设置文章排序方式*
我认为直接在`.thenComparing(creationTimestamp)`前面加上发布时间的比较就行了吧，不用提供设置了

**Comment by JohnNiang** [comment]
> 我认为直接在.thenComparing(creationTimestamp)前面加上发布时间的比较就行了吧，不用提供设置了

IMO，这样似乎可行。

/ping @halo-dev/sig-halo

**Comment by guqing** [comment]
> Hi, @JohnNiang #3113 中有提到 _允许站长设置文章排序方式_ 我认为直接在`.thenComparing(creationTimestamp)`前面加上发布时间的比较就行了吧，不用提供设置了
> 
> > 如果真的需要提供设置，我认为只需提供倒序和正序，不用提供以创建时间排序了

原先的逻辑是先排置顶文章，如果是置顶根据置顶顺序排列，然后在按照创建时间排序，如果两篇文章的创建时间相同按照名称排序避免顺序改变。

实际首页可以按照发布时间排序，所以应该将创建时间排序替换为发布时间是符合预期的行为。如果在创建时间之前加上发布时间表示发布时间相同按照创建时间排序意义不大。

后续确实还要提供一些其他的排序可供配置，比如较近创建、较晚创建、较近发布、较晚发布，文章热度（目前不好实现）等方式。

**Comment by longjuan** [comment]
> 实际首页可以按照发布时间排序，所以应该将创建时间排序替换为发布时间是符合预期的行为。如果在创建时间之前加上发布时间表示发布时间相同按照创建时间排序意义不大。

好的，我将创建时间排序替换为发布时间，并修改对应测试类，重新提PR

**Comment by longjuan** [comment]
> 默认排序如果是”发布时间“，可能会内容的顺序不固定，每次发布后，文章列表的顺序可能会有不小变化。
> 
> 之所以之前将”创建时间“作为默认排序，因为“创建时间”是固定的，最终的排序结果是稳定的。

我这边测试无论是 *修改内容点击发布* 还是 *取消发布再重新发布* ，都不会引起”发布时间“的变化，变化的是lastmodify？

**Comment by longjuan** [comment]
我的理解，不知道和你们设计符不符合：
CreationTimestamp：真正创建的时间，不可修改
PublishTime：用户自定义的发布时间，用户可以修改
lastModifyTime：修改后更新时间，系统修改

worldpress：
![image](https://user-images.githubusercontent.com/28662535/212112728-1cb184d3-51ba-40ff-9355-69727b6ae607.png)

**Comment by guqing** [comment]
> 默认排序如果是”发布时间“，可能会内容的顺序不固定，每次发布后，文章列表的顺序可能会有不小变化。
> 
> 之所以之前将”创建时间“作为默认排序，因为“创建时间”是固定的，最终的排序结果是稳定的。

发布时间存在的时候再次发布是不会修改发布时间的，除非手动修改

**Comment by guqing** [comment]
> 我的理解，不知道和你们设计符不符合： CreationTimestamp：真正创建的时间，不可修改 PublishTime：用户自定义的发布时间，用户可以修改 lastModifyTime：修改后更新时间，系统修改
> 
> worldpress： ![image](https://user-images.githubusercontent.com/28662535/212112728-1cb184d3-51ba-40ff-9355-69727b6ae607.png)

差不多正确，不过 lastModifyTime 是指的文章内容的，如果只修改了文章的设置则不会变

**Comment by longjuan** [comment]
我看WorldPress是按发布时间排序的，且顺序不能修改，真的要修改要用插件实现。
所以我认为把创建时间排序替换为发布时间排序更符合直觉，用户可以通过调整发布时间改变顺序，且https://github.com/halo-dev/halo/issues/3113 https://github.com/halo-dev/halo/issues/2961 也想要这个特性。

> 至于是否提供设置可以后续跟进
