### ISSUE TITLE
电脑更换了IP，halo内部某些地址还是旧的

### ISSUE THREAD

**Issue by youngledo** [halo-dev/halo#3147]
### 是什么版本出现了此问题？

1.6

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Fat Jar

### 发生了什么？

电脑更换了IP，但发现某些地址使用的还是旧的IP（比如备份的下载地址）。

**Comment by ruibaby** [comment]
博客设置 -> 博客地址，改为实际地址。
