### ISSUE TITLE
生产环境可以访问到 Swagger

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#3153]
### 是什么版本出现了此问题？

2.1.0

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式部署？

Docker Compose

### 在线站点地址

https://techman.run

### 发生了什么？

比如：https://techman.run/webjars/swagger-ui/index.html

虽然看起来应该只是 Swagger 的一个示例页面，但也不希望可以直接访问到。

/area core
/kind improvement

**Comment by vayci** [comment]
[WebFluxAutoConfiguration](https://github.com/spring-projects/spring-boot/blob/v3.0.1/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/reactive/WebFluxAutoConfiguration.java#L194-L198) 中默认添加了webjars的resource mapping，导致org.webjars:swagger-ui中的相关页面资源能够访问。

修复方案：可以在halo中 [WebFluxConfig#addResourceHandlers](https://github.com/halo-dev/halo/blob/main/src/main/java/run/halo/app/config/WebFluxConfig.java#L125)，根据相关配置对`/webjars/swagger-ui/**`资源路径进行屏蔽。

**Comment by JohnNiang** [comment]
IMO，这个问题可能需要等 SpringDoc 来处理。

**Comment by JohnNiang** [comment]
https://techman.run/webjars/swagger-ui/index.html 所访问到的只是 webjars 下的静态资源而已，并未请求真实的 API 文档。

如果直接访问 <https://techman.run/swagger-ui.html> 会出现符合预期的 404 错误。

/close
