### ISSUE TITLE
优化文章 snapshots 的逻辑和功能

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#3155]
### 你当前使用的版本

2.1.0

### 描述一下此特性

目前文章和自定义页面使用了 Snapshot 模型来保存文章内容，而且支持版本管理，但目前出现了因为 Snapshot 导致文章详情页面加载慢的问题，如：

- https://github.com/halo-dev/halo/issues/3026
- https://github.com/halo-dev/halo/issues/3140

目前基本上可以认为原因之一是由 Snapshot 内容和版本过多导致的，因为文章页面会查询所有 Snapshot 去比较，可复现方式：

1. 创建若干文章，保存大文本内容，并进行多次编辑和保存。
2. 检查任何一篇文章的渲染时长。

所以期望提供以下功能或优化：

1. 支持设置 Snapshot 保留数量，自动删除过旧的 Snapshot。
2. 支持一键清理所有 Snapshot，仅保留最新版本。
3. 甚至支持关闭 Snapshot 功能，因为目前 Snapshot 这个逻辑使用最多的场景只是可以做到仅保存内容而不发布。

/kind improvement
/area core
/priority important-soon

**Comment by leyedu** [comment]
这个太不合理了，正常cms逻辑基本上复制图片自动上传默认存储路径下才对

**Comment by JohnNiang** [comment]
> 这个太不合理了，正常cms逻辑基本上复制图片自动上传默认存储路径下才对

感谢反馈！不过我们正在着手处理这个事情。

1. 复制图片自动上传的功能已经提交了 PR，请参考：<https://github.com/halo-dev/console/pull/825>。该修复预计在 2.2.0 发布。
2. Snapshot 逻辑优化需要等到 2.3.0 或者 2.4.0 发布。

**Comment by JohnNiang** [comment]
IMO，这个问题已经被 <https://github.com/halo-dev/halo/pull/3168> 修复，我将关闭当前 issue。如果有任何问题，可随时重新打开 issue。

/close
