### ISSUE TITLE
archives没有按年份倒序排序

### ISSUE THREAD

**Issue by longjuan** [halo-dev/halo#3157]
### 是什么版本出现了此问题？

2.1.0

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Fat Jar

### 发生了什么？

归档的年份没有按年份倒序排序
![image](https://user-images.githubusercontent.com/28662535/212583365-8bf8b59a-d6ea-49aa-983c-2b444db07bc7.png)
![image](https://user-images.githubusercontent.com/28662535/212583351-72e513f7-04e5-4943-be4e-10103d603e9a.png)

原因是map.entrySet()没办法保证顺序
![image](https://user-images.githubusercontent.com/28662535/212583058-308e3ea4-e472-43f8-a1b3-5c810c2ac32d.png)

**Comment by ruibaby** [comment]
/kind improvement
/area core

@longjuan 要来提个 PR 吗？

**Comment by longjuan** [comment]
> @longjuan 要来提个 PR 吗？

我来吧
/assign
