### ISSUE TITLE
错误提示信息样式优化

### ISSUE THREAD

**Issue by wan92hen** [halo-dev/halo#3163]
### 是什么版本出现了此问题？

2.1.0

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式部署？

Docker

### 发生了什么？

![image](https://user-images.githubusercontent.com/27671436/212792520-1bb518d2-5bcf-4420-a7c8-b2df5ae40d12.png)
如图所示，错误提示信息较长时整体宽度不够，右侧存在部分遮挡。

**Comment by ruibaby** [comment]
<img width="1118" alt="image" src="https://user-images.githubusercontent.com/21301288/212853482-de7a2336-eca1-4edb-bbf0-a5c65822870d.png">

我这里似乎无法重现这个问题，甚至：

<img width="911" alt="image" src="https://user-images.githubusercontent.com/21301288/212853653-855976c2-8078-4228-9fea-e3b0be1ac477.png">

**Comment by wan92hen** [comment]
我用 Windows 和 Mac 试了下都出现了这样的问题。

提交了个 PR https://github.com/halo-dev/console/pull/829 进行处理。

**Comment by JohnNiang** [comment]
我在 Windows 下的 Firefox，Chrome 和 Edge 进行了测试，也未复现。
