### ISSUE TITLE
重复安装已存在的插件时提示升级

### ISSUE THREAD

**Issue by wan92hen** [halo-dev/halo#3164]
### 描述一下此特性

点击安装插件按钮，选择一个已经安装过的插件，会弹出插件已存在的错误。

建议检测到插件已安装时给出类似 ”已安装该插件是否进行升级“ 的提示，用户选择是时执行升级插件流程。

这样当安装的插件较多时，用户不需要找到具体的插件进行升级操作，可以直接通过安装入口处理，简化用户操作。

![image](https://user-images.githubusercontent.com/27671436/212792817-660545d3-a8e6-4b55-b045-812408d95b7e.png)

**Comment by ruibaby** [comment]
/kind improvement
/area console

妙

**Comment by JohnNiang** [comment]
/duplicate

See https://github.com/halo-dev/halo/issues/3159 instead.

**Comment by ruibaby** [comment]
> /duplicate
> 
> 
> 
> See https://github.com/halo-dev/halo/issues/3159 instead.

这是另外的需求。

**Comment by JohnNiang** [comment]
I have already done this improvment. So I'm going to unassin @LIlGG and assign myself.

/unassign @LIlGG 
/assign

**Comment by wan92hen** [comment]
> I have already done this improvment. So I'm going to unassin @LIlGG and assign myself.
> 
> /unassign @LIlGG /assign

这个 PR https://github.com/halo-dev/halo/pull/3350 只修改了错误提示，建议再配合上 console 的修改，可以在出现这种错误时直接提示转入升级流程。

**Comment by JohnNiang** [comment]
> > I have already done this improvment. So I'm going to unassin @LIlGG and assign myself.
> > /unassign @LIlGG /assign
> 
> 这个 PR #3350 只修改了错误提示，建议再配合上 console 的修改，可以在出现这种错误时直接提示转入升级流程。

/assign @ruibaby

**Comment by ruibaby** [comment]
> /assign @ruibaby 

![image](https://user-images.githubusercontent.com/21301288/220087482-232ffbd8-dac4-4019-a5bd-487aeb327cb3.jpeg)

**Comment by JohnNiang** [comment]
/reopen

Waiting for https://github.com/halo-dev/console/pull/871 merged.
