### ISSUE TITLE
分类listAll接口列表顺序与Console设置的相反

### ISSUE THREAD

**Issue by AirboZH** [halo-dev/halo#3169]
### 是什么版本出现了此问题？

2.1.0

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Fat Jar

### 发生了什么？

console的排序
![image](https://user-images.githubusercontent.com/50261327/212866126-8ed1c703-5c21-4e16-8c50-709e9972fe34.png)

Thymeleaf each 遍历测试

```html
<th:block th:each=" category,iterStat : ${categoryFinder.listAll()}">
        <p style="display:none" th:text="${category.spec.displayName}"></p>
</th:block>
```

Thymeleaf each 遍历结果：
![image](https://user-images.githubusercontent.com/50261327/212867800-6daf21c8-c006-46a8-a927-563aeb45afa0.png)

效果
![image](https://user-images.githubusercontent.com/50261327/212866609-6f6f054b-0ee3-4c8c-9be6-3f80ccc668ca.png)
![image](https://user-images.githubusercontent.com/50261327/212866663-602d38ec-052d-4778-b4e4-43da0499b3ab.png)

**在用到listAll接口的主题中分类顺序与后台排序相反**

https://github.com/halo-dev/halo/blob/cb850a85c9abfad32ad98d5d9d30f162794918a8/src/main/java/run/halo/app/theme/finders/impl/CategoryFinderImpl.java#L149-L153

注意到在152行有一个reversed，在帖子评论等有时效性的地方我们需要最新的内容出现在上方，可是在可以设置顺序的分类中我想这是不必要的。

**Comment by longjuan** [comment]
造成此问题的原因不是`defaultComparator`一个地方造成的影响
而是后端`listAll`使用的`defaultComparator`、后端`listAsTree`使用的`defaultTreeNodeComparator`、console端使用的`defaultTreeNodeComparator`三个比较器的行为不同造成的。

https://github.com/halo-dev/halo/blob/a7da2c0d76cf552a513782faa57cd0f38c823803/src/main/java/run/halo/app/theme/finders/impl/CategoryFinderImpl.java#L142-L153

https://github.com/halo-dev/halo/blob/a7da2c0d76cf552a513782faa57cd0f38c823803/src/main/java/run/halo/app/theme/finders/impl/CategoryFinderImpl.java#L130-L140

https://github.com/halo-dev/console/blob/397e05001060d71114e03fe5c8f6e77292c6c000/src/modules/contents/posts/categories/utils/index.ts#L42-L67

earth用的是`listAsTree`、一般三方主题用的是`listAll`、console用的console的比较器，三个比较器行为全部不同，所以出现排序问题。

![image](https://user-images.githubusercontent.com/28662535/213384362-7af3255d-60e1-457b-a98b-fdbaa765bbc3.png)
![image](https://user-images.githubusercontent.com/28662535/213384395-8d88b316-c3eb-4407-b782-396aa6ba55fe.png)
![image](https://user-images.githubusercontent.com/28662535/213384467-78f8a6b0-3d24-4230-8c8f-7bc33834dcfd.png)
