### ISSUE TITLE
后台删除评论后会导致下方头像错误

### ISSUE THREAD

**Issue by AirboZH** [halo-dev/halo#3170]
### 是什么版本出现了此问题？

2.2

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

![f956f1b6ca000384a6ba8cc087280cd](https://user-images.githubusercontent.com/50261327/212999584-ca85860f-b08e-4970-893e-703b3c39e61e.png)

删除第三行88888评论后

![05682f6ac9c63e049fd6b84dbd76ce3](https://user-images.githubusercontent.com/50261327/212999614-01884cab-dd4a-4694-a160-356daaf266e3.png)

https://github.com/halo-dev/console/blob/04819c12a82bfa0ce860f78fbe492cd27ab30ed4/src/modules/contents/comments/CommentList.vue#L400-L401

这很像是因为index做key造成的问题，我们应该用一个唯一id做key

**Comment by ruibaby** [comment]
很好的发现，但感觉应该和这里有关：

https://github.com/halo-dev/console/blob/04819c12a82bfa0ce860f78fbe492cd27ab30ed4/src/modules/contents/comments/components/CommentListItem.vue#L298

应该在头像的组件加 key

/area console
/kind bug

**Comment by AirboZH** [comment]
感谢您一大早五点就处理Issues哈哈，不好意思昨晚看错了代码
https://github.com/halo-dev/console/blob/04819c12a82bfa0ce860f78fbe492cd27ab30ed4/src/modules/contents/comments/CommentList.vue#L495

```html
 495:  <li v-for="(comment, index) in comments.items" :key="index">
```

应该是这个v-for导致的问题，我想这个地方的key换成`comment.comment.metadata.name`也就是这条评论的唯一标识，是不是更符合key的定义，也防止未来这个插槽下的其他内容出问题。**还是说这个地方有其他的考量，还请讲解一下。**

当时我也尝试了你说的在头像的组件加 key，效果都是没用问题的

测试效果图：
![becd4362a1064b5cba0a26298df8d8e](https://user-images.githubusercontent.com/50261327/213104813-ad81752a-4a6d-41e6-8916-99c12eaf12e6.png)
![96585c0a721ffed8be07781b0dd612c](https://user-images.githubusercontent.com/50261327/213104834-3c013aa9-a7f3-45f3-a108-eab14673be5a.png)

**Comment by ruibaby** [comment]
@AirboZH 两种方式解决目前的问题都是可以的。你可以先 assign 一下，然后有空可以提交一个 PR 来修复。（5点是因为我要坐车回家啦

**Comment by AirboZH** [comment]
好的，新年快乐🏮
/assign
