### ISSUE TITLE
支持自动将文章标题的拼音设置为别名

### ISSUE THREAD

**Issue by karma-sun** [halo-dev/halo#3171]
### Your current Halo version

2.1.0

### Describe this feature

支持自动将文章标题的拼音设置为别名,无需用户必填
1.6版有这个功能，建议移植过来

**Comment by JohnNiang** [comment]
/kind improvement
/area console

这个功能可能更适合在 Console 实现， @ruibaby 觉得呢？

**Comment by ruibaby** [comment]
@JohnNiang 是的，可以完全在 Console 实现。不过 2.0 我会尝试不仅仅是转拼音，推荐使用专门的 slug 转换库，比如：https://github.com/sindresorhus/slugify

**Comment by longjuan** [comment]
同时希望增加文章别名的帮助信息，例如：
![image](https://user-images.githubusercontent.com/28662535/213117519-5bd17655-cf24-4929-beaa-d791af7caabc.png)
![image](https://user-images.githubusercontent.com/28662535/213117575-4ab1e092-177a-4bee-9f93-1605c4daa0c3.png)

**Comment by ruibaby** [comment]
已在 https://github.com/halo-dev/console/pull/831 中支持，欢迎测试。

**Comment by karma-sun** [comment]
> 已在 [halo-dev/console#831](https://github.com/halo-dev/console/pull/831) 中支持，欢迎测试。

已测试，可以用
