### ISSUE TITLE
添加用户，如果有重名用户，报错信息有误

### ISSUE THREAD

**Issue by lixuejun725** [halo-dev/halo#3180]
### 是什么版本出现了此问题？

2.0

### 使用的什么数据库？

MySQL 5.7

### 使用的哪种方式部署？

Docker

### 发生了什么？

添加用户，如果有重名用户，报错信息有误

### 附加信息

![截屏2023-01-29 15 22 41](https://user-images.githubusercontent.com/38548829/215311534-bcf8708f-e46a-42e0-822b-f425f3bdc96e.png)

**Comment by ruibaby** [comment]
目前返回结构是这样的：

```
{
  "type": "about:blank",
  "title": "Internal Server Error",
  "status": 500,
  "detail": "executeMany; SQL [INSERT INTO extensions (name, data, version) VALUES ($1, $2, $3)]; duplicate key value violates unique constraint \"extensions_pkey\"",
  "instance": "/api/v1alpha1/users",
  "requestId": "a08bf55b-34389",
  "timestamp": "2023-01-30T04:42:24.045622Z"
}
```

不清楚是否可以语义化的输出异常信息。

/cc @halo-dev/sig-halo

**Comment by JohnNiang** [comment]
@ruibaby 这个错误确实需要转换一下，否则终端用户很难理解。

**Comment by ruibaby** [comment]
> @ruibaby 这个错误确实需要转换一下，否则终端用户很难理解。

怎么转。

**Comment by JohnNiang** [comment]
需要在服务端处理。
