### ISSUE TITLE
[Feature] 向默认文本编辑器提供添加链接语法

### ISSUE THREAD

**Issue by SanQianQVQ** [halo-dev/halo#3195]
### 你当前使用的版本

2.1.0

### 描述一下此特性

向默认文本编辑器提供使用语法：`[](url)`  从而添加链接的功能。

示例：
> `[Halo](https://github.com/halo-dev/halo)`
> [Halo](https://github.com/halo-dev/halo)

**Comment by ruibaby** [comment]
已经在 https://github.com/halo-sigs/richtext-editor/pull/3 中支持，会发布在 2.2.0。

/triage duplicate
/close
