### ISSUE TITLE
[Bug] 默认文本编辑器在移动端设备下无法正常渲染加粗后的简体中文

### ISSUE THREAD

**Issue by SanQianQVQ** [halo-dev/halo#3196]
### 是什么版本出现了此问题？

2.1.0

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker Compose

### 在线站点地址

https://blog.cute1000.com/archives/noelleGuide

### 发生了什么？

使用默认文本编辑器所提供的加粗功能加粗文字后并发表，发表的文章在移动端设备下无法正常看到简体中文的加粗效果

以下为示例：

> `**你好 Halo**`
预期效果：**你好 Halo**
实际效果：你好 **Halo**

测试环境： 
Android 11 - Chrome 109.0.5414.85
Android 11 - Via 4.2.6(20210331)

测试结果：稳定复现此问题

### 相关日志输出

```shell
None
```

### 附加信息

None

**Comment by ruibaby** [comment]
可能与设备字体有关，不属于 Halo 的问题。

/kind support

![image](https://user-images.githubusercontent.com/21301288/215925343-0ceef878-e4bf-46d7-bb7d-deb2e21c7a03.png)

**Comment by SanQianQVQ** [comment]
@ruibaby 更换设备后可正常显示，确实是字体问题

**Comment by JohnNiang** [comment]
问题似乎已经[解决](https://github.com/halo-dev/halo/issues/3196#issuecomment-1411330243)。我将关闭这个 issue。

/close
