### ISSUE TITLE
我觉得用的jar比较多 ，自己用的博客 太耗内存了

### ISSUE THREAD

**Issue by nhniu** [halo-dev/halo#320]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [ ] [Halo 使用文档](https://halo.run/docs)
- [ ] [Halo 论坛](https://bbs.halo.run)
- [ ] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [ ] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

**Comment by ruibaby** [comment]
@nhniu ？

**Comment by ruibaby** [comment]
@nhniu 嗯 看懂了，如果你在意这个的话。推荐Typecho或者Ghost。他们的包非常小，非常不错。
