### ISSUE TITLE
文章页出现资源不存在问题

### ISSUE THREAD

**Issue by Billow521** [halo-dev/halo#3203]
### 是什么版本出现了此问题？

2.2.0

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker Compose

### 发生了什么？

点击文章 - 点击页面 - 再点击文章，大概率会出现“资源不存在”
![图片](https://user-images.githubusercontent.com/81600616/216001881-71289bd0-f5ac-4436-b092-96f9a2141bc1.png)

**Comment by JohnNiang** [comment]
建议按 F12 键打开浏览器调试模式，看看具体是哪个网络请求出现了 404 错误。

/kind bug

**Comment by wangsz05** [comment]
![image](https://user-images.githubusercontent.com/25545685/216209969-bb794dd9-ee3c-4ce4-9860-2f2af393bba5.png)

看着是请求xxx/apis/api.console.halo.run/v1alpha1/posts/16e7f238-8b6f-4fc5-b1c6-41cd2ca1911b/head-content  
这个API请求不响应造成的
@JohnNiang

**Comment by guqing** [comment]
尝试清空一下 local storage 试一下 
<img width="538" alt="image" src="https://user-images.githubusercontent.com/38999863/216220722-74f64b8c-0ee9-435d-87b4-9adddcd7e2f4.png">

**Comment by ruibaby** [comment]
此问题已过时，在最新版本已经修复。

/close
