### ISSUE TITLE
插件提供的静态资源建议添加缓存标识

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#3205]
### 你当前使用的版本

2.2.0

### 描述一下此特性

目前在 https://github.com/halo-dev/halo/pull/3074 中对静态资源做了缓存策略的处理，但目前发现插件如果包含了静态资源，升级之后无法及时更新。

比如插件的静态资源为 `/plugins/PluginLinks/assets/console/main.js`，在未来某个版本更新了这个资源，那么在用户升级插件的时候就无法获取到新的资源。

目前设想的解决方案：

1. 添加版本的 path，如：/plugins/PluginLinks/1.1.0/assets/console/main.js
2. 添加版本的参数，如：/plugins/PluginLinks/assets/console/main.js?version=1.1.0

/kind improvement
/area core

**Comment by JohnNiang** [comment]
IMO，更倾向方案 2。这样既能缓存，也能在切换版本的时候忽略缓存。

**Comment by ruibaby** [comment]
@guqing 这个改动应该是不涉及到太多的业务，是否可以标记为 `good-first-issue`？

**Comment by guqing** [comment]
在以下部分设置两个链接时追加一个参数即可
https://github.com/halo-dev/halo/blob/0fd023b8f68ffead65b7fe9be63ea17150d5cda2/src/main/java/run/halo/app/core/extension/reconciler/PluginReconciler.java#L161-L165

/kind good-first-issue

**Comment by JohnNiang** [comment]
Duplicate https://github.com/halo-dev/halo/issues/3137
