### ISSUE TITLE
代码块bug

### ISSUE THREAD

**Issue by qqkkwan** [halo-dev/halo#3208]
### 是什么版本出现了此问题？

2.2

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式部署？

Docker Compose

### 发生了什么？

1. 新建文章
2. 插入代码块
3. **无法选中代码块右下角删除图标！**
4. **鼠标光标无法移动到代码块之外（有时候可以有时候不行），需要ctrl+enter才能到代码块之外**

### 附加信息

![image](https://user-images.githubusercontent.com/82800669/216262793-900ddcc4-1fd7-421f-aef3-4de7d58d2972.png)

**Comment by NOBB2333** [comment]
请问你的代码块在预览界面有颜色吗？  
同样是docker部署的项目2.3版本。  
我的在后台有颜色前台没有颜色，是黑白的

**Comment by JohnNiang** [comment]
> 请问你的代码块在预览界面有颜色吗？ 同样是docker部署的项目2.3版本。 我的在后台有颜色前台没有颜色，是黑白的

可能需要安装代码高亮插件：<https://github.com/halo-sigs/plugin-highlightjs>。

**Comment by NOBB2333** [comment]
@JohnNiang  多谢了，解决了很大问题，十分感谢

**Comment by ruibaby** [comment]
已经在 https://github.com/halo-sigs/richtext-editor/pull/13 中修复。

/close
