### ISSUE TITLE
评论组件博主标识和更多按钮的逻辑

### ISSUE THREAD

**Issue by Uyuhz** [halo-dev/halo#321]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [x] 添加新的特性或者功能
- [x] 请求技术支持

----
- 新特性或者新功能
1. 在评论者名字旁边增加一个博主之类的标识。如果用户没有注册Gravatar，一堆系统的头像容易分不清哪个是作者在回复....
2. 评论组件中的更多按钮点击第二次应该收起？比如把这个评论的回复前端清空之类的？

- 请求技术支持
评论组件的样式是不是不能直接在主题里覆盖啊，只能自己改一个打包了吗

**Comment by JohnNiang** [comment]
1. 后面会考虑将博主的头像作为回复的 avatar；
2. 博主标识也会在 halo-comment 加上；
3. 你可以考虑贡献代码至 halo-comment，我们 review 并合并之后，会发布一个版本，所有的博客的评论插件会自动引用最新版。

**Comment by JohnNiang** [comment]
关于评论组件中的更多按钮的二次点击，我们当时考虑的是再次请求服务器数据，如果你有更好的点击逻辑，可以考虑 PR 哦。

**Comment by ruibaby** [comment]
@JohnNiang 点击展开子评论后，再点击应该收起
