### ISSUE TITLE
2.2.0版本文章最后编辑日期显示不正确

### ISSUE THREAD

**Issue by xiuyuanjun** [halo-dev/halo#3212]
### 是什么版本出现了此问题？

2.2.0

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式部署？

Docker Compose

### 在线站点地址

http://www.xiuyuanjun.com

### 发生了什么？

旧的文章修改后，文章页最后编辑日期显示不正确。
<img width="426" alt="20230203103426845" src="https://user-images.githubusercontent.com/24690740/216498912-c551299b-d31c-4b5e-831e-6603ceddc76f.png">

### 附加信息

<img width="426" alt="20230203103426845" src="https://user-images.githubusercontent.com/24690740/216498926-daead761-e5c4-4456-885d-62282641922d.png">

**Comment by guqing** [comment]
需要注意的是，文章的最后修改时间指的是文章内容，需要发布后才会被更新，比如：
文章 A，发布一次后最后修改时间为：2023-02-02T09:47:25.234233Z 点保存是不会更新的，只有发布后才会变

**Comment by xiuyuanjun** [comment]
是的，就是重新修改后，点的发布。但是最后编辑时间还是没有变化啊

**Comment by ruibaby** [comment]
可能是主题没有适配，最后编辑时间是在 2.2 才加的。

**Comment by xiuyuanjun** [comment]
有可能。

**Comment by ruibaby** [comment]
建议向 https://github.com/LIlGG/halo-theme-sakura 提交 issue。

/close
