### ISSUE TITLE
session过期后浏览器弹出原生登录框

### ISSUE THREAD

**Issue by longjuan** [halo-dev/halo#3213]
### 是什么版本出现了此问题？

2.2.0

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

当session过期后，继续在console端操作，弹出原生登录提示框。
![image](https://user-images.githubusercontent.com/28662535/216504644-438b5f61-f115-4899-a08b-0e313f44e794.png)

console端已有重新登录提示框，弹出原生登录框影响体验。
![image](https://user-images.githubusercontent.com/28662535/216504679-d4ed0db2-45e1-4432-b499-69e0953c4d2e.png)

原因是响应头里有`WWW-Authenticate: Basic realm="Realm"`
![image](https://user-images.githubusercontent.com/28662535/216504895-268adcc9-ca28-42ba-9660-feab7c19c8a7.png)

### 附加信息

根据spring security的指引文档，可在请求头加入`X-Requested-With=XMLHttpRequest`
详情https://spring.io/guides/tutorials/spring-security-and-angular-js/ 中搜索`X-Requested-With`

可利用axios的defaults.headers.common实现
https://github.com/axios/axios#custom-instance-defaults

**Comment by guqing** [comment]
pr welcome

**Comment by JohnNiang** [comment]
@longjuan ，建议在生产环境禁用 BasicAuth 的认证方式。

**Comment by longjuan** [comment]
> @longjuan ，建议在生产环境禁用 BasicAuth 的认证方式。

这不是一个 feature 吗？
https://github.com/halo-dev/halo/blob/main/docs/authentication/README.md

**Comment by JohnNiang** [comment]
> > @longjuan ，建议在生产环境禁用 BasicAuth 的认证方式。
> 
> 这不是一个 feature 吗？ https://github.com/halo-dev/halo/blob/main/docs/authentication/README.md

可以移除这个 feature 么？

/meow

**Comment by guqing** [comment]
只要在生产环境不会出现弹出原生登录框的情况那么，在生产环境保留 basicAuth 是否也是可行的

**Comment by JohnNiang** [comment]
可以。先解决掉弹窗问题。

**Comment by guqing** [comment]
@longjuan 此 issue 依然需要，感谢贡献

**Comment by longjuan** [comment]
> 生产环境禁用 BasicAuth 的认证方式

好的

**Comment by guqing** [comment]
> > 生产环境禁用 BasicAuth 的认证方式
> 
> 好的

这项与此 issue 无关，可以不考虑，只需要解决 basicAuth 不弹出原生登录框即可

**Comment by JohnNiang** [comment]
> > 生产环境禁用 BasicAuth 的认证方式
> 
> 好的

经过以上讨论，暂时不禁用 BasicAuth 认证方式，因为这可能会造成破坏性更新。可能已经有人正在使用这种认证方式了。目前还是按照 PR 描述中的方案解决即可。

**Comment by longjuan** [comment]
...
引用错了
