### ISSUE TITLE
基础体验待优先优化

### ISSUE THREAD

**Issue by zongdeiqianxing** [halo-dev/halo#3218]
### 你当前使用的版本

v2.2.0

### 描述一下此特性

作为博客cms，markdown编辑的这一主体功能使用体验还未恢复

建议：
1. 选定某markdown编辑器内置到cms中，无需自己下扩展
2. markdown编辑时（已测试推荐的bytemd和StackEdit）图床总是出bug。首先是内存里复制的图片无法直接粘贴到文章里，其次应该是第一次插图成功后，后续其他图片永远都插不进去，总是报附件已存在
3. markdown编辑时应给到可以预览功能。

综上，建议优先恢复编辑使用这一主体功能，其他都是次要。

**Comment by guqing** [comment]
感谢你的建议，由于目前 2.0 是从头开始的，目前基础功能还未稳定，优化将是一个长期的过程，我们会不断改进体验 🫡

**Comment by ruibaby** [comment]
关于内置 Markdown 编辑器的问题，目前不考虑直接内置。后续会官方维护一个 Markdown 编辑器插件，并在 https://github.com/halo-dev/halo/issues/3120 完成之后默认集成这个插件。

**Comment by ruibaby** [comment]
在 https://github.com/halo-dev/halo/pull/3305 中仅解决了第二点。

/reopen

PS：后续反馈建议一个 issue 对应一个问题。

**Comment by ruibaby** [comment]
/close

目前第三点已经统一支持文章预览，社区提供的编辑器也应该支持预览。
