### ISSUE TITLE
博客响应超慢

### ISSUE THREAD

**Issue by Rainsheep** [halo-dev/halo#3221]
### What is version of Halo has the issue?

 2.2.0

### What database are you using?

MySQL 8.x

### What is your deployment method?

Docker Compose

### Your site address.

https://www.rainsheep.cn/

### What happened?

按照教程 https://docs.halo.run/getting-started/install/docker-compose 安装。

安装完成后使用迁移助手，从 1.6 迁移至 2.2 (备份文件大小 18M).

文章数量：512

迁移完成后博客响应超慢，基本无法使用。

**Comment by Rainsheep** [comment]
1.6 版本无此问题

**Comment by JohnNiang** [comment]
目前确实存在这个问题，不过我们也正在解决它。

Halo 在首次启动的时候会注册路由等一系列操作，需要再稍微等等。

/kind support

**Comment by Rainsheep** [comment]
等待较长时间后，有所好转，访问速度可以接受，还需优化。
