### ISSUE TITLE
插件安装之后无法保存设置

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#3224]
### 是什么版本出现了此问题？

2.2.0

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 在线站点地址

https://halo.run

### 发生了什么？

<img width="1442" alt="image" src="https://user-images.githubusercontent.com/21301288/216764069-06898f64-e6ff-4455-94f6-8014ae511ed3.png">

如图，具体表现为点击保存按钮无任何反应，原因可能是因为安装之后 configmap 没有正常初始化，比如 `/apis/api.console.halo.run/v1alpha1/plugins/PluginFeed/config` 接口是空的 Response。

临时解决方案：一般重启插件之后可以恢复正常。

/area core
/kind bug

**Comment by guqing** [comment]
原因分析：
 插件安装时先创建 plugin.yaml 然后判断是否配置了 settingName，如果设置了则需要根据 settingName 查询 Setting 然后读取默认值创建 ConfigMap
但此时查询 Setting 可能还查询不到，由于插件启动才会创建 Setting 且这个过程是异步的，而查询不到 Setting 就跳过了读取默认值的逻辑所以导致 ConfigMap 没有创建。

解决思路：如果 plugin.yaml 中配置了 settingName ，则默认为插件中一定有 Setting 对应的 yaml 它最终会被创建到数据库，如果没有则就是异常情况，所以当查询 Setting 没有获取到时将插件标记为 Failed 状态并抛出异常，然后会被 reconciler 重试，等到能查询到时即可继续完成剩余步骤。
