### ISSUE TITLE
完善初始化流程

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#3230]
### 你当前使用的版本

2.2.0

### 描述一下此特性

目前在首次安装的时候登录 Console 会有一个简单的初始化页面，仅支持设定站点标题，期望对其进行以下完善：

1. 保存初始化状态，首次安装时如果没有初始化，那么重定向到初始化页面，包括首页（目前的状态是可以访问首页，但没有任何数据，这会一定程度导致观感不佳。并且有一定概率主题模板因为没有数据而导致异常）。
2. 支持以下初始化内容
    1. 管理员
    2. 站点标题
    3. 插件、主题

相关 issue：https://github.com/halo-dev/halo/issues/3120

/area core
/area console
/kind improvement

**Comment by JohnNiang** [comment]
初步想法：

创建一个 Extension 专门用于保存初始化数据，同时运行 Reconciler 进行初始化（包括创建管理员，文章，页面，分类，标签，菜单等），初始化完毕之后在 status 中设置已初始化的状态。
