### ISSUE TITLE
搜索不准确

### ISSUE THREAD

**Issue by Rainsheep** [halo-dev/halo#3234]
### What is version of Halo has the issue?

 2.2.0

### What database are you using?

MySQL 5.7

### What is your deployment method?

Docker Compose

### Your site address.

https://www.rainsheep.cn/

### What happened?

搜索是博客的一个重要功能，帮助我们通过关键字快读找到自己想要的内容。
经过尝试，个人感觉，halo2 的搜索插件及其难用。 试了一下 wordpress/hexo 的搜索还不错，经过对比，从以下几个方面陈述下我个人认为不如意的地方。
整体来说，对于英文还行，对于中文太弱了。

搜索不到问题
我有一篇文章，title 为 "java 安全管理器", 直接搜 title 竟然搜索不到！
搜索关键字 "安全"，也搜索不到。 搜索 "java" 能搜到。 halo 中文用户这么多，希望支持一下。

搜索不全问题
英文情况下，因为中文根本搜不到。
比如我搜索 "java", 仅仅给我列出了一下文章，搜索内容不全

![image](https://user-images.githubusercontent.com/42384577/216901679-dae2679a-93fa-4f05-b139-71a1e34cfc45.png)

权重问题
还是这个例子
![image](https://user-images.githubusercontent.com/42384577/216901679-dae2679a-93fa-4f05-b139-71a1e34cfc45.png)

title 中含有 java 的是否应该在前面？ 这个搜寻结果的排序不符合预期，简单说，就是"相关性低的" 在 "相关性高的" 前面。
支持 or
希望可以同时多个关键字定位一篇文章，比如 我输入 "java springboot", 希望可以搜索出三类文章
a. 同时和 "java" "springboot" 相关的，排在最前面
b. 只和 "java" 相关的排在后面
c. 只和 "springboot" 相关的排在后面。
最后，halo2 问世时间还短，作者能做成现在规模已经很棒了，尤其还是开源的，各位作者辛苦了。
但从产品角度出发，halo2 甚至不满足我对于博客的基本需求，它不是一个好的选择，任重而道远。

**Comment by JohnNiang** [comment]
非常中肯的评价！

目前，[Lucene](https://lucene.apache.org/) 是以依赖的形式作为 Halo 的默认搜索引擎，是目前我们能找到的最适合作为默认选项的搜索引擎。正如文中所说，对于搜索结果的相关度没有适配得很好，可能主要是因为对 Lucene 的不熟悉。后面会不断迭代出更好的搜索体验。

同时也期望社区在未来能够贡献 MeiliSearch、ElasticSearch，Solr 等优秀的搜索引擎插件，解决以上问题。

/kind improvement
/area core

**Comment by Rainsheep** [comment]
本人基于 halo 1.x 集成了 meilisearch，增强了搜索功能， https://github.com/Rainsheep/rs-halo/tree/rs-main，有对搜索强需求的朋友可以先用。

**Comment by Rainsheep** [comment]
本人基于 halo 1.x 集成了 meilisearch，增强了搜索功能，有对搜索强需求的朋友可以试试，项目只进行bug修复和同步官方halo 1.x的更新，不做大的功能改动。
下个版本会继续 Dream 主题继续增强搜索功能。

后期有时间的话会进行 halo2 搜索插件的开发，项目地址  https://github.com/Rainsheep/rs-halo/tree/rs-main
本人站点 ： https://www.rainsheep.cn (可测试搜索功能)
搜索小提示：多个关键词用空格分开，前面关键词权重大于后面的

**Comment by JohnNiang** [comment]
Hi @Rainsheep ，默认搜索引擎搜索不准确的问题已经在 https://github.com/halo-dev/halo/pull/3457 修复，并且已经发布到 [Halo 2.3.1](https://github.com/halo-dev/halo/releases/tag/v2.3.1)，欢迎尝试并反馈。
