### ISSUE TITLE
IDEA运行卡住

### ISSUE THREAD

**Issue by khq007110** [halo-dev/halo#3237]
### What is version of Halo has the issue?

主干版本

### What database are you using?

H2

### What is your deployment method?

Docker

### What happened?

![1675739556279](https://user-images.githubusercontent.com/30292848/217139029-7472ba41-5033-477d-b39a-30e2af707683.png)

**Comment by guqing** [comment]
/kind support
卡住是什么表现，看你目前的日志并没有什么问题，访问不到 localhost:8090 吗

**Comment by khq007110** [comment]
启动一直没执行完，运行到这个为止就不往下走了
2023-02-07T11:15:46.403+08:00 DEBUG 15600 --- [eReconciler-t-1] r.h.a.e.controller.DefaultController     : run.halo.app.core.extension.reconciler.RoleReconciler-worker-1 >>> Reconciled request: Request[name=role-template-view-users] with result: Result[reEnqueue=false, retryAfter=null]

**Comment by guqing** [comment]
如果你不习惯 IDEA 的这种界面，可以在 Preferences -> Build -> Build Tools -> Gradle 将下图的两项都改为 Intellij IDEA
<img width="893" alt="image" src="https://user-images.githubusercontent.com/38999863/217139942-038acb14-15d7-4b32-ab3d-2141cd3ab0c8.png">

**Comment by guqing** [comment]
> 启动一直没执行完，运行到这个为止就不往下走了 2023-02-07T11:15:46.403+08:00 DEBUG 15600 --- [eReconciler-t-1] r.h.a.e.controller.DefaultController : run.halo.app.core.extension.reconciler.RoleReconciler-worker-1 >>> Reconciled request: Request[name=role-template-view-users] with result: Result[reEnqueue=false, retryAfter=null]

<img width="1086" alt="image" src="https://user-images.githubusercontent.com/38999863/217140585-f9d74017-5ff4-4411-a4e4-dfe5e0c5be7c.png">
你只要在最顶部的日志中看到例如 Started Application in 5.624 seconds (process running for 6.507) 的日志应用就已经启动成功了，后续的日志都是一个叫 DefaultController 的周期性日志，应用没有停止或者你可以访问到 localhost:8090 就是正常的

**Comment by khq007110** [comment]
进去了，前端也要启动，之前前端没启动，访问不了，我以为是启动没完成的问题

**Comment by guqing** [comment]
> 

好的
