### ISSUE TITLE
文章链接建议增加crc32生成选项

### ISSUE THREAD

**Issue by Vlary** [halo-dev/halo#3244]
### 你当前使用的版本

 v2.2.0

### 描述一下此特性

中文链接对百度等爬虫不太友好，文章链接建议增加crc32生成选项

**Comment by ruibaby** [comment]
你可以再系统设置里面这样设置：

<img width="812" alt="image" src="https://user-images.githubusercontent.com/21301288/217198352-5dc6b7ec-949f-4203-bd13-b5227bd67652.png">

另外，2.2.0 已经在 https://github.com/halo-dev/console/pull/831 中支持通过标题生成别名，但仅对新文章有效，以前的需要手动重新生成。
