### ISSUE TITLE
界面搜索框消失

### ISSUE THREAD

**Issue by khq007110** [halo-dev/halo#3248]
### What is version of Halo has the issue?

主干版本

### What database are you using?

H2

### What is your deployment method?

Docker

### What happened?

![1675825266332](https://user-images.githubusercontent.com/30292848/217417848-498afdd7-8146-467c-8e6a-b774f0bed6ed.png)

**Comment by ruibaby** [comment]
安装 https://github.com/halo-sigs/plugin-search-widget 插件即可。

/kind support
