### ISSUE TITLE
博客无法访问

### ISSUE THREAD

**Issue by Chexian1** [halo-dev/halo#325]
运行之后，显示一个Halo Dashboard的页面，里面是个空页面，加载不出来，怎么回事，求教。

**Comment by JohnNiang** [comment]
可以提供一下截图么？或者查看 halo 的日志是否有错误。

**Comment by Chexian1** [comment]
就是这个项目是Gradle构建的，我弄不太来，我配置了Tomcat运行后，显示\halo-master (1)\out\artifacts\unnamed not found for the web module.这个错误，然后也没有跳转出浏览器，不知道如何解决。

**Comment by ruibaby** [comment]
@Chexian1 不需要外置Tomcat ，直接运行Application类即可。

**Comment by ruibaby** [comment]
@Chexian1 参考 https://halo.run/develop/application/structure.html

**Comment by Chexian1** [comment]
是不是要创建数据库啊？我运行后点击控制台的连接
![截图1570593516](https://user-images.githubusercontent.com/50158987/66450733-28107900-ea8c-11e9-8545-56ff54831ad7.png)
然后出现下图

![截图1570593372](https://user-images.githubusercontent.com/50158987/66450701-044d3300-ea8c-11e9-86a2-c75b2bd2bb71.png)

**Comment by JohnNiang** [comment]
应该是网络问题。

**Comment by Chexian1** [comment]
就是在不停转圈

**Comment by JohnNiang** [comment]
再等等

**Comment by Chexian1** [comment]
而且Idea运行不应该自动跳出页面，为什么需要我去点击控制台链接

**Comment by JohnNiang** [comment]
> 而且Idea运行不应该自动跳出页面，为什么需要我去点击控制台链接

这个我们暂时不知道如何才能自动跳出页面。

如果没有其他问题，我们将关闭此 issue。
