### ISSUE TITLE
为插件提供评论、文章等操作事件感知能力

### ISSUE THREAD

**Issue by pannanxu** [halo-dev/halo#3251]
### 你当前使用的版本

2.x

### 描述一下此特性

1. 评论创建、审核时发布事件并通知到插件
2. 文章创建、审核等操作发布事件并通知到插件

**Comment by ruibaby** [comment]
[2.17](https://github.com/halo-dev/halo/releases/tag/v2.17.0) 已经支持监听事件。

/close
