### ISSUE TITLE
优化系统启动时主题端的链接访问

### ISSUE THREAD

**Issue by guqing** [halo-dev/halo#3254]
### Your current Halo version

latest

### Describe this feature

如果文章多系统刚启动时需要很长时间才能访问，主要是因为 Reconciler 在运行，只要运行到某个资源的 Reconciler 时才能注册路由因此很长时间才能访问到。

优化方案：
能通过注册 pattern 作为路由的就注册 pattern 这样系统启动时不会影响到资源的访问。

### Additional information

/kind improvement
/area core
/milestone 2.3.x
/assign

**Comment by JohnNiang** [comment]
More refs:

- https://github.com/halo-dev/halo/issues/3221
