### ISSUE TITLE
需要为编辑器上传图片提供默认的存储策略和附件分组

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#3258]
### 你当前使用的版本

2.2.0

### 描述一下此特性

目前在 https://github.com/halo-dev/console/pull/825 中已经实现了拖拽和粘贴图片到编辑器中并上传到附件库，但在初始实现中，获取上传存储策略的方式为获取所有存储策略中的第一个，这种方式的实现带来了不确定性，尤其是在同时有多个存储策略的时候，所以期望支持设置默认存储策略。

/area core
/area console
/priority important-soon
/milestone 2.3.x

**Comment by JohnNiang** [comment]
建议提供“多场景”（编辑器上传图片，上传用户头像）的附件策略和分组配置。

**Comment by ruibaby** [comment]
在 https://github.com/halo-dev/halo/pull/4866 中已经支持。

/close
