### ISSUE TITLE
使用外部编辑器插件时，编辑文章在未修改的前提下会提示：已从缓存中恢复未保存的内容

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#3259]
### 是什么版本出现了此问题？

2.2.0

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 在线站点地址

https://ryanc.cc

### 发生了什么？

如图：

<img width="1426" alt="image" src="https://user-images.githubusercontent.com/21301288/217549033-4de8b117-99fd-4d6c-a5cc-360c797eafd2.png">

只要打开编辑页面一次，在未修改的情况下再进入编辑页面就会出现这个提示，猜测与编辑器插件的更新内容时机有关。

可复现的插件：

1. https://github.com/halo-sigs/plugin-stackedit
2. https://github.com/halo-sigs/plugin-bytemd

/kind bug
/area console
/priority critical-urgent

**Comment by JohnNiang** [comment]
Closing due to https://github.com/halo-sigs/plugin-bytemd/pull/5 merged

/close
