### ISSUE TITLE
post.ftl中的categories变量问题

### ISSUE THREAD

**Issue by CodeLunatic** [halo-dev/halo#326]
我在进行主题开发的时候，想在post.ftl中使用categories变量，但是却发现categories总是返回所有的分类，是因为我错误的使用了吗？

我尝试使用：
```freemarker
${categories?size}
```
发现文章是否有分类，都会返回分类的总数量

当前我使用下面的方式来替代
```freemarker
<@categoryTag method="listByPostId" postId="${post.id}">
     <#list categories as categorie>
     <a href="/categories/${categorie.slugName}"
          class="text-dark font-weight-bold">${categorie.name}</a>
          <#sep>|
     </#list>
</@categoryTag>
```

**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

**Comment by JohnNiang** [comment]
> https://halo.run/develop/theme/model-variable.html#post

尝试 post.categories
