### ISSUE TITLE
2.2版本：删除附件图片后还可以访问，导致的无法显示新图片问题

### ISSUE THREAD

**Issue by ikcro** [halo-dev/halo#3260]
### What is version of Halo has the issue?

2.2

### What database are you using?

MySQL 5.7

### What is your deployment method?

Docker Compose

### What happened?

安装环境：

- 版本：2.2
- 数据库5.7

问题出现的步骤：

1. 当我上传了一张图片到附件库中（图片名称为logo.png），使其作为网站logo图片
2. 我删除了这个附件图片，然后上传了一张新图片（名称同样为logo.png）,然后设置中将新上传的图片设置为logo
3. 发现logo更换不起作用，我更换了电脑进行访问，而网站还是显示为旧的logo图片

问题排查：

1. 我尝试删除了附件中的logo图片，然后设置网站logo为空
2. 然后访问这个附件的地址（xx.com/upload/logo.png）发现这个图片还可以访问，并且是旧的图片（第一次上传时候的图片）

怀疑是删除附件的时候，系统内置的缓存并未清空，我重启了我的项目，然后发现这个删除的图片还是可以访问，请问是不是项目内部有文件缓存，我应该如何处理这种情况，我现在就是上传一张普通的图片，名字为logo.png，而访问的图片还是第一次上传的图片。

期望：

1. 是否可以删除附件时清理内部缓存，我不清楚是不是我操作上有什么问题，但这只是个更新logo的场景（上传名称一样的图片，而之前的图片已经删除的情况下），期望可以得到回复，非常感谢🙏。

**Comment by ikcro** [comment]
暂时使用OSS和COS来解决了这个问题，后序我继续测试了一会儿，发现问题还是会复现，期待解决

**Comment by JohnNiang** [comment]
目前，Halo 对静态资源添加了缓存相关的 Header，也就意味着浏览器可能会缓存图片一年时间。

```bash
accept-ranges: bytes
cache-control: max-age=31536000 # 默认浏览器缓存时长 1 年
content-length: 3592
content-type: image/svg+xml
date: Thu, 09 Feb 2023 06:07:14 GMT
last-modified: Wed, 04 Jan 2023 03:56:48 GMT
```

遇到以上情况，建议强制刷新一下网页或者清除浏览器缓存再试试。

**Comment by ikcro** [comment]
我更换了从未访问过的设备进行访问附件图片的地址，但还是可以访问的到这个图片，但之前这个图片已经被我删除了，所以应该不是浏览器缓存的问题🙏

**Comment by JohnNiang** [comment]
> 我更换了从未访问过的设备进行访问附件图片的地址，但还是可以访问的到这个图片，但之前这个图片已经被我删除了，所以应该不是浏览器缓存的问题🙏

如果删除后还能够访问图片，那可能是本地图片并未被物理删除。

下次仍然遇到这个问题的时候，建议捕捉最新的日志。

**Comment by ikcro** [comment]
谢谢回复，目前的解决方案是安装插件使用了外部存储
