### ISSUE TITLE
顶部导航栏建议加上背景颜色，白底黑字，黑底白字，目前浅色头部图片无法看清导航字体（如图）

### ISSUE THREAD

**Issue by wuzhuwei111** [halo-dev/halo#3262]
### 你当前使用的版本

1.0.7-main

### 描述一下此特性

顶部导航栏建议加上背景颜色，白底黑字，黑底白字，目前浅色头部图片无法看清导航字体（如图）

### 附加信息

[tu1](https://www.wuzhuwei.work/upload/2023/02/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_20230209101338.png)[tu2](https://www.wuzhuwei.work/upload/2023/02/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_20230209102022.png)

**Comment by wuzhuwei111** [comment]
![微信截图_20230209102022](https://www.wuzhuwei.work/upload/2023/02/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_20230209102022.png)
![微信截图_20230209101338](https://www.wuzhuwei.work/upload/2023/02/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_20230209101338.png)

**Comment by JohnNiang** [comment]
建议去对应的主题仓库提交 Issue：<https://github.com/liuzhihang/halo-theme-hao/issues>。

**Comment by JohnNiang** [comment]
Please refer to <https://github.com/liuzhihang/halo-theme-hao/issues/81>.
