### ISSUE TITLE
建议控制台概览界面新增数据库版本等信息展示

### ISSUE THREAD

**Issue by xiuyuanjun** [halo-dev/halo#3263]
### 你当前使用的版本

2.2.0

### 描述一下此特性

建议控制台概览界面新增所使用的数据库版本等信息展示

<img width="960" alt="微信截图_20230209103732" src="https://user-images.githubusercontent.com/24690740/217703480-4d5dc86a-6d87-4036-b1c5-72f259df236d.png">

**Comment by JohnNiang** [comment]
/kind feature
/area core
/area console
/milestone 2.3.x

如果有兴趣的话，可以了解一下：
- https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.endpoints.info.writing-custom-info-contributors
- https://r2dbc.io/spec/1.0.0.RELEASE/api/io/r2dbc/spi/class-use/ConnectionMetadata.html
