### ISSUE TITLE
增加插件仓库跟主题仓库

### ISSUE THREAD

**Issue by mytianya** [halo-dev/halo#3264]
### 你当前使用的版本

halo2.2

### 描述一下此特性

halo2.0版本之后安装主题跟插件需要用户到github自己找主题跟插件下载。建议：
1、默认内置常用的Rss、评论、markdown等常用插件，免得用户自己一个个找下载
2、提供halo1.0的主题跟插件仓库，让开发者上架主题或者插件，后面也可以集成收费模式，给企业使用类似Jpress让更多人有动力开发主题，不光用爱发电。

**Comment by ruibaby** [comment]
应用市场已经上线：https://halo.run/store/apps
内置插件已经在 https://github.com/halo-dev/halo/pull/3427 中支持。

/close
