### ISSUE TITLE
期待提供.md文件导入

### ISSUE THREAD

**Issue by Steven-WZH** [halo-dev/halo#3268]
### 你当前使用的版本

2.2.0

### 描述一下此特性

增加一个导入.md文件的功能
1.0版本的时候好像有2.0版本我没找到这个功能

**Comment by NOBB2333** [comment]
现在似乎只有数据迁移的功能，是一个插件，导入jar包就行

`https://github.com/halo-sigs/plugin-migrate`

**Comment by yunkailu** [comment]
+1

**Comment by JohnNiang** [comment]
Hi @Steven-WZH ，当前问题已经有不少社区成员期望支持，且暂未解决，建议重新打开。

/reopen

**Comment by Bytelv** [comment]
关注+1

**Comment by ruibaby** [comment]
建议尝试一下使用 VSCode 插件来发布 Markdown 到 Halo：https://marketplace.visualstudio.com/items?itemName=halo-dev.halo

我认为这种方式才是导入 Markdown 文档的最优解，而不是去后台上传 Markdown 文档。

**Comment by Bytelv** [comment]
> 
请问vscode中插件如何使用？
halo.json中app_id和app_secret在哪里获得？

**Comment by kz-worn** [comment]
+1

**Comment by ruibaby** [comment]
> > 
> 
> 请问vscode中插件如何使用？ halo.json中app_id和app_secret在哪里获得？

根据你的描述，似乎看的是 Halo 1.x 的旧版本，可能你的 VSCode 插件市场缓存没有更新。

使用方式可以看：https://github.com/halo-sigs/vscode-extension-halo/blob/main/README-zh.md

**Comment by kz-worn** [comment]
> > > 
> > 
> > 
> > 请问vscode中插件如何使用？ halo.json中app_id和app_secret在哪里获得？
> 
> 根据你的描述，似乎看的是 Halo 1.x 的旧版本，可能你的 VSCode 插件市场缓存没有更新。
> 
> 使用方式可以看：https://github.com/halo-sigs/vscode-extension-halo/blob/main/README-zh.md

在VS code中使用halo插件，初始化halo时卡在设置附件存储策略。
问题：设置为 local，但进度条一直在显示加载。
请问还需要什么前提条件吗？

**Comment by Bytelv** [comment]
> 

同问

**Comment by ruibaby** [comment]
目前已经提供了以下 Markdown 的发布方式：

1. https://github.com/halo-sigs/obsidian-halo
2. https://github.com/halo-sigs/vscode-extension-halo
3. https://github.com/terwer/siyuan-plugin-publisher

可以满足发布 Markdown 文档到 Halo，并且支持后续更新，我不认为单纯在 Console 提供一个选择 Markdown 文件导入是一个可持续的发布方式。我将关闭此 issue，如果后续有其他想法欢迎提交新的 issue。

/close
