### ISSUE TITLE
图库页面图片连接丢失bug

### ISSUE THREAD

**Issue by keNkasikoikoro** [halo-dev/halo#327]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x ] [Halo 使用文档](https://halo.run/docs)
- [x ] [Halo 论坛](https://bbs.halo.run)
- [x ] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x ] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持
photo页面中，使用中文文件名会导致作为图片浏览的html标签中 background-position: left center; background-image: url("");直接丢失其中的连接，还望告知是哪里出了问题。

**Comment by JohnNiang** [comment]
可能是因为 url 未进行编码的问题。我们后面会尝试修复这个问题。

**Comment by ruibaby** [comment]
这个问题已被修复。
