### ISSUE TITLE
部分文章目录跳转有误

### ISSUE THREAD

**Issue by ldm0715** [halo-dev/halo#3271]
### 是什么版本出现了此问题？

Halo 2.2

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

有些文章点击目录标题会跳转到文章开头，而有些文章能正常跳转到相应的标题部分。

**Comment by JohnNiang** [comment]
/triage needs-information

可能需要补充当前使用的主题以及截图。
