### ISSUE TITLE
期望提供备份和恢复功能

### ISSUE THREAD

**Issue by Steven-WZH** [halo-dev/halo#3274]
### 你当前使用的版本

2.2.0

### 描述一下此特性

新增一个备份功能（仅支持h2数据库）
可以把文章啊···等等等全部备份到一个压缩包里面，然后再做一个导入功能

**Comment by Steven-WZH** [comment]
还有就是如果现在想备份的话应该备份哪个目录或者文件捏

**Comment by Steven-WZH** [comment]
好的，thx

**Comment by wan92hen** [comment]
> Hi @Steven-WZH , 目前有两种数据需要备份：
> 
> 1. 附件+主题+插件+配置文件
>    如果你没有修改过工作目录，则只需要备份：`~/.halo2` 文件夹。
> 2. 数据库
>    
>    * 如果你使用的是 H2，则上一步已经完成了数据库的备份。
>    * 其他数据库则按照对应的备份方式备份即可。

可以先按目前的处理方式，补充下手动备份和恢复的文档。
