### ISSUE TITLE
当前分类以及层级较多时，拖拉分类不方便

### ISSUE THREAD

**Issue by lixuejun725** [halo-dev/halo#3281]
### 你当前使用的版本

2.2

### 描述一下此特性

当前分类以及层级较多时，拖拉分类不方便，期望增加分类层级结构，以及能够在新建分类的时候选择上级目录

**Comment by ruibaby** [comment]
已经在 2.7 支持。

https://github.com/halo-dev/halo/releases/tag/v2.7.0

**Comment by lixuejun725** [comment]
好的，后续进行尝试，感谢
