### ISSUE TITLE
搜索插件可以搜索已删除的文章???

### ISSUE THREAD

**Issue by Steven-WZH** [halo-dev/halo#3282]
### 是什么版本出现了此问题？

2.2.0

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 在线站点地址

https://blog.steven.tk

### 发生了什么？

搜索hello可以搜索出安装halo成功的默认文章

而这个文章我已经删除了

**Comment by ruibaby** [comment]
/triage duplicate

see https://github.com/halo-dev/halo/issues/3121

/close
