### ISSUE TITLE
自定义logo在console 端只有登录后展示

### ISSUE THREAD

**Issue by chengfeiyue** [halo-dev/halo#3285]
### What is version of Halo has the issue?

2.2.0

### What database are you using?

PostgreSQL

### What is your deployment method?

Docker Compose

### Your site address.

https://infra-pv.saicmotor.com/console

### What happened?

自定义logo在console 端只有登录后展示
console端未登录状态
<img width="179" alt="image" src="https://user-images.githubusercontent.com/49852751/218045071-670ab7d4-c725-40fb-90d9-fc20923947f1.png">

console端登录状态
<img width="198" alt="image" src="https://user-images.githubusercontent.com/49852751/218044936-f7598cb5-1247-48bc-926f-9980b49a2fbd.png">

**Comment by ruibaby** [comment]
目前没有在未登录的情况下，Console 无法拿到 Favicon 的设置项，可能需要后端通过类似 `/actuator/globalinfo` 接口将 Favicon 暴露出来。

/area core
