### ISSUE TITLE
Improve error tips when posts are not found

### ISSUE THREAD

**Issue by JohnNiang** [halo-dev/halo#3286]
### Your current Halo version

2.3.0-SNAPSHOT

### Describe this feature

I got the error tips below If the post was deleted.

![image](https://user-images.githubusercontent.com/16865714/218047044-d93b64a2-7faa-4663-8a99-263a53057fbd.png)

It would be better if the error page displays `Post not found or deleted` when the post is deleted or not found.

### Additional information

/kind improvement
/area core

**Comment by guqing** [comment]
此问题应该已经不存在了
我尝试了不存在的文章和回收站的文章访问均能得到下图所示：
<img width="1060" alt="image" src="https://user-images.githubusercontent.com/38999863/231404933-b422adef-bc33-49de-8c9b-47e85b6cb888.png">

/close
