### ISSUE TITLE
评论删除后文章管理界面仍然显示

### ISSUE THREAD

**Issue by Steven-WZH** [halo-dev/halo#3287]
### 是什么版本出现了此问题？

2.2.0

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 在线站点地址

https://blog.steven.tk

### 发生了什么？

![image](https://user-images.githubusercontent.com/113268133/218258433-176f37f9-48f5-4670-a51f-7cc92610a86f.png)
![image](https://user-images.githubusercontent.com/113268133/218258436-f0f9764a-b9b5-41de-af0b-68c9f2a63698.png)

**Comment by Steven-WZH** [comment]
文章链接：
https://blog.steven.tk/?p=you-xi-ravenfield

**Comment by JohnNiang** [comment]
我在本地并未复现。

/triage needs-information

**Comment by longjuan** [comment]
> 我在本地并未复现。

我这成功复现。
CommentReconciler在更新counter时，Comment有时没有删除，导致counter更新错误。
同时在删除最后一个评论时，按现在的逻辑，Comment删除后updateCommentCounter不会被执行，导致必然清不了零。
我明天再看看提个PR？

**Comment by longjuan** [comment]
/assign

> 昨天看错了，Comment删除后updateCommentCounter会被执行，只是没有过滤掉删除了的，同时不能把counter清零。
