### ISSUE TITLE
文章标题中包含“/”文章将无法访问的bug

### ISSUE THREAD

**Issue by itomcat666** [halo-dev/halo#329]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [ x] [Halo 使用文档](https://halo.run/docs)
- [x ] [Halo 论坛](https://bbs.halo.run)
- [ x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x ] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x ] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

如果自动生成的中文标题中包含“/”，发表的文章将无法访问并提示404，建议自动生成的标题按当前时间戳生成

**Comment by JohnNiang** [comment]
路径问题确实应该好好处理一下。

**Comment by ruibaby** [comment]
@itomcat666 建议发文章手动定义文章路径。

**Comment by itomcat666** [comment]
@ruibaby 手动定义文章标题也应该校验下标题中是否包含斜杠"/",不然文章没法访问

**Comment by ruibaby** [comment]
@itomcat666 好的，后面我们会对这个问题进行完整的优化。

**Comment by weiwensangsang** [comment]
#350

**Comment by ruibaby** [comment]
这个问题已经被解决了：https://github.com/halo-dev/halo/commit/cd2c3a17b37c2a71d96342fee5ee7ab05eed8d66
