### ISSUE TITLE
期望为 Console 端的用户管理单独提供接口以支持更多筛选条件

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#3290]
### 你当前使用的版本

2.2.0

### 描述一下此特性

<img width="1420" alt="image" src="https://user-images.githubusercontent.com/21301288/218302049-a66b5d1d-b071-4f34-b52e-2aeea5bf5362.png">

如图，目前用户管理仅支持通过关键词筛选（由前端实现），期望支持后端的关键词搜索，以及必要的条件筛选，比如角色。

/area core
/area console
/milestone 2.3.x

**Comment by ruibaby** [comment]
另外，建议将角色信息也聚合返回。

**Comment by JustinLiang522** [comment]
现在api里的V1alpha1UserApiListv1alpha1UserRequest接口没有关键词和角色的属性。是不是要先修改api-client的代码才行？

**Comment by guqing** [comment]
> 现在api里的V1alpha1UserApiListv1alpha1UserRequest接口没有关键词和角色的属性。是不是要先修改api-client的代码才行？

api-client  是根据后端的 api 自动生成的，参考  `localhost:8090/swagger-ui.html`  ，所以此 issue 需要改动到后端的 api 参数然后重新生成 api-client

**Comment by JustinLiang522** [comment]
> > 现在api里的V1alpha1UserApiListv1alpha1UserRequest接口没有关键词和角色的属性。是不是要先修改api-client的代码才行？
> 
> api-client 是根据后端的 api 自动生成的，参考 `localhost:8090/swagger-ui.html` ，所以此 issue 需要改动到后端的 api 参数然后重新生成 api-client

后端api的参数应该在哪里修改呢？以及改动后如何重新生成api-client？

**Comment by ruibaby** [comment]
@JustinLiang522 你可以先提交 Halo 的 PR，Console 这边的改动我可以来做。

**Comment by guqing** [comment]
目前用户管理列表的 api 还是自动生成的，要添加更多参数需要在 [UserEndpoint](https://github.com/halo-dev/halo/blob/26f29b20c705535c3bdecca95d2b57829d3da262/src/main/java/run/halo/app/core/extension/endpoint/UserEndpoint.java#L38) 提供一个列表查询的 endpoint 叫 .GET("/users", ...)
可以参考这个示例：https://github.com/halo-dev/halo/blob/26f29b20c705535c3bdecca95d2b57829d3da262/src/main/java/run/halo/app/core/extension/attachment/endpoint/AttachmentEndpoint.java#L87-L97

**Comment by JustinLiang522** [comment]
> @JustinLiang522 你可以先提交 Halo 的 PR，Console 这边的改动我可以来做。

OK :)

**Comment by JustinLiang522** [comment]
所以除了关键词搜索外，后端需要实现的条件筛选有哪些呢？按照现在前端`UserList`的代码，应该是有状态，角色以及对登陆时间的排序这三个？

**Comment by ruibaby** [comment]
> 所以除了关键词搜索外，后端需要实现的条件筛选有哪些呢？按照现在前端`UserList`的代码，应该是有状态，角色以及对登陆时间的排序这三个？

目前应该仅有角色有用，状态暂时没有用到。排序目前提供创建时间升降序即可，登录时间暂时也没用上。
