### ISSUE TITLE
Demo网站无法点赞

### ISSUE THREAD

**Issue by ZHU-SK** [halo-dev/halo#3298]
### 是什么版本出现了此问题？

2.2.0

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

https://demo.halo.run/
咱们的Demo网站每篇日志都无法点赞呢，希望早些修复啦

**Comment by ruibaby** [comment]
<img width="995" alt="image" src="https://user-images.githubusercontent.com/21301288/218483987-e0d90c08-5a9b-4fa1-8f64-a766da027fef.png">

如果你是指的这个主题，请向 https://github.com/xzhuz/halo-theme-xue 提交 issue。

/kind support

**Comment by ruibaby** [comment]
目前 2.0 的默认主题已经实现了点赞：https://github.com/halo-dev/theme-earth/pull/48

/close
