### ISSUE TITLE
安装markdown插件后无法使用

### ISSUE THREAD

**Issue by xiongtete0519** [halo-dev/halo#3299]
### 是什么版本出现了此问题？

2.0

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker Compose

### 在线站点地址

https://www.codeleader.top/

### 发生了什么？

我安装了两个markdown编辑器插件，但是在新建文章的时候没有出现选择编辑器的选项
![image](https://user-images.githubusercontent.com/66518135/218495730-41a05021-fba5-4642-874e-2ec501a6dca2.png)
![image](https://user-images.githubusercontent.com/66518135/218495883-85eaa6c7-8455-42e0-987d-e0dd0b14b866.png)
![image](https://user-images.githubusercontent.com/66518135/218495996-a6b669d1-f97f-4e16-a11a-8fc8dd72ffa9.png)

**Comment by ruibaby** [comment]
编辑器插件是 2.1 才支持的功能，你需要至少升级到 2.1。

详情看：https://github.com/halo-dev/halo/releases/tag/v2.1.0

/kind support

**Comment by XieLincai** [comment]
我用官网推荐docker compose 配置启动了halo服务，安装markdown 插件也无法使用，报错未找到符合 markdown 格式的编辑器，请检查是否已安装编辑器插件。



services:
  halo:
    image: registry.fit2cloud.com/halo/halo-pro:2.24
    restart: on-failure:3
    depends_on:
      halodb:
        condition: service_healthy
    networks:
      halo_network:
    volumes:
      - ./halo2:/root/.halo2
    ports:
      - "8090:8090"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/actuator/health/readiness"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    environment:
      # JVM 参数，默认为 -Xmx256m -Xms256m，可以根据实际情况做调整，置空表示不添加 JVM 参数
      - JVM_OPTS=-Xmx256m -Xms256m
    command:
      - --spring.r2dbc.url=r2dbc:pool:postgresql://halodb/halo
      - --spring.r2dbc.username=halo
      # PostgreSQL 的密码，请保证与下方 POSTGRES_PASSWORD 的变量值一致。
      - --spring.r2dbc.password=openpostgresql
      - --spring.sql.init.platform=postgresql
      # 外部访问地址，请根据实际需要修改
      - --halo.external-url=http://localhost:8090/
  halodb:
    image: postgres:15.4
    restart: on-failure:3
    networks:
      halo_network:
    volumes:
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_PASSWORD=openpostgresql
      - POSTGRES_USER=halo
      - POSTGRES_DB=halo
      - PGUSER=halo

networks:
  halo_network:
