### ISSUE TITLE
远程访问问题

### ISSUE THREAD

**Issue by lyolve** [halo-dev/halo#330]
您好，想问一下，能否通过NAS开启服务，然后远程访问，有公网ip，如果可以，应该如何操作

**Comment by ruibaby** [comment]
@lyolve NAS 支持 Java 环境或者 Docker 就行。如何操作看文档。

**Comment by JohnNiang** [comment]
有公网 IP 的话，大概率无法使用 80 端口，你只能通过反向代理访问你的  NAS。
