### ISSUE TITLE
halo.run 的域名即将备案，如需访问官网请访问 next.halo.run

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#3306]
https://halo.run 的域名即将进行备案，备案期间将无法通过该域名访问。

如需访问官网，可以访问临时域名：https://next.halo.run

> 我们计划于今晚 12 点（2023-2-15 00:00:00）将进行切换。

此外，其他二级域名不会受到影响：

- https://bbs.halo.run
- https://docs.halo.run

**Comment by jdgjxxchy** [comment]
都打不开了

**Comment by ruibaby** [comment]
> 都打不开了

从昨晚开始被 DDOS，然后被服务商自动阻断了。 :)

**Comment by angleGhost** [comment]
一个开源项目官网也能被DDOS，😂

**Comment by JohnNiang** [comment]
<https://halo.run/> 再次点亮。

/close
