### ISSUE TITLE
切换到系统概览菜单时会出现警告弹窗闪屏问题

### ISSUE THREAD

**Issue by guqing** [halo-dev/halo#3307]
### What is version of Halo has the issue?

2.2.0

### What database are you using?

PostgreSQL

### What is your deployment method?

Docker

### Your site address.

https://guqing.xyz

### What happened?
Chrome 浏览器环境

![Kapture 2023-02-14 at 23 11 13](https://user-images.githubusercontent.com/38999863/218778584-15bb47d6-d6c8-4f11-ae51-41a8ed3c5d0a.gif)

### Additional information

/kind bug
/area console
/milestone 2.3.x

**Comment by ruibaby** [comment]
/triage duplicate

see https://github.com/halo-dev/halo/issues/3225
