### ISSUE TITLE
评论审核，审核通过所有回复 无效；

### ISSUE THREAD

**Issue by wxyShine** [halo-dev/halo#3308]
### 是什么版本出现了此问题？

2.2.0

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

![image](https://user-images.githubusercontent.com/42802152/218895959-85e49ec2-1a66-47f0-91a4-009034bc112f.png)

评论审核，审核通过所有回复 无效；

![image](https://user-images.githubusercontent.com/42802152/218896165-74894f58-b673-4a7b-b8d6-31192bda6f3c.png)
操作成功，刷新之后还是待审核

**Comment by ruibaby** [comment]
这里显示的待审核应该是评论，所以点击 **审核通过所有回复** 是无效的。目前评论和回复是两个模型，所以分开做了审核通过按钮。
