### ISSUE TITLE
nginx将80端口转发到8090字体无法显示

### ISSUE THREAD

**Issue by LuHanUp** [halo-dev/halo#331]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [x] 请求技术支持

以下是我的nginx的配置

    server {
        listen       80;
        server_name  localhost;
		location / {
			proxy_set_header HOST $host;
			proxy_set_header X-Forwarded-Proto $scheme;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_pass http://47.101.210.186:8090/;
		}

        location /staticFiles {
            root   /root/;
            autoindex on;
        }

报错信息为
![image](https://user-images.githubusercontent.com/17198598/66453972-d02c3f00-ea98-11e9-8c7e-bf242507202b.png)

**Comment by ruibaby** [comment]
@LuHanUp servername为什么是localhost呢？

**Comment by LuHanUp** [comment]
@ruibaby 我域名还在备案中

**Comment by ruibaby** [comment]
@LuHanUp 填写你的外网ip试试呢

**Comment by LuHanUp** [comment]
@ruibaby 试过了呢  不行的

**Comment by ruibaby** [comment]
@LuHanUp 查看一下后台博客设置的博客地址是否填写正确

**Comment by LuHanUp** [comment]
@ruibaby 
![image](https://user-images.githubusercontent.com/17198598/66454233-d5d65480-ea99-11e9-983a-587274294002.png)
这样是对的吗？

**Comment by ruibaby** [comment]
@LuHanUp 去掉端口

**Comment by LuHanUp** [comment]
@ruibaby 好啦 谢谢
