### ISSUE TITLE
Ghost 用户在文章列表可被点击，并提示“资源不存在”

### ISSUE THREAD

**Issue by LIlGG** [halo-dev/halo#3317]
### 是什么版本出现了此问题？

release-2.2

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式部署？

Docker Compose

### 发生了什么？

操作步骤：
1. 新建一个用户
2. 使用这个用户发布一篇文章
3. 删除这个用户，文章发布人变为 ghost

![image](https://user-images.githubusercontent.com/31335418/218993633-eb3e2041-6f4e-4aa9-90ba-c3814823d4d0.png)

4. 在文章列表点击 ghost 用户，将会跳转到用户页面，会提示“资源不存在”

![image](https://user-images.githubusercontent.com/31335418/218993849-54b9d029-aeb4-4098-82ca-d7b31f0fac63.png)

/kind bug
/area console

**Comment by JustinLiang522** [comment]
感觉可以前端检测到`contirbutors[0].displayName === '已删除用户'`就不跳转？

**Comment by guqing** [comment]
> 

https://github.com/ghost 感觉这个效果还是不错的

**Comment by ruibaby** [comment]
> 系统默认初始化一个 ghost 用户，用于表示用户已删除。这个时候就可以根据 user.metadata.name 是否等于 ghost 来判断是否为已删除。

赞同。

此外，目前除了文章，还有页面、附件都记录了发布者，这些应该都要处理。

**Comment by JustinLiang522** [comment]
不过要是有用户将名字设为ghost岂不是当删除处理了？

**Comment by JohnNiang** [comment]
> 不过要是有用户将名字设为ghost岂不是当删除处理了？

用户名是全局唯一且无法更改的，但是 displayName 是可以随意更改的。

**Comment by JustinLiang522** [comment]
> > 不过要是有用户将名字设为ghost岂不是当删除处理了？
> 
> 用户名是全局唯一且无法更改的，但是 displayName 是可以随意更改的。

我想的是可能在创建用户的时候就将name设置为ghost

**Comment by JustinLiang522** [comment]
要不就给Contributor增加一个deleted属性，然后把ghost的deleted设置成true，如果前端检测到`contributors[0].deleted === true`就不跳转？ 这样可以避免占用ghost这个用户名
/assign

**Comment by guqing** [comment]
@JohnNiang 我感觉可以添加一个 ghost 用户，这样避免到处处理这个事情，ghost 用户添加后应该可以不需要做其他额外的判断

**Comment by JustinLiang522** [comment]
添加ghost用户还有一个可能要处理的点，就是listUsers的时候要把ghost用户隐藏起来

**Comment by JohnNiang** [comment]
目前我们已经有 anonymous user 了，再加上一个 ghost 后可统一过滤这两个用户。

可参考：<https://github.com/ghost>。

**Comment by ruibaby** [comment]
> 添加ghost用户还有一个可能要处理的点，就是listUsers的时候要把ghost用户隐藏起来

可以参考：https://github.com/halo-dev/console/blob/c8dbd2422c47fddd6811fbf2cad030f7b15a4271/src/modules/system/users/UserList.vue#L76

**Comment by JustinLiang522** [comment]
好的 :)
