### ISSUE TITLE
建议能够缓存发布文章时上次使用的模板

### ISSUE THREAD

**Issue by chengfeiyue** [halo-dev/halo#3329]
### 你当前使用的版本

2.2.1

### 描述一下此特性

1、默认模板总是在第一位，每次发布文章时都要选一下自己定义的模板，批量发布文章场景较多，每次选择就很烦。希望能够加个标记字段，上次写文章用的那模板，下次发布文章优先使用那个模板
<img width="737" alt="image" src="https://user-images.githubusercontent.com/49852751/219338727-30618f17-8638-4141-bf69-8f18df008cae.png">

**Comment by ruibaby** [comment]
/kind improvement
/area console

可以考虑，但目前可能只能实现在浏览器端缓存。

**Comment by sunerpy** [comment]
> ### 你当前使用的版本
> 2.2.1
> 
> ### 描述一下此特性
> 1、默认模板总是在第一位，每次发布文章时都要选一下自己定义的模板，批量发布文章场景较多，每次选择就很烦。希望能够加个标记字段，上次写文章用的那模板，下次发布文章优先使用那个模板 <img alt="image" width="737" src="https://user-images.githubusercontent.com/49852751/219338727-30618f17-8638-4141-bf69-8f18df008cae.png">
> 
> ### 附加信息
> _No response_

你好，请问下使用的哪款主题呢，我的默认主题找不到添加模板的地方

**Comment by chengfeiyue** [comment]
我们自己开发的主题。然后再主题里面添加了自己的渲染模板。但是在发布文章时候，默认放在了默认模板后面

**Comment by ruibaby** [comment]
@chengfeiyue 我尝试实现了一下，感觉这可能需要考虑使用场景，如果用户很少使用到自定义模板，这可能会是一个困扰。

所以我的建议是，如果你们的场景是知识库文章详情模板用的比较多，那么直接将他设置为默认模板（post.html）即可，其他模板再单独设置。

**Comment by chengfeiyue** [comment]
这边默认模板post.html 也有使用。自定义模板category-post.html也在使用。使用比率大约3比7吧。后续如果客户要求必须优先使用自定义模板的话。我这边就将两个模板内容互换下

**Comment by guicaiyue** [comment]
@ruibaby 请问有自定义渲染模板的主题例子嘛，还有halo的文档的algolia搜索中午搜不出东西。文档没找到相关例子

**Comment by ruibaby** [comment]
> @ruibaby 请问有自定义渲染模板的主题例子嘛，还有halo的文档的algolia搜索中午搜不出东西。文档没找到相关例子

https://docs.halo.run/developer-guide/theme/template-route-mapping#custom-templates
