### ISSUE TITLE
更新外部地址后文章中的附件库图片仍使用旧地址

### ISSUE THREAD

**Issue by wan92hen** [halo-dev/halo#3331]
### 是什么版本出现了此问题？

2.2.1

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式部署？

Docker

#### 现状
1. 使用外部地址 `http://domain1.com` 运行 Halo；
2. 附件中上传图片，新建一篇文章添加该图片，查看文章中图片链接为 `http://domain1.com/upload/xxx.png`；
3. 修改外部地址为 `http://domain2.com` 重启 Halo；
4. 再次查看文章中的图片链接仍然是 `http://domain1.com/upload/xxx.png`，如果原域名停止解析将导致图片不显示。

#### 期望

修改外部地址后，文章中的图片链接会同步变更为 `http://domain2.com` 下的链接。

#### 建议方案

目前想到了两种处理方案，个人倾向于方案二。

1. 修改外部地址重启后，系统自动将所有文章中的图片链接进行修改；
2. 插入附件库中的附件时，使用不包含 server 的 PATH `/upload/xxx.png` 进行插入。

**Comment by JohnNiang** [comment]
/kind improvement

我这里想到另外一种场景：

#### 前提条件

用户一开始使用的是 OSS（域名：oss.domain.com）作为附件存储

#### 方案评价

- 方案 1
    这个操作不建议在系统初始化的时候进行。
- 方案 2
    对于存储在 OSS 的附件，无法直接使用 path 进行插入。即使全部插入，又会回到更改域名后如何解决文章内附件引用的问题。

#### 我的方案

开发替换文章和页面内容链接的插件。这样不仅仅局限于附件链接的替换。

**Comment by wan92hen** [comment]
> * 方案 2
>   对于存储在 OSS 的附件，无法直接使用 path 进行插入。即使全部插入，又会回到更改域名后如何解决文章内附件引用的问题。

这里可以只针对 local 存储中的附件做这样的处理吧。如果还要在引入额外的插件来做这件事情，稍显繁琐了些。

**Comment by ruibaby** [comment]
> 插入附件库中的附件时，使用不包含 server 的 PATH /upload/xxx.png 进行插入。

现在默认为这种方案。

/close
