### ISSUE TITLE
在登录认证上，获取当前用户getCurrentUser拿数据库所有用户的第一个，感觉不妥

### ISSUE THREAD

**Issue by hardenCN** [halo-dev/halo#334]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [x] 添加新的特性或者功能
- [ ] 请求技术支持

最近在为这个博客加个多用户功能
在登录认证上，获取当前用户(run.halo.app.service.impl.UserServiceImpl.getCurrentUser())方法中，直接拿数据库所有用户的第一个，感觉不妥，应该是从SecurityContext中拿吧。
````java
public Optional<User> getCurrentUser() {
        // 从数据库获得所有用户
        List<User> users = listAll();
        if (CollectionUtils.isEmpty(users)) {
            // Return empty user
            return Optional.empty();
        }
        // Return the first user 
        //这里直接拿第一个用户，我觉得是不是应该从SecurityContext中拿好一些
        return Optional.of(users.get(0));
    }
````

**Comment by JohnNiang** [comment]
你可以考虑自己实现 UserService 接口哦

**Comment by JohnNiang** [comment]
由于一开始我们就没有打算开发多用户的功能，所以查询用户信息就是这样的逻辑。

**Comment by JohnNiang** [comment]
如果你要做多用户登录功能的话，这里可以考虑用 SecurityContext 获取当前用户信息。

**Comment by cowboyzhangkai** [comment]
@hardenCN 你多用户登录做的怎么样了？
