### ISSUE TITLE
可否考慮加入繁體中文的介面

### ISSUE THREAD

**Issue by den13501** [halo-dev/halo#3346]
### 你当前使用的版本

2.2.1

### 描述一下此特性

無意間接觸到halo，對於這套整合前後端，省去hugo, hexo等需要命令才可發布文章的高學習成本的一體式解決方案實在太喜歡了，希望官方可以加入繁中的支持，謝謝🙏

**Comment by ruibaby** [comment]
感谢支持，我们会考虑在 2.4.0 首先支持 Console 端的 i18n。

/area console
/milestone 2.4.x
/kind feature

**Comment by ruibaby** [comment]
届时我们可能会先提供英语和简体中文的语言包，繁体中文可能就会靠社区来支持啦。

有兴趣可以来参与贡献。

**Comment by den13501** [comment]
> 届时我们可能会先提供英语和简体中文的语言包，繁体中文可能就会靠社区来支持啦。
> 
> 有兴趣可以来参与贡献。

沒問題，我很樂意參與繁體語系的支援，感謝!

**Comment by ruibaby** [comment]
/reopen

这个特性还没实现，可以先保留这个 issues

**Comment by den13501** [comment]
感謝大大們的努力，我會儘快提出PR

**Comment by den13501** [comment]
已PR，請再看看是否有錯誤要修正，感謝
https://github.com/halo-dev/halo/pull/3672

**Comment by WSMI052** [comment]
想搭個版碰運氣問問看
在後台確實已經支援繁體中文(部分)
想問下在主題方面如果需要顯示繁體中文，必須依照該主題的代碼決定對嗎?

謝謝 @den13501 @JohnNiang

**Comment by JohnNiang** [comment]
Hi @WSMI052 , please refer to <https://github.com/halo-dev/docs/issues/418>.

**Comment by WSMI052** [comment]
> Hi [@WSMI052](https://github.com/WSMI052) , please refer to [halo-dev/docs#418](https://github.com/halo-dev/docs/issues/418).

@JohnNiang  感謝您的回答 🙇‍♂️
目前理解是建立i18n資料夾與properties來辦到主題多語言
如果網站支援簡體中文也支援繁體中文，想請教該區別properties文件？
謝謝

**Comment by JohnNiang** [comment]
Hi @WSMI052 , 请参考 <https://github.com/halo-dev/theme-earth/pull/214>。
