### ISSUE TITLE
后台用户显示错误

### ISSUE THREAD

**Issue by Steven-WZH** [halo-dev/halo#3349]
### 是什么版本出现了此问题？

2.2.1

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

![image](https://user-images.githubusercontent.com/113268133/220075834-129993f7-4b6c-45ec-a845-21faa89743b3.png)
![image](https://user-images.githubusercontent.com/113268133/220075869-9f5533ee-6eb6-41f4-8f06-653b670175be.png)

**Comment by ruibaby** [comment]
这是因为系统中包含了一些保留用户，不会在用户管理显示，但统计数量可能并未排除掉保留用户。

/kind improvement
/area core

**Comment by guqing** [comment]
目前不显示的用户是在 console 端过滤的，但后端感知不到，我建议是通过在 user labels 中添加标识，以用于这些场景下的数据过滤，否则只能通过写死 username 的方式不是很好，后续可能还有其他需要隐藏的用户。
@JohnNiang  @ruibaby

**Comment by JustinLiang522** [comment]
> 目前不显示的用户是在 console 端过滤的，但后端感知不到，我建议是通过在 user labels 中添加标识，以用于这些场景下的数据过滤，否则只能通过写死 username 的方式不是很好，后续可能还有其他需要隐藏的用户。 @JohnNiang @ruibaby

想问下这个user labels具体指的是什么？

**Comment by ruibaby** [comment]
> 目前不显示的用户是在 console 端过滤的，但后端感知不到，我建议是通过在 user labels 中添加标识，以用于这些场景下的数据过滤，否则只能通过写死 username 的方式不是很好，后续可能还有其他需要隐藏的用户。 @JohnNiang @ruibaby

Agree

> 想问下这个user labels具体指的是什么？

@JustinLiang522 模型的 metadata.labels，可以方便检索。
