### ISSUE TITLE
1.1.1 版本vno主题无法使用

### ISSUE THREAD

**Issue by Wonderful99668** [halo-dev/halo#335]
**我确定我已经查看了:** 

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请** 

- [x] BUG 反馈

1. vno主题的博客内容打不开
```500
Internal Server Error.
Request processing failed; nested exception is freemarker.core.InvalidReferenceException: The following has evaluated to null or missing: ==> options.subtitle [in template "themes/onevcat_vno/_includes/side-panel.ftl" at line 14, column 70]
```

2. vno博客的预览界面也报出相同错误

**Comment by ruibaby** [comment]
@Wonderful99668 稍后修复

**Comment by ruibaby** [comment]
已修复，更新主题即可。

**Comment by Wonderful99668** [comment]
还有一些其他问题，仍然无法使用:
```Request processing failed; nested exception is freemarker.core.InvalidReferenceException: The following has evaluated to null or missing: ==> options.welcome_message [in template "themes/onevcat_vno/_includes/side-panel.ftl" at line 21, column 55] ```

**Comment by ruibaby** [comment]
@Wonderful99668 再更新看看呢

**Comment by Wonderful99668** [comment]
谢谢快速的修复，已经可使用。
