### ISSUE TITLE
后台添加文章XSS，上传头像处可以上传任意文件

### ISSUE THREAD

**Issue by T-pod** [halo-dev/halo#336]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持
在后台添加博客文章时，代码中没有对插入的内容进行过滤和限制，可以插入XSS语句，前台用户访问便可以触发XSS，存在安全风险。
![image](https://user-images.githubusercontent.com/42511919/66836824-a1303480-ef94-11e9-80a5-d5fb186b566c.png)
![image](https://user-images.githubusercontent.com/42511919/66836909-c02ec680-ef94-11e9-989a-7320f597eb91.png)
在后台上传头像时，抓取上传文件的数据包，修改文件后缀，后端代码（halo/blob/master/src/main/java/run/halo/app/service/impl/AttachmentServiceImpl.java）没有限制，可以上传任意后缀的文件，导致存在安全风险。
![image](https://user-images.githubusercontent.com/42511919/66837891-57484e00-ef96-11e9-9f64-f2466554f272.png)
![image](https://user-images.githubusercontent.com/42511919/66837210-33d0d380-ef95-11e9-8431-fd3c1ab0859c.png)

**Comment by ruibaby** [comment]
@T-pod 感谢你的反馈，我们会进一步修复提出的问题。
