### ISSUE TITLE
文章筛选使用作者筛选时，输入作者名称输出的作者有的头像不显示

### ISSUE THREAD

**Issue by lixuejun725** [halo-dev/halo#3361]
### What is version of Halo has the issue?

2.2.1

### What database are you using?

MySQL 5.7

### What is your deployment method?

Docker

### What happened?

文章筛选使用作者筛选时，输入作者名称输出的作者有的头像不显示
![image](https://user-images.githubusercontent.com/38548829/220505206-7ea5d3cb-0144-47b1-b506-4af56ab4af49.png)

**Comment by ruibaby** [comment]
从截图来看是正常的，你的意思是本来有头像然后搜索之后没有吗？

/triage needs-information

**Comment by lixuejun725** [comment]
截图中，李艳秋，是有头像的，但是我搜索的时候，李艳秋的头像就没有了
