### ISSUE TITLE
新建分类报错

### ISSUE THREAD

**Issue by lixuejun725** [halo-dev/halo#3365]
### What is version of Halo has the issue?

2.2.1

### What database are you using?

MySQL 5.7

### What is your deployment method?

Docker

### What happened?

新建分类报错，保存的时候报错
![image](https://user-images.githubusercontent.com/38548829/220539210-53dc6b94-624e-4017-adbd-06d471fbe19e.png)

**Comment by JohnNiang** [comment]
/triage needs-information

建议提供一下近期的日志以帮助我们快速定位问题。

**Comment by ruibaby** [comment]
如果没有后续动态，我将关闭此 issue，如果有有后续问题可以新建 issue 或者 reopen。

/close
