### ISSUE TITLE
头部随机图

### ISSUE THREAD

**Issue by yikexiaoyao** [halo-dev/halo#3367]
### 是什么版本出现了此问题？

1.6.1

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Fat Jar

### 在线站点地址

https://www.tingyuxuan.tk/

### 发生了什么？

头部图片是作业题目

### 附加信息

![image](https://user-images.githubusercontent.com/36374114/220614566-2848ce01-2c61-42fb-8b32-8a23a6666e7e.png)

**Comment by ruibaby** [comment]
这个问题与 Halo 无关，你可以向 https://github.com/LIlGG/halo-theme-sakura 提交 issue。

/kind support
/close
