### ISSUE TITLE
文章分类统计的文章数量不对

### ISSUE THREAD

**Issue by lixuejun725** [halo-dev/halo#3369]
### What is version of Halo has the issue?

2.2.1

### What database are you using?

MySQL 5.7

### What is your deployment method?

Docker

### What happened?

在文章分类这里统计其下的文章数量不对，原本这个分类下面有一篇文章，但是统计是0个
![image](https://user-images.githubusercontent.com/38548829/220811221-14123165-310d-4d32-ac63-67506435d62a.png)

**Comment by guqing** [comment]
分类下的文章数量统计有一分钟延迟，如果关联了分类超过一分钟还没有统计出来可以看一下有没有错误日志，并提供一下复现此问题的步骤，我试了一下没有复现
/triage needs-information

**Comment by lixuejun725** [comment]
就是正常新建一个分类，然后，新建一篇文章，文章在这个分类下是有的，但是没有统计出来，我们有篇文章，2月7号就创建了，但是至今，相关分类下面还是没有这个统计数

**Comment by guqing** [comment]
你可以在新建一篇文章(可以不发布)关联这个分类等待一分钟看一下数量有没有变，来确定一下是否是那片文章有什么特殊的原因引起的，分类会每隔一分钟统计一次文章数量，除非一直都查询不到这篇文章才会统计不上。

并再次确认一下那篇文章满足以下条件才会被计数：
1. 文章没有被放到回收站
2. metadata.deletionTimestamp 为 null
3. 关联了这个分类

**Comment by guqing** [comment]
我测试了以下几种情况的统计：
1. 文章R 关联了分类  A 且状态为草稿，可见性为公开
2. 文章T 关联了分类 A 且状态为草稿，可见性为私有
3. 文章U 关联了分类 A 且状态为发布，可见性为公开
4. 文章P 关联了分类 A 且状态为发布，可见性为私有
均有正确计数

**Comment by lixuejun725** [comment]
好的，我试试

**Comment by chengfeiyue** [comment]
我这边也测试了下，一分钟后分类文章数量统计是正确的@lixuejun725
