### ISSUE TITLE
系统页脚设置处存在跨站脚本攻击(xss)

### ISSUE THREAD

**Issue by LiGNG** [halo-dev/halo#337]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

博客常规设置模块里添加页脚信息时，代码中没有对插入的内容进行过滤和限制，可以插入恶意脚本，例如`a"><img src=1 onerror=alert(document.cookie)>`，访问博客首页即便可以触发XSS，存在安全风险。
![image](https://user-images.githubusercontent.com/22877189/66848611-f9246680-efa7-11e9-80ad-82550c16df27.png)
访问首页触发XSS，如图所示
![image](https://user-images.githubusercontent.com/22877189/66848728-2c66f580-efa8-11e9-89ee-aaf204a85aef.png)
修复建议：针对页面输出做html转义处理，防止跨站脚本攻击。

**Comment by JohnNiang** [comment]
这个漏洞确实存在，不过该内容又博主自行添加，攻击者是没办法修改该内容的。
