### ISSUE TITLE
用户创建的体验问题咨询

### ISSUE THREAD

**Issue by wml3** [halo-dev/halo#3371]
### Your current Halo version

V2

### Describe this feature

![image](https://user-images.githubusercontent.com/49503874/220828758-9962daba-777a-43e3-b411-c240dbb974fe.png)
目前在创建后台用户时，需要多个步骤：
1、创建用户，填写用户信息，提交；
2、编辑用户，配置密码，提交；
3、编辑用户，配置角色，提交；
这几个步骤略显繁琐，体验上有没有可能优化

**Comment by ruibaby** [comment]
/triage duplicate 

see https://github.com/halo-dev/halo/issues/2852
