### ISSUE TITLE
希望分类 finder 提供根据名称获取树路径的方法

### ISSUE THREAD

**Issue by chengfeiyue** [halo-dev/halo#3374]
### What is version of Halo has the issue?

2.21

### What database are you using?

PostgreSQL

### What is your deployment method?

Docker Compose

### What happened?

1、要搭建一个知识库，分类作为知识库文件树，
<img width="1180" alt="image" src="https://user-images.githubusercontent.com/49852751/220862770-035bf759-a2f8-4414-87f4-6037b44c44f1.png">
2、每个树顶级分类是一个大的门类，是这个门类的入口
<img width="1346" alt="image" src="https://user-images.githubusercontent.com/49852751/220862980-7f8c4208-8fbd-4859-bc9d-7c00c7b34af0.png">
3、因为传参问题，绕了一大圈，存在刷新页面，左侧文件树结构丢失的问题。

<img width="848" alt="image" src="https://user-images.githubusercontent.com/49852751/220863576-8decca17-5a78-4ca3-a931-72f45a08514b.png">
5、只要listAsTree（）方法记录了他的所有子分类字段，就能解决刷新页面丢失的问题。原有的listAsTree()返回的children属性，无法在前端递归遍历。

**Comment by guqing** [comment]
listAsTree 如果对每个 node 添加一个记录树所在路径的名称集合也需要去遍历树，依然无法仅通过模板引擎就实现这样的功能吧，比如：
```
├── A
│   ├── A-1(pathTokens=[A, A-1])
│   │   ├── A-1-1(pathTokens=[A, A-1, A-1-1])
│   │   └── A-1-2(pathTokens=[A, A-1, A-1-2])
```
其中 pathTokens 即为路径元素，要查找 A-1-1 的一级父类也需要遍历树在其中找到 A-1-1 在取其 pathTokens 的第一个，但既然都已经遍历树了，其实本身就知道了路径也就知道顶级分类是谁。
通过 javascript 方法去实现可能更好

**Comment by chengfeiyue** [comment]
是这种格式：
├── A（childrenCategoryNames=[ A-1,A-1-1,A-1-2]）
│   ├── A-1(childrenCategoryNames=[-1-1,A-1-2])
│   │   ├── A-1-1(childrenCategoryNames=[A-1-2])
│   │   └── A-1-2(pathTokens=[])

**Comment by guqing** [comment]
会考虑提供一个根据名称获取树路径的方法返回结果可能是一个 List<CategoryVo>，为有序集合元素第一项表示顶层分类，最后一行为传入名称的分类信息，中间为所经路径的分类信息

**Comment by chengfeiyue** [comment]
问一下这个接口大概什么时间能给出那？

**Comment by chengfeiyue** [comment]
问一下，这个方法本月有规划吗？

**Comment by chengfeiyue** [comment]
这个方法本月有规划吗？

**Comment by ruibaby** [comment]
@chengfeiyue 

> 因为传参问题，绕了一大圈，存在刷新页面，左侧文件树结构丢失的问题。

首先，我们并不知道你主题的实现方式，所以大家并不清楚问题到底在哪里。如果可以，建议提供关键的代码。

然后我根据你截图中的需求，简单实现了一个主题（也是为了验证这种结构是否可行），可以检查一下是否符合你的需求。

仓库：https://github.com/ruibaby/theme-doc

演示：

https://github.com/halo-dev/halo/assets/21301288/7829cbb5-c835-4763-be4e-85661797b1c8

**Comment by chengfeiyue** [comment]
当时好像是缺少分类跳转文章的路由。所以才采取折中的方式来做的。只要修改在分类的listAsTree方法记录下分类的路径就行了。比如下面二级分类A-1,那么它的分类集合就是[A, A-1])
├── A
│   ├── A-1(pathTokens=[A, A-1])
│   │   ├── A-1-1(pathTokens=[A, A-1, A-1-1])
│   │   └── A-1-2(pathTokens=[A, A-1, A-1-2])

**Comment by chengfeiyue** [comment]
主题github地址：
https://github.com/east-district-f2c-shangqi/halo-theme-shangqi
<img width="1439" alt="image" src="https://github.com/halo-dev/halo/assets/49852751/be086021-50dd-4767-9b87-9edd0d2e31fe">
<img width="1439" alt="image" src="https://github.com/halo-dev/halo/assets/49852751/6d21f605-7d83-4e46-a920-85dd72213f71">

**Comment by ruibaby** [comment]
@chengfeiyue 

https://github.com/halo-dev/halo/issues/3374#issuecomment-1549727583 这里提供的实现方式有尝试或者下载主题看过吗？

**Comment by chengfeiyue** [comment]
不行的，演示的主题是在同一个页面列举出全部分类和分类下的文章。我的问题点在于要从某个（有多个分类树）一级分类进入详情页，这里展示的分类不是全部，是单个分类树，并且刷新页面左侧的分类树不丢失。案例不涉及刷新页面只显示当前文章所属的单个分类树。

**Comment by pandatools** [comment]
可以自己写个finder插件来实现
