### ISSUE TITLE
文章批量删除到回收站不生效

### ISSUE THREAD

**Issue by guqing** [halo-dev/halo#3375]
### 是什么版本出现了此问题？

2.2.1

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

文章列表的批量选中删除到回收站没有效果
<img width="445" alt="image" src="https://user-images.githubusercontent.com/38999863/220875017-585441fb-6ddd-4fc2-a41a-7ceb3b03ec9f.png">

### 附加信息

/kind bug
/area console
/milestone 2.3.x
/assign @ruibaby

**Comment by ruibaby** [comment]
实际上是 https://github.com/halo-dev/console/pull/879 中的修改导致的，并且已经修复。

/close
