### ISSUE TITLE
标签数量统计有误

### ISSUE THREAD

**Issue by jdgjxxchy** [halo-dev/halo#3378]
### 是什么版本出现了此问题？

2.2.1

### 使用的什么数据库？

Mysql 8.x

### 使用的哪种方式部署？

Docker

### 在线站点地址

https://blog.yukinashi.com/

### 发生了什么？

标签数量统计有问题
<img width="339" alt="image" src="https://user-images.githubusercontent.com/44478385/220945898-721567c3-7790-4bae-913c-f7c9a0f1b79d.png">

**Comment by guqing** [comment]
/triage duplicate
see https://github.com/halo-dev/halo/issues/3311
