### ISSUE TITLE
个人资料处存在XSS

### ISSUE THREAD

**Issue by wind226** [halo-dev/halo#338]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [ x ] [Halo 使用文档](https://halo.run/docs)
- [ x ] [Halo 论坛](https://bbs.halo.run)
- [ x ] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [ x ] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ x ] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持
修改个人资料时，在个人说明处填写11111"><img src=1 onerror=alert('xss')>，在主页处触发xss：

**Comment by JohnNiang** [comment]
虽然存在这样的漏洞，不过这些内容都有博主自行填写，攻击者是没有机会触发 xss 的。有关公开评论部分所触发的 xss 已经处理。
