### ISSUE TITLE
新建文章分类，出现服务器内部错误

### ISSUE THREAD

**Issue by lixuejun725** [halo-dev/halo#3384]
### What is version of Halo has the issue?

2.2.1

### What database are you using?

MySQL 5.7

### What is your deployment method?

Docker

### What happened?

新建文章分类，出现服务器内部错误
![image](https://user-images.githubusercontent.com/38548829/221104265-a858730e-c023-4016-867a-7fd465fd3520.png)

**Comment by guqing** [comment]
建议提供一下日志
/triage needs-information

**Comment by ruibaby** [comment]
如果没有后续动态，我将关闭此 issue，如果有有后续问题可以新建 issue 或者 reopen。

/close
