### ISSUE TITLE
无法打开评论窗口

### ISSUE THREAD

**Issue by howlshit** [halo-dev/halo#3387]
### 是什么版本出现了此问题？

2.2.0

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

按官网原封不动的docker命令部署，启动项目之后，评论模块点击无反应，没有弹出评论窗口

![image](https://user-images.githubusercontent.com/42687631/221122589-516f8a34-2016-4f36-9e41-92a9708d2759.png)

### 相关日志输出

```shell
./halo/logs/halo.log 点击时无日志输出
```

**Comment by JohnNiang** [comment]
你可能需要在 https://github.com/halo-sigs/awesome-halo 找到评论插件并安装。

/kind support

**Comment by howlshit** [comment]
> 你可能需要在 https://github.com/halo-sigs/awesome-halo 找到评论插件并安装。
> 
> /kind support

thinks
