### ISSUE TITLE
讨论：将 Console 项目合并到主仓库

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#3393]
### 你当前使用的版本

main branch

### 描述一下此特性

目前 Halo 的基本组成为 Halo 后端 + Console + 主题，最早将 Console（原 halo-admin）与后端分离的时候就是单独托管到另外一个库，但目前带来以下问题：

1. PR 和 Milestone 管理分散，无法仅在 Halo 的仓库进行管理，可能造成两边状态不同步。
    - https://github.com/halo-dev/console/milestones
    - https://github.com/halo-dev/halo/milestones
2. 构建流程和开发环境运行可能有点繁琐。

如果合并为一个仓库，会带来以下好处：

1. PR 和 Milestone 可以包括后端和 Console 端，发布版本的时候更加方便。
2. 可以统一使用 Gradle 脚本来构建或者运行 Console，也可以减少 CI 构建的流程，Console 的构建产物可以直接输出到 `src/main/resources/console`。
3. 可以让维护人员更加集中维护一个仓库。
4. 如果一个 PR 同时包含后端和 Console 的修改，可以仅用一个 PR 完成，而不是向两个仓库分别提交。
5. 和插件的项目结构一致，参考：https://github.com/halo-sigs/plugin-links

/area core
/area console
/kind improvement
/cc @halo-dev/sig-halo 
/cc @halo-dev/sig-halo-console

**Comment by ruibaby** [comment]
可以交流一下可能会带来什么样的问题，我先自行合并之后测试一下。

**Comment by maninhill** [comment]
我觉得插件和主题适合独立出去，对用户来说，这部分每个人需求和部署不太一样。但前后端确实应该合并在一起，每个用户都是一样的部署，这个阶段合并在一起利大于弊。

**Comment by JohnNiang** [comment]
IMO

如果 Console 不独立发版和不独立部署的话，分仓库的方式可能不那么和是。反而增加了维护成本。

但是，我们是否要考虑 Console 在未来独立发版和独立部署的可能性？

**Comment by ruibaby** [comment]
> 但是，我们是否要考虑 Console 在未来独立发版和独立部署的可能性？

我个人认为这样的需求很小，主要想不到这样的部署方式可以带来什么好处。另外，如果要支持独立发版，我们的维护成本也可能提高。

**Comment by ruibaby** [comment]
简单尝试了一下，基本对 Console 现有的流程不会有影响。

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/21301288/221342646-eff73371-6c3f-4ea7-964d-73be62feb419.png">

Gradle 的 Node 集成插件使用了 <https://github.com/node-gradle/gradle-node-plugin>，目前也已经内置支持了 pnpm。

另外，GItHub 的 Actions 需要做修改。

**Comment by JohnNiang** [comment]
> 如果一个 PR 同时包含后端和 Console 的修改，可以仅用一个 PR 完成，而不是向两个仓库分别提交。

真实的场景：很少有人能够同时支持前端和后端同时修改。仅用一个 PR 完成可能不太现实。

**Comment by ruibaby** [comment]
> > 如果一个 PR 同时包含后端和 Console 的修改，可以仅用一个 PR 完成，而不是向两个仓库分别提交。
> 
> 真实的场景：很少有人能够同时支持前端和后端同时修改。仅用一个 PR 完成可能不太现实。

那这种情况可能得分别由不同的人提交不同的 PR，或者不同的人在同一个 PR 进行，不过目前也有几次社区贡献者同时提交了后端和前端的 PR 来完成一个功能。

**Comment by ruibaby** [comment]
我将在 2.3.0 发布之后开始迁移。

**Comment by ruibaby** [comment]
同时需要修改一下 GitHub Action。

/assign @JohnNiang

**Comment by 7757** [comment]
> @7757 看 2.4.0-SNAPSHOT 的文档即可：https://docs.halo.run/2.4.0-SNAPSHOT/developer-guide/core/run
> 
> 目前因为 2.4.0 没有发布版本，所以文档最新的内容还是针对 2.3.0。
> 
> halo-dev/console 仅维护旧版本。

假如现在依旧使用2.3.2 是不是后期的2.4之后的PR也不会影响2.3之前console的独立部署并且我可以把2.4之后console里面的pr合并到自己fork的2.3console自行维护。
有点踌躇现在是拉2.3的还是最新的halo

**Comment by JohnNiang** [comment]
@7757 

2.4 的 commit 无法直接应用到 2.3。
这就是自己维护的成本。
