### ISSUE TITLE
现在不支持Latex公式吗？

### ISSUE THREAD

**Issue by xiongtete0519** [halo-dev/halo#3395]
### 是什么版本出现了此问题？

2.2.0

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker Compose

### 在线站点地址

https://codeleader.top/

### 发生了什么？

latex数学公式好像不支持，没有效果
![image](https://user-images.githubusercontent.com/66518135/221356224-9f619198-6837-4bbd-9fb6-f3e233996aa5.png)

![image](https://user-images.githubusercontent.com/66518135/221356379-85daf56f-0904-49a7-9c3a-ca9cf2cce013.png)

**Comment by xiongtete0519** [comment]
Latex公式用处太多了，我的好多博客都有公式出现，希望早日支持

**Comment by xiongtete0519** [comment]
![image](https://user-images.githubusercontent.com/66518135/236365210-08b4e971-3327-4728-9e2e-dfb277fc5f87.png)

**Comment by ruibaby** [comment]
KaTeX 插件的首个版本已经发布，可以将 Halo 升级到 2.7，然后安装此插件进行体验。

- https://github.com/halo-sigs/plugin-katex/releases/tag/v1.0.0
- https://halo.run/store/apps/app-ISCsX

/close
