### ISSUE TITLE
数据迁移

### ISSUE THREAD

**Issue by xiongtete0519** [halo-dev/halo#3396]
### What is version of Halo has the issue?

2.2.0

### What database are you using?

MySQL 8.x

### What is your deployment method?

Docker Compose

### Your site address.

https://codeleader.top/

### What happened?

我看了下，mysql数据库只有一张表，如果服务器到期之后需要做数据迁移怎么办？
我们的博客数据都是存在哪里的？
![image](https://user-images.githubusercontent.com/66518135/221356731-23d6b68b-601f-4b5f-8b78-0adfbf4e2bc0.png)

**Comment by guqing** [comment]
/kind support
备份问题参考：https://github.com/halo-dev/halo/issues/3274#issuecomment-1425067182
关于为什么表只有一张参考：https://github.com/halo-dev/rfcs/tree/main/extension
相关 issues：
- https://github.com/halo-dev/halo/issues/3274
- https://github.com/halo-dev/docs/issues/187

**Comment by JohnNiang** [comment]
我将关闭此 Issue。如果有任何问题，可随时打开 Issue。

/close
