### ISSUE TITLE
Logo头像引用错误

### ISSUE THREAD

**Issue by Alplexchur** [halo-dev/halo#3398]
### 是什么版本出现了此问题？

2.2.1

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker Compose

### 在线站点地址

https://www.alplexchur.icu/

### 发生了什么？

首次上传的logo是"猫猫.jpg"的，后来在本地重命名为"Logo.jpg"上传，并在附件中删除原有中文logo，更换logo后首页以及文章内部的logo头像引用的仍然是原来已经删除的logo。多次更换英文logo后引用的还是"猫猫.jpg"，猜测可能是中文问题...？

### 附加信息

![image](https://user-images.githubusercontent.com/110937548/221359174-5a73b5a8-5aef-4e0f-8ecb-948becce38e4.png)
![image](https://user-images.githubusercontent.com/110937548/221359627-39699d36-af95-4a74-bb4f-5b44a15285c3.png)

**Comment by ruibaby** [comment]
<img width="1357" alt="image" src="https://user-images.githubusercontent.com/21301288/221362655-413accc5-e7bb-452b-86e5-5a09a1287495.png">

我这边看似乎没有问题，你可以检查一下是否是浏览器缓存导致的。

/kind support

**Comment by Alplexchur** [comment]
www不是左上角的
是这个啦：)
![image](https://user-images.githubusercontent.com/110937548/221363780-1216bf26-2b6b-4e98-9deb-eee8322ee712.png)
之前尝试过清理浏览器缓存和cookie，也换edge浏览器看了下，还是引用的删除文件

**Comment by guqing** [comment]
> www不是左上角的 是这个啦：) 之前尝试过清理浏览器缓存和cookie，也换edge浏览器看了下，还是引用的删除文件 

我这里看一下首页显示正常了
<img width="481" alt="image" src="https://user-images.githubusercontent.com/38999863/221364021-d3b76666-1363-4aba-b971-86b1156199db.png">
<img width="846" alt="image" src="https://user-images.githubusercontent.com/38999863/221364031-36d64a2f-49e8-427c-84e1-ca409d58e9fe.png">
但文章页那里的不正确
<img width="827" alt="image" src="https://user-images.githubusercontent.com/38999863/221364183-56deabc3-c60c-474d-a6b4-e96d8d97c1f7.png">

**Comment by JohnNiang** [comment]
这个你可能得去设置当前用户的头像。

**Comment by Alplexchur** [comment]
已解决！在当前用户设置完头像后成功显示，感谢！

**Comment by guqing** [comment]
> 这个你可能得去设置当前用户的头像。

经确认这里使用的是用户头像，可能确实是这个原因导致
https://github.com/LIlGG/halo-theme-sakura/blob/0537be2e1aca5172ddafdc7916f034e6399a11d9/templates/post.html#L40
