### ISSUE TITLE
菜单选择打开方式为“新窗口打开”功能无效

### ISSUE THREAD

**Issue by jiewenhuang** [halo-dev/halo#3401]
### 是什么版本出现了此问题？

2.2.1

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式部署？

Docker Compose

### 在线站点地址

none

### 发生了什么？

菜单选择打开方式为“新窗口打开”功能无效
<img width="773" alt="image" src="https://user-images.githubusercontent.com/68629578/221404780-de0623b1-6ea5-48df-8a1f-f6c4d82bea19.png">
不管选哪个都是只在当前窗口打开

**Comment by ruibaby** [comment]
/kind improvement

这应该是 2.1 的时候加的字段，可能主题还没有适配。

**Comment by ruibaby** [comment]
之前添加这个字段的时候忘了修改文档，现在已经补充，可以先参考：https://github.com/halo-dev/docs/pull/191/files#diff-c60bee281468e65d4891e5b320c2d9c91df09a53c752acd53e05978eb8d44f72

**Comment by jiewenhuang** [comment]
> 之前添加这个字段的时候忘了修改文档，现在已经补充，可以先参考：https://github.com/halo-dev/docs/pull/191/files#diff-c60bee281468e65d4891e5b320c2d9c91df09a53c752acd53e05978eb8d44f72

好的，感谢

**Comment by ruibaby** [comment]
目前文档已经补充，默认主题也已经支持。

- https://github.com/halo-dev/theme-earth/pull/56
- https://docs.halo.run/developer-guide/theme/finder-apis/menu

/close
