### ISSUE TITLE
文章别名能否内置UUID等方式命名呢？

### ISSUE THREAD

**Issue by xiongtete0519** [halo-dev/halo#3402]
### 你当前使用的版本

2.2.0

### 描述一下此特性

目前文章别名是自动用的拼音，能否内置个UUID等方案自动生成别名呢，不用我们一个个改了
![image](https://user-images.githubusercontent.com/66518135/221407072-05dcb6fd-cc47-4b94-9366-5dfeddfebc3e.png)

**Comment by ruibaby** [comment]
如果期望文章访问地址是随机的，你可以使用这两种路由方式：

<img width="579" alt="image" src="https://user-images.githubusercontent.com/21301288/221412379-a7f49a77-9341-40e4-93d5-4e3a63215c95.png">

/kind feature

**Comment by xiongtete0519** [comment]
我试了下，不管我如何设置访问规则，在新建文章测试的时候都是生成的拼音
![image](https://user-images.githubusercontent.com/66518135/221412966-a2d5f04e-6047-49c0-9475-7150203b9149.png)

![image](https://user-images.githubusercontent.com/66518135/221412950-dbac35b5-53f2-411b-89e0-10f320168440.png)
