### ISSUE TITLE
后台预览主题时设置后启用，前台访问会带上预览主题参数

### ISSUE THREAD

**Issue by jiuyue52** [halo-dev/halo#3404]
### 是什么版本出现了此问题？

2.x

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式部署？

Docker Compose

### 发生了什么？

后台**首次**安装任意一款主题后，
在**没有启用过**的状态下直接预览主题并配置主题， 然后在预览状态下直接启用主题后，访问前台的首页，文章，页面等URL上会带上预览主题的参数

**xx.xxx/?preview-theme-xxx**

目前解决方法：卸载重新安装主题，然后直接启用主题后再配置主题 不会出现此问题

**Comment by it985** [comment]
+1，同遇到过

**Comment by ruibaby** [comment]
没有复现该问题，且后续版本没有人反馈，先关闭此 issue，如果后续有稳定复现办法，可以随时打开或者新建 issue。
