### ISSUE TITLE
菜单配置窗口在新页面打开，不起作用

### ISSUE THREAD

**Issue by lixuejun725** [halo-dev/halo#3409]
### What is version of Halo has the issue?

2.2.1

### What database are you using?

MySQL 5.7

### What is your deployment method?

Docker

### What happened?

菜单配置窗口在新页面打开，不起作用
<img width="1468" alt="image" src="https://user-images.githubusercontent.com/38548829/221493114-de7ab8c8-c36d-4058-92d8-26fb7b7920b6.png">

**Comment by ruibaby** [comment]
/triage duplicate

see https://github.com/halo-dev/halo/issues/3401

/close
