### ISSUE TITLE
非超级管理员用户点击概览页面的”复制”按钮时，复制出的内容包含大量 undefined

### ISSUE THREAD

**Issue by LIlGG** [halo-dev/halo#3410]
### 是什么版本出现了此问题？

2.3.0-rc.1

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式部署？

Docker Compose

### 发生了什么？

使用非超级管理员用户时，将能够看到概览界面（任何用户都可以，包括访客和没有任何角色组的用户），此时点击概览右上角的”复制“ 按钮，复制出的内容会携带大量 undefined。

有两种方案的预期功能：
1. 具有概览界面权限的用户，将能够完整获得系统信息内容。
2. 去除携带有 undefined 的无效内容。

/kind bug

### 相关日志输出

```shell
- 外部访问地址：http://localhost:8091/
- 启动时间：
- Halo 版本：undefined
- 构建时间：
- Git Commit：undefined
- Java：undefined / undefined
- 数据库：undefined / undefined
- 操作系统：undefined / undefined
```

**Comment by JohnNiang** [comment]
倾向第一种方案。没有权限的用户所能获取的信息有限，且对于排查问题没有足够帮助。

**Comment by ruibaby** [comment]
> 倾向第一种方案。没有权限的用户所能获取的信息有限，且对于排查问题没有足够帮助。

需要提供这个页面的 UI 权限？

**Comment by ruibaby** [comment]
在 https://github.com/halo-dev/halo/pull/4897 和 https://github.com/halo-dev/halo/pull/4945 中已优化。

/close
