### ISSUE TITLE
登录密码存在明文传输，且登录失败可以无限登录，无验证码机制或登录次数限制

### ISSUE THREAD

**Issue by chengfeiyue** [halo-dev/halo#3419]
### What is version of Halo has the issue?

2.2.1

### What database are you using?

PostgreSQL

### What is your deployment method?

Docker Compose

### What happened?

可以在控制台直接看到登录密码，并且登录失败可以一直登录

**Comment by chengfeiyue** [comment]
<img width="1288" alt="image" src="https://user-images.githubusercontent.com/49852751/221743177-5c136389-5791-45a4-92ed-e5c0f3d434c9.png">

**Comment by chengfeiyue** [comment]
![image](https://user-images.githubusercontent.com/49852751/221743377-67806cea-3461-48c8-a197-3ac33a48b128.png)

**Comment by ruibaby** [comment]
建议提供期望解决的方式。

/area core
/kind improvement

**Comment by chengfeiyue** [comment]
期望1、密码加密传输，只要不是明文就行，
期望2、登录失败次数限制，比如登录失败5次，限制10分钟内不允许登录。若不好实现，那就登录失败一次，需要输入验证码

**Comment by 9mlcy7** [comment]
密码可以使用rsa前端加密传输
可以记录当前IP，限制IP在某个时间段内的登录次数

**Comment by JohnNiang** [comment]
> 密码可以使用rsa前端加密传输 可以记录当前IP，限制IP在某个时间段内的登录次数

欢迎 Review：<https://github.com/halo-dev/halo/pull/3480>。
