### ISSUE TITLE
多用户登录

### ISSUE THREAD

**Issue by cowboyzhangkai** [halo-dev/halo#343]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [x] 添加新的特性或者功能
- [ ] 请求技术支持

**Comment by ruibaby** [comment]
@cowboyzhangkai 暂不支持多用户

**Comment by cowboyzhangkai** [comment]
@ruibaby 我知道不支持，如果在这个基础上修改的话，麻烦吗？

**Comment by ruibaby** [comment]
@cowboyzhangkai 单纯的多用户不难。如果涉及到权限之类的话，得费点时间

**Comment by cowboyzhangkai** [comment]
@ruibaby 好的，谢谢你的回答！

**Comment by ruibaby** [comment]
@cowboyzhangkai 不出意外，会。但是最近应该不会做，我们打算先让其更加稳定之后再开发。

**Comment by cowboyzhangkai** [comment]
@ruibaby 好的，期待中！！

**Comment by ruibaby** [comment]
@cowboyzhangkai 不过我们可以讨论一下，实现怎样的“多用户”。

**Comment by cowboyzhangkai** [comment]
@ruibaby 多用户肯定是少不了用户注册功能，可以先不用实现权限控制用户，刚开始用户使用的模块基本上都是相同的，每个用户管理自己的博客就行了。后面再加上权限控制来实现普通用户订制特殊的功能模块！

**Comment by ruibaby** [comment]
@cowboyzhangkai 好的

**Comment by JohnNiang** [comment]
#334 可以和这位讨论一下。

**Comment by cowboyzhangkai** [comment]
@ruibaby 好的，谢谢推荐

**Comment by cowboyzhangkai** [comment]
@JohnNiang 谢谢推荐

**Comment by isdotjim** [comment]
搭个车...
想邀请Repo参与者来w3c.group创建项目的对应小组。w3c.group是类似知识星球的社群工具，小组可设置为付费且有赞助功能，同时也是一个区块链主导的创作者社区。这是相关介绍：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA

**Comment by cowboyzhangkai** [comment]
@ruibaby Halo安全性怎么样？

**Comment by ruibaby** [comment]
@cowboyzhangkai 不知道，还没人搞我

**Comment by ruibaby** [comment]
@cowboyzhangkai 顺便在这里说一下，欢迎神通广大的朋友来搞一下我的博客，随意搞。博客地址: https://ryanc.cc

**Comment by nan963** [comment]
@ruibaby halo多用户，用户数量有限制嘛？

**Comment by ruibaby** [comment]
> @ruibaby halo多用户，用户数量有限制嘛？

没有
