### ISSUE TITLE
文章访问次数统计不更新

### ISSUE THREAD

**Issue by Steven-WZH** [halo-dev/halo#3448]
### What is version of Halo has the issue?

2.3.0

### What database are you using?

H2

### What is your deployment method?

Docker

### Your site address.

https://blog.stevenw.cc/?p=halo-bao-ta-mian-ban-da-jian-halo-fan-xiang-dai-li

### What happened?

![image](https://user-images.githubusercontent.com/113268133/222698650-11ef21ed-ea0e-4152-aa3e-3409c4765ec0.png)
可以访问一下https://blog.stevenw.cc/?p=halo-bao-ta-mian-ban-da-jian-halo-fan-xiang-dai-li
试试，访问次数老是不增长

**Comment by Steven-WZH** [comment]
[halo-log-2023-03-03 20_53.log](https://github.com/halo-dev/halo/files/10882093/halo-log-2023-03-03.20_53.log)

**Comment by JohnNiang** [comment]
/kind bug
/area core

```bash
curl 'https://blog.stevenw.cc/apis/api.halo.run/v1alpha1/trackers/counter' \
  -H 'authority: blog.stevenw.cc' \
  -H 'accept: */*' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'content-type: application/json' \
  -H 'cookie: SESSION=79c59e57-07fe-4a83-acad-5e0c11b71dfa; browsertc=1' \
  -H 'origin: https://blog.stevenw.cc' \
  -H 'referer: https://blog.stevenw.cc/?p=office-tool-plus-huo-qu-mian-fei-office' \
  -H 'sec-ch-ua: "Chromium";v="110", "Not A(Brand";v="24", "Google Chrome";v="110"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36' \
  --data-raw '{"group":"content.halo.run","plural":"posts","name":"null","hostname":"blog.stevenw.cc","screen":"1512x982","language":"en-US","url":"/?p=office-tool-plus-huo-qu-mian-fei-office","referrer":"https://blog.stevenw.cc/"}' \
  --compressed
```

Counter 接口的请求体的 name 字段为 null。

**Comment by Steven-WZH** [comment]
这个bug会在下个版本修复吗

**Comment by guqing** [comment]
> 这个bug会在下个版本修复吗

这周修复 然后发 patch 版本

**Comment by guqing** [comment]
我测试了一下文章的访问量统计没有问题，自定义页面的有问题，应该是上次重构路由后出现的取值 name 有问题导致的
