### ISSUE TITLE
尝试打开 Freemarker 缓存，在修改模板的之后重置缓存。

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#345]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [ ] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [x] 添加新的特性或者功能
- [ ] 请求技术支持

RT

**Comment by ruibaby** [comment]
得出的结论：模板放在项目外部的话，修改模板之后会刷新缓存，但是放在 classpath 下则不会。

参考：http://freemarker.foofun.cn/pgui_config_templateloading.html

**Comment by JohnNiang** [comment]
@ruibaby 目前不正是放在外部的么。而且我们也没有能力修改 classpath 下的文件啊😂
