### ISSUE TITLE
不同编辑器最终生成出来的html不完全一致

### ISSUE THREAD

**Issue by AKmoex** [halo-dev/halo#3453]
### Your current Halo version

2.3.0

### Describe this feature

环境：
1. halo 2.3.0
2. ByteMD 1.1.0

问题：
使用不同原生富文本编辑器和ByteMD编辑器编辑的文章，最终生成的html文档并不完全一致，下面距离说明
1. 原生的富文本编辑器：
<img width="561" alt="截屏2023-03-04 15 36 28" src="https://user-images.githubusercontent.com/63089888/222882752-682bc6fa-2d84-471f-9403-2203d00b9804.png">
<img width="352" alt="截屏2023-03-04 15 36 52" src="https://user-images.githubusercontent.com/63089888/222882767-d6277845-c5d7-408a-8a52-17080af076cb.png">
2. ByteMD编辑器：
<img width="411" alt="截屏2023-03-04 15 37 06" src="https://user-images.githubusercontent.com/63089888/222882860-63e7f6fc-3183-4b2d-9ac3-efb86ba9d5ea.png">
<img width="405" alt="截屏2023-03-04 15 37 20" src="https://user-images.githubusercontent.com/63089888/222882877-dfbd42d4-c3e9-4aab-bb8b-3805c08bea93.png">

希望的实现的需求：
1. 不同编辑器生成的最终html内容应该尽量一致
2. 生成html内容，应该尽量与其他平台生成的html内容一致（例如 hexo等）

**Comment by ruibaby** [comment]
渲染结果完全由插件实现，Halo 核心无法很好的干预，也不推荐干预。如果生成的 HTML 不符合预期，建议向插件反馈。

/close
