### ISSUE TITLE
新建文章复制粘贴图片,图片url还是旧平台的url

### ISSUE THREAD

**Issue by chengfeiyue** [halo-dev/halo#3463]
### What is version of Halo has the issue?

2.3.x

### What database are you using?

PostgreSQL

### What is your deployment method?

Docker Compose

### What happened?

1、新建文章
2、从任意一网站复制图片如公司官网首页
<img width="1196" alt="image" src="https://user-images.githubusercontent.com/49852751/223036870-55a79804-f499-4e53-ab4b-6b55e7d5dfd1.png">
3、黏贴图片，打开F12发现图片url 还是旧平台的url
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/49852751/223037070-aab5bf15-95ba-4e72-bee8-1d7fc1866dda.png">

**Comment by stinglong12** [comment]
这个需要搭建自己的图床

**Comment by stinglong12** [comment]
这个需要搭建自己的图床

**Comment by ruibaby** [comment]
/triage duplicate

see https://github.com/halo-dev/halo/issues/2335

/close
