### ISSUE TITLE
主题升级失败导致删除主题，重新安装

### ISSUE THREAD

**Issue by lan-yonghui** [halo-dev/halo#3466]
### 是什么版本出现了此问题？

2.1.0-

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式部署？

Docker Compose

### 在线站点地址

https://next.1tian.cc

### 发生了什么？

服务器1C2G，偶发现象，主题升级时，主题包过大会导致删除了主题但是升级失败，需要重新安装主题。。。

### 附加信息

![升级](https://user-images.githubusercontent.com/81747598/223089130-cdc6eb13-b5be-4afc-9138-efe4406fe4e6.png)
![重载](https://user-images.githubusercontent.com/81747598/223089155-dedc03c6-1b63-4569-b9ae-be5f8f2d9038.png)

**Comment by ruibaby** [comment]
如果没有后续动态，我将关闭此 issue，如果有后续问题可以新建 issue 或者 reopen。

/close
