### ISSUE TITLE
文章或页面插入表格后台预览是正确的,主站显示错误

### ISSUE THREAD

**Issue by fishandsheep** [halo-dev/halo#347]
- [x] BUG 反馈
文章或页面插入表格(ctril+alt+t)后台预览是正确的,主站显示错误
浏览器 chrom 360

**Comment by ruibaby** [comment]
@fishandsheep 文章地址看看

**Comment by fishandsheep** [comment]
@ruibaby http://39.96.66.128/archives/meishi

**Comment by ruibaby** [comment]
![EDE251B4-7B2B-4288-A5CD-61F88E3F3CAA.png](https://i.loli.net/2019/10/27/srB3mcnTOvgbQY9.png)

这样即可。

**Comment by fishandsheep** [comment]
@ruibaby 小哥，可以了，试验了一下必须7个“-”才有效，另外看一下我刚发布的文章http://39.96.66.128/archives/meishi，感谢！

**Comment by fishandsheep** [comment]
@ruibaby 小哥，可以了，试验了一下必须7个“-”才有效，感谢。
另外看一下我刚发布的文章 http://39.96.66.128/archives/meishi
