### ISSUE TITLE
FormKit Schema 中提供的标签 / 分类选择组件无法完整显示下拉框

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#3479]
### 是什么版本出现了此问题？

2.3.0

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式部署？

Docker Compose

### 在线站点地址

https://halo.run

### 发生了什么？

如图：

<img width="597" alt="image" src="https://user-images.githubusercontent.com/21301288/223428868-86323d24-fb51-40e5-a6e4-2be73e8132b7.png">

目前仅发现在 Repeater 组件中的标签/分类选择组件有这样的问题。

/area console
/kind bug

**Comment by 1357885013** [comment]
![image](https://user-images.githubusercontent.com/25767027/230599519-ccd2d6c7-fd3a-4bcc-be74-112298879393.png)
给这个li标签设置个overflow:visiable 就好

**Comment by JohnNiang** [comment]
@1357885013 欢迎提交 PR 祝福这个问题。
