### ISSUE TITLE
怎么样每天备份功能

### ISSUE THREAD

**Issue by hello1983** [halo-dev/halo#348]
怎么样备份网站 我是docker 部署的

**Comment by JohnNiang** [comment]
备份文件夹 ~/.halo

**Comment by hello1983** [comment]
谢谢啦
2019年10月28日 +0800 21:26 John Niang <notifications@github.com>，写道：

**Comment by JohnNiang** [comment]
有关文章导出为 markdown 文件的功能还需要等待后面再实现。

**Comment by hello1983** [comment]
嗯。我也是刚刚接触。很不错
2019年10月28日 +0800 21:29 John Niang <notifications@github.com>，写道：

**Comment by JohnNiang** [comment]
Have a good experience!
