### ISSUE TITLE
修改初始化用户名后无法修改显示名称

### ISSUE THREAD

**Issue by 9mlcy7** [halo-dev/halo#3482]
### 是什么版本出现了此问题？

2.3.0

### 使用的什么数据库？

Other

### 使用的哪种方式部署？

Docker Compose

### 发生了什么？

将--halo.security.initializer.superadminusername设置成非admin之后，在后台修改超级管理员的资料提交时，用户名会提示”请输入有效的用户名“，而用户名是不可修改的

**Comment by 9mlcy7** [comment]
![image](https://user-images.githubusercontent.com/51769096/223687150-2ae28438-a3bc-4931-a05d-02b838a1c313.png)
![image](https://user-images.githubusercontent.com/51769096/223687281-00239600-5152-4aac-b1d4-a0a8368ebb36.png)

**Comment by JohnNiang** [comment]
Hi @9mlcy7 ，我们目前已经对用户名添加了特殊校验，可参考：<https://github.com/halo-dev/halo/issues/3239> 和 <https://github.com/halo-dev/console/pull/868#issue-1591247694>。

**Comment by MoshiCoCo** [comment]
写配置的时候用户名直接用了邮箱账号。登陆后发现无法修改，查了下才发现这里有特殊的校验规则。

是否可以在前台提供校验规则说明？ 红色字体增加校验规则描述。

**Comment by JohnNiang** [comment]
用户名应该在服务端加上校验，这样可以保证在启动 Halo 的时候给出足够的提示。

我将重新开启当前 Issue。

/reopen
/milestone 2.5.x
