### ISSUE TITLE
关于异常信息抛出

### ISSUE THREAD

**Issue by 9mlcy7** [halo-dev/halo#3483]
### What is version of Halo has the issue?

2.3.0

### What database are you using?

Other

### What is your deployment method?

Docker Compose

### What happened?

![image](https://user-images.githubusercontent.com/51769096/223641833-70a07abe-a62a-49c1-9abd-c7c711bdf326.png)
对于异常抛出，建议使用ExceptionHandler将所有异常处理后再抛出，避免暴露敏感信息，图片中暴露本机实际目录

**Comment by JohnNiang** [comment]
目前我们只提供 Docker 容器部署，理论上讲，这些信息不用通过报错的方式也可以知道的。

不过就算是知道了似乎也做不了什么。

/kind improvement

**Comment by JohnNiang** [comment]
/reopen
/area core

但是，对于服务器内部错误，确实不需要展示以上详细信息。
