### ISSUE TITLE
字符在编辑器编辑和前端显示不一致问题

### ISSUE THREAD

**Issue by qgx66** [halo-dev/halo#3485]
### 是什么版本出现了此问题？

1.5最新版

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 在线站点地址

http://www.qigx.love:1314/archives/centos7linux-an-zhuang-mysql750

### 发生了什么？

在后端编辑器输入"" 在前端的输出是“” 导致做的笔记会出现复制错误问题。

### 相关日志输出

```shell
无
```

### 附加信息

无

**Comment by guqing** [comment]
<img width="276" alt="image" src="https://user-images.githubusercontent.com/38999863/223915449-29e0043e-58c3-45a1-832c-19132d6a2ea6.png">
你的这篇文章中有些是中文双引号有些是英文双引号，有复现步骤吗，什么情况下输入英文双引号会变成中文

**Comment by qgx66** [comment]
我在前端看到的都是中文双引号，后端编辑是英文双引号，
![1678415951539(1)](https://user-images.githubusercontent.com/111854328/224209295-cea4ae2b-a0e3-4c50-b9bf-74fe27954e3e.jpg)
![1678415604980](https://user-images.githubusercontent.com/111854328/224209328-6d589cd4-ecfe-4f62-86a9-7f31911f3524.jpg)
@guqing

**Comment by guqing** [comment]
> 我在前端看到的都是中文双引号，后端编辑是英文双引号


你换一个主题试试呢，我并没有发现 1.5 的编辑器有这样的英文符号转中文的问题

**Comment by qgx66** [comment]
好的呢，我看看，谢谢！

**Comment by qgx66** [comment]
跟主题没有关系，切换自带主题，依旧是如此问题， @guqing

**Comment by guqing** [comment]
> 跟主题没有关系，切换自带主题，依旧是如此问题， @guqing

确实，我已经复现了，目前临时解决方法可能就是输入的时候用反文号包裹
<img width="561" alt="image" src="https://user-images.githubusercontent.com/38999863/224233095-49d3852d-7a0c-4235-8981-dae62c581988.png">
1.x 版本已经快要停止维护了，后续可以迁移到 2.x 版本使用

**Comment by qgx66** [comment]
加到代码块也能解决，感谢支持！ @guqing 
![image](https://user-images.githubusercontent.com/111854328/224233878-63f161a5-cce9-44d2-b202-86ff12fa2f57.png)
