### ISSUE TITLE
希望halo在发布文章时，增加“是否在首页显示”的按钮

### ISSUE THREAD

**Issue by 52FengYu** [halo-dev/halo#3489]
### 你当前使用的版本

1.0.10

### 描述一下此特性

因为要写一篇《版权说明》、《关于我们》和《资源代查》的文章，这样类型的文章不适合在首页进行展示，同时也不适合输入密码才能查看
希望作者大大可惜出一个功能就是： 发布文章时可选“是否在首页显示”的按钮 ，否的话通过文章链接才能查看；是的话才在首页进行展示
非常感谢，现在的功能已经很完善，项目也很成熟了，还希望作者大大能再考虑考虑我的建议

**Comment by ruibaby** [comment]
这些内容建议用页面发布，页面的话就只能手动通过链接访问了，可以满足你的需求。

<img width="1681" alt="image" src="https://user-images.githubusercontent.com/21301288/223686494-6001edbb-e655-4ca3-bcf4-43b005b60e15.png">

/kind support

**Comment by 52FengYu** [comment]
好的 好的 非常感谢 明天试一下



---- 回复的原邮件 ----
| 发件人 | Ryan ***@***.***> |
| 日期 | 2023年03月08日 18:18 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [halo-dev/halo] 希望halo在发布文章时，增加“是否在首页显示”的按钮 (Issue #3489) |

这些内容建议用页面发布，页面的话就只能手动通过链接访问了，可以满足你的需求。

/kind support
