### ISSUE TITLE
第一次的时候没有配https直接用ip登陆了，配置好了后反而地址转向了IP，请问如何再次初始化

### ISSUE THREAD

**Issue by ariallyp** [halo-dev/halo#349]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [ ] [Halo 使用文档](https://halo.run/docs)
- [ ] [Halo 论坛](https://bbs.halo.run)
- [ ] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [ ] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

**Comment by JohnNiang** [comment]
在管理端的设置界面设置一下博客地址就好了，不需要初始化哦。

**Comment by ruibaby** [comment]
@ariallyp 这种情况你改一下后台的博客设置中的博客地址就好了。如果你想重新初始化，去服务器执行 rm -rf ~/.halo ，然后重启halo。

**Comment by JohnNiang** [comment]
@ruibaby 他的本意应该不是想重置

**Comment by ariallyp** [comment]
嗯好的谢谢，不用初始化改下博客地址就可以了的。
