### ISSUE TITLE
Nginx 部署 外部访问地址如何配置

### ISSUE THREAD

**Issue by peterzcl** [halo-dev/halo#3494]
### 是什么版本出现了此问题？

外部访问地址应该是服务器地址吧

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Fat Jar

### 在线站点地址

http://halo.chengfengit.com/

### 发生了什么？

账号：root
密码：root123
![image](https://user-images.githubusercontent.com/28745693/223932185-9a971544-b11b-4a5f-af24-b43e01cb6e4c.png)

**Comment by JohnNiang** [comment]
为 Halo 创建配置文件：`~/.halo2/application.yaml`，配置如下内容：

```yaml
halo:
  external-url: http://halo.chengfengit.com/
```

重启 Halo 容器即可。

/kind support

**Comment by ruibaby** [comment]
请参考文档：https://docs.halo.run/getting-started/install/docker-compose#:~:text=%E4%B8%8E%20SPRING_R2DBC_URL%20%E5%AF%B9%E5%BA%94-,halo.external%2Durl,-%E5%A4%96%E9%83%A8%E8%AE%BF%E9%97%AE%E9%93%BE

/close
