### ISSUE TITLE
頁面加載時會出現異常

### ISSUE THREAD

**Issue by HimiCos** [halo-dev/halo#3499]
### What is version of Halo has the issue?

2.3.1

### What database are you using?

H2

### What is your deployment method?

Docker

### Your site address.

https://blog.himicos.cc

### What happened?

頁面加載時會出現異常

https://user-images.githubusercontent.com/92566148/224300555-4ec879e2-3148-40a9-bbe7-32843e627565.MOV

**Comment by ruibaby** [comment]
这应该属于主题的问题，从视频来看应该是 https://github.com/dhjddcn/halo-theme-butterfly

你可以向这个仓库提交 issue。

/kind support
