### ISSUE TITLE
希望文档列表页的可见性图标点击可以修改

### ISSUE THREAD

**Issue by CV-Devlau** [halo-dev/halo#3501]
### Your current Halo version

2.3.0

### Describe this feature

当前修改可见性需要点击设置，进行修改可见性，操作有一些繁琐。
我将鼠标放到可见性图标上，有颜色反馈，但是点击并没有修改功能。
希望可以增加在列表页直接点击图标进行修改功能
![image](https://user-images.githubusercontent.com/63354237/224523902-e8cc1b16-e6aa-43f7-b242-7c2f54cc2be1.png)
点击后是一个黑框
![image](https://user-images.githubusercontent.com/63354237/224523885-4381dcaf-34f9-478d-b19a-e4965590c700.png)

**Comment by ruibaby** [comment]
已经在 https://github.com/halo-dev/halo/pull/3581 中支持，并在 [2.4.0](https://github.com/halo-dev/halo/releases/tag/v2.4.0) 中发布。

/close
