### ISSUE TITLE
后台无法更改或添加用户

### ISSUE THREAD

**Issue by L4v3nder** [halo-dev/halo#3504]
### 是什么版本出现了此问题？

2.3.0

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker Compose

### 在线站点地址

无

### 发生了什么？

在后台更改或添加用户时，一直显示请输入有效的用户名。

### 相关日志输出

```shell
无
```

### 附加信息

无

**Comment by ruibaby** [comment]
/triage duplicate

see https://github.com/halo-dev/halo/issues/3482

**Comment by EGOIST123** [comment]
我也出现了这样的问题，好像用户名有大写就不行，而我创建超级管理账户时用的全大写，导致我无法在修改其任何信息。

**Comment by JohnNiang** [comment]
/close

Close in favor of <https://github.com/halo-dev/halo/issues/3482>.
