### ISSUE TITLE
添加文章/文档的版本

### ISSUE THREAD

**Issue by infanx** [halo-dev/halo#3509]
### 你当前使用的版本

2.3.0

### 描述一下此特性

像 docusaurus 那样可以选择 博客文章的版本 就和 [docs](https://docs.halo.run/) 那样

**Comment by ruibaby** [comment]
欢迎大家提供实现想法。

/kind feature
/milestone Backlog

**Comment by ruibaby** [comment]
这种功能更适合文档，所以推荐使用专门的文档插件：https://www.halo.run/store/apps/app-yffxw

/close
