### ISSUE TITLE
新版本文章编辑器复制markdown语法文本解析错误

### ISSUE THREAD

**Issue by fsyj-123** [halo-dev/halo#3511]
### 是什么版本出现了此问题？

2.3

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker Compose

## 问题描述
在新版本中进行文章新增功能，
1. 在文章新增页中复制markdown格式的文本，会出现解析为代码块的问题
如
```
# 测试文章
```
代码块中的内容（不包括代码块定义符）复制到编辑器中会自动解析为markdown代码块
![image](https://user-images.githubusercontent.com/65690779/224704218-208a25df-34f5-4af3-abf9-5d16fccc6a72.png)

这种情况会出现在从IDE中复制出来的markdown文档。即将文本在IDE（测试IDE为VScode）中复制，到文章编辑器中粘贴出现

2. 复制的markdown文本不解析
这种情况如上。若复制源为记事本，则不会去解析markdown文本

## 问题解析

出现这种问题是因为IDE中复制的文本会自动复制格式信息，即富文本

## 解决建议

增加粘贴选项，如同word，若粘贴的文本为markdown纯文本，则自动解析，否则用户必须手动更改格式或从其他markdown编辑器中重新复制

**Comment by guqing** [comment]
可以先考虑安装 markdown 编辑器插件来实现：https://github.com/halo-sigs/plugin-bytemd
目前内置的编辑器是富文本编辑器，对 markdown 的支持并不完善
