### ISSUE TITLE
移动端文章编辑界面布局

### ISSUE THREAD

**Issue by Steven-WZH** [halo-dev/halo#3513]
### 是什么版本出现了此问题？

2.3.1

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

布局很奇怪，文章编辑只有左边一条，大纲预览占比太大了

**Comment by ruibaby** [comment]
目前尚未对移动端进行优化。

/triage duplicate

see https://github.com/halo-dev/halo/issues/2699

/close
