### ISSUE TITLE
手動在標題前或者普通文本前加空格保存後不會生效

### ISSUE THREAD

**Issue by HimiCos** [halo-dev/halo#3515]
### 是什么版本出现了此问题？

2.3.1

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

https://blog.himicos.cc/archives/test

**Comment by JohnNiang** [comment]
從 Page Source 來看，可能是主題的樣式問題：

<img width="1472" alt="image" src="https://user-images.githubusercontent.com/16865714/224917106-7c9022e6-a141-43be-9cf0-b9ffe9d015bb.png">

/kind improvement
/area theme

**Comment by kailin-hub** [comment]
请问这个问题有解决方法吗？
