### ISSUE TITLE
删除用户后，所有的文章作者均显示为已删除的用户，是否可以支持变更文章作者的功能。

### ISSUE THREAD

**Issue by MoshiCoCo** [halo-dev/halo#3518]
### 你当前使用的版本

2.3.1

## 需求场景描述

例如我初始化时使用了admin这个账户名初始化，后面我不需要用admin这个账户了。

用了自定义的superadmin作为默认账户。

之后删除admin账号，会导致之前的文章作者都变成”已删除用户“

## 需求描述

是否可以在管理后台修改文章时，增加一个变更作者的功能。

## 我的临时解决方案

目前我采用的方案时手动变更。

```mysql
update extensions
set  data=replace(data,'"owner":"admin"','"owner":"superadmin"')
where data like '%"owner":"admin"%'
  and name like '%"/registry/content.halo.run/posts"%'
```

**Comment by ruibaby** [comment]
/triage duplicate

see https://github.com/halo-dev/halo/issues/3056

/close
