### ISSUE TITLE
在阿里云CentOS7中执行 java -jar halo-latest.jar  后 在复制文件Copied theme folder from [/BOOT-INF/classes/templates/themes] to [/root/.halo/templates/themes]处一直不动

### ISSUE THREAD

**Issue by mikutown** [halo-dev/halo#352]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [x] 请求技术支持

**Comment by ruibaby** [comment]
`Copied`，已经运行成功，上面访问地址已经打印就行了。

**Comment by mikutown** [comment]
可是程序一直在执行不结束 ip:8090也没法访问

**Comment by ruibaby** [comment]
一直在执行不结束是什么意思？ 无法访问先看一下 `8090` 端口是否开放。

**Comment by JohnNiang** [comment]
> 可是程序一直在执行不结束 �ip:8090也没法访问

你好，这个日志表示已经成功运行了。你想要的效果应该是让它后台运行。你可以去了解一下 nohup 命令。

**Comment by mikutown** [comment]
就是 linux执行完程序后命令行会变成[root@Leafii ~]#  这样的啊 但是这个没有

**Comment by JohnNiang** [comment]
@mikutown 这个表示已经成功运行，并等待访问

**Comment by JohnNiang** [comment]
@mikutown nohup java -jar halo-latest.jar >/dev/null 2>&1&

**Comment by mikutown** [comment]
dashbord上去了 但是命令行 还是没有恢复成[root@Leafii ~]# 这样的 请问这个jar包执行完是不是不能返回 [root@Leafii ~]#这样的状态

**Comment by JohnNiang** [comment]
> dashbord上去了 但是命令行 还是没有恢复成[root@Leafii ~]# 这样的 请问这个jar包执行完是不是不能返回 [root@Leafii ~]#这样的状态

停止之后用这个命令运行：

```bash
nohup java -jar halo-latest.jar >/dev/null 2>&1&
```

**Comment by ruibaby** [comment]
进阶配置：https://halo.run/guide/install/install-with-linux.html#%E8%BF%9B%E9%98%B6%E9%85%8D%E7%BD%AE

**Comment by mikutown** [comment]
我好像明白了 dalao 是不是我ctrl+C终止这个进程 网站就无法继续运行了

**Comment by ruibaby** [comment]
@mikutown 是的，那个命令仅仅是测试是否能正常运行。正式部署参考进阶配置
