### ISSUE TITLE
【搜索bug】无法搜索中文内容

### ISSUE THREAD

**Issue by nop4LOL** [halo-dev/halo#3521]
### 是什么版本出现了此问题？

最新版本2.3.2

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker Compose

### 发生了什么？

【搜索bug】无法搜索中文内容

### 相关日志输出

```shell
【搜索bug】无法搜索中文内容
```

### 附加信息

【搜索bug】无法搜索中文内容

**Comment by nop4LOL** [comment]
只能搜索英文关键字，不能搜索中文关键字

**Comment by DarrenLuo** [comment]
可以提供文章内容以及查询的词语进行查看，有可能是ik分词的问题

**Comment by JohnNiang** [comment]
Hi @nop4LOL ，建议升级到 2.4.1，优化了文章搜索功能。
