### ISSUE TITLE
使用docker 和 docker-compose 安装halo时，在docker仓库中找不到指定版本

### ISSUE THREAD

**Issue by A563185000** [halo-dev/halo#3524]
### 是什么版本出现了此问题？

2.3.0

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker Compose

### 发生了什么？

使用docker 和 docker-compose 安装halo时，在docker仓库中找不到指定版本，报以下的错误
`**ERROR: manifest for docker.io/halohub/halo:2.3.0 not found**`

我又使用docker安装了一遍，报以下的错误
```
**/usr/bin/docker-current: manifest for docker.io/halohub/halo:2.3.0 not found.
See '/usr/bin/docker-current run --help'.**
```

我的docker daemon.json配置如下

> { 
 "registry-mirrors": ["https://alzgoonw.mirror.aliyuncs.com"] 
 }

**Comment by ruibaby** [comment]
<img width="900" alt="image" src="https://user-images.githubusercontent.com/21301288/225580286-daf5b402-07b9-4271-950a-9b83d3063fdd.png">

我不认为这个问题和 Halo 有关，建议检查一下源是否同步了 Halo 的镜像。

Docker Hub 上的状态是正常的：https://hub.docker.com/repository/docker/halohub/halo

**Comment by A563185000** [comment]
> <img alt="image" width="900" src="https://user-images.githubusercontent.com/21301288/225580286-daf5b402-07b9-4271-950a-9b83d3063fdd.png">
> 
> 我不认为这个问题和 Halo 有关，建议检查一下源是否同步了 Halo 的镜像。
> 
> Docker Hub 上的状态是正常的：https://hub.docker.com/repository/docker/halohub/halo

请问一下如何进行检查啊

**Comment by JohnNiang** [comment]
Hi @A563185000 建议多尝试其他源或者不配置 registry mirrors 并重启 Docker。

**Comment by MoshiCoCo** [comment]
> > <img alt="image" width="900" src="https://user-images.githubusercontent.com/21301288/225580286-daf5b402-07b9-4271-950a-9b83d3063fdd.png">
> > 我不认为这个问题和 Halo 有关，建议检查一下源是否同步了 Halo 的镜像。
> > Docker Hub 上的状态是正常的：https://hub.docker.com/repository/docker/halohub/halo
> 
> 请问一下如何进行检查啊

替换为dcoker 中国的就行，阿里云的源非热点镜像同步有延迟。
