### ISSUE TITLE
权限模板定义中关于内容的 snapshots 单词拼写错误

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#3529]
### 是什么版本出现了此问题？

2.3.1

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式部署？

Docker Compose

### 在线站点地址

https://halo.run

### 发生了什么？

如图：

<img width="687" alt="image" src="https://user-images.githubusercontent.com/21301288/225873796-51752b26-4cfe-4149-8f90-80eead493ec7.png">

**snaphosts** 应该是 **snapshots**。

需要确认修正之后是否会导致包含破坏更新。

/kind bug
/area core

**Comment by guqing** [comment]
需要先对旧数据添加 deletionTimeStamp 然后在模板中新添加记录，但是对于其他用户创建引用过这个权限的角色就会关联失效。

**Comment by JohnNiang** [comment]
目测没有影响。因为 `resources: ["snaphosts"]` 配置错误，导致无法正常访问到 `snapshots.content.halo.run` 接口。

如果有问题，再此之前就已经存在这个问题。
