### ISSUE TITLE
發布文章沒問題 文章設置保存時顯示服務器內部錯誤

### ISSUE THREAD

**Issue by HimiCos** [halo-dev/halo#3533]
### 是什么版本出现了此问题？

2.3.2

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

發布文章沒問題 文章設置保存時顯示服務器內部。
親自測試上一個版本沒報錯。
![CleanShot 2023-03-18 at 10 27 13@2x](https://user-images.githubusercontent.com/92566148/226078404-689a9b2f-8603-4214-9719-5a7ec3328bb3.png)

**Comment by ruibaby** [comment]
/triage needs-information

可以稳定复现吗？如果可以，建议打开浏览器开发者模式，然后看一下 Network 中的接口请求过程。

**Comment by HimiCos** [comment]
我可以嘗試截圖發給你，但是我並看不懂 wwww
![截圖 2023-03-18 14 03 11](https://user-images.githubusercontent.com/92566148/226088305-4ef9ba29-bf19-4454-84d1-c6cf57968cb2.png)

**Comment by ruibaby** [comment]
@HimiCos 这看起来不科学呀，这是重试了三次都失败。可以发一下 400 错误接口的返回内容吗？如果可以，顺便带一下日志。

**Comment by HimiCos** [comment]
### Response
{"type":"about:blank","title":"Schema Violation","status":400,"detail":"Validation error(s) :\nmetadata.annotations: Type expected 'string', found 'boolean'. (code: 1027)\nFrom: metadata.<#/components/schemas/Metadata>.annotations.<additionalProperties>.<type>\n of schema content.halo.run/v1alpha1/Post.","instance":"/apis/content.halo.run/v1alpha1/posts/e0ed855b-3493-44d6-bdcd-d4603d071157","requestId":"d61f1d9b-229","timestamp":"2023-03-18T08:20:07.377604767Z"}
### Request
curl 'http://host:8090/apis/content.halo.run/v1alpha1/posts/e0ed855b-3493-44d6-bdcd-d4603d071157' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: zh-TW,zh;q=0.9,en;q=0.8' \
  -H 'Connection: keep-alive' \
  -H 'Cookie: ; order=id%20desc; serverType=nginx; bt_user_info=%7B%22status%22%3Atrue%2C%22msg%22%3A%22%u83B7%u53D6%u6210%u529F%21%22%2C%22data%22%3A%7B%22username%22%3A%22186****8179%22%7D%7D; pro_end=-1; ltd_end=-1; memSize=1783; XSRF-TOKEN=23847c6c-42c8-4066-9c5f-768352c828f7; SESSION=0d2466d3-95b0-41ab-8823-1f67ed790652' \
  -H 'Referer: http://host:8090/console/' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.1661.44' \
  -H 'X-Requested-With: XMLHttpRequest' \
  -H 'X-XSRF-TOKEN: 23847c6c-42c8-4066-9c5f-768352c828f7' \
  --compressed \
  --insecure ;
curl 'http://host:8090/apis/content.halo.run/v1alpha1/posts/e0ed855b-3493-44d6-bdcd-d4603d071157' \
  -X 'PUT' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: zh-TW,zh;q=0.9,en;q=0.8' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json' \
  -H 'Cookie: ; order=id%20desc; serverType=nginx; bt_user_info=%7B%22status%22%3Atrue%2C%22msg%22%3A%22%u83B7%u53D6%u6210%u529F%21%22%2C%22data%22%3A%7B%22username%22%3A%22186****8179%22%7D%7D; pro_end=-1; ltd_end=-1; memSize=1783; XSRF-TOKEN=; SESSION=0d2466d3-95b0-41ab-8823-1f67ed790652' \
  -H 'Origin: http://host:8090' \
  -H 'Referer: http://host:8090/console/' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.1661.44' \
  -H 'X-Requested-With: XMLHttpRequest' \
  -H 'X-XSRF-TOKEN: ' \
  --data-raw '{"spec":{"title":"无标题文章","slug":"1679105765151","releaseSnapshot":"08ade9a2-1ba2-4644-bb7b-e6184c427c6f","headSnapshot":"8701e9c7-4feb-48cc-afee-94b3caa89493","baseSnapshot":"08ade9a2-1ba2-4644-bb7b-e6184c427c6f","owner":"admin","template":"","cover":"","deleted":false,"publish":true,"publishTime":"2023-03-18T02:18:10.517945543Z","pinned":false,"allowComment":true,"visible":"PUBLIC","priority":0,"excerpt":{"autoGenerate":true,"raw":""},"categories":[],"tags":[],"htmlMetas":[]},"status":{"phase":"PUBLISHED","conditions":[{"type":"PUBLISHED","status":"TRUE","lastTransitionTime":"2023-03-18T02:18:10.517934069Z","message":"Post published successfully.","reason":"Published"},{"type":"DRAFT","status":"TRUE","lastTransitionTime":"2023-03-18T02:16:05.297120800Z","message":"Drafted post successfully.","reason":"DraftedSuccessfully"}],"permalink":"http://114.116.228.248:8090/archives/1679105765151","excerpt":"前言 當今網站與應用程式的設計已經不再只是簡單的展示資訊，而是需要與用戶進行互動。表單元素是前端設計中不可或缺的一部分，它們讓用戶可以提交資訊，進而與網站或應用程式進行互動。不同的表單元素可以用來收集不同的資訊，例如文字輸入框、密碼框、提交按鈕等等。在這篇文章中，我們將探討前端表單元素的不同種類、如","inProgress":true,"contributors":["admin"],"lastModifyTime":"2023-03-18T02:18:10.449160828Z"},"apiVersion":"content.halo.run/v1alpha1","kind":"Post","metadata":{"finalizers":["post-protection"],"name":"e0ed855b-3493-44d6-bdcd-d4603d071157","labels":{"content.halo.run/published":"true","content.halo.run/deleted":"false","content.halo.run/owner":"admin","content.halo.run/visible":"PUBLIC","content.halo.run/archive-year":"2023","content.halo.run/archive-month":"03","content.halo.run/archive-day":"18"},"annotations":{"enable_toc_sequence":true,"content.halo.run/preferred-editor":"default","content.halo.run/permalink-pattern":"/archives/{slug}","content.halo.run/last-released-snapshot":"08ade9a2-1ba2-4644-bb7b-e6184c427c6f"},"version":19,"creationTimestamp":"2023-03-18T02:16:05.290960820Z"}}' \
  --compressed \
  --insecure

**Comment by ruibaby** [comment]
从请求来看是因为 Annotations 对象中 `enable_toc_sequence` 的值类型为 boolean，与后端类型不匹配导致的，目前 Annotations 的值只能为 string 类型。

`enable_toc_sequence` 这个值是如何产生的呢，是否使用了某个插件或者主题？

**Comment by HimiCos** [comment]
根據你的分析，我把主題降級了一下，因為那個主題也是根據halo的更新頻率來的，我也沒有考慮到是主題的問題。`enable_toc_sequence`這個值確實是主題產生的，現在問題已經解決，謝謝！

**Comment by ruibaby** [comment]
> 根據你的分析，我把主題降級了一下，因為那個主題也是根據halo的更新頻率來的，我也沒有考慮到是主題的問題。`enable_toc_sequence`這個值確實是主題產生的，現在問題已經解決，謝謝！

是哪个主题？ 可以提一个 issue。
