### ISSUE TITLE
文章设置中的标签功能与分类目录功能统一

### ISSUE THREAD

**Issue by QianChenJun** [halo-dev/halo#3536]
### 你当前使用的版本

2.3.2

### 描述一下此特性

目前在发布文章的时候需要选择分类目录喝标签功能，分类目录可以实现在发布文章的时候输入一个新的名称，并且可以自动创建且带有检索功能。而标签功能则只能手动一个个去创建以及一个个去选择，没办法实现发布时创建以及文字匹配选择。

### 附加信息

![image](https://user-images.githubusercontent.com/74245184/226162799-98cfd3fc-0b9e-47a4-b46c-dc204684be31.png)
![image](https://user-images.githubusercontent.com/74245184/226162789-ca49c7cc-4991-42a0-9f22-4a20ac6b15b9.png)

**Comment by QianChenJun** [comment]
刚试了一下默认自带的编译器是可以的，**出现的情况是使用了第三方md插件。**

**Comment by ruibaby** [comment]
可以复现，具体原因是搜索失效。

<img width="591" alt="image" src="https://user-images.githubusercontent.com/21301288/226175815-d9ed2acf-55e4-472d-a2ce-821844c60af2.png">

/area console
/kind bug
/good-first-issue
