### ISSUE TITLE
进行文章设置时,会抛出服务器内部错误

### ISSUE THREAD

**Issue by Douzi-Qishen** [halo-dev/halo#3537]
### 是什么版本出现了此问题？

2.3.2

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker Compose

### 发生了什么？

![image](https://user-images.githubusercontent.com/34978212/226168434-3b4e4210-cbde-41e6-9b0d-92822eb6a98e.png)

**Comment by ruibaby** [comment]
/triage duplicate

应该和 https://github.com/halo-dev/halo/issues/3533 是同一个问题。

主题相关 issue：https://github.com/dhjddcn/halo-theme-butterfly/issues/90
