### ISSUE TITLE
2.x版本目前还没有除了主题使用的Finder API之外的接口吗

### ISSUE THREAD

**Issue by AeroWang** [halo-dev/halo#3538]
### 你当前使用的版本

2.3.0

### 描述一下此特性

目前还是只有Finder API 啊。比如开发单页面应用，或者用Nuxt.js,Next.js。这还是需要接口的。

在2.x之前是有提供的 [https://api.halo.run/](https://api.halo.run/)，现在没找到相关的接口。

希望后续还会继续提供这样的接口

**Comment by JohnNiang** [comment]
/kind feature
/area theme
/area core

其实 Halo 2.x 是提供了丰富的 API 的，可参考：<https://demo.halo.run/>。

但是现在还没有完善的 Token 授权机制，所以第三方无法正常消费这些 API。

**Comment by AeroWang** [comment]
> /kind feature /area theme /area core
> 
> 其实 Halo 2.x 是提供了丰富的 API 的，可参考：https://demo.halo.run/webjars/swagger-ui/index.html。
> 
> 但是现在还没有完善的 Token 授权机制，所以第三方无法正常消费这些 API。

:tada:这里提供了一个[demo](https://codesandbox.io/p/sandbox/awesome-cache-6i29kh)，可以简单的使用这些接口，不知道这样是否完全可行🤣。
这种情况可能不适用于客户端请求的情况。demo 使用的 Next.js，在服务端请求

**Comment by ruibaby** [comment]
@AeroWang 简单看了一下，但我感觉这样有点繁琐，目前你可以考虑使用 Basic Auth 的方式来鉴权，比如：

Axios:

```ts
const axiosInstance = axios.create({
  baseURL: "http://localhost:8090",
  withCredentials: true,
  auth: {
    username: 'admin',
    password: 'halo2048',
  },
})
```

Fetch:

```ts
fetch(url, {
  method:'GET', 
  headers: {
    'Authorization': 'Basic ' + base64.encode(username + ":" + password) 
  } 
}).then()
```

需要注意这不能在 client 中进行请求，可能会导致鉴权信息泄露。此外，这也仅仅是目前在 server 端最合适的方式，最终还是期望可以实现 Personal Access Token 来实现接口鉴权。

**Comment by AeroWang** [comment]
@JohnNiang 2.x现在可以用这样的鉴权方式啊，如果可以这样，那我上面那个例子确实繁琐了🤣

**Comment by ruibaby** [comment]
> @JohnNiang 2.x现在可以用这样的鉴权方式啊，如果可以这样，那我上面那个例子确实繁琐了🤣

可以，但后面可能默认会关闭这种方式。

**Comment by AeroWang** [comment]
> 可以，但后面可能默认会关闭这种方式。

@ruibaby 👌🏻。接口返回的字段结构短时间内会有大变动吗？

**Comment by ruibaby** [comment]
> 

不会，整个 2.x 可能都不会有大的变动。

**Comment by AeroWang** [comment]
> 不会，整个 2.x 可能都不会有大的变动。

阔以

**Comment by ruibaby** [comment]
/close

see https://github.com/halo-dev/halo/issues/3661
