### ISSUE TITLE
默认编辑器支持 music 控件

### ISSUE THREAD

**Issue by HimiCos** [halo-dev/halo#3547]
### 你当前使用的版本

2.3.2

### 描述一下此特性

文章中支持添加音樂控件。

### 附加信息

![music](https://user-images.githubusercontent.com/92566148/226532324-47533e46-81ff-4177-a977-72c62291d867.jpeg)

**Comment by ruibaby** [comment]
目前编辑器是支持原生的 Audio 标签的：

<img width="1111" alt="image" src="https://user-images.githubusercontent.com/21301288/226550541-25654a04-6f3e-4fb3-b836-d6dc3421ffa1.png">
<img width="470" alt="image" src="https://user-images.githubusercontent.com/21301288/226550588-fd6c418c-65da-43b6-bfe7-3e7c2a072bed.png">

如果期望对这个原生的 audio 标签做一些样式定制或者功能定制，可能需要主题或者插件支持。

/triage needs-information

**Comment by HimiCos** [comment]
收到
