### ISSUE TITLE
评论功能感觉不好用，不登录就没法评论

### ISSUE THREAD

**Issue by YSoul-Rp** [halo-dev/halo#3566]
### 你当前使用的版本

2.3.2

### 描述一下此特性

我记得1.x版本的时候可以根据github和一个网站，可以获取头像，也可以直接评论，挺好用的但是2.x就不行了

**Comment by ruibaby** [comment]
<img width="890" alt="image" src="https://user-images.githubusercontent.com/21301288/227093373-8b695bea-d4ad-4b43-b5f6-21448292903b.png">

取消勾选即可。

/kind support

**Comment by YSoul-Rp** [comment]
感谢(,,#ﾟДﾟ)
