### ISSUE TITLE
oss配置bucket新增一个手动填写bucket名称的入口

### ISSUE THREAD

**Issue by githubshansheng** [halo-dev/halo#357]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [ ] [Halo 论坛](https://bbs.halo.run)
- [ ] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [ ] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [x] 添加新的特性或者功能
- [ ] 请求技术支持

**Comment by githubshansheng** [comment]
![image](https://user-images.githubusercontent.com/22028938/67975273-bcff3000-fc4e-11e9-83ac-313afbe3e7c2.png)
希望能够新增输入框，不能局限于国内cdn

**Comment by JohnNiang** [comment]
某些 oss 似乎至提供了这么几个 regions。

**Comment by githubshansheng** [comment]
> 某些 oss 似乎至提供了这么几个 regions。

可以提供常用的几个OSS选项，然后多出一个其他选项，使个别OSS区域可以通过填写方式配置

**Comment by ruibaby** [comment]
已支持，https://github.com/halo-dev/halo-admin/commit/b2ad98ed75a31e1fe48897b5d68b450d6aa783a7

可选也可自己填。
