### ISSUE TITLE
申请添加一个定时保存的功能，比如15分钟保存一次，今天写了半个多小时结果不小心键盘按到返回上一页的快捷键=-= 啥也没了

### ISSUE THREAD

**Issue by mikutown** [halo-dev/halo#358]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [x] 添加新的特性或者功能
- [ ] 请求技术支持

**Comment by ruibaby** [comment]
@mikutown 之前是有过自动保存的尝试，但是所带来的问题更多。所以目前我们已经去掉了这个功能。目前的解决方案是提供了保存的快捷键，你可以使用 ctrl s 来保存到草稿，随时按一下就行了。

**Comment by ruibaby** [comment]
@ruibaby macOS 下为 command s

**Comment by mikutown** [comment]
收到
