### ISSUE TITLE
除了主页和后台能进入，其余页面都是打不开

### ISSUE THREAD

**Issue by woody3rd** [halo-dev/halo#3583]
### 是什么版本出现了此问题？

2.3.0

### 使用的什么数据库？

MySQL 5.7

### 使用的哪种方式部署？

Docker Compose

### 发生了什么？

服务器和域名都是国外的，8090端口开放了，采用aapanel面板反向代理了
问题：除了主页和后台能通过域名进入，其余页面点开都无法访问，帮忙指点下。

<img width="1469" alt="image" src="https://user-images.githubusercontent.com/29486582/227701225-8cbecd1d-eeb9-4854-82c7-a86a38f874d2.png">
<img width="1504" alt="image" src="https://user-images.githubusercontent.com/29486582/227701203-38071e00-ceda-4bde-bcbe-f0a92b4402d4.png">

**Comment by HimiCos** [comment]
這裡和你現在的域名對不上

![8A5FF550-E6A2-41BB-9C33-5F3712085B63](https://user-images.githubusercontent.com/92566148/227720779-76e6d8fb-f305-43c4-8c27-d253db07231f.jpeg)

解決方案：
1. 停止並刪除容器
2. 重新創建一個容器，URL 記得改
```
docker run \
  -it -d \
  --name halo \
  -p 8090:8090 \
  -v ~/.halo2:/root/.halo2 \
  halohub/halo:2.2 \
  --halo.external-url=http://記得改:8090/ \
  --halo.security.initializer.superadminusername=admin \
  --halo.security.initializer.superadminpassword=P@88w0rd
```

**Comment by HimiCos** [comment]
看下系統概覽

**Comment by ruibaby** [comment]
没有足够的信息以判断，我暂时关闭此 issue，如果后续有补充可以随时打开。

/close
