### ISSUE TITLE
固定目錄在頁面右側

### ISSUE THREAD

**Issue by HimiCos** [halo-dev/halo#3584]
### 你当前使用的版本

2.3.2

### 描述一下此特性

目錄可不可以做成固定定位，這樣目錄可以跟著頁面滾動。
移動端似乎已經是了。

**Comment by ruibaby** [comment]
请说明具体位置。

/triage needs-information

**Comment by HimiCos** [comment]
### 解決方案
目前我能想到的較好解決方案是：**與移動端保持一致**
在右下角添加一個目錄按鈕，點擊展開 
> ![CleanShot 2023-03-26 at 16 58 55@2x](https://user-images.githubusercontent.com/92566148/227765861-1c698a74-94f2-44ce-9546-83cd83413891.png)
### 補充一點為什麼要改這個佈局
> 如視頻中所見，點擊 ```雪碧圖``` 會定位到這個標題，而 ```目錄``` 會消失在頁面中
往上找目錄，目錄又會自動收縮起來，所以不能在頁面中看到完整的目錄

> https://user-images.githubusercontent.com/92566148/227766133-49e2e80e-d5c4-45f9-876e-fa8c318dc472.mp4

**Comment by ruibaby** [comment]
@HimiCos 这种问题只能向主题作者提交建议，Halo 无法控制到这个地方。

/kind support

**Comment by HimiCos** [comment]
默認主題也存在這個問題，右側目錄不會固定住
