### ISSUE TITLE
博客评论区增加支持markdown语法

### ISSUE THREAD

**Issue by kanon-H** [halo-dev/halo#3589]
### 你当前使用的版本

2.3.0

### 描述一下此特性

你好，希望博客文章中，留言板等回复区增加像wordpress一样的Markdown语法支持

**Comment by itscolor** [comment]
支持~

**Comment by kanon-H** [comment]
> 支持~

请教一下，现在已经支持了吗？要怎么操作呀

**Comment by ruibaby** [comment]
See https://github.com/halo-dev/plugin-comment-widget/issues?q=is%3Aissue+is%3Aopen+Markdown

/close
