### ISSUE TITLE
克隆项目后启动抛错

### ISSUE THREAD

**Issue by haodedong** [halo-dev/halo#359]
+ 克隆项目后启动抛错
``` 
Plugin [id: 'org.springframework.boot', version: '2.1.7.RELEASE'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'org.springframework.boot:org.springframework.boot.gradle.plugin:2.1.7.RELEASE')
  Searched in the following repositories:
    Gradle Central Plugin Repository
```
是我的gradle不对吗

**Comment by ruibaby** [comment]
@haodedong https://halo.run/develop/application/start.html#%E6%89%80%E9%9C%80%E8%A6%81%E7%9A%84%E7%8E%AF%E5%A2%83

**Comment by JohnNiang** [comment]
gradle 版本可能需要升级至 5.2.1 及以上。

**Comment by haodedong** [comment]
我换成maven了，现在还好


| |
东
邮箱：haodedong1996@163.com
|

签名由 网易邮箱大师 定制

在2019年11月03日 09:46，John Niang 写道：

gradle 版本可能需要升级至 5.2.1 及以上。

**Comment by jiaogug** [comment]
我的也出现了同样的错误，请问怎么解决呢，或者怎么在intellij idea中升级gradle版本呢

**Comment by ruibaby** [comment]
抱歉我们从今天开始不会再处理这种问题，本项目的目的在于使用，并非提供学习。你们如果要在本地运行，文档已经提供了相关说明。解答这种问题会消耗我们大量精力，不如放在 Halo 本身更好。望谅解。

**Comment by haodedong** [comment]
在gitee中 有人搞了一个老版本的halo，是maven的 启动不报错


| |
东
邮箱：haodedong1996@163.com
|

签名由 网易邮箱大师 定制

在2019年12月05日 18:01，jiaogug 写道：

我的也出现了同样的错误，请问怎么解决呢，或者怎么在intellij idea中升级gradle版本呢
