### ISSUE TITLE
Local 认证方式的开关初始化状态为关闭

### ISSUE THREAD

**Issue by wan92hen** [halo-dev/halo#3602]
### 是什么版本出现了此问题？

2.4.0-rc.1

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

Local 认证方式开关默认为关闭状态，操作一次其他认证方式的开关后开关才变为开启状态。
![image](https://user-images.githubusercontent.com/27671436/228117231-c59a4179-e1de-4435-8cd5-99a014cd26d8.png)

**Comment by ruibaby** [comment]
![image](https://user-images.githubusercontent.com/21301288/228124635-568fe966-46b1-4a4f-916d-fa2b05b41b8d.png)

/area core
/kind bug
/assign @guqing
