### ISSUE TITLE
提供代表 v2 最新版本的镜像标签

### ISSUE THREAD

**Issue by wan92hen** [halo-dev/halo#3611]
### 描述一下此特性

由于直接给最新镜像添加 latest 标签可能会影响使用 1.x 版本的用户，在不知情的情况下升级到 2.x。
建议提供一个镜像标签例如 `v2` 表示当前 2.x 版本中的最新版本，这样在 Readme 及文档中可以直接使用这个标签安装到最新的已发布版本，不需要再去文档中修改标签值。同时用户升级时也可以直接更新镜像，不需要修改镜像标签。

**Comment by JohnNiang** [comment]
目前 Halo 的 Docker 镜像已经有类似 2.x 的标签，代表这 2.x.y 的最新版。

每个 Minor 版本的功能是有差异的，如果用户在浏览特定版本（如：2.0）的文档，直接使用 `halohub/halo.2` 的镜像可能导致实际的运行效果和文档不一致。

我们推荐用户在生产环境使用特定的版本（如：`halohub/halo:2.3.2`），而不是 `halohub/halo:2.x` 或者 `halohub/halo:2`。

**Comment by ruibaby** [comment]
已经在文档修改为使用类似于 2.4 这样的标签。

see https://github.com/halo-dev/docs/pull/207

/close
