### ISSUE TITLE
代码段可以自动换行吗

### ISSUE THREAD

**Issue by txcjhaz** [halo-dev/halo#362]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [x] 请求技术支持

代码段可以自动换行吗

**Comment by ruibaby** [comment]
@txcjhaz 能否再详细描述一下

**Comment by txcjhaz** [comment]
@ruibaby 
![image](https://user-images.githubusercontent.com/32667852/68099821-9ae00900-feff-11e9-86ed-fc291a0c1dcb.png)
类似于typora这种
![image](https://user-images.githubusercontent.com/32667852/68099840-b9460480-feff-11e9-9d77-7cb7030395a5.png)

**Comment by ruibaby** [comment]
@txcjhaz 看主题支持了
