### ISSUE TITLE
希望增加halo 2.0 备份/导出/导入 markdown文章的插件

### ISSUE THREAD

**Issue by cyolc932** [halo-dev/halo#3632]
### 描述一下此特性

希望增加halo 2.0 备份/导出/导入markdown文章的插件
从静态架构框架来的用户很需要这功能

**Comment by HappySnoopy** [comment]
同需要。正在搞h2迁移到MySQL的事儿，2.3.0版本halo，没法导出/导入文章，搞得很头疼。总不能真就从h2导出SQL文件再导入MySQL吧……

**Comment by Daixingdeng** [comment]
同需!  目前本地md无法迁移。  并且也需要halo的文章导出md，备份到代码库中。

**Comment by zzhao8053** [comment]
同需！

**Comment by shisuiyi** [comment]
同需

**Comment by itscolor** [comment]
是的呢，很需要，不想每次都敲代码备份。

**Comment by JohnNiang** [comment]
Hi @cyolc932 ，可以说一下关闭当前 Issue 的原因么？

社区成员都期望支持“备份/导出/导入”的功能，建议重新打开，等待社区一起解决这个问题。

**Comment by cyolc932** [comment]
> Hi @cyolc932 ，可以说一下关闭当前 Issue 的原因么？
> 
> 社区成员都期望支持“备份/导出/导入”的功能，建议重新打开，等待社区一起解决这个问题。

我的时间有限 换架构了

**Comment by JohnNiang** [comment]
理解。

我将重新打开当前 Issue，这个功能的呼声比较高。

/reopen

**Comment by Crany-web** [comment]
同需+1，做的笔记比较多不出这个功能或者插件想要全部搬到halo比较麻烦

**Comment by ruibaby** [comment]
实现一个这样的插件，具体可能需要解决的问题：

1. Frontmatter 解析，因为目前多数静态生成器的 Markdown 引擎的 Frontmatter 规则可能都不尽相同，可能需要支持让使用者配置。
2. Markdown 解析引擎，如何保证尽可能的兼容各个 Markdown 方言，还是提供可选项。
3. 使用场景考虑，需要考虑 **仅仅是迁移** 还是 **在本地写完之后导入到 Halo**，如果是后者，是否需要考虑更新的问题？
4. 导出功能：是否需要携带 Frontmatter，如何兼容各个平台，或者说是否要兼容。
5. 导出功能：是否需要支持默认富文本编辑器导出 Markdown，如何保证格式问题。

综上，我感觉更多的还是使用场景的问题，希望大家可以提出自己具体需要如何使用。等使用场景收集的差不多之后，我会考虑来开发这个插件。

**Comment by KitStarLee** [comment]
@ruibaby 感谢回复，我和@Crany-web 同样的需求，差不多都是 本地电脑有很多Markdown笔记文档，且比较多(一万左右)，想要批量上传到Halo文章中，减少工作量，不然 1万的得好多好多天

**Comment by KitStarLee** [comment]
我的区别可能是 那些 Markdown笔记文档是我用程序解析其他文档进行转化的。所以理论是只有平台支持批量上传，无论格式是什么，都能满足我的需求。（我生成平台支持的格式即可）

**Comment by ColanCN** [comment]
如果能有完整导出博客备份就好了

**Comment by redquilt** [comment]
+1

**Comment by Daixingdeng** [comment]
1.md导入或者pdf导入(倾向这个，关于图片视频类的halo能处理就nice了)
2.导出md备份(以目录结构布局，方便搭建静态博客上传到代码仓库备份存档，能够实现博客更代码仓库内容实时或者定时同步就nice了)
3.要是再支持从csdn或者开源中国博客社区里面的文章迁移就更好了

**Comment by JohnNiang** [comment]
Hi @Daixingdeng ，短期内我将尝试实现整站的备份、导出和导入。关于 Markdown 的导入和导出暂时不在计划呢，如果谁有兴趣，非常欢迎开发对应的插件来完成定制化的功能。

**Comment by Daixingdeng** [comment]
@JohnNiang     我有兴趣参与，但我不知道如何参与进来。针对这方面我需要做哪些准备工作，包括 1: md pdf这些场景的难点 2: 如何贡献代码，有什么约束。有相关资料可以推荐一下吗

**Comment by JohnNiang** [comment]
> @JohnNiang 我有兴趣参与，但我不知道如何参与进来。针对这方面我需要做哪些准备工作，包括 1: md pdf这些场景的难点 2: 如何贡献代码，有什么约束。有相关资料可以推荐一下吗

非常欢迎！关于如何贡献代码建议参考 <https://docs.halo.run/contribution/pr>。

在动手开发之前，建议现在 Issue 中详细描述你的方案，大家一起 Review 后可进行下一步。

**Comment by JohnNiang** [comment]
关于备份和恢复功能的 Proposal 请参考：<https://github.com/JohnNiang/halo/blob/9921deb0768cb22fb4ba738e20fdc099f1678926/docs/backup-and-restore.md>。

Workaround 请参考：<https://github.com/halo-dev/halo/pull/4206>。

**Comment by pandalabme** [comment]
期待

**Comment by ougato** [comment]
同需

**Comment by JohnNiang** [comment]
在 Halo 2.8 中，已经实现了备份和恢复功能。具体请参考：<https://github.com/halo-dev/halo/pull/4206>。

导入/导出 markdown 文章的需求暂时不考虑。理由如下：

- 可通过 VSCode 插件实现。具体情参考：<https://marketplace.visualstudio.com/items?itemName=halo-dev.halo>。

当前 Issue 即将被关闭。如果有任何问题请随时重新打开。

/close

**Comment by Emisaka123** [comment]
迫切需要

**Comment by ColanCN** [comment]
> 如果能有完整导出博客备份就好了

这个功能貌似已进做到了，好评！

**Comment by o85757o** [comment]
希望大佬关注到这个需求
