### ISSUE TITLE
上传七牛云的图片无法正常加载

### ISSUE THREAD

**Issue by yfdoor** [halo-dev/halo#3636]
### 是什么版本出现了此问题？

2.3.2

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker

### 发生了什么？

存储策略添加了七牛云，配置好后，上传图片什么的都正常，但是图片详情中图片预览显示加载异常，下面的原始连接却可以点击访问，在编辑文章中，插入图片也无法看到预览。
![Screenshot_2023-03-30-06-41-49-083_com microsoft emmx](https://user-images.githubusercontent.com/32769281/228685131-90812c2d-1dd8-4d81-b99e-c3f00280fe63.jpg)
![Screenshot_2023-03-30-06-42-29-294_com microsoft emmx](https://user-images.githubusercontent.com/32769281/228685529-adbad09a-a1ac-4245-b130-83ea68777274.jpg)

**Comment by ruibaby** [comment]
可能是由于 CDN 设置了防盗链，建议在 CDN 厂商那里检查一下。

/triage needs-information

**Comment by yfdoor** [comment]
> 可能是由于 CDN 设置了防盗链，建议在 CDN 厂商那里检查一下。
> 
> /triage needs-information

就是普通的七牛云的账号，防盗链之类的也没有开启啊
![Screenshot_2023-03-31-14-08-11-481_com microsoft emmx](https://user-images.githubusercontent.com/32769281/229037437-7726f82b-df2f-44db-a701-618d6722b817.jpg)

**Comment by JohnNiang** [comment]
这里需要开启防盗链，并正确配置你的域名才能正常访问。
