### ISSUE TITLE
希望支持配置图片/附件上传目标路径

### ISSUE THREAD

**Issue by Liu-Ya** [halo-dev/halo#364]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [x] 添加新的特性或者功能
- [ ] 请求技术支持

希望支持配置图片/附件上传目标路径

**Comment by ruibaby** [comment]
@Liu-Ya 会考虑

**Comment by Liu-Ya** [comment]
感谢👍

Ryan Wang <notifications@github.com> 于2019年11月5日周二 下午12:18写道：

**Comment by wh469012917** [comment]
这个其实很重要的，不然都是放到根目录，

**Comment by ruibaby** [comment]
其实现在是支持的。

application.yaml

```yaml
halo:
  workDir: ${user.home}/.halo/
```

**Comment by ruibaby** [comment]
> 这个其实很重要的，不然都是放到根目录，

你所说的根目录也不是根目录，而是用户目录。

**Comment by JohnNiang** [comment]
> 这个其实很重要的，不然都是放到根目录，

我们将所有的数据文件都放在了一个目录下，主要是方便用户备份和转移。

**Comment by Liu-Ya** [comment]
> > 这个其实很重要的，不然都是放到根目录，
> 
> 我们将所有的数据文件都放在了一个目录下，主要是方便用户备份和转移。

`workDir` 对于我来说就够用了，当时在用户文档中没找到，希望完善`application.yaml`可配置内容的文档

**Comment by wh469012917** [comment]
@ruibaby 但是传到云存储，都是放在根目录的，建议云储存附件也可以支持目录

**Comment by ruibaby** [comment]
@wh469012917 你用的哪一个服务

**Comment by wh469012917** [comment]
@ruibaby 静态资源用的是腾讯云的，上传图片我看默认都是存储到根目录

**Comment by ruibaby** [comment]
@wh469012917 嗯 好的

**Comment by wh469012917** [comment]
@ruibaby 问一下 你们后台是用哪个UI框架，饿了吗？

**Comment by ruibaby** [comment]
@wh469012917 Ant Design 没饿

**Comment by ruibaby** [comment]
@wh469012917 腾讯云和阿里云现在都已支持设置上传目录，等待下个版本的更新。
