### ISSUE TITLE
文章引入链接图片有些无法正常显示

### ISSUE THREAD

**Issue by wmq1013** [halo-dev/halo#3646]
### 是什么版本出现了此问题？

2.3

### 使用的什么数据库？

MySQL 5.7

### 使用的哪种方式部署？

Docker

### 在线站点地址

https://www.unique.fyi/archives/halotu-pian-xian-shi-wen-ti

### 发生了什么？

![image](https://user-images.githubusercontent.com/76677995/229009083-1d9030e6-f636-4558-abfc-38e4fd297b00.png)

下面的图片是语雀的线上附件，在typora中使用这种写法是可以正常显示的
使用img标签也是一样的结果：
![image](https://user-images.githubusercontent.com/76677995/229009135-19a9d29f-42a0-4180-9fd7-eeb4ea7360de.png)

**Comment by ruibaby** [comment]
可能和 https://github.com/halo-dev/halo/issues/3064 是一样的问题，目前 2.4.0 已经支持配置 referrer-policy。

https://github.com/halo-dev/halo/pull/3614
