### ISSUE TITLE
新增插件啟用不生效

### ISSUE THREAD

**Issue by HimiCos** [halo-dev/halo#3660]
### 是什么版本出现了此问题？

2.4.0

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

![CleanShot 2023-03-31 at 20 40 46@2x](https://user-images.githubusercontent.com/92566148/229123053-f0c4e16f-5fa1-4b7b-8a28-ec35d03b9df1.png)

**Comment by ruibaby** [comment]
刷新之后状态也没有发生改变吗？ 如果依旧如此，可以提供一下日志以供排查。

/triage needs-information

**Comment by HimiCos** [comment]
重新部署 docker 後解決了
