### ISSUE TITLE
Console 端主題設置無效

### ISSUE THREAD

**Issue by HimiCos** [halo-dev/halo#3666]
### 是什么版本出现了此问题？

2.4.0

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

## 詳細信息

前端是有生效的，但是想要取消勾選只有一個選項的設定，就無法操作了。

https://user-images.githubusercontent.com/92566148/229287231-54273b70-84b2-4cb5-bd77-91880dd1924a.mp4

**Comment by ruibaby** [comment]
可以复现，我这边发现在 FormKit Schema 定义的 boolean 类型，但表单最终得到的值却变成了 string 类型，目前还不知道原因。

<img width="898" alt="image" src="https://user-images.githubusercontent.com/21301288/229302975-d11609f5-96aa-4050-9a9a-c4bb42e36b08.png">

/area console
/kind bug
