### ISSUE TITLE
出现开关打开不显示的问题

### ISSUE THREAD

**Issue by Cxy-an** [halo-dev/halo#3667]
### 是什么版本出现了此问题？

2.4.0

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 在线站点地址

https://lvye.asia

### 发生了什么？

在主题设置内的开关会出现点击开，不弹出启动内容，并且按钮没了。(手机端)

### 相关日志输出

```shell
没有日志
```

### 附加信息

![Screenshot_20230401_211730](https://user-images.githubusercontent.com/105652758/229291707-89e042e2-a386-4c65-b8eb-daed7dc91428.jpg)

**Comment by ruibaby** [comment]
/triage duplicate

see https://github.com/halo-dev/halo/issues/3666

/close
