### ISSUE TITLE
第三方登录插件无法使用

### ISSUE THREAD

**Issue by Cxy-an** [halo-dev/halo#3670]
### 是什么版本出现了此问题？

2.4.0

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 在线站点地址

https://lvye.asia

### 发生了什么？

使用第三方登陆/绑定时,无法弹出正确页面,出现`/login?error`
如图
![Screenshot_20230402_160223_com huawei himovie](https://user-images.githubusercontent.com/105652758/229340369-a54f063d-f3fc-47f1-9781-e4bf3a38f2c4.jpg)

https://user-images.githubusercontent.com/105652758/229340382-171d774b-c67b-4893-810e-daf92d82c22e.mp4

### 相关日志输出

```shell
https://lvye.asia/#/login?error
```

**Comment by JohnNiang** [comment]
建议提供一下对应的日志信息。

/triage needs-information

**Comment by guqing** [comment]
是否使用了 CDN 回源到服务器，可能对协议无法识别到 https，你可以将 github 那边的回调地址协议改为 http 试试

**Comment by JohnNiang** [comment]
/reopen

I will fix this issue soon.

/assign

**Comment by Cxy-an** [comment]
> 是否使用了 CDN 回源到服务器，可能对协议无法识别到 https，你可以将 github 那边的回调地址协议改为 http 试试

改了现在出现
`Validation error(s) : spec: Field 'displayName' is required. (code: 1026) From: spec.<#/components/schemas/UserConnectionSpec>.<required> of schema auth.halo.run/v1alpha1/UserConnection.`

**Comment by Cxy-an** [comment]
升级2.4.2问题依然未解决

**Comment by jkjoy** [comment]
同样的情况
