### ISSUE TITLE
2.4版本本地存储策略无法编辑

### ISSUE THREAD

**Issue by 20020616** [halo-dev/halo#3674]
### 是什么版本出现了此问题？

2.4

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker Compose

### 发生了什么？

docker-compose更新完2.4版本以后无法新建本地存储策略，无法编辑本地存储策略。打开编辑或者新建界面就会卡死。

**Comment by JohnNiang** [comment]
/close

Close in favor of https://github.com/halo-dev/halo/issues/3662
