### ISSUE TITLE
首篇文章刪除後依然會被搜索到

### ISSUE THREAD

**Issue by HimiCos** [halo-dev/halo#3685]
### 是什么版本出现了此问题？

2.4.1

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

重構索引後依然能夠搜索到首篇文章，其他刪除的文章已經搜索不到了，但是這篇也刪除了。
![CleanShot 2023-04-03 at 13 27 51@2x](https://user-images.githubusercontent.com/92566148/229419230-cab7b8b7-583e-4cbb-b2d8-6148e216b3e9.png)

**Comment by JohnNiang** [comment]
/close

Close in favor of https://github.com/halo-dev/halo/issues/3121
