### ISSUE TITLE
更新了2.4.1，数据全没了，但是服务器文件夹都在，后台直接是全新安装的。

### ISSUE THREAD

**Issue by leealu** [halo-dev/halo#3688]
### 是什么版本出现了此问题？

2.4.1

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker Compose

### 在线站点地址

blog.801100.tk

### 发生了什么？

更新了2.4.1，数据全没了，但是服务器文件夹都在，后台直接是全新安装的。UPload下的文件也不显示，附件里面都是空的怎么恢复？

**Comment by ruibaby** [comment]
/triage needs-information

请提供完整的复现步骤，包括你部署的方式和升级的方式。

**Comment by leealu** [comment]
Docker Compose直接升级的

**Comment by JohnNiang** [comment]
> Docker Compose直接升级的

这样回复是无法解决你的问题的。

**Comment by leealu** [comment]
> > Docker Compose直接升级的
> 
> 这样回复是无法解决你的问题的。

就是按照官方给的方法一步一步来的·官方的我还要复制一遍吗？

**Comment by JohnNiang** [comment]
按照官方提供的步骤，是无法复现你的问题的。

而且官方文档提供了多种安装方式，我们不知道你具体采用了哪种，具体作了哪些修改。

**Comment by leealu** [comment]
> 按照官方提供的步骤，是无法复现你的问题的。
> 
> 而且官方文档提供了多种安装方式，我们不知道你具体采用了哪种，具体作了哪些修改。

官方的Docker Compose升级步骤
