### ISSUE TITLE
移动端后台带3个点的设置都无法进行

### ISSUE THREAD

**Issue by leealu** [halo-dev/halo#3689]
### 是什么版本出现了此问题？

2.4.1

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker Compose

### 在线站点地址

blog.801100.tk

### 发生了什么？

移动端后台带3个点的设置都无法进行

**Comment by ruibaby** [comment]
目前 Console 还未对移动端做适配，可以关注一下：https://github.com/halo-dev/halo/issues/2699

/triage duplicate
/close
