### ISSUE TITLE
请问如果我修改了数据库密码，该怎么样配置我的halo呢？我修改了配置文件直接jar halo的jar包依然报错502，数据库密码被坏人改了，还好没有被删库。。想把mysql密码彻底换了，已经把我吓得把能关的端口全都关闭了

### ISSUE THREAD

**Issue by mikutown** [halo-dev/halo#369]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [x] 请求技术支持

**Comment by mikutown** [comment]
就是halo已经配置好了但是我修改了我的数据库密码，这时要怎么操作 最好出一个教程。。谢谢大佬

**Comment by ruibaby** [comment]
MySQL？ 那你提供一下 application.yaml(隐藏下密码之类的)，再看看你在本地是否能正确连接到 MySQL。

**Comment by ruibaby** [comment]
@mikutown 另外，提供一下异常信息。
