### ISSUE TITLE
第三方登陆错误

### ISSUE THREAD

**Issue by leealu** [halo-dev/halo#3690]
### 是什么版本出现了此问题？

2.4.1

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker Compose

### 在线站点地址

blog.801100.tk

### 发生了什么？

绑定显示
500
Internal Server Error
ConfigMap oauth2-github-config not found

**Comment by ruibaby** [comment]
/triage needs-information

有正确配置该认证方式吗？

<img width="664" alt="image" src="https://user-images.githubusercontent.com/21301288/229669391-4f627eac-4843-4ca4-99ba-23e5de0caf98.png">

**Comment by leealu** [comment]
> /triage needs-information
> 
> 有正确配置该认证方式吗？
> 
> <img alt="image" width="664" src="https://user-images.githubusercontent.com/21301288/229669391-4f627eac-4843-4ca4-99ba-23e5de0caf98.png">

这个在哪里设置。。。别嫌弃啊小白，哈哈

**Comment by JohnNiang** [comment]
Hi @leealu ，建议参考：<https://github.com/halo-sigs/plugin-oauth2#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95>。

**Comment by ruibaby** [comment]
> 这个在哪里设置。。。别嫌弃啊小白，哈哈

点击 GitHub 的标题。

<img width="707" alt="image" src="https://user-images.githubusercontent.com/21301288/229671034-3b0bb7ee-45b6-4355-8752-3e3fefb110df.png">

**Comment by leealu** [comment]
> > 这个在哪里设置。。。别嫌弃啊小白，哈哈
> 
> 点击 GitHub 的标题。
> 
> <img alt="image" width="707" src="https://user-images.githubusercontent.com/21301288/229671034-3b0bb7ee-45b6-4355-8752-3e3fefb110df.png">

谢谢，设置完了·然后点github登陆，出现到/console/#/login?error，网页转个圈不动

**Comment by leealu** [comment]
> > 这个在哪里设置。。。别嫌弃啊小白，哈哈
> 
> 点击 GitHub 的标题。
> 
> <img alt="image" width="707" src="https://user-images.githubusercontent.com/21301288/229671034-3b0bb7ee-45b6-4355-8752-3e3fefb110df.png">

绑定的时候一直在刷新转圈·我看论坛里说把https的S去掉·返回被github定向次数太多

**Comment by ruibaby** [comment]
@leealu 请提供更多信息以供大家判断，包括但不限于：

1. GitHub 的 OAuth 配置，主要是 `Authorization callback URL`。
2. Halo 的日志，可以在 Console 的概览页面下载。

**Comment by leealu** [comment]
> @leealu 请提供更多信息以供大家判断，包括但不限于：
> 
> 1. GitHub 的 OAuth 配置，主要是 `Authorization callback URL`。
> 2. Halo 的日志，可以在 Console 的概览页面下载。

1.<img width="548" alt="QQ20230404-185902@2x" src="https://user-images.githubusercontent.com/103651858/229771796-76cb5217-6434-4b2c-a54a-7d7e5db94768.png">
2.[halo-log-2023-04-04 18_57.log](https://github.com/halo-dev/halo/files/11147695/halo-log-2023-04-04.18_57.log)

**Comment by ruibaby** [comment]
@leealu 从日志来看似乎只有配置未找到的问题。多次重定向可能是因为你的 Halo 反向代理设置了 http 转到 https，建议将 `Authorization callback URL` 设置为 https 协议然后再捕获一下日志。另外，建议再尝试配置一下 Gitee 试试。

**Comment by leealu** [comment]
> @leealu 从日志来看似乎只有配置未找到的问题。多次重定向可能是因为你的 Halo 反向代理设置了 http 转到 https，建议将 `Authorization callback URL` 设置为 https 协议然后再捕获一下日志。另外，建议再尝试配置一下 Gitee 试试。

1.<img width="563" alt="QQ20230404-203728@2x" src="https://user-images.githubusercontent.com/103651858/229794432-ed48b4b3-7373-409d-91e8-e6aee1f0751f.png">

2.[halo-log-2023-04-04 20_38.log](https://github.com/halo-dev/halo/files/11148582/halo-log-2023-04-04.20_38.log)


改成https了以后不停地跳转页面,但是就是不跳,一直在执行跳转

**Comment by guqing** [comment]
> 1.<img alt="QQ20230404-203728@2x" width="563" src="https://user-images.githubusercontent.com/103651858/229794432-ed48b4b3-7373-409d-91e8-e6aee1f0751f.png">

从图中看你的回调地址填写的有问题，你填写的是认证地址，需要注意一下改用下面的地址否则会循环
<img width="979" alt="image" src="https://user-images.githubusercontent.com/38999863/230388961-fe8ae014-ca7b-40a4-a5d1-ad5ee060272a.png">

**Comment by leealu** [comment]
> > 1.<img alt="QQ20230404-203728@2x" width="563" src="https://user-images.githubusercontent.com/103651858/229794432-ed48b4b3-7373-409d-91e8-e6aee1f0751f.png">
> 
> @leealu 从图中看你的回调地址填写的有问题，你填写的是认证地址，需要注意一下改用下面的地址否则会循环 <img alt="image" width="979" src="https://user-images.githubusercontent.com/38999863/230388961-fe8ae014-ca7b-40a4-a5d1-ad5ee060272a.png">

我没看懂你想表达什么，你给我一个你认为对的地址，我看看你想表达什么
