### ISSUE TITLE
新建站点却出现 "已删除用户" 字样 且无法删除

### ISSUE THREAD

**Issue by hexWars** [halo-dev/halo#3694]
### 是什么版本出现了此问题？

Halo1.4.1  theme-butterfly2.0.5

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker

### 在线站点地址

很遗憾，是局域网

### 发生了什么？

如图
![image](https://user-images.githubusercontent.com/61684793/229777049-30161a21-cd07-4273-8efc-7ed2a7c3f58e.png)
只有在文章页面的作者处才能看见

用户页面看不见，所以删不掉

我感觉并不是主题的问题，所以来提issue了

安装完主题就是这个样子

> 可能的原因：我之前局域网中安装过Halo2了，只是删掉了，然后重装，或许是遗留文件的问题

感谢你们的开源贡献

**Comment by hexWars** [comment]
补充一下，我使用的是1panel进行安装的

**Comment by ruibaby** [comment]
尝试在主题设置中配置一下作者唯一标识这个选项。因为目前 Halo 是多用户，没有向主题提供一个全局的用户，所以这个主题做了这样的设置。 

https://github.com/dhjddcn/halo-theme-butterfly/blob/5ee927e0f612bce9b8e83fad3dd45c9365ee8ec5/settings.yaml#L10

/kind support

**Comment by hexWars** [comment]
OK解决了，我的办法是重置主题即可
