### ISSUE TITLE
chrome浏览器访问注册界面，元素重叠问题

### ISSUE THREAD

**Issue by hughding** [halo-dev/halo#3695]
### 是什么版本出现了此问题？

2.4.0

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 在线站点地址

https://demo.halo.run/

### 发生了什么？

chrome浏览器直接访问https://demo.halo.run/ 站点的注册界面，“已有账号 立即登录”与“简体中文”文字重叠。如下图所示：
![image](https://user-images.githubusercontent.com/9402574/230003377-97dc63cb-f088-487e-98fa-4a68e2c94aca.png)

Chrome浏览器显示比例：100%。
windows显示器设置如下图：
![image](https://user-images.githubusercontent.com/9402574/230003692-9cd104a2-dfd7-4838-a756-8b9f358a163a.png)

**Comment by ruibaby** [comment]
@hughding 有兴趣的话可以参与优化一下。
