### ISSUE TITLE
外部访问地址无法修改

### ISSUE THREAD

**Issue by Crillerium** [halo-dev/halo#3696]
### 是什么版本出现了此问题？

2.4.0

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 在线站点地址

https://crillerium.com/

### 发生了什么？

在安装完毕后，外部访问地址无法修改，没办法在以后切换域名

### 附加信息

![Screenshot_2023-04-05-11-48-23-14](https://user-images.githubusercontent.com/96243292/230024518-c356ed45-43c3-4a1d-9db2-0414e4188eee.jpg)

**Comment by ruibaby** [comment]
修改容器的启动参数 `--halo.external-url`，然后重建容器即可，重启之后所有的访问链接都会自动更改。但是目前无法自动修改已保存的内容，比如文章中引用的附件地址。

如果考虑到后面可能会更换域名或者解析多个域名，你可以考虑将 `--halo.external-url` 设置为 `/`，可能我们后续会默认使用 `/`，参考：https://github.com/halo-dev/halo/pull/3655

/kind support
