### ISSUE TITLE
查询不存在的标签时服务器返回500问题

### ISSUE THREAD

**Issue by TYQPS** [halo-dev/halo#370]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [ ] [Halo 使用文档](https://halo.run/docs)
- [ ] [Halo 论坛](https://bbs.halo.run)
- [ ] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

访问不存在的博客类别，如xxx.com/categories/notexist
服务会抛出NotFoundException，但是没有进行相应处理，导致服务器返回的是500 Internal Server Error。

**Comment by JohnNiang** [comment]
请问你当前所部署的 halo 的版本是多少呢？

**Comment by JohnNiang** [comment]
我看到你的问题似乎已经解决了。
