### ISSUE TITLE
直接全选复制md语法的文档无法识别自动转化。

### ISSUE THREAD

**Issue by rookiehander** [halo-dev/halo#3702]
### 你当前使用的版本

2.0.4

### 描述一下此特性

![image](https://user-images.githubusercontent.com/61374918/230302154-6ddc58e8-abb9-4bef-9e18-57410e7f2659.png)
直接编写md文档。
比如: ## 会被识别成二级标题。
但是复制一个文档过来，无法识别出来。

### 附加信息

![image](https://user-images.githubusercontent.com/61374918/230302394-41ee8568-8765-4e45-8e25-cdbb08568422.png)

**Comment by JohnNiang** [comment]
/triage needs-information

从图片和文字描述没有看到有什么不同。

**Comment by rookiehander** [comment]
### 在编辑器里面应该给被识别为三级标题，可以写一些试试。``` 在md编辑器被识别为代码。

**Comment by ruibaby** [comment]
默认编辑器本身不支持 Markdown，如果你需要使用 Markdown 编写，你需要安装额外的插件：https://github.com/halo-sigs/awesome-halo
