### ISSUE TITLE
修改设置的任意内容，保存后主题会自动切换到Earth默认主题

### ISSUE THREAD

**Issue by jiewenhuang** [halo-dev/halo#3704]
### 是什么版本出现了此问题？

2.4.1

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

修改设置的任意内容，保存后主题会自动切换到Earth默认主题
<img width="1212" alt="image" src="https://user-images.githubusercontent.com/68629578/230527628-a24eda23-41bf-4d56-914c-3aed691fc4eb.png">
<img width="1472" alt="image" src="https://user-images.githubusercontent.com/68629578/230527711-8010dd53-9b98-4fc8-b59c-c3683f1b1d84.png">

**Comment by ruibaby** [comment]
/triage duplicate

see https://github.com/halo-dev/halo/issues/3673

/close
