### ISSUE TITLE
我如何将项目导入到idea2018.1.5中呢

### ISSUE THREAD

**Issue by LuHanUp** [halo-dev/halo#371]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [x] 请求技术支持

**Comment by LuHanUp** [comment]
![image](https://user-images.githubusercontent.com/17198598/68572906-88d30d00-04a1-11ea-9999-a21bbd14e18d.png)

**Comment by ruibaby** [comment]
@LuHanUp 不支持2018.1.5。 https://halo.run/develop/application/start.html

**Comment by LuHanUp** [comment]
那idea最低版本是多少呢？

**Comment by ruibaby** [comment]
@LuHanUp 建议19+

**Comment by LuHanUp** [comment]
好的

**Comment by LuHanUp** [comment]
谢谢
