### ISSUE TITLE
docker 方式启动后无法使用

### ISSUE THREAD

**Issue by wuyongwen** [halo-dev/halo#3712]
### 是什么版本出现了此问题？

2.4 2.3 2.3.2

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

按照文档docker方式启动
```shell
sudo docker run \
  -it -d \
  --name halo \
  -p 3003:8090 \
  -v ~/.halo2:/root/.halo2 \
  halohub/halo:2.3 \
  --halo.external-url=http://localhost:3003/ \
  --halo.security.initializer.superadminusername=admin \
  --halo.security.initializer.superadminpassword=P@88w0rd
```

启动后没有报错。但是后台无法使用，

文章 页面 评论等页面显示加载中 
F12 chrome 请求数据返回
```json
{"page":0,"size":0,"total":0,"items":[],"last":true,"first":true,"hasNext":false,"hasPrevious":false,"totalPages":1}
```
可以新建发布文章，但是后台列表页还是没内容。

如图：

![image](https://user-images.githubusercontent.com/6308933/230585763-bc1fda23-a417-4829-a6a7-91eb3abfe06d.png)

**Comment by wuyongwen** [comment]
好像是chrome浏览器的锅，请求了演示站也是加载不出来。

![image](https://user-images.githubusercontent.com/6308933/230589590-b2e50e2e-17f1-4b25-b04d-bd23ee38a527.png)

**Comment by ruibaby** [comment]
你这边只是 Chrome 有问题吗？ 可以提供一下 Chrome 的版本，我们尝试复现一下。

/triage needs-information

**Comment by wuyongwen** [comment]
> 你这边只是 Chrome 有问题吗？ 可以提供一下 Chrome 的版本，我们尝试复现一下。
> 
> /triage needs-information

我重新启动了下chrome 可以了，可能是长时间未关机引起了某些问题。
