### ISSUE TITLE
未知错误

### ISSUE THREAD

**Issue by Steven-WZH** [halo-dev/halo#3721]
### 是什么版本出现了此问题？

2.4.2

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

日志

**Comment by Steven-WZH** [comment]
[halo-log-2023-04-08_08_01.log](https://github.com/halo-dev/halo/files/11182150/halo-log-2023-04-08_08_01.log)

**Comment by JohnNiang** [comment]
/triage needs-information

建议提供复现步骤。

**Comment by Steven-WZH** [comment]
这个问题是我正常使用的时候突然想看看日志的时候发现的
