### ISSUE TITLE
解决单篇过长得字段验证错误

### ISSUE THREAD

**Issue by 764763903a** [halo-dev/halo#373]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [x] 添加新的特性或者功能
- [x] 请求技术支持

```java
    private String originalContent;
    @Column(
        name = "format_content",
        columnDefinition = "text not null"
    )
修改为
    private String originalContent;
    @Column(
        name = "format_content",
        columnDefinition = "longtext not null"
    )
```
数据库手动修改

**Comment by ruibaby** [comment]
@764763903a 好的

**Comment by ruibaby** [comment]
已解决。
