### ISSUE TITLE
Halo2.4.0新建存储策略控制台报错，页面卡死

### ISSUE THREAD

**Issue by Chen2226** [halo-dev/halo#3753]
### 是什么版本出现了此问题？

2.4.0

### 使用的什么数据库？

MySQL 5.7

### 使用的哪种方式部署？

Docker Compose

### 发生了什么？

点击新建存储策略，就卡死了

### 相关日志输出

```shell
控制台报错：MException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
```

### 附加信息

![微信截图_20230414164346](https://user-images.githubusercontent.com/77887862/231992703-9fae0fa5-a795-445c-8e91-fbb8ce44da87.png)

**Comment by LIlGG** [comment]
/close

Close in favor of https://github.com/halo-dev/halo/issues/3662

**Comment by JohnNiang** [comment]
当前问题已解决，需要升级到 Halo 2.4.2。
