### ISSUE TITLE
附件上传后删除，本地文件修改后重新上传同名附件还是原文件

### ISSUE THREAD

**Issue by duanluan** [halo-dev/halo#3755]
### 是什么版本出现了此问题？

2.4.2

### 使用的什么数据库？

MariaDB

### 使用的哪种方式部署？

Docker

### 在线站点地址

https://blog.zhjh.top/

### 发生了什么？

因为现在 ByteMD 编辑器还没法粘贴图片，所以无奈只能手动上传附件。
上传后发现不对，所以删除了，然后对本地文件进行了修改并覆盖。
再次上传，待上传预览界面是对的，点击上传后发现还是上一次上传的图片。

**Comment by ruibaby** [comment]
未复现，可能是浏览器或者 Nginx 缓存导致的，可以尝试强制刷新页面或者清空网站的浏览器缓存。

/triage duplicate 

see https://github.com/halo-dev/halo/issues/3260
