### ISSUE TITLE
halo的测试版docker标签是什么

### ISSUE THREAD

**Issue by maizi08** [halo-dev/halo#3758]
### 你当前使用的版本

2.4.2

### 描述一下此特性

halo的测试版docker标签是什么

**Comment by ruibaby** [comment]
- https://github.com/halo-dev/halo/pkgs/container/halo-dev
- https://hub.docker.com/r/halohub/halo-dev/tags

这两个镜像都是在 main 分支提交之后就会更新镜像，不推荐直接使用。如果是 beta 或者 rc 版本的镜像和正式版本的镜像一致，比如：https://hub.docker.com/layers/halohub/halo/2.4.0-rc.1/images/sha256-19b481fae8f2f15ecfec851ada3fe8a97e81ecf09b657f108ae967f10a2560ed?context=explore

/kind support
