### ISSUE TITLE
2.4.2安装主题报错

### ISSUE THREAD

**Issue by slowslo** [halo-dev/halo#3759]
### 是什么版本出现了此问题？

2.4.2

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

拖主题zip到安装主题上传页面，提示：Theme Upgrade Error: Missing theme manifest file "theme.yaml" or "theme.yml".

### 相关日志输出

```shell
Theme Upgrade Error: Missing theme manifest file "theme.yaml" or "theme.yml".
```

**Comment by ruibaby** [comment]
从日志来看，你上传 zip 文件没有包含 theme.yaml 配置文件，需要确认这是否是支持 Halo 的主题。

/kind support
/triage needs-information

**Comment by slowslo** [comment]
我一开始也这样以为，然后我解压了主题的压缩包，发现是有thenm.yaml文件的，接着我直接上传解压后的文件到服务器，文件路径：/root/.halo2/themes下面，是不是不可以直接这样上传文件呢？
![image](https://user-images.githubusercontent.com/38916586/232322012-1f49e545-6c7f-4d4e-9eb1-d9f3f1c014cf.png)

**Comment by JohnNiang** [comment]
建议提供一下你上传的主题文件。

**Comment by slowslo** [comment]
https://github.com/dhjddcn/halo-theme-butterfly/releases/download/v2.0.5/theme-butterfly-dist.zip

theme.yaml：

`apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
    name: theme-butterfly
spec:
    displayName: Butterfly
    author:
        name: 小红
        website: 'https://dhjdd.cn'
    description: '一个Halo博客主题，Butterfly 🦋'
    logo: 'https://halo.run/logo'
    website: 'https://dhjdd.cn'
    repo: 'https://github.com/dhjddcn/halo-theme-butterfly.git'
    settingName: theme-butterfly-setting
    configMapName: theme-butterfly-configMap
    version: 2.0.5
    require: 2.0.0
`

**Comment by JohnNiang** [comment]
Hi @slowslo ，我在本地测试了，并未出现以上问题。测试步骤：

- 本地运行 Halo 2.4.2
```bash
docker run --rm -it -p 8090:8090 halohub/halo:2.4.2 --halo.security.initializer.superadminusername=admin --halo.security.initializer.superadminpassword=admin --halo.external-url="/"
```
- 从 https://github.com/dhjddcn/halo-theme-butterfly/releases/download/v2.0.5/theme-butterfly-dist.zip 安装主题
- 访问主题和文章页面

**Comment by ruibaby** [comment]
any updates?

**Comment by JohnNiang** [comment]
我将关闭此 Issue，如果有任何问题可随时重新打开。

/close
