### ISSUE TITLE
2.x 支持video、audio、ifraame

### ISSUE THREAD

**Issue by hugeleaf** [halo-dev/halo#3760]
### 你当前使用的版本

2.x

### 描述一下此特性

1、支持video、audio的原生插入或者markdown插入
**强烈需求**发布halo原生markdown，现有迁移方案中提到的markdown插件质量不如1.0

2、支持iframe的原生插入或者markdown插入
个人觉得如今的博客系统，内容不应该只有文字图片，这是只是最基本需求，应当支持视频、音频、iframe。
目前使用iframe只能在markdown编译器中，且支持不好，比如：
（1）引用 [这个地址](https://bigleaf.top/tools/calculator/bak) 时会出现无响应问题
（2）iframe的event（如onload）无法触发问题

**Comment by ruibaby** [comment]
没有太明白你的需求。

1. 不是很清楚这些功能是指的默认编辑器还是官方提供的那两个 Markdown 插件不支持。
2. 目前默认的编辑器支持原生的 Video、Audio、Iframe 内容渲染和设置，你提供的地址似乎是因为源站不允许通过 iframe 的方式嵌入。
    <img width="1394" alt="image" src="https://user-images.githubusercontent.com/21301288/232402356-27fc94c8-ea8e-4151-96da-a402d15a7de7.png">
3. 官方有计划开发一个 Markdown 编辑器，不过目前没有太多时间。如果可以，可以先让目前的 Markdown 插件来支持这些功能。

**Comment by hugeleaf** [comment]
@ruibaby 
1、video和audio不能以http标签方式插入，不能使用网络url，貌似只能是已有附件可以插入。
``` html
<video controls><source src="http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4" type="video/mp4"></video>
```
2、video、audio、iframe在不安装或者不开启markdown插件时，也不能插入，发布后会直接显示rawcode。
有趣的是，开启markdown插件，切换到原始编辑器就能预览了。
我提供的地址403是因为跨域原因，稍后我可以放开，对于同源站没有这个问题。
该地址通过iframe嵌入在1.x版本没有出现任何问题，在2.x中会卡死（目前只发现这一个案例，其他都正常迁移）。

**Comment by ruibaby** [comment]
1. 可能与 Halo 无关，Chrome 系的浏览器会自动将 https 站点的 http 资源以 https 请求，我在 FireFox 上可以正常加载。
    
    <img width="1397" alt="image" src="https://user-images.githubusercontent.com/21301288/232472711-2c8ee96d-78f7-48b4-b66d-f90f4b53d411.png">
    <img width="875" alt="image" src="https://user-images.githubusercontent.com/21301288/232472885-bcd1525f-6c23-4ed3-b0c6-a917141231d4.png">

2. 默认的编辑器本身不是代码编辑器，不支持直接插入 html 代码（这是一个危险行为），目前视频、音频、Iframe 可以在命令栏插入（目前只有 iframe 代码支持自动识别并插入），如：

    <img width="706" alt="image" src="https://user-images.githubusercontent.com/21301288/232473732-70863d59-4913-4495-87c4-404bdd72ad3e.png">

3. 卡死的问题建议提供浏览器支持。

**Comment by hugeleaf** [comment]
![image](https://user-images.githubusercontent.com/28745194/232478909-90ed9b2f-6861-4eeb-9682-129456768601.png)
![image](https://user-images.githubusercontent.com/28745194/232479326-75a7bb57-6e42-4ddd-8c8e-0286b6cc1d4f.png)

**Comment by ruibaby** [comment]
在我本地无法复现这个问题：

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/21301288/232519763-21c991b8-f70b-42e6-a561-b88bd1a62da1.png">

你提供的链接无法访问似乎是因为有一个请求一直在 pending：

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/21301288/232519868-8f3fb268-daf7-4366-b459-4ea3e2a7f8fe.png">

**Comment by hugeleaf** [comment]
问题是应该是主题引入，具体原因我自己查吧，问题关闭，谢谢 @ruibaby
