### ISSUE TITLE
插件启动问题

### ISSUE THREAD

**Issue by nozuo-ux** [halo-dev/halo#3761]
### What is version of Halo has the issue?

克隆了项目，然后在本地机子上运行过后，安装插件并不能启动成功显示如图：

### What database are you using?

H2

### What is your deployment method?

Docker

### What happened?

克隆了项目，然后在本地机子上运行过后，安装插件并不能启动成功显示如图：
![插件1.png](https://panda995.top:500/img/2023/04/插件1.png)
请问怎么解决啊？

**Comment by JohnNiang** [comment]
/triage duplicate

如果以开发模式启动的话，目前是无法正常通过 Jar 包安装插件的，可参考：<https://github.com/halo-dev/halo/issues/2908>。

Close in favor of <https://github.com/halo-dev/halo/issues/2908>.

/close
