### ISSUE TITLE
默认将 external url 设置为 / 可能会带来一些问题

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#3762]
### 是什么版本出现了此问题？

main branch

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式部署？

Docker Compose

### 在线站点地址

https://ryanc.cc

### 发生了什么？

Halo 在 https://github.com/halo-dev/halo/pull/3655 中将默认的 External url 配置改为了 `/`，使内部的所有 permalink 变为相对路径，目的是为了支持多域名或者更换域名的需求。但目前发现会带来以下问题：

1. 部分插件使用了 External url 来生成完整链接，可能会导致链接生成不正确，比如：https://github.com/halo-sigs/plugin-feed 和 https://github.com/halo-sigs/plugin-sitemap
2. Console 端概览页面的外部访问地址无法正常渲染。

建议保留 External url 的设置，但可以提供一个额外的设置来支持使用相对路径。

/kind improvement
/area core

**Comment by JohnNiang** [comment]
IMO，再增加一个是否使用相对路径配置容易混淆使用者。

1. 我将完善这两个插件
2. Console 端应该假设外部访问地址可能是相对路径。不管是绝对路径和相对路径都应该正确跳转。

/assign

**Comment by ruibaby** [comment]
还有以下场景：

1. 邮件发送模板，里面可能需要包含 Halo 系统内的完整链接，否则邮件中的链接会无法访问。
2. 文章中可能需要完整的文章链接显示，比如转载提示，分享文章等。（虽然可以通过 js 获取到当前页面的地址，但总归不是一个统一的方案）。

综上，此 issue 可能讨论的是是否需要一个字段来标识网站主域名的问题，可能后续还会有暂时想不到的场景需要获取到域名设置。

所以建议再提供一个字段来用于专门生成系统内业务的 permalink，默认为 `/`，用户可以根据需要设置为完整域名地址。External url 保持不变，但它后续可能只被用于获取主域名设置。
