### ISSUE TITLE
请问这是我配置问题吗？

### ISSUE THREAD

**Issue by WenTesla** [halo-dev/halo#3766]
### 是什么版本出现了此问题？

最新官方版本

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker Compose

### 在线站点地址

http://43.138.126.75:8090/

### 发生了什么？

我这里发布文章后链接是本地：
看左下角！

![image](https://user-images.githubusercontent.com/88094223/232513128-fd7656ab-256f-4c09-8371-44371549260b.png)

**Comment by ruibaby** [comment]
/triage duplicate 

https://github.com/halo-dev/halo/issues/3763

/close

**Comment by WenTesla** [comment]
已经解决，感谢！
