### ISSUE TITLE
打开之前写过的文章，在大纲中没有目录，需要在文章任意地方敲回车以后才会出现

### ISSUE THREAD

**Issue by zhuwenbo111** [halo-dev/halo#3769]
### 是什么版本出现了此问题？

 2.4.2

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

打开之前写过的文章，在大纲中没有目录，需要在文章任意地方敲回车以后才会出现

### 附加信息

https://user-images.githubusercontent.com/102512051/232656070-769a5b82-4094-4e50-a968-2bbadc8609e1.mp4

**Comment by LIlGG** [comment]
确实存在这个问题。

/kind bug
/area console
/milestone 2.5.x
