### ISSUE TITLE
docker使用mysql数据库部署出现问题

### ISSUE THREAD

**Issue by Time185** [halo-dev/halo#377]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能

![a](https://user-images.githubusercontent.com/42808522/68820076-23f7fc80-06c5-11ea-8a06-ffb532861b3c.png)

根据安装指南操作出现这个问题，一开始以为是数据库的问题，切换成h2数据库之后，还是会出现同样的问题。

**Comment by JohnNiang** [comment]
从 h2 的错误码显示看，应该是 h2 创建 trace 文件的时候出错了，有可能已经存在，或者无权限。

建议删除 ~/.halo/db 重试呢。

**Comment by Time185** [comment]
> 从 h2 的错误码显示看，应该是 h2 创建 trace 文件的时候出错了，有可能已经存在，或者无权限。
> 建议删除 ~/.halo/db 重试呢。

你好  ~/.halo文件夹下就只有一个application.yaml文件，没有其他文件，应该不是这个问题

**Comment by ruibaby** [comment]
@Time185 你用jar包运行试试

**Comment by JohnNiang** [comment]
可以看看你的 application.yml 么(去除敏感信息)

**Comment by Time185** [comment]
> 可以看看你的 application.yml 么(去除敏感信息)
嗯  你看一下
![捕获](https://user-images.githubusercontent.com/42808522/68841560-c8973000-06ff-11ea-9172-015ff6b6a24a.PNG)

**Comment by ruibaby** [comment]
@Time185 你把type也注释了

**Comment by Time185** [comment]
> 可以看看你的 application.yml 么(去除敏感信息)

嗯  你看一下
![捕获](https://user-images.githubusercontent.com/42808522/68841720-12801600-0700-11ea-9571-36012b316fbb.PNG)

**Comment by Time185** [comment]
@JohnNiang 
![a](https://user-images.githubusercontent.com/42808522/68841819-42c7b480-0700-11ea-8727-e0c21ecb6a15.png)

**Comment by Time185** [comment]
@JohnNiang 
![捕获](https://user-images.githubusercontent.com/42808522/68841925-71de2600-0700-11ea-98f5-91a1041c8c9d.PNG)

**Comment by Time185** [comment]
@ruibaby type注释过了  用jar包运行的时候  可以启动 mysql中表也自动创建了   但无法访问  我在本地用的虚拟机   和这个有关系吗

**Comment by ruibaby** [comment]
@Time185 那要看你虚拟机和宿主机有没有连通。不过为什么还要用虚拟机跑呢？宿主机不行吗

**Comment by Time185** [comment]
@ruibaby 可以了  之前虚拟机里面没有做端口映射  多谢了
