### ISSUE TITLE
疑似导航目录过长引起的错误，以及不知名错误的百度访问失败

### ISSUE THREAD

**Issue by 764763903a** [halo-dev/halo#378]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [x] 添加新的特性或者功能
- [ ] 请求技术支持

```java
2019-11-16 03:30:17.830 ERROR 13740 --- [XNIO-1 I/O-3] io.undertow.request                      : UT005071: Undertow request failed HttpServerExchange{ CONNECT www.baidu.com:443}
java.lang.IllegalArgumentException: UT000068: Servlet path match failed
2019-11-16 04:54:54.898 ERROR 13740 --- [XNIO-1 task-20] r.h.a.controller.core.CommonController   : Error path: [/error], status: [404 NOT_FOUND]
2019-11-16 05:49:30.916 ERROR 13740 --- [XNIO-1 task-22] r.h.a.controller.core.CommonController   : Error path: [/error], status: [404 NOT_FOUND]
2019-11-16 08:38:35.886  WARN 13740 --- [XNIO-1 task-28] r.h.a.service.base.AbstractCrudService   : PostTag collection is empty
2019-11-16 08:38:36.129  WARN 13740 --- [XNIO-1 task-28] r.h.a.service.base.AbstractCrudService   : PostCategory collection is empty
```

**Comment by ruibaby** [comment]
@764763903a 这个错误具体有什么表现？

**Comment by 764763903a** [comment]
https://smxy.xyz:8899/archives/20191021173012  预览页面出现问题
编辑页面   无法增加新的目录标签，并且点击无响应

**Comment by 764763903a** [comment]
> @ 764763903a这个错误具体有什么表现？

浏览页面无法出现目录导航
编辑页面无法增加新的目录标签，并且点击无响应

**Comment by ruibaby** [comment]
@764763903a 在后台预览出现错误是吧

**Comment by 764763903a** [comment]
> @ 764763903a在后台预览出现错误是吧

https://smxy.xyz:8899/archives/20191021173012
前台也出现问题

**Comment by ruibaby** [comment]
@764763903a 导航目录是js生成的。你F12看看有没有什么异常

**Comment by 764763903a** [comment]
[logs.zip](https://github.com/halo-dev/halo/files/3853676/logs.zip)

**Comment by 764763903a** [comment]
[java基础.zip](https://github.com/halo-dev/halo/files/3853686/java.zip)

**Comment by ruibaby** [comment]
@764763903a 好的

**Comment by JohnNiang** [comment]
这个不算是明显的错误。

**Comment by JohnNiang** [comment]
Related: https://issues.jboss.org/browse/UNDERTOW-592

**Comment by JohnNiang** [comment]
And: https://github.com/jhipster/generator-jhipster/issues/9544

**Comment by 764763903a** [comment]
### 通配符的使用
1.使用类型通配符：？ 比如：List<?>   ，Map<?,?> List<?>是List<String>、List<Object>等各种泛型List的父类。
2.读取List<?>的对象list中的元素时，永远是安全的，因为不管list的真实类型 是什么，它包含的都是Object。
3.写入list中的元素时，不行。因为我们不知道c的元素类型，我们不能向其中 添加对象。  唯一的例外是null，它是所有类型的成员。
 将任意元素加入到其中不是类型安全的： Collection<?> c = new ArrayList<String>(); c.add(new Object()); // 编译时错误 因为我们不知道c的元素类型，我们不能向其中添加对象。add方法有类型参数E作为集 合的元素类型。我们传给add的任何参数都必须是一个未知类型的子类。因为我们不知 道那是什么类型，所以我们无法传任何东西进去。
 唯一的例外的是null，它是所有类型的成员。
 另一方面，我们可以调用get()方法并使用其返回值。返回值是一个未知的 类型，但是我们知道，它总是一个Object。
![image.png](https://smxy.xyz:8899/upload/2019/11/image-84f83bce95c341a6b8898c9da31b8175.png)
![image.png](https://smxy.xyz:8899/upload/2019/11/image-1f0312f6873847c6841babfef8dc0513.png)

这一段代码会干扰目录的生成

**Comment by 764763903a** [comment]
1.使用类型通配符：？ 比如：List<?>   ，Map<?,?> List<?>是List<String>、List<Object>等各种泛型List的父类。
这句话干扰了后续目录的生成，具体原因未知

**Comment by ruibaby** [comment]
@764763903a 应该是渲染器的问题。

**Comment by 764763903a** [comment]
<>里面填写字符会影响目录渲染，单填一个a实测只影响一个，填写其他可能全部影响，更具体的没有测试

**Comment by ruibaby** [comment]
这个问题已经修复了。语法：`[TOC]`。

另外，建议每一day一篇文章吧。
