### ISSUE TITLE
希望默认编辑器支持查看/编辑源码功能

### ISSUE THREAD

**Issue by ttiv** [halo-dev/halo#3788]
### 你当前使用的版本

2.4.2

### 描述一下此特性

希望默认编辑器支持查看/编辑源码功能。
点击编辑器工具栏中的html按钮，可以打开源代码，并支持编辑源代码功能。

### 附加信息

[![p9Fk841.png](https://s1.ax1x.com/2023/04/19/p9Fk841.png)](https://imgse.com/i/p9Fk841)
[![p9FkNjO.png](https://s1.ax1x.com/2023/04/19/p9FkNjO.png)](https://imgse.com/i/p9FkNjO)

**Comment by ruibaby** [comment]
在最新的版本中，已经支持同类型的编辑器切换，所以我认为没有必要在内置的富文本编辑器中支持插件和编辑源代码。我建议实现一个源代码编辑器插件。

/area plugin
/remove-area console

**Comment by LIlGG** [comment]
Halo 2 提供了一个在默认富文本编辑器中编写 HTML 源码的插件：https://www.halo.run/store/apps/app-NgHnY

/close
