### ISSUE TITLE
在2.X版本 速记 功能没有了吗？

### ISSUE THREAD

**Issue by KaniuBillows** [halo-dev/halo#3791]
### 你当前使用的版本

1.6

### 描述一下此特性

1.6的时候可以用速记，快速记录一些东西。我最近打算迁移到2.X，但是在在线demo中 没有看到速记功能。也没有日志的页面了。

**Comment by ruibaby** [comment]
2.0 不再内置这个功能，但为了 1.x 的迁移，我们提供了：https://github.com/halo-sigs/plugin-moments

迁移文档还在更新中，可查阅：https://github.com/halo-dev/docs/pull/209

/kind support
