### ISSUE TITLE
图片无法预览，页面也加载不了是什么原因呢？

### ISSUE THREAD

**Issue by Huang17485** [halo-dev/halo#3798]
### What is version of Halo has the issue?

2.4.2

### What database are you using?

H2

### What is your deployment method?

Docker

### What happened?

所有上传的图片都显示不了；
![image](https://user-images.githubusercontent.com/97492590/233345770-c8dae59d-b39f-4401-aa79-e9fe827220b6.png)

**Comment by ruibaby** [comment]
需要确认 external-url 是否设置正确：https://docs.halo.run/getting-started/install/docker-compose#:~:text=%E4%B8%8E%20SPRING_R2DBC_URL%20%E5%AF%B9%E5%BA%94-,halo.external%2Durl,-%E5%A4%96%E9%83%A8%E8%AE%BF%E9%97%AE%E9%93%BE

/kind support

**Comment by shuaipotian-joke** [comment]
> 需要确认 external-url 是否设置正确：https://docs.halo.run/getting-started/install/docker-compose#:~:text=%E4%B8%8E%20SPRING_R2DBC_URL%20%E5%AF%B9%E5%BA%94-,halo.external%2Durl,-%E5%A4%96%E9%83%A8%E8%AE%BF%E9%97%AE%E9%93%BE
> 
> /kind support

大佬你好，我也是这个问题，我用docker inspect halo 看了一下这个参数我觉得设置的没问题啊，请大佬帮忙看看
![image](https://user-images.githubusercontent.com/60846491/233814810-df120752-27b2-4e22-952f-eac736ae1103.png)
我的站点是  chenweilin.cn
还有就是大佬能顺便看一下图片为啥加载不了吗，是因为加载方式不一样？图片链接放到浏览器上是可以打开的，就是在halo里面展示不了，是否是不支持这种方式？后续新特性可以兼容吗

**Comment by JohnNiang** [comment]
@shuaipotian-joke 

1. 确认一下具体用的哪个站点：www.chenweilin.cn 或者是 chenweilin.cn。
2. 确认一下 Nginx 侧是否代理了 `/upload/` 路径。
    ```bash
    curl https://www.chenweilin.cn/upload/1.jpg
    Image not found!
    ```
    Halo 里面似乎没有这样的返回结果。

**Comment by shuaipotian-joke** [comment]
> @shuaipotian-joke
> 
> 1. 确认一下具体用的哪个站点：www.chenweilin.cn 或者是 chenweilin.cn。
> 2. 确认一下 Nginx 侧是否代理了 `/upload/` 路径。
>    ```shell
>    curl https://www.chenweilin.cn/upload/1.jpg
>    Image not found!
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    Halo 里面似乎没有这样的返回结果。

感谢大佬回复！确实是nginx代理了的问题，目前已经上传成功了，大佬们能顺便看看我的第二个问题吗？

**Comment by shuaipotian-joke** [comment]
> @shuaipotian-joke
> 
> 1. 确认一下具体用的哪个站点：www.chenweilin.cn 或者是 chenweilin.cn。
> 2. 确认一下 Nginx 侧是否代理了 `/upload/` 路径。
>    ```shell
>    curl https://www.chenweilin.cn/upload/1.jpg
>    Image not found!
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    Halo 里面似乎没有这样的返回结果。

感谢大佬的回复，请问第二个问题大佬们能请教一下是为啥吗？https://chenweilin.cn/archives/springboot 这篇博客第一张图片为啥加载不了嘞？

**Comment by ruibaby** [comment]
> 感谢大佬的回复，请问第二个问题大佬们能请教一下是为啥吗？https://chenweilin.cn/archives/springboot 这篇博客第一张图片为啥加载不了嘞？

https://github.com/halo-dev/halo/issues/3646

**Comment by ruibaby** [comment]
如果没有后续动态，我将关闭此 issue，后续可以随时打开或者新建 issue。

/close
