### ISSUE TITLE
建议新增pdf文件的预览和展示功能pdf内容直接展示在文章页面中

### ISSUE THREAD

**Issue by xiuyuanjun** [halo-dev/halo#3799]
### 你当前使用的版本

2.4.2

### 描述一下此特性

建议新增pdf文件的预览和展示功能pdf内容直接展示在文章页面中

**Comment by ruibaby** [comment]
此 issue 在 Halo 2.0 可以通过在编辑器插入 iframe 实现，比如：

<img width="1070" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/dd76067b-595f-4396-858c-5fe8c465c2e8">

所以我将关闭此 issue，如果后续有其他补充，欢迎重新提交 issue 或者重新打开此 issue。

/close
