### ISSUE TITLE
后台编辑有该页面，但是前台访问404

### ISSUE THREAD

**Issue by hhm1** [halo-dev/halo#3808]
### 是什么版本出现了此问题？

2.4.2

### 使用的什么数据库？

MariaDB

### 使用的哪种方式部署？

Docker Compose

### 在线站点地址

https://haoming9245.top

### 发生了什么？

后台有该页面，一打开链接就404

### 附加信息

![image](https://hhm1.github.io/hhm1/issuescreenshots/%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE%202023-04-21%20165015.png)
![image](https://hhm1.github.io/hhm1/issuescreenshots/%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE%202023-04-21%20165100.png)

**Comment by ruibaby** [comment]
可以复现，只要别名出现了中文。

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/21301288/233604833-e2f0a17f-0c6e-48e2-b837-d3a514953249.png">

/kind bug
/area core
/priority critical-urgent
