### ISSUE TITLE
logs表中没有记录IP地址。

### ISSUE THREAD

**Issue by mediocrePeople** [halo-dev/halo#381]
在记录用户的操作日志时，能否同时记录下用户的IP，在数据库的LOGS表中。

![2019-11-16_15-15-15](https://user-images.githubusercontent.com/37702397/68989596-058c2f80-0884-11ea-905f-1953b3fc6de5.png)

**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/guide)
- [ ] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [ ] [其他 Issues](https://github.com/halo-dev/halo-admin/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [x] 添加新的特性或者功能
- [x] 请求技术支持

**Comment by JohnNiang** [comment]
https://github.com/halo-dev/halo/blob/dev/src/main/java/run/halo/app/event/logger/LogEventListener.java

理论上应该在这里设置好 IP 的，不过这里采用的异步方式，可能暂时无法获取到 IP。

**Comment by mediocrePeople** [comment]
对了，我刚发现log_key也没记录到logs表中。

**Comment by JohnNiang** [comment]
好的，我们好好排查一下。

**Comment by mediocrePeople** [comment]
嗯，麻烦了，问题解决了你们直接关闭这个issue吧，我可能回复的不是很及时。过段时间我再下载你们修改好的源码试试。
