### ISSUE TITLE
上传文件卡100%

### ISSUE THREAD

**Issue by qq547176052** [halo-dev/halo#3812]
### What is version of Halo has the issue?

2.0

### What database are you using?

MySQL 8.x

### What is your deployment method?

Docker

### Your site address.

https://142536.vip/

### What happened?

上传附件卡100%
![image](https://user-images.githubusercontent.com/26636842/233669066-923eae03-c71a-43ce-8107-0f4cc6caf91e.png)

**Comment by JohnNiang** [comment]
大文件上传后需要稍微等等才能完成。

**Comment by ruibaby** [comment]
建议检查浏览器日志和 Halo 的日志，可以先看看是不是这个问题：https://docs.halo.run/user-guide/faq#%E9%99%84%E4%BB%B6%E4%B8%8A%E4%BC%A0%E6%8F%90%E7%A4%BA-413-request-entity-too-large-%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3

/kind support
/triage needs-information

**Comment by qq547176052** [comment]
![image](https://user-images.githubusercontent.com/26636842/235307557-6f2b7ad7-b0dd-4fbd-9630-7e71bfce1624.png)
服务器没限制

**Comment by qq547176052** [comment]
```

#PROXY-START/

location ^~ /
{
    proxy_pass http://127.0.0.1:18099;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header REMOTE-HOST $remote_addr;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    # proxy_hide_header Upgrade;

    add_header X-Cache $upstream_cache_status;

    #Set Nginx Cache
    
    
    set $static_filen1hUPzmb 0;
    if ( $uri ~* "\.(gif|png|jpg|css|js|woff|woff2)$" )
    {
    	set $static_filen1hUPzmb 1;
    	expires 12h;
        }
    if ( $static_filen1hUPzmb = 0 )
    {
    add_header Cache-Control no-cache;
    }
}

#PROXY-END/
```

**Comment by qq547176052** [comment]
![image](https://user-images.githubusercontent.com/26636842/235307602-cbcb9830-a03a-4341-bac3-c38e708273f3.png)
这个是不是同一个问题?

**Comment by JohnNiang** [comment]
如果没有配置 max request body，则默认是 1MB。也就是说默认情况下，Nginx 只允许 1MB 大小的文件上传。

**Comment by qq547176052** [comment]
![image](https://user-images.githubusercontent.com/26636842/235492354-7dc1c830-70bd-4b2a-aa98-ec5c36ae0f7a.png)
加上这句 附件能上传成功 但还是卡在100%

![image](https://user-images.githubusercontent.com/26636842/235492212-4516f107-f366-4b97-8373-b22a96b3556d.png)

**Comment by ruibaby** [comment]
我尝试了上传 1.2 G 大小的文件，是可以上传成功的，但是确实会在 100% 停留一段时间（我这里大概 10s）。这可能是 100% 代表着已经发送到服务器，但服务器接收和处理还需要一定的时间，你可以等待一会儿试试。

<img width="659" alt="image" src="https://user-images.githubusercontent.com/21301288/236121589-8b225f8f-9f59-4975-8bb1-23006c9c2c04.png">

**Comment by ruibaby** [comment]
如果没有后续动态，我将关闭此 issue，可以随时 reopen 或者新建 issue。

/close
