### ISSUE TITLE
上传视频附件到阿里云OSS失败

### ISSUE THREAD

**Issue by NGLSL** [halo-dev/halo#382]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [ ] [Halo 使用文档](https://halo.run/docs)
- [ ] [Halo 论坛](https://bbs.halo.run)
- [ ] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

上传视频附件到阿里云OSS失败。现在附件的上传难道不支持音频视频吗？

**Comment by ruibaby** [comment]
@NGLSL 请提供相关信息

**Comment by NGLSL** [comment]
> @NGLSL 请提供相关信息

已经找到问题了，nginx设置的上传大小太小了。

不过貌似视频不支持预览。
![image](https://user-images.githubusercontent.com/40338580/69002075-55223800-0924-11ea-9da4-4be028b37887.png)

**Comment by ruibaby** [comment]
@NGLSL @guching

**Comment by ruibaby** [comment]
@guqing

**Comment by guqing** [comment]
@ruibaby ok

**Comment by guqing** [comment]
已解决 等下次更新就可以了 或者你重新打包halo-admin的dev分支
