### ISSUE TITLE
家里电脑写的文章,点击了保存，来单位继续写发现内容没有了

### ISSUE THREAD

**Issue by zhuwenbo111** [halo-dev/halo#3820]
### 是什么版本出现了此问题？

 2.4.2

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

昨天在家里写文章写了一天，今天来单位本来想继续写的，但是打开发现，昨天写的内容都不见了，但是附件截图都在，打开的时候会显示已从缓存中恢复未保存内容。但是实际上内容不是我昨天写的，想问一下问题是啥，是不是我需要回家打开家里电脑昨天写的就会有了(缓存啥的），真的着急昨天写了一天

另外想问一下出现这个问题的原因是啥，我是群晖docker部署的，数据库是h2。急求!想附上图片但是，现在不敢往博客里面加入东西怕出现覆盖之类的，如图需要任何日志之类的我可以提供。

问题已经解决，浏览器打开无痕模式文章还在，不知道是不是bug所以提交下

### 附加信息

![微信截图_20230423113223](https://user-images.githubusercontent.com/102512051/233818642-2b90b1b3-3064-4ee5-9725-4a052edf74e9.png)

**Comment by ruibaby** [comment]
目前文章的内容会实时缓存到浏览器，会在 **保存或者发布文章** 的时候清空。你这个情况应该是在单位的电脑也编写过，回家保存之后，单位的浏览器缓存还在，所以会有这样的情况。

/kind support

**Comment by JohnNiang** [comment]
@ruibaby 对于这种情况有什么比较好的解决方案么？比如“撤销恢复”或者“恢复前对比内容，选择权交给使用者”。

**Comment by ruibaby** [comment]
> @ruibaby 对于这种情况有什么比较好的解决方案么？比如“撤销恢复”或者“恢复前对比内容，选择权交给使用者”。

缓存 Content 的时候同时保存当前 Content 的 version，重新进入编辑页面的时候判断 Content 的 version 和本地的是否一致，不一致那就提示用户选择。

**Comment by ruibaby** [comment]
> > @ruibaby 对于这种情况有什么比较好的解决方案么？比如“撤销恢复”或者“恢复前对比内容，选择权交给使用者”。
> 
> 缓存 Content 的时候同时保存当前 Content 的 version，重新进入编辑页面的时候判断 Content 的 version 和本地的是否一致，不一致那就提示用户选择。

/cc @Aanko

**Comment by zhuwenbo111** [comment]
2023年5月17号 问题再次出现
halo版本：2.5.2
数据库 ：h2
再次出现此问题，
详细说明：比如我第一次在单位写的文章没写完 回家继续写了也没写完 ，来到单位继续写 ，结果文章内容显示的是我第一次在单位的 ，我在家中写的 内容没有，在标准窗口下打开页面文章想继续编辑的同时，会提示已从缓存中恢复内容，图片如下所示：
![image](https://github.com/halo-dev/halo/assets/102512051/2f692116-ca64-4236-bea7-9272b34700ea)
目前我解决办法是：
1、清楚cookie可以解决，但是这个方法会同时清空其他浏览器的cookie不太方便
2、使用浏览器无痕窗口模式打开文章（无痕模式下正常）将内容复制出来，粘贴到标准窗口的页面保存之后问题解决。
