### ISSUE TITLE
安装主题异常提示信息不正确

### ISSUE THREAD

**Issue by LIlGG** [halo-dev/halo#3825]
### 是什么版本出现了此问题？

2.5.0

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 问题描述
安装主题时，主题的异常信息不正确，例如安装一个 1.x 的主题，提示 `Internal Server Error: Something went wrong, please try again later.`。

![image](https://user-images.githubusercontent.com/31335418/233825893-c3c04e14-54c6-41a2-bff4-9997735ec61e.png)

### 期望结果
应当显示安装主题失败的具体原因，如 `The [theme.yaml] does not conform to the theme specification.` 。 

该问题可能是由于 PR https://github.com/halo-dev/halo/pull/3747 修复导致，建议排查所有相关的修改。

**Comment by guqing** [comment]
/assign
因为 500 异常不显示详细信息，主题的安装这里抛出的异常类不正确
