### ISSUE TITLE
在线编辑文章时无法换行

### ISSUE THREAD

**Issue by mediocrePeople** [halo-dev/halo#383]
halo后台的markdonw在线编辑文章时，编辑好了发布后，前台页面上无法换行。
比如，下面一段文字：

二、定时备份文件：<br/>
需求：定期备份halo。<br/>
然后定期拷贝到移动硬盘中。

这一段文字，我必须在末尾加上<br/>，才能换行，否则前台页面上，这3行文字会显示在一行。

**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

**Comment by ruibaby** [comment]
![Snipaste_2019-11-17_20-55-04](https://user-images.githubusercontent.com/21301288/69007735-8f1f2880-097c-11ea-9a74-fc8c36428c12.jpg)
![Snipaste_2019-11-17_20-54-51](https://user-images.githubusercontent.com/21301288/69007738-921a1900-097c-11ea-87ff-6c869a09f6b0.jpg)

**Comment by mediocrePeople** [comment]
我再试试看。。。

**Comment by mediocrePeople** [comment]
在线编辑时，没问题，文章发布后，在前台页面上展示时有问题，不会换行。
![2019-11-17_22-00-18](https://user-images.githubusercontent.com/37702397/69008474-e970b700-0985-11ea-9913-3097b04c70e7.png)
![2019-11-17_22-00-47](https://user-images.githubusercontent.com/37702397/69008477-f097c500-0985-11ea-8bb8-032b2c72b50b.png)

**Comment by JohnNiang** [comment]
也有可能是主题引用的渲染样式的问题。

**Comment by mediocrePeople** [comment]
> 也有可能是主题引用的渲染样式的问题。
哦，那这个怎么排查的

**Comment by mediocrePeople** [comment]
> 也有可能是主题引用的渲染样式的问题。

我修改成了默认的主题 Anatole ， 发现还是一样的问题，谷歌，火狐，360浏览器，都测试过了，都有这个问题。

**Comment by ruibaby** [comment]
@mediocrePeople Markdown 的语法规定。两个换行符等于换行。

**Comment by mediocrePeople** [comment]
> @mediocrePeople Markdown 的语法规定。两个换行符等于换行。

你这个提醒我了，可能时markdown语法的问题。我查了下资料，
原来markdown换行的话，是使用两个或以上的空格，加上回车。
如果直接回车，无法换行。
