### ISSUE TITLE
2.0版本Docker启动报错

### ISSUE THREAD

**Issue by zerodayZHOUXUTIAN** [halo-dev/halo#3837]
### 是什么版本出现了此问题？

2.4，2.2

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

1.X版本启动没有问题，2.X版本启动报错内容如下：
[0.019s][warning][os,thread] Failed to start thread "VM Thread" - pthread_create failed (EPERM) for attributes: stacksize: 1024k, guardsize: 4k, detached.

**Comment by zerodayZHOUXUTIAN** [comment]
我使用不同配置的linux机器启动都有这样的问题。

**Comment by zerodayZHOUXUTIAN** [comment]
Docker version 18.09.9, build 039a7df9ba
Docker version 1.13.1, build 7d71120/1.13.1

**Comment by ruibaby** [comment]
/triage duplicate

see https://github.com/halo-dev/halo/issues/2503

/close
