### ISSUE TITLE
文章展示时@[TOC]自动生产目录无效，后台编辑时右边框预览是有的

### ISSUE THREAD

**Issue by WesleyOne** [halo-dev/halo#384]
文章展示时@[TOC]自动生产目录无效，后台编辑时右边框预览是有的

**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

**Comment by WesleyOne** [comment]
可以看下我的博客https://blog.51guagua.top/archives/SpringBoot-source-v1-4-2
![image](https://user-images.githubusercontent.com/24919538/69011689-441b0a80-09a8-11ea-8cb0-31015c188f4e.png)
他没有解析出目录

**Comment by JohnNiang** [comment]
后台的编辑器和服务器渲染组件是不一样的，结果也会有一些偏差。

**Comment by JohnNiang** [comment]
虽然没有在文章中生成 TOC，但是主题是支持这个功能的。

![image](https://user-images.githubusercontent.com/16865714/69014996-aedd3d80-09ca-11ea-9e2c-321582b7bfde.png)

**Comment by ruibaby** [comment]
这样试试。我这里是没有任何问题的。无关主题。

![8A41D9AF-FDCD-4525-82BA-C5C47A01C83B](https://user-images.githubusercontent.com/21301288/69020339-1c02ca00-09ef-11ea-8edf-252d5bbec8a4.png)
![73384DED-BCAE-43C2-B795-8E9B9935E13E](https://user-images.githubusercontent.com/21301288/69020340-1c9b6080-09ef-11ea-9207-aa5fca5f15a7.png)

**Comment by ruibaby** [comment]
导致的原因就是编辑器的语法不同。我尝试修改一下。

**Comment by WesleyOne** [comment]
[TOC]方式大部分主题可以了，谢谢
