### ISSUE TITLE
无需登录可预览任意已安装但未启用主题

### ISSUE THREAD

**Issue by cnskis** [halo-dev/halo#3849]
### 是什么版本出现了此问题？

2.4.0

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 在线站点地址

https://demo.halo.run

### 发生了什么？

在地址后面加：?preview-theme=theme-earth
可直接预览未启用的主题。
如：
https://demo.halo.run/?preview-theme=theme-earth
![image](https://user-images.githubusercontent.com/19919229/234157582-ba6d5f88-3c9e-439e-952e-c4a5cdd0a944.png)

**Comment by JohnNiang** [comment]
当初就是这样设计的。主要是为了支持主题预览，预览本身不会对系统造成任何影响，所以就没有设计必须登录才能预览。

/priority awaiting-more-evidence

**Comment by cnskis** [comment]
OK，那没事了。
