### ISSUE TITLE
编辑文章页面出现多余的滚动条

### ISSUE THREAD

**Issue by wan92hen** [halo-dev/halo#3853]
### 是什么版本出现了此问题？

2.5.0-rc.1

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式部署？

Docker Compose

### 发生了什么？

文章编辑页面出现多余滚动条，滚动后影响页面显示效果。
![image](https://user-images.githubusercontent.com/27671436/234222624-a3f5f23a-5625-44eb-ab62-a55483cd0a84.png)

#### 复现步骤
1. 在文章编辑器中输入大量文本，使编辑区域出现滚动条
2. 在编辑区域滚动到文章内容底部，再滚动到顶部
3. 将鼠标移出文章编辑区域，滑动鼠标滚轮，外侧滚动条出现

**Comment by ruibaby** [comment]
目前在最新版本（2.10）没有再复现这个问题，我将关闭此 issue，后续如果有补充可以随时打开或者提交新的 issue。

**Comment by guqing** [comment]
我在超过一屏内容时选中部分区域然后滚动到底部时复现（快速滚动几次）
<img width="1119" alt="image" src="https://github.com/halo-dev/halo/assets/38999863/f78b4c76-e611-47cb-ad64-dd4197ff8dca">

**Comment by guqing** [comment]
https://github.com/halo-dev/halo/assets/38999863/71f86156-b4c0-4616-ad38-a12dc94b1aed
