### ISSUE TITLE
评论组件只有登录没有注册按钮

### ISSUE THREAD

**Issue by cnskis** [halo-dev/halo#3855]
### 你当前使用的版本

2.5.0

### 描述一下此特性

今天测试发现引用评论组件后，只有登录才能评论，而组件自带的按钮只有登录没有注册。
建议增加注册按钮或增加设置项，可自行设置是否需要登录才可以评论。
![image](https://user-images.githubusercontent.com/19919229/234227425-3bc3366d-4590-4798-8b96-d9e1ed142d58.png)

**Comment by ruibaby** [comment]
可以考虑实现一个通用的登录组件，方便在其他地方也可以直接调用。

/kind feature
/area core

**Comment by ruibaby** [comment]
/close

目前已经统一使用 Console 的登录和注册入口。
