### ISSUE TITLE
docker版安装2.4.3 结果没看到插件的菜单

### ISSUE THREAD

**Issue by chenyueteng** [halo-dev/halo#3863]
### 是什么版本出现了此问题？

2.4.3

### 使用的什么数据库？

MySQL 5.7

### 使用的哪种方式部署？

Docker

### 发生了什么？

docker版安装2.4.3 结果没看到插件的菜单

**Comment by ruibaby** [comment]
/triage needs-information
/kind support

请详细描述你的问题和复现步骤，比如没看到插件的菜单是指哪里?

**Comment by ruibaby** [comment]
如果没有后续动态，我将关闭此 issue，如果有有后续问题可以新建 issue 或者 reopen。

/close
