### ISSUE TITLE
运行后打开网址一直如下图

### ISSUE THREAD

**Issue by Chexian1** [halo-dev/halo#388]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [x] 请求技术支持

![截图1574170733](https://user-images.githubusercontent.com/50158987/69151222-30d97d80-0b15-11ea-9d82-a22bcb306e94.png)

**Comment by ruibaby** [comment]
F12 查看有没有错误。

**Comment by ruibaby** [comment]
不用看了，你用的 360，应该是 IE 兼容模式。不支持 IE 内核。

**Comment by Chexian1** [comment]
一个web项目的什么因素决定了IE内核支不支持它？
我是不是换个浏览器就行了？

**Comment by JohnNiang** [comment]
尝试更换一个浏览器试试呢

**Comment by ruibaby** [comment]
ES 版本吧。换个现代浏览器即可。

**Comment by Chexian1** [comment]
卧槽，火狐可以！然后ES版本是什么？

**Comment by JohnNiang** [comment]
ES 可能是测试版的意思吧
