### ISSUE TITLE
编辑器支持通过链接插入图片

### ISSUE THREAD

**Issue by mobeicanyue** [halo-dev/halo#3882]
### 描述一下此特性

因为服务器带宽很小，图片都想放在图床上，但是默认的编辑方式只支持本地（服务器）上的图片，所以我想，可不可以直接引用图床上的图片来当成图库的一部分，这样直接在默认的编辑器里管理图片会更方便一点。
虽然用md也能实现但是更喜欢默认的编辑器，md不能调整图片大小

**Comment by JohnNiang** [comment]
或许可以尝试使用这个插件： https://github.com/halo-sigs/plugin-s3/

**Comment by Yooona-Lim** [comment]
> 或许可以尝试使用这个插件： https://github.com/halo-sigs/plugin-s3/

试了一下，这种好像需要去厂商那边调什么接口的，没怎么弄过。
我的想法其实很简单，就是像md那样引用链接到文章上，然后用一个插件来管理这些链接，只做“形式”上的存储，应该比oss简单（没用过）？

**Comment by JohnNiang** [comment]
@Yooona-Lim 我大概明白你的意思了。也就是说这个附件只是一个单纯的链接而已。不需要实际上传。

**Comment by Yooona-Lim** [comment]
> @Yooona-Lim 我大概明白你的意思了。也就是说这个附件只是一个单纯的链接而已。不需要实际上传。

是这样的，就只是一个链接管理。
我目前只看到了“图库”插件 有类似的功能，可以保存链接，图床的图片也能正常显示，但是它不能在文章中调用（只有“附件”这个选项）

**Comment by ruibaby** [comment]
/kind feature
/triage awaiting-more-evidence

似乎和 https://github.com/halo-dev/halo/issues/516 是同样的功能。

**Comment by Yooona-Lim** [comment]
> /kind feature /triage awaiting-more-evidence
> 
> 似乎和 #516 是同样的功能。

你好，我看了您给的issue， 似乎没有在附件库里面找到相应的选项，S3不是我描述的那种。
![image](https://user-images.githubusercontent.com/81098819/235949975-80b7287e-c112-4a5f-9b84-377ea2aa0a3b.png)
还是说我少安装了什么插件？
![image](https://user-images.githubusercontent.com/81098819/235950201-10b9e470-09e2-4068-8852-085ec26cae42.png)

还有，图库这个插件，虽然可以保存外部链接，但是无法在文章里调用
![image](https://user-images.githubusercontent.com/81098819/235950456-38fddff8-84c3-4d2c-ac85-035a326b3008.png)
![image](https://user-images.githubusercontent.com/81098819/235950662-d9d23303-0d70-4867-9e16-9d9eef0160a8.png)
插入图片时，仍然是从附件库而没有图库的选项

**Comment by Yooona-Lim** [comment]
> /kind feature /triage awaiting-more-evidence
> 
> 似乎和 #516 是同样的功能。

您好 过了一段时间发现还没有加上您所说的功能，文章的图片首先是只能在附件里面选择，而不是引用链接
![image](https://github.com/halo-dev/halo/assets/81098819/8ae6ecc8-5781-41b1-8e05-9213e806f3d6)

![image](https://github.com/halo-dev/halo/assets/81098819/6522887b-2c9d-49bd-8e3f-f2d93c97d5d1)
其次是附件库里面还是不能选择图库作为来源
![image](https://github.com/halo-dev/halo/assets/81098819/125f91eb-2b24-4f57-b609-05bcac304d60)

**Comment by Yooona-Lim** [comment]
> @Yooona-Lim 不明白你说的什么意思，Halo 是开源并且自托管的应用，你说的 **过了一段时间发现还没有加上您所说的功能** 真的很难理解。上面给你的 issue [#3882 (comment)](https://github.com/halo-dev/halo/issues/3882#issuecomment-1533138582) 只是说明和你提的 issue 一样，并没有进行实际的开发。
> 
> 此外，重新理解了一下你这个 issue 的内容，你应该是需要在附件选择弹框中添加你图床来源，类似于：
> 
> <img alt="image" width="1262" src="https://user-images.githubusercontent.com/21301288/240216659-900a9627-7bdd-4ea1-bc1b-d75147902cd8.png">
> 但我们并不知道你所用的图床平台或者程序是什么，以下是建议：
> 
> 1. 参考 https://github.com/halo-sigs/plugin-unsplash 插件自行实现针对你图床的插件。
> 2. 提供你所用图床的平台，看看社区是否有兴趣参与开发。

抱歉是我表述有问题，我意思就是发现还没有新版本，并不是说自动更新啥的。
我的想法如下：

https://i.imgtg.com/2023/05/23/Oak8AS.jpg
这个是我图床的一张图片 ，我想将其直接附加在文章中（halo默认的编辑器），不知道能不能实现

我想法的来源其实就是，在halo中用markdown 编辑，是可以直接引用图片链接的，那么既然可以引用，在图片众多的情况下，可以只进行**形式上的存储管理**，及：记住图片的位置（带了.jpg的url）直接调用，做成一个功能。

如果以上可以实现的话，那普通的文章编辑（halo默认的编辑器），是否可以实现呢

**Comment by ruibaby** [comment]
> 这个是我图床的一张图片 ，我想将其直接附加在文章中（halo默认的编辑器），不知道能不能实现

目前默认的编辑器还不支持输入链接来插入外链图片（这是一个新的功能，你可以单独提交一个 issue），但你可以在浏览器上打开这个图片然后复制并粘贴到编辑器。

此外，这种场景最方便的还是看看 imgtg.com 这个图床是否提供了 API，然后通过插件集成到 Halo。

**Comment by real-jiakai** [comment]
直接在浏览器的地址栏输入图片地址：https://i.imgtg.com/2023/05/23/Oak8AS.jpg
右键图片，复制图片，粘贴到halo的编辑器中就能实现外链图片的插入了。

希望halo未来能支持一下编辑器中，插入外链图片的markdown语法。
如下所示：

```markdown
![图片描述](图片外链地址)
```

**Comment by real-jiakai** [comment]
> > 直接在浏览器的地址栏输入图片地址：https://i.imgtg.com/2023/05/23/Oak8AS.jpg
> > 右键图片，复制图片，粘贴到halo的编辑器中就能实现外链图片的插入了。
> > 希望halo未来能支持一下，在编辑器中，插入外链图片的markdown语法。 如下所示：
> > ```
> > ![图片描述](图片外链地址)
> > ```
> 
> 你说的那种粘贴到编辑器的方式是上传到服务器的，我服务器带宽小如果跑很多图片会很费劲，所以我想的是指定文章图片的链接，让浏览器到图床去取而不是从服务器。 而在markdown编辑器模式下，是可以用
> 
> ```
> ![图片描述](图片外链地址)
> ```
> 
> markdown语法本来就是装了插件就支持的，我想的是既然markdown支持，那么默认编辑器也可以考虑支持。

我图片不放服务器上的，我都是甩图床上的，定期备份一下图床上的图片即可。你也可以这样操作。图床的话，你可以自己去搜一下，找个靠谱的即可。

halo原生不支持markdown图片语法格式啊。官方目前已经将编辑器支持markdown图片语法格式添加到2.7的里程碑里面了。

```markdown
![](https://i.imgtg.com/2023/05/23/Oak8AS.jpg]
```

**Comment by real-jiakai** [comment]
> 你好像没明白我问题
> 
> 1. 我图片是放图床上 我希望默认的编辑器可以直接像markdown那样引用而不是放到服务器上
> 2. 我没有说halo原生支持markdown，我说的是装了插件

ok，目前开发者已经将这个需求添加到2.7版本的规划中了，咱们期待即可。

**Comment by Yooona-Lim** [comment]
> ok，目前开发者已经将这个需求添加到2.7版本的规划中了，咱们期待即可。

是的，期待着。另外 你博客内容写的挺不错。😄
