### ISSUE TITLE
2.5版本 use-absolute-permalink=false 导致的问题

### ISSUE THREAD

**Issue by Yooona-Lim** [halo-dev/halo#3883]
### 是什么版本出现了此问题？

2.5.1

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker compose

### 发生了什么？

![image](https://user-images.githubusercontent.com/81098819/235318420-f61c0426-b08c-4bd6-a5cf-027e87327059.png)
估摸着是昨天的更新配置导致的问题，没有permalink之后相应的api还么有全部适配
希望尽快排查
![image](https://user-images.githubusercontent.com/81098819/235318370-a7ec910f-242a-4a58-95c4-53013e6fb70b.png)

**Comment by JohnNiang** [comment]
你需要升级插件。目前 sitemap 和 feed 插件是适配好了这个功能的。
