### ISSUE TITLE
使用1Panel部署后，端口正常通信但是打不开首页。

### ISSUE THREAD

**Issue by yangpin97** [halo-dev/halo#3885]
### What is version of Halo has the issue?

2.5.1

### What database are you using?

MySQL 8.x

### What is your deployment method?

Docker

### Your site address.

http://yydy.fun:18090

### What happened?

1

### Relevant log output

```shell
1
```

### Additional information

1

**Comment by ruibaby** [comment]
/triage needs-information

请完善 issue 的详细信息以供大家判断。此外，可以看看是否和 https://github.com/halo-dev/halo/issues/3869 一样的问题。

**Comment by ruibaby** [comment]
可以使用 2.5.2 尝试一下。https://github.com/halo-dev/halo/releases/tag/v2.5.2

/close

**Comment by yangpin97** [comment]
目前找到问题了，用 1panel 部署完，需要先访问一下 console 页面，才行，不然打不开，这个可以写字教程里，让其他人也知道，http://your-server-ip/console



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月6日(周六) 下午2:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [halo-dev/halo] 使用1Panel部署后，端口正常通信但是打不开首页。 (Issue #3885)




 
@ruibaby: Closing this issue.
  
In response to this:
  
可以使用 2.5.2 尝试一下。https://github.com/halo-dev/halo/releases/tag/v2.5.2
 
/close
  
Instructions for interacting with me using PR comments are available here.  If you have questions or suggestions related to my behavior, please file an issue against the kubernetes/test-infra repository.

**Comment by ruibaby** [comment]
> 目前找到问题了，用 1panel 部署完，需要先访问一下 console 页面，才行，不然打不开，这个可以写字教程里，让其他人也知道，http://your-server-ip/console

2.5.2 已经支持未初始化自动跳转到初始化页面，1Panel 的应用市场也已经更新到了 2.5.2。

**Comment by ghealer** [comment]
<img width="1047" alt="image" src="https://user-images.githubusercontent.com/23149905/236653438-ef301457-b313-4832-b2e7-85645a490fc0.png">
应用商店里依旧是2.5.1

**Comment by ruibaby** [comment]
> <img width="1047" alt="image" src="https://user-images.githubusercontent.com/23149905/236653438-ef301457-b313-4832-b2e7-85645a490fc0.png">
> 
> 应用商店里依旧是2.5.1

尝试更新应用商店。
