### ISSUE TITLE
2.4版本后台管理输入用户名密码之后无法进入

### ISSUE THREAD

**Issue by takuyasec** [halo-dev/halo#3890]
### 是什么版本出现了此问题？

2.4

### 使用的什么数据库？

MySQL 5.7

### 使用的哪种方式部署？

Docker Compose

### 发生了什么？

为什么站点部署之后，每次登录后台输入用户名和密码之后，都跳转不进去啊，一直不停循环的输入用户名密码。

### 相关日志输出

```shell
wu
```

**Comment by ruibaby** [comment]
/kind support

似乎和 https://github.com/halo-dev/halo/issues/3768 是一样的问题。

**Comment by ruibaby** [comment]
如果没有后续动态，我将关闭此 issue，如果有有后续问题可以新建 issue 或者 reopen。

/close
