### ISSUE TITLE
提升站点打开速度，默认将js css托管到免费cdn上，后台设置中可以设置使用本地站点js css 或者CDN上的js css

### ISSUE THREAD

**Issue by laiqinghua** [halo-dev/halo#3901]
### 你当前使用的版本

通用

### 描述一下此特性

halo非常好用，但是我们在注重更多的功能时却忽略了网站打开的速度，部分我们的个人服务器不上CDN，带宽小水管，有技术的同学也会启用gzip这些压缩工具，但是目前我们css 和js 大量占用了网站的打开时间，建议在下一个版本中将公共所有的JS和CSS托管到免费的CDN上例如七牛云。

**Comment by ruibaby** [comment]
你说的是主题还是 Console？

如果是 Console，我们不打算将资源托管到三方的公共 CDN，这会造成不可控的问题。可以参考以前的 jsDelivr 故障：https://github.com/halo-dev/halo/issues?q=is%3Aissue+jsdelivr+is%3Aclosed

如果是主题，你可能得向具体的主题提交 issue，Halo 无法控制主题的静态资源。

/kind support
