### ISSUE TITLE
发布文章的时候，可以把访问路径和访问密码input属性加上autocomplete="off"吗，每次都会自动填充

### ISSUE THREAD

**Issue by xebcxc** [halo-dev/halo#391]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

![image](https://user-images.githubusercontent.com/23736683/69230914-24136300-0bc3-11ea-9cc8-a1f3e357fb58.png)

**Comment by ruibaby** [comment]
@xebcxc 已经改了。 等待下个版本发布

**Comment by ruibaby** [comment]
@xebcxc off在某些时候是不生效的。

**Comment by ruibaby** [comment]
需要 `autocomplete="new-password"`

https://github.com/halo-dev/halo-admin/commit/ad57525b0cfc1e90ca02b4f1735c79e999500de5#diff-fcd394268fec1736e9a9232e89159c0eL34
