### ISSUE TITLE
Console 插件管理页面的一些建议

### ISSUE THREAD

**Issue by MoshiCoCo** [halo-dev/halo#3914]
### 你当前使用的版本

2.5.2

## 显示插件更新提示

当前版本无法知道已安装的插件是否在应用市场中存在更新版本。

如果应用市场中存在该插件的更新版本，则在页面上提供插件更新提示，并且支持点击进入应用市场中此插件的详情页。

## 明确插件列表显示的时间是什么时间，消除歧义。

<img width="1164" alt="image" src="https://user-images.githubusercontent.com/17582066/236914390-ce9b2fda-a2fa-4008-9aa3-ea5c64f90625.png">

此处的时间完全看不出来是首次安装时间，还是最后启动时间？还是插件的更新时间， 看接口返回的数据很像首次创建的时间，建议明确，另外觉得这里显示最近一次的更新（安装）时间更为合适。

## 查看插件详情页面，点击动作生效的区域和鼠标悬停样式不统一，造成操作误导。

<img width="1074" alt="image" src="https://user-images.githubusercontent.com/17582066/236915517-54d448b8-45db-4f8a-a5ac-44b54922b335.png">

鼠标悬停在A区域，就已经由指针转为手掌形状，但是点击是无效的，进入不了插件详情页，只有点击B区域，也就是插件名称时才会进入详情页。

修复建议：
1. 将列表的整行的所有区域都支持点击进入详情页。
2. 如果1不行，建议鼠标只有悬停在可进入详情页的区域时才变成手掌形状。

## 异常情况下，插件状态描述和按钮开关保持不一致。

<img width="1088" alt="image" src="https://user-images.githubusercontent.com/17582066/236916686-02b8ca4e-5989-4044-b5cd-cc8103c78ac2.png">

sitemap插件出现一个异常，侧边有小红点，悬停小红点时，是异常信息（忘了截图了），左侧文案显示未启用，但是右侧开关依旧是开启状态。

**Comment by ruibaby** [comment]
第一个问题请关注：https://github.com/halo-dev/halo/issues/3913

/area console
/kind improvement

感谢你的反馈，但建议每一个不同类型的反馈提交不同的 issue，方便我们管理和跟踪。

**Comment by MoshiCoCo** [comment]
> 第一个问题请关注：#3913
> 
> /area console /kind improvement
> 
> 感谢你的反馈，但建议每一个不同类型的反馈提交不同的 issue，方便我们管理和跟踪。

好的，下次我就知道了。
