### ISSUE TITLE
添加第三方统计，出现跨域问题

### ISSUE THREAD

**Issue by heyzqq** [halo-dev/halo#3924]
### 是什么版本出现了此问题？

v2.4.3

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker

### 在线站点地址

https://springx.fun

### 发生了什么？

添加了百度统计，访问时出现跨域问题。

访问地址：https://springx.fun

错误信息（无法请求百度统计）：
```
请求 URL: https://hm.baidu.com/hm.js?88223b873e1fd97660c0bd8fab5e7746
引用者策略: strict-origin-when-cross-origin
```

这个应该如何处理呢？是否需要配置什么

**Comment by JohnNiang** [comment]
建议提供浏览器 console 的截图，确认一下具体是哪个接口出现了跨域的问题。

从已提供的访问地址来看，百度统计请求是正常响应的。

<img width="1545" alt="image" src="https://github.com/halo-dev/halo/assets/16865714/e8ab1f2e-f317-4979-b19c-9c31704ccb2d">

/kind support
/close

**Comment by heyzqq** [comment]
> 建议提供浏览器 console 的截图，确认一下具体是哪个接口出现了跨域的问题。
> 
> 从已提供的访问地址来看，百度统计请求是正常响应的。
> 
> <img alt="image" width="1545" src="https://user-images.githubusercontent.com/16865714/237293828-e8ab1f2e-f317-4979-b19c-9c31704ccb2d.png">
> /kind support /close

Console 日志：

![image](https://github.com/halo-dev/halo/assets/47818994/38039405-a66c-4d06-85fc-f3ffdd74327e)

请求爆红：

![image](https://github.com/halo-dev/halo/assets/47818994/2f90335c-4146-49a1-9c4a-c15c0a286de9)

**Comment by JohnNiang** [comment]
建议检查一下是否安装了某些屏蔽统计的浏览器插件。

**Comment by heyzqq** [comment]
> 建议检查一下是否安装了某些屏蔽统计的浏览器插件。

感谢，是我浏览器的问题，被拦截了

![image](https://github.com/halo-dev/halo/assets/47818994/0c5106fe-c673-4872-9443-e824d454fb51)
