### ISSUE TITLE
实时查看日志信息

### ISSUE THREAD

**Issue by JohnNiang** [halo-dev/halo#393]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [x] 添加新的特性或者功能
- [ ] 请求技术支持

提供该功能后，方便博主在任何地方实时查看日志信息，而无需登录服务器查看。

**Comment by JohnNiang** [comment]
https://commons.apache.org/proper/commons-io/javadocs/api-2.4/org/apache/commons/io/input/Tailer.html

可以考虑通过 Tailer 实现。

**Comment by ruibaby** [comment]
已实现。

**Comment by JohnNiang** [comment]
虽然已经实现了，但是每次需要加载太多的日志，且不能实时输出。等后面有精力了继续完善。

**Comment by ruibaby** [comment]
@JohnNiang 可以分段，比如最近500行

**Comment by ruibaby** [comment]
可以自定义行数了。
