### ISSUE TITLE
文章支持

### ISSUE THREAD

**Issue by fzweclipse** [halo-dev/halo#3943]
### 你当前使用的版本

2.5.2

### 描述一下此特性

希望文章能添加对html链接的支持，因为文章太长的话，目前的系统是无法支持的。

**Comment by ruibaby** [comment]
没有明白这个描述，可以详细说明一下。

/triage needs-information

**Comment by fzweclipse** [comment]
比如我有一个文章，有大约12M，页面非常长，我写了静态html可以直接访问，但是放在现在的编辑器只显示前面一部分。但是现在的系统似乎不能支持直接链接到html，不知道这个是否好实现。

**Comment by ruibaby** [comment]
> 但是放在现在的编辑器只显示前面一部分

能否提供一个示例？

> 但是现在的系统似乎不能支持直接链接到html，不知道这个是否好实现。比如文章页增加一个直接添加链接的功能。

这个功能不考虑在 Halo 实现。但可以通过元数据 + 主题适配来支持，可以参考：但是现在的系统似乎不能支持直接链接到html，不知道这个是否好实现。比如文章页增加一个直接添加链接的功能。

**Comment by AeroWang** [comment]
我也不太明白，要不录个屏？提供个示例？
