### ISSUE TITLE
附件链接

### ISSUE THREAD

**Issue by fzweclipse** [halo-dev/halo#3946]
### 是什么版本出现了此问题？

2.5.2

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker

### 发生了什么？

附件链接复制之后显示复制成功，但是实际没有赋值，剪切板里面是空的

**Comment by ruibaby** [comment]
需要提供一下浏览器的信息，这个能否正常复制可能和浏览器是否兼容有关系。

/kind improvement
/area console
/triage needs-information
