### ISSUE TITLE
nginx反向代理后国内无法访问

### ISSUE THREAD

**Issue by QianChenJun** [halo-dev/halo#3947]
### 是什么版本出现了此问题？

2.5.2

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker Compose

### 在线站点地址

blog.qianchen.tk

### 发生了什么？

一旦加入nginx反向代理国内就无法访问，很奇怪（服务器位于香港）。
加了反向代理
![image](https://github.com/halo-dev/halo/assets/74245184/71770b26-384e-431a-8600-805fdeb098c0)
![image](https://github.com/halo-dev/halo/assets/74245184/d11610c5-b309-4201-b242-743bab623239)

没有加反向代理
![image](https://github.com/halo-dev/halo/assets/74245184/38bb4555-25c9-4260-bd15-723f13890060)
![image](https://github.com/halo-dev/halo/assets/74245184/b73ae3de-6925-43df-b354-70bf2df1d09c)

同一个服务器部署的其他项目
![image](https://github.com/halo-dev/halo/assets/74245184/0761cbff-f3eb-4fca-a785-7e7ada76e9c2)
![image](https://github.com/halo-dev/halo/assets/74245184/5d4ccd4c-cb73-4a0d-b5fa-9875a7c40350)

### 相关日志输出

```shell
1
```

### 附加信息

1

**Comment by ruibaby** [comment]
从你的截图来看，测试的似乎都是同一个域名， 那么是如何得出反向代理之后无法访问的呢？

我这里使用 Chinaz 的站长工具测试似乎没有什么问题：

<img width="1215" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/ccd143bd-eeea-4632-b4af-0c2ce5be0675">

直接访问也没有问题：

<img width="500" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/16641dff-e35d-4ed8-bfde-54c5df3c094c">

/kind support
/triage needs-information

**Comment by QianChenJun** [comment]
奇怪 我在研究一下
