### ISSUE TITLE
身份认证筛选无效

### ISSUE THREAD

**Issue by liuchangfitcloud** [halo-dev/halo#3948]
### 是什么版本出现了此问题？

2.5.1

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Fat Jar

### 发生了什么？

身份认证使用关键字搜索无效，
<img width="1427" alt="image" src="https://github.com/halo-dev/halo/assets/44662176/ab99668c-4121-493f-861b-c460db2bbe07">

**Comment by liuchangfitcloud** [comment]
/kind/bug

**Comment by liuchangfitcloud** [comment]
/area/console

**Comment by JustinLiang522** [comment]
请问需要在前端筛选还是后端筛选呢？

**Comment by ruibaby** [comment]
> 请问需要在前端筛选还是后端筛选呢？

这个筛选框可能只是为了让列表看起来更协调，搜索的意义可能不是很大，所以我建议前端搜索就行了，项目已经依赖了 fuse.js。
