### ISSUE TITLE
编辑时可以支持选中文字修改颜色吗

### ISSUE THREAD

**Issue by foolyan** [halo-dev/halo#395]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [x] 添加新的特性或者功能
- [ ] 请求技术支持

编辑时可以支持选中文字修改颜色吗？现在是markdown语法加颜色，写起来不太方便

**Comment by ruibaby** [comment]
高亮可以，其他颜色不行。

```markdown
`高亮`
```

`高亮`

**Comment by JohnNiang** [comment]
@ruibaby 看看能否在 halo-editor 上新增一个工具。

**Comment by ruibaby** [comment]
> @ruibaby 看看能否在 halo-editor 上新增一个工具。

markdown 要怎么改字体颜色。除了用 html.

**Comment by JohnNiang** [comment]
> > @ruibaby 看看能否在 halo-editor 上新增一个工具。
> 
> markdown 要怎么改字体颜色。除了用 html.

```html
<span style="color:red">cardinals</span>
```
可以搞一个工具添加这段代码

**Comment by ruibaby** [comment]
我持保守态度🌚

**Comment by ruibaby** [comment]
暂时不考虑做，等待后期对编辑器的大改版。
