### ISSUE TITLE
用户权限的需求

### ISSUE THREAD

**Issue by Helman123** [halo-dev/halo#3952]
### 你当前使用的版本

2.5

### 描述一下此特性

管理员：拥有管理所有文章（增删改查）的权限，其他没有
作者：只拥有对自己的文章的增删改查的权限。
目前Halo2的用户权限只能赋予某个角色文章查看权限，要么就是完全管理权限（类似管理员），上述类似作者的权限暂时不能实现。

**Comment by JohnNiang** [comment]
/triage duplicate

Close in favor of <https://github.com/halo-dev/halo/issues/3049>.

/close
