### ISSUE TITLE
无法启用插件

### ISSUE THREAD

**Issue by JustinLiang522** [halo-dev/halo#3957]
### 是什么版本出现了此问题？

main

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Fat Jar

### 发生了什么？

下载“图库管理“插件（其它插件也遇到这个问题），点击启用

预期结果：插件正常使用
实际结果：插件无法使用，后端传来数据显示 `phase=FAILED; Wait for setting [plugin-photos-settings] creation`

![image](https://github.com/halo-dev/halo/assets/73240868/ca6e2766-a337-4ccd-b753-17ce884c5af8)

**Comment by ruibaby** [comment]
如果是在开发环境下运行的话，需要确定插件的 runtime-mode 是否配置正确，目前通过 jar 文件加载和通过插件目录加载不能并存。

**Comment by JustinLiang522** [comment]
开发环境下不能直接通过jar加载插件吗？application-dev.yaml里插件的runtime-mode是development

**Comment by ruibaby** [comment]
> 开发环境下不能直接通过jar加载插件吗？application-dev.yaml里插件的runtime-mode是development

目前不能，runtime-mode 为 development 的时候，需要手动配置路径，请参考：https://docs.halo.run/developer-guide/plugin/hello-world#%E8%BF%90%E8%A1%8C%E6%8F%92%E4%BB%B6
