### ISSUE TITLE
文章显示不全

### ISSUE THREAD

**Issue by fzweclipse** [halo-dev/halo#3958]
### 是什么版本出现了此问题？

2.5.2

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker

### 发生了什么？

![QQ截图20230517100634](https://github.com/halo-dev/halo/assets/20226004/cc4432f0-953a-40b8-8b4b-2956e07ec342)
图中显示不全

**Comment by ruibaby** [comment]
具体出现在什么位置？ 根据这张图我们无法知道在哪儿。

/triage needs-information

**Comment by fzweclipse** [comment]
![QQ截图20230518092122](https://github.com/halo-dev/halo/assets/20226004/b8ca4b4b-dd46-4c00-a407-2b39d65542e4)
这样能看到是哪吗？

**Comment by ruibaby** [comment]
> ![QQ截图20230518092122](https://github.com/halo-dev/halo/assets/20226004/b8ca4b4b-dd46-4c00-a407-2b39d65542e4)
> 
> 这样能看到是哪吗？

这属于主题的问题，请向具体主题提交 issue。

/kind support
/close
