### ISSUE TITLE
选择已经拥有的分类目录和标签后，输入的内容不会消失

### ISSUE THREAD

**Issue by QianChenJun** [halo-dev/halo#3959]
### 你当前使用的版本

2.5.2

### 描述一下此特性

选择已经拥有的分类目录和标签后，输入的内容不会消失，需要手动删除
![image](https://github.com/halo-dev/halo/assets/74245184/3638d5f9-6cf8-41f0-bacd-4c6ed7fe5c75)
![image](https://github.com/halo-dev/halo/assets/74245184/8f96c0a5-62af-47dd-854f-28a4bd04fb1b)

**Comment by ruibaby** [comment]
可以复现，但只是在用鼠标选择的时候会，回车选择不会。

/area console
/kind improvement

**Comment by ruibaby** [comment]
@QianChenJun 为什么 Close 掉呢？

**Comment by QianChenJun** [comment]
抱歉😭，顺手了

**Comment by ruibaby** [comment]
> 抱歉😭，顺手了

没事，我以为你看到我上面说 **回车选择不会**，所以关掉。

如果有兴趣，你可以帮忙优化一下这个问题。
