### ISSUE TITLE
更新主题失败

### ISSUE THREAD

**Issue by xebcxc** [halo-dev/halo#396]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

![image](https://user-images.githubusercontent.com/23736683/69488510-2fa5a900-0ea5-11ea-8687-961909f14b68.png)

**Comment by JohnNiang** [comment]
请问你是用的测试版么？这个问题已经修复了。请等待下一个版本的发布。

**Comment by JohnNiang** [comment]
这个错误不影响正常的功能。大致是因为修改了右上角的设置，请求了 color.css，但是 halo server 错误地把该请求拦截了。

**Comment by xebcxc** [comment]
好的，使用的beta版本，不影响正常使用，只是每次登陆的时候，都会提示这个错误。
