### ISSUE TITLE
期望文章内容页支持创建多类型图文布局

### ISSUE THREAD

**Issue by intoyang** [halo-dev/halo#3962]
### 你当前使用的版本

2.5

### 描述一下此特性

1. 创建文章时，支持为正文内容选择不同布局；
2. 可将当前正常键入文章内容的布局理解为默认布局，支持纯文字及图片的顺序排列；在此之上，初步构想了三种拓展布局，分别是并列图文、遮罩图文及图片墙；
3. 该功能可以使用斜杠唤出，或加入富文本编辑器的 tab 菜单中；当功能唤出时，立即显示配置弹窗；
4. 完成相应配置后，在编辑器中显示为可编辑卡片，点击编辑按钮，可以再次进入配置界面；类似 confluence 当中的宏组件。
<img width="227" alt="image" src="https://github.com/halo-dev/halo/assets/73098982/1da4e0aa-ea5d-424b-b7dc-cc15018c12c0">

- 并列图文布局示例：
<img width="402" alt="image" src="https://github.com/halo-dev/halo/assets/73098982/0e133c1b-132a-48f6-9a38-bf1269ba60cd">

- 遮罩图文布局示例：
<img width="403" alt="image" src="https://github.com/halo-dev/halo/assets/73098982/494cecbf-94cc-4630-bbfa-7ea45f94cee7">

- 图片墙布局示例：
<img width="401" alt="image" src="https://github.com/halo-dev/halo/assets/73098982/739bbbe2-e00b-4c4c-bf73-a77c77df845d">

每种布局有相应配置选项，其中，文本输入框可支持最基础的文体设置，如：加粗、斜体、下划线、删除线、水平对齐（左/中/右）、垂直对齐（顶/居中/底）等。

### 附加信息

可以预想，正文多布局应该能让文章页更生动易读。
<img width="303" alt="image" src="https://github.com/halo-dev/halo/assets/73098982/447923b6-f013-4864-be98-ba4d9356c0fb">

**Comment by ruibaby** [comment]
已经在 https://github.com/halo-dev/halo/pull/4669 中支持分栏布局。

/close
