### ISSUE TITLE
Halo2.0文章支持图片云存储上传

### ISSUE THREAD

**Issue by fzweclipse** [halo-dev/halo#3964]
### 你当前使用的版本

2.5.2

### 描述一下此特性

默认编辑器不支持图片直接上传到云存储，只会上传到本地存储。

**Comment by guicaiyue** [comment]
有关于上传附件到其它云存储的插件，https://github.com/halo-sigs/awesome-halo

**Comment by ruibaby** [comment]
@guicaiyue

**Comment by fzweclipse** [comment]
@ruibaby 对的

**Comment by fzweclipse** [comment]
这个可以解决吗？
