### ISSUE TITLE
Max session limit reached

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#3966]
### 是什么版本出现了此问题？

2.5.2

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式部署？

Docker Compose

### 在线站点地址

https://ryanc.cc

### 发生了什么？

如图：

<img width="436" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/9ba314c6-5e41-4bb8-ae4f-4e182fe03dce">

可复现步骤：使用 Basic Auth 请求任意接口达到 1w 次左右可触发，重启可以解决。

目前不清楚这个限制会带来什么样的问题，需要检查一下。

/kind improvement
/area core

**Comment by guqing** [comment]
<img width="871" alt="image" src="https://github.com/halo-dev/halo/assets/38999863/1a16148c-7625-480f-8492-9eb59d0bae49">

**Comment by JohnNiang** [comment]
Hi @lixuejun725 ，Spring WebFlux 确实没有提供对应的配置，不过我们看能否自定义。

/assign

**Comment by JohnNiang** [comment]
> 这个问题目前进一步有提供在相关文件最大数配置选项吗

即使提供了最大数配置选项，也有可能会因为 session 过多造成 OOM。比较好的策略是：每个用户只能有一个 Session。

如果通过接口请求主题端页面，将会为每一次请求都创建一个 Session，但 Session 又需要 30 分钟后才会失效，这就很容易造成 Session 堆积，触发最大 Session 限制。

建议优化一下测试流程，首先通过用户名和密码登录后保存好 `Cookie - SESSION`，接下来的每次请求携带 Cookie，这样就不会那么容易触发 Session 限制。

**Comment by ruibaby** [comment]
@halo-dev/sig-halo 在 https://github.com/halo-dev/halo/pull/5757 中引入 Spring Session 之后，是否已经可以规避此问题？

**Comment by JohnNiang** [comment]
> @halo-dev/sig-halo 在 https://github.com/halo-dev/halo/pull/5757 中引入 Spring Session 之后，是否已经可以规避此问题？

暂时没有这个限制了。并且优化了匿名用户的 Session 机制，目前只有登录用户才会创建对应的 Session。

/close
