### ISSUE TITLE
如何将博客部署在二级目录下？

### ISSUE THREAD

**Issue by WAGFS** [halo-dev/halo#3976]
### 是什么版本出现了此问题？

2.5.0

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

您好，感谢提供好用的工具，我现在遇到一个问题，我想要把博客系统部署在主域名的二级目录下，例如：www.google.com/blog，请问该如何部署呢？谢谢！之前使用1.5.0版本时是可以这样部署的，现在使用2.5.0版本貌似不能这样操作了，看了[常见问题](https://docs.halo.run/user-guide/faq/#%E9%99%84%E4%BB%B6%E4%B8%8A%E4%BC%A0%E6%8F%90%E7%A4%BA-413-request-entity-too-large-%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3)后，设置HALO_EXTERNAL_URL后并未生效。

**Comment by Ciiiiing** [comment]
可以尝试使用反向代理工具例如 Nginx 或者 Caddy
以 Caddy 举例，使用 Caddy 的 handle_path 指令
具体配置文件怎么写可以看看官方文档

**Comment by ruibaby** [comment]
/triage duplicate

see https://github.com/halo-dev/halo/issues/3079

Halo 1.x 也是不支持二级目录部署的，你之前是怎么实现二级目录的呢？

**Comment by WAGFS** [comment]
> /triage duplicate
> 
> see #3079
> 
> Halo 1.x 也是不支持二级目录部署的，你之前是怎么实现二级目录的呢？

之前后台好像是可以自己设置博客路径啥的，时间太久远了有点记不清。请问如果现在我需要实现这样的访问路径除了配置Nginx或Caddy有什么简单一点的其他方法吗？😭

**Comment by ruibaby** [comment]
@WAGFS 这个功能不止需要在 Nginx 中配置，也需要 Halo 的支持。

此外，我更建议使用二级域名。

**Comment by WAGFS** [comment]
> @WAGFS 这个功能不止需要在 Nginx 中配置，也需要 Halo 的支持。
> 
> 此外，我更建议使用二级域名。

好的，感谢！✨请问之后有开发这个功能的想法吗？👀

**Comment by ruibaby** [comment]
> > @WAGFS 这个功能不止需要在 Nginx 中配置，也需要 Halo 的支持。
> > 此外，我更建议使用二级域名。
> 
> 好的，感谢！✨请问之后有开发这个功能的想法吗？👀

不确定，主要是感觉没有什么场景是必须要这样做的，而且 Halo 的改动应该是比较大的。

不过我们还是会保持开放态度，如果有较多的反馈和意见，我们会考虑适配。

**Comment by cyril-cheng** [comment]
反向代理应该是实现的

**Comment by JohnNiang** [comment]
理论上是支持 Context Path 的，不过我们还没有进行有效的测试来保证是否有问题。想要完全支持 Context Path 还需要在 Halo 侧做大量的适配。
