### ISSUE TITLE
Request to provide a unified request library for plugins

### ISSUE THREAD

**Issue by JohnNiang** [halo-dev/halo#3979]
### Your current Halo version

2.6.0-SNAPSHOT

### Describe this feature

I found that most of plugins have data fetching requirement, but each plugin has to import request library respectively, which is not necessary because console project has imported the `axios` request library.

If we expose the request library in console project and plugins are able to reuse it, it will be more efficient and savable.

### Additional information

/kind feature
/area console
/area plugin

**Comment by longjuan** [comment]
目前插件中的自封axios在遇到session过期后不会引导用户重新登录，且每个插件维护一个axios也很麻烦，希望能排上日程。
