### ISSUE TITLE
希望可以在指定页面中注入代码

### ISSUE THREAD

**Issue by Erzbir** [halo-dev/halo#3988]
### 你当前使用的版本

2.5.2

### 描述一下此特性

有些页面我希望使用自己的css和js代码，但是目前只支持在所有页面都注入代码

**Comment by ruibaby** [comment]
> 有些页面我希望使用自己的css和js代码

可以举个例子吗？

**Comment by ruibaby** [comment]
有一个新的 issue：https://github.com/halo-dev/halo/issues/3990

可以看看这种形式是否可以满足。

**Comment by Erzbir** [comment]
> 有一个新的 issue：https://github.com/halo-dev/halo/issues/3990
> 
> 
> 
> 可以看看这种形式是否可以满足。

这个 issue 提到的位置是页面中的某个位置吧，再加上一条 “注入/启用的页面”， 以 “全局作用域” 和 “单个页面作用域” 来进行管理。

**Comment by ruibaby** [comment]
> > 有一个新的 issue：#3990
> > 可以看看这种形式是否可以满足。
> 
> 这个 issue 提到的位置是页面中的某个位置吧，再加上一条 “注入/启用的页面”， 以 “全局作用域” 和 “单个页面作用域” 来进行管理。

对，可以自行配置匹配路由，比如 `/**`、`/archives/**`、`/archives/hello-halo`。

**Comment by Erzbir** [comment]
> > > 有一个新的 issue：#3990
> 
> > > 可以看看这种形式是否可以满足。
> 
> > 
> 
> > 这个 issue 提到的位置是页面中的某个位置吧，再加上一条 “注入/启用的页面”， 以 “全局作用域” 和 “单个页面作用域” 来进行管理。
> 
> 
> 
> 对，可以自行配置匹配路由，比如 `/**`、`/archives/**`、`/archives/hello-halo`。

那这样就够用了

**Comment by ruibaby** [comment]
/triage duplicate

Duplicate of #3990 

/close
