### ISSUE TITLE
文章列表点击下一页，url不完整

### ISSUE THREAD

**Issue by zwz9599** [halo-dev/halo#3992]
### 是什么版本出现了此问题？

2.5.2

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker Compose

### 在线站点地址

http://dtx-helper.yushu.center/

### 发生了什么？

在文章列表中点击下一页后，url由
![image](https://github.com/halo-dev/halo/assets/71952443/0cdd4060-cfae-4d42-8484-1b44765695ba)
变成
![image](https://github.com/halo-dev/halo/assets/71952443/81113729-44fe-4d6a-86ec-84d4b9e89a7d)
缺失了域名部分，手动添加域名部分后，可正常访问。
直接使用内网ip访问也有此问题

### 相关日志输出

```shell
无日志
```

**Comment by zjy4fun** [comment]
这个问题和使用的主题有关？

**Comment by ruibaby** [comment]
和主题有关，你可以向 https://github.com/f2ccloud/theme-ocean 提交 issue。

/kind support
/area theme
/close
