### ISSUE TITLE
期望开放Console全局代码注入

### ISSUE THREAD

**Issue by MartyAlien** [halo-dev/halo#3999]
### Your current Halo version

2.5.2

## 发生背景
我开发了一款插件《 [plugin-giteeoss](https://github.com/MartyAlien/plugin-giteeoss) 》，满足用户使用 Gitee 仓库做附件存储，但是由于 Gitee 现在对资源做了防盗链处理，目前并未向 Gitee 用户开放Refer白名单，插件用户想要引用 Gitee 资源外链时要么指定 `Refer` 为 `gitee.com` 相关域名、要么设置Refer为空才能保证资源不会被重定向到其他资源上。

## 解决思路
要解决 gitee 的防盗链问题，目前有以下方式：
1. 用户自行配置nginx
2. 引用图片资源外链时，添加 `referrerpolicy="no-referrer"` 
3. 全局请求去掉Refer：比如在HTML的head中添加: `<meta name="referrer" content="no-referrer">` 

> 方式1和2都需要用户手动配置，用户体验效果不好
> 
> 方式3可以通过插件本身实现Halo的 `TemplateHeaderProcessor` 注入代码，效果就是除 `console` 以外的地方都能正常获取到 gitee 资源，控制台不能够注入这串代码

## 期望功能
所以，基于方式3，期望halo官方能够支持 `console` 全局代码注入或者能开放接口来实现 `console` 端代码注入

### Additional information

![image](https://github.com/halo-dev/halo/assets/62040646/2f2621ef-9c1b-46ea-af7e-f423b4f4cd3d)

![image](https://github.com/halo-dev/halo/assets/62040646/03bab94d-efc4-48fc-a4a9-29b0cd8eb5dd)

![image](https://github.com/halo-dev/halo/assets/62040646/815da5d5-e738-4d48-a2b8-e3deaa9de43c)

**Comment by ruibaby** [comment]
Hi @MartyAlien，我刚刚尝试了一下直接在 console/index.ts 中添加插入 head 标签的代码，似乎是可行的。

<img width="692" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/fd4d4bb3-b856-486d-8078-f874f46c02c5">
<img width="661" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/c14b73d3-acd5-4947-82cd-83370bed88e2">

但我不确定这是否会带来安全性问题。

**Comment by MartyAlien** [comment]
hi @ruibaby :
这个标签通常用于保护用户隐私，防止其他网站通过检查 Referer 头部获取用户访问的信息。但需要注意的是，这并不能提供绝对的安全性，因为某些浏览器可能不支持该标签或者可以被绕过。此外，使用 no-referrer 可能会对某些功能依赖 Referer 信息的网站或应用程序产生影响。

综上所述， <meta name="referrer" content="no-referrer"> 标签的使用通常不会引起安全问题，但在特定的情况下需要仔细考虑其影响，并在安全性和功能性之间做出权衡。

**Comment by ruibaby** [comment]
目前你可以直接在插件项目的 `src/main/resources/console` 新建一个 main.js 写入我在 https://github.com/halo-dev/halo/issues/3999#issuecomment-1565339059 提供的 js 来解决这个问题。

/kind support

**Comment by ruibaby** [comment]
any updates?

**Comment by ruibaby** [comment]
如果没有后续动态，我将关闭此 issue。

/close
