### ISSUE TITLE
搜索不需要区分大小写，支持模糊匹配

### ISSUE THREAD

**Issue by xThink** [halo-dev/halo#400]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [ ] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

> `https://halo.run/docs` 该网站 `404`
----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [x] 添加新的特性或者功能
- [ ] 请求技术支持

刚开始使用这款博客程序，从官方主题页面下载了 `Simple Bootstrap` 这款主题，发现在搜索的时候，是区分大小写的，希望可用进行优化下。

**重现步骤：** 
安装博客后，搜索 `he` 会提示 `没有查询到"he"的结果` ，但安装后的第一篇文章，标题是：`Hello Halo` 是包含 `he` 关键字的，只是大小写不一致。

**优化目标：**
搜索不需要区分大小写，进行模糊匹配。

**谢谢大佬**

**Comment by JohnNiang** [comment]
好的，我们尝试解决一下这个问题。

**Comment by JohnNiang** [comment]
> https://halo.run/docs 该网站 404

对于这个问题，在 dev 分支已经修改了。等待后面合并至 master 分支。

对于模糊匹配这个问题，不依赖外部部件恐怕很难解决。
