### ISSUE TITLE
文章内容导致页面显示异常

### ISSUE THREAD

**Issue by Erzbir** [halo-dev/halo#4000]
### 是什么版本出现了此问题？

2.5.2

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker Compose

#### 描述:

在编辑文章时, 如果用了 *附加信息* 中的文本发布文章, 整个 halo 下的文章中的代码块渲染会出现异常(用主题 Sakura 2.0.0 版本可以明显看出), 并且页面内容会出现异常

**所有异常均不止有一个页面会出现**

##### 代码渲染异常:

首先这是正常的代码渲染:

![2023-05-27 22.59.49](https://bloghexofluid.oss-cn-hangzhou.aliyuncs.com/uPic/2023-05-27%2022.59.49.png)

这是异常的渲染:

![2023-05-27 23.03.00](https://bloghexofluid.oss-cn-hangzhou.aliyuncs.com/uPic/2023-05-27%2023.03.00.png)

##### 页面异常:

见下图顶部:

![2023-05-27 23.03.52](https://bloghexofluid.oss-cn-hangzhou.aliyuncs.com/uPic/2023-05-27%2023.03.52.png)

#### 可能引起异常的句子:

具体引起异常的句子是下图第 9 行到 13 行:

![2023-05-27 22.55.13](https://bloghexofluid.oss-cn-hangzhou.aliyuncs.com/uPic/2023-05-27%2022.55.13.png)

如果删除这行就会恢复正常

#### 复现:

- halo 最新版
- 以 *附加信息* 中的文本发布文章

### 附加信息
这是引起异常的文本:

```
## Lambda 表达式:

### Lambda 语法:

使用 lambda 表达式的一般语法是:

> `(Parameters) -> { Body }`

"->" 分隔参数和 lambda 表达式主体

参数括在括号中, 与方法相同, 而 lambda 表达式主体是用大括号括起来的代码块

lambda 表达式主体可以有局部变量和语句

我们可以在 lambda 表达式主体中使用 `break`, `continue` 和 `return`, 也可以从 lambda 表达式主体中抛出异常

- lambda 表达式没有名称, 因为它表示匿名内部类

- lambda 表达式的返回类型由编译器推断

- lambda 表达式不能像方法一样有 `throws` 子句

- lambda 表达式不能是泛型, 而泛型在函数接口中定义
```

_No response_

**Comment by ruibaby** [comment]
请完善标题以及内容，而不是把问题描述都放在一个压缩包，如果是文章的文件或者运行日志这种可以。

/kind support
/triage needs-information

**Comment by Erzbir** [comment]
> 请完善标题以及内容，而不是把问题描述都放在一个压缩包，如果是文章的文件或者运行日志这种可以。
> 
> /kind support /triage needs-information

已完善

**Comment by ruibaby** [comment]
在 plugin-bytemd 上可以复现，似乎是渲染出来的 html 有问题。

<img width="1470" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/1905e8dc-e3d7-4a05-af59-db98c3403dbd">

/kind bug
/area plugin
