### ISSUE TITLE
文章编辑器，引用是否可以去掉引号，很多markdown工具是没有引号的，如有道、github

### ISSUE THREAD

**Issue by youapple** [halo-dev/halo#4009]
### Your current Halo version

2.5.2

### Describe this feature

书写文章，使用markdown的 > 命令，文本自动加上了引号“”。同类markdown工具没有加上“”，包括github填写issue的编辑器也没有加上“”，建议保持一致。

**Comment by ruibaby** [comment]
/area editor
/kind improvement

这实际上是编辑器的文章样式导致的，目前编辑器和默认主题的文章样式方案都采用了 TailwindCSS 的 <https://tailwindcss.com/docs/typography-plugin> 插件。从目前反馈来看，这种样式可能确实在某些地方存在歧义，可以考虑切换为 <https://github.com/sindresorhus/github-markdown-css>。

相关 issue：

- https://github.com/halo-dev/theme-earth/issues/42

**Comment by ruibaby** [comment]
/close

Close in https://github.com/halo-sigs/richtext-editor/pull/15
