### ISSUE TITLE
从主页点击登录会导致二次显示登录页

### ISSUE THREAD

**Issue by longjuan** [halo-dev/halo#4010]
### 是什么版本出现了此问题？

main

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

从主页点击登录，地址栏url会带有redirect_uri
在跳转到redirect_uri时使用了window.location.href赋值跳转
https://github.com/halo-dev/halo/blob/ee1ea061713b21e81f40612185b3e7d4628135b3/console/src/modules/system/users/Login.vue#L32
这会使得需要将登录页面重新渲染完成后才进行跳转
表现为登录后加载过程中突然跳出个空白的登陆页一小段时间

### 附加信息

https://github.com/halo-dev/halo/assets/28662535/b59904fb-bfae-4c87-a184-968711b4e41b

**Comment by ruibaby** [comment]
/area console
/kind improvement

@longjuan 有没有优化的建议呢？

**Comment by longjuan** [comment]
> 有没有优化的建议呢？

vue router 好像只支持相对路径，要么就直接在登录页加个加载动画算了

**Comment by ruibaby** [comment]
@longjuan 已经在 https://github.com/halo-dev/halo/pull/4014 中解决了此问题，有时间可以帮忙测试一下。

解决办法是先导航到一个 Redirect 页面，然后在这个页面完成跳转。
