### ISSUE TITLE
优化 console 移动端适配

### ISSUE THREAD

**Issue by Erzbir** [halo-dev/halo#4012]
### 你当前使用的版本

2.5.2

### 描述一下此特性

**我的移动设备是 iPhone 14 PM, 系统为最新版, 浏览器为最新版 Chrome 和 Safari**

#### 无法修改内容:
有时候需要用手机端来进行一些修改, 但是如果不请求桌面网页, console 中很多有交互窗口的功能无法使用, 比如删除附件库内容, 我不知道这是否为bug.

#### 页面显示问题:

在某些页面, 例如 "仪表盘" 和 "链接页面" 都不能显示完全

![803C0985-D6AA-4FD0-A8B7-9B6DAF3B5640_1_101_o](https://github.com/halo-dev/halo/assets/100007608/b1669b32-b197-43bb-982b-4b2b51b5692a)
我看到代码是预留了右边区域, 但是移动端看着会比较不协调

![B1A8F499-A2AC-485C-9C18-1AD3E5340433_1_101_o](https://github.com/halo-dev/halo/assets/100007608/1946cd2e-52b2-4628-be56-2cbaa58393fe)

**Comment by ruibaby** [comment]
/triage duplicate

Duplicate of https://github.com/halo-dev/halo/issues/2699

/close
