### ISSUE TITLE
Request to support configuration properties in plugin

### ISSUE THREAD

**Issue by JohnNiang** [halo-dev/halo#4015]
### Your current Halo version

2.6.0-SNAPSHOT

### Describe this feature

Recently, I'm developing a plugin that needs get sensitive configuration from local file, such as api secret key, cert path.

If we define ConfigurationProperties like below:

```java
@Data
@ConfigurationProperties
public class PluginProperties {

    private String encryptKey;

    private String certPath;

}


@EnableConfigurationProperties(PluginProperties.class)
@Configuration
public class PluginConfiguration {
}
```

so that we can autowire the properties in any components:

```java
@Component
@Slf4j
public class MyPlugin extends BasePlugin {

    private final PluginProperties storeProperties;

    public MyPlugin(PluginWrapper wrapper, PluginProperties storeProperties) {
        super(wrapper);
        this.storeProperties = storeProperties;
    }

    @Override
    public void start() {
        log.info("Store properties: {}", storeProperties);
```

### Additional information

/kind feature
/area core
/area plugin

**Comment by JohnNiang** [comment]
Possible plugin's configurations path:

1. `${halo.work-dir}/configs/${plugin-id}.yaml`
2. `${halo.work-dir}/plugin-configs/${plugin-id}.yaml`
3. `${halo.work-dir}/plugins/configs/${plugin-id}.yaml`

I prefer option 3.

**Comment by JustinLiang522** [comment]
There is already a PluginProperties file. Can we just add these two properties to it?

**Comment by JohnNiang** [comment]
Hi @JustinLiang522 , thank you for your comment and willingness to contribute.

The `PluginProperties` is only an `example` here. These properties above should be defined into plugin instead of Halo core.

We need to provide `configuration properties mechanism` for plugins at Halo core instead of defining the properties.

**Comment by JustinLiang522** [comment]
Thank you for your explanation. Just to clarify, do you mean that we should resolve the plugin's yaml from the jar file and save it to `${halo.work-dir}/plugins/configs/${plugin-id}.yaml`?

**Comment by JohnNiang** [comment]
Not exactly correct. We can consider `config.yaml` in plugin jar as default configuration and `${halo.work-dir}/plugins/configs/${plugin-id}.yaml` as user-defined configuration. Just like Spring Boot.

**Comment by JohnNiang** [comment]
The main reason is that we can standardize the configuration method of the configuration file, and the plugin can obtain the content configured by the user without additional operations, and only needs to add the `@ConfigurationProperties` annotation. So we had to support this feature in Halo core.

**Comment by JohnNiang** [comment]
/assign

Hi @JustinLiang522 Thanks for your willingness to contribute again!

Looking forward to your code review.
