### ISSUE TITLE
文章页面渲染过慢

### ISSUE THREAD

**Issue by gao-tf** [halo-dev/halo#4017]
### 你当前使用的版本

2.5

### 描述一下此特性

问题1:在升级过程中有迁移插件很棒，但是当装完插件以后，使用docker重启2.5的halo，启动会很慢，个人就安装了迁移推荐的一些插件。
问题2:halo1.5有一个很棒的功能就是接口缓存，当然升级为2.5以后并没有明显觉得慢，并且觉得焕然一新，后管页面还ok,但是安装完主题以后，明显没有比1.5的快，当然也有主题cdn的问题。
以上问题可能是我的服务器问题导致的，2c4h 
下来附上我的地址：sky12580.cn

**Comment by JohnNiang** [comment]
随便访问了一篇文章，请求各项时间如下：

<img width="648" alt="image" src="https://github.com/halo-dev/halo/assets/16865714/174dd092-6184-489a-8953-03f809c1ec13">

确实有点儿慢了。目测 Halo 服务器和数据库之间的延迟比较高。

/triage needs-information

**Comment by JohnNiang** [comment]
Hi @gao-tf ，升级至 Halo 2.6.0 后是否有所改善呢？欢迎进一步的反馈，方便我们确认这个问题是否还存在。

**Comment by gao-tf** [comment]
好多啦发自我的手机-------- 原始邮件 --------发件人： John Niang ***@***.***>日期： 2023年6月5日周一 下午4:49收件人： halo-dev/halo ***@***.***>抄送： 高腾飞 ***@***.***>, Mention ***@***.***>主    题： Re: [halo-dev/halo] 文章页面渲染过慢 (Issue #4017)
Hi @gao-tf ，升级至 Halo 2.6.0 后是否有所改善呢？欢迎进一步的反馈，方便我们确认这个问题是否还存在。

**Comment by JohnNiang** [comment]
那我先关闭当前 Issue，后续有任何问题可随时重新打开 Issue。

/close
