### ISSUE TITLE
请问写好的文章是以.md格式保存在服务器中么？如果在服务器中，在什么路径呢？想备份一下自己的笔记

### ISSUE THREAD

**Issue by mikutown** [halo-dev/halo#402]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [x] 请求技术支持

**Comment by ruibaby** [comment]
@mikutown 在数据库。下个版本支持备份

**Comment by mikutown** [comment]
OK，感谢dalao

**Comment by JohnNiang** [comment]
该备份也只是将 halo 的所有资源文件（包括上传的文件，主题文件，数据库文件，日志文件和配置文件）打包备份。
