### ISSUE TITLE
菜单设置了上级菜单，页面展示并没有二级菜单？

### ISSUE THREAD

**Issue by Hongjinpin** [halo-dev/halo#403]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [ ] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [x] 添加新的特性或者功能
- [x] 请求技术支持

我已经在后台菜单设置里面添加了新菜单并且关联了上级菜单，但是在页面展示的时候顶部菜单目录并没有分级

另主题next可以添加友情链接功能吗?

**Comment by ruibaby** [comment]
@Hongjinpin Next 主题不支持二级菜单。 可以添加友链。在主题设置里。

**Comment by Hongjinpin** [comment]
主题设置里面能看到友链的一些设置，但是我这边页面设置里面显示该主题不支持友链
![image](https://user-images.githubusercontent.com/20333005/69689011-adb2bb80-1102-11ea-9a7c-c8741dd3064b.png)
![image](https://user-images.githubusercontent.com/20333005/69689043-d2a72e80-1102-11ea-87e8-f3dcd0f81382.png)

**Comment by ruibaby** [comment]
@Hongjinpin Next主题没有友链页面。他的友链是放在侧边栏。 你添加之后就能看到了。

**Comment by Hongjinpin** [comment]
@ruibaby 好的，已经看到 感谢！
