### ISSUE TITLE
编辑页面布局和大纲优化

### ISSUE THREAD

**Issue by zhangmengdi123** [halo-dev/halo#4030]
### 你当前使用的版本

2.6

### 描述一下此特性

- halo的左边侧边栏能不能增加展开收缩按钮，或者像旧版本一样可以切换横竖布局，编辑页面真的很占空间

- 编辑页面的大纲详情能不能收缩展开，小屏笔记本真的没办法，编辑页面真的很占空间

**Comment by ruibaby** [comment]
> halo的左边侧边栏能不能增加展开收缩按钮，或者像旧版本一样可以切换横竖布局，编辑页面真的很占空间

关于这个，我觉得可以专门为编辑页面创建一个 Layout，不显示与编辑无关的区域。
