### ISSUE TITLE
关于附件的问题

### ISSUE THREAD

**Issue by lehhair** [halo-dev/halo#4036]
### 是什么版本出现了此问题？

 v2.5.2

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

是这样，我上传了一个附件后发现上传的文件不对，就重新上传了一个，但是这两个文件名字是一样的，最后访问url的时候下载的文件居然还是第一次上传的那个，我起初怀疑是没删掉，去容器目录看了下，文件确实被删了，但是url依旧可以访问下载文件

**Comment by ruibaby** [comment]
大概率是浏览器或者 Nginx 的 缓存，尝试清理缓存试试。

/triage duplicate

Duplicate of https://github.com/halo-dev/halo/issues/3260

**Comment by lehhair** [comment]
> 大概率是浏览器或者 Nginx 的 缓存，尝试清理缓存试试。
> 
> /triage duplicate
> 
> Duplicate of #3260
在内网curl了一下不行，应该是nginx的缓存问题
