### ISSUE TITLE
主题开发本地调试阶段怎么在前端web页实时查看效果

### ISSUE THREAD

**Issue by blackomilk** [halo-dev/halo#4037]
### Your current Halo version

2.6

### Describe this feature

主题开发本地调试阶段怎么在前端web页实时查看效果

**Comment by ruibaby** [comment]
请参考：https://docs.halo.run/developer-guide/theme/prepare

/kind support

**Comment by blackomilk** [comment]
我是用docker起的后台，环境变量加了，但是每次改完主题的代码还是都要打包手动在管理后台升级才行，怎么才能不用手动上传升级这一步呢

**Comment by guqing** [comment]
> 我是用docker起的后台，环境变量加了，但是每次改完主题的代码还是都要打包手动在管理后台升级才行，怎么才能不用手动上传升级这一步呢

 直接在 halo 的主题目录下修改主题即可，也就是 themes 目录

**Comment by guqing** [comment]
> > 我是用docker起的后台，环境变量加了，但是每次改完主题的代码还是都要打包手动在管理后台升级才行，怎么才能不用手动上传升级这一步呢
> 
> 直接在 halo 的主题目录下修改主题即可，也就是 themes 目录，你可以将 .halo2/themes 目录挂载出来

**Comment by ruibaby** [comment]
如果没有后续动态，我将关闭此 issue。

/close
