### ISSUE TITLE
升级至2.6导入数据为空

### ISSUE THREAD

**Issue by xianhuadezhuren** [halo-dev/halo#4038]
### What is version of Halo has the issue?

2.6

### What database are you using?

MySQL 5.7

### What is your deployment method?

Docker Compose

### What happened?

docker部署的1.5.4版本按照官网升级文档步骤升级至2.6，最后一步迁移导入文档时，数据是空的

**Comment by JohnNiang** [comment]
/kind support

请问如何确定数据是空的。比如导入后没有文章数据，数据库只存在一张表。

**Comment by xianhuadezhuren** [comment]
导入json文件的时候  都是0 没法导入

**Comment by JohnNiang** [comment]
如果能提供一份 JSON 文件样例会更好，方便我们复现这个问题。

**Comment by xianhuadezhuren** [comment]
可否方便邮箱发送给到你，谢谢

**Comment by JohnNiang** [comment]
> 好的 我想请问下迁移插件是需要手动在配置吗？ 我使用的镜像里面直接进管理界面就已经有了 我想是不是这个原因

Halo 在默认情况下没有安装迁移插件。可能是因为当前安装的迁移插件版本过低，建议通过 <https://halo.run/store/apps/app-TlUBt> 下载最新的迁移插件并更新。

**Comment by xianhuadezhuren** [comment]
我已经按照您说的步骤去更新安装了，导入时还是空的，我邮件发你我的后台地址及登录方式，你看看？

**Comment by JohnNiang** [comment]
我发现上传文件的时候得到了以下响应：

```bash
HTTP/1.1 413 Request Entity Too Large
Server: nginx
Date: Mon, 05 Jun 2023 09:31:08 GMT
Content-Type: text/html
Content-Length: 578
Connection: close
```

建议参考：<https://docs.halo.run/user-guide/faq#%E9%99%84%E4%BB%B6%E4%B8%8A%E4%BC%A0%E6%8F%90%E7%A4%BA-413-request-entity-too-large-%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3>。

**Comment by xianhuadezhuren** [comment]
好的，已经解决完成，谢谢您的解答
