### ISSUE TITLE
文章类跳转路由里带参怎么取值

### ISSUE THREAD

**Issue by blackomilk** [halo-dev/halo#4042]
### Your current Halo version

2.6

### Describe this feature

![image](https://github.com/halo-dev/halo/assets/42260316/96bda223-2945-495c-98f9-92dd623b91da)
在文章别名里加了一个参数lang=cn,比如这样gong-si-jian-jie?lang=cn；
在前端跳转这篇文章的时候后边加的参数总是会被转义，然后就取不到了，请问这个怎么解决

**Comment by ruibaby** [comment]
你是需要在前端拿到 lang 这个参数然后进行处理吗？

可以尝试一下使用 `decodeURIComponent`。

<img width="547" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/b3d73f88-03dc-462e-a008-c0840fd0b4bb">

/kind support
