### ISSUE TITLE
需要一个消息通知机制

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#4045]
### 你当前使用的版本

2.7.0

### 描述一下此特性

目前 Halo 2.x 还没有任何的消息通知功能，一些需要通知的场景：

1. 注册验证
2. 评论通知
3. 重置密码

所以期望能够添加此功能。

**Comment by ColanCN** [comment]
那个邮件插件不能发送通知吗？我不知道，我还没有用过那个邮件插件。

**Comment by ruibaby** [comment]
> 那个邮件插件不能发送通知吗？我不知道，我还没有用过那个邮件插件。

通知还是交给 Core 来做比较好，因为很多系统内的功能需要依赖，比如注册验证、找回密码。

**Comment by sugarlesss** [comment]
> > 那个邮件插件不能发送通知吗？我不知道，我还没有用过那个邮件插件。
> 
> 通知还是交给 Core 来做比较好，因为有些系统内的功能需要依赖，比如注册验证、找回密码。

赞成，希望通知机制早日提上日程~
