### ISSUE TITLE
希望对登录页跳转提供扩展点

### ISSUE THREAD

**Issue by guqing** [halo-dev/halo#4046]
### Your current Halo version

latest

### Describe this feature

如果想提供一个插件扩展 Halo 的安全性，如当密码错误次数超过三次则弹出两步验证或输入图形验证码，此时需要能对登录界面做一些扩展（登录请求发送成功页面跳转之前这个阶段）

### Additional information

/kind feature
/area console

**Comment by ruibaby** [comment]
这个 [issue](https://github.com/halo-dev/halo/issues/5214) 可以覆盖此 issue 的需求，所以我将关闭此 issue。

/close
