### ISSUE TITLE
Console 端预览主题时，会突然丢失登录状态

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#4047]
### 是什么版本出现了此问题？

2.6.0

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式部署？

Docker Compose

### 在线站点地址

https://ryanc.cc

### 发生了什么？

如图，此时刚登录到 Console：

<img width="1920" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/47d988a5-01bd-4939-8f4d-c5af561def51">

但重新登录之后就不会再复现，即便是退出登录之后重新登录。

/kind bug

**Comment by wonderwander** [comment]
![image](https://github.com/halo-dev/halo/assets/8736975/ee396bba-8ced-4088-be6c-e4ce83cf66a6)
2.7版本也复现了这个问题

**Comment by JohnNiang** [comment]
Hi @wonderwander ，目前暂时还不清楚具体原因，所以还未修复。

**Comment by wxyShine** [comment]
halo 2.9.2  docker+pgsql部署

在后台频繁出现 登陆失效影响正常使用后台管理
![image](https://github.com/halo-dev/halo/assets/42802152/2cb33c27-deec-4930-bedc-3643a97300c4)

多次测试发现该场景可以复现:  在https://xxxx.com/console/plugins页面 鼠标右键刷新之后会提示失效 如果还在当前路由登陆，登陆成功即立刻失效，切换到页面登陆即可正常，再次到/plugins 页面刷新还是立刻失效

**Comment by wxyShine** [comment]
使用https://demo.halo.run/console/plugins  没复现该场景，我自己站点可以重复出现该问题
