### ISSUE TITLE
建议文章内添加的外部链接的图片自动保存到本地

### ISSUE THREAD

**Issue by llllkkkkhhhh** [halo-dev/halo#4048]
### 你当前使用的版本

2.60

### 描述一下此特性

复制文章内的图片的时候，仍然保持外部的url，这会导致如果外部url链接失效，就无法观看，建议可以markdown编辑器配置的时候，可以自动保存到本地

**Comment by ruibaby** [comment]
/triage duplicate

https://github.com/halo-dev/halo/issues/2335

/close
