### ISSUE TITLE
文章页面的 head 标签内出现两个 Meta Description

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#4049]
### 是什么版本出现了此问题？

2.6.0

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式部署？

Docker

### 在线站点地址

https://halo.run

### 发生了什么？

如图：

![CleanShot 2023-06-08 at 11 17 34@2x](https://github.com/halo-dev/halo/assets/21301288/28cc5e66-935c-43d9-b362-f0dfbdbbd8af)

可以访问 https://halo.run/archives/halo-260-released 查看 HTML 源码。

/kind bug
/area core

**Comment by ruibaby** [comment]
第一个是全局的描述设置，第二个是文章根据摘要生成的，在文章这样的页面只需要第二个。

**Comment by JohnNiang** [comment]
如果出现了 name 相同的 meta 会有什么影响么？比如 SEO，浏览器解析错误。

**Comment by ruibaby** [comment]
> 如果出现了 name 相同的 meta 会有什么影响么？比如 SEO，浏览器解析错误。

来源：https://halo.run/store/apps/app-KgWqR?tab=comment

**Comment by guqing** [comment]
https://castle.co.uk/seo/duplicate-meta-descriptions/
> The best thing you can hope for with duplicate meta descriptions is that they will have no effect. Duplicate meta descriptions don’t penalise you, however, when you have the same meta description for hundreds of products, you can’t expect one key product to rank higher than another with the same meta description.
>
> Meta descriptions are a great way to sell your products or services and your brand as a whole. Even if Google doesn’t penalise you for having duplicate meta descriptions, it is a wasted opportunity to sell your brand and implement unique keywords into your descriptions in hopes that your pages start to rank for them.
