### ISSUE TITLE
上传不了主题呢?

### ISSUE THREAD

**Issue by Dz318** [halo-dev/halo#405]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [ ] [Halo 使用文档](https://halo.run/docs)
- [ ] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [ ] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [x] 请求技术支持

**Comment by Dz318** [comment]
SOS

**Comment by JohnNiang** [comment]
提供一下保存信息呢

**Comment by Dz318** [comment]
![image](https://user-images.githubusercontent.com/42438345/69781052-ef696200-11e7-11ea-8d24-d09117d1c830.png)
就是找不到安装主题的按钮，感觉这个按钮的布局可以调整一下，不注意找半天

**Comment by JohnNiang** [comment]
> ![image](https://user-images.githubusercontent.com/42438345/69781052-ef696200-11e7-11ea-8d24-d09117d1c830.png)
> 就是找不到安装主题的按钮，感觉这个按钮的布局可以调整一下，不注意找半天

我们还做了故意效果的，哈哈哈。

下次改进。

**Comment by Dz318** [comment]
![image](https://user-images.githubusercontent.com/42438345/69781684-d2359300-11e9-11ea-96a4-95c545a8bf19.png)
一不注意就可能被我的小火箭挡住了，hh
