### ISSUE TITLE
新增pdf或者office等等的附件预览功能

### ISSUE THREAD

**Issue by xiuyuanjun** [halo-dev/halo#4051]
### 你当前使用的版本

2.6.0

### 描述一下此特性

新增pdf或者office等等的附件预览功能

**Comment by ruibaby** [comment]
能具体描述一下吗，在哪里预览？

/triage needs-information

**Comment by xiuyuanjun** [comment]
文章页面，比如我在文章里面引用了一个pdf附件。是否可以在页面直接打开预览内容呢？

**Comment by ruibaby** [comment]
> 文章页面，比如我在文章里面引用了一个pdf附件。是否可以在页面直接打开预览内容呢？

你可以用网页嵌入（iframe）。

<img width="523" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/35c2fa6e-fd51-4228-a567-707629a75046">

<img width="1384" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/1cebf0e8-d39c-428d-b7bc-5c906e99340d">

**Comment by xiuyuanjun** [comment]
好的。
