### ISSUE TITLE
docker中一直pull不了

### ISSUE THREAD

**Issue by fuckhere** [halo-dev/halo#4058]
### 是什么版本出现了此问题？

所有版本

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker

### 发生了什么？

docker中一直pull不了，其他的镜像可以，但是该镜像一直waiting

**Comment by ruibaby** [comment]
检查是否是网络问题或者使用了其他的镜像源，Halo 的镜像在 Docker Hub 都是正常状态的，无法拉取似乎和 Halo 无关。

/triage duplicate

https://hub.docker.com/r/halohub/halo/tags

/close
