### ISSUE TITLE
期望提供数据库&全站迁移/转换/备份功能

### ISSUE THREAD

**Issue by Steven-WZH** [halo-dev/halo#4059]
### 你当前使用的版本

2.6.1

### 描述一下此特性

在线导出（备份）数据库和目录（.halo2/~）。可以选择导出数据库的格式，例如h2、pgsql、mysql等，并且可以选择导出文件的格式，如zip或其他格式。

此外，提供了在线导入数据库和目录（.halo2/~）的功能。您可以导入数据库表，但需要确保导入的数据库与当前使用的数据库一致。在导入完成后，系统将提示重新启动Halo容器。

举个例子，假设正在使用h2数据库的系统A，并希望将其迁移到使用pgsql数据库的系统B。先导出A的数据库和目录（.halo2/~）为pgsql格式，然后将其导入到B中。这样就实现了从A到B的迁移，并且同时切换了数据库。

这个功能可以与全站备份功能一起提供

**Comment by V-Official-233** [comment]
建议增加导出多种格式，如：zip、7z、tar、tar.gz......
