### ISSUE TITLE
期望提供如1.5x的静态存储功能

### ISSUE THREAD

**Issue by luvying** [halo-dev/halo#4087]
### 你当前使用的版本

1.5.1

### 描述一下此特性

如1.5x的【开发者选项】中的【静态存储】，能够存放其他一些静态文件，虽然2.x系统有【附件】的功能，但因某些特殊原因会使用到【静态存储】，希望开发dalao们能考虑恢复该功能，或能够有相关插件可实现此需求

**Comment by ruibaby** [comment]
/kind feature
/area plugin

在某些情况下（比如部署到 Paas 平台），可能确实不好在根目录添加文件，而有些平台（比如 Google Ads、Google Seach Console 等）需要在根目录添加文件进行验证，所以有这个功能确实会方便很多。

这个功能可以考虑使用插件来支持。

**Comment by chris-ss** [comment]
请问下目前可以通过哪个插件来实现根目录放文件？

**Comment by JohnNiang** [comment]
/assign
/milestone 2.8.x

我将尝试在 Halo 2.8 中支持在工作目录（`${halo.work-dir/static}`）中映射静态路由。
