### ISSUE TITLE
halo如何设置redis缓存？

### ISSUE THREAD

**Issue by cyril-cheng** [halo-dev/halo#4089]
### 你当前使用的版本

2.6.1

### 描述一下此特性

我使用1panel安装了halo之后，如何设置redis缓存呢？在1panel面板上没有找到设置的地方。

**Comment by ruibaby** [comment]
Halo 2 目前不支持 Redis 缓存。

**Comment by cyril-cheng** [comment]
啊？我看官网文档上写支持redis的嘛。https://docs.halo.run/getting-started/config/

**Comment by JohnNiang** [comment]
> 啊？我看官网文档上写支持redis的嘛。https://docs.halo.run/getting-started/config/

这个应该还是 1.x 的文档，目前 2.x 的文章中没有对应的菜单。保留 1.x 的文档链接，主要是为了防止死链。

**Comment by ruibaby** [comment]
目前 Halo 2 暂时没有数据缓存的功能或者需求，如果需要缓存，建议我们再提交一个 issue 来跟踪，这个 issue 我先关闭。

/kind support
/close
