### ISSUE TITLE
上传找不到说明文件

### ISSUE THREAD

**Issue by Demonya** [halo-dev/halo#409]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x ] [Halo 使用文档](https://halo.run/docs)
- [x ] [Halo 论坛](https://bbs.halo.run)
- [x ] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [ x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [ x] 请求技术支持

上传主题包报错：
1575328779533.jpg

**Comment by Demonya** [comment]
/Users/yanhaifeng/Desktop/1575328779533.jpg

**Comment by JohnNiang** [comment]
截图可以直接粘贴在 Github 编辑框中。同时也建议提供一下主题文件。
