### ISSUE TITLE
Reconciling request Request[name=PluginS3ObjectStorage]

### ISSUE THREAD

**Issue by cqy19950601** [halo-dev/halo#4093]
### 是什么版本出现了此问题？

2.6

### 使用的什么数据库？

MySQL 5.7

### 使用的哪种方式部署？

Docker Compose

### 发生了什么？

Reconciling request Request[name=PluginS3ObjectStorage] not version match ，现在都把内存打爆了，一直反复加入队列 

### 相关日志输出

```shell
Adding request Request[name=PluginS3ObjectStorage] after PT0.005S
```

**Comment by JohnNiang** [comment]
/triage needs-information

建议提供一下详细的复现步骤。

**Comment by cqy19950601** [comment]
1.步骤1我在halo发布 插件后，数据库报version not match
2.然后看后台日志 一直报
2023-06-19T15:03:26.897+08:00 DEBUG 1 --- [-netty-thread-4] r.h.a.extension.controller.DefaultQueue : Adding request Request[name=PluginS3ObjectStorage] immediately
Mon, Jun 19 2023 3:03:26 pm | 2023-06-19T15:03:26.897+08:00 DEBUG 1 --- [-netty-thread-4] r.h.a.extension.controller.DefaultQueue : Adding request Request[name=PluginS3ObjectStorage] after PT0.005S
Mon, Jun 19 2023 3:03:26 pm | 2023-06-19T15:03:26.913+08:00 INFO 1 --- [-netty-thread-4] h.a.e.s.ReactiveExtensionStoreClientImpl : 当前版本号:/registry/plugin.halo.run/plugins/PluginS3ObjectStorage,60702

**Comment by JohnNiang** [comment]
建议提供完整的错误日志（目前的错误片段无法定位具体的问题），这样我才能理解上下文，具体发生了什么。

我在 Halo 侧安装 s3 插件，并没有遇到以上问题。

**Comment by cqy19950601** [comment]
<html>
<body>


Reconciler in run.halo.app.core.extension.reconciler.PostReconciler-worker-7 aborted with an error, re-enqueuing...
--
Mon, Jun 19 2023 3:20:52 pm |  
Mon, Jun 19 2023 3:20:52 pm | org.springframework.dao.DataAccessResourceFailureException: Failed to obtain R2DBC Connection 2023-06-19T07:20:52.826516983Z at org.springframework.r2dbc.connection.ConnectionFactoryUtils.lambda$getConnection$0(ConnectionFactoryUtils.java:90) ~[spring-r2dbc-6.0.4.jar!/:6.0.4] 2023-06-19T07:20:52.826525303Z at reactor.core.publisher.Mono.lambda$onErrorMap$28(Mono.java:3763) ~[reactor-core-3.5.2.jar!/:3.5.2] 2023-06-19T07:20:52.826533393Z at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94) ~[reactor-core-3.5.2.jar!/:3.5.2]
Mon, Jun 19 2023 3:20:52 pm | at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106) ~[reactor-core-3.5.2.jar!/:3.5.2]
Mon, Jun 19 2023 3:20:52 pm | at reactor.core.publisher.FluxRetry$RetrySubscriber.onError(FluxRetry.java:95) ~[reactor-core-3.5.2.jar!/:3.5.2] 2023-06-19T07:20:52.826551303Z at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:180) ~[reactor-core-3.5.2.jar!/:3.5.2]
Mon, Jun 19 2023 3:20:52 pm | at reactor.pool.AbstractPool$Borrower.fail(AbstractPool.java:475) ~[reactor-pool-1.0.0.jar!/:1.0.0] 2023-06-19T07:20:52.826562243Z at reactor.pool.SimpleDequePool.lambda$drainLoop$9(SimpleDequePool.java:429) ~[reactor-pool-1.0.0.jar!/:1.0.0] 2023-06-19T07:20:52.826567724Z at reactor.core.publisher.FluxDoOnEach$DoOnEachSubscriber.onError(FluxDoOnEach.java:186) ~[reactor-core-3.5.2.jar!/:3.5.2]
Mon, Jun 19 2023 3:20:52 pm | at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onError(FluxMapFuseable.java:340) ~[reactor-core-3.5.2.jar!/:3.5.2]
Mon, Jun 19 2023 3:20:52 pm | at reactor.core.publisher.MonoCompletionStage$MonoCompletionStageSubscription.apply(MonoCompletionStage.java:114) ~[reactor-core-3.5.2.jar!/:3.5.2]
Mon, Jun 19 2023 3:20:52 pm | at reactor.core.publisher.MonoCompletionStage$MonoCompletionStageSubscription.apply(MonoCompletionStage.java:64) ~[reactor-core-3.5.2.jar!/:3.5.2] 2023-06-19T07:20:52.826596994Z at java.base/java.util.concurrent.CompletableFuture.uniHandle(Unknown Source) ~[na:na]
Mon, Jun 19 2023 3:20:52 pm | at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source) ~[na:na] 2023-06-19T07:20:52.826608484Z at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[na:na] 2023-06-19T07:20:52.826614294Z at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) ~[na:na]
Mon, Jun 19 2023 3:20:52 pm | at com.github.jasync.sql.db.util.FutureUtilsKt.tryFailure(FutureUtils.kt:21) ~[jasync-pool-2.1.23.jar!/:na]
Mon, Jun 19 2023 3:20:52 pm | at com.github.jasync.sql.db.pool.TimeoutSchedulerImpl$addTimeout$1$scheduledFuture$1.invoke(TimeoutScheduler.kt:63) ~[jasync-common-2.1.23.jar!/:na] 2023-06-19T07:20:52.826631965Z at com.github.jasync.sql.db.pool.TimeoutSchedulerImpl$addTimeout$1$scheduledFuture$1.invoke(TimeoutScheduler.kt:62) ~[jasync-common-2.1.23.jar!/:na]
Mon, Jun 19 2023 3:20:52 pm | at com.github.jasync.sql.db.pool.TimeoutSchedulerImpl.schedule$lambda-0(TimeoutScheduler.kt:51) ~[jasync-common-2.1.23.jar!/:na] 2023-06-19T07:20:52.826643015Z at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[netty-common-4.1.87.Final.jar!/:4.1.87.Final] 2023-06-19T07:20:52.826648565Z at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153) ~[netty-common-4.1.87.Final.jar!/:4.1.87.Final] 2023-06-19T07:20:52.826654225Z at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.87.Final.jar!/:4.1.87.Final]
Mon, Jun 19 2023 3:20:52 pm | at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.87.Final.jar!/:4.1.87.Final]
Mon, Jun 19 2023 3:20:52 pm | at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.87.Final.jar!/:4.1.87.Final] 2023-06-19T07:20:52.826670935Z at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:406) ~[netty-transport-classes-epoll-4.1.87.Final.jar!/:4.1.87.Final] 2023-06-19T07:20:52.826676456Z at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.87.Final.jar!/:4.1.87.Final]
Mon, Jun 19 2023 3:20:52 pm | at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.87.Final.jar!/:4.1.87.Final] 2023-06-19T07:20:52.826688206Z at java.base/java.lang.Thread.run(Unknown Source) ~[na:na] 2023-06-19T07:20:52.826694226Z Suppressed: java.lang.Exception: #block terminated with an error 2023-06-19T07:20:52.826706646Z at reactor.core.publisher.BlockingOptionalMonoSubscriber.blockingGet(BlockingOptionalMonoSubscriber.java:123) ~[reactor-core-3.5.2.jar!/:3.5.2]
Mon, Jun 19 2023 3:20:52 pm | at reactor.core.publisher.Mono.blockOptional(Mono.java:1755) ~[reactor-core-3.5.2.jar!/:3.5.2] 2023-06-19T07:20:52.826718006Z at run.halo.app.extension.DelegateExtensionClient.fetch(DelegateExtensionClient.java:37) ~[classes!/:1.0-SNAPSHOT] 2023-06-19T07:20:52.826723536Z at run.halo.app.core.extension.reconciler.PostReconciler.publishPost(PostReconciler.java:110) ~[classes!/:1.0-SNAPSHOT] 2023-06-19T07:20:52.826729117Z at run.halo.app.core.extension.reconciler.PostReconciler.lambda$reconcileSpec$1(PostReconciler.java:101) ~[classes!/:1.0-SNAPSHOT] 2023-06-19T07:20:52.826734587Z at java.base/java.util.Optional.ifPresent(Unknown Source) ~[na:na] 2023-06-19T07:20:52.826739977Z at run.halo.app.core.extension.reconciler.PostReconciler.reconcileSpec(PostReconciler.java:89) ~[classes!/:1.0-SNAPSHOT] 2023-06-19T07:20:52.826749207Z at run.halo.app.core.extension.reconciler.PostReconciler.lambda$reconcile$0(PostReconciler.java:72) ~[classes!/:1.0-SNAPSHOT] 2023-06-19T07:20:52.826755017Z at java.base/java.util.Optional.ifPresent(Unknown Source) ~[na:na] 2023-06-19T07:20:52.826760487Z at run.halo.app.core.extension.reconciler.PostReconciler.reconcile(PostReconciler.java:64) ~[classes!/:1.0-SNAPSHOT] 2023-06-19T07:20:52.826766117Z at run.halo.app.core.extension.reconciler.PostReconciler.reconcile(PostReconciler.java:50) ~[classes!/:1.0-SNAPSHOT] 2023-06-19T07:20:52.826771497Z at run.halo.app.extension.controller.DefaultController$Worker.run(DefaultController.java:163) ~[classes!/:1.0-SNAPSHOT] 2023-06-19T07:20:52.826777357Z at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na] 2023-06-19T07:20:52.826783118Z at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na] 2023-06-19T07:20:52.826788648Z at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na] 2023-06-19T07:20:52.826794038Z at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na] 2023-06-19T07:20
  | :52.826800938Z ... 1 common frames omitted 2023-06-19T07:20:52.826806728Z Caused by: java.util.concurrent.TimeoutException: Operation timeout after it took too long to return (PT5S)


</body>
</html>

**Comment by cqy19950601** [comment]
2023-06-19T15:30:48.336+08:00 DEBUG 1 --- [-netty-thread-2] a.w.r.e.AbstractErrorWebExceptionHandler : [09ead6dd-107] Resolved [OptimisticLockingFailureException: Failed to update table [extensions]; Version does not match for row with Id [/registry/plugin.halo.run/plugins/PluginS3ObjectStorage]] for HTTP PUT /apis/plugin.halo.run/v1alpha1/plugins/PluginS3ObjectStorage
--
Mon, Jun 19 2023 3:30:48 pm | 2023-06-19T15:30:48.336+08:00 ERROR 1 --- [-netty-thread-2] a.w.r.e.AbstractErrorWebExceptionHandler : [09ead6dd-107] 500 Server Error for HTTP PUT "/apis/plugin.halo.run/v1alpha1/plugins/PluginS3ObjectStorage"
Mon, Jun 19 2023 3:30:48 pm | Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 2023-06-19T07:30:48.340593267Z Error has been observed at the following site(s): 2023-06-19T07:30:48.340598787Z *__checkpoint ⇢ run.halo.app.console.ConsoleProxyFilter [DefaultWebFilterChain] 2023-06-19T07:30:48.340604678Z *__checkpoint ⇢ AuthorizationWebFilter [DefaultWebFilterChain] 2023-06-19T07:30:48.340611178Z *__checkpoint ⇢ ExceptionTranslationWebFilter [DefaultWebFilterChain] 2023-06-19T07:30:48.340615778Z *__checkpoint ⇢ LogoutWebFilter [DefaultWebFilterChain] 2023-06-19T07:30:48.340620378Z *__checkpoint ⇢ ServerRequestCacheWebFilter [DefaultWebFilterChain] 2023-06-19T07:30:48.340624798Z *__checkpoint ⇢ SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain] 2023-06-19T07:30:48.340629408Z *__checkpoint ⇢ LogoutPageGeneratingWebFilter [DefaultWebFilterChain] 2023-06-19T07:30:48.340633808Z *__checkpoint ⇢ LoginPageGeneratingWebFilter [DefaultWebFilterChain]
Mon, Jun 19 2023 3:30:48 pm | at org.springframework.data.r2dbc.core.R2dbcEntityTemplate.lambda$doUpdate$13(R2dbcEntityTemplate.java:636) ~[spring-data-r2dbc-3.0.1.jar!/:3.0.1] 2023-06-19T07:30:48.340703899Z at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:112) ~[reactor-core-3.5.2.jar!/:3.5.2] 2023-06-19T07:30:48.340708649Z at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79) ~[reactor-core-3.5.2.jar!/:3.5.2] 2023-06-19T07:30:48.340712950Z at reactor.core.publisher.MonoUsingWhen$MonoUsingWhenSubscriber.deferredComplete(MonoUsingWhen.java:268) ~[reactor-core-3.5.2.jar!/:3.5.2] 2023-06-19T07:30:48.340717280Z at reactor.core.publisher.FluxUsingWhen$CommitInner.onComplete(FluxUsingWhen.java:527) ~[reactor-core-3.5.2.jar!/:3.5.2] 2023-06-19T07:30:48.340721690Z at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2205) ~[reactor-core-3.5.2.jar!/:3.5.2] 2023-06-19T07:30:48.340726040Z at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260) ~[reactor-core-3.5.2.jar!/:3.5.2] 2023-06-19T07:30:48.340730400Z at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2205) ~[reactor-core-3.5.2.jar!/:3.5.2] 2023-06-19T07:30:48.340734770Z at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:209) ~[reactor-core-3.5.2.jar!/:3.5.2]
Mon, Jun 19 2023 3:30:48 pm | at reactor.core.publisher.Mono.subscribe(Mono.java:4444) ~[reactor-core-3.5.2.jar!/:3.5.2] 2023-06-19T07:30:48.340913233Z at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103) ~[reactor-core-3.5.2.jar!/:3.5.2] 2023-06-19T07:30:48.340918873Z at reactor.core.publisher.MonoIgnoreElements$IgnoreElementsSubscriber.onError(MonoIgnoreElements.java:84) ~[reactor-core-3.5.2.jar!/:3.5.2] 2023-06-19T07:30:48.340924393Z at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:134) ~[reactor-core-3.5.2.jar!/:3.5.2]
Mon, Jun 19 2023 3:30:48 pm | at reactor.core.publisher.FluxFilter$FilterSubscriber.onError(FluxFilter.java:157) ~[reactor-core-3.5.2.jar!/:3.5.2] 2023-06-19T07:30:48.340943884Z at reactor.core.publisher.FluxFilter$FilterConditionalSubscriber.onError(FluxFilter.java:291) ~[reactor-core-3.5.2.jar!/:3.5.2] 2023-06-19T07:30:48.340949334Z at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onError(FluxMap.java:265) ~[reactor-core-3.5.2.jar!/:3.5.2] 2023-06-19T07:30:48.340953664Z at reactor.core.publisher.Operators.error(Operators.java:198) ~[reactor-core-3.5.2.jar!/:3.5.2] 2023-06-19T07:30:48.340957944Z at reactor.core.publisher.MonoError.subscribe(MonoError.java:53) ~[reactor-core-3.5.2.jar!/:3.5.2]
Mon, Jun 19 2023 3:30:48 pm | 2023-06-19T15:30:48.346+08:00 ERROR 1 --- [tReconciler-t-4] r.h.app.theme.router.PermalinkIndexer : Permalink [http://localhost:80/archives/private-mode-on-mac-and-the-best-alternative] already exists, you can try to change the slug [ExtensionLocator[gvk=content.halo.run/v1alpha1/Post, name=2d850635-cb71-47fb-a033-e50c5e2c9000, slug=private-mode-on-mac-and-the-best-alternative]].
Mon, Jun 19 2023 3:31:16 pm | 2023-06-19T15:31:16.370+08:00 ERROR 1 --- [tReconciler-t-9] r.h.app.theme.router.PermalinkIndexer : Permalink [http://localhost:80/archives/iphtml] already exists, you can try to change the slug [ExtensionLocator[gvk=content.halo.run/v1alpha1/Post, name=326ddead-13e4-4bde-851e-d23a5fd318ca, slug=iphtml]].

**Comment by cqy19950601** [comment]
现在由于后台大量跑这个队列线程，导致版本号异常了

**Comment by JohnNiang** [comment]
1. 根据你的描述，我无法复现这个问题。
2. 根据你提供的日志，我无法定位问题。
