### ISSUE TITLE
希望可以修改用户名或者设置用户名不显示在文章详情页面中

### ISSUE THREAD

**Issue by YyJqW** [halo-dev/halo#4095]
### 你当前使用的版本

2.6.0

### 描述一下此特性

文章详情页面中，在页面底部，头像下方会显示该文章作者在系统中的用户名而不是显示名称，同时头像标签内的链接也会包含用户名
让我困扰的在于，在halo早期版本中我直接使用了自己其他社交帐号的号码来作为halo用户的用户名，如今无法修改或隐藏用户名使得我的其他社交媒体账号在halo中暴露

**Comment by ruibaby** [comment]
这不是 Halo 本身可以控制的功能，建议向具体的主题提交 issue。

此外，我认为这个功能可能有点客制化，如果有强需求，可以考虑 fork 主题自行修改。

/close
/kind support
