### ISSUE TITLE
关于修改保存文章信息后自动跳转到列表首位的修改建议

### ISSUE THREAD

**Issue by yikexiaoyao** [halo-dev/halo#4098]
### 你当前使用的版本

2.6.0

### 描述一下此特性

每次修改保存文章信息后，都会自动跳转到列表首位，每次都要重新寻找文章所在页和位置，如果只是修改个别文章的内容倒还好，假如需要批量修改数据就会很麻烦，希望能增加定位功能，记录打开修改页面之前的浏览坐标，也可以使刚刚提交的文章标题在列表页面居中，可以提升浏览体验，个人建议，如若可行，望采纳，感谢

**Comment by ruibaby** [comment]
应该是需要将列表的查询参数放到地址栏，确实有这个计划。 1.x 时期是有这样的功能的。

/remove-area editor
/area console

**Comment by ruibaby** [comment]
我先对文章的管理列表进行修改，其他的数据管理列表会逐步支持。

**Comment by guqing** [comment]
如果能有一个选中效果就更好了，比如编辑完文章 A 跳转到列表后，文章 A 的背景有一个灰色背景效果

**Comment by ruibaby** [comment]
> 如果能有一个选中效果就更好了，比如编辑完文章 A 跳转到列表后，文章 A 的背景有一个灰色背景效果

好好好
