### ISSUE TITLE
新增分类之后没有生成对应的链接

### ISSUE THREAD

**Issue by xiongtete0519** [halo-dev/halo#4107]
### 是什么版本出现了此问题？

2.2.0

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker

### 在线站点地址

https://codeleader.top/

### 发生了什么？

新建分类之后没有生成对应的访问链接
![image](https://github.com/halo-dev/halo/assets/66518135/302cb835-38ca-4306-a7ef-cab8b325cd72)

然后去菜单管理那里新增之后，名字是个空的
![image](https://github.com/halo-dev/halo/assets/66518135/686f45ab-dbd1-4c1a-841e-c6c26656971f)

**Comment by ruibaby** [comment]
建议在最新的版本尝试一下，看看能不能复现。

**Comment by ruibaby** [comment]
如果没有后续动态，我将关闭此 issue，如有需要可以重新打开或者新建 issue。

/close
