### ISSUE TITLE
远程拉起主题报“theme install error"

### ISSUE THREAD

**Issue by StrawHat179** [halo-dev/halo#4109]
### 是什么版本出现了此问题？

2.6.1

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker

### 发生了什么？

用1panel进行部署的

### 附加信息

![image](https://github.com/halo-dev/halo/assets/104472839/670b688f-c7f8-4c48-adcf-a43a74c1efd6)

**Comment by ruibaby** [comment]
1. 目前不支持通过 Git 下载，链接最终下载的格式只能是 zip。
2. 你这个主题应该是 1.x 的，2.x 不兼容。

/kind support

**Comment by StrawHat179** [comment]
使用仓库地址进行下载吗？git下载的格式就是zip啊，我试了好几个主题都是这样，相同的报错，有没有可能是因为1panel面板安装导致的

**Comment by ruibaby** [comment]
你截图里的地址对于下载来说只是个网页，而不是 zip，你可以尝试这样的链接 https://github.com/halo-dev/theme-earth/archive/refs/heads/main.zip 或者 https://github.com/halo-dev/theme-earth/archive/refs/tags/v1.4.0.zip

你也可以去 https://halo.run/store/apps 中找兼容 2.x 的主题进行远程下载。

**Comment by StrawHat179** [comment]
好的，明白了，谢谢

**Comment by StrawHat179** [comment]
![image](https://github.com/halo-dev/halo/assets/104472839/4debba63-c165-4cc3-b9f8-2c3de9426f35)
刚试了，也不行，一样的报错，地址“https://github.com/qinhua/halo-theme-joe2.0/archive/refs/tags/1.0.10.zip”

**Comment by ruibaby** [comment]
https://github.com/qinhua/halo-theme-joe2.0 不支持 Halo 2.0+

**Comment by StrawHat179** [comment]
好的，我再试试其他的主题
