### ISSUE TITLE
我换成maven了，现在还好

### ISSUE THREAD

**Issue by jiaogug** [halo-dev/halo#411]
我换成maven了，现在还好

| |
东
邮箱：haodedong1996@163.com
|

签名由 网易邮箱大师 定制

在2019年11月03日 09:46，John Niang 写道：

gradle 版本可能需要升级至 5.2.1 及以上。

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.

_Originally posted by @haodedong in https://github.com/halo-dev/halo/issues/359#issuecomment-549197796_

**Comment by ruibaby** [comment]
哦
