### ISSUE TITLE
docker-compose部署报错

### ISSUE THREAD

**Issue by testnet0** [halo-dev/halo#4110]
### 是什么版本出现了此问题？

2.6.0

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker Compose

### 发生了什么？

#docker-compose up
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.halo.healthcheck value Additional properties are not allowed ('start_period' was unexpected)
services.halodb.healthcheck value Additional properties are not allowed ('start_period' was unexpected)
services.halo.depends_on contains an invalid type, it should be an array

docker-compose启动报错

Docker version 20.10.5, build 55c4c88

docker-compose version 1.16.1, build 6d1ac21

**Comment by ruibaby** [comment]
尝试升级 Docker 和 Compose，这个错误是你当前 Docker Compose 的版本与 docker-compose.yaml 不兼容。

/kind support
