### ISSUE TITLE
可否新增附件下载功能

### ISSUE THREAD

**Issue by xiuyuanjun** [halo-dev/halo#4122]
### 你当前使用的版本

2.6.0

### 描述一下此特性

有些博客文章会需要一些附件，能否新增出这样一个功能可以提供附件的下载。而不是使用第三方的功能，比如粘贴百度网盘之类的下载链接。

**Comment by JohnNiang** [comment]
/kind feature

目前，我们的附件都是公开访问的，可以将链接放在文章内容中供读者下载。如果我理解得有问题，请随时补充。或者你可以更详细描述一下想要实现的效果。

**Comment by xiuyuanjun** [comment]
对于不可预览的附件，如何提供下载功能？将链接放在文章中是什么意思？[xxxxx.tar.gz](/upload/xxxx.tar.gz)像这样吗？试了一下，并不能下载。
