### ISSUE TITLE
可以通过不重新编译修改源码的方式扩充Finder API的方法吗

### ISSUE THREAD

**Issue by pandatools** [halo-dev/halo#4127]
### Your current Halo version

2.6.0

### Describe this feature

想要自定义一些Finder API的方法，比如categoryFinder.getParent()之类的，能够不通过修改halo源码的方式实现吗，比如通过添加插件实现

**Comment by guqing** [comment]
可以使用插件添加 finder 参考 https://github.com/halo-sigs/plugin-links/blob/main/src/main/java/run/halo/links/finders/impl/LinkFinderImpl.java
