### ISSUE TITLE
访问首页会重定向跳转到后台管理地址 /console

### ISSUE THREAD

**Issue by hlovingness** [halo-dev/halo#4130]
### 是什么版本出现了此问题？

2.6

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker Compose

### 发生了什么？

删除了数据库，删除数据库之前导出了 sql，然后再导入sql后，访问首页就会重定向到后台地址 console，后台功能正常，就是访问不到前台

**Comment by ruibaby** [comment]
cc @guqing 

/kind support

**Comment by guqing** [comment]
重启一下 Halo 试试 ，因为你是通过 sql 导入的 halo 检测不到状态
