### ISSUE TITLE
使用搜索插件报错

### ISSUE THREAD

**Issue by qq1162411932** [halo-dev/halo#4131]
### What is version of Halo has the issue?

2.6

### What database are you using?

MySQL 8.x

### What is your deployment method?

Docker Compose

### What happened?

![image](https://github.com/halo-dev/halo/assets/69759290/92514ffa-244b-432c-884c-a491542a1de9)
后台日志错误为 

![image](https://github.com/halo-dev/halo/assets/69759290/66ceb0f7-ca3a-4722-9c47-f15551f2a2a0)

**Comment by ruibaby** [comment]
好像是索引文件有问题，可以尝试一下重建索引。

<img width="699" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/245227c3-7c16-4943-baa3-b3fd888d4b82">

/kind support

**Comment by qq1162411932** [comment]
刷新索引报错
![1687920688805](https://github.com/halo-dev/halo/assets/69759290/30e734e3-bca5-40c6-932c-57d3c07a9cac)

**Comment by JohnNiang** [comment]
Hi @qq1162411932 , 建议进入 halo 容器，并删除掉目录：`/root/.halo2/indices`，再试试。同时如果能够提供一份完整的错误日志就更好了，可以帮助我们排查这个问题。

**Comment by qq1162411932** [comment]
删除目录，重新刷新成功，可能是初始化的时候索引有问题
