### ISSUE TITLE
希望编辑器能支持 [TOC] 目录

### ISSUE THREAD

**Issue by psc1453** [halo-dev/halo#4133]
### 你当前使用的版本

2.6

### 描述一下此特性

在以前 1.x 的时候，编辑器内可以用 [TOC] 直接插入带页内超链接的目录，而目前 Halo 2.x 中，我试了 default，bytemd 和 stackedit 都用不了，文章发布后 `[TOC]` 会以文本的形式直接出现在文章中，虽然 [TOC] 是 Markdown 的拓展指令，但以前 1.x 的时候都可以用的，希望 2.x 中也能继续支持。感谢。

**Comment by ruibaby** [comment]
如果是在文章内保存 TOC 目录结构的话，可能需要各个编辑器都支持，因为目前编辑器渲染结果不受后端干预，都是前端渲染好之后保存的。

此外，在前端可以用 https://tscanlin.github.io/tocbot/ 之类的工具来生成。

/kind support

**Comment by shy-share** [comment]
@psc1453 
![image](https://github.com/halo-dev/halo/assets/50973219/c14941bf-7126-4cf1-a760-434275019d5a)
bytemd 这样不符合你的描述吗?

**Comment by ruibaby** [comment]
> bytemd 这样不符合你的描述吗?

@shy-share 这应该只是在编辑器上显示 TOC，实际发布之后没有。

**Comment by shy-share** [comment]
> > bytemd 这样不符合你的描述吗?
> 
> @shy-share 这应该只是在编辑器上显示 TOC，实际发布之后没有。

实际发布之后，在外部访问文章页面的时候  有toc插件支持的呀  可能他用的主题刚好不支持？

**Comment by psc1453** [comment]
> > > bytemd 这样不符合你的描述吗?
> 
> > 
> 
> > @shy-share 这应该只是在编辑器上显示 TOC，实际发布之后没有。
> 
> 
> 
> @ruibaby  实际发布之后，在外部访问文章页面的时候  有toc插件支持的呀  可能他用的主题刚好不支持？

TOC 插件实现的是在文章之外有一个模块可以显示目录内容，即使不使用 Markdown 的拓展指令 [TOC] 也可显示。我之前想寻求的是在文章内使用 [TOC] 指令以实现自动生成页内超链接的形式显示的目录，同时这个目录可以根据 [TOC] 指令位置的不同放在文章内任何位置。不过以 Halo 2.x 的架构来看，好像的确得编辑器支持才行。

**Comment by shy-share** [comment]
> 



> > > > bytemd 这样不符合你的描述吗?
> > 
> > 
> > > 
> > 
> > 
> > > @shy-share 这应该只是在编辑器上显示 TOC，实际发布之后没有。
> > 
> > 
> > @ruibaby  实际发布之后，在外部访问文章页面的时候  有toc插件支持的呀  可能他用的主题刚好不支持？
> 
> TOC 插件实现的是在文章之外有一个模块可以显示目录内容，即使不使用 Markdown 的拓展指令 [TOC] 也可显示。我之前想寻求的是在文章内使用 [TOC] 指令以实现自动生成页内超链接的形式显示的目录，同时这个目录可以根据 [TOC] 指令位置的不同放在文章内任何位置。不过以 Halo 2.x 的架构来看，好像的确得编辑器支持才行。

哦哦 那确实
