### ISSUE TITLE
文字修改

### ISSUE THREAD

**Issue by hyfree** [halo-dev/halo#4140]
### 描述一下此特性

https://demo.halo.run/console/umami
中的"Countries"修改为"Countries/Region"

**Comment by ruibaby** [comment]
这个问题建议向 Umami 提交 issue，plugin-umami 只是集成了 Umami ，我们无法直接修改 UI。

https://github.com/umami-software/umami

语言包代码：https://github.com/search?q=repo%3Aumami-software%2Fumami+label.countries&type=code

/kind support
