### ISSUE TITLE
halo2.6无法访问console后台

### ISSUE THREAD

**Issue by JinLiGame** [halo-dev/halo#4141]
### 是什么版本出现了此问题？

Halo2.6

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker Compose

### 发生了什么？

我用docker-compose和1panel分别部署的halo2.6都不能访问console后台，端口号都已经开了，而且外部访问连接改成域名和ip+port也都不行，不知道什么原因，希望大佬帮忙看看，下边分别是我用docker-compose和1panel部署配置
![1687943903852](https://github.com/halo-dev/halo/assets/53973570/1c4041fc-a7fa-4f78-b138-b8c7d69e93aa)
![1687943845573](https://github.com/halo-dev/halo/assets/53973570/f60dea0b-43ac-4c92-9cf5-0e7cea213181)

**Comment by JohnNiang** [comment]
/kind support

为什么 Docker compose 中配置的端口是 8091 呢？如果只想要更改端口，需要保留后半部分的配置，例如 `8091:8090`。
