### ISSUE TITLE
manifest for docker.io/halohub/halo:2.6 not found

### ISSUE THREAD

**Issue by ZhangWY0724** [halo-dev/halo#4142]
### 是什么版本出现了此问题？

2.6

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker Compose

### 发生了什么？

过程：
1.使用docker-compose文件部署时提示
Pulling halo (halohub/halo:2.6)...
Trying to pull repository docker.io/halohub/halo ... 
ERROR: manifest for docker.io/halohub/halo:2.6 not found

2.随后换成**docker pull halohub/halo:2.6**指令单独拉取halo，出现下列提示
manifest for docker.io/halohub/halo:2.6 not found

3.使用docker info查看源为
Registry Mirrors:
 https://registry.docker-cn.com

望处理。

**Comment by ruibaby** [comment]
/triage duplicate

see https://github.com/halo-dev/halo/issues/4058

这个问题与你网络和镜像源的连接以及源的镜像同步状态有关，我们无法干预。

**Comment by ZhangWY0724** [comment]
我尝试不带版本号拉取，镜像创建时间显示为7个月前
![image](https://github.com/halo-dev/halo/assets/65152647/19f0a251-726d-4717-9f41-c72ea0a336de)

**Comment by ZhangWY0724** [comment]
> 

有什么建议吗

**Comment by ruibaby** [comment]
latest 标签是 1.x 的版本，2.0 没有更新 latest 标签。

我的建议是更换镜像源或者开代理。

**Comment by ZhangWY0724** [comment]
用哪个源

**Comment by ruibaby** [comment]
> 用哪个源

我们也没有推荐的源，这个只能自己尝试了。

**Comment by JohnNiang** [comment]
目前我用的 aliyun 的 mirror 是可以正常拉取镜像的。

**Comment by ZhangWY0724** [comment]
重新安装docker换源后，已成功拉取部署，感觉大佬们支持。
