### ISSUE TITLE
halo数据迁移，预览文章图片破图

### ISSUE THREAD

**Issue by wyl985** [halo-dev/halo#4148]
### 是什么版本出现了此问题？

halo2.4.0

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker

### 发生了什么？

图片是上传到A服务器后台的，然后A服务器编辑文章上传图片。然后将A服务器整个挂载到宿主机的halo文件夹迁移到B服务器，然后在B服务器上部署halo，访问B服务器预览文章会破图。

因为是编辑图片的时候，完整的保存的图片的链接，这对于外链来说当然是正确的，但是对于内链，因为其他原因一旦迁移服务器，就会出现破图的问题

### 附加信息

![fff2369069f3fb40197aa87f3818d60](https://github.com/halo-dev/halo/assets/31380874/a9101417-d09b-4448-8c4b-127f25aaa594)

**Comment by ruibaby** [comment]
如果是因为切换了域名，这种情况你只能手动修改图片的链接，你切换域名之后并不能够自动去修改已保存的内容。

此外，建议升级到 2.5.0 以上的版本，在这个版本后，从附件库插入图片会默认使用相对地址，切换域名后不会收到影响。

https://github.com/halo-dev/halo/releases/tag/v2.5.0

/kind support

**Comment by wyl985** [comment]
谢谢，有空我升级下halo版本试一试
