### ISSUE TITLE
友联评论-缺失请求主体

### ISSUE THREAD

**Issue by yangpin97** [halo-dev/halo#4157]
### 是什么版本出现了此问题？

1.6.1

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker Compose

### 在线站点地址

https://yydy.fun:2023/links

### 发生了什么？

报错页面图：
https://img.gugu.ovh/i/2023/06/30/qudv0.webp

### 附加信息

用的是dream主题
博客评论设置图：https://img.gugu.ovh/i/2023/06/30/s01on.webp

**Comment by JohnNiang** [comment]
/triage needs-information

建议提供一下错误日志，已经错误请求的请求体和响应体。

**Comment by yangpin97** [comment]
以找到问题，不是halo的问题。



***@***.***
 
发件人： John Niang
发送时间： 2023-06-30 11:23
收件人： halo-dev/halo
抄送： yangpin97; Author
主题： Re: [halo-dev/halo] 友联评论-缺失请求主体 (Issue #4157)
/triage needs-information
建议提供一下错误日志，已经错误请求的请求体和响应体。
―

**Comment by JohnNiang** [comment]
/close

有任何问题请随时重新打开。
