### ISSUE TITLE
docker 安装后，界面默认为英文，如何修改为中文？

### ISSUE THREAD

**Issue by dudiao** [halo-dev/halo#4162]
### 是什么版本出现了此问题？

2.6.1

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

<img width="917" alt="image" src="https://github.com/halo-dev/halo/assets/38355949/21caea8e-43ef-4181-ab7f-32d7e322f4f0">

**Comment by ruibaby** [comment]
登录页面底部可以切换。

<img width="1013" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/197a7c25-91d9-4341-a1c6-2053781384c0">

目前选择语言的策略是：

1. 首次访问的情况会根据浏览器设置的语言而定。
2. 选择语言之后会缓存选项到浏览器。

**Comment by dudiao** [comment]
@ruibaby 好的，谢谢

**Comment by Jackiexiao** [comment]
建议允许在登录后切换语言. 另外, 现在如果是英文的话, 很多设置是中文....
