### ISSUE TITLE
编辑器的图片编辑框杂乱，建议浏览到下一张图片时就取消上个文件的编辑框

### ISSUE THREAD

**Issue by mobeicanyue** [halo-dev/halo#4164]
### 你当前使用的版本

2.7.0

### 描述一下此特性

如题
我觉得可以整理一下
![image](https://github.com/halo-dev/halo/assets/81098819/1dcc8be6-2cc7-4ad5-8e9e-dbc12e7f226e)
![image](https://github.com/halo-dev/halo/assets/81098819/aa64ff6d-290a-4d2f-9812-3fda645c1bfb)

**Comment by ruibaby** [comment]
已经在编辑器的仓库提了个 issue：https://github.com/halo-sigs/richtext-editor/issues/18

/area editor
/kind improvement
