### ISSUE TITLE
默认编辑器建议

### ISSUE THREAD

**Issue by Alfy-P** [halo-dev/halo#4166]
### 你当前使用的版本

2.6

### 描述一下此特性

默认编辑器中在2.6中直接粘贴图片资源，会随机上到其中的一个存储策略，能不能做个设置项，就是我每次直接粘贴图片时上传到指定的存储策略。不知道有没有这个功能，我反正是没找到O(∩_∩)O哈哈~

### 附加信息
我测试的时候是将本地策略新建了多个，每个在不同的目录下，结果上传就是不太确定，都没有到我想到的目录下

_No response_

**Comment by ruibaby** [comment]
/triage duplicate

Duplicate of https://github.com/halo-dev/halo/issues/3258

/close
