### ISSUE TITLE
重定向规则疑似失效

### ISSUE THREAD

**Issue by mobeicanyue** [halo-dev/halo#4170]
### 是什么版本出现了此问题？

2.7.0

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker Compose

### 发生了什么？

原理： 访问 https://blog.a.site/redirect 跳转至 https://wwww.a.site/
宝塔配置如下，一直都是可以跳转的。这几天发现不行了,怀疑是更新版本导致的
![image](https://github.com/halo-dev/halo/assets/81098819/706717f5-4c71-404a-bfe9-732d921ce1e6)

**Comment by ruibaby** [comment]
没有看懂这个配置，但这似乎与 Halo 无关，Halo 没有提供这样的路由。

/kind support
