### ISSUE TITLE
希望文章渲染增加对LaTeX语法的支持

### ISSUE THREAD

**Issue by weaknessQwQ** [halo-dev/halo#4171]
### 你当前使用的版本

2.6.1

### 描述一下此特性

官方编辑器不能识别LaTeX代码，第三方markdown编辑器虽然能正常识别LaTeX代码且正确预览，但是发布后在文章浏览页仍然无法渲染。

### 附加信息

如下：
![image](https://github.com/halo-dev/halo/assets/88975453/04559ee9-29bd-4ea8-848e-52ff78eb9e88)

**Comment by ruibaby** [comment]
2.7 已经支持了对编辑器进行扩展，KaTex 的插件已经在开发中，可以关注：https://github.com/halo-sigs/plugin-katex/pull/1

/area plugin

**Comment by ruibaby** [comment]
KaTeX 插件的首个版本已经发布，可以将 Halo 升级到 2.7，然后安装此插件进行体验。

- https://github.com/halo-sigs/plugin-katex/releases/tag/v1.0.0
- https://halo.run/store/apps/app-ISCsX

/close
