### ISSUE TITLE
增加插件更新提示功能，便于快速判断那些插件需要更新。

### ISSUE THREAD

**Issue by YuJian95** [halo-dev/halo#4185]
### 你当前使用的版本

2.7

## 功能背景:

**我需要解决批量更新插件的问题。** 

最近我进行了大量的插件升级，但我发现Console端 **插件页面没有显示插件更新的提示** 。这使得我无法确定当前插件版本是否是最新的，只能逐个查看插件以确定其对应的版本。此外，商城也没有提供按插件更新时间排序的功能，这导致我无法通过日期统一判断是否需要更新特定插件。

## 功能目标:

1. 能够快速了解哪些插件有更新，并能够迅速跳转到更新说明页面查看更新内容，以便判断是否需要更新插件。
2. 如果实现第一个目标较为困难，我建议在**商城中增加按更新日期排序的功能**。

**Comment by ruibaby** [comment]
目前 Console 还没有为插件和主题提供安装和检测更新的接口，也没有继承应用市场，可以关注：https://github.com/halo-dev/halo/issues/3913

至于应用市场我们将实现筛选和排序，用于更加方便的观测应用更新。同时也有计划为应用市场或者单个应用提供 RSS 订阅的功能。

**Comment by ruibaby** [comment]
> 如果实现第一个目标较为困难，我建议在商城中增加按更新日期排序的功能。

现在已经支持：https://halo.run/store/apps?sort=latestReleaseTimestamp%2Cdesc

**Comment by ruibaby** [comment]
目前已经发布应用市场集成插件的测试版本：

GitHub：https://github.com/halo-dev/plugin-app-store
应用市场：https://halo.run/store/apps/app-VYJbF

/close
