### ISSUE TITLE
Memory leak when uploading themes and plugins

### ISSUE THREAD

**Issue by JohnNiang** [halo-dev/halo#4186]
### What is version of Halo has the issue?

2.8.0-SNAPSHOT

### What database are you using?

H2

### What is your deployment method?

Fat Jar

### Your site address.

localhost

### What happened?

When I upload zip file(802MB) while installing a theme or plugin, it uses too much memory, please see the screenshot below:

<img width="716" alt="image" src="https://github.com/halo-dev/halo/assets/16865714/928b7f4b-30e8-4151-aaf8-2291bf9956cc">

It's abnormal for Halo.

### Additional information

/kind bug
/area core
/milestone 2.8.x

**Comment by JohnNiang** [comment]
But I found that the memory wouldn't increase too much when I set up VM option `-Xmx256m`, please see the screenshot below:

![image](https://github.com/halo-dev/halo/assets/16865714/9f2556d7-88b9-4ee5-862d-65a3e864a848)

So the problem shall wait for more evidence.

**Comment by ruibaby** [comment]
没有类似反馈，所以我将关闭此 issue。

/close
