### ISSUE TITLE
[Feature] Restful API / (SPA/PWA)

### ISSUE THREAD

**Issue by NaCoLiu** [halo-dev/halo#4188]
### Describe this feature

1. 目前看起来主题接口只能用现有的架构，无法显示SPA
2. 希望能提供 Restful API 功能

**Comment by JohnNiang** [comment]
/triage duplicate

目前 Halo 提供了公开的 API，可参考：<https://github.com/halo-dev/halo/issues/3661>。但是还没有实现 Token 访问 API 的机制，具体可以跟进 Issue：<https://github.com/halo-dev/halo/issues/1309>。

**Comment by guqing** [comment]
用户端 API 目前还还没有提供文档，可以参考 https://github.com/halo-dev/halo/issues/4189#issuecomment-1627986852 使用
