### ISSUE TITLE
swagger-ui文档上面没有看到登录获取 token 的方式

### ISSUE THREAD

**Issue by gaofangye** [halo-dev/halo#4189]
### What is version of Halo has the issue?

2.7.0

### What database are you using?

H2

### What is your deployment method?

Fat Jar

### Your site address.

https://demo.halo.run/webjars/swagger-ui/index.html?urls.primaryName=All%20APIs#/v1alpha1/PersonalAccessToken

### What happened?

目前没有找到登录获取 token 的 api 文档。
我想通过 api 的形式去访问 blog 数据，烦请告知我该如何操作，谢谢

**Comment by guqing** [comment]
目前还没有提供token认证方式 暂时可以使用 basic auth 认证，参考 [Wiki Basic Auth](https://en.m.wikipedia.org/wiki/Basic_access_authentication)

**Comment by gaofangye** [comment]
> 目前还没有提供token认证方式 暂时可以使用 basic auth 认证，参考 [Wiki Basic Auth](https://en.m.wikipedia.org/wiki/Basic_access_authentication) [Swagger Basic Auth](https://swagger.io/docs/specification/authentication/basic-authentication/)

 谢谢，还有一点想问下，我想开发移动端 app，请求的 api 在哪里查看？认证方式仍然是 basic auth 吗？

**Comment by guqing** [comment]
> > 目前还没有提供token认证方式 暂时可以使用 basic auth 认证，参考 [Wiki Basic Auth](https://en.m.wikipedia.org/wiki/Basic_access_authentication) [Swagger Basic Auth](https://swagger.io/docs/specification/authentication/basic-authentication/)
> 
> 谢谢，还有一点想问下，我想开发移动端 app，请求的 api 在哪里查看？认证方式仍然是 basic auth 吗？

想写的是用户端还是管理端 app？

**Comment by gaofangye** [comment]
> > > 目前还没有提供token认证方式 暂时可以使用 basic auth 认证，参考 [Wiki Basic Auth](https://en.m.wikipedia.org/wiki/Basic_access_authentication) [Swagger Basic Auth](https://swagger.io/docs/specification/authentication/basic-authentication/)
> 
> > 
> 
> > 谢谢，还有一点想问下，我想开发移动端 app，请求的 api 在哪里查看？认证方式仍然是 basic auth 吗？
> 
> 
> 
> 想写的是用户端还是管理端 app？

暂时先写用户端

**Comment by guqing** [comment]
用户端的 API 目前不需要鉴权，看 swagger-ui 上 group 为 api.halo.run 的 APIs，这个 group 是为用户端提供的，其他需要鉴权的都是管理端使用的 APIs
<img width="671" alt="image" src="https://github.com/halo-dev/halo/assets/38999863/253aff15-ceaa-44d3-a39d-9b1a5355dac9">

**Comment by gaofangye** [comment]
> Hi @gaofangye, 用户端的 API 目前不需要鉴权，看 swagger-ui 上 group 为 `api` 开头的但不以`api.console` 开头的 APIs， 其他需要鉴权的都是管理端使用的 APIs，目前还没有完善文档所以比较难找，先将就看看我们会尽快提供文档 <img alt="image" width="691" src="https://user-images.githubusercontent.com/38999863/252198800-4718edce-ee72-4273-9bf8-32e42589dab5.png"> <img alt="image" width="748" src="https://user-images.githubusercontent.com/38999863/252199436-9f41b50e-2bcb-403f-88d2-d14ba8d020d8.png">

好勒，非常感谢
