### ISSUE TITLE
关于在默认编辑器中粘贴图片

### ISSUE THREAD

**Issue by AccAutomaton** [halo-dev/halo#4191]
### 你当前使用的版本

2.7.0

### 描述一下此特性

编辑器直接粘贴剪切板内的文件时，自动上传至本地/对象存储中的文件名似乎只能默认与原始文件名保持一致。希望增加一个开关，可以选择自动重命名上传的文件（如生成UUID等），使资源uri整齐美观同时避免名称冲突带来的困扰。

### 附加信息

e.g.
![image](https://github.com/halo-dev/halo/assets/88975453/a8eaea00-9541-4f6b-b2a1-3fdd5535b05b)

**Comment by ruibaby** [comment]
我不认为这是一个好的方式，文件名最好还是保留一定的可读性和可识别性。

不过看社区的反馈吧，此外，这个似乎可以单独在插件中实现。

/kind improvement
/priority awaiting-more-evidence

**Comment by AccAutomaton** [comment]
halo-sigs/plugin-s3#60

**Comment by ruibaby** [comment]
已经在 https://github.com/halo-dev/plugin-s3/pull/60 中实现。

/close
