### ISSUE TITLE
缓存问题总是导致页面显示的不是最新内容

### ISSUE THREAD

**Issue by shy-share** [halo-dev/halo#4200]
### 是什么版本出现了此问题？

2.7.0

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker Compose

### 在线站点地址

https://shyblog.world

### 发生了什么？

清楚了浏览器缓存，点击了仪表盘的 刷新页面缓存，页面显示的还不是最新的，主题也点击了重载配置，保存，用的是openresty，ng是没有缓存的，但是不知道为啥我这里显示的总是不是最新的内容.
页面显示的瞬间
![image](https://github.com/halo-dev/halo/assets/50973219/118fa00e-dc8b-45a7-bbbb-c5bcc28cef7e)
后台的瞬间：
![image](https://github.com/halo-dev/halo/assets/50973219/c327e524-091a-4763-a18d-ed21b90cffae)

**Comment by guqing** [comment]
开启了页面缓存之后访问过的页面会产生缓存有效期是一小时，所以页面的数据会在一小时后变为最新，如果你需要实时生效可以关闭页面缓存，否则页面缓存的功能就是设计为”不要求实时性时缓存页面提高页面的访问速度”。

**Comment by shy-share** [comment]
@guqing 我已经禁用缓存了，那个不是图片，就是瞬间的展示而已，页面展示的和console端的没有同步，显示的不是最新的

**Comment by guqing** [comment]
你可以尝试在服务器通过 ip 地址访问看看是否有最新的数据排除其他缓存的干扰，因为目前 halo 除了页面缓存没有做其他的缓存

**Comment by shy-share** [comment]
> 你可以尝试在服务器通过 ip 地址访问看看是否有最新的数据排除其他缓存的干扰，因为目前 halo 除了页面缓存没有做其他的缓存

好的，我的cdn问题，缓存了所有文件
