### ISSUE TITLE
存在的密码验证安全问题

### ISSUE THREAD

**Issue by mirai-MIC** [halo-dev/halo#4203]
### 是什么版本出现了此问题？

2.7.0

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

在程序中存在一个严重的漏洞，即在登录时没有进行任何验证。此外，注册时密码的位数也没有限制，甚至可以为空或全为空。我认为这个漏洞具有重大的安全风险。

建议修复该漏洞，加入适当的登录验证措施，以确保只有经过授权的用户才能访问系统。登录验证可以包括用户名和密码的比对，以及使用其他身份验证方法（如双因素认证）来增加安全性。

同时，在用户注册过程中，应该设置一个最小密码位数的要求，以确保密码具有足够的复杂性和安全性。密码应该包含至少一定长度的字符，并且最好包含字母、数字和特殊字符等不同类型的字符。同时，应该对密码中的空串或全为空串进行限制，防止用户使用弱密码。

**Comment by ruibaby** [comment]
我将先在 Console 添加密码的校验规则。

/assign
