### ISSUE TITLE
对于私有文章，建议是只允许作者查看，而不是直接显示404！

### ISSUE THREAD

**Issue by xiuyuanjun** [halo-dev/halo#4204]
### 你当前使用的版本

2.7.0

### 描述一下此特性

当我想查看私有文章的时候，发现只能在编辑页面查看，无法在正常的页面查看。如果从console页面点击查看则直接显示404。我认为这样是不合理的。私有文章应该是只有作者有权限查看，而不是说不允许所有人查看，只能在编辑页面编辑。
![1689131514821](https://github.com/halo-dev/halo/assets/24690740/d9ecfead-8c26-4b2e-8407-3320f94f6148)
![1689131486272](https://github.com/halo-dev/halo/assets/24690740/16e71e55-af47-43be-98cb-a076e3f461ea)

**Comment by ClayGminx** [comment]
同意，建议用像 Apache Shiro 这样的库做权限控制。

**Comment by guqing** [comment]
duplicate #4204

**Comment by JohnNiang** [comment]
Close in favor of <https://github.com/halo-dev/halo/issues/4204>.

/close
/milestone clear
