### ISSUE TITLE
插入视频可否添加一个插入bilibili的视频

### ISSUE THREAD

**Issue by dadongsj** [halo-dev/halo#4205]
### 你当前使用的版本

halo2

### 描述一下此特性

文章插入视频可否添加一个插入bilibili的视频，就是直接显示b站上面的视频内容

**Comment by ruibaby** [comment]
在哔哩哔哩复制嵌入代码，然后直接粘贴到默认编辑器即可。

<img width="663" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/31f7d18e-f791-49ad-a385-c6bc9812fddb">

/kind support
