### ISSUE TITLE
希望支持LDAP登录，作为公司内部使用

### ISSUE THREAD

**Issue by JonSmall** [halo-dev/halo#4207]
### 你当前使用的版本

2.x

### 描述一下此特性

希望支持LDAP登陆，作为公司内部使用

**Comment by JohnNiang** [comment]
/assign

我将提供用户名密码认证的扩展，以帮助插件实现 LDAP 登录功能。

**Comment by ruibaby** [comment]
目前在应用市场已经有 [LDAP](https://www.halo.run/store/apps/app-vrSqF) 相关插件，此特性可能不会考虑在 Core 中实现，所以我将关闭此 issue。

/close
