### ISSUE TITLE
附件管理中 jar 类型文件的图标无法显示

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#4211]
### 是什么版本出现了此问题？

 2.7.0

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker Compose

### 在线站点地址

https://halo.run

### 发生了什么？

如图：

<img width="381" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/6d7ec86a-2610-437e-84b6-17169826f63f">

期望是：

<img width="458" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/2b2dc580-2221-4dc9-85b5-d910c248b7a8">

这个问题仅出现在构建后，dev server 并没有发现这个问题，并且目前观察到只有这个图标会无法显示。

/area console
/kind bug

**Comment by longjuan** [comment]
似乎没问题了
![image](https://github.com/halo-dev/halo/assets/28662535/22f51134-61e7-42f6-b0a9-5acf9f671579)

**Comment by ruibaby** [comment]
> 似乎没问题了 ![image](https://private-user-images.githubusercontent.com/28662535/286259241-22f51134-61e7-42f6-b0a9-5acf9f671579.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNzk1NzgsIm5iZiI6MTcwMTE3OTI3OCwicGF0aCI6Ii8yODY2MjUzNS8yODYyNTkyNDEtMjJmNTExMzQtNjFlNy00MmY2LWIwYTktNWFjZjlmNjcxNTc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDEzNDc1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5MGE4MWQ4ZjljMzc3MWM4ZGRkMWFmN2FjNzk0M2NkNjI1NWY4MWU3NTdmZmU2MTdmYjAzMDRiZDU0M2M1ZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0S4J59j2aTrm8Wk0lf2igp-xGdMVoFkVudCTHy7qMLM)

好像是诶，不过最近好像也没升级相关依赖啥的...，先 Close 了。

/close
