### ISSUE TITLE
编辑器增加快捷按键，提升写作沉浸感

### ISSUE THREAD

**Issue by zhuwenbo111** [halo-dev/halo#4218]
### 你当前使用的版本

halo2.7.0

### 描述一下此特性

如下面图片所示，希望可以在编辑器中增加指令快捷按键，比如我输入/会自动跳出相关指令，然后我选择即可。
![微信截图_20230715082644](https://github.com/halo-dev/halo/assets/102512051/d4ecb430-9359-410e-aa40-ab01366b07f2)
或者输入/代码，可以自动调出代码框，如下图。
![微信截图_20230715082704](https://github.com/halo-dev/halo/assets/102512051/9ea09e44-932c-4775-bcc8-e7b7b670fda0)

**Comment by ruibaby** [comment]
现在就是支持的，所以是使用上出现了什么问题吗？

<img width="562" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/4506a79a-7847-4b60-9f4b-3b62cfac583e">

**Comment by ruibaby** [comment]
> 谢谢大佬，尝试了一下可以使用 /尴尬

OK，那我关闭了。

/kind support
/close
