### ISSUE TITLE
编辑器嵌入网页功能需要支持主动刷新

### ISSUE THREAD

**Issue by yuanzhixiang** [halo-dev/halo#4227]
### 你当前使用的版本

2.7.0

### 描述一下此特性

目前编辑器在嵌入网页后如果想看嵌入的网页刷新的结果需要对整个页面进行刷新，很不方便，建议增加主动刷新嵌入网页按钮

**Comment by ruibaby** [comment]
Fixed in https://github.com/halo-dev/halo/pull/4288

**Comment by yuanzhixiang** [comment]
> Fixed in #4288

老哥，2.7.1 什么时候发布？

**Comment by ruibaby** [comment]
> > Fixed in #4288
> 
> 
> 
> 老哥，2.7.1 什么时候发布？

已经发布在了 https://github.com/halo-dev/halo/releases/tag/v2.8.0-rc.1

2.7.1 属于 patch 版本，应该不会包含。
