### ISSUE TITLE
希望支持 webhooks 类似的插件

### ISSUE THREAD

**Issue by AeroWang** [halo-dev/halo#4229]
### 你当前使用的版本

2.7.0

### 描述一下此特性

允许在特定事件发生时通知外部服务。当指定事件发生时，向提供的每个URL发送GET或POST请求。

事件举例：

- 发布事件（不局限于文章）
- 保存为草稿事件
- ...

如果只从前端（主动触发）考虑，可以给各类触发事件的按钮上添加唯一 `Id` （或许也可以不添加），在事件触发时同时触发指定 webhook。

被动触发的可能就是类似 github 的接收分支推送时，触发指定的 webhook

### 附加信息

可能描述不是很准确，还有可能也不完善🤣

**Comment by AeroWang** [comment]
🤣好吧，先这样，先放这里

**Comment by guqing** [comment]
目前应该可以通过插件实现 webhook 功能，可以通过 Reconciler 监听到自定义模型的修改如文章，然后触发 webhook，如果你感兴趣的话可以试试，在实现过程中遇到插件无法满足的地方再提 issue ，目前暂时无法由官方提供除非十分必要否则只能靠社区贡献了

**Comment by wxyShine** [comment]
> 🤣好吧，先这样，先放这里


https://github.com/wxyShine/halo-plugin-webhook

**Comment by AeroWang** [comment]
> https://github.com/wxyShine/halo-plugin-webhook

牛哇

**Comment by ruibaby** [comment]
> > 🤣好吧，先这样，先放这里
> 
> [wxyShine/halo-plugin-webhook](https://github.com/wxyShine/halo-plugin-webhook)

社区已经有实现了，就先关闭此 issue 了。

/close
