### ISSUE TITLE
编辑器中的提示框建议四边等宽

### ISSUE THREAD

**Issue by yuanzhixiang** [halo-dev/halo#4231]
### 你当前使用的版本

2.7.0

### 描述一下此特性

编辑器中的提示框建议四边等宽，现在的黑边看着有点难受

![image](https://github.com/halo-dev/halo/assets/25138766/855894a5-5704-45a5-a525-d6023a03d54f)

**Comment by ruibaby** [comment]
看起来是被 plugin-bytemd 的样式影响了，更新 plugin-bytemd 至最新版本即可。

https://github.com/halo-sigs/plugin-bytemd/releases/tag/v1.2.0

/kind support

**Comment by yuanzhixiang** [comment]
升级后就修复了，美观多了
