### ISSUE TITLE
评论时间错乱问题

### ISSUE THREAD

**Issue by TtBJSH** [halo-dev/halo#4237]
### 是什么版本出现了此问题？

2.7

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 在线站点地址

http://tone.band:9523/

### 发生了什么？

文章评论后 ，后台审核评论 看到评论时间不正确日期和时间都不对，刚才看日至二时间也是错的 因为我是7/15晚上部署的 但是日志有显示7/15中午的时间
![image](https://github.com/halo-dev/halo/assets/46512682/dbe02b31-9b1f-4ff1-a20d-982cebf38d5b)

**Comment by JohnNiang** [comment]
Halo server 默认使用 `Asia/Shanghai` 时区。如果需要调整时区，可尝试在运行 Halo container 处添加环境变量：`TZ`。

> https://github.com/halo-dev/halo/blob/b1a6fe3446cec86c8041a592454352e4f29ce42a/Dockerfile#L20C1-L20C1

**Comment by ruibaby** [comment]
此 issue 已经没有后续动态，我将关闭此 issue。

/close
