### ISSUE TITLE
多个用户登录之后，个人信息都是数据库第一条的信息

### ISSUE THREAD

**Issue by 1614196964** [halo-dev/halo#4243]
### What is version of Halo has the issue?

1.5.3及以前

### What database are you using?

H2

### What is your deployment method?

Fat Jar

### What happened?

使用IDEA部署起来之后，首先创建一个demo用户，再创建一个user用户。
用user用户登录之后，查看个人信息也是demo用户的
![](https://gitee.com/AWallFlower/picture/raw/master/img/20230717143618.png)
![](https://gitee.com/AWallFlower/picture/raw/master/img/20230717143700.png)
最后经过我们的排查，原因是在UserServiceImpl的getCurrentUser方法，每次都返回数据库第一条
![](https://gitee.com/AWallFlower/picture/raw/master/img/20230717143928.png)

**Comment by guqing** [comment]
1.x 版本并不支持多用户，只支持单个超管用户，如果需要多用户可以使用 2.x 版本

**Comment by 1614196964** [comment]
好的，感谢您
