### ISSUE TITLE
docker部署无法进行端口映射

### ISSUE THREAD

**Issue by hsowan-me** [halo-dev/halo#425]
![image](https://user-images.githubusercontent.com/55872984/70698221-fa50e600-1d01-11ea-9bdd-80929eceb623.png)

![image](https://user-images.githubusercontent.com/55872984/70698187-ead19d00-1d01-11ea-84fb-e5f21a5114dd.png)

![image](https://user-images.githubusercontent.com/55872984/70698256-0a68c580-1d02-11ea-90c5-9813b0d32e7b.png)

容器内服务启动在 http://172.31.0.3:8090，这是容器的内网ip，而不是localhost，这样不是无法做端口映射吗？

最终导致容器外无法正常访问

**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

**Comment by ruibaby** [comment]
别管那个 ip 了，按照文档来，https://halo.run/guide/install/install-with-docker.html

**Comment by ruibaby** [comment]
这个误导性的日志已经修改了。

**Comment by hsowan-me** [comment]
被修改了？但是这个日志还在呀，是镜像还没更新吗 @ruibaby

**Comment by ruibaby** [comment]
下个版本。你所看到的这个 ip 和能不能访问关系不大，你检查下其他地方。

**Comment by hsowan-me** [comment]
了解
