### ISSUE TITLE
docker 部署，使用mysql数据库，启动报错，无限重启

### ISSUE THREAD

**Issue by Meng-de-Cao** [halo-dev/halo#4254]
### What is version of Halo has the issue?

centos7

### What database are you using?

MySQL 8.x

### What is your deployment method?

Docker

### What happened?

```
create table if not exists extensions
(
    name    varchar(255) not null,
    data    longblob,
    version bigint,
    primary key (name)
);
```
使用这个脚本创建了数据库
![image](https://github.com/halo-dev/halo/assets/56462540/be3f0f74-99a9-42fb-93fe-83a75a126dff)

**Comment by JohnNiang** [comment]
建议提供完整的错误日志。尽可能粘贴文本。

/triage needs-information

**Comment by Meng-de-Cao** [comment]
感谢关注，问题已经解决，是我的创建docker容器时缺少了参数
