### ISSUE TITLE
评论无法关闭，新建页面 选择“不允许评论”，但是评论还是显示，并且可以评论

### ISSUE THREAD

**Issue by Wing-Li** [halo-dev/halo#4259]
### 是什么版本出现了此问题？

使用提供的demo

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 在线站点地址

https://demo.halo.run/home

### 发生了什么？

评论无法关闭。

新建页面 选择“不允许评论”，但是评论还是显示，并且可以评论；

还有，在设置页面，关闭评论也是没有作用。F12查看，就没有发起网络请求，是没有这个功能吗？

**Comment by ruibaby** [comment]
目前需要主题进行适配，由于目前判断条件可能过多且不方便，很多主题可能会忽略掉这个适配。详情可见：https://github.com/halo-dev/halo/issues/4137

/kind support

**Comment by Wing-Li** [comment]
![](https://github.com/halo-dev/halo/assets/12133489/8e412a69-61e8-4de7-9e80-22a5947d1714)

Hao 主题，可以选择这样的方式关闭评论。
