### ISSUE TITLE
把http修改为https时，导致css加载失败问题

### ISSUE THREAD

**Issue by byfcn** [halo-dev/halo#426]
1、安装的时候选择了http://，通过http://访问没问题。
但是如果通过https://访问，会导致css无法加载问题。
2、在后台把http修改为https，即可恢复正常

希望在后面这个版本修复这个问题。

**Comment by ruibaby** [comment]
@byfcn 本身就是这样设定的

**Comment by ruibaby** [comment]
@byfcn 建议设置 http 强制跳转到 https

**Comment by JohnNiang** [comment]
> 1、安装的时候选择了http://，通过[http://访问没问题。](http://%E8%AE%BF%E9%97%AE%E6%B2%A1%E9%97%AE%E9%A2%98%E3%80%82)
> 但是如果通过[https://访问，会导致css无法加载问题。](https://%E8%AE%BF%E9%97%AE%EF%BC%8C%E4%BC%9A%E5%AF%BC%E8%87%B4css%E6%97%A0%E6%B3%95%E5%8A%A0%E8%BD%BD%E9%97%AE%E9%A2%98%E3%80%82)
> 2、在后台把http修改为https，即可恢复正常
> 
> 希望在后面这个版本修复这个问题。

halo 博客对 https 是无感知的

**Comment by byfcn** [comment]
在css路径前面不在增加http或者https
直接//:css文件
以前我的碰到的解决问题就算这样做的。做到自动，不需要手动配置。

**Comment by ruibaby** [comment]
@byfcn 那你在博客设置中把博客地址改为 / 或者 //:域名 好了。

**Comment by byfcn** [comment]
行，修改了，没问题

**Comment by ruibaby** [comment]
@byfcn 但是不是很建议哦。还是建议http强制跳转到https。这是常规操作。

**Comment by hekaimsbl** [comment]
![image](https://user-images.githubusercontent.com/43072224/76695950-43795300-66c0-11ea-98a5-0000b87fde7b.png)
后台页面是好的,主页的css 404

**Comment by ruibaby** [comment]
@hekaimsbl https://halo.run/archives/other-faq#q7-安装完成之后前台页面无样式
