### ISSUE TITLE
导航设置为当前页面打开，但是还是新窗口打开的，设置无效

### ISSUE THREAD

**Issue by hlovingness** [halo-dev/halo#4261]
### 是什么版本出现了此问题？

2.7.0

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker

### 发生了什么？

导航设置为当前页面打开，但是还是新窗口打开的，设置无效，上一个版本都正常，升级到最新就不行了

**Comment by ruibaby** [comment]
是否有开启静态页面缓存？

/kind support

**Comment by hlovingness** [comment]
> 是否有开启静态页面缓存？
> 
> /kind support

没开，不过好像又好了，好像是跟主题有关
