### ISSUE TITLE
用户信息更改失败

### ISSUE THREAD

**Issue by ThomasXU-17** [halo-dev/halo#4269]
### 是什么版本出现了此问题？

2.7

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式部署？

Docker Compose

### 发生了什么？

当我希望修改用户资料时，提示错误“抱歉，部分字段未被正确填写。”用户名红色，提示“请输入有效的用户名”。但是，用户名为灰色不可更改，我认为是我的用户名在早期版本时设定的，但是更新到2.7后非法且不可更改了。这个bug是否跟大小写有关？我的用户名为“XuanyangXu”，是否在新版本中非法？我尝试了admin用户，该用户用户名为“admin”，用户资料可以被更改。

**Comment by ruibaby** [comment]
这可能是因为后面的版本中添加了用户名规则校验。

有什么办法解决这种情况吗？

cc @halo-dev/sig-halo 

/kind support

**Comment by ruibaby** [comment]
> 更新的时候忽略掉用户名的校验，毕竟更新是不允许修改用户名的

好主意，你可真是个小天才

/assign
