### ISSUE TITLE
后台用户的功能异常/失效

### ISSUE THREAD

**Issue by rise2629** [halo-dev/halo#4278]
### What is version of Halo has the issue?

奇怪

### What database are you using?

MySQL 5.7

### What is your deployment method?

Docker

### What happened?

![Snipaste_2023-07-21_21-36-46](https://github.com/halo-dev/halo/assets/140096248/7f52490b-89b8-402f-bb42-ed90d4d5e6c9)
本来很多选项的，突然就剩这几个选项了。
求告知！

**Comment by JohnNiang** [comment]
可以描述一下选项消失之前进行了什么操作么？

从图中提供的信息来看，似乎是当前用户的 UI 权限出现了问题。

/triage needs-information

**Comment by rise2629** [comment]
更换了端口，原来是挂在80端口，后来安装其他提示被占用，然后将halo改成2333端口，重新登录就变成这样了。

**Comment by ruibaby** [comment]
应该和 https://github.com/halo-dev/halo/issues/4372 有关，你的用户名在登录的时候没有区分大小写导致权限获取错误，建议使用正确的用户名试试。

**Comment by JohnNiang** [comment]
/triage duplicate
/remove-triage needs-information

Close in favor of <https://github.com/halo-dev/halo/issues/4372>.

/close
