### ISSUE TITLE
（偶现）某些情况下编辑文章时修改弹窗的保存按钮无效

### ISSUE THREAD

**Issue by WaterSunMount** [halo-dev/halo#4279]
### 是什么版本出现了此问题？

2.7.0

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式部署？

Docker Compose

### 发生了什么？

文章发布之后，点击`修改`，无论任何修改之后，`保存`按钮点击无效，F12看到点击该按钮也没有调用后台接口，但是`取消`之后再次点击`设置`按钮旁边的`保存`按钮与后台是有数据传输的；服务器是香港服务器，也有可能是这个原因引起的，所以不知道是不是某些接口未及时响应，导致确定按钮事件还未绑定，点击设置之后，确定按钮就点击无效了

**Comment by ruibaby** [comment]
出现这种情况的时候，表单的数据有正常显示吗？目前我这边没有复现成功。

/triage needs-information

**Comment by WaterSunMount** [comment]
> 

没有太明白你的意思，你是指点击修改按钮之后的弹窗内容吗？弹窗内容都是正常的，也可以正常修改内容，问题就是修改完成之后，修改弹窗的保存按钮，点击没有任何反应，也不会发送请求调用后端接口的

**Comment by WaterSunMount** [comment]
![22-19-28 (2)](https://github.com/halo-dev/halo/assets/75781948/ae49770c-97bc-42c1-ab83-198cb51bb29f)

**Comment by JohnNiang** [comment]
建议滑动一下“文章设置”表单，看是否有表单验证错误。

**Comment by guqing** [comment]
应该是 annotatioin 要求字段必填，但 annotation 是可以为空的，所以导致有存在 annotation 值为空的就无法提交的情况
