### ISSUE TITLE
关于	初始超级管理员

### ISSUE THREAD

**Issue by wangxiaoerYah** [halo-dev/halo#4280]
### 你当前使用的版本

2.1

### 描述一下此特性

根据使用文档,在第一次运行时会默认创建一个初始管理员.在这之后其实可以去掉:
```
--halo.security.initializer.superadminusername=admin \
  --halo.security.initializer.superadminpassword=P@88w0rd 
```
依然是正常运行的.
也许这样比较繁琐,可不可以直接内置这段代码到程序内部?
如果是第一次安装,那么程序默认创建一个超级用户,用户名:halo,密码:halo.
用户在后台界面自行修改即可.

**Comment by ruibaby** [comment]
计划是在首次初始化的时候设置初始管理员账户，通过参数指定后面只会变成一种选项。

详情可看：https://github.com/halo-dev/halo/issues/3230

/kind improvement

**Comment by JohnNiang** [comment]
Close in favor of <https://github.com/halo-dev/halo/issues/3230>.

/close
