### ISSUE TITLE
刷新页面静态缓存，缓存似乎失效了

### ISSUE THREAD

**Issue by heyzqq** [halo-dev/halo#4281]
### 是什么版本出现了此问题？

2.7.0

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker Compose

### 在线站点地址

https://springx.fun

### 发生了什么？

启用静态页面缓存之后（`--halo.cache.page.disabled=false`），可以明显看到缓存效果，但是刷新缓存之后，效果不见了。

![image](https://github.com/halo-dev/halo/assets/47818994/c4cb12c5-c985-43b1-b046-933222b36e97)

- 服务启动后，除了第一次加载页面，后面几次时间降到几十毫秒
- 去 Console 刷新页面缓存后，页面刷新时间上升到 200 毫秒（差不都是未开启缓存的水平）
- 重启服务后，缓存效果又有了

**Comment by JohnNiang** [comment]
需要注意的是，如果你是已登录状态，默认是不会走缓存的。

请参考：<https://docs.halo.run/getting-started/install/docker-compose#:~:text=%E5%BC%80%E5%90%AF%E7%BC%93%E5%AD%98%E4%B9%8B%E5%90%8E%EF%BC%8C%E5%9C%A8%E7%99%BB%E5%BD%95%E7%9A%84%E6%83%85%E5%86%B5%E4%B8%8B%E4%B8%8D%E4%BC%9A%E7%BB%8F%E8%BF%87%E7%BC%93%E5%AD%98>。

**Comment by heyzqq** [comment]
噢~明白了😄。

我启动服务后，是未登录状态，所以正常缓存。

去刷新缓存的时候，需要登陆，所以后续不使用缓存了。

重启服务器后，又是未登录状态，所以又恢复缓存了。

感谢~
