### ISSUE TITLE
附件功能：删除附件后，如果再次上传同名附件，那么还是调用的被删除图片

### ISSUE THREAD

**Issue by meilocon** [halo-dev/halo#4283]
### 是什么版本出现了此问题？

2.7

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式部署？

Docker Compose

### 在线站点地址

http://111.229.37.169:8090/

### 发生了什么？

采用本地存储上传附件
删除附件后，如果再次上传同名附件，那么还是调用的被删除图片
如果改变附件名字或者改变存储策略，那么可以正常上传并调用显示

### 附加信息

![1](https://github.com/halo-dev/halo/assets/65286070/cd89b2f1-ffb3-4f4d-a0e8-7370f36335d9)
![2](https://github.com/halo-dev/halo/assets/65286070/0d5e3d6c-c296-456a-925b-44dab9baa10a)
![3](https://github.com/halo-dev/halo/assets/65286070/63cdb2f6-f901-4844-b1bd-91982303de51)
![4](https://github.com/halo-dev/halo/assets/65286070/f1cb4a40-3815-4a3d-9cc6-dc94d325de23)

**Comment by ruibaby** [comment]
需要先排除一下是否是浏览器缓存或者 Nginx 缓存，建议尝试一下完全通过 ip 的方式访问，观察前后是否有更新。

/kind support
/triage needs-information

**Comment by meilocon** [comment]
看样子是由于缓存的问题导致没有实时刷新，感谢！

**Comment by JohnNiang** [comment]
默认情况下，Halo 的附件会让浏览器缓存 365 天。所以直接更改附件内容，访客可能无法及时得到最新的附件内容，除非主动在浏览器中刷新缓存。
