### ISSUE TITLE
附件重命名

### ISSUE THREAD

**Issue by winsway** [halo-dev/halo#4294]
### 你当前使用的版本

2.7

### 描述一下此特性

我手机里的一些照片上传到了附件中，并引用了链接。在时间仓促的情况下很难花时间对附件进行命名。空闲了管理文件时想可以再次命名，并且可以在命名后更新后台配置的链接名称。目前还么有文件重命名的功能。

**Comment by JohnNiang** [comment]
如果只是单纯修改附件的名称，支持起来是比较简单的，但是如果涉及到修改附件的访问链接就比较复杂了。

/triage needs-information

<img width="924" alt="image" src="https://github.com/halo-dev/halo/assets/16865714/254ace75-5ac5-4776-a3ba-a300c0593308">

**Comment by winsway** [comment]
这确实是个难题

**Comment by HowieHz** [comment]
可以和 #5120 结合一下，管理主要还是注重display name，相较之下引用路径显得没那么重要

**Comment by ruibaby** [comment]
我将在界面上实现修改显示名称的功能，修改物理文件名称应该不是当前的目标。
