### ISSUE TITLE
配置文件无法下载

### ISSUE THREAD

**Issue by shenzhou-6** [halo-dev/halo#430]
http://halo.ryanc.cc/config/application-template.yaml

**Comment by JohnNiang** [comment]
> http://halo.ryanc.cc/config/application-template.yaml

稍后会进行处理。

不过这个配置文件不是必须的，你可以不需要任何配置文件启动 Halo。

**Comment by ruibaby** [comment]
@shenzhou-6 再试试

**Comment by shenzhou-6** [comment]
@ruibaby  可以了谢谢
