### ISSUE TITLE
静态资源名称与未发布的文章/页面别名相同时访问返回 404

### ISSUE THREAD

**Issue by wan92hen** [halo-dev/halo#4309]
### 是什么版本出现了此问题？

v2.8.0-rc.1

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式部署？

Docker Compose

### 发生了什么？

问题描述：
1. 在静态资源目录创建 `test.html` 文件，访问 `/test.html` 地址，可以正常显示文件内容；
2. 在控制台创建并发布页面，别名也配置为 `test.html`；
3. 再次访问 `/test.html` 地址，页面内容变为上一步创建的页面；
4. 取消发布步骤 3 中创建的页面，再次访问 `/test.html` 地址，返回 404 页面。

取消发布页面后，访问 `/test.html` 地址应该可以返回静态资源目录 `test.html` 的内容。

**Comment by JohnNiang** [comment]
目前仅页面的路由好处理一些。文章，标签，分类等路由是通过规则（例如 `/archives/**`）匹配的，无法在路由匹配阶段过滤掉未发布的文章。
