### ISSUE TITLE
新建文章始终有缓存内容

### ISSUE THREAD

**Issue by yuanzhixiang** [halo-dev/halo#4310]
### 是什么版本出现了此问题？

2.8.0-rc.1

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker

### 发生了什么？

编辑文章后前端保存了缓存内容，在新建文章始终会使用缓存的内容

**Comment by ruibaby** [comment]
可以提供一下复现步骤吗？

目前在浏览器缓存的策略是：

1. 新建文章没有保存到服务器的时候，缓存不会自动清理。
2. 编辑已有文章时，只有保存或者发布的时候才会清理对应缓存。

**Comment by yuanzhixiang** [comment]
> 可以提供一下复现步骤吗？
> 
> 目前在浏览器缓存的策略是：
> 
> 1. 新建文章没有保存到服务器的时候，缓存不会自动清理。
> 2. 编辑已有文章时，只有保存或者发布的时候才会清理对应缓存。

复现步骤：
1. 无痕模式登录
2. New 文章，输入 hello
3. 点击 save，点击 publish
4. 再次 New 文章，会看到 content 里面依然有内容

**Comment by ruibaby** [comment]
@yuanzhixiang 确实容易复现，感谢反馈。

/kind bug
/remove-triage needs-information
/area console
/milestone 2.8.x

**Comment by JohnNiang** [comment]
> 复现步骤：
> 
> 1. 无痕模式登录
> 2. New 文章，输入 hello
> 3. 点击 save，点击 publish
> 4. 再次 New 文章，会看到 content 里面依然有内容

按照这个复现步骤，确认可复现。

/remove-triage needs-information
/kind bug
/area console
