### ISSUE TITLE
文章编辑建议添加内容恢复到上次发布内容的功能

### ISSUE THREAD

**Issue by cetr** [halo-dev/halo#4319]
### 你当前使用的版本

2.7.0

### 描述一下此特性

因为现在文章编辑有自动保存内容的功能，只要有更改就会保存为未发布，然后再次打开文章编辑又会自动加载未发布的内容

这就导致当文章被误修改后，再次打开编辑器将永远展示错误的文章内容

建议添加一个可以恢复上次已发布文章内容的功能或用其他更好的方式避免这个问题

**Comment by ruibaby** [comment]
我建议提供一个丢弃当前更改的功能。

/kind improvement
/area console
/area core
/milestone 2.9.x

**Comment by LIlGG** [comment]
PR #4458 新增了新编辑内容自动保存的功能，此功能会使文章内容在正常情况下自动保存至后端，但与之而来的问题便是用户修改文章内容之后无法还原为上一次发布时的内容（因为目前无法得知上一次发布时的内容是什么）。因此可能需要一个文章版本管理的功能，用于支持用户回退到某个本地/远端版本。
