### ISSUE TITLE
当文章路径包含中文时，预览功能无法正常使用以及关于路径的建议

### ISSUE THREAD

**Issue by Yuukion** [halo-dev/halo#432]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [x] 添加新的特性或者功能
- [ ] 请求技术支持

- bug反馈 
当文章路径包含中文时，预览功能无法正常使用
举例：文章标题为svn项目迁移git，路径同标题，使用预览功能

![image](https://user-images.githubusercontent.com/33031194/71175211-fbee5100-22a1-11ea-85e9-83779fc8ac9c.png)

原因，中文在路径中变成了???，当更改为中文时可正常访问

![image](https://user-images.githubusercontent.com/33031194/71175301-30620d00-22a2-11ea-9a7f-8163b6cb061c.png)

- 关于文章路径的建议，现在我使用chrome插件的方式生成UUID作为文章路径，总觉得此方式不便，希望能加入文章缺省路径，或指定路径生产方式，例如：
 1. uuid
 2. 时间戳

**Comment by ruibaby** [comment]
这个问题已经在刚刚被修复了。https://github.com/halo-dev/halo/commit/f5d957edc160a43ab6c3becc6352b26fe9557c53

**Comment by ruibaby** [comment]
请等待 `1.2.0` 版本。
