### ISSUE TITLE
附件

### ISSUE THREAD

**Issue by cetr** [halo-dev/halo#4326]
### 是什么版本出现了此问题？

2.7.0

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式部署？

Docker Compose

### 发生了什么？

![image](https://github.com/halo-dev/halo/assets/49756728/a0a50c5f-657f-4c29-aa2d-08532e21ea03)

如图所示，附件“最后一张”图片点击下一个后，会返回空值，https://demo.halo.run 里也可测试出来

**Comment by Erzbir** [comment]
我的也出现了

**Comment by Erzbir** [comment]
最后一张图再翻页会出现:
<img width="1160" alt="截屏2023-07-29 14 14 14" src="https://github.com/halo-dev/halo/assets/100007608/41f506f9-e34f-468e-aab1-e0d0059fb8b0">


看了代码, 逻辑是 `index === data.value.length - 1 && hasNext` 为 `true` 则 `page++`

改成 `index === data.value.length - 1 && hasNext.value` 可以避免

/assign
