### ISSUE TITLE
当关闭评论插件应该隐藏和关闭评论的所有功能

### ISSUE THREAD

**Issue by cetr** [halo-dev/halo#4327]
### 是什么版本出现了此问题？

2.7.0

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式部署？

Docker Compose

### 发生了什么？

在插件列表里关闭了评论插件在后台评论管理里依然可以评论及回复，不符合逻辑

**Comment by ruibaby** [comment]
已经在 https://github.com/halo-dev/halo/pull/4271 中优化，会发布在 2.8

/triage duplicate
