### ISSUE TITLE
关于2.8rc版本的链接插件存在以下bug

### ISSUE THREAD

**Issue by Roozenlz** [halo-dev/halo#4329]
### What is version of Halo has the issue?

2.8rc

### What database are you using?

MySQL 8.x

### What is your deployment method?

Docker

### Your site address.

https://roozen.top

### What happened?

1.切换链接分组时不刷新分组数据

https://github.com/halo-dev/halo/assets/93673944/d3a634e9-e579-46ba-b291-f1df27caf6de

2.有时在一个分组下添加链接，添加完成后链接却不在任何分组，需要手动移动分组，此bug遇过几次，但是无法刻意去复现

### Relevant log output

```shell
无相关日志，已提供相关视频
```

**Comment by Roozenlz** [comment]
不知道为什么视频显示不了，但是下载可以看

**Comment by Roozenlz** [comment]
2.7就正常，所以可能是halo这边的问题，我就没提到插件那边

**Comment by ruibaby** [comment]
应该是在 https://github.com/halo-dev/halo/pull/4102 中升级了 VueUse 依赖导致的。估计 Halo 2.8 发布之后，得对应更新一下收到影响的插件。

感谢反馈。
