### ISSUE TITLE
使用仅有文章管理权限的用户登录后台能查看并使用其他权限

### ISSUE THREAD

**Issue by hunteris666** [halo-dev/halo#4332]
### 是什么版本出现了此问题？

2.7正式版

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker

### 发生了什么？

使用仅有文章管理权限的用户登录后台能查看并使用其他权限。
看了其他issue，也有人反馈这一问题，希望作者大大能重视。
这边的场景是一个学生公用的文章网，同学挺多的，都拿管理权限也不太好。

### 附加信息

![image](https://github.com/halo-dev/halo/assets/103302747/20616737-36a2-40c9-b2bd-958765de150f)
![image](https://github.com/halo-dev/halo/assets/103302747/a76d1f9b-5d69-42e9-882a-c36b0f491108)

**Comment by ruibaby** [comment]
我这边没有复现这个问题：

<img width="612" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/2d8cd357-1bb9-4e28-a3a2-e40aa3c62270">

能简单提供一下复现过程吗？

/triage needs-information

**Comment by ruibaby** [comment]
使用基于角色创建新角色这个操作复现了。

<img width="756" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/5f8fdbee-b5c6-4d58-af4a-d6ec6453284c">

应该是在创建的时候没有清空原角色的 roles 信息。

<img width="678" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/f46bc381-62f0-4cd5-858b-56442b066753">

/kind bug
/area console
/milestone 2.8.x

/assign

**Comment by hunteris666** [comment]
但我是新建的角色，新建完后设置其为这个角色。
那边刚开始是这样
![image](https://github.com/halo-dev/halo/assets/103302747/cd7ea43a-b613-4df8-a64b-7105146dcc1b)
![image.png](https://s2.loli.net/2023/07/29/13dYbKGD7uoflhp.png)
他给我反馈后我登录他的账号后发现他有全部权限，重新设置确认他的权限为仅文章管理也无法改变。
![屏幕截图 2023-07-29 211109](https://github.com/halo-dev/halo/assets/103302747/81d13d3a-4c91-4e39-9f41-1d8a974b5943)
后来他换了Chrome最新版后也有全部权限，此前用的旧版Edge Dev。

**Comment by hunteris666** [comment]
@ruibaby

**Comment by ruibaby** [comment]
新建角色的时候是通过 **基于角色创建** 创建还是常规的创建角色？

**Comment by ruibaby** [comment]
@halo-dev/sig-halo cc

**Comment by JohnNiang** [comment]
如果方便的话，建议提供一个能够复现问题的账号。我的邮箱：`johnniang#halo.run`。

**Comment by hunteris666** [comment]
好的

**Comment by hunteris666** [comment]
尝试给了出问题的账号 **超级管理员** 权限后直接无法更改用户权限了。
![image](https://github.com/halo-dev/halo/assets/103302747/55c4a847-2147-40cb-9bd1-bf3343e9ef24)
![image](https://github.com/halo-dev/halo/assets/103302747/f44d25f4-3256-4492-bbb8-a72ec8149fae)
按提交后权限不变。
此时出问题的账号显示为**超级管理员**，实际权限是**仅文章管理**
![image](https://github.com/halo-dev/halo/assets/103302747/a1314f6c-23d5-459f-ad6a-d4f508b8be91)
@JohnNiang 不好意思，这个问题好像更严重了，创建时选定角色后权限正常，只是后面无法更改权限了。还需不需要给您账号？问题目前不好复现了。
@ruibaby

**Comment by hunteris666** [comment]
> 新建角色的时候是通过 **基于角色创建** 创建还是常规的创建角色？

直接新建的

**Comment by hunteris666** [comment]
2.8好像修复了，谢谢Halo团队

**Comment by lixuejun725** [comment]
我这边2.11出现类似问题，就是只设置可以管理自己文章，却可以删除他人的文章
