### ISSUE TITLE
【友链管理】1. 多选移动友链分组会导致未选择友链全部都移动到新分组中 2. 友链编辑新增中未提供从附件选择logo、背景功能

### ISSUE THREAD

**Issue by carolcoral** [halo-dev/halo#4336]
### 是什么版本出现了此问题？

2.8-rc1

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式部署？

Docker Compose

### 在线站点地址

http://blog.cnkj.site

### 发生了什么？

* 问题1:

> 使用“友链管理”中移动功能：
1. 多选友链
2. 选择“移动”
3. 所有友链移动到新指定分组（包含未勾选的友链）

* 问题2:

> 在“友链管理”中新增、编辑友链无法从附件中选择logo及背景图案

#### 问题一附件：
移动前：

<img width="1419" alt="image" src="https://github.com/halo-dev/halo/assets/8952687/7c4c0fa9-07ff-4a2c-9906-d2b22cbb475f">

勾选移动到“服务”：

<img width="1418" alt="image" src="https://github.com/halo-dev/halo/assets/8952687/31e4fb85-dfed-4c0d-92a2-93fabbeba2e1">

完成移动后，全部被移动了：

<img width="1043" alt="image" src="https://github.com/halo-dev/halo/assets/8952687/5c328306-9fec-4366-9ef6-38c5dcb59e14">

#### 问题2附件：

截图中有该功能为 [@chengzhongxue](https://github.com/chengzhongxue)  提供的魔改插件 [plugin-links](https://github.com/chengzhongxue/plugin-links)

<img width="636" alt="image" src="https://github.com/halo-dev/halo/assets/8952687/82d07b00-5956-4e60-a94a-04111da4ba65">

**Comment by ruibaby** [comment]
/area plugin
/king bug

第一个问题可以复现，第二个问题建议向魔改的插件提供反馈。

此外，这种问题建议向具体的插件仓库提交 issue。https://github.com/halo-sigs/plugin-links
