### ISSUE TITLE
删除附件提示未知错误

### ISSUE THREAD

**Issue by Meteor-showers** [halo-dev/halo#4337]
### 是什么版本出现了此问题？

 2.7

### 使用的什么数据库？

MySQL 5.7

### 使用的哪种方式部署？

Docker

### 发生了什么？

删除图片附件的时候提示未知错误
![image](https://github.com/halo-dev/halo/assets/32284743/6a729226-712a-483f-a8ef-4daf91b16a7e)
![image](https://github.com/halo-dev/halo/assets/32284743/b103e1dd-bcb8-457b-9409-d70480c2ebcd)

### 相关日志输出

```shell
后端无日志生成
```

**Comment by JohnNiang** [comment]
正常情况下，这个接口不会返回这样的结构，即使是附件未找到。

建议提供复现步骤，以及该接口的返回内容，越详细越好。

/triage needs-information

**Comment by Meteor-showers** [comment]
https://github.com/halo-dev/halo/assets/32284743/9ef7fa37-3a98-4d98-8c16-ff1c677df71b

这是我录了个复现视频 后端没任何日志

**Comment by ruibaby** [comment]
建议检查你的前置代理（Nginx，CDN）之类的配置。看接口的返回内容，似乎都还没有经过 Halo。

**Comment by Meteor-showers** [comment]
好像是这个接口不存在 我在查查我的 看着没触达后端

**Comment by Meteor-showers** [comment]
抱歉 找到问题了 是我这边的问题 我把DELETE 这个方法禁用了🥲
