### ISSUE TITLE
空间信息处理技术研究室

### ISSUE THREAD

**Issue by ceet2016** [halo-dev/halo#434]
网站名称：空间信息处理技术研究室
地址：https://vegagis.cn

**Comment by ruibaby** [comment]
@ceet2016 提高 halo 用户整体水平🌚

**Comment by ceet2016** [comment]
> 网站名称：空间信息处理技术研究室
> 地址：https://vegagis.cn

**Comment by ruibaby** [comment]
你可以在这里评论，https://github.com/halo-dev/halo/issues/26
