### ISSUE TITLE
文件上传接口失败后，界面应当做出错误反馈。

### ISSUE THREAD

**Issue by LIlGG** [halo-dev/halo#4359]
### 是什么版本出现了此问题？

2.8.0

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker Compose

## 问题描述

当服务器限制上传文件大小时，例如使用了 `nginx` 并且请求文件大小配置不足，此时上传大文件可能会出现 413 错误。如下所示。
<img width="716" alt="image" src="https://github.com/halo-dev/halo/assets/31335418/bfd3f7d4-9c3b-49e9-8d7e-60a4cb76fadb">

但此时上传文件的界面，还仍旧处于 0% 的状态。

<img width="655" alt="image" src="https://github.com/halo-dev/halo/assets/31335418/418b7e38-e9bd-491f-ba8e-c3b7ea4be22d">

## 期望结果

当上传接口报错时，界面应该停止上传并进行提示，而不是卡在 0%。

/kind bug
/area console

**Comment by Pusooy** [comment]
我也是使用nginx没有设置client_max_body_size，使得上传的时候一直卡在100%，谢谢层主让我发现原因

**Comment by ruibaby** [comment]
> 我也是使用nginx没有设置client_max_body_size，使得上传的时候一直卡在100%，谢谢层主让我发现原因

已经在 https://github.com/halo-dev/halo/pull/4431 中优化了，后续版本会支持捕获这个异常，排查起来就方便了。
