### ISSUE TITLE
如何指定目录运行？

### ISSUE THREAD

**Issue by shenweima** [halo-dev/halo#436]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [ ] [Halo 使用文档](https://halo.run/docs)
- [ ] [Halo 论坛](https://bbs.halo.run)
- [ ] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [ ] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [X ] 请求技术支持

已经有其他web服务运行，通过访问ip就可以访问。现在博客想要通过下一级目录访问，即通过输入ip/blog来访问，该如何设置呢？

**Comment by ruibaby** [comment]
@shenweima 理论可以，但是没有做系列测试。后面我们会发布相关指南，可以等等。目前你可以通过端口进行访问。

**Comment by shenweima** [comment]
谢谢您。服务器目前只对外开放了80端口，所以只能通过80端口访问。那我就在等等吧。

**Comment by ruibaby** [comment]
@shenweima 但是你可以用其他端口啊。
