### ISSUE TITLE
镜像无法获取

### ISSUE THREAD

**Issue by xiaofengjue** [halo-dev/halo#4360]
### What is version of Halo has the issue?

无法获取镜像

### What database are you using?

H2

### What is your deployment method?

Docker

### What happened?

在发出此文之前，我也是在issue里面翻找了一番，相关链接为：
https://github.com/halo-dev/halo/issues/4142
https://github.com/halo-dev/halo/issues/4058
https://github.com/halo-dev/halo/issues/3809
我把daemon.json改为如下：
~~~
{
    "registry-mirrors": [
"https://docker.mirrors.ustc.edu.cn",
"http://hub-mirror.c.163.com",
"https://registry.docker-cn.com"
]
}
~~~
重启docker，拉取halo2.8的镜像依然无法解决问题，报错：manifest for docker.io/halohub/halo:2.8 not found
docker info信息：
~~~
ID: ENTV:3WFK:YORW:LWIX:IOYV:Q4XD:GQAP:4LTF:S4T7:64EB:6PFS:2ZHF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://docker.mirrors.ustc.edu.cn
 http://hub-mirror.c.163.com
 https://registry.docker-cn.com
Live Restore Enabled: false
Registries: docker.io (secure)
~~~
请求帮助，的确是不知道要怎么做了

**Comment by JohnNiang** [comment]
建议去掉 mirrors 配置再试试。

/triage needs-information

**Comment by xiaofengjue** [comment]
我刚刚在宝塔安装docker，daemon.json添加了同样的加速链接，然后再拉取halo2.8镜像就可以了，我猜测应该还和docker本身的版本有关，因为之前我是直接yum安装的docker，docker版本1.X，通过宝塔我直接安装的docker 3.9.1

然后现在又遇到了新的问题，我把halo 1.X的整站备份，在2.8还原时遇到报错，提示上传失败，正在看官方文档找解决方法时，访问https://halo.run/store/apps/app-TlUBt这种我需要的迁移插件好慢，网站都打不开

**Comment by xiaofengjue** [comment]
> 我刚刚在宝塔安装docker，daemon.json添加了同样的加速链接，然后再拉取halo2.8镜像就可以了，我猜测应该还和docker本身的版本有关，因为之前我是直接yum安装的docker，docker版本1.X，通过宝塔我直接安装的docker 3.9.1
> 
> 然后现在又遇到了新的问题，我把halo 1.X的整站备份，在2.8还原时遇到报错，提示上传失败，正在看官方文档找解决方法时，访问[https://halo.run/store/apps/app-TlUBt这种我需要的迁移插件好慢，网站都打不开](https://halo.run/store/apps/app-TlUBt%E8%BF%99%E7%A7%8D%E6%88%91%E9%9C%80%E8%A6%81%E7%9A%84%E8%BF%81%E7%A7%BB%E6%8F%92%E4%BB%B6%E5%A5%BD%E6%85%A2%EF%BC%8C%E7%BD%91%E7%AB%99%E9%83%BD%E6%89%93%E4%B8%8D%E5%BC%80)

按照官方迁移教程迁移了，没有问题了，昨晚是我自己的网络原因
