### ISSUE TITLE
文章录入支持黏贴markdown文本，自动适配默认编辑器

### ISSUE THREAD

**Issue by cartebrother** [halo-dev/halo#4366]
### 描述一下此特性

有通过markdown编写的文章，需要发布在holo，直接黏贴markdown文本，识别为了mardown的文本块，显示效果很差。

如果可以直接适配默认编辑器，可以方便把存量的文章快速录入到halo进行发布。

### 附加信息

很多cms支持，比如语雀。 使用体验非常好。

**Comment by ruibaby** [comment]
/triage duplicate

see https://github.com/halo-dev/halo/issues/2549

/close
