### ISSUE TITLE
AnnotationsForm 重复的 Key 校验无效

### ISSUE THREAD

**Issue by guqing** [halo-dev/halo#4367]
### Your current Halo version

2.8.0

### Describe this feature

如填写了 a 作为 key 而 value 为 a，在添加 a 作为 key ，value=c表单校验通过，建议不允许重复的 key
<img width="573" alt="image" src="https://github.com/halo-dev/halo/assets/38999863/44188531-66f6-42d2-a53a-cc743cfa8474">
但代码中是有关于重复 key 校验的
<img width="509" alt="image" src="https://github.com/halo-dev/halo/assets/38999863/4f16cee8-a30a-49a2-b94f-a7fa0680fec4">

https://github.com/halo-dev/halo/blob/6b748efeaf3cac38cb34ae817d6bf8e5ad1cfeb6/console/src/components/form/AnnotationsForm.vue#L18

### Additional information

/kind improvement
/area console

**Comment by ruibaby** [comment]
/kind bug
/area console

cc @LIlGG
