### ISSUE TITLE
修复了一个token存储的过期时间bug

### ISSUE THREAD

**Issue by liaozan** [halo-dev/halo#437]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

存储 `access_token`的时候生成的过期时间是错误的，see https://github.com/halo-dev/halo/pull/435#issue-356039616

**Comment by ruibaby** [comment]
好的，非常感谢你的贡献。
