### ISSUE TITLE
【编辑用户】中没有头像设置选项

### ISSUE THREAD

**Issue by narcissuskid** [halo-dev/halo#4373]
### 是什么版本出现了此问题？

2.8 

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker Compose

### 在线站点地址

https://pandalab.me/

### 发生了什么？

<img width="521" alt="bug_user" src="https://github.com/halo-dev/halo/assets/58718517/8c4654ac-31b1-47a1-9a8a-ceffa279e45f">
<img width="514" alt="bug_user2" src="https://github.com/halo-dev/halo/assets/58718517/1ad5f8f4-aa11-4869-9d8b-1fb23e5ba34d">

**Comment by guqing** [comment]
点一下头像就可以修改，编辑表单不再提供头像设置

<img width="446" alt="image" src="https://github.com/halo-dev/halo/assets/38999863/c5502804-7aef-4b0e-b0e8-d0489e1fae6a">

**Comment by narcissuskid** [comment]
原来如此，感谢感谢

**Comment by shmilyabyy** [comment]
哇靠，吐血
