### ISSUE TITLE
默认编辑器-代码块快速输入空格bug

### ISSUE THREAD

**Issue by liuxiaobai5201314** [halo-dev/halo#4375]
### 是什么版本出现了此问题？

2.8.0

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker Compose

### 发生了什么？

在默认编辑器-代码块中，如果快速输入空格会有问题

### 附加信息

![1691118869950](https://github.com/halo-dev/halo/assets/54506419/c55a89a8-fe67-427f-9633-7230a10bc106)

**Comment by ruibaby** [comment]
我这边好像无法复现这个问题，是一直按着空格吗？

/triage needs-information

**Comment by liuxiaobai5201314** [comment]
目前没有这个问题了，可能是我用edge dev浏览器的bug，😂
