### ISSUE TITLE
希望备份能添加定时备份功能

### ISSUE THREAD

**Issue by Roozenlz** [halo-dev/halo#4376]
### 你当前使用的版本

2.8.0

### 描述一下此特性

希望可以给用户提供一个定时备份选项，用户能够自定义备份周期比如一天备份一次，以及自动备份任务所执行的时间点，比如凌晨4点(访问量小)，避免用户忘记备份可能造成的数据丢失风险。
拓展一下：
1. 定时备份在执行好后自动删除上一次自动备份的文件
2. 定时备份可以接入其他插件，选择不同的存储源，比如：定时备份任务执行完毕后自动上传到某某网盘/存储源，这样可以极大地保证数据的安全性,避免因为不可控因素导致的数据丢失，比如：升级halo版本时没有cp -r ,然后误操作将halo文件夹整个删除了,导致数据丢失

### 附加信息

感觉十分有必要，因为我1.6版本经历过一次误删数据库

**Comment by ruibaby** [comment]
目前我们已经为备份提供了后端和前端的扩展点：

- https://github.com/halo-dev/halo/blob/main/console/docs/extension-points/backup.md
- https://github.com/halo-dev/halo/blob/main/docs/backup-and-restore.md

我们期望这样的功能使用插件实现，并且我们已经上架了一款增强插件：https://www.halo.run/store/apps/app-dHakX

所以不考虑添加到 Core 当中，我将关闭此 issue。

/close
