### ISSUE TITLE
静态资源映射这个功能在哪？怎么用，没找到文档和位置

### ISSUE THREAD

**Issue by kecikeci** [halo-dev/halo#4379]
### 你当前使用的版本

2.8.0

### 描述一下此特性

静态资源映射这个功能在哪？怎么用，没找到文档和位置

**Comment by ruibaby** [comment]
目前没有在 Console 提供管理功能，需要手动在工作目录创建 static 目录以及放置文件。

**Comment by kecikeci** [comment]
> 目前没有在 Console 提供管理功能，需要手动在工作目录创建 static 目录以及放置文件。

嗯嗯   刚看到了那个pr的说明，了解了

**Comment by JohnNiang** [comment]
See https://github.com/halo-dev/halo/pull/4285 for more.
