### ISSUE TITLE
希望在配置项表单中添加可显示明文的密码框

### ISSUE THREAD

**Issue by longjuan** [halo-dev/halo#4382]
### 你当前使用的版本

main

### 描述一下此特性

目前在 s3 插件中，Access Key 和 Access Secret 是使用 password 输入框的。
但是这样对导致用户无法核对自己的输入，希望增加可显示明文的密码框，在截图保证安全的同时可以核对输入。
refer: https://github.com/halo-sigs/plugin-s3/issues/58

### 附加信息

1panel:
![image](https://github.com/halo-dev/halo/assets/28662535/701d4b26-2712-4f51-b2a3-6ee9e61b5eb2)

**Comment by ruibaby** [comment]
其实这种信息保存到 Secret 模型会更加安全，不过 password 类型的输入框也确实需要支持显示明文以方便核对。

/area console
/kind feature
