### ISSUE TITLE
默认编辑器有时出现极其卡顿的情况并一直保持这种卡顿，确定并不是电脑本身卡顿

### ISSUE THREAD

**Issue by Thomitics** [halo-dev/halo#4389]
### 是什么版本出现了此问题？

2.8.0

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker

### 在线站点地址

http://111.173.105.195:1234/

### 发生了什么？

默认编辑器有时出现极其卡顿的情况并一直保持这种卡顿，确定并不是电脑本身卡顿

### 附加信息

https://github.com/halo-dev/halo/assets/62173814/d6a9517b-7409-4cc6-b389-bde1ce072275

**Comment by JohnNiang** [comment]
目前我没有复现这个问题。我的操作环境如下：
- 操作系统： macOS 14.0 23A5301h arm64
- 浏览器：Chrome Version 113.0.5672.126 (Official Build) (arm64)
 和 Firefox 116.0.1 (64-bit)

**Comment by ruibaby** [comment]
是 Mac + Chrome 浏览器吗？我这边有几率复现，但其他网页上的输入框也一样，所以可能是 Chrome 的问题。建议换一个浏览器观察一下。

**Comment by Thomitics** [comment]
> 是 Mac + Chrome 浏览器吗？我这边有几率复现，但其他网页上的输入框也一样，所以可能是 Chrome 的问题。建议换一个浏览器观察一下。

是Windows22621.2070 + Edge115.0.1901.183

**Comment by ruibaby** [comment]
> > 是 Mac + Chrome 浏览器吗？我这边有几率复现，但其他网页上的输入框也一样，所以可能是 Chrome 的问题。建议换一个浏览器观察一下。
> 
> 是Windows22621.2070 + Edge115.0.1901.183

我会尝试用你的这篇文章进行复现：http://111.173.105.195:1234/archives/cpp_connect_mysql

**Comment by ruibaby** [comment]
我在 Windows 11 + Edge 上复制你的文章进行编辑，依旧没能复现这个问题。下次遇到这个问题的时候可以提供一下前后的操作步骤，不排除因为某个操作导致页面卡顿。

<img width="1920" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/4cda9b78-ff7c-43d9-a798-52619959b5ad">

我的设备：

Windows 22631.2129（运行在 Mac 的 Parallel Desktop 虚拟机，4g RAM） + Edge 115.0.1901.188

**Comment by Erzbir** [comment]
我也曾出现过此问题且不只是默认编辑器, 卡顿情况和视频中的一致, 但是不知道是什么原因, 也无法复显

MacBookPro + Chrome

没有具体操作步骤, 只是简单的编辑一篇文章, 并没有特别的操作

**Comment by chiyu-46** [comment]
我经常遇到这个问题，几乎每次使用默认编辑器编写较长的文章时都会出现，卡顿情况有时甚至比视频更严重。

这个问题并不是 Halo 2.8 版本的新问题，至少在 2.7 版本时，就已经有这个问题。（我之前一直在用 ByteMD ，不清楚更早的版本是否有问题）

刷新页面可以临时解决这个问题，但基本上再写一点，问题很快重新出现。

Windows11企业版22621.2134 + Chrome115.0.5790.171（因为有近10天没有写过新文章了，不能确定这两个版本是否仍是会出现问题的版本）

这是我的[博客](https://blog.chiyustudio.link/)，大家可以尝试使用这里的文章复现这个问题。并不需要局限哪篇文章，只要不是特别短，都会出现严重卡顿的问题。

**Comment by chiyu-46** [comment]
> 我在 Windows 11 + Edge 上复制您的文章进行编辑，仍然无法解决这个问题。接下来遇到这个问题的时候可以提供一下前后的操作步骤，不排除因为某些操作导致页面卡顿。
> 
> <img alt="图像" width="1920" src="https://user-images.githubusercontent.com/21301288/260215960-4cda9b78-ff7c-43d9-a798-52619959b5ad.png">
> 我的设备：
> 
> Windows 22631.2129（运行在Mac的并行桌面虚拟机，4g RAM）+ Edge 115.0.1901.188

我觉得并不能使用复制粘贴整篇文章的方式，复现这个问题。

这个问题可能是随着输入次数的增加而出现的，复制粘贴仅仅一篇文章也只是一次输入。

**Comment by gengxiaoxiaoxin** [comment]
输入大量的回车之后，大约800行，我产生了相似的卡顿体验。

以下是输入时的性能摘要：
![image](https://github.com/halo-dev/halo/assets/29268441/955f8e67-ead0-46d8-bc13-b8a215d9f34f)
1. 800行产生了800个`<p>`标签。

以下代码可能是导致相关卡顿。
https://github.com/halo-dev/halo/blob/43e1e446b64a74726984efe3cb675a3211f5211d/console/src/components/editor/DefaultEditor.vue#L238-L241

我们可以做：
1. 将三次getHtml调用调整为一次
2. 使用debounce来控制onUpdate的频率

以下是一些无关技术的建议：
1. 尝试关闭浏览器的拼接检查。

**Comment by ruibaby** [comment]
@gengxiaoxiaoxin 感谢花时间分析，有时间提交一个 PR 来优化这个问题吗？

**Comment by gengxiaoxiaoxin** [comment]
> @gengxiaoxiaoxin 感谢花时间分析，有时间提交一个 PR 来优化这个问题吗？

我会在周末尝试解决这个问题。

**Comment by tanqidi** [comment]
我现在卡顿非常非常严重但是只出现在代码块，其他的地方一点也不卡，我测试关闭 **highlight.js 代码高亮** 这个插件后一切都恢复正常了不再卡顿，我怀疑问题出在 **highlight.js 代码高亮** 这个插件上，大量的内容需要使用它进行样式渲染导致卡顿？只要我编写的文件内容非常大的并且**highlight.js 代码高亮**处于启用状态，在代码块中输入内容就会非常卡顿。
![Image](https://github.com/user-attachments/assets/6c591158-e513-4681-a005-7e0ad360d9e5)
![Image](https://github.com/user-attachments/assets/c8e2358c-322f-4fe7-b1a7-3fe7fda4ef73)
