### ISSUE TITLE
博客部署在heroku上出现的问题

### ISSUE THREAD

**Issue by blackappleD** [halo-dev/halo#439]
博客部署在heroku上的时候，发现初始化博客之后，第二天访问 之前的记录都没了，需要重新初始化。数据库用的h2。

最开始出现这个问题，我猜想可能是程序休眠导致内存中的h2数据库中的数据被回收了（heroku过半个小时如果没有访问就会让应用休眠）；

于是我我自己写了一小段代码会过5分钟请求一次接口。看日志也发现确实每5分钟都请求接口了，程序并没有休眠。但是第二天访问博客 还是会发生同样的问题。不知道有没有其他老铁知道这是什么原因。是heroku的原因还是说部署在其他云平台上也可能会有这个问题？（我自己没有尝试部署在其他云平台上，因为还没有购买服务器）

**Comment by ruibaby** [comment]
嗯，好的，晚点我试试再给你答复。

**Comment by blackappleD** [comment]
> 嗯，好的，晚点我试试再给你答复。

好的谢谢！

**Comment by ruibaby** [comment]
昨晚试了下，没过多久就被重置了，没找到问题所在，难道重置的时候会把应用生成的数据都删掉？而且看文档没发现配置环境的一些说明。

**Comment by blackappleD** [comment]
> 昨晚试了下，没过多久就被重置了，没找到问题所在，难道重置的时候会把应用生成的数据都删掉？而且看文档没发现配置环境的一些说明。

怀疑是因为数据库使用的是h2数据库，而因为某些原因，过一段时间这部份使用的内存因为长时间没有访问而被回收掉（可能是因为 heroku的某些限制），我想应该把数据库换成mysql就不会发生类似的问题了。

**Comment by ruibaby** [comment]
恐怕同样会出现问题，因为既然 h2 物理文件被清除了，那估计是 .halo 文件夹也被清除。那么就算你用 MySQL，.halo 内的附件，主题都可能会被清除。

**Comment by blackappleD** [comment]
> 恐怕同样会出现问题，因为既然 h2 物理文件被清除了，那估计是 .halo 文件夹也被清除。那么就算你用 MySQL，.halo 内的附件，主题都可能会被清除。

那就是求一波云平台的安利了>_>

**Comment by blackappleD** [comment]
> 恐怕同样会出现问题，因为既然 h2 物理文件被清除了，那估计是 .halo 文件夹也被清除。那么就算你用 MySQL，.halo 内的附件，主题都可能会被清除。

那就该求一波云平台的安利了。你们都把博客部署在哪儿啊？

**Comment by JohnNiang** [comment]
@ruibaby 如果 .halo 被清理了，那么 halo.jar 也会被清理啊

**Comment by ruibaby** [comment]
![Snipaste_2019-12-24_11-17-37](https://user-images.githubusercontent.com/21301288/71391429-05c7d980-263f-11ea-8f42-9d6ab0011678.png)
https://protected-beyond-76597.herokuapp.com/

**Comment by blackappleD** [comment]
> ![Snipaste_2019-12-24_11-17-37](https://user-images.githubusercontent.com/21301288/71391429-05c7d980-263f-11ea-8f42-9d6ab0011678.png)
> https://protected-beyond-76597.herokuapp.com/

我验证了，数据库换成mysql不会出现这样的情况

**Comment by JohnNiang** [comment]
@blackappleD 刚刚试着访问了该链接，仍然被重定向至了安装页面，也就是说 ~/.halo 这个文件夹已经被清理了（意味着配置文件也被干掉了

**Comment by blackappleD** [comment]
> @blackappleD 刚刚试着访问了该链接，仍然被重定向至了安装页面，也就是说 ~/.halo 这个文件夹已经被清理了（意味着配置文件也被干掉了

https://halo-tp.herokuapp.com/你访问这个 试试

**Comment by blackappleD** [comment]
> @blackappleD 刚刚试着访问了该链接，仍然被重定向至了安装页面，也就是说 ~/.halo 这个文件夹已经被清理了（意味着配置文件也被干掉了

我昨天部署的，用的是免费的mysql服务器 ，今天来访问倒是没有被 重置

**Comment by ruibaby** [comment]
@blackappleD 上传附件看看呢？会不会 heroku把 halo.mv.db当作临时文件了？

**Comment by blackappleD** [comment]
> @blackappleD 上传附件看看呢？会不会 heroku把 halo.mv.db当作临时文件了？

上传了，没有被删除，好像就是数据库的问题，内存数据库长时间未访问估计被heroku回收了

**Comment by ruibaby** [comment]
@blackappleD 可是h2的数据不是存在内存里的啊

**Comment by blackappleD** [comment]
> @blackappleD 可是h2的数据不是存在内存里的啊

哦哦也对，我看配置文件是使用的持久化模式，。。那就不知道到底什么原因了...

**Comment by ruibaby** [comment]
@blackappleD 估计是 heroku 当作临时文件了

**Comment by blackappleD** [comment]
> @blackappleD 估计是 heroku 当作临时文件了

嗯嗯，很有可能，我待会儿发邮件问一下他们对h2数据库的支持程度

**Comment by ruibaby** [comment]
@blackappleD 嗯

**Comment by Aienao** [comment]
> 博客部署在heroku上的时候，发现初始化博客之后，第二天访问 之前的记录都没了，需要重新初始化。数据库用的h2。
> 
> 最开始出现这个问题，我猜想可能是程序休眠导致内存中的h2数据库中的数据被回收了（heroku过半个小时如果没有访问就会让应用休眠）；
> 
> 于是我我自己写了一小段代码会过5分钟请求一次接口。看日志也发现确实每5分钟都请求接口了，程序并没有休眠。但是第二天访问博客 还是会发生同样的问题。不知道有没有其他老铁知道这是什么原因。是heroku的原因还是说部署在其他云平台上也可能会有这个问题？（我自己没有尝试部署在其他云平台上，因为还没有购买服务器）

老哥，有部署到heroku的教程吗
