### ISSUE TITLE
自带编辑器 无法预览图片 发布后无法显示图片 

### ISSUE THREAD

**Issue by lipanpan-hub** [halo-dev/halo#4395]
### 是什么版本出现了此问题？

2.8.0 和 2.7.0

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式部署？

Docker Compose

### 发生了什么？

从 2.7 升级到2.8 之后 写文章插入的图片无法显示 无法预览也无法显示 
经过检查发现 图片的地址 错误 我回退到2.7 发现也存在这个问题 
由于我挺久没有写带图片的文章了 还真不知道是从哪个版本出现的这个问题  不过可以肯定的是3.20号之前是没问题的
我是部署在 群晖上面的 一般情况下带端口号访问 

### 附加信息

![image](https://github.com/halo-dev/halo/assets/47287977/7ae5d260-3926-4934-a114-75192374e0e8)
![image](https://github.com/halo-dev/halo/assets/47287977/c4995393-8485-4df5-83f9-a9bbf594f9ce)

**Comment by guqing** [comment]
你使用的是什么编辑器写的文章呢

**Comment by lipanpan-hub** [comment]
自带的哪个编辑器

**Comment by lipanpan-hub** [comment]
https://lipanpanx.com

**Comment by lipanpan-hub** [comment]
姐姐 能不能尽快把这个问题 尽快解决掉  我全力配合测试  不能插图片这太头疼了呀

**Comment by guqing** [comment]
无法复现呢，能提供复现步骤吗，目前我尝试使用默认编辑器发布文章并且修改后端 `halo.external-url` 都没有能复现出你说的问题
<img width="1496" alt="image" src="https://github.com/halo-dev/halo/assets/38999863/760b713f-c6d7-4981-998b-e606e8159cb5">

**Comment by lipanpan-hub** [comment]
你直接登录我后台看看行吗  你邮箱给我我账号密码发给你

**Comment by guqing** [comment]
> 你直接登录我后台看看行吗 你邮箱给我我账号密码发给你

i#guqing.email

**Comment by lipanpan-hub** [comment]
你登录tg了吗 我也可以tg 联系你

**Comment by guqing** [comment]
> 你登录tg了吗 我也可以tg 联系你

好的

**Comment by guqing** [comment]
经过排查是安装了 `WebP Cloud Services` 插件并且启用了，但是没有配置它
<img width="626" alt="image" src="https://github.com/halo-dev/halo/assets/38999863/a7a4138a-761d-4338-918e-db52cacdd1c9">
这个插件的作用就是代理所有文章内容中的图片如果没有配置代理地址但是启用了就出现这个问题
即决办法
1. 配置这个插件的 `Proxy Address`
2. 或者直接停用这个插件

**Comment by lipanpan-hub** [comment]
嗯嗯 我试试 感谢
