### ISSUE TITLE
默认编辑器提供修改图片的alt内容

### ISSUE THREAD

**Issue by ghfkui** [halo-dev/halo#4397]
### 你当前使用的版本

2.8

### 描述一下此特性

添加图片后，可以自定义修改图片的alt。这对seo有帮助。
目前安装了stackEdit插件。但是使用默认编辑器创建的文章无法转换到stackEdit编辑器。如果能转换也就可以修改了

### 附加信息

目前安装了stackEdit插件。但是使用默认编辑器创建的文章一旦保存过后无法转换到stackEdit编辑器。
如果能转换也就可以修改了
![image](https://github.com/halo-dev/halo/assets/4645418/83b80e10-a14f-44f1-9e8c-771d241f4cab)

**Comment by ruibaby** [comment]
/kind feature
/area editor
/good-first-issue

有兴趣参与贡献可以向 https://github.com/halo-sigs/richtext-editor 提交 PR。

> 目前安装了stackEdit插件。但是使用默认编辑器创建的文章一旦保存过后无法转换到stackEdit编辑器。
如果能转换也就可以修改了

目前不同格式的文章不支持切换，这涉及到格式转换，是一个不小的工作量。
