### ISSUE TITLE
套用 CloudFront CDN 文章页面报错

### ISSUE THREAD

**Issue by Mrered** [halo-dev/halo#4398]
### 是什么版本出现了此问题？

2.7.0

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式部署？

Docker Compose

### 在线站点地址

https://blog.uijxmug.top

### 发生了什么？

不知道是什么原因，也不知道如何排查该 bug 。当打开首页、分类页面或标签页面时，不会提示如下图消息，当打开文章页面、自定义页面时会提示。

之前使用 Cloudflare CDN 速度过慢，所以换成 CloudFront CDN 了，换了之后就成这样了。

复现举例：https://blog.uijxmug.top/archives/US%20Apple%20ID%20enrollment%20tutorial

在论坛发过[帖子](https://bbs.halo.run/d/4154-%E5%A5%97%E7%94%A8-cloudfront-cdn-%E6%96%87%E7%AB%A0%E9%A1%B5%E9%9D%A2%E6%8A%A5%E9%94%99)，但没后续了，，，

### 附加信息

![](https://user-images.githubusercontent.com/34948506/257042758-33821ff6-5368-4877-9925-1ef4f840adcc.png)

**Comment by JohnNiang** [comment]
从现场看，可能是因为 CloudFront CDN 在回源的时候没有携带 query parameters。建议：
- 取消对 /apis/** 和 /api/** 接口的缓存
- 或者允许参数跟随
具体操作需要参考对应的文档。

/kind support

**Comment by Mrered** [comment]
> 从现场看，可能是因为 CloudFront CDN 在回源的时候没有携带 query parameters。建议：
> 
> * 取消对 /apis/** 和 /api/** 接口的缓存
> * 或者允许参数跟随
>   具体操作需要参考对应的文档。
> 
> /kind support /善意的支持

感谢！但是我第一次使用 CDN 不太清楚该从哪里检查配置，请问下面的配置正确吗？

<img width="726" alt="image" src="https://github.com/halo-dev/halo/assets/34948506/b1d2e9cf-14cf-4141-b3c2-a8be2b521574">


<img width="581" alt="image" src="https://github.com/halo-dev/halo/assets/34948506/d190ac19-8529-486f-9d08-23c1cb8f9d7f">

**Comment by Mrered** [comment]
已解决：

<img width="822" alt="image" src="https://github.com/halo-dev/halo/assets/34948506/52a28947-6154-4adc-97ba-ac10395b9953">
