### ISSUE TITLE
当插入代码块选择为auto时，里面的数据在前端页面无法直接看见

### ISSUE THREAD

**Issue by xiaobai3310** [halo-dev/halo#4404]
### 是什么版本出现了此问题？

2.8.0

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker Compose

### 发生了什么？

当我在后台的编写文章，需要往代码块插入文本数据时，选的语言是“auto”，发布之后代码块中数据无法直接看见，因为它的颜色与页面颜色混在一起了，需要选中这些数据才可以看见。

### 附加信息

![1](https://pic7.58cdn.com.cn/nowater/webim/big/n_v25a1c0612732a47dbbaf39b75e03b5f11.png)
![选中之后可见](https://pic7.58cdn.com.cn/nowater/webim/big/n_v2724f10535dae42fc885029b25c446e40.png)

**Comment by ruibaby** [comment]
是和 https://github.com/halo-dev/halo/discussions/4405#discussioncomment-6697358 相同的问题吗？

**Comment by xiaobai3310** [comment]
> 是和 [#4405 (reply in thread)](https://github.com/halo-dev/halo/discussions/4405#discussioncomment-6697358) 相同的问题吗？

是的，装了代码高亮插件后就都解决了。
