### ISSUE TITLE
发布完代码模块不高亮显示

### ISSUE THREAD

**Issue by gistmap** [halo-dev/halo#441]
在编写md的时候，右侧预览是有代码高亮的。
但在点下侧预览和查看文章的时候代码不高亮。

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [x] 请求技术支持

**Comment by ruibaby** [comment]
@gistmap 哪个主题？

**Comment by gistmap** [comment]
Material

**Comment by ruibaby** [comment]
@gistmap https://halo.run/guide/use/markdown.html

**Comment by gistmap** [comment]
@ruibaby 你好 我是用```java ```包裹起来的，切换到原始主题，高亮就显示了。

**Comment by ruibaby** [comment]
@gistmap 看看主题设置中有没有打开代码高亮

**Comment by gistmap** [comment]
@ruibaby 感谢，解决了

**Comment by qrqhuang** [comment]
我的情况是没有指定代码块语言。

直到看到文档中的说明

> 其中，language 为必填，如果不填写，很可能主题的代码高亮插件无法识别代码的语言，导致样式异常。举几个例子：
