### ISSUE TITLE
建议增加restful api

### ISSUE THREAD

**Issue by chenlip** [halo-dev/halo#4414]
### 你当前使用的版本

V1.5.2

### 描述一下此特性

建议增加restful api

场景:
我需要线下使用Markdown格式的文件能批量上传到站点中,

原来1.5版本时, 我直接在本地使用(typora)编写Markdown博客日志, 然后用python脚本直接调用restful api进行博客日志的发布.
非常的方便维护我的博客.

现在2.0之后的版本, 功能很强, 也很美, 可是没有restful api, 维护起来需要登录后台, 复制粘贴进行博客内容维护, 不方便

**Comment by ruibaby** [comment]
目前针对管理有完善的 API，只是暂时没有 API 的使用文档，可以关注：https://github.com/halo-dev/docs/issues/216

如果你需要使用 Python 编写发布脚本，可以参考：https://github.com/halo-sigs/vscode-extension-halo/blob/main/src/service/index.ts#L59

或者直接使用 VSCode 插件来发布 Markdown 文档：https://github.com/halo-sigs/vscode-extension-halo

/kind support

**Comment by ruibaby** [comment]
> 或者直接使用 VSCode 插件来发布 Markdown 文档：[halo-sigs/vscode-extension-halo](https://github.com/halo-sigs/vscode-extension-halo)

除了 VSCode 的发布插件，我也正在开发一个 Obsidian 的发布插件。Typora 的话，有一个上传图片的 CLI：https://github.com/halo-sigs/attachment-upload-cli

**Comment by terwer** [comment]
https://github.com/terwer/siyuan-plugin-publisher/issues/588 思源笔记发布工具准备支持halo，希望作者有时间可以补充下rest文档，不过目前来看，可以参考vscode-halo插件。

**Comment by LiuOcean** [comment]
> > 或者直接使用 VSCode 插件来发布 Markdown 文档：[halo-sigs/vscode-extension-halo](https://github.com/halo-sigs/vscode-extension-halo)
> 
> 除了 VSCode 的发布插件，我也正在开发一个 Obsidian 的发布插件。Typora 的话，有一个上传图片的 CLI：https://github.com/halo-sigs/attachment-upload-cli

请问 Obsidian 的插件有新进展嘛。
