### ISSUE TITLE
不同浏览器返回不同格式图片

### ISSUE THREAD

**Issue by Mrered** [halo-dev/halo#4417]
### 你当前使用的版本

2.7.0

### 描述一下此特性

由于 Edge 桌面浏览器暂未支持 `.avif` 格式图片，但放眼主流浏览器，皆已支持。如何才能让访客在使用不同浏览器访问时，

- 根据浏览器是否支持 `.avif` 来自动决定要加载 `.avif` 还是 `.webp` 甚至 `.jpg`；
- 无论上传哪种格式的图片，都尽可能向访客展示等质量下体积最小的格式；
- 希望在插入图片方式不变的情况下实现上述功能。

**Comment by ruibaby** [comment]
这在 Halo 这边实现的成本可能会比较高，或许可以自行部署一个这样的服务：https://github.com/webp-sh/webp_server_go


/priority awaiting-more-evidence

**Comment by Mrered** [comment]
感谢提供参考，那暂时不用开发此功能了，等待 Edge 浏览器适配之后，我再手动批量变更图床内容吧。我的图床是用存储桶创建的，所以比较好操作。
