### ISSUE TITLE
创建分类问题！

### ISSUE THREAD

**Issue by Karlvision** [halo-dev/halo#4421]
### 是什么版本出现了此问题？

2.8.0

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 在线站点地址

https://halo.karlvision.top:8443

### 发生了什么？

当我在后台文章页创建一个分类。文章设置了新的分类，但是，无法索引到文章
![image](https://github.com/halo-dev/halo/assets/50682981/77ab45d5-36b3-43a4-92d6-903fe9028952)
好像没有创建成功。不知道是哪里出了问题
这个是我创建的其中一个内容
![image](https://github.com/halo-dev/halo/assets/50682981/16a15491-52bb-4dd7-9858-d508e1e03a76)

### 附加信息

[halo-log-2023-08-14 13_38.log](https://github.com/halo-dev/halo/files/12331716/halo-log-2023-08-14.13_38.log)

**Comment by ruibaby** [comment]
日志文件中好像没有与之相关的日志。

/triage needs-information

**Comment by Karlvision** [comment]
感谢问题的关注。我今天尝试重启镜像，发现分类信息已恢复。可以正常显示了，并且创建了一个新的分类，正常。

![image](https://github.com/halo-dev/halo/assets/50682981/4f6e245a-f352-4e2f-92c4-d8b3a156e9be)
