### ISSUE TITLE
升级 Formkit 版本之后，系统初始化时输入框报错

### ISSUE THREAD

**Issue by LIlGG** [halo-dev/halo#4424]
### 是什么版本出现了此问题？

2.9.0-SNAPSHOT

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker Compose

### 发生了什么？

系统初始化时，输入用户名则会出现如下错误：

<img width="1920" alt="image" src="https://github.com/halo-dev/halo/assets/31335418/ce92ed48-a75f-4d0c-8da0-cba39efbba97">

进而导致无法点击初始化按钮。其他输入框未出现此问题
经过测试，与 Formkit 版本升级有关 #4411 

/kind bug

**Comment by ruibaby** [comment]
似乎已经在 0.18.0 中修复，请看：https://github.com/formkit/formkit/issues/852
