### ISSUE TITLE
控制台附件管理中，附件移动无下拉选项

### ISSUE THREAD

**Issue by zry0310** [halo-dev/halo#4426]
### 是什么版本出现了此问题？

halo:2.8

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker Compose

### 发生了什么？

进入控制台页面，选择左侧菜单中’附件‘栏，点击勾选任意附件，点击上方出现的移动按钮，发现下拉框为空，没有已创建的附件存储策略、附件分类等下拉框

### 附加信息

<img width="1010" alt="Snipaste_2023-08-15_10-45-32" src="https://github.com/halo-dev/halo/assets/85779793/45b0fdaa-2738-4e7b-88f6-a07deb6557d8">

**Comment by JohnNiang** [comment]
/kind improvement
/area console

这里的移动指的是“移动分组”，不是“存储策略”。
