### ISSUE TITLE
Metaweblog API 特性支持

### ISSUE THREAD

**Issue by LiuOcean** [halo-dev/halo#4429]
### 你当前使用的版本

2.8

### 描述一下此特性

之前在 [论坛地址](https://bbs.halo.run/d/2961-halo2%E7%9A%84xmlrpc%E6%8F%92%E4%BB%B6) 中，有一位开发者已经写了类似的内容。但由于链接损坏，目前 Metaweblog 特性无法使用

该 API 的使用场景，一般是在使用 MWeb 编辑器写文章，然后上传到博客中。这样做的好处是，如果作者需要同时发多个渠道的文章，可以统一使用 MWeb 做管理

目前在我的使用流程上比较蹩脚，在 MWeb 写完文章后，导出至 VSCode，然后再用插件上传到 Halo 上

希望官方可以提供这个上传标准，或者提供一个 Halo 自己的 API 标准，让 MWeb 做一下支持

**Comment by ruibaby** [comment]
> 希望官方可以提供这个上传标准，或者提供一个 Halo 自己的 API 标准，让 MWeb 做一下支持

现在本身就是有 API 的，参考：https://github.com/halo-dev/halo/issues/4414#issuecomment-1675772860

Metaweblog 相关讨论：

1. https://github.com/halo-dev/halo/issues/35
