### ISSUE TITLE
假如在docker上运行了很久，现在要换服务器(学生机到期)，应该把所有容器copy一份吗？

### ISSUE THREAD

**Issue by zmylk** [halo-dev/halo#443]

**Comment by ruibaby** [comment]
@zmylk 只需备份 .halo

**Comment by zmylk** [comment]
@ruibaby 感谢，明白了。

**Comment by hiparker** [comment]
这是干嘛呢 在我博客上疯狂留言

**Comment by ruibaby** [comment]
> 这是干嘛呢 在我博客上疯狂留言

可能是某个孤儿在作祟。建议在博客设置的评论设置中先关闭 Api 评论。

**Comment by WinteWu** [comment]
真是孤儿、刷三天了，公开几个ip吧
109.70.100.41
185.165.168.229
46.165.230.5
查看方法
当天：grep "/api/content/posts/comments" /var/log/nginx/access.log
之前：zcat /var/log/nginx/access.log-20201026.gz | grep "/api/content/posts/comments"

**Comment by qaiu** [comment]
什么傻逼玩意儿，老是留言，留尼玛呢

**Comment by maplefix** [comment]
丢啊，有没有办法屏蔽一手，我被刷了13页的评论。。

**Comment by JohnNiang** [comment]
> 丢啊，有没有办法屏蔽一手，我被刷了13页的评论。。

后台设置可以关闭评论 API。

**Comment by maplefix** [comment]
医管。109.70.100.35/54 IP段都有，看日志还是随机出现的。

**Comment by qaiu** [comment]
建议增加防垃圾评论功能  针对同一个ip可以设定评论间隔时间间隔阈值 或者重复留言设置次数限制 之前用typecho有相关设置

**Comment by qaiu** [comment]
建议增加防垃圾评论功能  针对同一个ip可以设定评论间隔时间间隔阈值 或者重复留言设置次数限制 之前用typecho有相关设置
