### ISSUE TITLE
主页排除 某些 tag 显示

### ISSUE THREAD

**Issue by LiuOcean** [halo-dev/halo#4436]
### Your current Halo version

2.8

### Describe this feature

希望主页可以根据自定义的 tags 排除某一类文章的显示，这些被排除的 tag，只能手动点击分类才可查看

**Comment by LiuOcean** [comment]
这个 feature 主要适用下述场景：

希望主页可以专注显示某类文章，比如技术相关，但是平时也会有其他内容，都显示在主页少了一些技术的专注性。

**Comment by ruibaby** [comment]
之前确实有考虑到这个场景，但个人感觉这个设置放在分类会更合适，感谢提出。

/kind feature

**Comment by ruibaby** [comment]
这个功能已经在 https://github.com/halo-dev/halo/pull/6116 中实现，并发布在了 [2.17.0](https://github.com/halo-dev/halo/releases/tag/v2.17.0)。

/close
