### ISSUE TITLE
希望可以在后台文章页面右侧的分类和标签页面下添加返回按钮

### ISSUE THREAD

**Issue by erruicoders** [halo-dev/halo#4438]
### Your current Halo version

2.8.0

### Describe this feature

希望可以在后台文章页面右侧的分类和标签页面内添加返回按钮，就像打开回收站那样有一个返回的按钮

### Additional information

![image](https://github.com/halo-dev/halo/assets/75353639/466996cc-c3ac-4cee-99c0-28cf91642b3c)
![image](https://github.com/halo-dev/halo/assets/75353639/923a2136-af5f-4d3d-aa81-c936ceafa91f)

**Comment by ruibaby** [comment]
我们计划直接修改 Console 的结构，支持全局的返回按钮和面包屑导航。

/triage duplicate

see https://github.com/halo-dev/halo/issues/2654
