### ISSUE TITLE
启动程序时 AttachmentReconciler 不能更新使用插件上传的附件的 Permalink

### ISSUE THREAD

**Issue by longjuan** [halo-dev/halo#4439]
### 是什么版本出现了此问题？

2.8.0

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

在程序启动时 DefaultAttachmentService 不能拿到插件中的 AttachmentHandler，导致进入 fallback 获取 annotations 的 Permalink，最终不会更新。
![image](https://github.com/halo-dev/halo/assets/28662535/213aead4-7265-4f3d-8c0c-471a8ca01bc3)
![image](https://github.com/halo-dev/halo/assets/28662535/41c51c89-7c82-46e2-992a-62c40a54770f)

所以当初设计 AttachmentReconciler 去更新 Permalink 是只针对本地存储的附件吗？

目前有人想更新 s3 插件中附件的地址，我想通过这个实现，排查出这个问题。
https://github.com/halo-sigs/plugin-s3/issues/62

### 附加信息

https://github.com/halo-dev/halo/blob/43e1e446b64a74726984efe3cb675a3211f5211d/application/src/main/java/run/halo/app/core/extension/reconciler/attachment/AttachmentReconciler.java#L49-L67

**Comment by JohnNiang** [comment]
感谢反馈这个问题！

> 当初设计 AttachmentReconciler 去更新 Permalink

主要是为了兼容以前的数据。

关于更新后无法继续更新的问题，我目前能想到的方案：找不到对应的实现，直接抛出异常，直到插件安装并启用。目前尚不清楚是否会产生新的兼容性问题。

/kind bug
/area plugin
