### ISSUE TITLE
无法使用RSS软件订阅

### ISSUE THREAD

**Issue by Aqpcet** [halo-dev/halo#444]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

**Comment by ruibaby** [comment]
你的博客地址是？

**Comment by Aqpcet** [comment]
> 你的博客地址是？

https://blog.xu-lin.top

**Comment by ruibaby** [comment]
可以。https://blog.xu-lin.top/atom.xml or https://blog.xu-lin.top/rss.xml

![Snipaste_2019-12-26_17-37-52](https://user-images.githubusercontent.com/21301288/71470275-900e6a00-2806-11ea-9337-b496e65ff82b.png)

**Comment by Aqpcet** [comment]
> https://blog.xu-lin.top/atom.xml
https://blog.xu-lin.top/atom.xml 
ipad的RSS Reader app可订阅无内容

https://blog.xu-lin.top/rss.xml
ipad的RSS Reader app可订阅有内容

感谢！

**Comment by ruibaby** [comment]
可能是它不支持 atom 格式？

**Comment by Aqpcet** [comment]
> 可能是它不支持 atom 格式？

有可能，再次感谢！
