### ISSUE TITLE
halo2.8上传附件，超过1M出错

### ISSUE THREAD

**Issue by ozersource** [halo-dev/halo#4440]
### 是什么版本出现了此问题？

2。8

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

无论什么格式，超过1M上传到100%会无响应，调试模式显示错误
  Uncaught SyntaxError: Unexpected token '<', "<html>
<h"... is not valid JSON
    at JSON.parse (<anonymous>)
    at Object.getResponseError (index-e1788345.js:102:46123)
    at XMLHttpRequest.<anonymous> (index-e1788345.js:102:26487)

清空所有数据，重新部署docker，也是同样的错误，但好像前几天还能上传大于1M的附件

**Comment by ruibaby** [comment]
/triage duplicate

see https://github.com/halo-dev/halo/issues/4359

 解决办法：https://docs.halo.run/user-guide/faq#%E9%99%84%E4%BB%B6%E4%B8%8A%E4%BC%A0%E6%8F%90%E7%A4%BA-413-request-entity-too-large-%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3

/close
