### ISSUE TITLE
分享链接无法自动抓取标题等信息

### ISSUE THREAD

**Issue by LiuOcean** [halo-dev/halo#4442]
### Your current Halo version

2.8

### Describe this feature

之前使用 wordpress 时，如果分享到 即刻 平台上，会自动抓取文章标题和头图，但是在 halo 上的文章只能被抓取到站点名称
<img width="361" alt="image" src="https://github.com/halo-dev/halo/assets/20659474/c763824f-b6eb-4592-b7b9-555e68a45d45">

希望 halo 可以增加类似的功能

**Comment by ruibaby** [comment]
这似乎和主题中模板的 head 头部标签元素有关，具体使用的什么主题？

/triage needs-information

**Comment by LiuOcean** [comment]
使用的 hao 主题。不太懂 web 相关的内容，这个有办法自己修吗。

**Comment by ruibaby** [comment]
建议向 [hao](https://github.com/liuzhihang/halo-theme-hao) 主题提交 issue，我刚刚看了一下，这个主题设置 title 信息似乎是通过 js 去设置的，所以社交平台无法正确读取到实际的 title 。

**Comment by LiuOcean** [comment]
谢谢。
