### ISSUE TITLE
search google 提交站点地图 google 提示无法抓取

### ISSUE THREAD

**Issue by czqclm** [halo-dev/halo#4443]
### 是什么版本出现了此问题？

 2.8.0

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker Compose

### 在线站点地址

https://blog.aicq.icu

### 发生了什么？

<img width="940" alt="image" src="https://github.com/halo-dev/halo/assets/26992194/82624e77-4881-4b05-b7e4-f72728b238c2">
直接访问是可以的
https://blog.aicq.icu/sitemap.xml

### 附加信息

>

**Comment by ruibaby** [comment]
<img width="572" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/8b0007c2-111a-4b3b-a1cd-7970a5a89285">

 可能是因为链接不是 https，你可以将 external-url 设置为 https 协议试试。

https://docs.halo.run/getting-started/install/docker-compose#:~:text=mysql%E3%80%81h2-,halo.external%2Durl,-%E5%A4%96%E9%83%A8%E8%AE%BF%E9%97%AE%E9%93%BE

/kind support

**Comment by JohnNiang** [comment]
建议更新 sitemap 插件至最新，并同时删除外部访问链接（external-url）配置。

**Comment by czqclm** [comment]
> <img alt="image" width="572" src="https://user-images.githubusercontent.com/21301288/261855948-8b0007c2-111a-4b3b-a1cd-7970a5a89285.png">
> 可能是因为链接不是 https，你可以将 external-url 设置为 https 协议试试。
> 
> https://docs.halo.run/getting-started/install/docker-compose#:~:text=mysql%E3%80%81h2-,halo.external%2Durl,-%E5%A4%96%E9%83%A8%E8%AE%BF%E9%97%AE%E9%93%BE
> 
> /kind support /kind支持
1. 我将 external-url 已经改成 https 
![image](https://github.com/halo-dev/halo/assets/26992194/fd6e599e-1789-4ad1-a82c-86ce963192c6)
![image](https://github.com/halo-dev/halo/assets/26992194/0d2c019d-34e5-43a1-82cd-302530160fa0)

2. 我访问 sitemap.xml 还是 http
![image](https://github.com/halo-dev/halo/assets/26992194/fa28e5f3-3051-467e-8674-4ad3e4d5c628)


> 建议更新 sitemap 插件至最新，并同时删除外部访问链接（external-url）配置。
3. @JohnNiang sitemap 版本号为 1.0.2
![image](https://github.com/halo-dev/halo/assets/26992194/bb994b9e-dfaf-4760-a65a-0a195c2bad32)
4. 貌似改了也是一样
![image](https://github.com/halo-dev/halo/assets/26992194/7f4685cd-5938-4ef6-905f-b91cdd09fb51)
![image](https://github.com/halo-dev/halo/assets/26992194/76ba2f30-b5c2-42e6-9a00-f3b1b64a3868)
![image](https://github.com/halo-dev/halo/assets/26992194/07dfd9c0-4116-4b4a-b538-2b1263d020eb)

是不是因为我外部套了一层 cloudflare 导致的，我是服务器开 nginx 暴露 80 端口，然后 cloudflare 开代理模式进行 https 的访问
![image](https://github.com/halo-dev/halo/assets/26992194/4a35a663-b0cd-496c-b6ac-c7de69c41db7)

**Comment by wangweiweiwei** [comment]
小哥哥你好，我看你的sitemap里面的链接协议已经变成https了请问一下你是怎么搞的？我external-url设置为https或者不设置这项配置，sitemap里面的链接都还是http协议的链接

**Comment by wangweiweiwei** [comment]
> 小哥哥你好，我看你的sitemap里面的链接协议已经变成https了请问一下你是怎么搞的？我external-url设置为https或者不设置这项配置，sitemap里面的链接都还是http协议的链接

我看已经大佬们已经在改了

>https://github.com/halo-sigs/plugin-sitemap/pull/16

**Comment by czqclm** [comment]
> 小哥哥你好，我看你的sitemap里面的链接协议已经变成https了请问一下你是怎么搞的？我external-url设置为https或者不设置这项配置，sitemap里面的链接都还是http协议的链接

我是将 cloudflare CDN 改成了直接访问 nginx，nginx 配置 ssl。但目前 google 还是无法抓取
![image](https://github.com/halo-dev/halo/assets/26992194/cf7887a2-fabc-41cc-a0d8-d91ffae3807e)

**Comment by ruibaby** [comment]
@czqclm 我使用了一个 Sitemap 验证平台，似乎是没有问题的：

<img width="815" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/bc0755cf-f953-4cb3-ad83-bbd87af59b11">

https://www.xml-sitemaps.com/validate-xml-sitemap.html

**Comment by czqclm** [comment]
![IMG_8104](https://github.com/halo-dev/halo/assets/26992194/c1b29f1c-9d36-4246-924a-1efe5090e730)
那就真的奇怪了😥，难道是nginx的问题么

**Comment by guqing** [comment]
> ![IMG_8104](https://user-images.githubusercontent.com/26992194/266764487-c1b29f1c-9d36-4246-924a-1efe5090e730.png) 那就真的奇怪了😥，难道是nginx的问题么

应该不是图中说的 content type 的问题，sitemap.xml 的 content type 使用的是 text/xml，和 google 的 sitemap一致，所以 google 不会因为这个问题无法抓取，我们的都是可以成功的：

<img width="1545" alt="image" src="https://github.com/halo-dev/halo/assets/38999863/2aeb0245-4d5d-4316-aeb7-7a4e15d6afe8">

**Comment by guqing** [comment]
我看你的 sitemap.xml 访问很慢，需要 17.9 秒，google 会不会因为访问超时而抓取失败

**Comment by czqclm** [comment]
> 我看你的 sitemap.xml 访问很慢，需要 17.9 秒，google 会不会因为访问超时而抓取失败，你可以先让你的 sitemap.xml 访问的快点然后在重试 google 抓取

不好意思，有其他变量导致了我这个访问出现了卡顿，周五在服务器上跑了 k3s 的节点，安装了一些吃性能的服务。我现在已经将 k3s 关闭了，访问正常了。稍微慢点也比较正常，我这个服务器在香港。
![image](https://github.com/halo-dev/halo/assets/26992194/221ba813-5dea-4378-a118-ff0f9a641f23)
目前速度上来了，结果还是依旧，我还是比较头疼。期间我怀疑过是不是生成链接中包含中文，转义为 url 编码导致 xml 不识别，我把链接地址全改了好像也没解决问题。
![image](https://github.com/halo-dev/halo/assets/26992194/481d4b66-6969-4620-9113-d9d3475ca873)
这里的检查确实没问题了，但 google 还是没有抓取
![image](https://github.com/halo-dev/halo/assets/26992194/cf2e233a-cfe9-4941-81a6-60759095bd25)

**Comment by guqing** [comment]
你可以先将 /feed.xml 提交到 google 效果和 sitemap 一样，目前还无法定位问题原因，google 也没有个提示什么的

**Comment by wangweiweiwei** [comment]
> > 你可以先将 /feed.xml 提交到 google 效果和 sitemap 一样，目前还无法定位问题原因，google 也没有个提示什么的 需要安装这个插件 feed 插件 仓库地址：https://github.com/halo-sigs/plugin-feed 应用市场地址：https://halo.run/store/apps/app-KhIVw
> 
> 我安装了最新版的 1.1.1 的 feed。 生成链接如下：https://blog.aicq.icu/feed.xml google 结果 ![image](https://user-images.githubusercontent.com/26992194/267181261-d8650928-48ab-40f5-abd7-a5a497fcb7bd.png) 我开始怀疑是不是谷歌无法访问我的站点，于是我拨测了海外的线路 ![image](https://user-images.githubusercontent.com/26992194/267181406-dba95075-a71a-4250-944d-1ab7115e3131.png) 最慢的也没有超过 2 秒。 Google 也不给个提示还是比较难排查

你可以试试看有没有报告里面可以看到一些信息
路径在：设置-抓取统计信息-打开报告 
里面可以看到一些信息
![image](https://github.com/halo-dev/halo/assets/38938115/b0358dc3-77cb-4fe4-a470-42b0ba7b5e17)

**Comment by guqing** [comment]
我尝试了一下通过 https://www.xml-sitemaps.com/ 填入我站点的链接生成 sitemap 后放到站点然后重新提交 sitemap 到 google 发现也无法抓取,但是其他人的可以，所以估计跟 sitemap 插件没有什么关系，原因不明🙂
<img width="1094" alt="image" src="https://github.com/halo-dev/halo/assets/38999863/b18a9066-cff9-492f-9eb0-937cb5fd0ceb">

**Comment by czqclm** [comment]
> > > 你可以先将 /feed.xml 提交到 google 效果和 sitemap 一样，目前还无法定位问题原因，google 也没有个提示什么的 需要安装这个插件 feed 插件 仓库地址：https://github.com/halo-sigs/plugin-feed 应用市场地址：https://halo.run/store/apps/app-KhIVw
> > 
> > 
> > 我安装了最新版的 1.1.1 的 feed。 生成链接如下：https://blog.aicq.icu/feed.xml google 结果 ![image](https://user-images.githubusercontent.com/26992194/267181261-d8650928-48ab-40f5-abd7-a5a497fcb7bd.png) 我开始怀疑是不是谷歌无法访问我的站点，于是我拨测了海外的线路 ![image](https://user-images.githubusercontent.com/26992194/267181406-dba95075-a71a-4250-944d-1ab7115e3131.png) 最慢的也没有超过 2 秒。 Google 也不给个提示还是比较难排查
> 
> 你可以试试看有没有报告里面可以看到一些信息 路径在：设置-抓取统计信息-打开报告 里面可以看到一些信息 ![image](https://user-images.githubusercontent.com/38938115/267193716-b0358dc3-77cb-4fe4-a470-42b0ba7b5e17.png)

![image](https://github.com/halo-dev/halo/assets/26992194/463aa38f-9dcd-4020-b948-ecb592c3823c)
我看到响应中都是成功的，404的 favicon.ico 是因为我确实没有传，但里面没有 sitemap
![image](https://github.com/halo-dev/halo/assets/26992194/c9094e26-6d9a-42fe-9e22-29dee820fafe)

**Comment by czqclm** [comment]
> 我尝试了一下通过 https://www.xml-sitemaps.com/ 填入我站点的链接生成 sitemap 后放到站点然后重新提交 sitemap 到 google 发现也无法抓取,但是其他人的可以，所以估计跟 sitemap 插件没有什么关系，原因不明🙂 <img alt="image" width="1094" src="https://user-images.githubusercontent.com/38999863/267198185-b18a9066-cff9-492f-9eb0-937cb5fd0ceb.png">

我可以尝试先把 sitemap 插件卸载了，然后在用 feed 试试

**Comment by ruibaby** [comment]
如果这个问题和 sitemap 插件无关，我将关闭此 issue，后续有其他问题欢迎提交新 issue。

/close

**Comment by cc114230** [comment]
你好，请问解决了吗
