### ISSUE TITLE
请问这个如何设置？貌似halo是标签，并且固定在上面，没办法改。

### ISSUE THREAD

**Issue by youngledo** [halo-dev/halo#4444]
### 你当前使用的版本

最新版

### 描述一下此特性

请问这个如何设置？貌似halo是标签，并且固定在上面，没办法改。
<img width="431" alt="企业微信截图_d26a1c3d-1df2-41ef-bde8-0d4acf48578d" src="https://github.com/halo-dev/halo/assets/68590897/17f18b90-e4e5-4d6a-9498-c84d4c9af93c">

**Comment by JohnNiang** [comment]
/kind support

头部菜单需要在 `Console > 菜单` 中设置
