### ISSUE TITLE
服务器使用Ubuntu，halo成功运行，公网无法访问

### ISSUE THREAD

**Issue by Poison02** [halo-dev/halo#4446]
### What is version of Halo has the issue?

2.8

### What database are you using?

MySQL 8.x

### What is your deployment method?

Docker Compose

### What happened?

我是在Ubuntu的环境下用docker-compose部署了halo，也放开了对应的端口，但是依然无法访问！
![image](https://github.com/halo-dev/halo/assets/106656220/dc082859-dbb0-4b0a-ac04-f93973696d4c)
访问出现**502**
![image](https://github.com/halo-dev/halo/assets/106656220/42f5ad09-326b-42ba-9ac8-123ef135285a)

**Comment by ruibaby** [comment]
建议先确认 Halo 是否正常运行，你可以在服务器上执行 `curl http://localhost:8090/` 观察是否可以正常输出网页内容，也可以观察 Halo 的运行日志。如果 Halo 的运行情况没有问题，建议检查你服务器的其他配置，我们在不了解你服务器配置信息的情况时，很难进行判断。

**Comment by Poison02** [comment]
上面的是halo的运行日志，红框的是`curl`，但是没有反应
![image](https://github.com/halo-dev/halo/assets/106656220/07a9460c-c4c9-43c2-9888-dd9fe3995734)
查看防火墙也是开放了端口的，但就是不能访问
![image](https://github.com/halo-dev/halo/assets/106656220/867e9a53-4760-4326-afe5-5036e204bcea)
我就是按照官方文档的`docker-compose`部署来的，请问我还需要提供什么信息吗

**Comment by JohnNiang** [comment]
你可能需要贴出反向代理配置的细节。

从[截图](https://user-images.githubusercontent.com/106656220/261791861-42f5ad09-326b-42ba-9ac8-123ef135285a.png)中来看，极有可能是反向代理配置错误导致的。

**Comment by Poison02** [comment]
> 你可能需要贴出反向代理配置的细节。
> 
> 从[截图](https://user-images.githubusercontent.com/106656220/261791861-42f5ad09-326b-42ba-9ac8-123ef135285a.png)中来看，极有可能是反向代理配置错误导致的。

我这里并没有使用`Nginx`做反向代理呀？请问我应该怎么做呢？

**Comment by Poison02** [comment]
抱歉，各位，这里没有访问到的原因是我以为我室友打开了腾讯云的防火墙的，但是他没有开，经过了各种排查，解决了，真的打扰了，感谢你们😁
