### ISSUE TITLE
没有显示评论的地方，无法评论

### ISSUE THREAD

**Issue by mengdalida** [halo-dev/halo#4449]
### What is version of Halo has the issue?

2.8.0

### What database are you using?

H2

### What is your deployment method?

Fat Jar

### Your site address.

localhost

### What happened?

根本没有评论区显示
版本release2.8
主题是earth1.5.0
用户设置里已经开发注册
评论设置里启动了评论，关闭了评论审核和仅允许新注册用户评论

### Relevant log output

```shell
没有报错日志
```

### Additional information

![X9W23B602UYF6WYXCH4JQ}W](https://github.com/halo-dev/halo/assets/104249502/262e1900-c8f1-48c2-a7af-7b65ff78014c)

**Comment by JohnNiang** [comment]
1. 建议看看评论插件是否安装或者是否正常运行；
2. 打开浏览器控制台（F12）看看是否有报错。

/triage needs-information

**Comment by mengdalida** [comment]
> 1. 建议看看评论插件是否安装或者是否正常运行；
> 2. 打开浏览器控制台（F12）看看是否有报错。
> 
> /triage needs-information

1.没有安装评论插件，需要安装什么插件？
2.控制台没有报错

**Comment by mengdalida** [comment]
`<html>
<body>


  | <!DOCTYPE html>
-- | --
  | <html lang="zh">
  | <head>
  | <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  | <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  | <title>1111 - xingzi</title>
  | <meta name="apple-mobile-web-app-capable" content="yes" />
  | <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  | <meta name="format-detection" content="telephone=no" />
  | <meta name="renderer" content="webkit" />
  | <link rel="alternate" type="application/rss+xml" title="atom 1.0" href="/rss.xml" />
  | <style>
  | .sidebar {
  | width: 40%;
  | }
  |  
  | .page-top {
  | width: calc(100% - 40%);
  | }
  |  
  | .content {
  | width: calc(100% - 40%);
  | }
  |  
  | /* <#if settings.sidebar_background?? && settings.sidebar_background!=''>
  | .sidebar {
  | background: url("${settings.sidebar_background!}") no-repeat center center fixed;
  | }
  | </#if> */
  | </style>
  |  
  |  
  |  
  | <link rel="stylesheet" href="/themes/theme-anatole/assets/dist/style.css?v=2.1.0" />
  | <script src="/themes/theme-anatole/assets/dist/main.iife.js?v=2.1.0"></script>
  |  
  |  
  | <meta name="description" content="21212121" />
  | <script async defer src="/halo-tracker.js" data-group="content.halo.run" data-plural="posts" data-name="ac38044b-a03e-4681-882e-9b155e255054"></script>
  | </head>
  | <body>
  | <div class="sidebar animated fadeInDown">
  | <div class="logo-title">
  | <div class="title">
  | <img
  | alt="Logo"
  | class="inline-block"
  | src=""
  | style="width: 127px ;border-radius:50%"
  | />
  | <h3 class="!mt-3 !mb-0">
  | <a href="/" title="xingzi">xingzi</a>
  | </h3>
  | <div class="description mt-2">
  | <p class="description-text"></p>
  | </div>
  | </div>
  | </div>
  | <ul class="social-links mt-1">
  |  
  | </ul>
  |  
  | <div class="footer">
  | <a target="_blank" href="#">
  | <a href="https://www.caicai.me">Designed by CaiCai</a>
  | <div class="by_halo">
  | <a href="https://halo.run" target="_blank">Proudly published with Halo</a>
  | </div>
  | <div class="footer_text">
  |  
  | </div>
  | </a>
  | </div>
  | </div>
  |  
  | <div class="main">
  | <div class="page-top animated fadeInDown">
  | <div
  | id="nav"
  | class="nav ml-[30px] mr-4 flex h-full flex-1 flex-nowrap items-center gap-6 overflow-x-auto whitespace-nowrap text-sm"
  | >
  | <div
  | class="nav-item relative inline-flex h-full items-center text-black/70 transition-all hover:text-[#4786D6]"
  | >
  | <a
  | href="/"
  | >首页</a>
  | </div>
  | <div
  | class="nav-item relative inline-flex h-full items-center text-black/70 transition-all hover:text-[#4786D6]"
  | >
  | <a
  | href="/archives/hello-halo"
  | >Hello Halo</a>
  | </div>
  | <div
  | class="nav-item relative inline-flex h-full items-center text-black/70 transition-all hover:text-[#4786D6]"
  | >
  | <a
  | href="/tags/halo"
  | >Halo</a>
  | </div>
  | <div
  | class="nav-item relative inline-flex h-full items-center text-black/70 transition-all hover:text-[#4786D6]"
  | >
  | <a
  | href="/about"
  | >关于</a>
  | </div>
  | </div>
  | <div class="information gap-4">
  | 
  |  
  | 
  | 
  | </div>
  | </div>
  |  
  | <div class="content">
  |  
  | <div class="animated fadeInDown m-[30px] mt-[20px] border-b border-gray-200">
  | <div class="flex flex-col pb-3">
  | <div class="flex flex-wrap items-end">
  | <h3 class="text-xl font-medium leading-6 text-gray-900">1111</h3>
  |  
  | </div>
  | <div>
  |  
  | <div class="post-info mt-2" x-data="upvote('post','content.halo.run','posts')">
  | <div class="meta" x-data="{name:&#39;ac38044b-a03e-4681-882e-9b155e255054&#39;}">
  | <div class="info">
  | <i class="i-mdi-calendar-month-outline h-3 w-3"></i>
  | <span>2023-08-21</span>
  | <i class="i-mdi-eye h-3 w-3"></i>
  | <span>13</span>
  | <i class="i-mdi-comment-outline h-3 w-3"></i>
  | <a href="#comment_widget">0</a>
  | <div
  | class="inline-block cursor-pointer hover:text-red-700"
  | x-bind:class="{'text-red-700': upvoted(name)}"
  | x-on:click="handleUpvote(name)"
  | >
  | <i x-show="upvoted(name)" class="i-mdi-heart h-3 w-3"></i>
  | <i x-show="!upvoted(name)" class="i-mdi-heart-outline h-3 w-3"></i>
  | <span data-upvote-post-name="ac38044b-a03e-4681-882e-9b155e255054">0</span>
  | </div>
  |  
  |  
  | </div>
  | </div>
  | </div>
  |  
  | </div>
  | </div>
  | </div>
  |  
  | <div class="post-page">
  | <div class="post animated fadeInDown">
  | <div id="post-content" class="post-content markdown-body"><p>21212121</p></div>
  | </div>
  | <div
  | class="pagination flex items-center justify-between"
  | >
  |  
  | <a
  | class="btn"
  | role="navigation"
  | href="/archives/hello-halo"
  | title="Hello Halo"
  | >
  | 下一篇
  | </a>
  | </div>
  | <div id="comment_widget" style="margin: 30px">
  |  
  | </div>
  | </div>
  |  
  | </div>
  | </div>
  | </body>
  | </html>
  |  


</body>
</html><!DOCTYPE html>
<html lang="zh">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>1111 - xingzi</title>
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black" />
    <meta name="format-detection" content="telephone=no" />
    <meta name="renderer" content="webkit" />
    <link rel="alternate" type="application/rss+xml" title="atom 1.0" href="[/rss.xml](http://localhost:8090/rss.xml)" />
    <style>
  .sidebar {
    width: 40%;
  }

  .page-top {
    width: calc(100% - 40%);
  }

  .content {
    width: calc(100% - 40%);
  }

  /* <#if settings.sidebar_background?? && settings.sidebar_background!=''>
  .sidebar {
      background: url("${settings.sidebar_background!}") no-repeat center center fixed;
  }
  </#if> */
</style>



    <link rel="stylesheet" href="[/themes/theme-anatole/assets/dist/style.css?v=2.1.0](http://localhost:8090/themes/theme-anatole/assets/dist/style.css?v=2.1.0)" />
    <script src="[/themes/theme-anatole/assets/dist/main.iife.js?v=2.1.0](http://localhost:8090/themes/theme-anatole/assets/dist/main.iife.js?v=2.1.0)"></script>

    
  <meta name="description" content="21212121" />
<script async defer src="[/halo-tracker.js](http://localhost:8090/halo-tracker.js)" data-group="content.halo.run" data-plural="posts" data-name="ac38044b-a03e-4681-882e-9b155e255054"></script>
</head>
  <body>
    <div class="sidebar animated fadeInDown">
  <div class="logo-title">
    <div class="title">
      <img
        alt="Logo"
        class="inline-block"
        src=""
        style="width: 127px ;border-radius:50%"
      />
      <h3 class="!mt-3 !mb-0">
        <a href="[/](http://localhost:8090/)" title="xingzi">xingzi</a>
      </h3>
      <div class="description mt-2">
        <p class="description-text"></p>
      </div>
    </div>
  </div>
  <ul class="social-links mt-1">
  
</ul>

  <div class="footer">
    <a target="_blank" href="[#](http://localhost:8090/archives/1111#)">
      <a href="https://www.caicai.me/">Designed by CaiCai</a>
      <div class="by_halo">
        <a href="https://halo.run/" target="_blank">Proudly published with Halo</a>
      </div>
      <div class="footer_text">
        
      </div>
    </a>
  </div>
</div>

    <div class="main">
      <div class="page-top animated fadeInDown">
  <div
    id="nav"
    class="nav ml-[30px] mr-4 flex h-full flex-1 flex-nowrap items-center gap-6 overflow-x-auto whitespace-nowrap text-sm"
  >
    <div
      class="nav-item relative inline-flex h-full items-center text-black/70 transition-all hover:text-[#4786D6]"
    >
      <a
        href="[/](http://localhost:8090/)"
      >首页</a>
    </div>
    <div
      class="nav-item relative inline-flex h-full items-center text-black/70 transition-all hover:text-[#4786D6]"
    >
      <a
        href="[/archives/hello-halo](http://localhost:8090/archives/hello-halo)"
      >Hello Halo</a>
    </div>
    <div
      class="nav-item relative inline-flex h-full items-center text-black/70 transition-all hover:text-[#4786D6]"
    >
      <a
        href="[/tags/halo](http://localhost:8090/tags/halo)"
      >Halo</a>
    </div>
    <div
      class="nav-item relative inline-flex h-full items-center text-black/70 transition-all hover:text-[#4786D6]"
    >
      <a
        href="[/about](http://localhost:8090/about)"
      >关于</a>
    </div>
  </div>
  <div class="information gap-4">
    
    
    
    
  </div>
</div>

      <div class="content">
        
    <div class="animated fadeInDown m-[30px] mt-[20px] border-b border-gray-200">
  <div class="flex flex-col pb-3">
    <div class="flex flex-wrap items-end">
      <h3 class="text-xl font-medium leading-6 text-gray-900">1111</h3>
      
    </div>
    <div>
      
        <div class="post-info mt-2" x-data="upvote('post','content.halo.run','posts')">
          <div class="meta" x-data="{name:&#39;ac38044b-a03e-4681-882e-9b155e255054&#39;}">
            <div class="info">
              <i class="i-mdi-calendar-month-outline h-3 w-3"></i>
              <span>2023-08-21</span>
              <i class="i-mdi-eye h-3 w-3"></i>
              <span>13</span>
              <i class="i-mdi-comment-outline h-3 w-3"></i>
              <a href="[#comment_widget](http://localhost:8090/archives/1111#comment_widget)">0</a>
              <div
                class="inline-block cursor-pointer hover:text-red-700"
                x-bind:class="{'text-red-700': upvoted(name)}"
                x-on:click="handleUpvote(name)"
              >
                <i x-show="upvoted(name)" class="i-mdi-heart h-3 w-3"></i>
                <i x-show="!upvoted(name)" class="i-mdi-heart-outline h-3 w-3"></i>
                <span data-upvote-post-name="ac38044b-a03e-4681-882e-9b155e255054">0</span>
              </div>
              
              
            </div>
          </div>
        </div>
      
    </div>
  </div>
</div>

    <div class="post-page">
      <div class="post animated fadeInDown">
        <div id="post-content" class="post-content markdown-body"><p>21212121</p></div>
      </div>
      <div
        class="pagination flex items-center justify-between"
      >
        
        <a
          class="btn"
          role="navigation"
          href="[/archives/hello-halo](http://localhost:8090/archives/hello-halo)"
          title="Hello Halo"
        >
          下一篇
        </a>
      </div>
      <div id="comment_widget" style="margin: 30px">
        
      </div>
    </div>
  
      </div>
    </div>
  </body>
</html>`

**Comment by mengdalida** [comment]
![U(H151KTFAQ2A`U__O(O%B](https://github.com/halo-dev/halo/assets/104249502/eb5c40b1-f0d3-49af-b04d-f947d3caac03)

**Comment by Flionay** [comment]
我这里也遇到了这个问题，请问解决了吗

**Comment by ruibaby** [comment]
当前未复现此问题，且没有再收到类似的反馈，所以我将关闭此 issue。后续如果可以提供更多信息，可以重新提交 issue。

/close
