### ISSUE TITLE
管理员后台API设置未登录也可以修改

### ISSUE THREAD

**Issue by JarvisPongSky** [halo-dev/halo#445]
- [ ] BUG 反馈

![image](https://user-images.githubusercontent.com/53456132/71494573-094ba280-2883-11ea-9a04-3c2ffd6c1384.png)

不登录也可以修改，没有鉴权。刚刚测试随便后缀加了/test，导致后台登录不上。

**Comment by ruibaby** [comment]
@JarvisPongSky 恢复默认即可

**Comment by JarvisPongSky** [comment]
怕恶意操作，脚本一直乱改，这样子会导致管理员进不去。
建议是 登录后配置。

**Comment by ruibaby** [comment]
@JarvisPongSky 不会的 放心吧。此操作不涉及接口调用。通过 vuex 管理在浏览器端的。你多虑了。
