### ISSUE TITLE
插件升级的问题

### ISSUE THREAD

**Issue by Crany-web** [halo-dev/halo#4450]
### 你当前使用的版本

halo:2.8.0

### 描述一下此特性

希望halo能检查已安装的插件是否有更新，如果有更新用户也执行了更新动作，那么就拉取相对应的github项目中的jar包接着升级插件，这样会比较方便一点，否则平常升级插件，一个一个的都得重复手动更新着实不太方便

**Comment by ruibaby** [comment]
/triage duplicate

see https://github.com/halo-dev/halo/issues/3913
