### ISSUE TITLE
搜索引擎优化：当标题中存在英文单词时，单词不写全的情况下搜索不到

### ISSUE THREAD

**Issue by lan-yonghui** [halo-dev/halo#4455]
### 是什么版本出现了此问题？

2.8.0

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式部署？

Docker Compose

### 在线站点地址

https://kb.fit2cloud.com

### 发生了什么？

当标题中存在英文单词时，单词不写全的情况下搜索不到，必须输入完整的英文单词才可以检索到。希望可以优化检索时的分词算法，使检索使用更加便捷。。

### 附加信息

![image-2023-8-17_11-33-0](https://github.com/halo-dev/halo/assets/81747598/74bea8c7-f7b5-48e8-bda2-60a3dadf8662)
![image-2023-8-17_11-33-29](https://github.com/halo-dev/halo/assets/81747598/5cf1627d-055f-4b08-83fc-56c16e2c3729)

**Comment by JohnNiang** [comment]
可以试试这样的语法：`Communica*`或者 `title:Communitca*`。

**Comment by lan-yonghui** [comment]
这样是不是对使用者的要求太高了？使用的人可能只是一些小白，还需要我们把这种语法做个说明提示，告知他们如何使用😭

**Comment by lan-yonghui** [comment]
nice

**Comment by JohnNiang** [comment]
Hi @jyx-fyh ，感谢反馈！

目前， Lucene 似乎只能处理一个关键字对应一个字段（content），所以默认情况下，只能搜索文章内容，后续我看能否再优化一下，保证可以搜索到所有字段，并且也能根据单个字段进行搜索。

**Comment by Rainsheep** [comment]
@jyx-fyh   可以使用下 https://github.com/Rainsheep/halo-plugin-meilisearch，已上架应用商店，极大的提升了搜索体验、精确度，可以使用空格分割关键字，使用要求低
