### ISSUE TITLE
增加全局背景图片

### ISSUE THREAD

**Issue by JarvisPongSky** [halo-dev/halo#446]
- [ ] 请求技术支持
希望可以加入全局背景图片，点缀下 ;)

**Comment by ruibaby** [comment]
@JarvisPongSky 哪里？

**Comment by JarvisPongSky** [comment]
![image](https://user-images.githubusercontent.com/53456132/71499218-85051980-289a-11ea-8c62-e6b19ede80c8.png)

希望可以在主题配置加个全局背景图片 :)

@ruibaby

**Comment by ruibaby** [comment]
@JarvisPongSky 你在自己的主题改改就好了

**Comment by JarvisPongSky** [comment]
![image](https://user-images.githubusercontent.com/53456132/71499350-0ceb2380-289b-11ea-8ced-0760db9d9999.png)

这里 改吗？

**Comment by ruibaby** [comment]
@JarvisPongSky 可以。不过貌似你可以在博客设置里面的自定义head加样式

**Comment by JarvisPongSky** [comment]
好的，我试下，谢谢 :)
