### ISSUE TITLE
Console 端评论根据用户搜索为空

### ISSUE THREAD

**Issue by LIlGG** [halo-dev/halo#4465]
### 是什么版本出现了此问题？

2.8.0

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 问题描述

当前 console 根据用户搜索时，返回的结果始终为空，如下所示：

<img width="1920" alt="image" src="https://github.com/halo-dev/halo/assets/31335418/7f6776f0-2385-48ca-bd09-429cdf40bdd7">

### 期望结果

根据用户搜索时，能够正确返回对应用户的评论

/area console
/kind bug

**Comment by ruibaby** [comment]
/assign @LIlGG 

应该是前端没有传 kind
