### ISSUE TITLE
建议默认错误模板中首页链接使用相对路径

### ISSUE THREAD

**Issue by wan92hen** [halo-dev/halo#4483]
### 你当前使用的版本

v2.8.0

### 描述一下此特性

建议该链接使用相对路径，避免没有正确配置站点地址时跳转到错误的链接。

https://github.com/halo-dev/halo/blob/42ef7265c70479d31751c8931f4bdbc42f0b60db/application/src/main/resources/templates/error/error.html#L124C1-L124C1

![image](https://github.com/halo-dev/halo/assets/27671436/ab37aacc-cede-40a3-b122-9848966c8c7e)

**Comment by GodlessLiu** [comment]
能否改成回到上一页地址？

**Comment by JohnNiang** [comment]
可以提供一下对应的错误日志么？没太明白具体是什么配置导致了什么样的问题。

**Comment by wan92hen** [comment]
> 可以提供一下对应的错误日志么？没太明白具体是什么配置导致了什么样的问题。

已完善 Issue 描述。

**Comment by wan92hen** [comment]
> 能否改成回到上一页地址？

也可以吧，但是感觉跟浏览器的回退功能有些重复了。

**Comment by ruibaby** [comment]
> 避免没有正确配置站点地址时跳转到错误的链接。

这种情况本身也属于异常情况，暂不考虑更改，目前也没有再收到类似反馈。

/close
