### ISSUE TITLE
主题设置无法成功应用

### ISSUE THREAD

**Issue by 7tianv** [halo-dev/halo#4492]
### 是什么版本出现了此问题？

2.8

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker Compose

### 在线站点地址

none

### 发生了什么？

安装了多个主题，想从A主题切换到B主题，提示成功切换，但主题设置界面还是A主题，前端也是A主题。
将A主题内的设置更改，提示更改成功，刷新之后依旧是更改之前的设置。
删除A主题，删除成功了，但主题设置依旧显示是A主题
将博客备份，删除docker容器在恢复备份，问题依旧

**Comment by ruibaby** [comment]
根据你提供的步骤无法复现，是否有设置反向代理或者 CDN 之类的？可以检查一下缓存设置。

/triage needs-information

**Comment by 7tianv** [comment]
> 根据你提供的无法恢复的步骤，是否有设置反向代理或者CDN之类的？可以检查一下服务器设置。
> 
> /分类需求信息

根据教程设置了反代并且开启了CDN，但应该和这些无关，多次删除容器并重建，现在的情况是前端可以更改其他主题，但后台主题设置界面依旧卡在A主题，将A主题删除，重装，重置，更换版本都不行
此前的操作有：
将halo博客从2.6版本升级到2.8版本
更新了全部插件
更新了主题并安装了一些新主题
卡住的A主题为theme-butterfly，将该主题从2.0.2升级到2.0.5版本

**Comment by ruibaby** [comment]
你通过服务器 ip 访问 Console 进行这些操作试试，就知道和你的 CDN 是否有关了。
