### ISSUE TITLE
附件管理可添加外部链接

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#45]
增加附件管理可添加外部链接的特性

**Comment by PuShaoWei** [comment]
加一行判断吧 😄

**Comment by ruibaby** [comment]
@PuShaoWei 什么判断

**Comment by PuShaoWei** [comment]
就是如果选用外部的静态资源上传方式，在`"<img src="`标签这里，加上协议头`https://` 或者这里预留个字段把，不然现在附件管理 如果我选了七牛的，那里图都是裂的，但是地址是有效的

**Comment by PuShaoWei** [comment]
![image](https://user-images.githubusercontent.com/18391791/50053064-5160c100-0169-11e9-9316-b394c2e62970.png)
![image](https://user-images.githubusercontent.com/18391791/50053067-63426400-0169-11e9-9bcb-2f67932532d5.png)

![image](https://user-images.githubusercontent.com/18391791/50053081-a0a6f180-0169-11e9-8aa4-df6343a4acbf.png)

**Comment by ruibaby** [comment]
可以的啊，预留了的，必须添加http或者https，另外缩略图要在七牛配置策略填上去，晚点我出个教程

**Comment by PuShaoWei** [comment]
手动加上https 就可以了，策略那里简单说下嘛

**Comment by ruibaby** [comment]
这个不好说明呀，要不你加我个QQ？ 我截图给你看看？ 709831589

**Comment by PuShaoWei** [comment]
加了

**Comment by ruibaby** [comment]
由于目前正在开发 V1 版本，所以该 issue 已经不适用于新版本，所以先关闭了。
