### ISSUE TITLE
网页不支持业内跳转

### ISSUE THREAD

**Issue by JarvisPongSky** [halo-dev/halo#450]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x ] 添加新的特性或者功能

![image](https://user-images.githubusercontent.com/53456132/71540566-5b75ec00-2987-11ea-8aab-e4192e21b580.png)

现在不支持业内跳转功能。

地址：https://www.pongsky.com/archives/Nginx%20%E9%80%9A%E5%85%B3%E6%94%BB%E7%95%A5#Nginx%E9%85%8D%E7%BD%AE%E9%80%89%E9%A1%B9

**Comment by ruibaby** [comment]
https://www.pongsky.com/archives/Nginx%20%E9%80%9A%E5%85%B3%E6%94%BB%E7%95%A5#nginx%E9%85%8D%E7%BD%AE%E9%80%89%E9%A1%B9
