### ISSUE TITLE
Session 过期时间不符合预期

### ISSUE THREAD

**Issue by LiuOcean** [halo-dev/halo#4503]
### 是什么版本出现了此问题？

2.8.0

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 在线站点地址

https://liuocean.com

### 发生了什么？

我这里几乎每天都要登录很多次，但是看 cookie 中 session 过期时间似乎很久，目前的表现不太符合预期

![image](https://github.com/halo-dev/halo/assets/20659474/65407efa-2dff-44ac-93af-405c6ea54230)

我在  Arc 和 Chrome 两个浏览器上，都复现了这个异常

**Comment by JohnNiang** [comment]
从图中看，SESSION 的过期时间为当前 Session，也就是说关闭浏览器后，将需要重新登录。

请参考：<https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#attributes:~:text=If%20unspecified%2C%20the%20cookie%20becomes%20a%20session%20cookie.%20A%20session%20finishes%20when%20the%20client%20shuts%20down%2C%20after%20which%20the%20session%20cookie%20is%20removed.>

/kind support

**Comment by LiuOcean** [comment]
原来如此。谢谢。
