### ISSUE TITLE
图片阿里oss访问失败

### ISSUE THREAD

**Issue by zhongzhouping** [halo-dev/halo#451]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x ] [Halo 使用文档](https://halo.run/docs)
- [ ] [Halo 论坛](https://bbs.halo.run)
- [ x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [ x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x ] BUG 反馈
- [ ] 添加新的特性或者功能
- [ x] 请求技术支持

部署方式：docker(ruibaby/halo:latest)

配置号阿里的oss后，可以上传成功，但是无法预览，查看了一下控制台：
博客内的地址为：http://www.zhongzp.com/admin/alioss.zhongzp.com/image_1577534371469.png 
但是实际上我图片地址为：alioss.zhongzp.com/image_1577534371469.png 
控制台报错如下：

![image](https://user-images.githubusercontent.com/43698606/71543476-16b17b80-29ae-11ea-8d7e-ea294a58aed6.png)

**Comment by ruibaby** [comment]
绑定域名那里加上 https:// 或者 http://

**Comment by zhongzhouping** [comment]
好的，谢谢，加上http后可以了，非常感谢
