### ISSUE TITLE
在文章列表界面。希望赛选项能设置成按照文章的更新时间来操作。

### ISSUE THREAD

**Issue by isrun** [halo-dev/halo#4513]
### 描述一下此特性

![5312edbeca2de412be57c1aeb96b77a](https://github.com/halo-dev/halo/assets/118182481/f4a7136b-4141-42a4-bf4e-fbc96867dce6)
在文章列表界面。希望赛选项能设置成按照文章的更新时间来操作。有些文章是很久之前创建和发布的。修改后想查看更新的文章。需要翻页很多。希望能够根据跟新时间来进行排序。  谢谢大佬。

**Comment by ruibaby** [comment]
/area core

应该需要后端的改动。
