### ISSUE TITLE
文章表格解析失败

### ISSUE THREAD

**Issue by zhongzhouping** [halo-dev/halo#452]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [ ] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

部署方式：docker部署（ruibaby/halo:latest， 2019年12月18号部署)
表格部署后显示错误
显示如下：
![image](https://user-images.githubusercontent.com/43698606/71543981-5da26f80-29b4-11ea-856d-27845203ad31.png)

博客地址：http://www.zhongzp.com/archives/redis-sds

**Comment by ruibaby** [comment]
| C字符串                               | SDS                                        |
 | ------- | ------- |
 | 获取字符串长度时间复杂度为O(N)        | 获取字符串长度时间复杂度为O(1)             |  | API是不安全的，可能导致缓存区溢出 | API是安全的，不会造成缓存区溢出 |
 | 修改字符串长度必然进行N次内存重新分配 | 修改字符串的长度N次最多进行N次内存重新分配 |
 | 只能保存文本数据                      | 可以保存二进制数据                         |
 | 可以使用所有<string.h>库中的函数      | 可以使用一部分<string.h>库中的函数         |

我这边没有出现问题。

**Comment by zhongzhouping** [comment]
这个是和浏览器有关系嘛？还是有什么其他原因，我的事谷歌浏览器。

**Comment by ruibaby** [comment]
把你写的截个图

**Comment by zhongzhouping** [comment]
我用Safari浏览器打开也是一样的，源码如下：
![image](https://user-images.githubusercontent.com/43698606/71544398-fdaec780-29b9-11ea-8d9a-a6bf9bc94b3d.png)

编辑的时候预览也是可以的额
![image](https://user-images.githubusercontent.com/43698606/71544401-056e6c00-29ba-11ea-9d68-71984db85bef.png)

**Comment by ruibaby** [comment]
把你表格的格式和上面的内容换个行。

你使用的版本编辑器支持一个换行即解析为换行符，但是后端渲染需要两个换行才能解析为一个换行，这是 markdown 的标准规范。

不过这个问题已经在新版中修复了，等待下一个版本发布。

**Comment by zhongzhouping** [comment]
可以了，非常感谢，没注意到这里，感谢！
