### ISSUE TITLE
java -jar 后只出现一个主页面

### ISSUE THREAD

**Issue by sukai-cheng** [halo-dev/halo#453]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [ ] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [x] 请求技术支持

**Comment by ruibaby** [comment]
@sukai-cheng 请描述清楚

**Comment by sukai-cheng** [comment]
1.查看日志发现这个错误:
2019-12-28 21:45:06.095 ERROR 2768 --- [ XNIO-1 task-14] r.h.a.controller.core.CommonController   : Error path: [/error], status: [404 NOT_FOUND]
2.截图如下，而且没有登陆注册界面，感觉就是个html
不好意思，网太卡，图片加载太慢

**Comment by sukai-cheng** [comment]
<img width="1650" alt="图片" src="https://user-images.githubusercontent.com/35868545/71544561-1ddf8600-29bc-11ea-9d0e-e8334a15c7f4.png">

**Comment by sukai-cheng** [comment]
<img width="1394" alt="图片" src="https://user-images.githubusercontent.com/35868545/71544575-38b1fa80-29bc-11ea-8daa-4548bce43978.png">

**Comment by ruibaby** [comment]
就是这样的啊

**Comment by ruibaby** [comment]
你访问到这个页面之前不是有初始化吗？

**Comment by sukai-cheng** [comment]
我直接打开http://1xx.xx.xxx.xx:8090/就只出现了这个页面，我之前也java -jar过，但是不是这样的，一开始会有一个登陆注册页面，进去之后还会有后台管理什么的... @ruibaby

**Comment by ruibaby** [comment]
那你先清理掉 ~/.halo 重新运行就有了。

每次重启都要初始化是什么设定？

**Comment by ruibaby** [comment]
对了，/admin 是管理页面。

**Comment by sukai-cheng** [comment]
ruibababy,请教一下怎么清理啊

**Comment by ruibaby** [comment]
rm -rf ~/.halo

**Comment by sukai-cheng** [comment]
![image](https://user-images.githubusercontent.com/35868545/71544838-afe88e00-29be-11ea-85a0-d62c415e4f4d.png)

**Comment by sukai-cheng** [comment]
好了，没仔细看，我眼瞎了
![image](https://user-images.githubusercontent.com/35868545/71544885-503eb280-29bf-11ea-8ed5-e32f41a542de.png)
谢谢您

**Comment by sukai-cheng** [comment]
我密码和用户名忘了

**Comment by ruibaby** [comment]
@sukai-cheng 删掉 .halo 文件夹重启是最快的方法
