### ISSUE TITLE
对于发布文章默认生成地址的需求

### ISSUE THREAD

**Issue by xiaozhangStudent** [halo-dev/halo#4537]
### Your current Halo version

2.8

### Describe this feature

对于发布文章的时候我们往往填写文章名称后就会自动生成拼音的文章链接，但是如果我不填名字直接发布就可以得到随机的数字，然后在前往文章重新发布修改名字，但是这样觉得有点麻烦希望可以将文章链接后面的刷新按钮更改为，点击变成随机数字，或者某种算法生成的数字，谢谢！！

**Comment by ruibaby** [comment]
/triage duplicate

see https://github.com/halo-dev/halo/issues/1790
