### ISSUE TITLE
图库功能闪屏

### ISSUE THREAD

**Issue by zhuozhm** [halo-dev/halo#4538]
### 你当前使用的版本

2.9

### 描述一下此特性

图库->修改->编辑分组表单页面，不管是点击提交还是取消，都会闪一下出现新建分组表单页面

**Comment by LIlGG** [comment]
未能在本地进行复现。如果不是最新版本的图库插件，建议升级之后再进行尝试，可能与 https://github.com/halo-sigs/plugin-photos/issues/12 有关。

**Comment by ruibaby** [comment]
如果没有后续动态，我将关闭此 issue。

/close
