### ISSUE TITLE
手机上博客的图片无法放大和缩小，看起来很累

### ISSUE THREAD

**Issue by sukai-cheng** [halo-dev/halo#454]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [ ] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [x] 请求技术支持

**Comment by sukai-cheng** [comment]
手机上的图片无法拉大看

**Comment by ruibaby** [comment]
@sukai-cheng 有各种各样的图片放大插件。想办法自己改一下主题。或参考目前已有的主题。
