### ISSUE TITLE
新功能建议:增加登录用户二步验证（Authenticator)

### ISSUE THREAD

**Issue by Feicus** [halo-dev/halo#4541]
### 你当前使用的版本

halo-2.8.0

### 描述一下此特性

希望在halo2.x版本中增加 两步验证的功能（可参考Alist的两步验证），具体描述如下：

1. 可以以插件或者是写在halo里面。在“用户”的旁边放置一个 是否开启两步验证 （默认：否）
如果为是，旁边出现一个 绑定 按钮
2. 开启后，出现QRcode或者是验证秘钥，通过下载的 Authenticator 可以进行 绑定
3. 绑定后，用户的标签会有个提示（已绑定两步验证）
4. 如果是已绑定，则可以进行解绑。
5. 如果强制关闭两步验证，会提示先解绑，或者是强制进行解绑。

---

也可以简单点，如果 开启两步验证，强制要求绑定，必须Authenticator软件绑定；如果 关闭 两步验证，强制解绑

---

7.在绑定过程中会遇到一个问题，不知道是否绑定成功？可以加一个验证码校验，校验通过才算是绑定。

### 附加信息

![image](https://github.com/halo-dev/halo/assets/30593919/2008e276-915e-4f14-994e-c2029800d448)

![GIF 2022-11-8 星期二 10-28-16](https://github.com/halo-dev/halo/assets/30593919/be278b10-0b04-4661-a5d2-61e334d5bda1)

![OAAOW`PU1}`3M4870O@_D$2](https://github.com/halo-dev/halo/assets/30593919/6585eda1-422a-46c4-b60a-8f67078417bd)

**Comment by JohnNiang** [comment]
/kind feature

Thanks for reaching out here!
