### ISSUE TITLE
（可能为偶发性）文章浏览页的Modal渲染层级异常

### ISSUE THREAD

**Issue by AccAutomaton** [halo-dev/halo#4542]
### 是什么版本出现了此问题？

<= 2.9.0

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker Compose

### 在线站点地址

https://blog.acautomaton.com

### 发生了什么？

> 我从2.5版本开始使用halo，当时已经有这个bug，但是直到2.9版本都没有被修复。因为奇怪如此显眼的bug居然没有人提及，我自己拉代码下来构建发现在本地的demo居然没有这个bug...（可能其他用户也没有）

当目录Modal位于标签Modal和分类目录Modal等之上时，下层的部分文本会被错误渲染：
![image](https://github.com/halo-dev/halo/assets/88975453/4542a4cc-dbca-42b7-8426-8864e06612d2)

例如：https://blog.acautomaton.com/archives/1688455921719

**Comment by ruibaby** [comment]
这似乎是主题的样式问题，已经在 https://github.com/halo-dev/theme-earth/pull/85 中修复，你可以尝试更新一下主题到最新版本。

/area theme
/kind support

**Comment by AccAutomaton** [comment]
确实是，没想到是主题的问题
