### ISSUE TITLE
Prevent basic authentication from popping up

### ISSUE THREAD

**Issue by JohnNiang** [halo-dev/halo#4547]
### Your current Halo version

2.10.0-SNAPSHOT

### Describe this feature

We may encounter a pop-up from browser while our session expires. This is not what we expected.

The main reason for popping up is the response header `WWW-Authenticate: Basic realm="Realm"`. I recommend never responding the header at any time.

/kind improvement
/area core

### Additional information

<img width="797" alt="image" src="https://github.com/halo-dev/halo/assets/16865714/04e82fe7-790c-4883-af0d-bf4bf1fd093d">

**Comment by longjuan** [comment]
之前在axios中做过配置：https://github.com/halo-dev/halo/issues/3213
但是插件和一些地方没有使用经过设置的axios，导致没带上请求头，我觉得应该推进这个：https://github.com/halo-dev/halo/issues/3979

**Comment by JohnNiang** [comment]
> 之前在axios中做过配置：#3213 但是插件和一些地方没有使用经过设置的axios，导致没带上请求头，我觉得应该推进这个：#3979

确实需要封装一个请求库，不过在出现 401 的情况下后端返回的 Header 中不应当包含 `WWW-Authenticate: Basic realm="Realm"`。
