### ISSUE TITLE
建议固定页面的保存按钮位置在页面显示区域

### ISSUE THREAD

**Issue by Snychng** [halo-dev/halo#4548]
### 你当前使用的版本

2.8.0

### 描述一下此特性

当前设置页面的保存按钮在最下面，每次设置完你都要拉到最下面才能点保存。我希望把那个保存按钮浮动设置到页面的可视范围的最下面，而不是页面正文底部

**Comment by Mrered** [comment]
同求

**Comment by Mrered** [comment]
这个功能还没添加吗？
