### ISSUE TITLE
运行一段时间后提示无权限访问

### ISSUE THREAD

**Issue by testnet0** [halo-dev/halo#4549]
### 是什么版本出现了此问题？

2.6

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker

### 发生了什么？

docker-compose启动的，过段时间发现没办法登录后台，提示无权限访问：
<img width="387" alt="image" src="https://github.com/halo-dev/halo/assets/18673513/166a0755-fc11-46fa-9215-df3f3274faf9">

**Comment by testnet0** [comment]
<img width="398" alt="image" src="https://github.com/halo-dev/halo/assets/18673513/bd8de4fc-48b4-433e-ac4d-d80a490233b3">
/actuator/globalinfo请求是正常的，其他路径都提示Access Denied，docker-compose重装升级都不行

**Comment by testnet0** [comment]
<img width="866" alt="image" src="https://github.com/halo-dev/halo/assets/18673513/18841d52-88cf-49ca-852d-8b0222cbd1b7">

**Comment by JohnNiang** [comment]
建议升级到最新版本（2.9）后再试试。

目前我们无法复现该问题。

/triage needs-information

**Comment by testnet0** [comment]
定位到问题了，登录的时候用户名不区分大小写，但是登入后台后权限判断会区分大小写，导致用户没办法正常使用

**Comment by ruibaby** [comment]
> 定位到问题了，登录的时候用户名不区分大小写，但是登入后台后权限判断会区分大小写，导致用户没办法正常使用

应该和 https://github.com/halo-dev/halo/issues/4372 是相同的问题。

**Comment by JohnNiang** [comment]
那我先临时解决一下因为大小写问题导致仍然能够登录的问题。

/assign
