### ISSUE TITLE
 问题:请问上传的图片的存放路径在哪里

### ISSUE THREAD

**Issue by sukai-cheng** [halo-dev/halo#455]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [ ] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [x] 请求技术支持
问题:请问上传的图片的存放路径在哪里

**Comment by sukai-cheng** [comment]
问题:请问上传的图片的存放路径在哪里

**Comment by guqing** [comment]
@sukai-cheng 在后台有配置，如果没有配置过其他存储方式默认存在服务器的home目录下的.halo文件夹中的upload里面

**Comment by sukai-cheng** [comment]
谢谢
