### ISSUE TITLE
使用 Docker 部署 用 Docker-compose 编排  报连接不上数据库 

### ISSUE THREAD

**Issue by dlx79** [halo-dev/halo#4550]
### 是什么版本出现了此问题？

2

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker

### 发生了什么？

![image](https://github.com/halo-dev/halo/assets/105104454/5586a599-3812-4ccf-80de-22d9973b8cc4)

**Comment by JohnNiang** [comment]
建议提供一下 docker-compose.yaml 配置。

/triage needs-information

**Comment by dlx79** [comment]
你好，我把docker-compose.yaml里面的数据库端口 3306 改了才连接不上，因为我本地 3306 已经被另外一个程序占用了 我把它停掉才能用， 还有一个问题就是我把这个项目部署到云服务器发现 2C 的 CPU 直接拉满了，这个对配置有要求么
















在 2023-09-05 00:12:34，"John Niang" ***@***.***> 写道：

建议提供一下 docker-compose.yaml 配置。

/triage needs-information

**Comment by JohnNiang** [comment]
Hi @dlx79 ，请看 <https://github.com/halo-dev/halo/issues/4539#issuecomment-1705894603>。

**Comment by dlx79** [comment]
1
