### ISSUE TITLE
halo的富文本编辑器能提供左边是图片，右边是文字的排版嘛,我想用ckeditor来实现，插件的console目录一定得是vue吗

### ISSUE THREAD

**Issue by pandatools** [halo-dev/halo#4554]
### Your current Halo version

2.8

### Describe this feature

halo编辑器能够提供对图片，文字的排版支持嘛，像文字环绕之类的

**Comment by ruibaby** [comment]
布局的需求可以关注：https://github.com/halo-sigs/richtext-editor/issues/30

集成外部编辑器的文档可查阅：https://github.com/halo-dev/halo/blob/main/console/docs/extension-points/editor.md

/triage duplicate
