### ISSUE TITLE
使用文档修改建议

### ISSUE THREAD

**Issue by le0zh0u** [halo-dev/halo#456]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [ ] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

昨天使用docker方式部署halo，在安装过程中发现了docker会在启动后自动关闭，排查发现是因为docker中的应用连接不到数据库导致。但是在文档中未找到相关的说明。
所以，需要在文档中做一下说明，如果是用docker方式，在application中关于数据库地址的配置需要调整成宿主机的访问ip才可以请求到。

**Comment by ruibaby** [comment]
抱歉给你带来的困扰，不过文档针对的是默认的 h2 数据库，并没有写 MySQL 相关的文档。

**Comment by le0zh0u** [comment]
我昨天的解决方式是：
1. 使用`ifconfig`命令找到`docker`的`inet`属性，
2. 在application中修改mysql的访问host为xxx.xx.x.1
这样就运行起来了。
