### ISSUE TITLE
[Future] 用户在网站评论之后，后台对于未处理的评论消息，可以选择开启消息提醒功能

### ISSUE THREAD

**Issue by xiaobai3310** [halo-dev/halo#4565]
### 你当前使用的版本

2.8.0

### 描述一下此特性

现在没有提示，也不知道有没评论，需要点进去看，进入主页就能知道有没未处理的评论消息就更方便了。

**Comment by guqing** [comment]
/triage duplicate

see https://github.com/halo-dev/halo/issues/4045

**Comment by xiaobai3310** [comment]
>

Received, thank you very much

**Comment by ruibaby** [comment]
已经有 PR 了：https://github.com/halo-dev/halo/pull/4527

有兴趣可以一起测试下。
