### ISSUE TITLE
我选择了Vno主题后，点击归档显示404，详细见如下

### ISSUE THREAD

**Issue by sukai-cheng** [halo-dev/halo#457]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [ ] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [ ] 添加新的特性或者功能
- [x] 请求技术支持

问题:
我选择了Vno主题后，点击归档显示404，请问如何自建模版？在Anatole是有效的？我是新手，这几天一下课就在搞这个，但是效率好低，求师兄不吝赐教，这是我的第一个博客
<img width="524" alt="图片" src="https://user-images.githubusercontent.com/35868545/71558692-eb538d00-2a90-11ea-8291-0b0bba0bfafa.png">
<img width="326" alt="图片" src="https://user-images.githubusercontent.com/35868545/71558696-f6a6b880-2a90-11ea-9e62-84c3ce209732.png">
<img width="288" alt="图片" src="https://user-images.githubusercontent.com/35868545/71558706-12aa5a00-2a91-11ea-8e74-93acc8d3f939.png">

**Comment by ruibaby** [comment]
@sukai-cheng Vno主题没有归档模板。
