### ISSUE TITLE
[Future] 使用备份插件设置好定时备份后，能否选择手动触发一次？

### ISSUE THREAD

**Issue by xiaobai3310** [halo-dev/halo#4581]
### 你当前使用的版本

2.9.1

### 描述一下此特性

现在配置远程备份，但是否能按照预想的备份，只有到了设置的时间才会知道，如果有问题，那么修改后只能下一次同步时间了。希望增加一个手动触发按钮，来测试自己的配置是没有的，且方便后面自己想偶尔手动备份一下也行。

**Comment by JohnNiang** [comment]
<img width="288" alt="image" src="https://github.com/halo-dev/halo/assets/16865714/e2112c37-00b2-4cf5-b29c-c09a5f4807aa">

/kind support

**Comment by xiaobai3310** [comment]
> <img alt="image" width="288" src="https:user-images.githubusercontent.com/16865714/266518305-e2112c37-00b2-4cf5-b29c-c09a5f4807aa.png">
> /kind support
perfect
