### ISSUE TITLE
[Feature] 调整配置选单 UI

### ISSUE THREAD

**Issue by LiuOcean** [halo-dev/halo#4582]
### Your current Halo version

2.9.1

### Describe this feature

当配置页比较多时，下方的滑动条非常不明显

![image](https://github.com/halo-dev/halo/assets/20659474/93cf4f77-9b14-4f09-ab3a-cee8a98cdc02)

可以考虑，超出范围的内容作为 drop down ？或者其他形式

**Comment by guqing** [comment]
感觉是缺少了可滚动的提示，比如在可滚动时在右侧添加指示器
<img width="129" alt="image" src="https://github.com/halo-dev/halo/assets/38999863/f18b8b1b-e616-42df-b53f-25482b3b80e8">
