### ISSUE TITLE
[Bug] 无法选择 Markdown 编辑器

### ISSUE THREAD

**Issue by LiuOcean** [halo-dev/halo#4583]
### 是什么版本出现了此问题？

 2.9.1

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 在线站点地址

https://liuocean.com

### 发生了什么？

![image](https://github.com/halo-dev/halo/assets/20659474/b9da4df4-2812-406e-846c-0e7ec72c3543)
![image](https://github.com/halo-dev/halo/assets/20659474/8ba79604-9d19-4dfc-ada0-b198a826bfe8)

ByteMD 仍然在，但是无法选中默认编辑器，StackEdit 也不在下拉列表中

尝试过卸载 ByteMD 和 StackEdit 插件，重新安装后，问题依然存在

**Comment by ruibaby** [comment]
文章在保存之后不支持切换到其他不同类型的编辑器。默认编辑器属于富文本，不是 Markdown 格式。如果允许切换，那么将出现格式问题。

**Comment by LiuOcean** [comment]
嗯， 这个能理解，但是新建文章时，StackEdit 不在下拉列表中是为什么呢？

**Comment by ruibaby** [comment]
> 嗯， 这个能理解，但是新建文章时，StackEdit 不在下拉列表中是为什么呢？

如果是启用了插件但是在 Console 这边没有任何效果，可能是加载 bundle.js 的问题，你可以观察一下在启动插件和停止插件的时候，bundle.js 尾部的参数是否发生了变化。

<img width="880" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/a853f4d1-9f99-48de-9d39-62c3533c73cc">

**Comment by LiuOcean** [comment]
我尝试清理了一下 cookie 和 cache 后，重新安装插件就都好啦。 感谢回复。

**Comment by ruibaby** [comment]
> 我尝试清理了一下 cookie 和 cache 后，重新安装插件就都好啦。 感谢回复。

启动或者停止某个插件之后还是用的旧的 bundle.js 其实是有问题的。

我重新打开，看看有没有其他人有类似的问题。

/reopen

**Comment by ruibaby** [comment]
应该已经在 https://github.com/halo-dev/halo/pull/4591 中修复。

/close
