### ISSUE TITLE
希望能自定义后台路径，文章界面显示用户昵称

### ISSUE THREAD

**Issue by xiaofengjue** [halo-dev/halo#4584]
### 你当前使用的版本

2.8

### 描述一下此特性

后台登录地址不能自定义路径了，文章页面就显示登录名，一般来说都是显示用户昵称的，怎么能把登录名直接这么暴露出来呢， 这2.X的版本安全性做的还没1.X好，感觉像是生怕脚本小子找不到后台路径找不到用户名去爆破一样。

**Comment by ruibaby** [comment]
即便后台地址可以修改，登录的接口（/login）还是固定不变的，并且登录目前已经做了限流处理。

前台显示用户名的问题可以向主题提交 issue 。

/kind support
