### ISSUE TITLE
升级后插件开发，开发修改后不生效了，需要每次卸载了重新安装才会生效

### ISSUE THREAD

**Issue by hlovingness** [halo-dev/halo#4585]
### 是什么版本出现了此问题？

2.9

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker

### 发生了什么？

本地开发插件，升级到github最新分支后，修改console代码不生效，之前是可以生效的，这次死活不生效

**Comment by ruibaby** [comment]
我也复现了这个问题，开发环境不应该缓存 bundle.js

cc @guqing 

/reopen
/kind improvement

**Comment by guqing** [comment]
临时解决方案：在开发模式下打开浏览器控制台将disable cache勾选上开发
