### ISSUE TITLE
希望能为改动了 api 模块的 PR 推送 maven 依赖

### ISSUE THREAD

**Issue by guqing** [halo-dev/halo#4590]
### Your current Halo version

latest

### Describe this feature

如果为改动了 api 模块的 PR 推送依赖便于在插件中引入进行同步开发或验证，如果没有这样的功能可能需要改插件的依赖为 jar lib 比较麻烦

### Additional information

/kind feature
/area core

**Comment by JohnNiang** [comment]
建议只向发布分支推送，而不是给每个 PR 都推送。

目前如果想要测试 PR，可直接执行 `./gradlew publishToMavenLocal`，并在插件中配置 `mavenLocal()` repositories 即可。

**Comment by guqing** [comment]
> 建议只向发布分支推送，而不是给每个 PR 都推送。
> 
> 目前如果想要测试 PR，可直接执行 `./gradlew publishToMavenLocal`，并在插件中配置 `mavenLocal()` repositories 即可。

貌似也行，忽略了这一点
