### ISSUE TITLE
在后台编辑的表格前端页面展示时仅展示横线，不展示竖线

### ISSUE THREAD

**Issue by xueqidove** [halo-dev/halo#4595]
### 是什么版本出现了此问题？

V2.9.1

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 在线站点地址

公网demo环境地址

### 发生了什么？

后端编辑表格如下所示：
<img width="469" alt="image" src="https://github.com/halo-dev/halo/assets/60059766/44dde933-ddd5-4f5e-a3d7-677233d37f6b">

前端展示表格如下所示：
![image](https://github.com/halo-dev/halo/assets/60059766/e1f665bf-9d6b-4d95-b85a-99344dc99470)

**Comment by ruibaby** [comment]
目前编辑器输出的文档都是没有样式的 HTML 文本，意味着所有内容的样式都基于模板提供的样式。如果有这样的需求，建议自行修改主题样式或者向具体主题反馈。

/kind support

**Comment by ruibaby** [comment]
/triage duplicate

see https://github.com/halo-dev/halo/issues/2929

/close
