### ISSUE TITLE
建议添加文章自定义发布时间功能

### ISSUE THREAD

**Issue by chakid** [halo-dev/halo#46]
建议添加文章自定义发布时间功能啦，可以方便排序

**Comment by Chakid** [comment]
好的，辛苦！

**Comment by ruibaby** [comment]
@Chakid 以添加该特性，https://github.com/ruibaby/halo/commit/90a53dcf9cb5f1ecf160a090d57f0baae34437bd

**Comment by JohnNiang** [comment]
Reopen for `halo v1`.

**Comment by ruibaby** [comment]
已完成
