### ISSUE TITLE
富文本框插入图片

### ISSUE THREAD

**Issue by fengzhongsikao** [halo-dev/halo#4601]
### What is version of Halo has the issue?

halo2.9

### What database are you using?

H2

### What is your deployment method?

Docker

### What happened?

当windows的显示设置缩放为150%时，插入图片会超出宽度
![image](https://github.com/halo-dev/halo/assets/118974220/239c63e3-c57d-4b8e-890a-0a22f8f34497)、
---
***
***
不知道以后会不会适配一下

**Comment by JohnNiang** [comment]
个人认为这里设置成为 150% 超出屏幕是正常的。否则和 100% 没啥区别，都不知道是否正确设置了。

另外，图片宽度设置成 150% 的场景是什么呢？

**Comment by fengzhongsikao** [comment]
原来如此，不过这也影响不大。不是图片设置为150%，而是win10系统屏幕的缩放
