### ISSUE TITLE
2.9版本安装后，直接新建分类失败，无法新建网站分类

### ISSUE THREAD

**Issue by CoffinLove** [halo-dev/halo#4606]
### 是什么版本出现了此问题？

2.9

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式部署？

Docker Compose

### 发生了什么？

![image](https://github.com/halo-dev/halo/assets/39045932/563ced01-9ac6-41d1-b5a2-08fe81bc5b48)

**Comment by JohnNiang** [comment]
Thanks for reaching out here!

输入新的分类后，试试按回车键看能否创建出新的分类。

/triage needs-information
