### ISSUE TITLE
主题PandaPRO最新版本安装了评论插件,但是文章页面没有评论输入框

### ISSUE THREAD

**Issue by flyGetHu** [halo-dev/halo#4611]
### 是什么版本出现了此问题？

2.9

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Fat Jar

### 发生了什么？

如题,本地开发,运行后安装主题,评论插件,但是文章页面没有展示评论的输入框
![image](https://github.com/halo-dev/halo/assets/33747047/3d98ecc6-66bd-4d7d-bb94-a17593d20429)

**Comment by ruibaby** [comment]
如果是以 dev 的 profile 启动的话，需要检查一下插件是否正常启动。因为目前开发环境启动时，不能通过安装插件 jar 包的形式加载插件，请看：https://docs.halo.run/developer-guide/plugin/hello-world#%E8%BF%90%E8%A1%8C%E6%8F%92%E4%BB%B6

关于在开发环境通过 jar 加载插件也已经准备支持：https://github.com/halo-dev/halo/pull/4589

/kind support

**Comment by flyGetHu** [comment]
我将：https://github.com/halo-dev/halo/pull/4589 合并到我本地开发分支,解决了这个问题
