### ISSUE TITLE
[Bug] 发布文章失败

### ISSUE THREAD

**Issue by LiuOcean** [halo-dev/halo#4612]
### 是什么版本出现了此问题？

 2.9.1

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 在线站点地址

https://liuocean.com

### 发生了什么？

发布文章虽然弹出发布成功的 UI，但是文章状态依然是未发布，如果将旧的文章调整为未发布，再手动点击发布，这篇文章后续也无法正常发布

9 月 14 日时，发布功能是好的，这两天升级了 halo-theme-hao 到 1.3.7，但我尝试降级到 1.3.6，问题仍然会出现

相关日志截图如下：

<img width="874" alt="image" src="https://github.com/halo-dev/halo/assets/20659474/63d79e4d-2c08-4b69-829c-e5e0b9d0d7ce">

**Comment by ruibaby** [comment]
能提供一个可以复现的步骤吗？根据当前的描述我没有复现成功。

/triage needs-information

**Comment by LiuOcean** [comment]
没找到如何触发这个问题… 尝试降级一些主题和插件，问题仍然存在，有点头疼。 

还有其他办法可以排查吗？

**Comment by LiuOcean** [comment]
https://github.com/RickyGu777/halo-plugin-publish

感谢 Ryan 的支持， 这个问题由于这个发布插件导致的。
