### ISSUE TITLE
markdown里无法插入视频

### ISSUE THREAD

**Issue by ConstStar** [halo-dev/halo#4616]
### 是什么版本出现了此问题？

2.9.1

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式部署？

Docker Compose

### 在线站点地址

https://blog.conststar.cn

### 发生了什么？

markdmarkdown中无法插入视频文件
stackEdit和dyteMD编辑器都试过，通过链接直接打开视频文件正常播放，通过默认编辑器视频文件也正常播放
主题:Earth

### 附加信息

![image](https://github.com/halo-dev/halo/assets/42526758/9b835b39-81d8-41e9-8923-c781dd2fa718)

**Comment by ruibaby** [comment]
/triage duplicate

应该是编辑器过滤了 html 标签，相关 issue：https://github.com/halo-sigs/plugin-bytemd/issues/11

/close
