### ISSUE TITLE
说几个特别影响halo作者编辑体验的地方，希望halo能够更好！

### ISSUE THREAD

**Issue by baoyu0** [halo-dev/halo#4625]
### 你当前使用的版本

2.9.1

### 描述一下此特性

halo忠实用户，感谢官方工作人员的贡献，感谢开发人员的辛勤付出！！！

# 几点建议

### 1. 关于登录会话失效问题（紧急需解决）：
建议在Halo博客的后台登录界面中引入会话超时设置选项，以允许用户根据自身需求自定义会话超时时间。这一改进将显著提升用户体验，特别是在编辑和管理博客内容时。

### 2. 编辑面板背景模式切换（适中，期待近期解决）：
建议添加主题切换功能，允许用户在明亮和暗黑主题之间切换，以满足不同用户的视觉偏好。这一改进将提高编辑面板的可用性和舒适性。

### 3. Halo后台文件导出为Markdown备份的需求（必要但非紧急；期望在halo3.0前解决）：
建议在Halo博客的后台管理界面中引入文件导出功能，使用户能够将博客内容以Markdown格式导出到本地，从而提供备份和安全性。这有助于用户维护其博客数据的完整性和可靠性。

### 4. 优化资源利用和性能（非紧急但期待官方支持；提高博客性能和效率）：
建议对Halo博客软件进行性能和资源利用的优化工作，以确保博客能够在较低硬件配置下运行，提高响应速度。这包括减少内存和CPU占用、改进数据库查询效率和优化缓存策略等方面。通过此优化，用户可以在各种环境中流畅运行博客，并提供更好的用户体验

**Comment by ruibaby** [comment]
1. 确实需要优化。
2. 这个问题属于不紧急且比较费时的功能，Console 如果需要实现完整的主题切换需要不少的开发量。
3. 几个问题：
    1. 目前 Halo 2 的默认编辑器并不是 Markdown 格式，而是富文本（HTML），应该如何导出。
    2. 如果导出文档仅仅是为了数据安全，那么直接使用系统自带的备份可能会更好。
    3. 如果本身就使用 Markdown 发布文章，或许可以直接在本地编写 Markdown，然后发布到 Halo，可以使用：https://github.com/halo-sigs/vscode-extension-halo
    4. 此功能我推荐使用插件实现，目前文章的操作菜单已经支持扩展：<https://github.com/halo-dev/halo/pull/4452>
4. 这是一个持续优化的过程。

感谢反馈。

**Comment by baoyu0** [comment]
# 无法登录Halo插件

## 问题描述

使用vscode-extension-halo插件时,按照说明配置了站点、用户名和密码,但登录始终失败。

## 重现步骤

1. 在VS Code插件市场安装vscode-extension-halo
2. 在设置中配置:
   - 站点:https://example.com/ (不包含/console)  
   - 用户名:myusername
   - 密码:mypassword
3. 存储策略选择"本地"
4. 尝试登录,但一直显示登录失败

## 环境信息

- 操作系统:Windows 10
- VS Code版本:
版本: 1.82.2 (user setup)
- 插件版本:最新版

## 尝试过的解决方案

- 确认站点、用户名和密码正确
- 尝试过重新启动VS Code
- 尝试重新安装插件

## 补充信息

我参考了插件的使用文档,但没有看到特殊的登录要求。所以不清楚具体是什么原因导致无法登录。

如果需要我提供任何额外的信息来协助分析这个问题,请告知。

非常感谢!

**Comment by JohnNiang** [comment]
Hi @baoyu0 ，我们推荐创建一个[新的 Issue](https://github.com/halo-dev/halo/issues/4651) 来讨论[这个问题](https://github.com/halo-dev/halo/issues/4625#issuecomment-1731551994)。请看这里：<https://github.com/halo-dev/halo/issues/4651>。

**Comment by ruibaby** [comment]
> 关于登录会话失效问题

在 https://github.com/halo-dev/halo/pull/4949 中已经优化，目前会在文章编辑的时候定时请求 health 接口以保持登录会话。

> 优化资源利用和性能

在 2.11.0 中使用了 OpenJ9 作为运行容器，内存占用有显著优化，请看：https://github.com/halo-dev/halo/pull/4896

**Comment by ruibaby** [comment]
>  Halo后台文件导出为Markdown备份的需求

现在已经有了一个导出文章的插件：https://www.halo.run/store/apps/app-vWbpZ

**Comment by ruibaby** [comment]
> 编辑面板背景模式切换（适中，期待近期解决）

请关注：https://github.com/halo-dev/halo/issues/2288

我将关闭此 issue，后续提交 issue 建议分开提交，一个 issue 中包含多条内容会让我们很难管理。

/close
