### ISSUE TITLE
初始化完成后数据库中的中文是乱码

### ISSUE THREAD

**Issue by zhaohaao131** [halo-dev/halo#4629]
### 是什么版本出现了此问题？

2.9.1

### 使用的什么数据库？

MySQL 5.7

### 使用的哪种方式部署？

Docker Compose

### 发生了什么？

Docker Compose部署，使用外部的mysql，初始化完成后数据库中的中文是乱码
数据库创建代码是：create database halo character set utf8mb4 collate utf8mb4_bin;

**Comment by ruibaby** [comment]
建议提供乱码的截图。

/triage needs-information

**Comment by zhaohaao131** [comment]
![image](https://github.com/halo-dev/halo/assets/11420586/b3456ec1-2ae2-470c-b04e-d3952e3e92fb)
![image](https://github.com/halo-dev/halo/assets/11420586/12093b5d-ea6d-41ce-87dc-6f5146924384)

**Comment by ruibaby** [comment]
请问界面上有任何异常吗？这个 data 字段存储的是二进制，可能因为插件工具的不同而有差异。

**Comment by ruibaby** [comment]
如果没有后续动态，我将关闭此 issue。后续有问题可以随时重新打开或者提交新 issue。

/close
