### ISSUE TITLE
控制台提示：加载插件入口文件失败!

### ISSUE THREAD

**Issue by PulSe-kun** [halo-dev/halo#4630]
### 是什么版本出现了此问题？

2.9.1

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式部署？

Docker Compose

### 发生了什么？

从2.8升级到2.9.1版本，进入后台，发现“加载插件入口文件失败”的提示；
F12，发现是bundle.jss/bundle.css 报错，目前不太清楚为什么会出现这样的错误。

### 附加信息

![Snipaste_2023-09-19_13-56-09](https://github.com/halo-dev/halo/assets/66857592/31c8fe33-b67b-44e2-986c-295f19c0923b)
![Snipaste_2023-09-19_13-56-27](https://github.com/halo-dev/halo/assets/66857592/7047bacc-10e3-4d71-b03b-c58f735e9052)

**Comment by ruibaby** [comment]
我在你网站注册了一个账号看了下，这似乎是 Nginx 给出的 404，建议检查一下 Nginx 的规则。

/kind support

<img width="1135" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/8add3cc8-aa13-466d-8096-e6f6b827176b">

**Comment by PulSe-kun** [comment]
> 我在你网站注册了一个账号看了下，这似乎是 Nginx 给出的 404，建议检查一下 Nginx 的规则。
> 
> /kind support
> 
> <img alt="image" width="1135" src="https://user-images.githubusercontent.com/21301288/268857694-8add3cc8-aa13-466d-8096-e6f6b827176b.png">



> 我在你网站注册了一个账号看了下，这似乎是 Nginx 给出的 404，建议检查一下 Nginx 的规则。
> 
> /kind support
> 
> <img alt="image" width="1135" src="https://user-images.githubusercontent.com/21301288/268857694-8add3cc8-aa13-466d-8096-e6f6b827176b.png">

谢谢，经过排查 ，是我已经设置过nginx防盗链造成的，我把相关代码注释掉就正常了

**Comment by PulSe-kun** [comment]
谢谢，经过排查 ，是我已经设置过nginx防盗链造成的，我把相关代码注释掉就正常了

**Comment by PulSe-kun** [comment]
> 我在你网站注册了一个账号看了下，这似乎是 Nginx 给出的 404，建议检查一下 Nginx 的规则。
> 
> /kind support
> 
> <img alt="image" width="1135" src="https://user-images.githubusercontent.com/21301288/268857694-8add3cc8-aa13-466d-8096-e6f6b827176b.png">

谢谢，经过排查 ，是我以前设置过nginx防盗链造成的，把相关代码注释掉就正常了
