### ISSUE TITLE
备份失败

### ISSUE THREAD

**Issue by jiahe-tan-u** [halo-dev/halo#4637]
### 是什么版本出现了此问题？

2.9

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker Compose

### 发生了什么？

点击创建备份备份失败

### 附加信息

![image](https://github.com/halo-dev/halo/assets/124785542/4aed42a5-c0a9-4704-80c6-bcdbf789b1a9)

**Comment by ruibaby** [comment]
/triage needs-information

请提供日志以供判断。

**Comment by JohnNiang** [comment]
需要把鼠标悬停在红色原点上，看看具体的错误信息。

**Comment by jiahe-tan-u** [comment]
![image](https://github.com/halo-dev/halo/assets/124785542/d4646914-ea5d-457b-adc8-46d91c622c09)
![image](https://github.com/halo-dev/halo/assets/124785542/2c8d0206-fb1c-4462-865d-9808c86da690)

**Comment by JohnNiang** [comment]
@jiahe-tan-u 目测是 Halo 的工作目录 Nginx 相关的目录导致无法备份。我建议：

1. 创建新的目录用于当做 Halo 的工作目录，例如：`./halo2`，并将以下目录 `attachments backups     db          indices     keys        logs        plugins     themes` 移动到 `./halo2`。
2. 修改 Docker compose 文件：

```diff
version: "3"

services:
  halo:
    image: halohub/halo:2.9
    container_name: halo
    restart: on-failure:3
    depends_on:
      halodb:
        condition: service_healthy
    networks:
      halo_network:
    volumes:
-     - ./:/root/.halo2
+     - ./halo2:/root/.halo2
```

**Comment by jiahe-tan-u** [comment]
感谢回答，已经不考虑这个问题了
