### ISSUE TITLE
使用StackEdit编写的链接（Markdown）无法在新窗口打开

### ISSUE THREAD

**Issue by youngledo** [halo-dev/halo#4640]
### 你当前使用的版本

2.9.0

### 描述一下此特性

我希望使用StackEdit编写的文章链接能使用新窗口打开，但每次都是当前窗口，也没找到有设置的地方。

**Comment by ruibaby** [comment]
Markdown 本身的链接语法就不支持设置 target，你期望的使用方式是？

/triage needs-information
/area plugin

**Comment by youngledo** [comment]
> Markdown 本身的链接语法就不支持设置 target，你期望的使用方式是？
> 
> /triage needs-information /area plugin

我也找了下资料，貌似markdown原生不支持。不过这个网友提供了一种方式：https://www.cnblogs.com/cforcnb/p/15568511.html

不过这个可能需要halo在生成页面的时候添加进去：
<img width="1113" alt="image" src="https://github.com/halo-dev/halo/assets/68590897/1ba2df0b-2051-4442-9bf8-d97e03e8d0ea">

**Comment by youngledo** [comment]
另外我发现，我在StackEdit窗口右边渲染出来的页面，点击链接是新窗口打开的。

**Comment by youngledo** [comment]
> 如果是要使用这样的 JS 去处理文章内容，那你在 Console 设置中设置就行了。
> 
> <img alt="image" width="857" src="https://user-images.githubusercontent.com/21301288/269859473-c9fb4980-df95-4b38-af7b-104a41e61613.png">

这个方式可行～

**Comment by youngledo** [comment]
> 如果是要使用这样的 JS 去处理文章内容，那你在 Console 设置中设置就行了。
> 
> <img alt="image" width="857" src="https://user-images.githubusercontent.com/21301288/269859473-c9fb4980-df95-4b38-af7b-104a41e61613.png">

很遗憾，以为这个方式完美解决，发现用着用着就失效了，必须强制刷新页面才能生效。

还是接上面的，另外我发现，我在StackEdit窗口右边渲染出来的页面，点击链接是新窗口打开的，而发布文章后却不行了，不知这种有什么不一样呢？

**Comment by ruibaby** [comment]
> 很遗憾，以为这个方式完美解决，发现用着用着就失效了，必须强制刷新页面才能生效。

是不是主题用了 Pjax？

> 另外我发现，我在StackEdit窗口右边渲染出来的页面，点击链接是新窗口打开的

应该是 StackEdit 本身对预览区域做了处理，这并不是 Markdown 的功能。因为 StackEdit 实际上是一个嵌入的网页，他不支持通过依赖的方式在其他程序中使用，如果对所有外部链接设置了新窗口打开。

https://stackedit.io/

**Comment by ruibaby** [comment]
此问题本身应该与 Halo 无关，因为默认编辑器支持设置链接打开方式，以下是其他解决办法：

1. 如果有这样的需求，可以考虑使用默认编辑器。
2. 主题提供适配。
3. 修改 Markdown 编辑器插件，支持为标签设置打开方式（不推荐），并且我们应该无法修改 StackEdit 的行为。

/close
