### ISSUE TITLE
无法 Halo VSCode 插件中登录

### ISSUE THREAD

**Issue by JohnNiang** [halo-dev/halo#4651]
# 无法登录Halo插件
![image](https://github.com/halo-dev/halo/assets/128916922/2aefc563-dde9-4216-a881-a1eada5cafe7)

## 问题描述

使用vscode-extension-halo插件时,按照说明配置了站点、用户名和密码,但登录始终失败。

## 重现步骤

1. 在VS Code插件市场安装vscode-extension-halo
2. 在设置中配置:
   - 站点:https://example.com/ (不包含/console)  
   - 用户名:myusername
   - 密码:mypassword
3. 存储策略选择"本地"
4. 尝试登录,但一直显示登录失败

## 环境信息

- 操作系统:Windows 10
- VS Code版本:
版本: 1.82.2 (user setup)
- 插件版本:最新版

## 尝试过的解决方案

- 确认站点、用户名和密码正确
- 尝试过重新启动VS Code
- 尝试重新安装插件

## 补充信息

我参考了插件的使用文档,但没有看到特殊的登录要求。所以不清楚具体是什么原因导致无法登录。

如果需要我提供任何额外的信息来协助分析这个问题,请告知。

非常感谢!

_Originally posted by @baoyu0 in https://github.com/halo-dev/halo/issues/4625#issuecomment-1731551994_

**Comment by baoyu0** [comment]
![image](https://github.com/halo-dev/halo/assets/128916922/f2986154-ca20-422a-9eb1-c186eaac81e8)

- 试了一下，始终显示这个，我的站点信息就填的是博客外部访问地址啊
- 是不是halo的后台还需要特别的设置？比如权限什么的？
- 有没有其他的办法检查是什么原因导致的错误？

**Comment by baoyu0** [comment]
![image](https://github.com/halo-dev/halo/assets/128916922/e87641b7-8214-4e1e-88e4-cbb97fb7dc1a)

![image](https://github.com/halo-dev/halo/assets/128916922/5f9942ef-5e46-4222-a9ff-605234ee2e79)

- 此外我用官网提供的demo来测试仍然是无法登录

**Comment by baoyu0** [comment]
> 我刚刚尝试复现，能够正常登录 Halo 并上传文章。
> 
> 复现步骤：
> 
> 1. 安装 Halo VSCode 插件 v1.1.0。
> 2. 按 `Command/Ctrl + P` 打开命令版，输入 `halo setup` 即可初始化 Halo 站点、用户名和密码即可配置完成。
> 3. 创建 Markdown 文件，并填充内容，打开命令版并输入 `halo publish` 即可发布成功。

我用官网的demo账号登录仍然是无法登录

**Comment by ruibaby** [comment]
@baoyu0 可以尝试查看一下 VSCode 的运行日志：

<img width="1044" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/cafc2c7a-04b8-4704-9ca1-d3014a028592">

<img width="1027" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/d56a11d1-4a6e-4e53-a132-9e6d5e4787b8">

**Comment by baoyu0** [comment]
没有输出，不知道到底是啥原因

**Comment by PengXuanyao** [comment]
> 输入站点地址的时候加上协议即可，比如：`https://example.com`
> 
> 需要输入站点地址之后做一下校验或者补全。
> 
> /kind improvement

我开始也遇到了这个问题，只使用example.com无法登录，必须要加上https才可以。
