### ISSUE TITLE
安装Katex和ByteMD插件后，在编辑器里可以预览公式，但在网页中就缺失渲染，行内代码块也是如此。

### ISSUE THREAD

**Issue by CGengdu** [halo-dev/halo#4654]
### 是什么版本出现了此问题？

2.9.1

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式运行？

Docker Compose

### 在线站点地址

http://gengduc.site

### 发生了什么？

安装Katex和ByteMD插件后，在编辑器里可以预览公式，但在网页中就缺失渲染，行内代码块也是如此。
Bug网页：[http://gengduc.site/archives/1695477664310](http://gengduc.site/archives/1695477664310)

### 附加信息

![image](https://github.com/halo-dev/halo/assets/71617674/4e71e080-fbe8-4252-91a8-3d41f97b5514)

**Comment by ruibaby** [comment]
有参考 https://github.com/halo-sigs/plugin-katex?tab=readme-ov-file#%E6%96%87%E7%AB%A0%E9%A1%B5%E6%B8%B2%E6%9F%93%E5%85%AC%E5%BC%8F 进行配置吗？

/triage duplicate
/area plugin

**Comment by CGengdu** [comment]
以下是我在ByteMD中截图
![image](https://github.com/halo-dev/halo/assets/71617674/f5a1a35a-29f9-4f5e-99ab-1376037ceb5f)
Katex中的配置如下：
![image](https://github.com/halo-dev/halo/assets/71617674/0801c8a5-6352-4693-990c-2cd9d1215f10)
虽然可以渲染出来，但似乎又出现了行内公式和块公式渲染的混乱,一个公式被渲染成了两次块公式，如下：
![image](https://github.com/halo-dev/halo/assets/71617674/e9313239-8d90-45fe-9c3a-ba78de1ab7da)
而且似乎较长的公式也没办法渲染。

当我将Katex中的配置改为
![image](https://github.com/halo-dev/halo/assets/71617674/62248af7-a552-45a1-956c-e49c8b52fdc6)
这下行内公式正常，但块公式又出错了，如下：
![image](https://github.com/halo-dev/halo/assets/71617674/747fa627-7837-40e5-8698-fa80e31c02a6)

**Comment by ruibaby** [comment]
<img width="868" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/47c0f4ff-ab72-490b-8f3a-7f5b912ce10a">

**Comment by CGengdu** [comment]
😊👍
