### ISSUE TITLE
希望能够添加自定义文章url和自定义页面url

### ISSUE THREAD

**Issue by Lostars** [halo-dev/halo#466]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [x] 添加新的特性或者功能
- [ ] 请求技术支持

搜了相关issue和bbs内容后，

**Comment by ruibaby** [comment]
本来就支持啊

**Comment by Lostars** [comment]
阅读相关issue和bbs内容后，代码也拉下来看了下，发现在controller中没有实现能够自定义url得实现，特别是自定义页面得url都是在/s路径下，略显蛋疼。而文章url也是，在另一个issue中也有提到，不知道能不能提供相关的支持

**Comment by ruibaby** [comment]
这个路径呀，会支持的。

**Comment by ruibaby** [comment]
不过工作量有点大，需要等待。

**Comment by ruibaby** [comment]
https://github.com/halo-dev/halo/issues/299

**Comment by Lostars** [comment]
还有个就是最新的beta版本还是没有提供像xxx.html这种自定义文章url的支持吗，我看设置的类似url都会被移除掉.然后设置成xxxhtml

**Comment by ruibaby** [comment]
不支持，过滤了特殊符号
