### ISSUE TITLE
期望增加对第三方存储仅删除附件记录而不实际删除文件的功能

### ISSUE THREAD

**Issue by longjuan** [halo-dev/halo#4667]
### 你当前使用的版本

2.9

### 描述一下此特性

在 s3 插件下一个版本中会加入关联已有文件的功能。

而目前 Permalink 重新生成存在问题，因此想增加第三方存储仅删除附件记录而不删除文件的功能。

当用户想修改cdn域名时，对附件仅删除记录，然后修改或者新增策略，再使用新功能关联回原来的文件。

s3 插件在写的文件处理后缀参数的功能会将后缀写入annotation里，想修改这个后缀可以先删除后关联。

**Comment by JohnNiang** [comment]
我们只需要在[这里](https://github.com/halo-dev/plugin-s3/blob/0265a71c83c677fd87eb02839958a4142dc72e23/src/main/java/run/halo/s3os/S3OsAttachmentHandler.java#L87)控制是否需要真实删除的逻辑。

**Comment by JohnNiang** [comment]
Hi @halo-dev/sig-halo-console ，可能需要在附件列表这里提供扩展点。

**Comment by ruibaby** [comment]
> Hi @halo-dev/sig-halo-console ，可能需要在附件列表这里提供扩展点。

提供扩展之后使用 S3 插件来拓展吗？

**Comment by JohnNiang** [comment]
> > Hi @halo-dev/sig-halo-console ，可能需要在附件列表这里提供扩展点。
> 
> 提供扩展之后使用 S3 插件来拓展吗？

是的。只要列表元素能扩展，S3 插件就能够修改当前附件的 annotations。这样就可以在删除逻辑中根据 annotation 来判断是否需要真正删除 S3 文件。

**Comment by JohnNiang** [comment]
> > Hi @halo-dev/sig-halo-console ，可能需要在附件列表这里提供扩展点。
> 
> 提供扩展之后使用 S3 插件来拓展吗？

是的。只要列表元素能扩展，S3 插件就能够修改当前附件的 annotations。这样就可以在删除逻辑中根据 annotation 来判断是否需要真正删除 S3 文件。

**Comment by ruibaby** [comment]
> 我的想法是在附件操作下新增一个仅删除记录的功能。
> ![image](https://user-images.githubusercontent.com/28662535/271338785-6cf9d539-c265-495d-9b8b-6f458c14c17c.png)

我将实现这个操作列表的扩展点。

PS: 这个按钮叫做 **解除绑定** 是不是更好？

**Comment by longjuan** [comment]
> PS: 这个按钮叫做 **解除绑定** 是不是更好？ For S3 Only

  `解除绑定` `解除关联` 感觉都挺好。
