### ISSUE TITLE
写文章时，代码块后方无元素时无法向后跳出代码块

### ISSUE THREAD

**Issue by luijp** [halo-dev/halo#4675]
### 是什么版本出现了此问题？

2.9.2

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式运行？

Docker

### 发生了什么？

在文章编辑界面，新建代码块写完代码后，若代码块后面没有其他文章内容，则无法跳出当前代码块编辑。
应该通过方向键或其他方式能够继续文章编写工作

![QQ截图20230930174914](https://github.com/halo-dev/halo/assets/139390536/bddf53f8-560c-43b1-a384-bb164e9de0e8)

**Comment by ruibaby** [comment]
已经在 [2.10.0-alpha.1](https://github.com/halo-dev/halo/releases/tag/v2.10.0-alpha.1) 中实现，可以先在本地体验和测试一下。

/triage duplicate
