### ISSUE TITLE
删除/themes目录中不需要的主题目录后，后台登陆提示密码错误

### ISSUE THREAD

**Issue by pandalabme** [halo-dev/halo#4682]
### 是什么版本出现了此问题？

2.8 

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式运行？

Docker Compose

### 在线站点地址

https://pandalab.me/

### 发生了什么？

删除安装路径中/themes目录中不需要的主题目录后，以下两种情况后台登陆均提示密码错误：
1. 使用已有用户登录失败
2. 新注册用户成功，但退出后重新登陆，再次失败

**Comment by JohnNiang** [comment]
我这里无法复现这个问题。主题和目录没有直接联系，建议检查一下用户名的大小写是否正确。

**Comment by pandalabme** [comment]
> 我这里无法复现这个问题。主题和目录没有直接联系，建议检查一下用户名的大小写是否正确。

刚才docker compose restart重启修复了 😂

**Comment by pandalabme** [comment]
> 我这里无法复现这个问题。主题和目录没有直接联系，建议检查一下用户名的大小写是否正确。

应该不太会是用户名密码输入错误导致，用的是浏览器密码管理器自动填充。
又删除了一个主题，的确没复现，目前不知道触发原因。

**Comment by ruibaby** [comment]
如果后面再遇到这种问题可以先看看浏览器控制台的日志和网络请求。
