### ISSUE TITLE
输入错误的字符导致日志页面无法预期展示。

### ISSUE THREAD

**Issue by xiaofsu** [halo-dev/halo#469]
## 我的环境

Server 版本：1.2.0
Admin 版本：1.2.0
数据库：H2
运行模式：production
UA 信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36

---

## 错误日志

暂无。

---

## 期望行为

期望能够正常按照字符串或按照换行来进行输出。

## 当前行为

查看 [halo-theme-simple-bootstrap](https://github.com/CodeLunatic/halo-theme-simple-bootstrap/issues/9)，以便于详细了解。

**Comment by ruibaby** [comment]
你可以这样：

```markdown
在thymeleaf中使用js获取后台传到前台的值，不仅需要在首页声明： `xmlns:th="http://www.thymeleaf.org"` 还需要在`<script>`声明： `th:inline="javascript"`
这样才能使用：`[[${titleText}]]` 进行取值操作。
```

**Comment by xiaofsu** [comment]
> 你可以这样：
> 
> ```gfm
> 在thymeleaf中使用js获取后台传到前台的值，既需要在首页声明：`xmlns：th =“ http://www.thymeleaf.org”`还需要在`<script>`声明：`th：inline =“ javascript”` 
> 这样才能使用：`[[$ {titleText}]]`进行取值操作。
> ```

🤣🤣 这也只是一个暂时的解决方案吧...因为速记那里写东西时看不到任何格式的，所以可能需要改进下？

**Comment by ruibaby** [comment]
后面提供个预览吧，你用 markdown 格式写就好了。

**Comment by xiaofsu** [comment]
> 后面提供个预览吧，你用 markdown 格式写就好了。

好的，看到是个文本框就直接输入进去了...

---

我使用上面你给的格式去编辑了，编辑完之后：
![image](https://user-images.githubusercontent.com/46067472/71799209-ada5c400-308f-11ea-962b-2de64928f877.png)

**Comment by ruibaby** [comment]
@xiaofsu 你尝试把这段内容发文章试试

**Comment by xiaofsu** [comment]
@ruibaby https://www.xiaofsu.com/archives/test0001

**Comment by ruibaby** [comment]
@xiaofsu 嗯。日志的 markdown 渲染器和文章的是一样的。既然文章没问题，可能是和日志页的某个js插件起了冲突。

**Comment by xiaofsu** [comment]
@ruibaby OK谢谢，我去找主题的作者了...😅😅😅

**Comment by ruibaby** [comment]
@xiaofsu 我现在去看看吧。完了给他提pr
