### ISSUE TITLE
没有找到用户头像设置的地方。

### ISSUE THREAD

**Issue by shmilyabyy** [halo-dev/halo#4693]
### 是什么版本出现了此问题？

2.9.1

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

没有找到设置头像的地方。
![image.png](https://vip2.loli.io/2023/10/09/vlka8BscPbZ4jI3.png)
![1696820347394.png](https://vip2.loli.io/2023/10/09/H3SVijbUGarZ26v.png)

**Comment by ruibaby** [comment]
/triage duplicate

https://github.com/halo-dev/halo/issues/4373

**Comment by ruibaby** [comment]
不过这里可以稍微优化一下，可以参考我们的论坛，在未设置头像的时候显示一个设置图标。

<img width="182" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/8766cf91-8f4f-42b6-b87d-f37d1673675f">

/kind improvement
/remove-triage duplicate
/area console

**Comment by shmilyabyy** [comment]
> 不过这里可以稍微优化一下，可以参考我们的论坛，在未设置头像的时候显示一个设置图标。
> 
> <img alt="image" width="182" src="https://user-images.githubusercontent.com/21301288/273491649-8766cf91-8f4f-42b6-b87d-f37d1673675f.png">
> /kind improvement /remove-triage duplicate /area console

请问一下，不能从附件中选择吗？为什么设置头像点击上传是直接从本地里上传啊

**Comment by ruibaby** [comment]
> 请问一下，不能从附件中选择吗？为什么设置头像点击上传是直接从本地里上传啊

不能，不是所有用户都能访问附件库，设置头像属于单个用户行为。

**Comment by shmilyabyy** [comment]
> > 请问一下，不能从附件中选择吗？为什么设置头像点击上传是直接从本地里上传啊
> 
> 不能，不是所有用户都能访问附件库，设置头像属于单个用户行为。
