### ISSUE TITLE
从2.8.0升级到2.9.1之后就没法访问

### ISSUE THREAD

**Issue by Thomitics** [halo-dev/halo#4696]
### 是什么版本出现了此问题？

2.9.1

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式运行？

Docker

### 在线站点地址

http://111.173.105.195:1111/

### 发生了什么？

从2.8.0升级到2.9.1之后就没法访问,然后用备份退回2.8.0就好了,再升级回到2.9.1就又不行，重建之后也还是无法访问。无法访问表现为显示“当前无法使用此页面，111.173.105.195 当前无法处理此请求。”同一服务器上其他网站一切正常。部署方式是使用1panel里面的应用商店自动docker部署

**Comment by Thomitics** [comment]
日志文件
[halo.log.2023-10-06.2.txt](https://github.com/halo-dev/halo/files/12845377/halo.log.2023-10-06.2.txt)

**Comment by Thomitics** [comment]
这个问题的解决方法是修改 `.env` 文件参数
从 1Panel 应用商店-已安装页面 进入 Halo 的安装目录
修改 `.env` 文件
添加以下参数 `PANEL_DB_TYPE="mysql"`
然后 ”重建“ Halo 应用

希望能在更新时自动执行这一步，我是找了好一阵子才成功解决的

**Comment by ruibaby** [comment]
> 这个问题的解决方法是修改 `.env` 文件参数 从 1Panel 应用商店-已安装页面 进入 Halo 的安装目录 修改 `.env` 文件 添加以下参数 `PANEL_DB_TYPE="mysql"` 然后 ”重建“ Halo 应用
> 
> 希望能在更新时自动执行这一步，我是找了好一阵子才成功解决的

与 Halo 无关，建议向 1Panel 提交 issue。

/kind support
/close
