### ISSUE TITLE
关于博客的备案信息设置

### ISSUE THREAD

**Issue by tangkai007** [halo-dev/halo#470]
您好，我在查找了主题编辑，系统设置，和issues之后并没有发现是怎么去设置页脚的网站备案信息，请问是在哪里设置的

**Comment by ruibaby** [comment]
博客设置 -> 页脚信息

**Comment by tangkai007** [comment]
但是没有覆盖原有的页脚信息
https://www.gfy5800.com/
是因为我设置的不正确吗？

**Comment by ruibaby** [comment]
不是覆盖，是追加，你已经加上了。

**Comment by tangkai007** [comment]
只能追加，不能覆盖是嘛？

**Comment by ruibaby** [comment]
自己去改模板

**Comment by tangkai007** [comment]
好的

**Comment by qianliangchang** [comment]
可以自己修改主题里面的页脚，这里面可以改
[cid:_Foxmail.1@d284e531-1024-f124-0caa-317b8c8e9b52]


________________________________
qianliangzhang@outlook.com

发件人： tangkai007<mailto:notifications@github.com>
发送时间： 2020-01-06 15:53
收件人： halo-dev/halo<mailto:halo@noreply.github.com>
抄送： Subscribed<mailto:subscribed@noreply.github.com>
主题： [halo-dev/halo] 关于博客的备案信息设置 (#470)

您好，我在查找了主题编辑，系统设置，和issues之后并没有发现是怎么去设置页脚的网站备案信息，请问是在哪里设置的

**Comment by pencilso** [comment]
卧槽  老哥搞黑产的 ？
