### ISSUE TITLE
附件库bug就是照片那个(急急急)

### ISSUE THREAD

**Issue by a12cn** [halo-dev/halo#4707]
### 是什么版本出现了此问题？

2.x-2.10

### 使用的什么数据库？

MySQL 5.7

### 使用的哪种方式运行？

Docker Compose

### 在线站点地址

www.a12x.cn

### 发生了什么？

简单点就比如Halo.png，我直接换张照片吧命名改为Halo.png，显示还是之前的，必须要改halo.png或者其他命名才可以，还有附件库不跟/root/halo/attachments/upload/同步？

**Comment by Steven-WZH** [comment]
cdn缓存？
