### ISSUE TITLE
我在开发一个halo插件，在console端会新开一个页面，用vue3编写，如何能够快速调用halo默认的编辑器

### ISSUE THREAD

**Issue by pandatools** [halo-dev/halo#4711]
### Your current Halo version

2.9

### Describe this feature

![截图_20231011160242](https://github.com/halo-dev/halo/assets/44802141/befe6738-706c-4358-8604-9b492fad348c)
vue3代码，我想把这个换成系统默认的编辑器，我该如何调用才能快速实现

**Comment by ruibaby** [comment]
这个编辑器就是和文章的用的一样的，只是可能版本有差异，并且是单独引用的，目前 Console 并未在全局注册默认编辑器。

/kind feature
/area console

**Comment by ruibaby** [comment]
目前（2.11）在插件中已经可以使用默认编辑器，可以参考 https://github.com/halo-sigs/plugin-moments 的做法。

/close
