### ISSUE TITLE
建议邮件的“通知设置”添加一个“发送测试”的功能

### ISSUE THREAD

**Issue by GuGuGee** [halo-dev/halo#4714]
### Your current Halo version

2.10.0

### Describe this feature

目前后台有提供“启用邮件通知器”的功能，配置完SMTP之后，没有一个类似之前1.6版本的“发送测试”功能，验证自己的SMTP配置是否正确，希望可以在之后的版本添加这个功能，非常感谢！

**Comment by JohnNiang** [comment]
/kind feature
/area core

Thank you for reaching out here! We will try our best to recover the feature.

**Comment by LIlGG** [comment]
> 可能还需要为 FormKit 提供一个这样的组件。

实际上我感觉只需要简单的扩展一下 `Form` 组件，例如将 [示例](https://formkit.com/inputs/form#submitting-via-xhrfetch-request) 中的 `@submit="login"` 更改为一个内置的验证方法即可。
