### ISSUE TITLE
Safari 15.6 浏览器登录控制台，应用市场插件不能正确显示

### ISSUE THREAD

**Issue by lichlaughing** [halo-dev/halo#4720]
### 是什么版本出现了此问题？

2.10

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

如题，浏览器报错如下：

[![pipktVx.png](https://z1.ax1x.com/2023/10/13/pipktVx.png)](https://imgse.com/i/pipktVx)
谷歌浏览器下正常。

**Comment by ruibaby** [comment]
Safari 的版本是？我这边没有复现这个问题。

<img width="284" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/87b1d8ba-4dca-419f-bc9b-a11e759629b6">

/triage needs-information

**Comment by ruibaby** [comment]
在 Safari 15.6.1 上确实可以复现这个问题，建议先使用其他浏览器。

<img width="1316" alt="图片" src="https://github.com/halo-dev/halo/assets/21301288/5022d0f8-2e19-4e06-955c-d2ecf893513e">

/area console
/kind bug

**Comment by ruibaby** [comment]
排查了一下，似乎是部分插件的 js 中使用了不兼容 Safari 正则表达式写法导致的，不太清楚这个问题需要怎么解决...

**Comment by ruibaby** [comment]
目前无法在 Halo Core 当中解决，如果后续遇到此问题，可以在插件中尝试对低版本浏览器进行兼容。

/close
