### ISSUE TITLE
之后版本是否计划支持内置主题编辑菜单

### ISSUE THREAD

**Issue by stars-one** [halo-dev/halo#4726]
### 你当前使用的版本

2.10.0

### 描述一下此特性

之前1.5.0,比较喜欢的主题编辑功能,目前发现halo后台没法和之前一样提供主题编辑功能

虽然我可以自行通过文件管理器到theme对应的主题文件夹进行文件的编辑,但是还是希望可以考虑加个主题编辑功能

**Comment by JohnNiang** [comment]
目前我们计划不再支持使用者手动编辑主题文件。如果确实有自定义需求，建议 fork 主题仓库，所有的修改都在自己的仓库中，这样可避免升级主题可能出现的冲突。

**Comment by LIlGG** [comment]
正如 @JohnNiang 所述，我们不再建议、支持使用者手动编辑主题文件。

/triage unresolved
