### ISSUE TITLE
后台设置菜单图标后，在页面上仍无法显示

### ISSUE THREAD

**Issue by wjj0227** [halo-dev/halo#4729]
### 是什么版本出现了此问题？

halo 2.10

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式运行？

Docker Compose

### 在线站点地址

http://blog.vrxiaojie.top

### 发生了什么？

已根据fontawesome官方给的 https://fontawesome.dashgame.com/#new ，修改设置-代码注入-全局head标签部分。如图
![image](https://github.com/halo-dev/halo/assets/74085232/aaae47fe-f901-4009-95c2-7a4100106604)

然后在 菜单-“首页”-编辑-图标 填入了 fa fa-home：
![image](https://github.com/halo-dev/halo/assets/74085232/581e574f-4db6-4c9e-8d3d-690ccadb126e)

回到博客刷新后，“首页”位置仍然没有该图标。
![image](https://github.com/halo-dev/halo/assets/74085232/df14a7f3-9243-4dd0-8c40-2d4ed16a17f5)

P.S :尝试过更换到官方主题和另一款主题，依旧无法显示。现在使用的主题是theme-hao。

**Comment by wjj0227** [comment]
目前测试发现，一级菜单不能放图标，二级的就行。很奇怪，不知道是bug还是什么？

![image](https://github.com/halo-dev/halo/assets/74085232/4f2f4f5d-a995-4622-9f1b-ededd9addf51)
我看别人也用halo搭建的，他们一级菜单就能放图。

**Comment by ruibaby** [comment]
这是对应主题提供的功能，建议查阅[主题文档](https://www.yuque.com/liuzhihangs/halo-theme-hao/nlmywot0y7eaz519)，或者向主题提交 issue。

/kind support
/close
