### ISSUE TITLE
联想浏览器无法新建文章

### ISSUE THREAD

**Issue by Jamtoal** [halo-dev/halo#4733]
### 是什么版本出现了此问题？

2.10.0

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

在联想浏览器访问博客控制台，点击文章，再点击新建，卡在加载界面，无法新建文章（在edge，chrome无此问题）
![1](https://github.com/halo-dev/halo/assets/91370415/73a9d7ea-52d0-4e6c-aae7-7544846fc189)
![2](https://github.com/halo-dev/halo/assets/91370415/8a2e3a8c-4365-4d5e-8058-4ea2a0674fe9)

**Comment by ruibaby** [comment]
我这边使用最新的联想浏览器测试没有复现这个问题。

<img width="1470" alt="图片" src="https://github.com/halo-dev/halo/assets/21301288/2a7665c5-b3c3-4a81-b11e-639a9db4e3ce">

<img width="1470" alt="图片" src="https://github.com/halo-dev/halo/assets/21301288/793faf5c-0bd9-4b5a-95d6-456b73af7e85">

/triage needs-information

**Comment by Jamtoal** [comment]
更新浏览器后未复现，疑似旧版浏览器不兼容，问题已在更新浏览器版本后解决
