### ISSUE TITLE
在 Console 引入 @tailwindcss/forms 以统一表单元素的基础样式

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#4734]
### 你当前使用的版本

2.10.0

### 描述一下此特性

期望通过引入 `@tailwindcss/forms` 来统一表单元素在不同浏览器的基础样式。

https://github.com/tailwindlabs/tailwindcss-forms

/area console
/kind improvement

**Comment by wan92hen** [comment]
现在的样式不是也挺统一的吗？

**Comment by ruibaby** [comment]
> 现在的样式不是也挺统一的吗？

Firefox:

<img width="474" alt="图片" src="https://github.com/halo-dev/halo/assets/21301288/489a8512-724d-468d-99de-ff413490e19f">

Safari:

<img width="486" alt="图片" src="https://github.com/halo-dev/halo/assets/21301288/acfd7532-86cf-4f19-9527-363c232f65d1">

Chrome:

<img width="458" alt="图片" src="https://github.com/halo-dev/halo/assets/21301288/cf3f1513-ce5f-4c11-9e09-c555f87c9dc7">

更新描述了，应该是浏览器的差异。
