### ISSUE TITLE
文档编辑的角色创建文章报未知错误

### ISSUE THREAD

**Issue by lohasty** [halo-dev/halo#4735]
### 是什么版本出现了此问题？

v2.10.0

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

创建文档编辑的角色，新建用户关联到此角色，创建文章报未知错误，但可以正在常编辑和发布。

### 相关日志输出

```shell
2023-10-17T11:23:31.989+08:00  WARN 7 --- [tReconciler-t-1] r.h.a.e.controller.DefaultController     : Optimistic locking failure when reconciling request: run.halo.app.core.extension.reconciler.PostReconciler-worker-1/Request[name=c69918eb-7990-450a-93d4-e9789cb850e9]
```

### 附加信息

![image](https://github.com/halo-dev/halo/assets/124872512/d4bc2caa-f80b-4e35-96da-9257a5af954d)

**Comment by guqing** [comment]
@halo-dev/sig-halo-console 原因是获取附件存储策略无权限，是否需要对从附件库选择图片增加 ui 权限控制？
<img width="801" alt="image" src="https://github.com/halo-dev/halo/assets/38999863/fac9a17a-9be1-4b29-bad9-aa3934f761ef">

**Comment by guqing** [comment]
Hi @lohasty，此原因是由于没有分配附件权限导致的提示，不影响文章发布，只是不能从附件库挑选附件，我们会排查并处理，感谢你提出此问题♥️

**Comment by ruibaby** [comment]
在 https://github.com/halo-dev/halo/pull/4866 中已经优化此问题，并且提供了个人中心的文章管理。

/close
