### ISSUE TITLE
console页、搜索内容页面、标签选择

### ISSUE THREAD

**Issue by lcese** [halo-dev/halo#4738]
### 你当前使用的版本

2.10

### 描述一下此特性

一、建议console页面支持模板化，这样可以通过模板自定义console登陆及注册页；
![微信截图_20231017163605](https://github.com/halo-dev/halo/assets/96273492/83803743-f805-4f24-b2fa-ad84597d957b)

二、搜索内容页面建议可以增加一个单独显示的界面，该页面也可以支持模板。目前搜索出来的内容就显示在搜索框下面，如果内容一多。也是一个问题。
![微信截图_20231017163910](https://github.com/halo-dev/halo/assets/96273492/9c45e8c7-4a33-44ea-befb-6da3617afacd)

三、添加文章内容时标签如果在非常多的情况下面还采取这种单列下滑会很费劲。能够增加多列或者可以翻页的功能。
![微信截图_20231017163723](https://github.com/halo-dev/halo/assets/96273492/7bf4d062-1c2f-4403-9f3d-19d6ff759537)

**Comment by ruibaby** [comment]
请不要在一个 issue 里面提多个不相关的内容，请参考：[https://github.com/halo-dev/halo/issues/new?assignees=&labels=&projects=&template=feature_request.zh.yml](https://github.com/halo-dev/halo/issues/new?assignees=&labels=&projects=&template=feature_request.zh.yml#:~:text=%E4%B8%BA%E4%BA%86%E6%96%B9%E4%BE%BF%E6%88%91%E4%BB%AC%E7%AE%A1%E7%90%86%EF%BC%8C%E8%AF%B7%E4%B8%8D%E8%A6%81%E5%9C%A8%E5%90%8C%E4%B8%80%E4%B8%AA%20issue%20%E4%B8%8B%E6%8F%90%E4%BA%A4%E5%A4%9A%E4%B8%AA%E6%B2%A1%E6%9C%89%E7%9B%B8%E5%85%B3%E6%80%A7%E7%9A%84%E7%89%B9%E6%80%A7%E3%80%82)

<img width="894" alt="图片" src="https://github.com/halo-dev/halo/assets/21301288/b64d97db-bcc4-4fae-b9cb-dd12db2f90e8">

我将关闭此 issue。
