### ISSUE TITLE
console页面支持模板化

### ISSUE THREAD

**Issue by lcese** [halo-dev/halo#4739]
### 你当前使用的版本

2.10

### 描述一下此特性

建议console页面支持模板化，这样可以通过模板自定义console登陆及注册页；
![微信截图_20231017163605](https://github.com/halo-dev/halo/assets/96273492/0d3cf4a4-4ce1-48cd-8580-37aee9df5af8)

**Comment by ruibaby** [comment]
可以再说明一下用途。

/triage needs-information

**Comment by lcese** [comment]
如注册条款等可以进行操作

**Comment by ruibaby** [comment]
目前 Console 的登录页面是不会加载插件资源的，也没有提供扩展，因为目前针对登录页面没有统一的扩展需求。以下是当前的实现建议：

1. 在主题端提供登录或者注册弹框，实现方式可以参考 Console 的代码。

**Comment by ruibaby** [comment]
已经计划重构登录页面的渲染方式，后续可跟踪：https://github.com/halo-dev/halo/issues/5214

/close
