### ISSUE TITLE
搜索内容页面独立显示

### ISSUE THREAD

**Issue by lcese** [halo-dev/halo#4740]
### 你当前使用的版本

2.10

### 描述一下此特性

搜索内容页面建议可以增加一个单独显示的界面，该页面也可以支持模板。目前搜索出来的内容就显示在搜索框下面，如果内容一多。也是一个问题。
![微信截图_20231017163910](https://github.com/halo-dev/halo/assets/96273492/f636f368-f248-400c-abe9-8f9ffb99ce30)

**Comment by ruibaby** [comment]
/triage duplicate

see https://github.com/halo-dev/halo/issues/2862

/close
