### ISSUE TITLE
【1panel】升级失败

### ISSUE THREAD

**Issue by guomingshan** [halo-dev/halo#4742]
### 是什么版本出现了此问题？

2.9.1

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式运行？

Docker

### 发生了什么？

![image](https://github.com/halo-dev/halo/assets/38829832/3570fbbb-f4cb-4e03-90c9-cfc690db2845)
使用的 **1panel**平台，升级时提示 “文件不存在”

**Comment by guqing** [comment]
建议到 1Panel 提交 issue，升级问题与 halo 无关

**Comment by wanghe-fit2cloud** [comment]
> 升级时提示 “文件不存在”

是准备升级到哪个目标版本？
> 也可以先同步应用商店，成功之后再来尝试升级 Halo。
<img width="1475" alt="image" src="https://github.com/halo-dev/halo/assets/46734380/fbb72b04-3a5a-48b0-8014-b69e6a35c27d">

**Comment by guomingshan** [comment]
> 准备升级到哪个目标版本？
2.10.0
![image](https://github.com/halo-dev/halo/assets/38829832/99fb15bf-7b5c-4a6e-9f21-7a3219b85c7e)

**Comment by guomingshan** [comment]
> 建议到 1Panel 提交 issue，升级问题与 halo 无关

好的，谢谢

**Comment by guomingshan** [comment]
> > 升级时提示 “文件不存在”
> 
> 是准备升级到哪个目标版本？
> 
> > 也可以先同步应用商店，成功之后再来尝试升级 Halo。
> 
> <img alt="image" width="1475" src="https://user-images.githubusercontent.com/46734380/275867084-fbb72b04-3a5a-48b0-8014-b69e6a35c27d.png">

同步之后升级成功了，谢谢
