### ISSUE TITLE
 用户console界面问题

### ISSUE THREAD

**Issue by krunlien** [halo-dev/halo#4748]
### 你当前使用的版本

Halo 2.x

### 描述一下此特性

对用户仪表盘中的概览和身份认证以及右上角的设置按钮好像并没什么用，怎么隐藏或者删除

**Comment by JohnNiang** [comment]
目前你可以点击设置按钮，移除小组件即可。

**Comment by ruibaby** [comment]
是指低权限用户还可以看到这些入口吗？

**Comment by ruibaby** [comment]
2.11 已经支持个人中心，你可以选择不让用户进入到控制台。

/close
