### ISSUE TITLE
不止为何console的一些页面不显示，一直转圈圈

### ISSUE THREAD

**Issue by youngledo** [halo-dev/halo#4753]
### 是什么版本出现了此问题？

2.9.2，最新版也是如此

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式运行？

Docker、1Panel

### 发生了什么？

<img width="1124" alt="image" src="https://github.com/halo-dev/halo/assets/68590897/1624c0da-1402-4cfd-a9b5-efd71f44ce78">
<img width="1182" alt="image" src="https://github.com/halo-dev/halo/assets/68590897/4961298d-457f-41bc-be6e-dd14f825fabc">
我也看了日志控制台、包括浏览器控制台都没有发现报错

**Comment by ruibaby** [comment]
/area console

你当前设备是否有正常连接网络？

**Comment by youngledo** [comment]
有网啊，不然我这个issue就提交不了。
<img width="1114" alt="image" src="https://github.com/halo-dev/halo/assets/68590897/1f462126-b0ae-4d7f-95a0-be296de151b4">
点击【文章】浏览器控制台只调用了如图上面的接口，貌似没有文章的接口。

**Comment by youngledo** [comment]
我这个是因为edge异常，换成chrome浏览器正常。但edge上的问题大概率是因为使用了百度广告联盟，触发了安全机制的缘故：
<img width="957" alt="企业微信截图_ae1a86df-d60c-4306-929d-76594c311cd0" src="https://github.com/halo-dev/halo/assets/68590897/66f4f900-5607-4a58-b8f3-c4c6ed9bbbe8">

**Comment by ruibaby** [comment]
感觉和这个无关，你的 Edge 上有安装什么插件吗？比如屏蔽广告之类的

**Comment by youngledo** [comment]
确实装了一些插件，包括屏蔽广告的插件，但禁用了还是不行。就算开启edge的InPrivate窗口也是不行。
