### ISSUE TITLE
建议专门为插件设置一个外部访问地址设置项

### ISSUE THREAD

**Issue by dearlance** [halo-dev/halo#4760]
### 你当前使用的版本

2.10.0

### 描述一下此特性

Halo的开发者，你们好！

感谢你们开发出Halo这个好用的博客系统。

但是我在使用Halo的过程中发现一些问题。

通过阅读Halo文档，文档中提到Halo的docker compose有个参数是：halo.external-url

按照配置文件中的注释，这个配置项应该改为自己解析到服务器IP的域名。

但是这么做似乎无法支持https。于是我就把该配置项保持了默认值，设为了：http://localhost:8090

然后，我在Halo前面套了一层nginx。我在nginx中监听了80端口，绑定了我的域名，并配置了https的ssl证书，然后把请求转到http://127.0.0.1:8090  备注：nginx和Halo安装在同一台主机。

这么做似乎没任何问题。博客系统也能正常使用，除了系统后台中显示外部访问地址为：http:/localhost:8090/

但是当我使用rss和sitemap插件的时候，发现这两个插件都是基于外部访问地址生成的内容。

订阅和站点地图中所生成的连接都变成了：http://localhost:8090开头的链接。

很显然，这个地址对访客来说，是无法访问的。

我想，这些插件似乎都使用了外部访问链接的地址作为了链接生成的规则。但是在我这个场景下，这么做将会导致问题。

因此，我有个想法和建议：
如果针对插件，有一个独立的外部访问地址配置项就好了，这个配置项只对插件有效。这样就能解决我的问题了。既能使用nginx做前置，又能使用Halo监听本地端口。

顺便问一下，如果不使用nginx作为前置，而是直接使用外部访问地址配置将博客系统开放给公网，这么做能加上https吗？我想也许是我的Halo打开方式不对。但是如果这样不行，又必须使用nginx作为前置并配置https，那么又会出现我上面提到的问题。

感谢你花时间阅读我的问题，谢谢！

**Comment by ruibaby** [comment]
> 但是这么做似乎无法支持https

external-url 的设置和能不能访问以及支持不支持 https 没有任何关系，目前它的意义仅仅只是主域名。比如给邮件通知模板中提供完整的网站地址，以及为 sitemap 这样的插件提供完整地址。

> 但是当我使用rss和sitemap插件的时候，发现这两个插件都是基于外部访问地址生成的内容。

修改 external-url 为你的实际访问地址即可，比如 `https://www.halo.run` 然后重建容器。

只需要理解到 external-url 不会对任何访问逻辑造成影响即可。

**Comment by dearlance** [comment]
原来是我理解错误。

我以为halo.external-url这个参数和网络监听的配置逻辑一样，例如配置成0.0.0.0:8090意思是允许任何IP访问8090端口，配置成localhost:8090就只允许本地访问8090端口。实际上，这个参数是不影响访问的。

问题已解决，原来是自己的打开方式不对。感谢回复。
