### ISSUE TITLE
安装完站点迁移插件，但是没有工具栏，没有迁移按钮

### ISSUE THREAD

**Issue by dayunnas** [halo-dev/halo#4761]
### 是什么版本出现了此问题？

2.10.0

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式运行？

Docker Compose

### 在线站点地址

https://halo.851224.xyz/

### 发生了什么？

安装完站点迁移插件，但是没有工具栏，没有迁移按钮

**Comment by dayunnas** [comment]
![微信图片_20231022155718](https://github.com/halo-dev/halo/assets/80449837/b7302a14-dae8-4245-a837-b8a076bd17a9)

**Comment by ruibaby** [comment]
加载 Console 的时候有异常提示吗？我看你这个似乎有关 Console 的扩展都没有加载。

/kind support
/triage needs-information

**Comment by ruibaby** [comment]
可以在浏览器控制台检查一下这个请求：

<img width="885" alt="图片" src="https://github.com/halo-dev/halo/assets/21301288/dd6f7cb5-3037-435d-8335-e7cc0decd3a2">

这个请求的状态码是 307，后端已经将 cache-control 设置为了 `no-cache`，但目前发现有一些反向代理会将这个 header 给覆盖掉，导致 js 缓存没有在操作插件状态之后及时更新。

正常情况：

<img width="719" alt="图片" src="https://github.com/halo-dev/halo/assets/21301288/4855487e-0a60-4ba8-9830-db2eb0fda69a">

**Comment by dayunnas** [comment]
已解决，感谢大佬

**Comment by JohnNiang** [comment]
当前 Issue 将被关闭。如果有任何问题，请随时重新打开。

/close
