### ISSUE TITLE
增加 Pushable 等类似接口

### ISSUE THREAD

**Issue by Erzbir** [halo-dev/halo#4762]
### 你当前使用的版本

2.10.0

### 描述一下此特性

当我在编写插件时, 我想要我的代码处理所有 "可发布" 的 `Extension`, 发现并无此接口

是否可以改变设计增加这个接口以及类似接口?

**Comment by JohnNiang** [comment]
没有太明白你的意思。可以更详细描述一下你的需求么。

**Comment by ruibaby** [comment]
如果没有后续动态，我将关闭此 issue。

/close
/triage unresolved
