### ISSUE TITLE
文章元数据错误

### ISSUE THREAD

**Issue by Steven-WZH** [halo-dev/halo#4764]
### What is version of Halo has the issue?

2.10.0

### What database are you using?

PostgreSQL

### What is the project operation method?

Docker Compose

### What happened?

从菜单访问文章设置：
![image](https://github.com/halo-dev/halo/assets/113268133/5621519e-09c3-4eeb-9b85-2139fd8b3fb8)
从文章编辑页访问会出现多个空白元数据
![image](https://github.com/halo-dev/halo/assets/113268133/5d3cdfb0-53b8-461d-9ad2-9246d54d9869)
后台日志无报错

**Comment by Steven-WZH** [comment]
在2.10.0新建的文章也会出现类似错误

**Comment by Steven-WZH** [comment]
使用域名访问后台会出现这个问题，用ip访问正常，用变量指定的链接（域名）访问，会出现这个问题

**Comment by JohnNiang** [comment]
如果通过 IP 地址访问是正常的，建议看看浏览器的控制台是否有报错以及网络请求详情。

**Comment by Steven-WZH** [comment]
没报错，而且用ip访问的时候也会出现这样的情况

**Comment by ruibaby** [comment]
我这边没能复现这个问题，不管是新建还是打开以前文章的设置。

**Comment by xmengnet** [comment]
也遇到了，多了几个空白的元数据，就今晚创建的两篇文章都是，还无法修改保存了。。。那几个空白元数据删除后保存提示：    当前 Key 已被占用 ，不删除也不让保存，希望尽快看一下什么原因。之前创建的文章都没这个问题，我试了下新增文章都有这个问题。

**Comment by xmengnet** [comment]
刚试了下发现如果不点进文章编辑页面，直接在文章列表右边的三个点选择设置是正常的，如果点击进文章编辑界面就会出现这个问题。

**Comment by Steven-WZH** [comment]
用系统自带的备份迁移功能复制数据到新的容器也会出现这种情况

**Comment by LIlGG** [comment]
在生产环境中确实有概率复现此问题，但本地开发环境暂时未复现。

复现操作：
1. 新建文章并保存
2. 打开此文章编辑页面，点击设置。
3. 循环 2 步骤，直至出现空白元数据。

<img width="1920" alt="image" src="https://github.com/halo-dev/halo/assets/31335418/38c84faf-8288-4330-a4c0-64f6681dc417">

/remove-triage needs-information
/area console
/kind bug

**Comment by Steven-WZH** [comment]
2.10.1版本貌似还是会出现这个问题

**Comment by JohnNiang** [comment]
/ping @LIlGG 

可能还需要再看看这个问题。

**Comment by LIlGG** [comment]
> 可能还需要再看看这个问题。

确实还能够复现这个问题，经过测试应该是自定义元数据导致的，我将重新打开这个 issue

/reopen

**Comment by LIlGG** [comment]
@Steven-WZH 我这边重新修复了该问题，但此问题在本地不容易复现。你可以下载镜像 `lixingyong/halo:fix-annotations` 在生产环境进行测试。

**Comment by Einstein-schrodinger** [comment]
我也遇到了，2.10.2版本，编辑之后再设置很容易出现这个问题，删除空白之后又会出现

**Comment by ruibaby** [comment]
> 我也遇到了，2.10.2版本，编辑之后再设置很容易出现这个问题，删除空白之后又会出现

2.10.2 应该只解决了删除空白项也无法提交的问题，这个问题应该会在 2.11 彻底解决。

目前 main 分支已经重写了相关组件，但由于改动过大，不会发布在 2.10.x。

**Comment by ruibaby** [comment]
此问题已经在 [2.11](https://github.com/halo-dev/halo/releases/tag/v2.11.0) 中修复。

/close
