### ISSUE TITLE
Role "postgres" does not exist. 	Connection matched file "/var/lib/postgresql/data/pg_hba.conf" line 128: "host all all all scram-sha-256"

### ISSUE THREAD

**Issue by Steven-WZH** [halo-dev/halo#4766]
### 是什么版本出现了此问题？

2.10.0

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

Role "postgres" does not exist.
	Connection matched file "/var/lib/postgresql/data/pg_hba.conf" line 128: "host all all all scram-sha-256"
使用官方compose文档内容部署
![image](https://github.com/halo-dev/halo/assets/113268133/1ba1b69d-cec3-4e3d-a0e9-2cc1f90dcbfd)

**Comment by ruibaby** [comment]
建议提供你的 Docker Compose 文件以及详细复现步骤。
