### ISSUE TITLE
文章底部的评论模块不显示图片

### ISSUE THREAD

**Issue by pencilso** [halo-dev/halo#477]
在文章详情下有一个评论模块
然后有一个图标还是啥东西，图片加载不进来。我看了一下图片引用，是引用的cdn.v2ex.com/gravatar?d=monsterid

cdn.v2ex.com  这个站点崩了，然后会加载不到这个站点的图片。  
还有，这里为什么会加载外部站点的图片呢。

**Comment by ruibaby** [comment]
@pencilso 建议使用另外一个评论组件试试看

**Comment by ruibaby** [comment]
@pencilso 这个支持定义 gravatar 源，https://github.com/halo-dev/halo-comment-normal

**Comment by pencilso** [comment]
我在自定义内容页 head加入以下代码 还是没有生效，最后加载的还是v2ex的，而且我看了一下审查元素，页面的head上已经有这一段代码了
<script>
        var configs = {
            autoLoad: true,
            showUserAgent: true,
            gravatarSource: 'https://blog-cdn.pencilso.cn/422e9de02f2d4e77b7f6c73db845f858.png'
        }
</script>

**Comment by ruibaby** [comment]
@pencilso Gravatar 源不是一个图片地址...

**Comment by pencilso** [comment]
那是啥玩意？

**Comment by ruibaby** [comment]
你用默认的v2ex源也不行吗？

**Comment by pencilso** [comment]
我这访问不到v2ex啊

**Comment by ruibaby** [comment]
等会儿，给你找个

**Comment by pencilso** [comment]
而且我换网络了也访问不到v2ex

**Comment by pencilso** [comment]
确定不是v2ex挂了？

**Comment by ruibaby** [comment]
我这里没问题哦

**Comment by pencilso** [comment]
谢谢，辛苦了

**Comment by pencilso** [comment]
好吧，我把翻墙关了后，能访问v2ex了，现在可以了

**Comment by ruibaby** [comment]
`//gravatar.loli.net/avatar`

**Comment by pencilso** [comment]
这不就是图片么 = =

**Comment by ruibaby** [comment]
`https://gravatar.loli.net/avatar/7cc7f29278071bd4dce995612d428834?s=256&d=mm`

懂了吗？

**Comment by pencilso** [comment]
不懂   还是图片啊，只是你这加了图片处理参数

**Comment by ruibaby** [comment]
好吧，你那没问题就行了。

**Comment by pencilso** [comment]
v2ex 又访问不到了，这回关了翻墙也不行
我在head里加了这一段代码，可是最后加载的还是v2ex的站点  这个怎么搞 = =
求大佬指点
<script>
var configs = {
   gravatarSource:'//gravatar.loli.net/avatar'
}
</script>

**Comment by ruibaby** [comment]
```
<halo-comment id="${post.id?c}" type="post" :configs="configs">
```

这里有改吗？

https://github.com/halo-dev/halo-comment-normal#%E8%87%AA%E5%AE%9A%E4%B9%89%E9%85%8D%E7%BD%AE

**Comment by pencilso** [comment]
<halo-comment id="${post.id?c}" type="post" :configs="configs"> 
这个在哪个ftl里面？  我看了下post.ftl  没这个东西

**Comment by pencilso** [comment]
哥   真的没用啊
我用的Fantastic主题
然后我把layout/comment/comment.ftl 给改了：
```
<#macro comment post,type>
    <#if !post.disallowComment!false>
        <script src="//cdn.jsdelivr.net/npm/vue@2.6.10/dist/vue.min.js"></script>
        <script src="${options.comment_internal_plugin_js!'//cdn.jsdelivr.net/gh/halo-dev/halo-comment@latest/dist/halo-comment.min.js'}"></script>
        <script>
            var configs = {
                gravatarSource:'//gravatar.loli.net/avatar'
            }
        </script>
        <halo-comment id="${post.id?c}" type="post" :configs="configs">
    </#if>
    <style>
        .halo-comment .comment-placeholder {
            border: none !important;
        }
        .comment-item-content img {
            width: 100%;
        }
    </style>
</#macro>
```

但是最后访问的还是v2ex的站点


Fantastic主题下 post.ftl、sheet.ftl 都#include 了 article.ftl

 article.ftl 下写了：
```
    <#if !index>
        <div class="card" id="comment-wrapper">
            <div class="card-content">
                <h3 class="title is-5 has-text-weight-normal">评论</h3>
                <#if commentType == 'post'>
                    <@comment post,"post" />
                <#else>
                    <@comment post,"sheet" />
                </#if>
            </div>
        </div>
    </#if>
```

**Comment by pencilso** [comment]
费那么大劲 还改不好....
我最后把https://cdn.jsdelivr.net/npm/halo-comment-normal@1.1.1/dist/halo-comment.min.js 这个js下载下来   然后把里面的v2ex站点给替换了  上传到自己的cdn   终于好了
