### ISSUE TITLE
【严重BUG】请求瞬间、链接的api地址访问地址错误！

### ISSUE THREAD

**Issue by carolcoral** [halo-dev/halo#4790]
### 是什么版本出现了此问题？

2.10.1

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式运行？

Docker Compose

### 在线站点地址

https://blog.cnkj.site

### 发生了什么？

更新halo版本从 `2.10.0` 到 `2.10.1` 后发现在管理端访问 `瞬间` 和 `链接` 侧边栏提示 404地址不存在。

通过查看console内容发现请求的地址出现了代理端口，因此导致访问了一个无效地址！

本站部署方式采用: nas本地docker comspose 部署 - 代理端口转发到公网域名 - 阿里云CDN回源代理域名端口请求地址

<img width="830" alt="image" src="https://github.com/halo-dev/halo/assets/8952687/bfcf1e57-38b2-4f91-99ec-0872e7c8a421">

<img width="1347" alt="image" src="https://github.com/halo-dev/halo/assets/8952687/d4d0f6c6-e591-48d7-95d5-2b2702e42e73">

### 相关日志输出

```shell
{
    "type": "about:blank",
    "title": "Not Found",
    "status": 404,
    "instance": "http://blog.cnkj.site:18082/apis/api.plugin.halo.run/v1alpha1/plugins/PluginMoments/moments?page=1&size=20&keyword=&startDate=&endDate=",
    "requestId": "047fbe03-350",
    "timestamp": "2023-10-30T08:35:47.298946399Z"
}
```

**Comment by carolcoral** [comment]
本次错误可以参考 site-map 插件修改方式进行处理，该问题我在`站点地图`插件0.0.1版本遇到并提交[request](https://github.com/halo-dev/plugin-sitemap/pull/16)修复过。

**Comment by ruibaby** [comment]
这个和 external-url 的设置应该没有任何关系，插件调用接口并不携带域名，而是 `/apis/content/...`，异常给出的路径可能只是因为你的代理没有携带类似 HOST 的 header。

问题本身可能出在插件加载上，你可以尝试重启插件。

**Comment by JohnNiang** [comment]
Hi @carolcoral ，请问问题又解决么？如果解决了，建议描述一下解决过程以帮助到其他遇到相同问题的用户。

**Comment by carolcoral** [comment]
> Hi @carolcoral ，请问问题又解决么？如果解决了，建议描述一下解决过程以帮助到其他遇到相同问题的用户。

问题已经解决。需要重新pull镜像并且清空缓存，如果使用的是cdn方式也需要同步刷新cdn。
