### ISSUE TITLE
搜索功能极不完善

### ISSUE THREAD

**Issue by jyx-fyh** [halo-dev/halo#4796]
### 是什么版本出现了此问题？

2.10.0

### 使用的什么数据库？

MySQL 5.7

### 使用的哪种方式运行？

Docker

### 在线站点地址

https://butcherx.cn/

### 发生了什么？

搜索插件仍有较多缺陷：
1.搜索到结果，但结果显示不全
2.无关结果过多
3.权重排序混乱，全匹配的条目居然排再很后面
这对重度依赖搜索的用户实在太致命啦！希望作者大大早日修复！感谢！

### 附加信息

![image](https://github.com/halo-dev/halo/assets/116637015/ca357668-d4ab-4fb0-8366-dc02c27c6510)

**Comment by JohnNiang** [comment]
感谢反馈问题！

本地搜索精准度和排序，后面会慢慢优化。

/kind improvement
/area core
/assign

**Comment by RiverChu0** [comment]
附议，当文章越来越多时，找文章就靠关键词搜索。目前发现了个问题，后台文章页，搜索功能，只针对标题搜索。如果搜索内容里的词，标题也没有这个关键词，是搜索不出结果的。

**Comment by ruibaby** [comment]
在优化内置搜索引擎的同时，是否也可以考虑支持通过插件集成外部搜索引擎？比如：https://github.com/meilisearch/meilisearch

他们还为前台提供了 JS 库：https://github.com/meilisearch/docs-searchbar.js

**Comment by RiverChu0** [comment]
> 附议，当文章越来越多时，找文章就靠关键词搜索。目前发现了个问题，后台文章页，搜索功能，似乎只针对标题搜索但又不完全是。搜索文章内容，有些能搜索出来。有些搜索不出来。刷新搜索引擎缓存也不行。

前台搜索能搜到内容，后台文章页的搜索不行。搜不到文章里面内容，有时编辑某篇文章，想把它找出来。只能搜标题里的词，希望能重视一下后台文章页的搜索。

**Comment by JohnNiang** [comment]
Hi @RiverChu0 ，感谢反馈！

待 Halo 更加稳定后，我们会考虑重构一下文章搜索的功能，尽可能保证前后端都能够使用同一个搜索引擎。

**Comment by Rainsheep** [comment]
@RiverChu0  可以试用下 https://github.com/Rainsheep/halo-plugin-meilisearch 插件，提高了前台搜索体验。 体验网站 https://blog.rainsheep.cn
