### ISSUE TITLE
建议增加资源库按文件夹整理功能

### ISSUE THREAD

**Issue by a1098832322** [halo-dev/halo#48]
当大量的文章素材在资源库中堆成一堆时，后续更博想再找到某一张图时就会变得十分困难，建议增加按文件夹整理资源库的功能，可以让用户自己建立文件夹，按文章、天数等等自己把文件归档。

**Comment by ruibaby** [comment]
由于目前正在开发 V1 版本，所以该 issue 已经不适用于新版本，所以先关闭了。
