### ISSUE TITLE
建议增加文章粘贴图片时可选择默认存储策略

### ISSUE THREAD

**Issue by mjsoftking** [halo-dev/halo#4801]
### Your current Halo version

2.10.0

### Describe this feature

建议增加文章粘贴图片时可选择默认存储策略。

当前新建存储策略会使新策略创建在第一位，当前不能排序，而此时新文章粘贴图片会就会储存在这个新建的存储策略中，而这个策略并不是我需要的存储位置。
默认编辑器支持粘贴图片也确实是快速便捷的，期望有办法调整这个存储策略。

**Comment by ruibaby** [comment]
/triage duplicate

see https://github.com/halo-dev/halo/issues/3258

已经放在了 2.11 的 milestone，尽可能在 2.11 中发布。

/close
