### ISSUE TITLE
期望 Console 侧边菜单支持二级菜单

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#4807]
### 你当前使用的版本

2.10.1

### 描述一下此特性

当前 Console 的侧边菜单仅有分组和菜单项的概念，不支持二级菜单，插件安装多了之后会导致侧边菜单项过多，尤其是有一些菜单项可能并不常用。所以期望菜单项支持子菜单，可以更好的组织菜单项结构。

Ref https://github.com/halo-dev/halo/issues/4732#issuecomment-1767633457

/area console
/kind feature

**Comment by longjuan** [comment]
![image](https://github.com/halo-dev/halo/assets/28662535/df214f2c-3b43-495e-aab2-9c09725a8543)
![image](https://github.com/halo-dev/halo/assets/28662535/b5d2501a-3149-438e-884b-1cf0d7db6ffb)
貌似已经有样式了，好像没用起来

**Comment by ruibaby** [comment]
> 貌似已经有样式了，好像没用起来

是的，Menu 组件本身是支持的，但我记得 definePlugin 的路由定义似乎还不支持，你这是怎么测试的呢。

**Comment by longjuan** [comment]
> 你这是怎么测试的呢。

![image](https://github.com/halo-dev/halo/assets/28662535/0038b2b0-c9d7-4442-a136-b063c98e4d71)

**Comment by ruibaby** [comment]
> 我觉得可以提供几个预设的一级菜单，然后在route的meta加一个字段，决定这个菜单项是一级菜单还是归于哪个二级菜单

可以提供预设的菜单，但渲染二级菜单我觉得可以按照现在的获取方式。设置好 parent route 和 menu meta 即可。

**Comment by longjuan** [comment]
> 现在的获取方式

现在有什么地方使用到二级菜单吗，我这边测试，最终的menu会出现两次
![image](https://github.com/halo-dev/halo/assets/28662535/e71fbfc9-a4d0-461f-9a6d-45cd1585a05f)
![image](https://github.com/halo-dev/halo/assets/28662535/f11dd60e-4d80-4a26-83af-266ccc82cb96)

**Comment by ruibaby** [comment]
> 现在有什么地方使用到二级菜单吗，我这边测试，最终的menu会出现两次

还没，目前只在基础的 Menu 组件层面实现了二级菜单，还没有完整的进行实际测试。

/assign
