### ISSUE TITLE
全站加密，禁止游客访问权限

### ISSUE THREAD

**Issue by timen3303** [halo-dev/halo#4822]
### 你当前使用的版本

2.10.1

### 描述一下此特性

开发者大神们，我想将halo作为一个完全个人博客网站，并且公布在官网上以便于与我在任何地方可以直接访问它。
但是，只要知道我域名都可以直接访问，这不是我想要的。我想对整个博客添加一个账号密码访问权限，或者出现“不登录无法访问”的权限呢？

**Comment by JohnNiang** [comment]
/kind feature
/area core

感谢反馈这个功能！

接下来看看社区对于这个功能的反馈。

**Comment by ruibaby** [comment]
是不是用 Nginx Basic Auth 就行了？

https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/

**Comment by timen3303** [comment]
> 是不是用 Nginx Basic Auth 就行了？
> 
> https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/

有尝试过基于NPS HTTP  Basic Auth  的方案，有2个明显的缺点：1、基于HTTP来进行认证，认证完成后数据传输还是明文的。我的技术有限，不知道如何设置基于HTTPS进行认证；2、NPS中一旦针对某个客户开启 HTTP  Basic Auth 的话，那么使用这个客户端的所有域名解析都进行加密了，https根本无法访问。
有大神能进行一些指导吗？

**Comment by ruibaby** [comment]
> NPS中一旦针对某个客户开启 HTTP Basic Auth 的话，那么使用这个客户端的所有域名解析都进行加密了，https根本无法访问。
有大神能进行一些指导吗？

不太懂这个 NPS 是啥，不过是否可以针对某个域名设置规则？

此外，如果这个功能要在 Halo 程序中实现的话，或许可以考虑通过插件实现，插件如果可以添加拦截器的话。

**Comment by haust-lyb** [comment]
> > NPS中一旦针对某个客户开启 HTTP Basic Auth 的话，那么使用这个客户端的所有域名解析都进行加密了，https根本无法访问。
> > 有大神能进行一些指导吗？
> 
> 不太懂这个 NPS 是啥，不过是否可以针对某个域名设置规则？
> 
> 此外，如果这个功能要在 Halo 程序中实现的话，或许可以考虑通过插件实现，插件如果可以添加拦截器的话。

NPS应该是一个工具内网穿透软件，这位兄弟估计是网站在家里某个电脑上部署的，只是通过公网NPS做了内网穿透，将内网的博客发布到了公网上

**Comment by ruibaby** [comment]
可以看看这个方案是否满足需求：https://github.com/halo-dev/halo/issues/5050#issuecomment-1859496143

**Comment by ruibaby** [comment]
目前 [Halo 专业版](https://www.lxware.cn/halo) 已经提供了内置支持，所以开源版本暂不打算支持，但如上所述，此功能仍然可以通过插件来获得支持。

/close
