### ISSUE TITLE
官方应用市场插件挂了

### ISSUE THREAD

**Issue by cyril-cheng** [halo-dev/halo#4823]
### 是什么版本出现了此问题？

2.10.2

### 使用的什么数据库？

MySQL 5.7

### 使用的哪种方式运行？

Docker

### 发生了什么？

官方应用商店插件，列表刷新不出来。一片空白

**Comment by JohnNiang** [comment]
我的站点可以正常试用，请看截图：
<img width="1665" alt="image" src="https://github.com/halo-dev/halo/assets/16865714/d2facb3e-a891-4f30-ae72-305804fcbb2e">

**Comment by cyril-cheng** [comment]
> 我的站点可以正常试用，请看截图： <img alt="image" width="1665" src="https://user-images.githubusercontent.com/16865714/280639463-d2facb3e-a891-4f30-ae72-305804fcbb2e.png">

![image](https://github.com/halo-dev/halo/assets/49748357/9309da32-9f79-4bd7-b536-0ce583f83f9d)

**Comment by cyril-cheng** [comment]
有了，重新生成了一个令牌填进去就好了
