### ISSUE TITLE
安装Katex和ByteMD插件后，在编辑器里可以预览公式，但在网页中就缺失渲染

### ISSUE THREAD

**Issue by FelicxFoster** [halo-dev/halo#4825]
### 是什么版本出现了此问题？

2.10

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式运行？

Docker Compose

### 在线站点地址

https://felicx.eu.org

### 发生了什么？

安装Katex和ByteMD插件后，在编辑器里可以预览公式，但在网页中就缺失渲染。

已参考 https://github.com/halo-sigs/plugin-katex?tab=readme-ov-file#%E6%96%87%E7%AB%A0%E9%A1%B5%E6%B8%B2%E6%9F%93%E5%85%AC%E5%BC%8F 进行配置

Bug网页：https://felicx.eu.org/archives/xiao-gong-ju-1-slam-zhi-ni-he-zhi-xian

### 附加信息

Katex中的配置如下：
<img width="270" alt="屏幕截图 2023-11-06 210912" src="https://github.com/halo-dev/halo/assets/33318659/25153d02-b657-4739-b8ea-c916d4aad578">

ByteMD预览公式正常：
<img width="778" alt="屏幕截图 2023-11-06 210851" src="https://github.com/halo-dev/halo/assets/33318659/7b55001b-df89-46ef-afa8-40a53335f0c1">

网页渲染异常：
<img width="732" alt="屏幕截图 2023-11-06 210745" src="https://github.com/halo-dev/halo/assets/33318659/3255410a-11da-4489-8ea4-b20013f53456">

**Comment by ruibaby** [comment]
使用 ByteMD + KaTex 插件在我这边没有复现此问题，建议提供一下目前已激活的插件列表，可能是其他插件干扰了 KaTex 插件的行为。

![image](https://github.com/halo-dev/halo/assets/21301288/6f491776-83e0-486e-b7c2-eefce6183db7)

**Comment by FelicxFoster** [comment]
> 使用 ByteMD + KaTex 插件在我这边没有复现此问题，建议提供一下目前已激活的插件列表，可能是其他插件干扰了 KaTex 插件的行为。
> 
> ![image](https://user-images.githubusercontent.com/21301288/280722716-6f491776-83e0-486e-b7c2-eefce6183db7.png)

已下是我安装的插件：
<img width="828" alt="屏幕截图 2023-11-06 214048" src="https://github.com/halo-dev/halo/assets/33318659/2b821116-e82e-4f98-90cc-7fa339b7c46d">
<img width="755" alt="屏幕截图 2023-11-06 214112" src="https://github.com/halo-dev/halo/assets/33318659/bd66d080-b463-4da4-8282-b917e74b8e52">
