### ISSUE TITLE
【忽略的漏洞】仪表盘基础数据对任何角色可见

### ISSUE THREAD

**Issue by Aiden-777** [halo-dev/halo#4826]
### 是什么版本出现了此问题？

2.10.2

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式运行？

Docker Compose

### 在线站点地址

localhost

### 发生了什么？

普通角色登录后台，可以查看 访问数、用户数 等商业机密 ，并不合理。

**Comment by ruibaby** [comment]
从 2.11 开始，你可以在角色中禁止用户访问到 Console，但这个数据的接口还未添加权限控制。
