### ISSUE TITLE
无法打开H2控制台

### ISSUE THREAD

**Issue by whaodong** [halo-dev/halo#4828]
### 是什么版本出现了此问题？

2.10

### 使用的什么数据库？

H2

### 使用的哪种方式运行？

Docker

### 发生了什么？

![image](https://github.com/halo-dev/halo/assets/38680752/1548b066-e69f-4e89-a9e8-82105dc0b471)
![image](https://github.com/halo-dev/halo/assets/38680752/22e16fa5-7492-4dbf-9a10-55eff4c09188)

**Comment by JohnNiang** [comment]
感谢反馈问题！

因为 H2 Console 用到了 Servlet 技术，而 Halo 试用 WebFlux 技术，所以无法通过配置的方式打开 H2 Console。

如果确实需要打开 H2 Console，可以参考 <https://www.h2database.com/html/quickstart.html#h2_console> 或者其他支持 H2 的数据库工具。

/kind support
