### ISSUE TITLE
站点配置cdn后，后台提示“加载插件入口文件失败”

### ISSUE THREAD

**Issue by ilusymon** [halo-dev/halo#4829]
### 是什么版本出现了此问题？

2.10

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式运行？

Docker Compose

### 在线站点地址

https://nsyue.com

### 发生了什么？

![image](https://github.com/halo-dev/halo/assets/61956642/08433490-82d1-4250-b9ef-ecb9bef7681e)
![image](https://github.com/halo-dev/halo/assets/61956642/44f7feb5-e63b-4e56-98b4-d469560d946d)

如图，/apis/api.console.halo.run/v1alpha1/plugins/-/bundle.css和/apis/api.console.halo.run/v1alpha1/plugins/-/bundle.js一直重定向导致插件无法加载。
加速域名[https://nsyue.com](https://nsyue.com)访问有此问题
源站域名[https://blog.nsyue.com](https://blog.nsyue.com)访问正常

### 附加信息

nginx配置如下：
```
server{
    listen 80;
    listen 443 ssl http2;
    server_name blog.nsyue.com;
    client_max_body_size 10240m;
    ssl_certificate /http-cert/blog.nsyue.com/blog.nsyue.com.pem;
    ssl_certificate_key /http-cert/blog.nsyue.com/blog.nsyue.com.key;
    ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;
    ssl_ciphers EECDH+CHACHA20:EECDH+CHACHA20-draft:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    add_header Strict-Transport-Security "max-age=31536000";
    error_page 497  https://$host$request_uri;
    location / {
      proxy_pass http://127.0.0.1:8090;
      proxy_redirect http://$host/ http://$http_host/;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```

**Comment by ruibaby** [comment]
这可能需要在 CDN 服务商检查配置，我们无法得知具体原因。

/kind support

**Comment by ilusymon** [comment]
解决了，谢谢，cdn没有配置跟随参数
