### ISSUE TITLE
期望文章可以复制

### ISSUE THREAD

**Issue by intoyang** [halo-dev/halo#4830]
### 你当前使用的版本

2.9

### 描述一下此特性

创作系列文章时，可能希望多篇文章保持同一种命名风格或排版样式。此时，如果能将历史文章进行复制，提供类似「文章模版」的体验就太方便了。

复制的文章可以继承初始文章的常规设置、高级设置、原数据，其中，文章标题和别名可以在原有基础上添加“copy-”字样。

**Comment by JohnNiang** [comment]
感谢反馈问题！

/kind feature
/area core
/area console

**Comment by ruibaby** [comment]
赞同，我也想要这个功能

**Comment by QAQ3254865169** [comment]
同qwq

**Comment by ruibaby** [comment]
See https://github.com/halo-dev/halo/issues/4831

/close
