### ISSUE TITLE
期望对新建文章进行设置时可以支持复用历史文章

### ISSUE THREAD

**Issue by intoyang** [halo-dev/halo#4831]
### 你当前使用的版本

2.9

### 描述一下此特性

新建文章后回到文章列表页面，对文章进行设置时，期望可以增加一个「复用历史文章」按钮；在此选中某篇文章后，可以自动延用该文章除文章名称及别名以外的常规设置、高级设置及原数据内容。
实际上和 #4830 中提到的文章复制功能类似，都能使系列创作更加便捷。

### 附加信息

/kind feature

**Comment by ruibaby** [comment]
现在有一个插件支持文章克隆：https://github.com/ruibaby/plugin-content-tools

![Image](https://github.com/user-attachments/assets/d38f0f5f-b266-484a-80d8-f9564a90fdca)
![Image](https://github.com/user-attachments/assets/43061888-284f-424a-bb84-08ac22c2989b)

/close
