### ISSUE TITLE
feature request: 希望根据 heading 标题来生成 id

### ISSUE THREAD

**Issue by Lu7fer** [halo-dev/halo#4838]
### 你当前使用的版本

2.10.0

### 描述一下此特性

现在的标题id是`前缀-数字`结构
```html
<h1 style="" id="heading-1">使用jar部署Halo2博客站点</h1>
<h2 style="" id="heading-2">准备工作</h2>
```
这样的结构在文章内跳转变得困难, 一旦使用`<a herf="#heading-2"></a>`进行位置跳转, 添加或者删除标题后将转到错误的位置, 并且这种目录id在使用时也颇为不便

所以可以考虑引入目录本身的层次特征, 一种解决方法是使用`h-1.1`这种包含目录层次的id取代顺序编号, 虽然不是完美的解决方案, 但是可以增加易用性

**Comment by ruibaby** [comment]
/area editor
/area console
/kind improvement

可以考虑根据 heading 标题来生成 id。

**Comment by Lu7fer** [comment]
标题可以是可以, 不过`" < >` 等这些特殊的字符可能要在保存文章的时候转义一下, md编辑器可以在标题中嵌入html, 生成id的时候也得过滤掉, 感觉工作量还是不小

**Comment by ruibaby** [comment]
> 标题可以是可以, 不过`" < >` 等这些特殊的字符可能要在保存文章的时候转义一下, md编辑器可以在标题中嵌入html, 生成id的时候也得过滤掉, 感觉工作量还是不小

这种是有成熟的方案的，比如：https://github.com/valeriangalliat/markdown-it-anchor

**Comment by Lu7fer** [comment]
nice👍
