### ISSUE TITLE
代码块中含有空行时渲染异常

### ISSUE THREAD

**Issue by Nanoic39** [halo-dev/halo#4841]
### 是什么版本出现了此问题？

2.10.1

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式运行？

Docker

### 在线站点地址

https://nanoic.cc/archives/codetest

### 发生了什么？

**文章浏览样式：**
![image](https://github.com/halo-dev/halo/assets/52908732/f5c28b51-c2f9-4fa9-acfb-afe2cd08bbce)
**文章内容：**
![image](https://github.com/halo-dev/halo/assets/52908732/e9643cd8-a675-4c77-98af-a624ed342691)

当代码块中出现空白行时会导致后面所有的代码块渲染出现问题，测试了Halo默认的Earth主题和Hao主题，均出现这个问题，可能不是主题的问题

### 附加信息

插件信息：
![image](https://github.com/halo-dev/halo/assets/52908732/85b2dc3a-fd83-4cbc-a3f0-db2a67e81aea)

**Comment by ruibaby** [comment]
建议关闭所有插件再看看有没有问题，如果没有问题再一个一个启动并尝试复现。

/kind support

**Comment by Nanoic39** [comment]
找到了，是ToolBench插件的问题，非常感谢
