### ISSUE TITLE
后台看到的评论，瞬间日志里的评论显示异常

### ISSUE THREAD

**Issue by zyy247796143** [halo-dev/halo#4843]
### 是什么版本出现了此问题？

 2.10.2

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式运行？

Docker Compose

### 在线站点地址

seafog.cn

### 发生了什么？

在后台评论区看到的瞬间日志评论，看到的评论通知显示是“未知”，并且不能像文章评论那样可以定位到是哪条日志发出的评论。
![image](https://github.com/halo-dev/halo/assets/23225911/89420a2c-0da9-406e-a8f6-fc60d3ce55a5)

**Comment by ruibaby** [comment]
你可能需要升级瞬间插件的版本，最新版本应该是支持的。

<img width="517" alt="图片" src="https://github.com/halo-dev/halo/assets/21301288/043db059-21a1-4e31-8417-41713bebc4dd">

/kind support

**Comment by zyy247796143** [comment]
我这个是1.3.0版本，应用市场最新也是1.3.0。
好吧，我刚测试更换主题就正常了。是主题的问题。
