### ISSUE TITLE
RSS 报错

### ISSUE THREAD

**Issue by Yuukion** [halo-dev/halo#487]
- 我已经安装了最新版的 Halo
  - 我已经搜索了已有的 Issues 列表中有关的信息
  - 我已经搜索了论坛中有关的信息：https://bbs.halo.run
  - 我已经阅读了 Halo 的 FAQ：https://halo.run/guide/faq.html

## 我的环境
 ```txt
Server 版本：1.2.0
Admin 版本：1.2.0
数据库：MySQL
运行模式：production
UA 信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36 Edg/79.0.309.63
```

## 错误日志

 无相关错误日志

## 期望行为
正常返回相关数据

## 当前行为
![image](https://user-images.githubusercontent.com/33031194/72198214-2d9fa580-3465-11ea-95ed-7c66c278155d.png)

我使用的Pinghsu 主题，点击页脚处的RSS。

**Comment by ruibaby** [comment]
能提供一个详细地址吗？

**Comment by Yuukion** [comment]
> 能提供一个详细地址吗？

https://tiandex.cn/

**Comment by ruibaby** [comment]
似乎和 `Mikasa - 记录生活&分享成长` 有关，你尝试把 `&` 去掉，或者用转义之后的 `&` 试试。后面我们把标题也用 CDATA 括起来应该就好了。

**Comment by Yuukion** [comment]
@ruibaby  谢谢，已解决，`&`替换为 `&amp;`

**Comment by ruibaby** [comment]
enjoy~
