### ISSUE TITLE
希望能支持 直接上传markdown文件 然后自动解析，比如我用其他软件导出markdown 然后网页可以自动解析

### ISSUE THREAD

**Issue by 1193700079** [halo-dev/halo#4873]
### 你当前使用的版本

1.3

### 描述一下此特性

目前很多软件 比如语雀 notion  印象笔记  有道云笔记 都可以导出html 以及 markdown等格式，希望能够支持导出的文件，能够直接上传到halo中！

**Comment by ruibaby** [comment]
目前 Halo 不支持 Markdown 导入导出的功能，但社区提供了两个外部的插件可以实现这一点：

- https://github.com/halo-sigs/vscode-extension-halo/
- https://github.com/halo-sigs/obsidian-halo

针对于 Halo，也有一个社区的插件：

- https://github.com/Lyn4ever29/halo-plugin-export-md

可以看看是否满足需求。

/kind support

**Comment by 1193700079** [comment]
好的 我打算试试 非常感谢！
