### ISSUE TITLE
【BUG】博客首页显示的文章数量不对

### ISSUE THREAD

**Issue by mimajiushi** [halo-dev/halo#488]
## 我的环境 

Halo版本：最新版（docker不指定版本安装）  
操作系统：Centos7
MYSQL：5.7.21

## 环境信息

Server 版本：1.1.1
Admin 版本：1.1.1
数据库：MySQL
运行模式：production
启动时间：2020-01-05 22:18

## 错误日志
无

## 期望行为

博客首页显示的【文章】数量为为**已发布**的文章数量，不应该包含**草稿**。   

PS：后台首页显示的【文章】数量则是**已发布**的文章数量，不包含**草稿**。  

## 当前行为

博客首页的【文章】数量显示的是包含**草稿**的数量。  

## 附上截图

![当前编辑的文章（其中一篇是草稿）](https://www.wenjie.store//bug/后台首页文章.png)

![后台显示的文章数量为4（不包含草稿）](https://www.wenjie.store//bug/halo/后台首页显示文章数量.png)

![博客首页显示文章5（包含草稿）](https://www.wenjie.store//bug/halo/首页显示的文章数量等.png)

**Comment by ruibaby** [comment]
新版已修复，1.2.0。
