### ISSUE TITLE
文章/页面 添加附件选择 S3 存储内容缺少“桶”

### ISSUE THREAD

**Issue by carolcoral** [halo-dev/halo#4880]
### 是什么版本出现了此问题？

2.10.2

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式运行？

Docker

### 在线站点地址

https://blog.cnkj.site

### 发生了什么？

1. 使用 `1.6.3` 版本的对象存储插件成功添加附件S3存储策略 MinIO
2. 上传图片到MinIO中后新建文章/页面
3. 选择`默认编辑器`
4. 在默认编辑器的左侧功能按钮`添加`中选择`附件`
5. 插入刚才上传到对象存储中的图片文件并发布文章/页面
6. 图片无法正常显示
7. 查看图片地址发现缺少`桶`名

#### 例如：
* url: https://minio.cnkj.site
* 桶: blog
* 图片地址: /files/2023/11/1.png

直接插入图片附件后生成的地址 `https://minio.cnkj.site/files/2023/11/1.png`
实际应当生成的可访问地址 `https://minio.cnkj.site/blog/files/2023/11/1.png`

**Comment by ruibaby** [comment]
cc @longjuan 

/area plugin

**Comment by longjuan** [comment]
在 `绑定域名（CDN域名）` 中写 `minio.cnkj.site/blog` 应该就可以了

**Comment by ruibaby** [comment]
> 在 `绑定域名（CDN域名）` 中写 `minio.cnkj.site/blog` 应该就可以了

不会自动添加上 bucket 吗

**Comment by longjuan** [comment]
因为一般cdn是直接绑定桶的



---原始邮件---
发件人: "Ryan ***@***.***&gt;
发送时间: 2023年11月21日(周二) 下午3:07
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [halo-dev/halo] 文章/页面 添加附件选择 S3 存储内容缺少“桶” (Issue #4880)




  
在 绑定域名（CDN域名） 中写 minio.cnkj.site/blog 应该就可以了
  
不会自动添加上 bucket 吗

**Comment by carolcoral** [comment]
> 在 `绑定域名（CDN域名）` 中写 `minio.cnkj.site/blog` 应该就可以了

可是我用的直连，没有挂载CDN，也是这样配置么

**Comment by longjuan** [comment]
> > 在 `绑定域名（CDN域名）` 中写 `minio.cnkj.site/blog` 应该就可以了
> 
> 可是我用的直连，没有挂载CDN，也是这样配置么

是的
