### ISSUE TITLE
Response body of /system/initialize does not match with the header

### ISSUE THREAD

**Issue by LinuxSuRen** [halo-dev/halo#4885]
### What is version of Halo has the issue?

2.10.2

### What database are you using?

H2

### What is the project operation method?

Docker Compose

### What happened?

I'm trying to add e2e testing for halo. But `/system/initialize` returns a string `true` instead of a JSON, while the response header indicate it should be a JSON.

See also https://github.com/LinuxSuRen/halo/pull/1

**Comment by LinuxSuRen** [comment]
See also the background https://bbs.halo.run/d/3945-%E7%99%BB%E9%99%86%E6%8E%A5%E5%8F%A3%E7%9A%84%E5%AF%86%E7%A0%81%E5%A6%82%E4%BD%95%E5%8A%A0%E5%AF%86/9

**Comment by JohnNiang** [comment]
Thank you for pointing out this issue!

IMO, the API response could be empty with HTTP status `201` instead of only `true` here.

/kind improvement
/area core
/milestone 2.11.x

**Comment by LinuxSuRen** [comment]
> the API response could be empty with HTTP status 201 instead of only true here.

Sounds good to me.

**Comment by JohnNiang** [comment]
/assign

I'm willing to fix the issue as soon as possible.
