### ISSUE TITLE
无法上传文件

### ISSUE THREAD

**Issue by LQY-920** [halo-dev/halo#4886]
### 是什么版本出现了此问题？

2.10.1

### 使用的什么数据库？

H2

### 使用的哪种方式运行？

Docker

### 发生了什么？

![Uploading image.png…]())

**Comment by LQY-920** [comment]
Multiple errors occurred while adding files：*Object.hasOwn is not function

**Comment by LQY-920** [comment]
<img width="527" alt="halo-bug1" src="https://github.com/halo-dev/halo/assets/102708342/4335253d-eeca-455e-8fc4-80db12af9824">

**Comment by guqing** [comment]
可以提供复现步骤吗
/triage needs-information

**Comment by ruibaby** [comment]
应该是上传组件内部使用了 Object.hasOwn，但这个 API 可能在部分低版本浏览器没有。

https://caniuse.com/?search=hasown

你使用的浏览器以及版本是？

**Comment by LQY-920** [comment]
应该是浏览器的问题，换了一个浏览器，就可以正常上传了

> 应该是上传组件内部使用了 Object.hasOwn，但这个 API 可能在部分低版本浏览器没有。
> 
> https://caniuse.com/?search=hasown
> 
> 你使用的浏览器以及版本是？

**Comment by JohnNiang** [comment]
/close
/remove-triage needs-information
/kind support

I'm going to close this issue. Feel free to reopen it at any time if you have any question.
