### ISSUE TITLE
希望根据不同的客户端访问使用不同的主题

### ISSUE THREAD

**Issue by zhuozhm** [halo-dev/halo#4888]
### 你当前使用的版本

2.10

### 描述一下此特性

有些主题在移动端适配得比较好，有些在pc端适配得比较好
希望通过后台提前设置不同的客户端访问使用不同的主题，这样当识别到不同客户端可以自动跳转到预设的主题
------
虽然说可以通过预览的方式达到同样的效果，但是每次访问还是要手动拼接主题有点不智能
https://ip/?preview-theme=theme-xxx

**Comment by zhuozhm** [comment]
十分感谢

**Comment by wan92hen** [comment]
如果可以接受拼 preview-theme 参数的话，可以试下在 Nginx 上判断 user-agent 然后重写地址的方式。
