### ISSUE TITLE
首次安装应用市场插件不生效

### ISSUE THREAD

**Issue by zhuozhm** [halo-dev/halo#4891]
### 是什么版本出现了此问题？

2.10

### 使用的什么数据库？

H2

### 使用的哪种方式运行？

Docker

### 发生了什么？

![Snipaste_2023-11-22_20-31-15](https://github.com/halo-dev/halo/assets/122162970/0569040c-0096-430b-848c-2083c6f3e4e8)

---首次安装halo，携带的应用市场显示是启用状态，但是不生效

**Comment by guqing** [comment]
可以复现
![image](https://github.com/halo-dev/halo/assets/38999863/d617cf97-aa2e-4768-a3c7-4aff0ba2b196)

安装预设应用市场插件的 API 在加载插件 bundlejs 之后执行因此没有显示出菜单，需要手动刷新页面后一切正常

/kind improvement
/area console

**Comment by guqing** [comment]
Hi @zhuozhm，手动刷新一下页面后即可出现应用市场菜单

**Comment by ruibaby** [comment]
我将尝试重构这个逻辑，在插件准备就绪之后再进入 Console。

/assign
