### ISSUE TITLE
使用 ExtensionPointDefinition 统一 Core 中扩展点的定义和使用方式

### ISSUE THREAD

**Issue by guqing** [halo-dev/halo#4895]
### Your current Halo version

2.10.2

### Describe this feature

目前 Core 中有一些扩展点的定义和扩展的使用已经过时，可以使用 ExtensionPointDefinition 和 ExtensionDefinition 来重构部分扩展点和扩展的定义和使用方式以便在后续在插件中使用，为后续提供完整的插件开发文档做准备

### Additional information

/kind improvement
/area core

**Comment by ruibaby** [comment]
此 issue 是否已经在 2.17 中得到解决？
