### ISSUE TITLE
后置设置文章查看密码，但是在博客页面并未生效，只是隐藏掉了，没有录入密码的提示

### ISSUE THREAD

**Issue by AllenSL** [halo-dev/halo#490]

**Comment by JohnNiang** [comment]
这里确实没有做好密码的跳转，目前是需要在 url 后面加上 /password 后缀才会有输入密码框。

**Comment by AllenSL** [comment]
不好意思啊。我没太明白，/password具体加在哪里？那个url后面？



15533783957@163.com
 
发件人： John Niang
发送时间： 2020-01-11 17:38
收件人： halo-dev/halo
抄送： AllenSL; Author
主题： Re: [halo-dev/halo] 后置设置文章查看密码，但是在博客页面并未生效，只是隐藏掉了，没有录入密码的提示 (#490)
这里确实没有做好密码的跳转，目前是需要在 url 后面加上 /password 后缀才会有输入密码框。

**Comment by JohnNiang** [comment]
> 不好意思啊。我没太明白，/password具体加在哪里？那个url后面？ 

在浏览器访问的时候，加上这个后缀即可。

**Comment by ruibaby** [comment]
这个问题在 1.2.0 不是解决了吗？也不用加 /password 呀，你直接正常访问文章地址就好了，在文章后台列表点击文章的标题即可。但是不会在前台的文章列表中显示。

**Comment by lybtt** [comment]
@ruibaby 设置密码然后重新发布的时候，加一个是否在前台显示的选项是不是会好一点？

**Comment by ruibaby** [comment]
@lybtt 暂无在前台文章列表私密文章的打算。

**Comment by haodedong** [comment]
> @ruibaby 设置密码然后重新发布的时候，加一个是否在前台显示的选项是不是会好一点？

我也感觉在首页可以看到才对，否则我搞一个加密码的文章，首页里没有，时间长了还以为丢了呢
