### ISSUE TITLE
是否支持通过接口创建文档

### ISSUE THREAD

**Issue by LetTTGACO** [halo-dev/halo#4907]
### 描述一下此特性

是否可以通过接口，将本地的 markdown 文档或者其他格式的文档，通过 API 上传文档到 halo 站点呢

**Comment by LetTTGACO** [comment]
这样的好处就在于，我可以使用市面上其他更好用的编辑器，甚至在线编辑器，然后将流程串起来。实现在线编辑文档，同步部署到 Halo 站点

**Comment by ruibaby** [comment]
目前还未提供关于 API 的使用文档，但你可以参考以下插件的做法：

1. https://github.com/halo-sigs/vscode-extension-halo/
2. https://github.com/halo-sigs/obsidian-halo
3. https://github.com/terwer/siyuan-plugin-publisher

/kind support

**Comment by LetTTGACO** [comment]
ok 感谢，希望尽快完善技术文档
