### ISSUE TITLE
1.x转移到2.x出现名称显示不出来的问题

### ISSUE THREAD

**Issue by wangsunlight** [halo-dev/halo#4911]
## 1.x转移到2.x出现名称显示不出来的问题

从1.x升级到2.x 确实界面好了不少，并且功能扩展也相对完善不少
但是我最不能理解的地方是为什么数据库只做了一张表 并且数据用longblob 来存储
这样对一些开发者个人觉得极不友好，想改个什么东西都比较麻烦
个人觉得1.x版本的表结构比较好，看起来清晰明了，也想请问下为什么要改成现在这种表结构呢？

目前碰到的问题是用户信息界面显示 “已删除用户”并且不能修改（新增和编辑任何用户都不能影响到界面），简单看了看数据结构发现读的是以下用户的数据
> registry/users/ghost

看了一下程序启动就会创建该用户，我这边该怎么修改成我自己的用户呢

![1700818889385](https://github.com/halo-dev/halo/assets/48200443/dc7de1f4-f3f1-4da8-9729-3df11d18dbda)

**Comment by ruibaby** [comment]
表结构的问题请看：https://github.com/halo-dev/rfcs/blob/main/extension/README.md

针对于你这个问题应该是需要去主题设置一个用户名，2.0 不同于 1.0 只有单用户，目前主题无法确定一个具体的用户，所以会有这样设置。

/kind support

**Comment by wangsunlight** [comment]
> 表结构的问题请看：https://github.com/halo-dev/rfcs/blob/main/extension/README.md
> 
> 针对于你这个问题应该是需要去主题设置一个用户名，2.0 不同于 1.0 只有单用户，目前主题无法确定一个具体的用户，所以会有这样设置。
> 
> /kind support

非常感谢您的解答，我这边配置后解决了以上问题 ，感谢
