### ISSUE TITLE
是真的希望管理界面能够分屏显示，还有深色模式

### ISSUE THREAD

**Issue by Sakura-LF** [halo-dev/halo#4914]
### 你当前使用的版本

latest

### 描述一下此特性

# 如图分屏太难受了:sob:
## 1. 左边的图标，完全可以用你们公司 1panel 的做法

![image](https://github.com/halo-dev/halo/assets/80140609/fc676619-0e40-4e24-af8f-03d3eae47892)

![image](https://github.com/halo-dev/halo/assets/80140609/864076c4-c2b7-4c70-a675-c334b4adc429)

## 2. 右边的大纲和希望能提供一个关闭按钮:sob:，（ 其实我觉得鼠标放上去显示大纲更好:blush:，类似语雀 ）
![image](https://github.com/halo-dev/halo/assets/80140609/d334e344-25be-4bdd-9a3b-9a705e11cfd8)
这是语雀的做法
![image](https://github.com/halo-dev/halo/assets/80140609/7689be0d-592a-43f2-a88f-d17ec5dcfb0e)

### 附加信息

真的希望能采纳

**Comment by ruibaby** [comment]
感谢反馈，但不接受在一个 issue 提交多个问题，请看：

<img width="620" alt="图片" src="https://github.com/halo-dev/halo/assets/21301288/c2549770-f6d0-4dba-8d28-a873273096b8">

建议分次提交。

/close
