### ISSUE TITLE
Add Index on post_tags to Accelerate Query

### ISSUE THREAD

**Issue by wtune** [halo-dev/halo#492]
Missing index on table `post_tags` (which is an associative table of `posts` and `tags`) column `post_id` and `tag_id` might make the underlying query issued via [PostTagService#listPostsBy](https://github.com/halo-dev/halo/blob/05a2ad14b1bd9503614dbed5731c95968d6b4e8c/src/main/java/run/halo/app/service/PostTagService.java#L74) and [PostTagService#listTagsBy](https://github.com/halo-dev/halo/blob/05a2ad14b1bd9503614dbed5731c95968d6b4e8c/src/main/java/run/halo/app/service/PostTagService.java#L37) slow. Since table `post_tags` is mostly read and sometimes inserted or updated, the performance impact for write operations is acceptable under common cases.

**Comment by ruibaby** [comment]
OK, we will try to solve it.
