### ISSUE TITLE
建议添加分类归档，上级分类可以看到下级分类的所有文章

### ISSUE THREAD

**Issue by chengzhongxue** [halo-dev/halo#4923]
### 你当前使用的版本

2.10.2

### 描述一下此特性

![image](https://github.com/halo-dev/halo/assets/89380218/908081e5-8cab-42a6-a735-510a28875d34)
上级分类
![image](https://github.com/halo-dev/halo/assets/89380218/964ddf64-3f12-49c7-8169-2d34ac1c1fd0)
下级分类
![image](https://github.com/halo-dev/halo/assets/89380218/56c272cd-2ae9-4233-8176-af6a17a7055d)
上级分类应该也可以看到下级分类的这两篇文章

**Comment by ruibaby** [comment]
这个功能如果要实现的话，建议为单个分类提供是否要查询子目录文章的字段，不然可能会改变现有的行为。

/area core
/kind improvement

**Comment by ruibaby** [comment]
> 你的意思是，主题加个字段判断然后去自己处理？

不是，还是交给后端。

**Comment by chengzhongxue** [comment]
那这样可以
