### ISSUE TITLE
默认编辑器嵌入网页，内容超出网页，选择项被挡住了

### ISSUE THREAD

**Issue by chengzhongxue** [halo-dev/halo#4926]
### 系统信息

v2.11.0-rc.1

### 使用的哪种方式运行？

Docker

### 在线站点地址

/

### 发生了什么？

![image](https://github.com/halo-dev/halo/assets/89380218/e6ee91a6-9f45-48e3-838e-e449fd5992e1)

**Comment by ruibaby** [comment]
/triage duplicate

see https://github.com/halo-dev/halo/issues/4869

/close
