### ISSUE TITLE
JDK21支持

### ISSUE THREAD

**Issue by 129duckflew** [halo-dev/halo#4929]
### 你当前使用的版本

2.10

### 描述一下此特性

JDK21支持

**Comment by JohnNiang** [comment]
近期，我们替换了 Hotspot JDK 为 OpenJ9，具体操作请参考：<https://github.com/halo-dev/halo/pull/4896>。

由于 OpenJ9 暂时还不支持 Java 21，Halo 得等上游支持后才能支持 Java 21。OpenJ9 的发版计划以及 Milestone 请参考：

- https://eclipse.dev/openj9/docs/openj9_support/
- https://github.com/eclipse-openj9/openj9/milestone/45

/kind feature
/area core
/assign
