### ISSUE TITLE
Form Schema 增加 userSelect 和 userCheckbox 组件

### ISSUE THREAD

**Issue by wan92hen** [halo-dev/halo#4931]
### 你当前使用的版本

v2.11.0-rc.1

### 描述一下此特性

https://docs.halo.run/developer-guide/form-schema#%E7%BB%84%E4%BB%B6%E7%B1%BB%E5%9E%8B

在 FormKit Schema 中增加自定义的 userSelect 和 userCheckbox 组件支持，以便在主题、插件设置中直接选择用户。

**Comment by LIlGG** [comment]
可以先在 components 中增加一个通用的 `Autocomplete` 组件。之后再使用此组件用 `FormKit` 实现一个 input 输入组件。

/assign

**Comment by bynowi** [comment]
> 可以先在 components 中增加一个通用的 `Autocomplete` 组件。之后再使用此组件用 `FormKit` 实现一个 input 输入组件。
> 
> /assign

大佬，自定义扩展$formkit 类型这个功能后期会加吗

**Comment by ruibaby** [comment]
> > 可以先在 components 中增加一个通用的 `Autocomplete` 组件。之后再使用此组件用 `FormKit` 实现一个 input 输入组件。
> > /assign
> 
> 大佬，自定义扩展$formkit 类型这个功能后期会加吗

会，如果你当前只是想在插件中自定义，暂时可以参考 https://bbs.halo.run/d/5677 中提到的做法。

**Comment by bynowi** [comment]
> > > 可以先在 components 中增加一个通用的 `Autocomplete` 组件。之后再使用此组件用 `FormKit` 实现一个 input 输入组件。
> > > /assign
> > 
> > 
> > 大佬，自定义扩展$formkit 类型这个功能后期会加吗
> 
> 会，如果你当前只是想在插件中自定义，暂时可以参考 https://bbs.halo.run/d/5677 中提到的做法。

感谢，我先参考论坛里面的做法试一试
