### ISSUE TITLE
console端主题组件 repeater 设置max问题

### ISSUE THREAD

**Issue by mjsoftking** [halo-dev/halo#4948]
### 系统信息

- 外部访问地址：https://www.sw0.top/
- 启动时间：2023-11-29 18:41
- 版本
- 构建时间：2023-11-02 18:01
- Git Commit：2ccf811
- Java：OpenJDK Runtime Environment / 17.0.9+9
- 数据库：MySQL Community Server (GPL) / 5.7.44
- 操作系统：Linux / 5.10.0-23-amd64
  

### 使用的哪种方式运行？

Docker

### 发生了什么？

![image](https://github.com/halo-dev/halo/assets/23021469/0b1d5f1b-a5fd-482c-a1da-0a8f9104cdde)
主题配置中设置了最大3个，添加按钮正常变成不可用，每项中的添加按钮还会生效。
![image](https://github.com/halo-dev/halo/assets/23021469/29fd5d9c-16a3-4c8b-a321-f13e45ad7a7b)

**Comment by ruibaby** [comment]
方便在 2.11.0-rc.1 上测试吗？2.11.0 已经完全重写了这个组件。

**Comment by mjsoftking** [comment]
我在nas里拉一下2.11试试

**Comment by mjsoftking** [comment]
@ruibaby 仍然有问题

- 显示效果没有问题
- 每项的添加按钮没有问题
![image](https://github.com/halo-dev/halo/assets/23021469/0edd3b63-b0ff-4a04-9cab-8b5a497ee459)

### 但是“添加”按钮存在问题，显示效果正确，但是可以点击并添加成功
![image](https://github.com/halo-dev/halo/assets/23021469/eaba6f01-ec51-4a3d-b511-c3d348f7dc5d)

**Comment by mjsoftking** [comment]
@ruibaby 经过多次尝试发现，点击 **“添加”** 按钮的 **图标** 和 **文字** 区域可以添加成功，其他区域无效

**Comment by ruibaby** [comment]
cc @LIlGG

**Comment by LIlGG** [comment]
在 safari 中可以成功复现。

/kind bug
/assgin

**Comment by ruibaby** [comment]
> 在 safari 中可以成功复现。
> 
> /kind bug /assgin

我爱 Safari
