### ISSUE TITLE
设置默认存储策略，默认编辑器中图片自动上传到默认存储策略中

### ISSUE THREAD

**Issue by chengzhongxue** [halo-dev/halo#4950]
### 你当前使用的版本

2.10.2

### 描述一下此特性

现有版本默认编辑器会自动上传到新建的默认编辑器

**Comment by JohnNiang** [comment]
Thank you for reaching out here!

/kind feature
/area core
/milestone 2.11.0

目前，我们已经在 https://github.com/halo-dev/halo/pull/4866 中修改了编辑器中上传附件的功能。管理员可以在系统设置中选择需要上传的存储策略和组。有兴趣的话可以测试一下。

**Comment by chengzhongxue** [comment]
好的，我去试试

**Comment by chengzhongxue** [comment]
![Uploading image.png…]()
是这个？

**Comment by JohnNiang** [comment]
Hi @chengzhongxue , 你提供的图片无法查看。不过 PR https://github.com/halo-dev/halo/pull/4866 已经合并，预计今天中午会发布 `2.11.0-rc.2`，到时候可整体测试一下。期待你的进一步反馈！

**Comment by mjsoftking** [comment]
@JohnNiang 
![image](https://github.com/halo-dev/halo/assets/23021469/a0e4f828-da03-4f91-8627-a82d158192b5)
这个也增加个组是最好的

**Comment by JohnNiang** [comment]
Hi @mjsoftking ，用户头像默认是存放在存储组 `user-avatar-group` 下的，该组默认是隐藏的，在附件管理处也是查看不了的。所以没有提供自定义“存储组”的功能。
