### ISSUE TITLE
注册用户可能无法正常绑定角色

### ISSUE THREAD

**Issue by wan92hen** [halo-dev/halo#4954]
### 系统信息

- 外部访问地址: http://localhost:8090/
- 启动时间: 2023-11-30 13:51
- 版本: 2.11.0-rc.2
- 构建时间: 2023-11-30 12:25
- Git Commit: 7a84f55
- Java: IBM Semeru Runtime Open Edition / 17.0.9+9
- 数据库: PostgreSQL / 15.3 (Debian 15.3-1.pgdg120+1)
- 操作系统: Linux / 5.15.133.1-microsoft-standard-WSL2
- 已激活主题: Daisyblocks
- 已启动插件:
  - [AI 插件](https://github.com/LIlGG/plugin-copilot-chat)
  - [Markdown / HTML 内容块](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [应用市场服务端](https://github.com/f2ccloud/plugin-app-store-server)
  - [WangEditor](https://gitee.com/handsome-npc/halo-wangEditor-plugin)
  - [微信公众号发布](https://github.com/f2ccloud/plugin-platforms-sync)
  - [站点迁移](https://github.com/halo-sigs/plugin-migrate)
  - [文章限制阅读](https://github.com/f2ccloud/plugin-restricted-reading)
  - [StackEdit](https://github.com/halo-sigs/plugin-stackedit)
  - [ByteMD](https://github.com/ruibaby/plugin-bytemd)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)
  - [lightgallery.js 灯箱](https://github.com/halo-sigs/plugin-lightgallery)
  - [图库管理](https://github.com/halo-sigs/plugin-photos)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [Sitemap](https://github.com/halo-sigs/plugin-sitemap)
  - [Unsplash](https://github.com/halo-sigs/plugin-unsplash)
  - [prism.js 代码高亮](https://github.com/liuzhihang/plugin-prismjs)
  - [reveal.js 幻灯片编辑器](https://github.com/wan92hen/plugin-revealjs)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [OAuth2 认证](https://github.com/halo-sigs/plugin-oauth2)
  - [RSS](https://github.com/halo-sigs/plugin-feed)
  - [评论组件](https://github.com/halo-sigs/plugin-comment-widget)
  - [搜索组件](https://github.com/halo-sigs/plugin-search-widget)
  - [highlight.js 代码高亮](https://github.com/halo-sigs/plugin-highlightjs)

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

用户注册时偶现注册成功后没有绑定角色的问题，观察日志发现当 `Adding request Request[name=test] immediately` 日志出现在 `Adding request Request[name=test-role-EukPY-binding] immediately` 之前时，角色可以正常绑定；反之角色不能正常绑定。

看起来是用户还未真正创建时便开始了 RoleBinding Reconcile 过程而导致。

**Comment by JohnNiang** [comment]
用户注册时添加了事务，确实可能导致 RoleBindingReconciler （运行在其他线程中）无法查询到用户，导致无法为用户设置正确的 `rbac.authorization.halo.run/role-names`。

/assign

**Comment by guqing** [comment]
> 用户注册时添加了事务，确实可能导致 RoleBindingReconciler （运行在其他线程中）无法查询到用户，导致无法为用户设置正确的 `rbac.authorization.halo.run/role-names`。
> 
> /assign

但是现在除了 console 端用户过滤使用了 rbac.authorization.halo.run/role-names 这个 annotaion 应该是没有依赖它的，用户登陆获取用户角色是现查询的
