### ISSUE TITLE
菜单删除后，前台空白

### ISSUE THREAD

**Issue by adozhao** [halo-dev/halo#4956]
### 系统信息

- 外部访问地址：
- 启动时间：2023-11-27 15:53
- 版本
- 构建时间：2023-11-02 18:01
- Git Commit：2ccf811
- Java：OpenJDK Runtime Environment / 17.0.9+9
- 数据库：H2 / 2.1.214
- 操作系统：Linux / 3.10.0-1160.99.1.el7.x86_64
  

### 使用的哪种方式运行？

Docker

### 发生了什么？

应用halo2.10默认主题，后台菜单删除之后，前台打开空白，且不知道如何恢复😓
![Snipaste_2023-11-30_14-37-37](https://github.com/guqing/halo-theme-higan/assets/23180747/ee4c277c-c883-45ac-81d7-f7efba02e65e)

**Comment by JohnNiang** [comment]
删除的菜单目前无法恢复原菜单。目前可以试试创建新的菜单看前台能否正常访问。

我这边手动测试过，重新创建菜单后可以正常访问。

/kind support

**Comment by github-ayio** [comment]
> 删除的菜单目前无法恢复原菜单。目前可以试试创建新的菜单看前台能否正常访问。
> 
> 我这边手动测试过，重新创建菜单后可以正常访问。
> 
> /kind support
我尝试去新建，但是还是没用，不知道是不是没有SET到那个点。
即使可以，我觉得这里用户的试错成本比较大，应该加以限制或修复
![image](https://github.com/halo-dev/halo/assets/23180747/f652b46a-5912-448d-8770-dd06c12355c7)

**Comment by JohnNiang** [comment]
Hi @github-ayio ，目前，我们仅对文章（重要数据）添加了回收站功能。菜单这里我不认为有必要去做这个功能。无论是否有回收站功能，都建议定期备份数据。

不过这也算是主题的 Bug（在没有菜单的情况下无法正常渲染），我先标记为 bug，后续转到主题仓库的 Issue 中。

/remove-kind support
/kind bug

**Comment by github-ayio** [comment]
> Hi @github-ayio ，目前，我们仅对文章（重要数据）添加了回收站功能。菜单这里我不认为有必要去做这个功能。无论是否有回收站功能，都建议定期备份数据。
> 
> 不过这也算是主题的 Bug（在没有菜单的情况下无法正常渲染），我先标记为 bug，后续转到主题仓库的 Issue 中。
> 
> 另外，建议同时提供一下 Halo 版本和主题版本。
> 
> /remove-kind support /kind bug


halo版本：
2.10.2
主题版本：
Earth1.7.0

**Comment by guqing** [comment]
需不需要限制一下主菜单不允许删除？

**Comment by ruibaby** [comment]
> 需不需要限制一下主菜单不允许删除？

我将在前端限制主菜单不允许删除，防止误操作。

/assign
/milestone 2.17.x
