### ISSUE TITLE
Dev环境下无法正常运行Console

### ISSUE THREAD

**Issue by pillar-cat** [halo-dev/halo#4963]
### 系统信息

Mac Os 14、Windows11 
Node 18.11 
pnpm 8.11

### 使用的哪种方式运行？

Source Code

### 发生了什么？

当在dev环境下运行Console时，会输出大量报错(如附加信息所示)，并且无法正常使用。看起来是alias配置'@'被识别成了console根路径，导致console/packages/*下的包无法找到自己的组件。
问题疑似是#Issue 4932产生的，但是不影响生产环境。

### 相关日志输出

```shell
详情可查看附加信息
```

### 附加信息

![image](https://github.com/halo-dev/halo/assets/149342718/eff518e5-2180-4208-874f-332e9cf3da74)

**Comment by pillar-cat** [comment]
#4932

**Comment by ruibaby** [comment]
这个错误不会影响正常访问，并且再次运行似乎不会出现这样的日志。

这个问题可能和 editor 包生成的 dts 有关，

**Comment by JohnNiang** [comment]
无论是否影响正常访问，都建议修复这个让人困扰的错误提示。
