### ISSUE TITLE
升级到2.11后，默认编辑器输入中文出现问题

### ISSUE THREAD

**Issue by GodlessLiu** [halo-dev/halo#4970]
### 系统信息

Halo 2.11

### 使用的哪种方式运行？

Docker Compose

### 在线站点地址

https://aifengliu.top

### 发生了什么？

编写文章时，进行中文输入时，出现字母重复问题。

### 附加信息
https://github.com/halo-dev/halo/assets/110895612/20296d54-5977-4672-b27c-46c6bc2a720e
![image](https://github.com/halo-dev/halo/assets/110895612/69a3175d-9273-4cf8-ab27-b332ab6ae011)

> 这里使用h1标签，切换输入法为中文，输入文字halo，出现问题

**Comment by Sakura-LF** [comment]
# 我也出现这个问题了,不过只有标题有这个问题,正文没事
![image](https://github.com/halo-dev/halo/assets/80140609/6f5dd9fa-7384-43e3-a29e-33b6c8dc8741)
![image](https://github.com/halo-dev/halo/assets/80140609/89104f70-f314-4038-ae0d-0772ec73a793)

**Comment by ruibaby** [comment]
可以复现。

/kind bug
/area editor
/priority critical-urgent

**Comment by ruibaby** [comment]
经过排查，和 https://github.com/halo-dev/halo/pull/4909 有关，我将优先解决此问题并发布在 2.11.1。

目前暂时可以在标题前先输入一个空格，后续打字就没有问题。
