### ISSUE TITLE
希望修改控制台页面左侧的图标以便以分屏显示

### ISSUE THREAD

**Issue by Sakura-LF** [halo-dev/halo#4971]
### 你当前使用的版本

latest

### 描述一下此特性

# 现在这样子没办法分屏编辑文章😭
![image](https://github.com/halo-dev/halo/assets/80140609/cad4fbdd-da25-4ae7-af00-39f37cea0e16)
> 感觉直接可以用你们公司 1panel 的做法
![image](https://github.com/halo-dev/halo/assets/80140609/6db8b355-c7ed-4388-ac51-360294a3eea5)

**Comment by Sakura-LF** [comment]
# 2.11 虽然侧边栏可以隐藏了，但是分屏的话还是有点儿窄
![image](https://github.com/halo-dev/halo/assets/80140609/b4995bb9-2264-49e0-8a0a-6374436ae7d2)

**Comment by AirboZH** [comment]
#4407 这应该是已经在做了

**Comment by ruibaby** [comment]
/triage duplicate

see https://github.com/halo-dev/halo/issues/4197

/close
