### ISSUE TITLE
关于用户体验的一个建议

### ISSUE THREAD

**Issue by GodlessLiu** [halo-dev/halo#4974]
### 你当前使用的版本

2.10.2

### 描述一下此特性

期望增加一个token无感刷新的选项，用户可以自定义选择是否开启这个选项
## why
当前编写文章时，时间可能很长，每次保存文章后，都有可能由于用户token过期而需要重新登录。

**Comment by ruibaby** [comment]
2.11.0 已经在文章编辑页面优化了这个问题，会每五分钟自动调用一次 /actuator/health 接口来保持会话。

see https://github.com/halo-dev/halo/pull/4949

**Comment by JohnNiang** [comment]
Duplicate with <https://github.com/halo-dev/halo/issues/2362>.

/close
