### ISSUE TITLE
手动缩放图片无法等比例缩放

### ISSUE THREAD

**Issue by Sakura-LF** [halo-dev/halo#4985]
### 系统信息

无

### 使用的哪种方式运行？

Docker Compose

## 现在手动缩放图无法等比例缩放，只会将图片拉伸或者挤压

> 2.11 和最新的 2.11.1 都有这个问题，之前是好的

![image](https://github.com/halo-dev/halo/assets/80140609/046d33b9-3546-4521-8950-3c37fb62b841)
## 具体情况如图所示

![GIF 2023-12-4 0-06-32](https://github.com/halo-dev/halo/assets/80140609/23b3fc7e-a3f2-4449-9537-41994cb55a61)

**Comment by ruibaby** [comment]
可以复现，这个功能似乎只在 Firefox 上正常。

/kind bug
/area editor
