### ISSUE TITLE
Walker 主题有 bug

### ISSUE THREAD

**Issue by yuanzhixiang** [halo-dev/halo#4986]
### 系统信息

- External url: http://blog.yuanzhixiang.com/
- Start time: 2023-12-04 02:43
- Version: 2.11.1
- Build time: 2023-12-02 22:53
- Git Commit: 54f77d5
- Java: IBM Semeru Runtime Open Edition / 17.0.9+9
- Database: MySQL Community Server - GPL / 8.0.31
- Operating system: Linux / 5.15.49-linuxkit-pr
- Activated theme: [Walker](https://halo.run/store/apps/app-GHgAR)
- Enabled plugins:
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [Willow Markdown 编辑器](https://github.com/guqing/willow-mde)
  - [Metrics Graph](https://github.com/guqing/plugin-metrics-graph)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)
  - [highlight.js 代码高亮](https://github.com/halo-sigs/plugin-highlightjs)
  - [ByteMD](https://github.com/ruibaby/plugin-bytemd)
  - [RSS](https://github.com/halo-sigs/plugin-feed)
  - [评论组件](https://github.com/halo-sigs/plugin-comment-widget)
  - [搜索组件](https://github.com/halo-sigs/plugin-search-widget)
  - [Sitemap](https://github.com/halo-sigs/plugin-sitemap)

### 使用的哪种方式运行？

Docker Compose

### 在线站点地址

https://blog.yuanzhixiang.com/moments

### 发生了什么？

walker 主题瞬间页面显示有 bug，见下图

<img width="909" alt="图片" src="https://github.com/halo-dev/halo/assets/25138766/bf5b21b9-8eff-46ec-89d7-de2f4ba150c1">

**Comment by ruibaby** [comment]
这是因为这里显示的是头像，但你没有设置或者头像链接请求不到，最终浏览器会显示 Alt 信息，这可能并不是一个问题。

**Comment by yuanzhixiang** [comment]
> 这是因为这里显示的是头像，但你没有设置或者头像链接请求不到，最终浏览器会显示 Alt 信息，这可能并不是一个问题。

了解，我设置了头像，但是不知道为什么不显示，我看看什么原因

**Comment by yuanzhixiang** [comment]
> 这个是 logo，瞬间是使用的个人头像。你需要在这里设置：
> <img alt="图片" width="543" src="https://private-user-images.githubusercontent.com/21301288/287580180-79693841-7762-48cc-b23e-ddb4453f9ee7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2NTk3NjAsIm5iZiI6MTcwMTY1OTQ2MCwicGF0aCI6Ii8yMTMwMTI4OC8yODc1ODAxODAtNzk2OTM4NDEtNzc2Mi00OGNjLWIyM2UtZGRiNDQ1M2Y5ZWU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDAzMTEwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1OWQ5NDE4NGFkNmJjMTNiYmNiZTcyYmYyY2U2ZDAwYTRmYmNlZmI0MDcxODBmMjAyYzYyNzQ5MmI2MzcwMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XVrLvLkVhE82ukZRLnqEeqKPYlJAEuHrdxOn9Rt9JK4">

成功了，感谢

**Comment by LIlGG** [comment]
> 您好，我在使用瞬间碰到了一个问题想资讯一下，瞬间在后台预览的时候和编辑的时候呈现的格式不太一样，比如下图中编辑时有空行，预览时没有空行，没有空行的预览看起来文字太过紧密，这里能优化成增加空行的版本么？

这个应该是需要在瞬间中优化的地方，可以去 moments 的仓库提 [issue](https://github.com/halo-sigs/plugin-moments/issues)
