### ISSUE TITLE
本地开发环境中console报错

### ISSUE THREAD

**Issue by Lyn4ever29** [halo-dev/halo#4989]
### 系统信息

访问不了console

### 使用的哪种方式运行？

Source Code

### 发生了什么？

![image](https://github.com/halo-dev/halo/assets/25952589/f618bdda-de4d-411c-87a6-aacb0f854fd7)

如图，我是重新下载了代码，重新执行pnpm install 的，还是这个错

### 相关日志输出

```shell
ERROR  Failed to resolve entry for package "@halo-dev/api-client". The package may have incorrect main/module/exports specified in its package.json. (x25)
```

**Comment by ruibaby** [comment]
执行 `pnpm dev` 之前有 `pnpm build:packages` 吗？

**Comment by Lyn4ever29** [comment]
> 执行 `pnpm dev` 之前有 `pnpm build:packages` 吗？

okok 我的问题，没问题了。谢谢
