### ISSUE TITLE
新创建的文章无法通过目录到文章对应位置

### ISSUE THREAD

**Issue by Sakura-LF** [halo-dev/halo#4994]
### 系统信息

无

### 使用的哪种方式运行？

Docker Compose

### 在线站点地址

https://www.sakurasss.top/archives/1701708209380

### 发生了什么？

# 今天给之前的文章重置目录结构的时候发现的
> 不管点那个都会直接回到顶部
https://www.sakurasss.top/archives/api-wang-guan#

![image](https://github.com/halo-dev/halo/assets/80140609/28ab5a0e-98cf-44d7-b203-046c10b67b75)

# 新创建的文章点目录没反应
版本是 2.11.1
> 主题是 Joe3，应该不是主题的问题
> 目前不知道是 2.11 就有的 bug，还是 2.11.1 之后的

https://www.sakurasss.top/archives/1701708209380
点 1. Test 还会直接返回底部
![image](https://github.com/halo-dev/halo/assets/80140609/71bf81e4-701e-4522-9104-3f81840e598c)

# 之前的文章是正常的
https://www.sakurasss.top/archives/go-zero-api-shi-yong

**Comment by masteranthoneyd** [comment]
同问, 我回滚到 2.10.2 发现也是无法跳转

**Comment by LIlGG** [comment]
已知问题，在重构默认编辑器 heading 时丢失了渲染后内容的 id。 已经提交了 PR 进行修复。 #4997 

/kind bug
/area console
/milestone 2.12.x
