### ISSUE TITLE
咨询从 1.x 升级上来时的 attachments 文件怎么做映射

### ISSUE THREAD

**Issue by yuanzhixiang** [halo-dev/halo#4996]
### 系统信息

- External url: http://blog.yuanzhixiang.com/
- Start time: 2023-12-04 02:43
- Version: 2.11.1
- Build time: 2023-12-02 22:53
- Git Commit: 54f77d5
- Java: IBM Semeru Runtime Open Edition / 17.0.9+9
- Database: MySQL Community Server - GPL / 8.0.31
- Operating system: Linux / 5.15.49-linuxkit-pr
- Activated theme: [Walker](https://halo.run/store/apps/app-GHgAR)
- Enabled plugins:
  - [Metrics Graph](https://github.com/guqing/plugin-metrics-graph)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)
  - [highlight.js 代码高亮](https://github.com/halo-sigs/plugin-highlightjs)
  - [ByteMD](https://github.com/ruibaby/plugin-bytemd)
  - [RSS](https://github.com/halo-sigs/plugin-feed)
  - [评论组件](https://github.com/halo-sigs/plugin-comment-widget)
  - [搜索组件](https://github.com/halo-sigs/plugin-search-widget)
  - [Sitemap](https://github.com/halo-sigs/plugin-sitemap)

### 使用的哪种方式运行？

Docker

### 发生了什么？

你好，我从 1.x 升级上来时发现在 attachments 中出现了 ~/.halo2/attachments/migrate-from-1.x/ 这个文件夹，而原本的图片在 migrate-from-1.x 中，这部份图片无法访问了。

例如 原本的文件 ~/.halo2/attachments/migrate-from-1.x/media/xxx.jpg，老的站点访问时填写的地址是 https://domain/media/xxx.jpg，现在在新站点无法访问，我发现只能访问 ~/.halo2/attachments/upload/ 目录下的文件，例如 ~/.halo2/attachments/upload/aaa.jpg 可以用 https://domain/upload/aaa.jpg 访问到，我应该如何恢复 https://domain/media/xxx.jpg 这种访问方式？

在 attachments 中做如下的配置也不生效

<img width="609" alt="图片" src="https://github.com/halo-dev/halo/assets/25138766/4b70fcb6-f266-433d-a2c1-1728fc0bbfb1">

**Comment by JohnNiang** [comment]
Hi @yuanzhixiang ，建议参考迁移文档：<https://docs.halo.run/getting-started/migrate-from-1.x#移动附件>。

/kind support

**Comment by Simple-Stark** [comment]
于今日完成了升级
![image](https://github.com/halo-dev/halo/assets/61400566/7dd4056a-9bf4-4654-9b0e-f961085aa033)
将 update（不包含 update 这个目录） 文件下的所有文件移动到指定文件夹可以恢复。

**Comment by yuanzhixiang** [comment]
> Hi @yuanzhixiang ，建议参考迁移文档：[https://docs.halo.run/getting-started/migrate-from-1.x#移动附件](https://docs.halo.run/getting-started/migrate-from-1.x#%E7%A7%BB%E5%8A%A8%E9%99%84%E4%BB%B6)。
> 
> 文件夹移动操作需要手动在服务器完成。
> 
> /kind support



> 于今日完成了升级 ![image](https://private-user-images.githubusercontent.com/61400566/288759795-7dd4056a-9bf4-4654-9b0e-f961085aa033.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5NTM0OTcsIm5iZiI6MTcwMTk1MzE5NywicGF0aCI6Ii82MTQwMDU2Ni8yODg3NTk3OTUtN2RkNDA1NmEtOWJmNC00NjU0LTliMGUtZjk2MTA4NWFhMDMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDEyNDYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlY2RjYzExY2QyY2ViODk4ZGNlYzYzODgzZDQ3MTM0OTZjNDk0MGFlMmI0ZDAzNWMyZDI4N2E5MTJkYjQyMTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yWOcTrAIFfjzfbKu_dVn8oHc2vcmqUqsiO2RCuKtR1Y) 将 update（不包含 update 这个目录） 文件下的所有文件移动到指定文件夹可以恢复。

我已经迁移过了好几个月了，最近才发现文章图片不生效，然后图片在 migrate-from-1.x 这个目录下面，感觉是当时迁移的时候迁移的程序有问题，没迁移我的文件？所以这种情况怎样解决？

**Comment by Simple-Stark** [comment]
不是没迁移，只是没有映射成功。
![image](https://github.com/halo-dev/halo/assets/61400566/94097d78-be16-4460-af77-1bc23b97dc59)
如图是我 1.x 的本地文件存储位置，我将其拷贝至 2.11 的指定目录下
![image](https://github.com/halo-dev/halo/assets/61400566/1c7efe23-0c25-4fb8-b285-63b102170b9e)
附件就能看到 1.x 的文件了

**Comment by yuanzhixiang** [comment]
> 是我 1.x 的本地文件存储位置，我将其拷贝至 2.

> @Simple-Stark 你这个好像是 1.x 的 static 目录，和附件应该无关，附件是在 upload。如果 1.x 有 static 目录，也需要将 static 移动到 2.x 的工作目录。

对，这个好像之前是 static 文件，这是我在用 halo 之前的文件，后面迁移好 halo 的之后直接放到静态文件里面就行了，然后 1.x 迁移到 2.x 的时候忘记是怎么操作的了，我前几天看之前博客图片失效了，然后在服务器上面找了一下，文件都在 ~/.halo2/attachments/migrate-from-1.x/* 下面，但是访问不到。

例如我要访问 ~/.halo2/attachments/migrate-from-1.x/media/cat/1.jpg，我用 https://xxx.com/migrate-from-1.x/media/cat/1.jpg 访问不到这部份文件。

实际上希望的效果是 https://xxx.com/media/cat/1.jpg 访问到文件，否则我所有文章的 图片路径都要修改才行，我之前有几百篇文章，工作量太大，这肯定是没法改了。所以就想资讯一下有没有什么别的方法恢复。

**Comment by ruibaby** [comment]
提供 migrate-from-1.x 的静态文件映射就是为了让 1.x 以前的文件访问路径可用，迁移之后并不需要修改以前的访问路径，新上传的附件也并不会上传到这个目录。所以你应该用 /upload/xx 访问，而不是 /media/xx。

@yuanzhixiang 建议截图一下你目前 migrate-from-1.x 目录的结构。

**Comment by Simple-Stark** [comment]
> @Simple-Stark 你这个好像是 1.x 的 static 目录，和附件应该无关，附件是在 upload。如果 1.x 有 static 目录，也需要将 static 移动到 2.x 的工作目录。

修改了截图

**Comment by yuanzhixiang** [comment]
> 或许修

没有修改上传目录，是在用 halo 之前的几百篇文章的图片我当时想直接迁移到 halo 上，所以当时发现后台我记得有个口子能上传到服务器的 static 里面，并且可以直接访问，所以当时就那么做了

**Comment by yuanzhixiang** [comment]
是在这个目录下面创建 static 文件夹，然后把文件移动进去就行了么

<img width="789" alt="图片" src="https://github.com/halo-dev/halo/assets/25138766/7429eba5-ab38-45b8-9318-9c02081b5a31">

**Comment by ruibaby** [comment]
> 是在这个目录下面创建 static 文件夹，然后把文件移动进去就行了么

对

**Comment by yuanzhixiang** [comment]
> > 是在这个目录下面创建 static 文件夹，然后把文件移动进去就行了么
> 
> 对

我试试
