### ISSUE TITLE
Halo上传附件，建议新增附件自动重命名功能

### ISSUE THREAD

**Issue by molaina-oiu** [halo-dev/halo#5000]
### Your current Halo version

 2.10.2

### Describe this feature

现在的情况是，附件上传之后本地文件叫什么名字，上传之后就叫什么名字。建议加一个选项“自动重命名”，选中之后，上传附件会自动重命名，比如重命名为 时间戳加随机数。有时候本地的图片会和服务器已经上传的图片名称，重名。如果出现重名目前会直接被覆盖，halo自带的文章编辑器可以 Ctrl V 图片，现在如果直接C V图片的话，图片名重复，之前的图片也会被覆盖掉

**Comment by ruibaby** [comment]
目前本地上传如果有文件重复是会重命名的，应该不会存在覆盖的问题。

<img width="340" alt="图片" src="https://github.com/halo-dev/halo/assets/21301288/18841ec4-f903-4c44-8bdb-cbdf84006039">

如果使用了的是外部存储，建议使用 S3 插件，可以支持。

**Comment by molaina-oiu** [comment]
> 目前s3插件支持这个功能，建议搭建minio配合s3插件使用



> 目前本地上传如果有文件重复是会重命名的，应该不会存在覆盖的问题。
> 
> <img alt="图片" width="340" src="https://private-user-images.githubusercontent.com/21301288/288349121-18841ec4-f903-4c44-8bdb-cbdf84006039.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NTU4NDQsIm5iZiI6MTcwMTg1NTU0NCwicGF0aCI6Ii8yMTMwMTI4OC8yODgzNDkxMjEtMTg4NDFlYzQtZjkwMy00YzQ0LThiZGItY2JkZjg0MDA2MDM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDA5MzkwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3OWY0ZmFhNTRjMzU4MGUzOTA1NTZlNWY1YmE2ZGFhYzVkMDk5ODE2ODQ1NGYzNmRkY2I5MjlmNTk4ODYyZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WaB7vRwidRehDOe_BuhrMXEu4KaS8E6ZWs0y0PgUeLI">
> 如果使用了的是外部存储，建议使用 S3 插件，可以支持。

使用的是插件oss，OSS的话，是要找插件那边吗
