### ISSUE TITLE
当使用 labelSelector 查询时如果 label 的 value 只有一位如 1 解析不到 value

### ISSUE THREAD

**Issue by guqing** [halo-dev/halo#5001]
### 系统信息

此问题不需要系统信息,因此不再提供

### 使用的哪种方式运行？

Docker

### 发生了什么？

如标题所述，原因是以下这一行判断有误导致
https://github.com/halo-dev/halo/blob/197c622b35bb7685312e612eee5fe28a2ad8f37b/api/src/main/java/run/halo/app/extension/router/selector/Operator.java#L15

### 附加信息

/kind bug
/area core

**Comment by JohnNiang** [comment]
/good-first-issue

两种修复方式：
1. `<` 更改为 `<=`
2. `selector.length() - 1` 更改为 `selector.length()`
