### ISSUE TITLE
文章发布时使用H1 标签 中文录入时 有bug

### ISSUE THREAD

**Issue by wongjull** [halo-dev/halo#5003]
### System information

<img width="1286" alt="image" src="https://github.com/halo-dev/halo/assets/26252021/645d4aaf-e14a-4b22-a558-f92b7e7c9e39">

### What is the project operation method?

Docker

### Your site address.

https://demo.halo.run/console/posts/editor?name=db0620bc-e7d0-4361-9ba7-846986ca20c2

### What happened?

我是使用演示站时发现的

### Relevant log output

```shell
其他h标签同样存在 应该是插件的问题
```

**Comment by ruibaby** [comment]
> 我发现2.10版本，代码片段页会有提示符号。

新问题建议提交新的 issue。
