### ISSUE TITLE
个人令牌不起作用

### ISSUE THREAD

**Issue by GodlessLiu** [halo-dev/halo#5006]
### 系统信息

- 外部访问地址: http://aifengliu.top
- 启动时间: 
- 版本: 2.11.1
- 构建时间: 2023-12-02 22:53
- Git Commit: 54f77d5
- Java: IBM Semeru Runtime Open Edition / 17.0.9+9
- 数据库: PostgreSQL / 15.4 (Debian 15.4-2.pgdg120+1)
- 操作系统: Linux / 4.18.0-193.14.2.el8_2.x86_64
- 已激活主题: [Earth](https://github.com/halo-dev/theme-earth.git)
- 已启动插件:
  - [应用市场](https://github.com/halo-dev/plugin-app-store)
  - [highlight.js 代码高亮](https://github.com/halo-sigs/plugin-highlightjs)
  - [lightgallery.js 灯箱](https://github.com/halo-sigs/plugin-lightgallery)
  - [OAuth2 认证](https://github.com/halo-sigs/plugin-oauth2)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [图库管理](https://github.com/halo-sigs/plugin-photos)
  - [Sitemap](https://github.com/halo-sigs/plugin-sitemap)
  - [RSS](https://github.com/halo-sigs/plugin-feed)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)

### 使用的哪种方式运行？

Docker Compose

### 在线站点地址

https://aifengliu.top

### 发生了什么？

当我进行google插件开发时，需要使用附件管理的个人令牌，于是去个人中心进行注册，并使用，但是遇到一个奇怪的现象，当我账户登录在线时，个人令牌起作用，退出登录后，个人令牌则不起作用了。网络状态码为401.

### 附加信息

![image](https://github.com/halo-dev/halo/assets/110895612/7386b709-aa46-45cb-81d8-df338a0c94d0)
上面为退出登录和登录的两个状态

**Comment by JohnNiang** [comment]
/kind support

请确保参考过文档：<https://github.com/halo-dev/halo/tree/main/docs/authentication#%E4%BD%BF%E7%94%A8%E6%96%B9%E5%BC%8F>。

如果出现 401 错误，应该是没有正确传递 Authorization 头。如果 PAT 没有权限则会返回 403 错误。建议提供一下出现 401 后的返回内容（包括 headers 和 response body）。

**Comment by GodlessLiu** [comment]
> /kind support
> 
> 请确保参考过文档：https://github.com/halo-dev/halo/tree/main/docs/authentication#%E4%BD%BF%E7%94%A8%E6%96%B9%E5%BC%8F。
> 
> 如果出现 401 错误，应该是没有正确传递 Authorization 头。如果 PAT 没有权限则会返回 403 错误。建议提供一下出现 401 后的返回内容（包括 headers 和 response body）。

两次携带的信息没有任何差别，区别在于第一次未登录

**Comment by JohnNiang** [comment]
Hi @GodlessLiu ，可能需要注意 `Bearer` 和 `Beaer` 的区别。
