### ISSUE TITLE
使用 Halo 部署的博客在此列出 #2

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#501]
> 由于上一个 issue 已经达到了 200 多评论，每次一评论将会有 200 多个账号收到 Github 的邮件通知，所以这类 issue 将定期 close，并重开。

> 如果你不想被 Github 的通知邮件打扰，建议评论之后点击右侧的 `Unsubscribe`。

### 往期

- [https://github.com/halo-dev/halo/issues/26](https://github.com/halo-dev/halo/issues/26)

如果你是用的 Halo，可以将你博客的地址贴出来，以供其他正在观望的用户查看具体效果。

格式如下：

博客名称：RyanWang's Blog
地址：[https://ryanc.cc](https://ryanc.cc)

**Comment by JohnNiang** [comment]
博客名称：JohnNiang's Blog
地址：<https://johnniang.me/>

**Comment by guqing** [comment]
博客名称: guqing's blog
地址: https://guqing.xyz

**Comment by NGLSL** [comment]
博客名称：我的Coding之路
地址：https://codedream.xin/

**Comment by dhstime** [comment]
微博名称:Hunter Code
http://www.dhsstrive.com/

**Comment by fennylv** [comment]
自豪的采用了Halo Blog，目前完善中
博客名称：mandla's blog
地址： http://mantuoluo88.com/

**Comment by yangjinhaoaa** [comment]
博客名称：小浩很可喜
地址：https://iot-me.club

**Comment by yanQuanfei** [comment]
博客名称：HelloWord
地址：http://blog.rusi.ink/

**Comment by xyaowh** [comment]
我想知道文章的标题英语单词大写问题怎么解决

**Comment by ruibaby** [comment]
@xyaowh Anatole？ 在主题设置。

**Comment by xuyuntian** [comment]
博客名称：记事本
地址： https://lightx.ltd

**Comment by xuyuntian** [comment]
博客名称：记事本
地址： https://lightx.ltd

**Comment by kuqili** [comment]
博客名称： Lxy Blog
地址： http://www.kuqili.top:8090/   （目前未备案）

**Comment by lybtt** [comment]
博客名称： 个人学习工作分享
地址： https://lllyyb.com

**Comment by wangming2674** [comment]
博客名称：Evan's Blog:laughing:
http://evanwang.top/

**Comment by F1ReKing** [comment]
博客名称：我的极客虫blog
地址：http://geekbug.xyz

**Comment by AF-lmf** [comment]
博客名称：秃来顺受
地址：https://www.limingfeng.top

友链请前往博客留言~

**Comment by mediocrePeople** [comment]
博客地址改成https的了，同时去掉了以前的增加端口号的访问方式，现地址为https://mediocrepeople.tpddns.cn/

**Comment by mediocrePeople** [comment]
使用了nginx做了反向代理，监听443端口，博客地址改成https的了，同时去掉了以前的增加端口号的访问方式，现地址为https://mediocrepeople.tpddns.cn/

**Comment by kuqili** [comment]
> 博客名称：秃来顺受
> 地址：https://www.limingfeng.top
> 
> 友链请前往博客留言~

个人简历部分太优秀了

**Comment by Damon-Yo** [comment]
博客名称：Damon's Blog
地址：https://www.damon.cool/

**Comment by Damon-Yo** [comment]
> 博客名称：秃来顺受
> 地址：https://www.limingfeng.top
> 
> 友链请前往博客留言~

大哥好秀呀

**Comment by JachinDu** [comment]
博客名称：Jachin's Boke
地址：http://jachindo.top:8090

**Comment by wang-song** [comment]
博客名称：wangsong's blog
地址：isong.fun

**Comment by AndrewElvis** [comment]
博客名称：Andrew’s Blog
地址：http://www.tocca.top

**Comment by ligyDt** [comment]
博客名称：简一
地址：https://hongmengyunstars.top

**Comment by qaiu** [comment]
博客名称：千百度
地址：https://blog.qaiu.top
欢迎留言，交换友联

**Comment by pikapiu** [comment]
博客名称：东方未白的小世界
地址：https://pkq.xyz

**Comment by miantiao5115** [comment]
博客名称：面条
地址：http://miantiao.online/

**Comment by removeif** [comment]
> 博客名称：秃来顺受
> 地址：https://www.limingfeng.top
> 
> 友链请前往博客留言~

哈哈 优秀

**Comment by zyao-genius** [comment]
博客名称：唯爱冠希
地址：https://zyao.club

**Comment by kkblock** [comment]
博客名称：Alex's Blog
地址：http://www.kchampion.top/

**Comment by feng-dan** [comment]
博客名称：Adrian
地址：https://oushuiying.com

**Comment by EthanLoving** [comment]
博客名称：﹏年華ゝ未央づ
地址：https://ethanloving.top

**Comment by rookiegao** [comment]
博客名称：learn data
地址：https://www.rookiegao.top/

**Comment by paopao7** [comment]
博客名称：itinfor
地址：https://java.itinfor.cn

**Comment by zdljy** [comment]
博客名称：ZGGJAVAHOME
地址：http://182.92.159.37:8090/

**Comment by cs-java** [comment]
博客名称：长生的梦呓
地址：https://shengjava.com/

**Comment by y836097668** [comment]
博客名称：Sherlock - 个人博客
地址：https://halo.sherlocky.com/

**Comment by JackSengKing** [comment]
> 博客名称：Jack King's Blog
> 地址：http://jackking.world/
Halo 很好用

**Comment by Lostars** [comment]
终于迁移过来了
https://minei.me

**Comment by ruibaby** [comment]
@Lostars 主题不错，分享下吗

**Comment by ruibaby** [comment]
@Lostars 主题不错，分享下吗

**Comment by Lostars** [comment]
> @Lostars 主题不错，分享下吗

来源是一个hexo主题：[hexo-theme-cactus](https://github.com/probberechts/hexo-theme-cactus)，我随便改了改弄了下
https://github.com/Lostars/halo-theme-cactus

**Comment by ilei131** [comment]
博客名称：Openwit启智
地址：https://www.openwit.net/
Halo真的很好用

**Comment by MuZiPeng** [comment]
博客名称： 办法总比困难多
地址： https://www.pippen.top

**Comment by JohnNiang** [comment]
> 博客名称： 办法总比困难多
> 地址： https://www.pippen.top

建议升级至最新版（1.3.1）。

**Comment by wooseng** [comment]
博客名称：殇之界
地址：https://wooseng.com

**Comment by lyqiangmny** [comment]
博客名称：郭儿的跋涉
地址：http://www.ruiyan.run

**Comment by Gxz-NGU** [comment]
博客名称：小小震的偏执
地址：https://xiaofeiyang.club

**Comment by codenow99** [comment]
博客名称：码在当下
地址：https://codenow.top

**Comment by sfyumi** [comment]
博客名称：Agent Digital
地址：https://agentd.cn

**Comment by cxying** [comment]
博客名称：Ying
地址：https://yingserver.cn
欢迎交换友链鸭~

**Comment by PIPIKAI** [comment]
博客名称：暮商之秋
地址：https://blog.kiass.top/

**Comment by ChoviWu** [comment]
我的怎么被删了，
https://choviwu.top 
2018年9月接入的

**Comment by ChoviWu** [comment]
我的怎么被删了，
博客名：奕仁
https://choviwu.top 
2018年9月接入的

**Comment by ruibaby** [comment]
@ChoviWu 该更新了

**Comment by ruibaby** [comment]
@ChoviWu 这是另外一个issue了

**Comment by 1542254356** [comment]
博客名：philhuan blog
https://hjwblog.com/

**Comment by AttackingBigCat** [comment]
博客名：白驹之过
https://landz.zone/
目前备案中

**Comment by lircs** [comment]
博客名称：lircS blog
地址：http://blog.lircs.com

**Comment by AF-lmf** [comment]
> > 博客名称：秃来顺受
> > 地址：https://www.limingfeng.top
> > 友链请前往博客留言~
> 
> 个人简历部分太优秀了

哈哈，抄的。

**Comment by AF-lmf** [comment]
> > 博客名称：秃来顺受
> > 地址：https://www.limingfeng.top
> > 友链请前往博客留言~
> 
> 大哥好秀呀

抄的抄的。

**Comment by zhangasia** [comment]
博客名称：胖子的技术博客
地址：www.zhangyazhou.top

**Comment by a1105013796** [comment]
博客名称：C.w Notes
地址：https://www.cwblog.ink

**Comment by abadfox233** [comment]
博客名称：狐狸的搬砖生活
地址：https://www.ironblog.cn

**Comment by MomentDerek** [comment]
博客名称：Moment的小小技术空间
地址：http://tech.momincong.xyz

**Comment by feitian124** [comment]
博客名称：TOP开发者社区
地址：https://www.topcoder.club/

**Comment by yangyang-zhang** [comment]
博客名称：洋洋的博客
地址：https://todobest.cn

**Comment by Sanarous** [comment]
博客名称：Sanarous's Blog
地址：https://bestzuo.cn

**Comment by Sanarous** [comment]
> 博客名称：秃来顺受
> 地址：https://www.limingfeng.top
> 
> 友链请前往博客留言~

你这个简历部分真的太秀了

**Comment by lomofu** [comment]
博客名称：LOMO PALACE
地址：https://www.lomofu.com/

**Comment by LIlGG** [comment]
博客名称：たかぎ
地址：https://lixingyong.com

Sakura。目前正在完善主题~打算将其作为halo的分支！欢迎各位大佬！！！

**Comment by ruibaby** [comment]
@LIlGG 欢迎分享这个主题哦。

**Comment by LIlGG** [comment]
@ruibaby 会的。目前还是开发阶段，第一版完成就会分享。不过现在也已经可以下载到了

**Comment by liweitao92** [comment]
http://www.itaoui.com

**Comment by wajncn** [comment]
王勤奋
https://javanet123.com

**Comment by corsoo** [comment]
Corso'blog
https://corso.run
欢迎友链交换

**Comment by likecy-yun** [comment]
博客名称：云中有鹿来
地址：https://www.likecy.cn

**Comment by PierceTsu** [comment]
博客名称：Patrick's Blog
地址：https://blog.yaoyuehome.com
欢迎友链交换

**Comment by likecy-yun** [comment]
已加.云中有鹿来:https://www.likecy.cn&nbsp;


云中有鹿来
18715706435@qq.com



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Patrick"<notifications@github.com&gt;; 
发送时间: 2020年6月28日(星期天) 晚上10:42
收件人: "halo-dev/halo"<halo@noreply.github.com&gt;; 
抄送: "无香［拒聊］"<1218524208@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [halo-dev/halo] 使用 Halo 部署的博客在此列出 @2 (#501)





 
博客名称：Patrick's Blog
 地址：https://blog.yaoyuehome.com
 欢迎友链交换

**Comment by hgmsq** [comment]
博客名称：IT技术分享社区
地址：https://programmerblog.xyz/
![小程序](https://user-images.githubusercontent.com/13517103/86131338-1e4a0c80-bb18-11ea-98f4-a3338d4c75b6.jpg)

**Comment by kfyidrig** [comment]
DIYBOY'S BLOG
http://blog.ieleven.xyz

**Comment by guankang1314** [comment]
博客名称：Qingtian's Blog
地址：https://qingtianblog.com

**Comment by sheiy** [comment]
博客名称：Sheiy's Blog
地址：https://blog.ownw.site

**Comment by Stars-One** [comment]
Stars-One的杂货小窝
地址：https://stars-one.site

**Comment by codesensi** [comment]
博客名称：龙猫汪汪汪
地址：https://codesensi.top/

**Comment by Gray-p** [comment]
博客名称：明明同学的博客
地址：https://oiyatsm.top

**Comment by kiritoghy** [comment]
博客名称：kiritoghy's blog
地址：https://www.kiritoghy.cn

**Comment by manction** [comment]
博客名称：月光海岸
地址：[https://m.xiaobaipb.com](https://m.xiaobaipb.com)
![mp](https://user-images.githubusercontent.com/9378928/92199971-2ec98b00-eeab-11ea-8c2d-ea1473d637e0.jpg)

**Comment by zwc456baby** [comment]
名称： zhouzhou 的博客
地址：https://zwc365.com/

友链求换

**Comment by xianfengoby** [comment]
博客名称：钓鱼喵
地址：https://xf.fengma.xin/

**Comment by Planeswalker23** [comment]
博客名称：JavaGeekers
地址：http://javageekers.club/
----
Halo实在是太顶了！
