### ISSUE TITLE
全局代码注入不生效

### ISSUE THREAD

**Issue by heihei180** [halo-dev/halo#5013]
### 系统信息

版本v2.10

- 外部访问地址：
- 启动时间：2023-11-20 16:08
- 版本
- 构建时间：2023-11-20 15:55
- Git Commit：8453ff6
- Java：OpenJDK Runtime Environment / 17.0.1+12-39
- 数据库：Source distribution / 8.0.32
- 操作系统：Linux / 5.10.134-15.al8.x86_64
  

### 使用的哪种方式运行？

Fat Jar

### 发生了什么？

代码注入=>全局head标签
输入
`<meta name="referrer" content="no-referrer" />` 

发现在文章页面生效了，但是在编辑界面，这行标签并不会被注入

### 附加信息

![配置页截图](https://github.com/halo-dev/halo/assets/38102241/d8ba70f9-4cd5-4146-bd71-090290fd429a) 
![编辑页head标签代码](https://github.com/halo-dev/halo/assets/38102241/b1c6ec28-5992-4bea-b1eb-671bebdbc19b)

**Comment by ruibaby** [comment]
当前代码注入不会对 Console 生效。

**Comment by ruibaby** [comment]
> > 当前代码注入不会对 Console 生效。
> 
> 您好，感谢回复，这个是否有修复计划呢？

这并不是一个问题，计划就是不支持在 Console 让用户注入代码，这很可能因为输入了有问题的 JS 代码导致 Console 访问异常。

你当前的需要注入 ` <meta name="referrer" content="no-referrer" />` 解决什么问题？
