### ISSUE TITLE
目前邮箱填写即可注册，建议添加邮箱验证完成后才能注册。

### ISSUE THREAD

**Issue by zqzld** [halo-dev/halo#5016]
### 你当前使用的版本

2.11.0

### 描述一下此特性

目前邮箱填写即可注册，建议添加邮箱验证完成后才能注册。

**Comment by ruibaby** [comment]
可以考虑在系统设置的用户设置中提供这个选项，这种方式应该可以更好地防止恶意注册。

/kind feature
/area core
/area console

**Comment by mashirot** [comment]
> 可以考虑在系统设置的用户设置中提供这个选项(注册是否需要验证邮箱)，这种方式应该可以更好地防止恶意注册。
> 
> /kind feature /area core /area console

1. 在后台 设置-用户设置 加一个checkbox，在新用户注册时是否强制验证邮箱regRequireVerifyEmail
    - true 在后台邮件通知相关填写时才能开启，
        - 请求/signup时返回regRequireVerifyEmail
        - 根据regRequireVerifyEmail渲染不同组件，true 多个发送验证码的btn和填写验证码的input
    - false 与现在行为相同
2. 在后台 设置-用户设置 加一个类似于element-plus的[动态标签](https://element-plus.org/zh-CN/component/tag.html#%E5%8A%A8%E6%80%81%E7%BC%96%E8%BE%91%E6%A0%87%E7%AD%BE)，用于填写allowedEmailProvider，或者搞个input填正则
目前想法是这样的，看看可行吗

**Comment by JohnNiang** [comment]
IMO，注册流程不变，只需在登录时验证是否验证过邮箱来决定登录成功与否。

**Comment by mashirot** [comment]
> IMO，注册流程不变，只需在登录时验证是否验证过邮箱来决定登录成功与否。

这样与“邮箱验证完成后才能注册”似乎不符，逻辑上更接近于“填写邮箱可以注册，邮箱验证完成后才能进行后续交互”，当然应该符合题主要的效果，并且后端不用改，交给前端判断就行，你们觉得这样更好的话给我那个pr关了就行

**Comment by JohnNiang** [comment]
暂时先讨论一下，也并非由我一个人决定。

Hi @mashirot ，你的实现也是一个非常好的方案，正如这里所说：<https://github.com/halo-dev/halo/issues/5016#issuecomment-1845346736>，可以有效防止恶意注册。

对于已经有注册用户的 Halo 站点，https://github.com/halo-dev/halo/pull/5320 的实现似乎也只能限制后注册的用户，此前已注册未验证邮箱的用户仍然能够正常登录使用，这里是否需要处理呢？
