### ISSUE TITLE
halo 2.10.2 升级到 2.11.2， 备份恢复失败

### ISSUE THREAD

**Issue by github-ayio** [halo-dev/halo#5017]
### 系统信息

- 外部访问地址：
- 启动时间：2023-12-07 21:31
- 版本
- 构建时间：2023-11-02 18:01
- Git Commit：2ccf811
- Java：OpenJDK Runtime Environment / 17.0.9+9
- 数据库：H2 / 2.1.214
- 操作系统：Linux / 3.10.0-1160.99.1.el7.x86_64
  

### 使用的哪种方式运行？

Docker

### 在线站点地址

ado.js.cn

### 发生了什么？

docker部署，halo版本号 10.2, 想升级到11.2，
在10.2下利用系统的“创建备份”备份数据， 然后用docker进行的全新安装，安装版本号为11.2，
安装并初始化完成后，用新版本备份恢复10.2备份数据，上传验时候验证报错，
![Snipaste_2023-12-07_21-25-17](https://github.com/halo-dev/halo/assets/23180747/459aae2d-679f-481b-835a-42cec5bd28b3)

**Comment by github-ayio** [comment]
打扰一下，增强备份（Backup IMproved）插件能自动备份到自己的群晖nas吗？demo演示站没权限看到这个插件 @ruibaby

**Comment by ruibaby** [comment]
> 打扰一下，增强备份（Backup IMproved）插件能自动备份到自己的群晖nas吗？demo演示站没权限看到这个插件 @ruibaby 

如果你的网站能够正常连接到你的 Nas，你可在 Nas 搭建一个 Minio 之类的服务，然后就可以在 Halo 这边配置了。

**Comment by github-ayio** [comment]
> > 打扰一下，增强备份（Backup IMproved）插件能自动备份到自己的群晖nas吗？demo演示站没权限看到这个插件 @ruibaby
> 
> 如果你的网站能够正常连接到你的 Nas，你可在 Nas 搭建一个 Minio 之类的服务，然后就可以在 Halo 这边配置了。

了解，这就去搭个MinIO
