### ISSUE TITLE
文章归档会支持到日的查询？

### ISSUE THREAD

**Issue by chengzhongxue** [halo-dev/halo#5022]
### 你当前使用的版本

2.11.1

### 描述一下此特性

目前文章归档只能支持到月份查询
![image](https://github.com/halo-dev/halo/assets/89380218/a33039cf-2dd2-43cc-9d07-901a41c91eb1)
能支持到日期查询？
![image](https://github.com/halo-dev/halo/assets/89380218/276a720e-9dbf-4b48-98a8-57511bb9aeaa)

**Comment by guqing** [comment]
查询到天的具体需求是什么呢，目前真的有多少用户一天会写很多文章吗几乎根据天都查询不出文章来显示的就很稀疏也不好管理

**Comment by chengzhongxue** [comment]
我做了个这样的需求
![image](https://github.com/halo-dev/halo/assets/89380218/9a9dfa5a-e807-4c2a-a93e-e8596a08f60f)
如果不太行就算了

**Comment by guqing** [comment]
目前你可以试试通过查询参数的方式来自己过滤，比如访问 /archives/2023/11?archive_day=05 然后在页面获取到archive_day查询参数就将11月的数据中不是05日的数据过滤掉只显示当日的如果没有参数则显示所有，毕竟你这个日历上会有红点标记是否有文章所以还是会需要查询到整月的文章

**Comment by chengzhongxue** [comment]
行吧，那也只能这样弄了
