### ISSUE TITLE
网页中的行内代码渲染错误

### ISSUE THREAD

**Issue by LinXu-LinXu** [halo-dev/halo#5027]
### 系统信息

- 外部访问地址: http://localhost:8090
- 启动时间: 2023-12-09 22:28
- 版本: 2.11.2
- 构建时间: 2023-12-07 16:29
- Git Commit: 97b5f72
- Java: IBM Semeru Runtime Open Edition / 17.0.9+9
- 数据库: MySQL Community Server - GPL / 8.2.0
- 操作系统: Linux / 5.15.0-86-generic
- 已激活主题: [Earth](https://github.com/halo-dev/theme-earth.git)
- 已启动插件:
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)

### 使用的哪种方式运行？

Docker

### 在线站点地址

http://47.120.7.184:8090/

### 发生了什么？

使用的是默认的 earth 主题和默认的编辑器
默认编辑器中渲染的样式：
![编写](https://github.com/halo-dev/halo/assets/74867256/841714f1-6a1b-49f6-8f01-7a81d1fa84c1)

网页中渲染的样式：
![渲染](https://github.com/halo-dev/halo/assets/74867256/57fd0bf8-5b71-483c-8fde-8ad93f4b2a2e)

安装的插件：
![插件](https://github.com/halo-dev/halo/assets/74867256/d89f3a4d-da20-469f-8eee-1ec2ebe1de19)

**Comment by LinXu-LinXu** [comment]
开启截图中的第二个插件后，代码块可以渲染成指定的格式，但是行内代码仍然渲染错误
![渲染2](https://github.com/halo-dev/halo/assets/74867256/797dc9ce-5a68-44dd-aa32-feb73335f3e3)
![插件2](https://github.com/halo-dev/halo/assets/74867256/eb5d6993-9a59-4b1b-b310-1aa426618cfc)
![设置](https://github.com/halo-dev/halo/assets/74867256/a24552f3-266e-4735-993c-62f3e6161c97)

**Comment by LinXu-LinXu** [comment]
在theme-earth找到了解答 [https://github.com/halo-dev/theme-earth/issues/42](https://github.com/halo-dev/theme-earth/issues/42)
这里的意思是实现了编辑器内的单行代码渲染，但是没有实现页面内的吗？ [https://github.com/halo-sigs/richtext-editor/pull/15](https://github.com/halo-sigs/richtext-editor/pull/15)

**Comment by JohnNiang** [comment]
Hi @LinXu-LinXu ，建议持续跟进 <https://github.com/halo-dev/theme-earth/issues/42>。编辑器的`行内代码渲染`已经搞定了，不过主题还需要做相应的优化。

/area theme
/triage duplicate

**Comment by ruibaby** [comment]
> 在theme-earth找到了解答 [https://github.com/halo-dev/theme-earth/issues/42](https://github.com/halo-dev/theme-earth/issues/42)
> 
> 这里的意思是实现了编辑器内的单行代码渲染，但是没有实现页面内的吗？ [https://github.com/halo-sigs/richtext-editor/pull/15](https://github.com/halo-sigs/richtext-editor/pull/15)

说法有歧义，默认主题现在是渲染了行内样式的，并不是没有实现。只是因为我们用的 Tailwindcss Typography 故意将行内样式渲染成了 Markdown 语法的样子。

**Comment by ruibaby** [comment]
后续请关注：https://github.com/halo-dev/theme-earth/pull/132

/close
