### ISSUE TITLE
连接外部mysql数据库部署后表现异常

### ISSUE THREAD

**Issue by adozhao** [halo-dev/halo#5031]
### 系统信息

外部访问地址: https://xxxx:8090/ #本地nas尝试部署，不方便暴露地址
启动时间: 2023-12-11 13:43
版本: 2.11.2
构建时间: 2023-12-07 16:29
Git Commit: https://github.com/halo-dev/halo/commit/97b5f7290904b318a41261c34332d84aa371c7eb
Java: IBM Semeru Runtime Open Edition / 17.0.9+9
数据库: MySQL Community Server - GPL / 8.0.33
操作系统: Linux / 4.4.302+
已激活主题: [Earth](https://github.com/halo-dev/theme-earth.git)
已启动插件:

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

利用docker-compose连接已有的外部数据库mysql，成功安装，但运行不正常，数据库好像没解包？日志也有mysql相关错误~
![image](https://github.com/halo-dev/halo/assets/23180747/943b704e-04c1-45fd-ac21-7bd7847b1570)
![image](https://github.com/halo-dev/halo/assets/23180747/6e25cb98-99d4-4547-9858-e410263185dd)

### 相关日志输出

```shell
日志见附件
```

### 附加信息

[halo-log-2023-12-11 14_00.log](https://github.com/halo-dev/halo/files/13631669/halo-log-2023-12-11.14_00.log)

**Comment by github-ayio** [comment]
mysql信息：
![image](https://github.com/halo-dev/halo/assets/23180747/253ef288-9df1-4f5b-a40c-9195d3b88267)

**Comment by JohnNiang** [comment]
关键错误日志：

```java
Caused by: run.halo.app.infra.exception.NotFoundException: 404 NOT_FOUND "No primary menu found"
```

建议检查是否有菜单，如果没有的话建议自己手动创建一个，并设置为主菜单。

另外，从 Issue 的描述中，没有看到“表现异常”的描述，比如某个页面无法访问，期待提交更多的信息。

/triage needs-information

**Comment by github-ayio** [comment]
数据全部没有初始化进去，除了console里面看到的页面路由能正常切换，其他所有操作都是异常的，整个数据库就一张表
![image](https://github.com/halo-dev/halo/assets/23180747/0844684a-7804-45b9-9fe3-836e8a8973ee)
所以可能是数据库哪里有问题，日志有数据库的相关报错，所以我需要你们帮助 @JohnNiang

**Comment by github-ayio** [comment]
1.我安装的是 2.11.2版本，为嘛没有应用市场呢？
2.生产是docker 安装的2.11.2，默认的h2数据库，能通过备份然后在mysql数据库的环境下恢复备份么？
@JohnNiang

**Comment by ruibaby** [comment]
> 1.我安装的是 2.11.2版本，为嘛没有应用市场呢？ 2.生产是docker 安装的2.11.2，默认的h2数据库，能通过备份然后在mysql数据库的环境下恢复备份么？(试了下，貌似可以) @JohnNiang

1. 应用市场在 2.10 才作为预设插件，如果是从 2.10 一下版本升级上来的，需要手动安装。https://www.halo.run/store/apps/app-VYJbF
2. 文档已经提及，备份恢复功能不限制数据库。https://docs.halo.run/user-guide/backup

如果有其他问题，请单独提交 issue，如果当前 issue 已经解决，我将关闭此 issue。

/close

**Comment by github-ayio** [comment]
我是直接docker-compose安装的2.11版本，没有发现应用市场 @ruibaby 
![image](https://github.com/halo-dev/halo/assets/23180747/1383224e-9dac-411c-a661-e5b63418aeec)

**Comment by JohnNiang** [comment]
Hi @github-ayio ，尝试重启一下“应用市场”插件，并强制刷新一下页面。

**Comment by ruibaby** [comment]
> 我是直接docker-compose安装的2.11版本，没有发现应用市场 @ruibaby 

从你截图来看，应用市场插件是安装了的，建议检查你的前置代理（Nginx、CDN、内网穿透等）是否有缓存设置。

**Comment by github-ayio** [comment]
我在云服务器上docker-compose部署的mysql，用HeidiSQL正常连接，进入mysql的/bin用命令也是可以连接数据库，但是我用halo应用去连接数据库就报错，搞了几个小时搞不定不知道哪里的问题。Halo也是docker-compose部署的，连接docker-compose单独部署的mysql.
麻烦两位大佬帮我看下大概咋回事，@ruibaby @JohnNiang  ❀
[logs.txt](https://github.com/halo-dev/halo/files/13636618/logs.txt)

**Comment by LinQi57** [comment]
> 关键错误日志：
> 
> ```java
> Caused by: run.halo.app.infra.exception.NotFoundException: 404 NOT_FOUND "No primary menu found"
> ```
> 
> 建议检查是否有菜单，如果没有的话建议自己手动创建一个，并设置主菜单。
> 
> 另外，从 Issue 的描述中，没有看到“表现异常”的描述，比如某些页面无法访问，期待提交更多的信息。
> 
> /分类需求信息

我也遇到这个报错，请问菜单要怎么检查，如何手动创建主菜单。
