### ISSUE TITLE
编辑粘贴图片BUG

### ISSUE THREAD

**Issue by githubgeekrabbit** [halo-dev/halo#5035]
### 系统信息

在设置界面创建的文章就可以粘贴图片，而在用户界面创建的文章粘贴图片就报错
<img width="1514" alt="iShot_2023-12-11_23 32 42" src="https://github.com/halo-dev/halo/assets/45820964/5d0aa5c2-03b8-4f5e-9951-427d85e40426">
<img width="1602" alt="iShot_2023-12-11_23 37 01" src="https://github.com/halo-dev/halo/assets/45820964/026a283e-47c9-4365-90be-482e6299252c">

### 使用的哪种方式运行？

Docker

### 在线站点地址

https://demo.halo.run/

### 发生了什么？

在设置界面创建的文章就可以粘贴图片，而在用户界面创建的文章粘贴图片就报错
<img width="1514" alt="iShot_2023-12-11_23 32 42" src="https://github.com/halo-dev/halo/assets/45820964/5d0aa5c2-03b8-4f5e-9951-427d85e40426">
<img width="1602" alt="iShot_2023-12-11_23 37 01" src="https://github.com/halo-dev/halo/assets/45820964/026a283e-47c9-4365-90be-482e6299252c">

### 相关日志输出

```shell
在设置界面创建的文章就可以粘贴图片，而在用户界面创建的文章粘贴图片就报错
<img width="1514" alt="iShot_2023-12-11_23 32 42" src="https://github.com/halo-dev/halo/assets/45820964/5d0aa5c2-03b8-4f5e-9951-427d85e40426">
<img width="1602" alt="iShot_2023-12-11_23 37 01" src="https://github.com/halo-dev/halo/assets/45820964/026a283e-47c9-4365-90be-482e6299252c">
```

**Comment by JohnNiang** [comment]
Hi @githubgeekrabbit ，感谢反馈问题！

我确认在未创建文章的状态下，在个人中心的文章模块中直接上传图片会出现以上错误。可能的原因是上传图片前自动创建文章的数据中没有包含文章标题。 @halo-dev/sig-halo-console 

/kind bug
/area console

**Comment by githubgeekrabbit** [comment]
还有就是，用户模式下，文章不会自动保存，切出去再回来写的东西就全没了

**Comment by JohnNiang** [comment]
> 还有就是，用户模式下，文章不会自动保存，切出去再回来写的东西就全没了

Hi @githubgeekrabbit ，再次感谢反馈！不过这个问题和当前 Issue 没有直接关联，建议提交新的 Issue 跟踪。

**Comment by ruibaby** [comment]
https://github.com/halo-dev/halo/blob/03ef4bbaaac030678f452f473463193041e5844c/console/uc-src/modules/contents/posts/PostEditor.vue#L341-L350

需要在这里自动设置 title 和 slug，参考：https://github.com/AeroWang/halo/blob/03ef4bbaaac030678f452f473463193041e5844c/console/console-src/modules/contents/posts/PostEditor.vue#L148-L154

/good-first-issue
