### ISSUE TITLE
普通用户编辑文章不会自动保存

### ISSUE THREAD

**Issue by githubgeekrabbit** [halo-dev/halo#5036]
### 系统信息

普通用户编辑文章不会自动保存，不小心切换或者网络卡顿直接就导致编写的文本全部丢失了

### 使用的哪种方式运行？

Docker

### 发生了什么？

普通用户编辑文章不会自动保存，不小心切换或者网络卡顿直接就导致编写的文本全部丢失了

### 相关日志输出

```shell
普通用户编辑文章不会自动保存，不小心切换或者网络卡顿直接就导致编写的文本全部丢失了
```

### 附加信息

普通用户编辑文章不会自动保存，不小心切换或者网络卡顿直接就导致编写的文本全部丢失了

**Comment by JohnNiang** [comment]
感谢在这里反馈问题！

自动保存功能在 Console 端已经实现完整了，不过在实现个人中心的时候缺失了这个功能，期望能够在 2.12.0 中发布此功能。 @halo-dev/sig-halo-console 

/kind improvement
/area console
/milestone 2.12.x

**Comment by ruibaby** [comment]
Console 已经封装了 useContentCache 和 useAutoSaveContent，可以参考 https://github.com/halo-dev/halo/blob/03ef4bbaaac030678f452f473463193041e5844c/console/console-src/modules/contents/posts/PostEditor.vue#L371-L389 进行适配。

/good-first-issue
