### ISSUE TITLE
docker-compose执行报错

### ISSUE THREAD

**Issue by github-ayio** [halo-dev/halo#5038]
### 系统信息

docker-compose(halo + mysql)全新安装

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

执行docker-compose up -d报错
![image](https://github.com/halo-dev/halo/assets/23180747/8f24dbcc-41e5-4fcd-a0cd-ee1df027d321)

### 相关日志输出

```shell
[root@VM-12-15-centos haloo]# docker-compose up -d
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.halo.healthcheck value Additional properties are not allowed ('start_period' was unexpected)
services.halodb.healthcheck value Additional properties are not allowed ('start_period' was unexpected)
services.halo.depends_on contains an invalid type, it should be an array
```

**Comment by guqing** [comment]
你的 docker compose 版本号是多少呢使用 `docker-compose -v` 查看

/kind needs-information

**Comment by github-ayio** [comment]
> 你的 docker compose 版本号是多少呢使用 `docker-compose -v` 查看
> 
> /kind needs-information

1.10.0

**Comment by github-ayio** [comment]
> 你的 docker compose 版本号是多少呢使用 `docker-compose -v` 查看
> 
> /kind needs-information

升级compose版本后执行成功，服务正常启动，非常感谢!
