### ISSUE TITLE
feat: 附件分类&可自定义选择存储位置

### ISSUE THREAD

**Issue by xtherk** [halo-dev/halo#504]
## 概述
1. 希望增加在附件中新建文件夹功能，方便对附件进行管理归纳。
2. 上传文件时可以选择存储位置，例如：选择上传到本地或者又拍云等云存储。

**Comment by JohnNiang** [comment]
1. 这一个在这里已经提到了：<https://github.com/halo-dev/halo/issues/427>；
2. 这个功能确实可以提供。

**Comment by Yuukion** [comment]
@JohnNiang 
1. 抱歉，疏忽了没看到，重复提到了。

**Comment by JohnNiang** [comment]
@Yuukion 没有的，是我刚刚 Reopen 了，不知道为什么今天被我 close 了。It's my fault.

**Comment by ruibaby** [comment]
2.0 已经实现分组和上传时选分组以及策略：https://github.com/halo-dev/halo/releases/tag/v2.0.0

/close
