### ISSUE TITLE
Lucene不能在64位jvm上正确计算对象大小，这些jvm不是基于Hotspot或兼容的实现。 

### ISSUE THREAD

**Issue by AKAOOK** [halo-dev/halo#5041]
### System information

Lucene cannot correctly calculate object sizes on 64bit JVMs that are not based on Hotspot or a compatible implementation.

### What is the project operation method?

Docker

### What happened?

Lucene cannot correctly calculate object sizes on 64bit JVMs that are not based on Hotspot or a compatible implementation.

**Comment by JohnNiang** [comment]
Hi @AKAOOK ，目前，这只是一个警告级别的日志，暂时不会影响系统的正常运行，具体细节请参考：<https://github.com/apache/lucene/pull/572>。

/triage needs-information

**Comment by JohnNiang** [comment]
I'm going to close the issue. Please feel free to reopen this issue if you have any feedback.

/close
