### ISSUE TITLE
默认编辑器编辑BUG

### ISSUE THREAD

**Issue by Stonewalling** [halo-dev/halo#5042]
### 系统信息

2.11.0

### 使用的哪种方式运行？

Docker Compose

### 在线站点地址

https://blog.micromatrix.cf/

### 发生了什么？

在默认编辑器里面编辑文章。我输入了## 然后按了tab之后出现二级标题，然后我输入文字就会出现紊乱

**Comment by LIlGG** [comment]
/triage duplicate

See #4970 

在 2.11.1 中修复了这个问题，建议使用最新的 2.11.2 版本

https://github.com/halo-dev/halo/releases/tag/v2.11.2

/close
