### ISSUE TITLE
我复制的图片粘贴不出来，我在语雀复制过来的图片显示的是图片的名称:image.png

### ISSUE THREAD

**Issue by fenhuahua** [halo-dev/halo#5043]
### 系统信息

https://www.yuque.com/yuque/blog/negoo054vqrgfon8
我是在这复制的图片

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

![image](https://github.com/halo-dev/halo/assets/153573296/dec4aa40-dbe1-48f2-b734-c7c2eac21999)
我复制上面的图片得到了下面的图片，我怎么才能直接复制过去？
![image](https://github.com/halo-dev/halo/assets/153573296/51e5c6db-f0e4-4629-8470-9f3dfe7942c2)

### 相关日志输出

```shell
1Panel-halo-8QY5  | 2023-12-13T10:17:21.871+08:00  INFO 7 --- [undedElastic-23] h.a.c.e.a.e.LocalAttachmentUploadHandler : Wrote attachment image.png into /root/.halo2/attachments/upload/image-xutw.png
1Panel-halo-8QY5  | 2023-12-13T10:20:30.102+08:00  INFO 7 --- [undedElastic-20] h.a.c.e.a.e.LocalAttachmentUploadHandler : Wrote attachment image.png into /root/.halo2/attachments/upload/image-naed.png
1Panel-halo-8QY5  | 2023-12-13T10:20:35.024+08:00  INFO 7 --- [undedElastic-25] h.a.c.e.a.e.LocalAttachmentUploadHandler : Wrote attachment image.png into /root/.halo2/attachments/upload/image-grxc.png
1Panel-halo-8QY5  | 2023-12-13T10:20:39.817+08:00  INFO 7 --- [undedElastic-20] h.a.c.e.a.e.LocalAttachmentUploadHandler : Wrote attachment image.png into /root/.halo2/attachments/upload/image-swrp.png
```

### 附加信息

![image](https://github.com/halo-dev/halo/assets/153573296/ba5d0cb2-462c-4fbf-b5a4-0c78c3937b83)

**Comment by JohnNiang** [comment]
Hi @fenhuahua ，感谢在这里反馈问题！

图片无法显示的原因是因为“语雀”的图片服务开启了防盗链，正常情况下，无法被第三方网站直接引用。解除限制的方法请参考：<https://github.com/halo-dev/halo/issues/3064>。

当然，也可以可以在附件管理中上传图片，再在编辑器中选择附件。

/triage duplicate

**Comment by fenhuahua** [comment]
非常感谢，你能及时回复，我明白了其中道理，用户角色做了区分，编辑者无法上传图片

**Comment by JohnNiang** [comment]
这里的权限似乎有点问题，“编辑者”和“作者”应该需要“附件上传”的权限的。 @halo-dev/sig-halo ，你们觉得呢？

**Comment by ruibaby** [comment]
> 这里的权限似乎有点问题，“编辑者”和“作者”应该需要“附件上传”的权限的。 @halo-dev/sig-halo ，你们觉得呢？

可以，但 issue 作者的问题可能不是没有上传权限，如果没有权限，应该不会显示裂图。可能还是和 referrer 策略有关。

**Comment by fenhuahua** [comment]
> 这里的权限似乎有点问题，"编辑者"和"作者"应该需要"附件上传"的权限的。@halo-dev/sig-halo ，你们觉得呢？
附件可以上传很多东西，脚本之类的，如果能连接就麻烦了，这个上传附件的权限可以由超级管理员分配吗？

**Comment by ruibaby** [comment]
> 附件可以上传很多东西，脚本之类的，如果能连接就麻烦了，这个上传附件的权限可以由超级管理员分配吗？

你可以自定义角色来自行决定。

![image](https://github.com/halo-dev/halo/assets/21301288/8f21e1b0-1309-4784-a349-49559011721f)

**Comment by JohnNiang** [comment]
I'm going to close the issue. Please feel free to reopen this issue if you have any feedback.

/close
