### ISSUE TITLE
Bubble menu of editor is covered by tool bar

### ISSUE THREAD

**Issue by JohnNiang** [halo-dev/halo#5044]
### System information

- External url: https://www.halowrite.com/
- Start time: 2023-12-04 12:18
- Version: 2.11.1
- Build time: 2023-12-02 22:53
- Git Commit: 54f77d5
- Java: IBM Semeru Runtime Open Edition / 17.0.9+9
- Database: PostgreSQL / 15.3
- Operating system: Linux / 5.4.225-200.el7.x86_64
- Activated theme: [Walker](https://halo.run/store/apps/app-GHgAR)

### What is the project operation method?

Docker

### What happened?

Please see the screenshot below. Bubble menu of editor is covered by tool bar when I insert an attachment at the first line.

/kind bug
/area editor

### Additional information

<img width="989" alt="image" src="https://github.com/halo-dev/halo/assets/16865714/645a6a91-c1b2-42b9-90e3-be4dd6e9f23a">

**Comment by LIlGG** [comment]
/triage duplicate

See #4869

**Comment by JohnNiang** [comment]
Sorry for raising the duplicate issue.

/close
