### ISSUE TITLE
编辑器支持代码编辑器，支持html、js、css等等渲染

### ISSUE THREAD

**Issue by huasio** [halo-dev/halo#5046]
### 你当前使用的版本

latest

### 描述一下此特性

编写页面的时候，需要编写html、css、js，但是现有的编辑器会经过处理，不会渲染。

![image](https://github.com/halo-dev/halo/assets/23445537/ad19f906-3ca9-487e-8fcf-4e6659e8960f)

**Comment by wan92hen** [comment]
可以试一下这个插件。
https://www.halo.run/store/apps/app-NgHnY

**Comment by huasio** [comment]
> 可以试一下这个插件。 https://www.halo.run/store/apps/app-NgHnY

尝试了下，有点差缺补漏的样子，但也能做到效果，感谢！

**Comment by ruibaby** [comment]
> 尝试了下，有点差缺补漏的样子

富文本编辑器直接让用户操作 html 本身就不是一个好主意，提供这个插件就是为了不时之需。
