### ISSUE TITLE
Remind users who are using H2 database in console

### ISSUE THREAD

**Issue by JohnNiang** [halo-dev/halo#5047]
### Your current Halo version

2.12.0-SNAPSHOT

### Describe this feature

Too many people who are using H2 database in production environment encountered an error `Caused by: org.h2.mvstore.MVStoreException: File is corrupted`, which is annoying, even thought we pointed it out in the official documentation.

- https://github.com/halo-dev/halo/issues/4982
- https://github.com/halo-dev/halo/issues/5029
- https://github.com/halo-dev/halo/issues/5045

H2 database is very convinient for users who want to have a try or develop, but it's not recommented to use it in production environment. So I request to remind users who are using H2 database in console to be aware of dangers of using H2 database.

### Additional information

/area console
/kind improvement

**Comment by ruibaby** [comment]
<img width="795" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/ce302de3-7e94-430f-891f-5f9cbad684b4">

I will add an alert here.
