### ISSUE TITLE
个人中心用户登录方式显示问题

### ISSUE THREAD

**Issue by liuchangfitcloud** [halo-dev/halo#5048]
### 系统信息

- 外部访问地址: https://www.wggznb.top/
- 启动时间: 2023-12-14 17:26
- 版本: 2.11.1
- 构建时间: 2023-12-02 22:53
- Git Commit: 54f77d5
- Java: IBM Semeru Runtime Open Edition / 17.0.9+9
- 数据库: PostgreSQL / 15.4 (Debian 15.4-2.pgdg120+1)
- 操作系统: Linux / 3.10.0-1160.71.1.el7.x86_64
- 已激活主题: [Walker](https://halo.run/store/apps/app-GHgAR)
- 已启动插件:
  - [Willow Markdown 编辑器](https://github.com/guqing/willow-mde)
  - [文章限制阅读 Pro](https://github.com/f2ccloud/plugin-restricted-reading-pro)
  - [图库管理](https://github.com/halo-sigs/plugin-photos)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [搜索组件](https://github.com/halo-sigs/plugin-search-widget)
  - [Sitemap](https://github.com/halo-sigs/plugin-sitemap)
  - [增强备份（Backup IMproved）](https://halo.run/store/apps/app-dHakX)
  - [LDAP Login](https://github.com/f2ccloud/plugin-ldap-login)
  - [社交 IAM 认证](https://github.com/f2ccloud/plugin-social-login)

### 使用的哪种方式运行？

Docker Compose

### 在线站点地址

https://www.wggznb.top/

### 发生了什么？

启用社交登录后，个人中心的登录方式无论当前用户是否已经绑定第三方登录都会显示只能解绑，
目前我只绑定了微信登录。
<img width="967" alt="image" src="https://github.com/halo-dev/halo/assets/44662176/426842f2-506a-41c0-be07-06235d570e68">

**Comment by JohnNiang** [comment]
/good-first-issue

应该是此前修改多语言的时候，误写了 key，只需要将下面的代码中的 `unbind.button` 更改为 `bind.button` 即可。

https://github.com/halo-dev/halo/blob/d777dbf7edf5ebd20f2fc0eb023ff67401696c70/console/uc-src/modules/profile/tabs/Detail.vue#L188
