### ISSUE TITLE
希望在后台增加全局认证功能

### ISSUE THREAD

**Issue by wannengge1988** [halo-dev/halo#5050]
### 你当前使用的版本

2.11

### 描述一下此特性

希望在后台增加全局认证功能，就是用户只要访问网站就判断用户是否登录，只要没有登录就跳转至登录页面，我希望开发都能考虑一下这个功能，我迫切的需要这个功能，因为代码注释很少，我找不到相关修改的地方，也希望有懂的朋友们帮助一下我，谢谢。

### 附加信息

期待你们的帮助

**Comment by ruibaby** [comment]
当前可以通过修改主题来支持，具体做法是在主题公共布局模板中根据 `sec:authorize` 标签判断是否已登录，以下是默认主题中的示例：

```diff
<!DOCTYPE html>
<html lang="en" th:fragment="html (title,hero,content,head,footer,sidebar,contentClass)">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=2" />
    <title th:text="${title}"></title>
    <link rel="stylesheet" th:href="@{/assets/dist/style.css?v={version}(version=${theme.spec.version})}" />
    <script th:src="@{/assets/dist/main.iife.js?v={version}(version=${theme.spec.version})}"></script>
    <th:block th:if="${head != null}">
      <th:block th:replace="${head}" />
    </th:block>
    <script>
      main.initColorScheme("[[${theme.config.style.color_scheme}]]",[[${theme.config.style.enable_change_color_scheme}]])
    </script>
  </head>
-  <body class="bg-slate-50 dark:bg-slate-900">
+  <body sec:authorize="isAuthenticated()" class="bg-slate-50 dark:bg-slate-900">
    <th:block th:replace="~{modules/header}" />
    <th:block th:if="${hero != null}">
      <th:block th:replace="${hero}" />
    </th:block>
    <th:block th:unless="${hero != null}">
      <th:block th:replace="~{modules/hero :: hero(isHome = true, cover = null, title = null)}" />
    </th:block>
    <section class="container mx-auto mt-6 grid grid-cols-4 gap-6" th:classappend="${contentClass}">
      <div class="z-0 col-span-4 sm:col-span-3">
        <th:block th:replace="${content}" />
      </div>
      <th:block th:if="${sidebar != null}">
        <th:block th:replace="${sidebar}" />
      </th:block>
      <th:block th:if="${sidebar == null}">
        <th:block th:replace="~{modules/sidebar :: sidebar(prepend = null)}" />
      </th:block>
    </section>
    <th:block th:replace="~{modules/footer}" />
    <th:block th:if="${footer != null}">
      <th:block th:replace="${footer}" />
    </th:block>
  </body>
+  <body sec:authorize="isAnonymous()">
+    <script>
+      window.location.href = "/console/login";
+    </script>
+  </body>
</html>
```

至于是否要在 Halo Core 当中提供此功能，我认为有待考虑。

/kind feature

**Comment by wan92hen** [comment]
> 当前可以通过修改主题来支持，具体做法是在主题公共布局模板中根据 `sec:authorize` 标签判断是否已登录，以下是默认主题中的示例：
> 
> ```diff
> <!DOCTYPE html>
> <html lang="en" th:fragment="html (title,hero,content,head,footer,sidebar,contentClass)">
>   <head>
>     <meta charset="UTF-8" />
>     <meta http-equiv="X-UA-Compatible" content="IE=edge" />
>     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=2" />
>     <title th:text="${title}"></title>
>     <link rel="stylesheet" th:href="@{/assets/dist/style.css?v={version}(version=${theme.spec.version})}" />
>     <script th:src="@{/assets/dist/main.iife.js?v={version}(version=${theme.spec.version})}"></script>
>     <th:block th:if="${head != null}">
>       <th:block th:replace="${head}" />
>     </th:block>
>     <script>
>       main.initColorScheme("[[${theme.config.style.color_scheme}]]",[[${theme.config.style.enable_change_color_scheme}]])
>     </script>
>   </head>
> -  <body class="bg-slate-50 dark:bg-slate-900">
> +  <body sec:authorize="isAuthenticated()" class="bg-slate-50 dark:bg-slate-900">
>     <th:block th:replace="~{modules/header}" />
>     <th:block th:if="${hero != null}">
>       <th:block th:replace="${hero}" />
>     </th:block>
>     <th:block th:unless="${hero != null}">
>       <th:block th:replace="~{modules/hero :: hero(isHome = true, cover = null, title = null)}" />
>     </th:block>
>     <section class="container mx-auto mt-6 grid grid-cols-4 gap-6" th:classappend="${contentClass}">
>       <div class="z-0 col-span-4 sm:col-span-3">
>         <th:block th:replace="${content}" />
>       </div>
>       <th:block th:if="${sidebar != null}">
>         <th:block th:replace="${sidebar}" />
>       </th:block>
>       <th:block th:if="${sidebar == null}">
>         <th:block th:replace="~{modules/sidebar :: sidebar(prepend = null)}" />
>       </th:block>
>     </section>
>     <th:block th:replace="~{modules/footer}" />
>     <th:block th:if="${footer != null}">
>       <th:block th:replace="${footer}" />
>     </th:block>
>   </body>
> +  <body sec:authorize="isAnonymous()">
> +    <script>
> +      window.location.href = "/console/login";
> +    </script>
> +  </body>
> </html>
> ```
> 
> 至于是否要在 Halo Core 当中提供此功能，我认为有待考虑。
> 
> /kind feature

类似这种对于主题模板修改的场景，有可能通过插件来实现吗？比如做一个禁止匿名访问的插件。

**Comment by ruibaby** [comment]
> 类似这种对于主题模板修改的场景，有可能通过插件来实现吗？比如做一个禁止匿名访问的插件。

当前插件应该可以自行实现拦截器，按理来说应该可行。

**Comment by guqing** [comment]
> > 类似这种对于主题模板修改的场景，有可能通过插件来实现吗？比如做一个禁止匿名访问的插件。
> 
> 当前插件应该可以自行实现拦截器，按理来说应该可行。

参考 https://github.com/halo-sigs/plugin-oauth2/blob/main/src/main/java/run/halo/oauth/Oauth2AuthorizationRequestRedirectWebFilter.java 用插件实现一个拦截器即可控制某些路由的登陆访问

**Comment by wannengge1988** [comment]
非常感谢你们的帮助，我的问题得到了解决。
