### ISSUE TITLE
Support Phone Number

### ISSUE THREAD

**Issue by midsmr** [halo-dev/halo#5051]
### 你当前使用的版本

2.11.2

### 描述一下此特性

支持电话号码注册用户，邮件可为空，验证电话号码，这样的话可以利用一些插件将网站绑定到微信公众号中，减轻注册繁琐程度，将网站使用门槛降低，以拓展更多的使用方法。

**Comment by ruibaby** [comment]
可能需要支持通过插件拓展用户验证方式，不推荐在 Core 中实现。

/kind feature
/area plugin

**Comment by guqing** [comment]
关于想实现使用微信公众号注册登陆貌似有个现成的社交登陆插件可以实现这一功能
