### ISSUE TITLE
后台登录总是有问题

### ISSUE THREAD

**Issue by itangqiao** [halo-dev/halo#5053]
### System information

环境信息
版本
[2.10.2](https://github.com/halo-dev/halo/releases/tag/v2.10.2)
构建时间
2023-11-02 18:01
Git Commit
[2ccf811](https://github.com/halo-dev/halo/commit/2ccf811)
Java
OpenJDK Runtime Environment / 17.0.9+9
数据库
MySQL Community Server - GPL / 8.1.0
操作系统
Linux 4.18.0-348.7.1.el8_5.x86_64 / amd64

### What is the project operation method?

Docker Compose

### What happened?

最近后台登录总是登录不上，经常需要好几次，点击登录会自动刷新网页

**Comment by ruibaby** [comment]
有异常提示吗？根据这段描述我没有复现这个问题。

/triage needs-information

**Comment by liuchengts** [comment]
![image](https://github.com/halo-dev/halo/assets/28919312/282f4669-aeb7-45cc-8fb2-060b7ad9ede1)
我套了个cdn，登录不了了，这个 XSRF-TOKEN 每点击一次登录就会变化，删除它也没用。

**Comment by guqing** [comment]
可以检查一下是否是 CDN 缓存了登陆页面

**Comment by liuchengts** [comment]
> 可以检查一下是否是CDN服务器了登陆页面



> 可以检查一下是否是CDN服务器了登陆页面

去了cdn也是这样，包括 删除了 halo docker镜像  只保留数据库 重建halo docker镜像 还是这样 https://github.com/halo-dev/halo/issues/5085

**Comment by guqing** [comment]
由于这个 issue 已在新 issue 讨论，我关闭它，转到 #5085
/close
