### ISSUE TITLE
新站点第一个用户在管理账号用户列表里不显示用户权限

### ISSUE THREAD

**Issue by cetr** [halo-dev/halo#5057]
### 系统信息

- 启动时间: 2023-12-17 21:16
- 版本: 2.11.2
- 构建时间: 2023-12-07 16:29
- Git Commit: 97b5f72
- Java: IBM Semeru Runtime Open Edition / 17.0.9+9
- 数据库: PostgreSQL / 15.4 (Debian 15.4-1.pgdg120+1)
- 操作系统: Linux / 4.15.0-159-generic

### 使用的哪种方式运行？

Docker

### 发生了什么？

新部署的站点，初始化完成后用户注册的账号在管理员后台用户列表里不显示用户角色权限，不过功能正常
在删除那个用户后再次注册就显示了

**Comment by ruibaby** [comment]
需要复现一下。

/triage needs-information
/king bug
