### ISSUE TITLE
将 console 源码目录重命名为 ui

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#5061]
### 你当前使用的版本

2.11

### 描述一下此特性

从 Halo 2.11 开始，提供了新的个人中心平台（uc），并和原来的 Console 共享同一个项目，插件机制也和 Console 一致，所以目前可能将 console 目录改为 ui 会更加合适。后续 ui 的定义为 Console + UC。

此外，原来是从插件的 `src/resources/console` 读取静态资源并捆绑为 `bundle.js` 和 `bundle.css`，现在是否可以考虑改为 `src/resources/ui` 并兼容 `src/resources/console`，后续文档等统一以 ui 为准。 cc @guqing 

/kind api-change

**Comment by guqing** [comment]
可以

**Comment by JohnNiang** [comment]
我申请认领当前 Issue。我将额外完成将 ui 项目重构成 Gradle 子项目。@ruibaby
