### ISSUE TITLE
v2.10.0 升级到 v2.11.2，容器启动成功，服务无法访问

### ISSUE THREAD

**Issue by liufei20151013** [halo-dev/halo#5062]
### 系统信息

v2.10.0 访问正常，v2.11.2无法访问

### 使用的哪种方式运行？

Docker

### 发生了什么？

v2.10.0 升级到 v2.11.2，容器启动成功，服务无法访问
![image](https://github.com/halo-dev/halo/assets/15103510/0b479d0b-dba7-47e8-9d06-f0b05f3e40ea)
![image](https://github.com/halo-dev/halo/assets/15103510/198afc78-8c83-4cc7-9ab5-e4d5e3db383e)

**Comment by ruibaby** [comment]
建议提供更完整的日志，从当前日志似乎无法判断。

/triage needs-information

**Comment by ruibaby** [comment]
如果没有后续动态，我将关闭此 issue，后续可以重新提交或者重新打开此 issue。

/close
