### ISSUE TITLE
编辑文章，选择列表格式，最后一个列表项无法使用删除键回到上一行，导致多出一个空行

### ISSUE THREAD

**Issue by RuanLia** [halo-dev/halo#5065]
### 系统信息

- 外部访问地址: https://demo.halo.run/
- 启动时间: 2023-12-18 08:00
- 版本: 2.11.2
- 构建时间: 2023-12-07 16:29
- Git Commit: 97b5f72
- Java: IBM Semeru Runtime Open Edition / 17.0.9+9
- 数据库: PostgreSQL / 15.2 (Debian 15.2-1.pgdg110+1)
- 操作系统: Linux / 5.15.0-67-generic
- 已激活主题: [Ocean](https://github.com/f2ccloud/theme-ocean.git)
- 已启动插件:
  - [Markdown / HTML 内容块](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - 联系表单
  - [文章限制阅读 Pro](https://github.com/f2ccloud/plugin-restricted-reading-pro)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)
  - [KaTeX](https://github.com/halo-sigs/plugin-katex)
  - [ByteMD](https://github.com/ruibaby/plugin-bytemd)
  - [图库管理](https://github.com/halo-sigs/plugin-photos)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [站点迁移](https://github.com/halo-sigs/plugin-migrate)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [OAuth2 认证](https://github.com/halo-sigs/plugin-oauth2)
  - [对象存储（Amazon S3 协议）](https://github.com/halo-dev/plugin-s3)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [StackEdit](https://github.com/halo-sigs/plugin-stackedit)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [Unsplash](https://github.com/halo-sigs/plugin-unsplash)
  - [highlight.js 代码高亮](https://github.com/halo-sigs/plugin-highlightjs)
  - [lightgallery.js 灯箱](https://github.com/halo-sigs/plugin-lightgallery)
  - [Umami](https://github.com/halo-sigs/plugin-umami)

### 使用的哪种方式运行？

Docker

### 发生了什么？

编辑文章，选择列表格式，最后一个列表项无法使用删除键回到上一行，导致多出一个空行

### 附加信息

Uploading 2abc06e6a0d7eecfbe1f5609c6c10e2d.mp4…

**Comment by RuanLia** [comment]
![Uploading 微信图片_20231218171354.png…]()

**Comment by AirboZH** [comment]
在 tiptap 官方的 Demo 中也发现了这个问题，包括 bullet list 和 ordered list 

当 list-item 下方为一个段落 p 时
![image](https://github.com/halo-dev/halo/assets/50261327/421deb87-3341-4ebf-9e36-7b138fd80927)

删除(backspace) p 标签时光标会移动到 list-item 当中并新建一个 item
![image](https://github.com/halo-dev/halo/assets/50261327/948d054d-80da-45c7-aa53-3b2ba610df2b)

上面描述的和 halo 默认编辑器中出现的状况是一样的。

不同的是，在 tiptap 的演示当中，按下退格键 (backspace) 时候并不会在 list 下方创建一个 p 标签。
而是在上一个 item 中新建一个 p 标签，再按删除的时候才会移除，或者按 回车键 会将这个 item 中的 p 转为ul之外的 p 段落
![image](https://github.com/halo-dev/halo/assets/50261327/fd884997-c6bb-4910-89c8-6a7e08b85402)

但是在 halo 默认编辑器中删除后立即变为 p 标签，p 标签删除(backspace) 又变成 item ，以此循环。

这个问题似乎是 ProseMirror 的遗留问题 https://github.com/ProseMirror/prosemirror/issues/370

不过tiptap也给出了解决方法
https://github.com/ueberdosis/tiptap/issues/3367#issuecomment-1666785236
使用一个新的按键映射来暂时解决这个问题
https://github.com/ueberdosis/tiptap/tree/develop/packages/extension-list-keymap
