### ISSUE TITLE
一些功能建议

### ISSUE THREAD

**Issue by yuanchenyangGithub** [halo-dev/halo#5066]
### Your current Halo version

2.11.2

### Describe this feature

1、那个文章公开和私有能不能做成，私有不在博客展示，但是可以分享链接地址可以查看
2、文章带分类展示，虽然右上角进行了分类，但是文章展示在一起看起来很乱
3、附件支持菜单那种列表展示，那样好分类
4、最好带简单点的图片修改器
5、

**Comment by JohnNiang** [comment]
可以考虑转移到 [Discussions](https://github.com/halo-dev/halo/discussions) 中。
