### ISSUE TITLE
日志巨量增长和reactor.core.Exceptions异常

### ISSUE THREAD

**Issue by chaixiang2002** [halo-dev/halo#5067]
### System information

2023年10月左右通过dokcer安装halo
是此命令安装的
docker run -it -d --name halo -p 8090:8090 -v ~/.halo2:/root/.halo2 halohub/halo:2.11

### What is the project operation method?

Docker

### What happened?

1. 日志巨大，今天发现服务器磁盘可用空间为0，发现18G的docker容器日志，是halo的
[23f4a2029afb31efbd527b1266d75a07ba5703cef720ef5f57ae39f6463d5704.log](https://github.com/halo-dev/halo/files/13704045/23f4a2029afb31efbd527b1266d75a07ba5703cef720ef5f57ae39f6463d5704.log)

![屏幕截图 2023-12-18 201955](https://github.com/halo-dev/halo/assets/84395046/ede986a3-247e-4f9c-829b-54344adefaa3)

2. 日志发现大量异常报错，查看了4，5000行，基本都是报错，我吧最后1000行日志保留下来了
3. 刷新搜索引擎异常
4. 个别文章显示505异常，数据库没有该文章

### Additional information

![image](https://github.com/halo-dev/halo/assets/84395046/82b535d5-9aed-460f-bbf7-18f9124d2a17)
下面是我点击刷新搜索引擎时，最后1000日志
[a.log](https://github.com/halo-dev/halo/files/13704142/a.log)

![image](https://github.com/halo-dev/halo/assets/84395046/67d26eea-8828-409b-b8c3-fdcac67845ca)

**Comment by JohnNiang** [comment]
Hi @chaixiang2002 ，Halo 默认是限制了日志文件总存储不超过 1G，请看下面的代码片段：

https://github.com/halo-dev/halo/blob/d6dc2a7bbeacbd1774ca38699649308062517fe9/application/src/main/resources/application.yaml#L54-L61

如果需要限制 Docker 的日志存储，可参考 [Docker 官方文档](https://docs.docker.com/config/containers/logging/configure/)。

/kind support

**Comment by gengxiaoxiaoxin** [comment]
@chaixiang2002 你可以通过Docker设置，限制Container的日志大小，也可以通过相关的配置(see application.yml)关闭console输出。

**Comment by ruibaby** [comment]
如果没有后续动态，我将关闭此 issue，后续可以重新提交或者重新打开此 issue。

/close
