### ISSUE TITLE
feat: 新增文章排序功能

### ISSUE THREAD

**Issue by JohnNiang** [halo-dev/halo#507]
## 概述

支持自定义排序功能。

## 动机

能够更好地排版文章。

## 详细解释

可能需要在 `posts` 中新增一个排序字段，`halo-admin` 也可以实现拖拽的功能。

**Comment by ruibaby** [comment]
@JohnNiang 现在有排序字段呀。

**Comment by JohnNiang** [comment]
> @JohnNiang 现在有排序字段呀。

似乎只是 topPriority。是否还需要一个字段用于表示该文章是否置顶？

**Comment by ruibaby** [comment]
@JohnNiang 不用，这里的文章排序应该是可选按照访问量 评论量 创建时间等来排序。

**Comment by ruibaby** [comment]
@JohnNiang 而且如果改这个文章置顶，那么主题那边也要改。

**Comment by youngledo** [comment]
能否增加按“分类”排序呢？
