### ISSUE TITLE
代码块内容格式错乱，且复制按钮无效。

### ISSUE THREAD

**Issue by NikoYomi** [halo-dev/halo#5082]
### 系统信息

- 外部访问地址：https://snty.de/
- 启动时间：2023-12-06 13:31
- 版本
- 构建时间：2023-09-22 22:51
- Git Commit：54d8393
- Java：OpenJDK Runtime Environment / 17.0.8.1+1
- 数据库：PostgreSQL / 15.4 (Debian 15.4-2.pgdg120+1)
- 操作系统：Linux / 5.10.0-8-amd64
  

### 使用的哪种方式运行？

Docker

### 在线站点地址

https://snty.de/

### 发生了什么？

问题一：代码块内容格式错乱。
问题二：代码块胖的复制点击失效。
下图

### 附加信息

如图：
编辑界面：
![1703037706982](https://github.com/halo-dev/docs/assets/120245220/4e300019-8334-4ad9-b19b-e8d7f07b05af)
预览界面：
![1703037661367](https://github.com/halo-dev/docs/assets/120245220/205acdf5-e86d-44c8-9cf2-79c1c9519e02)

可以看到预览时的行间距不一样的，而且多了<p>。

**Comment by ruibaby** [comment]
看起来和 ToolBench 这个插件有关，相关 issue：https://github.com/halo-dev/halo/issues/4853#issuecomment-1810403899

<img width="1080" alt="图片" src="https://github.com/halo-dev/halo/assets/21301288/917514c5-7fc9-46aa-a60b-7a272a737693">

/triage duplicate

**Comment by NikoYomi** [comment]
> 看起来和 ToolBench 这个插件有关，相关 issue：[#4853 (comment)](https://github.com/halo-dev/halo/issues/4853#issuecomment-1810403899)
> 
> <img alt="图片" width="1080" src="https://private-user-images.githubusercontent.com/21301288/291761843-917514c5-7fc9-46aa-a60b-7a272a737693.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMzI4NzYsIm5iZiI6MTcwMzEzMjU3NiwicGF0aCI6Ii8yMTMwMTI4OC8yOTE3NjE4NDMtOTE3NTE0YzUtN2ZjOS00NmFhLWE2MGItN2EyNzJhNzM3NjkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDA0MjI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3YjFhODE1NzE3ODAyNzY3NWFhYmYwNDc0YTlmZjYzMmVjZDM0M2E5OGFiNjBmZmMxNzVmNzcxYTRjZGJjMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p8xudLj0Ze4T-9FJlUFRqhaBfMVh3n2PZ37CC20I9SI">
> /triage duplicate

感谢！！已经解决，请问代码块旁边的复制无效怎么解决呢？

**Comment by LIlGG** [comment]
> 感谢！！已经解决，请问代码块旁边的复制无效怎么解决呢？

代码块复制无效应该是主题的问题，建议向对应主题仓库提 issue 进行解决。

/close
