### ISSUE TITLE
发布文章报错，求大佬帮忙看下

### ISSUE THREAD

**Issue by pandatools** [halo-dev/halo#5086]
### 系统信息

halo2.10 mysql8

### 使用的哪种方式运行？

Docker

### 发生了什么？

发布时，提示如下报错，但是实际上他是发布成功了，但是后台也是有报错信息

![1334e299b50cbf5e67074a9aff18895](https://github.com/halo-dev/halo/assets/44802141/65a0f2e3-697b-4a96-a8c0-50cb53240f31)

### 相关日志输出

```shell
报错信息见图片。我搭建的该博客中，现存的信息比较多，mysql数据库里有接近三千行信息，不知道是不是数据过多引起的，请问怎样才能避免这种问题
```

### 附加信息

![截图_20231220144829](https://github.com/halo-dev/halo/assets/44802141/313189e4-80e9-4393-8d57-8095025720c3)

**Comment by pandatools** [comment]
问题找到了，前端提交的时候没有，content.halo.run/last-released-snapshot字段，但是发布的时候为啥会没有这个字段，我不是很清除
![截图_20231220154528](https://github.com/halo-dev/halo/assets/44802141/3892cdb2-6caf-4787-b48b-14eb6c2c64d4)

**Comment by guqing** [comment]
应该和这个没关系，就是发布的时候等待超时了 你看报错之后实际有没有发布成功

**Comment by guqing** [comment]
你可以升级到最新版用，2.11版本把这个等待时长调大了 https://github.com/halo-dev/halo/pull/4814 应该就很少会出现了，但升级前请先备份一个
