### ISSUE TITLE
application.yaml方式启动失败

### ISSUE THREAD

**Issue by xiedeacc** [halo-dev/halo#5087]
### 系统信息

- External url: 
- Start time: 2023-12-20 15:35
- Version: 2.12.0-SNAPSHOT
- Build time: 2023-12-19 22:03
- Git Commit: d6dc2a7
- Java: Java(TM) SE Runtime Environment / 17.0.9+11-LTS-201
- Database: (Ubuntu) / 8.0.35-0ubuntu0.20.04.1
- Operating system: Linux / 5.15.0-1051-aws
- Activated theme: [Earth](https://github.com/halo-dev/theme-earth.git)
- Enabled plugins: 

### 使用的哪种方式运行？

Fat Jar

### 发生了什么？

参考 https://docs.halo.run/getting-started/config/ 配置的application.yaml，启动的时候提示

```
BindException: Failed to bind properties under 'halo' to run.halo.app.infra.properties.HaloProperties failed
```

启动命令
```
/usr/local/jdk-17.0.9/bin/java -server -Xms256m -Xmx256m -jar /home/ubuntu/halo/application-2.12.0-SNAPSHOT.jar --spring.config.location=/home/ubuntu/.halo2/application.yaml
```

**Comment by JohnNiang** [comment]
/kind support

1. Halo 2.x 没有提供 Fat Jar 部署，描述中所提到的文档应该只适用于 1.x，官方文档中也没有菜单入口进入（可能是为了不造成死链而保留）。
2. 关于配置文件的配置项，建议参考 [Spring Boot 官方文档](https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.external-config)。
3. 如果确实需要额外的配置，这里建议用 `spring.config.additional-location` 配置，而不是 `spring.config.location`。

**Comment by xiedeacc** [comment]
加上--halo.workDir="/home/ubuntu/.halo2"后启动成功了

**Comment by xiedeacc** [comment]
> /kind support
> 
> 1. Halo 2.x 没有提供 Fat Jar 部署，描述中所提到的文档应该只适用于 1.x，官方文档中也没有菜单入口进入（可能是为了不造成死链而保留）。
> 2. 关于配置文件的配置项，建议参考 [Spring Boot 官方文档](https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.external-config)。
> 3. 如果确实需要额外的配置，这里建议用 `spring.config.additional-location` 配置，而不是 `spring.config.location`。

应该提供fat jar部署，不是每个机器性能和磁盘足够到支持docker

**Comment by JohnNiang** [comment]
Hi @xiedeacc ，关于是否提供 Jar 部署的讨论，请参考 <https://github.com/halo-dev/halo/issues/2996>。

**Comment by xiedeacc** [comment]
fatjar + mysql + systemd 可以参考 https://blog.xiedeacc.com/archives/1703214614553
