### ISSUE TITLE
在接受halo通知邮件的邮箱邮件中点击了取消订阅，能恢复订阅吗

### ISSUE THREAD

**Issue by xmenbe** [halo-dev/halo#5092]
### Your current Halo version

2.11.2

### Describe this feature

在接受halo通知邮件的邮箱邮件中点击了取消订阅，无法接受邮件了，有办法恢复吗

**Comment by guqing** [comment]
如果是想收到文章新评论事件可以重新发布一下文章，如果是有新回复事件目前可能不好重新订阅，因为要重新参与事件

**Comment by xmenbe** [comment]
> 如果是想文章新评论事件可以重新发布一下文章，如果是有新回复事件目前可能不好重新订阅，因为要重新参与事件

重新发布一下文章解决了问题
