### ISSUE TITLE
将Halo默认编辑器作为可插拔的插件

### ISSUE THREAD

**Issue by adozhao** [halo-dev/halo#5096]
### 你当前使用的版本

2.11.2

### 描述一下此特性

建议把Halo默认编辑器也作为可插拔的插件，当没有安装任何编辑器时候，在界面上提供安装编辑器插件的入口就行 。

**Comment by JohnNiang** [comment]
Hi @github-ado , thanks for reaching out here!

无论 Halo 默认编辑器是否可插拔，默认情况下，都建议安装上。不过[App Store 插件](https://github.com/halo-dev/plugin-app-store)倒是可以考虑扩展一下“选择编辑器”下拉框，方便用户直接点击安装其他编辑器插件。

**Comment by wan92hen** [comment]
> Hi @github-ado , thanks for reaching out here!
> 
> 无论 Halo 默认编辑器是否可插拔，默认情况下，都建议安装上。不过[App Store 插件](https://github.com/halo-dev/plugin-app-store)倒是可以考虑扩展一下“选择编辑器”下拉框，方便用户直接点击安装其他编辑器插件。

感觉为应用增加更加完善的分类和标签更合适呢，`编辑器` 作为众多分类中的一个。

**Comment by github-ado** [comment]
> Hi @github-ado , thanks for reaching out here!
> 
> 无论 Halo 默认编辑器是否可插拔，默认情况下，都建议安装上。不过[App Store 插件](https://github.com/halo-dev/plugin-app-store)倒是可以考虑扩展一下“选择编辑器”下拉框，方便用户直接点击安装其他编辑器插件。

主要考虑到想一直使用应用商店其他贡献者的编辑器，这样的话，默认编辑器总是开启总觉得不太好，对于有”洁癖“的人来说

**Comment by ruibaby** [comment]
Ref https://github.com/justice2001/halo-plugin-vditor/issues/7#issuecomment-1865970996

如上所说，将默认编辑器作为预设插件是可行的，但目前编辑器和 Console 耦合比较严重、且不少插件会依赖编辑器，比如瞬间等。

所以就目前而言不是特别适合作为插件提供。

**Comment by xiedeacc** [comment]
支持作为插件独立出来

**Comment by ruibaby** [comment]
> Ref [justice2001/halo-plugin-vditor#7 (comment)](https://github.com/justice2001/halo-plugin-vditor/issues/7#issuecomment-1865970996)
> 
> 如上所说，将默认编辑器作为预设插件是可行的，但目前编辑器和 Console 耦合比较严重、且不少插件会依赖编辑器，比如瞬间等。
> 
> 所以就目前而言不是特别适合作为插件提供。

基于以上问题，暂不考虑将默认编辑器独立。

/close
