### ISSUE TITLE
fatjar方式部署的评论没有存储在mysql？

### ISSUE THREAD

**Issue by xiedeacc** [halo-dev/halo#5097]
### System information

- External url: 
- Start time: 2023-12-21 17:47
- Version: 2.12.0-SNAPSHOT
- Build time: 2023-12-19 22:03
- Git Commit: d6dc2a7
- Java: Java(TM) SE Runtime Environment / 17.0.9+11-LTS-201
- Database: (Ubuntu) / 8.0.35-0ubuntu0.20.04.1
- Operating system: Linux / 5.15.0-1051-aws
- Activated theme: [Earth](https://github.com/halo-dev/theme-earth.git)
- Enabled plugins:
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)

### What is the project operation method?

Fatjar

### Your site address.

https://blog.xiedeacc.com/archives/hello-halo

### What happened?

我是用fatjar方式启动的服务，存储使用了mysql，评论功能本身正常，但是mysql没有找到对应记录？请问下评论存储在哪里？

**Comment by xiedeacc** [comment]
目录也没有看到db文件夹
![image](https://github.com/halo-dev/halo/assets/8072296/725c688d-ba03-494a-a825-66c19cc3e8de)

**Comment by wan92hen** [comment]
1. 使用外部数据库的话，工作目录不会存储数据库数据，数据库数据目录需要在对应数据库配置中查看
2. Halo 数据库使用了单表的模式，请查看之前的 Issue https://github.com/halo-dev/halo/issues/3061

**Comment by xiedeacc** [comment]
ok, thks, 确实存在myql中
