### ISSUE TITLE
Halo默认主题Earth"一行三列"分页问题

### ISSUE THREAD

**Issue by github-ado** [halo-dev/halo#5098]
### 系统信息

- 外部访问地址:  xxx
- 启动时间: 2023-12-11 17:20
- 版本: 2.11.2
- 构建时间: 2023-12-07 16:29
- Git Commit: 97b5f72
- Java: IBM Semeru Runtime Open Edition / 17.0.9+9
- 数据库: MySQL Community Server - GPL / 8.0.33
- 操作系统: Linux / 4.4.302+
- 已激活主题: [Earth](https://github.com/halo-dev/theme-earth.git)
- 已启动插件:
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [highlight.js 代码高亮](https://github.com/halo-sigs/plugin-highlightjs)
  - [对象存储（Amazon S3 协议）](https://github.com/halo-dev/plugin-s3)
  - [增强备份（Backup IMproved）](https://halo.run/store/apps/app-dHakX)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

一共八条数据，应该第一页6条数据，第二页2条数据
![image](https://github.com/halo-dev/halo/assets/23180747/79cb6038-1cb7-45da-9f5c-9ed175437a96)
![image](https://github.com/halo-dev/halo/assets/23180747/bbf9cad9-5ed5-4d86-802f-bcfc266e5b27)
![image](https://github.com/halo-dev/halo/assets/23180747/465d6115-d8d3-4233-99f3-1eeacbf8b02c)

**Comment by wan92hen** [comment]
/kind support

每页显示的文章数量，是设置-文章设置中配置的，主题这边的配置只影响布局。

![image](https://github.com/halo-dev/halo/assets/27671436/8deca5a5-8aa8-4e17-9a89-64bd4c696a90)

**Comment by github-ado** [comment]
明白了 @wan92hen  🙇‍
