### ISSUE TITLE
无法收到邮箱验证码

### ISSUE THREAD

**Issue by W433567423** [halo-dev/halo#5100]
### 系统信息

- 外部访问地址: https://wtututu.top/
- 启动时间: 
- 版本: 2.11.2
- 构建时间: 2023-12-07 16:29
- Git Commit: 97b5f72
- Java: IBM Semeru Runtime Open Edition / 17.0.9+9
- 数据库: H2 / 2.2.224
- 操作系统: Linux / 5.15.0-86-generic
- 已激活主题: [Dream](https://github.com/nineya/halo-theme-dream2.0.git)
- 已启动插件:
  - [lightgallery.js 灯箱](https://github.com/halo-sigs/plugin-lightgallery)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [KaTeX](https://github.com/halo-sigs/plugin-katex)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [StackEdit](https://github.com/halo-sigs/plugin-stackedit)
  - [highlight.js 代码高亮](https://github.com/halo-sigs/plugin-highlightjs)
  - [图库管理](https://github.com/halo-sigs/plugin-photos)
  - [对象存储（Amazon S3 协议）](https://github.com/halo-dev/plugin-s3)
  - [live2d 看板娘](https://github.com/LIlGG/plugin-live2d)
  - [ByteMD](https://github.com/ruibaby/plugin-bytemd)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)

### 使用的哪种方式运行？

Docker

### 在线站点地址

https://wtututu.top

### 发生了什么？

我的邮箱是163网易邮箱，点击个人中心->验证电子邮箱功能，邮箱无法收到验证码
![image](https://github.com/halo-dev/halo/assets/81465518/7429e1cc-51c9-4171-8891-a4c1d630f943)

**Comment by guqing** [comment]
一般都是配置问题：
<img width="716" alt="image" src="https://github.com/halo-dev/halo/assets/38999863/6a4ae028-b7be-4ea4-93ab-462d2daf847c">

检查你的 SSL 端口与是否开启 SSL 的配置是否对应
