### ISSUE TITLE
默认编辑器渲染的markdown不好看

### ISSUE THREAD

**Issue by xiedeacc** [halo-dev/halo#5106]
### Your current Halo version

halo-1.12

### Describe this feature

代码块渲染后，左边没有多余的空间，不好看，也没有高亮了

![image](https://github.com/halo-dev/halo/assets/8072296/146c38c1-2b11-4163-b720-4cc858eaa5a8)
渲染后一点也不好看
![image](https://github.com/halo-dev/halo/assets/8072296/368ccbe4-b9c9-445e-ad03-271e83794bdf)

**Comment by ruibaby** [comment]
这和编辑器无关，你需要安装一个代码高亮的插件，比如：https://www.halo.run/store/apps/app-sqpgf

/kind support

**Comment by xiedeacc** [comment]
好的，感谢，感谢
