### ISSUE TITLE
启用瞬间插件时移动端无法显示该菜单

### ISSUE THREAD

**Issue by intoyang** [halo-dev/halo#5109]
### 系统信息

- 外部访问地址: https://intoyang.fun/
- 启动时间: 2023-12-01 15:55
- 版本: 2.11.0
- 构建时间: 2023-12-01 12:01
- Git Commit: 0351a67
- Java: IBM Semeru Runtime Open Edition / 17.0.9+9
- 数据库: MySQL Community Server - GPL / 8.0.31
- 操作系统: Linux / 3.10.0-1160.62.1.el7.x86_64
- 已激活主题: [Walker](https://halo.run/store/apps/app-GHgAR)
- 已启动插件:
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [文章限制阅读 Pro](https://github.com/f2ccloud/plugin-restricted-reading-pro)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [lightgallery.js 灯箱](https://github.com/halo-sigs/plugin-lightgallery)
  - [highlight.js 代码高亮](https://github.com/halo-sigs/plugin-highlightjs)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)
  - [live2d 看板娘](https://github.com/LIlGG/plugin-live2d)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [ByteMD](https://github.com/ruibaby/plugin-bytemd)
  - [Umami](https://github.com/halo-sigs/plugin-umami)

### 使用的哪种方式运行？

Docker Compose

### 在线站点地址

https://intoyang.fun/

### 发生了什么？

- 尝试在移动端发布瞬间，启用瞬间插件且 pc 端运行正常的情况下，移动端后台未能显示瞬间菜单（链接菜单同样启动但未显示）。![image](https://github.com/halo-dev/halo/assets/73098982/ece8ca38-4380-4ec0-83d0-6bdf3886ea0d)

- 关闭瞬间插件后，链接菜单恢复了正常显示。
![image](https://github.com/halo-dev/halo/assets/73098982/2c120767-211c-4712-aa0f-9d2d849a0067)

**Comment by ruibaby** [comment]
看起来和前置代理有关，可以提供一下 Nginx 的配置吗？

/kind support

**Comment by intoyang** [comment]
看起来是手机浏览器版本受限。升级至 ios17 后没有再出现这个问题。

**Comment by ruibaby** [comment]
> 看起来是手机浏览器版本受限。升级至 ios17 后没有再出现这个问题。

可能和 Safari 版本有关，旧版本对正则表达式的支持和其他浏览器不同，而且问题在于正则可能是在一些依赖库中出现的，所以感觉很难解决这个问题。

https://github.com/halo-dev/halo/issues/4720

**Comment by ruibaby** [comment]
目前无法在 Halo Core 当中解决，如果后续遇到此问题，可以在插件中尝试对低版本浏览器进行兼容。

/close
