### ISSUE TITLE
链接插件删除链接后列表不自动刷新

### ISSUE THREAD

**Issue by adozhao** [halo-dev/halo#5110]
### 系统信息

- 外部访问地址: https://xxxx:8090/
- 启动时间: 2023-12-11 17:20
- 版本: 2.11.2
- 构建时间: 2023-12-07 16:29
- Git Commit: 97b5f72
- Java: IBM Semeru Runtime Open Edition / 17.0.9+9
- 数据库: MySQL Community Server - GPL / 8.0.33
- 操作系统: Linux / 4.4.302+
- 已激活主题: [Earth](https://github.com/halo-dev/theme-earth.git)
- 已启动插件:
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [highlight.js 代码高亮](https://github.com/halo-sigs/plugin-highlightjs)
  - [对象存储（Amazon S3 协议）](https://github.com/halo-dev/plugin-s3)
  - [增强备份（Backup IMproved）](https://halo.run/store/apps/app-dHakX)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

**链接管理**插件，删除一个链接之后，列表没有刷新，需要手动进行刷新操作~
![image](https://github.com/halo-dev/halo/assets/23180747/72e653a0-98d4-4b92-817d-94becbeddb03)

**Comment by JohnNiang** [comment]
This issue has been fixed by <https://github.com/halo-sigs/plugin-links/pull/51>.

/close
