### ISSUE TITLE
加载第三方编辑器插件新增过渡状态

### ISSUE THREAD

**Issue by adozhao** [halo-dev/halo#5117]
### 你当前使用的版本

2.11.2

### 描述一下此特性

新增文章，应用第三方编辑器的时候，插件需要加载，中间没有过渡状态，就是很生硬的在等插件加载并渲染完成，然后最终显示，有时候渲染时间比较长，大概3秒左右。建议增加loading或者其他的交互状态过渡~

**Comment by ruibaby** [comment]
可以尝试用 Vue 的 [Suspense](https://vuejs.org/guide/built-ins/suspense.html#suspense) 来解决这个问题。当然，这个问题在编辑器本身去做也是比较合理的，如果要在 Halo 这边使用 Suspense 做的话，所有编辑器组件可能都得跟着适配。

/area console

**Comment by github-ado** [comment]
> 可以尝试用 Vue 的 [Suspense](https://vuejs.org/guide/built-ins/suspense.html#suspense) 来解决这个问题。当然，这个问题在编辑器本身去做也是比较合理的，如果要在 Halo 这边使用 Suspense 做的话，所有编辑器组件可能都得跟着适配。
> 
> /area console

@justice2001

**Comment by justice2001** [comment]
> > 可以尝试用 Vue 的 [Suspense](https://vuejs.org/guide/built-ins/suspense.html#suspense) 来解决这个问题。当然，这个问题在编辑器本身去做也是比较合理的，如果要在 Halo 这边使用 Suspense 做的话，所有编辑器组件可能都得跟着适配。
> > /area console
> 
> @justice2001

OK，下个版本解决这个问题
https://git.mczhengyi.top/zhengyi/halo-plugin-vditor/issues/28
