### ISSUE TITLE
文章设置别名生成策略问题

### ISSUE THREAD

**Issue by UPToZ-Core** [halo-dev/halo#5118]
### 系统信息

- 外部访问地址: 
- 启动时间: 2023-12-27 13:47
- 版本: 2.11.3
- 构建时间: 2023-12-27 12:13
- Git Commit: 8e9b07d
- Java: IBM Semeru Runtime Open Edition / 17.0.9+9
- 数据库: MySQL Community Server - GPL / 8.2.0
- 操作系统: Linux / 5.10.120
- 已激活主题: [Hao](https://githubfast.com/liuzhihang/halo-theme-hao)
- 已启动插件:
  - [Docsme](https://github.com/f2ccloud/plugin-docsme)
  - [StackEdit](https://github.com/halo-sigs/plugin-stackedit)
  - [又拍云 OSS](https://github.com/AirboZH/plugin-uposs)
  - [无色界](https://github.com/guqing/halo-plugin-colorless)
  - [Umami](https://github.com/halo-sigs/plugin-umami)
  - [Vditor编辑器](https://github.com/justice2001/veditor-plugin)
  - [Metrics Graph](https://github.com/guqing/plugin-metrics-graph)
  - [文章导入导出](https://jhacker.cn/2023/halo-plugin-export2doc)
  - [Markdown / HTML 内容块](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [站点推送插件](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [ByteMD](https://github.com/ruibaby/plugin-bytemd)
  - [lightgallery.js 灯箱](https://github.com/halo-sigs/plugin-lightgallery)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)
  - [我的装备管理](https://github.com/halo-sigs/plugin-equipments)
  - [OAuth2 认证](https://github.com/halo-sigs/plugin-oauth2)
  - [复制追加](https://github.com/turka-cn/plugin-copyadd)
  - [WebP Cloud Services](https://webp.se/)
  - [图库管理](https://github.com/halo-sigs/plugin-photos)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)

### 使用的哪种方式运行？

Docker

### 在线站点地址

https://blog.uptoz.cn/

### 发生了什么？

创建文章时，默认的别名是时间戳，跟后台设置的文章别名生成策略不一致，需要手动刷新一次才会显示与后台配置的别名策略一致

**Comment by ruibaby** [comment]
这是因为直接保存的时候还没有足够的信息来生成 slug，因为标题也是固定的**未命名文章**，但创建文章的操作逻辑确实需要优化，以下是可能需要优化的地方：

1. 在编辑页面提供标题的输入框，这样在不设置文章的情况下创建文章才能根据标题生成 slug。

/area console
/kind improvement
