### ISSUE TITLE
需要多图轮播功能

### ISSUE THREAD

**Issue by assassinliujie** [halo-dev/halo#5126]
### 你当前使用的版本

latest

### 描述一下此特性

需要一个多图轮播功能，对于部分分享类文章很有用

**Comment by ruibaby** [comment]
这种功能放在 Halo 核心可能不是特别合适，因为不是每个主题都需要，实现方式可能也各有不同。所以建议主题自行通过主题配置实现。

**Comment by wan92hen** [comment]
除了主题支持外，应该也可以做一个编辑器扩展插件，可以在编辑文章时插入轮播图内容块。
