### ISSUE TITLE
将Attachment的类型声明添加到console-shared中

### ISSUE THREAD

**Issue by justice2001** [halo-dev/halo#5127]
### 你当前使用的版本

2.11.2

### 描述一下此特性

在2.11版本编辑器插件的props中加入了一个`uploadImage`的参数，他的返回类型包含Attachment，但我发现`Attachment`这个类型是存在在`@halo-dev/api-client`这个包下，因此我想是否将这个类型声明也加入到`console-shared`中比较好。

### 附加信息

现在的Attachment在编辑器中会爆红，虽然能用，但看起来挺难受的。

<img width="486" alt="截屏2023-12-29 15 26 12" src="https://github.com/halo-dev/halo/assets/28425753/bf585697-e168-4ec5-a6fc-0f661d20e0ed">

**Comment by ruibaby** [comment]
直接安装 `@halo-dev/api-client` 即可。

**Comment by justice2001** [comment]
OKOK
