### ISSUE TITLE
关于同名图片附件无法显示新附件内容的问题

### ISSUE THREAD

**Issue by mjsoftking** [halo-dev/halo#5131]
### 系统信息

- 外部访问地址: https://www.sw0.top
- 启动时间: 2023-12-29 08:40
- 版本: 2.11.3
- 构建时间: 2023-12-27 12:13
- Git Commit: 8e9b07d
- Java: IBM Semeru Runtime Open Edition / 17.0.9+9
- 数据库: MySQL Community Server - GPL / 8.2.0
- 操作系统: Linux / 5.10.0-26-amd64
- 已激活主题: [Dream](https://github.com/nineya/halo-theme-dream2.0.git)
- 已启动插件:
  - [Docsme](https://github.com/f2ccloud/plugin-docsme)
  - AI 助手
  - [Umami](https://github.com/halo-sigs/plugin-umami)
  - [LDAP Login](https://github.com/f2ccloud/plugin-ldap-login)
  - [增强备份（Backup IMproved）](https://halo.run/store/apps/app-dHakX)
  - [Metrics Graph](https://github.com/guqing/plugin-metrics-graph)
  - [社交 IAM 认证](https://github.com/f2ccloud/plugin-social-login)
  - [Vditor编辑器](https://github.com/justice2001/veditor-plugin)
  - [文章导入导出](https://jhacker.cn/2023/halo-plugin-export2doc)
  - [对象存储（Amazon S3 协议）](https://github.com/halo-dev/plugin-s3)
  - 联系表单
  - [追番插件](https://github.com/Roozenlz/plugin-bilibili-bangumi)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [微信公众号发布](https://github.com/f2ccloud/plugin-platforms-sync)
  - [Markdown / HTML 内容块](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [文章限制阅读 Pro](https://github.com/f2ccloud/plugin-restricted-reading-pro)
  - [Willow Markdown 编辑器](https://github.com/guqing/willow-mde)
  - [站点推送插件](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [OAuth2 认证](https://github.com/halo-sigs/plugin-oauth2)
  - [KaTeX](https://github.com/halo-sigs/plugin-katex)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [lightgallery.js 灯箱](https://github.com/halo-sigs/plugin-lightgallery)
  - [live2d 看板娘](https://github.com/LIlGG/plugin-live2d)
  - [图库管理](https://github.com/halo-sigs/plugin-photos)
  - [ByteMD](https://github.com/ruibaby/plugin-bytemd)
  - [StackEdit](https://github.com/halo-sigs/plugin-stackedit)
  - [highlight.js 代码高亮](https://github.com/halo-sigs/plugin-highlightjs)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)

### 使用的哪种方式运行？

Docker

### 在线站点地址

https://www.sw0.top/

### 发生了什么？

在附件管理中删除一个存在问题的图片附件，然后重新上传同名图片附件，附件查看还是原来的附件内容并未被替换新图片附件。
但是在服务器中存储的图片附件文件则是后上传的内容。

目前重启halo也不会显示新附件内容。

**Comment by JohnNiang** [comment]
Hi @mjsoftking , thanks for reaching out here!

先尝试更换浏览器或者用隐私模式打开网站，确认一下是不是浏览器缓存导致。

/triage needs-information

**Comment by mjsoftking** [comment]
@JohnNiang 换了一个没打开过这个图片的浏览器去访问，还是旧的图片，使用ctrl+F5刷新仍然一样

**Comment by mjsoftking** [comment]
使用隐私浏览器和访问图片下载都是旧的图片

**Comment by JohnNiang** [comment]
还需要确认是否使用了 CDN。如果使用了，可能还需要手动清理一下缓存。

**Comment by mjsoftking** [comment]
> 还需要确认是否使用了 CDN。如果使用了，可能还需要手动清理一下缓存。

没有使用CDN的

**Comment by mjsoftking** [comment]
先传一张图片，然后附件中删除，在上传同名的不通图片，然后在附件中查看是否更新了

**Comment by ruibaby** [comment]
建议先通过 ip 访问以排除是 Halo 的问题，我这边在本地无法复现。

除了以上说的浏览器缓存和 CDN 缓存，还有可能在 Nginx 有静态资源缓存。

**Comment by mjsoftking** [comment]
@ruibaby 
[视频](https://pan.sw0.top:8999/f/8mfY/%E9%99%84%E4%BB%B6%E5%BA%93%20-%20Halo%20%E5%90%8C%E5%90%8D%E5%9B%BE%E7%89%87%E8%A6%86%E7%9B%96%E9%97%AE%E9%A2%98.mp4)

当前环境：
内网docker部署；
ip直连未经过nginx；
刷新为 Ctrl键 + F5刷新模式；
因内网，不存在CDN等情况。

**Comment by ruibaby** [comment]
> @ruibaby [视频演示地址](https://pan.sw0.top:8999/f/8mfY/%E9%99%84%E4%BB%B6%E5%BA%93%20-%20Halo%20%E5%90%8C%E5%90%8D%E5%9B%BE%E7%89%87%E8%A6%86%E7%9B%96%E9%97%AE%E9%A2%98.mp4)
> 
> 当前环境： 内网docker部署； ip直连未经过nginx； 刷新为 Ctrl键 + F5刷新模式； 因内网，不存在CDN等情况。

Ctrl + F5 并不能保证每次请求都是经过服务器，你可以尝试打开浏览器的 Dev Tools，在网络中勾选禁用缓存。

https://github.com/halo-dev/halo/assets/21301288/a6f1ae4c-46fa-4608-b0b9-781671c1396e

**Comment by mjsoftking** [comment]
@ruibaby 感谢你的解答，看来应该是浏览器缓存了，这下放心替换错误的文件了，其他人浏览时估计会显示新图片了
