### ISSUE TITLE
默认earth主题侧边栏的社交不显示

### ISSUE THREAD

**Issue by xiedeacc** [halo-dev/halo#5132]
### System information

- External url: 
- Start time: 2023-12-30 14:18
- Version: 2.11.1-SNAPSHOT
- Build time: 2023-12-30 14:22
- Git Commit: 8e9b07d
- Java: Java(TM) SE Runtime Environment / 17.0.9+11-LTS-201
- Database: (Ubuntu) / 8.0.35-0ubuntu0.20.04.1
- Operating system: Linux / 5.15.0-1051-aws
- Activated theme: [Earth](https://github.com/halo-dev/theme-earth.git)
- Enabled plugins:
  - [highlight.js 代码高亮](https://github.com/halo-sigs/plugin-highlightjs)
  - [Vditor编辑器](https://github.com/justice2001/veditor-plugin)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)

### What is the project operation method?

Fat Jar

### Your site address.

https://blog.xiedeacc.com

### What happened?

主题设置了社交媒体，保存后不显示，小部件导致展示正常
![image](https://github.com/halo-dev/halo/assets/8072296/69b2dd52-66e7-401a-9de7-786476a0e698)

**Comment by ruibaby** [comment]
<img width="281" alt="图片" src="https://github.com/halo-dev/halo/assets/21301288/a128a86f-c59f-42c2-8223-ba862f2a517a">

没有添加**站点资料**的部件。

/kind support
/area theme

**Comment by xiedeacc** [comment]
感谢 感谢
