### ISSUE TITLE
文章或页面的设置中显示唯一ID，不可编辑可复制

### ISSUE THREAD

**Issue by mjsoftking** [halo-dev/halo#5135]
### Your current Halo version

2.11.3

### Describe this feature

文章或页面的设置中显示唯一ID，不可编辑可复制，主题友链需要设置一个页面ID来启用评论功能，如果ID填写页面别名，则评论审核时会显示 `未知 未知` ，这是因为填写的ID不正确，查看api文档说明，api的参数也是唯一ID所以没办法根据页面别名获取到唯一ID，如果可以显示这个ID就更好了。目前虽然可以通过控制台找到页面ID，但是获取ID的过程有些麻烦。

**Comment by ruibaby** [comment]
在主题设置中用 https://docs.halo.run/developer-guide/form-schema#singlepageselect 可能更好。

**Comment by mjsoftking** [comment]
@ruibaby 收到，另外咨询下这个组件选择后可以清空吗

**Comment by ruibaby** [comment]
> @ruibaby 收到，另外咨询下这个组件选择后可以清空吗

似乎不行，建议单独提个 issue，当前你可以在主题设置再加一个选项用于控制是否选择。

**Comment by mjsoftking** [comment]
@ruibaby 测试了一下确实不行，我先加一个独立开关吧
