### ISSUE TITLE
默认富文本编辑器的表格列宽显示问题

### ISSUE THREAD

**Issue by xueqidove** [halo-dev/halo#5138]
### System information

在线体验环境：https://demo.halo.run/console/actuator
版本号：[2.11.2]

### What is the project operation method?

Docker

### Your site address.

https://demo.halo.run/console

### What happened?

表格的展示问题，在编辑页面调整好了行列宽度，比如A宽B窄，但发布后可能A窄B宽，找不到规律，导致视觉上字少的反而很宽，字多的却窄窄的，很难看。
默认Markdown编辑器的编辑页面：
<img width="987" alt="image" src="https://github.com/halo-dev/halo/assets/60059766/df55103d-04b5-4c8b-8690-430ef2223f9d">

预览效果
<img width="867" alt="image" src="https://github.com/halo-dev/halo/assets/60059766/497133be-8ac4-4764-a395-cd4b57e4deab">

**Comment by LIlGG** [comment]
目前对于富文本编辑器生成的 HTML 没有包含 width 内联样式，可能需要增加。

/retitle 默认富文本编辑器的表格列宽显示问题

/kind improvement
/area console
/area editor
