### ISSUE TITLE
表格合并单元格后，能否默认将光标放在合并后的单元格中

### ISSUE THREAD

**Issue by xueqidove** [halo-dev/halo#5144]
### 你当前使用的版本

2.12.2

### 描述一下此特性

表格进行单元格合并后，能否默认将光标放在合并后的单元格中
![image](https://github.com/halo-dev/halo/assets/60059766/9bba9628-fd96-4332-9460-a12e13590025)

**Comment by LIlGG** [comment]
合并之后光标默认就在合并后的单元格内，不过由于合并后的单元格呈选中状态，因此光标不出现。
你直接在合并单元格之后直接输入内容。

/kind support
/close
