### ISSUE TITLE
如何设置文章，展示原创或者转载声明

### ISSUE THREAD

**Issue by TrueSaveWorldPig** [halo-dev/halo#5146]
### Your current Halo version

2.11

### Describe this feature

使用的是默认Earth主题，无法设置文章是原创或者转载

**Comment by ruibaby** [comment]
两个方案：

1. 通过主题提供自定义元数据，由主题适配，参考：https://docs.halo.run/developer-guide/theme/annotations
2. 通过插件在文章内容顶部或底部添加代码。

Halo 核心可能暂时不会考虑这样的功能。

/kind support

**Comment by ruibaby** [comment]
如果没有后续动态，我将关闭此 issue，后续可以重新提交或者重新打开此 issue。

/close
