### ISSUE TITLE
通过Docker Compose 部署无法自定义后台路径

### ISSUE THREAD

**Issue by 52lemon6** [halo-dev/halo#5152]
### 系统信息

- 外部访问地址: https://oniya.cn/
- 启动时间: 2024-01-04 09:53
- 版本: 2.11.3
- 构建时间: 2023-12-27 12:13
- Git Commit: 8e9b07d
- Java: IBM Semeru Runtime Open Edition / 17.0.9+9
- 数据库: 20200531 / 5.7.18-cynos-log
- 操作系统: Linux / 5.4.0-132-generic
- 已激活主题: [Theme Joe3](https://github.com/jiewenhuang/halo-theme-joe3.0)
- 已启动插件:
  - [Willow Markdown 编辑器](https://github.com/guqing/willow-mde)
  - [图库管理](https://github.com/halo-sigs/plugin-photos)
  - [文章导入导出](https://jhacker.cn/2023/halo-plugin-export2doc)
  - AI 助手
  - [Docsme](https://github.com/f2ccloud/plugin-docsme)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [站点推送插件](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [增强备份（Backup IMproved）](https://halo.run/store/apps/app-dHakX)
  - 联系表单
  - [文章限制阅读 Pro](https://github.com/f2ccloud/plugin-restricted-reading-pro)
  - [对象存储（Amazon S3 协议）](https://github.com/halo-dev/plugin-s3)
  - [站点迁移](https://github.com/halo-sigs/plugin-migrate)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

通过Docker Compose 部署无法自定义后台路径，尝试在`docker-compose.yaml`文件中加`admin-path: admin`但是`up`的时候提示`services.halo Additional property admin_path is not allowed`根据`https://docs.halo.run/getting-started/config/#%E5%90%8E%E5%8F%B0%E8%B7%AF%E5%BE%84`文档中所述修改`application.yaml`文件但是貌似Docker Compose部署的halo持久化的目录下并没有`application.yaml`文件，论坛中`https://bbs.halo.run/d/2216-%E5%90%8E%E5%8F%B0%E7%AE%A1%E7%90%86%E8%B7%AF%E5%BE%84%E8%83%BD%E5%90%A6%E9%85%8D%E7%BD%AE/3`所说使用 HALO_ADMIN_PATH 环境变量，参考：`https://docs.halo.run/getting-started/install/other/docker-compose`  其中的参考链接也已失效，无法打开

**Comment by ruibaby** [comment]
Halo 2 不支持修改控制台的访问地址，1.x 旧的文档已经在 docs.halo.run 中被删除，1.x 文档可以查阅：https://v1.legacy-docs.halo.run/

使用 Halo 2 请以最新的文档为准，论坛中的评论很可能已过时。
