### ISSUE TITLE
希望能增加新注册用户的邮箱认证和手机号认证，并且能限制注册的邮箱

### ISSUE THREAD

**Issue by 52lemon6** [halo-dev/halo#5154]
### 你当前使用的版本

2.11.3

### 描述一下此特性

1、现在`2.11.3`是只要你填写邮箱就能注册成功，希望能增加邮箱验证功能，即用户注册的时候就必须要验证通过后才能注册成功。这样能确保注册的邮箱是个真实有效的邮箱不是随便填写的邮箱
2、希望能限制注册的邮箱厂家，避免有人拿公共邮箱来注册
3、希望能支持手机号认证，并且能实现能设置使用某个功能的时候需要手机号验证成功后才能使用，比如发稿、ai助手、上传文件之类的行为

**Comment by mashirot** [comment]
1. 在后台 设置-用户设置 加一个checkbox，在新用户注册时是否强制验证邮箱regRequireVerifyEmail
    - true 在后台邮件通知相关填写时才能开启，
        - 请求/signup时返回regRequireVerifyEmail
        - 根据regRequireVerifyEmail渲染不同组件，true 多个发送验证码的btn和填写验证码的input
    - false 与现在行为相同
2. 在后台 设置-用户设置 加一个类似于element-plus的[动态标签](https://element-plus.org/zh-CN/component/tag.html#%E5%8A%A8%E6%80%81%E7%BC%96%E8%BE%91%E6%A0%87%E7%AD%BE)，用于填写allowedEmailProvider，或者搞个input填正则？
3. 没啥想法，也许可以单开一个issue

**Comment by mashirot** [comment]
#5016 repeated

**Comment by ruibaby** [comment]
感谢反馈这些问题。上述需求已经在 [Halo 专业版](https://www.lxware.cn/halo) 中支持，当前在开源版本中暂不考虑支持，但我们仍会探索让插件能够扩展这些表现。

/close
