### ISSUE TITLE
默认编辑器导出成md文件

### ISSUE THREAD

**Issue by MicroMatrixOrg** [halo-dev/halo#5157]
### Your current Halo version

 2.11.2

### Describe this feature

我看Notion的编辑器和halo的默认编辑器好像，然后我发现他们可以导出成md文档，绝大部分的语法都支持。halo的默认编辑器能否也导出成md文档，我写博客目前都是采用md的语法，还是挺希望能导出成md文档的

**Comment by wan92hen** [comment]
> ### Your current Halo version
> 2.11.2
> 
> ### Describe this feature
> 我看Notion的编辑器和halo的默认编辑器好像，然后我发现他们可以导出成md文档，绝大部分的语法都支持。halo的默认编辑器能否也导出成md文档，我写博客目前都是采用md的语法，还是挺希望能导出成md文档的
> 
> ### Additional information
> _No response_

导出后是需要做什么用呢？存档吗？

**Comment by ruibaby** [comment]
如果需要在多个地方编辑 Markdown 文件，建议一开始就使用 Markdown 编辑器进行编写。否则我们无法保证从富文本转到 Markdown 不会导致格式异常。

但如果只是为了导出以存档，可以考虑给 https://github.com/Lyn4ever29/halo-plugin-export-md 提交一个 issue，在导出文章的时候提供一个是否转到 Markdown 格式的选项。

/kind support

**Comment by MicroMatrixOrg** [comment]
> > ### Your current Halo version
> > 2.11.2
> > ### Describe this feature
> > 我看Notion的编辑器和halo的默认编辑器好像，然后我发现他们可以导出成md文档，绝大部分的语法都支持。halo的默认编辑器能否也导出成md文档，我写博客目前都是采用md的语法，还是挺希望能导出成md文档的
> > ### Additional information
> > _No response_
> 
> 导出后是需要做什么用呢？存档吗？

想存档，然后试试其他的md博客程序

**Comment by xinkeng0** [comment]
> > > ### Your current Halo version
> > > 2.11.2
> > > ### Describe this feature
> > > 我看Notion的编辑器和halo的默认编辑器好像，然后我发现他们可以导出成md文档，绝大部分的语法都支持。halo的默认编辑器能否也导出成md文档，我写博客目前都是采用md的语法，还是挺希望能导出成md文档的
> > > ### Additional information
> > > _No response_
> > 
> > 
> > 导出后是需要做什么用呢？存档吗？
> 
> 想存档，然后试试其他的md博客程序

1. 默认编辑器可以直接导出MD吗？
[答案是不可以](https://tiptap.dev/docs/editor/guide/output#not-an-option-markdown)
2. 但是我就需要导出MD有没有办法？
[答案是有](https://github.com/ProseMirror/prosemirror-markdown)，大致就是用markdown-it来映射Prosemirror-Schema。
有一个问题在于：任何Extension，必要时你都需要指明serialize function.
比如有一个Extension，其html为`<custome-p>`
```js
import { defaultMarkdownSerializer} from "@tiptap/pm/markdown"
defaultMarkdownSerializer.nodes['custome-p'] = (state, node) => {
    // To Markdown
    state.write(node.attrs.content)
}
```

**Comment by MicroMatrixOrg** [comment]
> > > > ### Your current Halo version
> > > > 2.11.2
> > > > ### Describe this feature
> > > > 我看Notion的编辑器和halo的默认编辑器好像，然后我发现他们可以导出成md文档，绝大部分的语法都支持。halo的默认编辑器能否也导出成md文档，我写博客目前都是采用md的语法，还是挺希望能导出成md文档的
> > > > ### Additional information
> > > > _No response_
> > > 
> > > 
> > > 导出后是需要做什么用呢？存档吗？
> > 
> > 
> > 想存档，然后试试其他的md博客程序
> 
> 1. 默认编辑器可以直接导出MD吗？
>    [答案是不可以](https://tiptap.dev/docs/editor/guide/output#not-an-option-markdown)
> 2. 但是我就需要导出MD有没有办法？
>    [答案是有](https://github.com/ProseMirror/prosemirror-markdown)，大致就是用markdown-it来映射Prosemirror-Schema。
>    有一个问题在于：任何Extension，必要时你都需要指明serialize function.
>    比如有一个Extension，其html为`<custome-p>`
> 
> ```js
> import { defaultMarkdownSerializer} from "@tiptap/pm/markdown"
> defaultMarkdownSerializer.nodes['custome-p'] = (state, node) => {
>     // To Markdown
>     state.write(node.attrs.content)
> }
> ```

哦哦，谢谢大佬解答，我发现一个很好的博客程序，可以达到我想要的结果了，也能解决博客文章的问题。我目前看中的是notion这种非常好的编辑器，但是渲染我挺喜欢halo的。https://elog.1874.cool/notion/ubcut43kgf97fag6 这个程序大佬合并了这几种方式
