### ISSUE TITLE
求助，docker部署的halo2.5，删除容器，重新运行到2.11.0版本后直接清空了我的站点，请问如何恢复

### ISSUE THREAD

**Issue by llody55** [halo-dev/halo#5158]
### System information

求助，docker部署的halo2.5，删除容器，重新运行到2.11.0版本后直接清空了我的站点，请问如何恢复，我重新拉起halo2.5的镜像也是一样，直接被初始化了。

### What is the project operation method?

Docker

### What happened?

求助，docker部署的halo2.5，删除容器，重新运行到2.11.0版本后直接清空了我的站点，请问如何恢复，我重新拉起halo2.5的镜像也是一样，直接被初始化了。

**Comment by JohnNiang** [comment]
/triage needs-information

需要提供更多关于安装和更新操作的细节，包括完整的执行命令。

**Comment by llody55** [comment]
@JohnNiang 请问命令我应该如何执行，我的执行过程如下
![image](https://github.com/halo-dev/halo/assets/9710645/230379aa-d094-400c-ade2-48b4cc86ebce)

**Comment by JohnNiang** [comment]
Hi @llody55 ，从截图中发现，你错误地挂载了目录 `/root/.halo`，Halo 2.x 应该挂载到 `/root/.halo2` 目录。具体情参考官方文档：<https://docs.halo.run/getting-started/install/docker>。

**Comment by llody55** [comment]
@JohnNiang 请问我还可以进行恢复吗？

**Comment by JohnNiang** [comment]
建议去搜索一下 Docker 容器误删后如何恢复 Volume。

同时你也可以通过 `docker volume ls` 查看卷，并通过 `docker inspect {{volume_id}}` 查看挂载宿主机目录，看看数据是否还存在。

**Comment by llody55** [comment]
@JohnNiang 我这个容器好像没有挂载目录，我以为数据都存储在数据库中呢

**Comment by ruibaby** [comment]
如果没有后续动态，我将关闭此 issue，后续可以重新提交或者重新打开此 issue。

/close
