### ISSUE TITLE
中途更换域名，sitemap里面域名不更新

### ISSUE THREAD

**Issue by adozhao** [halo-dev/halo#5161]
### 系统信息

- 外部访问地址: https://ado.js.cn/  ??? 概览里怎么也是老域名，应该是ado.zone
- 启动时间: 2023-12-21 11:20
- 版本: 2.11.2
- 构建时间: 2023-12-07 16:29
- Git Commit: 97b5f72
- Java: IBM Semeru Runtime Open Edition / 17.0.9+9
- 数据库: MySQL Community Server - GPL / 8.1.0
- 操作系统: Linux / 3.10.0-1160.99.1.el7.x86_64
- 已激活主题: [彼岸](https://github.com/guqing/halo-theme-higan)
- 已启动插件:
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [站点推送插件](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [Vditor编辑器](https://github.com/justice2001/veditor-plugin)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [highlight.js 代码高亮](https://github.com/halo-sigs/plugin-highlightjs)
  - [对象存储（Amazon S3 协议）](https://github.com/halo-dev/plugin-s3)
  - [增强备份（Backup IMproved）](https://halo.run/store/apps/app-dHakX)
  - [lightgallery.js 灯箱](https://github.com/halo-sigs/plugin-lightgallery)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)

### 使用的哪种方式运行？

Docker Compose

### 在线站点地址

https://ado.zone

### 发生了什么？

之前的域名是ado.js.cn，后来更换的ado.zone域名，二十天了，刚发现sitemap.xml里面的域名仍然是老域名，尝试卸载插件重新安装还是不行~

**Comment by guqing** [comment]
使用的什么版本的 sitemap 插件呢，升级到最新版试试

**Comment by adozhao** [comment]
> 使用的什么版本的 sitemap 插件呢，升级到最新版试试


1.1.1,这个应该是最新的了吧？而且我重启docker-compose服务也不行~

**Comment by ruibaby** [comment]
修改 compose 的配置文件之后，需要重建容器。

docker compose up -d

**Comment by adozhao** [comment]
> 修改 compose 的配置文件之后，需要重建容器。
> 
> docker compose up -d

挖草，感谢，我都忘记这里有配置了~

**Comment by ruibaby** [comment]
> 挖草，感谢，我都忘记这里有配置了~

修改之后解决了吗？

**Comment by adozhao** [comment]
> > 挖草，感谢，我都忘记这里有配置了~
> 
> 修改之后解决了吗？

解决了，感谢老大~
