### ISSUE TITLE
ocean主题搜索引擎老是搜索不到文章

### ISSUE THREAD

**Issue by fenhuahua** [halo-dev/halo#5172]
### 系统信息

发行版本 centos-7.9.2009
内核版本 3.10.0-1160.102.1.el7.x86_64
系统类型 x86_64

### 使用的哪种方式运行？

Docker

### 在线站点地址

https://zhiku.comtom.cn:8093/

### 发生了什么？

![image](https://github.com/halo-dev/halo/assets/153573296/a25f44df-2d2e-42fa-826c-9711a2b2f720)
![image](https://github.com/halo-dev/halo/assets/153573296/0e28d99a-0165-4752-9e05-f84ec60ef771)
搜索不到发布的文章，刷新搜索引擎也没有用？
怎么处理？？？？

**Comment by JohnNiang** [comment]
1. 环境信息还不够完整，例如 Halo 版本。
1. 建议刷新本地搜索引擎后，提供一下完整的日志。

/triage needs-information

**Comment by fenhuahua** [comment]
> 1. 环境信息还不够完整，例如 Halo 版本。
> 2. 建议刷新本地搜索引擎后，提供一下完整的日志。
> 
> /triage needs-information

[halo-20240110163839.log](https://github.com/halo-dev/halo/files/13885136/halo-20240110163839.log)
![image](https://github.com/halo-dev/halo/assets/153573296/220605cf-7e2b-4891-9232-30b4223d1c96)

**Comment by Rainsheep** [comment]
@fenhuahua 可以尝试 https://github.com/Rainsheep/halo-plugin-meilisearch 插件，已上架应用商店，部署/使用问题可联系我
