### ISSUE TITLE
feat: 统一 slug 字段

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#518]
## 概述

修改 `category` `tag` 表的 `slugName` 为 `slug`。修改 `post` 表的 `url` 为 `slug`。

## 动机

有些混乱，可能会造成主题开发者的困惑。同时满足我的强迫症。

## 详细解释

需要注意的是，需要向下兼容。此次改动将在下个版本中修改，并在下下个版本中废弃以前的 `slugName` 以及 `url`。

**Comment by wooseng** [comment]
建议修改下官网的主题开发文档，对着官网文档，一直出错，找了好半天才在这儿找到的答案，已经修改完了

**Comment by ruibaby** [comment]
> 建议修改下官网的主题开发文档，对着官网文档，一直出错，找了好半天才在这儿找到的答案，已经修改完了

会尽快修改的，现在公司太忙了。

**Comment by wooseng** [comment]
😄辛苦辛苦
