### ISSUE TITLE
文件编辑设置时间

### ISSUE THREAD

**Issue by MicroMatrixOrg** [halo-dev/halo#5180]
### 系统信息

2.11

### 使用的哪种方式运行？

Docker

### 在线站点地址

https://blog.micromatrix.cf/

### 发生了什么？

文字编辑设置时间，当第一次设置年的时候能正常设置。下一次修改的时候，年就设置紊乱，无法设置到正确的时间

**Comment by ruibaby** [comment]
根据你的描述无法复现这个问题，可以使用截图来说明问题吗？

/triage needs-information

**Comment by MicroMatrixOrg** [comment]
![image](https://github.com/halo-dev/halo/assets/21361701/daa1732f-19af-463d-8aeb-232b34661215)
目前是2021年，我想修改为2022年，先删除
![image](https://github.com/halo-dev/halo/assets/21361701/932d6f99-44c9-4591-96e2-8d4253f59c7d)
输入2
![image](https://github.com/halo-dev/halo/assets/21361701/11c9de4a-2ff8-4a87-baad-9c753a4b877b)
就变成上面这样了，而且无法输入到正确的数字

**Comment by ruibaby** [comment]
这个表现与浏览器有关，你可以使用右侧的图标进行日期选择。

当前日期时间选择使用的是浏览器原生提供的，自行实现组件请关注：https://github.com/halo-dev/halo/issues/2794

**Comment by MicroMatrixOrg** [comment]
> 这个表现与浏览器有关，你可以使用右侧的图标进行日期选择。
> 
> 当前日期时间选择使用的是浏览器原生提供的，自行实现组件请关注：#2794

我这个截图实在Chrome浏览器上的，我去MDN上看了
![image](https://github.com/halo-dev/halo/assets/21361701/769f0bd1-e136-48dc-8723-321919efe859)
原生的时间选择，他的是正常的
