### ISSUE TITLE
富文本编辑器表格滚动条鼠标移入不会出现导致无法滚动

### ISSUE THREAD

**Issue by guqing** [halo-dev/halo#5182]
### Your current Halo version

2.11.2

### Describe this feature

如题所述，富文本编辑器当横向过长后输入移入不会出现滚动条导致无法滚动，有写时候会误以为后面没内容

### Additional information

/kind improvement
/area editor
/area console

**Comment by LIlGG** [comment]
经过测试，滚动问题与系统中的是否自动显示滚动条有关。以 mac 为例，将 `系统设置 -> 外观 -> 显示滚动条` 设置为 滚动时，此时就会出现此问题。

解决此问题的办法是使用 `::-webkit-scrollbar` 重写表格的 scroll，使其永久显示滚动条。

/assign
