### ISSUE TITLE
 站点推送插件无法升级且点击升级后插件的配置会丢失

### ISSUE THREAD

**Issue by 52lemon6** [halo-dev/halo#5183]
### 系统信息

- 外部访问地址: https://oniya.cn/
- 启动时间: 2024-01-11 22:17
- 版本: 2.11.3
- 构建时间: 2023-12-27 12:13
- Git Commit: 8e9b07d
- Java: IBM Semeru Runtime Open Edition / 17.0.9+9
- 数据库: 20200531 / 5.7.18-cynos-log
- 操作系统: Linux / 5.4.0-132-generic
- 已激活主题: [Theme Joe3](https://github.com/jiewenhuang/halo-theme-joe3.0)
- 已启动插件:
  - [Willow Markdown 编辑器](https://github.com/guqing/willow-mde)
  - [图库管理](https://github.com/halo-sigs/plugin-photos)
  - [文章导入导出](https://jhacker.cn/2023/halo-plugin-export2doc)
  - AI 助手
  - [Docsme](https://github.com/f2ccloud/plugin-docsme)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [站点推送插件](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [增强备份（Backup IMproved）](https://halo.run/store/apps/app-dHakX)
  - 联系表单
  - [文章限制阅读 Pro](https://github.com/f2ccloud/plugin-restricted-reading-pro)
  - [对象存储（Amazon S3 协议）](https://github.com/halo-dev/plugin-s3)
  - [站点迁移](https://github.com/halo-sigs/plugin-migrate)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

 `站点推送插件`无法升级(1.4.0->1.4.1)且点击升级后插件的配置会丢失,日志太长了，GitHub上没办法直接粘进来所以传百度网盘了，链接: https://pan.baidu.com/s/1fY8XkHZHZ300YQuZ-15LnA?pwd=f66s 提取码: f66s

**Comment by ruibaby** [comment]
从日志来看，没有发现有关的异常。

[halo-log-2024-01-12 19_51.log](https://github.com/halo-dev/halo/files/13947283/halo-log-2024-01-12.19_51.log)

**Comment by ruibaby** [comment]
如果没有后续动态，我将关闭此 issue，如果可以确认是插件的问题，建议向插件提交 issue。

/close
