### ISSUE TITLE
ExtensionPoint 无法添加进 ExtensionPointEnabled

### ISSUE THREAD

**Issue by Rainsheep** [halo-dev/halo#5184]
### 你当前使用的版本

2.11

### 描述一下此特性

PostSearchService 使用 run.halo.app.plugin.extensionpoint.DefaultExtensionGetter#getEnabledExtension 来获取扩展点。
会读取 systemConfig 的 extensionPointEnabled，我没办法将插件扩展点添加进 systemConfig 的 extensionPointEnabled，并且我见其它扩展点都开始使用 getEnabledExtensionByDefinition。

综上，DefaultExtensionGetter#getEnabledExtension 是否是一个被淘汰的东西？ 是否应该统一使用 getEnabledExtensionByDefinition，或者提供将插件 PostSearchService 添加到 EnabledExtension 的方案。

**Comment by guqing** [comment]
我们后续会统一使用 getEnabledExtensionByDefinition
参考： https://github.com/halo-dev/halo/issues/4895
不过你可以就现在那样用 后续我们改了后会提供文档，也可以考虑提 pr 帮你修改

**Comment by Rainsheep** [comment]
ok, thanks
