### ISSUE TITLE
部分页面关闭评论功能

### ISSUE THREAD

**Issue by Omoinemie** [halo-dev/halo#5186]
### 描述一下此特性

目前是所有的页面下面都有个评论区，我想在管理主菜单时，就可以设置每个子菜单下面关闭打开评论功能，这样就只有自己想要的页面才有评论，一般是文章才有。
还有设置一个接口功能，对访客隐藏所有评论，国内个人博客备案要求不能有评论功能了。

**Comment by ruibaby** [comment]
有没有评论和菜单无关，也很难产生联系。如果你某些文章不需要评论，可以在文章设置中关闭评论功能。全局关闭可以在系统设置的评论设置中取消勾选 **启用评论**。

/kind support

**Comment by ruibaby** [comment]
相关文档：

- https://docs.halo.run/user-guide/settings#%E8%AF%84%E8%AE%BA%E8%AE%BE%E7%BD%AE
- https://docs.halo.run/user-guide/posts#%E8%AE%BE%E7%BD%AE%E8%AF%B4%E6%98%8E

**Comment by Omoinemie** [comment]
比如我相册，瞬间页面想关闭评论，我看了，没有独立可以设置的地方，我是直接添加的自定义链接页面/photos

**Comment by Omoinemie** [comment]
> 相关文档：
> 
> * https://docs.halo.run/user-guide/settings#%E8%AF%84%E8%AE%BA%E8%AE%BE%E7%BD%AE
> * https://docs.halo.run/user-guide/posts#%E8%AE%BE%E7%BD%AE%E8%AF%B4%E6%98%8E

比如我相册页面想关闭评论，我看了，没有独立可以设置的地方，我是直接添加的自定义链接页面/photos，
![image](https://github.com/halo-dev/halo/assets/31991443/4dfccaae-5cfc-4840-95e2-7de33330eed7)

**Comment by ruibaby** [comment]
相册本来就不支持评论，如果你是通过创建页面并设置主题的相册模板，那你可以在页面设置中关闭评论。

<img width="709" alt="图片" src="https://github.com/halo-dev/halo/assets/21301288/7479b3dd-53fa-4960-a0b4-d05df112ff78">

如果无效，那就是主题没有适配，建议向主题提交 issue。

**Comment by ruibaby** [comment]
如果没有后续动态，我将关闭此 issue，后续可重新提交或者重新打开。

/close
