### ISSUE TITLE
附件下载与直接查看存储策略中的附件

### ISSUE THREAD

**Issue by mhdy2233** [halo-dev/halo#5188]
### 你当前使用的版本

2.11.3

### 描述一下此特性

附件下载与直接查看存储策略中的附件,因为我经常使用Piclist所以挺希望加入这个功能的

**Comment by ruibaby** [comment]
没有理解这个功能。

> 直接查看存储策略中的附件

目前附件管理中可以根据存储策略筛选。

> 因为我经常使用Piclist所以挺希望加入这个功能的

和这个软件有什么必然的联系吗？

/triage needs-information

**Comment by mhdy2233** [comment]
这个功能的大致意思就是直接在halo的附件中查看到s3存储桶中的所以附件。
目前附件管理中虽然可以根据存储策略筛选，但是只能查看从halo中上传的附件。
我有时候会用Piclist上传到s3存储，需要使用的时候无法直接从halo附件中找到，需要回到Piclist从相册中查找链接。所以想问一下是否能实现这个功能

**Comment by ruibaby** [comment]
现在不能直接读取 S3 的内容，但 S3 的插件提供了关联的功能，可以利用此功能将存储桶的文件关联到 Halo。

<img width="1666" alt="图片" src="https://github.com/halo-dev/halo/assets/21301288/18905b98-ec86-42a1-a734-14714ef96c86">

**Comment by mhdy2233** [comment]
好的好的谢谢回答
