### ISSUE TITLE
API 备份失败问题

### ISSUE THREAD

**Issue by gaofangye** [halo-dev/halo#5190]
### System information

2.11.3

### What is the project operation method?

Docker

### What happened?

很奇怪的现象，我调用 API /apis/migration.halo.run/v1alpha1/backups 发起备份请求，成功后数据库表的 verison 值为 2，过了几秒钟变为 5，再过几秒记录就消失了

**Comment by JohnNiang** [comment]
需要确认一下是否设置过 `.spec.expiresAt`，如果备份到期了，则会自动删除。详情可看源码：

https://github.com/halo-dev/halo/blob/6d49047408fd89d11b8592d21db088b4420184f8/application/src/main/java/run/halo/app/migration/BackupReconciler.java#L108

/triage needs-information

**Comment by gaofangye** [comment]
解决了，就是你说的这个问题，谢谢
