### ISSUE TITLE
应用商店的上架流程是怎样的，付费内容的分成比例和支付方式等有文档吗

### ISSUE THREAD

**Issue by zhheo** [halo-dev/halo#5198]
### 描述一下此特性

找了好久没看到啊

**Comment by ruibaby** [comment]
目前还不支持开发者上架应用市场，不过已经在筹备相关开发事项，开发者中心上线之后我们提供详细的文档。

相关讨论：https://bbs.halo.run/d/4851-%E4%B8%AA%E4%BA%BA%E5%A6%82%E4%BD%95%E5%8F%91%E5%B8%83%E4%BB%98%E8%B4%B9%E6%8F%92%E4%BB%B6

> 我们可能会分阶段上线开发者中心，第一阶段可能会先支持申请入驻和上架免费应用。

**Comment by zhheo** [comment]
感谢，有兴趣开发付费主题，期待未来共同繁荣
