### ISSUE TITLE
编辑已发布文章的内容，只更改图片链接，不更改文章文字内容，点发布，提示发布成功，但实际不会保存新图片链接

### ISSUE THREAD

**Issue by mengtaixiao** [halo-dev/halo#5199]
### 系统信息

- 外部访问地址: https://blog.209902.xyz/
- 启动时间: 2024-01-17 01:35
- 版本: 2.11.3
- 构建时间: 2023-12-27 12:13
- Git Commit: 8e9b07d
- Java: IBM Semeru Runtime Open Edition / 17.0.9+9
- 数据库: H2 / 2.2.224
- 操作系统: Linux / 5.10.0-8-amd64
- 已激活主题: [Dream](https://github.com/nineya/halo-theme-dream2.0.git)
- 已启动插件:
  - [Vditor编辑器](https://github.com/justice2001/veditor-plugin)
  - [对象存储（Amazon S3 协议）](https://github.com/halo-dev/plugin-s3)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)

### 使用的哪种方式运行？

Docker Compose

### 在线站点地址

https://blog.209902.xyz/archives/1705491991649

### 发生了什么？

发现个BUG，Halo博客，Markdown编辑器（Vditor Markdown），编辑已发布文章的内容，只更改图片链接（更换图床，换新链接但图片还是那一张），不更改文章文字内容，点发布，提示发布成功，但实际不会保存新图片链接，再点编辑还是原来的图片链接，我还以为是CDN的问题，排查了半天才发现是Halo或者是Markdown编辑器的问题。

解决办法，更新图片链接的时候，也要更改文字内容，加个文字标点什么的都行（空格不行）。

**Comment by ruibaby** [comment]
> 解决办法，更新图片链接的时候，也要更改文字内容，加个文字标点什么的都行（空格不行）。

这似乎就已经可以判断是编辑器的问题，建议向插件提交 issue。

https://github.com/justice2001/halo-plugin-vditor

**Comment by justice2001** [comment]
确认是插件问题，这个issue应该可以关闭了。

**Comment by ruibaby** [comment]
See https://github.com/justice2001/halo-plugin-vditor/issues/20#issuecomment-1895979564

/close
