### ISSUE TITLE
建议添加微信提醒

### ISSUE THREAD

**Issue by 9527tech** [halo-dev/halo#52]
总觉得现在的邮件提醒有时候不能实时的看到,所以希望添加一个微信提醒的功能

> 可以使用方糖的[Server酱](http://sc.ftqq.com/)，设置简单，能实时推送评论,希望作者能添加这个功能

**Comment by ruibaby** [comment]
@9527tech 好的，感谢你的建议。

**Comment by ruibaby** [comment]
由于目前正在开发 V1 版本，所以该 issue 已经不适用于新版本，所以先关闭了。
