### ISSUE TITLE
使用docker-compose迁移1.x到2.11.3版本，使用外部mysql，页面都正常，修改内容数据库搜索不到

### ISSUE THREAD

**Issue by good2luck** [halo-dev/halo#5201]
### 系统信息

- 外部访问地址: https://xudj.top/
- 启动时间: 2024-01-15 22:15
- 版本: 2.11.3
- 构建时间: 2023-12-27 12:13
- Git Commit: 8e9b07d
- Java: IBM Semeru Runtime Open Edition / 17.0.9+9
- 数据库: (Ubuntu) / 8.0.35-0ubuntu0.22.04.1
- 操作系统: Linux / 5.15.0-86-generic
- 已激活主题: [Hao](https://githubfast.com/liuzhihang/halo-theme-hao)
- 已启动插件:
  - [Markdown / HTML 内容块](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [ByteMD](https://github.com/ruibaby/plugin-bytemd)
  - [StackEdit](https://github.com/halo-sigs/plugin-stackedit)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [站点迁移](https://github.com/halo-sigs/plugin-migrate)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

1、拉取镜像
docker pull halohub/halo:2.11.3
地址：https://hub.docker.com/r/halohub/halo/tags
2、创建docker-compose.yaml文件：命名为halo-docker-compose.yaml
`version: "3"

services:
  halo:
    image: halohub/halo:2.11.3
    container_name: halo
    restart: on-failure:3
    network_mode: "host"
    volumes:
      - ./halo2:/root/.halo2
    command:
      # 修改为自己已有的 MySQL 配置
      - --spring.r2dbc.url=r2dbc:pool:mysql://127.0.0.1:3306/xudj_top_halodb
      - --spring.r2dbc.username=root
      - --spring.r2dbc.password=***
      - --spring.sql.init.platform=mysql
      # 外部访问地址，请根据实际需要修改
      - --halo.external-url=https://xudj.top/
      # 端口号 默认8090
      - --server.port=8090`
3、部署与查看日志：
docker-compose -f halo-docker-compose.yaml up -d
docker-compose -f halo-docker-compose.yaml logs -f

问题：一切都正常，但数据库数据在哪？

**Comment by JohnNiang** [comment]
目前，Halo 就只有一张表，详情可参考：
- https://github.com/halo-dev/halo/issues/4388#issuecomment-1667701859
- https://github.com/halo-dev/halo/issues/4946#issuecomment-1835690121

/triage duplicate

**Comment by good2luck** [comment]
get, tks

**Comment by JohnNiang** [comment]
Close in favor of <https://github.com/halo-dev/halo/issues/4388>.

/close
