### ISSUE TITLE
希望可以支援部署在域名的二级目录

### ISSUE THREAD

**Issue by yohaneowo** [halo-dev/halo#5204]
### 你当前使用的版本

2.11.2

### 描述一下此特性

希望可以支援部署在域名的二级目录下，如www.google.com/blog 。
现在尝试用反向代理发现小部分可以支援，可是比如说文章之类的还是会导向主域名/archives，而不是www.xxx.com/blog/achives

**Comment by ruibaby** [comment]
不支持，且没有验证测试过，建议使用二级域名而不是二级目录。

此外，在提交 issue 前建议先搜索是否有相同的 issue。https://github.com/halo-dev/halo/issues?q=is%3Aissue+sort%3Aupdated-desc+%E4%BA%8C%E7%BA%A7%E7%9B%AE%E5%BD%95+is%3Aclosed

/triage duplicate
