### ISSUE TITLE
注册用户在默认编辑器粘贴图片报错

### ISSUE THREAD

**Issue by xhmily** [halo-dev/halo#5209]
### 系统信息

- 外部访问地址: https://wiki.dayz.plus/
- 启动时间: 2024-01-19 12:27
- 版本: 2.11.2
- 构建时间: 2023-12-07 16:29
- Git Commit: 97b5f72
- Java: IBM Semeru Runtime Open Edition / 17.0.9+9
- 数据库: 20220401 / 8.0.22-cynos
- 操作系统: Linux / 3.10.0-1160.95.1.el7.x86_64
- 已激活主题: [Ocean](https://github.com/f2ccloud/theme-ocean.git)
- 已启动插件:
  - [文本绘图](https://github.com/halo-sigs/plugin-text-diagram)
  - [通知我](https://github.com/monyuan/notify-me)
  - [Docsme](https://github.com/f2ccloud/plugin-docsme)
  - AI 助手
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [ToolBench](https://github.com/DioxideCN/Tool-Bench)
  - [社交 IAM 认证](https://github.com/f2ccloud/plugin-social-login)
  - [微信公众号发布](https://github.com/f2ccloud/plugin-platforms-sync)
  - [Willow Markdown 编辑器](https://github.com/guqing/willow-mde)
  - [站点推送插件](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [lightgallery.js 灯箱](https://github.com/halo-sigs/plugin-lightgallery)
  - [对象存储（Amazon S3 协议）](https://github.com/halo-dev/plugin-s3)
  - [增强备份（Backup IMproved）](https://halo.run/store/apps/app-dHakX)
  - [文章导入导出](https://jhacker.cn/2023/halo-plugin-export2doc)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)

### 使用的哪种方式运行？

Docker Compose

### 在线站点地址

wiki.dayz.plus

### 发生了什么？

测试除了使用超级管理员账号可以在默认编辑器通过粘贴方式上传图片，其它用户，无论什么角色，即使该角色基于超级管理员角色创建(权限一模一样)，也无法上传，粘贴就直接报错

### 相关日志输出

```shell
后台没有找到报错，这是接口返回的报错数据

{
  "apiVersion": "content.halo.run/v1alpha1",
  "kind": "Post",
  "metadata": {
    "annotations": {
      "content.halo.run/preferred-editor": "default",
      "content.halo.run/content-json": "{\"content\":\"<p style=\\\"\\\"></p>\",\"raw\":\"<p style=\\\"\\\"></p>\",\"rawType\":\"HTML\"}"
    },
    "name": "6ad9709a-05bb-46c2-aeeb-a83b1db618fb"
  },
  "spec": {
    "allowComment": true,
    "baseSnapshot": "",
    "categories": [],
    "cover": "",
    "deleted": false,
    "excerpt": {
      "autoGenerate": true,
      "raw": ""
    },
    "headSnapshot": "",
    "htmlMetas": [],
    "owner": "",
    "pinned": false,
    "priority": 0,
    "publish": false,
    "publishTime": "",
    "releaseSnapshot": "",
    "slug": "",
    "tags": [],
    "template": "",
    "title": "",
    "visible": "PUBLIC"
  }
}
```

**Comment by xhmily** [comment]
接口返回的状态代码:
400 Bad Request

**Comment by ruibaby** [comment]
这个问题已经在 2.11.3 修复。https://github.com/halo-dev/halo/releases/tag/v2.11.3

/triage duplicate
