### ISSUE TITLE
2.11 can not working！！！

### ISSUE THREAD

**Issue by yanbo5257** [halo-dev/halo#5215]
### System information

Docker environment information
Client:
 Version:           18.09.0
 EulerVersion:      18.09.0.320
 API version:       1.39
 Go version:        go1.19.4
 Git commit:        dc32e88
 Built:             Mon Mar 27 03:06:53 2023
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.0
  EulerVersion:     18.09.0.320
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.19.4
  Git commit:       dc32e88
  Built:            Mon Mar 27 03:06:18 2023
  OS/Arch:          linux/amd64
  Experimental:     false

### What is the project operation method?

Docker

### What happened?

Using the most basic installation example:
docker run -it -d --name halo -p 8090:8090 -v ~/.halo2:/root/.halo2 halohub/halo:2.11
After running, it is observed that port 8090 is listening, but there is no response through http://ip:port. In the logs, the following error is found:
r.h.a.e.controller.DefaultController: Optimistic locking failure when reconciling request: run.halo.app.core.extension.reconciler.SystemSettingReconciler-worker-1/Request[name=system-default]

### Relevant log output

```shell
r.h.a.e.controller.DefaultController: Optimistic locking failure when reconciling request: run.halo.app.core.extension.reconciler.SystemSettingReconciler-worker-1/Request[name=system-default]
```

**Comment by ruibaby** [comment]
see https://github.com/halo-dev/halo/issues/5215

/close
