### ISSUE TITLE
what the fuck？？》？？》？？？？

### ISSUE THREAD

**Issue by yanbo5257** [halo-dev/halo#5217]
### System information

fffff

### What is the project operation method?

Docker

### What happened?

version: "3"

services:
  halo:
    image: halohub/halo:2.11
    container_name: halo
    restart: on-failure:3
    depends_on:
      halodb:
        condition: service_healthy
    networks:
      halo_network:
    volumes:
      - ./halo2:/root/.halo2
    ports:
      - "8066:8066"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8066/actuator/health/readiness"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    command:
      - --spring.r2dbc.url=r2dbc:pool:postgresql://halodb/halo
      - --spring.r2dbc.username=halo
      # PostgreSQL 的密码，请保证与下方 POSTGRES_PASSWORD 的变量值一致。
      - --spring.r2dbc.password=openpostgresql
      - --spring.sql.init.platform=postgresql
      # 外部访问地址，请根据实际需要修改
      - --halo.external-url=http://localhost:8066/
  halodb:
    image: postgres:15.4
    container_name: halodb
    restart: on-failure:3
    networks:
      halo_network:
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_PASSWORD=openpostgresql
      - POSTGRES_USER=halo
      - POSTGRES_DB=halo
      - PGUSER=halo

networks:
  halo_network:

docker-compose up -d
ERROR: The Compose file './docker-compose.yaml' is invalid because:
services.halo.healthcheck value Additional properties are not allowed ('start_period' was unexpected)
services.halo.depends_on contains an invalid type, it should be an array

没有一个能用的，建议当场去世

### Relevant log output

```shell
fffff
```

### Additional information

fffff

**Comment by ruibaby** [comment]
Stupid issue.

You have seriously violated the https://github.com/halo-dev/halo/blob/main/CODE_OF_CONDUCT.md, and I will add you to the halo-dev blacklist."
