### ISSUE TITLE
feat: 增加文章以及页面的缓存功能

### ISSUE THREAD

**Issue by 52Lau** [halo-dev/halo#522]
## 提高用户打开页面速度，减少服务器压力

在拥有大量的文章的时候，希望能增加页面缓存，从而提高用户打开页面速度，减少服务器压力

**Comment by ruibaby** [comment]
是缓存整个页面还是数据？

**Comment by 52Lau** [comment]
@ruibaby 缓存整个页面,类似PHP建站

**Comment by ruibaby** [comment]
可以有，不过得排在后面了。

**Comment by 52Lau** [comment]
嗯，感谢采纳

**Comment by ruibaby** [comment]
目前已经做好了全站的静态页面生成，稍微改造应该可以实现你的需求。

**Comment by 52Lau** [comment]
是的，我看了issues里面网友分享的网站，都很快。
一般文章页面，发布之后，很少变动了，可以缓存起来，分类页面发布或更新文章之后触发更新缓存。
文章多，流量大的情况下，可以有限的利用服务器资源。

**Comment by ruibaby** [comment]
嗯，是个不错的主意，我们会在静态部署这个功能完善之后再做这方面的功能。

**Comment by 52Lau** [comment]
嗯，非常感谢

**Comment by ruibaby** [comment]
/close

see https://github.com/halo-dev/halo/issues/2827
