### ISSUE TITLE
"投稿者"和"作者"角色拥有的权限貌似和语义不符

### ISSUE THREAD

**Issue by guqing** [halo-dev/halo#5222]
### Your current Halo version

2.11.3

### Describe this feature

投稿者拥有“允许管理自己文章”的权限，而“作者”拥有允许投稿的角色，权限和角色名语义不符，建议改为:

- 投稿者：拥有“允许投稿”的权限。
- 作者：拥有“允许管理自己的文章”和”允许发布自己的文章“的权限。

### Additional information

/kind improvement
/area core

**Comment by JohnNiang** [comment]
从 https://github.com/halo-dev/halo/blob/14580b96b07525fc25f161b96a8459ec803f9e5e/application/src/main/resources/extensions/role-template-uc-content.yaml 看，角色定义应该没有问题。应该是翻译过程中混淆了，请看下面的代码片段：
https://github.com/halo-dev/halo/blob/14580b96b07525fc25f161b96a8459ec803f9e5e/console/src/locales/en.yaml#L1355-L1356

**Comment by ruibaby** [comment]
应该是前端没有处理好依赖关系，正常情况应该是这样：

<img width="934" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/82da2052-9ea2-461c-a000-3a0ca2c33df9">

但是回显的时候没有勾上依赖的角色模板。
