### ISSUE TITLE
Halo程序支持自动更新

### ISSUE THREAD

**Issue by adozhao** [halo-dev/halo#5231]
### 你当前使用的版本

2.11.2

### 描述一下此特性

以后Halo程序回支持在线更新么，或者目前有没有在开发计划中？

**Comment by JohnNiang** [comment]
/triage duplicate

See https://github.com/halo-dev/halo/issues/1675 for more.

**Comment by JohnNiang** [comment]
Close in favor of <https://github.com/halo-dev/halo/issues/1675>.

/close
