### ISSUE TITLE
统计项里同时返回访客数据，与访问量不同

### ISSUE THREAD

**Issue by mjsoftking** [halo-dev/halo#5242]
### 你当前使用的版本

2.11.3

### 描述一下此特性

统计项里同时返回访客数据，与访问量不同。
```
siteStatsFinder.getStats()
```
应该访问统计IP数量就行

**Comment by mjsoftking** [comment]
不知道是否可以实现，若不能实现就关闭吧

**Comment by ruibaby** [comment]
目前数据统计应该是没有持久化所有数据的，这个量会比较大。两种解决方式：

1. 使用外部的统计服务，Halo 只需要暴露数据。
2. 使用网站数据统计平台，比如 Umami。

**Comment by guqing** [comment]
siteStatsFinder.getStats() 这个访问量只是文章和自定义页面的访问量，不区分 ip 只计数访问次数

**Comment by mjsoftking** [comment]
@ruibaby 因为第三方的数据与哈喽的计数严重不符，所以才想halo可以返回是最好的，不方便实现就无用关注这个
