### ISSUE TITLE
插件停止生命周期中Scheme卸载问题导致升级错误

### ISSUE THREAD

**Issue by guqing** [halo-dev/halo#5243]
### 系统信息

- 外部访问地址: https://guqing.io
- 启动时间: 2023-12-01 14:22
- 版本: 2.11.0
- 构建时间: 2023-12-01 12:01
- Git Commit: 0351a67
- Java: IBM Semeru Runtime Open Edition / 17.0.9+9
- 数据库: PostgreSQL / 10.4 (Debian 10.4-2.pgdg90+1)
- 操作系统: Linux / 3.10.0-1160.62.1.el7.x86_64
- 已激活主题: [彼岸](https://github.com/guqing/halo-theme-higan)
- 已启动插件:
  - AI 助手
  - [Metrics Graph](https://github.com/guqing/plugin-metrics-graph)
  - [Willow Markdown 编辑器](https://github.com/guqing/willow-mde)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)
  - [增强备份（Backup IMproved）](https://halo.run/store/apps/app-dHakX)
  - [图库管理](https://github.com/halo-sigs/plugin-photos)
  - [lightgallery.js 灯箱](https://github.com/halo-sigs/plugin-lightgallery)
  - [ByteMD](https://github.com/ruibaby/plugin-bytemd)
  - [OAuth2 认证](https://github.com/halo-sigs/plugin-oauth2)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [Umami](https://github.com/halo-sigs/plugin-umami)
  - [highlight.js 代码高亮](https://github.com/halo-sigs/plugin-highlightjs)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [对象存储（Amazon S3 协议）](https://github.com/halo-dev/plugin-s3)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)

### 使用的哪种方式运行？

Docker

### 在线站点地址

https://guqing.io

### 发生了什么？

在插件的停止（stop）生命周期中，尝试通过 `Scheme.buildFromType` 方法构建 Scheme 并使用 `schemeManager.unregister` 进行清理。但是，这种方式无法正确地从 `SchemeManager` 中移除相应的 scheme，导致在升级插件时出现 `indexer 已存在的错误。问题代码段如下：

```java
public void stop() {
        schemeManager.unregister(Scheme.buildFromType(AuthorizedClient.class));
        schemeManager.unregister(Scheme.buildFromType(Oauth2ClientRegistration.class));
 }
```
需要确保 Scheme 的 equals 和 hashCode 方法是否正确。

参考: [Stop life cycle method in oauth2](https://github.com/halo-sigs/plugin-oauth2/blob/c5fa0baf3077f4ac6f5188aad98d49ad699452f6/src/main/java/run/halo/oauth/OauthGithubPlugin.java#L33)

关联 issue: #5237

### 附加信息

/kind bug
/area core
/milestone 2.12.x

**Comment by JohnNiang** [comment]
建议在 https://github.com/halo-dev/halo/issues/5237 下直接评论即可，无需创建新的 Issue。
