### ISSUE TITLE
用户登录可以支持MFA

### ISSUE THREAD

**Issue by chinagoldline** [halo-dev/halo#5247]
### 你当前使用的版本

2.11.0

### 描述一下此特性

实现思路类似github账号两步验证这种，保障系统安全性。
看了下历史Issue，之前有伙伴提交过PR，希望Halo2.0可以把该功能从1.0迁移过来。

**Comment by chinagoldline** [comment]
历史Issue: [https://github.com/halo-dev/halo/issues/712](url)
历史PR: [https://github.com/halo-dev/halo/pull/745](url)

**Comment by ruibaby** [comment]
/triage duplicate 

See https://github.com/halo-dev/halo/issues/4541

2.12.0-alpha.1 已经支持 TOTP，https://github.com/halo-dev/halo/releases/tag/v2.12.0-alpha.1
