### ISSUE TITLE
标题无法换行 输入\r\n都没用

### ISSUE THREAD

**Issue by yuanyiying123** [halo-dev/halo#5257]
### System information

运行正常

### What is the project operation method?

Docker

### What happened?

主页标题输入框文字无法换行显示

**Comment by JohnNiang** [comment]
Hi @yuanyiying123 , thanks for reaching out here!

`\r\n` 是 Windows 的[换行符](https://en.wikipedia.org/wiki/Newline)，并不适用于 HTML。

如果主题设置本身不支持换行，那应该是无法实现换行的。建议去对应的主题提交 Issue。

/triage unresolved
