### ISSUE TITLE
feat: 新增 metadata 获取器

### ISSUE THREAD

**Issue by JohnNiang** [halo-dev/halo#526]
## 概述

用户上传文件的时候会打开图片文件，并读取相关信息，此时的会消耗较多的 CPU 和内存。所以，可以考虑只读取图片的 Metadata 来获取图片的各种信息。

**Comment by KristenLawrence** [comment]
你好，我想帮忙实现这个feature : )
请问读取图片metadata可以借助一些现有的库来完成吗？Halo对于第三方依赖的引入有没有什么限制？

**Comment by JohnNiang** [comment]
- 外部依赖尽可能的小
- 足够稳定，就算不稳定也得持续活跃更新

如果外部依赖也是通过 BufferednImage 来实现的话，那就没有必要引入了。
