### ISSUE TITLE
分类api返回的数据好像是倒序的

### ISSUE THREAD

**Issue by mjsoftking** [halo-dev/halo#5264]
### 系统信息

- 外部访问地址: https://www.sw0.top
- 启动时间: 2024-01-27 14:22
- 版本: 2.11.3
- 构建时间: 2023-12-27 12:13
- Git Commit: 8e9b07d
- Java: IBM Semeru Runtime Open Edition / 17.0.9+9
- 数据库: PostgreSQL / 16.1
- 操作系统: Linux / 5.10.0-16-amd64
- 已激活主题: [Dream](https://github.com/nineya/halo-theme-dream2.0.git)
- 已启动插件:
  - [朋友圈](https://github.com/chengzhongxue/plugin-friends)
  - [文本绘图](https://github.com/halo-sigs/plugin-text-diagram)
  - [Docsme](https://github.com/f2ccloud/plugin-docsme)
  - AI 助手
  - [Umami](https://github.com/halo-sigs/plugin-umami)
  - [LDAP Login](https://github.com/f2ccloud/plugin-ldap-login)
  - [增强备份（Backup IMproved）](https://halo.run/store/apps/app-dHakX)
  - [Metrics Graph](https://github.com/guqing/plugin-metrics-graph)
  - [社交 IAM 认证](https://github.com/f2ccloud/plugin-social-login)
  - [Vditor编辑器](https://github.com/justice2001/veditor-plugin)
  - [文章导入导出](https://jhacker.cn/2023/halo-plugin-export2doc)
  - [对象存储（Amazon S3 协议）](https://github.com/halo-dev/plugin-s3)
  - 联系表单
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [微信公众号发布](https://github.com/f2ccloud/plugin-platforms-sync)
  - [Markdown / HTML 内容块](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [文章限制阅读 Pro](https://github.com/f2ccloud/plugin-restricted-reading-pro)
  - [Willow Markdown 编辑器](https://github.com/guqing/willow-mde)
  - [站点推送插件](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [OAuth2 认证](https://github.com/halo-sigs/plugin-oauth2)
  - [KaTeX](https://github.com/halo-sigs/plugin-katex)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [lightgallery.js 灯箱](https://github.com/halo-sigs/plugin-lightgallery)
  - [live2d 看板娘](https://github.com/LIlGG/plugin-live2d)
  - [图库管理](https://github.com/halo-sigs/plugin-photos)
  - [ByteMD](https://github.com/ruibaby/plugin-bytemd)
  - [StackEdit](https://github.com/halo-sigs/plugin-stackedit)
  - [highlight.js 代码高亮](https://github.com/halo-sigs/plugin-highlightjs)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)

### 使用的哪种方式运行？

Docker

### 发生了什么？

分类api返回的数据好像是倒序的
![image](https://github.com/halo-dev/halo/assets/23021469/bbc8d30c-bd27-42db-a21e-aeefb0bb848c)

### api
tagFinder.list(1,num)

### 结果
![image](https://github.com/halo-dev/halo/assets/23021469/1e87bc77-f787-4867-8790-f83ece3a0c6c)

**Comment by ruibaby** [comment]
请根据 issue 模板补充系统信息。

/triage needs-information

**Comment by mjsoftking** [comment]
> 请根据 issue 模板补充系统信息。
> 
> /triage needs-information

 补充了

**Comment by ruibaby** [comment]
在我这边没有复现这个问题，建议提供一下主题的相关代码。

<img width="254" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/52da5f28-9165-42c6-ae3a-9541a968c60e">
<img width="352" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/d3ee9e19-7593-4216-ae42-537afb49e874">

**Comment by mjsoftking** [comment]
```
<div xmlns:th="https://www.thymeleaf.org"
     th:fragment="widget (hide)"
     th:class="'card widget tags ' + ${hide}"
     th:with="num = ${#strings.isEmpty(theme.config.sidebar.tags_num)? 18 : T(java.lang.Integer).parseInt(theme.config.sidebar.tags_num)},
     tags = ${tagFinder.list(1,num)},
     isEmpty = ${#lists.isEmpty(tags)},
     enableTagsColor = ${theme.config.sidebar.enable_tag_color}">
    <div class="card-title">
        <i class="ri-price-tag-3-line card-title-label"></i><span>标签</span>
        <a th:if="${tags.hasNext}" class="card-more" th:href="@{/tags}">更多<i class="ri-arrow-right-double-line"></i></a>
    </div>
    <div th:if="${isEmpty}" class="card-empty">暂无标签</div>
    <div th:unless="${isEmpty}" class="card-content">
        <a
          th:each="tag : ${tags}"
          th:href="@{${tag.status.permalink}}"
          th:text="${tag.spec.displayName}"
          th:style="${(enableTagsColor && tag.spec.color != '#ffffff')? 'color: ' + tag.spec.color +'; border-color: ' + tag.spec.color +'; background: ' + tag.spec.color +'20;' : ''}"></a>
    </div>
</div>
```

看了一下主题的代码，就请求了一下，然后循环写入的

**Comment by mjsoftking** [comment]
好像还是主题的问题
