### ISSUE TITLE
自定义的mysql数据库中的halo库并没有任何表和数据？且没有报错

### ISSUE THREAD

**Issue by Sdreamery** [halo-dev/halo#5267]
### System information

Nothing to preview

### What is the project operation method?

Docker Compose

### What happened?

![image](https://github.com/halo-dev/halo/assets/38490969/c0d87e36-c29a-480f-940c-aa5a4c8d6b31)
![image](https://github.com/halo-dev/halo/assets/38490969/0b237266-470e-4806-bde7-037654aa1a5d)
![image](https://github.com/halo-dev/halo/assets/38490969/f2e29332-10fc-4126-aecb-3e192b18f126)

### Relevant log output

```shell
Nothing to preview
```

### Additional information

Nothing to preview

**Comment by guqing** [comment]
根据你给出的配置来看并没有什么问题，启动 halo 后你的连接 MySQL 的客户端是否有点击过刷新视图？

**Comment by Sdreamery** [comment]
> 根据你给出的配置来看并没有什么问题，启动 halo 后你的连接 MySQL 的客户端是否有点击过刷新？如果没有可以刷新一下看看

刷新过了呢，就是没有数据不知道为啥

**Comment by Sdreamery** [comment]
是对数据库的属性有什么要求吗？
![image](https://github.com/halo-dev/halo/assets/38490969/32009e02-be8a-4dfb-be5e-2a33b8974129)

**Comment by Sdreamery** [comment]
还是说对MySQL版本有要求？我用的mysql版本是8.1.0

**Comment by Sdreamery** [comment]
之前使用已有的MySQL数据库不行，换成带MySQL镜像的重新构建可以了，但是只有一个表吗？
![1706506400485](https://github.com/halo-dev/halo/assets/38490969/5a325c7a-cccf-41ed-86da-97a0545dbf30)
![image](https://github.com/halo-dev/halo/assets/38490969/7f69f83e-602f-4163-8490-2310ffaf1629)

**Comment by guqing** [comment]
> 之前使用已有的MySQL数据库不行，换成带MySQL镜像的重新构建可以了，但是只有一个表吗？ ![1706506400485]

是的，目前 Halo 只有一张表，参考：
- [Halo 自定义模型设计](https://github.com/halo-dev/rfcs/tree/main/extension)
- [Halo 索引设计](https://github.com/halo-dev/halo/tree/main/docs/index)

**Comment by JohnNiang** [comment]
/triage unresolved
/remove-kind support

I'm going to close this issue. Please feel free to reopen if the problem still exists.

/close
