### ISSUE TITLE
将 AttachmentSelectorModal 组件向个人中心全局注册

### ISSUE THREAD

**Issue by LIlGG** [halo-dev/halo#5278]
### 你当前使用的版本

2.12.0-alpha.1

### 描述一下此特性

瞬间插件使用 `AttachmentSelectorModal` 打开附件选择库来上传文件。但由于此组件只在 console 端进行了全局注册，因此在个人中心使用时无法生效，建议向个人中心也注册此组件。

https://github.com/halo-dev/halo/blob/2de03851c4ddf7910e6f0b8df2e64c96f1185272/console/console-src/modules/contents/attachments/module.ts#L8-L11

/area console
/milestone 2.12.x

**Comment by ruibaby** [comment]
> 这个2.15能不能上

这个功能可能不仅仅是将 AttachmentSelectorModal 在个人中心注册就可以解决的，还需要：

- 重构 AttachmentSelectorModal 组件，因为目前这个组件依赖了太多 Console 这边才支持的东西
- 要考虑权限问题
- 要考虑是否为个人中心提供单独接口的问题（用于列出单个用户上传的附件
