### ISSUE TITLE
非管理员无法正常使用两步验证设置

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#5287]
### 系统信息

- 外部访问地址: 
- 启动时间: 2024-01-31 11:26
- 版本: 2.12.0-SNAPSHOT
- 构建时间: 2024-01-31 11:26
- Git Commit: 859cbad
- Java: OpenJDK Runtime Environment / 17.0.9+0
- 数据库: PostgreSQL / 15.2 (Debian 15.2-1.pgdg110+1)
- 操作系统: Mac OS X / 14.3
- 已激活主题: [Walker](https://halo.run/store/apps/app-GHgAR)
- 已启动插件: 

### 使用的哪种方式运行？

Source Code

### 发生了什么？

如图：

<img width="1920" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/a325a2a4-9e7d-4055-8592-7acaf9a2298c">

**Comment by JohnNiang** [comment]
确认是因为权限配置有问题，我将重构 2FA 相关的 API，并重新配置角色模板。

/kind bug
/area core
/milestone 2.12.0
/assign
