### ISSUE TITLE
希望 AdditionalWebFilter 可以拦截门户请求

### ISSUE THREAD

**Issue by guqing** [halo-dev/halo#5300]
### Your current Halo version

2.12.0

### Describe this feature

目前 AdditionalWebFilter 只支持拦截受保护的 APIs 不支持拦截门户请求如访问首页，这就无法实现诸如门户访问统计等功能，希望可以支持拦截门户请求

### Additional information

/kind improvement
/area core
/milestone 2.13.x

**Comment by JohnNiang** [comment]
建议提供一个特定位置的 WebFilter，例如：`org.springframework.security.config.web.server.SecurityWebFiltersOrder#LAST`。这样可以保证 Filter 不会在系统中所一定的 Filters 之前或者之后。

**Comment by JohnNiang** [comment]
从我[了解的情况](https://docs.spring.io/spring-framework/reference/web/webflux/reactive-spring.html#webflux-filters)来看，只需要定义一个 WebFilter 即可完成以上功能，和 Security 模块没有任何关系。Spring Security 也是类似提供了 org.springframework.security.web.server.WebFilterChainProxy（WebFilter 的实现） 来管理和 Security 相关的 filters。

而且，目前的 AdditionalWebFilter 本身就是执行在 Security 相关的 filters 之前，请看下面的截图：
<img width="1297" alt="image" src="https://github.com/halo-dev/halo/assets/16865714/b36a5a06-bcb3-4717-bca0-43541ca98b2e">


以上截图中的结果并非我们的预期。所以我们是否需要重新考虑一下 AdditionalWebFilter 的定位，可以学习一下 WebFilterChainProxy 的实现，并在 WebFilterChainProxy 之前组合 AdditionalWebFilters，既能不破坏现有逻辑，也能实现拦截门户的请求。

**Comment by guqing** [comment]
@JohnNiang 原本的预期是希望 AdditionalFilter 可以自由组合在 security 的 filters 之间，但实际发现目前无法实现，如果改用 WebFilterChainProxy 相当于 AdditionalFilter 只是可以在 filter chains 上增加过滤器而不再与 security 的 filters 有关系对吧

**Comment by JohnNiang** [comment]
> @JohnNiang 原本的预期是希望 AdditionalFilter 可以自由组合在 security 的 filters 之间，但实际发现目前无法实现，如果改用 WebFilterChainProxy 相当于 AdditionalFilter 只是可以在 filter chains 上增加过滤器而不再与 security 的 filters 有关系对吧

是的，当前实现和预期不符。AdditionWebFilter 的行为可以保持，不影响已有的插件。这样既可以实现门户请求的拦截，也可以实现插件已经实现的功能。

后面可以考虑再增加相关的 Security 相关的 Filter 扩展点，而不是用 AdditionaWebFilter。

https://github.com/halo-dev/halo/pull/5349 中明确了 AdditionalWebFilter 的作用而已，没有改变执行逻辑，不影响已有的插件。

**Comment by guqing** [comment]
> > @JohnNiang 原本的预期是希望 AdditionalFilter 可以自由组合在 security 的 filters 之间，但实际发现目前无法实现，如果改用 WebFilterChainProxy 相当于 AdditionalFilter 只是可以在 filter chains 上增加过滤器而不再与 security 的 filters 有关系对吧
> 
> 是的，当前实现和预期不符。AdditionWebFilter 的行为可以保持，不影响已有的插件。这样既可以实现门户请求的拦截，也可以实现插件已经实现的功能。
> 
> 后面可以考虑再增加相关的 Security 相关的 Filter 扩展点，而不是用 AdditionaWebFilter。
> 
> #5349 中明确了 AdditionalWebFilter 的作用而已，没有改变执行逻辑，不影响已有的插件。

OK，可行
