### ISSUE TITLE
支持通过 docker 镜像标签设置为 halohub/halo:2 来拉取最新镜像

### ISSUE THREAD

**Issue by leic4u** [halo-dev/halo#5303]
### 你当前使用的版本

v2.12.0

### 描述一下此特性

目前可以通过把 docker 镜像的标签设置为 `halohub/halo:2.12` 来拉取 v2.12.x 版本，但涉及到跨小版本时还是得手动改下配置。

期望可以支持在 docker 镜像标签设置为 `halohub/halo:2` 的情况下，拉取 v2.x.x 版本的最新镜像。

**Comment by leic4u** [comment]
same issue #4976

**Comment by JohnNiang** [comment]
Hi @leic4u，建议不要提交重复的 Issue，可以直接在 https://github.com/halo-dev/halo/issues/4976 下评论即可。

/triage duplicate

Close in favor of https://github.com/halo-dev/halo/issues/4976

/close
