### ISSUE TITLE
管理员页面出现黑黑色的圆

### ISSUE THREAD

**Issue by heqiaomu** [halo-dev/halo#5306]
### 系统信息

- 外部访问地址: http://blog.heqiaomu123.cn/
- 启动时间: 2024-02-02 14:42
- 版本: 2.12.0
- 构建时间: 2024-02-01 10:29
- Git Commit: e85a55e
- Java: IBM Semeru Runtime Open Edition / 17.0.9+9
- 数据库: MySQL Community Server - GPL / 8.1.0
- 操作系统: Linux / 3.10.0-1160.105.1.el7.x86_64
- 已激活主题: [Theme Joe3](https://github.com/jiewenhuang/halo-theme-joe3.0)
- 已启动插件:
  - [Meilisearch](https://github.com/Rainsheep/halo-plugin-meilisearch)
  - [Vditor编辑器](https://github.com/justice2001/veditor-plugin)
  - [站点推送插件](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)

### 使用的哪种方式运行？

Docker

### 在线站点地址

http://blog.heqiaomu123.cn

### 发生了什么？

在 console 路由页面下，出现了大量的：
<img width="1026" alt="image" src="https://github.com/halo-dev/halo/assets/117645192/fca994c9-592c-48bb-abf5-a10d9a0c15ac">
<img width="1517" alt="image" src="https://github.com/halo-dev/halo/assets/117645192/f896d581-e542-474d-b3be-16530e540fda">
在当前的页面上，如果页面本身内容过多，会发现下面的被黑色区域覆盖的部分是无法去进行选择的。这应该是前端的一个BUG。

**Comment by JohnNiang** [comment]
建议尝试强制刷新浏览器缓存（或者使用无痕模式运行）后重试。

/triage needs-information

**Comment by YyJqW** [comment]
你是否使用了MaxAI.me的浏览器拓展插件？在该插件设置中的外观选项里关闭快速访问，或者禁用该插件可解决此问题

**Comment by ruibaby** [comment]
如果没有后续动态，我将关闭此 issue，后续如果还有类似问题，可以重新提交 issue。

/close
