### ISSUE TITLE
新建菜单 无法显示

### ISSUE THREAD

**Issue by losie** [halo-dev/halo#5316]
### 系统信息

- 外部访问地址: 
- 启动时间: 2024-02-03 12:39
- 版本: 2.12.0
- 构建时间: 2024-02-01 10:29
- Git Commit: e85a55e
- Java: IBM Semeru Runtime Open Edition / 17.0.9+9
- 数据库: Source distribution / 5.7.40-log
- 操作系统: Linux / 3.10.0-957.21.3.el7.x86_64
- 已激活主题: [Hao](https://githubfast.com/liuzhihang/halo-theme-hao)
- 已启动插件:
  - [我的装备管理](https://github.com/halo-sigs/plugin-equipments)
  - [HaoTag](https://github.com/chengzhongxue/plugin-haotag)
  - [追番插件](https://github.com/Roozenlz/plugin-bilibili-bangumi)
  - [图库管理](https://github.com/halo-sigs/plugin-photos)
  - [prism.js 代码高亮](https://github.com/liuzhihang/plugin-prismjs)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)

### 使用的哪种方式运行？

Docker

### 在线站点地址

/

### 发生了什么？

https://github.com/halo-dev/halo/assets/36534236/373e0230-6c76-4349-9019-c7364cafca86

新建菜单 无法显示

**Comment by ruibaby** [comment]
看起来问题原因和 https://github.com/halo-dev/halo/issues/5315 一致，目前已经发布 [2.12.2](https://github.com/halo-dev/halo/releases/tag/v2.12.2) 修复了此问题，建议更新到 2.12.2 试试。

/triage needs-information

**Comment by ruibaby** [comment]
any updates?
