### ISSUE TITLE
使用1plane将halo从2.11.3升级到2.12.0后博客首页404

### ISSUE THREAD

**Issue by YoungLee-coder** [halo-dev/halo#5318]
### 系统信息

- 外部访问地址: https://younglee.cn
- 启动时间: 2024-02-03 22:19
- 版本: 2.11.3
- 构建时间: 2023-12-27 12:13
- Git Commit: 8e9b07d
- Java: IBM Semeru Runtime Open Edition / 17.0.9+9
- 数据库: MariaDB / 10.11.6-MariaDB-1:10.11.6+maria~ubu2204
- 操作系统: Linux / 5.15.0-84-generic
- 已激活主题: [Walker](https://halo.run/store/apps/app-GHgAR)
- 已启动插件:
  - [文章导入导出](https://jhacker.cn/2023/halo-plugin-export2doc)
  - [Markdown / HTML 内容块](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [OAuth2 认证](https://github.com/halo-sigs/plugin-oauth2)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [lightgallery.js 灯箱](https://github.com/halo-sigs/plugin-lightgallery)
  - [StackEdit](https://github.com/halo-sigs/plugin-stackedit)
  - [站点推送插件](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [追番插件](https://github.com/Roozenlz/plugin-bilibili-bangumi)
  - [KaTeX](https://github.com/halo-sigs/plugin-katex)
  - [图库管理](https://github.com/halo-sigs/plugin-photos)
  - [highlight.js 代码高亮](https://github.com/halo-sigs/plugin-highlightjs)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [Sitemap](https://github.com/halo-sigs/plugin-sitemap)
  - [RSS](https://github.com/halo-sigs/plugin-feed)
  - [评论组件](https://github.com/halo-sigs/plugin-comment-widget)

### 使用的哪种方式运行？

Docker

### 发生了什么？

博客首页404
后台显示502 bad gateways
文章栏目显示No static resource api/v1alpha1/annotationsettings.
求助

**Comment by JohnNiang** [comment]
建议提供发生错误时**完整**的错误日志文件（不要只提供部分日志）。

/triage needs-information

**Comment by YoungLee-coder** [comment]
- 外部访问地址: https://younglee.cn
- 启动时间: 2024-02-04 16:12
- 版本: 2.12.0
- 构建时间: 2024-02-01 10:29
- Git Commit: e85a55e
- Java: IBM Semeru Runtime Open Edition / 17.0.9+9
- 数据库: MariaDB / 10.11.6-MariaDB-1:10.11.6+maria~ubu2204
- 操作系统: Linux / 5.15.0-84-generic
- 已激活主题: [Walker](https://halo.run/store/apps/app-GHgAR)
- 已启动插件:
  - [文章导入导出](https://jhacker.cn/2023/halo-plugin-export2doc)
  - [Markdown / HTML 内容块](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [OAuth2 认证](https://github.com/halo-sigs/plugin-oauth2)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [lightgallery.js 灯箱](https://github.com/halo-sigs/plugin-lightgallery)
  - [StackEdit](https://github.com/halo-sigs/plugin-stackedit)
  - [站点推送插件](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [追番插件](https://github.com/Roozenlz/plugin-bilibili-bangumi)
  - [KaTeX](https://github.com/halo-sigs/plugin-katex)
  - [图库管理](https://github.com/halo-sigs/plugin-photos)
  - [highlight.js 代码高亮](https://github.com/halo-sigs/plugin-highlightjs)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [Sitemap](https://github.com/halo-sigs/plugin-sitemap)
  - [RSS](https://github.com/halo-sigs/plugin-feed)
  - [评论组件](https://github.com/halo-sigs/plugin-comment-widget)
[halo-log-2024-02-04 16_13.log](https://github.com/halo-dev/halo/files/14156031/halo-log-2024-02-04.16_13.log)

**Comment by YoungLee-coder** [comment]
[halo-log-2024-02-04 16_13.log](https://github.com/halo-dev/halo/files/14156061/halo-log-2024-02-04.16_13.log)

**Comment by androidmumo** [comment]
遇到了同样的问题

**Comment by YoungLee-coder** [comment]
> 遇到了同样的问题

昨天调试了一下，应该是数据库的问题，把数据库换成MySQL或者等官方修复

**Comment by JohnNiang** [comment]
Hi @YoungLee-coder and @androidmumo ，即将发布 Halo 2.12.2，到时候建议尝试一下问题是否解决。

**Comment by YoungLee-coder** [comment]
@JohnNiang 好的

**Comment by Joezhong111** [comment]
遇到同样的问题了，等个解决办法，1panel 1.9.6, Halo 2.12.2

**Comment by JohnNiang** [comment]
Hi @YoungLee-coder ， @androidmumo , @Joezhong111 ，我刚刚在本地用 MariaDB 数据库（latest）启动 Halo 2.12.2，似乎没有出现以上问题。

如果有任何问题建议多提供日志文件。

**Comment by myhloli** [comment]
> 遇到同样的问题了，等个解决办法，1panel 1.9.6, Halo 2.12.2

我遇到了同样的问题，版本和你一致，在1panel中重启OpenResty，MariaDB，Halo的容器解决了该问题

**Comment by ruibaby** [comment]
可能和 https://github.com/halo-dev/halo/issues/5534 是相同的问题，临时解决方法见：https://github.com/halo-dev/halo/issues/5534#issuecomment-2011499798

/close
