### ISSUE TITLE
附件上传图片后无法预览，也没有路径

### ISSUE THREAD

**Issue by PeifengRen** [halo-dev/halo#5321]
### System information

下面是我的docker-compose.yaml
services:
  halo:
    image: halohub/halo:2.12
    container_name: halo
    restart: on-failure:3
    network_mode: "host"
    volumes:
      - ~/.halo:/root/.halo2
    ports:
      - "8090:8090"
    environment:
      - JVM_XMS=256m
      - JVM_XMX=256m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/actuator/health/readiness"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    command:
      - --spring.r2dbc.url=r2dbc:pool:mysql://localhost:3306/halo
      - --spring.r2dbc.username=halo
      # MySQL 的密码，请保证与下方 MYSQL_ROOT_PASSWORD 的变量值一致。

      - --spring.sql.init.platform=mysql
      # 初始化的超级管理员用户名

      # 初始化的超级管理员密码

### What is the project operation method?

Docker Compose

### What happened?

附件上传后图片无法加载也没有路径。不知道是不是文件路径配置的有问题。请大佬们指点迷津 谢谢
![image](https://github.com/halo-dev/halo/assets/50514566/a98a5516-23d8-4371-9411-3e356d326ea3)
![image](https://github.com/halo-dev/halo/assets/50514566/f0189c89-7f13-4d8e-a248-30b1329fcaaa)
![image](https://github.com/halo-dev/halo/assets/50514566/2cd80f39-596c-42dc-b1b4-411b076f8cfb)

### Additional information

这是文件夹的目录结构。
![image](https://github.com/halo-dev/halo/assets/50514566/2f5b97bf-a254-4391-863e-f78d5e6233d9)

**Comment by PeifengRen** [comment]
兄弟们破案了。我是傻子。 我用的root账户登录的。 文件夹没权限 图片读不出来 呜呜呜

**Comment by JohnNiang** [comment]
Hi @PeifengRen ，如果是通过附件上传后没有得到 permalink，可能是  Halo 2.12 的问题，我在我的环境也遇到了这个问题。

See https://github.com/halo-dev/halo/issues/5315#issuecomment-1925249471 for more.

**Comment by PeifengRen** [comment]
> Hi @PeifengRen ，如果是通过附件上传后没有得到 permalink，可能是 Halo 2.12 的问题，我在我的环境也遇到了这个问题。
> 
> See [#5315 (comment)](https://github.com/halo-dev/halo/issues/5315#issuecomment-1925249471) for more.

现在转成普通用户创建的。还是预览不了 每次都需要 chmod 赋权之后 重启 才能加载出来图片、

**Comment by ruibaby** [comment]
> > Hi @PeifengRen ，如果是通过附件上传后没有得到 permalink，可能是 Halo 2.12 的问题，我在我的环境也遇到了这个问题。
> > See [#5315 (comment)](https://github.com/halo-dev/halo/issues/5315#issuecomment-1925249471) for more.
> 
> 现在转成普通用户创建的。还是预览不了 每次都需要 chmod 赋权之后 重启 才能加载出来图片、

和文件权限无关，只要重启就能正常生成链接。

**Comment by PeifengRen** [comment]
> > > Hi @PeifengRen ，如果是通过附件上传后没有得到 permalink，可能是 Halo 2.12 的问题，我在我的环境也遇到了这个问题。
> > > See [#5315 (comment)](https://github.com/halo-dev/halo/issues/5315#issuecomment-1925249471) for more.
> > 
> > 
> > 现在转成普通用户创建的。还是预览不了 每次都需要 chmod 赋权之后 重启 才能加载出来图片、
> 
> 和文件权限无关，只要重启就能正常生成链接。

确实是这样的 刚才验证了一遍。每次上传之后需要重启一下容器。你们有什么解决方案吗？还是降halo版本就可以解决

**Comment by ruibaby** [comment]
@PeifengRen 先降到 2.11 吧，我们将优先解决此问题，并发布到 2.12.2

**Comment by JohnNiang** [comment]
Close in favor of <https://github.com/halo-dev/halo/issues/5315>.

/triage duplicate
/close

**Comment by PeifengRen** [comment]
> @PeifengRen 先降到 2.11 吧，我们将优先解决此问题，并发布到 2.12.2

感谢！
