### ISSUE TITLE
手机端文章打赏无法点击二维码放大

### ISSUE THREAD

**Issue by hitushen** [halo-dev/halo#5327]
### 系统信息

- 外部访问地址: http://localhost:8090/
- 启动时间: 2024-02-04 10:55
- 版本: 2.11.3
- 构建时间: 2023-12-27 12:13
- Git Commit: 8e9b07d
- Java: IBM Semeru Runtime Open Edition / 17.0.9+9
- 数据库: Source distribution / 8.0.24
- 操作系统: Linux / 5.4.0-72-generic
- 已激活主题: [Hao](https://githubfast.com/liuzhihang/halo-theme-hao)
- 已启动插件:
  - [Meilisearch](https://github.com/Rainsheep/halo-plugin-meilisearch)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [OAuth2 认证](https://github.com/halo-sigs/plugin-oauth2)
  - [lightgallery.js 灯箱](https://github.com/halo-sigs/plugin-lightgallery)
  - [highlight.js 代码高亮](https://github.com/halo-sigs/plugin-highlightjs)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [ByteMD](https://github.com/ruibaby/plugin-bytemd)
  - [Markdown / HTML 内容块](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [文章导入导出](https://jhacker.cn/2023/halo-plugin-export2doc)
  - [对象存储（Amazon S3 协议）](https://github.com/halo-dev/plugin-s3)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)

### 使用的哪种方式运行？

Docker

### 在线站点地址

https://blog.hitushen.cn/archives/1707038102209

### 发生了什么？

手机无法打开打赏二维码，一点击就自动关闭了。电脑端正常

**Comment by ruibaby** [comment]
主题的问题请向对应的主题仓库提交 issue。

/close
