### ISSUE TITLE
链接支持设定nofollow

### ISSUE THREAD

**Issue by Leezj9671** [halo-dev/halo#5328]
### 描述一下此特性

SEO中非常重要的是内部链接建设，文内增加的链接都是nofollow属性，无法自行控制

**Comment by ruibaby** [comment]
感谢提出这个问题。

/kind feature
/area editor

**Comment by Leezj9671** [comment]
当前所有链接都为dofollow，但在SEO中，一般需要使用nofollow来控制权重的传递。比如，对于一些引用了外部资料的链接，需要加上nofollow，表示不传递权重。

建议在 `LinkBubbleButton.vue` 中，增加可以勾选 nofollow 的设定。或者统一地读取当前的域名，对于非当前域名的链接自动加上nofollow。
