### ISSUE TITLE
从md文件导入的文章标题

### ISSUE THREAD

**Issue by fcwys** [halo-dev/halo#533]
从md文件导入的文章标题希望不要有.MD后缀

**Comment by padin** [comment]
希望md导入的时候可以选择分类，因为按类型导入一批文章是常用操作。
希望路径结尾最好为.html而不是md以利于SEO。
辛苦了。

**Comment by ruibaby** [comment]
1. 是可以按照分类导入的，会识别 front-matter，前提是你有写 front-matter，不过你的想法应该是导入的时候选择已有的分类，这样的话可能会和 front-matter 中定义的分类起冲突，不好做取舍。

2. 以 md 结尾也是因为你没有在 front-matter 中定义 title，所以默认取的文件名称，这个后面可以判断去掉。

3. 文章标题以 HTML 结尾不会对 SEO 造成影响，你应该说的是文章路径。这个在下个版本就支持了。

![Snipaste_2020-03-11_23-32-42](https://user-images.githubusercontent.com/21301288/76434436-a1701700-63f0-11ea-963a-e23b840aa58e.png)

**Comment by est7** [comment]
@ruibaby 尝试front-matter写入
```
---
title: 纷纷
date: 2017-10-31 20:38:17
categories:
- Diary
tags:
- PS3
- Games
---
```
只能识别title和date，请问想从hexo把文章的标签和分类都迁移过来应该怎么写
