### ISSUE TITLE
2.12.1消息页面不显示新增的评论信息

### ISSUE THREAD

**Issue by Miraclezhb** [halo-dev/halo#5336]
### 系统信息

- 外部访问地址: https://www.miraclezhb.com
- 启动时间: 2024-02-05 17:20
- 版本: 2.12.1
- 构建时间: 2024-02-02 21:39
- Git Commit: c71b2ec
- Java: IBM Semeru Runtime Open Edition / 17.0.9+9
- 数据库: MySQL Community Server - GPL / 8.0.27
- 操作系统: Linux / 5.4.119-20.0009.20
- 已激活主题: [Hao](https://githubfast.com/liuzhihang/halo-theme-hao)
- 已启动插件:
  - [Vditor编辑器](https://github.com/justice2001/veditor-plugin)
  - [文章导入导出](https://jhacker.cn/2023/halo-plugin-export2doc)
  - [KaTeX](https://github.com/halo-sigs/plugin-katex)
  - [Metrics Graph](https://github.com/guqing/plugin-metrics-graph)
  - [站点推送插件](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [追番插件](https://github.com/Roozenlz/plugin-bilibili-bangumi)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [live2d 看板娘](https://github.com/LIlGG/plugin-live2d)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)

### 使用的哪种方式运行？

Docker

### 在线站点地址

https://www.miraclezhb.com

### 发生了什么？

升级到2.12.1版本之后，文章中新增的评论无法在消息页面收到通知，配置的邮件通知机制也失效了。回退到2.11.x版本是没问题的。

**Comment by Miraclezhb** [comment]
[halo-log-2024-02-05 17 03.log](https://github.com/halo-dev/halo/files/14163139/halo-log-2024-02-05.17.03.log)
这是完整日志文件

**Comment by JohnNiang** [comment]
/ping @halo-dev/sig-halo

请看看是不是这个 PR https://github.com/halo-dev/halo/pull/5286 造成的这种现象呢？

**Comment by ruibaby** [comment]
> /ping @halo-dev/sig-halo
> 
> 请看看是不是这个 PR #5286 造成的这种现象呢？

No，和 https://github.com/halo-dev/halo/pull/5323 应该是一样的问题。

@Miraclezhb 建议升级到 [2.12.2](https://github.com/halo-dev/halo/releases/tag/v2.12.2) 试试。

**Comment by Miraclezhb** [comment]
@JohnNiang @ruibaby 升级到2.12.2之后就没问题了，感谢！
