### ISSUE TITLE
评论管理页面显示错误

### ISSUE THREAD

**Issue by TianMiao8152** [halo-dev/halo#5337]
### 系统信息

- 外部访问地址: https://www.tianmiao.fun/
- 启动时间: 2024-02-05 14:58
- 版本: 2.12.1
- 构建时间: 2024-02-02 21:39
- Git Commit: c71b2ec
- Java: IBM Semeru Runtime Open Edition / 17.0.9+9
- 数据库: MySQL Community Server - GPL / 8.2.0
- 操作系统: Linux / 6.1.0-17-amd64
- 已激活主题: [Hao](https://githubfast.com/liuzhihang/halo-theme-hao)
- 已启动插件:
  - [OAuth2 认证](https://github.com/halo-sigs/plugin-oauth2)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [Markdown / HTML 内容块](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [Meilisearch](https://github.com/Rainsheep/halo-plugin-meilisearch)
  - [图库管理](https://github.com/halo-sigs/plugin-photos)
  - [文本绘图](https://github.com/halo-sigs/plugin-text-diagram)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [Vditor编辑器](https://github.com/justice2001/veditor-plugin)
  - [站点推送插件](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [Metrics Graph](https://github.com/guqing/plugin-metrics-graph)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)

### 使用的哪种方式运行？

Docker Compose

### 在线站点地址

https://www.tianmiao.fun/

### 发生了什么？

![image](https://github.com/halo-dev/halo/assets/83683108/f6e63219-d2d7-404e-aeb5-13a893c090e9)
实际评论页面为https://www.tianmiao.fun/moments
<img width="1120" alt="d8b922a6fe15b80832d6231bf9b0e9ca" src="https://github.com/halo-dev/halo/assets/83683108/26f168fe-47d8-4b70-8fe6-22f93694ec62">

**Comment by ruibaby** [comment]
主题的问题，建议向对应的主题提交 issue。这个问题在于主题在这个页面写死了页面 `metadata.name`，但你的系统中并没有名为 moments 的页面。

相关代码：https://github.com/liuzhihang/halo-theme-hao/blob/a7587f3b2f7f118c63d7132e516ac899ad34330c/templates/moments.html#L76-L80

文档：https://docs.halo.run/developer-guide/theme/template-tag#halocomment

/triage unresolved
