### ISSUE TITLE
插件中元数据表单定义，会重复渲染表单项

### ISSUE THREAD

**Issue by liuyiwuqing** [halo-dev/halo#5342]
### 系统信息

- 外部访问地址: http://localhost:8090
- 启动时间: 2024-02-06 20:50
- 版本: 2.11.2
- 构建时间: 2023-12-07 16:29
- Git Commit: 97b5f72
- Java: IBM Semeru Runtime Open Edition / 17.0.9+9
- 数据库: H2 / 2.2.224
- 操作系统: Linux / 6.6.12-linuxkit

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

在插件中使用元数据表单定义时，首次启动变单项渲染成功，重启之后变单项会重复渲染，渲染次数随启动次数递增
参考文档：[元数据表单定义](https://docs.halo.run/developer-guide/annotations-form/)
<img width="692" alt="image" src="https://github.com/halo-dev/halo/assets/52553268/1ccef932-e833-45c4-9db2-b3dd0bf55a49">

**Comment by JohnNiang** [comment]
Hi @liuyiwuqing ，thank you for reaching out here!

实际上，文档中给出的示例有问题，不应当使用 generateName。建议你直接使用特定的 name。

/kind bug
/area docs

**Comment by ruibaby** [comment]
已经在 https://github.com/halo-dev/docs/pull/314 中修改。

/close
