### ISSUE TITLE
完善事件机制并开放给开发者

### ISSUE THREAD

**Issue by Erzbir** [halo-dev/halo#5343]
### 你当前使用的版本

2.12.2

### 描述一下此特性

有时插件需要在 文章 / 页面 发布时触发逻辑, 但目前无法做到

**Comment by JohnNiang** [comment]
Hi @Erzbir , thank you for reaching out here!

目前我们已经提供了 SharedEvent 的能力，不过暂时还没有适配系统中的事件。有兴趣的话，可以考虑给你需要的事件加上注解 `run.halo.app.plugin.SharedEvent`，并移动到 api module 中。

如何测试：

1. 发布 api module 到本地 Maven 仓库：

```bash
./gradlew publishToMavenLocal
```

2. 修改插件中的 `build.gradle`：

```gradle
repositories {
    ...
    mavenLocal()
}

dependencies {
    implementation platform('run.halo.tools.platform:plugin:2.13.0-SNAPSHOT')
    compileOnly 'run.halo.app:api'
}
```

3. 打包插件并测试

/area core
/area plugin

**Comment by Erzbir** [comment]
> 
> 目前我们已经提供了 SharedEvent 的能力，不过暂时还没有适配系统中的事件。有兴趣的话，可以考虑给你需要的事件加上注解 `run.halo.app.plugin.SharedEvent`，并移动到 api module 中。
> 

确实可以这么做, 但是目前并没有关于 SinglePage 的事件
