### ISSUE TITLE
表格前的字符无法被修改

### ISSUE THREAD

**Issue by fanganpai** [halo-dev/halo#5352]
### 系统信息

- 外部访问地址: http://localhost:8080
- 启动时间: 2024-02-07 00:33
- 版本: 2.12.2
- 构建时间: 2024-02-05 15:14
- Git Commit: 46efa87
- Java: IBM Semeru Runtime Open Edition / 17.0.9+9
- 数据库: MySQL Community Server - GPL / 8.2.0
- 操作系统: Linux / 5.15.0-86-generic
- 已激活主题: [Butterfly](https://github.com/dhjddcn/halo-theme-butterfly.git)
- 已启动插件:
  - AI 助手
  - [live2d 看板娘](https://github.com/LIlGG/plugin-live2d)
  - [文章导入导出](https://jhacker.cn/2023/halo-plugin-export2doc)
  - [Markdown / HTML 内容块](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)

### 使用的哪种方式运行？

Docker

### 在线站点地址

https://www.fang-anpai.cn/

### 发生了什么？

我正尝试在默认编辑器中插入表格，并为表格中的文本设置特殊字体：
![Uploading image.png…]()
之后，我发现只要一段文本出现在表格之前，就无法进行有效的编辑：
当我输入数字或字母，一切正常
当我使用输入法输入单个汉字，似乎也正常
当我使用输入法输入一个词组，我会进入“虚空状态”，该状态下我的任何操作都不会被记录，直到我点击保存或试图ctrl+a全选文章内容或点击任意非编辑器区域后退出。退出“虚空状态”后，输入框中只会留下输入法对应的字符（我使用自然码双拼输入法，当我试图输入“输入词组”后，最终会留下“uurucizu”），并且除了进入该状态时的那个词以外其余一切操作都会凭空消失。

### 附加信息

![image](https://github.com/halo-dev/halo/assets/51364417/6356a324-3ad4-4c3a-8576-3a0ebe52e17f)
![image](https://github.com/halo-dev/halo/assets/51364417/5b7b8679-a207-4208-a44d-21b550c378f5)

**Comment by ruibaby** [comment]
/kind bug
/area editor

cc @LIlGG
