### ISSUE TITLE
提交sitemap站点地图状态无法抓取

### ISSUE THREAD

**Issue by cc114230** [halo-dev/halo#5355]
### 系统信息

- 外部访问地址: https://c1dy.cc
- 启动时间: 2024-02-08 20:52
- 版本: 2.12.2
- 构建时间: 2024-02-05 15:14
- Git Commit: 46efa87
- Java: IBM Semeru Runtime Open Edition / 17.0.9+9
- 数据库: MySQL Community Server - GPL / 8.1.0
- 操作系统: Linux / 3.10.0-1160.105.1.el7.x86_64
- 已激活主题: [Theme Joe3](https://github.com/jiewenhuang/halo-theme-joe3.0)
- 已启动插件:
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [站点推送插件](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [对象存储（Amazon S3 协议）](https://github.com/halo-dev/plugin-s3)
  - [ByteMD](https://github.com/ruibaby/plugin-bytemd)
  - [图库管理](https://github.com/halo-sigs/plugin-photos)
  - [通知我](https://github.com/monyuan/notify-me)
  - [文章导入导出](https://jhacker.cn/2023/halo-plugin-export2doc)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)

### 使用的哪种方式运行？

Docker

### 在线站点地址

https://c1dy.cc

### 发生了什么？

浏览器可以访问到站点地图，但是谷歌一直显示无法抓取。
https://c1dy.cc/sitemap.xml

<img width="1057" alt="image" src="https://github.com/halo-dev/halo/assets/108390929/c8dfc998-616b-49d8-b9d4-2d939f3aad08">

### 附加信息

halo版本:2.12.2

**Comment by ruibaby** [comment]
你网站的 IP 在海外似乎是无法访问的，建议确认是否是这个问题导致的。

/triage duplicate

<img width="1742" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/09eed7f6-f9fa-47c1-b751-8857a7499732">

**Comment by cc114230** [comment]
看起来应该是这样，谢谢作者
