### ISSUE TITLE
几乎所有插件的静态资源都没有进入浏览器缓存

### ISSUE THREAD

**Issue by happyZYM** [halo-dev/halo#5357]
### 系统信息

- 外部访问地址: https://blog.zymsite.ink/
- 启动时间: 2024-02-17 09:23
- 版本: 2.12.2
- 构建时间: 2024-02-05 15:14
- Git Commit: 46efa87
- Java: IBM Semeru Runtime Open Edition / 17.0.9+9
- 数据库: PostgreSQL / 16.1 (Debian 16.1-1.pgdg120+1)
- 操作系统: Linux / 5.15.0-79-generic
- 已激活主题: [Hao](https://githubfast.com/liuzhihang/halo-theme-hao)
- 已启动插件:
  - [Vditor编辑器](https://github.com/justice2001/veditor-plugin)
  - [Markdown / HTML 内容块](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [文章导入导出](https://jhacker.cn/2023/halo-plugin-export2doc)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [Metrics Graph](https://github.com/guqing/plugin-metrics-graph)
  - [站点推送插件](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [KaTeX](https://github.com/halo-sigs/plugin-katex)
  - [对象存储（Amazon S3 协议）](https://github.com/halo-dev/plugin-s3)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)

### 使用的哪种方式运行？

Docker

### 在线站点地址

https://blog.zymsite.ink/

### 发生了什么？

有时网站会突然很卡，F12查看网络活动信息时发现，Katex、Viditor之类的插件携带的静态资源较多，但这些资源几乎全都没有进入浏览器缓存，响应头里也没有Cache-Control信息。

### 附加信息

![图片](https://github.com/halo-dev/halo/assets/33191271/8ced6ddd-3f7e-412e-bf0b-ba9413993d2d)
![图片](https://github.com/halo-dev/halo/assets/33191271/46ac7878-a6ac-4588-b1b7-754d677c9aaa)

**Comment by ruibaby** [comment]
确实有这样的问题。

<img width="1073" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/7500c7ac-154f-4cb9-9354-cc7fdcae397e">

/kind improvement
/area core

**Comment by happyZYM** [comment]
> 确实有这样的问题。
> <img alt="image" width="1073" src="https://private-user-images.githubusercontent.com/21301288/305598286-7500c7ac-154f-4cb9-9354-cc7fdcae397e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNTA3MjAsIm5iZiI6MTcwODE1MDQyMCwicGF0aCI6Ii8yMTMwMTI4OC8zMDU1OTgyODYtNzUwMGM3YWMtMTU0Zi00Y2I5LTkzNTQtY2M3ZmRjYWUzOTdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDA2MTM0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczYzEyODg3NWI1ODQ4MGIyOGViYTg0MmFhZTdiZTZhMjUwMDQ2ODFkNTBkYjBjNjNhZDU0NzAxOWIwYmRkZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mh7E6OCZyEuzA_sCKdPHkfax6DF0LHgIwGAxvrEg_Rw">
> 
> /kind improvement /area core

话说改进这个地方是要在内核里统一加东西还是让插件自行解决？

**Comment by ruibaby** [comment]
可能需要在注册 ReverseProxy 的地方统一修改。

cc @guqing

**Comment by li88iioo** [comment]
+1
