### ISSUE TITLE
关闭actuator端点

### ISSUE THREAD

**Issue by hitushen** [halo-dev/halo#5360]
### 你当前使用的版本

2.12.2

### 描述一下此特性

屏蔽actuator端点在生产环节，不然直接访问域名加actuator/heapdump即可下载相关内存文件，并提取敏感信息

**Comment by guqing** [comment]
actuator 只有 `globalinfo`、`health`、`health/*` 是可以匿名访问的，其他的需要为对应角色分配权限才可访问，超级管理员登陆后可访问所有，建议你使用无痕模式测试

/needs-information

**Comment by JohnNiang** [comment]
尝试使用普通用户请求 /actuator/heapdump 接口，结果如下：

```bash
http -a tester:tester http://localhost:8090/actuator/heapdump
HTTP/1.1 403 Forbidden
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Expires: 0
Pragma: no-cache
Referrer-Policy: no-referrer
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
WWW-Authenticate: Bearer
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 0
content-length: 0
set-cookie: SESSION=24aec4fc-2cf1-45f5-9b7e-09b4c5bf6aa2; Path=/; HTTPOnly; SameSite=Lax
```

目前应该只有管理员权限才能够正常访问该接口。

**Comment by hitushen** [comment]
> 尝试使用普通用户请求 /actuator/heapdump 接口，结果如下：
> 
> ```shell
> http -a tester:tester http://localhost:8090/actuator/heapdump
> HTTP/1.1 403 Forbidden
> Cache-Control: no-cache, no-store, max-age=0, must-revalidate
> Expires: 0
> Pragma: no-cache
> Referrer-Policy: no-referrer
> Vary: Origin
> Vary: Access-Control-Request-Method
> Vary: Access-Control-Request-Headers
> WWW-Authenticate: Bearer
> X-Content-Type-Options: nosniff
> X-Frame-Options: DENY
> X-XSS-Protection: 0
> content-length: 0
> set-cookie: SESSION=24aec4fc-2cf1-45f5-9b7e-09b4c5bf6aa2; Path=/; HTTPOnly; SameSite=Lax
> ```
> 
> 目前应该只有管理员权限才能够正常访问该接口。

好的，是的
