### ISSUE TITLE
建议用户中心互通

### ISSUE THREAD

**Issue by lcese** [halo-dev/halo#5367]
### 你当前使用的版本

2.12

### 描述一下此特性

已经安装了一个HALO，准备再用HALO建立几个站点，但目前用户中心都是独立的，导致站点之间的用户不能够互通，是否考虑打通用户互通这个通道。让通过HALO建立的站点用户全部进行互通，这样用户只需要注册一个站点，就能够畅通全部子站点。

**Comment by ruibaby** [comment]
这种需求似乎接入统一的用户中心会更好，比如 LDAP，应用市场也有相关的插件：https://www.halo.run/store/apps?tag=authentication
