### ISSUE TITLE
stemap插件生成的loc地址是本地地址，而不是域名地址

### ISSUE THREAD

**Issue by FunkyGod** [halo-dev/halo#5381]
### 系统信息

https://funkygod.vip/sitemap.xml

### 使用的哪种方式运行？

Docker

### 在线站点地址

https://funkygod.vip

### 发生了什么？

使用Halo自带的siteMap插件生成的sitemap文件，loc显示的是localhost
https://funkygod.vip/sitemap.xml
![image](https://github.com/halo-dev/halo/assets/39259580/48fd0e4f-1b89-4222-833b-4834c6a4e0bc)

**Comment by guqing** [comment]
<img width="942" alt="image" src="https://github.com/halo-dev/halo/assets/38999863/834fe3ba-e621-42e6-9628-788fc11be476">

上图中 1 处的 `- --halo.external-url` 配置是否有改为你自己的域名

> https://docs.halo.run/getting-started/install/docker-compose

/triage needs-information

**Comment by FunkyGod** [comment]
是的，没有修改，已解决，谢谢
