### ISSUE TITLE
在发布文章设置选项里面，当新增文章标签的时候，只要新增的标签在之前的标签里包含了，就无法新增成功。

### ISSUE THREAD

**Issue by GuGuGee** [halo-dev/halo#5385]
### 系统信息

- 外部访问地址: https://back.laoda.de
- 启动时间: 2024-02-20 15:06
- 版本: 2.12.2
- 构建时间: 2024-02-05 15:14
- Git Commit: 46efa87
- Java: IBM Semeru Runtime Open Edition / 17.0.9+9
- 数据库: MySQL Community Server - GPL / 8.1.0
- 操作系统: Linux / 6.1.0-18-amd64
- 已激活主题: [Theme Joe3](https://github.com/jiewenhuang/halo-theme-joe3.0)
- 已启动插件:
  - [朋友圈](https://github.com/chengzhongxue/plugin-friends)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [lightgallery.js 灯箱](https://github.com/halo-sigs/plugin-lightgallery)
  - [ByteMD](https://github.com/ruibaby/plugin-bytemd)
  - [通知我](https://github.com/monyuan/notify-me)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)

### 使用的哪种方式运行？

Docker

### 发生了什么？

比如我在发布文章的时候，想要给文章添加一下`Ward`的标签，但是因为我之前有添加过`Bitwarden`的标签，当我在标签栏里输入`Ward`然后敲回车键之后，默认会给我添加`Bitwarden`而不是`Ward`标签。

![2024-02-21 13-54-35.2024-02-21 13_55_43](https://img.laoda.de/i/2024/02/21/140102-1.gif)

希望可以修复一下这个BUG，非常感谢！

**Comment by ruibaby** [comment]
/triage duplicate

see https://github.com/halo-dev/halo/issues/4660

/close
