### ISSUE TITLE
发布之后的文章如果想要再次修改发布时间的BUG

### ISSUE THREAD

**Issue by GuGuGee** [halo-dev/halo#5389]
### 系统信息

- 外部访问地址: https://backup.laoda.de
- 启动时间: 2024-02-22 09:22
- 版本: 2.12.2
- 构建时间: 2024-02-05 15:14
- Git Commit: 46efa87
- Java: IBM Semeru Runtime Open Edition / 17.0.9+9
- 数据库: MySQL Community Server - GPL / 8.1.0
- 操作系统: Linux / 6.1.0-18-amd64
- 已激活主题: [Theme Joe3](https://github.com/jiewenhuang/halo-theme-joe3.0)
- 已启动插件:
  - [朋友圈](https://github.com/chengzhongxue/plugin-friends)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [lightgallery.js 灯箱](https://github.com/halo-sigs/plugin-lightgallery)
  - [ByteMD](https://github.com/ruibaby/plugin-bytemd)
  - [通知我](https://github.com/monyuan/notify-me)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)

### 使用的哪种方式运行？

Docker

### 发生了什么？

我发布了一篇markdown写的文章，发布的时候没有填发布时间，默认按照当前时间发布了，但是这篇文章其实是我在2022年写的， 现在我重新编辑，发现直接在发布时间那边打`2022`无法显示，效果如下：

![2024-02-22 10-04-54.2024-02-22 10_06_14](https://img.laoda.de/i/2024/02/22/100938-1.gif)

如果是正常编辑的时候填写发布时间，输入`2022`的话，是正常的。

![2024-02-22 10-11-15.2024-02-22 10_11_50](https://img.laoda.de/i/2024/02/22/101205-1.gif)

**Comment by ruibaby** [comment]
手动填写确实有问题，原因可见：https://github.com/halo-dev/halo/issues/5180#issuecomment-1888710986

在修复之前，建议使用选择器。

/area ui
/kind bug

**Comment by GuGuGee** [comment]
> 手动填写确实有问题，原因可见：[#5180 (comment)](https://github.com/halo-dev/halo/issues/5180#issuecomment-1888710986)
> 
> 在修复之前，建议使用选择器。
> 
> /area ui /kind bug

好的
