### ISSUE TITLE
开发模式下修改插件资源后重启 Halo 不会重新加载需重启插件

### ISSUE THREAD

**Issue by guqing** [halo-dev/halo#5394]
### Your current Halo version

2.12.2

### Describe this feature

如题所述，复现步骤：
1. 开发模式运行插件
2. 停止 Halo，然后修改插件的自定义资源如 `resources/extensions` 下的配置文件并 build 插件
3. 再次启动 Halo
此时，插件的自定义资源仍然是旧的，需要重启插件才会被重新加载，应该是与 #5148 的重构有关，开发模式下重启 Halo 我认为可以重新加载插件的自定义资源与之前保持一致，至于生产模式下则可以不必要

### Additional information

/kind bug
/area core
/milestone 2.13.x

**Comment by guqing** [comment]
Hi @JohnNiang，这块你重构过比较熟悉帮忙解决一下此问题

**Comment by JohnNiang** [comment]
我按照 Issue 描述中所提到的复现步骤测试了一下，并未复现。

建议确认一下，构建插件之后，目录 `build/resources/main/extensions/` 目录中的数据是修改之后的。

**Comment by guqing** [comment]
请看 VCR ，视频中部分片段做了加速处理

https://github.com/halo-dev/halo/assets/38999863/e5639139-da8b-406f-84d8-b0c29db41f45

**Comment by JohnNiang** [comment]
/assign

确认在更新资源的时候存在问题。之前之所以无法复现，是因为我修改的是 Settings 资源，它的更新和 extensions 目录中的资源更新步骤不同。
