### ISSUE TITLE
开启两步验证但未设置 TOTP 时，无法正常登录

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#5398]
### 系统信息

- 外部访问地址: https://ryanc.cc
- 启动时间: 2024-02-23 17:45
- 版本: 2.13.0-SNAPSHOT
- 构建时间: 2024-02-23 17:37
- Git Commit: bf6bf8c
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: PostgreSQL / 15.4 (Debian 15.4-2.pgdg120+1)
- 操作系统: Linux / 5.15.0-88-generic
- 已激活主题: [Walker](https://halo.run/store/apps/app-GHgAR)
- 已启动插件:
  - [Metrics Graph](https://github.com/guqing/plugin-metrics-graph)
  - [Markdown / HTML 内容块](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [Markdown 编辑器](https://github.com/ruibaby/plugin-markdown-editor)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [图库管理](https://github.com/halo-sigs/plugin-photos)
  - [对象存储（Amazon S3 协议）](https://github.com/halo-dev/plugin-s3)
  - [增强备份（Backup IMproved）](https://halo.run/store/apps/app-dHakX)
  - [WebP Cloud Services](https://webp.se/)
  - [highlight.js 代码高亮](https://github.com/halo-sigs/plugin-highlightjs)
  - [lightgallery.js 灯箱](https://github.com/halo-sigs/plugin-lightgallery)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [Umami](https://github.com/halo-sigs/plugin-umami)
  - [OAuth2 认证](https://github.com/halo-sigs/plugin-oauth2)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)

### 使用的哪种方式运行？

Docker Compose

### 在线站点地址

https://ryanc.cc

### 发生了什么？

为账户启用两步验证之后，且未设置 TOTP 验证方式时，登录之后也会要求输入验证码，导致无法登录。

<img width="1653" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/f2647b2a-4b62-4ff8-aed9-79cdb0ba09e9">
<img width="498" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/1d01405b-4764-46e3-b4b9-e3b0df52bd9a">

**Comment by JohnNiang** [comment]
默认情况下，如果邮箱已经验证通过了，则邮箱也可以作为二步验证渠道之一，详情请看下面的源码。

https://github.com/halo-dev/halo/blob/bf6bf8cd7c41788d4ca3919f14ed9485007202dc/application/src/main/java/run/halo/app/security/authentication/twofactor/TwoFactorAuthSettings.java#L19-L21

所以会出现仅启用”二步验证“，没有配置”TOTP“也会出现 2FA 验证步骤。

目前有两种方案可以解决：

1. 暂时禁用 Email-based 2FA
2. 在“二步验证”页面添加邮箱发送验证码的功能

**Comment by JohnNiang** [comment]
为了快速修复这个问题，我将使用第一种方案。第二种方案可以留在以后完成。

/assign
/milestone 2.13.x
