### ISSUE TITLE
Uncaught TypeError: Object.hasOwn is not a function

### ISSUE THREAD

**Issue by cheng896911036** [halo-dev/halo#5399]
### 系统信息

Uncaught TypeError: Object.hasOwn is not a function

### 使用的哪种方式运行？

Docker

### 发生了什么？

点击上传附件进行上传文件提示   Uncaught TypeError: Object.hasOwn is not a function
经查看是Uncaught TypeError: Object.hasOwn is not a function造成的异常

**Comment by cheng896911036** [comment]
该问题经过验证为低版本谷歌内核浏览器导致的，只要使用最新版本内核浏览器即可

**Comment by ruibaby** [comment]
/triage duplicate

see https://github.com/halo-dev/halo/issues/4886

/close
