### ISSUE TITLE
注册

### ISSUE THREAD

**Issue by Newzealcoin** [halo-dev/halo#5405]
### 你当前使用的版本

halohub/halo:2.12.3

### 描述一下此特性

1/注册方式过于单调，不能使用<注册码> <邀请码><公众号获取注册码> 注册，在这两点之上可以开发一个付费购买/积分兑换注册码的选项（并集成在主题里）
2/图片水印功能暂无
3/后台文章采集功能（营销号用的）

轻量使用还可以吧，稍微带点商业就举步维艰了，对支付这方面功能做的太简单了，希望后续优化，以上功能我本人愿付费使用插件。

**Comment by Newzealcoin** [comment]
补充
后台地址无法通过面板修改，这.... *-*

**Comment by ruibaby** [comment]
我将关闭此 Issue，建议重新提交。

/close
