### ISSUE TITLE
数据库自动同步的文章数据halo不展示

### ISSUE THREAD

**Issue by htc10** [halo-dev/halo#5412]
### System information

Halo 2.12.0+版本
postgres 15.4

### What is the project operation method?

Docker Compose

### What happened?

我有2个不同的节点，halo和postgres独立部署。
我在A节点添加一篇文章，由数据同步工具同步到B节点数据库，并且B数据库中数据可查最新添加的文章。
问题：
A节点文章在前后台都展示，B节点文章在前后台均不展示。
目前解决方案：
重启B节点，文章可展示
或者在B节点访问后台文章的posts/editor地址，文章可展示。
实际是我不止AB两个节点，所有节点操作一遍很麻烦，希望解决该问题。

Halo 2.12.0版本开始出现 Halo 2.11.0未出现该问题。

### Relevant log output

```shell
没有异常日志
```

**Comment by guqing** [comment]
目前 Halo 并不支持多节点部署包括插件和数据同步以及登陆等都是需要考虑的点，Halo 目前只能优先考虑目前更加迫切需要的功能，多实例部署目前这不是 Halo 的重点，由于现在没有使用场景得看后续反馈，你可以说一下你多实例部署的原因吗，是遇到了什么瓶颈或者出于什么考虑以给我们提供参考

/triage needs-information
/priority awaiting-more-evidence

**Comment by htc10** [comment]
> 目前 Halo 并不支持多节点部署包括插件和数据同步以及登陆等都是需要考虑的点，Halo 目前只能优先考虑目前更加迫切需要的功能，多实例部署目前这不是 Halo 的重点，由于现在没有使用场景得看后续反馈，你可以说一下你多实例部署的原因吗，是遇到了什么瓶颈或者出于什么考虑以给我们提供参考
> 
> /triage needs-information /priority awaiting-more-evidence

我的多实例部署的应用场景是全球任何地方都能快速访问到我的博客。
我认为这是BUG，因为2.11版本数据完成同步后可正常展示文章，2.12版本开始就不展示了。

**Comment by ruibaby** [comment]
这个问题的具体原因是 2.12 在 https://github.com/halo-dev/halo/pull/5121 中实现的索引机制，由于目前索引是存在内存的，所以没有办法在两台机器上共享。

我不认为这是一个问题，如 https://github.com/halo-dev/halo/issues/5412#issuecomment-1966114076 中所说，不仅索引会有问题，其他地方也可能出现问题，从 Halo 2 最开始到现在都还没有考虑过多实例的场景。

**Comment by ruibaby** [comment]
@htc10 这虽然不是我们目前的重点，但后续是有计划针对内存缓存和索引做优化的，比如可配置 Redis 或者文件存储的方式。

**Comment by ruibaby** [comment]
> 我的多实例部署的应用场景是全球任何地方都能快速访问到我的博客。

如果仅仅是为了这个需求，我个人建议用全球可访问的 CDN 服务，使用 Halo 单实例。

**Comment by htc10** [comment]
> > 我的多实例部署的应用场景是全球任何地方都能快速访问到我的博客。
> 
> 如果仅仅是为了这个需求，我个人建议用全球可访问的 CDN 服务，使用 Halo 单实例。

感谢您的建议，我大部分节点已完成纯静态化的改造，但是由于地理位置的问题，不得不需要有就近halo服务提供后端接口，比如搜索、评论的功能。

**Comment by ruibaby** [comment]
@htc10 如果当前没有办法处理的话，你可以暂时先使用 2.11 版本。

> 但是从架构上来说往有状态服务越做越深，不利于未来无状态服务的改造。
> 感谢您的建议，我大部分节点已完成纯静态化的改造

当前你多台机器部署是如何处理的呢？比如插件、主题、附件等。可以给我们参考下。

**Comment by htc10** [comment]
> @htc10 如果当前没有办法处理的话，你可以暂时先使用 2.11 版本。
> 
> > 但是从架构上来说往有状态服务越做越深，不利于未来无状态服务的改造。
> > 感谢您的建议，我大部分节点已完成纯静态化的改造
> 
> 当前你多台机器部署是如何处理的呢？比如插件、主题、附件等。可以给我们参考下。

我的处理方法未实现自动化：
插件和主题都是手搓，即一个节点通过后台安装或更新完毕后，将插件、主题目录同步到其他节点，重启halo。这个问题我觉得可以参考下jenkins的架构，他也是插件热部署，但是他支持集群模式。
附件存储是自建的minio，多节点部署，一个附件上传，所有节点自动同步，这个并不困难。

**Comment by guqing** [comment]
> @ruibaby halo这个项目毋容置疑非常的棒，但是从架构上来说往有状态服务越做越深，不利于未来无状态服务的改造。

我们得先确保基础功能完善的前提下才能去做这方面的改造 还没到那个体量就过度超前设计现有的精力达不到

**Comment by aeuicey** [comment]
这个多实例同步的想法很好，不过可以逐步功能的实现，例如播客文章同步到能够支持官方插件的一些数据同步。不仅仅是高可用部署，还有类似于实验环境到生产环境的部署需要用到这个功能。并不要求一定要做到呈现形式一模一样，这个功能可以做到到有限实现。
