### ISSUE TITLE
在文章编辑器上方显示文章标题

### ISSUE THREAD

**Issue by V-Official-233** [halo-dev/halo#5427]
### 你当前使用的版本

2.13.0

### 描述一下此特性

建议在写作时在文章上方显示标题（毕竟之前想要查看标题还要查看这篇文章的设置 :p ）

**Comment by ruibaby** [comment]
从正常的流程来讲，标题确实需要放置在编辑页面。但目前主要问题可能在于样式，因为目前支持多编辑器，如何让标题输入框和其他编辑器看起来协调是个问题。

感谢反馈。

/area ui
/kind feature
/milestone 2.14.x

**Comment by ruibaby** [comment]
尝试了一下，如果统一在编辑页面添加标题输入框的话，将很难适配其他编辑器插件，会导致页面严重不协调。所以我建议为编辑器扩展点的组件添加 title 字段，让每个编辑器自行实现，如果不实现则按照以前的逻辑。默认编辑器针对的标题输入框将默认提供。

扩展点文档：https://docs.halo.run/developer-guide/plugin/api-reference/ui/extension-points/editor-create#:~:text=%E4%BB%A5%E4%B8%8B%E5%AE%9E%E7%8E%B0%E8%A6%81%E6%B1%82%EF%BC%9A-,%E7%BB%84%E4%BB%B6%E5%BF%85%E9%A1%BB%E5%8C%85%E5%90%AB%E4%BB%A5%E4%B8%8B%20props%EF%BC%9A,-raw%3Astring%EF%BC%9A%E7%94%A8%E4%BA%8E
