### ISSUE TITLE
希望附件分组可以按照创建时间排序

### ISSUE THREAD

**Issue by admin10101010** [halo-dev/halo#5429]
### Your current Halo version

2.13.0

### Describe this feature

更新到最新的2.13.0版本后
附件选项中的附件库从原本的按照新建附件库的顺序排列变成了随机排列，在把上传的附件归类起来的时候还需要找半天，希望可以恢复为按照新建附件库的顺序进行排列。
或者将附件的排列功能一并添加到附件库（文件夹），便于对上传的附件进行归类整理。

**Comment by JohnNiang** [comment]
Hi @admin10101010 , thank you for reaching out here!

目前，我这边无法复现这个问题。请看下面的截图：
<img width="1108" alt="image" src="https://github.com/halo-dev/halo/assets/16865714/9d969aad-b72f-479e-a631-175586d6d58c">

默认的排序方式：附件创建时间降序排列。

/triage needs-information

**Comment by guqing** [comment]
你说的”按照新建附件库的顺序“ 是说的目前**附件分组**的顺序不固定吗还是什么，很难理解你说的这段话，附件管理中有三个部分组成，附件存储策略（比如存储在本地或者OSS的这个）、附件分组（通过分组归类图片）和附件（文件）组成，希望可以明确一下你说的是哪个部分顺序有问题

**Comment by admin10101010** [comment]
请看此截图，意思就是存储附件的文件夹不能进行排序，新建一个文件夹后需要从众多的文件夹中翻到新建的文件夹，才能把对应文章的附件移动到新建的文件夹内，这极度不方便。
在更新之前默认是新建的文件夹排列在最后/最前。
是按照创建时间进行排序的。
![image](https://github.com/halo-dev/halo/assets/121286783/056fb854-5867-4f8d-a16b-7776ce1c0c63)

**Comment by guqing** [comment]
我测试了 2.11 版本，附件分组的排序也是不固定的与 2.13.0 版本无关,之前是想着分组不会太多不关心顺序，可以将附件分组按照创建时间排序

/kind improvement
/retitle 希望附件分组可以按照创建时间排序

**Comment by admin10101010** [comment]
我是跨版本更新的，单篇文章的附件，例如截图之类的很多，会按照文章名进行分类，或许很快就会超过数百篇及更多。
希望在下个版本可以恢复排序。
如果文章发布后，文章内的图片有自动添加水印的功能更好，感谢回复。

**Comment by guqing** [comment]
> 如果文章发布后，文章内的图片有自动添加水印的功能更好

不错的想法 👍，你可以单独提一个 issue 讨论一下

**Comment by guqing** [comment]
/remove-assign @guqing 
/assign @ruibaby 

附件分组是单独的 API 已经支持按照创建时间排序不需要后端修改,只需要在前端调用时增加排序参数即可
