### ISSUE TITLE
添加备份选项

### ISSUE THREAD

**Issue by JohnNiang** [halo-dev/halo#543]
建议可选备份内容。

- [x] 数据库
- [x] 附件
- [ ] 主题

像主题这种，很多人十几个主题，备份的话完全没必要，导致包太大，logs 文件夹也没必要。

_Originally posted by @ruibaby in https://github.com/halo-dev/halo/issues/542#issuecomment-581258804_

**Comment by cjzzy** [comment]
你好，我可以尝试去解决这个问题吗？

**Comment by ruibaby** [comment]
> 你好，我可以尝试去解决这个问题吗？

可以。
