### ISSUE TITLE
关于邮件通知的配置信息填入,建议提供相关文档进行引导填入

### ISSUE THREAD

**Issue by stars-one** [halo-dev/halo#5431]
### 你当前使用的版本

2.12.3

### 描述一下此特性

关于邮件通知里的冒出的表单一时之间不知道该填什么提供下下面几点建议

建议:

1.官方文档增加邮件通知的配置的文档说明或邮件通知表单对每个选项进行说明

2.协议,端口和加密方式几个好像是有关联关系,同样的协议,如果加密方式不一样,端口号也是不一样,建议也提供下表格说明(我还是在[issue](https://github.com/halo-dev/halo/issues/5100)里找到的解决答案)

3.邮件通知页面可以提供一个测试邮件配置的按钮 点击按钮,可以使用当前配置信息给自己邮箱发送一封邮件(目前还得去到个人信息那边页面,进行邮箱验证,有些繁琐)

比如说邮件通知配置的是xx@xx.com,可以给xx@xx.com发送一个测试的邮件,验证配置是否成功

**Comment by guqing** [comment]
1. 关于如何配置的问题参考用户 [使用文档-邮件通知](https://docs.halo.run/user-guide/settings#%E9%82%AE%E4%BB%B6%E9%80%9A%E7%9F%A5)
2. 关于“如果加密方式不一样,端口号也是不一样”的问题，给出的文档里也提供了常见的邮箱服务商的文档的配置地址，这些配置地址都有相应的说明，如 QQ 的文档：
> 使用SSL的通用配置如下：
> 接收邮件服务器：pop.qq.com，使用SSL，端口号995
> 发送邮件服务器：smtp.qq.com，使用SSL，端口号465或587
> 账户名：您的QQ邮箱账户名（如果您是VIP账号或Foxmail账号，账户名需要填写完整的邮件地址）
> 密码：您的QQ邮箱密码
> 电子邮件地址：您的QQ邮箱的完整邮件地址
3. 关于增加测试按钮与 issue #4714 重复
4. 如果有其他用户使用文档不容易理解的地方可以到 https://github.com/halo-dev/docs 文档仓库提 issue

/kind support
/triage duplicate
