### ISSUE TITLE
不填写分类目录的话，访问归档页（archives）会报错500

### ISSUE THREAD

**Issue by hurriedlu** [halo-dev/halo#5432]
### 系统信息

- 外部访问地址: http://localhost:8090
- 启动时间: 2024-03-03 13:58
- 版本: 2.12.4
- 构建时间: 2024-02-25 21:48
- Git Commit: 5200d86
- Java: IBM Semeru Runtime Open Edition / 17.0.10+7
- 数据库: MySQL Community Server - GPL / 8.2.0
- 操作系统: Linux / 5.15.0-94-generic
- 已激活主题: [Ocean](https://github.com/f2ccloud/theme-ocean.git)
- 已启动插件:
  - [文本绘图](https://github.com/halo-sigs/plugin-text-diagram)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [Docsme](https://github.com/f2ccloud/plugin-docsme)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)

### 使用的哪种方式运行？

Docker

### 发生了什么？

如果不填写分类目录的话，访问归档页（/archives）会报错500。希望如果没填写分类目录的话，使用默认的一个值
![image](https://github.com/halo-dev/halo/assets/84308195/fc926f08-df69-4c6a-a3a2-a5a63325413d)
![image](https://github.com/halo-dev/halo/assets/84308195/c9315f94-489d-40d5-952a-80a43e4d3081)

下面是容器的报错日志
[log.log](https://github.com/halo-dev/halo/files/14472084/log.log)

**Comment by ruibaby** [comment]
```
org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating SpringEL expression: "post.categories[0].status.permalink" (template: "modules/post-card" - line 33, col 9)
	at org.thymeleaf.spring6.expression.SPELVariableExpressionEvaluator.evaluate(SPELVariableExpressionEvaluator.java:292) ~[thymeleaf-spring6-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ Handler run.halo.app.theme.router.factories.ArchiveRouteFactory$$Lambda$2843/0x00000000e332c868@d3279700 [DispatcherHandler]
	*__checkpoint ⇢ run.halo.app.security.InitializeRedirectionWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ run.halo.app.security.authentication.login.UsernamePasswordAuthenticator [DefaultWebFilterChain]
	*__checkpoint ⇢ AuthorizationWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ ExceptionTranslationWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ LogoutWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ ServerRequestCacheWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ HaloAnonymousAuthenticationWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ ReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ CsrfWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ HttpHeaderWriterWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
	*__checkpoint ⇢ HTTP GET "/archives" [ExceptionHandlingWebHandler]
Original Stack Trace:
```

应该是主题在获取 post.categories 第一个的时候没有判断 categories 是否有数据，直接取第一个导致异常，这个问题建议向主题反馈。

https://github.com/f2ccloud/theme-ocean

/kind support

**Comment by hurriedlu** [comment]
> ```
> org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating SpringEL expression: "post.categories[0].status.permalink" (template: "modules/post-card" - line 33, col 9)
> 	at org.thymeleaf.spring6.expression.SPELVariableExpressionEvaluator.evaluate(SPELVariableExpressionEvaluator.java:292) ~[thymeleaf-spring6-3.1.2.RELEASE.jar:3.1.2.RELEASE]
> 	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
> Error has been observed at the following site(s):
> 	*__checkpoint ⇢ Handler run.halo.app.theme.router.factories.ArchiveRouteFactory$$Lambda$2843/0x00000000e332c868@d3279700 [DispatcherHandler]
> 	*__checkpoint ⇢ run.halo.app.security.InitializeRedirectionWebFilter [DefaultWebFilterChain]
> 	*__checkpoint ⇢ run.halo.app.security.authentication.login.UsernamePasswordAuthenticator [DefaultWebFilterChain]
> 	*__checkpoint ⇢ AuthorizationWebFilter [DefaultWebFilterChain]
> 	*__checkpoint ⇢ ExceptionTranslationWebFilter [DefaultWebFilterChain]
> 	*__checkpoint ⇢ LogoutWebFilter [DefaultWebFilterChain]
> 	*__checkpoint ⇢ ServerRequestCacheWebFilter [DefaultWebFilterChain]
> 	*__checkpoint ⇢ SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
> 	*__checkpoint ⇢ HaloAnonymousAuthenticationWebFilter [DefaultWebFilterChain]
> 	*__checkpoint ⇢ ReactorContextWebFilter [DefaultWebFilterChain]
> 	*__checkpoint ⇢ CsrfWebFilter [DefaultWebFilterChain]
> 	*__checkpoint ⇢ HttpHeaderWriterWebFilter [DefaultWebFilterChain]
> 	*__checkpoint ⇢ ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
> 	*__checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
> 	*__checkpoint ⇢ HTTP GET "/archives" [ExceptionHandlingWebHandler]
> Original Stack Trace:
> ```
> 
> 应该是主题在获取 post.categories 第一个的时候没有判断 categories 是否有数据，直接取第一个导致异常，这个问题建议向主题反馈。
> 
> https://github.com/f2ccloud/theme-ocean
> 
>  /kind支持

好的
