### ISSUE TITLE
关于评论显示的建议

### ISSUE THREAD

**Issue by GuGuGee** [halo-dev/halo#5435]
开发者您好，这是我的系统信息：
- 外部访问地址: https://blog.laoda.de
- 启动时间: 2024-03-04 14:03
- 版本: 2.13.0
- 构建时间: 2024-03-01 10:35
- Git Commit: 6ea7abe
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: MySQL Community Server - GPL / 8.1.0
- 操作系统: Linux / 6.1.0-18-amd64
- 已激活主题: [Theme Joe3](https://github.com/jiewenhuang/halo-theme-joe3.0)
- 已启动插件:
  - [图库管理](https://github.com/halo-sigs/plugin-photos)
  - [朋友圈](https://github.com/chengzhongxue/plugin-friends)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [lightgallery.js 灯箱](https://github.com/halo-sigs/plugin-lightgallery)
  - [ByteMD](https://github.com/ruibaby/plugin-bytemd)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)

对于评论插件，目前在后台，我发现我自己给用户的回复，也会显示一个跳动绿色的小点（个人感觉会误以为是用户发的评论，我还没点击查看）显得有点奇怪。
![image-20240304141740502](https://img.laoda.de/i/2024/03/04/141743-1.webp)

另外，在文章页面，评论区，作者对用户的评论回复默认是折叠的状态：

![image-20240304141800295](https://img.laoda.de/i/2024/03/04/141803-1.webp)

需要点击一下`"`号才能显示回复改条评论的内容：

![image-20240304141808743](https://img.laoda.de/i/2024/03/04/141811-1.webp)

猜测可能是为了让评论区看起来简洁一下，所以这样设计。

不知道开发者是否可以考虑在博客后台加一个开关，让博客搭建者选择是否折叠评论区（个人觉得展开评论区会更好一些，因为文章中有些讨论，可能对其他的读者也有帮助，默认打开会方便其他用户浏览）

感谢！

**Comment by guqing** [comment]
> 感谢反馈问题，但这些问题似乎以 Halo 的改动为主，和此插件可能关系不大，我将转移到 halo-dev/halo。
> 
> > 猜测可能是为了让评论区看起来简洁一下，所以这样设计。
> 
> 其实主流媒体的评论区也有不少是这样设计的，当时这样设计可能还考虑到查询性能问题，但目前应该可以优化。
> 
> cc @guqing 是否可以在评论设置中添加一个 **展开评论回复** 的选项？然后在接口的每一项评论中添加 replies。

当时这么做是出于性能考虑而作出的取舍，目前已经实现了索引机制可以在查询评论时默认附上一页（10条或5条）回复数据，当读者对某条评论下的回复感兴趣时可以点击加载更多来获取更多条

**Comment by ruibaby** [comment]
> 目前已经实现了索引机制可以在查询评论时默认附上一页（10条或5条）回复数据，当读者对某条评论下的回复感兴趣时可以点击加载更多来获取更多条

这里的排序规则我建议按照 点赞量+创建时间 联合起来排序。
