### ISSUE TITLE
相比过重的spring.thymeleaf.cache: false开关，能否在主题管理增加一个重载主题缓存功能，实现缓存的更新

### ISSUE THREAD

**Issue by guicaiyue** [halo-dev/halo#5440]
### 你当前使用的版本

2.12

### 描述一下此特性

[主题修改后，要将 halo 服务重启主题才能更新，为什么会这样？](https://bbs.halo.run/d/5123-%E4%B8%BB%E9%A2%98%E4%BF%AE%E6%94%B9%E5%90%8E%E8%A6%81%E5%B0%86-halo-%E6%9C%8D%E5%8A%A1%E9%87%8D%E5%90%AF%E4%B8%BB%E9%A2%98%E6%89%8D%E8%83%BD%E6%9B%B4%E6%96%B0%E4%B8%BA%E4%BB%80%E4%B9%88%E4%BC%9A%E8%BF%99%E6%A0%B7)

因为目前主题仅考虑自建自用
所有我上线的方式比较直接，通过 git pull 更新源代码，加构建命令生成主题文件，相比打包升级更简单。
可以麻烦加在主题管理的重载主题配置下嘛，加一个重载主题缓存选项，谢谢

**Comment by JohnNiang** [comment]
Hi @guicaiyue , thank you for reaching out here!

/kind feature
/area core
/area console
/area theme
