### ISSUE TITLE
使用1panel更新halo，有问题

### ISSUE THREAD

**Issue by dlrb666** [halo-dev/halo#5441]
### 系统信息

发行版本 centos-7.9.2009
内核版本 3.10.0-1160.102.1.el7.x86_64
系统类型 x86_64

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

更新后报错内容：No static resource apis/content.halo.run/v1alpha1/categories.

**Comment by ruibaby** [comment]
请补充完整的日志。

/triage needs-information

**Comment by dlrb666** [comment]
> 请补充完整的日志。
> 
> /triage needs-information

2024-03-05T01:22:37.920955300Z 
2024-03-05T01:22:37.921396047Z 2024-03-05T09:22:37.919+08:00 ERROR 7 --- [tor-tcp-epoll-1] i.a.r.mysql.client.ReactorNettyClient    : Error: java.lang.OutOfMemoryError: Java heap space
2024-03-05T01:22:37.921420066Z 
2024-03-05T01:22:37.921423652Z reactor.netty.ReactorNetty$InternalNettyException: java.lang.OutOfMemoryError: Java heap space
2024-03-05T01:22:37.921425995Z Caused by: java.lang.OutOfMemoryError: Java heap space
2024-03-05T01:22:37.921428152Z 	at java.base/java.util.Arrays.copyOfRange(Unknown Source) ~[na:na]
2024-03-05T01:22:37.921430497Z 	at java.base/java.lang.StringUTF16.newString(Unknown Source) ~[na:na]
2024-03-05T01:22:37.921432620Z 	at java.base/java.lang.StringBuilder.toString(Unknown Source) ~[na:na]

**Comment by ruibaby** [comment]
@dlrb666 建议直接上传日志文件，在工作目录的 logs 下，从当前的日志来看是因为内存不足，但不知道具体是在哪个操作之后导致的这个问题。

**Comment by dlrb666** [comment]
> @dlrb666 建议直接上传日志文件，在工作目录的 logs 下，从当前的日志来看是因为内存不足，但不知道具体是在哪个操作之后导致的这个问题。

[
[Uploading halo.log…]()
](url)

**Comment by dlrb666** [comment]
> @dlrb666 建议直接上传日志文件，在工作目录的 logs 下，从当前的日志来看是因为内存不足，但不知道具体是在哪个操作之后导致的这个问题。

请问这个文件你可以看到吗
[halo.log](https://github.com/halo-dev/halo/files/14493183/halo.log)

**Comment by ruibaby** [comment]
> > @dlrb666 建议直接上传日志文件，在工作目录的 logs 下，从当前的日志来看是因为内存不足，但不知道具体是在哪个操作之后导致的这个问题。
> 
> 请问这个文件你可以看到吗 [halo.log](https://github.com/halo-dev/halo/files/14493183/halo.log)

这个日志没有体现上面说提到的问题，只有一个明显的异常：

```
2024-03-05T16:54:40.465+08:00  WARN 7 --- [reactor-tcp-epoll-2] r.h.h.HighlightJSHeadProcessor           : Parse route pattern [/app/{admin,user}/**] failed

org.springframework.web.util.pattern.PatternParseException: Char ',' is not allowed in a captured variable name
```

这个异常是因为你的 highlight.js 插件的路由配置有问题，不支持 `/app/{admin,user}/**` 这种形式。目前网站的具体表现是？ Console 能够访问到吗？

**Comment by dlrb666** [comment]
> > > @dlrb666 建议直接上传日志文件，在工作目录的 logs 下，从当前的日志来看是因为内存不足，但不知道具体是在哪个操作之后导致的这个问题。
> > 
> > 
> > 请问这个文件你可以看到吗 [halo.log](https://github.com/halo-dev/halo/files/14493183/halo.log)
> 
> 这个日志没有体现上面说提到的问题，只有一个明显的异常：
> 
> ```
> 2024-03-05T16:54:40.465+08:00  WARN 7 --- [reactor-tcp-epoll-2] r.h.h.HighlightJSHeadProcessor           : Parse route pattern [/app/{admin,user}/**] failed
> 
> org.springframework.web.util.pattern.PatternParseException: Char ',' is not allowed in a captured variable name
> ```
> 
> 这个异常是因为你的 highlight.js 插件的路由配置有问题，不支持 `/app/{admin,user}/**` 这种形式。目前网站的具体表现是？ Console 能够访问到吗？

升级后看了容器的状态是unhealth

**Comment by ruibaby** [comment]
> 升级后看了容器的状态是unhealth

需要升级后的日志，目前给的升级前的日志无法查看到你升级后的问题。

**Comment by dlrb666** [comment]
> > 升级后看了容器的状态是unhealth
> 
> 需要升级后的日志，目前给的升级前的日志无法查看到你升级后的问题。
[1Panel-halo-8QY5-20240311094629.log](https://github.com/halo-dev/halo/files/14552646/1Panel-halo-8QY5-20240311094629.log)
你好 这是我升级后halo容器的日志

**Comment by dlrb666** [comment]
[halo (1).log](https://github.com/halo-dev/halo/files/14552719/halo.1.log)
这是安装目录中的日志

**Comment by guqing** [comment]
看起来是分配给 jvm 的内存不足导致的

**Comment by dlrb666** [comment]
> 看起来是分配给 jvm 的内存不足导致的

那这个有办法解决吗

**Comment by guqing** [comment]
你在 1panel 中部署 halo 时这里填写的是多少呢
<img width="451" alt="image" src="https://github.com/halo-dev/halo/assets/38999863/485b897b-d007-4fba-976b-23823c721a89">

**Comment by dlrb666** [comment]
> 你在 1panel 中部署 halo 时这里填写的是多少呢 <img alt="image" width="451" src="https://private-user-images.githubusercontent.com/38999863/311573069-485b897b-d007-4fba-976b-23823c721a89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxMjgzNzgsIm5iZiI6MTcxMDEyODA3OCwicGF0aCI6Ii8zODk5OTg2My8zMTE1NzMwNjktNDg1Yjg5N2ItZDAwNy00ZmJhLTk3NmItMjM4MjNjNzIxYTg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDAzMzQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwNjkxOWUzNDlmNWI5NzhmYjQ4YmU4ZTJiMzkwOTZmNjY5NTE4YjRmYmEyNjkwZWVkNWMxNjkwNTQ3ZDFkZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IZLm7hhWtVWEQwepI5GtB8_7WdIBSJNzEEtRL6sb2xo">

这里我没有开限制

**Comment by guqing** [comment]
> > 你在 1panel 中部署 halo 时这里填写的是多少呢 <img alt="image" width="451" src="https://private-user-images.githubusercontent.com/38999863/311573069-485b897b-d007-4fba-976b-23823c721a89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxMjgzNzgsIm5iZiI6MTcxMDEyODA3OCwicGF0aCI6Ii8zODk5OTg2My8zMTE1NzMwNjktNDg1Yjg5N2ItZDAwNy00ZmJhLTk3NmItMjM4MjNjNzIxYTg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDAzMzQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwNjkxOWUzNDlmNWI5NzhmYjQ4YmU4ZTJiMzkwOTZmNjY5NTE4YjRmYmEyNjkwZWVkNWMxNjkwNTQ3ZDFkZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IZLm7hhWtVWEQwepI5GtB8_7WdIBSJNzEEtRL6sb2xo">
> 
> 这里我没有开限制

可以试试下图的方式来将 jvm 的内存调大
<img width="872" alt="image" src="https://github.com/halo-dev/halo/assets/38999863/c843ad41-fb5f-4c45-82d0-5b0d53f31d8c">
如果能成功启动 halo 后在进一步排查原因,比如使用安装 https://www.halo.run/store/apps/app-ZZvZq 插件观察 jvm 内存占用

**Comment by ruibaby** [comment]
如果没有后续动态，我将关闭此 issue。后续可随时打开或者重新提交 issue。

/close
