### ISSUE TITLE
设置用户头像：图片上传失败

### ISSUE THREAD

**Issue by HttpStatusOK** [halo-dev/halo#5444]
### 系统信息

- 啟動時間: 2024-02-28 13:45
- 版本: 2.12.4
- 構建時間: 2024-02-25 21:48
- Git Commit: 5200d86
- Java: IBM Semeru Runtime Open Edition / 17.0.10+7
- 資料庫: MySQL Community Server - GPL / 8.2.0
- 操作系統: Linux / 3.10.0-1160.105.1.el7.x86_64
- 已啟動主題: [PandaPRO](https://www.nicetheme.cn)
- 已啟動插件:
  - [对象存储（Amazon S3 协议）](https://github.com/halo-dev/plugin-s3)
  - [文章导入导出](https://jhacker.cn/2023/halo-plugin-export2doc)
  - [图库管理](https://github.com/halo-sigs/plugin-photos)
  - [ByteMD](https://github.com/ruibaby/plugin-bytemd)
  - [lightgallery.js 灯箱](https://github.com/halo-sigs/plugin-lightgallery)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)

### 使用的哪种方式运行？

Docker

### 发生了什么？

删除默认的本地存储策略后无法上传用户头像，即使重新创建本地存储策略。

<img width="379" alt="image" src="https://github.com/halo-dev/halo/assets/116876598/da525431-7415-4fb7-a4fa-420a39df2bbe">

**Comment by LIlGG** [comment]
你可以尝试修改一下用户头像的存储地址

<img width="1920" alt="image" src="https://github.com/halo-dev/halo/assets/31335418/bb78d164-15c8-4890-8209-887cffd1a743">

/kind support

**Comment by HttpStatusOK** [comment]
> 你可以尝试修改一下用户头像的存储地址
> 
> <img alt="image" width="1920" src="https://private-user-images.githubusercontent.com/31335418/309985553-bb78d164-15c8-4890-8209-887cffd1a743.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MTUzODksIm5iZiI6MTcwOTYxNTA4OSwicGF0aCI6Ii8zMTMzNTQxOC8zMDk5ODU1NTMtYmI3OGQxNjQtMTVjOC00ODkwLTgyMDktODg3Y2ZmZDFhNzQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDA1MDQ0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyYTk1YzQ1ZWNlZDZjYmQ4MTFmNDU4MzJkYWJhNDliZWFjNmE4ZmI1N2I0YjgzZTNlYTFkMDJlYTI4YTUxYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5F4j1MUCWUyWFGz4rW9EwEBD2P-3GuUCcMbbj8GMF8M">
> /kind support

感谢回答，已解决
