### ISSUE TITLE
表单定义中是否可以新增组件类型LinkGroupSelect

### ISSUE THREAD

**Issue by liuyiwuqing** [halo-dev/halo#5449]
### 你当前使用的版本

2.13

### 描述一下此特性

目前在使用halo提供的[表单定义](https://docs.halo.run/developer-guide/form-schema)
现有需求：在插件配置或者主题配置中需要选择友情链接分组，目前如果配置友链分组，需要手动去复制LinkGroup的name，有些不方便，官方是否可以在halo中新增一下LinkGroupSelect组件

**Comment by ruibaby** [comment]
感谢反馈这个问题！

在 Core 中支持一个需要插件支持的选择组件显然是有点不合理的，我们应该需要支持让插件去扩展输入类型。

/kind feature
/area plugin
/area ui

**Comment by bynowi** [comment]
请问这个特性预计会在哪个版本推出

**Comment by ruibaby** [comment]
Halo 2.19 之后，如果是使用的自定义模型生成的接口，可以使用新的 select 表单组件，支持远程获取选择项。

https://docs.halo.run/developer-guide/form-schema#select

/close
