### ISSUE TITLE
关于文章api接口的一个小小的问题

### ISSUE THREAD

**Issue by lybtt** [halo-dev/halo#545]
为什么没有像 /api/content/posts/{postId:\d+}/likes 一样开放visits 的接口呢？:flushed:
（有这个需求是因为在用Wehalo 这个微信小程序。。）

ps：非常感谢这个开源作品，用起来很方便，对本人java的学习也很有帮助。

**Comment by ruibaby** [comment]
目前 Content API 使用的并不多，所以我们也在根据反馈完善。就像反馈你一样。后面会添加这个接口。

**Comment by lybtt** [comment]
@ruibaby ok

**Comment by JohnNiang** [comment]
如果您有兴趣，可以尝试提交 PR。

**Comment by lybtt** [comment]
> 如果您有兴趣，可以尝试提交 PR。

:joy: 我看源码关于这个接口好像其实就差一哆嗦了，但是我也有看到别的issue 说关于浏览量的问题（一定时间内同个ip多次访问的计数），所以我也不太清楚你们打算怎么设计。。

**Comment by JohnNiang** [comment]
访问统计本身就是一个不小的工程量，还需要慢慢琢磨。

**Comment by ruibaby** [comment]
不对啊。/likes 应该是点赞文章。那么 visits 不需要接口啊，请求单篇文章不久自动 +1。

**Comment by lybtt** [comment]
@ruibaby :smirk: 网站访问文章是会自动+1，但是在微信小程序端通过api获取的文章内容，就没有+1了。

**Comment by ruibaby** [comment]
@lybtt 不会吧，只要查询单篇文章都会 +1.

**Comment by ruibaby** [comment]
待会儿我看看
