### ISSUE TITLE
新建文章报错

### ISSUE THREAD

**Issue by kkrrsq** [halo-dev/halo#5457]
### 系统信息

- 外部访问地址: http://127.0.0.1:8090/
- 启动时间: 2024-03-06 20:31
- 版本: 2.13.0
- 构建时间: 2024-03-01 10:35
- Git Commit: 6ea7abe
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: MySQL Community Server - GPL / 8.0.30
- 操作系统: Linux / 3.10.0-1062.9.1.el7.x86_64
- 已激活主题: [Earth](https://github.com/halo-dev/theme-earth.git)
- 已启动插件:
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

无法新建和编辑文章，点击新建、编辑后页面一直转圈，前端报错
![image](https://github.com/halo-dev/halo/assets/16069934/b07d0f74-ea60-475b-b8ab-ddc5b02949e5)

![image](https://github.com/halo-dev/halo/assets/16069934/d7bbced8-0a8d-41a7-8965-7776b540b42c)

**Comment by ruibaby** [comment]
感谢反馈此问题，这个问题和 https://github.com/halo-dev/halo/issues/5399 一致，你当前使用的浏览器版本不支持 Object.hasOwn，所以建议升级浏览器。

但我们也可以考虑尝试兼容。

/priority awaiting-more-evidence

**Comment by kkrrsq** [comment]
> 感谢反馈此问题，这个问题和 #5399 一致，你当前使用的浏览器版本不支持 Object.hasOwn，所以建议升级浏览器。
> 
> 但我们也可以考虑尝试兼容。
> 
> /priority awaiting-more-evidence

了解了，多谢
