### ISSUE TITLE
feat: 支持国际化

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#546]
## 概述

支持设置语言包。

## 动机

健壮性。

## 详细解释

主要有三个地方需要支持。

1. halo-admin
2. API
3. 主题

对于主题可能需要注意的有：

1. 动态设置语言包，就是切换主题的时候加载对应主题目录下的语言包。
2. 主题语言包位置 `i18n/zh-Hans.properties` `i18n/en.properties`等。

另外：如果能实现在线更新语言包更好。

**Comment by li-guohao** [comment]
这个功能，是不是应该给文章加个语言标识，一篇文章可以关联多种语言的同一文章，比如用户用中文写了一篇文章，然后为了方便让母语为其它语言(比如英语或者日语)的朋友看，又翻译成了对应语言的文章，但都是同一篇文章的不同语言版本。

最终期望达到的效果是，同一文章链接，中文朋友看的是中文，英文朋友看的是英文版本的，日语朋友看的是日语版本的。

**Comment by ruibaby** [comment]
> 这个功能，是不是应该给文章加个语言标识，一篇文章可以关联多种语言的同一文章，比如用户用中文写了一篇文章，然后为了方便让母语为其它语言(比如英语或者日语)的朋友看，又翻译成了对应语言的文章，但都是同一篇文章的不同语言版本。
> 
> 最终期望达到的效果是，同一文章链接，中文朋友看的是中文，英文朋友看的是英文版本的，日语朋友看的是日语版本的。

是的，欢迎到 https://github.com/halo-dev/rfcs/issues/6 交流一下想法。

**Comment by zz-ok** [comment]
> 这个功能，是不是应该给文章加个语言标识，一篇文章可以关联多种语言的同一文章，比如用户用中文写了一篇文章，然后为了方便让母语为其它语言(比如英语或者日语)的朋友看，又翻译成了对应语言的文章，但都是同一篇文章的不同语言版本。
> 
> 最终期望达到的效果是，同一文章链接，中文朋友看的是中文，英文朋友看的是英文版本的，日语朋友看的是日语版本的。

请问有没有实现了呢

**Comment by ruibaby** [comment]
/close

See https://github.com/halo-dev/rfcs/issues/6
