### ISSUE TITLE
文章上传图片无法显示

### ISSUE THREAD

**Issue by kabaka9527** [halo-dev/halo#5460]
### 系统信息

- 外部访问地址: 
- 启动时间: 2024-03-04 19:51
- 版本: 2.12.4
- 构建时间: 2024-02-25 21:48
- Git Commit: 5200d86
- Java: IBM Semeru Runtime Open Edition / 17.0.10+7
- 数据库: MySQL Community Server - GPL / 8.2.0
- 操作系统: Linux / 5.10.0-14-cloud-amd64
- 已激活主题: [Earth](https://github.com/halo-dev/theme-earth.git)
- 已启动插件:
  - [图库管理](https://github.com/halo-sigs/plugin-photos)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [Willow Markdown 编辑器](https://github.com/guqing/willow-mde)
  - [Docsme](https://github.com/f2ccloud/plugin-docsme)
  - [Vditor编辑器](https://github.com/justice2001/veditor-plugin)
  - [豆瓣](https://github.com/chengzhongxue/plugin-douban)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

![IMG_20240306_222218](https://github.com/halo-dev/halo/assets/142149737/636c582d-7629-4df3-9ae6-053da127330e)

图片链接为http://xx.x.x/archives/null/upload/1000045006.png
正常应该为http://xx.x.x/archives/upload/1000045006.png

**Comment by kabaka9527** [comment]
但是在关于页，图片上传是正常的

**Comment by ruibaby** [comment]
可以提供一个可访问的地址以供排查吗？

/triage needs-information

**Comment by kabaka9527** [comment]
怎么提供给你呢@ruibaby

**Comment by kabaka9527** [comment]
> 怎么提供给你呢@ruibaby 

blog.kabaka.xyz

**Comment by kabaka9527** [comment]
@guqing

**Comment by guqing** [comment]
> @guqing

已启动插件里面列出的已安装插件信息属实吗,你没有手动删除一些其他已安装的插件吧,我觉得你说的这种情况如果你信息属实的话应该是不可能出现的,是否安装过 [WebP Cloud](https://www.halo.run/store/apps/app-fVJSY) 插件

**Comment by kabaka9527** [comment]
安装了

**Comment by kabaka9527** [comment]
需要删除吗

**Comment by kabaka9527** [comment]
o～

**Comment by kabaka9527** [comment]
谢谢你(∗❛ั∀❛ั∗)✧*。

**Comment by guqing** [comment]
> 安装了

好小子,故意谎报信息增加排查难度是吧
![image](https://github.com/halo-dev/halo/assets/38999863/89ae0545-e2b7-401d-bdc1-132230957594)
![image](https://github.com/halo-dev/halo/assets/38999863/09a75fb0-d54c-4488-80de-612f4c5bd6f5)
