### ISSUE TITLE
平台管理界面短时间不登录，就会自动过期，能否保持长连接？

### ISSUE THREAD

**Issue by FunkyGod** [halo-dev/halo#5463]
### 你当前使用的版本

2.12.0

### 描述一下此特性

![image](https://github.com/halo-dev/halo/assets/39259580/6c1f23ed-ad5b-48bb-a99d-d0843a5ba419)
平台管理界面短时间不等了就会自动过期，能否保持长连接，期望关闭当前界面再让登录时效，避免反复登录

**Comment by FunkyGod** [comment]
附录：[博客地址](https://funkygod.vip)

**Comment by ruibaby** [comment]
目前默认过期时间为 30min，但这个可以通过追加配置来调整，你可以在运行的时候追加如 `--server.reactive.session.timeout=2d` 的配置来实现更改。（2d 代表 2 天）

我认为这个配置可以考虑放在文档的部署文档中。

/kind documentation
/kind support

**Comment by guqing** [comment]
/triage duplicate
#5463
/close
