### ISSUE TITLE
附件默认文件夹归档

### ISSUE THREAD

**Issue by wflac** [halo-dev/halo#5467]
### 你当前使用的版本

2.13

### 描述一下此特性

现在的附件上传太多照片，虽说有这个文件夹分组归档....
默认附件是否可支持更改默认分组，而不是所有，每次强制加载慢死了。。

**Comment by ruibaby** [comment]
感谢反馈此问题，这个问题是说需要记住上次所选的分组吗？

/triage needs-information

**Comment by paluo90** [comment]
@ruibaby 也可以，只要不是默认全部都可，增加可默认选择的项可以减少加载的时间，如果全部用缩略图，每次强制加载费时间

**Comment by ruibaby** [comment]
目前 Halo 已经支持生成小的缩略图，Console 的附件列表也是用的最小的缩略图，所以应该可以缓解这个问题，如果仍然慢，建议切换为列表模式。

/close
