### ISSUE TITLE
评论优化(超管的评论直接通过审核)

### ISSUE THREAD

**Issue by stars-one** [halo-dev/halo#5468]
### 你当前使用的版本

2.12.3

### 描述一下此特性

开启了新评论审核设置,如果是在文章页面登录超级管理员账号进行评论,仍然需要在后台进行审核

希望效果就是**直接能够通过审核**

### 附加信息

无

**Comment by ruibaby** [comment]
感谢反馈此问题，我认为可以考虑在窗见评论的时候判断当前用户是否有评论管理的权限，如果有，可以跳过审核。

/area comment
/area ui
/kind improvement
