### ISSUE TITLE
主题升级前能否进行主题配置数据的备份操作

### ISSUE THREAD

**Issue by stars-one** [halo-dev/halo#5469]
### 你当前使用的版本

2.12.3

### 描述一下此特性

> 我使用一款主题,然后升级到新版本后发现主页打不开了,排查发现是主题新版本读取数据导致抛出异常了

但这个时候我想解决上面的问题,只能**重置我的主题设置数据**才能解决,之后就得重新配置主题里的各个设置,很麻烦

**目前想法:**

主题升级前能否将之前的那个版本主题进行一个备份,之后升级主题出现问题,可以以此备份,重新覆盖新版本进行还原操作?

### 附加信息

无

**Comment by ruibaby** [comment]
感谢反馈，这和 https://github.com/halo-dev/halo/issues/1073 应该是一样的需求，可以考虑实现一个主题配置导入导出的功能。

/kind feature

**Comment by ruibaby** [comment]
> 哈哈 看起来鸽了好久,20年的issue了 🤣

使用场景不够有说服力，并且没有相关需求反馈。

**Comment by stars-one** [comment]
之前研究了下`.halo2`里的theme文件夹,我把那个备份了好像也不能实现我的效果,和halo1.x版本不一样了

那个主题对应的配置是不是也存数据库里头了,如果开放到指定目录固定,其实我自己备份就完事了

我主要就是担心主题升级后新版本主题出现问题,导致我自己需要重新进行主题的选项的配置工作

**Comment by ruibaby** [comment]
[2.17](https://github.com/halo-dev/halo/releases/tag/v2.17.0) 已经支持导入导出主题配置。

/close
