### ISSUE TITLE
手机端编辑文章会清除该文章已有的所有插件效果

### ISSUE THREAD

**Issue by 666ghj** [halo-dev/halo#5470]
### 系统信息

- 外部访问地址: http://localhost:8090/
- 启动时间: 2024-03-07 16:39
- 版本: 2.13.1
- 构建时间: 2024-03-06 17:40
- Git Commit: 9473261
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: Source distribution / 5.7.43-log
- 操作系统: Linux / 5.15.0-71-generic
- 已激活主题: [Hao](https://githubfast.com/liuzhihang/halo-theme-hao)
- 已启动插件:
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [文章限制阅读](https://github.com/f2ccloud/plugin-restricted-reading-pro)
  - [对象存储（Amazon S3 协议）](https://github.com/halo-dev/plugin-s3)
  - [朋友圈](https://github.com/chengzhongxue/plugin-friends)
  - [KaTeX](https://github.com/halo-sigs/plugin-katex)
  - [文章导入导出](https://jhacker.cn/2023/halo-plugin-export2doc)
  - [Vditor编辑器](https://github.com/justice2001/veditor-plugin)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [Metrics Graph](https://github.com/guqing/plugin-metrics-graph)
  - [图库管理](https://github.com/halo-sigs/plugin-photos)
  - [Markdown / HTML 内容块](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [站点推送插件](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [lightgallery.js 灯箱](https://github.com/halo-sigs/plugin-lightgallery)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)

### 使用的哪种方式运行？

Docker

### 发生了什么？

百分百触发，默认编辑器，使用了[文章限制阅读]、 [Markdown / HTML 内容块]的文章电脑上好好的，只要用手机端打开这个文章就会发现插件全不见了，保存、发布都会导致这篇文章使用的所有插件效果消失，并且还没办法恢复！

**Comment by ruibaby** [comment]
根据你的描述没有复现此问题，你使用手机访问的时候是否有异常提示？这可能是因为你用手机访问的时候没有正常加载插件资源。

/triage needs-information
