### ISSUE TITLE
个人中心文章无法自定义发布时间

### ISSUE THREAD

**Issue by LIlGG** [halo-dev/halo#5473]
### 系统信息

- 外部访问地址: http://localhost:8090
- 启动时间: 2024-03-08 11:10
- 版本: 
- 构建时间: 
- Git Commit: 
- Java: OpenJDK Runtime Environment / 17.0.7+7-LTS
- 数据库: H2 / 2.2.224
- 操作系统: Mac OS X / 13.4
- 已激活主题: [Sakura](https://github.com/LIlGG/halo-theme-sakura.git)
- 已启动插件:
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)
  - [图库管理](https://github.com/halo-sigs/plugin-photos)

### 使用的哪种方式运行？

Source Code

### 发生了什么？

在个人中心文章页面，用户无法自定义发布时间。

1. 在保存时设置发布时间，然后点击发布会将发布时间覆盖为当前时间
2. 在已经保存、发布的文章中，修改发布时间并点击保存或发布，发布时间不会被修改。

/kind bug
/area ui

**Comment by cowqer** [comment]
http://localhost:8090/这个不是本机访问端口吗？

**Comment by LIlGG** [comment]
> [http://localhost:8090](http://localhost:8090/) 这个不是本机访问端口吗？

我的运行方式是 `Source Code` ，使用源码进行本地开发，因此是 8090 端口。

**Comment by JohnNiang** [comment]
按照设计，应当是允许用户自定义发布时间的。建议移除掉。

**Comment by LIlGG** [comment]
> 按照设计，应当是允许用户自定义发布时间的。建议移除掉。

ok。了解了。
