### ISSUE TITLE
无法删除插件提供的Console页面

### ISSUE THREAD

**Issue by story-x** [halo-dev/halo#5480]
### 系统信息

- 外部访问地址: http://localhost:8090
- 启动时间: 2024-03-07 22:11
- 版本: 2.13.1
- 构建时间: 2024-03-06 17:40
- Git Commit: 9473261
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: MySQL Community Server - GPL / 8.1.0
- 操作系统: Linux / 5.15.0-76-generic
- 已激活主题: [Theme Joe3](https://github.com/jiewenhuang/halo-theme-joe3.0)
- 已启动插件:
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [图库管理](https://github.com/halo-sigs/plugin-photos)
  - [豆瓣](https://github.com/chengzhongxue/plugin-douban)
  - [Docsme](https://github.com/f2ccloud/plugin-docsme)
  - [文章导入导出](https://jhacker.cn/2023/halo-plugin-export2doc)
  - [Vditor编辑器](https://github.com/justice2001/veditor-plugin)
  - [站点推送插件](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [备份增强插件](https://github.com/jiangqiang1996/qy-backup-plugin.git)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [ToolBench](https://github.com/DioxideCN/Tool-Bench)
  - [Gitee附件插件](https://github.com/MartyAlien/plugin-giteeoss)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)
  - [OAuth2 认证](https://github.com/halo-sigs/plugin-oauth2)
  - [Github附件插件](https://github.com/halo-dev/plugin-starter)
  - [邮件通知](https://github.com/pannanxu/halo-plugin-email)
  - [Unsplash](https://github.com/halo-sigs/plugin-unsplash)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [站点迁移](https://github.com/halo-sigs/plugin-migrate)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [RSS](https://github.com/halo-sigs/plugin-feed)

### 使用的哪种方式运行？

Docker

### 发生了什么？

禁用和卸载【瞬间】和【图库】插件，侧边栏还是有他们提供的页面，点进去报错404，高版本启动也报错404，低版本可以正常进去。下载了低版本再卸载插件，卸载了侧边栏还是有这个瞬间和图库
![image](https://github.com/halo-dev/halo/assets/45375162/4406d1b9-cafd-4199-8aa6-7fd815e2a55b)
![image](https://github.com/halo-dev/halo/assets/45375162/c72bc423-06b5-45bf-9751-e8207117f7fc)
![image](https://github.com/halo-dev/halo/assets/45375162/70870c04-16d0-4087-b9a6-9ac6b6327c88)

### 相关日志输出

```shell
{
    "type": "about:blank",
    "title": "Not Found",
    "status": 404,
    "detail": "No static resource apis/api.plugin.halo.run/v1alpha1/plugins/PluginMoments/moments.",
    "instance": "/api.plugin.halo.run/v1alpha1/plugins/PluginMoments/moments?page=1&size=20&keyword=&startDate=&endDate=",
    "requestId": "4d76c967-1768",
    "timestamp": "2024-03-08T10:12:23.665916641Z"
}
```

**Comment by ruibaby** [comment]
> 外部访问地址: http://localhost:8090

本地运行还是生产环境？ 目前只要是启停插件，升级插件等操作，都会抛弃插件资源（bundle.js）的缓存，并且这个请求自动添加了版本参数用于告诉浏览器及时抛弃缓存。

所以如果你是在本地运行，几乎不能造成缓存不及时更新。生产环境的话，可能和 Nginx 或者 CDN 配置有关，没有按照程序的缓存策略抛弃缓存。

**Comment by story-x** [comment]
> > 外部访问地址：http://localhost:8090
> 
> 目前只要是启停插件，升级插件等操作，都会抛弃插件资源（bundle.js）的缓存，并且这个请求自动添加了版本参数用于告诉浏览器及时抛弃缓存。
> 
> 所以如果你在本地运行，几乎无法造成服务器不及时更新。生产环境的话，可能和Nginx或者CDN有关配置，没有按照程序的服务器策略抛弃服务器。

感谢感谢，CDN的锅，ip访问是正常的
