### ISSUE TITLE
网站后台全局设置https问题

### ISSUE THREAD

**Issue by 837609420** [halo-dev/halo#5484]
### 系统信息

- 外部访问地址: 
- 启动时间: 2024-03-09 23:19
- 版本: 2.13.1
- 构建时间: 2024-03-06 17:40
- Git Commit: 9473261
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: H2 / 2.2.224
- 操作系统: Linux / 3.10.0-1160.45.1.el7.x86_64
- 已激活主题: [Theme Joe3](https://github.com/jiewenhuang/halo-theme-joe3.0)
- 已启动插件:
  - [WebP Cloud Services](https://webp.se/)
  - [OAuth2 认证](https://github.com/halo-sigs/plugin-oauth2)
  - [通知我](https://github.com/monyuan/notify-me)
  - [Webhook](https://github.com/wxyShine/halo-plugin-webhook)
  - [Vditor编辑器](https://github.com/justice2001/veditor-plugin)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)

### 使用的哪种方式运行？

Docker

### 发生了什么？

程序不能识别网站是http站点或者https站点。
站点目前不能将https同步到SEO的HTML标签上，打开前台F12查看时还是显示http://网站地址/   不利于搜索引擎收录。
![2024-03-10_15-19-30](https://github.com/halo-dev/halo/assets/60169341/70713292-ef1a-4a25-8705-6f1f6cd812c7)

**Comment by ruibaby** [comment]
你可能需要修改 external-url。

https://docs.halo.run/getting-started/install/docker-compose#:~:text=mysql%E3%80%81h2-,halo.external%2Durl,-%E5%A4%96%E9%83%A8%E8%AE%BF%E9%97%AE%E9%93%BE

**Comment by 837609420** [comment]
谢谢，ok了
