### ISSUE TITLE
Halo 2.13无法在Windows环境下运行（openJDK 17）

### ISSUE THREAD

**Issue by commandalan** [halo-dev/halo#5485]
### 系统信息

![Screenshot_2024-03-10-17-48-54-99_2665fb67b16260a8d818298cef8dc107](https://github.com/halo-dev/halo/assets/68139516/4c3cdd3d-3012-4808-a6ee-82dcd47500be)

### 使用的哪种方式运行？

Fat Jar

### 发生了什么？

运行失败，一直想在Windows server上跑halo了，然后试了下jar运行，还是报错

**Comment by guqing** [comment]
通过日志看出,数据库连接中用到的文件路径配置不对,你可以尝试将 halo.work-dir 配置的路径中的所有`\`改为`/`
正确的示例:
```
C:/path/to/your/directory
```
错误的示例:
```
C:\path\to\your\directory
```

**Comment by commandalan** [comment]
没问题了，Windows下运行的话可以参考我的垃圾blog：https://zanjoye.top/archives/win-run-halo2

**Comment by commandalan** [comment]
没问题了，Windows下运行的话可以参考我的垃圾blog：https://zanjoye.top/archives/win-run-halo2
