### ISSUE TITLE
/avatar 或者 /logo 等接口对相对地址敏感

### ISSUE THREAD

**Issue by JohnNiang** [halo-dev/halo#549]
# 描述

如果用户的头像地址为：`//cn.gravatar.com/avatar/xxxxxxxxxxxxxxxxxxxxxxxxxs=256&d=mm`，则我们通过 /avatar 获取头像的时候会跳转到 `https://domain.com//cn.gravatar.com/avatar/xxxxxxxxxxxxxxxxxxxxxxxxxs=256&d=mm`，并不符合预期。

# 期望

希望能够提供一个单元测试，保证该功能有效。

**Comment by ruibaby** [comment]
补全链接就好了。使用 `//` 开头是因为如果限定 `https` 的话，如果用户的博客没有开启 https，则头像无法加载。
