### ISSUE TITLE
无法联网

### ISSUE THREAD

**Issue by lwh666666** [halo-dev/halo#5501]
### 系统信息

系统概览
基本信息
外部访问地址
http://localhost:8080
启动时间
2024-03-12 14:42
已激活主题
Earth
Earth
已启动插件
AI 助手
AI 助手
朋友圈
朋友圈
链接管理
链接管理
图库管理
图库管理
搜索组件
搜索组件
RSS
RSS
评论组件
评论组件
应用市场
应用市场
环境信息
版本
2.13.1
构建时间
2024-03-06 17:40
Git Commit
9473261
Java
IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
数据库
MySQL Community Server - GPL / 8.2.0
操作系统
Linux 3.10.0-1160.76.1.el7.x86_64 / amd64
系统时区
Asia/Shanghai
系统语言
en_US

### 使用的哪种方式运行？

Docker

### 发生了什么？

重新安装了几遍，我使用的是 1panel然后安装的 halo，有的时候，安装进去之后能访问网络，就比如我安装主题或者说插件model的，但是很多次基本上都无法进行联网。

### 相关日志输出

```shell
系统概览
基本信息
外部访问地址
http://localhost:8080
启动时间
2024-03-12 14:42
已激活主题
Earth
Earth
已启动插件
AI 助手
AI 助手
朋友圈
朋友圈
链接管理
链接管理
图库管理
图库管理
搜索组件
搜索组件
RSS
RSS
评论组件
评论组件
应用市场
应用市场
环境信息
版本
2.13.1
构建时间
2024-03-06 17:40
Git Commit
9473261
Java
IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
数据库
MySQL Community Server - GPL / 8.2.0
操作系统
Linux 3.10.0-1160.76.1.el7.x86_64 / amd64
系统时区
Asia/Shanghai
系统语言
en_US
```

**Comment by ruibaby** [comment]
如果没有后续动态，我将关闭此 issue。后续可随时打开或者重新提交 issue。

/close
