### ISSUE TITLE
feat: 可否加入访客地图

### ISSUE THREAD

**Issue by YuppyHub** [halo-dev/halo#551]
## 概述
在 admin 页面可以不止可以看到有多少访客，还可以看到这些访客的 ip 分布， 比如中国有多少访客， 美国有多少访客。。

## 动机
这样方便我知道我的访客大多是来源哪里，以便我更新内容有针对性。

## 详细解释
我希望我能明确的知道我的访客来自哪些地方的人数多， 以便我能针对性的更新我的博客内容 ，希望大佬加上此功能。。

**Comment by ruibaby** [comment]
@YuppyHub 是有这个计划的，但不会太快。

**Comment by BrandoQ** [comment]
你好，请问我可以试着解决一下这个问题吗 :)

**Comment by ruibaby** [comment]
@BrandoQ 不用问，做好提交pr就行了。

**Comment by lnsane** [comment]
有一个思路：
取出所有的访客记录，通过geoip2获取所有的国家存在Map中，返回给前端，然后前端显示一个list，这个list有overflow，并且有scroll可以滚动。你们看可以不?还是说要ECharts实现？
@ruibaby @JohnNiang

**Comment by ruibaby** [comment]
@lnsane 暂时不会将其列入开发重点，这功能三方统计实现的更好。

**Comment by hanhuoer** [comment]
问下，现在有这个功能了吗，希望能看到访客 IP，就类似访问记录表一样的东西，ip地址啥，啥时间访问等等。

**Comment by guqing** [comment]
> 问下，现在有这个功能了吗，希望能看到访客 IP，就类似访问记录表一样的东西，ip地址啥，啥时间访问等等。

Halo 不打算做这个功能，建议使用 Umami
