### ISSUE TITLE
是否考虑集成JIB？

### ISSUE THREAD

**Issue by isfong** [halo-dev/halo#5510]
### 你当前使用的版本

2.14.0-SNAPSHOT

### 描述一下此特性

构建镜像严重依赖于Docker进程, 是否考虑集成[https://github.com/GoogleContainerTools/jib](https://github.com/GoogleContainerTools/jib)使devops更简单

**Comment by JohnNiang** [comment]
Hi @isfong , thank you for reaching out here!

/kind improvement
/area core

近期我会试着用 JIB Gradle 插件试试，看能否做到简化构建的流程。

**Comment by JohnNiang** [comment]
Hi @isfong ，我经过一段时间的深入研究，发现 JIB 目前暂时无法满足我们当前的需求：构建 Docker 镜像的同时也能够发布 Fat Jar 至 GitHub Release Assets。对应的讨论请参考：<https://github.com/GoogleContainerTools/jib/issues/1851>。

如果你的构建环境确实没有 Docker daemon，建议参考 <https://github.com/GoogleContainerTools/jib/blob/master/jib-gradle-plugin/README.md> 适配，过程也比较简单。

/priority awaiting-more-evidence
