### ISSUE TITLE
允许放弃文章修改/新增对比文章前后修改

### ISSUE THREAD

**Issue by HowieHz** [halo-dev/halo#5512]
### 你当前使用的版本

2.13.1

### 描述一下此特性

文章点进去复制一点素材
出来发现文章列表多了绿点
1. 不知道哪里修改了
2. 无法撤销修改

不点发布，绿点一直在，非常恼人

### 附加信息

我平时使用的是vditor编辑器

**Comment by ruibaby** [comment]
我建议在提供版本对比功能前，提供一个舍弃当前未发布内容的功能，因为有些时候我们进入文章编辑页面可能只是查看文档，但由于目前的自动保存功能，也可能产生一个修改差异，导致 ** status.isProgress ** 字段更改，这在一定程度确实容器造成困扰。

/kind feature

**Comment by ruibaby** [comment]
已经在 https://github.com/halo-dev/halo/pull/5787 中支持查看版本历史，也可以删除未发布的更改，所以我将关闭此 issue。

/close
