### ISSUE TITLE
使用推送到微信公众号的官方插件，无法同步

### ISSUE THREAD

**Issue by FunkyGod** [halo-dev/halo#5519]
### System information

![image](https://github.com/halo-dev/halo/assets/39259580/52acd16e-2784-4752-aacb-71365d98fc98)
上周还是正常的，今天发现一直显示这个同步错误，公众号没有收到同步的文章

### What is the project operation method?

Docker

### What happened?

公众号没有收到同步的文章

**Comment by FunkyGod** [comment]
![image](https://github.com/halo-dev/halo/assets/39259580/b76c6a4b-014e-41dd-87e2-be304f3f2063)
![image](https://github.com/halo-dev/halo/assets/39259580/698c9947-cdeb-438e-aae6-ac1eb730ba7d)
要么同步稍后，要么直接报错，求助

**Comment by JohnNiang** [comment]
Hi @john1298308460 , please help @FunkyGod  resolve the problem.

**Comment by ruibaby** [comment]
@FunkyGod 感谢反馈此问题，但因为这个插件是应用市场的付费插件，所以我建议直接加入售后群（在官网的订单页面右上角有入口）。此仓库主要用于反馈 Halo 本身的问题，可能并不适合在这里提交 issue，也会给后来的人带来困惑。
