### ISSUE TITLE
默认编辑器里的代码块没有Dart语言高亮

### ISSUE THREAD

**Issue by Sakura-LF** [halo-dev/halo#5530]
### 你当前使用的版本

latest

**Comment by ruibaby** [comment]
感谢反馈这个问题，欢迎提交 PR 进行支持。

只需要在 https://github.com/halo-dev/halo/blob/main/ui/packages/editor/src/extensions/code-block/lowlight.ts 中导入 dart 语言并注册即可。

/good-first-issue
/kind feature
/area editor
