### ISSUE TITLE
希望可以优化评论功能

### ISSUE THREAD

**Issue by Songxinlann** [halo-dev/halo#5543]
### 你当前使用的版本

2.13.1

### 描述一下此特性

可以评论，但无法对自己的评论内容进行重新编辑；还希望可以对评论也加入收藏功能。

**Comment by ruibaby** [comment]
感谢反馈此问题，但请不要使用笼统的标题创建 issue。我将临时关闭此 issue，请补充 issue 以重新开启 Issue。

/triage unresolved
/close
