### ISSUE TITLE
用户登录账户安全性及密码更改安全性改进

### ISSUE THREAD

**Issue by wangjiajia0402** [halo-dev/halo#5544]
### 你当前使用的版本

2.13.1

### 描述一下此特性

在密码共享的情况下，其他用户可以随意更改密码，在第一所有用户不知情的情况下就无法登录，安全性大大下降。建议增加更多信息绑定，例如绑定邮箱、wechat等，或使用手机号验证码登录。可以对账户第一所有者的权限进行保护，减少其余使用者的权限，以提高用户账户安全性，确保多人工作使用共享一个账户的情况下更加安全。

**Comment by ruibaby** [comment]
感谢反馈此问题。

账户共享本身就不是一个常规的做法，正确的做法是创建不同的账户并分配相同的权限。

> 建议增加更多信息绑定，例如绑定邮箱、wechat等，或使用手机号验证码登录。

当前本身就有三方登录的相关插件：https://www.halo.run/store/apps/app-ESVDK

/triage unresolved
