### ISSUE TITLE
新增解决标签

### ISSUE THREAD

**Issue by fhhndfgrdhw** [halo-dev/halo#5545]
### 你当前使用的版本

2.13.1

### 描述一下此特性

在Issue后面增加表示问题已解决或没有解决按钮，让浏览者选择是否已经解决该问题，并统计解决与未解决数量，显示在Issue页面

**Comment by ruibaby** [comment]
这和 GitHub 平台相关，与此项目无关。此外，针对你的问题，你可以查看：https://github.com/halo-dev/halo/milestones

/triage unresolved
