### ISSUE TITLE
官网主页的登陆注册无法用试用账户登录

### ISSUE THREAD

**Issue by mangning** [halo-dev/halo#5548]
### 系统信息

- 外部访问地址: https://demo.halo.run
- 启动时间: 
- 版本: 
- 构建时间: 
- Git Commit: 
- Java: 
- 数据库: 
- 操作系统: 
- 已激活主题: Daisyblocks
- 已启动插件: 

### 使用的哪种方式运行？

Docker

### 发生了什么？

主页右上角登录附带地址，无法正常登录，试用用户demo与密码无法正常输入进入。

**Comment by ruibaby** [comment]
Duplicate of [#5563 (comment)](https://github.com/halo-dev/halo/discussions/5563?converting=1#discussioncomment-8872670)
