### ISSUE TITLE
登录慢，登录频繁卡退

### ISSUE THREAD

**Issue by xingmangmmmm** [halo-dev/halo#5549]
### 你当前使用的版本

2.13.1

### 描述一下此特性

登录慢，登录频繁卡退，登录用户多，多次刷新也刷不出来

**Comment by ruibaby** [comment]
由于没有正确选择 issue 模板或按照 issue 模板提供足够的信息，我们暂时关闭该 Issue。请补充 issue 以重新开启 Issue。

/triage unresolved
/close
