### ISSUE TITLE
halo  gcp cpu利用率100%  

### ISSUE THREAD

**Issue by riocwong** [halo-dev/halo#555]
## 我的环境 gcp  宝塔面板 最新  现在进不去系统  halo都是最新版的，
我启动或者停止了 nginx 和 mysql cpu使用率都没有大变化，只要一启动halo  cpu就100%  停止halo就好了，我也是不会了  

---

## 错误日志

an : Closing JPA EntityManagerFactory for persistence unit 'default'
2020-02-10 09:58:21.162  INFO 6847 --- [           main] com.zaxxer.hikari.HikariDataSource    
   : HikariPool-1 - Shutdown initiated...
2020-02-10 09:58:21.173  INFO 6847 --- [           main] com.zaxxer.hikari.HikariDataSource    
   : HikariPool-1 - Shutdown completed.
2020-02-10 09:58:21.178  INFO 6847 --- [           main] io.undertow                           
   : stopping server: Undertow - 2.0.27.Final---

**Comment by ruibaby** [comment]
确定启动不会有异常吗?

**Comment by riocwong** [comment]
我去 秒回啊  启动没有什么异常啊 就是我从宝塔面板看  cpu占用率 回100% ，之前都用着 好好的

**Comment by riocwong** [comment]
我实在搞不定了  刚才又升级了一下halo  wget https://github.com/halo-dev/halo/releases/download/v1.2.0/halo-1.2.0.jar -O halo-latest.jar

**Comment by ruibaby** [comment]
一般情况下，只会在启动过程中占用较大的 cpu 资源，启动完成之后会降回去，使用过程中也不会 cpu 剧增。

**Comment by riocwong** [comment]
启动之后 cpu 占用率 一直100%

**Comment by ruibaby** [comment]
页面访问能成功吗？详细日志发出来看看，在 ~/.halo/logs/spring.log。

**Comment by riocwong** [comment]
访问不了 ip+端口也不行
[spring.log](https://github.com/halo-dev/halo/files/4180205/spring.log)

**Comment by guqing** [comment]
@riocwong 防火墙开了吗  检查服务器端口放行规则

**Comment by ruibaby** [comment]
你这是启动失败了。

日志：

```
org.flywaydb.core.internal.license.FlywayEditionUpgradeRequiredException: Flyway Enterprise Edition or MySQL upgrade required: MySQL 5.6 is no longer supported by Flyway Community Edition, but still supported by Flyway Enterprise Edition.
```

提示不支持 MySQL 5.6 ，文档也有说必须要求 5.7 以上。

另外，不建议使用 MySQL，详情看：https://halo.run/archives/other-faq

**Comment by ruibaby** [comment]
![Snipaste_2020-02-10_18-19-48](https://user-images.githubusercontent.com/21301288/74141481-f2de8800-4c31-11ea-8ae7-a59019f92d72.png)

**Comment by riocwong** [comment]
好的  我之前用的 5.6的 一直没问题，我也就没在意  突然访问不了 我去换了试试

**Comment by ruibaby** [comment]
1.2.0 引入了 flyway 管理数据库版本，这是 flyway 的社区版不支持 5.6 的 MySQL。

**Comment by riocwong** [comment]
哦 好的 谢谢 作者，感谢 感谢
