### ISSUE TITLE
主页找回密码对邮箱是否正确的判断不够迅速

### ISSUE THREAD

**Issue by fight-for-all-the-beauty-in-the-world** [halo-dev/halo#5556]
### 你当前使用的版本

2.13

### 描述一下此特性

主页找回密码时要求提供用户名和邮箱，提醒是如果对上会发邮箱。可我有几个邮箱，并且有分如gmail的不能及时收到的邮箱，为什么不直接告诉我填入的邮箱是否有注册，等半天没一个收到还要重新检查用户名和邮箱

**Comment by ruibaby** [comment]
感谢反馈此问题。

如果在找回密码的时候直接告诉对方邮箱是否有注册，那么此接口就很有可能被利用，用于检查邮箱是否存在并进行定向尝试。通常在做登录相关的设计时，都不能直接告诉对方账号是否存在，只能提示当前用户名或密码不正确。
