### ISSUE TITLE
字体改进

### ISSUE THREAD

**Issue by D2451976** [halo-dev/halo#5559]
### 你当前使用的版本

2.13.1

### 描述一下此特性

字体无法选择 只有默认字体

**Comment by YANGYI441781** [comment]
主题[theme-dream](https://github.com/nineya/halo-theme-dream)有自定义字体和更改字体的功能,你可以考虑使用这个主题.
这个功能在[theme-dream](https://github.com/nineya/halo-theme-dream)主题的基础样式中设置.

**Comment by D2451976** [comment]
这是来自QQ邮箱的自动回复邮件。
 
你好，很高兴收到你的邮件。我会尽快给您回复！

**Comment by ruibaby** [comment]
请完善 issue，具体是哪里需要设置字体。

/triage awaiting-more-evidence
