### ISSUE TITLE
win10可以用halo吗？一定要买CentOS的服务器吗？

### ISSUE THREAD

**Issue by melodyjerry** [halo-dev/halo#557]

**Comment by JohnNiang** [comment]
理论上任何系统都可以使用 Halo 的，但是你总得提供给外部访问的接口，服务器是一个很好的选择。

**Comment by melodyjerry** [comment]
可以配套使用github或码云或腾讯cloudstudio等等之类的吗？ @JohnNiang

**Comment by ruibaby** [comment]
@melodyjerry 请参考文档

**Comment by JohnNiang** [comment]
目前有生成静态资源文件功能的计划，不过还需要等一段时间。
