### ISSUE TITLE
个人头像不显示

### ISSUE THREAD

**Issue by AKAOOK** [halo-dev/halo#5572]
### 系统信息

up

### 使用的哪种方式运行？

Docker

### 发生了什么？

![Uploading PixPin_2024-03-22_20-16-56.png…]()
配置了，头像但是不显示

### 相关日志输出

```shell
up
```

**Comment by AKAOOK** [comment]
![Uploading PixPin_2024-03-22_20-16-56.png…]()

**Comment by guqing** [comment]
/triage needs-information

请提供详细信息，复现步骤和日志

**Comment by jkjoy** [comment]
avatar的链接看看是不是官方的,如果是,那就是正常的,被墙了.
