### ISSUE TITLE
点击头像 ipv6 域名会转跳到ipv4的地址上

### ISSUE THREAD

**Issue by shirainbown** [halo-dev/halo#5574]
### 系统信息

- 外部访问地址：https://songshiyu.cn/
- 启动时间：2024-02-06 00:00
- 版本
- 构建时间：2023-09-22 22:51
- Git Commit：54d8393
- Java：OpenJDK Runtime Environment / 17.0.8.1+1
- 数据库：H2 / 2.1.214
- 操作系统：Linux / 4.4.302+
  

### 使用的哪种方式运行？

Docker

### 发生了什么？

songshiyu.cn 使用了反向代理，还有另一个blog.songshiyu.cn 直接解析到ipv6地址上。
直接访问blog.songshiyu.cn的时候，各个导航以及文章是可以转跳到对应blog.songshiyu.cn的地址上，但是点击左上角的头像会转跳到主页songshiyu.cn的域名上去。

### 附加信息

如果需要复现，只需访问blog.songshiyu.cn。点击首页左上角的头像，即可。

**Comment by mjsoftking** [comment]
外部访问地址：https://songshiyu.cn/
外部访问地址没设置正确

**Comment by shirainbown** [comment]
你好，感谢回复！
但是我的ipv4 地址解析的是songshiyu.cn
如果这么设置外部访问地址的话，那就会是的没有ipv6的情况下，用songshiyu.cn访问主页时，点击头像会转跳无法连接



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月24日(周日) 上午6:08
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [halo-dev/halo] 点击头像 ipv6 域名会转跳到ipv4的地址上 (Issue #5574)




 
外部访问地址：https://songshiyu.cn/
 外部访问地址没设置正确

**Comment by mjsoftking** [comment]
> 你好，感谢回复！ 但是我的ipv4 地址解析的是songshiyu.cn 如果这么设置外部访问地址的话，那就会是的没有ipv6的情况下，用songshiyu.cn访问主页时，点击头像会转跳无法连接
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年3月24日(周日) 上午6:08 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [halo-dev/halo] 点击头像 ipv6 域名会转跳到ipv4的地址上 (Issue #5574) 外部访问地址：https://songshiyu.cn/ 外部访问地址没设置正确 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

那你v4和v6解析到一个域名呗，由用户端的网络情况自动选择走v4还是v6呗

**Comment by ruibaby** [comment]
因为主题在左上角头像取的变量为 `site.url`，这个就是设置的外部访问地址。以下是可能解决的访问：

1. 确定一个主域名，另外一个域名重定向到主域名（推荐，本身多个域名解析到一个网站并且内容完全一致也不是一个好主意）。
2. 自行修改主题或者给主题提交反馈，让左上角的 Logo 链接设置为 `/`。
