### ISSUE TITLE
基于“作者”权限创建的用户编写文章上传图片时，打开附件库会报“未知错误”

### ISSUE THREAD

**Issue by LiberatorHg** [halo-dev/halo#5581]
### 系统信息

- 启动时间: 2024-03-15 16:00
- 版本: 2.13.1
- 构建时间: 2024-03-06 17:40
- Git Commit: 9473261
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: MySQL Community Server - GPL / 8.1.0
- 操作系统: Linux / 3.10.0-957.1.3.el7.x86_64
- 已激活主题: [Dream](https://github.com/nineya/halo-theme-dream2.0.git)
- 已启动插件:
  - AI 助手
  - [Markdown / HTML 内容块](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [文章导入导出](https://jhacker.cn/2023/halo-plugin-export2doc)
  - 联系表单
  - [应用市场](https://github.com/halo-dev/plugin-app-store)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [图库管理](https://github.com/halo-sigs/plugin-photos)
  - [Sitemap](https://github.com/halo-sigs/plugin-sitemap)
  - [RSS](https://github.com/halo-sigs/plugin-feed)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

基于“作者”这个角色创建用户后，该用户编写文章，添加图片，点击附件库的时候，会报“未知错误”，按道理就不应该有附件库这个按钮，报错的内容也是“未知错误”。
![image](https://github.com/halo-dev/halo/assets/52238701/59afb3a1-ca69-4a17-841f-86e9b59bddc8)
![image](https://github.com/halo-dev/halo/assets/52238701/e5d4d43d-2842-456e-9985-2be8f437acc8)
![image](https://github.com/halo-dev/halo/assets/52238701/e25508ba-9458-48c7-9831-2ae23684a948)

### 相关日志输出

```shell
halo后端无相关错误提示
```

**Comment by LIlGG** [comment]
感谢反馈，确实存在这个问题。

/area ui
/kind bug
/milestone 2.14.x
