### ISSUE TITLE
添加自动备份功能

### ISSUE THREAD

**Issue by rong6** [halo-dev/halo#5598]
### 你当前使用的版本

2.12.2

### 描述一下此特性

目前Halo没有提供相关的API，所以能否官方添加一个自动备份的功能，定时备份至服务器磁盘（插件可以备份到第三方平台）。

**Comment by ruibaby** [comment]
感谢反馈此问题，当前在应用市场已经有了官方提供的增强备份插件，已经涵盖了上述需求，所以暂时不考虑在核心中添加。

https://www.halo.run/store/apps/app-dHakX

/triage unresolved

**Comment by guqing** [comment]
在 console 点击备份按钮你应该就能在浏览器控制台网络选项看到调用的备份 api 了，你可以自己写个脚本在服务器定时调用

**Comment by rong6** [comment]
> > 目前Halo没有提供相关的API
> 
> 在 console 点击备份按钮你应该就能在浏览器控制台网络选项看到调用的备份 api 了，你可以自己写个脚本在服务器定时调用

还是希望有插件能直接调用方便一点，这个我也尝试过，后来不了了之了，也感谢提供方法。

------------
> 感谢反馈此问题，当前在应用市场已经有了官方提供的增强备份插件，已经涵盖了上述需求，所以暂时不考虑在核心中添加。
> 
> https://www.halo.run/store/apps/app-dHakX
> 
> /triage unresolved

行吧，价格着实有点贵，刚刚在GitHub搜了一下相关插件，找到了一个：https://github.com/jiangqiang1996/qy-backup-plugin ，功能没官方的多，不过勉强能用就是了。
