### ISSUE TITLE
反代二级目录的显示异常

### ISSUE THREAD

**Issue by yfdoor** [halo-dev/halo#5600]
### 描述一下此特性

我查看了之前的 issue, 有人提过，但似乎没有解决。
将网站反代到二级目录下，例如
https://xxx.com/halo 这种二级目录下时，页面由于静态资源路径的问题显示异常。只能反代二级域名，例如 https://halo.xxx.com, 但实际中为了减少dns解析设置，第一种的需求还是挺重要的，希望考虑可以支持

**Comment by guqing** [comment]
/triage duplicate

see also:
- https://github.com/halo-dev/halo/issues/5204
- https://github.com/halo-dev/halo/issues/1132
- https://github.com/halo-dev/halo/issues/3976

目前 Halo 没有计划支持 context path, 这个功能得不偿失，能用 subdomain 做的却用 context path，一方面为这个功能的付出远远超过这个功能带来的好处，几乎没有遇到使用场景或需求是 subdomain 无法满足必须要使用 context path 的，这属于是有点特立独行了，另一方面，目前这样的功能会破坏 halo 生态，为了适配这个功能必须要插件也跟着适配否则只要使用 context path 的用户就会经常出现某些插件功能不能用的问题从而带来大量与 Halo Core 不相关的 issue，如果只是 dns 解析配置麻烦这个场景很难有足够的动力去做这个功能

/needs-information
