### ISSUE TITLE
使用jar环境部署启动jar包报错

### ISSUE THREAD

**Issue by adozhao** [halo-dev/halo#5605]
### 系统信息

jdk版本"1.8.0_402"

### 使用的哪种方式运行？

Fat Jar

### 发生了什么？

按照  `使用jar环境部署`  报错，不是后端，希望得到帮助，报错内容如下：

![image](https://github.com/halo-dev/halo/assets/23180747/eb271ff1-82f2-463f-9bd2-608f28b6903e)

**Comment by adozhao** [comment]
打扰了，应该是java版本有问题~ `[Java](https://openjdk.org/) 环境，目前 Halo 最低需要 JRE 17 的环境` 我看成 1.7了，我更换个版本试试

**Comment by adozhao** [comment]
搞定了，官方文档写的不错，只是看眼剽了~

**Comment by adozhao** [comment]
貌似这只是java后端服务启动了，没提到前端怎么搞~

**Comment by guqing** [comment]
> @guqing 貌似按照文档，只是java后端服务启动了，没提到前端怎么搞~

有没有可能没写就是不需要，只要启动了 jar 就可以访问了

**Comment by adozhao** [comment]
> > @guqing 貌似按照文档，只是java后端服务启动了，没提到前端怎么搞~
> 
> 你说有没有可能没写就是不需要，只要启动了 jar 就可以访问了👨‍💻

有想过这个问题，那我现在环境还是有点儿问题，jar启动是正常的了，没报错。如果正常访问到页面的话，那我的前端项目在哪里呢？我要如何管理....  
还有 ，我发现我docker-compose部署的打不开了，哈哈~

**Comment by guqing** [comment]
1. 前端部分已经打包到 jar 里面了是一体的，启动 jar 看日志是否功能
2. docker 部署看端口映射是否和 jar 的 yaml 配置冲突
3. 如果你要手动管理前端部分那你应该是想开发环境启动 halo ，可以参考开发指南

**Comment by adozhao** [comment]
我发现文档写的有问题的地方了，后续我重新开个issue提出

**Comment by guqing** [comment]
文档问题可以到 [halo-dev/docs](https://github.com/halo-dev/docs) 仓库提 issue

**Comment by adozhao** [comment]
`如果你要手动管理前端部分那你应该是想开发环境启动 halo ，可以参考开发指南`  

比如我想替换前端文件，这个做不到？

**Comment by guqing** [comment]
不懂你的需求，建议详细描述，否则沟通成本很高
为什么要替换前端文件，你说的前端文件是只 console 和个人中心的页面,还是主题文件,一个 jar 包是成品，如果你要修改那你应该参考构建指南和开发指南，然后修改 console 或者 ui 模块之后重新自己打包为一个 jar 这是你的自由

**Comment by adozhao** [comment]
![image](https://github.com/halo-dev/halo/assets/23180747/fb0325a9-0015-496d-98ee-4cddf3043a7c)

![image](https://github.com/halo-dev/halo/assets/23180747/d8af6dd3-d015-4bfe-b8d3-5ba1536089f8)

@guqing 这里指定工作目录就可以映射到前端文件了，我以为每次修改前端文件都要重新打jar包呢

**Comment by guqing** [comment]
> ![image](https://github.com/halo-dev/halo/assets/23180747/fb0325a9-0015-496d-98ee-4cddf3043a7c)
> 
> 
> 
> ![image](https://github.com/halo-dev/halo/assets/23180747/d8af6dd3-d015-4bfe-b8d3-5ba1536089f8)
> 
> 
> 
> @guqing 这里指定工作目录就可以映射到前端文件了，我以为每次修改前端文件都要重新打jar包呢
> 
> 

你真是个小机灵鬼，让你参考开发文档来开发，你连修改 jar 里的前端文件都搞出来了 我都懵逼了

**Comment by adozhao** [comment]
直接jar包部署的OK了，我的docker-compose部署的站点打不开了，还没想到哪里问题，端口的话一个运行在8090，一个运行在9080
