### ISSUE TITLE
关于私密文章逻辑的一些讨论

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#561]
自从私密文章上线之后，很多人表示不会用，而且认为私密文章的逻辑有问题。首先不可否认的是，如果出现这种情况，那么肯定是我们功能设计有问题，或者考虑不周。所以开个 issue 讨论一下，看看是否有必要做一些修改。

### 目前的逻辑

1. 只要设置了文章密码，那么自动转为私密文章。
2. 私密文章不会在博客的任何地方列表出来。
3. 只能通过访问文章地址的方式进行访问（需先输入密码）。

### 很多人认为的

1. 需要在首页列表出来。

### 我认为的

1. 没有必要在首页列表出来，这是一个对其他访客很不友好的设计。想想在文章列表中突然出现一个以【私密文章】为标题的文章。
2. 你完全可以通过 `文章地址+密码` 的方式发给你想发的人，这才是 “私密文章” 的意义所在。

![Snipaste_2020-02-11_10-54-03](https://user-images.githubusercontent.com/21301288/74208097-14d11c80-4cbd-11ea-930e-1b3f6c3ff3c0.png)
![Snipaste_2020-02-11_10-54-16](https://user-images.githubusercontent.com/21301288/74208103-17cc0d00-4cbd-11ea-84c3-77b577671cca.png)

**Comment by lybtt** [comment]
个人觉得可以在设置的时候给个选项是否展示。其实这应该是两种不一样的东西。
1. 真私密文章，只能通过链接发给想要发的人。
2. 可能会在密码界面提示用户去哪里获取密码，目的是给别的东西引流之类的。

**Comment by ruibaby** [comment]
@lybtt 你说的第二种情况应该不算是私密文章了，类似 CSDN 那种？

**Comment by lybtt** [comment]
@ruibaby 大概吧，第二种是我个人想要的情况:joy:

**Comment by QuinnTian** [comment]
现在这感觉像是百度云盘私密分享的逻辑，但总感觉怪怪的估计是我用不到的原因。其实可以搞个第二种的功能。

**Comment by ChannD** [comment]
私密文章, 我个人的理解是自己可看, 并且外网不显示入口,在登录后方可显示出来! 这个可以参考QZone的文章的逻辑!  不难理解!  它是不同于加密文章的!

**Comment by JohnNiang** [comment]
我的理解同 @ChannD ，私密文章不应该公开入口。否则会对读者造成严重的困扰，破坏 Blog 环境。

**Comment by ChannD** [comment]
> 我的理解同 @ChannD ，私密文章不应该公开入口。否则会对读者造成严重的困扰，破坏 Blog 环境。

恩, 换一种角度来说即使不是用来记录私人的日记,私密文章这个在国内互联网是必须要有的, 一些好的文章,在国内的政治环境下是不允许被公开访问的, 但是这个时候遇到一篇好的文章,不存的话, 可能随时就404!实属可惜!显然这类文章并不适合有公开的入口进行访问!  个人见解 !

**Comment by JohnNiang** [comment]
昨日我发现以为 haloer 通过在一篇公开的文章中添加私密文章的链接，这个做法似乎可以解决满足伪公开的需求。

**Comment by ruibaby** [comment]
可以这样，我们提供一个固定的地址，用于列表私密文章。如果你们觉得可以，后续我们会提供这个功能。 另外，类似于 CSDN 那种引导用户去关注啥公众号获取密码之类的功能我们永远不会做，望理解。

**Comment by ChannD** [comment]
> 可以这样，我们提供一个固定的地址，用于列表私密文章。如果你们觉得可以，后续我们会提供这个功能。 另外，类似于 CSDN 那种引导用户去关注啥公众号获取密码之类的功能我们永远不会做，望理解。

您说的这个,一般都是用来商业用途, 这是个伪需求! 太商业, 我个人也不喜欢!如果是一个固定的地址获取私密文章列表, 基本上还是等于公开(虽然没公开文章内容, 但公开了文章的标题,),
如果是我开发这个私密的话, 进主页后,我回去session或者缓存里面找一串密钥, 这个密钥是在登录后生产的! 如果这个session里面的密钥和后台随机生产的密钥一致, 认为是已登录状态,  调整主页文章列表获取策略(公开和非公开一起取),

**Comment by SaintLoong** [comment]
私密文章是不想公开的，但从另一个角度说，博客写文章有几种情况：
1、纯技术分享，当然这个就是公开的
2、未整理好的随手记，大家都忙，有的时候可能随便整理点东西放到电脑里了，但换个环境就没了，放到博客里加上密码就可以随时更新，公开文章列表可以方便查找，不用总去登录后台，有的时候公开场合只是想看看，找些知识碎片而已，如果没有列表甚至时间久了自己都不记得写过，文章多了总要登陆后台去查找，但首页显示了可以提醒自己，因为工作忙文章跳票的估计大有人在
3、写好的文章，自己觉得涉及些商业或者秘密的内容，不方便公开但可以在有限的圈子里传播，首先博客的一个优势就是分享，每次都通知别人去访问个链接，有些麻烦，那还不如一个mackdown文档邮件或者QQ发过去，更省心，所以通知某些人固定链接的方式其实也给别人和自己增添了麻烦，对方换个电脑想去看你文章的时候未必记录了你的链接，还需要找你要文章地址

其实用户体验的确很重要，但博客是你自己的空间，本着分享的精神去发布文章，难道你去博主家做客博主就要打开保险箱证明他的诚意吗？他不需要隐私吗？想获取加密文章内容那可以进行更深层次的沟通，对大家都好，因为每个人都有些小范围传播的东西是吧？

所以单独页面显示加密文章也挺好的，因为页面不是都可以设置是否显示吗？

**Comment by JohnNiang** [comment]
综上，我们可以考虑提供一个公共的默认页面用于展示私密文章列表，当然主题也可以自行创建覆盖默认的样式。**但是我们绝不会将私密文章和公开文章混合在一起给读者展示。**

**Comment by ChannD** [comment]
>" 但博客是你自己的空间，本着分享的精神去发布文章"

这个并不一定是适用于所有人的, 分享的归分享, 私密的归私密(即使文章名称也得是私密的)

**Comment by LainNetWork** [comment]
我的建议是提给模板提供一个当前访问用户是否已经登录后台的状态参数，如果登录后台了，说明是作者本人，则将私密文章渲染到列表。参考typecho的相关功能。这个参数我觉得很有必要，可以扩展许多便捷功能，比如在文章页面可以根据登录状态，显示编辑按钮，快速跳转到后台相应文章的编辑界面，这样就不用专门登录后台去查找想要编辑的文章了。

**Comment by xijiangkiki** [comment]
逻辑上请不要修改，私密文章真的不想让任何人看到，标题也不行

但是目前有bug，无法访问

**Comment by ruibaby** [comment]
> 逻辑上请不要修改，私密文章真的不想让任何人看到，标题也不行
> 
> 但是目前有bug，无法访问

无法访问的bug已经修复，等待下个版本发布。
