### ISSUE TITLE
默认评论没有随机头像或者从腾讯QQ获取头像

### ISSUE THREAD

**Issue by carolcoral** [halo-dev/halo#5610]
### Your current Halo version

2.14.0-rc.1

### Describe this feature

默认评论没有随机头像或者从腾讯QQ获取头像

<img width="506" alt="image" src="https://github.com/halo-dev/halo/assets/8952687/7827b497-c706-40bc-a5ee-0835434338b4">

**Comment by carolcoral** [comment]
获取QQ头像接口：http://q.qlogo.cn/headimg_dl?dst_uin=QQ号码&spec=140&img_type=jpg

**Comment by ruibaby** [comment]
感谢反馈此问题，后续将在评论组件中兼容 Gravatar，会根据邮箱生成 Gravatar 链接，https://github.com/halo-dev/plugin-comment-widget/issues/97

但 QQ 似乎不是很好支持，如果要支持还需要让访客填写 QQ，并且没有字段用于存储这个信息。我不认为这是一个好的方案，并且也不是类似于 Gravatar 的公共头像服务。

/triage duplicate

**Comment by carolcoral** [comment]
> 感谢反馈此问题，后续将在评论组件中兼容 Gravatar，会根据邮箱生成 Gravatar 链接，[halo-dev/plugin-comment-widget#97](https://github.com/halo-dev/plugin-comment-widget/issues/97)
> 
> 但 QQ 似乎不是很好支持，如果要支持还需要让访客填写 QQ，并且没有字段用于存储这个信息。我不认为这是一个好的方案，并且也不是类似于 Gravatar 的公共头像服务。
> 
> /triage duplicate

可以考虑使用邮箱字段：
1. 判断当前用户是否已登录，如果登录则使用登录账号的头像
2. 如果未登录则判断当前填写的邮箱内容后缀为 `@qq.com` 则获取前面的QQ号码生成QQ头像即可，否则就使用avatar随机头像

**Comment by carolcoral** [comment]
随机头像可以考虑使用改rep，感觉好看点：https://github.com/multiavatar/Multiavatar

**Comment by guqing** [comment]
> 随机头像可以考虑使用改rep，感觉好看点：[multiavatar/Multiavatar](https://github.com/multiavatar/Multiavatar)

有想过，或许可以

**Comment by adozhao** [comment]
默认直接搞 ryanc 的头像吧, 毕竟那么帅
![03736097](https://github.com/halo-dev/halo/assets/23180747/f499d68b-3a88-4e8a-8656-9fe30d671e28)

**Comment by carolcoral** [comment]
> ryanc

ryan 头像？感觉可能不太合适，没有提供可用的api或js钩子呢

**Comment by ruibaby** [comment]
已经在 https://github.com/halo-dev/halo/pull/5642 和 https://github.com/halo-dev/plugin-comment-widget/pull/111 中支持 Gravatar。

/close
