### ISSUE TITLE
增加AI内容生成

### ISSUE THREAD

**Issue by Yangxiaoba** [halo-dev/halo#5611]
### 你当前使用的版本

1.82.2

### 描述一下此特性

与AI相结合
结合当前前沿的人工智能技术和自然语言处理技术，引入AI内容生成器，用户在撰写博客文章时，能根据关键词、标题或初步大纲自动生成部分内容草稿，以此提高创作效率。
AI还可以用于生成摘要、关键词标签等，帮助博主进行内容优化

**Comment by guqing** [comment]
应用市场已经有 AI 插件可以做到你说大部分功能 https://www.halo.run/store/apps/app-riNgb 你可以到此插件的评论区提建议来增强， Halo core 中只会做核心功能，这种功能不是所有人都能够使用还受限与地区和网络限制等因此只适合做成插件

/priority awaiting-more-evidence
