### ISSUE TITLE
使用搜索但是搜索不到东西

### ISSUE THREAD

**Issue by txbxxx** [halo-dev/halo#5613]
### 系统信息

- 外部访问地址: http://blog.tanc.fun:9999/
- 启动时间: 2024-02-25 11:39
- 版本: 2.11.3
- 构建时间: 2023-12-27 12:13
- Git Commit: 8e9b07d
- Java: IBM Semeru Runtime Open Edition / 17.0.9+9
- 数据库: MariaDB Server / 5.5.5-10.4.32-MariaDB
- 操作系统: Linux / 3.10.0-1160.105.1.el7.x86_64
- 已激活主题: [Hao](https://githubfast.com/liuzhihang/halo-theme-hao)
- 已启动插件:
  - [KaTeX](https://github.com/halo-sigs/plugin-katex)
  - [highlight.js 代码高亮](https://github.com/halo-sigs/plugin-highlightjs)
  - AI 助手
  - [Meilisearch](https://github.com/Rainsheep/halo-plugin-meilisearch)
  - [文本绘图](https://github.com/halo-sigs/plugin-text-diagram)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [ByteMD](https://github.com/ruibaby/plugin-bytemd)
  - [lightgallery.js 灯箱](https://github.com/halo-sigs/plugin-lightgallery)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [对象存储（Amazon S3 协议）](https://github.com/halo-dev/plugin-s3)
  - [Willow Markdown 编辑器](https://github.com/guqing/willow-mde)
  - [Vditor编辑器](https://github.com/justice2001/veditor-plugin)
  - [Docsme](https://github.com/f2ccloud/plugin-docsme)
  - [文章导入导出](https://jhacker.cn/2023/halo-plugin-export2doc)
  - [Markdown / HTML 内容块](https://github.com/halo-dev/plugin-hybrid-edit-block)

### 使用的哪种方式运行？

Docker

### 发生了什么？

在开启了搜索插件后，使用却搜索不到东西
![image](https://github.com/halo-dev/halo/assets/79389617/d367a180-ad9e-4624-aa52-461858b3bd93)

**Comment by ruibaby** [comment]
感谢反馈此问题，当前你可以尝试在仪表盘的快捷访问中点击“刷新搜索引擎”按钮。

/triage needs-information

**Comment by txbxxx** [comment]
> 感谢反馈此问题，当前你可以尝试在仪表盘的快捷访问中点击“刷新搜索引擎”按钮。
> 
> /triage needs-information

刷新显示报错如下:

2024-03-30T17:26:42.879+08:00  INFO 6 --- [tor-tcp-epoll-1] c.r.h.p.m.s.MeilisearchPostService       : remove all documents
2024-03-30T17:26:42.911+08:00 ERROR 6 --- [tor-tcp-epoll-1] a.w.r.e.AbstractErrorWebExceptionHandler : [92fd0f88-62561]  500 Server Error for HTTP POST "/apis/api.console.halo.run/v1alpha1/indices/post"

com.meilisearch.sdk.exceptions.MeilisearchCommunicationException: java.net.UnknownHostException: meilisearch: Name or service not known
	at com.meilisearch.sdk.http.CustomOkHttpClient.execute(CustomOkHttpClient.java:45) ~[na:na]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):

**Comment by Rainsheep** [comment]
@txbxxx 请按照 https://github.com/Rainsheep/halo-plugin-meilisearch 中配置，重新更新下 docker-compose 文件。 需要外挂 meilisearch

**Comment by Rainsheep** [comment]
@ruibaby 辛苦安装 github readme，更新下插件市场说明。
