### ISSUE TITLE
全新安装halo，备份恢复后，出现两个超级管理员用户

### ISSUE THREAD

**Issue by adozhao** [halo-dev/halo#5617]
### 系统信息

halo 2.x

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

1. 全新安装halo程序，注册新用户并进入控制台
2. 恢复其他网站的备份
3. 出现两个超级管理员用户，一个是新注册的，另一个是从备份恢复的

这里逻辑是合并而不是数据库全部替换？

![image](https://github.com/halo-dev/halo/assets/23180747/ece5fdc2-b989-4f98-a371-e71b927e0913)

**Comment by ruibaby** [comment]
符合预期，当前的逻辑就是增量恢复，只有遇到重复的数据才会覆盖，不会删除已有数据。

See https://github.com/halo-dev/halo/blob/main/docs/backup-and-restore.md#tbds

/kind support

**Comment by adozhao** [comment]
索迪斯耐~

**Comment by adozhao** [comment]
其实这个备份，我觉得是否有必要做个选项，增量或者覆盖。因为我个人每次的还原操作，其实都是想完全替换的
