### ISSUE TITLE
希望可以在配置文件中自定义console的路径

### ISSUE THREAD

**Issue by cnsino** [halo-dev/halo#5618]
### 描述一下此特性

自定义console的路径

**Comment by guqing** [comment]
目前不会考虑实在这个功能，我们一致认为改 console 的路径是没有意义的，如果你担心别人知道你的管理页面而觉得不安全，应该提升的是登陆的安全性而不是修改 console 的路径，Halo 支持以下几个措施:
1. 输入密码错误超过一定次数会被限流在一定程度上避免暴力尝试
2. 开启 TOTP 两步验证，开启后输入密码还需要二次确认即使知道密码也无法登陆
3. 建议不要使用弱密码

**Comment by alexallen1** [comment]
> 目前不会考虑实在这个功能，我们一致认为改 console 的路径是没有意义的，如果你担心别人知道你的管理页面而觉得不安全，应该提升的是登陆的安全性而不是修改 console 的路径，Halo 支持以下几个措施:
> 
> 1. 输入密码错误超过一定次数会被限流在一定程度上避免暴力尝试
> 2. 开启 TOTP 两步验证，开启后输入密码还需要二次确认即使知道密码也无法登陆
> 3. 建议不要使用弱密码

一扫一大把，需要我整理个txt放上来吗。
"console界面毫无漏洞坚不可摧，我是这么想的"

![1727125194836](https://github.com/user-attachments/assets/2ad83472-c1bd-4c91-8bf6-12404acc3842)

![1727125311235](https://github.com/user-attachments/assets/5b3133d4-6fda-41d7-80f4-e0df1882c081)

**Comment by ruibaby** [comment]
> > 目前不会考虑实在这个功能，我们一致认为改 console 的路径是没有意义的，如果你担心别人知道你的管理页面而觉得不安全，应该提升的是登陆的安全性而不是修改 console 的路径，Halo 支持以下几个措施:
> 
> > 
> 
> > 1. 输入密码错误超过一定次数会被限流在一定程度上避免暴力尝试
> 
> > 2. 开启 TOTP 两步验证，开启后输入密码还需要二次确认即使知道密码也无法登陆
> 
> > 3. 建议不要使用弱密码
> 
> 
> 
> 一扫一大把，需要我整理个txt放上来吗。
> 
> "console界面毫无漏洞坚不可摧，我是这么想的"
> 
> 
> 
> ![1727125194836](https://github.com/user-attachments/assets/2ad83472-c1bd-4c91-8bf6-12404acc3842)
> 
> 
> 
> ![1727125311235](https://github.com/user-attachments/assets/5b3133d4-6fda-41d7-80f4-e0df1882c081)
> 
> 
> 
> 

任何地方都不是坚不可摧，如果非常担心这个问题，我的建议是直接不要使用。

截图中的情况本身就是异常情况，首次安装时没有初始化始终都会跳转到初始化页面，用户本来就应该部署之后及时初始化。

上面已经说明了主要原因，再补充一下：https://bbs.halo.run/d/5230-%E7%AE%A1%E7%90%86%E5%90%8E%E5%8F%B0%E5%9C%B0%E5%9D%80/9
