### ISSUE TITLE
还是能搜索到已经删除的文章

### ISSUE THREAD

**Issue by stupid-pig** [halo-dev/halo#5625]
### 系统信息

- 外部访问地址: 
- 启动时间: 2024-03-30 23:25
- 版本: 2.14.0-SNAPSHOT
- 构建时间: 2024-03-27 22:27
- Git Commit: 35cc323
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: H2 / 2.2.224
- 操作系统: Linux / 3.10.0-1160.108.1.el7.x86_64
- 已激活主题: [Earth](https://github.com/halo-dev/theme-earth.git)
- 已启动插件:
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)

### 使用的哪种方式运行？

Docker

### 发生了什么？

我在后台将文章删除掉了，在搜索的时候还是能将文章搜索出来，点击这篇文章就到404界面了
![29b27893a601bec26c7e5ea1e1bfe38](https://github.com/halo-dev/halo/assets/93697379/fba9fa05-1cbc-4a66-b63e-5196580e4040)
![96920555dccd791689a7b62c13ddfbd](https://github.com/halo-dev/halo/assets/93697379/4a9d6a7a-67c5-461f-aa70-c4ac9da57f39)

**Comment by ruibaby** [comment]
ping @JohnNiang 

/kind bug
/area core
