### ISSUE TITLE
文章分类建议

### ISSUE THREAD

**Issue by chengzhongxue** [halo-dev/halo#5631]
### 你当前使用的版本

2.14

### 描述一下此特性

我文章都在子分类里，查看父分类的话，是拿不到子分类的文章的，能不能实现在父分类里也可以看到他的子分类的所有文章
![image](https://github.com/halo-dev/halo/assets/89380218/3adaf7f1-d5f3-48b2-a8c3-b3126f3bf3c8)
![image](https://github.com/halo-dev/halo/assets/89380218/acf8df2d-be8b-42fe-9e24-c9f8a6ea2f8f)
![image](https://github.com/halo-dev/halo/assets/89380218/5c20f134-c312-4c44-bb13-7e44aa191ff2)

**Comment by ruibaby** [comment]
/triage duplicate

Duplicate of https://github.com/halo-dev/halo/issues/4923

/close
