### ISSUE TITLE
有关于默认编辑器或文章的建议

### ISSUE THREAD

**Issue by paluo90** [halo-dev/halo#5636]
### 你当前使用的版本

 2.14

### 描述一下此特性

关于文章编辑，能否增加编辑历史的功能，以便恢复或提供对比。

**Comment by JohnNiang** [comment]
/triage duplicate

In favor of <https://github.com/halo-dev/halo/issues/5391>.

**Comment by paluo90** [comment]
我明明关闭了issue，咋又重启了。

**Comment by JohnNiang** [comment]
> 我明明关闭了issue，咋又重启了。

当前 Issue 仍然处于关闭状态。我只是添加了一个 Label，并和已经存在的 Issue 进行了关联。
