### ISSUE TITLE
主题已删除文件未被删除

### ISSUE THREAD

**Issue by carolcoral** [halo-dev/halo#5638]
### 系统信息

2.14.0

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

hao主题在新版本中删除了douban相关页面，但是安装新版本主题后发现被删除的页面仍然在halo系统中导致访问报错

https://github.com/liuzhihang/halo-theme-hao/issues/705

**Comment by chengzhongxue** [comment]
主题更新的时候删掉了个文件，然后用户更新主题，主题删掉的那个文件，用户的文件夹里还是存在，没有在更新主题的时候覆盖整个主题文件

**Comment by guqing** [comment]
我使用一个测试主题，结构如下：
```
.
├── templates
│   ├── fragments
│   │   ├── layout.html
│   │   └── post.html
│   ├── index.html
│   └── post.html
└── theme.yaml
```
然后删除其中的 post.html 并升级主题，得到的目录结构如下
```
.
├── templates
│   ├── fragments
│   │   └── layout.html
│   └── index.html
└── theme.yaml
```
因此根据描述并没有复现你们所说的问题呢

/triage needs-information

**Comment by carolcoral** [comment]
@guqing 可以测试一下呢
删除douban页面的版本：https://github.com/chengzhongxue/halo-theme-hao/releases/tag/v1.4.9-beta1
未删除douban页面的版本：https://github.com/chengzhongxue/halo-theme-hao/releases/tag/v1.4.8

**Comment by guqing** [comment]
Hi @carolcoral , 不知你所说的是不是 templates/douban.html 的这个文件，我根据你的描述下载的 https://github.com/chengzhongxue/halo-theme-hao/releases/tag/v1.4.9-beta1
然后直接解压，发现里面依然存在 templates/douban.html 文件

<img width="709" alt="image" src="https://github.com/halo-dev/halo/assets/38999863/75749978-7426-4bc5-8cfa-c399629dc686">

**Comment by carolcoral** [comment]
@guqing 稍后我们重新打包发布一下beta版本，检查PR发现确实是提交了删除的
<img width="1267" alt="image" src="https://github.com/halo-dev/halo/assets/8952687/d4046df9-2f5a-4c81-8514-f22529edb41a">

**Comment by carolcoral** [comment]
https://github.com/chengzhongxue/halo-theme-hao/releases/tag/v1.4.9-beta2
