### ISSUE TITLE
期望能够将内置的静态页面缓存封装为单独的插件

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#5639]
### 你当前使用的版本

2.14.0

### 描述一下此特性

在 https://github.com/halo-dev/halo/pull/4091 中，Halo 提供了内置的静态页面缓存功能，可以将模板渲染之后的页面缓存到内存 ，下次访问的时候就无需进行数据库查询和模板渲染，但此功能一直处于实验性功能，需要在配置中开启，这会比较麻烦。

所以期望能够将其独立出来作为插件，能够更好的单独进行迭代（如果通过插件可行），并且可以让使用者更加方便的停用和启用此功能。

/area core
/area plugin
/kind feature

**Comment by guqing** [comment]
目前技术上应该可以通过插件来完成

**Comment by ruibaby** [comment]
> 整站静态化是不是可以放到同一个插件里来做呢

这两者的实现方式可能还有点差别，目前应该拦截了请求，然后拿到返回内容进行缓存。如果是输出全站的静态页面，应该就不能用这样的方式了。
