### ISSUE TITLE
两步验证丢了怎么办

### ISSUE THREAD

**Issue by xiaopengzzc** [halo-dev/halo#5640]
### 系统信息

- 外部访问地址: https://chovy.cn/
- 启动时间: 2024-04-02 09:44
- 版本: 2.14.0
- 构建时间: 2024-04-01 11:15
- Git Commit: ae274db
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: MySQL Community Server - GPL / 8.2.0
- 操作系统: Linux / 6.1.0-13-amd64
- 已激活主题: [Hao](https://githubfast.com/liuzhihang/halo-theme-hao)
- 已启动插件:
  - [Media Optimizer](https://github.com/guqing/plugin-cloudinary)
  - [豆瓣](https://github.com/chengzhongxue/plugin-douban)
  - [朋友圈](https://github.com/chengzhongxue/plugin-friends)
  - [Meilisearch](https://github.com/Rainsheep/halo-plugin-meilisearch)
  - [文本绘图](https://github.com/halo-sigs/plugin-text-diagram)
  - [通知我](https://github.com/monyuan/notify-me)
  - [增强备份（Backup IMproved）](https://halo.run/store/apps/app-dHakX)
  - [文章限制阅读 Pro](https://github.com/f2ccloud/plugin-restricted-reading-pro)
  - [社交 IAM 认证](https://www.halo.run/store/apps/app-IXZkJ)
  - [微信公众号发布](https://github.com/f2ccloud/plugin-platforms-sync)
  - [Docsme](https://github.com/f2ccloud/plugin-docsme)
  - AI 助手
  - [StackEdit](https://github.com/halo-sigs/plugin-stackedit)
  - [ByteMD](https://github.com/ruibaby/plugin-bytemd)
  - [highlight.js 代码高亮](https://github.com/halo-sigs/plugin-highlightjs)
  - [文章导入导出](https://jhacker.cn/2023/halo-plugin-export2doc)
  - [我的装备管理](https://github.com/halo-sigs/plugin-equipments)
  - [prism.js 代码高亮](https://github.com/liuzhihang/plugin-prismjs)
  - [无色界](https://github.com/guqing/halo-plugin-colorless)
  - [WordPress导入](https://github.com/wan92hen/plugin-wordpress)
  - [KaTeX](https://github.com/halo-sigs/plugin-katex)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [图库管理](https://github.com/halo-sigs/plugin-photos)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [Markdown / HTML 内容块](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [对象存储（Amazon S3 协议）](https://github.com/halo-dev/plugin-s3)
  - 联系表单
  - [站点推送插件](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [Willow Markdown 编辑器](https://github.com/guqing/willow-mde)
  - [lightgallery.js 灯箱](https://github.com/halo-sigs/plugin-lightgallery)
  - [Metrics Graph](https://github.com/guqing/plugin-metrics-graph)
  - [Vditor编辑器](https://github.com/justice2001/veditor-plugin)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

两步验证丢了，不知道用什么软件弄的了，该如何重置

**Comment by JohnNiang** [comment]
目前暂时没有比较好的办法。不过我可以基于 2.14.0 构建一个禁用二步验证的 Docker 镜像，供你临时解决当前问题。

后续可以提供一个启动配置的方式来临时禁用二步验证，例如：

```yaml
halo:
  security:
    two-factor-disabled: true
```

/kind improvement
/area core
/milestone 2.15.x

**Comment by JohnNiang** [comment]
禁用二步验证的 Docker 镜像：[johnniang/halo:2.14.0-no-2fa](https://hub.docker.com/layers/johnniang/halo/2.14.0-no-2fa/images/sha256-a7c5b70bb2ffb22540ea7c22d90400b93ca32d588bc154632b023b9ce03e331f?tab=layers)

成功修改二步验证后，建议恢复至 `halohub/halo:2.14.0`。

**Comment by xiaopengzzc** [comment]
![Clip_2024-04-03_15-04-35](https://github.com/halo-dev/halo/assets/136769452/feb3c2d1-df6e-44e8-80e5-2830d2e9545f)
报这个错误，是什么问题呢

**Comment by xiaopengzzc** [comment]
> 取消二步验证的 Docker 镜像：[johnniang/halo:2.14.0-no-2fa](https://hub.docker.com/layers/johnniang/halo/2.14.0-no-2fa/images/sha256-a7c5b70bb2ffb22540ea7c22d90400b93ca32d588bc154632b023b9ce03e331f?tab=layers)
> 
> 成功修改二步验证后，建议恢复至`halohub/halo:2.14.0`。

![Clip_2024-04-03_15-04-35](https://github.com/halo-dev/halo/assets/136769452/bce64f91-eb42-41c3-8f37-e9c8d239c719)

**Comment by xiaopengzzc** [comment]
> > 取消二步验证的 Docker 镜像：[johnniang/halo:2.14.0-no-2fa](https://hub.docker.com/layers/johnniang/halo/2.14.0-no-2fa/images/sha256-a7c5b70bb2ffb22540ea7c22d90400b93ca32d588bc154632b023b9ce03e331f?tab=layers)
> > 成功修改二步验证后，建议恢复至`halohub/halo:2.14.0`。
> 
> ![Clip_2024-04-03_15-04-35](https://private-user-images.githubusercontent.com/136769452/319075536-bce64f91-eb42-41c3-8f37-e9c8d239c719.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMjgzODYsIm5iZiI6MTcxMjEyODA4NiwicGF0aCI6Ii8xMzY3Njk0NTIvMzE5MDc1NTM2LWJjZTY0ZjkxLWViNDItNDFjMy04ZjM3LWU5YzhkMjM5YzcxOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwM1QwNzA4MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZDFlZGJmMjg5OTcwNWZiMWU2Y2Y1ZWE5MTY0YzgwZGY1NjVkNzg5MzY2Y2FlZmVkYjIyN2NiZDg2ZmUzNmU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DAzpNap8F_jjKOCvxonJwV-VeZ6DobK2btSg0V1SvEk)

![Clip_2024-04-03_15-09-26](https://github.com/halo-dev/halo/assets/136769452/4cf24d70-0d06-42ba-84ee-48b867dfb0b4)

**Comment by JohnNiang** [comment]
从日志来看，你的服务器访问 Docker 存在网络问题。建议检查一下服务器的网络状态并尝试执行以下命令测试连通性：
```bash
docker pull johnniang/halo:2.14.0-no-2fa
```

**Comment by acmookey** [comment]
@JohnNiang 你好，我的Docker镜像 `halohub/halo:2.12.0` 在重启后同样出现了2fa验证失败的情况（我是使用Vaultwarden作为TOTP的管理器，其他的2fa是可以正常验证的）

正好看到这个issue，但是我的服务器是 `linux/arm64`平台的树莓派，但 `johnniang/halo:2.14.0-no-2fa`这个镜像目前不支持该平台，想看看您是否方便同样提供一份 'linux/arm64'平台的 `johnniang/halo:2.14.0-no-2fa` 镜像 :)

**Comment by JohnNiang** [comment]
Hi @acmookey , 请重新尝试拉取一下，我已经通过 buildx 重新构建了包含 linux/arm64 平台的镜像。

> https://hub.docker.com/layers/johnniang/halo/2.14.0-no-2fa/images/sha256-a7c5b70bb2ffb22540ea7c22d90400b93ca32d588bc154632b023b9ce03e331f?tab=layers

**Comment by acmookey** [comment]
> 禁用二步验证的 Docker 镜像：[johnniang/halo:2.14.0-no-2fa](https://hub.docker.com/layers/johnniang/halo/2.14.0-no-2fa/images/sha256-a7c5b70bb2ffb22540ea7c22d90400b93ca32d588bc154632b023b9ce03e331f?tab=layers)
> 
> 成功修改二步验证后，建议恢复至 `halohub/halo:2.14.0`。

@JohnNiang 感谢帮助，按照以上步骤已经禁用了 2fa，目前正常使用了

**Comment by xiaopengzzc** [comment]
> halohub/halo:2.14.0

![Clip_2024-04-03_16-31-51](https://github.com/halo-dev/halo/assets/136769452/90977d75-f13b-4bc2-9a45-55f29c9f14c4)
还是不可以，用的google的totp

**Comment by xiaopengzzc** [comment]
> > halohub/halo:2.14.0
> 
> ![Clip_2024-04-03_16-31-51](https://private-user-images.githubusercontent.com/136769452/319105086-90977d75-f13b-4bc2-9a45-55f29c9f14c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMzM1MjksIm5iZiI6MTcxMjEzMzIyOSwicGF0aCI6Ii8xMzY3Njk0NTIvMzE5MTA1MDg2LTkwOTc3ZDc1LWYxM2ItNGJjMi05YTQ1LTU1ZjI5YzlmMTRjNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwM1QwODMzNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZjFiYTIyN2I4YjdhYjJkYmJjNzkyODdkYjRiM2UzMDc2MDU2YTBmNTQxZDg1NzRiNzczMDdjMTM4NDQ3MmFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SwofsxmgpPq1nA85ZSx0iygYepYhbi4ytt_kDT7bc7Q) 还是不可以，用的google的totp

![Clip_2024-04-03_16-34-51](https://github.com/halo-dev/halo/assets/136769452/9d027660-82f5-4950-ae71-8e96928919be)
配置是成功的

**Comment by JohnNiang** [comment]
Hi @xiaopengzzc ，我在 www.halo.run 配置好 2FA 之后可以成功登录。

不太明白为什么你需要在 www.halo.run 中登录，而不是你自己的站点。

**Comment by xiaopengzzc** [comment]
> Hi @xiaopengzzc ，我在 [www.halo.run](http://www.halo.run) 配置好 2FA 之后可以成功登录。
> 
> 不太明白为什么你需要在 [www.halo.run](http://www.halo.run) 中登录，而不是你自己的站点。

就是在商店购买的时候，登录就会跳出这个两步验证

**Comment by ruibaby** [comment]
@xiaopengzzc 这是 Halo 官网的两步验证，如果你登录之后需要两步验证，那么应该是你手动设置过。Halo 官网的两步验证和你自己搭建的网站没有任何关系。

**Comment by xiaopengzzc** [comment]
> @xiaopengzzc 这是 Halo 官网的两步验证，如果你登录之后需要两步验证，那么应该是你手动设置过。Halo 官网的两步验证和你自己搭建的网站没有任何关系。

现在已经不知道了，有什么解决方案，目前在商店买的那些插件主题无法使用，也不能购买新的插件和主题

**Comment by ruibaby** [comment]
> > @xiaopengzzc 这是 Halo 官网的两步验证，如果你登录之后需要两步验证，那么应该是你手动设置过。Halo 官网的两步验证和你自己搭建的网站没有任何关系。
> 
> 现在已经不知道了，有什么解决方案，目前在商店买的那些插件主题无法使用，也不能购买新的插件和主题

如果是在 Halo 官网的两步验证设备丢失，你可以发送邮件到 `hi@halo.run`，注明你的用户名、邮箱等，以及能够证明你身份的资料（比如支付信息），我们可以帮你取消两步验证。

**Comment by xiaopengzzc** [comment]
> > > @xiaopengzzc 这是 Halo 官网的两步验证，如果你登录之后需要两步验证，那么应该是你手动设置过。Halo 官网的两步验证和你自己搭建的网站没有任何关系。
> > 
> > 
> > 现在已经不知道了，有什么解决方案，目前在商店买的那些插件主题无法使用，也不能购买新的插件和主题
> 
> 如果是在 Halo 官网的两步验证设备丢失，你可以发送邮件到 `hi@halo.run`，注明你的用户名、邮箱等，以及能够证明你身份的资料（比如支付信息），我们可以帮你取消两步验证。

感谢，我已发送邮件

**Comment by xiaopengzzc** [comment]
> > > @xiaopengzzc 这是 Halo 官网的两步验证，如果你登录之后需要两步验证，那么应该是你手动设置过。Halo 官网的两步验证和你自己搭建的网站没有任何关系。
> > 
> > 
> > 现在已经不知道了，有什么解决方案，目前在商店买的那些插件主题无法使用，也不能购买新的插件和主题
> 
> 如果是在 Halo 官网的两步验证设备丢失，你可以发送邮件到 `hi@halo.run`，注明你的用户名、邮箱等，以及能够证明你身份的资料（比如支付信息），我们可以帮你取消两步验证。

麻烦官方大大尽快处理一下哈，已经把所需的素材资料发给你们了，感谢

**Comment by ruibaby** [comment]
以上问题都已解决，我将关闭此 issue。

/close

**Comment by JohnNiang** [comment]
/reopen
/milestone 2.17.x

See https://github.com/halo-dev/halo/issues/5640#issuecomment-2033669465 for more.

**Comment by elijahxb** [comment]
v2.25.4 遇到相同问题，不过我自己解决了。
1. select * from extensions where data  like '%totp%' and name like '%你的用户名%'
2. 找到spec字段中的twoFactorAuthEnabled 和 totpEncryptedSecret，分别改为false 和 null
3. 保存之后重新登陆
