### ISSUE TITLE
使用makedown编辑时，增加拖入附件或者照片时自动上传功能

### ISSUE THREAD

**Issue by szgacsaftop** [halo-dev/halo#5644]
### 你当前使用的版本

halo:2.14 StackEdit:1.1.1,ByteMD:1.4.0

### 描述一下此特性

使用makedown编辑时，增加拖入附件或者照片时自动上传功能

**Comment by szgacsaftop** [comment]
目前我所使用的步骤为：1.先 上传附件。2.选择附件

**Comment by ruibaby** [comment]
此问题无法在此仓库中解决，建议向具体的插件仓库提交 issue。

**Comment by szgacsaftop** [comment]
好的
