### ISSUE TITLE
增强备份和站点收录推送的日志都是不按时间排序的

### ISSUE THREAD

**Issue by 52lemon6** [halo-dev/halo#5647]
### 系统信息

- 外部访问地址: https://oniya.cn/
- 启动时间: 2024-04-01 20:16
- 版本: 2.14.0
- 构建时间: 2024-04-01 11:15
- Git Commit: ae274db
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: 20200531 / 5.7.18-cynos-log
- 操作系统: Linux / 6.1.0-13-amd64
- 已激活主题: [Theme Joe3](https://github.com/jiewenhuang/halo-theme-joe3.0)
- 已启动插件:
  - [OAuth2 认证](https://github.com/halo-sigs/plugin-oauth2)
  - [highlight.js 代码高亮](https://github.com/halo-sigs/plugin-highlightjs)
  - [Metrics Graph](https://github.com/guqing/plugin-metrics-graph)
  - [Markdown / HTML 内容块](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [Vditor编辑器](https://github.com/justice2001/veditor-plugin)
  - [Willow Markdown 编辑器](https://github.com/guqing/willow-mde)
  - [图库管理](https://github.com/halo-sigs/plugin-photos)
  - [文章导入导出](https://jhacker.cn/2023/halo-plugin-export2doc)
  - AI 助手
  - [Docsme](https://github.com/f2ccloud/plugin-docsme)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [站点推送插件](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [增强备份（Backup IMproved）](https://halo.run/store/apps/app-dHakX)
  - 联系表单
  - [文章限制阅读 Pro](https://github.com/f2ccloud/plugin-restricted-reading-pro)
  - [对象存储（Amazon S3 协议）](https://github.com/halo-dev/plugin-s3)
  - [站点迁移](https://github.com/halo-sigs/plugin-migrate)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

增强备份和站点收录推送的日志既不按时间排序的也不是按照成功与否排序的，正常情况下我们看日志要么是按照时间查看，看最近有没有出问题，又或者是查看哪些请求出了问题，希望这些插件的日志能够按照时间或失败与否排序
![image](https://github.com/halo-dev/halo/assets/40059643/2cec6c42-54d6-425e-b115-7c20cd07c3a8)
![image](https://github.com/halo-dev/halo/assets/40059643/2f24dd7e-021a-4608-921a-3e133f0755ae)

**Comment by ruibaby** [comment]
感谢反馈此问题。这个问题可能和 [2.12.0](https://github.com/halo-dev/halo/releases/tag/v2.12.0) 中加入了索引机制有关，目前默认为所有模型的创建时间字段添加了索引。

ping @halo-dev/sig-halo 

请帮忙确认这是否符合预期，如果符合预期，可能得在调用接口的时候默认传递 sort 参数。

**Comment by guqing** [comment]
> 感谢反馈此问题。这个问题可能和 [2.12.0](https://github.com/halo-dev/halo/releases/tag/v2.12.0) 中加入了索引机制有关，目前默认为所有模型的创建时间字段添加了索引。
> 
> ping @halo-dev/sig-halo
> 
> 请帮忙确认这是否符合预期，如果符合预期，可能得在调用接口的时候默认传递 sort 参数。

确实是因为现在没有默认的排序参数导致的
