### ISSUE TITLE
用户选项没有头像功能

### ISSUE THREAD

**Issue by 1945251yyq** [halo-dev/halo#5648]
### 系统信息

Linux NEW-3573315869 6.1.0-10-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.37-1 (2023-07-03) x86_64 GNU/Linux

### 使用的哪种方式运行？

Docker

### 发生了什么？

编辑超级管理员账户以及新增用户没有头像选项

### 附加信息

![QQ截图20240406181200](https://github.com/halo-dev/halo/assets/154125368/27cc696b-d6d4-4186-9af2-dd5b13a8c0b3)

**Comment by 1945251yyq** [comment]
image: halohub/halo:2.14

**Comment by ruibaby** [comment]
感谢反馈此问题，当前确实无法再创建表单中为用户指定头像，但管理员或者用户自己可以在个人资料页面上传头像：

<img width="693" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/356cda42-4e0d-4c1a-b58a-5dc523123a97">

请问此 issue 是需要支持在创建用户的时候就支持上传头像吗？

/kind feature
/area ui
