### ISSUE TITLE
表单插件导出csv使用office打开时会乱码

### ISSUE THREAD

**Issue by 52lemon6** [halo-dev/halo#5649]
### 系统信息

- 外部访问地址: https://oniya.cn/
- 启动时间: 2024-04-01 20:16
- 版本: 2.14.0
- 构建时间: 2024-04-01 11:15
- Git Commit: ae274db
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: 20200531 / 5.7.18-cynos-log
- 操作系统: Linux / 6.1.0-13-amd64
- 已激活主题: [Theme Joe3](https://github.com/jiewenhuang/halo-theme-joe3.0)
- 已启动插件:
  - [OAuth2 认证](https://github.com/halo-sigs/plugin-oauth2)
  - [highlight.js 代码高亮](https://github.com/halo-sigs/plugin-highlightjs)
  - [Metrics Graph](https://github.com/guqing/plugin-metrics-graph)
  - [Markdown / HTML 内容块](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [Vditor编辑器](https://github.com/justice2001/veditor-plugin)
  - [Willow Markdown 编辑器](https://github.com/guqing/willow-mde)
  - [图库管理](https://github.com/halo-sigs/plugin-photos)
  - [文章导入导出](https://jhacker.cn/2023/halo-plugin-export2doc)
  - AI 助手
  - [Docsme](https://github.com/f2ccloud/plugin-docsme)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [站点推送插件](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [增强备份（Backup IMproved）](https://halo.run/store/apps/app-dHakX)
  - 联系表单
  - [文章限制阅读 Pro](https://github.com/f2ccloud/plugin-restricted-reading-pro)
  - [对象存储（Amazon S3 协议）](https://github.com/halo-dev/plugin-s3)
  - [站点迁移](https://github.com/halo-sigs/plugin-migrate)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

表单插件导出csv使用office打开时会乱码，因为没有添加utf-8的bom信息，在使用office的时候打开csv文件会乱码，因为在没有添加bom信息的时候会导致office将文件的格式识别成unicode，因为在unicode格式中没有bom信息所以会默认命中unicode

**Comment by ruibaby** [comment]
感谢反馈此问题，但这个问题无法在此仓库解决，建议直接为具体的插件仓库提交 issue，如果此插件为应用市场的付费插件，那么可以直接在应用的[讨论](https://www.halo.run/store/apps/app-gSebd?tab=comment)中提交。
