### ISSUE TITLE
默认编辑器会将并不相关的url或ip转换为超链

### ISSUE THREAD

**Issue by 52lemon6** [halo-dev/halo#5653]
### 系统信息

- 外部访问地址: https://oniya.cn/
- 启动时间: 2024-04-01 20:16
- 版本: 2.14.0
- 构建时间: 2024-04-01 11:15
- Git Commit: ae274db
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: 20200531 / 5.7.18-cynos-log
- 操作系统: Linux / 6.1.0-13-amd64
- 已激活主题: [Theme Joe3](https://github.com/jiewenhuang/halo-theme-joe3.0)
- 已启动插件:
  - [OAuth2 认证](https://github.com/halo-sigs/plugin-oauth2)
  - [highlight.js 代码高亮](https://github.com/halo-sigs/plugin-highlightjs)
  - [Metrics Graph](https://github.com/guqing/plugin-metrics-graph)
  - [Markdown / HTML 内容块](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [Vditor编辑器](https://github.com/justice2001/veditor-plugin)
  - [Willow Markdown 编辑器](https://github.com/guqing/willow-mde)
  - [图库管理](https://github.com/halo-sigs/plugin-photos)
  - [文章导入导出](https://jhacker.cn/2023/halo-plugin-export2doc)
  - AI 助手
  - [Docsme](https://github.com/f2ccloud/plugin-docsme)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [站点推送插件](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [增强备份（Backup IMproved）](https://halo.run/store/apps/app-dHakX)
  - 联系表单
  - [文章限制阅读 Pro](https://github.com/f2ccloud/plugin-restricted-reading-pro)
  - [对象存储（Amazon S3 协议）](https://github.com/halo-dev/plugin-s3)
  - [站点迁移](https://github.com/halo-sigs/plugin-migrate)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

默认编辑器会将并不相关的url或ip转换为超链，如图，我都换行了，他还把域名和IP转换成一个连接

![image](https://github.com/halo-dev/halo/assets/40059643/332398fd-624f-4ff1-9b99-71d8b4837db8)
![image](https://github.com/halo-dev/halo/assets/40059643/52149065-e79e-4858-99be-054dd31f952c)

**Comment by LIlGG** [comment]
目前默认编辑器链接的默认策略是粘贴之后如果检测到是链接相关文本（正则匹配），则会将其转为链接。

但这样确实会产生上述困扰，我认为粘贴链接文本后不转为链接，而是当用户选中一段文本并点击链接按钮时，根据选中的内容进行检测并转换，这种方式可能更加合理。

/kind improvement
/area editor
