### ISSUE TITLE
在多级分类情况下，父级文章分类可以点击但是显示文章内容不全（或为空）

### ISSUE THREAD

**Issue by AdRainty** [halo-dev/halo#5663]
### 系统信息

- 外部访问地址: https://www.adrainty.online/
- 启动时间: 2024-04-03 03:18
- 版本: 2.14.0
- 构建时间: 2024-04-01 11:15
- Git Commit: ae274db
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: MySQL Community Server - GPL / 8.3.0
- 操作系统: Linux / 5.4.119-20.0009.29
- 已激活主题: [Dream](https://github.com/nineya/halo-theme-dream2.0.git)
- 已启动插件:
  - [文章导入导出](https://jhacker.cn/2023/halo-plugin-export2doc)
  - [KaTeX](https://github.com/halo-sigs/plugin-katex)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [对象存储（Amazon S3 协议）](https://github.com/halo-dev/plugin-s3)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)

### 使用的哪种方式运行？

Docker

### 发生了什么？

如图, categories页面下显示文章分类中后端开发有10个文章，但10个文章都是子目录下的，点击子目录可以显示文章，但后端开发点击后里面没有显示文章

![image](https://github.com/halo-dev/halo/assets/62246440/6df7e629-832a-442c-bb6c-7766a6c37d11)

![image](https://github.com/halo-dev/halo/assets/62246440/90d76242-de8b-47d7-856a-b6b78ee2bda9)

![image](https://github.com/halo-dev/halo/assets/62246440/a4dec89b-795e-4520-af94-d40708c8e084)

能否在点击父分类的情况下，不仅有该分类下的文章，还加载全部子分类的文章内容呢？

**Comment by ruibaby** [comment]
/area core
/kind improvement

我建议为单个分类提供设置选项，用于确定是否要包含其下所有子分类的文章，包括计数。

**Comment by AirboZH** [comment]
我想尝试一下这个Issue

---

![image](https://github.com/halo-dev/halo/assets/50261327/861239e4-bcc6-4edd-a54a-5304ef3c8192)

这两种方式倾向于哪一种呢？

/assgin

**Comment by AirboZH** [comment]
BTW, 要是我们能写一种 [toggle](https://formkit.com/inputs/toggle) 效果就好了 😎

**Comment by ruibaby** [comment]
> 这两种方式倾向于哪一种呢？

第二种，实际上在任何只有 true/false 值的表单项目前都更推荐直接用 Checkbox。

**Comment by ruibaby** [comment]
> BTW, 要是我们能写一种 [toggle](https://formkit.com/inputs/toggle) 效果就好了 😎

目前无法直接使用 FormKit Pro，这个得自己实现，可以先提交一个 issue。

**Comment by ruibaby** [comment]
> /area core /kind improvement
> 
> 我建议为单个分类提供设置选项，用于确定是否要包含其下所有子分类的文章，包括计数。

针对改动的方式我又想了一下，可能还有另外一种方式：给单个分类添加**标记为独立**的选项，即勾选此选项之后，父级分类统计文章数和查询文章的时候就忽略这个分类。然后默认情况下查询父级分类的时候查询所有其下子分类的文章。

可以讨论一下哪种更好，我认为第二种可能会更符合直觉，用户使用也更加方便。

**Comment by AirboZH** [comment]
> 针对改动的方式我又想了一下，可能还有另外一种方式：给单个分类添加**标记为独立**的选项，即勾选此选项之后，父级分类统计文章数和查询文章的时候就忽略这个分类。然后默认情况下查询父级分类的时候查询所有其下子分类的文章。
> 
> 可以讨论一下哪种更好，我认为第二种可能会更符合直觉，用户使用也更加方便。

我赞同这个方法，将更多可能性给用户。就这样做吧

**Comment by AirboZH** [comment]
![image](https://github.com/halo-dev/halo/assets/50261327/5fd0a086-70da-4437-81f4-6d08d46e1bbd)

@ruibaby

括号当中是各分组的文章数量，后面的计数是其下所有子分类的计数，

是否需要一个标识来标识独立分组，目前看起来有些乱

默认分组 24 篇文章下面是技术规范 26 篇文章。

或者 独立分组的计数可以置为 0 （好像更怪了。

**Comment by AirboZH** [comment]
独立分类 这个词或许有点不够直观，或许可以直接叫做 "不计入父级"，如何？
![image](https://github.com/halo-dev/halo/assets/50261327/df793a12-dbfe-499d-9e36-4711051c588c)

**Comment by guqing** [comment]
> > /area core /kind improvement
> > 我建议为单个分类提供设置选项，用于确定是否要包含其下所有子分类的文章，包括计数。
> 
> 针对改动的方式我又想了一下，可能还有另外一种方式：给单个分类添加**标记为独立**的选项，即勾选此选项之后，父级分类统计文章数和查询文章的时候就忽略这个分类。然后默认情况下查询父级分类的时候查询所有其下子分类的文章。
> 
> 可以讨论一下哪种更好，我认为第二种可能会更符合直觉，用户使用也更加方便。

如果经常需要单独查询当前分类而不包括子分类的情况，这种方案可能不够灵活。
而单独为分类添加是否包含子分类则更控制范围加灵活

**Comment by ruibaby** [comment]
> 如果经常需要单独查询当前分类而不包括子分类的情况，这种方案可能不够灵活。
而单独为分类添加是否包含子分类则更控制范围加灵活

那如果是需要给父分类下的部分子分类排除掉呢？这个策略是包括所有层级的子分类还是第一层级？并且用户也无法直观的知道到底包含了哪些子分类。

**Comment by ruibaby** [comment]
> 独立分类 这个词或许有点不够直观，或许可以直接叫做 "不计入父级"，如何？ ![image](https://private-user-images.githubusercontent.com/50261327/322672460-df793a12-dbfe-499d-9e36-4711051c588c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNDMxMjEsIm5iZiI6MTcxMzI0MjgyMSwicGF0aCI6Ii81MDI2MTMyNy8zMjI2NzI0NjAtZGY3OTNhMTItZGJmZS00OTlkLTllMzYtNDcxMTA1MWM1ODhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDA0NDcwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1ZTYwN2MyYzJkMmFhODYzOGI3MzA5ZTg3NDY0NTM5NjhiMWI4Y2YwYWJlOTRmZjgyMTc5YzU5NzBmZGFiMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nGS7M63q1a0M6wl3DeJFVtAAZHcp2TiiEXY3dwTziaE)

我觉得只需要在 help 中描述清楚勾选之后的影响即可。
