### ISSUE TITLE
控制台数据加载不出来

### ISSUE THREAD

**Issue by cyril-cheng** [halo-dev/halo#5665]
### 系统信息

1panel安装的halo

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

今天想打开halo升级的，之前是2.13
登录控制台之后发现数据无法加载，所有菜单项都在转圈圈，日志和浏览器调试都没有发现错误。
![image](https://github.com/halo-dev/halo/assets/49748357/96c33b7e-3b46-4740-86a4-c8c02ce96e04)
然后我升级到了2.14，问题依旧，请问应该怎么解决？

### 相关日志输出

```shell
无。
```

**Comment by ruibaby** [comment]
感谢反馈此问题，请问是否使用了 MariaDB 数据库？

**Comment by ruibaby** [comment]
> 有没有通过控制台禁用插件的方法？我想查查是不是插件更新的问题，因为刚登录后台的时候数据是能正常加载的，然后我看到了几个插件提示升级，我就点了升级，然后就加载不了了。

有可能，如果数据无法加载，那估计只能去工作目录的 plugins 目录删除插件文件，然后重启了。

**Comment by ruibaby** [comment]
> ![image](https://private-user-images.githubusercontent.com/49748357/320348365-4870ec7e-6cbc-4480-9258-480be008dde5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NTQ3MDQsIm5iZiI6MTcxMjU1NDQwNCwicGF0aCI6Ii80OTc0ODM1Ny8zMjAzNDgzNjUtNDg3MGVjN2UtNmNiYy00NDgwLTkyNTgtNDgwYmUwMDhkZGU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDA1MzMyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlYWRmZGE3OThjNTg1ODY3YzQxNDJkNWQyMzFmNTFlMjZjMWE0ZjI2NDQ4ZTQ3MDI0N2U4YTUyZWFmNWE5OTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rVQPN5sZHgkQ2ZPJchpEhmV2NwMmu1ULa-BzATCqIao) 一共有这5个插件更新过，我挨个删除试试

我在上图看到了有 WordPress 导入插件，这个插件目前工作正常吗？ 为什么在工作目录中没有看到

**Comment by JohnNiang** [comment]
我也遇到类似的问题，不过只在 [Arc Browser](https://arc.net/) 上出现，Firefox 和 Chrome 暂时正常。

最后我重启了一下 Arc Browser，控制台就一切正常了。

**Comment by holwell** [comment]
> 我也遇到类似的问题，不过只在 [Arc Browser](https://arc.net/) 上出现，Firefox 和 Chrome 暂时正常。
> 
> 最后我重启了一下 Arc Browser，控制台就一切正常了。

卧槽，神医
![0D3CF434](https://github.com/user-attachments/assets/1aa16849-a223-4f48-839c-24f9834654ec)
