### ISSUE TITLE
提供 demo 配置功能

### ISSUE THREAD

**Issue by JohnNiang** [halo-dev/halo#567]
## 概述

提供 demo 配置功能，为官方 demo 做准备。

## 动机

为官方提供一个 halo demo，方便新用户更愉快便捷地体验。

## 详细解释

提供一种新的 Mode：demo（`run.halo.app.model.enums.Mode`），只需要添加  `application-demo.yml` 配置文件，并在执行的时候指定 `spring.profiles.active=demo` 即可。

在 demo 模式中，密码不允许被任何用户修改，不允许随意修改系统配置，即 `Option`。

**Comment by ruibaby** [comment]
@JohnNiang 其实这个我之前是这么做的
