### ISSUE TITLE
应用市场RSS插件下载量大于浏览量

### ISSUE THREAD

**Issue by adozhao** [halo-dev/halo#5670]
### 系统信息

- 版本: 2.14.0
- 构建时间: 2024-04-01 11:15
- Git Commit: ae274db
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: MySQL Community Server (GPL) / 5.7.44
- 操作系统: Linux / 3.10.0-1160.99.1.el7.x86_64
- 已激活主题: [Zero](https://github.com/adozhao/halo-theme-zero.git)
- 已启动插件:
  - [Media Optimizer](https://github.com/guqing/plugin-cloudinary)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [Vditor编辑器](https://github.com/justice2001/veditor-plugin)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [highlight.js 代码高亮](https://github.com/halo-sigs/plugin-highlightjs)
  - [对象存储（Amazon S3 协议）](https://github.com/halo-dev/plugin-s3)
  - [增强备份（Backup IMproved）](https://halo.run/store/apps/app-dHakX)
  - [lightgallery.js 灯箱](https://github.com/halo-sigs/plugin-lightgallery)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

RSS插件的下载量大于浏览量   
 
![image](https://github.com/halo-dev/halo/assets/23180747/a3d0828e-bc16-4727-ab5c-31ab1fe16508)

**Comment by ruibaby** [comment]
这可能是因为这个插件是预设插件，不少人首次安装 Halo 之后进入到插件管理都可能看到有预设插件有新的版本，然后就直接点击更新，没有查看详情就自然不会有新的浏览量。

这不属于 Halo 本身的问题。

/close
