### ISSUE TITLE
1.6升级到2.14，可以访问console,不能访问主页

### ISSUE THREAD

**Issue by wuyukk** [halo-dev/halo#5673]
### System information

- External url: http://localhost:8092/
- Start time: 2024-04-08 14:32
- Version: 2.14.0
- Build time: 2024-04-01 11:15
- Git Commit: ae274db
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- Database: mariadb.org binary distribution / 5.5.5-10.6.17-MariaDB-1:10.6.17+maria~deb11
- Operating system: Linux / 5.10.0-28-amd64
- Activated theme: [Earth](https://github.com/halo-dev/theme-earth.git)
- Enabled plugins: 

### What is the project operation method?

Docker Compose

### What happened?

1.6版本正常，同时安装了2.14，只改了端口号。
用2.14版本访问主页返回404，访问console各页面均正常。
[halo2.log](https://github.com/halo-dev/halo/files/14914323/halo2.log)

**Comment by ruibaby** [comment]
> Caused by: run.halo.app.infra.exception.NotFoundException: 404 NOT_FOUND "No primary menu found"

看日志是因为没有设置主菜单，你可以去菜单管理将某个菜单设置为主菜单试试。

**Comment by wuyukk** [comment]
Thank you !
