### ISSUE TITLE
Console 和 UC 的页面标题建议改为网站的实际标题

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#5679]
### 你当前使用的版本

2.14.0

### 描述一下此特性

如题，目前 Console 和 UC 的浏览器页面标题默认都为 `Halo`，期望能够改为用户设置的网站标题。

<img width="576" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/f83ff2f8-62aa-4cd9-9862-c01d133d7e9c">

**Comment by wan92hen** [comment]
现在发现在页面刷新、加载的时候标题还都是 Halo，这个需要新开个 issue 吗？

**Comment by ruibaby** [comment]
> 现在发现在页面刷新、加载的时候标题还都是 Halo，这个需要新开个 issue 吗？

这是因为后续设置 title 是异步的，刷的时候还没有执行 js，所以只能显示 index.html 中默认的 title。如果要改进，那只能删除 index.html 中的 title 文本。

可以新开 issue。
