### ISSUE TITLE
为用户设置中的 默认角色 设置默认值 或改为必填

### ISSUE THREAD

**Issue by mashirot** [halo-dev/halo#5688]
### 你当前使用的版本

2.14.0

### 描述一下此特性

/area core

如图，现有行为允许此选项为 `请选择角色`，值为 `"defaultRole": ""`
但此时可以保存成功，注册选项也在ui显示，但无法注册，这种现象是在预期内的吗

![image](https://github.com/halo-dev/halo/assets/52254895/2b064b99-2a16-45f7-84aa-d4813e889dd5)
![image](https://github.com/halo-dev/halo/assets/52254895/aac6a841-946a-458d-8788-67652ebc441a)
![image](https://github.com/halo-dev/halo/assets/52254895/b90a1f17-835d-4d68-b3c0-53e8a8ad6b61)

**Comment by ruibaby** [comment]
感谢反馈此问题，这里我觉得可以将 **默认角色** 改为必填，并且为这个选项添加显示条件，即勾选 **开放注册** 之后再显示 **默认角色** 选项。
