### ISSUE TITLE
halo支持高可用部署么？

### ISSUE THREAD

**Issue by lin1005q** [halo-dev/halo#5693]
### Your current Halo version

2.14

### Describe this feature

目前halo内部使用了pf4j作为插件系统。 单副本是没有问题的，高可用部署时如何支撑有考虑过么？

**Comment by lin1005q** [comment]
@ruibaby

**Comment by ruibaby** [comment]
hi @lin1005q ，可以先看看这个 issue 的讨论：https://github.com/halo-dev/halo/issues/5412

**Comment by lin1005q** [comment]
感谢
