### ISSUE TITLE
预览主题时打开文章或页面会改变主题为站点主题

### ISSUE THREAD

**Issue by kuankqaq** [halo-dev/halo#5700]
### 系统信息

- 外部访问地址: 
- 启动时间: 2024-04-14 14:28
- 版本: 2.14.0
- 构建时间: 2024-04-01 11:15
- Git Commit: ae274db
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: H2 / 2.2.224
- 操作系统: Linux / 5.10.0-16-amd64
- 已激活主题: [Earth](https://github.com/halo-dev/theme-earth.git)
- 已启动插件:
  - [无色界](https://github.com/guqing/halo-plugin-colorless)
  - [OAuth2 认证](https://github.com/halo-sigs/plugin-oauth2)
  - [Markdown / HTML 内容块](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)

### 使用的哪种方式运行？

Docker

### 发生了什么？

预览主题时打开任意文章或页面会改变主题为站点主题

### 附加信息

![image](https://github.com/halo-dev/halo/assets/144250506/5dff3678-06b8-431f-bc9b-65accd80c2b2)

**Comment by ruibaby** [comment]
感谢反馈此问题，这可能和主题适配有关，因为目前主题预览功能是在页面路由添加 `preview-theme` 参数来实现的，所以在切换页面的时候同样也需要携带这个参数，如果主题没有适配，那么将不再是预览主题的状态。

目前主题适配的方式是在所有动态超链接的语法中使用 `@{}` 包裹实际的路由变量，但目前似乎没有在开发文档中提到，后续可以专门提供一篇文档来说明。

/kind documentation

**Comment by guqing** [comment]
> 感谢反馈此问题，这可能和主题适配有关，因为目前主题预览功能是在页面路由添加 `preview-theme` 参数来实现的，所以在切换页面的时候同样也需要携带这个参数，如果主题没有适配，那么将不再是预览主题的状态。
> 
> 目前主题适配的方式是在所有动态超链接的语法中使用 `@{}` 包裹实际的路由变量，但目前似乎没有在开发文档中提到，后续可以专门提供一篇文档来说明。
> 
> /kind documentation

使用此 issue 来代替 https://github.com/halo-dev/docs/issues/424

/close
