### ISSUE TITLE
“作者”权限用户功能优化

### ISSUE THREAD

**Issue by CarryBit1** [halo-dev/halo#5703]
### 你当前使用的版本

最新版

### 描述一下此特性

我新建了一个“作者”权限的用户，用该用户账号登录后编辑的文章退出后会默认保存草稿，但是无法删除草稿。
由于是草稿，所以很多情况下会是废稿，所以建议加上可以删除本人的草稿这一权限

**Comment by ruibaby** [comment]
已经在 https://github.com/halo-dev/halo/pull/6729 中支持，将在 2.20.0 发布。

/close
