### ISSUE TITLE
---

### ISSUE THREAD

**Issue by QYG2297248353** [halo-dev/halo#5709]
---

**Comment by Haoke98** [comment]
same question

**Comment by ruibaby** [comment]
/triage duplicate 

Duplicate of https://github.com/halo-dev/theme-earth/issues/42

默认主题[最新版本](https://github.com/halo-dev/theme-earth/releases/tag/v1.8.0)已经支持更换内容渲染样式，你可以切换为 GitHub 风格。

<img width="575" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/0bbfc950-54be-4005-9048-0f7de8aaf18b">

**Comment by QYG2297248353** [comment]
不更换主题可以修复吗，还是说要等下个版本

**Comment by QYG2297248353** [comment]
哦哦哦，看差了，在插件市场找了半天，正在更新
