### ISSUE TITLE
分享文章存在锚点时链接超出输入框，显示异常

### ISSUE THREAD

**Issue by QYG2297248353** [halo-dev/halo#5711]
### 系统信息

- 外部访问地址: https://blog.lifebus.top
- 启动时间: 2024-04-09 21:00
- 版本: 2.14.0
- 构建时间: 2024-04-01 11:15
- Git Commit: ae274db
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: PostgreSQL / 16.1
- 操作系统: Linux / 5.14.0-362.18.1.el9_3.x86_64
- 已激活主题: [Earth](https://github.com/halo-dev/theme-earth.git)
- 已启动插件:
  - [lightgallery.js 灯箱](https://github.com/halo-sigs/plugin-lightgallery)
  - [对象存储（Amazon S3 协议）](https://github.com/halo-dev/plugin-s3)
  - [StackEdit](https://github.com/halo-sigs/plugin-stackedit)
  - [Markdown / HTML 内容块](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [highlight.js 代码高亮](https://github.com/halo-sigs/plugin-highlightjs)
  - [ByteMD](https://github.com/ruibaby/plugin-bytemd)
  - [图库管理](https://github.com/halo-sigs/plugin-photos)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

+ 锚点被提前编码(可算可不算)
+ 分享链接超出输入框
+ 复制按钮位置很别扭
![image](https://github.com/halo-dev/halo/assets/56836951/9e5c398a-a241-4d89-9681-d9da31b6264f)
![image](https://github.com/halo-dev/halo/assets/56836951/b86ba58c-c22e-45c0-aabc-20faee65bb8c)
![image](https://github.com/halo-dev/halo/assets/56836951/642de818-af2e-4349-a6c6-84177275621d)

没有超出输入框的复制按钮正常
![image](https://github.com/halo-dev/halo/assets/56836951/2dc19fde-1a44-4311-aeb1-73f404f2e98c)

鼠标从后向前选择时频闪严重

### 附加信息

要么对链接做个超出省略
要么链接放到富文本框中
要么复制按钮放到输入框下方居中，链接在输入框水平滚动
都是建议而已

**Comment by QYG2297248353** [comment]
频闪
![halo](https://github.com/halo-dev/halo/assets/56836951/bad0c204-f231-4d11-ad75-b06a608e42cf)

**Comment by ruibaby** [comment]
感谢反馈此问题，但这个问题属于主题的问题，不能在此仓库解决，所以我将转移到对应的主题仓库。

/triage unresolved
/close
