### ISSUE TITLE
插件开发 $formkit: code language: json 无法渲染

### ISSUE THREAD

**Issue by XiaoMo-Donald** [halo-dev/halo#5718]
### 系统信息

- 外部访问地址: http://localhost:8090
- 启动时间: 2024-04-15 23:17
- 版本: 2.14.0
- 构建时间: 2024-04-01 11:15
- Git Commit: ae274db
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: H2 / 2.2.224
- 操作系统: Linux / 5.15.146.1-microsoft-standard-WSL2
- 已激活主题: [Chirpy](https://github.com/AirboZH/halo-theme-chirpy.git)
- 已启动插件:
  - [uhalo 应用配置](https://github.com/XiaoMo-Donald/plugin-uhalo)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)

### 使用的哪种方式运行？

Docker

### 发生了什么？

插件开发过程中，定义表单 $formkit: code language: json 无法渲染

 
![image](https://github.com/halo-dev/halo/assets/49033970/b1ce46e5-afca-4014-ae16-c27ba5e8b36d)
![image](https://github.com/halo-dev/halo/assets/49033970/6b8ac4b1-012f-4939-a2d5-58213dec3374)

**Comment by ruibaby** [comment]
感谢反馈此问题，但我这边并未复现：

<img width="629" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/00be8a8b-4012-4f74-9e4e-0cc5562f1264">

看了你提供的配置，应该是默认值的类型有问题，此组件的 value 类型应该是 string，而不是一个对象。

/kind support

**Comment by XiaoMo-Donald** [comment]
okk 确实是 value的问题
