### ISSUE TITLE
文章作者转让功能

### ISSUE THREAD

**Issue by yovvis** [halo-dev/halo#5720]
### Your current Halo version

halo pro 2.14.0-rc.3

### Describe this feature

现状：超级管理员只有在文章列表操作文章，但是在我的文章里面目前是没有的（这个确实不是管理员发的，功能没问题）
需求：站点的超级管理员可以选择文章所属作者，预防用户注销，或者长时间不登录用户，文章所属不明的风险
提出原因：站点的用户删除了，其在网站上的所著所权，无特殊说明默认挂靠至管理员账户下

### Additional information

可以在以下位置加 <转让> 或者在设置的元数据中添加也可以
![image](https://github.com/halo-dev/halo/assets/60733474/60972a4a-7d7f-4b01-b14b-fa9edb2c975a)

**Comment by ruibaby** [comment]
感谢反馈此问题，这个功能确实有必要添加。我们可以考虑在文章设置中支持手动设置作者。

/area ui
/area core
/kind feature

**Comment by yovvis** [comment]
> 感谢反馈此问题，这个功能确实有必要添加。我们可以考虑在文章设置中支持手动设置作者。
> 
> /area ui /area core /kind feature

好滴

**Comment by LIlGG** [comment]
> 感谢反馈此问题，这个功能确实有必要添加。我们可以考虑在文章设置中支持手动设置作者。

系统当中目前有 `owner` 及 `contributors`。而在个人中心使用 `owner` 查询文章是否属于当前登录用户。

https://github.com/halo-dev/halo/blob/38ae38c842575420114d58c3720abba80c28c1ad/application/src/main/java/run/halo/app/content/PostQuery.java#L113-L117

因此这里是否为修改 `owner` 而不是 `contributors` ？在 console 的过滤项中，作者指 `contributors` 字段。

并且如果是修改 `owner`，则应该只允许有一个

**Comment by lv-goose** [comment]
> ### Your current Halo version
> halo pro 2.14.0-rc.3
> 
> ### Describe this feature
> 现状：超级管理员只有在文章列表操作文章，但是在我的文章里面目前是没有的（这个确实不是管理员发的，功能没问题） 需求：站点的超级管理员可以选择文章所属作者，预防用户注销，或者长时间不登录用户，文章所属不明的风险 提出原因：站点的用户删除了，其在网站上的所著所权，无特殊说明默认挂靠至管理员账户下
> 
> ### Additional information
> 可以在以下位置加 <转让> 或者在设置的元数据中添加也可以 ![image](https://private-user-images.githubusercontent.com/60733474/322707954-60972a4a-7d7f-4b01-b14b-fa9edb2c975a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3Njc5NzEsIm5iZiI6MTcxODc2NzY3MSwicGF0aCI6Ii82MDczMzQ3NC8zMjI3MDc5NTQtNjA5NzJhNGEtN2Q3Zi00YjAxLWIxNGItZmE5ZWRiMmM5NzVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDAzMjc1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExMmU1OTQ1MzgwNDU3ZDMwOGQzYTNiMjhkNTY3YjczZDI1MGFmMWE5N2MyM2U3Yjc0YjU4MDJkODAwMjEyZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FhKb0F5LrzvJKQCyc7-eUe6cOicKRmtsjTHhSqWxXFY)

遇到同样问题，期待早日实现。

**Comment by ruibaby** [comment]
/assign

我将尝试在文章设置中提供编辑作者的选项。
