### ISSUE TITLE
附件库外链支持

### ISSUE THREAD

**Issue by king-zhangbn** [halo-dev/halo#5728]
### 你当前使用的版本

214

### 描述一下此特性

我目前图片全部在图床上，我不想在本地留下任何图片元素，能否支持外链直接调用，附近库有外链的话可以大大减少资源的占用

**Comment by ruibaby** [comment]
感谢反馈此问题。

我觉得最佳解决方案应该是为你的图床编写一个选取图片的插件，类似于：<https://www.halo.run/store/apps/app-KfOps>，相关文档：<https://docs.halo.run/developer-guide/plugin/api-reference/ui/extension-points/attachment-selector-create>

通过链接转存到服务器我觉得是可以考虑的，直接保存一个外链我感觉不是特别有必要。

**Comment by king-zhangbn** [comment]
picgo 批量上传的图片可以直接在附件库里面上传链接，再在瞬间等地方调用图片
相册这东西能不能批量放外链，一个个传太麻烦了
我知道 s3 可以关联，但是我更加倾向于 GitHub+vercel 的图床

**Comment by ruibaby** [comment]
上面贴错了，应该是 https://www.halo.run/store/apps/app-NRcGw
