### ISSUE TITLE
点击菜单左侧“用户”，显示“未知错误”，且加载不出来用户信息

### ISSUE THREAD

**Issue by zeng-yq** [halo-dev/halo#5731]
### System information

![image](https://github.com/halo-dev/halo/assets/51290945/a0184bbf-11ff-40ae-a830-965db787afa3)

### What is the project operation method?

Docker

### What happened?

![image](https://github.com/halo-dev/halo/assets/51290945/adb538bf-2036-4b43-a8a1-53380612d8f2)

**Comment by ruibaby** [comment]
请按照 issue 模板填写完整的信息，包括环境信息、日志、浏览器日志等。

/close
