### ISSUE TITLE
【抖动】写文章出现屏幕抖动

### ISSUE THREAD

**Issue by QYG2297248353** [halo-dev/halo#5734]
### 系统信息

- 外部访问地址: https://blog.lifebus.top
- 启动时间: 2024-04-09 21:00
- 版本: 2.14.0
- 构建时间: 2024-04-01 11:15
- Git Commit: ae274db
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: PostgreSQL / 16.1
- 操作系统: Linux / 5.14.0-362.18.1.el9_3.x86_64
- 已激活主题: [Earth](https://github.com/halo-dev/theme-earth.git)
- 已启动插件:
  - [lightgallery.js 灯箱](https://github.com/halo-sigs/plugin-lightgallery)
  - [对象存储（Amazon S3 协议）](https://github.com/halo-dev/plugin-s3)
  - [StackEdit](https://github.com/halo-sigs/plugin-stackedit)
  - [Markdown / HTML 内容块](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [highlight.js 代码高亮](https://github.com/halo-sigs/plugin-highlightjs)
  - [ByteMD](https://github.com/ruibaby/plugin-bytemd)
  - [图库管理](https://github.com/halo-sigs/plugin-photos)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

写文章过程中，不知什么规则会出现屏幕抖动

### 附加信息

![halo](https://github.com/halo-dev/halo/assets/56836951/443f9463-9aed-4588-b482-575128b712e0)

**Comment by ruibaby** [comment]
hi @QYG2297248353 ，我这边似乎很难复现这个问题，目前猜测是因为元素拖动按钮的出现影响了内容整体高度，导致出现滚动条。

期望提供一下信息以供我们排查：

1. 原始内容
2. 浏览器型号和版本
3. 分辨率

**Comment by QYG2297248353** [comment]
确实是，应该是内容高度发生了变化，可能受到浏览器插件影响，我再次实验发现抖动是不见了，内容上确实是多一行就会出现垂直滚动条，我想这是随机事件，且难以复现

**Comment by QYG2297248353** [comment]
已升级，且无法复现，并且当时只要多一行就不会闪屏，不影响内容的撰写与发布
- 外部访问地址: https://blog.lifebus.top
- 启动时间: 2024-04-23 16:44
- 版本: 2.14.1
- 构建时间: 2024-04-23 14:50
- Git Commit: 7e829a5
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: PostgreSQL / 16.1
- 操作系统: Linux / 5.14.0-362.18.1.el9_3.x86_64
- 已激活主题: [Earth](https://github.com/halo-dev/theme-earth.git)
- 已启动插件:
  - [lightgallery.js 灯箱](https://github.com/halo-sigs/plugin-lightgallery)
  - [对象存储（Amazon S3 协议）](https://github.com/halo-dev/plugin-s3)
  - [StackEdit](https://github.com/halo-sigs/plugin-stackedit)
  - [Markdown / HTML 内容块](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [highlight.js 代码高亮](https://github.com/halo-sigs/plugin-highlightjs)
  - [ByteMD](https://github.com/ruibaby/plugin-bytemd)
  - [图库管理](https://github.com/halo-sigs/plugin-photos)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)

**Comment by ruibaby** [comment]
> 已升级，且无法复现，并且当时只要多一行就不会闪屏，不影响内容的撰写与发布

Okay，后续如果知道稳定复现的办法了，可以再提一个 issue。

**Comment by QYG2297248353** [comment]
好的
