### ISSUE TITLE
粘贴代码块的时候代码块格式丢失

### ISSUE THREAD

**Issue by ry0513** [halo-dev/halo#5736]
### 系统信息

- 启动时间: 2024-04-01 09:07
- 版本: 2.13.1
- 构建时间: 2024-03-06 17:40
- Git Commit: 9473261
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: MySQL Community Server - GPL / 8.2.0
- 操作系统: Linux / 6.6.13+bpo-cloud-amd64
- 已激活主题: [Earth](https://github.com/halo-dev/theme-earth.git)
- 已启动插件:
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)

### 使用的哪种方式运行？

Docker

### 发生了什么？

我在写文章，当直接粘贴代码的时候，会保留代码块格式，当我写完一段话后回车再粘贴代码会出现代码块格式消失的问题，这个问题在 tiptap 官方demo中也会复现，疑似 tiptap 的问题

### 附加信息

https://github.com/halo-dev/halo/assets/44745967/4b1ef8dc-60bf-47fd-b64d-23b0d6537d9e

**Comment by LIlGG** [comment]
感谢反馈，测试了一下，确实会出现这样的问题。

/kind bug
/area editor

**Comment by ry0513** [comment]
> 感谢反馈，测试结论，确实会出现这样的问题。
> 
> /kind bug /区域编辑器

可以参考一下这个
https://github.com/ueberdosis/tiptap/pull/3606

**Comment by LIlGG** [comment]
> 可以参考一下这个 [ueberdosis/tiptap#3606](https://github.com/ueberdosis/tiptap/pull/3606)

感谢，看了一下确实与这个问题相关。但此 PR 已经很久没有处理了，因此我会拷贝一份 `Code-Block` 相关代码并在 Halo 这边进行处理。

/assign
