### ISSUE TITLE
希望 FormKit 组件支持 taglist

### ISSUE THREAD

**Issue by liuchangfitcloud** [halo-dev/halo#5744]
### 你当前使用的版本

2.14

### 描述一下此特性

希望 FormKit 组件支持 taglist 来满足多选的下拉列表

### 附加信息

<img width="432" alt="image" src="https://github.com/halo-dev/halo/assets/44662176/89752293-1c61-42a9-8db1-5e882fa60c12">

**Comment by ruibaby** [comment]
已经在 2.19 中支持。

https://docs.halo.run/developer-guide/form-schema#select

/close
