### ISSUE TITLE
后台登录不跳转

### ISSUE THREAD

**Issue by zeng-yq** [halo-dev/halo#5747]
### 系统信息

控制台啥都没有
![image](https://github.com/halo-dev/halo/assets/51290945/6b5452c2-4be6-4354-8f8b-8b76f1679730)

### 使用的哪种方式运行？

Docker

### 发生了什么？

采用1Panel部署的，点击登录后没有反应，换过好几个浏览器，清理过浏览器换成，换过电脑登录，都不行，怀疑是1Panel的问题。服务器也重启过，还是无法解决。
![image](https://github.com/halo-dev/halo/assets/51290945/e0ab5bd4-b01f-43a6-a7aa-29ad3172bad4)

**Comment by zeng-yq** [comment]
有时候又会显示用户名和密码错误，我担保没有输错!
![image](https://github.com/halo-dev/halo/assets/51290945/209b6c54-de42-4169-a704-7be7b2127e1b)

此时的控制台是这样的：
![image](https://github.com/halo-dev/halo/assets/51290945/51f8aef4-9986-4fc1-9d0c-ae54a43efd0d)


![image](https://github.com/halo-dev/halo/assets/51290945/e97189f1-06f5-41db-8e06-0f24cd07a387)

**Comment by ruibaby** [comment]
建议先通过 IP 的形式测试一下 Halo 是否存在问题，这样能够更好的确认排查方向。

**Comment by ruibaby** [comment]
如果没有后续动态，我将关闭此 issue。后续有补充的话可以重新提交 issue 或者开启此 issue。

/close
