### ISSUE TITLE
用户编辑资料里的问题

### ISSUE THREAD

**Issue by chengzhongxue** [halo-dev/halo#5750]
### 系统信息

- 外部访问地址: https://moony.la
- 启动时间: 2024-04-18 22:18
- 版本: 2.14.0
- 构建时间: 2024-04-18 11:04
- Git Commit: 7ce48e9
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: PostgreSQL / 16.2
- 操作系统: Linux / 5.4.0-28-generic
- 已激活主题: [THYUU/星度](https://moony.la)
- 已启动插件:
  - [Netease Music](https://github.com/chengzhongxue/plugin-netease-music)
  - [SEO 工具集](https://github.com/f2ccloud/plugin-seo-tools)
  - [OAuth2 认证](https://github.com/halo-sigs/plugin-oauth2)
  - [highlight.js 代码高亮](https://github.com/halo-sigs/plugin-highlightjs)
  - [对象存储（Amazon S3 协议）](https://github.com/halo-dev/plugin-s3)
  - [豆瓣](https://github.com/chengzhongxue/plugin-douban)
  - [朋友圈](https://github.com/chengzhongxue/plugin-friends)
  - [Meilisearch](https://github.com/Rainsheep/halo-plugin-meilisearch)
  - [文章导入导出](https://jhacker.cn/2023/halo-plugin-export2doc)
  - [站点推送插件](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [图库管理](https://github.com/halo-sigs/plugin-photos)
  - [Docsme](https://github.com/f2ccloud/plugin-docsme)
  - [Umami](https://github.com/halo-sigs/plugin-umami)
  - AI 助手
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [Metrics Graph](https://github.com/guqing/plugin-metrics-graph)
  - [Vditor编辑器](https://github.com/justice2001/veditor-plugin)
  - 联系表单
  - [增强备份（Backup IMproved）](https://www.halo.run/store/apps/app-dHakX)
  - [社交 IAM 认证](https://www.halo.run/store/apps/app-IXZkJ)
  - [文章限制阅读 Pro](https://github.com/f2ccloud/plugin-restricted-reading-pro)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [Markdown / HTML 内容块](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)

### 使用的哪种方式运行？

Docker

### 发生了什么？

用户编辑资料里的 邮箱 手机号 修改前是不是要先验证一下之前的  手机号 邮箱 ，不然会出现一个问题，如果号被别人登录，那么别人就可以直接改掉你账号的邮箱 和手机号 这样是不是就会出现账号找不回来了

**Comment by ruibaby** [comment]
感谢反馈这个问题，可以考虑在个人中心修改邮箱的时候验证旧邮箱，如果无法进行验证，可以提示联系管理员。

/kind improvement
/area ui
/area core
/milestone 2.15.x

**Comment by wan92hen** [comment]
关闭/修改 MFA 是否也有必要发起一次 MFA 验证呢？

**Comment by ruibaby** [comment]
> 关闭/修改 MFA 是否也有必要发起一次 MFA 验证呢？

单独提交 issue 吧。

**Comment by guqing** [comment]
> /assign

Hi @mashirot , 首先感谢你的积极参与，但这个 issue 我已经完成的差不多了忘记 assign 了，由于这个的问题被 Halo 生态系统依赖需要紧急处理，因此不在交由社区处理，再次干倒抱歉🫡
