### ISSUE TITLE
刷新页面时控制台页面标题均显示为 `Halo`

### ISSUE THREAD

**Issue by wan92hen** [halo-dev/halo#5752]
### 系统信息

- 启动时间: 2024-04-18 23:12
- 版本: 2.15.0-SNAPSHOT
- 构建时间: 2024-04-18 18:26
- Git Commit: 2d8b15a
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: PostgreSQL / 16.1
- 操作系统: Linux / 5.15.0-91-generic
- 已激活主题: [LingXia](https://github.com/f2ccloud/theme-lingxia.git)
- 已启动插件:
  - 联系表单
  - [应用市场](https://github.com/halo-dev/plugin-app-store)
  - Reflect Halo 微信小程序配套插件
  - [增强备份（Backup IMproved）](https://halo.run/store/apps/app-dHakX)
  - [Docsme](https://github.com/f2ccloud/plugin-docsme)
  - [Markdown / HTML 内容块](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [图库管理](https://github.com/halo-sigs/plugin-photos)
  - [Sitemap](https://github.com/halo-sigs/plugin-sitemap)
  - [RSS](https://github.com/halo-sigs/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [highlight.js 代码高亮](https://github.com/halo-sigs/plugin-highlightjs)

### 使用的哪种方式运行？

Docker

### 发生了什么？

https://github.com/halo-dev/halo/pull/5696 中修改了登录页及控制台的页面标题显示内容，但是在刷新页面及页面加载的时候，标题还是会只显示 `Halo` 字样。建议刷新及页面加载的时候能够显示实际的页面标题，或者显示空标题。

**Comment by ruibaby** [comment]
/area ui
/kind improvement

可以考虑直接移除掉 Console 的 index.html 中的 title 文本。
