### ISSUE TITLE
隐性URL无法使用，显示连接被拒绝

### ISSUE THREAD

**Issue by Omoinemie** [halo-dev/halo#5758]
### 系统信息

隐性转发：用的是 iframe 框架技术、非重定向技术，效果为浏览器地址栏输入 http://www.dnspod.cn 回车，打开网站内容是目标地址 http://cloud.tencent.com/ 的网站内容，但地址栏显示当前地址 http://www.dnspod.cn

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

希望能够手动打开嵌套功能

**Comment by ruibaby** [comment]
可以参考：https://github.com/halo-dev/halo/pull/3612

/kind support

**Comment by Omoinemie** [comment]
> 可以参考：#3612
> 
> /kind support
s是这样吗？但是启动报错
ERROR: The Compose file './docker-compose.yaml' is invalid because:
Unsupported config option for services.halo: 'security'

配置文件
 docker-compose.yaml                                                           
version: "3"

services:
  halo:
    image: halohub/halo:2.14
    container_name: halo
    restart: on-failure:3
    network_mode: "host"
    volumes:
      - ./halo2:/root/.halo2
    command:
    security:
      frame-options:
        disabled: true
        mode: sameorigin

**Comment by ruibaby** [comment]
> ```yaml
> security:
>       frame-options:
>         disabled: true
>         mode: sameor
> ```

添加 command 参数：

```
- --halo.security.frame-options.disabled=true
```

**Comment by ruibaby** [comment]
由于此 issue 不再活跃，我将关闭此 issue，后续如果有需要，可以重新开启或者提交新的 issue。

/close
