### ISSUE TITLE
设置-通知设置中的邮件通知器对 STARTTLS 协议支持的建议

### ISSUE THREAD

**Issue by Un-dying** [halo-dev/halo#5759]
### 你当前使用的版本

2.14

### 描述一下此特性

现有邮件通知器仅支持TLS，SSL和不加密三种方式，但微软系邮箱（尤其是高校教育版、开发者版）所用邮箱均为 STARTTLS 加密方式。
由于微软高校教育版、开发者版邮箱在国内有相当广泛的受众，且这类邮箱搭配Azure可以完成一些自动化操作，希望在后续版本可以添加对该协议的支持，以便应用微软开发者邮箱进行通知。
顺颂春祺

### 附加信息

微软控制台已激活smtp服务

据[官网文档][ms]，微软的SMTP设置如下：
>SMTP 服务器名称：smtp-mail.outlook.com
>SMTP 端口：587
>SMTP 加密：STARTTLS

另有其他[微软QA][qa]认为可以使用TLS协议，但经本人测试无法使用
>服务器名称：smtp.office365.com 
>端口：587 
>加密方法：TLS

测试连接后Halo提示
>Failed to send email, please check your email configuration.

[ms]:https://support.microsoft.com/zh-cn/office/outlook-com-%E7%9A%84-pop-imap-%E5%92%8C-smtp-%E8%AE%BE%E7%BD%AE-d088b986-291d-42b8-9564-9c414e2aa040
[qa]:https://answers.microsoft.com/zh-hans/outlook_com/forum/all/%E6%88%91%E7%9A%84%E6%9C%8D%E5%8A%A1%E5%99%A8/0e903769-6342-4f4a-b72c-ab1868976eae

**Comment by mashirot** [comment]
> mail.smtp.starttls.enable: If true, enables the use of the STARTTLS command (if supported by the server) to switch the connection to a TLS-protected connection before issuing any login commands. If the server does not support STARTTLS, the connection continues without the use of TLS;  Note that an appropriate trust store must configured so that the client will trust the server's certificate.

```java
if ("TLS".equals(senderConfig.getEncryption())) {
    props.put("mail.smtp.starttls.enable", "true");
}
```

请检查你的配置，以及服务器与邮箱服务提供者之间的连接

**Comment by ruibaby** [comment]
https://github.com/halo-dev/halo/blob/cc7f2de805cf43cf862ce6eb4002fa211c44f00d/application/src/main/java/run/halo/app/notification/EmailSenderHelperImpl.java#L40

确实是有配置的。

**Comment by Un-dying** [comment]
> https://github.com/halo-dev/halo/blob/cc7f2de805cf43cf862ce6eb4002fa211c44f00d/application/src/main/java/run/halo/app/notification/EmailSenderHelperImpl.java#L40
> 
> 确实是有配置的。

重新部署后测试成功，感谢您的解答！多有叨扰。
