### ISSUE TITLE
feat: 希望可以在附件区域增加文件夹功能

### ISSUE THREAD

**Issue by GeneralBBG** [halo-dev/halo#577]
## 概述
附件区域增加文件夹功能，对用户上传的文件进行分类

## 动机
编写一篇 Blog 时，halo 对于在剪贴板的图片导入支持的很好，但是默认上传到附件库会导致与用户主动上传的背景图片等资源堆放在一起

然后需要找这些背景图片的时候就异常麻烦

所以希望能加入文件夹功能，方便管理

最好还能在编写文章的页面对粘贴的图片有可选择的保存路径（也就是文件夹）

**Comment by JohnNiang** [comment]
您这个需求已经在计划中。

**Comment by JohnNiang** [comment]
Duplicated：https://github.com/halo-dev/halo/issues/427

**Comment by LainNetWork** [comment]
支持，这个功能很有必要
