### ISSUE TITLE
迁移halo后许可证失效后在halo.run后台删除了绑定设备后点击重新激活仍会提示许可证无效

### ISSUE THREAD

**Issue by 52lemon6** [halo-dev/halo#5779]
### 系统信息

- 外部访问地址: https://oniya.cn/
- 启动时间: 2024-04-21 18:28
- 版本: 2.14.0
- 构建时间: 2024-04-18 11:04
- Git Commit: 7ce48e9
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: 20200531 / 5.7.18-cynos-log
- 操作系统: Linux / 6.1.0-13-amd64
- 已激活主题: [Theme Joe3](https://github.com/jiewenhuang/halo-theme-joe3.0)
- 已启动插件:
  - [朋友圈](https://github.com/chengzhongxue/plugin-friends)
  - [OAuth2 认证](https://github.com/halo-sigs/plugin-oauth2)
  - [highlight.js 代码高亮](https://github.com/halo-sigs/plugin-highlightjs)
  - [Metrics Graph](https://github.com/guqing/plugin-metrics-graph)
  - [Markdown / HTML 内容块](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [Vditor编辑器](https://github.com/justice2001/veditor-plugin)
  - [Willow Markdown 编辑器](https://github.com/guqing/willow-mde)
  - [图库管理](https://github.com/halo-sigs/plugin-photos)
  - [文章导入导出](https://jhacker.cn/2023/halo-plugin-export2doc)
  - AI 助手
  - [Docsme](https://github.com/f2ccloud/plugin-docsme)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [站点推送插件](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [增强备份（Backup IMproved）](https://www.halo.run/store/apps/app-dHakX)
  - [文章限制阅读 Pro](https://github.com/f2ccloud/plugin-restricted-reading-pro)
  - [对象存储（Amazon S3 协议）](https://github.com/halo-dev/plugin-s3)
  - [站点迁移](https://github.com/halo-sigs/plugin-migrate)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

迁移halo后许可证失效后在halo.run后台删除了绑定设备后点击重新激活仍会提示UnexpectedState:Refuse to start plugin due to invalid license.需要取消激活后然后再激活才能重新激活

**Comment by ruibaby** [comment]
/area plugin
/kind improvement

感谢反馈。这个问题无法在此仓库解决，已经在应用市场插件中提交相同的 issue，优化后会关闭此 issue。

**Comment by ruibaby** [comment]
应用市场插件最新版本（1.2.0）已支持：https://www.halo.run/store/apps/app-VYJbF?tab=releases

/close
