### ISSUE TITLE
希望选许可证的时候可以展示哪些许可证已经用了，哪些许可证还没用

### ISSUE THREAD

**Issue by 52lemon6** [halo-dev/halo#5781]
### 你当前使用的版本

2.14.0

### 描述一下此特性

希望选许可证的时候可以展示哪些许可证已经用了，哪些许可证还没用
需求场景：在有多个插件license的时候选license的时候都不知道哪些license用了哪些没用

**Comment by ruibaby** [comment]
/area plugin
/kind improvement

这个问题无法在此仓库解决，已经在应用市场插件中提交相同的 issue，优化后会关闭此 issue。

**Comment by ruibaby** [comment]
应用市场插件最新版本（1.2.0）已支持：https://www.halo.run/store/apps/app-VYJbF?tab=releases

/close
