### ISSUE TITLE
主题的表单定义里能否支持 Range组件

### ISSUE THREAD

**Issue by chengzhongxue** [halo-dev/halo#5782]
### 你当前使用的版本

2.14.0

### 描述一下此特性

![image](https://github.com/halo-dev/halo/assets/89380218/f8d7708f-20e3-466d-b661-823c625acb33)

**Comment by ruibaby** [comment]
range 属于原生输入框，是支持的，请问是遇到什么问题了吗？

**Comment by chengzhongxue** [comment]
我知道怎么用了，我看到文档没有写还以为没有
