### ISSUE TITLE
默认编辑器插入网页，文本框无法填写

### ISSUE THREAD

**Issue by ShermanQ** [halo-dev/halo#5785]
### 系统信息

- 启动时间: 2024-04-23 23:06
- 版本: 2.14.1
- 构建时间: 2024-04-23 14:50
- Git Commit: 7e829a5
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: MySQL Community Server - GPL / 8.0.31
- 操作系统: Linux / 5.15.0-1030-oracle
- 已激活主题: [Hao](https://github.com/liuzhihang/halo-theme-hao)
- 已启动插件:
  - [Umami](https://github.com/halo-sigs/plugin-umami)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [StackEdit](https://github.com/halo-sigs/plugin-stackedit)
  - [评论组件](https://github.com/halo-sigs/plugin-comment-widget)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [lightgallery.js 灯箱](https://github.com/halo-sigs/plugin-lightgallery)
  - [highlight.js 代码高亮](https://github.com/halo-sigs/plugin-highlightjs)

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

默认编辑器插入网页，文本框无法填写，自动清空内容

### 相关日志输出

```shell
ncaught RangeError: Index 1 out of range for <paragraph(iframe)>
    at $.child (halo-rich-text-editor.iife.6df4e5a1.js:17:35990)
    at $.findIndex (halo-rich-text-editor.iife.6df4e5a1.js:17:36505)
    at Ep.nodeAt (halo-rich-text-editor.iife.6df4e5a1.js:17:47711)
    at zv (halo-rich-text-editor.iife.6df4e5a1.js:20:23009)
    at Wm.setNodeMarkup (halo-rich-text-editor.iife.6df4e5a1.js:20:36405)
    at halo-rich-text-editor.iife.6df4e5a1.js:106:8518
    at halo-rich-text-editor.iife.6df4e5a1.js:28:1520
    at Object.command (halo-rich-text-editor.iife.6df4e5a1.js:25:11942)
    at XM.updateAttributes (halo-rich-text-editor.iife.6df4e5a1.js:106:8468)
    at Proxy.updateAttributes (halo-rich-text-editor.iife.6df4e5a1.js:106:58500)
```

**Comment by LIlGG** [comment]
我在本地无法复现此问题，希望能提供更多的信息来帮助我排查此问题，例如详细描述一下你的操作过程或者提供一个视频。

**Comment by LIlGG** [comment]
Hi, @ShermanQ 我按照你上述的操作之后本地仍旧没有复现。

操作视频如下：

![Kapture 2024-04-24 at 11 24 31](https://github.com/halo-dev/halo/assets/31335418/bd17d9b4-7d21-4fff-acff-edfcea08da99)

我所使用的测试环境如下：

- 外部访问地址: https://lixingyong.com/
- 启动时间: 2024-04-12 18:41
- 版本: 2.14.0
- 构建时间: 2024-04-01 11:15
- Git Commit: ae274db
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: MySQL Community Server - GPL / 8.0.33
- 操作系统: Linux / 5.4.0-42-generic
- 已激活主题: [Sakura](https://github.com/LIlGG/halo-theme-sakura.git)
- 已启动插件:
  - [SEO 工具集](https://github.com/f2ccloud/plugin-seo-tools)
  - AI 助手
  - [Metrics Graph](https://github.com/guqing/plugin-metrics-graph)
  - [Markdown / HTML 内容块](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [Willow Markdown 编辑器](https://github.com/guqing/willow-mde)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)
  - [增强备份（Backup IMproved）](https://halo.run/store/apps/app-dHakX)
  - [OAuth2 认证](https://github.com/halo-sigs/plugin-oauth2)
  - [StackEdit](https://github.com/halo-sigs/plugin-stackedit)
  - [live2d 看板娘](https://github.com/LIlGG/plugin-live2d)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [站点迁移](https://github.com/halo-sigs/plugin-migrate)
  - [对象存储（Amazon S3 协议）](https://github.com/halo-dev/plugin-s3)
  - [ByteMD](https://github.com/ruibaby/plugin-bytemd)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [图库管理](https://github.com/halo-sigs/plugin-photos)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)

如果我有什么遗漏，欢迎补充。

**Comment by LIlGG** [comment]
你这边浏览器版本是多少？可以将浏览器插件停止之后再进行尝试，另外可能还需要补充你的 Halo 概览信息。

**Comment by ShermanQ** [comment]
搞定了，是插件引起的，感谢。
