### ISSUE TITLE
账户认证的许可证频繁失败问题

### ISSUE THREAD

**Issue by meng-plus** [halo-dev/halo#5786]
### 系统信息

- 外部访问地址: https://mengplus.top
- 启动时间: 2024-04-22 07:58
- 版本: 2.14.0
- 构建时间: 2024-04-18 11:04
- Git Commit: 7ce48e9
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: MySQL Community Server - GPL / 8.2.0
- 操作系统: Linux / 5.15.0-105-generic
- 已激活主题: [Hao](https://github.com/chengzhongxue/halo-theme-hao)
- 已启动插件:
  - [图库管理](https://github.com/halo-sigs/plugin-photos)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [ByteMD](https://github.com/ruibaby/plugin-bytemd)
  - [live2d 看板娘](https://github.com/LIlGG/plugin-live2d)
  - [文章导入导出](https://jhacker.cn/2023/halo-plugin-export2doc)
  - [highlight.js 代码高亮](https://github.com/halo-sigs/plugin-highlightjs)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)

### 使用的哪种方式运行？

Docker

### 发生了什么？

正常激活的 频繁发现许可证认证失败
点重新激活也不行，要先取消激活 再激活才能恢复
![image](https://github.com/halo-dev/halo/assets/37764731/cb2f3dbe-d042-472f-8a23-3e810750a560)

**Comment by JohnNiang** [comment]
Hi @meng-plus ,近期我们更新了官网，应该已经解决了这个问题，建议再观察一下。

/triage needs-information

**Comment by ruibaby** [comment]
目前没有再收到类似反馈，所以我将关闭此 issue。

/close
