### ISSUE TITLE
halo 2.14.1版本 许可证管理功能异常

### ISSUE THREAD

**Issue by TIkc9** [halo-dev/halo#5797]
### 系统信息

- 外部访问地址: http://localhost:8080
- 启动时间: 2024-04-25 10:45
- 版本: 2.14.0
- 构建时间: 2024-04-18 11:04
- Git Commit: 7ce48e9
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: MySQL Community Server (GPL) / 5.7.44
- 操作系统: Linux / 6.1.0-10-amd64
- 已激活主题: [Earth](https://github.com/halo-dev/theme-earth.git)
- 已启动插件:
  - [通知我](https://github.com/monyuan/notify-me)
  - AI 助手
  - [Markdown / HTML 内容块](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [文章导入导出](https://jhacker.cn/2023/halo-plugin-export2doc)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)

### 使用的哪种方式运行？

Docker

### 发生了什么？

许可证管理一直转圈

### 相关日志输出

```shell
Extension vlalphal/Secret/halo run app store pat secret was not found.
```

### 附加信息

<img width="442" alt="faed05016b4a57e3bd96da57b0ecdba" src="https://github.com/halo-dev/halo/assets/17921262/a55795e7-5211-4306-ab0d-6c79820231b5">

<img width="325" alt="01b947762f16e6774a72b318dfe4ddb" src="https://github.com/halo-dev/halo/assets/17921262/536209bf-b27d-436b-ac1d-2be8ac20d4e3">

**Comment by ruibaby** [comment]
需要先在应用市场的插件设置中填写个人令牌。

<img width="712" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/3519c536-33f2-47cd-8f9b-f91714472527">

/kind support

**Comment by ruibaby** [comment]
如果没有后续动态，我将关闭此 issue。后续有补充的话可以重新提交 issue 或者开启此 issue。

/close
