### ISSUE TITLE
静态文件缓存问题

### ISSUE THREAD

**Issue by LiuXIn011** [halo-dev/halo#5798]
### 描述一下此特性

在模板中引用的CSS、JS文件都有缓存问题，导致部分bug在修改完成后，不能及时同步到客户端。在PC端需要shift+F5强制刷新浏览器；移动端就需要更多复杂的操作清除缓存。

**Comment by ruibaby** [comment]
感谢反馈此问题，但为静态资源添加缓存策略是一个常规的做法，并且为了能够及时更新静态资源，我们为主题和插件的的静态资源添加了版本号参数，以便在更新之后可以加载新的静态资源。目前你的操作过程是什么呢，是否有重新创建主题版本？

此外，如果一定要禁用静态资源缓存，你可以在反向代理中为静态资源设置 `Cache Control`，或者为 Halo 添加启动参数以禁用缓存：

```
--spring.web.resources.cache.cachecontrol.no-cache=true
```

/kind support

**Comment by ruibaby** [comment]
如果没有后续动态，我将关闭此 issue。后续有补充的话可以重新提交 issue 或者开启此 issue。

/close
