### ISSUE TITLE
如果有多个用户来在平台发表博客，在主页中如何区分呢？

### ISSUE THREAD

**Issue by txbxxx** [halo-dev/halo#5799]
### 你当前使用的版本

docker halo 2

### 描述一下此特性

如果有多个用户都在使用这个自己搭建的博客系统，然后都发表了博客，只能拿通过分类和标签来区分这些博客的发表吗？

**Comment by ruibaby** [comment]
如果没有后续动态，我将关闭此 issue。后续有补充的话可以重新提交 issue 或者开启此 issue。

/close
