### ISSUE TITLE
注册页面优化

### ISSUE THREAD

**Issue by lan-yonghui** [halo-dev/halo#5801]
### 系统信息

- 外部访问地址: https://lan.1tian.cc
- 启动时间: 2024-04-23 20:00
- 版本: 2.14.0
- 构建时间: 2024-04-01 11:15
- Git Commit: ae274db
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: MySQL Community Server (GPL) / 5.6.51
- 操作系统: Linux / 3.10.0-1160.108.1.el7.x86_64
- 已激活主题: [Earth](https://github.com/halo-dev/theme-earth.git)
- 已启动插件:
  - [社交 IAM 认证](https://www.halo.run/store/apps/app-IXZkJ)
  - [OAuth2 认证](https://github.com/halo-sigs/plugin-oauth2)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

注册页面开启三方登陆后，页面有点偏下，出现了滚动条，头部预留空间可以减少点儿！
注册页面表单输入框之间的间隔不统一

### 附加信息

![WechatIMG282](https://github.com/halo-dev/halo/assets/81747598/05d7a835-1836-4add-9c7c-e8bd9dd54ca9)

**Comment by ruibaby** [comment]
感谢反馈此问题，目前这样设计是为了和登录表单保持一致，防止切换到注册页面的时候表单位置不一致，但考虑到注册表单的元素较多，可以考虑优化一下。

/area ui
/kind improvement
