### ISSUE TITLE
请求新增文本展示类 FormKit 组件

### ISSUE THREAD

**Issue by ichenhe** [halo-dev/halo#5802]
### 你当前使用的版本

v2.14.0

### 描述一下此特性

插件经常有在配置页面中展示关键提示/警告信息的需求，毕竟大部分用户都不愿意认真阅读文档。目前的解决方案是随意选择一个占位组件，非常丑陋，包括官方的 S3 插件也是这么干的。

建议：

- 提供一个组件专门展示信息。
- 尽量支持加粗，斜体等简易样式。
- 最好能支持超链接跳转，便于引导用户进一步阅读使用指南。
- 可以考虑使用 Markdown 语法的子集，或 html 标签。

### 附加信息

丑陋的方案：

![](https://github.com/halo-dev/halo/assets/10266066/35c28966-f9d3-4595-b57a-5ad6b00e7ccc)

**Comment by ruibaby** [comment]
感谢反馈此问题，目前我们使用的 FormKit 是支持使用 el 的，也就是渲染 html 文本，可以参考：https://formkit.com/essentials/schema

对象存储这个插件确实是以前的疏忽，后续可以改一下，可以向 https://github.com/halo-dev/plugin-s3 提交一个 issue。

**Comment by ichenhe** [comment]
感谢解答
