### ISSUE TITLE
搜索框部分文章搜索不出

### ISSUE THREAD

**Issue by GD2021** [halo-dev/halo#5805]
### 系统信息

- 外部访问地址: https://ishort.ink/8zbZ
- 启动时间: 2024-04-19 22:37
- 版本: 2.14.0
- 构建时间: 2024-04-18 11:04
- Git Commit: 7ce48e9
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: MySQL Community Server - GPL / 8.2.0
- 操作系统: Linux / 5.10.0-28-amd64
- 已激活主题: [Theme Fluid](https://github.com/chengzhongxue/halo-theme-fluid)
- 已启动插件:
  - [Willow Markdown 编辑器](https://github.com/guqing/willow-mde)
  - [文章导入导出](https://jhacker.cn/2023/halo-plugin-export2doc)
  - [highlight.js 代码高亮](https://github.com/halo-sigs/plugin-highlightjs)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)

### 使用的哪种方式运行？

使用1panel应用商店安装，Docker运行

### 发生了什么？

搜索框搜索部分文章，搜索不到？
刷新搜索引擎也没用

比如：你搜索“懒人配置大全” https://ishort.ink/yEj6，搜索不到

**Comment by ruibaby** [comment]
感谢反馈此问题，目前内置的搜索引擎的搜索策略确实有优化的空间，当前如果要精准搜索标题的话，可能需要在关键字前加上 `title:`，比如：

<img width="668" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/a1058f1c-2143-438d-9245-e68e2b8b6b76">

虽然目前支持这样去搜索，但搜索组件还未对其进行操作指引。如果你现在想获取更好的搜索体验，建议先使用外挂 Meilisearch，参考：https://www.halo.run/store/apps/app-yJlEz

**Comment by GD2021** [comment]
好
