### ISSUE TITLE
请对logout页面优化

### ISSUE THREAD

**Issue by byteforgecn** [halo-dev/halo#5806]
### 你当前使用的版本

2.14

### 描述一下此特性

![image](https://github.com/halo-dev/halo/assets/144019326/e163b174-9a0c-4b20-b72d-a9c3074c9d2f)
https://www.halo.run/logout

### 附加信息

目前应该是spring security的默认页面, 多语种以及页面美观性存在割裂体验
在首页点注销会进入此页面, 后台的退出登录弹窗后会直接退出
我认为应该统一ui效果

**Comment by ruibaby** [comment]
感谢反馈此问题，你是期望 Halo 官网对其进行优化吗？还是对 Halo 本身进行优化。

因为这个问题实际上可以完全在主题侧（调用方）进行解决，默认 GET /logout 是一个退出登录页面，但同时这个路由也支持直接异步调用 POST /logout，所以主题完全可以对其进行定制。

不过，后续仍然可以对其进行样式统一，但我建议先完成：https://github.com/halo-dev/halo/issues/5214

**Comment by byteforgecn** [comment]
目前我使用的是默认主题。我希望halo程序以及默认主题优化，我个人看法时不需要logout页面，就想管理后台那样弹个窗确认一下就很美观。而且我发现spring security的默认logout页面可能存在国外服务器的css资源，导致国内用户点击注销后，出现长达十几秒的白屏加载css文件，如果此时触发浏览器的中断加载，会出现我截图中没有任何样式的原生按钮，会很影响国内用户体验
---- 回复的原邮件 ----
发件人 Ryan ***@***.***> 日期 2024年04月27日 21:35 收件人 ***@***.***> 抄送至 ***@***.***>***@***.***> 主题 Re: [halo-dev/halo] 请对logout页面优化 (Issue #5806) 
感谢反馈此问题，你是期望 Halo 官网对其进行优化吗？还是对 Halo 本身进行优化。
因为这个问题实际上可以完全在主题侧（调用方）进行解决，默认 GET /logout 是一个退出登录页面，但同时这个路由也支持直接异步调用 POST /logout，所以主题完全可以对其进行定制。
不过，后续仍然可以对其进行样式统一，但我建议先完成：#5214

**Comment by ruibaby** [comment]
@byteforgecn 

> 目前我使用的是默认主题。我希望halo程序以及默认主题优化，我个人看法时不需要logout页面，就想管理后台那样弹个窗确认一下就很美观。而且我发现spring security的默认logout页面可能存在国外服务器的css资源，导致国内用户点击注销后，出现长达十几秒的白屏加载css文件，十秒后会请求失败，会出现我截图中没有任何样式的原生按钮，这十几秒的等待时间会很影响国内用户体验

Okay，默认主题已经有了一个相关的 PR：https://github.com/halo-dev/theme-earth/pull/143

将在默认主题的下个版本优化这个问题。

**Comment by QYG2297248353** [comment]
不是退出登录 单独一个页面，要么美化一下，要么搞个弹窗都比这个 一段英文强多了吧，不行不行，这个页面丑的无法接受！

其他页面都是高大上，最后退出这么丑，谁能受得了

![image](https://github.com/user-attachments/assets/ad166bad-bb3c-426a-98cf-23a759e121f8)

**Comment by LIlGG** [comment]
> 不是退出登录 单独一个页面，要么美化一下，要么搞个弹窗都比这个 一段英文强多了吧，不行不行，这个页面丑的无法接受！
> 
> 其他页面都是高大上，最后退出这么丑，谁能受得了
>

请详细阅读 https://github.com/halo-dev/halo/issues/5806#issuecomment-2080675475 ，如果你有想法，完全可以帮助我们更好的完成这件事而不是去抱怨，抱怨并不会改进这件事情哪怕一点。

如果你有能力编写代码，那么欢迎提交 PR，如果你有更好的想法，那么欢迎讨论。

**Comment by QYG2297248353** [comment]
> 请详细阅读 [#5806 (comment)](https://github.com/halo-dev/halo/issues/5806#issuecomment-2080675475) ，如果你有想法，完全可以帮助我们更好的完成这件事而不是去抱怨，抱怨并不会改进这件事情哪怕一点。

我认为你完全理解错了，我反馈的是问题，是感受，既然软件已经推出，发布了。多少不应该是是个 `毛坯房` 的状态。

> Okay，默认主题已经有了一个相关的 PR：https://github.com/halo-dev/theme-earth/pull/143

>
> 将在默认主题的下个版本优化这个问题。

我比较了这两个前后的状态，仅仅是 登出按钮 有了变化。

既然做了一点修改，至少 英文顺便也换了。要么这个页面暂时就不要上线，直接退出。

![image](https://github.com/user-attachments/assets/2356c2bb-4f07-4ae5-a8f9-eb5e56ff8067)

**Comment by ruibaby** [comment]
@QYG2297248353 使用 https://github.com/halo-dev/theme-earth/pull/159

**Comment by JohnNiang** [comment]
这里我推荐允许主题自定义 `/logout` 路由对应的模板，可参考错误模板。

**Comment by ruibaby** [comment]
> 这里我推荐允许主题自定义 `/logout` 路由对应的模板，可参考错误模板。

那最好是先完成 https://github.com/halo-dev/halo/issues/5214
