### ISSUE TITLE
登录时使用 MFA TOTP 两步验证时使用工具自动填充

### ISSUE THREAD

**Issue by vicat47** [halo-dev/halo#5812]
### 你当前使用的版本

2.14.1

### 描述一下此特性

我使用 1password 作为密码管理工具进行密码管理，在其中有登记了 mfa totp 的账号，现在无法自动填充。
在 1panel 中该工具是可以自动填充的，暂不清楚为什么 halo 这边没法填充。猜测与 input 的类型有关系

**Comment by ruibaby** [comment]
我们在 https://github.com/halo-dev/halo/releases/tag/v2.20.0-rc.1 重构了 TOTP 的页面，并为输入框添加了 `autocomplete="one-time-code"`，有兴趣请帮我们测试一下是否已经解决了此问题。

**Comment by ruibaby** [comment]
Halo 2.20 已发布，建议升级之后再试试，如果仍然有问题，可以重新提交 issue。

/close
