### ISSUE TITLE
社交 IAM 认证 插件身份认证排序混乱

### ISSUE THREAD

**Issue by hjdyzy** [halo-dev/halo#5813]
### 系统信息

2.14.1

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

在 系统 > 插件菜单中，把 [社交 IAM 认证] 插件关闭再打开后，身份认证里面的选项排序就会发生变化，这个直接会影响网站登录页面的第三方登录排序，影响使用了；是否可以支持自定义排序？

### 附加信息

![image](https://github.com/halo-dev/halo/assets/71299416/c7013844-54cb-4575-b3c1-34a1e8a51fe7)
![image](https://github.com/halo-dev/halo/assets/71299416/5b80616e-4921-46f4-ac24-d6ed3c276e01)

**Comment by guqing** [comment]
/kind improvement
/area core

可以考虑为 AuthProvider 增加 priority 字段用于排序

**Comment by guqing** [comment]
不用 close，目前要增加这个字段还需要 halo 添加然后由插件自己适配，因此我将 reopen 它
