### ISSUE TITLE
http://halo.ryanc.cc文件路径失效

### ISSUE THREAD

**Issue by liuurick** [halo-dev/halo#582]
前辈，教程指令有问题：
`curl -o ~/.halo/application.yaml --create-dirs http://halo.ryanc.cc/config/application-template.yaml
`
显示问题：
```
<Error>
<Code>UserDisable</Code>
<Message>UserDisable</Message>
<RequestId>5E4E424377491D30320CEC6E</RequestId>
<HostId>halo.ryanc.cc</HostId>
</Error>

```

**Comment by ruibaby** [comment]
刚刚看了下是因为 oss 流量用完欠费了，刚刚已经续上。

抱歉没有关注到。

**Comment by panxiaoguang** [comment]
您好，好像又没法下载了

**Comment by JohnNiang** [comment]
> 您好，好像又没法下载了

https://halo.nova.moe/
