### ISSUE TITLE
支持通用 OAuth 和反向代理认证

### ISSUE THREAD

**Issue by hhhguany** [halo-dev/halo#5824]
### 你当前使用的版本

2.14.1

### 描述一下此特性

我是一位购买了专业版的用户，我了解知道 halo 提供了 IAM 和 OAuth 插件来增加外部认证能力，但是这些插件都必须与公开的认证系统结合，不提供通用配置能力（对接自建 IdP）。希望在专业版中加入对通用 OAuth 或者反向代理认证的支持，这也是专业用户所需要的。

**Comment by ruibaby** [comment]
目前你提到的 IAM 插件是支持自建认证提供商的：

<img width="1660" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/fd14fe5b-b188-414d-a622-c532a0643404">

现在是遇到什么问题了吗？

**Comment by hhhguany** [comment]
好的，谢谢！
