### ISSUE TITLE
halo2 settings.yaml 改变后，后台主题设置里面没改变

### ISSUE THREAD

**Issue by qiushaocloud** [halo-dev/halo#5833]
### 系统信息

- 外部访问地址: https://www.qiushaocloud.top/
- 启动时间: 2024-04-29 23:45
- 版本: 2.15.0-rc.1
- 构建时间: 2024-04-26 18:39
- Git Commit: 8abae05
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: MySQL Community Server - GPL / 8.2.0
- 操作系统: Linux / 5.15.0-86-generic
- 已激活主题: [Theme Joe3](https://github.com/jiewenhuang/halo-theme-joe3.0)
- 已启动插件:
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [WordPress导入](https://github.com/wan92hen/plugin-wordpress)
  - [阿里云 OSS](https://github.com/halo-sigs/plugin-alioss)
  - [又拍云 OSS](https://github.com/AirboZH/plugin-uposs)
  - [追番插件](https://github.com/Roozenlz/plugin-bilibili-bangumi)
  - [ByteMD](https://github.com/ruibaby/plugin-bytemd)
  - [StackEdit](https://github.com/halo-sigs/plugin-stackedit)
  - [ToolBench](https://github.com/DioxideCN/Tool-Bench)
  - [Unsplash](https://github.com/halo-sigs/plugin-unsplash)
  - [Umami](https://github.com/halo-sigs/plugin-umami)
  - [通知我](https://github.com/monyuan/notify-me)
  - AI 助手
  - [KaTeX](https://github.com/halo-sigs/plugin-katex)
  - [文本绘图](https://github.com/halo-sigs/plugin-text-diagram)
  - [Metrics Graph](https://github.com/guqing/plugin-metrics-graph)
  - [Markdown / HTML 内容块](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [文章导入导出](https://jhacker.cn/2023/halo-plugin-export2doc)
  - [Willow Markdown 编辑器](https://github.com/guqing/willow-mde)
  - [highlight.js 代码高亮](https://github.com/halo-sigs/plugin-highlightjs)
  - [OAuth2 认证](https://github.com/halo-sigs/plugin-oauth2)
  - [朋友圈](https://github.com/chengzhongxue/plugin-friends)
  - [lightgallery.js 灯箱](https://github.com/halo-sigs/plugin-lightgallery)
  - [Docsme](https://github.com/f2ccloud/plugin-docsme)
  - [Vditor编辑器](https://github.com/justice2001/veditor-plugin)
  - [豆瓣](https://github.com/chengzhongxue/plugin-douban)
  - [对象存储（Amazon S3 协议）](https://github.com/halo-dev/plugin-s3)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [图库管理](https://github.com/halo-sigs/plugin-photos)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [站点迁移](https://github.com/halo-sigs/plugin-migrate)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)

### 使用的哪种方式运行？

Docker

### 发生了什么？

我修改了主题的 settings.yaml 后，在后台主题没见改变，我应该怎么做才能改变，希望提供下教程

**Comment by lan-yonghui** [comment]
可以看下文档: [halo 主题开发](https://docs.halo.run/category/%E4%B8%BB%E9%A2%98%E5%BC%80%E5%8F%91)

**Comment by ruibaby** [comment]
目前修改主题配置需要手动重载一下。参考：https://docs.halo.run/developer-guide/theme/settings#%E6%9B%B4%E6%96%B0%E9%85%8D%E7%BD%AE

**Comment by ruibaby** [comment]
如果没有后续动态，我将关闭此 issue。后续有补充的话可以重新提交 issue 或者开启此 issue。

/close
