### ISSUE TITLE
支持系统级评论插件

### ISSUE THREAD

**Issue by ichenhe** [halo-dev/halo#5835]
### 你当前使用的版本

2.14

### 描述一下此特性

目前看起来评论系统与主应用绑定，没有插件化。开发者文档有两个相关的扩展点：
- 评论主体：只能显示评论所属的页面
- 评论组件：只能控制 UI 显示

希望实现的功能是整个评论数据的插件化，就像存储后端那样。Halo 自带的评论不一定完全满足需求，例如：匿名评论，邮箱验证码直接登录，Halo 未支持的第三方登录，以及其他奇奇怪怪的需求。

除此之外，很多静态博客常使用外部评论系统，目前难以快速导入到 Halo，而且个人也不太喜欢把内容与建站程序捆绑（评论也是内容的一部分）。

从架构层面，内容格式与来源的多样性也比较重要。例如文章内容就通过编辑器插件提供了扩展能力。

---

部分开发者在主题层面实现了第三方评论的支持，但这样不具有普适性，同时也无法整合到 Halo 后台进行管理。

---

这个需求可能的确有一定的难度，牵扯到 Halo 的用户系统，权限管理等等问题。不知道官方是否有其他统一接入外部评论系统更好的方案？

**Comment by ruibaby** [comment]
感谢提出这些问题。

> 希望实现的功能是整个评论数据的插件化，就像存储后端那样。

这确实有一定难度的，但理论上可行。目主要考虑到其他插件可能也会会使用评论模型，比如[瞬间](https://github.com/halo-sigs/plugin-moments)，所以评论内置到 Halo 可能会更好。

> 不知道官方是否有其他统一接入外部评论系统更好的方案？

如果只是考虑用插件来集成三方评论系统的话，目前应该是可行的，我也是更加推荐用单独的插件来集成评论系统，而不是在主题中提供。

目前在主题中我们提供了一个 [<halo:comment />](https://docs.halo.run/developer-guide/theme/template-tag#halocomment) 标签，用于嵌入评论组件，然后就可以在插件中来实现这个标签。相关资料：

1. https://docs.halo.run/developer-guide/theme/template-tag#halocomment
2. https://github.com/halo-dev/plugin-comment-widget/blob/220219dd7f4bc71078662f945521105d8e6cbfae/src/main/java/run/halo/comment/widget/DefaultCommentWidget.java#L35

> 同时也无法整合到 Halo 后台进行管理。

集成三方评论系统之后，可以考虑把三方评论系统的管理 url 添加到 Console 侧边菜单。

**Comment by ichenhe** [comment]
> 目前在主题中我们提供了一个 [<halo:comment />](https://docs.halo.run/developer-guide/theme/template-tag#halocomment) 标签，用于嵌入评论组件

若有多个插件实现了此组件，怎么选择到底使用哪个插件呢？没找到选项。

> 集成三方评论系统之后，可以考虑把三方评论系统的管理 url 添加到 Console 侧边菜单。

我的意思不是说集成管理 UI，而是评论仅仅作为数据，管理 UI 还是使用 Halo 官方的。这样体验更一致，也预防分裂成 WordPress 那样乱七八糟的实现。

**Comment by ruibaby** [comment]
> 若有多个插件实现了此组件，怎么选择到底使用哪个插件呢？没找到选项。

相关 issue：<https://github.com/halo-dev/halo/issues/3206>，这是当前还未实现的一个功能，目前底层实际上是支持插件实现同一个扩展点，也有优先级和选择实现插件的功能，但我们的期望是做一个类似于 **集成** 的管理功能，专门用于调整插件的优先级和选择具体实现的插件（比如评论，只需要选择一个，类似的还有搜索引擎）。目前如果实现了集成三方评论的插件，那可能只能让用户停用默认的评论插件。

> 而且这样的实现没法很好地与主题兼容，后果就是往往一个评论插件只能和1个主题搭配。

所以我才说所有三方插件应该都和默认的插件一样，实现 `<halo:comment />` 自定义标签，比如 disqus 这种根据页面 url 来做页面标识的评论系统，可以利用在 `<halo:comment />` 标签上的 name、kind、group 来确定一个 url，或者根据 context（我不确定是否可行）。因为基本上主题都会实现 `<halo:comment />`，所以不会造成一个评论插件只能给一个主题用的情况。

> 最保守的，也是兼容性最强的。Halo 定义评论数据的格式，插件作为提供者。评论 UI 使用官方实现，但可以提供几个 slot 用于让插件添加一些小按钮，这些按钮的样式默认由官方插件统一管理（类似 FormKit）。这种模式开发的评论插件可以无缝兼容大部分主题。

> 我的意思不是说集成管理 UI，而是插件仅仅作为评论数据的 Provider，管理 UI 还是使用 Halo 官方的。这样体验更一致，也预防分裂成 WordPress 那样乱七八糟的实现。

这种方式如果是要集成三方平台的评论系统，比如 disqus，twikoo 等，感觉会有点困难，因为数据格式差异可能会比较大。

感谢参与这个问题的讨论，实际上最初我们的设想就是考虑了集成的情况，但后续类似需求的反馈确实比较少，基本都是主题自行集成了三方评论。

**Comment by ichenhe** [comment]
感谢回复，评论的插件化的确更为复杂，相比一些完全不考虑评论定制的框架 Halo 做的已经很好了。
