### ISSUE TITLE
web界面Markdown解析错误

### ISSUE THREAD

**Issue by txbxxx** [halo-dev/halo#5837]
### 系统信息

- 外部访问地址: http://blog.tanc.fun:9999/
- 启动时间: 2024-04-28 16:50
- 版本: 2.14.1
- 构建时间: 2024-04-23 14:50
- Git Commit: 7e829a5
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: MariaDB Server / 5.5.5-10.4.32-MariaDB
- 操作系统: Linux / 3.10.0-1160.105.1.el7.x86_64
- 已激活主题: [Hao](https://githubfast.com/liuzhihang/halo-theme-hao)
- 已启动插件:
  - [highlight.js 代码高亮](https://github.com/halo-sigs/plugin-highlightjs)
  - [文本绘图](https://github.com/halo-sigs/plugin-text-diagram)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [lightgallery.js 灯箱](https://github.com/halo-sigs/plugin-lightgallery)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [对象存储（Amazon S3 协议）](https://github.com/halo-dev/plugin-s3)
  - [Vditor编辑器](https://github.com/justice2001/veditor-plugin)
  - [Docsme](https://github.com/f2ccloud/plugin-docsme)
  - [文章导入导出](https://jhacker.cn/2023/halo-plugin-export2doc)
  - [Markdown / HTML 内容块](https://github.com/halo-dev/plugin-hybrid-edit-block)

### 使用的哪种方式运行？

Docker

### 发生了什么？

我发现如果是导入文件后发布，就会导致在web界面中markdown文档解析会不成功，像:star: 和 :one: 这些符号会解析不成功，但是如果我ctrl+x 如何粘贴上去，他就会解析成功？非常奇怪
![image](https://github.com/halo-dev/halo/assets/79389617/cea97bab-c8b2-47b7-887b-a9829a7630d7)
重写复制后:
![image](https://github.com/halo-dev/halo/assets/79389617/1ed97523-a007-4d62-a701-4f4fca3d5c6e)

**Comment by ruibaby** [comment]
> [文章导入导出](https://jhacker.cn/2023/halo-plugin-export2doc)

是使用这个插件导入的吗？如果是的话，建议向插件提交 issue，这个问题的原因可能是插件中的 Markdown 解析不支持 emoji 文本解析。

**Comment by txbxxx** [comment]
> > [文章导入导出](https://jhacker.cn/2023/halo-plugin-export2doc)
> 
> 是使用这个插件导入的吗？如果是的话，建议向插件提交 issue，这个问题的原因可能是插件中的 Markdown 解析不支持 emoji 文本解析。

好滴谢谢
