### ISSUE TITLE
安装官方docker安装，然后启动docker 提示h2连接url没设置

### ISSUE THREAD

**Issue by skyydq** [halo-dev/halo#5841]
### 系统信息

mac m2 docker 使用官网提供的命令，
docker run -it -d --name halo -p 8090:8090 -v ~/.halo2:/root/.halo2 halohub/halo:2.14
然后启动他，控制台就有错误信息

### 使用的哪种方式运行？

Docker

### 发生了什么？

<img width="1264" alt="image" src="https://github.com/halo-dev/halo/assets/17490986/b0fb7889-a936-4987-ad04-ccda2f00f8bd">

**Comment by ruibaby** [comment]
/triage duplicate

相关 issue：https://github.com/halo-dev/halo/issues/5322
