### ISSUE TITLE
文章/页面历史版本代码框字体颜色看不清

### ISSUE THREAD

**Issue by longjuan** [halo-dev/halo#5845]
### 系统信息

- 启动时间: 2024-04-30 20:06
- 版本: 2.15.0
- 构建时间: 2024-04-30 16:27
- Git Commit: 1582a62
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: MySQL Community Server (GPL) / 5.7.44
- 操作系统: Linux / 6.1.0-17-amd64
- 已激活主题: [Theme-Stack](https://github.com/jiewenhuang/halo-theme-stack)
- 已启动插件:
  - [highlight.js 代码高亮](https://github.com/halo-sigs/plugin-highlightjs)
  - [站点推送插件](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [Metrics Graph](https://github.com/guqing/plugin-metrics-graph)
  - [增强备份（Backup IMproved）](https://www.halo.run/store/apps/app-dHakX)
  - [应用市场](https://www.halo.run/store/apps/app-VYJbF)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [ByteMD](https://github.com/ruibaby/plugin-bytemd)
  - [lightgallery.js 灯箱](https://github.com/halo-sigs/plugin-lightgallery)
  - [对象存储（Amazon S3 协议）](https://github.com/halo-dev/plugin-s3)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [Unsplash](https://github.com/halo-sigs/plugin-unsplash)

### 使用的哪种方式运行？

Docker

### 发生了什么？

如图
![image](https://github.com/halo-dev/halo/assets/28662535/d2a70dc1-ce53-41bc-8874-6ef20499f906)
![image](https://github.com/halo-dev/halo/assets/28662535/d2aad9c4-2093-4494-a602-e0a7651ca488)

**Comment by ruibaby** [comment]
感谢反馈这个问题，这可能是由于当前只是单纯的渲染了 HTML 结构，但暂时并未对内容做任何处理，所以代码块这种样式还未得到适配。我这边主要能想到两个优化方案：

1. 单独为每种格式做优化，但可能很难达到与编辑器完全一致。
2. 让默认编辑器支持只读模式，完全用默认编辑器渲染 HTML。

/kind improvement
/area ui

**Comment by longjuan** [comment]
我觉得删了这个background就行
![image](https://github.com/halo-dev/halo/assets/28662535/9a0f0d54-5bc6-41dd-ae1d-5b535d345b05)
https://github.com/halo-dev/halo/blob/2178bd8b80d372ba2575176ac609e070ce5696f8/ui/console-src/modules/contents/pages/components/SnapshotContent.vue#L66
