### ISSUE TITLE
主页的文章必须点击文章标题才可以跳转进去文章，是否可以改成点击摘要或者封面或者是任何部位也可以跳转？

### ISSUE THREAD

**Issue by rtsbtx** [halo-dev/halo#5846]
### 描述一下此特性

主页的文章必须点击文章标题才可以跳转进去文章，是否可以改成点击摘要或者封面或者是任何部位也可以跳转？

**Comment by ruibaby** [comment]
感谢反馈此问题，但这个问题似乎和主题有关，建议向具体的主题提交 issue。

**Comment by rtsbtx** [comment]
> 感谢反馈此问题，但这个问题似乎和主题有关，建议向具体的主题提交 issue。

目前使用的是默认主题
