### ISSUE TITLE
希望作者权限下，也可删除作者自己文章

### ISSUE THREAD

**Issue by Herbert0501** [halo-dev/halo#5851]
### 你当前使用的版本

2.14.1

### 描述一下此特性

作者权限，增加一个可以删除自己文章的功能。

目前没有提供给作者权限下，可以删除自己文章的功能，需要管理员删除。

### 附加信息

角色：作者
![issue](https://image.kangyaocoding.top/issue/issue08.png)

**Comment by ruibaby** [comment]
感谢反馈，这个最好是为个人中心的文章管理提供一个新的删除接口，并提供一个新的权限 **允许删除自己的文章**。不过需要讨论一下是否需要支持管理员审核。

/kind feature
