### ISSUE TITLE
v2.15 瞬间插件报404

### ISSUE THREAD

**Issue by chinagoldline** [halo-dev/halo#5864]
### 系统信息

/console/moments

### 使用的哪种方式运行？

Docker

### 发生了什么？

报错：资源不存在

### 相关日志输出

```shell
404：
/apis/console.api.moment.halo.run/v1alpha1/tags
```

**Comment by LIlGG** [comment]
你可以先在插件列表查看一下瞬间插件是否正常启动。

另外可能需要提供详细的后台日志。

/kind support

**Comment by chinagoldline** [comment]
先关闭插件，然后更新1.6.1的新版本后，再启用插件，插件就可以正常使用了，暂未观察到其他异常。
