### ISSUE TITLE
2.15.1 在数据初始化时，无法正常启动预设插件

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#5867]
### 系统信息

- 外部访问地址: http://localhost:8090/
- 启动时间: 2024-05-07 15:12
- 版本: 2.15.1
- 构建时间: 2024-05-07 11:51
- Git Commit: 7c90ed5
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: PostgreSQL / 15.4 (Debian 15.4-2.pgdg120+1)
- 操作系统: Linux / 6.7.11-orbstack-00143-ge6b82e26cd22
- 已激活主题: [Earth](https://github.com/halo-dev/theme-earth.git)
- 已启动插件:
  - [应用市场](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker

### 发生了什么？

<img width="1819" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/458217b4-2c5c-4f8b-bd28-7a20fc4bb1e1">

如图，第一个插件无法正常启动，接口一直处于 pending 状态，然后刷新页面之后仅安装了一个插件且没有启动。再次启动可以正常启动插件。

日志：[halo-log-2024-05-07 15_14.log](https://github.com/halo-dev/halo/files/15231692/halo-log-2024-05-07.15_14.log)

/kind bug
/area core
/priority critical-urgent

**Comment by JohnNiang** [comment]
经过排查，主要是因为安装好插件后，立即启用了插件，此时插件正在被解析并禁用，禁用的时候会自动设置 plugin.spec.enabled 为 false，这也就导致启动插件接口会一直等待插件启动成功，直到等待超时。

目前，我的解决方案就是在启用插件的重试逻辑中尝试重新设置插件状态，这可能是当前修改最小的解决方案。
