### ISSUE TITLE
LOGO墙的图片不知道为啥换不了图片

### ISSUE THREAD

**Issue by michael1020li** [halo-dev/halo#5871]
### 系统信息

docker 安装

### 使用的哪种方式运行？

Docker

### 发生了什么？

不知道怎么选图片 ,我的首页看不到这个图片在LOGO墙出来。装了图库管理。

### 附加信息

![image](https://github.com/halo-dev/halo/assets/73422348/374c1529-5f24-458d-9f9b-6c50917e2c05)
![image](https://github.com/halo-dev/halo/assets/73422348/c5141d24-d7d8-440c-915e-1e9bc3e5e14b)

**Comment by wan92hen** [comment]
需要使用 photo-group-xxx 这样的名字，可以在图库管理页面选中图库后，通过浏览器地址栏查看。

**Comment by michael1020li** [comment]
![image](https://github.com/halo-dev/halo/assets/73422348/1562af04-d0b8-4879-a4c9-6a10dbbc608b)
photo-group-JQpTj   ????

**Comment by michael1020li** [comment]
可以了 非常感谢

**Comment by michael1020li** [comment]
![image](https://github.com/halo-dev/halo/assets/73422348/4bbe4fc2-2609-41b1-868f-ac27e0baf235)

**Comment by wan92hen** [comment]
因为刚才的两条回复暴露了 IP 信息，这边进行了删除操作。
这个 Issue 也先关掉了。
