### ISSUE TITLE
点击主题菜单就会显示这条错误信息

### ISSUE THREAD

**Issue by wwwxhenry** [halo-dev/halo#5875]
### 系统信息

- 外部访问地址: http://localhost:8090/
- 启动时间: 2024-05-09 16:48
- 版本: 2.15.1
- 构建时间: 2024-05-07 11:51
- Git Commit: 7c90ed5
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: MySQL Community Server - GPL / 8.1.0
- 操作系统: Linux / 3.10.0-1160.el7.x86_64
- 已激活主题: [Theme-Stack](https://github.com/jiewenhuang/halo-theme-stack)
- 已启动插件:
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

![QQ截图20240509182007](https://github.com/halo-dev/halo/assets/101274603/797539d9-4774-4a45-8217-ce9eb0563429)

**Comment by ruibaby** [comment]
看提示应该是应用市场插件启动有问题，你可以尝试重启一下应用市场插件。
