### ISSUE TITLE
专业版 2.15.1 安装 Trailing Slash v1.0.0 插件后，应用市场显示未

### ISSUE THREAD

**Issue by Mattoids** [halo-dev/halo#5878]
### 系统信息

debian 12.2 + 1Panel + docker + Halo2.15.1 + Trailing Slash v1.0.0

### 使用的哪种方式运行？

Docker

### 发生了什么？

如下图，插件实际安装成功了，但应用商店中显示的安装状态不正确。

相同的问题还存在于以下插件
Vditor 编辑器 1.6.2
对象存储（Amazon S3 协议）1.9.1

### 附加信息
![image](https://github.com/halo-dev/halo/assets/16252517/9269e7e0-bd96-4040-bb9c-07ef285ff9cf)
![image](https://github.com/halo-dev/halo/assets/16252517/8e693c70-e7d2-452c-9960-d30cfe4db22c)
![image](https://github.com/halo-dev/halo/assets/16252517/28b9d699-d916-4ce6-8c6a-8043c6230787)

安装途中有因为某些原因导致 OpenResty 无法访问，实际是否有影响不得而知

**Comment by ruibaby** [comment]
建议在 1Panel 上检查防火墙的拦截情况，看看是不是有 Halo 的接口被拦截了。

/kind support

**Comment by Mattoids** [comment]
> 建议在 1Panel 上检查防火墙的拦截情况，看看是不是有 Halo 的接口被拦截了。
> 
> /kind 支持

但是我只在部分插件中遇到了这个问题，部分插件的安装状态是正确的。

**Comment by Mattoids** [comment]
> 建议在 1Panel 上检查防火墙的拦截情况，看看是不是有 Halo 的接口被拦截了。
> 
> /kind 支持

我想你是对的，排查下来是因为 1Panel 的 WAF 防火墙拦截了 v1alpha1/plugins/PluginS3ObjectStorage 接口导致安装状态无法更新。

**Comment by Mattoids** [comment]
> 建议在 1Panel 上检查防火墙的拦截情况，看看是不是有 Halo 的接口被拦截了。
> 
> /kind 支持

我想你是对的，排查下来是因为 1Panel 的 WAF 防火墙拦截了 v1alpha1/plugins/PluginS3ObjectStorage 接口导致安装状态无法更新。
