### ISSUE TITLE
在主题页新增自己的页面

### ISSUE THREAD

**Issue by YuppyHub** [halo-dev/halo#588]
你好， 我现在想在主题页新增自己的静态页面，请问怎么访问呢？是添加 ftl,还是 直接 html 结尾就可以？

**Comment by JohnNiang** [comment]
可能需要 ftl 结尾。具体等 @ruibaby 解释。

**Comment by ruibaby** [comment]
如果是纯静态，你可以参考：https://halo.run/archives/use-hidden-features#%E5%BC%80%E5%8F%91%E8%80%85%E9%80%89%E9%A1%B9

如果需要结合数据渲染，请参考：https://halo.run/archives/develop-theme-ready#%E7%9B%AE%E5%BD%95%E7%BB%93%E6%9E%84
