### ISSUE TITLE
更改外部访问链接地址导致控制台报错

### ISSUE THREAD

**Issue by xishouyunxing** [halo-dev/halo#5884]
### 系统信息

- 外部访问地址: https://moeuu.cn
- 启动时间: 2024-05-10 13:24
- 版本: 2.15.1
- 构建时间: 2024-05-07 11:53
- Git Commit: 2f9aa57
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: MySQL Community Server (GPL) / 5.7.43
- 操作系统: Linux / 3.10.0-1160.108.1.el7.x86_64
- 已激活主题: [Hao](https://github.com/chengzhongxue/halo-theme-hao)
- 已启动插件:
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [Media Optimizer](https://github.com/guqing/plugin-cloudinary)
  - [highlight.js 代码高亮](https://github.com/halo-sigs/plugin-highlightjs)
  - [增强备份（Backup IMproved）](https://www.halo.run/store/apps/app-dHakX)
  - [SEO 工具集](https://www.halo.run/store/apps/app-FNGbT)
  - [Lsky Pro 兰空图床](https://github.com/ichenhe/halo-lsky-pro)
  - [Umami](https://github.com/halo-sigs/plugin-umami)
  - [Tocbot 目录生成](https://github.com/liuzhihang/plugin-tocbot)
  - [我的装备管理](https://github.com/halo-sigs/plugin-equipments)
  - [站点迁移](https://github.com/halo-sigs/plugin-migrate)
  - [Markdown / HTML 内容块](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [文章导入导出](https://jhacker.cn/2023/halo-plugin-export2doc)
  - [朋友圈](https://github.com/chengzhongxue/plugin-friends)
  - [Vditor 编辑器](https://github.com/justice2001/halo-plugin-vditor)
  - [对象存储（Amazon S3 协议）](https://github.com/halo-dev/plugin-s3)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [ToolBench](https://github.com/DioxideCN/Tool-Bench)
  - [live2d 看板娘](https://github.com/LIlGG/plugin-live2d)
  - [WordPress导入](https://github.com/wan92hen/plugin-wordpress)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [追番插件](https://github.com/Roozenlz/plugin-bilibili-bangumi)
  - [图库管理](https://github.com/halo-sigs/plugin-photos)
  - [站点推送插件](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [ByteMD](https://github.com/ruibaby/plugin-bytemd)
  - [应用市场](https://www.halo.run/store/apps/app-VYJbF)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-sigs/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)

### 使用的哪种方式运行？

Docker

### 发生了什么？

使用最新版halo时，在1panel中更新外部访问地址造成控制台部分功能显示502无法使用
![屏幕截图 2024-05-10 134643](https://github.com/halo-dev/halo/assets/135615287/4f5f3327-77ee-48ef-b23c-10b3c838c2a1)

**Comment by guqing** [comment]
检查 1panel 防火墙设置， halo 这边没有 502 的状态码，建议这种 1panel 使用问题到 1pannel 提问
/triage needs-information
/kind support
