### ISSUE TITLE
请问一下如何设置一篇博客为多人共同编辑，或者说让别人假如编辑呢

### ISSUE THREAD

**Issue by txbxxx** [halo-dev/halo#5889]
### 你当前使用的版本

docker halo 2

### 描述一下此特性

我站内有多个用户，我想要用户一起来编辑一个博客，这个如何设置呢？

**Comment by ruibaby** [comment]
请参考使用文档：

1. https://docs.halo.run/user-guide/users
2. https://docs.halo.run/user-guide/user-center

/kind support
