### ISSUE TITLE
为 halo:comment 标签 colorScheme 参数添加 无指定配色 的值

### ISSUE THREAD

**Issue by HowieHz** [halo-dev/halo#5890]
### 描述一下此特性

![image](https://github.com/halo-dev/halo/assets/94725606/f3737998-7aa9-42df-a170-eb2b0c40c11e)
https://docs.halo.run/developer-guide/theme/template-tag/#halocomment
如: [normal](https://developer.mozilla.org/zh-CN/docs/Web/CSS/color-scheme#normal) 或者 [auto](https://www.halo.run/store/apps/app-YXyaD)

![image](https://github.com/halo-dev/halo/assets/94725606/91ae53d2-b811-4aac-ba84-5047f835dd90)
![image](https://github.com/halo-dev/halo/assets/94725606/60ec96c8-7d5d-481d-b848-db29614ea78b)

**Comment by ruibaby** [comment]
> 添加无指定配色

这个需求是什么呢？当前 auto 无法满足需求吗？或许可以参考 https://github.com/halo-dev/plugin-comment-widget#%E9%85%8D%E8%89%B2%E5%88%87%E6%8D%A2%E6%96%B9%E6%A1%88 强制在主题指定配色方案。

![image](https://github.com/halo-dev/halo/assets/21301288/1e41bd10-46c5-46df-8d7c-e0f2a89bea81)

此外，这里的文档可能需要更新，<halo:comment /> 标签中的 colorScheme 已经无效，这本身也是以前的设计问题，最好是通过 CSS 变量设置。

**Comment by HowieHz** [comment]
> 文档可能需要更新，<halo:comment /> 标签中的 colorScheme 已经无效，这本身也是以前的设计问题，最好是通过 CSS 变量设置。

哦，这个废除了就没啥关系了。
我是在想适配其他的评论系统，通过这个注入要是只能传递 light 和 dark 就会导致设计不统一，其他地方都有 auto light dark，就这中间卡一下没 auto，太突兀了。

**Comment by ruibaby** [comment]
文档已经提交修改，https://github.com/halo-dev/docs/pull/352
