### ISSUE TITLE
默认评论系统BUG

### ISSUE THREAD

**Issue by carolcoral** [halo-dev/halo#5891]
### 系统信息

- 外部访问地址: https://blog.xindu.site
- 启动时间: 2024-05-08 09:30
- 版本: 2.15.1
- 构建时间: 2024-05-07 11:53
- Git Commit: 2f9aa57
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: PostgreSQL / 15.3 (Debian 15.3-1.pgdg120+1)
- 操作系统: Linux / 4.4.302+
- 已激活主题: [Hao](https://github.com/chengzhongxue/halo-theme-hao)
- 已启动插件:
  - [爱发电插件](https://github.com/carolcoral/plugin-afdian)
  - [Lsky Pro 兰空图床](https://github.com/ichenhe/halo-lsky-pro)
  - [SEO 工具集](https://github.com/f2ccloud/plugin-seo-tools)
  - [复制追加](https://github.com/turka-cn/plugin-copyadd)
  - [站点推送插件](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [Docsme](https://github.com/f2ccloud/plugin-docsme)
  - [Vditor编辑器](https://github.com/justice2001/veditor-plugin)
  - [增强备份（Backup IMproved）](https://www.halo.run/store/apps/app-dHakX)
  - [文章导入导出](https://jhacker.cn/2023/halo-plugin-export2doc)
  - [对象存储（Amazon S3 协议）](https://github.com/halo-dev/plugin-s3)
  - [Markdown / HTML 内容块](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [我的装备管理](https://github.com/halo-sigs/plugin-equipments)
  - [文章限制阅读 Pro](https://github.com/f2ccloud/plugin-restricted-reading-pro)
  - [应用市场](https://www.halo.run/store/apps/app-VYJbF)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [图库管理](https://github.com/halo-sigs/plugin-photos)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [WebP Cloud Services](https://webp.se/)
  - [无色界](https://github.com/guqing/halo-plugin-colorless)
  - [Tocbot 目录生成](https://github.com/liuzhihang/plugin-tocbot)
  - [lightgallery.js 灯箱](https://github.com/halo-sigs/plugin-lightgallery)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [站点迁移](https://github.com/halo-sigs/plugin-migrate)
  - [KaTeX](https://github.com/halo-sigs/plugin-katex)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

使用默认评论系统，用户评论后无法正确关联评论页面地址。

![image](https://github.com/halo-dev/halo/assets/8952687/39cac1ec-f708-4d15-8e0b-d76c587bd8f1)
![image](https://github.com/halo-dev/halo/assets/8952687/6b773213-27ab-4c45-8c15-2fd06159bd66)

**Comment by guqing** [comment]
这并不是 bug，你使用的友情链接插件是不支持评论的，这应该是主题在此页面添加了一个可以评论的标签而已，但是对于 Halo 来说是无法识别的，除非友情链接插件去适配评论显示，建议到友情链接插件去提交 issue

/kind support
/close

**Comment by carolcoral** [comment]
了解
