### ISSUE TITLE
我用不同电脑的浏览器访问管理后台，有的显示中文，有的显示英文

### ISSUE THREAD

**Issue by hlcen66** [halo-dev/halo#5896]
### System information

- External url: https://chenhanlin.com.cn/
- Start time: 2024-05-10 15:30
- Version: 2.15.1
- Build time: 2024-05-07 11:51
- Git Commit: 7c90ed5
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- Database: MySQL Community Server - GPL / 8.0.27
- Operating system: Linux / 3.10.0-1160.114.2.el7.x86_64
- Activated theme: [Theme Joe3](https://github.com/jiewenhuang/halo-theme-joe3.0)
- Enabled plugins:
  - [Meilisearch](https://github.com/Rainsheep/halo-plugin-meilisearch)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - AI 助手
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)

### What is the project operation method?

Docker

### What happened?

我用不同电脑的浏览器访问管理后台，有的显示中文，有的显示英文

### Relevant log output

```shell
如何更改System Locale  en_US
```

**Comment by ruibaby** [comment]
当前第一次访问 Console 时，会根据系统或者浏览器语言设置首选显示语言。但你可以在登录页面底部手动选择：

<img width="513" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/bc23e333-3c24-4e0e-ad07-30e562ef3848">

/kind support
