### ISSUE TITLE
Halo更新到版本2.15.2后，添加的菜单网站变空白

### ISSUE THREAD

**Issue by ahhuipt** [halo-dev/halo#5897]
### 系统信息

- 外部访问地址: https://gyhwd.top/
- 启动时间: 2024-05-11 22:34
- 版本: 2.15.2
- 构建时间: 2024-05-10 14:22
- Git Commit: fba7d0a
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: MySQL Community Server - GPL / 8.2.0
- 操作系统: Linux / 3.10.0-1160.114.2.el7.x86_64
- 已激活主题: [Hao](https://githubfast.com/liuzhihang/halo-theme-hao)
- 已启动插件:
  - [Markdown / HTML 内容块](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [朋友圈](https://github.com/chengzhongxue/plugin-friends)
  - [对象存储（Amazon S3 协议）](https://github.com/halo-dev/plugin-s3)
  - [友链自助提交插件](https://github.com/liuyiwuqing/halo-plugin-links-submit)
  - [KaTeX](https://github.com/halo-sigs/plugin-katex)
  - [ByteMD](https://github.com/ruibaby/plugin-bytemd)
  - [Willow Markdown 编辑器](https://github.com/guqing/willow-mde)
  - [豆瓣](https://github.com/chengzhongxue/plugin-douban)
  - [图库管理](https://github.com/halo-sigs/plugin-photos)
  - [追番插件](https://github.com/Roozenlz/plugin-bilibili-bangumi)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [应用市场](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker

### 发生了什么？

在1Panel将Halo更新到版本2.15.2后，添加的菜单网站变空白，不显示站点图标和名称

![Snipaste_2024-05-12_12-07-58](https://github.com/halo-dev/halo/assets/130829182/bd718e72-e843-4244-899e-31f446a24e09)
![Snipaste_2024-05-12_12-11-42](https://github.com/halo-dev/halo/assets/130829182/8ccf70f4-4db2-4f50-8408-fca85398148b)

**Comment by ruibaby** [comment]
看看有没有异常日志。

**Comment by chengzhongxue** [comment]
![image](https://github.com/halo-dev/halo/assets/89380218/f10090cb-801b-4037-8791-103d7d23f52f)
编辑的内容也有，但是在页面上不显示，然后主题读取的菜单数据空白的
![image](https://github.com/halo-dev/halo/assets/89380218/45260a38-5ba6-467a-b7f1-bcad01c5bd0c)

**Comment by chengzhongxue** [comment]
> ![image](https://private-user-images.githubusercontent.com/89380218/330259454-f10090cb-801b-4037-8791-103d7d23f52f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NTQ2NjMsIm5iZiI6MTcxNTY1NDM2MywicGF0aCI6Ii84OTM4MDIxOC8zMzAyNTk0NTQtZjEwMDkwY2ItODAxYi00MDM3LTg3OTEtMTAzZDdkMjNmNTJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDAyMzkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4M2NhMzhlZTZiMzA3MDUxOGY1MmI5Nzc2MTMzNGVkNTI4YjZkOTY3NjQxOWY2NDM5NWZjNTdiZDZkNjQ0MzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o78mUwF-dlWj55IiMiAyQide9Xgxogq6xLj9nkk5MGA) 编辑的内容也有，但是在页面上不显示，然后主题读取的菜单数据空白的 ![image](https://private-user-images.githubusercontent.com/89380218/330259476-45260a38-5ba6-467a-b7f1-bcad01c5bd0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NTQ2NjMsIm5iZiI6MTcxNTY1NDM2MywicGF0aCI6Ii84OTM4MDIxOC8zMzAyNTk0NzYtNDUyNjBhMzgtNWJhNi00NjdhLWI3ZjEtYmNhZDAxYzViZDBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDAyMzkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3N2QwZTkyYTdmOGQ1YTg2MjU3NGE3MWZlYmIwNTIwYjc2OGJiNDQwOTZkNTE3MzRhMzM2MDkyZTRhYTU4MGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NWGx43mOPMP32XTXluCV5xedfOWqONO15RPqP9PBEN0)

没发现有异常日志

**Comment by ruibaby** [comment]
hi @chengzhongxue @ahhuipt 目前还能复现此问题吗？我们无法复现，也没有类似的反馈。

**Comment by chengzhongxue** [comment]
关掉这个Issues吧，后面不知道怎么搞搞又好了，可能是哪里操作问题
