### ISSUE TITLE
login页面优化

### ISSUE THREAD

**Issue by QingFeng-awa** [halo-dev/halo#5908]
### 你当前使用的版本

2.15.2

### 描述一下此特性

将Halo登录/注册页面的表单调大一点(类似于浏览器自带缩放110%的大小)。
个人认为Halo登录页面的表单太小了。
而且,你们不认为登录页面太空旷了嘛?

**Comment by ruibaby** [comment]
感谢反馈，你当前的屏幕分辨率是？可以考虑在全局为高分屏做适配。

> 而且,你们不认为登录页面太空旷了嘛?

建议直接给出你的建议。

PR Welcome :)

/kind improvement
/area console

**Comment by QingFeng-awa** [comment]
我当前的屏幕是2K(2160 × 1440)。
登录页面可以尝试允许用户自定义背景图片,允许用户加一些自定义文字(类似于公告)来丰富登录页。

**Comment by ruibaby** [comment]
我建议先完成 <https://github.com/halo-dev/halo/issues/5214>，然后支持通过插件改变登录页面的 UI 或者行为，或者允许主题提供登录页面目录。

**Comment by QingFeng-awa** [comment]
作为一个Halo用户,我很希望自己能为Halo做出贡献,但前提是————
我会Java。

在[issue#5214](https://github.com/halo-dev/halo/issues/5214)完成后,这个issue会被重新打开。

**Comment by ruibaby** [comment]
Hi @QingFeng-awa 我建议此 issue 保持打开，可以方便社区参与者进行讨论，也可以推进 https://github.com/halo-dev/halo/issues/5214

/reopen
