### ISSUE TITLE
插件提供小程序访问接口，但没有JWT登录的接口可以使用

### ISSUE THREAD

**Issue by Ccl2007** [halo-dev/halo#5913]
### 系统信息

无

### 使用的哪种方式运行？

Docker

### 发生了什么？

小程序通过微信登录，然后转到系统登录，获取token，然后请求带上token。这个token无需通过页面登录生成，再交给小程序，而是通过接口获取一个token。没有发现这个获取token的接口。

**Comment by XiaoMo-Donald** [comment]
哦嚯？要开放 jwt登录了吗

**Comment by JohnNiang** [comment]
Hi @Ccl2007 , thank you for reaching out here!

请问你提到的登录流程是 https://developers.weixin.qq.com/miniprogram/dev/framework/open-ability/login.html 所描述的么？如果是的话，Halo Core 中无法实现以上流程，需要你在插件中自定义认证相关的扩展才可以实现。

具体请参考：

- https://docs.halo.run/developer-guide/plugin/api-reference/server/extension-points/authentication-webfilter
- https://github.com/halo-sigs/plugin-oauth2

**Comment by Ccl2007** [comment]
特别感谢，我在插件里实现这个流程。

**Comment by XiaoMo-Donald** [comment]
大佬，有思路了吗 @Ccl2007

**Comment by Ccl2007** [comment]
这个没有难度，计划之中，写好了，分享插件给你。

**Comment by JohnNiang** [comment]
/reopen
/remove-kind support
/kind feature
/area core
/milestone 2.24.x

我将尝试在 Core 中实现 JWT 认证。
