### ISSUE TITLE
代码注入功能可否支持Thymeleaf

### ISSUE THREAD

**Issue by yefoenix** [halo-dev/halo#5922]
### 你当前使用的版本

2.15.0

### 描述一下此特性

希望代码注入功能能够支持Thymeleaf,
例如：
在代码注入功能中，为内容页面Head标签添加类似以下代码

`<meta property="og:image" th:content="${post.spec.cover}">`

前端应当转化为

`<meta property="og:image" content="文章封面图片实际地址">`

**Comment by JohnNiang** [comment]
如果你指的是系统设置中代码注入功能，该功能面向的是所有页面，不仅仅是文章，所以无法知道具体哪些变量可以使用。

/triage needs-information

**Comment by yefoenix** [comment]
指的是，系统设置中代码注入功能。
目前这个功能支持分别设置全局页 Head 标签和内容页 Head 标签，因此可以进行一定程度的区分。
![image](https://github.com/halo-dev/halo/assets/8215230/4fe622cb-b9a2-450c-ab1b-9d8b204c95a2)

实际上我目前的需求是暂时通过修改主题的 head 模板来实现了，就是这样不太优雅。

**Comment by guqing** [comment]
有现成的 SEO 插件可以支持你说的功能，或者你可以选择修改主题模板来实现，这里的内容页不仅仅只是说的文章详情还有自定义页面等因此你这样的写法是有问题的

**Comment by ruibaby** [comment]
此 issue 已不再活跃，我将关闭此 issue。

/close
