### ISSUE TITLE
There is no PasswordEncoder mapped for the id "null"

### ISSUE THREAD

**Issue by coderstory** [halo-dev/halo#5939]
### 系统信息

Ubuntu  22.04
openjdk version "21.0.2" 2024-01-16
halo2 2.15.2
mysql 8.0

### 使用的哪种方式运行？

Fat Jar

### 发生了什么？

后端登入失败
https://blog.xxxx.cn/console/login

通过issues搜索 找到几个相同类型的异常，但都不是登入接口报错，且都标记已修复或者关闭。

最开始是没问题，后来我改了一下nginx的配置（原本将外部端口8888映射到8090，现在将443映射到8090）
application里的域名去掉8888端口，还导入了wp导出的内容。

### 相关日志输出

```shell
java.lang.IllegalArgumentException: There is no PasswordEncoder mapped for the id "null"
	at org.springframework.security.crypto.password.DelegatingPasswordEncoder$UnmappedIdPasswordEncoder.matches(DelegatingPasswordEncoder.java:289) ~[spring-security-crypto-6.3.0-RC1.jar!/:6.3.0-RC1]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ? AuthenticationWebFilter [DefaultWebFilterChain]
	*__checkpoint ? AuthenticationWebFilter [DefaultWebFilterChain]
	*__checkpoint ? ReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ? CsrfWebFilter [DefaultWebFilterChain]
	*__checkpoint ? CorsWebFilter [DefaultWebFilterChain]
	*__checkpoint ? HttpHeaderWriterWebFilter [DefaultWebFilterChain]
	*__checkpoint ? ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
	*__checkpoint ? run.halo.app.webfilter.AdditionalWebFilterChainProxy [DefaultWebFilterChain]
	*__checkpoint ? HTTP POST "/login" [ExceptionHandlingWebHandler]
Original Stack Trace:
		at org.springframework.security.crypto.password.DelegatingPasswordEncoder$UnmappedIdPasswordEncoder.matches(DelegatingPasswordEncoder.java:289) ~[spring-security-crypto-6.3.0-RC1.jar!/:6.3.0-RC1]
		at org.springframework.security.crypto.password.DelegatingPasswordEncoder.matches(DelegatingPasswordEncoder.java:237) ~[spring-security-crypto-6.3.0-RC1.jar!/:6.3.0-RC1]
		at org.springframework.security.authentication.AbstractUserDetailsReactiveAuthenticationManager.lambda$authenticate$0(AbstractUserDetailsReactiveAuthenticationManager.java:107) ~[spring-security-core-6.3.0-RC1.jar!/:6.3.0-RC1]
		at reactor.core.publisher.FluxFilter$FilterSubscriber.onNext(FluxFilter.java:99) ~[reactor-core-3.6.5.jar!/:3.6.5]
		at reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.run(MonoPublishOn.java:181) ~[reactor-core-3.6.5.jar!/:3.6.5]
		at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) ~[reactor-core-3.6.5.jar!/:3.6.5]
		at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) ~[reactor-core-3.6.5.jar!/:3.6.5]
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[na:na]
		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
		at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
```

### 附加信息

{
    "type": "about:blank",
    "title": "服务器内部错误",
    "status": 500,
    "detail": "服务器内部发生错误，请稍候再试。",
    "instance": "https://blog.xxxx.cn/login",
    "requestId": "7df9ee83-224",
    "timestamp": "2024-05-17T07:51:44.195902240Z"
}

**Comment by JohnNiang** [comment]
从目前的日志来看，数据库中用户名的密码似乎被修改过，并不符合规范。

另外，你需要提供完整的复现步骤，才能进一步定位问题。

/triage needs-information

**Comment by coderstory** [comment]
> 从目前的日志来看，数据库中用户名的密码似乎被修改过，并不符合规范。
> 
> 另外，你需要提供完整的复现步骤，才能进一步定位问题。
> 
> /triage needs-information

我没执行过更新密码的操作，数据库中的数据我也没修改过。 

目前我随便输入个账号和密码，也是同样的报错.
之后再登入我的账号，居然ok

**Comment by coderstory** [comment]
fetch("https://blog.coderstory.cn/login", {
  "headers": {
    "accept": "application/json, text/plain, */*",
    "accept-language": "zh-CN,zh;q=0.9",
    "content-type": "application/x-www-form-urlencoded",
    "priority": "u=1, i",
    "sec-ch-ua": "\"Chromium\";v=\"124\", \"Google Chrome\";v=\"124\", \"Not-A.Brand\";v=\"99\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"Windows\"",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin",
    "x-requested-with": "XMLHttpRequest",
    "x-xsrf-token": "dbea16c4-6c7d-405b-a1de-90b97a76b7e5"
  },
  "referrer": "https://blog.coderstory.cn/console/login",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": "_csrf=dbea16c4-6c7d-405b-a1de-90b97a76b7e5&username=youzhabaozi&password=eI9zmSZfa26hYU%2B3l%2F0S%2FeEKfa1TN%2Fa4oUVonwtmgUam1m%2BR5tHdRoutdw08geiCzm7x5uNjgtXP3JLu5YpeDcD%2FS9qW7Pw2A1Fj82CtKwUBOTwARsRvUTpLg9okoXKK2rCEXjO51tUD94J9UXVSRMFTZKfbsmaN8Zce072qUiGFLWlN0Z02l8oABJp17ZcAZr8UkreXNr%2FukkQU3mxFZjVP4EASR23inSaJkmTjsStsG0756cAiIjiRUJGmrZEECVOGxcBbW5CVqjrliBw%2BIUNg3qKm70J7GqQRPYVVcxIL%2FrmQusRxltV2KHZUuwAEsXISSHJi%2FHwtpB5%2FnNSgPg%3D%3D",
  "method": "POST",
  "mode": "cors",
  "credentials": "include"
});

**Comment by JohnNiang** [comment]
我这边测试没有任何问题，请看下面的结果：

```bash
❯ curl 'https://blog.coderstory.cn/login' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/x-www-form-urlencoded' \
  -H 'cookie: SESSION=32393ef0-48ea-490d-94c4-01946db0a2e2; XSRF-TOKEN=ceb0bb9a-1eb7-4788-b65f-16217dfa03c5' \
  -H 'dnt: 1' \
  -H 'origin: https://blog.coderstory.cn' \
  -H 'pragma: no-cache' \
  -H 'priority: u=1, i' \
  -H 'referer: https://blog.coderstory.cn/console/login?redirect_uri=https%253A%252F%252Fblog.coderstory.cn%252Fconsole%252F' \
  -H 'sec-ch-ua: "Chromium";v="125", "Not.A/Brand";v="24"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36' \
  -H 'x-requested-with: XMLHttpRequest' \
  -H 'x-xsrf-token: ceb0bb9a-1eb7-4788-b65f-16217dfa03c5' \
  --data-raw '_csrf=ceb0bb9a-1eb7-4788-b65f-16217dfa03c5&username=admin&password=eJDXjiVFVrBeKRHZ6sQEKsLugidmsV6NiUp1xKeo%2By%2FI9EvhA57XZUOqbb5AyqZopuoJYeSpUF2FesMhVg5%2B9yhQNKKbtXPWs%2FWlpOHaX9kM5Ys%2B%2Bog6JRt2L1QLQWzZncsJT8bv4%2FuX1I4mW2NdnZJUiCBIzkoKOgaMxrNO0pe2oxCmLgP1Sa%2BmxU0UvPFPvElBw1N7vvxK8YkPdh0HygmyTLcC%2F%2FlCDWg2QFLV%2BeWBwylYuFvYqT4KTl4eoWf5Rsql8PXcmSP7H4S8woA22F0s7pfKqCTi1vbw0vFRYpS7SOexQbQC0dGUQ2lHLi%2FraDWAj4BHiacnLJmvia2%2FOQ%3D%3D' -s | jq .
{
  "type": "https://halo.run/probs/invalid-credential",
  "title": "Bad Credentials",
  "status": 401,
  "detail": "The username or password is incorrect.",
  "instance": "https://blog.coderstory.cn/login",
  "requestId": "cac9fb6c-190",
  "timestamp": "2024-05-17T09:15:35.662573228Z"
}
```

**Comment by coderstory** [comment]
fetch("https://blog.coderstory.cn/login", {
  "headers": {
    "accept": "application/json, text/plain, */*",
    "accept-language": "zh-CN,zh;q=0.9",
    "content-type": "application/x-www-form-urlencoded",
    "priority": "u=1, i",
  
    "sec-ch-ua-mobile": "?0",
  
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin",
    "x-requested-with": "XMLHttpRequest",
    "x-xsrf-token": "dbea16c4-6c7d-405b-a1de-90b97a76b7e5"
  },
  "referrer": "https://blog.coderstory.cn/console/login",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": "_csrf=dbea16c4-6c7d-405b-a1de-90b97a76b7e5&username=youzhabaozi&password=eI9zmSZfa26hYU%2B3l%2F0S%2FeEKfa1TN%2Fa4oUVonwtmgUam1m%2BR5tHdRoutdw08geiCzm7x5uNjgtXP3JLu5YpeDcD%2FS9qW7Pw2A1Fj82CtKwUBOTwARsRvUTpLg9okoXKK2rCEXjO51tUD94J9UXVSRMFTZKfbsmaN8Zce072qUiGFLWlN0Z02l8oABJp17ZcAZr8UkreXNr%2FukkQU3mxFZjVP4EASR23inSaJkmTjsStsG0756cAiIjiRUJGmrZEECVOGxcBbW5CVqjrliBw%2BIUNg3qKm70J7GqQRPYVVcxIL%2FrmQusRxltV2KHZUuwAEsXISSHJi%2FHwtpB5%2FnNSgPg%3D%3D",
  "method": "POST",
  "mode": "cors",
  "credentials": "include"
});


![企业微信截图_20240517172250](https://github.com/halo-dev/halo/assets/11525359/0c4b9785-324e-4a42-96c0-60cecb6d6931)

![企业微信截图_17159378092126](https://github.com/halo-dev/halo/assets/11525359/5f139f72-4fd2-4e3f-a7fd-7c5b2f1a631b)


您chrome下试试？

**Comment by JohnNiang** [comment]
建议提供复现步骤，我们这边仍旧无法复现以上问题。

**Comment by JohnNiang** [comment]
> ```
> {"spec":{"displayName":"Administrator","email":"**********","emailVerified":false,"password":"{bcrypt}$2a$10$TFiT1qiCRwOWB4/ZZ96XheZIRzQhHYJ1VsYUzz8s91NAqcS4kneF2","registeredAt":"2024-05-17T06:05:46.522399Z","twoFactorAuthEnabled":false,"disabled":false},"status":{"permalink":"/authors/*****"},"apiVersion":"v1alpha1","kind":"User","metadata":{"finalizers":["user-protection"],"name":"*****"","annotations":{"rbac.authorization.halo.run/role-names":"["super-role"]"},"version":2,"creationTimestamp":"2024-05-17T06:05:46.608523500Z"}}
> ```
> 
> 这个是数据库里找出来的数据 账号名和邮箱改成 ***

这个 metadata.name 是 `youzhabaozi` 么？我看这里的 password 字段是符合 Bcrypt PasswordDecoder 所需要的前缀。非常抱歉我在[这里](https://github.com/halo-dev/halo/issues/5939#issuecomment-2117109120)测试的用户名是 `admin`，所以没有复现你的错误。

从日志来看，用户名为 `youzhabaozi` 的用户的密码字段可能是这样的一种格式：`xxxx`，而不是 `{bcrypt}$2a$10$xxx`。
