### ISSUE TITLE
我写的一个主题在上传到其他服务器时提示：Failed to unzip theme

### ISSUE THREAD

**Issue by zhheo** [halo-dev/halo#5941]
### 系统信息

unbuntu

### 使用的哪种方式运行？

Docker

### 发生了什么？

<img width="915" alt="image" src="https://github.com/halo-dev/halo/assets/33177975/666ff6b1-263e-4a04-9f25-535be2028821">

主题地址：https://github.com/zhheo/halo-theme-heolink

是我的配置文件有问题吗，还望能得到答案，感谢。

安装其他主题都可以直接下载安装包安装，只有我自己写的不行

### 相关日志输出

```
{
    "type": "about:blank",
    "title": "请求参数有误",
    "status": 400,
    "detail": "Failed to unzip theme",
    "instance": "http://127.0.0.1/apis/api.console.halo.run/v1alpha1/themes/install",
    "requestId": "2f85dcd9-380",
    "timestamp": "2024-05-17T08:49:26.871000984Z"
}
```

**Comment by guqing** [comment]
你的 yaml 格式有问题，建议使用 yaml 格式化工具检查一下
<img width="737" alt="image" src="https://github.com/halo-dev/halo/assets/38999863/177ed7f3-8557-421a-8746-3155dd90d33b">

/kind support
/close

**Comment by zhheo** [comment]
确实哈哈哈，刚才刚看到想赶紧过来关，结果你们已经回了，效率太高了，抱歉
