### ISSUE TITLE
希望ai助手可以支持腾讯混元ai

### ISSUE THREAD

**Issue by 52lemon6** [halo-dev/halo#5943]
### 你当前使用的版本

1.0.0-alpha.2

### 描述一下此特性

希望ai助手可以支持腾讯混元ai

**Comment by guqing** [comment]
这个问题不是此仓库可以解决的 用此你之前提的我已经转到了 discussion 去讨论， 请不要重复提交 https://github.com/halo-dev/halo/discussions/5935
