### ISSUE TITLE
希望pro版可以支持一个环境多个网站

### ISSUE THREAD

**Issue by 52lemon6** [halo-dev/halo#5944]
### 你当前使用的版本

2.5.2 pro

### 描述一下此特性

希望pro版可以支持一个环境多个网站，如Docker Compose部署的时候配置好几个站点，什么域名，通过访问对应的域名来指向对应的网站
如果一个网站一个环境，我部署两个网站就要1g+的内存了部署四个就要2g+的内存了

**Comment by ruibaby** [comment]
/triage duplicate

See https://github.com/halo-dev/halo/issues/3207

/close
