### ISSUE TITLE
建议halo附件库添加显示视频封面

### ISSUE THREAD

**Issue by fxyun** [halo-dev/halo#5945]
### 你当前使用的版本

2.15.2

### 描述一下此特性

![image](https://github.com/halo-dev/halo/assets/168253884/69cd4b10-991d-4c61-9a0b-5457e9e1085e)
建议halo附件库添加显示视频封面，因为有时候使用到视频时看不到视频封面导致用错视频
![image](https://github.com/halo-dev/halo/assets/168253884/da47a7b9-3d79-4ad6-8a84-f30a88fa33d8)

**Comment by LonelySnowman** [comment]
我有意向完成这个 pr，截取视频的第一帧作为封面展示可以吗

/assign

**Comment by fxyun** [comment]
> 我有意向完成这个 pr，截取视频的第一帧作为封面展示可以吗
> 
> /assign

这样也可以

**Comment by fxyun** [comment]
> 我有意向完成这个 pr，截取视频的第一帧作为封面展示可以吗
> 
> /assign

弄这个封面主要是用来区分视频的内容，不用太复杂
