### ISSUE TITLE
文章中通过链接创建的视频，设置居中无效

### ISSUE THREAD

**Issue by lomiles** [halo-dev/halo#5949]
### 系统信息

- 外部访问地址: http://localhost:8080
- 启动时间: 2024-05-15 08:40
- 版本: 2.15.2
- 构建时间: 2024-05-10 14:22
- Git Commit: fba7d0a
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: MySQL Community Server - GPL / 8.0.37
- 操作系统: Linux / 5.15.0-106-generic
- 已激活主题: [Daisyblocks](https://www.halo.run/store/apps/app-WgWHe)
- 已启动插件:
  - [图库管理](https://github.com/halo-sigs/plugin-photos)
  - 联系表单
  - [Vditor 编辑器](https://github.com/justice2001/halo-plugin-vditor)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker

### 发生了什么？

文章中通过AList嵌入的视频，设置居中无效，可以去这个链接看看http://www.tengogo.com/archives/ren-ji-dui-zhan
![image](https://github.com/halo-dev/halo/assets/35911812/964b0727-4440-4b0f-8828-9d20c42569a7)

**Comment by lomiles** [comment]
不只是嵌入方式，正常附件方式也都不能设置居中

**Comment by ruibaby** [comment]
See https://github.com/halo-dev/halo/issues/6557#issuecomment-2323885789

/close
