### ISSUE TITLE
halo专业版配置注册页面无手机号表单

### ISSUE THREAD

**Issue by IDamor** [halo-dev/halo#5954]
### 系统信息

版本
2.15.2
构建时间
2024-05-10 14:22
Git Commit
fba7d0a
Java
IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
数据库
MySQL Community Server - GPL / 8.2.0
操作系统
Linux 5.15.0-94-generic / amd64

### 使用的哪种方式运行？

Docker

### 发生了什么？

当专业版配置好短信通知后，打开用户注册开关与短信验证码登录，不勾选“注册验证手机号”，此时注册页面将其他信息填完后点击注册提示需要输入手机号，但此页面并无手机号输入表单

**Comment by ruibaby** [comment]
已经在 2.16.0 修复。

https://www.lxware.cn/docs/helpcenter/halo-pro/changlog#21602024-06-03

/close
