### ISSUE TITLE
S3 关联的文件，不能对文件设置分组

### ISSUE THREAD

**Issue by Tonmyn** [halo-dev/halo#5962]
### 你当前使用的版本

2.15.0

### 描述一下此特性

1、S3 关联的文件，不能对文件设置分组；
2、附件库在网格模式下，文件没有 “...” 按钮；
3、附件库希望能够调节网格模式下 文件的网格尺寸大小；

4、网站迁移后，文章的创建者都变成了当前管理员（已经通过切换用户，分批次导入解决此问题）
5、网站迁移后，原网站有CDN，原网站的附件路径为 "https://cdn.xxx.com/wp-content/uploads/xxx" ，迁移后所有附件的路径都变为了 “/wp-content/uploads/xxx/” ，按道理应该是路径变为 “/upload/wp-content/uploads/xxx/**” 才对（也许是我没有设置正确），最后导致在附件库中无法正常加载和调用（目前已经通过添加S3存储策略解决，但感觉有必要反馈一下）；

6、上传附件对话框，当存储策略名称过长时，“选择存储策略：”下面的按钮无法完整显示存储策略名称；
7、存储策略是否可以添加类似用户的权限，防止用户上传文件到限制之外的存储策略,类似仅可读和可读可写；

> 题外话：foxmail.com接收不到验证邮件；

**Comment by ruibaby** [comment]
感谢反馈问题，但请不要在一个 issue 里面同时反馈多个问题。我将关闭此 issue，建议分 issue 提交。

<img width="487" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/9da1216c-4c3a-4f01-84ec-d3defa37581f">

/close
