### ISSUE TITLE
性能优化

### ISSUE THREAD

**Issue by xxx252525** [halo-dev/halo#5963]
### 你当前使用的版本

 2.15.2

### 描述一下此特性

Halo运行的过程中，Java占用过高，对于轻量级的个人服务器不太友好，建议对Halo的性能进行优化，降低内存占用；例如2核心2G内存的云服务器，在安装使用Halo的过程中，Java的占用可以达到400MB+

### 附加信息

![图片](https://github.com/halo-dev/halo/assets/104115333/5e5af873-9714-4151-98b1-b3497635d278)
![图片](https://github.com/halo-dev/halo/assets/104115333/93880293-97b2-4819-9da7-03032f999d9b)

**Comment by ruibaby** [comment]
感谢反馈此问题，但当前因为受限于语言平台以及我们使用的 Web 框架，除非支持类似于 https://github.com/halo-dev/halo/issues/3215 提到的 GraalVM，否则内存基本上无法再进行降低，。如果你的服务器内存充足，建议忽略这个问题，内存本身就是需要拿来使用的，只要不会出现内存泄露的问题。

/triage unresolved

**Comment by coderstory** [comment]
对于java写的东西 400MB已经很少了  默认的镜像用的都是j9 我都是自己封装改成openjdk的
