### ISSUE TITLE
使用Daisyblocks，图库块的图片alt属性不能修改

### ISSUE THREAD

**Issue by lomiles** [halo-dev/halo#5964]
### 系统信息

- 外部访问地址: http://www.tengogo.com
- 启动时间: 2024-05-20 12:15
- 版本: 2.15.2
- 构建时间: 2024-05-10 14:22
- Git Commit: fba7d0a
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: MySQL Community Server - GPL / 8.0.37
- 操作系统: Linux / 5.15.0-106-generic
- 已激活主题: [Daisyblocks](https://www.halo.run/store/apps/app-WgWHe)
- 已启动插件:
  - [图库管理](https://github.com/halo-sigs/plugin-photos)
  - [Vditor 编辑器](https://github.com/justice2001/halo-plugin-vditor)
  - [站点推送插件](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker

### 发生了什么？

首页的图库块的图片，alt属性没有编辑入口，默认就是文件名，非常不利于官网的专业性形象，而且也无法被搜索引擎识别
![image](https://github.com/halo-dev/halo/assets/35911812/a7f11903-2473-4b19-b010-49b1b095dc5c)

**Comment by wan92hen** [comment]
图片名称是可以点击图库中的图片进行编辑的。
![image](https://github.com/halo-dev/halo/assets/27671436/9ddb5163-b824-46f0-bba6-38b71bda0a47)

**Comment by lomiles** [comment]
以前没发现，UE需要再完善。在我的chrome浏览器里，单击图片上半部分是选中（提示删除），单击下半部分才可以
