### ISSUE TITLE
1panel一键部署Halo之后访问网站网站渲染问题

### ISSUE THREAD

**Issue by xxx252525** [halo-dev/halo#5973]
### 系统信息

云服务器：
发行版本 rocky
系统类型 x86_64

1panel版本：1.10.7-lts
Halo版本：2.15.2

### 使用的哪种方式运行？

Docker

### 发生了什么？

使用1panel一键部署网站后，配置了域名，DNS、SSL等网站相关信息，网站已经通过备案，在访问网页的时候出现如下问题：
![图片](https://github.com/halo-dev/halo/assets/104115333/c4cd2c08-adfb-4638-909d-79b62b4188eb)

应该是CSS渲染的问题，查看openresty的目录，www目录下没有index文件，查看Halo目录下，相关的网站内容都在主题目录下，如何实现正常网页的渲染呢？

### 附加信息

公网访问正常网页如下：
![图片](https://github.com/halo-dev/halo/assets/104115333/cf5e0b41-fc6d-48f9-8efc-00b7adafba36)
---
域名访问如下：
![图片](https://github.com/halo-dev/halo/assets/104115333/f89e4c0b-a603-491c-992a-e80dab926df1)

**Comment by ruibaby** [comment]
建议检查你的 Nginx 配置，我们不知道你的 Nginx 配置情况，所以无法判断。

/triage needs-information
/kind support
