### ISSUE TITLE
feat: 分类目录层级展示在菜单下！！！（感叹号用于提醒）

### ISSUE THREAD

**Issue by James-Hao** [halo-dev/halo#598]
halo的开发大佬们好，有个分类层级的问题，我在hshan主题作者那里提到了，链接放在这里提醒一哈哈群主大佬！！！！！！
https://github.com/hshanx/halo-theme-hshan/issues/18 希望增加这个功能，thx！😂

**Comment by ruibaby** [comment]
已经支持，但是并不完美，这个等我们后面详细讨论之后再做改动。目前只是比较简单的实现了。

https://github.com/halo-dev/halo/pull/689

写法如下：

```
<@categoryTag method="tree">
    <ul>
        <#list categories as category>
            <li>
                <a href="${category.fullPath!}">
                    ${category.name!}
                </a>
            </li>

            <#if category.children?? && category.children?size gt 0>
                <@childCategories category.children></@childCategories>
            </#if>
        </#list>
    </ul>
</@categoryTag>

<#macro childCategories categories>
    <ul class="sub-category">
        <#list categories as category>
            <li>
                <a  href="${category.fullPath!}">
                    ${(category.name)!}
                </a>
                <#if category.children?? && category.children?size gt 0>
                    <@childCategories category.children></@childCategories>
                </#if>
            </li>
        </#list>
    </ul>
</#macro>
```

效果：

![Snipaste_2020-03-17_22-57-04](https://user-images.githubusercontent.com/21301288/76869213-f1445780-68a2-11ea-93d4-9216e6a1da25.png)

**Comment by James-Hao** [comment]
> 已经支持，但是并不完美，这个等我们后面详细讨论之后再做改动。目前只是比较简单的实现了。
> 
> #689
> 
> 写法如下：
> 
> ```
> <@categoryTag method="tree">
>     <ul>
>         <#list categories as category>
>             <li>
>                 <a href="${category.fullPath!}">
>                     ${category.name!}
>                 </a>
>             </li>
> 
>             <#if category.children?? && category.children?size gt 0>
>                 <@childCategories category.children></@childCategories>
>             </#if>
>         </#list>
>     </ul>
> </@categoryTag>
> 
> <#macro childCategories categories>
>     <ul class="sub-category">
>         <#list categories as category>
>             <li>
>                 <a  href="${category.fullPath!}">
>                     ${(category.name)!}
>                 </a>
>                 <#if category.children?? && category.children?size gt 0>
>                     <@childCategories category.children></@childCategories>
>                 </#if>
>             </li>
>         </#list>
>     </ul>
> </#macro>
> ```
> 
> 效果：
> 
> ![Snipaste_2020-03-17_22-57-04](https://user-images.githubusercontent.com/21301288/76869213-f1445780-68a2-11ea-93d4-9216e6a1da25.png)

感谢！
