### ISSUE TITLE
图片写入403、插入表格403（音频和视频403）

### ISSUE THREAD

**Issue by xxx252525** [halo-dev/halo#5988]
### System information

- 外部访问地址: http://localhost:8080
- 启动时间: 2024-05-25 15:41
- 版本: 2.15.2
- 构建时间: 2024-05-10 14:22
- Git Commit: fba7d0a
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: MySQL Community Server - GPL / 8.2.0
- 操作系统: Linux / 5.15.0-94-generic
- 已激活主题: [Theme Joe3](https://github.com/jiewenhuang/halo-theme-joe3.0)
- 已启动插件:
  - [图库管理](https://github.com/halo-sigs/plugin-photos)
  - [lightgallery.js 灯箱](https://github.com/halo-sigs/plugin-lightgallery)
  - AI 助手
  - [文章导入导出](https://jhacker.cn/2023/halo-plugin-export2doc)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [站点迁移](https://github.com/halo-sigs/plugin-migrate)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [Vditor 编辑器](https://github.com/justice2001/halo-plugin-vditor)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场](https://www.halo.run/store/apps/app-VYJbF)

### What is the project operation method?

Docker

### What happened?

# 问题
编写文章的时候，文章写入视频、图片、音频，插入表格均会出现403的错误。在1panle中暂未开启防盗链。

## 问题视频如下：

https://github.com/halo-dev/halo/assets/104115333/ab2b05cd-8d78-4c3d-b27f-13f3d10b30fb

### Relevant log output

```shell
文件写入403日志：
223.85.205.94 - - [25/May/2024:16:08:17 +0800] "GET /apis/api.console.halo.run/v1alpha1/attachments?page=1&size=60&ungrouped=false HTTP/2.0" 200 1143 "https://tiangesec.org.cn/console/posts/editor?name=5152aea5-c2e8-4717-8bba-2263d46e19d5" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
223.85.205.94 - - [25/May/2024:16:08:28 +0800] "PUT /apis/api.console.halo.run/v1alpha1/posts/5152aea5-c2e8-4717-8bba-2263d46e19d5/content HTTP/2.0" 403 16910 "https://tiangesec.org.cn/console/posts/editor?name=5152aea5-c2e8-4717-8bba-2263d46e19d5" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
223.85.205.94 - - [25/May/2024:16:08:28 +0800] "PUT /apis/api.console.halo.run/v1alpha1/posts/5152aea5-c2e8-4717-8bba-2263d46e19d5/content HTTP/2.0" 403 16910 "https://tiangesec.org.cn/console/posts/editor?name=5152aea5-c2e8-4717-8bba-2263d46e19d5" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
223.85.205.94 - - [25/May/2024:16:08:28 +0800] "PUT /apis/api.console.halo.run/v1alpha1/posts/5152aea5-c2e8-4717-8bba-2263d46e19d5/content HTTP/2.0" 403 16910 "https://tiangesec.org.cn/console/posts/editor?name=5152aea5-c2e8-4717-8bba-2263d46e19d5" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
223.85.205.94 - - [25/May/2024:16:08:29 +0800] "PUT /apis/api.console.halo.run/v1alpha1/posts/5152aea5-c2e8-4717-8bba-2263d46e19d5/content HTTP/2.0" 403 16910 "https://tiangesec.org.cn/console/posts/editor?name=5152aea5-c2e8-4717-8bba-2263d46e19d5" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
223.85.205.94 - - [25/May/2024:16:08:29 +0800] "PUT /apis/api.console.halo.run/v1alpha1/posts/5152aea5-c2e8-4717-8bba-2263d46e19d5/content HTTP/2.0" 403 16910 "https://tiangesec.org.cn/console/posts/editor?name=5152aea5-c2e8-4717-8bba-2263d46e19d5" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
223.85.205.94 - - [25/May/2024:16:08:29 +0800] "PUT /apis/api.console.halo.run/v1alpha1/posts/5152aea5-c2e8-4717-8bba-2263d46e19d5/content HTTP/2.0" 403 16910 "https://tiangesec.org.cn/console/posts/editor?name=5152aea5-c2e8-4717-8bba-2263d46e19d5" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
223.85.205.94 - - [25/May/2024:16:08:29 +0800] "PUT /apis/api.console.halo.run/v1alpha1/posts/5152aea5-c2e8-4717-8bba-2263d46e19d5/content HTTP/2.0" 403 16910 "https://tiangesec.org.cn/console/posts/editor?name=5152


无法访问日志：
https://tiangesec.org.cn/console/plugins
```

### Additional information

https://github.com/halo-dev/halo/assets/104115333/d9ffd1a6-0615-448e-aaf4-db8ece9541cb

## 日志文件：
[halo-log-2024-05-25 16_14.log](https://github.com/halo-dev/halo/files/15442291/halo-log-2024-05-25.16_14.log)

**Comment by JohnNiang** [comment]
/triage duplicate

Duplicates of https://github.com/halo-dev/halo/issues/4047

等待近期发布 2.16。

**Comment by ruibaby** [comment]
> /triage duplicate
> 
> Duplicates of #4047
> 
> 等待近期发布 2.16。

这看起来和 Halo 并没有什么关系，日志并无任何异常，保存文章出现 403 和保存失败基本可以确定是前置代理拦截。 @xxx252525 建议检查反向代理或者防火墙的配置和日志，如果要确定是否是 Halo 的问题，建议直接使用 ip 访问看看是否能够复现。

**Comment by 107064547** [comment]
我发现只要文章中带有链接，无法通过外网保存文章，会提示403，但是通过内网保存带链接的文章就没有任何问题，不知道什么原因。
WARN 7 --- [garbage-collector-controller-t-9] io.r2dbc.h2.H2Connection                 : Option{name='readOnly', sensitive=false} + isn't supported in H2 at the transaction level. You must set it on conenction URL. See http://www.h2database.com/html/features.html#read_only
这是一段log

**Comment by 107064547** [comment]
你是不是套了雷池之类的东西

**Comment by xxx252525** [comment]
使用腾讯云一键部署的，应该是没有雷池的，我自己没有安装，默认应该没有



***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "halo-dev/halo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月29日(星期三) 凌晨0:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [halo-dev/halo] 图片写入403、插入表格403（音频和视频403） (Issue #5988)





 
你是不是套了雷池之类的东西

**Comment by ruibaby** [comment]
@xxx252525 建议直接看浏览器中对应的接口返回内容。

**Comment by xxx252525** [comment]
> @xxx252525建议直接查看浏览器中对应的接口并返回内容。

找到问题了，是Halo默认的编辑器存在的问题，更换其他的markdown编辑器就能保存了，使用Halo默认的编辑器就无法保存，直接403，官方可以关注下Halo默认的文本编辑的问题

**Comment by xxx252525** [comment]
> 你是不是制定了雷池禁令

没有

**Comment by xxx252525** [comment]
> > /分类重复
> > #4047的重复项[](https://github.com/halo-dev/halo/issues/4047)
> > 等待近期发布 2.16。
> 
> 这看起来和 Halo 并没有什么关系，日志并没有任何异常，文章出现 403 和失败基本可以确定是前置代理拦截。@xxx252525建议检查漏洞代理或者防火墙的配置和日志，如果确定是否是 Halo 问题，建议直接使用 ip 访问看看是否能够复现。

![image](https://github.com/halo-dev/halo/assets/104115333/e6250e30-ef93-4f6e-a8b0-86160be36af0)

**Comment by xxx252525** [comment]
![image](https://github.com/halo-dev/halo/assets/104115333/bab0b3a9-f303-4d59-ae20-1b8810be06b3)
第三方的markdown编辑器也出现这个问题了

**Comment by ruibaby** [comment]
这可以肯定就是前置代理的拦截，建议不要在 Halo 这边耽搁太多时间。这种问题我们也无法帮助你排查，因为这没有统一的解决访问，每个用户的情况都可能不一样。

**Comment by ruibaby** [comment]
> 使用腾讯云一键部署的，应该是没有雷池的，我自己没有安装，默认应该没有

看 1Panel 的配置，尤其是 WAF 部分。

**Comment by xxx252525** [comment]
好的
