### ISSUE TITLE
网页中添加文件优化：能在页面直接添加word、pdf、Excel、文本等文件，目前只能从附件里添加，然后在添加到页面里。操作比较繁琐

### ISSUE THREAD

**Issue by huangxine** [halo-dev/halo#5991]
### Describe this feature

网页中添加文件优化：能在页面直接添加word、pdf、Excel、文本等文件，目前只能从附件里添加，然后在添加到页面里。操作比较繁琐

**Comment by ruibaby** [comment]
添加 word、pdf、excel 是需要在网页上显示吗？还是仅仅插入一个文件链接？

/area editor
/triage needs-information
/kind feature
