### ISSUE TITLE
2.15.2 页面跳转错误问题

### ISSUE THREAD

**Issue by ZJOBS** [halo-dev/halo#5992]
### 系统信息

- 外部访问地址: 
- 启动时间: 2024-05-21 09:36
- 版本: 2.15.2
- 构建时间: 2024-05-10 14:17
- Git Commit: 9a4c41a
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: PostgreSQL / 16.3 (Debian 16.3-1.pgdg120+1)
- 操作系统: Linux / 4.4.302+
- 已激活主题: [Hao](https://github.com/chengzhongxue/halo-theme-hao)
- 已启动插件:
  - [文本绘图](https://github.com/halo-sigs/plugin-text-diagram)
  - [KaTeX](https://github.com/halo-sigs/plugin-katex)
  - [Markdown / HTML 内容块](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [对象存储（Amazon S3 协议）](https://github.com/halo-dev/plugin-s3)
  - [ByteMD](https://github.com/ruibaby/plugin-bytemd)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [应用市场](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker

### 发生了什么？

博客主页页面跳转错误，明明是A文章，打开显示的却是B文章。此问题同时出现在管理端文章的预览按钮上

**Comment by cybaijie** [comment]
检查下你的两篇文章别名是不是还是默认的

**Comment by ZJOBS** [comment]
> 检查下你的两篇文章别名是不是还是默认的

别名已经叫“wei-ming-ming-wen-zhang”

**Comment by ruibaby** [comment]
有重复的别名，建议检查并修改为不同的。
