### ISSUE TITLE
更新到2.16.0-rc.1套了CDN以后无法正常登录和退出登录

### ISSUE THREAD

**Issue by UPToZ-Core** [halo-dev/halo#6002]
### 系统信息

- 外部访问地址: https://blog.uptoz.cn/
- 启动时间: 2024-05-28 12:05
- 版本: 2.16.0-rc.1
- 构建时间: 2024-05-27 17:02
- Git Commit: afabffc
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: MySQL Community Server - GPL / 8.4.0
- 操作系统: Linux / 4.4.302+
- 已激活主题: [Hao](https://gitea.uptoz.cn/UPToZ/halo-theme-hao)
- 已启动插件:
  - [Docsme](https://www.halo.run/store/apps/app-yffxw)
  - [爱发电插件](https://github.com/carolcoral/plugin-afdian)
  - [TinyTale小程序设置](https://github.com/jiewenhuang/halo-plugin-TinyTale)
  - [豆瓣](https://github.com/chengzhongxue/plugin-douban)
  - [朋友圈](https://github.com/chengzhongxue/plugin-friends)
  - [Meilisearch](https://github.com/Rainsheep/halo-plugin-meilisearch)
  - [对象存储（Amazon S3 协议）](https://github.com/halo-dev/plugin-s3)
  - [Umami](https://github.com/halo-sigs/plugin-umami)
  - [Vditor 编辑器](https://github.com/justice2001/halo-plugin-vditor)
  - [Metrics Graph](https://github.com/guqing/plugin-metrics-graph)
  - [文章导入导出](https://jhacker.cn/2023/halo-plugin-export2doc)
  - [Markdown / HTML 内容块](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [站点推送插件](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [ByteMD](https://github.com/ruibaby/plugin-bytemd)
  - [lightgallery.js 灯箱](https://github.com/halo-sigs/plugin-lightgallery)
  - [应用市场](https://www.halo.run/store/apps/app-VYJbF)
  - [我的装备管理](https://github.com/halo-sigs/plugin-equipments)
  - [OAuth2 认证](https://github.com/halo-sigs/plugin-oauth2)
  - [复制追加](https://github.com/turka-cn/plugin-copyadd)
  - [图库管理](https://github.com/halo-sigs/plugin-photos)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)

### 使用的哪种方式运行？

Docker

### 发生了什么？

通过CDN加速，无法正常登录和退出登录

### 相关日志输出

```shell
无
```

**Comment by JohnNiang** [comment]
Hi @UPToZ-Core , thank you for reaching out here!

/triage duplicate

Duplicates of https://github.com/halo-dev/halo/issues/6003

/close
