### ISSUE TITLE
后台所有文章页面，文章列表的批量功能在未筛选的情况下被禁用

### ISSUE THREAD

**Issue by LainNetWork** [halo-dev/halo#601]
- [x] 我已经安装了最新版的 Halo
  - [x] 我已经搜索了已有的 Issues 列表中有关的信息
  - [x] 我已经搜索了论坛中有关的信息：https://bbs.halo.run
  - [x] 我已经阅读了 Halo 的 FAQ：https://halo.run/archives/other-faq
## 我的环境

Server 版本：1.2.0
Admin 版本：1.2.0
数据库：H2
运行模式：production
UA 信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36
---

## 错误日志

无，前端bug

## 期望行为
进入文章管理页面，即可勾选文章列表，无论搜索框中是否筛选，都能进行批量操作

## 当前行为
进入文章管理页面，无法勾选文章列表，鼠标点击被禁用。但在筛选框中选择文章状态后，又能被勾选，重置选项后又进入无法勾选的状态
![image](https://user-images.githubusercontent.com/20994069/75422122-d1420800-5976-11ea-9afd-adfa7569d3c2.png)
![image](https://user-images.githubusercontent.com/20994069/75422422-7f4db200-5977-11ea-8665-3b31d4418961.png)

**Comment by ruibaby** [comment]
@LainNetWork 设定就是这样

**Comment by LainNetWork** [comment]
> @LainNetWork 设定就是这样

只能对筛选后的文章进行批量操作吗？

**Comment by ruibaby** [comment]
@LainNetWork 对，因为没有找到隐藏复选框的api，而且目前批量操作也只针对文章状态，后续会对此优化。

**Comment by LainNetWork** [comment]
> @LainNetWork 设定就是这样

感觉还蛮奇怪的。。按道理筛选和搜索应该不能影响本身的功能才对，我觉得这里不用做这么一个判断会更好一点。

**Comment by ruibaby** [comment]
@LainNetWork 是有点奇怪，后面我们会针对优化

**Comment by LainNetWork** [comment]
> @LainNetWork 是有点奇怪，后面我们会针对优化

好的，目测这个表格是elementUI？如果是的话把那个type = “selection”的<el-table-column>，里面塞一个v-if判断，或许可以实现你刚刚说的那个效果。如果不是的话当我没说（手动滑稽
顺便感谢你们的贡献，这个项目比我一年前来看的时候变化太大了。

**Comment by ruibaby** [comment]
@LainNetWork ant.design，确实没有找到隐藏的api，我本想加个 批量操作按钮，点击之后再显示复选框，这样的话 列表好看点
