### ISSUE TITLE
购买的表单插件突然无法使用

### ISSUE THREAD

**Issue by lomiles** [halo-dev/halo#6010]
### 系统信息

- 外部访问地址: https://www.tengogo.com
- 启动时间: 2024-05-25 05:18
- 版本: 2.15.2
- 构建时间: 2024-05-10 14:22
- Git Commit: fba7d0a
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: MySQL Community Server - GPL / 8.0.37
- 操作系统: Linux / 5.15.0-106-generic
- 已激活主题: [Daisyblocks](https://www.halo.run/store/apps/app-WgWHe)
- 已启动插件:
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [SEO 工具集](https://github.com/f2ccloud/plugin-seo-tools)
  - [图库管理](https://github.com/halo-sigs/plugin-photos)
  - 联系表单
  - [Vditor 编辑器](https://github.com/justice2001/halo-plugin-vditor)
  - [站点推送插件](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker

### 发生了什么？

之前设计的表单挂在官网上，突然发现表单没有了，看插件发现有问题
![image](https://github.com/halo-dev/halo/assets/35911812/a7e76b28-ade6-4153-86cf-a4fd05077487)

买的时候是开发环境，后来改到正式官网上面的

**Comment by JohnNiang** [comment]
Hi @lomiles, thank you for reaching out here!

建议提供一下应用市场插件的版本，如果不是最新的话，建议更新至最新版。

> https://www.halo.run/store/apps/app-VYJbF?tab=releases

/triage needs-information
