### ISSUE TITLE
markdown的流程图不显示

### ISSUE THREAD

**Issue by huangge1199** [halo-dev/halo#6016]
### Your current Halo version

2.15.2

### Describe this feature

下面是流程图的部分
![image](https://github.com/halo-dev/halo/assets/9335756/3bfa5034-b671-4d63-8992-fd0f00e62f7f)

我在后台管理的设置--代码注入--内容页 head 标签添加了下面的代码：
```
<script src="https://cdn.jsdelivr.net/npm/mermaid@8.4.4/dist/mermaid.min.js"></script>
```
但是流程图没有显示出来，还是原样子显示的
![image](https://github.com/halo-dev/halo/assets/9335756/369940bc-d0aa-4b0c-820e-5a07470f1d8e)

**Comment by ruibaby** [comment]
默认编辑器目前可以使用 https://www.halo.run/store/apps/app-ahBRi 插件，其他编辑器需要看编辑器的支持。Halo 本身并不提供这样的功能。

/kind support
