### ISSUE TITLE
安装 theme-hao 主题 500错误，其他主题正常

### ISSUE THREAD

**Issue by fanrujiang** [halo-dev/halo#6017]
### 系统信息

- 外部访问地址: https://blog.fanliu.top
- 启动时间: 2024-05-29 17:00
- 版本: 2.15.2
- 构建时间: 2024-05-10 14:17
- Git Commit: 9a4c41a
- Java: Java(TM) SE Runtime Environment / 17.0.8+9-LTS-211
- 数据库: MySQL Community Server (GPL) / 5.7.44
- 操作系统: Linux / 5.10.134-16.1.al8.x86_64
- 已激活主题: [Hao](https://github.com/chengzhongxue/halo-theme-hao)
- 已启动插件:
  - [Markdown / HTML 内容块](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [我的装备管理](https://github.com/halo-sigs/plugin-equipments)
  - [KaTeX](https://github.com/halo-sigs/plugin-katex)
  - [图库管理](https://github.com/halo-sigs/plugin-photos)
  - [追番插件](https://github.com/Roozenlz/plugin-bilibili-bangumi)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [站点推送插件](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [应用市场](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Fat Jar

### 发生了什么？

![微信图片_20240530104008](https://github.com/halo-dev/halo/assets/96752375/5b49b08d-59a2-480d-a243-829e8ae4c708)
![微信图片_20240530104014](https://github.com/halo-dev/halo/assets/96752375/af9cc936-3455-47b4-b01a-20b9fd0a60f7)
![微信图片_20240530104018](https://github.com/halo-dev/halo/assets/96752375/192bb260-7725-4353-8091-ca7f6b915a12)
原因是因为 MySQL 的 BLOB数据类型太小 hao主题的配置信息较多 将数据库的 data的BLOB类型改成 mediumblob 就可以了，望采纳
![PixPin_2024-05-30_10-43-34](https://github.com/halo-dev/halo/assets/96752375/2b9ed42d-b3cc-46c6-be45-1ed996416fb0)

**Comment by fanrujiang** [comment]
原因是因为 MySQL 的 BLOB数据类型太小 hao主题的配置信息较多 将数据库的 data的BLOB类型改成 mediumblob 就可以了，望采纳

**Comment by guqing** [comment]
我们已经在很早的版本就将 blob 类型改为了 longblob ，估计你是很早之前就初始化过的数据所以导致后续升级后类型没有同步，目前用的 r2dbc 的技术栈暂时有没有好的办法去自动同步类型而且以后也几乎不会存在数据类型改动因此目前这个问题只能手动改一下，可以改为 longblob
