### ISSUE TITLE
编辑页面能渲染Latex，但是实际浏览却无法渲染Latex

### ISSUE THREAD

**Issue by GeekHades1** [halo-dev/halo#602]
RT

**Comment by ruibaby** [comment]
@GeekHades1 你可以参考引入 Latex 依赖。 https://halo.run/archives/use-markdown#数学公式

**Comment by GeekHades1** [comment]
> @GeekHades1 你可以参考引入 Latex 依赖。 [https://halo.run/archives/use-markdown#数学公式](https://halo.run/archives/use-markdown#%E6%95%B0%E5%AD%A6%E5%85%AC%E5%BC%8F)

感谢！
