### ISSUE TITLE
更新`站点推送插件`失败，手动下载`站点推送插件`更新，出现无限报错并且页面无法访问

### ISSUE THREAD

**Issue by HowieHz** [halo-dev/halo#6027]
### 系统信息

- 外部访问地址: https://howiehz.top
- 启动时间: 2024-06-01 00:31
- 版本: 2.15.2
- 构建时间: 2024-05-10 14:22
- Git Commit: fba7d0a
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: mariadb.org binary distribution / 5.5.5-10.11.8-MariaDB-ubu2204
- 操作系统: Linux / 6.1.0-18-amd64
- 已激活主题: [彼岸-皓改](https://github.com/howiehz/halo-theme-higan-hz.git)
- 已启动插件:
  - [Vditor 编辑器](https://github.com/justice2001/halo-plugin-vditor)
  - [站点推送插件](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [Markdown / HTML 内容块](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [Metrics Graph](https://github.com/guqing/plugin-metrics-graph)
  - [Meilisearch](https://github.com/Rainsheep/halo-plugin-meilisearch)
  - [图库管理](https://github.com/halo-sigs/plugin-photos)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [通知我](https://github.com/monyuan/notify-me)
  - [OAuth2 认证](https://github.com/halo-sigs/plugin-oauth2)
  - [文章导入导出](https://jhacker.cn/2023/halo-plugin-export2doc)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [lightgallery.js 灯箱](https://github.com/halo-sigs/plugin-lightgallery)
  - [highlight.js 代码高亮](https://github.com/halo-sigs/plugin-highlightjs)
  - [Willow Markdown 编辑器](https://github.com/guqing/willow-mde)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker

### 发生了什么？

更新`站点推送插件`失败，手动下载`站点推送插件`更新，出现无限报错并且页面无法访问

### 附加信息

日志下载：https://wwp.lanzoul.com/ibaXg20dk6xa
一个错误之后引起了几个错误，裁剪不太好裁，干脆全部发上来了
推荐 ctrl+f `... 26 common frames omitted` 进行快速查看

**Comment by JohnNiang** [comment]
日志中的关键部分如下所示：

```java
halo  | 2024-06-01T00:31:23.317+08:00 ERROR 8 --- [oundedElastic-6] o.s.w.s.adapter.HttpWebHandlerAdapter    : [59bfb780-540] 500 Server Error for HTTP GET "/"
halo  | 
halo  | org.thymeleaf.exceptions.TemplateProcessingException: Error during execution of processor 'run.halo.app.theme.dialect.GlobalHeadInjectionProcessor' (template: "/fragments/layout" - line 3, col 3)
halo  | 	at org.thymeleaf.processor.element.AbstractElementModelProcessor.process(AbstractElementModelProcessor.java:141) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
halo  | 	at org.thymeleaf.util.ProcessorConfigurationUtils$ElementModelProcessorWrapper.process(ProcessorConfigurationUtils.java:649) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
halo  | 	at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1510) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
halo  | 	at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
halo  | 	at org.thymeleaf.engine.Model.process(Model.java:282) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
halo  | 	at org.thymeleaf.engine.Model.process(Model.java:290) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
halo  | 	at org.thymeleaf.engine.GatheringModelProcessable.process(GatheringModelProcessable.java:78) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
halo  | 	at org.thymeleaf.engine.ProcessorTemplateHandler.handleCloseElement(ProcessorTemplateHandler.java:1640) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
halo  | 	at org.thymeleaf.engine.CloseElementTag.beHandled(CloseElementTag.java:139) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
halo  | 	at org.thymeleaf.engine.Model.process(Model.java:282) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
halo  | 	at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1587) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
halo  | 	at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
halo  | 	at org.thymeleaf.engine.TemplateModel.process(TemplateModel.java:136) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
halo  | 	at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:592) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
halo  | 	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1103) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
halo  | 	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1077) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
halo  | 	at org.thymeleaf.spring6.SpringWebFluxTemplateEngine.lambda$createFullStream$0(SpringWebFluxTemplateEngine.java:198) ~[thymeleaf-spring6-3.1.2.RELEASE.jar:3.1.2.RELEASE]
halo  | 	at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:61) ~[reactor-core-3.6.5.jar:3.6.5]
halo  | 	at reactor.core.publisher.Mono.subscribe(Mono.java:4568) ~[reactor-core-3.6.5.jar:3.6.5]
halo  | 	at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.run(MonoSubscribeOn.java:126) ~[reactor-core-3.6.5.jar:3.6.5]
halo  | 	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.6.5.jar:3.6.5]
halo  | 	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.6.5.jar:3.6.5]
halo  | 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
halo  | 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
halo  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
halo  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
halo  | 	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
halo  | Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.stonewu.sitepush.SiteHeadProcessor' available
halo  | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:343) ~[spring-beans-6.1.6.jar:6.1.6]
halo  | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:334) ~[spring-beans-6.1.6.jar:6.1.6]
halo  | 	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1252) ~[spring-context-6.1.6.jar:6.1.6]
halo  | 	at run.halo.app.plugin.SpringExtensionFactory.lambda$create$0(SpringExtensionFactory.java:67) ~[classes/:2.15.2]
halo  | 	at java.base/java.util.Optional.map(Unknown Source) ~[na:na]
halo  | 	at run.halo.app.plugin.SpringExtensionFactory.create(SpringExtensionFactory.java:67) ~[classes/:2.15.2]
halo  | 	at org.pf4j.ExtensionWrapper.getExtension(ExtensionWrapper.java:37) ~[pf4j-3.10.0.jar:3.10.0]
halo  | 	at org.pf4j.AbstractPluginManager.getExtensions(AbstractPluginManager.java:971) ~[pf4j-3.10.0.jar:3.10.0]
halo  | 	at org.pf4j.AbstractPluginManager.getExtensions(AbstractPluginManager.java:580) ~[pf4j-3.10.0.jar:3.10.0]
halo  | 	at run.halo.app.plugin.ExtensionComponentsFinder.getExtensions(ExtensionComponentsFinder.java:38) ~[classes/:2.15.2]
halo  | 	at run.halo.app.theme.dialect.GlobalHeadInjectionProcessor.getTemplateHeadProcessors(GlobalHeadInjectionProcessor.java:93) ~[classes/:2.15.2]
halo  | 	at run.halo.app.theme.dialect.GlobalHeadInjectionProcessor.doProcess(GlobalHeadInjectionProcessor.java:75) ~[classes/:2.15.2]
halo  | 	at org.thymeleaf.processor.element.AbstractElementModelProcessor.process(AbstractElementModelProcessor.java:98) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
halo  | 	... 26 common frames omitted
```

当前问题可能和 https://github.com/halo-dev/halo/issues/5999 类似，已经被修复，预计在 2.16.0 中发布。

临时解决方案：进入 Console 后重新启用 SitePush 插件。如果还是不行的话，建议更新到 2.16.0-rc.2 后再试试。

/triage duplicate

Duplicates of https://github.com/halo-dev/halo/issues/5999

**Comment by HowieHz** [comment]
> 日志中的关键部分如下所示：
> 
> ```java
> halo  | 2024-06-01T00:31:23.317+08:00 ERROR 8 --- [oundedElastic-6] o.s.w.s.adapter.HttpWebHandlerAdapter    : [59bfb780-540] 500 Server Error for HTTP GET "/"
> halo  | 
> halo  | org.thymeleaf.exceptions.TemplateProcessingException: Error during execution of processor 'run.halo.app.theme.dialect.GlobalHeadInjectionProcessor' (template: "/fragments/layout" - line 3, col 3)
> halo  | 	at org.thymeleaf.processor.element.AbstractElementModelProcessor.process(AbstractElementModelProcessor.java:141) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
> halo  | 	at org.thymeleaf.util.ProcessorConfigurationUtils$ElementModelProcessorWrapper.process(ProcessorConfigurationUtils.java:649) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
> halo  | 	at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1510) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
> halo  | 	at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
> halo  | 	at org.thymeleaf.engine.Model.process(Model.java:282) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
> halo  | 	at org.thymeleaf.engine.Model.process(Model.java:290) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
> halo  | 	at org.thymeleaf.engine.GatheringModelProcessable.process(GatheringModelProcessable.java:78) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
> halo  | 	at org.thymeleaf.engine.ProcessorTemplateHandler.handleCloseElement(ProcessorTemplateHandler.java:1640) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
> halo  | 	at org.thymeleaf.engine.CloseElementTag.beHandled(CloseElementTag.java:139) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
> halo  | 	at org.thymeleaf.engine.Model.process(Model.java:282) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
> halo  | 	at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1587) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
> halo  | 	at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
> halo  | 	at org.thymeleaf.engine.TemplateModel.process(TemplateModel.java:136) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
> halo  | 	at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:592) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
> halo  | 	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1103) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
> halo  | 	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1077) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
> halo  | 	at org.thymeleaf.spring6.SpringWebFluxTemplateEngine.lambda$createFullStream$0(SpringWebFluxTemplateEngine.java:198) ~[thymeleaf-spring6-3.1.2.RELEASE.jar:3.1.2.RELEASE]
> halo  | 	at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:61) ~[reactor-core-3.6.5.jar:3.6.5]
> halo  | 	at reactor.core.publisher.Mono.subscribe(Mono.java:4568) ~[reactor-core-3.6.5.jar:3.6.5]
> halo  | 	at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.run(MonoSubscribeOn.java:126) ~[reactor-core-3.6.5.jar:3.6.5]
> halo  | 	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.6.5.jar:3.6.5]
> halo  | 	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.6.5.jar:3.6.5]
> halo  | 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
> halo  | 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
> halo  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
> halo  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
> halo  | 	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
> halo  | Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.stonewu.sitepush.SiteHeadProcessor' available
> halo  | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:343) ~[spring-beans-6.1.6.jar:6.1.6]
> halo  | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:334) ~[spring-beans-6.1.6.jar:6.1.6]
> halo  | 	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1252) ~[spring-context-6.1.6.jar:6.1.6]
> halo  | 	at run.halo.app.plugin.SpringExtensionFactory.lambda$create$0(SpringExtensionFactory.java:67) ~[classes/:2.15.2]
> halo  | 	at java.base/java.util.Optional.map(Unknown Source) ~[na:na]
> halo  | 	at run.halo.app.plugin.SpringExtensionFactory.create(SpringExtensionFactory.java:67) ~[classes/:2.15.2]
> halo  | 	at org.pf4j.ExtensionWrapper.getExtension(ExtensionWrapper.java:37) ~[pf4j-3.10.0.jar:3.10.0]
> halo  | 	at org.pf4j.AbstractPluginManager.getExtensions(AbstractPluginManager.java:971) ~[pf4j-3.10.0.jar:3.10.0]
> halo  | 	at org.pf4j.AbstractPluginManager.getExtensions(AbstractPluginManager.java:580) ~[pf4j-3.10.0.jar:3.10.0]
> halo  | 	at run.halo.app.plugin.ExtensionComponentsFinder.getExtensions(ExtensionComponentsFinder.java:38) ~[classes/:2.15.2]
> halo  | 	at run.halo.app.theme.dialect.GlobalHeadInjectionProcessor.getTemplateHeadProcessors(GlobalHeadInjectionProcessor.java:93) ~[classes/:2.15.2]
> halo  | 	at run.halo.app.theme.dialect.GlobalHeadInjectionProcessor.doProcess(GlobalHeadInjectionProcessor.java:75) ~[classes/:2.15.2]
> halo  | 	at org.thymeleaf.processor.element.AbstractElementModelProcessor.process(AbstractElementModelProcessor.java:98) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
> halo  | 	... 26 common frames omitted
> ```
> 
> 当前问题可能和 #5999 类似，已经被修复，预计在 2.16.0 中发布。
> 
> 临时解决方案：进入 Console 后重新启用 SitePush 插件。如果还是不行的话，建议更新到 2.16.0-rc.2 后再试试。
> 
> /triage duplicate
> 
> Duplicates of #5999

最后实际我重启了 halo，再之后手动更新了插件。
因 issue 标记为 Duplicates 并被声明已在 2.16.0-rc2 修复，故关闭。
PS: 我并没有尝试再次复现，如果再次出现类似的问题会重新打开这个issue。
