### ISSUE TITLE
后台管理模块编译主题

### ISSUE THREAD

**Issue by mwgPatrick** [halo-dev/halo#603]
我是自己打包halo部署在服务器中的，但是后台管理模块中修改主题颜色时，总是/color.less请求不到，经过排查是后端过滤器的原因，将路径替换为了/{admin-path}/color.less。 

目前本地是将/color.less排除在过滤器之外解决，同样的修改后端管理模块的前端文件亦可。

不知是我其他配置有误还是确实有此缺陷？

**Comment by ruibaby** [comment]
那就不要自己打包，最新的 release 已经说了，不要应用在线上环境：https://github.com/halo-dev/halo/releases

这个问题是已知问题，会在正式版修复。

**Comment by ruibaby** [comment]
那就不要自己打包，最新的 release 已经说了，不要应用在线上环境：https://github.com/halo-dev/halo/releases

这个问题是已知问题，会在正式版修复。

**Comment by mwgPatrick** [comment]
> 那就不要自己打包，最新的 release 已经说了，不要应用在线上环境：https://github.com/halo-dev/halo/releases
> 
> 这个问题是已知问题，会在正式版修复。

嗯嗯，多谢，因为我是想做一些自己的修改，所以选择源码打包的方式，先换旧版本进行测试。

**Comment by ruibaby** [comment]
> 嗯嗯，多谢，因为我是想做一些自己的修改，所以选择源码打包的方式，先换旧版本进行测试。

如果非要自己打包部署。建议切换到目前最新版：

```bash
git checkout v1.2.0
```
