### ISSUE TITLE
V2.16.0版本邮箱配置正确，但注册时候无法发送验证码

### ISSUE THREAD

**Issue by wenjing-xin** [halo-dev/halo#6030]
### 系统信息

- 外部访问地址: https://blog.wenjing.xin
- 启动时间: 2024-06-03 13:09
- 版本: 2.16.0
- 构建时间: 2024-06-03 11:12
- Git Commit: f8c1ed3
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: MySQL Community Server - GPL / 8.1.0
- 操作系统: Linux / 3.10.0-1160.114.2.el7.x86_64
- 已激活主题: [Hao 1.5.7](https://githubfast.com/liuzhihang/halo-theme-hao)
- 已启动插件:
  - [信息墙 1.0.0](https://blog.wenjing.xin/docs/halo-plugins/message-wall/introduce)
  - [静态网页服务 1.0.0-alpha.2](https://www.halo.run/store/apps/app-gFkMn)
  - [Tools工具箱 1.1.0](https://github.com/liuyiwuqing/halo-plugin-tools.git)
  - [无色界 1.0.0-v1alpha.1](https://github.com/guqing/halo-plugin-colorless)
  - [Vditor 编辑器 1.7.0](https://github.com/justice2001/halo-plugin-vditor)
  - [链接安全跳转中台 1.3.2](https://github.com/wenjing-xin/link-security-detect.git)
  - [爱发电插件 1.5.1](https://github.com/carolcoral/plugin-afdian)
  - [TinyTale小程序设置 1.0.4](https://github.com/jiewenhuang/halo-plugin-TinyTale)
  - [插件授权管理 1.0.5](https://github.com/liuyiwuqing/lywq-plugins-auth)
  - [SEO 工具集 1.0.5](https://www.halo.run/store/apps/app-FNGbT)
  - [增强备份（Backup IMproved） 1.1.1](https://www.halo.run/store/apps/app-dHakX)
  - [微信公众号发布 1.3.1](https://www.halo.run/store/apps/app-Dtuoa)
  - [Unsplash 1.1.0](https://github.com/halo-sigs/plugin-unsplash)
  - [豆瓣 1.1.7](https://github.com/chengzhongxue/plugin-douban)
  - [友链自助提交插件 1.4.1](https://github.com/liuyiwuqing/halo-plugin-links-submit)
  - [pangu 1.0.0](https://github.com/liuzhihang/plugin-pangu)
  - [OAuth2 认证 1.1.1](https://github.com/halo-sigs/plugin-oauth2)
  - [lightgallery.js 灯箱 1.2.0](https://github.com/halo-sigs/plugin-lightgallery)
  - [Meilisearch 1.2.0](https://github.com/Rainsheep/halo-plugin-meilisearch)
  - [Metrics Graph 1.0.0](https://github.com/guqing/plugin-metrics-graph)
  - [对象存储（Amazon S3 协议） 1.9.1](https://github.com/halo-dev/plugin-s3)
  - [KaTeX 2.0.1](https://github.com/halo-sigs/plugin-katex)
  - [追番插件 1.0.0](https://github.com/Roozenlz/plugin-bilibili-bangumi)
  - [我的装备管理 1.2.0](https://github.com/halo-sigs/plugin-equipments)
  - [朋友圈 1.3.2](https://github.com/chengzhongxue/plugin-friends)
  - [图库管理 1.3.0](https://github.com/halo-sigs/plugin-photos)
  - [链接管理 1.3.3](https://github.com/halo-sigs/plugin-links)
  - [Markdown / HTML 内容块 1.2.0](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [ByteMD 1.4.0](https://github.com/ruibaby/plugin-bytemd)
  - [Docsme 1.0.0-alpha.6](https://www.halo.run/store/apps/app-yffxw)
  - [文章导入导出 1.2.4](https://jhacker.cn/2023/halo-plugin-export2doc)
  - [瞬间 1.6.1](https://github.com/halo-sigs/plugin-moments)
  - [Sitemap 1.1.1](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.4.0](https://github.com/halo-dev/plugin-search-widget)
  - [RSS 1.2.2](https://github.com/halo-dev/plugin-feed)
  - [应用市场 1.2.0](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

![image](https://github.com/halo-dev/halo/assets/130843859/7a505f60-4389-4f02-96ee-06b6cfe51182)
邮箱配置有两个 ，测试邮箱的时候正常，而且两个一摸一样，在用户注册开启了邮箱校验的时候，报错 500 
![image](https://github.com/halo-dev/halo/assets/130843859/88435529-43ef-42e0-a56c-c16ef917c479)

**Comment by liuyiwuqing** [comment]
日志补充

**Comment by ruibaby** [comment]
请尝试升级到：Pro 2.16.2，https://www.lxware.cn/docs/helpcenter/halo-pro/changlog#21622024-06-05

**Comment by wenjing-xin** [comment]
> 请尝试升级到：Pro 2.16.2，https://www.lxware.cn/docs/helpcenter/halo-pro/changlog#21622024-06-05

升级之后邮件无法正常发送已解决，但是后台还是显示两个邮件通知配置选项，浏览器缓存已刷新，但还是无法解决
![image](https://github.com/halo-dev/halo/assets/130843859/83fd9de7-906e-457d-bcf7-4d1745024126)

**Comment by ruibaby** [comment]
> > 请尝试升级到：Pro 2.16.2，[lxware.cn/docs/helpcenter/halo-pro/changlog#21622024-06-05](https://www.lxware.cn/docs/helpcenter/halo-pro/changlog#21622024-06-05)
> 
> 升级之后邮件无法正常发送已解决，但是后台还是显示两个邮件通知配置选项，浏览器缓存已刷新，但还是无法解决 ![image](https://private-user-images.githubusercontent.com/130843859/337096304-83fd9de7-906e-457d-bcf7-4d1745024126.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNTkzNzEsIm5iZiI6MTcxODE1OTA3MSwicGF0aCI6Ii8xMzA4NDM4NTkvMzM3MDk2MzA0LTgzZmQ5ZGU3LTkwNmUtNDU3ZC1iY2Y3LTRkMTc0NTAyNDEyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMlQwMjI0MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMmRhZWUxODg5YWQ3N2VjYTRhOGQ5M2ZhOTRiN2ExODY0YzUyM2E2NDY1Njc5OGU2N2FiZjBhMzMzNzczZGVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.p1xBmOkkbFQbiZlGTyUn-VnlOYcFy8w_--acGMx6vZQ)

可以打开浏览器控制台看看：/apis/notification.halo.run/v1alpha1/notifierDescriptors 接口的返回内容。

**Comment by wenjing-xin** [comment]
> apis/notification.halo.run/v1alpha1/notifierDescriptors
返回了三项json，邮箱是重复的
![image](https://github.com/halo-dev/halo/assets/130843859/fc41905a-7a4b-4cce-9e65-11c9440a5304)

**Comment by ruibaby** [comment]
ping @guqing

**Comment by guqing** [comment]
> > apis/notification.halo.run/v1alpha1/notifierDescriptors
> > 返回了三项json，邮箱是重复的

你这个图看不全，点击 `Response` 然后复制粘贴到这里

**Comment by wenjing-xin** [comment]
> > > apis/notification.halo.run/v1alpha1/notifierDescriptors
> > > 返回了三项json，邮箱是重复的
> 
> 你这个图看不全，点击 `Response` 然后复制粘贴到这里

```json
{
    "page": 1,
    "size": 0,
    "total": 3,
    "items": [
        {
            "spec": {
                "displayName": "邮件通知",
                "description": "通过邮件将通知发送给用户",
                "notifierExtName": "halo-email-notifier",
                "senderSettingRef": {
                    "name": "notifier-setting-for-email",
                    "group": "sender"
                }
            },
            "apiVersion": "notification.halo.run/v1alpha1",
            "kind": "NotifierDescriptor",
            "metadata": {
                "name": "message-wall-email-notifier",
                "labels": {
                    "plugin.halo.run/plugin-name": "plugin-message-wall"
                },
                "version": 0,
                "creationTimestamp": "2024-06-10T07:06:14.673691441Z"
            }
        },
        {
            "spec": {
                "displayName": "短信通知",
                "description": "通过短信将通知发送给用户",
                "notifierExtName": "halo-sms-notifier",
                "senderSettingRef": {
                    "name": "notifier-setting-for-sms",
                    "group": "sender"
                }
            },
            "apiVersion": "notification.halo.run/v1alpha1",
            "kind": "NotifierDescriptor",
            "metadata": {
                "name": "default-sms-notifier",
                "labels": {
                    "halo.run/hidden": "true"
                },
                "version": 0,
                "creationTimestamp": "2024-04-20T14:17:26.049095932Z"
            }
        },
        {
            "spec": {
                "displayName": "邮件通知",
                "description": "通过邮件将通知发送给用户",
                "notifierExtName": "halo-email-notifier",
                "senderSettingRef": {
                    "name": "notifier-setting-for-email",
                    "group": "sender"
                }
            },
            "apiVersion": "notification.halo.run/v1alpha1",
            "kind": "NotifierDescriptor",
            "metadata": {
                "name": "default-email-notifier",
                "version": 0,
                "creationTimestamp": "2024-02-18T07:32:53.179157412Z"
            }
        }
    ],
    "first": true,
    "last": true,
    "hasNext": false,
    "hasPrevious": false,
    "totalPages": 1
}
```

**Comment by guqing** [comment]
> > > > apis/notification.halo.run/v1alpha1/notifierDescriptors
> > > > 返回了三项json，邮箱是重复的
> > 
> > 
> > 你这个图看不全，点击 `Response` 然后复制粘贴到这里
> 
> ```json
...
> ```

看这个数据的样子是你安装了一个名称叫做 `plugin-message-wall` 的插件创建出来的数据与 Halo 无关，建议去对应的插件提问

**Comment by wenjing-xin** [comment]
> > apis/notification.halo.run/v1alpha1/notifierDescriptors
> > 返回了三项json，邮箱是重复的
> > ```
> > ...
> > ```
> 
> 看这个数据的样子是你安装了一个名称叫做 `plugin-message-wall` 的插件创建出来的数据与 Halo 无关，建议去对应的插件提问

好的 谢谢！
