### ISSUE TITLE
Latex公式被吞掉{}

### ISSUE THREAD

**Issue by Guanzhou-Ke** [halo-dev/halo#604]
当我按照说明添加了以下代码在`head`中之后，行内公式可以正常显示，但是`$$ *** $$`包裹的公式会被吃掉`{}`例如我有一条公式是`$$ E = \sum_{i=0}^{n} $$`文章发布之后Latex公式无法显示并且出现了`$$E = \sum_^n$$`这样的情况，我将下面代码本地运行该公式时可以正常显示！这是否意味着某个环节处理掉了`{}`？但`mathjax`这个库我本地测试过没有问题的。
```
<script src="//cdn.jsdelivr.net/npm/mathjax@2.7.5/unpacked/MathJax.js?config=TeX-MML-AM_CHTML" defer></script>
    <script>
    document.addEventListener('DOMContentLoaded', function () {
        MathJax.Hub.Config({
            'HTML-CSS': {
                matchFontHeight: false
            },
            SVG: {
                matchFontHeight: false
            },
            CommonHTML: {
                matchFontHeight: false
            },
            tex2jax: {
                inlineMath: [
                    ['$','$'],
                    ['\\(','\\)']
                ],
                displayMath: [["$$", "$$"], ["\\[", "\\]"]]
            }
        });
    });
</script>
```

另外我使用`\{`这样的方式处理所有的`{}`后，公式得以正常现实，即`$$ E= \sum_\{i=0\}^\{n\}$$`

**Comment by ruibaby** [comment]
后端应该转义了 `{}`，这个确实是个问题。

**Comment by Smith-Cruise** [comment]
![image](https://user-images.githubusercontent.com/18729228/75604252-af30bd00-5b11-11ea-9513-1a120048fbb2.png)
![image](https://user-images.githubusercontent.com/18729228/75604262-ce2f4f00-5b11-11ea-9539-848cc01ecbcf.png)
我这边公式全都不能正常显示了，\\ 换行也全都被转义了。

**Comment by Smith-Cruise** [comment]
`&=` 发现也被转义了，这一块还是要好好审视下了。不然数学公式这块基本就没法用了，稍微复杂点的数学公式基本没法正常显示了。

**Comment by Smith-Cruise** [comment]
附带问题页面：https://www.inlighting.org/archives/amdahls-law-and-its-proof
