### ISSUE TITLE
无法备份文章markdown

### ISSUE THREAD

**Issue by carolin-violet** [halo-dev/halo#6041]
### 系统信息

- 外部访问地址: 
- 启动时间: 2024-05-20 17:36
- 版本: 2.15.2
- 构建时间: 2024-05-10 14:17
- Git Commit: 9a4c41a
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: H2 / 2.2.224
- 操作系统: Linux / 6.6.6-2401.0.1.oc9.4.x86_64
- 已激活主题: [Sakura](https://github.com/LIlGG/halo-theme-sakura.git)
- 已启动插件:
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker

### 发生了什么？

备份后没有备份文章markdown

**Comment by ruibaby** [comment]
1. 当前 Halo 默认的文章编辑不是 Markdown。
2. 备份不会将文章数据输出为文件，而是导出数据库的所有数据，请参考：https://docs.halo.run/user-guide/backup

如果你只是期望导出文章为 Markdown 文件，你可以使用：https://www.halo.run/store/apps/app-vWbpZ

/kind support
