### ISSUE TITLE
升级到2.16.0以后 新用户无法注册

### ISSUE THREAD

**Issue by liuhuongtao** [halo-dev/halo#6042]
### 系统信息

![image](https://github.com/halo-dev/halo/assets/137203821/5b20f7d4-29b9-4b5a-83c4-a52555eb9ad2)

### 使用的哪种方式运行？

Docker

### 发生了什么？

回退到2.15.2可以正常注册

**Comment by JohnNiang** [comment]
/triage duplicate

Duplicates of https://github.com/halo-dev/halo/issues/6034

/close
