### ISSUE TITLE
V2.16.1上传附件时 附件分组无效

### ISSUE THREAD

**Issue by xindi520** [halo-dev/halo#6047]
### 系统信息

基本信息
外部访问地址
https://blog.404n.cn
启动时间
2024-06-05 10:30
已激活主题
Hao
环境信息
版本
[2.16.1]
Git Commit
547a8b4
Java
IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
数据库
MySQL Community Server - GPL / 8.2.0
操作系统
Linux 6.1.0-21-cloud-amd64 / amd64
系统时区
Asia/Shanghai
系统语言
en_US

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

在上传附件图片时，已经提前选择分组信息，但是上传完成后附件还是显示“未分组”，需要手动移动。

**Comment by ruibaby** [comment]
能够提供一下详细的复现步骤吗？目前根据描述无法复现这个问题。

**Comment by xindi520** [comment]
在回复您之前升级到了2.16.3，再次测试的时候发现已经正常了🥲

**Comment by xindi520** [comment]
> 能够提供一下详细的复现步骤吗？目前根据描述无法复现这个问题。

现在测试已经恢复正常了，可能是当时环境有问题
