### ISSUE TITLE
2.16.2上传附件403与502

### ISSUE THREAD

**Issue by XJ814** [halo-dev/halo#6053]
### 系统信息

![1](https://github.com/halo-dev/halo/assets/46837334/49d7ecf7-7495-48a7-8203-bfae680dc101)

### 使用的哪种方式运行？

Docker

### 发生了什么？

2.16.2上传附件403最终导致崩溃网页打不开，只能重启服务器解决，排查许久最终回退2.15.2解决
![1](https://github.com/halo-dev/halo/assets/46837334/527ebdce-13ee-4522-953e-5d9fa83200d8)

**Comment by ruibaby** [comment]
看起来与 Halo 无关，建议检查你服务器的反向代理和防火墙设置。

/kind support

**Comment by ruibaby** [comment]
相关 issue：https://github.com/halo-dev/halo/issues?q=is%3Aissue+sort%3Aupdated-desc+%E9%98%B2%E7%81%AB%E5%A2%99+is%3Aclosed
