### ISSUE TITLE
希望可以设置TOTP在短时间内不需要再次输入

### ISSUE THREAD

**Issue by Oct-autumn** [halo-dev/halo#6054]
### 你当前使用的版本

 2.16.2

### 描述一下此特性

当前TOTP为每次登录时都需要输入，感觉有些麻烦，是否可以设计成成功登录后的一段时间内不需要再次进行TOTP认证？

预计需要修改的内容有：
- 数据库添加“用户最后一次操作的时间”字段
- 代码逻辑修改TOTP的触发逻辑

可以进一步开发的内容：
- 由用户自定义不需要进行TOTP认证的时长：禁用该功能~1周

**Comment by JohnNiang** [comment]
目前，Halo 2.16 已经支持了登录时“记住我”的功能，默认 14 天不会退出登录，重启也不会导致登录失效。

/triage needs-information

**Comment by Oct-autumn** [comment]
感谢回复，这确实是一个解决方案！
