### ISSUE TITLE
复制粘贴的文章,无法通过目录到文章对应位置

### ISSUE THREAD

**Issue by davidcrybao** [halo-dev/halo#6056]
### 系统信息

默认主题 ,Halo 2.16.3  Earth 1.8.0

### 使用的哪种方式运行？

Docker,

### 发生了什么？
文章内容是从外面复制过来,且编辑能正确显示H3-H4标题,
![23b0460c-5ac7-45ca-abf8-1dfd01f48268](https://github.com/halo-dev/halo/assets/25499165/05f30d62-a84d-4879-9820-25222cf0b2e1)

如果只有复制过来的内容,点击是无法跳转,
但当我收到添加一个标题,就可以正常跳转

文章无法通过目录到文章对应位置, 文章游览到下面,然后点击目录,自动跳转到最上面去了,不会跳到对应的位置
不知道是什么原因导致的,之前的版本没问题的,

### 附加信息

https://loserme.com/archives/dIizRrMY#  增加了H2标题,可以跳转

https://loserme.com/archives/M6a7frhR  复制过来的内容,标题是无法跳转

https://github.com/halo-dev/halo/assets/25499165/3d652400-19e4-4b15-abc6-efa78f4151da

**Comment by ruibaby** [comment]
我没有在 2.16.3 的默认编辑器上复现，你的编辑器是默认编辑器吗？

<img width="1442" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/dff4ceac-9e70-4e64-8eb5-b6d18e650f9c">

**Comment by davidcrybao** [comment]
> 我没有在 2.16.3 的默认编辑器上复现，你的编辑器是默认编辑器吗？
> 
> <img alt="image" width="1442" src="https://private-user-images.githubusercontent.com/21301288/338427382-dff4ceac-9e70-4e64-8eb5-b6d18e650f9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNzg0MzgsIm5iZiI6MTcxODA3ODEzOCwicGF0aCI6Ii8yMTMwMTI4OC8zMzg0MjczODItZGZmNGNlYWMtOWU3MC00ZTY0LThlYjUtYjZkMThlNjUwZjljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDAzNTUzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5NTYzYjkzZTUyMTg4YzNkZWYyMjVmMGE5NmE2NDYzNmJmYTc2NDA3M2Q4OTMzM2MzOGI3ZDc1MjE1NGVmMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TWhZWy8rZkug5l8T4dTDUDHA5JRKgDO6O-Scp9U2ZNI">

是的 使用的是默认编辑器

**Comment by davidcrybao** [comment]
@ruibaby 你好,已经通过视频重新复现操作了 期待更新解决这个问题

**Comment by ruibaby** [comment]
ping @LIlGG

**Comment by LIlGG** [comment]
/kind bug
/area ui
/area editor

应该是未处理直接粘贴后的文章标题导致的。

手动修改任意标题或者增加任意标题即可解决此问题。
