### ISSUE TITLE
模板中是否有判断当前用户是否登录后台的相关参数？

### ISSUE THREAD

**Issue by LainNetWork** [halo-dev/halo#606]
您好。我打算在主题的文章页面中，根据用户后台的登录状态来显示隐藏一个文章编辑按钮，点击它就可以快速跳转到后台对应的文章编辑页面。但是我在查阅文档和源代码后发现好像并没有相关的参数（包括获取用户后台路径配置的）我觉得这两个参数在模板中开放出来应该没什么关系，毕竟是在后端渲染的，不知道后期能否考虑开放出来？

**Comment by ruibaby** [comment]
@LainNetWork 暂无，既然你提到了，在下个版本发布前可以做一下。

**Comment by LainNetWork** [comment]
> @LainNetWork 暂无，既然你提到了，在下个版本发布前可以做一下。
刚刚我想了一下，，可能要实现还有点难，因为后台是前后端分离的，前端是在storage里面存储的token而不是cookie里的JSESSIONID，要想在渲染模板的时候获取状态好像有点不太现实，除非cookie里也存一份，改动还蛮大的

**Comment by ruibaby** [comment]
@LainNetWork 晚点我试试。

**Comment by JohnNiang** [comment]
@ruibaby 还记得我写了一个 one-time-token 么，可以向服务端申请一个 ott，追加到私密文章链接。

**Comment by LainNetWork** [comment]
> @LainNetWork 晚点我试试。

好的，感谢各位

**Comment by JohnNiang** [comment]
@LainNetWork 你可以通过 localStorage.getItem(halo__Access-Token) 来获取 token，如果存在，就直接跳转至文章编辑页面即可。

**Comment by LainNetWork** [comment]
> @LainNetWork 你可以通过 localStorage.getItem(halo__Access-Token) 来获取 token，如果存在，就直接跳转至文章编辑页面即可。

您的意思是说，渲染编辑按钮由前端js来完成吗？虽然也可以实现效果，不过这样判断不了token是否有效，而且如果要把主题给别人用的话，还是需要获取后台的入口地址。
我先用这个方法做吧，感谢你的答复

**Comment by ruibaby** [comment]
/close

目前 1.x 已经不打算对此做修改。2.0 请查阅 https://github.com/halo-dev/halo/issues/2676
