### ISSUE TITLE
希望默认编辑器中的代码块可以设置标题

### ISSUE THREAD

**Issue by 52lemon6** [halo-dev/halo#6065]
### 你当前使用的版本

2.16.2pro

### 描述一下此特性

希望默认编辑器中的代码块可以设置标题如图中这种，md是支持的
![image](https://github.com/halo-dev/halo/assets/40059643/e017abc0-f771-416b-a5b1-92dfc17d0b3e)

**Comment by ruibaby** [comment]
有相关的文档吗？方便我们知道这些代码块高亮库是如何处理的。

**Comment by LIlGG** [comment]
这可能并不是标题，而是指代代码块类型。

目前默认编辑器中的代码块是默认提供了 `language` 类型，用于提供给主题来手动检测代码块类型。

<img width="1666" alt="image" src="https://github.com/halo-dev/halo/assets/31335418/2062599f-138b-41ed-92cb-6a074295082c">

在主题端的展示效果如下：

<img width="855" alt="image" src="https://github.com/halo-dev/halo/assets/31335418/55d7d654-d9a5-45e4-a850-501674ef598e">

可能是你所使用的主题不支持显示。建议向主题提交 issue。
