### ISSUE TITLE
Typecho文章导入 插件报错

### ISSUE THREAD

**Issue by KleinerSource** [halo-dev/halo#6066]
### 系统信息

- 外部访问地址: 
- 启动时间: 2024-06-10 19:58
- 版本: 2.16.2
- 构建时间: 2024-06-07 11:51
- Git Commit: 7b2c8e4
- Java: IBM Semeru Runtime Open Edition / 21.0.3+9-LTS
- 数据库: mariadb.org binary distribution / 5.5.5-10.11.2-MariaDB-1:10.11.2+maria~ubu2204
- 操作系统: Linux / 5.10.60-qnap
- 已激活主题: [Hao 1.5.2](https://github.com/chengzhongxue/halo-theme-hao)
- 已启动插件:
  - [Typecho文章导入 1.0.2](https://github.com/mashirot/halo-plugin-typecho)
  - [爱发电插件 1.6.1](https://github.com/carolcoral/plugin-afdian)
  - [Unsplash 1.1.0](https://github.com/halo-sigs/plugin-unsplash)
  - [KaTeX 2.1.0](https://github.com/halo-sigs/plugin-katex)
  - [Markdown / HTML 内容块 1.2.0](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [Metrics Graph 1.0.0](https://github.com/guqing/plugin-metrics-graph)
  - [AI 助手 1.0.0](https://www.halo.run/store/apps/app-riNgb)
  - [图库管理 1.3.0](https://github.com/halo-sigs/plugin-photos)
  - [瞬间 1.6.1](https://github.com/halo-sigs/plugin-moments)
  - [Sitemap 1.1.1](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.4.0](https://github.com/halo-dev/plugin-search-widget)
  - [评论组件 2.2.0](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场 1.2.0](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

启动插件出错
![image](https://github.com/halo-dev/halo/assets/920875/0a61c2e3-5e87-4d85-a8d6-a0a4dcf73fc7)

**Comment by ruibaby** [comment]
这个问题建议向插件反馈：https://github.com/ShiinaKin/halo-plugin-typecho

> 数据库: mariadb.org binary distribution / 5.5.5-10.11.2-MariaDB-1:10.11.2+maria~ubu2204

此外，注意到你使用了 MariaDB 驱动，暂时建议更换为 MySQL 的驱动，请看：https://github.com/halo-dev/halo/issues/5534#issuecomment-2011499798

**Comment by KleinerSource** [comment]
> 这个问题建议向插件反馈：https://github.com/ShiinaKin/halo-plugin-typecho
> 
> > 数据库: mariadb.org binary distribution / 5.5.5-10.11.2-MariaDB-1:10.11.2+maria~ubu2204
> 
> 此外，注意到你使用了 MariaDB 驱动，暂时建议更换为 MySQL 的驱动，请看：[#5534 (comment)](https://github.com/halo-dev/halo/issues/5534#issuecomment-2011499798)

感谢提醒   我使用的是 mariadb数据库   驱动用的是 mysql的驱动 
--spring.r2dbc.url=r2dbc:pool:mysql://
--spring.sql.init.platform=mysql
