### ISSUE TITLE
Latex 公式异常

### ISSUE THREAD

**Issue by Smith-Cruise** [halo-dev/halo#607]
我看到之前有一个 issue 反馈过类似问题，我这里完整详细的反馈下，帮助开发人员一步到位解决 Latex 异常问题。

## 我的环境
Server 版本：1.2.0
Admin 版本：1.2.0
数据库：H2
运行模式：production
UA 信息：Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36
**均已经开启 Mathjax 插件**

---

## 问题1
Halo 后台会对 latex 公式进行转义，**导致前台无法正常显示，不过编辑后台是能够正常显示的**。
附上问题公式
```
$$
S=\frac{1}{1-a+\frac{a}{n}}
$$
```
![image](https://user-images.githubusercontent.com/18729228/75619121-9fb58080-5bb2-11ea-8a7d-bc04864a417a.png)

**后台编辑页面正常显示**
![image](https://user-images.githubusercontent.com/18729228/75619192-911b9900-5bb3-11ea-9928-58e8d6dc4815.png)

**但是前台页面显示异常**
![image](https://user-images.githubusercontent.com/18729228/75619196-a7c1f000-5bb3-11ea-9bbe-598646146010.png)

## 问题2
后台编辑器对有些 latex 公式显示也异常
附上问题公式，该公式我发表到掘金，简书上是正常的。本地的 Typora 也是正常显示的。
**这一块问题感觉是后台 markdown 编辑器对数学公式标准支持不同**，不知道后台编辑器的数学公式标准是什么。
```
$$
S=\frac{T}{T'}\\
T=t_n+t\\
T'=t_n+t'\\
f' = \frac{t}{T}=\frac{t}{t_n+t}\\
s'=\frac{t}{t'}\\
\frac{f'}{s'}=\frac{t}{t_n+t} \div \frac{t}{t'}=\frac{t'}{t_n+t}\\
$$
```
![image](https://user-images.githubusercontent.com/18729228/75619165-3a15c400-5bb3-11ea-98bf-61108e236690.png)

## 说明
附上我的问题页面：https://www.inlighting.org/archives/amdahls-law-and-its-proof 。
希望大佬能尽快解决下这类问题，不然像机器学习这块数学公式基本就没法正常显示了。

**Comment by ruibaby** [comment]
抱歉给你带来的困扰，目前你可以把数学公式这样写：

```markdown
    ```math

    ```
```

前台就可以正常显示了，不过问题就是后台编辑器无法解析。

**Comment by Smith-Cruise** [comment]
好，那我先这样应付下

**Comment by Smith-Cruise** [comment]
不过还是希望大佬能解决下这个问题，感觉 halo 做博客真的很合适，不想再换了。

**Comment by ruibaby** [comment]
@Smith-Cruise 会的。

**Comment by Smith-Cruise** [comment]
额，大佬另外问一个问题。我块状的数学公式按照你的处理能够正常使用，但是我行内数学公式该怎么弄。
我试了
```
`$Fraction_{enhanced}$`
``` 
这样子是不能正常显示的。

**Comment by ruibaby** [comment]
@Smith-Cruise 可以看这里，目前我们的后端解析用的 gitlab 的一套标准。https://docs.gitlab.com/ee/user/markdown.html#math

**Comment by Smith-Cruise** [comment]
使用  $\`$\sqrt{123}$\`$  可解决行内公式。

使用
\`\`\`math
$$
\sqrt{123}
$$
\`\`\`
可解决块状公式。
留下来给别人当做应急方案使用吧。

**Comment by hshanx** [comment]
大佬很厉害，点赞

**Comment by ysgncss** [comment]
就想选个支持markdown的，结果还是整半天

**Comment by ruibaby** [comment]
> 就想选个支持markdown的，结果还是整半天

？

**Comment by ysgncss** [comment]
使用 $`$\sqrt{123}$`$ 可解决行内公式。

使用
```math
$$
\sqrt{123}
$$
```
稳健！！！

**Comment by Jasonwi** [comment]
> 使用 $`$\sqrt{123}$`$ 可解决行内公式。
> 
> 使用
> ```math
> $$
> \sqrt{123}
> $$
> ```
> 可解决块状公式。
> 留下来给别人当做应急方案使用吧。

厉害，我试了好多下行内的比如`F_n=F_{n{-1}}+F_{n{-2}}(n\geq2)`也可以正常显示如`$F_n = F_{n-1} + F_{n-2} (n \geq 2)$`
行间的暂时就只有这一种解决方法了

**Comment by hshanx** [comment]
建议后端不渲染Markdown ，直接扔给前端处理@ruibaby

**Comment by Jasonwi** [comment]
@hshanx [MathJax公式解析问题讨论](https://bbs.halo.run/d/866-mathjax)

**Comment by hshanx** [comment]
> @hshanx [MathJax公式解析问题讨论](https://bbs.halo.run/d/866-mathjax)

我的这个真不是数学公式的问题，感觉就是Markdown渲染的问题

**Comment by Jasonwi** [comment]
@hshanx 这个讨论就是说markdown的问题啊

**Comment by SeanMWX** [comment]
> 使用 ‘ \sqrt{123}$`$ 可解决行内公式。
> 
> 使用 ```math $$ \sqrt{123} $$ ``` 可解决块状公式。 留下来给别人当做应急方案使用吧。

您好，这个行内公式的没有看懂，为什么我不行呢？
试了好多种：

<img width="1087" height="403" alt="Image" src="https://github.com/user-attachments/assets/7fdf19cb-7880-4625-8c47-85f04a17ab4f" />

<img width="453" height="410" alt="Image" src="https://github.com/user-attachments/assets/9a2429fc-7f51-45d5-9ee5-93f98f337678" />
