### ISSUE TITLE
希望管理控制台附件界面能够支持svg格式图片预览

### ISSUE THREAD

**Issue by eoser** [halo-dev/halo#6074]
### 你当前使用的版本

2.16.2

### 描述一下此特性

管理控制台界面附件页面，显示SVG图片没有用<img>标签包裹指向svg图片链接，直接使用了svg标签，导致无法预览svg图片，希望控制台前端页面能够添加img标签引用svg实现支持预览。
Wordpress等其他平台迁移过来的，很可能需要该功能，不支持的话不方便管理附件。

**Comment by ruibaby** [comment]
当前就是使用 img 标签加载 svg 的，没有复现你的问题。

<img width="1342" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/34791bb8-2169-4709-a480-c2dc7a34bac8">

/triage needs-information

**Comment by eoser** [comment]
我本地测试了下，应该是早期Wordpress导入问题，图片路径不符合现在的规范，文件类型识别为空，现在新上传的SVG图片上传到之前的Wordpress文件夹能正常显示。我对比检查了下我两种情况的文件资源路径，发现非常奇怪，属于奇怪的资源迁移导致的（我也不知道怎么回事），这个建议可以忽略了。

**Comment by ruibaby** [comment]
> 我本地测试了下，应该是早期Wordpress导入问题，图片路径不符合现在的规范，文件类型识别为空，现在新上传的SVG图片上传到之前的Wordpress文件夹能正常显示。我对比检查了下我两种情况的文件资源路径，发现非常奇怪，属于奇怪的资源迁移导致的（我也不知道怎么回事），这个建议可以忽略了。

如果是使用的 https://github.com/halo-sigs/plugin-migrate 插件导入的数据并且可以稳定复现的话，可以先在插件的仓库提交一个 issue。

/close
