### ISSUE TITLE
文章的侧边栏怎么增加文章目录 

### ISSUE THREAD

**Issue by aoaoclub** [halo-dev/halo#6075]
### Your current Halo version

1.1.3

### Describe this feature

文章的侧边栏怎么增加文章目录

**Comment by sunheyi6** [comment]
这个是看你的主题是否支持了，主题如果支持 设置一下 就可以显示了

**Comment by aoaoclub** [comment]
theme-fit2blog  我的主题是这个，哪看来我得去找主题问问了，谢
