### ISSUE TITLE
halo 后台里是否可以新增对附件库的附件进行维护性操作？

### ISSUE THREAD

**Issue by zyy2477** [halo-dev/halo#6078]
### 你当前使用的版本

2.16.1

### 描述一下此特性

在维护附件库的时候，发现附件库中有几个损坏的附件，提示加载异常（如下截图）。预览状态显示加载异常，在下面的URL链接中发现文件的 .png 后缀丢了。在F12调试中把预览的URL地址重新加上 .png 后缀就能正常显示了。

在前端页面中找到这个图片的文章，发现是能正常显示的。所以不知道这个 .png 是怎么丢掉的。除了删除重新上传，貌似没其他方式维护。

### 附加信息

![image](https://github.com/halo-dev/halo/assets/23225911/194241e3-0f11-4ba3-9672-4a605799a656)

**Comment by ruibaby** [comment]
理论上文件上传之后是不太可能去修改链接的，能够稳定复现这个问题吗？

/triage needs-information

**Comment by zyy247796143** [comment]
不知道如何复现。200多张附件图片里，就有2张这样。很久之前的图片了
