### ISSUE TITLE
已删除的附件还能访问，替换同名附件，展示的附件还是之前的。

### ISSUE THREAD

**Issue by Xiaotingwen** [halo-dev/halo#6088]
### 系统信息

基本信息
外部访问地址
https://blog.404n.cn
启动时间
2024-06-16 12:32
已激活主题

Hao
已启动插件
Tools工具箱
站点推送插件

链接安全跳转中台
静态网页服务

友链自助提交插件

爱发电插件

追番插件

豆瓣

朋友圈

AI 助手
应用市场

KaTeX
我的装备管理

Markdown / HTML 内容块
图库管理

链接管理
瞬间

OAuth2 认证
邮件通知

Tocbot 目录生成
站点迁移

对象存储（Amazon S3 协议）
StackEdit

ByteMD
RSS

搜索组件
评论组件

Sitemap

环境信息
版本
[2.16.3]
构建时间
2024-06-07 11:55
Git Commit
77f888d
Java
IBM Semeru Runtime Open Edition / 21.0.3+9-LTS
数据库
MySQL Community Server - GPL / 8.2.0
操作系统
Linux 6.1.0-21-cloud-amd64 / amd64
系统时区
Asia/Shanghai
系统语言
en_US

### 使用的哪种方式运行？

Docker

### 发生了什么？

https://blog.404n.cn/biaoqing/emoji.json
在静态网页插件中上传的文件，已经删除，且在1panel“文件”中已经看到没有文件了，但是文件地址还是能访问的。
在系统的附件插件中也有这个情况。尝试过关闭插件，删除插件，重启+halo，都不行。
![1](https://github.com/halo-dev/halo/assets/37939296/677c28c4-08ac-460f-a44a-00ae8161650b)
![2](https://github.com/halo-dev/halo/assets/37939296/816596e0-c8c6-42e5-abae-4023fa8b4ac2)

https://blog.404n.cn/upload/shangbanla.svg
此文件是上传到“附件”中，svg文件内容是已经更改成“听闻：上班啦”，在1panel和本地中都能看到已修改，但是直接访问附件地址和在“附件”中预览还是旧的内容。操作步骤是删除原文件，上传新的同名文件。
![3](https://github.com/halo-dev/halo/assets/37939296/628dcb8a-9113-4038-8d21-ea07eacfde7d)
![4](https://github.com/halo-dev/halo/assets/37939296/0278b7e2-bd32-4976-b7d9-cf364345c925)
![5](https://github.com/halo-dev/halo/assets/37939296/364d81f2-45d6-4593-9232-f81db1bcc971)

**Comment by IDamor** [comment]
是不是没清理NGINX反代缓存

**Comment by ruibaby** [comment]
建议检查一下浏览器以及 Nginx 反向代理缓存，你 issue 中已经提到了文件实际上已经被修改，那么和 Halo 可能无关。

/kind support
