### ISSUE TITLE
增加提供设置默认编辑器的设置选项

### ISSUE THREAD

**Issue by stars-one** [halo-dev/halo#6091]
### 你当前使用的版本

2.16.0

### 描述一下此特性

希望可以提供一个设置选项,用来设置每次新建文章使用的编辑器(如使用的其他的第三方编辑器插件)

目前每次切换都要自行更改编辑器有些繁琐

**Comment by chengzhongxue** [comment]
这个想法不错

**Comment by wan92hen** [comment]
我记得之前新建文章时是会使用上次选择的编辑器的。

**Comment by wan92hen** [comment]
> > 我记得之前新建文章时是会使用上次选择的编辑器的。
> 
> 我本来也以为是记住了选择的，但是好像没有。
> 
> /kind improvement /area ui

我看浏览器本地存储里是有相关 key 存这个信息的，印象中也有过这样的体验 😢

**Comment by LIlGG** [comment]
> > 我记得之前新建文章时是会使用上次选择的编辑器的。
> 
> 我本来也以为是记住了选择的，但是好像没有。
> 
> /kind improvement /area ui

总感觉自动保存失效可能与这个有关系，都与 localstore 相关，有可能是依赖升级的问题。

**Comment by ruibaby** [comment]
> > > 我记得之前新建文章时是会使用上次选择的编辑器的。
> 
> > 
> 
> > 我本来也以为是记住了选择的，但是好像没有。
> 
> > 
> 
> > /kind improvement /area ui
> 
> 
> 
> 总感觉自动保存失效可能与这个有关系，都与 localstore 相关，有可能是依赖升级的问题。
> 
> 
> 
> <img width="526" alt="image" src="https://github.com/halo-dev/halo/assets/31335418/47b4350c-cb3e-4960-9f6e-b971371d774e">
> 
> 

我会检查一下。
