### ISSUE TITLE
期望支持隐藏文章分类

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#6093]
### 你当前使用的版本

2.16.3

### 描述一下此特性

RT，期望文章分类支持设置隐藏分类，即设置之后，不会在前台任何分类列表，文章列表主动出现相关的文章和分类。只能通过 `/categories/{slug}` 访问。

原因：

1. 在某些类型的网站中，可能会使用分类归档页面（`/categories/{slug}`）将一部分文章内容作为单独的领域，比如帮助中心、版本发布日志、公告等。然后这些分类的文章就可能不再适合放在首页的文章列表中。尤其是目前主题能够为不同的分类场景单独设置渲染模板。
2. 比如 Halo 官网后续可能会提供案例中心页面，但这些案例文章并不期望出现在 https://www.halo.run/archives

/area core
/milestone 2.17.x
/kind feature
/kind api-change

**Comment by guqing** [comment]
与之关联性较强的 issue #3374
