### ISSUE TITLE
期望 FormKit 的 list 输入框能支持动态添加元素

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#6098]
### 你当前使用的版本

2.16.3

### 描述一下此特性

目前我们在表单定义中支持了 Repeater，但只能定义为对象的数组，但某些场景下，我们可能只期望得到简单类型的数组，比如在主题配置中选择一批文章分类的 name，目前只能通过 Repeater 得到类似于 `[ { name: 'foo' }, { name: 'bar' } ]` 的结构，实际上只需要 `[ 'foo', 'bar' ]`。所以期望扩展一些 FormKit 的原生 List 组件，能够支持和 Repeater 一样的动态添加/排序/删除元素。

<img width="626" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/473ba7bc-fcd2-420f-89df-7eb75b1f3503">

/area ui
/kind feature

**Comment by bynowi** [comment]
当前版本可以使用插件扩展这个表单类型吗
