### ISSUE TITLE
图片延迟加载标签

### ISSUE THREAD

**Issue by IDamor** [halo-dev/halo#6105]
### 你当前使用的版本

2.16.3

### 描述一下此特性

可否将图片标签新增一个延迟加载的属性，loading="lazy"，目前很多浏览器都支持这个属性了

**Comment by LIlGG** [comment]
是指在主题中添加这个属性还是在默认编辑器中添加？如果是主题中的话可以向主题作者提交 issue。

如果是默认编辑器中的话，可能需要讨论一下是否需要添加此功能。

**Comment by IDamor** [comment]
> 是指在主题中添加这个属性还是在默认编辑器中添加？如果是主题中的话可以向主题作者提交 issue。
> 
> 如果是默认编辑器中的话，可能需要讨论一下是否需要添加此功能。

是默认编辑器
