### ISSUE TITLE
服务运行后，后台java进程有明文信息显示，包括数据库密码等

### ISSUE THREAD

**Issue by lengchuanwen** [halo-dev/halo#6107]
### 你当前使用的版本

 2.16.3

### 描述一下此特性

服务运行后，后台java进程有显示docker-compose.yaml文件的command:参数，包含数据库密码等信息
<img width="1019" alt="java后台" src="https://github.com/halo-dev/halo/assets/88364485/186545e2-1d30-4ef9-a573-dcc0835c16a4">
不知开发者是否有注意到，或者是否有解决办法，谢谢！

**Comment by ruibaby** [comment]
如果你是使用容器编排的数据库并且不将其暴露到公网，这应该是不会有什么问题的。当前是有什么安全上的顾虑吗？

> 或者是否有解决办法，谢谢！

如果只是需要在进程中不显示，你可以手动外挂配置文件，可以参考：https://docs.halo.run/getting-started/install/jar-file#:~:text=%E5%86%85%E5%AE%B9%E5%A4%8D%E5%88%B6%E5%88%B0-,application.yaml,-%E4%B8%AD%EF%BC%8C%E6%A0%B9%E6%8D%AE%E4%B8%8B%E9%9D%A2

或者使用 Docker env file：https://docs.docker.com/compose/environment-variables/set-environment-variables/#use-the-env_file-attribute

/kind support
