### ISSUE TITLE
feat: 重构文章 meta 关键词和描述的生成

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#611]
## 概述

RT

## 详细解释

现在文章 meta 关键词固定取的标签列表，description 取的文章摘要信息，这样很不方便用户自己定义。

现在需要讨论如何让用户自己定义关键词和描述，解决了这一点，就可以实现 `<!--more-->` 标签形式的摘要了。

方案一：

文章表新增：meta_keywords 和 meta_description 字段，这样做的好处是可以使用 flyway 进行迁移，把 summary 字段的数据拷贝到 meta_description。

方案二：

使用之前提供的 metas 表，但是这样的话无法在升级到新版本的时候进行迁移。可能导致用户的所有文章都没有 keywords 和 description。

**Comment by JohnNiang** [comment]
我们是否可以通过扩展 Markdown 渲染器来完成自定义摘要的获取？

**Comment by ruibaby** [comment]
可以，但是我之前是这样做的：

伪代码：

```
String[] split = content.split("<!--more-->");

if(split.length==2){
     post.setSummary(MarkdownUtils.render(split[0]));
}
```

这样做的问题在于，生成的 summary 是 html 格式的，放在 <meta name="description" content=""> 会打乱页面的布局，所以 seo 的描述就不能取摘要了。
