### ISSUE TITLE
建议新增页面时候能够设置默认的别名规则

### ISSUE THREAD

**Issue by UPToZ-Core** [halo-dev/halo#6118]
### 你当前使用的版本

2.16.3

### 描述一下此特性

像文章那样支持设置默认的别名规则

### 附加信息

![image](https://github.com/halo-dev/halo/assets/73866989/442844a2-f131-4407-a41c-3a7f19878b29)

**Comment by ruibaby** [comment]
当前的页面设计应该是独立的页面，比如关于、联系我们等。这些页面通常会主动去设置别名，以保证访问路径有一定的辨识度。你这边有什么特别的场景需要自动生成别名吗？

/priority awaiting-more-evidence
