### ISSUE TITLE
移除默认评论插件后在侧边栏的功能区依旧显示评论

### ISSUE THREAD

**Issue by Einstein-schrodinger** [halo-dev/halo#6119]
### 系统信息

2.16.3

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

移除默认评论插件后在侧边栏的功能区依旧显示评论

**Comment by ruibaby** [comment]
当前评论插件的作用仅仅是为主题提供统一的评论区域，由主题自行实现的侧边栏评论无法由插件或者 Halo 控制，建议向主题反馈。

/kind support

**Comment by Einstein-schrodinger** [comment]
> 当前评论插件的作用仅仅是为主题提供统一的评论区域，由主题自行实现的侧边栏评论无法由插件或者 Halo 控制，建议向主题反馈。
> 
> /kind support

功能区的 评论 不是由默认评论插件提供的吗，比如关闭瞬间插件之后功能区就不再显示 瞬间 了，同样的关闭评论插件之后，功能区的 评论 也应该不再显示
![image](https://github.com/halo-dev/halo/assets/62790820/7f4a6664-6616-4e27-9b49-4efc1ac053a8)

**Comment by ruibaby** [comment]
> 当前[评论插件](https://github.com/halo-dev/plugin-comment-widget/)的作用仅仅是为主题提供统一的评论区域

上面已经说了，评论插件只是提供 UI，评论的数据支持由 Halo 内置。相关讨论可见：https://github.com/halo-dev/halo/issues/5835
