### ISSUE TITLE
为什么最新下载lastest默认是1.4.16。

### ISSUE THREAD

**Issue by LofiSu** [halo-dev/halo#6121]
### 系统信息

![2ca2fde8ce92d9d631df5b4f054cbdb7](https://github.com/halo-dev/halo/assets/163713803/867bbdaa-2805-48a0-8672-b5dd3e53c3ba)
![066be81896a2de3e90c614f2ce253b24](https://github.com/halo-dev/halo/assets/163713803/99e14ba2-c259-48b0-888e-543f046db089)

### 使用的哪种方式运行？

Docker

### 发生了什么？

下latest默认是1.4.16

**Comment by ruibaby** [comment]
从 Halo 2 开始，我们不再更新 latest 标签，原因可见：https://docs.halo.run/getting-started/install/docker-compose#%E5%88%9B%E5%BB%BA%E5%AE%B9%E5%99%A8%E7%BB%84

/kind support
