### ISSUE TITLE
请问支持多语言比如中英文切换吗

### ISSUE THREAD

**Issue by qianyucc** [halo-dev/halo#6125]
### 描述一下此特性

后台配置多语言切换

**Comment by ruibaby** [comment]
不支持，当前多语言的的范围仅仅在固定的 UI 元素上，比如 Console 和主题的固定元素，目前所有持久化的数据都无法支持多语言。

具体可以关注：https://github.com/halo-dev/rfcs/issues/6

/triage duplicate
