### ISSUE TITLE
新增文章分类添加“保存并继”

### ISSUE THREAD

**Issue by SerMs** [halo-dev/halo#6127]
### Your current Halo version

2.16

### Describe this feature

文章得分类和标签如果有个批量插入是否会更方便？或者在添加页面下方再加一个“保存并继续添加”的按钮是否会更好？
![image](https://github.com/halo-dev/halo/assets/67584847/60b4cdff-99ef-4137-a5d1-8c62085238d7)

**Comment by LonelySnowman** [comment]
我有意向完成这个 PR 😀
/assign
