### ISSUE TITLE
希望能够添加给文章 自动保存 的功能设计

### ISSUE THREAD

**Issue by Preke-Li** [halo-dev/halo#6129]
### 你当前使用的版本

 2.16.2

### 描述一下此特性

希望能给文章添加一个字段保存的设置选项，可以自定义自动保存的设置规则。当然能用自动保持就已经很不错了。由于自己平常使用typoar写文章习惯了自动保存,所有没有保存的习惯。在用博客写的时候，也没保存，直接关机了。有的时候开机重新打开会有提示恢复缓存，但是今天我打开了没有提示恢复缓存。这无疑是由于我个人的不良习惯造成的后果，于是我想着是否能够给文章一个自动保存的设置，能够更加方便我们用户写文章。

**Comment by ruibaby** [comment]
感谢反馈，这应该是 2.16 的问题，本身是有自动保存在浏览器和自动保存到数据库的。

/milestone 2.17.x
/kind bug
/area ui
/assign @LIlGG
