### ISSUE TITLE
新建一个'关于我'页面，怎样去掉 '新建页面' 选项中URL的/s/

### ISSUE THREAD

**Issue by haodedong** [halo-dev/halo#613]
- 我已经安装了最新版的 Halo
  - 我已经搜索了已有的 Issues 列表中有关的信息
  - 我已经搜索了论坛中有关的信息：https://bbs.halo.run
  - 我已经阅读了 Halo 的 FAQ：https://halo.run/archives/other-faq

## 我的环境
docker 部署，使用mysql，mysql版本5.7

---

## 错误日志

没报错

---

## 期望行为
可以正常创建关于我 页面，url地址为 http:xxx:8090/about  
而不是http:8090/s/about

## 当前行为

![image](https://user-images.githubusercontent.com/28796955/75862140-6a6e9400-5e39-11ea-9593-82ebd0a795c9.png)

**Comment by haodedong** [comment]
![image](https://user-images.githubusercontent.com/28796955/75862723-524b4480-5e3a-11ea-94fa-311d15ffafc5.png)

**Comment by haodedong** [comment]
github显示图片，需要翻墙

**Comment by ruibaby** [comment]
没办法，必须要有一个根地址，所以无法去掉，但是下个版本你可以自己修改这个 `s`。

![Snipaste_2020-03-04_17-33-45](https://user-images.githubusercontent.com/21301288/75865320-54af9d80-5e3e-11ea-9ab9-fb7feea73794.png)
