### ISSUE TITLE
如何防止网站被爬虫攻击

### ISSUE THREAD

**Issue by juanmaocxy** [halo-dev/halo#6144]
### Describe this feature

我做一个新闻网站，里面会有很多的图片，如何可以做到防爬虫攻击，因为图片的流量也不少

**Comment by ruibaby** [comment]
虽然这样的功能可以在 Halo 或者插件中实现，但这可能并不是 Halo 的实现目标，因为通常前置的反向代理或者 WAF 之类的工具可以更加高效和灵活的处理。

/kind support
