### ISSUE TITLE
jar包部署80端口日志提示占用

### ISSUE THREAD

**Issue by ROCKET2676** [halo-dev/halo#6149]
### System information

其实80没占用，nginx80可以正常启动。但是启动jar包80用不了，其它端口可以

### What is the project operation method?

Fat Jar

### What happened?

***************************
APPLICATION FAILED TO START
***************************

Description:

Web server failed to start. Port 80 was already in use.

Action:

Identify and stop the process that's listening on port 80 or configure this application to listen on another port.

**Comment by ruibaby** [comment]
建议检查你的 Nginx 进程，很可能没有完全关闭，可能有守护进程。

/kind support
/triage unresolved

**Comment by ROCKET2676** [comment]
没装nginx，后来nginx装上可以直接用，我用nginx 反向代理了

---- 回复的原邮件 ----
| 发件人 | Ryan ***@***.***> |
| 发送日期 | 2024年06月26日 21:26 |
| 收件人 | halo-dev/halo ***@***.***> |
| 抄送人 | ROCKET2676 ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [halo-dev/halo] jar包部署80端口日志提示占用 (Issue #6149) |

建议检查你的 Nginx 进程，很可能没有完全关闭，可能有守护进程。

/kind support
/triage unresolved

**Comment by ROCKET2676** [comment]
没装nginx 前，80端口没被监听，但是启动jar 包，报80端口被占用

---- 回复的原邮件 ----
| 发件人 | Ryan ***@***.***> |
| 发送日期 | 2024年06月26日 21:26 |
| 收件人 | halo-dev/halo ***@***.***> |
| 抄送人 | ROCKET2676 ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [halo-dev/halo] jar包部署80端口日志提示占用 (Issue #6149) |

建议检查你的 Nginx 进程，很可能没有完全关闭，可能有守护进程。

/kind support
/triage unresolved

**Comment by ruibaby** [comment]
这个问题只能靠你自己在服务器上检查，这个问题不属于 Halo 的解决范围，我们无法得知你服务器的具体情况。

/close
