### ISSUE TITLE
跨大版本升级

### ISSUE THREAD

**Issue by graveskeeper** [halo-dev/halo#6154]
### Your current Halo version

1.4.17

### Describe this feature

请问1.4.17版本的halo升级2.16.3如何操作呢？备份数据好像不能直接恢复，有没有工具可以完成跨越大版本的数据升级呢？或者需要先升级到哪个版本的数据格式，再升级至最新版本？有没有这样的方法可以解决问题？

**Comment by JohnNiang** [comment]
Please refer to <https://docs.halo.run/getting-started/migrate-from-1.x>.

/close
/kind support
