### ISSUE TITLE
文章别名生成策略选择short uuid未生效

### ISSUE THREAD

**Issue by UPToZ-Core** [halo-dev/halo#6155]
### 系统信息

- 外部访问地址: https://blog.uptoz.cn/
- 启动时间: 2024-06-26 13:35
- 版本: 2.16.3
- 构建时间: 2024-06-14 12:48
- Git Commit: 6e1f0f3
- Java: IBM Semeru Runtime Open Edition / 21.0.3+9-LTS
- 数据库: MySQL Community Server - GPL / 8.4.0
- 操作系统: Linux / 4.4.302+
- 已激活主题: [Hao 1.0.3-ce](https://gitea.uptoz.cn/UPToZ/halo-theme-hao)
- 已启动插件:
  - [lightgallery.js 灯箱 1.2.0](https://github.com/halo-sigs/plugin-lightgallery)
  - [Data Studio（数据工厂） 1.0.0-alpha.2](https://github.com/halo-sigs/plugin-data-studio)
  - [Docsme 1.0.0-alpha.6](https://www.halo.run/store/apps/app-yffxw)
  - [爱发电插件 1.1.0](https://github.com/carolcoral/plugin-afdian)
  - [TinyTale小程序设置 1.0.4](https://github.com/jiewenhuang/halo-plugin-TinyTale)
  - [豆瓣 1.1.7](https://github.com/chengzhongxue/plugin-douban)
  - [Meilisearch 1.2.0](https://github.com/Rainsheep/halo-plugin-meilisearch)
  - [对象存储（Amazon S3 协议） 1.9.1](https://github.com/halo-dev/plugin-s3)
  - [Umami 1.2.0](https://github.com/halo-sigs/plugin-umami)
  - [Vditor 编辑器 1.7.0](https://github.com/justice2001/halo-plugin-vditor)
  - [Metrics Graph 1.0.0](https://github.com/guqing/plugin-metrics-graph)
  - [文章导入导出 1.2.4](https://jhacker.cn/2023/halo-plugin-export2doc)
  - [Markdown / HTML 内容块 1.2.0](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [站点推送插件 1.5.1](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [ByteMD 1.4.0](https://github.com/ruibaby/plugin-bytemd)
  - [应用市场 1.2.0](https://www.halo.run/store/apps/app-VYJbF)
  - [我的装备管理 1.2.0](https://github.com/halo-sigs/plugin-equipments)
  - [OAuth2 认证 1.1.1](https://github.com/halo-sigs/plugin-oauth2)
  - [复制追加 1.2.0](https://github.com/turka-cn/plugin-copyadd)
  - [图库管理 1.3.0](https://github.com/halo-sigs/plugin-photos)
  - [链接管理 1.4.0](https://github.com/halo-sigs/plugin-links)
  - [瞬间 1.6.2](https://github.com/halo-sigs/plugin-moments)
  - [RSS 1.2.2](https://github.com/halo-dev/plugin-feed)
  - [搜索组件 1.4.0](https://github.com/halo-dev/plugin-search-widget)
  - [Sitemap 1.1.1](https://github.com/halo-dev/plugin-sitemap)

### 使用的哪种方式运行？

Docker

### 发生了什么？

文章别名生成策略选择short uuid，然后新建文章，直接保存，点开设置，发现默认生成的别名是时间戳，非我设置的short uuid，需要点击旁边的刷新小图标才显示short uuid

### 相关日志输出

```shell
None
```

### 附加信息

![image](https://github.com/halo-dev/halo/assets/73866989/e8bf8321-eb1d-4be6-b0e8-feb9ca96490c)
![image](https://github.com/halo-dev/halo/assets/73866989/c1df535d-e6ce-45d3-b929-910f8a218c18)

**Comment by ruibaby** [comment]
/kind improvement
/area ui
/area editor
/milestone 2.17.x

需要在编辑页面创建的时候也应用别名生成规则。

**Comment by zyy2477** [comment]
刚在2.17.1版本中貌似还有这个现象，我的设置了也是short UUID，然后生成文章默认也是时间戳，也是需要手动刷新才变成short uuid
