### ISSUE TITLE
feat: 希望可以为每篇文章设置单独的CSS样式

### ISSUE THREAD

**Issue by LainNetWork** [halo-dev/halo#616]
## 概述
为每篇文章，添加一个可以单独设置的CSS样式，可以用于覆盖主题中全局的样式

## 动机
比如部分主题的设置头图功能，有的时候我们在文章页面发现主题的全局样式并不能很好的把用作头图的图片展示出来，有可能大了有可能小了，图太亮太白把标题盖住了，有可能范围不够，把图片上老婆的脸给挡住了（大雾
![无头小圆异闻录。小圆你怎么学姐了！小圆！](https://user-images.githubusercontent.com/20994069/75915468-830a9880-5e91-11ea-8c4d-ecb5e5c843bf.png)

<center>eg:小圆你怎么学姐了！小圆！</center>

因此期望可以有一个选项，可以填入为当前文章定制的CSS片段，用于优化设置每篇文章的外观。
## 详细解释
我想到可以在文章中嵌入html标签来实现这个功能，但我觉得这个功能应该是内容无关的，如果日后需要备份迁移到其他主题，或者其他博客系统，这样的样式调整就很累赘了，会污染文章本身的内容。

**Comment by ruibaby** [comment]
这个特性似乎有点小众，可能会对其他用户造成困扰。我相信很多用户都是有表单恐惧症的。

不过现在已有的特性似乎就能完成你现在的需求，只是稍微有点麻烦，如图：

![Snipaste_2020-03-05_14-14-42](https://user-images.githubusercontent.com/21301288/75953144-b0843000-5eeb-11ea-99f9-75b501be7106.png)

**Comment by LainNetWork** [comment]
> 这个特性似乎有点小众，可能会对其他用户造成困扰。我相信很多用户都是有表单恐惧症的。
> 
> 不过现在已有的特性似乎就能完成你现在的需求，只是稍微有点麻烦，如图：
> 
> ![Snipaste_2020-03-05_14-14-42](https://user-images.githubusercontent.com/21301288/75953144-b0843000-5eeb-11ea-99f9-75b501be7106.png)
> 
> 然后你可以在页面使用 `${metas.custom_meta!}` 取用这个值。

原来元数据是可以这么用的...之前一直不知道它是什么。感谢您的解答！

**Comment by ruibaby** [comment]
@LainNetWork 是的，利用这个你可以拓展任何字段。
