### ISSUE TITLE
之前用后台admin配置了一个域名访问，现在域名到期了，导致服务启动也访问不了，如何更改

### ISSUE THREAD

**Issue by bunnyml** [halo-dev/halo#618]
之前用后台admin配置了一个域名访问，现在域名到期了，导致服务启动也访问不了，如何更改域名

**Comment by bunnyml** [comment]
最近那个域名到期后，就一直访问不了博客了。一直不知道什么原因。刚刚启动服务的时候才发现了这个问题
![image](https://user-images.githubusercontent.com/20871797/75954169-09ed5e80-5eee-11ea-92f3-046988afd7ab.png)
现在我新的域名已经解析到这里了，但是就是访问不了

**Comment by bunnyml** [comment]
![微信图片_20200305143309](https://user-images.githubusercontent.com/20871797/75954306-58026200-5eee-11ea-8af6-8909753e685b.png)

**Comment by ruibaby** [comment]
后台设置的域名不会影响你的访问。你解析之后有修改反向代理配置吗？

**Comment by bunnyml** [comment]
> 后台设置的域名不会影响您的访问。您解析之后有修改反向代理配置吗？

你好，请问您指的是application.yaml这个文件中的反向代理配置吗

**Comment by bunnyml** [comment]
不通过域名，通过IP+端口方式也访问不进来

**Comment by ruibaby** [comment]
> > 后台设置的域名不会影响您的访问。您解析之后有修改反向代理配置吗？
> 
> 你好，请问您指的是application.yaml这个文件中的反向代理配置吗

Nginx or Caddy?

**Comment by ruibaby** [comment]
> 不通过域名，通过IP+端口方式也访问不进来

ip+端口不行只能说明你端口没开放

**Comment by bunnyml** [comment]
> > 不通过域名，通过IP+端口方式也访问不进来
> 
> ip+端口不行只能说明你端口没开放

端口肯定是开了的。telnet也能通

**Comment by bunnyml** [comment]
我重新部署一下试试吧。H2是数据库所在目录不删除的话，重新部署后是不是以前写的博客还在？

**Comment by bunnyml** [comment]
我重新部署一下试试吧。H2数据库所在目录不删除的话，重新部署后是不是以前写的博客还在？

**Comment by ruibaby** [comment]
@bunnyml 是的

**Comment by bunnyml** [comment]
> @bunnyml 是的

好的，感谢
