### ISSUE TITLE
卸载重装应用后 插件文件丢失

### ISSUE THREAD

**Issue by QYG2297248353** [halo-dev/halo#6198]
### 系统信息

- 外部访问地址: https://blog.lifebus.top
- 启动时间: 2024-06-28 13:13
- 版本: 2.16.3
- 构建时间: 2024-06-14 12:48
- Git Commit: 6e1f0f3
- Java: IBM Semeru Runtime Open Edition / 21.0.3+9-LTS
- 数据库: PostgreSQL / 16.3 (Debian 16.3-1.pgdg120+1)
- 操作系统: Linux / 5.14.0-427.18.1.el9_4.x86_64
- 已激活主题: [Earth 1.8.0](https://github.com/halo-dev/theme-earth.git)
- 已启动插件:
  - [Umami 1.2.0](https://github.com/halo-sigs/plugin-umami)
  - [Markdown / HTML 内容块 1.2.0](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [图库管理 1.3.0](https://github.com/halo-sigs/plugin-photos)
  - [highlight.js 代码高亮 1.2.1](https://github.com/halo-sigs/plugin-highlightjs)
  - [lightgallery.js 灯箱 1.2.0](https://github.com/halo-sigs/plugin-lightgallery)
  - [编辑器超链接卡片 1.0.2](https://github.com/halo-sigs/plugin-editor-hyperlink-card)
  - [链接管理 1.4.0](https://github.com/halo-sigs/plugin-links)
  - [Sitemap 1.1.1](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.4.0](https://github.com/halo-dev/plugin-search-widget)
  - [RSS 1.2.2](https://github.com/halo-dev/plugin-feed)
  - [评论组件 2.2.0](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场 1.2.0](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

Extension plugin.halo.run/v1alpha1/Plugin/PluginUmami was not found.

![image](https://github.com/halo-dev/halo/assets/56836951/32e507b6-1eea-4e3c-9cad-717ebfb6eb8f)

![image](https://github.com/halo-dev/halo/assets/56836951/aae69578-f3e5-4e3b-a5f6-361eb6387f5e)

![image](https://github.com/halo-dev/halo/assets/56836951/e47f08b9-6600-45d3-8f45-7cb73f0ad401)

插件文件全部丢失，我没办法重装插件

希望能够再出现问题时，这里可以出现重装插件按钮
![image](https://github.com/halo-dev/halo/assets/56836951/104df629-104f-4da5-b45a-d7fdbfb0a869)

**Comment by udevil** [comment]
同一个版本，卸载插件后，重启服务失败，服务崩溃
