### ISSUE TITLE
非超级管理员角色打开个人令牌及两步验证页面报 403 错误

### ISSUE THREAD

**Issue by wan92hen** [halo-dev/halo#6199]
### 系统信息

- 外部访问地址: https://2a1e-14-155-63-83.ngrok-free.app
- 启动时间: 2024-06-28 13:55
- 版本: 2.17.0-alpha.2
- 构建时间: 2024-06-27 18:48
- Git Commit: 4b6d373
- Java: IBM Semeru Runtime Open Edition / 21.0.3+9-LTS
- 数据库: PostgreSQL / 15.4 (Debian 15.4-2.pgdg120+1)
- 操作系统: Linux / 5.15.153.1-microsoft-standard-WSL2
- 已激活主题: [Earth 1.8.0](https://github.com/halo-dev/theme-earth.git)
- 已启动插件:
  - [全视之眼 1.0.0-SNAPSHOT](https://github.com/halo-sigs/plugin-god-mode)
  - [插件快速开始模板 1.0.0-SNAPSHOT](https://github.com/halo-dev/plugin-hellopage)
  - [静态网页服务 1.0.0-alpha.1](https://github.com/ruibaby/plugin-static-pages)
  - [Docsme 1.0.0-alpha.5](https://github.com/f2ccloud/plugin-docsme)
  - [SEO 工具集 1.0.0-SNAPSHOT](https://github.com/f2ccloud/plugin-seo-tools)
  - 联系表单 1.2.0-SNAPSHOT
  - Reflect Halo 微信小程序配套插件 1.0.0-SNAPSHOT
  - [应用市场 1.2.0](https://www.halo.run/store/apps/app-VYJbF)
  - [社交 IAM 认证 1.0.2-SNAPSHOT](https://www.halo.run/store/apps/app-IXZkJ)
  - AI 助手 1.0.0-alpha.2
  - [代码注入增强插件 1.0.0-SNAPSHOT](https://github.com/halo-sigs/plugin-codeInjection)
  - [lightgallery.js 灯箱 1.1.1](https://github.com/halo-sigs/plugin-lightgallery)
  - [文章限制阅读 Pro 1.0.0-SNAPSHOT](https://www.halo.run/store/apps/app-TzRqd)
  - [Markdown / HTML 内容块 1.0.1](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [WangEditor 1.0.0](https://gitee.com/handsome-npc/halo-wangEditor-plugin)
  - [微信公众号发布 1.1.2-SNAPSHOT](https://github.com/f2ccloud/plugin-platforms-sync)
  - [站点迁移 1.3.0](https://github.com/halo-sigs/plugin-migrate)
  - [StackEdit 1.1.1](https://github.com/halo-sigs/plugin-stackedit)
  - [ByteMD 1.4.0](https://github.com/ruibaby/plugin-bytemd)
  - [图库管理 1.3.0](https://github.com/halo-sigs/plugin-photos)
  - [链接管理 1.3.3](https://github.com/halo-sigs/plugin-links)
  - [LDAP 认证 1.0.0-SNAPSHOT](https://github.com/f2ccloud/plugin-ldap-login)
  - [Sitemap 1.0.2](https://github.com/halo-sigs/plugin-sitemap)
  - [Unsplash 1.0.0](https://github.com/halo-sigs/plugin-unsplash)
  - [reveal.js 幻灯片编辑器 1.0.0-rc.1](https://github.com/wan92hen/plugin-revealjs)
  - [瞬间 1.5.1](https://github.com/halo-sigs/plugin-moments)
  - [OAuth2 认证 1.1.0](https://github.com/halo-sigs/plugin-oauth2)
  - [RSS 1.1.1](https://github.com/halo-sigs/plugin-feed)
  - [评论组件 2.0.1](https://github.com/halo-dev/plugin-comment-widget)
  - [搜索组件 1.4.0](https://github.com/halo-dev/plugin-search-widget)
  - [highlight.js 代码高亮 1.2.0](https://github.com/halo-sigs/plugin-highlightjs)

### 使用的哪种方式运行？

Docker

### 发生了什么？

非超级管理员角色，访问个人中心中的个人令牌及两步验证页面报 403 错误。
报错接口：
```
/apis/uc.api.security.halo.run/v1alpha1/personalaccesstokens
```
```
/apis/uc.api.security.halo.run/v1alpha1/authentications/two-factor/settings
```

### 附加信息

![image](https://github.com/halo-dev/halo/assets/27671436/117bb6d2-ff22-41fb-b354-9edde7a2560a)

**Comment by JohnNiang** [comment]
/assign
/milestone 2.17.x

This issue was introduced by <https://github.com/halo-dev/halo/pull/6130>.
