### ISSUE TITLE
请问该如何开启https

### ISSUE THREAD

**Issue by wellmoonloft** [halo-dev/halo#62]
我只有一台服务器，上面是一套tomcat的环境，自己做了几个api跑在上面，打的war包，
https是在server里面配置的8443，但是这个是直接运行，我就不太懂了？也直接扔到tomcat下吗？

**Comment by ruibaby** [comment]
@wellmoonloft nginx

**Comment by wellmoonloft** [comment]
<img width="850" alt="image" src="https://user-images.githubusercontent.com/20944693/50040497-77aa3200-007f-11e9-9a55-7eb4283de1c6.png">
是这样的，我这里面有已经有一个应用上了生产了，同时这个应用是通过443出去的，现在只能是用tomcat做为web服务器了吧？

**Comment by ruibaby** [comment]
@wellmoonloft 额.... 啊？？？ 没听懂，另外不需要另外的web服务器，应用本身内置，再者，也没用tomcat，建议看看教程哦。

**Comment by ruibaby** [comment]
@wellmoonloft 哦，不好意思，刚刚没看到图，你的意思是你服务器已经有上线的了是吧？而且你的这个应用已经在tomcat上配置了https是吧，没关系的，用nginx代理就行了，halo默认跑的是8090端口，你再用nginx代理到80和443端口，然后配置好ssl证书就行了

**Comment by wellmoonloft** [comment]
> @wellmoonloft 额.... 啊？？？ 没听懂，另外不需要另外的web服务器，应用本身内置，再者，也没用tomcat，建议看看教程哦。

我了解了～我本来想mvn打包之后dist里面的包直接扔到tomcat的webapp里，仔细看了一下发现

> @wellmoonloft 哦，不好意思，刚刚没看到图，你的意思是你服务器已经有上线的了是吧？而且你的这个应用已经在tomcat上配置了https是吧，没关系的，用nginx代理就行了，halo默认跑的是8090端口，你再用nginx代理到80和443端口，然后配置好ssl证书就行了

是的是的，～感谢，我先试一下代理的方式，如果有冲突那我下源码，改配置文件打个war包试一下，主要是看到这个项目太漂亮了，没仔细看是spring boot....sry

**Comment by ruibaby** [comment]
@wellmoonloft 嗯，注意一下，我用的是undertow容器，你打成war包最好排除一下。

**Comment by ChoviWu** [comment]
我已经放到nginx了，这是教程https://help.aliyun.com/knowledge_detail/95491.html?spm=a2c4g.11186623.2.12.48b234f15TugIi

**Comment by wellmoonloft** [comment]
目前重新部署给小程序用的时候，采用了nginx的方式，供其他人参考。
1、首先在宿主机上安装独立的nginx
2、宿主机上安装docker
3、使用halo的docker版本，选最新的那一版直接部署就可以
4、映射端口到宿主机某端口比如8888
5、去阿里云申请免费的证书
6、上传证书到宿主机的nginx安装目录，修改nginx.conf的同时进行端口映射，把443塞给8888

**Comment by ruibaby** [comment]
@wellmoonloft 感谢你的分享。

**Comment by JohnNiang** [comment]
cloudflare 或者 certbot (Let's Encrypt)

**Comment by krscuti** [comment]
（先编篡好nginx）
apt-get update
apt-get install software-properties-common
add-apt-repository ppa:certbot/certbot
apt-get update
apt-get install python-certbot-nginx

#自动配置Nginx，根据提示进行操作
certbot --nginx

#测试自动续订能否工作
certbot renew --dry-run
#设置自动续订
certbot renew

**Comment by zuojunZzz** [comment]
请问这个如何让这个项目运行起来？？

**Comment by ruibaby** [comment]
@zuojunZzz 请问这个项目是什么?
