### ISSUE TITLE
extensionPointEnabled 不会随着插件 stop 而禁用

### ISSUE THREAD

**Issue by Rainsheep** [halo-dev/halo#6212]
### 系统信息

- 外部访问地址: https://blog.rainsheep.cn/
- 启动时间: 2024-06-28 13:48
- 版本: 2.17.0-alpha.2
- 构建时间: 2024-06-27 18:23
- Git Commit: 68d94f6
- Java: IBM Semeru Runtime Open Edition / 21.0.3+9-LTS
- 数据库: 20221221 / 8.0.30-txsql
- 操作系统: Linux / 3.10.0-1160.83.1.el7.x86_64
- 已激活主题: [Dream 1.3.1](https://github.com/nineya/halo-theme-dream2.0.git)
- 已启动插件:
  - [Vditor 编辑器 1.7.0](https://github.com/justice2001/halo-plugin-vditor)
  - [瞬间 1.6.2](https://github.com/halo-sigs/plugin-moments)
  - [lightgallery.js 灯箱 1.2.0](https://github.com/halo-sigs/plugin-lightgallery)
  - [对象存储（Amazon S3 协议） 1.9.1](https://github.com/halo-dev/plugin-s3)
  - [链接管理 1.4.0](https://github.com/halo-sigs/plugin-links)
  - [搜索组件 1.4.0](https://github.com/halo-dev/plugin-search-widget)
  - [评论组件 2.3.1](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场 1.2.0](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

我启动了插件 meilisearch(本地开发版)且在扩展点进行选择后
<img width="822" alt="image" src="https://github.com/halo-dev/halo/assets/42384577/68c2f45a-0d24-4045-a973-a0d1401b0724">
系统设置的配置是正确的  {
    "extensionPointEnabled": "{\"search-engine\":[\"search-engine-meilisearch\"]}"
}，

但是当我禁用插件 meilisearch 后，extensionPointEnabled 中的 meilisearch 并没有被删除。  理论别的插件也会是这样。

**Comment by JohnNiang** [comment]
Hi @Rainsheep , thank you for reaching out here!

这里的 SearchEngine 列表中都是扩展实现的定义，不是插件中已经启用的扩展。这个扩展实现的定义会随着插件的卸载而删除。

不过后面确实可以出一个查看扩展点实现是否存在的提示。

/kind improvement
/area core
/area plugin

**Comment by Rainsheep** [comment]
@JohnNiang  好像没理解我意思。
我选择扩展点后数据库中 /registry/configmaps/system 会出现下面字段
<img width="1125" alt="image" src="https://github.com/halo-dev/halo/assets/42384577/6f8bc49c-8e8f-4ae8-a00e-88dd6040d996">
这个字段的 key 和 value 并不会随着我卸载插件而删除

**Comment by Rainsheep** [comment]
@JohnNiang 好像没理解我意思。
比如这里我使用插件后选择了 meilisearch search engine 后，数据库 /registry/configmaps/system 就会多出这样一个记录。
<img width="1189" alt="image" src="https://github.com/halo-dev/halo/assets/42384577/df831ab3-89a7-408e-b7a7-a5a00fc36067">
这个 key-value 不会随着插件的卸载而删除，就会导致插件卸载后 被启动的扩展依旧是被卸载的插件。  导致默认的搜索无法使用

**Comment by JohnNiang** [comment]
首先，我是明白你的意思的。

如果 MeiliSearch 插件卸载之后，立即删除 `extensionPointEnabled.search-engine.[].search-engine-meilisearch` 系统配置的最终效果和不删除似乎没有什么区别。而且这里保留该配置也有一个好处：卸载后重新安装，用户无需重新再去配置。

**Comment by Rainsheep** [comment]
yes
