### ISSUE TITLE
插件中调用 ReactiveSettingFetcher.get 获取到的一直是上一次的结果 

### ISSUE THREAD

**Issue by Rainsheep** [halo-dev/halo#6213]
### 系统信息

- 外部访问地址: https://blog.rainsheep.cn/
- 启动时间: 2024-06-29 12:32
- 版本: 2.17.0-alpha.2
- 构建时间: 2024-06-27 18:23
- Git Commit: 68d94f6
- Java: IBM Semeru Runtime Open Edition / 21.0.3+9-LTS
- 数据库: 20221221 / 8.0.30-txsql
- 操作系统: Linux / 3.10.0-1160.83.1.el7.x86_64
- 已激活主题: [Dream 1.3.1](https://github.com/nineya/halo-theme-dream2.0.git)
- 已启动插件:
  - [Meilisearch 1.2.1-SNAPSHOT](https://github.com/Rainsheep/halo-plugin-meilisearch)
  - [Vditor 编辑器 1.7.0](https://github.com/justice2001/halo-plugin-vditor)
  - [瞬间 1.6.2](https://github.com/halo-sigs/plugin-moments)
  - [lightgallery.js 灯箱 1.2.0](https://github.com/halo-sigs/plugin-lightgallery)
  - [对象存储（Amazon S3 协议） 1.9.1](https://github.com/halo-dev/plugin-s3)
  - [链接管理 1.4.0](https://github.com/halo-sigs/plugin-links)
  - [搜索组件 1.4.0](https://github.com/halo-dev/plugin-search-widget)
  - [评论组件 2.3.1](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场 1.2.0](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

版本: 2.17.0-alpha.2
我在插件中监听了 ConfigMap 的更新。 监听到更新后，我使用 ReactiveSettingFetcher.get  获取到的永远是上一次的值。
怀疑和 6 月 26 日 run.halo.app.plugin.DefaultReactiveSettingFetcher#getValuesInternal 的缓存变更有关

**Comment by JohnNiang** [comment]
我会尝试复现以上问题。

**Comment by JohnNiang** [comment]
经过排查，大概率是更新缓存发生在发送 Config 更新事件之后了。所以在事件监听处理中通过 ReactiveSettingFetcher#get 获取到的配置是过时的。

https://github.com/halo-dev/halo/blob/8e9781401853c27ad94e0ef9ec73583448285adb/application/src/main/java/run/halo/app/plugin/DefaultReactiveSettingFetcher.java#L165-L171

/kind bug
/area core
/area plugin
/milestone 2.17.x
/assign
