### ISSUE TITLE
点击作者名称出现错误码500

### ISSUE THREAD

**Issue by hit111cn** [halo-dev/halo#6214]
### 系统信息

- 外部访问地址: https://hit111.cn:90
- 启动时间: 2024-06-29 09:37
- 版本: 2.16.4
- 构建时间: 2024-06-14 12:51
- Git Commit: 98d4b31
- Java: IBM Semeru Runtime Open Edition / 21.0.3+9-LTS
- 数据库: PostgreSQL / 16.3
- 操作系统: Linux / 6.9.6-200.fc40.x86_64
- 已激活主题: [Theme Joe3 1.2.2](https://github.com/jiewenhuang/halo-theme-joe3.0)
- 已启动插件:
  - [站点推送插件 1.5.1](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [图库管理 1.3.0](https://github.com/halo-sigs/plugin-photos)
  - [朋友圈 1.3.2](https://github.com/chengzhongxue/plugin-friends)
  - [Lsky Pro 兰空图床 0.2.1](https://github.com/ichenhe/halo-lsky-pro)
  - [瞬间 1.6.2](https://github.com/halo-sigs/plugin-moments)
  - [对象存储（Amazon S3 协议） 1.9.1](https://github.com/halo-dev/plugin-s3)
  - [评论组件 2.3.1](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场 1.2.0](https://www.halo.run/store/apps/app-VYJbF)
  - [Sitemap 1.1.1](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.4.0](https://github.com/halo-dev/plugin-search-widget)
  - [RSS 1.2.2](https://github.com/halo-dev/plugin-feed)

### 使用的哪种方式运行？

Docker

### 发生了什么？

500服务器内部错误
服务器内部发生错误，请稍候再试。

### 相关日志输出

```shell
GET https://hit111.cn:90/authors/hit111 500 (Internal Server Error)
```

**Comment by JohnNiang** [comment]
[主题](https://github.com/jiewenhuang/halo-theme-joe3.0) 缺少作者页面的模板。建议像对应的主题仓库提交 Issue 以支持该功能。

/close
/triage unresolved
