### ISSUE TITLE
docker近几天无法使用,影响halo的升级,希望提供一个官方镜像

### ISSUE THREAD

**Issue by dokisekai** [halo-dev/halo#6215]
### 描述一下此特性

docker无法拉取镜像,替换阿里源无法使用,是否能提供替代的镜像地址

**Comment by zyy247796143** [comment]
有一个`registry.fit2cloud.com/halo/halo`，貌似2.16.2以上的版本才有，其他都会报找不到tag。比如`registry.fit2cloud.com/halo/halo:2.16.2`

**Comment by ShiinaKin** [comment]
可以用ghcr的 https://github.com/halo-dev/halo/pkgs/container/halo-dev

**Comment by ShiinaKin** [comment]
@JohnNiang 能否考虑在action中release时向ghcr也发布一个带版本tag的镜像

**Comment by ruibaby** [comment]
目前我们维护了三个镜像源，可以参考：https://docs.halo.run/getting-started/install/docker-compose#%E5%88%9B%E5%BB%BA%E5%AE%B9%E5%99%A8%E7%BB%84



> 可以用ghcr的 [halo-dev/halo/pkgs/container/halo-dev](https://github.com/halo-dev/halo/pkgs/container/halo-dev)

这个是 dev，只会推送 main 分支或者 PR 的构建，<https://github.com/halo-dev/halo/pkgs/container/halo> 才是和 Docker Hub 完全同步的。
