### ISSUE TITLE
文章编辑器无法识别attribute中带有@字符的html代码

### ISSUE THREAD

**Issue by mark07x** [halo-dev/halo#622]
你好！感谢你正在考虑为 Halo 提交一个 bug。请花一点点时间尽量详细地回答以下基础问题。

  谢谢！

  请确认你已经做了下面这些事情，若 bug 还是未解决，那么请尽可详细地描述你的问题。

  - [x] 我已经安装了最新版的 Halo
  - [x] 我已经搜索了已有的 Issues 列表中有关的信息
  - [x] 我已经搜索了论坛中有关的信息：https://bbs.halo.run
  - [x] 我已经阅读了 Halo 的 FAQ：https://halo.run/archives/other-faq

## 我的环境

  请登录到博客后台，进入菜单 `系统->关于` 点击 `环境信息` 旁边的按钮即可复制环境信息。

---
Server 版本：1.2.0
Admin 版本：1.2.0
数据库：H2
运行模式：production
UA 信息：Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.5 Safari/605.1.15

## 错误日志

  请登录到博客后台，点击菜单栏中的 `Halo Dashboard` 10 次即可开启 `开发者选项`。进入开发者选项中的 `实时日志`。
  你可以选择查找具体的错误日志，或者直接下载日志文件复制到下面即可。（注意：日志堆栈信息请用 Markdown 的代码块语法，以方便查看。）

---
不需要错误日志
## 期望行为

  你期望会发生什么？

---
@是合法的html attribute字符，因此
`<button @click="print"></button>`
应当被转换为
`<p><button @click="print"></button></p>`

> Attributes have a name and a value. Attribute names must consist of one or more characters other than controls, U+0020 SPACE, U+0022 ("), U+0027 ('), U+003E (>), U+002F (/), U+003D (=), and noncharacters. In the HTML syntax, attribute names, even those for foreign elements, may be written with any mix of ASCII lower and ASCII upper alphas.

参见：[HTML Standard](https://html.spec.whatwg.org/multipage/syntax.html#attributes-2)

## 当前行为

  描述 bug 细节，确认出现此问题的复现步骤，例如点击了哪里，发生了什么情况？

  你可以粘贴截图或附件。

---

当使用带有@字符的attribute时，html始终无法被正常解析。
例子：
`<button @click="print"></button>`
被错误的转换为
`<p>&lt;button @click=“print”&gt;Print</button></p>`

截图：
<img width="1440" alt="Screen Shot 2020-03-07 at 2 22 03 AM" src="https://user-images.githubusercontent.com/24959084/76112248-cf361400-601c-11ea-919a-b3144e0c2414.png">
<img width="1440" alt="Screen Shot 2020-03-07 at 2 22 11 AM" src="https://user-images.githubusercontent.com/24959084/76112258-d3623180-601c-11ea-919d-dac43ccbcead.png">

**Comment by ruibaby** [comment]
为什么不用代码块包裹呢？

**Comment by mark07x** [comment]
不不，我的意思是在markdown里嵌入html来解释，我想要达到的是下图中间的效果。
<img width="1440" alt="Screen Shot 2020-03-07 at 11 24 36 AM" src="https://user-images.githubusercontent.com/24959084/76135887-3cba6280-6066-11ea-86c3-6109c940306e.png">

**Comment by ruibaby** [comment]
建议等待富文本编辑器上线，并不建议这样操作。

**Comment by mark07x** [comment]
Emmm...所以现在还是先把它当纯markdown编辑器用嘛

**Comment by ruibaby** [comment]
> Emmm...所以现在还是先把它当纯markdown编辑器用嘛

emmmmm，有些特殊字符会被转义的。

**Comment by ruibaby** [comment]
下个版本不会太远了，应该就在近期。

**Comment by mark07x** [comment]
嗯嗯。markdown中嵌入html或多或少好像都有这个问题。
毕竟markdown不是html，仅仅是部分兼容html
我在wordpress上用的一个markdown插件也会把带@的html解释错误
可能压根就没考虑过还有人会在attribute里放特殊符号
结果我想在自己文章里跑vue，就挂了，只能改成v-on的写法
