### ISSUE TITLE
时区问题

### ISSUE THREAD

**Issue by EthanLoving** [halo-dev/halo#623]
docker-compose方式部署，docker容器和宿主机差8小时

**Comment by ruibaby** [comment]
构建镜像的时候已经设置了时区，https://github.com/halo-dev/halo/blob/master/Dockerfile

**Comment by EthanLoving** [comment]
> 构建镜像的时候已经设置了时区，https://github.com/halo-dev/halo/blob/master/Dockerfile

时区是asia，我的容器里面比宿主机少8小时 
**docker exec halo date**
**Sat Mar  7 07:08:04 Asia 2020**

**Comment by ruibaby** [comment]
你在 docker-compose.yaml 加上：

```
environment:
  - TZ=Asia/Shanghai
```

试试

**Comment by EthanLoving** [comment]
> 你在 docker-compose.yaml 加上：
> 
> ```
> environment:
>   - TZ=Asia/Shanghai
> ```
> 
> 试试

这个方法试过了，nginx可以起作用，halo镜像不行，还有挂载/etc/localtime 、/etc/timezone的数据卷可以使docker-gen起作用，halo依旧不起作用

**Comment by ruibaby** [comment]
> > 你在 docker-compose.yaml 加上：
> > ```
> > environment:
> >   - TZ=Asia/Shanghai
> > ```
> > 
> > 
> > 试试
> 
> 这个方法试过了，nginx可以起作用，halo镜像不行，还有挂载/etc/localtime 、/etc/timezone的数据卷可以使docker-gen起作用，halo依旧不起作用

好的，我现在试下。

**Comment by EthanLoving** [comment]
> > > 你在 docker-compose.yaml 加上：
> > > ```
> > > environment:
> > >   - TZ=Asia/Shanghai
> > > ```
> > > 
> > > 
> > > 试试
> > 
> > 
> > 这个方法试过了，nginx可以起作用，halo镜像不行，还有挂载/etc/localtime 、/etc/timezone的数据卷可以使docker-gen起作用，halo依旧不起作用
> 
> 好的，我现在试下。

嗯 我是按照halo官网上的docker-compose部署方式来的

**Comment by ruibaby** [comment]
刚刚试了下确实有问题，设置环境变量和挂载 /etc/localtime 都不行，我怀疑和基础镜像有关，因为之前没有更改基础镜像的时候是没有问题的。

**Comment by EthanLoving** [comment]
> 刚刚试了下确实有问题，设置环境变量和挂载 /etc/localtime 都不行，我怀疑和基础镜像有关，因为之前没有更改基础镜像的时候是没有问题的。

嗯嗯  我用的mysql数据库，发现数据库里面的时间差的十四个小时，但是页面显示没问题，接口返回的时间戳换算成date类型也是对的

**Comment by ruibaby** [comment]
> > 刚刚试了下确实有问题，设置环境变量和挂载 /etc/localtime 都不行，我怀疑和基础镜像有关，因为之前没有更改基础镜像的时候是没有问题的。
> 
> 嗯嗯 我用的mysql数据库，发现数据库里面的时间差的十四个小时，但是页面显示没问题，接口返回的时间戳换算成date类型也是对的

后面我们排查下，预计下个版本修复。

**Comment by EthanLoving** [comment]
> > > 刚刚试了下确实有问题，设置环境变量和挂载 /etc/localtime 都不行，我怀疑和基础镜像有关，因为之前没有更改基础镜像的时候是没有问题的。
> > 
> > 
> > 嗯嗯 我用的mysql数据库，发现数据库里面的时间差的十四个小时，但是页面显示没问题，接口返回的时间戳换算成date类型也是对的
> 
> 后面我们排查下，预计下个版本修复。

嗯 好的 谢谢

**Comment by donggangcj** [comment]
替换了基础镜像，测试没有问题。

**Comment by JohnNiang** [comment]
经测试，这种方式可以彻底解决时区问题：

```bash
docker run --rm -it -e JAVA_OPTS="-Duser.timezone=Asia/Shanghai" ruibaby/halo
```
