### ISSUE TITLE
启用插件将导致 halo 前台页面报 500 错误

### ISSUE THREAD

**Issue by leic4u** [halo-dev/halo#6249]
### 系统信息

从 2.16 升级到 2.17 后，访问前台页面出现 `500` 错误，后台控制页面可以正常访问。

发现 breaking changes 有关于插件的内容，怀疑是主题或插件导致的，遂对主题和插件进行逐一排查。

最终发现是 @Stonewuu 的[「站点推送插件」](https://github.com/Stonewuu/halo-plugin-sitepush) 导致的问题。禁用到该插件后，前台页面即可正常访问。

因为我不确定是 halo 的问题还是插件的问题，所以我在两边都提了个 issue，方便排查。

给插件那边提的 issue 链接：https://github.com/Stonewuu/halo-plugin-sitepush/issues/88

### 使用的哪种方式运行？

Docker

### 发生了什么？

前台页面 500 错误

**Comment by buyfakett** [comment]
我这里的情况是不止你说的那个插件，应该是这个版本移除了过时api导致的

**Comment by Stonewuu** [comment]
该问题已发布新版本1.5.2修复，可以更新新版本再试试 @leic4u @buyfakett

**Comment by leic4u** [comment]
[「站点推送插件」](https://github.com/Stonewuu/halo-plugin-sitepush) 插件已通过更新到 `v1.5.2` 修复报 `500` 错误的问题。

这个情况看来应该是需要插件开发者更新下插件，适配新版 API 了。

 @buyfakett  你那里还发现有什么插件出现这个问题，建议去插件项目主页提交下 issue 寻求支持。
