### ISSUE TITLE
登录设备中IP地址无法获取

### ISSUE THREAD

**Issue by 52lemon6** [halo-dev/halo#6255]
### 系统信息

- 外部访问地址: https://oniya.cn/
- 启动时间: 2024-07-03 08:19
- 版本: 2.17.0
- 构建时间: 2024-07-02 10:06
- Git Commit: c5bf192
- Java: IBM Semeru Runtime Open Edition / 21.0.3+9-LTS
- 数据库: 20200531 / 5.7.18-cynos-log
- 操作系统: Linux / 6.1.0-13-amd64
- 已激活主题: [Theme Joe3 1.2.2](https://github.com/jiewenhuang/halo-theme-joe3.0)
- 已启动插件:
  - [静态网页服务 1.0.0-alpha.2](https://www.halo.run/store/apps/app-gFkMn)
  - [Meilisearch 2.0.1](https://github.com/Rainsheep/halo-plugin-meilisearch)
  - [TinyTale小程序设置 1.0.4](https://github.com/jiewenhuang/halo-plugin-TinyTale)
  - [Webhook 1.0.0](https://www.wxy97.com/)
  - [朋友圈 1.3.3](https://github.com/chengzhongxue/plugin-friends)
  - [SEO 工具集 1.0.6](https://www.halo.run/store/apps/app-FNGbT)
  - [OAuth2 认证 1.1.1](https://github.com/halo-sigs/plugin-oauth2)
  - [highlight.js 代码高亮 1.2.2](https://github.com/halo-sigs/plugin-highlightjs)
  - [Metrics Graph 1.0.0](https://github.com/guqing/plugin-metrics-graph)
  - [Markdown / HTML 内容块 1.1.0](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [Vditor 编辑器 1.7.0](https://github.com/justice2001/halo-plugin-vditor)
  - [Willow Markdown 编辑器 1.0.0](https://github.com/guqing/willow-mde)
  - [图库管理 1.3.0](https://github.com/halo-sigs/plugin-photos)
  - [文章导入导出 1.2.4](https://jhacker.cn/2023/halo-plugin-export2doc)
  - [AI 助手 1.0.0](https://www.halo.run/store/apps/app-riNgb)
  - [Docsme 1.0.0-alpha.7](https://www.halo.run/store/apps/app-yffxw)
  - [瞬间 1.6.2](https://github.com/halo-sigs/plugin-moments)
  - [链接管理 1.4.0](https://github.com/halo-sigs/plugin-links)
  - [站点推送插件 1.5.2](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [增强备份（Backup IMproved） 1.1.1](https://www.halo.run/store/apps/app-dHakX)
  - 联系表单 1.0.2
  - [文章限制阅读 Pro 1.2.4](https://www.halo.run/store/apps/app-TzRqd)
  - [对象存储（Amazon S3 协议） 1.9.1](https://github.com/halo-dev/plugin-s3)
  - [站点迁移 1.6.1](https://github.com/halo-sigs/plugin-migrate)
  - [Sitemap 1.1.1](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.4.0](https://github.com/halo-dev/plugin-search-widget)
  - [RSS 1.2.2](https://github.com/halo-dev/plugin-feed)
  - [评论组件 2.2.0](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场 1.2.0](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

如图，设备登录中无法获取到IP地址
![image](https://github.com/halo-dev/halo/assets/40059643/c1a34fe6-dbce-4ba8-b6cb-d125f738c29a)

**Comment by guqing** [comment]
建议检查你的 nginx或其他组件需要确保halo能正确获取到 ip

/triage needs-information

**Comment by 52lemon6** [comment]
希望增加X-Forwarded-Proto和X-Forwarded-Host，通过雷池代理的网站是通过这俩请求头传递上游IP的

**Comment by guqing** [comment]
> 希望增加X-Forwarded-Proto和X-Forwarded-Host，通过雷池代理的网站是通过这俩请求头传递上游IP的

Hi @52lemon6 , 看看能否通过配置的方式解决 https://waf-ce.chaitin.cn/docs/faq/other ，一般来说 X-Forwarded-For 和 X-Real-IP 才是最常用的

**Comment by 52lemon6** [comment]
> > 希望增加X-Forwarded-Proto和X-Forwarded-Host，通过雷池代理的网站是通过这俩请求头传递上游IP的
> 
> Hi @52lemon6 , 看看能否通过配置的方式解决 https://waf-ce.chaitin.cn/docs/faq/other ，一般来说 X-Forwarded-For 和 X-Real-IP 才是最常用的

这个是雷池获取上游的的设置，比如腾讯云eo默认就是Tencent-Client-IP在这个地方就要设置Tencent-Client-IP

**Comment by guqing** [comment]
> 这个是雷池获取上游的的设置，比如腾讯云eo默认就是Tencent-Client-IP在这个地方就要设置Tencent-Client-IP
已在 #6363 中增加了对这两个请求头的支持，可以帮忙测试一下看你能否正确获取到真实 IP 吗

**Comment by guqing** [comment]
> 这个是雷池获取上游的的设置，比如腾讯云eo默认就是Tencent-Client-IP在这个地方就要设置Tencent-Client-IP

Hi @52lemon6 , 已经在 #6363 中添加了对这两个请求头的支持，但在合并之前，可以帮忙在你的 Halo 上安装这个插件
[plugin-ip-1.0.0-SNAPSHOT.jar.zip](https://github.com/user-attachments/files/16356905/plugin-ip-1.0.0-SNAPSHOT.jar.zip)
并访问 `域名/echo-ip` 来验证一下是否可以获取到正确的 IP 以验证这个改动的正确性吗

**Comment by 52lemon6** [comment]
> Hi @52lemon6 , 已经在 #6363 中添加了对这两个请求头的支持，但在合并之前，可以帮忙在你的 Halo 上安装这个插件 [plugin-ip-1.0.0-SNAPSHOT.jar.zip](https://github.com/user-attachments/files/16356905/plugin-ip-1.0.0-SNAPSHOT.jar.zip) 并访问 `域名/echo-ip` 来验证一下是否可以获取到正确的 IP 以验证这个改动的正确性吗

![image](https://github.com/user-attachments/assets/c4526491-ad2a-416b-ba39-18e11b5beabd)
貌似获取不到

**Comment by guqing** [comment]
那应该就是不是你说的这两个请求头哦，重新安装一下插件看一下请求头有什么是包含真实 IP 的
[plugin-ip-1.0.0-SNAPSHOT.jar.zip](https://github.com/user-attachments/files/16357079/plugin-ip-1.0.0-SNAPSHOT.jar.zip)

**Comment by guqing** [comment]
由于此 issue 长时间没有任何回应，默认为已经解决，我将关闭此 issue，如果还有问题请随时打开

/close
