### ISSUE TITLE
用户登录邮件时间异常

### ISSUE THREAD

**Issue by 52lemon6** [halo-dev/halo#6256]
### 系统信息

- 外部访问地址: https://oniya.cn/
- 启动时间: 2024-07-03 08:19
- 版本: 2.17.0
- 构建时间: 2024-07-02 10:06
- Git Commit: c5bf192
- Java: IBM Semeru Runtime Open Edition / 21.0.3+9-LTS
- 数据库: 20200531 / 5.7.18-cynos-log
- 操作系统: Linux / 6.1.0-13-amd64
- 已激活主题: [Theme Joe3 1.2.2](https://github.com/jiewenhuang/halo-theme-joe3.0)
- 已启动插件:
  - [静态网页服务 1.0.0-alpha.2](https://www.halo.run/store/apps/app-gFkMn)
  - [Meilisearch 2.0.1](https://github.com/Rainsheep/halo-plugin-meilisearch)
  - [TinyTale小程序设置 1.0.4](https://github.com/jiewenhuang/halo-plugin-TinyTale)
  - [Webhook 1.0.0](https://www.wxy97.com/)
  - [朋友圈 1.3.3](https://github.com/chengzhongxue/plugin-friends)
  - [SEO 工具集 1.0.6](https://www.halo.run/store/apps/app-FNGbT)
  - [OAuth2 认证 1.1.1](https://github.com/halo-sigs/plugin-oauth2)
  - [highlight.js 代码高亮 1.2.2](https://github.com/halo-sigs/plugin-highlightjs)
  - [Metrics Graph 1.0.0](https://github.com/guqing/plugin-metrics-graph)
  - [Markdown / HTML 内容块 1.1.0](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [Vditor 编辑器 1.7.0](https://github.com/justice2001/halo-plugin-vditor)
  - [Willow Markdown 编辑器 1.0.0](https://github.com/guqing/willow-mde)
  - [图库管理 1.3.0](https://github.com/halo-sigs/plugin-photos)
  - [文章导入导出 1.2.4](https://jhacker.cn/2023/halo-plugin-export2doc)
  - [AI 助手 1.0.0](https://www.halo.run/store/apps/app-riNgb)
  - [Docsme 1.0.0-alpha.7](https://www.halo.run/store/apps/app-yffxw)
  - [瞬间 1.6.2](https://github.com/halo-sigs/plugin-moments)
  - [链接管理 1.4.0](https://github.com/halo-sigs/plugin-links)
  - [站点推送插件 1.5.2](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [增强备份（Backup IMproved） 1.1.1](https://www.halo.run/store/apps/app-dHakX)
  - 联系表单 1.0.2
  - [文章限制阅读 Pro 1.2.4](https://www.halo.run/store/apps/app-TzRqd)
  - [对象存储（Amazon S3 协议） 1.9.1](https://github.com/halo-dev/plugin-s3)
  - [站点迁移 1.6.1](https://github.com/halo-sigs/plugin-migrate)
  - [Sitemap 1.1.1](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.4.0](https://github.com/halo-dev/plugin-search-widget)
  - [RSS 1.2.2](https://github.com/halo-dev/plugin-feed)
  - [评论组件 2.2.0](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场 1.2.0](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

用户登录邮件时间异常，和实际时间不一致，也和halo后台显示的时间不一致，且疑似存在意义不明的内容
![image](https://github.com/halo-dev/halo/assets/40059643/477103d6-ea11-4e55-b5ba-9b75e8d41748)
![image](https://github.com/halo-dev/halo/assets/40059643/7ee60421-99a9-420f-84a0-34abc260df0d)

**Comment by guqing** [comment]
邮件里面显示的 utc 时间，后续可以优化一下邮件内容的时间
