### ISSUE TITLE
文章分类创建没有做防重复验证

### ISSUE THREAD

**Issue by loeyun** [halo-dev/halo#6258]
### 你当前使用的版本

2.17

### 描述一下此特性

文章分类名称创建没有做防重复验证导致新建的文章无法正常访问，建议改为使用ID访问或者同名称的情况下防止创建重复访问链接

### 附加信息

![image](https://github.com/halo-dev/halo/assets/19212518/27f5b79b-8256-4df1-b78a-c1bb89049dd9)

**Comment by ruibaby** [comment]
Duplicate of https://github.com/halo-dev/halo/issues/3172
