### ISSUE TITLE
重装halo后无法初始化

### ISSUE THREAD

**Issue by Common-zhou** [halo-dev/halo#627]
## 我的环境

版本：
数据库：H2
运行模式：production
启动时间：2020-03-09 09:07

---

---

## 期望行为

重新安装之后，删除.halo文件夹可以进行正常初始化操作

## 当前行为
重装过halo后，已经删除Administrator下的.halo文件夹，没有用户。重新启动之后，无法再进行初始化。进入网页直接是登录页面

## 已经尝试过的解决办法

1.用postman发送post请求添加用户之后可以正常工作，但是想请问有其他的方法可以正常进行初始化吗？
http://127.0.0.1:8090/api/admin/installations

{"title":"zhou", "username":"zhou", "nickname":"zhou", "email":"1050@qq.com", "password":"zhouzhou"}

2.尝试直接在h2数据库插入用户，但是登录后博客未初始化(失败)

**Comment by ruibaby** [comment]
@Common-zhou 建议使用官方提供的安装包，你这是master分支的代码，并没有发布版本。

**Comment by Common-zhou** [comment]
> @Common-zhou 建议使用官方提供的安装包，你这是master分支的代码，并没有发布版本。

想学习一下halo的源码，所以想用代码运行，请问没有其他办法可以正常初始化吗？
