### ISSUE TITLE
浏览器夜览模式下高亮文字无法正常显示

### ISSUE THREAD

**Issue by Terryisthebest** [halo-dev/halo#6285]
### 系统信息

- 外部访问地址: 
- 启动时间: 2024-07-05 16:08
- 版本: 2.16.0
- 构建时间: 2024-06-03 11:01
- Git Commit: ba96118
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: H2 / 2.2.224
- 操作系统: Linux / 5.10.60-qnap
- 已激活主题: [Sakura 2.3.0](https://github.com/LIlGG/halo-theme-sakura.git)
- 已启动插件:
  - [Vditor 编辑器 1.7.0](https://github.com/justice2001/halo-plugin-vditor)
  - [Markdown / HTML 内容块 1.2.0](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [AI 助手 1.0.0](https://www.halo.run/store/apps/app-riNgb)
  - [瞬间 1.6.2](https://github.com/halo-sigs/plugin-moments)
  - [Sitemap 1.1.1](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.4.0](https://github.com/halo-dev/plugin-search-widget)
  - [RSS 1.2.2](https://github.com/halo-dev/plugin-feed)
  - [评论组件 2.1.0](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场 1.1.0](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker

### 发生了什么？

浏览器夜览模式下高亮文字无法正常显示

**Comment by ruibaby** [comment]
建议截图说明，目前无法清楚是什么问题。

**Comment by Terryisthebest** [comment]
![image](https://github.com/halo-dev/halo/assets/140528909/56a22cd9-0731-4705-bfd9-3a95b565dbe1) ![image](https://github.com/halo-dev/halo/assets/140528909/ae51eca1-cad4-4d93-9ed2-9e35098945aa)

**Comment by Terryisthebest** [comment]
已尝试通过主动更改高亮文字的字体颜色为黑色，从而使文字正常显示。如果可以默认将高亮文字的字体调整为固定颜色就更好了～
