### ISSUE TITLE
文章无法显示有序列表

### ISSUE THREAD

**Issue by Terryisthebest** [halo-dev/halo#6286]
### 系统信息

- 外部访问地址: 
- 启动时间: 2024-07-05 16:08
- 版本: 2.16.0
- 构建时间: 2024-06-03 11:01
- Git Commit: ba96118
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: H2 / 2.2.224
- 操作系统: Linux / 5.10.60-qnap
- 已激活主题: [Sakura 2.3.0](https://github.com/LIlGG/halo-theme-sakura.git)
- 已启动插件:
  - [Vditor 编辑器 1.7.0](https://github.com/justice2001/halo-plugin-vditor)
  - [Markdown / HTML 内容块 1.2.0](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [AI 助手 1.0.0](https://www.halo.run/store/apps/app-riNgb)
  - [瞬间 1.6.2](https://github.com/halo-sigs/plugin-moments)
  - [Sitemap 1.1.1](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.4.0](https://github.com/halo-dev/plugin-search-widget)
  - [RSS 1.2.2](https://github.com/halo-dev/plugin-feed)
  - [评论组件 2.1.0](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场 1.1.0](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker

### 发生了什么？

文章编辑器中使用的是**有序列表**，发布后却异常显示为**无序列表**

### 附加信息

![截屏2024-07-06 上午10 25 31](https://github.com/halo-dev/halo/assets/140528909/99125c98-fc6e-471b-b8a6-19cd56623825)
![截屏2024-07-06 上午10 25 42](https://github.com/halo-dev/halo/assets/140528909/f217b645-9a44-4703-b749-0a754c892a32)

**Comment by ruibaby** [comment]
请向主题反馈。
