### ISSUE TITLE
建议全栈私有化登录页面底部显示信息

### ISSUE THREAD

**Issue by fxyun** [halo-dev/halo#6292]
### 你当前使用的版本

2.17.1

### 描述一下此特性

建议全栈私有化后登录页面底部显示信息（比如：ICP、公安备案号及版权信息等）
![image](https://github.com/halo-dev/halo/assets/168253884/84f9bee0-cafd-4a67-8f23-4455ec29dce3)

**Comment by ruibaby** [comment]
将在 https://github.com/halo-dev/halo/issues/5214 完成后支持。
