### ISSUE TITLE
瞬间可否支持直接黏贴图片，现在手动上传再选择的交互逻辑太冗余

### ISSUE THREAD

**Issue by FunkyGod** [halo-dev/halo#6293]
### 你当前使用的版本

2.12.0

### 描述一下此特性

![image](https://github.com/halo-dev/halo/assets/39259580/4b79bae3-d176-4fd5-8442-673e51b954b5)

**Comment by ruibaby** [comment]
感谢反馈，但这个问题建议在 https://github.com/halo-sigs/plugin-moments 中提交。

/triage unresolved
/close
