### ISSUE TITLE
h2数据库问题

### ISSUE THREAD

**Issue by riocwong** [halo-dev/halo#630]
之前用的mysql 后来升级后cpu利用率100% 没办法，备份.halo文件夹和数据库后。重新搭建halo，
我的思路是，安装默认的h2数据库，然后用sql语句，写入到h2数据库中。然后把备份的文件夹覆盖过去，希望能达到回复的效果。
    现在问题是，用了默认的h2数据库后，在.halo/db下面 重启服务后会自动有halo.mv.db,但是一旦我用ip：端口/h2-console 打开数据库后，里面没有自动建立attachment表。并且你用这个方法打开数据库后会在.halo/db下面产生另外一个halo.mv.db.mv.db的文件，你每次打开一次都会出现一个。最后一个大小在不断增大。
请问1.我这样恢复的思路对不对？如不对怎么办？我重新搭建，mysql升级到5.7依然利用率100%
请问2..halo/db下面为什么会产生这么多数据库

**Comment by ruibaby** [comment]
你URL 写对了吗？

```
jdbc:h2:file:~/.halo/db/halo
```

**Comment by riocwong** [comment]
你是指什么url？我halo都可以使用了，可以发文章什么的都没问题了？

**Comment by ruibaby** [comment]
h2-console

**Comment by riocwong** [comment]
原来如此，我写的是jdbc:h2:file:~/.halo/db/halo.mv.db

**Comment by ruibaby** [comment]
嗯，如果数据不多的话，还是建议一篇文章一篇文章的复制过去。MySQL 转到 H2 可能会出现一些问题。

**Comment by riocwong** [comment]
谢谢 @ruibaby  看到attachment表了 好的 我在本机测试，一下子执行所有的sql语句 会报错

**Comment by ruibaby** [comment]
嗯，后面会提供数据导入导出功能，可以不限制数据库。

**Comment by ruibaby** [comment]
https://github.com/halo-dev/halo/issues/631

**Comment by ruibaby** [comment]
https://github.com/halo-dev/halo/pull/672
