### ISSUE TITLE
console 后台的编辑框，看不见下横线

### ISSUE THREAD

**Issue by zyy2477** [halo-dev/halo#6301]
### 系统信息

- 外部访问地址: https://www.seafog.cn/
- 启动时间: 2024-07-06 08:23
- 版本: 2.17.1
- 构建时间: 2024-07-05 20:03
- Git Commit: 226c5c3
- Java: IBM Semeru Runtime Open Edition / 21.0.3+9-LTS
- 数据库: Source distribution / 8.0.36
- 操作系统: Linux / 4.18.0-477.13.1.el8_8.x86_64
- 已激活主题: [Dream 1.3.2](https://github.com/nineya/halo-theme-dream2.0.git)
- 已启动插件:
  - [静态网页服务 1.0.0-alpha.4](https://www.halo.run/store/apps/app-gFkMn)
  - [lightgallery.js 灯箱 1.2.1](https://github.com/halo-sigs/plugin-lightgallery)
  - [Vditor 编辑器 1.7.0](https://github.com/justice2001/halo-plugin-vditor)
  - [应用市场 1.2.0](https://www.halo.run/store/apps/app-VYJbF)
  - [highlight.js 代码高亮 1.2.2](https://github.com/halo-sigs/plugin-highlightjs)
  - [对象存储（Amazon S3 协议） 1.10.0](https://github.com/halo-dev/plugin-s3)
  - [图库管理 1.3.0](https://github.com/halo-sigs/plugin-photos)
  - [瞬间 1.6.2](https://github.com/halo-sigs/plugin-moments)
  - [链接管理 1.4.0](https://github.com/halo-sigs/plugin-links)
  - [ByteMD 1.4.0](https://github.com/ruibaby/plugin-bytemd)
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.5.0](https://github.com/halo-dev/plugin-search-widget)
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [评论组件 2.4.0](https://github.com/halo-dev/plugin-comment-widget)

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

在 2.17.1 版本的后台中的很多输入框都看不到下横线，要把浏览器缩放到90%才看得到。试过edge和chrome浏览器都这样。

当前电脑分辨率1920*1080、125%的缩放。

这是浏览器100%缩放下的
![image](https://github.com/halo-dev/halo/assets/23225911/23662978-1f15-43fe-8122-768940fff69a)

这是浏览器90%缩放下的
![image](https://github.com/halo-dev/halo/assets/23225911/fb98fce5-64b6-4788-9d74-5cd411bc7bd0)

**Comment by ruibaby** [comment]
使用的操作系统是？目前我这边无法复现这个问题，无论缩放多少。

<img width="551" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/f7200684-7a41-4aa0-9701-ac1839d70750">

/triage needs-information

**Comment by zyy2477** [comment]
> 使用的操作系统是？目前我这边无法复现这个问题，无论缩放多少。
> 
> <img alt="image" width="551" src="https://private-user-images.githubusercontent.com/21301288/347234035-f7200684-7a41-4aa0-9701-ac1839d70750.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1Nzc3ODksIm5iZiI6MTcyMDU3NzQ4OSwicGF0aCI6Ii8yMTMwMTI4OC8zNDcyMzQwMzUtZjcyMDA2ODQtN2E0MS00YWEwLTk3MDEtYWMxODM5ZDcwNzUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDAyMTEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4NTM5MDY5ZTY0ZWJmN2FhMDk2NGE3NmNkOTIzZjc4ZGEyYmY2Nzk5Nzk3MjIzNGZmYzdhZmI2ZDI5MDgyODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XGjEbsVvojz9qOmik3r__XvWnjk1DjosJo3Uey02oxw">
> /triage needs-information

win 11 的系统。win 11 家庭版，23H2

**Comment by zyy2477** [comment]
刚测试了一下，把系统的显示改为1920*1080、100%的缩放。浏览器也是100%缩放的情况下，显示没问题，能看到下横线。
就是系统的显示为1920*1080、125%的缩放。浏览器100%缩放，就显示不出来。
就是系统的显示为1920*1080、125%的缩放。浏览器90%缩放，就可以显示。

**Comment by ruibaby** [comment]
这个问题已经在 https://github.com/halo-dev/halo/pull/6694 中修复，将发布到 2.20

/close
