### ISSUE TITLE
打开Chrome插件<Dark Reader> 会导致页面卡死

### ISSUE THREAD

**Issue by aoebiu** [halo-dev/halo#6302]
### 系统信息

浏览器: Chrome 126.0.6478.127
操作系统: Macos12.6.7 ARM

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

进入Halo后台后点击我的一篇文章进入编辑页面,100%导致页面卡死
Chrome进程CPU占用达到15%+,内存占用不断飙升达到8G+
并且只有这一个页面有这个问题,当关闭Dark Reader 插件时问题不再复现,并且这个问题是突然出现的,之前这个插件也是一直保持开启状态
http://101.133.140.15/console/posts/editor?name=d3cfd71c-fad7-47c8-842b-4c099b99b977
<img width="1483" alt="截屏2024-07-10 11 09 31" src="https://github.com/halo-dev/halo/assets/59640283/2f0b510d-4ef1-44f4-b7cd-dc36aabf2b59">
<img width="1078" alt="截屏2024-07-10 11 13 55" src="https://github.com/halo-dev/halo/assets/59640283/9c1c3fe5-561b-4ae4-a9c5-82fe6ddea0f0">

**Comment by aoebiu** [comment]
目前怀疑是因为页面中有svg图片

**Comment by ruibaby** [comment]
我这边没有复现这个问题。

<img width="1132" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/f1072afd-a321-4e08-8c3c-d095d637997f">

/triage needs-information

**Comment by ruibaby** [comment]
当前未复现此问题，且没有再收到类似的反馈，所以我将关闭此 issue。后续如果可以提供更多信息，可以重新提交 issue。

/close
