### ISSUE TITLE
文章 Markdown 部分的 mermaid 代码块无法渲染

### ISSUE THREAD

**Issue by lookoutldz** [halo-dev/halo#6312]
### 系统信息

- 外部访问地址: http://localhost:8090/
- 启动时间: 2024-07-13 08:49
- 版本: 2.17.1
- 构建时间: 2024-07-05 20:03
- Git Commit: 226c5c3
- Java: IBM Semeru Runtime Open Edition / 21.0.3+9-LTS
- 数据库: PostgreSQL / 15.7 (Debian 15.7-1.pgdg120+1)
- 操作系统: Linux / 6.8.0-38-generic
- 已激活主题: [Earth 1.8.0](https://github.com/halo-dev/theme-earth.git)
- 已启动插件:
  - [ByteMD 1.4.0](https://github.com/ruibaby/plugin-bytemd)
  - [highlight.js 代码高亮 1.2.2](https://github.com/halo-sigs/plugin-highlightjs)
  - [lightgallery.js 灯箱 1.2.1](https://github.com/halo-sigs/plugin-lightgallery)
  - [瞬间 1.6.2](https://github.com/halo-sigs/plugin-moments)
  - [图库管理 1.3.0](https://github.com/halo-sigs/plugin-photos)
  - [链接管理 1.4.0](https://github.com/halo-sigs/plugin-links)
  - [站点迁移 1.7.0](https://github.com/halo-sigs/plugin-migrate)
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.5.0](https://github.com/halo-dev/plugin-search-widget)
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [评论组件 2.4.0](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场 1.2.0](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker

### 发生了什么？

Markdown 的 mermaid 代码块不渲染。
如下代码块：

````
```mermaid
graph LR
subgraph A["VLAN"]
subgraph B["Local Server"]
C("nginx server")
end
subgraph D["VPS"]
E("nginx server")
end
end
F["Internet"] --http/https--> E
E --http--> C
```
````
正常显示结果：
```mermaid
graph LR
subgraph A["VLAN"]
subgraph B["Local Server"]
C("nginx server")
end
subgraph D["VPS"]
E("nginx server")
end
end
F["Internet"] --http/https--> E
E --http--> C

```
文章页面渲染结果：
![QQ_1720834122386](https://github.com/user-attachments/assets/45af2ea7-fe75-4e5a-acbc-af078b58da1e)

### 相关日志输出

```shell
页面渲染时无日志输出
```

**Comment by lookoutldz** [comment]
求求尽快处理吧，这个问题影响挺大的博客许多文章都没法正常显示😥

**Comment by ruibaby** [comment]
建议安装 https://www.halo.run/store/apps/app-ahBRi 插件，并按照文档中的提示进行设置。目前这个插件为默认编辑器提供了开箱即用的支持，也为其他编辑器提供了设置选项。

/kind support
