### ISSUE TITLE
希望官方增加独立页面的搜索栏

### ISSUE THREAD

**Issue by itscolor** [halo-dev/halo#6321]
### 你当前使用的版本

V2.17.1

### 描述一下此特性

- sun-panel的官网：https://doc.sun-panel.top/zh_cn/advanced/landscap.html
- 我部署了这位开发者的个人主页，最新版本支持搜索引擎自定义为自己的博客搜索网址，但由于HALO没有适配，不是百度那种格式https://www.baidu.com/s?wd=%25s，导致我无法配置。
- 我想通过sun-panel直接搜索博客的文章内容，目前HALO弹窗搜索都是返回json的，无法返回正确结果，意思就是url中必须包含有搜索内容，我才能配置到sun-panel的主页作为搜索引擎使用.
- 希望HALO官方，有适配的计划。。。谢谢答复~

**Comment by ruibaby** [comment]
没有看懂这个问题，为什么 Halo 需要向 Sun-Panel 去做适配，建议提供 Sun-Panel 相关的文档，看看是否有通用的方案。

/kind support
/triage needs-information

**Comment by itscolor** [comment]
> 没有看懂这个问题，为什么 Halo 需要向 Sun-Panel 去做适配，建议提供 Sun-Panel 相关的文档，看看是否有通用的方案。
> 
> /kind support /triage needs-information

感谢你的答复，PIX主题开发者表示下个版本会进行适配了，不劳烦HALO了，已解决。

**Comment by itscolor** [comment]
> 没有看懂这个问题，为什么 Halo 需要向 Sun-Panel 去做适配，建议提供 Sun-Panel 相关的文档，看看是否有通用的方案。
> 
> /kind support /triage needs-information

- 相关的视频内容，在这里：[【Sun-Panel】](https://www.bilibili.com/video/BV1A6421f7Gy/?spm_id_from=333.33.header_right.history_list.click&vd_source=d0c0c07b8ba04e3bbb603517182399f2)

**Comment by ruibaby** [comment]
> > 没有看懂这个问题，为什么 Halo 需要向 Sun-Panel 去做适配，建议提供 Sun-Panel 相关的文档，看看是否有通用的方案。
> > /kind support /triage needs-information
> 
> * 相关的视频内容，在这里：[【Sun-Panel】](https://www.bilibili.com/video/BV1A6421f7Gy/?spm_id_from=333.33.header_right.history_list.click&vd_source=d0c0c07b8ba04e3bbb603517182399f2)

应该是指 <https://github.com/halo-dev/plugin-search-widget/pull/35>，/search 路由目前需要主题主动适配。

/close
