### ISSUE TITLE
2.17.1搜索引擎问题

### ISSUE THREAD

**Issue by AlessandroQi1234** [halo-dev/halo#6333]
### 系统信息

- 外部访问地址: http://localhost:8090
- 启动时间: 2024-07-12 21:46
- 版本: 2.17.1
- 构建时间: 2024-07-05 14:06
- Git Commit: a44859f
- Java: IBM Semeru Runtime Open Edition / 21.0.3+9-LTS
- 数据库: MySQL Community Server - GPL / 8.2.0
- 操作系统: Linux / 5.15.0-1062-oracle
- 已激活主题: [Hao 1.5.6](https://github.com/chengzhongxue/halo-theme-hao)
- 已启动插件:
  - [页面静态缓存 1.0.0](https://github.com/halo-sigs/plugin-page-cache)
  - [AI 助手 1.0.0](https://www.halo.run/store/apps/app-riNgb)
  - [瞬间 1.6.2](https://github.com/halo-sigs/plugin-moments)
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.5.0](https://github.com/halo-dev/plugin-search-widget)
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [评论组件 2.4.0](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场 1.2.0](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

2.17版本如论坛其他人所述，搜索引擎丢失内容或者搜索不全，已尝试重新选择官方默认搜索引擎Lucene问题照旧。希望官方可以处理。通过1panel部署
![image](https://github.com/user-attachments/assets/d43fdfe7-4289-48ea-9c5c-dcb3b3985341)
![image](https://github.com/user-attachments/assets/77a808df-5bd9-41ef-9ce8-9c3f44b74ca3)

**Comment by JohnNiang** [comment]
> 建议在提交 Issue 之前搜索一下是否已经有相关的 Issue。

参考：
- https://github.com/halo-dev/halo/issues/6317
- https://github.com/halo-dev/halo/issues/6311

**Comment by JohnNiang** [comment]
/triage duplicate

Duplicates of https://github.com/halo-dev/halo/issues/6317

/close
