### ISSUE TITLE
设置界面的附件页空白，提示403错误

### ISSUE THREAD

**Issue by bluezsd** [halo-dev/halo#6336]
### 系统信息

- 外部访问地址: https://sancy.cn/
- 启动时间: 2024-07-12 16:34
- 版本: 2.16.3
- 构建时间: 2024-06-14 12:48
- Git Commit: 6e1f0f3
- Java: IBM Semeru Runtime Open Edition / 21.0.3+9-LTS
- 数据库: Source distribution / 5.7.44-log
- 操作系统: Linux / 3.10.0-1160.108.1.el7.x86_64
- 已激活主题: [Theme Joe3 1.2.2](https://github.com/jiewenhuang/halo-theme-joe3.0)
- 已启动插件:
  - [站点推送插件 1.5.1](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [链接管理 1.3.3](https://github.com/halo-sigs/plugin-links)
  - [图库管理 1.3.0](https://github.com/halo-sigs/plugin-photos)
  - [应用市场 1.2.0](https://www.halo.run/store/apps/app-VYJbF)
  - [搜索组件 1.4.0](https://github.com/halo-dev/plugin-search-widget)
  - [Sitemap 1.1.1](https://github.com/halo-dev/plugin-sitemap)

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

在设置界面，想修改LOGO或者Favicon，进入附件页显示空白，提示302错误，查看页面源代码，提示“

We're sorry but halo console client doesn't work properly without
--
  | JavaScript enabled. Please enable it to continue.

”
如附件图
![2](https://github.com/user-attachments/assets/3f1d2915-e1f5-4eca-9a4e-e248ddde0668)
![1](https://github.com/user-attachments/assets/02aac383-0148-4a67-a544-1a9cdd3bfd87)

**Comment by ruibaby** [comment]
在创建新的 issue 之前，建议先搜索已有的 issue。

https://github.com/halo-dev/halo/issues?q=is%3Aissue+sort%3Aupdated-desc+%E9%98%B2%E7%81%AB%E5%A2%99+is%3Aclosed

/triage duplicate
/close
