### ISSUE TITLE
希望不要后台强制跳转到/console路径下

### ISSUE THREAD

**Issue by pandatools** [halo-dev/halo#6337]
### 你当前使用的版本

2.13

### 描述一下此特性

我有一个站点，有中文站，英文站，我通过nginx进行配置让xxx.com/cn/走中文站，xxx.com/en/走英文站，但是当我想登录后台时，代码是强制跳转到/console路径，而不是xxxx.com/cn/console路径，导致后台无法登录的情况

**Comment by ruibaby** [comment]
当前并不支持代理到二级目录，暂时我们也没有考虑解决方案，详情可查阅：https://github.com/halo-dev/halo/issues/5600

/triage duplicate
