### ISSUE TITLE
关于选择附件的建议

### ISSUE THREAD

**Issue by AR-26710** [halo-dev/halo#6352]
### 你当前使用的版本

2.17.2

### 描述一下此特性

可以在选择附件列表中添加附件管理中的网格模式与列表模式。

有时候在带宽不高的情况下，本地存储过多，没做图片优化、压缩，一下展开这么多图片会造成页面卡顿，而在退出附件选择后由于附件选择列表依旧还在加载图片，就会造成其他需要加载的页面无法正常加载。

使用列表模式+列表模式的预览方式可大幅改善该情况。

### 附加信息

![image](https://github.com/user-attachments/assets/fbde88fc-480d-45b3-8c77-87a21141beb3)

**Comment by ruibaby** [comment]
/area ui
/kind improvement

可以这样改，但最终的解决方案应该还是：https://github.com/halo-dev/halo/issues/5196
