### ISSUE TITLE
邮箱无法发送

### ISSUE THREAD

**Issue by hamlk** [halo-dev/halo#6356]
### 系统信息

- 启动时间: 2024-07-22 15:11
- 版本: 2.17.0
- 构建时间: 2024-07-02 10:06
- Git Commit: c5bf192
- Java: Java(TM) SE Runtime Environment / 22.0.1+8-16
- 数据库: Source distribution / 8.0.24
- 操作系统: Linux / 6.9.6-1.el7.elrepo.x86_64
- 已激活主题: [Chirpy 1.4.4](https://github.com/AirboZH/halo-theme-chirpy.git)
- 已启动插件:
  - [应用市场 1.2.0](https://www.halo.run/store/apps/app-VYJbF)
  - [豆瓣 1.1.9](https://github.com/chengzhongxue/plugin-douban)

### 使用的哪种方式运行？

Fat Jar

### 发生了什么？

开启通知设置，配置好邮箱信息点击测试，提示：Failed to send email, please check your email configuration. 
邮箱是信息填写都无错误也开启了SMTP，使用的腾讯企业邮箱，SMTP服务器地址 ：smtp.exmail.qq.com 更换为163邮箱也是提升这个
Docker和Jar都是这个错误

### 相关日志输出

```shell
7月 22 15:54:06 linux.localdomain java[20494]: at java.base/java.lang.Thread.run(Thread.java:1570) ~[na:na]
7月 22 15:54:06 linux.localdomain java[20494]: Caused by: jakarta.mail.AuthenticationFailedException: 535 Error: authentication failed
7月 22 15:54:06 linux.localdomain java[20494]: at org.eclipse.angus.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:954) ~[jakarta.mail-2.0.3.jar!/:na]
7月 22 15:54:06 linux.localdomain java[20494]: at org.eclipse.angus.mail.smtp.SMTPTransport.authenticate(SMTPTransport.java:865) ~[jakarta.mail-2.0.3.jar!/:na]
7月 22 15:54:06 linux.localdomain java[20494]: at org.eclipse.angus.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:769) ~[jakarta.mail-2.0.3.jar!/:na]
7月 22 15:54:06 linux.localdomain java[20494]: at jakarta.mail.Service.connect(Service.java:345) ~[jakarta.mail-2.0.3.jar!/:na]
7月 22 15:54:06 linux.localdomain java[20494]: at org.springframework.mail.javamail.JavaMailSenderImpl.connectTransport(JavaMailSenderImpl.java:480) ~[spring-context-support-6.1.10.jar!/:6.1.10
7月 22 15:54:06 linux.localdomain java[20494]: at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:399) ~[spring-context-support-6.1.10.jar!/:6.1.10]
7月 22 15:54:06 linux.localdomain java[20494]: ... 84 common frames omitted
lines 1-21/21 (END)
```

**Comment by guqing** [comment]
配置错误，请检查你的邮箱密码，参考文档https://docs.halo.run/user-guide/settings#%E9%80%9A%E7%9F%A5%E8%AE%BE%E7%BD%AE

**Comment by hamlk** [comment]
![image](https://github.com/user-attachments/assets/4fa0d326-7b18-41e4-86a0-817429705119)


> 配置错误，请检查你的邮箱密码，参考文档https://docs.halo.run/user-guide/settings#%E9%80%9A%E7%9F%A5%E8%AE%BE%E7%BD%AE

![image](https://github.com/user-attachments/assets/da52f8d1-2901-4b5c-b5f4-a28c011a0d58)
你好，配置是没错的的，在cloudreve也是这个邮箱配置，是可以正常发送的

**Comment by guqing** [comment]
<img width="255" alt="image" src="https://github.com/user-attachments/assets/fa477184-2dd5-463f-a506-89bc80e30bc3">

把这个发信地址去掉不要填，这是给第三方发件服务用的如 aws

**Comment by hamlk** [comment]
> <img alt="image" width="255" src="https://private-user-images.githubusercontent.com/38999863/351222492-fa477184-2dd5-463f-a506-89bc80e30bc3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MDE1NTMsIm5iZiI6MTcyMTkwMTI1MywicGF0aCI6Ii8zODk5OTg2My8zNTEyMjI0OTItZmE0NzcxODQtMmRkNS00NjNmLWE1MDYtODliYzgwZTMwYmMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDA5NTQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzMDM5ZDY5ZDhhYTFmODYyNDMxNmVlOTBlMzgyNjY1YzQ3ZTdiOTI1ZDc2MzZiYTA5ZWYwM2E1ZDIzNDVhYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DyDA40wuyHVLXEr0dMlu-J3vTVQ1TkkCVPXH22qPtS8">
> 把这个发信地址去掉不要填，这是给第三方发件服务用的如 aws

![image](https://github.com/user-attachments/assets/3e30047f-c0a1-44a7-8bf1-674c4f821d21)
你好，非必填的都取消了，点击测试和用户哪里放送邮箱都是不发正常发送

7月 25 17:56:23 linux.localdomain java[20494]: at java.base/java.lang.Thread.run(Thread.java:1570) ~[na:na]
7月 25 17:56:23 linux.localdomain java[20494]: Suppressed: java.lang.Exception: #block terminated with an error
7月 25 17:56:23 linux.localdomain java[20494]: at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:104) ~[reactor-core-3.6.7.jar!/:3.6.7]
7月 25 17:56:23 linux.localdomain java[20494]: at reactor.core.publisher.Mono.block(Mono.java:1779) ~[reactor-core-3.6.7.jar!/:3.6.7]
7月 25 17:56:23 linux.localdomain java[20494]: at run.halo.app.notification.DefaultNotificationSender.lambda$sendNotification$0(DefaultNotificationSender.java:61) ~[!/:na]
7月 25 17:56:23 linux.localdomain java[20494]: at run.halo.app.notification.DefaultNotificationSender.reconcile(DefaultNotificationSender.java:87) ~[!/:na]
7月 25 17:56:23 linux.localdomain java[20494]: at run.halo.app.notification.DefaultNotificationSender.reconcile(DefaultNotificationSender.java:30) ~[!/:na]
7月 25 17:56:23 linux.localdomain java[20494]: at run.halo.app.extension.controller.DefaultController$Worker.run(DefaultController.java:163) ~[api-2.17.0.jar!/:na]
7月 25 17:56:23 linux.localdomain java[20494]: at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[na:na]
7月 25 17:56:23 linux.localdomain java[20494]: at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[na:na]
7月 25 17:56:23 linux.localdomain java[20494]: ... 3 common frames omitted
7月 25 17:56:23 linux.localdomain java[20494]: Caused by: jakarta.mail.AuthenticationFailedException: 535 Error: authentication failed, system busy
7月 25 17:56:23 linux.localdomain java[20494]: at org.eclipse.angus.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:954) ~[jakarta.mail-2.0.3.jar!/:na]
7月 25 17:56:23 linux.localdomain java[20494]: at org.eclipse.angus.mail.smtp.SMTPTransport.authenticate(SMTPTransport.java:865) ~[jakarta.mail-2.0.3.jar!/:na]
7月 25 17:56:23 linux.localdomain java[20494]: at org.eclipse.angus.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:769) ~[jakarta.mail-2.0.3.jar!/:na]
7月 25 17:56:23 linux.localdomain java[20494]: at jakarta.mail.Service.connect(Service.java:345) ~[jakarta.mail-2.0.3.jar!/:na]
7月 25 17:56:23 linux.localdomain java[20494]: at org.springframework.mail.javamail.JavaMailSenderImpl.connectTransport(JavaMailSenderImpl.java:480) ~[spring-context-support-6.1.10.jar!/:6.1.10
7月 25 17:56:23 linux.localdomain java[20494]: at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:399) ~[spring-context-support-6.1.10.jar!/:6.1.10]
7月 25 17:56:23 linux.localdomain java[20494]: ... 12 common frames omitted
7月 25 17:56:24 linux.localdomain java[20494]: 2024-07-25T17:56:24.434+08:00 ERROR 20494 --- [ationSender-t-4] r.h.a.n.DefaultNotificationSender        : Failed to send notification after retry

**Comment by guqing** [comment]
> 你好，非必填的都取消了，点击测试和用户哪里放送邮箱都是不发正常发送

参考 https://open.work.weixin.qq.com/help2/pc/19886?person_id=1&subtype=1&id=28&no=1000585

**Comment by struggle-upwards** [comment]
![img](https://pioneerpan.cn/img/202408131943891.png)

**Comment by struggle-upwards** [comment]
我也遇到这个坑，查看后台日志报了这个错
```bash
Caused by: jakarta.mail.AuthenticationFailedException: 535 Login Fail. Please enter your authorization code to login. More information in http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256
```
就是直接点击管理服务直接生成的授权码权限不够，反而点击下面`继续生成授权码`就成功了
这是我的完整配置：
![img](https://pioneerpan.cn/img/202408131943891.png)![img](https://pioneerpan.cn/img/202408131951353.png)



![image-20240813194918260](https://pioneerpan.cn/img/202408131949329.png)
