### ISSUE TITLE
希望能够向插件提供 ExtensionGetter 扩展

### ISSUE THREAD

**Issue by LIlGG** [halo-dev/halo#6357]
### 描述一下此特性

目前我所编写的插件中，需要获取到所有`激活中的搜索引擎`中的数据，但这需要 `ExtensionGetter` 这个 Bean 的支持。

但可能需要考虑此扩展是否会被插件滥用，因为它似乎可以获取到 Core 中的任何 Bean。

/area core
/kind feature

**Comment by JohnNiang** [comment]
从长期来看，插件也有可能会提供自己的扩展点给其他插件实现，所以我认为将 ExtensionGetter 提供给插件调用是合理的。
