### ISSUE TITLE
1panel一键部署的halo在备份恢复时如果点了确定并且重启会502

### ISSUE THREAD

**Issue by inv1ctusme** [halo-dev/halo#6360]
### 系统信息

1Panel-halo-Nwqo exited with code 0

### 使用的哪种方式运行？

Docker

### 发生了什么？

halo在备份恢复时如果点了确定并且重启会502

**Comment by ruibaby** [comment]
请提供日志。

**Comment by inv1ctusme** [comment]
谢谢回复，后来不知道怎么回事弄好了，现在没问题了
2429298577
***@***.***
---- 回复的原邮件 ----
发件人Ryan ***@***.***>发送日期2024年7月29日 ***@***.***>***@***.***>,
***@***.***>主题Re: [halo-dev/halo] 1panel一键部署的halo在备份恢复时如果点了确定并且重启会502 (Issue #6360)
请提供日志。
