### ISSUE TITLE
Win11系统使用360极速浏览器X访问https://demo.halo.run/console/dashboard会页面崩溃

### ISSUE THREAD

**Issue by chinagoldline** [halo-dev/halo#6361]
### 系统信息

访问地址：https://demo.halo.run/console/dashboard
浏览器信息：
![image](https://github.com/user-attachments/assets/ad2c96be-af09-4737-ae53-66ecd5d4693a)
操作系统信息：
![image](https://github.com/user-attachments/assets/d1133d6e-0948-4387-b3b5-2ad8fa6c8f49)
浏览器崩溃信息：
![image](https://github.com/user-attachments/assets/32fdee39-1d73-424b-a3af-1d1f5cd4a4c2)

### 使用的哪种方式运行？

Docker

### 发生了什么？

Win11系统使用360极速浏览器X访问https://demo.halo.run/console/dashboard会页面崩溃

**Comment by ruibaby** [comment]
与 https://github.com/halo-dev/halo/issues/6393 类似，当前无法判断问题来源。

/triage duplicate

**Comment by zyy2477** [comment]
我之前也试过这样。后来发现是语雀的浏览器插件造成的，暂时关掉相应的插件就好。记得在F12里看到会一直重复加载页面，直到出错。。。。不过现在这个插件更新了，访问console页面也没问题了。

**Comment by ruibaby** [comment]
> 我之前也试过这样。后来发现是语雀浏览器插件的侧边栏悬浮气泡造成的，关掉就好。记得在F12里看到会一直重复加载页面，直到出错。。。。不过现在这个插件更新了，访问console页面也没问题了。

大概率是 Edge 本身的问题，网页除了内存溢出，几乎很难导致浏览器出现崩溃的问题。所以我暂时关闭此 issue。
