### ISSUE TITLE
[Feat] 期望Halo优化内存占用

### ISSUE THREAD

**Issue by QingFeng-awa** [halo-dev/halo#6367]
### 你当前使用的版本

v2.17.2

### 描述一下此特性

目前通过1Panel部署Halo的内存占用达到大约400MiB(关闭所有插件)相比还启用了一些插件的WordPress占用也才只有300MiB,故期望Halo优化内存占用。

**Comment by ruibaby** [comment]
在创建新的 issue 前，建议先搜索是否已有相关 issue。

https://github.com/halo-dev/halo/issues/5963

/triage duplicate
