### ISSUE TITLE
无法登录用户浏览页，同时在/console控制面板下，无法查看站点预览，报错

### ISSUE THREAD

**Issue by douyan2662** [halo-dev/halo#6368]
### System information

<img width="938" alt="image" src="https://github.com/user-attachments/assets/7ae7a844-8e57-4122-839c-f561d8101483">

### What is the project operation method?

Docker

### What happened?

按照docker-compose方法部署，配置文件都没动，部署服务器后，能访问控制面板，但无法查看站点而且http://ip:8090浏览器无法打开，无法访问。
请问怎么解决?

**Comment by guqing** [comment]
建议提供一下日志

**Comment by cirbinus** [comment]
[halo-halo-1.csv](https://github.com/user-attachments/files/16403782/halo-halo-1.csv)
你好，我也出现了类似情况，只能查看console页面，这是docker日志。

**Comment by cirbinus** [comment]
> [halo-halo-1.csv](https://github.com/user-attachments/files/16403782/halo-halo-1.csv) 你好，我也出现了类似情况，只能查看console页面，这是docker日志。

![1722178975650](https://github.com/user-attachments/assets/d582299c-8464-4db0-af18-1f46710b22fd)
 已通过 #5673 解决。

**Comment by ruibaby** [comment]
当前未复现此问题，且没有再收到类似的反馈，所以我将关闭此 issue。后续如果可以提供更多信息，可以重新提交 issue。

/close
