### ISSUE TITLE
文件上传卡在100%

### ISSUE THREAD

**Issue by muzijin520** [halo-dev/halo#637]
## 我的环境
Server 版本：1.2.0
Admin 版本：1.2.0
数据库：H2
运行模式：production
UA 信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.116 Safari/537.36

---

## 错误日志

[halo-log-1583999496043.log](https://github.com/halo-dev/halo/files/4322917/halo-log-1583999496043.log)

---

## 期望行为
上传图片

## 当前行为
![image](https://user-images.githubusercontent.com/50431087/76499080-0d965d80-6479-11ea-9b56-917932bb2a18.png)
在头像更换处，和附件上传处，上传图片,卡在100%，试过不同文件，试过不同浏览器，包括火狐谷歌，都不行,但是在开发者中的静态存储中可以上传成功，

**Comment by JohnNiang** [comment]
从日志上看，并没有任何的错误。

**Comment by ruibaby** [comment]
@muzijin520 建议看看 F12 控制台

**Comment by muzijin520** [comment]
![image](https://user-images.githubusercontent.com/50431087/76500619-cfe70400-647b-11ea-94e3-a42a57a9991d.png)
![image](https://user-images.githubusercontent.com/50431087/76500636-d6757b80-647b-11ea-9a44-e0148e7c4c68.png)
控制台就是等待中，网络是正常的

**Comment by ruibaby** [comment]
没有遇到过这种情况，不知能不能上你后台看看。

**Comment by muzijin520** [comment]
昨天我把服务器系统从Windows Server 换成了CentOS 之后，按照文档部署之后该问题已解决

**Comment by toarujs** [comment]
我也这样，系统ubuntu
<img width="846" height="461" alt="Image" src="https://github.com/user-attachments/assets/c6d56b93-4537-4fb8-a772-b94a5bd64613" />

**Comment by toarujs** [comment]
219.142.225.226 - - [26/Mar/2026:17:33:49 +0800] "POST /apis/api.console.halo.run/v1alpha1/attachments/upload HTTP/2.0" 200 990 "https://bak.toarujs.com:8090/console/attachments" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Safari/537.36 Edg/146.0.0.0"8.155.1.108 - - [26/Mar/2026:17:34:00 +0800] "GET / HTTP/2.0" 200 12644 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 SafeLine-CE/v9-3-3"
