### ISSUE TITLE
恢复备份时，从已有备份恢复建议改为选择 backups 目录的文件进行恢复。

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#6370]
### 你当前使用的版本

2.17.x

### 描述一下此特性

![image](https://github.com/user-attachments/assets/4fbb6a4c-0126-4524-9d11-d06017437552)

如图，这个功能建议直接改为扫描 backups 目录，并直接选择文件进行恢复，理由如下：

1. 数据库中的备份条目并不准确，尤其是已经经历过恢复的情况下，这里可能有条目，但备份文件不一定有。
2. 考虑到备份文件大小和服务器带宽问题，直接从服务器选择备份文件恢复会减少出错率和来回尝试的成本（恢复可能失败，但重试只能重新上传，如果直接从服务器选择，至少可以提前上传到服务器。）

/area core
/kind improvement

**Comment by JohnNiang** [comment]
我将提供新的接口：<http://localhost:8090/apis/console.api.migration.halo.run/v1alpha1/backups>，返回结果示例如下所示：

```json
[
  {
    "filename": "20240820142136-backup-AagZi.zip",
    "size": 209172403,
    "lastModifiedTime": "2024-08-20T06:21:47.289905555Z"
  }
]
```

恢复的时候提供文件名参数即可。

**Comment by ruibaby** [comment]
> 我将提供新的接口：http://localhost:8090/apis/console.api.migration.halo.run/v1alpha1/backups，返回结果示例如下所示：
> 
> ```json
> [
>   {
>     "filename": "20240820142136-backup-AagZi.zip",
>     "size": 209172403,
>     "lastModifiedTime": "2024-08-20T06:21:47.289905555Z"
>   }
> ]
> ```
> 
> 恢复的时候提供文件名参数即可。

/backup-files 可能会更好？
