### ISSUE TITLE
附件库分离独立部署

### ISSUE THREAD

**Issue by Omoinemie** [halo-dev/halo#6382]
### 你当前使用的版本

2.17.0

### 描述一下此特性

可以将附件库分离部署到独立的服务器，这样前端服务器可以减轻负载，用户访问附件或者图片的时候，可以直接从附件服务器获取直链，这样大文件流量就不需要由前端服务器转发。
前端就可以部署在国内低延迟小带宽服务器上，附件可以存储在无延迟要求的大存储大带宽服务器上。

**Comment by wan92hen** [comment]
自己额外部署个 Minio 服务，然后使用对象存储插件，这样是不是就可以呢。

**Comment by JohnNiang** [comment]
附件库本身就是支持扩展的。你可以考虑安装 [S3 插件](https://www.halo.run/store/apps/app-Qxhpp)来使用外部存储服务。

另外，我们也正在开发 [alist 插件](https://github.com/halo-sigs/plugin-alist)，也可以满足你的要求。

/close
/triage unresolved
