### ISSUE TITLE
【容器异常】更新到2.17.2专业版后经常出现容器异常服务报错

### ISSUE THREAD

**Issue by carolcoral** [halo-dev/halo#6384]
### 系统信息

- 外部访问地址: https://blog.xindu.site
- 启动时间: 2024-07-26 09:44
- 版本: 2.17.2
- 构建时间: 2024-07-15 18:20
- Git Commit: aacd8c6
- Java: IBM Semeru Runtime Open Edition / 21.0.3+9-LTS
- 数据库: MySQL Community Server - GPL / 8.2.0
- 操作系统: Linux / 4.4.302+
- 已激活主题: [Hao 1.5.6](https://github.com/chengzhongxue/halo-theme-hao)
- 已启动插件:
  - [爱发电插件 1.6.3](https://github.com/carolcoral/plugin-afdian)
  - [页面静态缓存 1.0.0](https://github.com/halo-sigs/plugin-page-cache)
  - [友链自助提交插件 2.0.1](https://github.com/liuyiwuqing/halo-plugin-links-submit)
  - [WebP Cloud Services 1.1.0](https://webp.se/)
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [KaTeX 2.1.0](https://github.com/halo-sigs/plugin-katex)
  - [文本绘图 1.2.1](https://github.com/halo-sigs/plugin-text-diagram)
  - [Markdown / HTML 内容块 1.2.0](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [文章导入导出 1.2.4](https://jhacker.cn/2023/halo-plugin-export2doc)
  - [图库管理 1.3.0](https://github.com/halo-sigs/plugin-photos)
  - [搜索组件 1.5.0](https://github.com/halo-dev/plugin-search-widget)
  - [lightgallery.js 灯箱 1.2.1](https://github.com/halo-sigs/plugin-lightgallery)
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [增强备份（Backup IMproved） 1.1.1](https://www.halo.run/store/apps/app-dHakX)
  - [对象存储（Amazon S3 协议） 1.10.0](https://github.com/halo-dev/plugin-s3)
  - [Lsky Pro 兰空图床 0.2.1](https://github.com/ichenhe/halo-lsky-pro)
  - [评论组件 2.4.0](https://github.com/halo-dev/plugin-comment-widget)
  - [Vditor 编辑器 1.7.1](https://github.com/justice2001/halo-plugin-vditor)
  - [Docsme 1.0.0-alpha.7](https://www.halo.run/store/apps/app-yffxw)
  - [图床插件 1.1.0](https://github.com/liuyiwuqing/halo-plugin-picture-bed)
  - [编辑器超链接卡片 1.0.3](https://github.com/halo-sigs/plugin-editor-hyperlink-card)
  - [链接管理 1.4.0](https://github.com/halo-sigs/plugin-links)
  - [瞬间 1.6.2](https://github.com/halo-sigs/plugin-moments)
  - [站点迁移 1.7.0](https://github.com/halo-sigs/plugin-migrate)
  - [SEO 工具集 1.0.6](https://www.halo.run/store/apps/app-FNGbT)
  - [Data Studio（数据工厂） 1.0.0-alpha.2](https://github.com/halo-sigs/plugin-data-studio)
  - [Tools工具箱 1.3.2](https://github.com/liuyiwuqing/halo-plugin-tools.git)
  - [TinyTale小程序设置 1.0.4](https://github.com/jiewenhuang/halo-plugin-TinyTale)
  - [应用市场 1.3.0](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

更新到2.17.2专业版后，平均2天就会出现服务故障，容器异常，需要重启容器，否则访问就有问题

### 相关日志输出

<table>
<tr><th>date</th><th>stream</th><th>content</th></tr>
<tr><td>2024/07/26&nbsp;05:00:00</td><td>stdout</td><td>2024-07-26T05:00:00.594+08:00&nbsp;&nbsp;INFO&nbsp;8&nbsp;---&nbsp;[AsyncExecutor-1]&nbsp;s.m.l.s.impl.LinksSubmitServiceImpl&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:&nbsp;Executing&nbsp;scheduled&nbsp;task&nbsp;to&nbsp;clean&nbsp;links
</td></tr>
<tr><td>2024/07/26&nbsp;04:00:00</td><td>stdout</td><td>2024-07-26T04:00:00.845+08:00&nbsp;&nbsp;INFO&nbsp;8&nbsp;---&nbsp;[AsyncExecutor-5]&nbsp;s.m.l.s.impl.LinksSubmitServiceImpl&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:&nbsp;Executing&nbsp;scheduled&nbsp;task&nbsp;to&nbsp;clean&nbsp;links
</td></tr>
<tr><td>2024/07/26&nbsp;03:00:00</td><td>stdout</td><td>2024-07-26T03:00:00.329+08:00&nbsp;&nbsp;INFO&nbsp;8&nbsp;---&nbsp;[AsyncExecutor-4]&nbsp;s.m.l.s.impl.LinksSubmitServiceImpl&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:&nbsp;Executing&nbsp;scheduled&nbsp;task&nbsp;to&nbsp;clean&nbsp;links
</td></tr>
<tr><td>2024/07/26&nbsp;03:00:00</td><td>stdout</td><td>2024-07-26T03:00:00.005+08:00&nbsp;&nbsp;INFO&nbsp;8&nbsp;---&nbsp;[&nbsp;&nbsp;&nbsp;scheduling-1]&nbsp;r.h.a.s.a.r.RememberTokenCleaner&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:&nbsp;Expired&nbsp;remember&nbsp;me&nbsp;tokens&nbsp;have&nbsp;been&nbsp;cleaned&nbsp;up.
</td></tr>
<tr><td>2024/07/26&nbsp;02:00:01</td><td>stdout</td><td>2024-07-26T02:00:01.673+08:00&nbsp;&nbsp;INFO&nbsp;8&nbsp;---&nbsp;[AsyncExecutor-3]&nbsp;s.m.l.s.impl.LinksSubmitServiceImpl&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:&nbsp;Executing&nbsp;scheduled&nbsp;task&nbsp;to&nbsp;clean&nbsp;links
</td></tr>
<tr><td>2024/07/26&nbsp;01:00:01</td><td>stdout</td><td>2024-07-26T01:00:01.035+08:00&nbsp;&nbsp;INFO&nbsp;8&nbsp;---&nbsp;[AsyncExecutor-2]&nbsp;s.m.l.s.impl.LinksSubmitServiceImpl&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:&nbsp;Executing&nbsp;scheduled&nbsp;task&nbsp;to&nbsp;clean&nbsp;links
</td></tr>
<tr><td>2024/07/26&nbsp;00:00:00</td><td>stdout</td><td>2024-07-26T00:00:00.762+08:00&nbsp;&nbsp;INFO&nbsp;8&nbsp;---&nbsp;[AsyncExecutor-1]&nbsp;s.m.l.s.impl.LinksSubmitServiceImpl&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:&nbsp;Executing&nbsp;scheduled&nbsp;task&nbsp;to&nbsp;clean&nbsp;links
</td></tr>
<tr><td>2024/07/25&nbsp;23:00:00</td><td>stdout</td><td>2024-07-25T23:00:00.879+08:00&nbsp;&nbsp;INFO&nbsp;8&nbsp;---&nbsp;[AsyncExecutor-5]&nbsp;s.m.l.s.impl.LinksSubmitServiceImpl&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:&nbsp;Executing&nbsp;scheduled&nbsp;task&nbsp;to&nbsp;clean&nbsp;links
</td></tr>
<tr><td>2024/07/25&nbsp;22:00:00</td><td>stdout</td><td>2024-07-25T22:00:00.636+08:00&nbsp;&nbsp;INFO&nbsp;8&nbsp;---&nbsp;[AsyncExecutor-4]&nbsp;s.m.l.s.impl.LinksSubmitServiceImpl&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:&nbsp;Executing&nbsp;scheduled&nbsp;task&nbsp;to&nbsp;clean&nbsp;links
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>		at&nbsp;java.base/java.lang.Thread.run(Unknown&nbsp;Source)&nbsp;~[na:na]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>		at&nbsp;io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)&nbsp;~[netty-common-4.1.111.Final.jar:4.1.111.Final]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>		at&nbsp;io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)&nbsp;~[netty-common-4.1.111.Final.jar:4.1.111.Final]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>		at&nbsp;io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)&nbsp;~[netty-common-4.1.111.Final.jar:4.1.111.Final]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>		at&nbsp;io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:405)&nbsp;~[netty-transport-classes-epoll-4.1.111.Final.jar:4.1.111.Final]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>		at&nbsp;io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)&nbsp;~[netty-common-4.1.111.Final.jar:4.1.111.Final]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>		at&nbsp;io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)&nbsp;~[netty-common-4.1.111.Final.jar:4.1.111.Final]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>		at&nbsp;io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)&nbsp;~[netty-common-4.1.111.Final.jar:4.1.111.Final]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>		at&nbsp;io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:811)&nbsp;~[netty-transport-4.1.111.Final.jar:4.1.111.Final]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>		at&nbsp;io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:900)&nbsp;~[netty-transport-4.1.111.Final.jar:4.1.111.Final]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>		at&nbsp;io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281)&nbsp;~[netty-transport-4.1.111.Final.jar:4.1.111.Final]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>		at&nbsp;io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:301)&nbsp;~[netty-transport-4.1.111.Final.jar:4.1.111.Final]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>		at&nbsp;io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1402)&nbsp;~[netty-transport-4.1.111.Final.jar:4.1.111.Final]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>		at&nbsp;io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274)&nbsp;~[netty-transport-4.1.111.Final.jar:4.1.111.Final]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>		at&nbsp;io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281)&nbsp;~[netty-transport-4.1.111.Final.jar:4.1.111.Final]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>		at&nbsp;io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:303)&nbsp;~[netty-transport-4.1.111.Final.jar:4.1.111.Final]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>		at&nbsp;io.netty.channel.CombinedChannelDuplexHandler.channelInactive(CombinedChannelDuplexHandler.java:221)&nbsp;~[netty-transport-4.1.111.Final.jar:4.1.111.Final]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>		at&nbsp;io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:377)&nbsp;~[netty-codec-4.1.111.Final.jar:4.1.111.Final]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>		at&nbsp;io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:412)&nbsp;~[netty-codec-4.1.111.Final.jar:4.1.111.Final]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>		at&nbsp;io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelInactive(CombinedChannelDuplexHandler.java:418)&nbsp;~[netty-transport-4.1.111.Final.jar:4.1.111.Final]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>		at&nbsp;io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274)&nbsp;~[netty-transport-4.1.111.Final.jar:4.1.111.Final]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>		at&nbsp;io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281)&nbsp;~[netty-transport-4.1.111.Final.jar:4.1.111.Final]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>		at&nbsp;io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:303)&nbsp;~[netty-transport-4.1.111.Final.jar:4.1.111.Final]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>		at&nbsp;reactor.netty.channel.ChannelOperationsHandler.channelInactive(ChannelOperationsHandler.java:73)&nbsp;~[reactor-netty-core-1.1.20.jar:1.1.20]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>		at&nbsp;reactor.netty.http.server.HttpServerOperations.onInboundClose(HttpServerOperations.java:830)&nbsp;~[reactor-netty-http-1.1.20.jar:1.1.20]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>Original&nbsp;Stack&nbsp;Trace:
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>	*__checkpoint&nbsp;⇢&nbsp;HTTP&nbsp;POST&nbsp;"/apis/api.halo.run/v1alpha1/trackers/counter"&nbsp;[ExceptionHandlingWebHandler]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>	*__checkpoint&nbsp;⇢&nbsp;run.halo.app.webfilter.AdditionalWebFilterChainProxy&nbsp;[DefaultWebFilterChain]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>	*__checkpoint&nbsp;⇢&nbsp;run.halo.seo.tools.CrawlRecordFilter&nbsp;[DefaultWebFilterChain]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>	*__checkpoint&nbsp;⇢&nbsp;run.halo.app.sms.security.SmsLoginAuthenticator&nbsp;[DefaultWebFilterChain]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>	*__checkpoint&nbsp;⇢&nbsp;site.muyin.tools.filter.ToolsPluginApiWebFilter&nbsp;[DefaultWebFilterChain]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>	*__checkpoint&nbsp;⇢&nbsp;run.halo.comment.widget.captcha.CommentCaptchaFilter&nbsp;[DefaultWebFilterChain]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>	*__checkpoint&nbsp;⇢&nbsp;se.webp.plugin.WebpCloudImageOptimizerWebFilter&nbsp;[DefaultWebFilterChain]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>	*__checkpoint&nbsp;⇢&nbsp;run.halo.seo.tools.AdvancedRedirectWebFilter&nbsp;[DefaultWebFilterChain]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>	*__checkpoint&nbsp;⇢&nbsp;run.halo.cache.page.PageCacheWebFilter&nbsp;[DefaultWebFilterChain]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>	*__checkpoint&nbsp;⇢&nbsp;org.springframework.security.web.server.WebFilterChainProxy&nbsp;[DefaultWebFilterChain]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>	*__checkpoint&nbsp;⇢&nbsp;ServerWebExchangeReactorContextWebFilter&nbsp;[DefaultWebFilterChain]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>	*__checkpoint&nbsp;⇢&nbsp;HttpHeaderWriterWebFilter&nbsp;[DefaultWebFilterChain]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>	*__checkpoint&nbsp;⇢&nbsp;CorsWebFilter&nbsp;[DefaultWebFilterChain]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>	*__checkpoint&nbsp;⇢&nbsp;CsrfWebFilter&nbsp;[DefaultWebFilterChain]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>	*__checkpoint&nbsp;⇢&nbsp;ReactorContextWebFilter&nbsp;[DefaultWebFilterChain]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>	*__checkpoint&nbsp;⇢&nbsp;AuthenticationWebFilter&nbsp;[DefaultWebFilterChain]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>	*__checkpoint&nbsp;⇢&nbsp;AuthenticationWebFilter&nbsp;[DefaultWebFilterChain]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>	*__checkpoint&nbsp;⇢&nbsp;SecurityWebFilterChainProxy&nbsp;[DefaultWebFilterChain]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>	*__checkpoint&nbsp;⇢&nbsp;RememberMeAuthenticationFilter&nbsp;[DefaultWebFilterChain]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>	*__checkpoint&nbsp;⇢&nbsp;SecurityWebFilterChainProxy&nbsp;[DefaultWebFilterChain]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>	*__checkpoint&nbsp;⇢&nbsp;AuthenticationWebFilter&nbsp;[DefaultWebFilterChain]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>	*__checkpoint&nbsp;⇢&nbsp;TotpAuthenticationFilter&nbsp;[DefaultWebFilterChain]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>	*__checkpoint&nbsp;⇢&nbsp;SecurityWebFilterChainProxy&nbsp;[DefaultWebFilterChain]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>	*__checkpoint&nbsp;⇢&nbsp;AnonymousAuthenticationWebFilter&nbsp;[DefaultWebFilterChain]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>	*__checkpoint&nbsp;⇢&nbsp;LogoutPageGeneratingWebFilter&nbsp;[DefaultWebFilterChain]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>	*__checkpoint&nbsp;⇢&nbsp;SecurityContextServerWebExchangeWebFilter&nbsp;[DefaultWebFilterChain]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>	*__checkpoint&nbsp;⇢&nbsp;ServerRequestCacheWebFilter&nbsp;[DefaultWebFilterChain]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>	*__checkpoint&nbsp;⇢&nbsp;LogoutWebFilter&nbsp;[DefaultWebFilterChain]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>	*__checkpoint&nbsp;⇢&nbsp;ExceptionTranslationWebFilter&nbsp;[DefaultWebFilterChain]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>	*__checkpoint&nbsp;⇢&nbsp;AuthorizationWebFilter&nbsp;[DefaultWebFilterChain]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>	*__checkpoint&nbsp;⇢&nbsp;run.halo.app.sms.security.SmsLoginAuthenticator&nbsp;[DefaultWebFilterChain]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>	*__checkpoint&nbsp;⇢&nbsp;run.halo.app.security.device.DeviceSessionFilter&nbsp;[DefaultWebFilterChain]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>	*__checkpoint&nbsp;⇢&nbsp;run.halo.app.security.LoginRequiredForAccessWebFilter&nbsp;[DefaultWebFilterChain]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>	*__checkpoint&nbsp;⇢&nbsp;run.halo.app.security.InitializeRedirectionWebFilter&nbsp;[DefaultWebFilterChain]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>Error&nbsp;has&nbsp;been&nbsp;observed&nbsp;at&nbsp;the&nbsp;following&nbsp;site(s):
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>	Suppressed:&nbsp;reactor.core.publisher.FluxOnAssembly$OnAssemblyException:&nbsp;
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>	at&nbsp;reactor.netty.http.server.HttpServerOperations.onInboundClose(HttpServerOperations.java:830)&nbsp;~[reactor-netty-http-1.1.20.jar:1.1.20]
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>reactor.netty.channel.AbortedException:&nbsp;Connection&nbsp;has&nbsp;been&nbsp;closed
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>
</td></tr>
<tr><td>2024/07/25&nbsp;21:44:24</td><td>stdout</td><td>2024-07-25T21:44:24.575+08:00&nbsp;ERROR&nbsp;8&nbsp;---&nbsp;[or-http-epoll-2]&nbsp;o.s.w.s.adapter.HttpWebHandlerAdapter&nbsp;&nbsp;&nbsp;&nbsp;:&nbsp;[aefae889-10954]&nbsp;500&nbsp;Server&nbsp;Error&nbsp;for&nbsp;HTTP&nbsp;POST&nbsp;"/apis/api.halo.run/v1alpha1/trackers/counter"
</td></tr>
<tr><td>2024/07/25&nbsp;21:00:00</td><td>stdout</td><td>2024-07-25T21:00:00.508+08:00&nbsp;&nbsp;INFO&nbsp;8&nbsp;---&nbsp;[AsyncExecutor-3]&nbsp;s.m.l.s.impl.LinksSubmitServiceImpl&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:&nbsp;Executing&nbsp;scheduled&nbsp;task&nbsp;to&nbsp;clean&nbsp;links
</td></tr>
<tr><td>2024/07/25&nbsp;20:00:00</td><td>stdout</td><td>2024-07-25T20:00:00.842+08:00&nbsp;&nbsp;INFO&nbsp;8&nbsp;---&nbsp;[AsyncExecutor-2]&nbsp;s.m.l.s.impl.LinksSubmitServiceImpl&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:&nbsp;Executing&nbsp;scheduled&nbsp;task&nbsp;to&nbsp;clean&nbsp;links
</td></tr>
</table

**Comment by carolcoral** [comment]
[halo.html.zip](https://github.com/user-attachments/files/16385630/halo.html.zip)

**Comment by JohnNiang** [comment]
我完整的看了一下错误日志，其中的错误似乎不会影响到正常的访问和操作。

如果是友链提交报错，建议去对应的插件仓库提交 Issue。
