### ISSUE TITLE
edge 浏览器 console后台访问失败

### ISSUE THREAD

**Issue by shelli-site** [halo-dev/halo#6393]
### System information

**浏览器：**
Microsoft Edge
**版本** 126.0.2592.87 (正式版本) (64 位)

**操作系统：**
**版本**	Windows 11 专业版
**版本号**	23H2
**安装日期**	‎2024/‎3/‎1
**操作系统版本**	22631.3880
**体验**	Windows Feature Experience Pack 1000.22700.1020.0

### What is the project operation method?

Docker Compose

### What happened?

访问 https://demo.halo.run/console 时，页面崩溃！
![image](https://github.com/user-attachments/assets/a7a2225c-adcd-4478-be65-974279f1a69a)

### Reproduce Steps

edge浏览器访问 https://demo.halo.run/console

### Relevant log output

```shell
无运行日志，不用自己部署即可重现（至少我的电脑是的）
```

### Additional information

我自己排查了一些状况，
1. edge下 https://demo.halo.run/ 页面可以正常访问，没有问题，不会崩溃。但是切换到后台登录时，即 https://demo.halo.run/console 链接时，就会一闪而过的出现后台页面，紧接着马上弹出页面崩溃。
2. chrom浏览器访问一切正常。
3. edge打开无痕模式可以正常访问。
4. 不止 https://demo.halo.run/ 站点有这样的规律，我本地搭建的、服务器搭建的、其他人搭建的都有这个问题。即主页可以访问，console 访问崩溃。

> edge也是使用人数比较多的浏览器，希望能排查并解决这个问题。

![image](https://github.com/user-attachments/assets/0cb54d7e-3eb4-44a6-b6e9-820d20e290a4)

![image](https://github.com/user-attachments/assets/cc5f885e-f8e5-473b-921e-de795fcf424e)

**Comment by shelli-site** [comment]
其他网站如 baidu、github均能正常访问，目前只在halo搭建的网站上发现了

**Comment by shelli-site** [comment]
另外发现 https://www.halo.run/console/login 页面可以正常访问

**Comment by ruibaby** [comment]
我这边并未复现此问题，建议检查是否有浏览器插件干扰。

<img width="952" alt="image" src="https://github.com/user-attachments/assets/b4166c9d-c25f-49fa-b28c-80f979102485">

**Comment by shelli-site** [comment]
谢谢，排查出是浏览器插件的问题了。通过排除法发现是 [书签侧边栏](https://microsoftedge.microsoft.com/addons/detail/%E4%B9%A6%E7%AD%BE%E4%BE%A7%E8%BE%B9%E6%A0%8F/lmjefbghkfeppnpofmbfmhgodpclipbl?hl=zh-CN)造成的，具体原因未知，可能与webflux有关或者什么的。

**Comment by ruibaby** [comment]
这看起来很像浏览器本身的问题，毕竟这个异常页面是浏览器的页面。相关问题：https://answers.microsoft.com/en-us/microsoftedge/forum/all/status-access-violation-issues/1fd4a2ef-6736-441f-8421-6ed167105093

**Comment by ruibaby** [comment]
See https://github.com/halo-dev/halo/issues/6361#issuecomment-2268290756

/close
