### ISSUE TITLE
又是数据库建表sql吗

### ISSUE THREAD

**Issue by yhcxy** [halo-dev/halo#6404]
### System information

又是数据库建表sql吗

### What is the project operation method?

Docker

### What happened?

又是数据库建表sql吗

### Reproduce Steps

又是数据库建表sql吗

### Relevant log output

```shell
又是数据库建表sql吗
```

**Comment by guqing** [comment]
请完善 issue 信息后重新提交，提问先到 discussion 或 bbs 上查找相关问题
/close
