### ISSUE TITLE
修改表结构

### ISSUE THREAD

**Issue by yhcxy** [halo-dev/halo#6415]
### System information

项目已经启动了，如何修改表结构呀，目前我看到没有数据库存在，都是存在内存里面的吗？

### What is the project operation method?

Docker

### What happened?

项目已经启动了，如何修改表结构呀，目前我看到没有数据库存在，都是存在内存里面的吗？

### Reproduce Steps

项目已经启动了，如何修改表结构呀，目前我看到没有数据库存在，都是存在内存里面的吗？

### Relevant log output

```shell
项目已经启动了，如何修改表结构呀，目前我看到没有数据库存在，都是存在内存里面的吗？
```

### Additional information

项目已经启动了，如何修改表结构呀，目前我看到没有数据库存在，都是存在内存里面的吗？

**Comment by ruibaby** [comment]
请严格按照 issue 模板创建 issue，你已经连续三次完全无视我们的 issue 模板，如果依旧如此，我们会认为这是 spam issue，你会被限制访问此仓库。

- https://github.com/halo-dev/halo/issues/6404
- https://github.com/halo-dev/halo/issues/6398

/close
