### ISSUE TITLE
Add Index on categories.name to Accelerate Query

### ISSUE THREAD

**Issue by wtune** [halo-dev/halo#642]
## Problem
Missing index on table **categories** column **name** might make the underlying query issued 
via [CategoryServiceImpl#getByName](https://github.com/halo-dev/halo/blob/1d020ff550cf9dd760e433aa4381f7b0f20feec5/src/main/java/run/halo/app/service/impl/CategoryServiceImpl.java#L166) slow.Since table categories is mostly read and sometimes inserted or updated, the performance impact for write operations is acceptable under common cases.
## Possible Solution
Add Index on categories.name

**Comment by ruibaby** [comment]
merged
