### ISSUE TITLE
附件删除后依旧可以访问

### ISSUE THREAD

**Issue by liuyiwuqing** [halo-dev/halo#6420]
### 系统信息

- 外部访问地址: https://blog.muyin.site
- 启动时间: 2024-07-31 11:21
- 版本: 2.17.2
- 构建时间: 2024-07-15 18:20
- Git Commit: aacd8c6
- Java: IBM Semeru Runtime Open Edition / 21.0.3+9-LTS
- 数据库: MySQL Community Server - GPL / 8.2.0
- 操作系统: Linux / 6.1.0-13-amd64
- 已激活主题: [Theme Joe3 1.3.0](https://github.com/jiewenhuang/halo-theme-joe3.0)
- 已启动插件:
  - [图床插件 1.1.0](https://github.com/liuyiwuqing/halo-plugin-picture-bed)
  - [Umami 1.4.0](https://github.com/halo-sigs/plugin-umami)
  - [编辑器超链接卡片 1.0.3](https://github.com/halo-sigs/plugin-editor-hyperlink-card)
  - [页面静态缓存 1.0.0](https://github.com/halo-sigs/plugin-page-cache)
  - [Algolia Search Engine 1.0.0](https://github.com/halo-dev/plugin-starter)
  - [UniHalo 配置 1.0.5](https://github.com/ialley-workshop-open/plugin-uni-halo)
  - [Data Studio（数据工厂） 1.0.0-alpha.2](https://github.com/halo-sigs/plugin-data-studio)
  - [highlight.js 代码高亮 1.2.2](https://github.com/halo-sigs/plugin-highlightjs)
  - [AI 助手 1.0.0](https://www.halo.run/store/apps/app-riNgb)
  - [静态网页服务 1.0.0-alpha.4](https://www.halo.run/store/apps/app-gFkMn)
  - [lightgallery.js 灯箱 1.2.1](https://github.com/halo-sigs/plugin-lightgallery)
  - [Vditor 编辑器 1.7.1](https://github.com/justice2001/halo-plugin-vditor)
  - [Tools工具箱 1.4.1](https://github.com/liuyiwuqing/halo-plugin-tools.git)
  - [文章限制阅读 1.3.0](https://www.halo.run/store/apps/app-IzWXo)
  - [TinyTale小程序设置 1.0.5-rc2](https://github.com/jiewenhuang/halo-plugin-TinyTale)
  - [爱发电插件 1.6.3](https://github.com/carolcoral/plugin-afdian)
  - [Lsky Pro 兰空图床 0.2.1](https://github.com/ichenhe/halo-lsky-pro)
  - [站点迁移 1.7.0](https://github.com/halo-sigs/plugin-migrate)
  - [Chirpy Add-on 0.0.2](https://github.com/airbozh/halo-plugin-chirpy)
  - [对象存储（Amazon S3 协议） 1.10.0](https://github.com/halo-dev/plugin-s3)
  - [SEO 工具集 1.0.6](https://www.halo.run/store/apps/app-FNGbT)
  - [增强备份（Backup IMproved） 1.1.1](https://www.halo.run/store/apps/app-dHakX)
  - [插件授权管理 1.2.0-alpha](https://github.com/liuyiwuqing/lywq-plugins-auth)
  - [友链自助提交插件 2.0.2](https://github.com/liuyiwuqing/halo-plugin-links-submit)
  - [站点推送插件 1.5.2](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [Nps管理 1.3.1](https://github.com/liuyiwuqing/halo-plugin-nps)
  - [Unsplash 1.1.0](https://github.com/halo-sigs/plugin-unsplash)
  - [图库管理 1.3.0](https://github.com/halo-sigs/plugin-photos)
  - [Docsme 1.0.0-alpha.7](https://www.halo.run/store/apps/app-yffxw)
  - [Markdown / HTML 内容块 1.2.0](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [Metrics Graph 1.0.0](https://github.com/guqing/plugin-metrics-graph)
  - [链接管理 1.4.0](https://github.com/halo-sigs/plugin-links)
  - [OAuth2 认证 1.2.0](https://github.com/halo-sigs/plugin-oauth2)
  - [瞬间 1.7.0](https://github.com/halo-sigs/plugin-moments)
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.5.0](https://github.com/halo-dev/plugin-search-widget)
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [评论组件 2.4.0](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场 1.3.0](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

上传的附件进行删除之后，访问原附件地址依旧可以访问；
附带问题：附件删除重新上传显示的研究是删除前的附件

**Comment by ruibaby** [comment]
先看看是否和这个问题一致：https://github.com/halo-dev/halo/issues/5131

/triage duplicate

**Comment by liuyiwuqing** [comment]
> 先看看是否和这个问题一致：#5131
> 
> /triage duplicate

已解决
