### ISSUE TITLE
安全性能升级，后台登录时，系统无验证码。

### ISSUE THREAD

**Issue by zhangkai2019** [halo-dev/halo#6421]
### 你当前使用的版本

2.6.0-SNAPSHOT

### 描述一下此特性

系统无验证码，攻击者可直接对系统账户进行暴力破解，一旦破解成功，即可登陆系统。建议添加验证码，并在后端进行校验，及时销毁防止复用。

**Comment by guqing** [comment]
/triage duplicate
see alse #5335

**Comment by guqing** [comment]
目前已经有以下措施可以在很大程度上解决登录暴力破解问题
1. 提供有两步验证，可在后台开启
2. 密码错误重试 3 次后会触发限流需 1 分钟后重试，并且可以配置让等待时间更长
3. 不要使用弱密码
