### ISSUE TITLE
Joe3不显示二级菜单

### ISSUE THREAD

**Issue by NikoYomi** [halo-dev/halo#6432]
### 系统信息

- 外部访问地址: https://blog.snty.de/
- 启动时间: 2024-08-02 17:12
- 版本: 2.17.2
- 构建时间: 2024-07-15 18:19
- Git Commit: 6d4bedd
- Java: IBM Semeru Runtime Open Edition / 21.0.3+9-LTS
- 数据库: Source distribution / 5.5.5-10.11.6-MariaDB
- 操作系统: Linux / 4.4.302+
- 已激活主题: [Theme Joe3 1.3.0](https://github.com/jiewenhuang/halo-theme-joe3.0)
- 已启动插件:
  - [通知我 1.1.0](https://github.com/monyuan/notify-me)
  - [AI 助手 1.0.0](https://www.halo.run/store/apps/app-riNgb)
  - [爱发电插件 1.6.3](https://github.com/carolcoral/plugin-afdian)
  - [Markdown / HTML 内容块 1.2.0](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [图库管理 1.3.0](https://github.com/halo-sigs/plugin-photos)
  - [Trailing Slash 1.0.0](https://github.com/halo-sigs/plugin-trailing-slash)
  - [链接管理 1.4.0](https://github.com/halo-sigs/plugin-links)
  - [Docsme 1.0.0-alpha.7](https://www.halo.run/store/apps/app-yffxw)
  - [highlight.js 代码高亮 1.2.2](https://github.com/halo-sigs/plugin-highlightjs)
  - [编辑器超链接卡片 1.0.3](https://github.com/halo-sigs/plugin-editor-hyperlink-card)
  - [ByteMD 1.4.0](https://github.com/ruibaby/plugin-bytemd)
  - [Willow Markdown 编辑器 1.0.0](https://github.com/guqing/willow-mde)
  - [瞬间 1.6.2](https://github.com/halo-sigs/plugin-moments)
  - [图床插件 1.1.0](https://github.com/liuyiwuqing/halo-plugin-picture-bed)
  - [waline 评论系统 1.0.0](https://github.com/wenjing-xin/plugin-waline)
  - [搜索组件 1.5.0](https://github.com/halo-dev/plugin-search-widget)
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [评论组件 2.4.0](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场 1.3.0](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker

### 发生了什么？

1.不显示二级菜单。

![Screenshot - 2024-08-02 22.55.08.png](https://imgs.snty.de/uploads/0/2024/08/02/66acf3796e9e4.png)
![Screenshot - 2024-08-02 22.55.20.png](https://imgs.snty.de/uploads/0/2024/08/02/66acf379d6277.png)

2.友链添加了并不显示。

![Screenshot - 2024-08-02 22.57.28.png](https://imgs.snty.de/uploads/0/2024/08/02/66acf3e315a3b.png)

**Comment by ruibaby** [comment]
Halo 无法为主题主动适配二级菜单，建议向主题反馈。

/triage unresolved
/close
