### ISSUE TITLE
docker-compose 运行的halo2程序，系统内进程会明文显示数据库密码信息

### ISSUE THREAD

**Issue by ZTfred** [halo-dev/halo#6433]
### 系统信息

- 启动时间: 2024-08-03 09:04
- 版本: 2.17.1
- 构建时间: 2024-07-05 20:03
- Git Commit: 226c5c3
- Java: IBM Semeru Runtime Open Edition / 21.0.3+9-LTS
- 数据库: MySQL Community Server (GPL) / 5.7.39-log
- 操作系统: Linux / 6.8.0-39-generic

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

![image](https://github.com/user-attachments/assets/67fd5507-4903-4526-bc52-b8da60c420b4)
操作系统内执行：ps aux | grep halo
可以看到明文显示的数据库登录信息，存在数据泄露高风险

**Comment by ruibaby** [comment]
/triage duplicate

See https://github.com/halo-dev/halo/issues/6107
