### ISSUE TITLE
间歇性500错误

### ISSUE THREAD

**Issue by yyhhkya** [halo-dev/halo#6434]
### 系统信息

- 外部访问地址: http://localhost:8090/
- 启动时间: 2024-08-03 10:00
- 版本: 2.18.0
- 构建时间: 2024-08-01 10:17
- Git Commit: 58fe872
- Java: IBM Semeru Runtime Open Edition / 21.0.3+9-LTS
- 数据库: H2 / 2.2.224
- 操作系统: Linux / 5.4.0-182-generic
- 已激活主题: [Theme-Stack 2.2.3](https://github.com/jiewenhuang/halo-theme-stack)
- 已启动插件:
  - [vanilla-lazyload 懒加载 1.0.0](https://github.com/liuzhihang/plugin-lazyload)
  - [站点推送插件 1.4.6](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [链接安全检测 1.1.0](https://github.com/wenjing-xin/link-security-detect.git)
  - [瞬间 1.7.0](https://github.com/halo-sigs/plugin-moments)
  - [highlight.js 代码高亮 1.2.2](https://github.com/halo-sigs/plugin-highlightjs)
  - [Vditor 编辑器 1.7.1](https://github.com/justice2001/halo-plugin-vditor)
  - [链接管理 1.4.0](https://github.com/halo-sigs/plugin-links)
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.5.0](https://github.com/halo-dev/plugin-search-widget)
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [评论组件 2.4.0](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场 1.3.0](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

间歇性500错误 面板使用的1panel

### 复现步骤

多刷新几次就会复现

### 附加信息

# ng配置
server {
    listen 80 ; 
    listen 443 ssl http2 ; 
    server_name blog.isyyo.com; 
    index index.php index.html index.htm default.php default.htm default.html; 
    proxy_set_header Host $host; 
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
    proxy_set_header X-Forwarded-Host $server_name; 
    proxy_set_header X-Real-IP $remote_addr; 
    proxy_http_version 1.1; 
    proxy_set_header Upgrade $http_upgrade; 
    proxy_set_header Connection "upgrade"; 
    access_log /www/sites/blog.isyyo.com/log/access.log main; 
    error_log /www/sites/blog.isyyo.com/log/error.log; 
    location ^~ /.well-known/acme-challenge {
        allow all; 
        root /usr/share/nginx/html; 
    }
    location / {
        proxy_pass http://127.0.0.1:8090; 
    }
    if ($scheme = http) {
        return 301 https://$host$request_uri; 
    }
    ssl_certificate /www/sites/blog.isyyo.com/ssl/fullchain.pem; 
    ssl_certificate_key /www/sites/blog.isyyo.com/ssl/privkey.pem; 
    ssl_protocols TLSv1.3 TLSv1.2 TLSv1.1 TLSv1; 
    ssl_ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:!aNULL:!eNULL:!EXPORT:!DSS:!DES:!RC4:!3DES:!MD5:!PSK:!KRB5:!SRP:!CAMELLIA:!SEED; 
    ssl_prefer_server_ciphers on; 
    ssl_session_cache shared:SSL:10m; 
    ssl_session_timeout 10m; 
    error_page 497 https://$host$request_uri; 
    proxy_set_header X-Forwarded-Proto https; 
    add_header Strict-Transport-Security "max-age=31536000"; 
}

**Comment by yyhhkya** [comment]
[halo-log-2024-08-03 10_19.log](https://github.com/user-attachments/files/16477864/halo-log-2024-08-03.10_19.log)

站点：blog.isyyo.com

**Comment by ruibaby** [comment]
```
run.halo.img.error.LazyLoadHeadProcessor.process
```

可以看到是一个叫 LazyLoad 的插件提供的类导致的，应该是因为我们在新版本中移除了一个过时的问题导致的，建议向插件反馈修改这个问题。

修改方法可见：https://github.com/halo-sigs/plugin-umami/pull/22

/kind support

**Comment by yyhhkya** [comment]
好的感谢

**Comment by ruibaby** [comment]
目前你可以关闭此插件。
