### ISSUE TITLE
升级到halo:2.17后发现我的文章链接访问报错500

### ISSUE THREAD

**Issue by Jack-Ywn** [halo-dev/halo#6435]
### 系统信息

版本halo:2.17
数据库postgres:15.4

### 使用的哪种方式运行？

docker-compose

### 发生了什么？

我尝试升级halo:2.12到halo:2.17的版本
升级后发现访问文章链接报错500

### 复现步骤

我原本是打算升级到halo:2.18的版本，我尝试直接从halo:2.12的版本直接升级到halo:2.18，也出现了文章链接访问的时候报错500
我就开始从halo:2.12逐步升级
halo:2.12>halo:2.13  正常
halo:2.13>halo:2.14  正常
halo:2.14>halo:2.15  正常
halo:2.16>halo:2.17  此时出现文章链接访问的时候报错500

### 附加信息

[log.txt](https://github.com/user-attachments/files/16478823/log.txt)

**Comment by Jack-Ywn** [comment]
老版本升级到halo:2.17或者halo:2.18的时候，注意可以尝试先禁用这两个插件，特别是代码高亮插件，会导致500
![image](https://github.com/user-attachments/assets/cb59615d-a508-4cf6-9948-ff80cb8e33ef)

**Comment by ruibaby** [comment]
> 老版本升级到halo:2.17或者halo:2.18的时候，注意可以尝试先禁用这两个插件，特别是代码高亮插件，会导致500
> 
> ![image](https://github.com/user-attachments/assets/cb59615d-a508-4cf6-9948-ff80cb8e33ef)
> 
> 

建议从应用市场重新安装插件，实际上这些插件早已兼容。
