### ISSUE TITLE
Docker 12升级到18后, 首页和文章连接打不开了.后台正常.

### ISSUE THREAD

**Issue by aimu2000** [halo-dev/halo#6444]
### 系统信息

Docker 12升级到18后, 首页和文章连接打不开了.后台正常.

### 使用的哪种方式运行？

Docker

### 发生了什么？

Docker 12升级到18后, 首页和文章连接打不开了.后台正常.

### 复现步骤

后台正常,前台500错误

**Comment by aimu2000** [comment]
Failed to load resource: the server responded with a status of 500 ()

**Comment by ruibaby** [comment]
检查是否有插件不兼容，相关 issue：https://github.com/halo-dev/halo/issues/6273

/triage duplicate
