### ISSUE TITLE
当只分配了菜单管理而没有系统配置权限时菜单管理页面会报 403 错误

### ISSUE THREAD

**Issue by guqing** [halo-dev/halo#6468]
如题：错误原因是调用了 `/api/v1alpha1/configmaps/system` 获取主菜单，但没有权限

_Originally posted by @guqing in https://github.com/halo-dev/halo/issues/6462#issuecomment-2287764606_

**Comment by ruibaby** [comment]
我的建议是专门为主菜单信息的获取和更新提供接口，毕竟菜单管理权限强依赖 ConfigMap 的权限并不合理。

**Comment by guqing** [comment]
> 我的建议是专门为主菜单信息的获取和更新提供接口，毕竟菜单管理权限强依赖 ConfigMap 的权限并不合理。

我感觉可以单独为设置项出一个自定义 API 可以根据 group 来获取，这样就可以将权限绑定到 Menu 管理权限上，每个地方都为获取配置出两个自定义 APIs 感觉很繁琐

**Comment by ruibaby** [comment]
> 我感觉可以单独为设置项出一个自定义 API 可以根据 group 来获取，这样就可以将权限绑定到 Menu 管理权限上，每个地方都为获取配置出两个自定义 APIs 感觉很繁琐

专门给 system 的 ConfigMap 提供接口吗？还是 metadata.name 也可以传入

**Comment by guqing** [comment]
> > 我感觉可以单独为设置项出一个自定义 API 可以根据 group 来获取，这样就可以将权限绑定到 Menu 管理权限上，每个地方都为获取配置出两个自定义 APIs 感觉很繁琐
> 
> 专门给 system 的 ConfigMap 提供接口吗？还是 metadata.name 也可以传入

GET/PUT `/apis/console.api.halo.run/configmaps/{name}`
