### ISSUE TITLE
跳转链接是本地的

### ISSUE THREAD

**Issue by abcxiaobu** [halo-dev/halo#6474]
### 系统信息

https://www.xiaobu.xyz/ 个人控制台跳转的链接是本地的

### 使用的哪种方式运行？

Docker

### 发生了什么？

![image](https://github.com/user-attachments/assets/f3eb42dc-6691-414f-9c62-4a0f27545cce)

**Comment by guqing** [comment]
/triage duplicate

https://github.com/halo-dev/halo/issues/4760
https://github.com/halo-dev/halo/issues/6452
https://github.com/halo-dev/halo/issues/5484
https://github.com/halo-dev/halo/issues/3763
https://github.com/halo-dev/halo/issues/3696
https://github.com/halo-dev/halo/issues/3399
