### ISSUE TITLE
Halo一直高CPU占用

### ISSUE THREAD

**Issue by rong6** [halo-dev/halo#6478]
### 系统信息

- 外部访问地址: https://rong6.cn/
- 启动时间: 2024-08-19 00:02
- 版本: 2.18.0
- 构建时间: 2024-08-01 10:17
- Git Commit: 58fe872
- Java: IBM Semeru Runtime Open Edition / 21.0.3+9-LTS
- 数据库: Source distribution / 5.7.43-log
- 操作系统: Linux / 6.1.0-9-amd64
- 已激活主题: [Sakura 2.4.0](https://github.com/LIlGG/halo-theme-sakura.git)
- 已启动插件:
  - [备份增强插件 1.0.0](https://github.com/jiangqiang1996/qy-backup-plugin.git)
  - [Umami 1.4.0](https://github.com/halo-sigs/plugin-umami)
  - [通知我 1.1.0](https://github.com/monyuan/notify-me)
  - [OAuth2 认证 1.1.0](https://github.com/halo-sigs/plugin-oauth2)
  - [Metrics Graph 1.0.0](https://github.com/guqing/plugin-metrics-graph)
  - [文章导入导出 1.2.3](https://jhacker.cn/2023/halo-plugin-export2doc)
  - [Vditor 编辑器 1.7.1](https://github.com/justice2001/halo-plugin-vditor)
  - [Willow Markdown 编辑器 1.0.0-beta.2](https://github.com/guqing/willow-mde)
  - [瞬间 1.4.0](https://github.com/halo-sigs/plugin-moments)
  - [链接管理 1.3.2](https://github.com/halo-sigs/plugin-links)
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.6.2](https://github.com/halo-dev/plugin-search-widget)
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [评论组件 2.4.0](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场 1.3.0](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

之前一直用着旧版本，自更换服务器（2c4g）重新拉取最新版本[2.18.0](https://github.com/halo-dev/halo/releases/tag/v2.18.0)Docker镜像以来，Halo一直保持高CPU使用率（可至100%）。前几天重装了Halo，占用恢复正常，但是目前重新启动后依然保持高CPU占用，网站打开极度缓慢：
![image](https://github.com/user-attachments/assets/ed93ace1-4ff2-4677-bae5-1f54ea5eb304)
![image](https://github.com/user-attachments/assets/0dc5afda-99d8-41db-975c-fa478fea92ed)
日志已附在“附加信息”，求帮忙看看，谢谢了。

### 附加信息

这是宝塔Docker的容器日志，它记录了自容器启动后的所有日志：[0d867295b3f6f0db9c801a256e17307ebbcd9ceb7e36270d2594e424d12a421a-json.log](https://github.com/user-attachments/files/16649922/0d867295b3f6f0db9c801a256e17307ebbcd9ceb7e36270d2594e424d12a421a-json.log)   

这是Halo的日志：
[halo-log-2024-08-19_00_20.log](https://github.com/user-attachments/files/16650025/halo-log-2024-08-19_00_20.log)

**Comment by JohnNiang** [comment]
Hi @rong6 , thank you for reaching out here!

从日志来看，没有发现导致缓慢的异常信息。而且 Halo 启动只花了 15s，在服务器上感觉挺快的了。

另外，Halo 启动的时候会尝试构建索引和启动插件等流程，这个过程可能会大量消耗 CPU 和内存。建议长期持续监控一下服务器状态。仅靠瞬时的消耗无法说明问题。

/triage needs-information

> Started Application in 15.884 seconds (process running for 16.342)

**Comment by rong6** [comment]
> Hi @rong6 , thank you for reaching out here!
> 
> 从日志来看，没有发现导致缓慢的异常信息。而且 Halo 启动只花了 15s，在服务器上感觉挺快的了。
> 
> 另外，Halo 启动的时候会尝试构建索引和启动插件等流程，这个过程可能会大量消耗 CPU 和内存。建议长期持续监控一下服务器状态。仅靠瞬时的消耗无法说明问题。
> 
> /triage needs-information
> 
> > Started Application in 15.884 seconds (process running for 16.342)

我又重启了一遍，挂了一上午，名为java的进程一直保持高CPU占用，网站根本打不开，晚点我降级看看有没有改善

**Comment by rong6** [comment]
重启后莫名其妙好了，先这样吧
