### ISSUE TITLE
Add Index on comments.post_id to Accelerate Query

### ISSUE THREAD

**Issue by wtune** [halo-dev/halo#648]
## Problem
Missing index on table **comments** column **post_id** might make the underlying query slow
(eg. [BaseCommentRepository#findAllByPostId](https://github.com/halo-dev/halo/blob/c5af5d787d955fc1ecaeb7fdf4713d65c219918d/src/main/java/run/halo/app/repository/base/BaseCommentRepository.java#L46)).It's easy to find out that column post_id is always in the condition when we read table comments.It's worth adding the index on comments, although it is inserted somtimes. 
## Possible Solution
Add Index on comments.post_id

**Comment by ruibaby** [comment]
merged
