### ISSUE TITLE
第三方登录后没有根据角色跳转指定路径

### ISSUE THREAD

**Issue by QYG2297248353** [halo-dev/halo#6485]
### 系统信息

- 外部访问地址: https://blog.lifebus.top
- 启动时间: 2024-08-05 16:21
- 版本: 2.18.0
- 构建时间: 2024-08-01 10:17
- Git Commit: 58fe872
- Java: IBM Semeru Runtime Open Edition / 21.0.3+9-LTS
- 数据库: PostgreSQL / 16.3 (Debian 16.3-1.pgdg120+1)
- 操作系统: Linux / 5.14.0-427.18.1.el9_4.x86_64
- 已激活主题: [Earth 1.8.0](https://github.com/halo-dev/theme-earth.git)
- 已启动插件:
  - [豆瓣 1.2.0](https://github.com/chengzhongxue/plugin-douban)
  - [Data Studio（数据工厂） 1.0.0-alpha.2](https://github.com/halo-sigs/plugin-data-studio)
  - [无色界 1.0.0](https://github.com/guqing/halo-plugin-colorless)
  - [AList 存储库 1.0.1](https://github.com/halo-sigs/plugin-alist)
  - [页面静态缓存 1.1.0](https://github.com/halo-sigs/plugin-page-cache)
  - [链接管理 1.4.0](https://github.com/halo-sigs/plugin-links)
  - [StackEdit 1.1.1](https://github.com/halo-sigs/plugin-stackedit)
  - [ByteMD 1.4.0](https://github.com/ruibaby/plugin-bytemd)
  - [图库管理 1.4.0](https://github.com/halo-sigs/plugin-photos)
  - [Markdown / HTML 内容块 1.2.0](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [highlight.js 代码高亮 1.2.2](https://github.com/halo-sigs/plugin-highlightjs)
  - [OAuth2 认证 1.3.0](https://github.com/halo-sigs/plugin-oauth2)
  - [lightgallery.js 灯箱 1.2.1](https://github.com/halo-sigs/plugin-lightgallery)
  - [Trailing Slash 1.0.0](https://github.com/halo-sigs/plugin-trailing-slash)
  - [编辑器超链接卡片 1.0.3](https://github.com/halo-sigs/plugin-editor-hyperlink-card)
  - [瞬间 1.7.0](https://github.com/halo-sigs/plugin-moments)
  - [Umami 1.4.0](https://github.com/halo-sigs/plugin-umami)
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.6.2](https://github.com/halo-dev/plugin-search-widget)
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [评论组件 2.4.0](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场 1.3.0](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

根据角色配置《登录之后默认跳转位置》
使用本地登录也就是 用户名 + 密码 方式 正常跳转
但是使用 OAuth2 的 Gitee 登录后，就没有正常跳转，而是在默认页面 `/console/dashboard`

![image](https://github.com/user-attachments/assets/02e5b520-f422-4461-b23b-8af34d3c6ffc)

### 复现步骤

配置角色 登录后的跳转路径

配置 OAuth2 认证 登录方式

使用 OAuth2 登录

角色的跳转方式失效

**Comment by ruibaby** [comment]
ping @guqing 

/triage needs-information

**Comment by guqing** [comment]
此问题需要等待 https://github.com/halo-dev/halo/pull/6488 合并后修改插件解决
