### ISSUE TITLE
Add Index on links.name to Accelerate Query

### ISSUE THREAD

**Issue by wtune** [halo-dev/halo#650]
## Problem
Missing index on table **links** column **name** might make the underlying query issued
via [LinkServiceImpl#existByName](https://github.com/halo-dev/halo/blob/c5af5d787d955fc1ecaeb7fdf4713d65c219918d/src/main/java/run/halo/app/service/impl/LinkServiceImpl.java#L95) slow.Since table links is mostly read and sometimes inserted or updated, the performance impact for write operations is acceptable under common cases.
## Possible Solution
Add Index on links.name

**Comment by ruibaby** [comment]
merged
