### ISSUE TITLE
Oauth2集成问题

### ISSUE THREAD

**Issue by yasyx** [halo-dev/halo#6508]
### 系统信息

- 外部访问地址: https://yasy.run
- 启动时间: 2024-08-24 15:25
- 版本: 2.18.0
- 构建时间: 2024-08-01 10:17
- Git Commit: 58fe872
- Java: IBM Semeru Runtime Open Edition / 21.0.3+9-LTS
- 数据库: PostgreSQL / 15.4 (Debian 15.4-2.pgdg120+1)
- 操作系统: Linux / 5.15.0-91-generic
- 已激活主题: [Earth 1.8.0](https://github.com/halo-dev/theme-earth.git)
- 已启动插件:
  - [图库管理 1.3.0](https://github.com/halo-sigs/plugin-photos)
  - [文章导入导出 1.2.4](https://jhacker.cn/2023/halo-plugin-export2doc)
  - [AI 助手 1.0.0](https://www.halo.run/store/apps/app-riNgb)
  - [Docsme 1.0.0-alpha.6](https://www.halo.run/store/apps/app-yffxw)
  - [对象存储（Amazon S3 协议） 1.9.1](https://github.com/halo-dev/plugin-s3)
  - [OAuth2 认证 1.3.0](https://github.com/halo-sigs/plugin-oauth2)
  - [Sitemap 1.1.1](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.4.0](https://github.com/halo-dev/plugin-search-widget)
  - [RSS 1.2.2](https://github.com/halo-dev/plugin-feed)
  - [评论组件 2.2.0](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场 1.4.0](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker

### 发生了什么？

集成github登录后，跳转地址中redirect uri 为http://localhost:8090

### 复现步骤

1. 登录时选择github登录方式
2. 点击登录，查看重定向地址

### 附加信息

![image](https://github.com/user-attachments/assets/861c1da1-deea-440b-a62c-f312826ebf40)

**Comment by JohnNiang** [comment]
确认一下你配置了 `External URL` 么？配置可参考：<https://docs.halo.run/category/%E5%AE%89%E8%A3%85%E6%8C%87%E5%8D%97>。

/triage needs-information

**Comment by yasyx** [comment]
docker compose文件 配置了 --halo.external-url=https://yasy.run 
<img width="759" alt="image" src="https://github.com/user-attachments/assets/df44868a-1d12-4bef-97d0-ed40bde79851">
我一开始也是怀疑这里，但是改完了也没效果。我这边目前是修改数据库里字段解决的。
``` sql
UPDATE
      extensions
  SET
      data = convert_to(
          jsonb_set(
              convert_from(data, 'UTF-8') :: jsonb,
              '{spec,redirectUri}',
              '"https://yasy.run/login/oauth2/code/gitee"'
          ) :: text,
          'UTF-8'
      )
  WHERE
      name LIKE '/registry/oauth.halo.run/oauth2clientregistrations/gitee';
```

**Comment by guqing** [comment]
检查你的 github oauth2 应用的 Authorization callback URL 是否正确

<img width="597" alt="image" src="https://github.com/user-attachments/assets/1e8ba82b-e74e-4ae6-a244-e0060009423f">

**Comment by yasyx** [comment]
我截图中的链接是点击github登录时跳转的链接，从业务流程上来说的话好像还不到用到callback url的步骤。
我这里的配置其实也是配置好了。
![image](https://github.com/user-attachments/assets/a83b2015-075c-4f99-972e-ee5c36f85919)

**Comment by yasyx** [comment]
数据库中有个配置叫redirectUri 它的默认配置是 {baseUri}/login/oauth2/code/github。 所以我倾向于是这个baseUri没有正确配置造成的，但是我没找到在哪配置这个变量。所以我就直接修改了这个值

**Comment by guqing** [comment]
> 数据库中有个配置叫redirectUri 它的默认配置是 {baseUri}/login/oauth2/code/github。 所以我倾向于是这个baseUri没有正确配置造成的，但是我没找到在哪配置这个变量。所以我就直接修改了这个值

baseUri 是根据你的访问地址来自动获取的，比如你访问的是 https://yasy.run 那么从当前请求中获取到的地址就是这个域名，除非是 nginx 没有配置好导致无法从请求中获取到正确的访问地址

**Comment by yasyx** [comment]
那我知道是咋回事儿了，我这边nginx应该是没有配host相关的变量。

**Comment by yasyx** [comment]
谢谢各位大佬。@all

**Comment by yasyx** [comment]
![image](https://github.com/user-attachments/assets/2c747167-ff2d-4b92-ba59-bef7733de9b0)
目前我访问的地址是https，这个redirect_uri的协议会被替换为http，这个是halo的行为吗。

**Comment by guqing** [comment]
> ![image](https://private-user-images.githubusercontent.com/12021357/361294878-2c747167-ff2d-4b92-ba59-bef7733de9b0.png?
> 目前我访问的地址是https，这个redirect_uri的协议会被替换为http，这个是halo的行为吗。

同样的，说明从当前请求获得的协议是 http，检查 nginx 是否携带了协议，比如 `proxy_set_header X-Forwarded-Proto $scheme;`

**Comment by yasyx** [comment]
@guqing 感谢，已搞定。
我感觉咱们后端的插件架构设计的很有意思，但是文档上没看到相关的资料。您这边有相关资料可以参考吗

**Comment by guqing** [comment]
> @guqing 感谢，已搞定。 我感觉咱们后端的插件架构设计的很有意思，但是文档上没看到相关的资料。您这边有相关资料可以参考吗

有一个 RFC 可以参考 https://github.com/halo-dev/rfcs/blob/main/plugin/pluggable-design.md
具体实现就需要看源码了

**Comment by yasyx** [comment]
> > @guqing 感谢，已搞定。 我感觉咱们后端的插件架构设计的很有意思，但是文档上没看到相关的资料。您这边有相关资料可以参考吗
> 
> 有一个 RFC 可以参考 https://github.com/halo-dev/rfcs/blob/main/plugin/pluggable-design.md 还可以参考 [插件开发文档](https://docs.halo.run/developer-guide/plugin/basics/framework) 具体实现就需要看源码了

好的，谢谢
