### ISSUE TITLE
默认编辑器的行内代码显示异常

### ISSUE THREAD

**Issue by jxd134** [halo-dev/halo#6513]
### 系统信息

- 外部访问地址: https://www.2tuan.work/
- 启动时间: 2024-08-23 15:24
- 版本: 2.18.0
- 构建时间: 2024-08-01 10:17
- Git Commit: 58fe872
- Java: IBM Semeru Runtime Open Edition / 21.0.3+9-LTS
- 数据库: PostgreSQL / 15.4 (Debian 15.4-2.pgdg120+1)
- 操作系统: Linux / 5.15.0-119-generic
- 已激活主题: [Earth 1.8.0](https://github.com/halo-dev/theme-earth.git)
- 已启动插件:
  - [链接管理 1.4.0](https://github.com/halo-sigs/plugin-links)
  - [编辑器超链接卡片 1.0.3](https://github.com/halo-sigs/plugin-editor-hyperlink-card)
  - [瞬间 1.7.0](https://github.com/halo-sigs/plugin-moments)
  - [页面静态缓存 1.1.0](https://github.com/halo-sigs/plugin-page-cache)
  - [OAuth2 认证 1.3.0](https://github.com/halo-sigs/plugin-oauth2)
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.6.2](https://github.com/halo-dev/plugin-search-widget)
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [评论组件 2.4.0](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场 1.4.0](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

![图片](https://github.com/user-attachments/assets/0f1418ad-2387-43a0-a3b9-2f0554729733)
默认浏览器中编写文章，行内代码使用编辑器的快捷按钮进行设置，编辑页面显示正常。
![图片](https://github.com/user-attachments/assets/9da8bcb7-4563-44fd-bbdd-0b0d4948c7bd)
文章发布后，发现行内代码，会出现*``*包围行内代码现象。
文章链接URL：https://www.2tuan.work/archives/rCore-Learning%E2%80%94address-translation-under-RISC-V%27s-SV39-multi-level-page-table-mechanism

### 复现步骤

1.打开默认编辑器，编写文章；
2.选择指定段落，启用行内代码；
3.发布文章；
4.检查文章页面，发现行内代码显示异常。

### 附加信息

相同现象地址：
- https://www.2tuan.work/archives/Random-number-generator-in-Java%3A%20the-difference-between-Random%2FThreadLocalRandom%2FSecureRandom
- https://www.2tuan.work/archives/MyBatis-Plus-entity-field-encrypted-storage-solution

**Comment by LIlGG** [comment]
提交 Issue 前建议先进行搜索，可以比较快速的解决问题。

/triage duplicate

Duplicate of #5709

/close
