### ISSUE TITLE
Add Index on tags.name to Accelerate Query

### ISSUE THREAD

**Issue by wtune** [halo-dev/halo#652]
## Problem
Missing index on table **tags** column **name** might make the underlying query issued 
via [TagServiceImpl#getByName](https://github.com/halo-dev/halo/blob/c5af5d787d955fc1ecaeb7fdf4713d65c219918d/src/main/java/run/halo/app/service/impl/TagServiceImpl.java#L71) slow. Since TagServiceImpl always read table **tags** with the condition including column **name**, it's worth adding index on tags.name.
## Possible Solution
Add Index on tags.name

**Comment by ruibaby** [comment]
merged
