### ISSUE TITLE
2.19.0-rc.2版本   postFinder.list 方法排序无效

### ISSUE THREAD

**Issue by chengzhongxue** [halo-dev/halo#6534]
### 系统信息

- 外部访问地址: http://localhost:8088/
- 启动时间: 2024-08-28 11:08
- 版本: 2.19.0-rc.2
- 构建时间: 2024-08-27 20:48
- Git Commit: 2815678
- Java: IBM Semeru Runtime Open Edition / 21.0.4+7-LTS
- 数据库: H2 / 2.2.224
- 操作系统: Linux / 5.10.16.3-microsoft-standard-WSL2
- 已激活主题: Oyiso 1.1.1
- 已启动插件:
  - [highlight.js 代码高亮 1.2.1](https://github.com/halo-sigs/plugin-highlightjs)
  - [豆瓣 1.1.6](https://github.com/chengzhongxue/plugin-douban)
  - [朋友圈 1.3.2](https://github.com/chengzhongxue/plugin-friends)
  - [Vditor 编辑器 1.7.0](https://github.com/justice2001/halo-plugin-vditor)
  - [文章限制阅读 Pro 1.2.3](https://github.com/f2ccloud/plugin-restricted-reading-pro)
  - [文章导入导出 1.2.4](https://jhacker.cn/2023/halo-plugin-export2doc)
  - [图库管理 1.3.0](https://github.com/halo-sigs/plugin-photos)
  - [对象存储（Amazon S3 协议） 1.9.1](https://github.com/halo-dev/plugin-s3)
  - [ByteMD 1.4.0](https://github.com/ruibaby/plugin-bytemd)
  - [Markdown / HTML 内容块 1.2.0](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [瞬间 1.7.0](https://github.com/halo-sigs/plugin-moments)
  - [链接管理 1.3.3](https://github.com/halo-sigs/plugin-links)
  - [RSS 1.2.2](https://github.com/halo-dev/plugin-feed)
  - [评论组件 2.2.0](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场 1.2.0](https://www.halo.run/store/apps/app-VYJbF)
  - [搜索组件 1.6.1](https://github.com/halo-dev/plugin-search-widget)
  - [Sitemap 1.1.1](https://github.com/halo-dev/plugin-sitemap)

### 使用的哪种方式运行？

Docker

### 发生了什么？

postFinder.list({page: 1, size: 8, sort: {'stats.visit,desc'}}) 当前语法是否错误

**Comment by JohnNiang** [comment]
/assign @guqing 
/kind bug
/area core
/area theme
/milestone 2.19.0

The issue was introduced by <https://github.com/halo-dev/halo/pull/6531>.
