### ISSUE TITLE
Add Index on menus.parent_id to Accelerate Query

### ISSUE THREAD

**Issue by wtune** [halo-dev/halo#654]
## Problem
Missing index on table **menus** column **parent_id** might make the underlying query issued via 
[MenuServiceImpl#listByParentId](https://github.com/halo-dev/halo/blob/c5af5d787d955fc1ecaeb7fdf4713d65c219918d/src/main/java/run/halo/app/service/impl/MenuServiceImpl.java#L127) slow. Since table **menus** is mostly read and sometimes inserted or updated, the performance impact for write operations is acceptable under common cases.
## Possible Solution
Add Index on menus.parent_id

**Comment by ruibaby** [comment]
merged
