### ISSUE TITLE
不支持流格式的视频 hls  m3u8 

### ISSUE THREAD

**Issue by oxygensohn** [halo-dev/halo#6559]
### 你当前使用的版本

2.18

### 描述一下此特性

不支持流格式的视频 hls  m3u8 , 请问能支持吗？

**Comment by SuJin860912** [comment]
2、avif 格式不支持预览，不能直接插入为图片。

**Comment by ruibaby** [comment]
目前 Halo 编辑器的视频嵌入功能是单纯的利用浏览器的 video 标签，没有使用三方播放器库，了解到 m3u8 在 video 标签中使用时，只有少部分设备支持（Apple Safari），所以并不能直接利用 video 标签加载 m3u8 流媒体。

当前也没有引入三方播放器库的计划，但此功能可以通过插件在主题侧加载三方播放器库来实现。

/priority awaiting-more-evidence

**Comment by ruibaby** [comment]
> 2、avif 格式不支持预览，不能直接插入为图片。

2.19 已经支持。

**Comment by oxygensohn** [comment]
![WeChat0e882b3753f2d15c72d5344b0376b048](https://github.com/user-attachments/assets/f31d13d1-8360-4c8c-8bb9-50d906d07951)
![WeChat9377e15d29fa17e900b338d217b80341](https://github.com/user-attachments/assets/062e6604-81ef-47ae-9dd4-1dd6475fa7de)
![WeChat581b7f746dfb9ac12ff8680a33075785](https://github.com/user-attachments/assets/69e73f84-4ffe-476d-9590-e3bb5be8c8d6)

**Comment by oxygensohn** [comment]
<img width="748" alt="image" src="https://github.com/user-attachments/assets/c4137cbe-6221-4ce5-b2d5-ea4684c407e3">

**Comment by oxygensohn** [comment]
插入图片，并不能选择avif格式的图片。

**Comment by ruibaby** [comment]
你这里的图片文件类型为 application/octet-stream，我不清楚你这个图片为什么是这个类型，我这边上传的 avif 文件是正确的。

<img width="846" alt="image" src="https://github.com/user-attachments/assets/3c91821f-0f2c-4ac9-a8a5-7b20746677f0">

**Comment by oxygensohn** [comment]
刚测试过，存服务器本地能正常识别为image/avif ,存至minio 识别为application/octet-stream

**Comment by ruibaby** [comment]
> 刚测试过，存服务器本地能正常识别为image/avif ,存至minio 识别为application/octet-stream

那我不认为这是 Halo 需要解决的问题，我们无法根据 application/octet-stream 去识别为 avif，根据后缀也不会是一个稳妥的方案。

**Comment by oxygensohn** [comment]
明白了，我需要解决minio 服务器，感谢解答。

**Comment by oxygensohn** [comment]
已上传至Minio服务器的图片，通过 minio mc 命令批量修改 content-type类型。

**Comment by oxygensohn** [comment]
对象存储（Amazon S3 协议） 
<img width="842" alt="image" src="https://github.com/user-attachments/assets/592ae1ac-b69e-4f3e-a8f1-9a370605fa81">
通过插件上传的avif  ，需要更新插件对于avif上传Content-Type指定为image/avif

**Comment by oxygensohn** [comment]
minio browser 手动上传avif格式图片至服务器，Content-Type 正确 image/avif
<img width="623" alt="image" src="https://github.com/user-attachments/assets/b9b71641-e956-4069-a3f7-dbc85b0ea4c8">
通过S3关联服务器上未关联的avif，附件中正常识别为image/avif，文章页面能够正常插入图片。
