### ISSUE TITLE
Add Index on photos.team to Accelerate Query

### ISSUE THREAD

**Issue by wtune** [halo-dev/halo#656]
## Problem
Missing index on table **photos** column **team** might make the underlying query issued via 
[PhotoServiceImpl#listByTeam](https://github.com/halo-dev/halo/blob/c5af5d787d955fc1ecaeb7fdf4713d65c219918d/src/main/java/run/halo/app/service/impl/PhotoServiceImpl.java#L77) slow. Since we always read table **photos** by column team, it's worth adding index on photos.team.
## Possible Solution
Add Index on photos.team

**Comment by ruibaby** [comment]
merged
