### ISSUE TITLE
halo 中自建页面字数统计有问题。

### ISSUE THREAD

**Issue by zyy2477** [halo-dev/halo#6560]
### 系统信息

- 外部访问地址: https://www.seafog.cn/
- 启动时间: 2024-08-20 17:01
- 版本: 2.17.2
- 构建时间: 2024-07-15 18:19
- Git Commit: 6d4bedd
- Java: IBM Semeru Runtime Open Edition / 21.0.3+9-LTS
- 数据库: Source distribution / 8.0.36
- 操作系统: Linux / 4.18.0-477.13.1.el8_8.x86_64
- 已激活主题: [Dream 1.3.2](https://github.com/nineya/halo-theme-dream2.0.git)
- 已启动插件:
  - [静态网页服务 1.0.0-alpha.5](https://www.halo.run/store/apps/app-gFkMn)
  - [lightgallery.js 灯箱 1.2.1](https://github.com/halo-sigs/plugin-lightgallery)
  - [Vditor 编辑器 1.8.0](https://github.com/justice2001/halo-plugin-vditor)
  - [应用市场 1.4.0](https://www.halo.run/store/apps/app-VYJbF)
  - [highlight.js 代码高亮 1.2.2](https://github.com/halo-sigs/plugin-highlightjs)
  - [对象存储（Amazon S3 协议） 1.11.0](https://github.com/halo-dev/plugin-s3)
  - [图库管理 1.4.0](https://github.com/halo-sigs/plugin-photos)
  - [瞬间 1.7.0](https://github.com/halo-sigs/plugin-moments)
  - [链接管理 1.4.0](https://github.com/halo-sigs/plugin-links)
  - [ByteMD 1.4.0](https://github.com/ruibaby/plugin-bytemd)
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.6.2](https://github.com/halo-dev/plugin-search-widget)
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [评论组件 2.4.0](https://github.com/halo-dev/plugin-comment-widget)

### 使用的哪种方式运行？

Docker

### 发生了什么？

https://www.seafog.cn/about 这个关于我的页面字数统计，似乎有点问题。文中50个字都没有，不知为何统计出1033字出来。如图：
![image](https://github.com/user-attachments/assets/29afed38-dd64-4e0d-8db0-0e5a7c6b3fa1)

---

另外在 console 页面中的自建页面里，有一个基础的历史版本，无法清理。是否正常呢？
![image](https://github.com/user-attachments/assets/9876aef4-7c0f-4aa2-9ad2-d62ef86b8334)

**Comment by ruibaby** [comment]
字数统计问题建议向具体的主题反馈，因为目前 Halo 并没有提供字数统计的功能，编辑器侧边栏中的字数统计也仅仅是编辑器的功能。

> 另外在 console 页面中的自建页面里，有一个基础的历史版本，无法清理。是否正常呢？

基础版本为第一次创建的版本，清理之后无法和后续的版本做对比，所以不能删除。
