### ISSUE TITLE
看板娘插件无法显示模型图片

### ISSUE THREAD

**Issue by aling466** [halo-dev/halo#6567]
### 系统信息

- 外部访问地址: 
- 启动时间: 2024-09-02 00:53
- 版本: 2.18.0
- 构建时间: 2024-08-01 10:17
- Git Commit: 58fe872
- Java: IBM Semeru Runtime Open Edition / 21.0.3+9-LTS
- 数据库: H2 / 2.2.224
- 操作系统: Linux / 6.1.74-Unraid
- 已激活主题: [iEmo 1.0.2](https://github.com/chengzhongxue/halo-theme-iemo)
- 已启动插件:
  - [live2d 看板娘 1.2.1](https://github.com/LIlGG/plugin-live2d)
  - [链接管理 1.4.0](https://github.com/halo-sigs/plugin-links)
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [站点迁移 1.7.0](https://github.com/halo-sigs/plugin-migrate)
  - [瞬间 1.7.0](https://github.com/halo-sigs/plugin-moments)
  - [评论组件 2.4.0](https://github.com/halo-dev/plugin-comment-widget)
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [Markdown / HTML 内容块 1.2.0](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [站点推送插件 1.5.2](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [highlight.js 代码高亮 1.2.2](https://github.com/halo-sigs/plugin-highlightjs)
  - [编辑器超链接卡片 1.0.3](https://github.com/halo-sigs/plugin-editor-hyperlink-card)
  - [lightgallery.js 灯箱 1.2.1](https://github.com/halo-sigs/plugin-lightgallery)
  - [无色界 1.0.0](https://github.com/guqing/halo-plugin-colorless)
  - [OAuth2 认证 1.3.0](https://github.com/halo-sigs/plugin-oauth2)
  - [图库管理 1.4.0](https://github.com/halo-sigs/plugin-photos)
  - [搜索组件 1.6.2](https://github.com/halo-dev/plugin-search-widget)
  - [应用市场 1.4.0](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker

### 发生了什么？

看板娘版本：1.2.1，
halo版本：2.18

问题：看板娘插件突然无法在桌面显示模型图片，即使重新安装插件也无法解决
docker后台日志无报错
![image](https://github.com/user-attachments/assets/b4cf5f37-e6e9-485b-99d9-6e62ea911f74)
![image](https://github.com/user-attachments/assets/4fbe25ef-ee15-474e-bda3-8f00e010a782)
![image](https://github.com/user-attachments/assets/affe59a5-f7b7-4f08-874e-9377b053f7da)
![image](https://github.com/user-attachments/assets/50596a3b-223d-481a-9b5b-29a1a6b4ed41)

**Comment by LIlGG** [comment]
与 Halo 无关，请前往插件仓库提交 issue。

/close
