### ISSUE TITLE
无法统计评论数量

### ISSUE THREAD

**Issue by aling466** [halo-dev/halo#6572]
### 系统信息

- 外部访问地址: 
- 启动时间: 2024-09-02 10:51
- 版本: 2.18.0
- 构建时间: 2024-08-01 10:17
- Git Commit: 58fe872
- Java: IBM Semeru Runtime Open Edition / 21.0.3+9-LTS
- 数据库: H2 / 2.2.224
- 操作系统: Linux / 6.1.74-Unraid
- 已激活主题: [iEmo 1.0.2](https://github.com/chengzhongxue/halo-theme-iemo)
- 已启动插件:
  - [live2d 看板娘 1.2.1](https://github.com/LIlGG/plugin-live2d)
  - [链接管理 1.4.0](https://github.com/halo-sigs/plugin-links)
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [站点迁移 1.7.0](https://github.com/halo-sigs/plugin-migrate)
  - [瞬间 1.7.0](https://github.com/halo-sigs/plugin-moments)
  - [评论组件 2.4.0](https://github.com/halo-dev/plugin-comment-widget)
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [Markdown / HTML 内容块 1.2.0](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [站点推送插件 1.5.2](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [highlight.js 代码高亮 1.2.2](https://github.com/halo-sigs/plugin-highlightjs)
  - [编辑器超链接卡片 1.0.3](https://github.com/halo-sigs/plugin-editor-hyperlink-card)
  - [lightgallery.js 灯箱 1.2.1](https://github.com/halo-sigs/plugin-lightgallery)
  - [无色界 1.0.0](https://github.com/guqing/halo-plugin-colorless)
  - [OAuth2 认证 1.3.0](https://github.com/halo-sigs/plugin-oauth2)
  - [图库管理 1.4.0](https://github.com/halo-sigs/plugin-photos)
  - [搜索组件 1.6.2](https://github.com/halo-dev/plugin-search-widget)
  - [应用市场 1.4.0](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker

### 发生了什么？

仪表盘无法正确统计评论数量
![image](https://github.com/user-attachments/assets/f14f9df5-40d4-494c-a1d8-8a66474be461)
![image](https://github.com/user-attachments/assets/12d4844e-abad-4ac2-8e3c-ee20e347cbc5)

**Comment by guqing** [comment]
我试了一下没有复现，你可以再创建一条试试来触发一下评论数量更新，如果还没有的话就提供一下日志

**Comment by aling466** [comment]
> 我试了一下没有复现，你可以再创建一条试试来触发一下评论数量更新，如果还没有的话就提供一下日志

[halo-log-2024-09-03 19_04.log](https://github.com/user-attachments/files/16847637/halo-log-2024-09-03.19_04.log)

**Comment by aling466** [comment]
> 我试了一下没有复现，你可以再创建一条试试来触发一下评论数量更新，如果还没有的话就提供一下日志

[halo-log-2024-09-03 19_04.log](https://github.com/user-attachments/files/16847642/halo-log-2024-09-03.19_04.log)
日志，请查收

**Comment by aling466** [comment]
> 我试了一下没有复现，你可以再创建一条试试来触发一下评论数量更新，如果还没有的话就提供一下日志

[halo-log-2024-09-03 19_16.log](https://github.com/user-attachments/files/16847745/halo-log-2024-09-03.19_16.log)
我这边是了一下，只要我启用这个主题[iEmo 1.0.2](https://github.com/chengzhongxue/halo-theme-iemo)，就无法正确统计数量

**Comment by chengzhongxue** [comment]
已解决主题问题

**Comment by JohnNiang** [comment]
/close

See https://github.com/chengzhongxue/halo-theme-iemo/commit/8e9de30aa9d6e3a6209c85b59799040953554d10 for more.
