### ISSUE TITLE
文章里的多级标题显示 效果失效

### ISSUE THREAD

**Issue by aling466** [halo-dev/halo#6577]
### 系统信息

- 外部访问地址: 
- 启动时间: 2024-09-02 13:53
- 版本: 2.19.0
- 构建时间: 2024-09-02 10:37
- Git Commit: 142f46b
- Java: IBM Semeru Runtime Open Edition / 21.0.4+7-LTS
- 数据库: H2 / 2.2.224
- 操作系统: Linux / 6.1.74-Unraid
- 已激活主题: [iEmo 1.0.3](https://github.com/chengzhongxue/halo-theme-iemo)
- 已启动插件:
  - [Webhook 1.0.0](https://www.wxy97.com/)
  - [页面静态缓存 1.1.0](https://github.com/halo-sigs/plugin-page-cache)
  - [链上好文 1.0.1](https://github.com/guqing/plugin-share-post-via-link)
  - [链接管理 1.4.0](https://github.com/halo-sigs/plugin-links)
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [站点迁移 1.7.0](https://github.com/halo-sigs/plugin-migrate)
  - [瞬间 1.7.0](https://github.com/halo-sigs/plugin-moments)
  - [评论组件 2.4.0](https://github.com/halo-dev/plugin-comment-widget)
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [Markdown / HTML 内容块 1.2.0](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [站点推送插件 1.5.2](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [highlight.js 代码高亮 1.3.0](https://github.com/halo-sigs/plugin-lightgallery)
  - [编辑器超链接卡片 1.0.3](https://github.com/halo-sigs/plugin-editor-hyperlink-card)
  - [lightgallery.js 灯箱 1.2.1](https://github.com/halo-sigs/plugin-lightgallery)
  - [无色界 1.0.0](https://github.com/guqing/halo-plugin-colorless)
  - [OAuth2 认证 1.3.0](https://github.com/halo-sigs/plugin-oauth2)
  - [图库管理 1.4.0](https://github.com/halo-sigs/plugin-photos)
  - [搜索组件 1.6.2](https://github.com/halo-dev/plugin-search-widget)
  - [应用市场 1.4.0](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker

### 发生了什么？

文章里的多级标题显示效果失效，实际显示效果一样
![image](https://github.com/user-attachments/assets/cfb5eaad-68d1-4d36-956d-e28eef650cb1)
![image](https://github.com/user-attachments/assets/96430bca-2dd9-42a0-bcbb-801f0d55cf7e)
![image](https://github.com/user-attachments/assets/8267d8e9-ef8f-4e27-bfa3-979553b333ce)

### 附加信息

持续出现

**Comment by ruibaby** [comment]
![image](https://github.com/user-attachments/assets/7e4510b7-aa60-436a-ab46-6eb5c3336bed)

这个为主题的功能，Halo 无法干预，请向主题提交 issue。

/triage unresolved
/close
