### ISSUE TITLE
2.19版本图片响应式对小尺寸图片显示不友好

### ISSUE THREAD

**Issue by Mira-Get** [halo-dev/halo#6579]
### 系统信息

略

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

2.19版本图片响应式对小尺寸图片显示不友好。在文章中插入一张64*64px的小图，宽高设置都是auto，然后分别在2.18和2.19版本中查看文章，截图如下。
![d1d9e12c3372d745dd57e940139327c](https://github.com/user-attachments/assets/76f94315-b9ad-4a95-a117-79a635d2c08d)

![b2a94533fa61971d02b9c6c16df3a4e](https://github.com/user-attachments/assets/06d361fb-33a6-4137-b189-c380e649ec9f)

![ccb21f37034c0246ec0e2d863de5f46](https://github.com/user-attachments/assets/bd99281a-c959-4053-8a36-552d470cfdf7)

### 复现步骤

1.随便写一篇文章，插入一张小图，比如50*50px的那种，图片显示宽高设置为auto。
2.发布文章，查看文章。

### 相关日志输出

```shell
略
```

### 附加信息

略

**Comment by ruibaby** [comment]
确实存在这个问题，应该需要优化一下尺寸生成的逻辑，如果原尺寸小于目标尺寸，应该忽略。

/kind improvement
/area core
