### ISSUE TITLE
select 的 fieldSelector 查询有问题

### ISSUE THREAD

**Issue by chengzhongxue** [halo-dev/halo#6589]
### 系统信息

- 外部访问地址: https://noxox.cn
- 启动时间: 2024-09-04 23:55
- 版本: 2.19.1
- 构建时间: 2024-09-04 14:26
- Git Commit: 30d054a
- Java: IBM Semeru Runtime Open Edition / 21.0.4+7-LTS
- 数据库: PostgreSQL / 16.3
- 操作系统: Linux / 3.10.0-957.1.3.el7.x86_64
- 已激活主题: [Earth 1.8.0](https://github.com/halo-dev/theme-earth.git)
- 已启动插件:
  - [Data Studio（数据工厂） 1.0.0-alpha.2](https://github.com/halo-sigs/plugin-data-studio)
  - [编辑器超链接卡片 1.0.3](https://github.com/halo-sigs/plugin-editor-hyperlink-card)
  - [插件授权管理 1.2.0](https://github.com/liuyiwuqing/lywq-plugins-auth)
  - [lightgallery.js 灯箱 1.2.1](https://github.com/halo-sigs/plugin-lightgallery)
  - [highlight.js 代码高亮 1.2.2](https://github.com/halo-sigs/plugin-highlightjs)
  - [Umami 1.4.0](https://github.com/halo-sigs/plugin-umami)
  - [Vditor 编辑器 1.8.0](https://github.com/justice2001/halo-plugin-vditor)
  - [Markdown / HTML 内容块 1.2.0](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [应用市场 1.4.0](https://www.halo.run/store/apps/app-VYJbF)
  - [增强备份（Backup IMproved） 1.1.1](https://www.halo.run/store/apps/app-dHakX)
  - [社交 IAM 认证 1.3.0](https://www.halo.run/store/apps/app-IXZkJ)
  - [链接管理 1.4.0](https://github.com/halo-sigs/plugin-links)
  - [对象存储（Amazon S3 协议） 1.11.0](https://github.com/halo-dev/plugin-s3)
  - [瞬间 1.7.0](https://github.com/halo-sigs/plugin-moments)
  - [OAuth2 认证 1.3.0](https://github.com/halo-sigs/plugin-oauth2)
  - [图库管理 1.4.0](https://github.com/halo-sigs/plugin-photos)
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [搜索组件 1.6.2](https://github.com/halo-dev/plugin-search-widget)
  - [评论组件 2.4.0](https://github.com/halo-dev/plugin-comment-widget)

### 使用的哪种方式运行？

Docker

### 发生了什么？

![8583224fba2eec2a4a24068d681b1c8](https://github.com/user-attachments/assets/b49ce72a-5448-4ece-a499-b6353652f015)
如果 valueField 设置 user.metadata.name 就会出现一下情况
![2d041fdcde80caa652c64df135a298d](https://github.com/user-attachments/assets/3629daa0-9204-4a15-8841-d1c6784ba0b3)

**Comment by JohnNiang** [comment]
Hi @chengzhongxue ，从[官方文档](https://github.com/halo-dev/halo/blob/733679d5ac98b9e93c373244e2b05d7d79000409/ui/docs/custom-formkit-input/README.md?plain=1#L233-L237)来看，应该是错误描述了 valueField 的值，这里尝试设置为 metadata.name 试试呢。

另外，请 @LIlGG 帮忙确认一下这里具体应该传入什么值？

/kind bug
/area ui

**Comment by LIlGG** [comment]
目前这里的值取的是 `valueField` 的值，可以额外增加一个参数用于解决此问题。

不过对于用户列表的查询，Halo 默认提供了 `userSelect` 这个 formkit 组件，可以直接使用。

**Comment by chengzhongxue** [comment]
> 目前这里的值取的是 `valueField` 的值，可以额外增加一个参数用于解决此问题。
> 
> 不过对于用户列表的查询，Halo 默认提供了 `userSelect` 这个 formkit 组件，可以直接使用。

这个支持多选？

**Comment by LIlGG** [comment]
> 这个支持多选？

默认支持多选，你也可以使用大部分支持 `Select` 的参数，因为它就是通过 `Select` 实现的。

**Comment by chengzhongxue** [comment]
> > 这个支持多选？
> 
> 默认支持多选，你也可以使用大部分支持 `Select` 的参数，因为它就是通过 `Select` 实现的。

好的
