### ISSUE TITLE
500:intenet sever error

### ISSUE THREAD

**Issue by douyan2662** [halo-dev/halo#6593]
### System information

升级为[2.19.1](https://github.com/halo-dev/halo/releases/tag/v2.19.1)版本后
console配置页面能访问和设置
但是预览时无法打开网站预览页面
报错显示：500:intenet sever error

### What is the project operation method?

Docker

### What happened?

升级为[2.19.1](https://github.com/halo-dev/halo/releases/tag/v2.19.1)版本后
console配置页面能访问和设置
但是预览时无法打开网站预览页面
报错显示：500:intenet sever error

**Comment by JohnNiang** [comment]
/close

请根据 Issue 模板认真填写。
