### ISSUE TITLE
formkit select组件值变化的问题

### ISSUE THREAD

**Issue by liuchangfitcloud** [halo-dev/halo#6594]
### 系统信息

- 外部访问地址: https://vaguely-integral-oyster.ngrok-free.app
- 启动时间: 2024-09-05 14:38
- 版本: 2.19.0-SNAPSHOT
- 构建时间: 2024-09-05 14:38
- Git Commit: c3ba869
- Java: Java(TM) SE Runtime Environment / 17.0.11+7-LTS-207
- 数据库: MySQL Community Server - GPL / 8.0.32
- 操作系统: Mac OS X / 12.2.1
- 已激活主题: [LingXia 1.5.0](https://github.com/f2ccloud/theme-lingxia.git)
- 已启动插件:
  - [应用市场 1.3.0](https://www.halo.run/store/apps/app-VYJbF)
  - [瞬间 1.7.0](https://github.com/halo-sigs/plugin-moments)
  - [链接管理 1.4.0](https://github.com/halo-sigs/plugin-links)
  - [图库管理 1.4.0](https://github.com/halo-sigs/plugin-photos)
  - [搜索组件 1.6.2](https://github.com/halo-dev/plugin-search-widget)
  - 联系表单 1.0.2
  - [评论组件 2.4.0](https://github.com/halo-dev/plugin-comment-widget)
  - [社交 IAM 认证 1.0.2-SNAPSHOT](https://www.halo.run/store/apps/app-IXZkJ)
  - [文章限制阅读 Pro 1.0.0-SNAPSHOT](https://www.halo.run/store/apps/app-TzRqd)
  - [LDAP 认证 1.0.0-SNAPSHOT](https://www.halo.run/store/apps/app-vrSqF)

### 使用的哪种方式运行？

Fat Jar

### 发生了什么？

- 值发生变化未触发change方法
- 如果本身选中某个值如选中`测试`再通过js将值设置为undefined，还是显示原来的label`测试`

**Comment by LIlGG** [comment]
`值发生变化未触发change方法` 

这里由于目前是自定义组件，因此 `@change` 事件传递的参数需要发生变化。即原来的参数为 `event`，更改之后现在的参数为 `Array<{ label: string; value: string }>`。
