### ISSUE TITLE
文章标签页显示文章数量与实际不符

### ISSUE THREAD

**Issue by luijp** [halo-dev/halo#6598]
### 系统信息

- 外部访问地址: https://blog.luijp.cn
- 启动时间: 2024-09-05 22:44
- 版本: 2.19.1
- 构建时间: 2024-09-04 14:28
- Git Commit: c3ba869
- Java: IBM Semeru Runtime Open Edition / 21.0.4+7-LTS
- 数据库: MariaDB / 11.5.2-MariaDB-ubu2404
- 操作系统: Linux / 5.15.0-107-generic
- 已激活主题: [Walker 1.10.0](https://www.halo.run/store/apps/app-GHgAR)
- 已启动插件:
  - [highlight.js 代码高亮 1.3.0](https://github.com/halo-sigs/plugin-lightgallery)
  - [瞬间 1.7.0](https://github.com/halo-sigs/plugin-moments)
  - [图库管理 1.4.0](https://github.com/halo-sigs/plugin-photos)
  - [页面静态缓存 1.2.0](https://github.com/halo-sigs/plugin-page-cache)
  - [对象存储（Amazon S3 协议） 1.11.0](https://github.com/halo-dev/plugin-s3)
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.6.2](https://github.com/halo-dev/plugin-search-widget)
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [评论组件 2.4.0](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场 1.4.0](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker

### 发生了什么？

当文章被删除后，后台标签数量不更新

### 复现步骤

1.发布文章并添加标签 xxx
2.直接删除文章

此时，后台查看标签页文章数量与实际文章数量不符

### 附加信息

![QQ20240905-225353](https://github.com/user-attachments/assets/e0a880aa-d3fb-445c-aea4-8439be4b2234)

**Comment by guqing** [comment]
文章是有回收站功能的，从回收站删除了吗

**Comment by luijp** [comment]
从回收站删除后确实数量就一致了，理解了
