### ISSUE TITLE
在Anatole主题下访问SSR atom.xml页面上会出现错误提示

### ISSUE THREAD

**Issue by jiajuncheng** [halo-dev/halo#660]
## 我的环境
Server 版本：1.2.0
Admin 版本：1.2.0
数据库：MySQL
运行模式：production
UA 信息：Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
![image](https://user-images.githubusercontent.com/20538542/76680573-97cef500-6624-11ea-87e8-eb08e035cf0c.png)
地址是：https://www.idreamyou.cn/atom.xml

**Comment by ruibaby** [comment]
这个已经修复了，请等待下个版本发布。
