### ISSUE TITLE
Failed to fetch backups

### ISSUE THREAD

**Issue by liuurick** [halo-dev/halo#661]
前辈你好，我是halo的使用者，最近在测试halo博客的备份功能，出现如无法备份的问题，请问是什么问题？
目前还是ip访问
**版本信息：**
Server 版本：1.2.0
Admin 版本：1.2.0
数据库：H2
运行模式：production
启动时间：2020-02-20 17:20
**Linux报错信息：**
![HM5TK66DZ3TX(ZE99T{CGKY](https://user-images.githubusercontent.com/35891330/76693568-4ebd8600-66a2-11ea-81d4-f77470f21f22.png)

## 我的环境

---

## 错误日志

---

**Comment by bestsort** [comment]
没能复现，能再详细一点吗

> 前辈你好，我是 halo 的使用者，最近在测试 halo 博客的备份功能，出现如无法备份的问题，请问是什么问题？
> 目前还是 ip 访问
> **版本信息：**
> Server 版本：1.2.0
> Admin 版本：1.2.0
> 数据库：H2
> 运行模式：production
> 启动时间：2020-02-20 17:20
> **Linux 报错信息：**
> ![HM5TK66DZ3TX(ZE99T{CGKY](https://user-images.githubusercontent.com/35891330/76693568-4ebd8600-66a2-11ea-81d4-f77470f21f22.png)
> 
> ## 我的环境
> ## 错误日志
> ## 期望行为
> ## 当前行为

没能复现BUG，描述可以再详细一点吗？

**Comment by ruibaby** [comment]
@liuurick 这是一个偶发性的bug，已修复，请等待下个版本发布

**Comment by liuurick** [comment]
👌，谢谢各位前辈
