### ISSUE TITLE
默认编辑器的引用中的有序列表不渲染开头数字

### ISSUE THREAD

**Issue by Sleepstars** [halo-dev/halo#6615]
### 系统信息

- 外部访问地址: https://blog.sleepstars.net
- 启动时间: 2024-09-03 13:32
- 版本: 2.19.0
- 构建时间: 2024-09-02 11:10
- Git Commit: 6c9a7dd
- Java: IBM Semeru Runtime Open Edition / 21.0.4+7-LTS
- 数据库: PostgreSQL / 16.4
- 操作系统: Linux / 6.1.0-23-arm64
- 已激活主题: [Walker 1.9.1](https://www.halo.run/store/apps/app-GHgAR)
- 已启动插件:
  - [Metrics Graph 1.0.0](https://github.com/guqing/plugin-metrics-graph)
  - [Vditor 编辑器 1.8.0](https://github.com/justice2001/halo-plugin-vditor)
  - [静态网页服务 1.0.0-alpha.5](https://www.halo.run/store/apps/app-gFkMn)
  - [站点推送插件 1.5.2](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [链接管理 1.5.0](https://github.com/halo-sigs/plugin-links)
  - [编辑器超链接卡片 1.0.3](https://github.com/halo-sigs/plugin-editor-hyperlink-card)
  - [图库管理 1.4.0](https://github.com/halo-sigs/plugin-photos)
  - [豆瓣 1.2.1](https://github.com/chengzhongxue/plugin-douban)
  - [页面静态缓存 1.2.0](https://github.com/halo-sigs/plugin-page-cache)
  - [AList 存储库 1.0.2](https://github.com/halo-sigs/plugin-alist)
  - [瞬间 1.7.0](https://github.com/halo-sigs/plugin-moments)
  - [对象存储（Amazon S3 协议） 1.11.0](https://github.com/halo-dev/plugin-s3)
  - [SEO 工具集 1.1.0](https://www.halo.run/store/apps/app-FNGbT)
  - [增强备份（Backup IMproved） 1.1.1](https://www.halo.run/store/apps/app-dHakX)
  - [文章限制阅读 1.4.1](https://www.halo.run/store/apps/app-IzWXo)
  - [文章导入导出 1.2.4](https://jhacker.cn/2023/halo-plugin-export2doc)
  - [Willow Markdown 编辑器 1.0.0](https://github.com/guqing/willow-mde)
  - [OAuth2 认证 1.3.0](https://github.com/halo-sigs/plugin-oauth2)
  - [lightgallery.js 灯箱 1.2.1](https://github.com/halo-sigs/plugin-lightgallery)
  - [highlight.js 代码高亮 1.3.0](https://github.com/halo-sigs/plugin-lightgallery)
  - [Markdown / HTML 内容块 1.2.0](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [搜索组件 1.6.2](https://github.com/halo-dev/plugin-search-widget)
  - [应用市场 1.5.0](https://www.halo.run/store/apps/app-VYJbF)
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [评论组件 2.4.0](https://github.com/halo-dev/plugin-comment-widget)

### 使用的哪种方式运行？

Docker

### 发生了什么？

使用默认编辑器的时候，插入引用后，在引用中插入有序列表，有序列表前数字不渲染，无序列表渲染情况正常。在文章实际预览中也可以正常渲染。
（图中1前为无序列表，a为有序列表，a前数字不渲染）
![image](https://github.com/user-attachments/assets/3b9fed76-327e-4881-a900-52c6367da6c9)

### 复现步骤

1. 使用默认编辑器
2. 正文部分使用引用
3. 引用中使用有序列表
4. 有序列表数字渲染消失

**Comment by ruibaby** [comment]
可以复现此问题，原因是列表样式层叠问题。

<img width="832" alt="image" src="https://github.com/user-attachments/assets/acf52707-652f-4724-8b5a-8928c917bf0e">

/kind bug
/area ui
/area editor
