### ISSUE TITLE
文章发表时间仅输入日期，点击发布后会重置为当前日期

### ISSUE THREAD

**Issue by luijp** [halo-dev/halo#6623]
### 系统信息

- 外部访问地址: https://blog.luijp.cn
- 启动时间: 2024-09-06 13:21
- 版本: 2.19.1
- 构建时间: 2024-09-04 14:28
- Git Commit: c3ba869
- Java: IBM Semeru Runtime Open Edition / 21.0.4+7-LTS
- 数据库: MariaDB / 11.5.2-MariaDB-ubu2404
- 操作系统: Linux / 5.15.0-107-generic
- 已激活主题: [Walker 1.10.0](https://www.halo.run/store/apps/app-GHgAR)
- 已启动插件:
  - [静态网页服务 1.0.0-alpha.5](https://www.halo.run/store/apps/app-gFkMn)
  - [highlight.js 代码高亮 1.3.0](https://github.com/halo-sigs/plugin-lightgallery)
  - [站点推送插件 1.5.2](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [瞬间 1.7.0](https://github.com/halo-sigs/plugin-moments)
  - [页面静态缓存 1.2.0](https://github.com/halo-sigs/plugin-page-cache)
  - [对象存储（Amazon S3 协议） 1.11.0](https://github.com/halo-dev/plugin-s3)
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.6.2](https://github.com/halo-dev/plugin-search-widget)
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [评论组件 2.4.0](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场 1.5.0](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker

### 发生了什么？

文章发表时间仅输入日期，点击发布后会重置为当前时间

### 复现步骤

1.文章编辑页面点击发布按钮
2.发表时间仅仅输入日期不输入时间（发表时间输入不完整）
3.文章发表成功，没有任何提示，文章发表时间重置为当前日期和时间。

是否应当给出恰当提示输入完整发表时间，或使用输入的发表日期而不完整地方系统根据一定的规则自动填充

![image](https://github.com/user-attachments/assets/9f32c9ab-abab-4bc0-b137-d01e9c9e0c20)

![image](https://github.com/user-attachments/assets/acc113f2-a3ca-4d6b-8d82-5a1c4e40b397)

**Comment by ruibaby** [comment]
<img width="672" alt="image" src="https://github.com/user-attachments/assets/fc9f5a00-6759-409a-b7b0-efbd113095b1">

需要完整输入或者选择时间，否则不会生效，这是浏览器原生实现的限制，在 https://github.com/halo-dev/halo/issues/2794 解决之前，无法很好解决此问题。

/triage duplicate

**Comment by JohnNiang** [comment]
/close

Close in favor of <https://github.com/halo-dev/halo/issues/2794>.
