### ISSUE TITLE
优化主题获取主菜单的 Finder API

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#6625]
### 你当前使用的版本

2.19.2

### 描述一下此特性

当前出现了不少关于主菜单找不到或者未设置的问题，导致前台无法正常渲染，这个时候也没有明显的提示原因。所以期望优化这个问题，建议方案：

1. 如果没有设置或者通过某种方式取消了主菜单的设置，那么直接使用第一个 Menu 数据。
2. 如果设置的主菜单不存在，同上。

/kind improvement
/area core

**Comment by guqing** [comment]
我尝试设置一个不存在的主菜单和不设置主菜单在默认主题下都不会报错,只有在没有任何菜单的情况下会出现这样的问题
