### ISSUE TITLE
最新版本默认编辑器在插入表格的时候会卡死

### ISSUE THREAD

**Issue by yangshifei** [halo-dev/halo#6626]
### 系统信息

- 外部访问地址: https://www.yangsf.top/
- 启动时间: 2024-09-10 10:16
- 版本: 2.19.1
- 构建时间: 2024-09-04 14:26
- Git Commit: 30d054a
- Java: IBM Semeru Runtime Open Edition / 21.0.4+7-LTS
- 数据库: PostgreSQL / 15.4 (Debian 15.4-2.pgdg120+1)
- 操作系统: Linux / 3.10.0-1160.108.1.el7.x86_64
- 已激活主题: [Butterfly 2.0.5](https://github.com/dhjddcn/halo-theme-butterfly.git)
- 已启动插件:
  - [静态网页服务 1.0.0-alpha.5](https://www.halo.run/store/apps/app-gFkMn)
  - [highlight.js 代码高亮 1.3.0](https://github.com/halo-sigs/plugin-lightgallery)
  - [站点推送插件 1.5.2](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [编辑器超链接卡片 1.0.3](https://github.com/halo-sigs/plugin-editor-hyperlink-card)
  - [对象存储（Amazon S3 协议） 1.11.0](https://github.com/halo-dev/plugin-s3)
  - [Vditor 编辑器 1.8.0](https://github.com/justice2001/halo-plugin-vditor)
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.6.2](https://github.com/halo-dev/plugin-search-widget)
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [评论组件 2.4.0](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场 1.5.0](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

最新版本2.19默认编辑器在插入表格的时候会卡死

**Comment by LIlGG** [comment]
在 2.19.2 中修复了这个问题。

see #6585

**Comment by yangshifei** [comment]
> 在 2.19.2 中修复了这个问题。
> 
> see #6585

好的谢谢
