### ISSUE TITLE
希望在ui的`package.json`中加入`packageManager`字段

### ISSUE THREAD

**Issue by ShiinaKin** [halo-dev/halo#6635]
### Describe this feature

`"packageManager": "pnpm@9.10.0"`

https://nodejs.org/api/packages.html#packagemanager

之前用旧版本pnpm运行时经常会遇到怪问题，最后更新pnpm之后再次install就行，加入此字段有助于减少这一问题

**Comment by ruibaby** [comment]
感谢反馈，可以考虑加上这个字段，但建议宽松一点，比如 `pnpm@9`。

另外，使用这个字段似乎必须要求启用 corepack，我不确定这是否会给维护者带来其他副作用。

/kind improvement
/area ui
