### ISSUE TITLE
希望文章添加附件功能自动可以识别文字（自动变成文字）

### ISSUE THREAD

**Issue by gcs8111** [halo-dev/halo#6640]
### 你当前使用的版本

2.19.3

### 描述一下此特性

![123](https://github.com/user-attachments/assets/9b57c693-caf9-431b-aaac-7f30cbc08212)

### 附加信息

![123](https://github.com/user-attachments/assets/8fa54b5a-f34b-4ab5-a78c-1169760b2e4a)

**Comment by ruibaby** [comment]
根据标题没有明白这个特性是怎样的，建议详细描述一下。

/triage needs-information
