### ISSUE TITLE
上传图片失败

### ISSUE THREAD

**Issue by xie-zhiyan** [halo-dev/halo#665]
## 我的环境

---

## 错误日志

---

## 当前行为

![TIM图片20200315222936](https://user-images.githubusercontent.com/42953750/76703422-9842bb00-670c-11ea-8718-50bd51b6eb49.png)

**Comment by ruibaby** [comment]
请按照 issue 填写相关内容。

**Comment by ruibaby** [comment]
已知问题。现已修复，请等待新版本发布。目前你可以通过重启 Halo 解决。
