### ISSUE TITLE
希望：默认编辑器新增导出功能

### ISSUE THREAD

**Issue by simanya2** [halo-dev/halo#6652]
### 描述一下此特性

希望：默认编辑器可以新增导出功能，比如导出markdown格式的文件，这样可以更方便去转成其他格式

**Comment by ruibaby** [comment]
现在社区已经有了类似的插件：https://github.com/Lyn4ever29/halo-plugin-export-md

如果这个插件不能满足需求，也仍然推荐使用插件去实现这个功能，当前不考虑在核心中提供。

/kind support

**Comment by simanya2** [comment]
好的谢谢
