### ISSUE TITLE
文章高级设置有不存在的用户

### ISSUE THREAD

**Issue by QingFeng-awa** [halo-dev/halo#6665]
### 系统信息

- 外部访问地址: https://qingfengawa.me
- 启动时间: 2024-09-16 18:46
- 版本: 2.19.3
- 构建时间: 2024-09-10 17:46
- Git Commit: b6ec7b9
- Java: IBM Semeru Runtime Open Edition / 21.0.4+7-LTS
- 数据库: MySQL Community Server - GPL / 8.4.2
- 操作系统: Linux / 6.1.0-10-amd64
- 已激活主题: [Hao 1.5.8](https://github.com/chengzhongxue/halo-theme-hao)
- 已启动插件:
  - [Markdown / HTML 内容块 1.2.0](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [编辑器超链接卡片 1.0.3](https://github.com/halo-sigs/plugin-editor-hyperlink-card)
  - [站点推送插件 1.5.2](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [爱发电插件 1.6.3](https://github.com/carolcoral/plugin-afdian)
  - [图库管理 1.4.0](https://github.com/halo-sigs/plugin-photos)
  - [链接管理 1.5.0](https://github.com/halo-sigs/plugin-links)
  - [瞬间 1.8.0](https://github.com/halo-sigs/plugin-moments)
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.6.2](https://github.com/halo-dev/plugin-search-widget)
  - [评论组件 2.4.0](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场 1.5.0](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker

### 发生了什么？

在我的站点中文章高级设置中的作者**有3个用户**:**QingFeng(我),Anonymous User(翻译来看是匿名用户),已删除用户**。
![image](https://github.com/user-attachments/assets/8aff131b-bc3c-4702-b9b7-3aee335c9a2a)
问题是我的站点**注册是关闭的**,并且**用户列表中也没有这个所谓匿名用户**。
![image](https://github.com/user-attachments/assets/5664497f-a73d-4e2c-ab8e-94667294baf2)
我又创建一篇文章测试,结果还是这个情况。

### 复现步骤

1. 创建文章,保存。
2. 打开设置,找到`高级设置-作者`。
3. 点击作者选项。

**Comment by ruibaby** [comment]
这是系统保留用户，适用于一些特殊情况，比如删除用户后，文章的所属就会变成已删除用户。

这里确实可以不用显示这两个用户，可以优化一下。

/triage accepted
/area ui
/kind improvement
