### ISSUE TITLE
文章编辑问题

### ISSUE THREAD

**Issue by askfname** [halo-dev/halo#6667]
### 系统信息

外部访问地址 https://example.com/
启动时间 2024-09-07 23:07
已激活主题 Butterfly
已启动插件 站点推送插件 评论组件搜索组件 Sitemap RSS
版本 2.13.1
构建时间 2024-03-06 17:40
Git Commit 9473261
Java IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
数据库 MySQL Community Server - GPL / 8.0.31
操作系统 Linux 6.1.0-18-amd64 / amd64
系统时区 Asia/Shanghai
系统语言 en_US

### 使用的哪种方式运行？

Docker

### 发生了什么？

1. 写文章时会时不时自动撤回输入的内容；
2. 写文章时光标突然跳转到文章末尾；
3. 输入 `/xxx` 的话会显示“没有搜索结果”，导致无法换行。

版本 2.13.1，请问最新版有修复上面的问题吗？

**Comment by ruibaby** [comment]
2.13 已经不在维护列表，建议升级或者在 [https://demo.halo.run](https://docs.halo.run/#%E5%9C%A8%E7%BA%BF%E4%BD%93%E9%AA%8C) 中尝试复现。

/triage duplicate

**Comment by ruibaby** [comment]
如果能在最新版本复现这些问题，请单独提交新的 issue。

/close
