### ISSUE TITLE
用户通过邮箱重置密码显示验证码不正确

### ISSUE THREAD

**Issue by LuoyeAutumn** [halo-dev/halo#6669]
### 系统信息

- 外部访问地址: http://www.xjzxxydst.cloud
- 启动时间: 2024-09-11 14:20
- 版本: 2.19.3
- 构建时间: 2024-09-10 17:46
- Git Commit: b6ec7b9
- Java: IBM Semeru Runtime Open Edition / 21.0.4+7-LTS
- 数据库: MySQL Community Server - GPL / 8.4.2
- 操作系统: Linux / 3.10.0-1127.el7.x86_64
- 已激活主题: [Hao 1.5.6](https://github.com/chengzhongxue/halo-theme-hao)
- 已启动插件:
  - [Lsky Pro 兰空图床 0.2.1](https://github.com/ichenhe/halo-lsky-pro)
  - [AList 存储库 1.0.2](https://github.com/halo-sigs/plugin-alist)
  - [爱发电插件 1.6.3](https://github.com/carolcoral/plugin-afdian)
  - [Markdown / HTML 内容块 1.2.0](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [链接管理 1.4.0](https://github.com/halo-sigs/plugin-links)
  - [追番插件 1.0.0](https://github.com/Roozenlz/plugin-bilibili-bangumi)
  - [图库管理 1.2.0](https://github.com/halo-sigs/plugin-photos)
  - [KaTeX 2.0.1](https://github.com/halo-sigs/plugin-katex)
  - [我的装备管理 1.2.0](https://github.com/halo-sigs/plugin-equipments)
  - [瞬间 1.7.0](https://github.com/halo-sigs/plugin-moments)
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.6.2](https://github.com/halo-dev/plugin-search-widget)
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [评论组件 2.4.0](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场 1.4.0](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker

### 发生了什么？

在Halo登陆页面点击找回密码，输入用户名与邮箱地址后，通过邮件通知设置的smtp信发服务成功发送（客户端成功接收邮件）密码重置链接，进入链接后输入新密码，点击重置密码后提示 “验证码不正确。”
![微信截图_20240917195940](https://github.com/user-attachments/assets/b8878484-acc3-4c8e-9fdc-c200901b2787)

### 复现步骤

1.进入console登录页面。
2.点击“找回密码”。
3.输入正确的用户名与对应的邮件地址。
4.点击发送验证邮件。
5.通过邮箱接收密码重置链接，并在浏览器输入链接进入。
6.输入新密码，并输入确认密码。
7.点击重置密码。

问题成功复现
![微信截图_20240917195940](https://github.com/user-attachments/assets/31623358-32dd-4cfe-b628-5a17e81876d1)

**Comment by LuoyeAutumn** [comment]
Halo运行日志（附件
[halo-log-2024-09-17 20_06.log](https://github.com/user-attachments/files/17027924/halo-log-2024-09-17.20_06.log)
）

**Comment by JohnNiang** [comment]
Hi @LuoyeAutumn，我这边无法复现以上问题。重置密码的邮箱能够正常接收到，并且能够根据重置链接成功重置密码。

/triage needs-information

**Comment by ruibaby** [comment]
2.20 有相关功能的重构，建议升级之后再试试，如果有问题，可以继续提交 issue。

/close
