### ISSUE TITLE
Add Index on logs.create_time to Accelerate Query

### ISSUE THREAD

**Issue by wtune** [halo-dev/halo#667]
## Problem
Missing index on table **logs** column **create_time** might make the underlying query issued via 
[LogServiceImpl#pageLatest](https://github.com/halo-dev/halo/blob/134dae00a8a4b2d3f05b037f231089205986b6fa/src/main/java/run/halo/app/service/impl/LogServiceImpl.java#L31) & [LogController#pageBy](https://github.com/halo-dev/halo/blob/134dae00a8a4b2d3f05b037f231089205986b6fa/src/main/java/run/halo/app/controller/admin/api/LogController.java#L43) slow.Since it's also easy to find that we always read **logs** order by create_time, the performance impact for write operations is acceptable under common cases.
## Possible Solution
Add Index on logs.create_time

**Comment by JohnNiang** [comment]
LGTM. Maybe you could fire a PR, or we'll enhance that later.

**Comment by ruibaby** [comment]
merged
