### ISSUE TITLE
备份恢复后重启出现 DuplicateNameException 异常

### ISSUE THREAD

**Issue by KweilinFang** [halo-dev/halo#6672]
### 系统信息

在构建/registry/storage.halo.run/localthumbnails的索引时，出现了DuplicateNameException异常，提示值[69fec8f0441190ce14242bb7eb63936cc745631b5ffb227731333bc4c3d0dd81]在唯一索引[spec.thumbSignature]中已存在。
由于该异常，导致应用上下文初始化失败，应用启动失败。

### 使用的哪种方式运行？

Docker

### 发生了什么？

在构建/registry/storage.halo.run/localthumbnails的索引时，出现了DuplicateNameException异常，提示值[69fec8f0441190ce14242bb7eb63936cc745631b5ffb227731333bc4c3d0dd81]在唯一索引[spec.thumbSignature]中已存在。
由于该异常，导致应用上下文初始化失败，应用启动失败。

**Comment by guqing** [comment]
我尝试了几次但是没有复现，有复现步骤吗，理论上来说备份恢复的时候如果有重复是无法创建的

/triage needs-information

**Comment by guqing** [comment]
/remove-triage needs-information
/kind improvement

经过排查发现备份恢复的时候执行 https://github.com/halo-dev/halo/blob/f6409a0cb0574c49d4fb9da0f73fa7deca4e0e97/application/src/main/java/run/halo/app/migration/impl/MigrationServiceImpl.java#L247 时为了确保能够恢复成功跳过了索引验证,但是是启动时构建索引却发现数据冲突,这是数据处理步骤不一致造成的,恢复备份时建议先丢弃所有数据然后只以备份数据为准避免因为某些唯一字段重复造成恢复后无法启动

@KweilinFang 临时解决办法是先初始化一个新环境 -> 初始化之后直接登录 -> 直接点击到恢复界面进行恢复
(不要去浏览首页,浏览器首页可能会创建 logo 图片的缩略图造成数据冲突)

**Comment by KweilinFang** [comment]
[
[1Panel-halo-MPtO-20240918092506.log](https://github.com/user-attachments/files/17128175/1Panel-halo-MPtO-20240918092506.log)
](url)

**Comment by KweilinFang** [comment]
这个是恢复相关的日志内容

**Comment by guqing** [comment]
> 这个是恢复相关的日志内容

感谢回复,目前已经在修复了,你可以按照 https://github.com/halo-dev/halo/issues/6672#issuecomment-2373460702 中所说的先将服务恢复 晚些时候我们会发布一个修复版本
