### ISSUE TITLE
登录前后主题显示问题

### ISSUE THREAD

**Issue by txbxxx** [halo-dev/halo#6674]
### 系统信息

- 外部访问地址: http://blog.tanc.fun:9999/
- 启动时间: 2024-09-17 18:27
- 版本: 2.19.3
- 构建时间: 2024-09-10 17:45
- Git Commit: 9ffb1bb
- Java: IBM Semeru Runtime Open Edition / 21.0.4+7-LTS
- 数据库: MariaDB Server / 5.5.5-10.4.32-MariaDB-log
- 操作系统: Linux / 3.10.0-1160.105.1.el7.x86_64
- 已激活主题: [Sakura 2.4.0](https://github.com/LIlGG/halo-theme-sakura.git)
- 已启动插件:
  - [追番插件 1.0.0](https://github.com/Roozenlz/plugin-bilibili-bangumi)
  - [豆瓣 1.2.1](https://github.com/chengzhongxue/plugin-douban)
  - [页面静态缓存 1.2.0](https://github.com/halo-sigs/plugin-page-cache)
  - [站点推送插件 1.5.2](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [应用市场 1.5.0](https://www.halo.run/store/apps/app-VYJbF)
  - [图库管理 1.3.0](https://github.com/halo-sigs/plugin-photos)
  - [highlight.js 代码高亮 1.1.0](https://github.com/halo-sigs/plugin-highlightjs)
  - [评论组件 2.4.0](https://github.com/halo-dev/plugin-comment-widget)
  - [搜索组件 1.6.2](https://github.com/halo-dev/plugin-search-widget)
  - [lightgallery.js 灯箱 1.2.0](https://github.com/halo-sigs/plugin-lightgallery)
  - [瞬间 1.4.0](https://github.com/halo-sigs/plugin-moments)
  - [链接管理 1.3.2](https://github.com/halo-sigs/plugin-links)
  - [对象存储（Amazon S3 协议） 1.7.0](https://github.com/halo-dev/plugin-s3)
  - [Vditor 编辑器 1.8.0](https://github.com/justice2001/halo-plugin-vditor)

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

使用在console中设置的主题样式在退出后就无法显示，登录又可以正常显示

### 复现步骤

![image](https://github.com/user-attachments/assets/27b15424-dfbd-4073-897d-4d2efdcf1690)
退出登录后
![image](https://github.com/user-attachments/assets/ca67354a-bec2-4336-a0e9-ed30e5fd127d)

**Comment by ruibaby** [comment]
> [页面静态缓存 1.2.0](https://github.com/halo-sigs/plugin-page-cache)

应该是这个插件导致的，目前不支持监听主题变化去刷新缓存，你在变更之后需要点击页面右下角的按钮手动刷新。

详情可查阅：https://github.com/halo-sigs/plugin-page-cache?tab=readme-ov-file#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9

/kind support

**Comment by txbxxx** [comment]
> > [页面静态缓存 1.2.0](https://github.com/halo-sigs/plugin-page-cache)
> 
> 应该是这个插件导致的，目前不支持监听主题变化去刷新缓存，你在变更之后需要点击页面右下角的按钮手动刷新。
> 
> 详情可查阅：https://github.com/halo-sigs/plugin-page-cache?tab=readme-ov-file#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9
> 
> /kind support /kind 支持

解决了谢谢大佬
