### ISSUE TITLE
Firefox 浏览器默认编辑器无法从剪切板粘贴图片文件

### ISSUE THREAD

**Issue by Sleepstars** [halo-dev/halo#6684]
### 系统信息

- 外部访问地址: https://blog.sleepstars.net
- 启动时间: 2024-09-12 16:28
- 版本: 2.19.3
- 构建时间: 2024-09-10 17:46
- Git Commit: b6ec7b9
- Java: IBM Semeru Runtime Open Edition / 21.0.4+7-LTS
- 数据库: PostgreSQL / 16.4
- 操作系统: Linux / 6.1.0-23-arm64
- 已激活主题: [Walker 1.11.0](https://www.halo.run/store/apps/app-GHgAR)
- 已启动插件:
  - [Vditor 编辑器 1.8.0](https://github.com/justice2001/halo-plugin-vditor)
  - [静态网页服务 1.0.0-alpha.5](https://www.halo.run/store/apps/app-gFkMn)
  - [站点推送插件 1.5.2](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [链接管理 1.5.0](https://github.com/halo-sigs/plugin-links)
  - [编辑器超链接卡片 1.0.3](https://github.com/halo-sigs/plugin-editor-hyperlink-card)
  - [图库管理 1.4.0](https://github.com/halo-sigs/plugin-photos)
  - [豆瓣 1.2.1](https://github.com/chengzhongxue/plugin-douban)
  - [页面静态缓存 1.2.0](https://github.com/halo-sigs/plugin-page-cache)
  - [瞬间 1.8.0](https://github.com/halo-sigs/plugin-moments)
  - [对象存储（Amazon S3 协议） 1.11.0](https://github.com/halo-dev/plugin-s3)
  - [SEO 工具集 1.1.0](https://www.halo.run/store/apps/app-FNGbT)
  - [增强备份（Backup IMproved） 1.1.1](https://www.halo.run/store/apps/app-dHakX)
  - [文章限制阅读 1.4.2](https://www.halo.run/store/apps/app-IzWXo)
  - [Willow Markdown 编辑器 1.0.0](https://github.com/guqing/willow-mde)
  - [OAuth2 认证 1.3.1](https://github.com/halo-sigs/plugin-oauth2)
  - [lightgallery.js 灯箱 1.2.1](https://github.com/halo-sigs/plugin-lightgallery)
  - [highlight.js 代码高亮 1.3.1](https://github.com/halo-sigs/plugin-highlightjs)
  - [Markdown / HTML 内容块 1.2.0](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [搜索组件 1.6.2](https://github.com/halo-dev/plugin-search-widget)
  - [应用市场 1.5.0](https://www.halo.run/store/apps/app-VYJbF)
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [评论组件 2.4.0](https://github.com/halo-dev/plugin-comment-widget)

### 使用的哪种方式运行？

Docker

### 发生了什么？

使用第三方截图工具（例如 Pixpin）可以将截图复制为文件，为了减少图像格式转换的步骤，赋值为文件可以直接导出 WebP 格式的图片。
![图片](https://github.com/user-attachments/assets/9b4682a3-9642-43ca-9f2a-9f27ef9fbff1)

如果不开启复制为文件功能，则可以正常直接将剪贴板图像复制进文章（默认编辑器），若开启复制为文件功能后，粘贴即失效。
（其实有更简单的复现方法，文件夹直接复制图片文件，也无法直接粘贴进文章）

仅在 FireFox 浏览器中复现，已实测 Edge 等 Chromium 系浏览器中可以正常复制为图像并上传到附件库。

### 复现步骤

1. 使用第三方截图工具
2. 复制图片为文件
3. 在 Firefox 浏览器中的默认编辑器粘贴
4. 对粘贴行为无响应
5. 附件中也可见无相关图像保存

**Comment by ruibaby** [comment]
可以复现，其实问题不在于使用截图工具，直接复制一个本地图片去粘贴即可复现。

/king bug
/area editor
