### ISSUE TITLE
阿里云centos7.6，中国无法运行，已经试过阿里云加速和dns方法，，docker-compose up -d无法运行

### ISSUE THREAD

**Issue by angelstears4** [halo-dev/halo#6692]
### 系统信息

[root@iZbp1afcuyl2hyoalfo4b8Z halo]# docker-compose up -d
WARN[0000] /halo/docker-compose.yaml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
[+] Running 1/1
 ✘ halodb Error Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)                                           45.3s 
Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

### 使用的哪种方式运行？

Docker

### 发生了什么？

[root@iZbp1afcuyl2hyoalfo4b8Z halo]# docker-compose up -d
WARN[0000] /halo/docker-compose.yaml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
[+] Running 1/1
 ✘ halodb Error Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)                                           45.3s 
Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by JohnNiang** [comment]
/triage duplicate

Closes in favor of <https://github.com/halo-dev/halo/issues/6215#issuecomment-2198045547>.

/close
