### ISSUE TITLE
“分类”项目如何实现手动排序？

### ISSUE THREAD

**Issue by Gabriel-six** [halo-dev/halo#6710]
### Your current Halo version

2.19

### Describe this feature

希望分类项目能进行手动排序

**Comment by ruibaby** [comment]
可拖动，参考文档：https://docs.halo.run/user-guide/posts#%E8%B0%83%E6%95%B4%E5%88%86%E7%B1%BB%E5%B1%82%E7%BA%A7

/triage unresolved

**Comment by Gabriel-six** [comment]
> 可拖动，参考文档：https://docs.halo.run/user-guide/posts#%E8%B0%83%E6%95%B4%E5%88%86%E7%B1%BB%E5%B1%82%E7%BA%A7
> 
> /triage unresolved

好的，已成功，感谢
