### ISSUE TITLE
希望可以对存量的图片进行域名、后缀修改

### ISSUE THREAD

**Issue by 52lemon6** [halo-dev/halo#6714]
### 你当前使用的版本

2.19.3 pro

### 描述一下此特性

希望可以历史上传的图片进行域名、后缀批量修改
场景：如：对历史图片进行迁移，更换了服务商，比如从腾讯迁移到了阿里，若此在腾讯使用了数据万象模板进行了处理，比如xxx.xxx.xx/a.png!webp  阿里那头不支持！参数的时候就需要变更，此时halo并没有什么方法能够将之前上传的图片进行进行批量修改，希望pro版可以支持

**Comment by guqing** [comment]
/triage duplicate 
with https://github.com/halo-dev/halo/issues/6509

一个可能的解决方案是 https://github.com/orgs/halo-dev/discussions/6465
目前没有一个好的办法可以完整的实现这个功能,自定义模型是可以由插件扩展的因此无法很好的确定哪些链接需要替换

相似 issue :  https://github.com/halo-dev/halo/issues/5829
/close
