### ISSUE TITLE
建议halo备份时不要把适配图片也备份进来，会导致备份包过大，恢复备份变得困难

### ISSUE THREAD

**Issue by Joneeys** [halo-dev/halo#6717]
### 你当前使用的版本

2.19.3

### 描述一下此特性

昨天重装了一下服务器，备份的包1.8G，出于好奇为啥这么大，就解压了包看一看，不看不知道，我本来upload图片700多mb的数据，硬生生的给生成了w400/w800/w1200/w1600/的适配图共占资源1.03g，导致halo恢复困难，我删掉适配资源重新压缩上传备份，恢复时出现服务器错误。希望官方能在备份的时候不要把适配图备份进来，恢复之后让Halo重新生成适配图片。
<img width="576" alt="截屏2024-09-28 10 55 08" src="https://github.com/user-attachments/assets/9d817102-a682-44b6-9072-0ae8cf6bf3c7">

<img width="1064" alt="截屏2024-09-28 11 02 25" src="https://github.com/user-attachments/assets/7dca6730-595f-4089-aed3-0790e7bf1ab3">

<img width="1064" alt="截屏2024-09-28 11 01 48" src="https://github.com/user-attachments/assets/025bbd62-b9c4-4fb9-9d83-3835288fc6a9">

### 附加信息

还有一个问题，什么时候能尽快解决上传恢复备份过大导致504的问题？

**Comment by 52lemon6** [comment]
可以检查一下nginx的文件上传大小和等待时间设置。也可以试着直接通过halo的端口直接访问，中间不经过任何服务再试试

**Comment by Joneeys** [comment]
> 可以检查一下nginx的文件上传大小和等待时间设置。也可以试着直接通过halo的端口直接访问，中间不经过任何服务再试试

我的意思是不是备份包不能上传，是备份的文件太大了

**Comment by JohnNiang** [comment]
Hi @Joneeys , thank you for reaching out here!

1. 可以考虑不备份缩略图文件
2. Halo 2.19 已经支持通过将备份文件放置到备份目录进行恢复，具体请参考：["备份恢复功能改进"](https://www.halo.run/archives/halo-2.19-released#:~:text=%E5%88%87%E6%8D%A2%E7%AD%89%E5%8A%9F%E8%83%BD%E3%80%82-,%E5%A4%87%E4%BB%BD%E6%81%A2%E5%A4%8D%E5%8A%9F%E8%83%BD%E6%94%B9%E8%BF%9B,-%E5%9C%A8%20Halo%202.19)。

/kind improvement
/area core
/milestone 2.20.x

**Comment by Joneeys** [comment]
> 嗨@Joneeys，谢谢你在这里联系我！
> 
> 1. 可以考虑不备份缩略图文件
> 2. Halo 2.19 已经支持通过将备份文件放置到备份目录进行恢复，具体请参考[：“备份恢复功能改进”。](https://www.halo.run/archives/halo-2.19-released#:~:text=%E5%88%87%E6%8D%A2%E7%AD%89%E5%8A%9F%E8%83%BD%E3%80%82-,%E5%A4%87%E4%BB%BD%E6%81%A2%E5%A4%8D%E5%8A%9F%E8%83%BD%E6%94%B9%E8%BF%9B,-%E5%9C%A8%20Halo%202.19)
> 
> /种类改进/区域核心/里程碑2.20.x

是的 我就是通过1panel文件上传通过/opt/1panel/apps/halo/blog/data/backups将备份文件放置到备份目录进行恢复 要是用halo上传 那估计更传不了

**Comment by Irqis** [comment]
+1 同一问题 备份图片包太大，导致恢复时困难

我是控制台能进去，前台无法访问，显示500报错。这才想起来恢复一下备份，一看备份文件，我就感觉有点不对劲了，正常备份文件100M出头，加上upload的图片200M，总共300M是正常备份文件要恢复的。

![kejiayun_2024-09-29_11-01-33](https://github.com/user-attachments/assets/ee573481-fe00-4337-ad93-f21ffea5be01)
