### ISSUE TITLE
备份还原功能疑似会造成性能问题

### ISSUE THREAD

**Issue by 52lemon6** [halo-dev/halo#6719]
### 系统信息

- 外部访问地址: https://oniya.cn/
- 启动时间: 2024-09-28 23:11
- 版本: 2.19.3
- 构建时间: 2024-09-10 17:46
- Git Commit: b6ec7b9
- Java: IBM Semeru Runtime Open Edition / 21.0.4+7-LTS
- 数据库: 20200531 / 5.7.18-cynos-log
- 操作系统: Linux / 6.1.0-13-amd64
- 已激活主题: [Theme Joe3 1.4.0](https://github.com/jiewenhuang/halo-theme-joe3.0)
- 已启动插件:
  - [页面静态缓存 1.2.0](https://github.com/halo-sigs/plugin-page-cache)
  - [编辑器超链接卡片 1.0.3](https://github.com/halo-sigs/plugin-editor-hyperlink-card)
  - [静态网页服务 1.0.0-alpha.5](https://www.halo.run/store/apps/app-gFkMn)
  - [Meilisearch 2.0.1](https://github.com/Rainsheep/halo-plugin-meilisearch)
  - [TinyTale小程序设置 1.0.5](https://github.com/jiewenhuang/halo-plugin-TinyTale)
  - [Webhook 1.0.0](https://www.wxy97.com/)
  - [朋友圈 1.3.5](https://github.com/chengzhongxue/plugin-friends-new)
  - [OAuth2 认证 1.3.1](https://github.com/halo-sigs/plugin-oauth2)
  - [highlight.js 代码高亮 1.3.2](https://github.com/halo-sigs/plugin-highlightjs)
  - [Metrics Graph 1.0.0](https://github.com/guqing/plugin-metrics-graph)
  - [Markdown / HTML 内容块 1.1.0](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [文本绘图 1.3.0](https://github.com/halo-sigs/plugin-text-diagram)
  - [Vditor 编辑器 1.8.0](https://github.com/justice2001/halo-plugin-vditor)
  - [Willow Markdown 编辑器 1.0.0](https://github.com/guqing/willow-mde)
  - [图库管理 1.4.0](https://github.com/halo-sigs/plugin-photos)
  - [文章导入导出 1.2.4](https://jhacker.cn/2023/halo-plugin-export2doc)
  - [AI 助手 1.0.0](https://www.halo.run/store/apps/app-riNgb)
  - [Docsme 1.0.0-alpha.8](https://www.halo.run/store/apps/app-yffxw)
  - [瞬间 1.8.0](https://github.com/halo-sigs/plugin-moments)
  - [链接管理 1.5.0](https://github.com/halo-sigs/plugin-links)
  - [站点推送插件 1.5.2](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [增强备份（Backup IMproved） 1.1.1](https://www.halo.run/store/apps/app-dHakX)
  - 联系表单 1.0.2
  - [文章限制阅读 Pro 1.4.2](https://www.halo.run/store/apps/app-TzRqd)
  - [对象存储（Amazon S3 协议） 1.11.0](https://github.com/halo-dev/plugin-s3)
  - [站点迁移 1.7.0](https://github.com/halo-sigs/plugin-migrate)
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.6.2](https://github.com/halo-dev/plugin-search-widget)
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [评论组件 2.4.0](https://github.com/halo-dev/plugin-comment-widget)

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

备份还原功能疑似会造成性能问题
↓初装后一直正常使用的首页延迟（原始初装的已经没有记录了，这是使用的在使用备份还原功能前备份的sql）
![image](https://github.com/user-attachments/assets/40c12ed2-9612-4c96-8f3e-93cfff427f20)
↓初装的首页延迟
![image-20240928193226-1bj93i8](https://github.com/user-attachments/assets/e630684b-ba5f-4267-9ad2-08ee9f271735)
↓使用备份还原的首页访问延迟（禁用了所有插件）
![image-20240928192547-m7d06wq](https://github.com/user-attachments/assets/aa4d730d-6823-4d96-b4d3-cff9039ce285)

**Comment by ruibaby** [comment]
恢复之后会有一段时间去进行数据调和，这个阶段可能导致页面访问稍慢。建议观察一下 cpu 和内存占用，或者开启 debug 日志观察是否有数据库查询问题。

```yaml
--logging.level.run.halo.app=DEBUG
```

/triage needs-information

**Comment by JohnNiang** [comment]
I'm going to close this issue due to no negative feedback. Feel free to reopen it if the issue persists.

/close
