### ISSUE TITLE
Add Index on post_tags.post_id to Accelerate Query

### ISSUE THREAD

**Issue by wtune** [halo-dev/halo#673]
## Problem
Missing index on table **post_tags** column **post_id** might make the underlying query issued via 
[eg. PostTagRepository#findAllByPostId](https://github.com/halo-dev/halo/blob/1248cb7b147328406903e60b798d43c3443daf9b/src/main/java/run/halo/app/repository/PostTagRepository.java#L31) slow.Since it's also easy to find that we always read **post_tags** by post_id or tag_id and sometimes insert or update, the performance impact for write operations is acceptable under common cases.
## Possible Solution
Add Index on post_tags.post_id

**Comment by ruibaby** [comment]
merged
