### ISSUE TITLE
相同的文章标题问题

### ISSUE THREAD

**Issue by azwcl** [halo-dev/halo#6733]
### 系统信息

- 启动时间: 2024-09-30 08:07
- 版本: 2.19.3
- 构建时间: 2024-09-10 17:45
- Git Commit: 9ffb1bb
- Java: IBM Semeru Runtime Open Edition / 21.0.4+7-LTS
- 数据库: MySQL Community Server - GPL / 8.4.2
- 操作系统: Linux / 5.15.0-116-generic
- 已激活主题: [Earth 1.9.0](https://github.com/halo-dev/theme-earth)
- 已启动插件:
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.6.2](https://github.com/halo-dev/plugin-search-widget)
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [评论组件 2.4.0](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场 1.4.0](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

1. 当两个相同的标题的时候，因为路由问题，无法跳转到对应文章了；
2. 具体如下图，两篇文章，怎么点，都是后发布的那篇文章了；
![image](https://github.com/user-attachments/assets/7e2f74fe-f6cc-45a9-b328-5434972d5715)
3. 即便在不同分类下，也不能打开第一篇发布的文章了
![image](https://github.com/user-attachments/assets/c3fdc000-96ee-4b92-afc3-1618978d673c)

### 复现步骤

1. 创建文章 A ，标题 ：Test
2. 创建文章 B ，标题 ： Test；
3. 文章 A 打不开了

**Comment by ruibaby** [comment]
相同问题：https://github.com/halo-dev/halo/issues/6715#issuecomment-2380586893

/triage duplicate

**Comment by ruibaby** [comment]
如果你不关心你文章的访问地址，可以去主题路由设置一个相对随机的生成策略，以减少这个问题出现的可能。

https://docs.halo.run/user-guide/settings#%E4%B8%BB%E9%A2%98%E8%B7%AF%E7%94%B1%E8%AE%BE%E7%BD%AE
