### ISSUE TITLE
从应用市场下载的主题未与应用市场绑定

### ISSUE THREAD

**Issue by QingFeng-awa** [halo-dev/halo#6746]
### 系统信息

- 外部访问地址: https://blog.xtreme.net.cn
- 启动时间: 2024-10-02 22:00
- 版本: 2.19.3
- 构建时间: 2024-09-10 17:46
- Git Commit: b6ec7b9
- Java: IBM Semeru Runtime Open Edition / 21.0.4+7-LTS
- 数据库: MySQL Community Server - GPL / 8.4.2
- 操作系统: Linux / 6.1.0-25-amd64
- 已激活主题: [Theme Joe3 1.4.0](https://github.com/jiewenhuang/halo-theme-joe3.0)
- 已启动插件:
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.6.2](https://github.com/halo-dev/plugin-search-widget)
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [评论组件 2.4.0](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场 1.5.0](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker

### 发生了什么？

通过应用市场下载的主题(我下的是Joe3.0)下载后提示未与应用市场绑定。

### 复现步骤

1. 在安装应用市场插件后打开`/console/app-store`。
2. 选择主题`Joe 3.0`并安装。
3. 转到`/console/theme`,选择`管理主题`。
4. 然后你就能发现安装的主题提示未绑定了。
![未绑定应用市场](https://github.com/user-attachments/assets/7d4a1daa-aee4-4cd2-b115-39a22539c5da)

### 附加信息

在下图中,未显示`已安装`字样的主题则为下载后未与应用市场绑定的主题。
![未与应用市场绑定的主题](https://github.com/user-attachments/assets/0a58d6d1-2f5f-4d03-9695-d7911276f446)

我**猜测**这可能跟Halo的某些逻辑有关,因此我选择在Halo仓库报告而不是在应用市场仓库报告这个issue。

**Comment by ruibaby** [comment]
没有复现，建议打开浏览器控制台，在安装时观察 Network 面板，观察是否有接口异常。

/triage needs-information

**Comment by ruibaby** [comment]
> 没有复现，建议打开浏览器控制台，在安装时观察 Network 面板，观察是否有接口异常。
> 
> /triage needs-information

在最新版本的应用市场插件（1.5.0）确实可以复现，应该与插件有关，我将在插件中修复。

**Comment by ruibaby** [comment]
已经在 [1.5.1](https://www.halo.run/store/apps/app-VYJbF?tab=releases) 中修复，感谢反馈。
