### ISSUE TITLE
新的登录/注册页面会经过 TemplateHeadProcessor 处理

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#6750]
### 系统信息

- 外部访问地址: http://192.168.8.22:8090
- 启动时间: 2024-09-29 15:55
- 版本: 2.20.0-SNAPSHOT
- 构建时间: 2024-09-29 15:55
- Git Commit: dcbfd48
- Java: OpenJDK Runtime Environment / 17.0.11+9-LTS
- 数据库: PostgreSQL / 15.2 (Debian 15.2-1.pgdg110+1)
- 操作系统: Mac OS X / 15.1
- 已激活主题: [Apex 企业官网主题 1.1.0](https://www.halo.run/store/apps/app-OTFHl)
- 已启动插件:
  - [LDAP 认证 1.0.0-SNAPSHOT](https://www.halo.run/store/apps/app-vrSqF)
  - [Image Stream 1.0.0-SNAPSHOT](https://github.com/halo-sigs/plugin-image-stream)
  - [OAuth2 认证 1.0.4-SNAPSHOT](https://github.com/halo-sigs/plugin-oauth2)

### 使用的哪种方式运行？

Source Code

### 发生了什么？

观察到目前新提供的登录相关的页面会经过 TemplateHeadProcessor 处理，注入了插件中提供的 head 标签代码，如图：

<img width="1281" alt="image" src="https://github.com/user-attachments/assets/2c8d138b-7b61-4036-a901-78ecd5f29d30">

暂不确定是否会造成一定的隐患。

/area core
/triage needs-information

**Comment by JohnNiang** [comment]
可以考虑过滤对登录、注册、找回密码、二步验证和登出模板的处理。

**Comment by ruibaby** [comment]
> 可以考虑过滤对登录、注册、找回密码、二步验证和登出模板的处理。

可以看看能不能专门为这些页面提供接口和代码注入设置项，毕竟这些页面还算比较特殊。

**Comment by ruibaby** [comment]
这个问题和 https://github.com/halo-dev/halo/issues/6500 也有点相关。

**Comment by JohnNiang** [comment]
我的想法：我们约定这些特殊的模板放置到统一目录（例如 `pre_auth`）下， 这样我们可以在 TemplateProcessor 中统一进行过滤。

**Comment by JohnNiang** [comment]
This issue was fixed by <https://github.com/halo-dev/halo/pull/6709>.

/close
