### ISSUE TITLE
后台的退出登录功能失效

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#6756]
### 系统信息

- 外部访问地址: https://halo-dev.ryanc.cc
- 启动时间: 2024-10-03 17:39
- 版本: 2.20.0-SNAPSHOT
- 构建时间: 2024-10-01 23:41
- Git Commit: 462fac0
- Java: IBM Semeru Runtime Open Edition / 21.0.4+7-LTS
- 数据库: PostgreSQL / 15.4 (Debian 15.4-2.pgdg120+1)
- 操作系统: Linux / 5.15.0-88-generic
- 已激活主题: [Official V3 2.8.1](https://github.com/f2ccloud/halo-theme-official-v3.git)
- 已启动插件:
  - [Unsplash 1.1.0](https://github.com/halo-sigs/plugin-unsplash)
  - [Data Studio（数据工厂） 1.0.0-alpha.2](https://github.com/halo-sigs/plugin-data-studio)
  - [HTML 转 Markdown 1.0.0-SNAPSHOT](https://github.com/halo-dev/plugin-html2markdown)
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [应用市场 1.4.0-dev](https://halo-dev.ryanc.cc/store/apps/app-VYJbF)
  - [增强备份（Backup IMproved） 1.1.1](https://www.halo.run/store/apps/app-dHakX)
  - [lightgallery.js 灯箱 1.2.1](https://github.com/halo-sigs/plugin-lightgallery)
  - [highlight.js 代码高亮 1.2.2](https://github.com/halo-sigs/plugin-highlightjs)
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [ByteMD 1.4.0](https://github.com/ruibaby/plugin-bytemd)
  - [对象存储（Amazon S3 协议） 1.10.0](https://github.com/halo-dev/plugin-s3)
  - [搜索组件 1.5.0](https://github.com/halo-dev/plugin-search-widget)
  - [OAuth2 认证 1.2.0](https://github.com/halo-sigs/plugin-oauth2)
  - [评论组件 2.4.0](https://github.com/halo-dev/plugin-comment-widget)

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

如图：

<img width="728" alt="image" src="https://github.com/user-attachments/assets/d21e15bf-d886-4afe-9e31-5a84f201e981">
<img width="828" alt="image" src="https://github.com/user-attachments/assets/bf9f897b-d130-4221-acb5-290c91ecd9cf">

Response: Invalid CSRF Token

/kind bug
/area ui
/milestone 2.20.x

**Comment by ruibaby** [comment]
但没有在本地环境复现这个问题。

**Comment by JohnNiang** [comment]
建议点击`登出`按钮之后跳转至 `/logout` 页面。
