### ISSUE TITLE
将默认编辑器的内容尾部滚动到中间

### ISSUE THREAD

**Issue by YttriumC** [halo-dev/halo#6768]
### 你当前使用的版本

2.19.3

### 描述一下此特性

![image](https://github.com/user-attachments/assets/1ed20b23-f57e-4920-a732-c3a731911287)
 如上图, 目前编辑器在行数到达页面底部时不支持继续向上滚动一部分, 
下图中IDE显示到最后一行时还可以将内容向上滚动一部分使其阅读和编辑更方便.
![image](https://github.com/user-attachments/assets/13262bf6-a67d-4f8d-a18b-5732178ee512)
其它编辑器,比如Notepad++, 更是可以将内容尾部轮动到第一行.
![image](https://github.com/user-attachments/assets/58a8b920-a463-40bf-84cb-710eec424dec)
该特性可以使编辑器输入大量内容后方便阅读与编辑

**Comment by YttriumC** [comment]
理论上说 在编辑器元素上添加一个margin或padding即可实现
![image](https://github.com/user-attachments/assets/f8fb2cf3-e654-4a17-8f16-ee2b44bd3510)

**Comment by ruibaby** [comment]
/triage duplicate

See https://github.com/halo-dev/halo/issues/6495

/close
