### ISSUE TITLE
角色的[禁止访问 Console]选项失效

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#6773]
### 系统信息

- 外部访问地址: http://127.0.0.1:8090
- 启动时间: 2024-10-06 11:33
- 版本: 2.20.0-SNAPSHOT
- 构建时间: 2024-10-06 11:33
- Git Commit: b0ad040
- Java: OpenJDK Runtime Environment / 17.0.11+9-LTS
- 数据库: PostgreSQL / 15.2 (Debian 15.2-1.pgdg110+1)
- 操作系统: Mac OS X / 15.1
- 已激活主题: [Walker 1.10.0](https://www.halo.run/store/apps/app-GHgAR)
- 已启动插件:
  - [LDAP 认证 1.0.0-SNAPSHOT](https://www.halo.run/store/apps/app-vrSqF)
  - [Image Stream 1.0.0-SNAPSHOT](https://github.com/halo-sigs/plugin-image-stream)
  - [OAuth2 认证 1.0.4-SNAPSHOT](https://github.com/halo-sigs/plugin-oauth2)
  - [评论组件 2.0.0-SNAPSHOT](https://github.com/halo-dev/plugin-comment-widget)

### 使用的哪种方式运行？

Source Code

### 发生了什么？

Halo 2.20.0 在 https://github.com/halo-dev/halo/pull/6488 中重构了登录认证相关的逻辑，以及改为由后端处理各种页面重定向，但遗漏了角色的 **禁止访问 Console** 选项，此选项主要目的是不允许拥有此角色的用户可以访问到 /console。

/kind bug
/area ui
/milestone 2.20.x

**Comment by JohnNiang** [comment]
因为用户从路径 /uc 访问 /console 不一定会经过后端，所以这里在前端做相应的判断是合理的。

**Comment by JohnNiang** [comment]
是否允许进入 console 页面属于授权范畴（权限检查），可以考虑交给后端操作。
