### ISSUE TITLE
后台编辑器相关建议

### ISSUE THREAD

**Issue by holwell** [halo-dev/halo#6778]
### 你当前使用的版本

2.x

### 描述一下此特性

* 默认编辑器
希望支持 markdown 源格式解析。也就说直接将一篇 markdown 源格式的文本复制到默认编辑器后，不会自己解析二级标题、代码块之类的，得像原始编辑器输入一样，得在标识符后按空格触发格式匹配。有可能这是默认编辑器的设计，毕竟它本身可能就不是为了 markdown 而生，而是为了普通用户的体验。
* 其他编辑器
希望在编辑页能增加写标题的位置。像 vditor 等其他编辑器，在编辑页竟然没有写标题的位置，这也太离谱了吧，还得跑到外面文章信息页去编写文章标题，有点不符合使用逻辑了。
* 瞬间
希望在后台登录状态有效的情况下，能把隐藏的说说在前端显示出来，只是对外不可见，而不是真正的隐藏。瞬间是一个插件吧，不知道是不是咱官方开发的，所以也不知道在这里提建议合不合适，我根据自己体验想到哪就写到哪了，请见谅！

**Comment by ruibaby** [comment]
1. 默认编辑器是富文本编辑器，只是支持部分 Markdown 快捷输入方式。
2. 详见：<https://github.com/halo-dev/halo/issues/5427#issuecomment-1976133372>，你提到的 Vditor 插件也已经提供了支持，https://github.com/justice2001/halo-plugin-vditor/issues/33
3. 与当前仓库无关，请在对应仓库提交。

此外，请不要在一个 issue 下提交多个问题。

<img width="884" alt="image" src="https://github.com/user-attachments/assets/4cf1f1b1-839c-4d0a-baf4-46a93431b3f6">

/kind support

**Comment by holwell** [comment]
谢谢解答
