### ISSUE TITLE
邮件通知

### ISSUE THREAD

**Issue by HiddenScholars** [halo-dev/halo#6784]
### 系统信息

环境：使用163邮箱

### 使用的哪种方式运行？

Docker

### 发生了什么？

问题：设置邮件通知，实际发信地址配置邮箱后，用户名还是必须填写邮件地址，才能发送成功。
想要达到效果：评论邮件通知时，可以自定义发件地址

### 复现步骤

设置-》通知设置-》邮件通知

**Comment by HiddenScholars** [comment]
想要达到用户看不到实际的发件的邮箱地址

**Comment by guqing** [comment]
> 想要达到用户看不到实际的发件的邮箱地址

建议你通过邮件转发服务来实现如 Cloudflare, 参考 https://www.cloudflare.com/zh-cn/developer-platform/email-routing/

**Comment by HiddenScholars** [comment]
感谢，我试一下
