### ISSUE TITLE
重置密码时如果两次密码不一致会使用户名变为 null

### ISSUE THREAD

**Issue by LIlGG** [halo-dev/halo#6790]
### 系统信息

- 外部访问地址: http://localhost:8090
- 启动时间: 2024-10-08 16:43
- 版本: 
- 构建时间: 
- Git Commit: 
- Java: OpenJDK Runtime Environment / 17.0.7+7-LTS
- 数据库: PostgreSQL / 15.4 (Debian 15.4-2.pgdg120+1)
- 操作系统: Mac OS X / 14.6
- 已激活主题: [Sakura 2.4.0](https://github.com/LIlGG/halo-theme-sakura.git)
- 已启动插件:
  - [Data Studio（数据工厂） 1.0.0-alpha.2](https://github.com/halo-sigs/plugin-data-studio)
  - [shiki 代码高亮 1.0.0-SNAPSHOT](https://github.com/halo-sigs/plugin-shiki)
  - [瞬间 1.0.1-SNAPSHOT](https://github.com/halo-sigs/plugin-moments)
  - [AI 助手 1.0.0-SNAPSHOT](https://www.halo.run/store/apps/app-riNgb)
  - [Metrics Graph 1.0.0](https://github.com/guqing/plugin-metrics-graph)
  - [Markdown / HTML 内容块 1.0.0-SNAPSHOT](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [Willow Markdown 编辑器 1.0.0-beta.3](https://github.com/guqing/willow-mde)
  - [应用市场 1.0.2](https://github.com/halo-dev/plugin-app-store)
  - [增强备份（Backup IMproved） 1.0.0](https://halo.run/store/apps/app-dHakX)
  - [OAuth2 认证 1.1.0](https://github.com/halo-sigs/plugin-oauth2)
  - [StackEdit 1.1.1](https://github.com/halo-sigs/plugin-stackedit)
  - [链接管理 1.3.3](https://github.com/halo-sigs/plugin-links)
  - [站点迁移 1.3.0](https://github.com/halo-sigs/plugin-migrate)
  - [对象存储（Amazon S3 协议） 1.11.0-SNAPSHOT](https://github.com/halo-dev/plugin-s3)
  - [ByteMD 1.4.0](https://github.com/ruibaby/plugin-bytemd)
  - [图库管理 1.3.0](https://github.com/halo-sigs/plugin-photos)
  - [RSS 1.2.2](https://github.com/halo-dev/plugin-feed)
  - [搜索组件 1.5.0](https://github.com/halo-dev/plugin-search-widget)
  - [评论组件 2.1.0](https://github.com/halo-dev/plugin-comment-widget)
  - [Sitemap 1.1.1](https://github.com/halo-dev/plugin-sitemap)

### 使用的哪种方式运行？

Source Code

### 发生了什么？

在重置密码界面，如果新密码与确认密码不一致时，页面刷新后，用户名会变为 null，且提示信息为英文。如下所示：

<img width="594" alt="image" src="https://github.com/user-attachments/assets/7b29eb96-468d-48ee-994a-958c10e754ac">

/kind bug
/area core
/milestone 2.20.x

### 复现步骤

1. 在登录页面点击重置密码。
2. 在邮箱中点击重置密码链接。
3. 新密码与旧密码输入不同的内容。

**Comment by JohnNiang** [comment]
当前问题疑似在 https://github.com/halo-dev/halo/pull/6823 中修复了，麻烦确认一下 Halo 2.20.0-rc.1 是否还有问题。
