### ISSUE TITLE
使用基于后端的登录方式时可以使用中文用户名与密码进行注册登录

### ISSUE THREAD

**Issue by LIlGG** [halo-dev/halo#6793]
### 系统信息

- 外部访问地址: http://localhost:8090
- 启动时间: 2024-10-08 16:43
- 版本: 
- 构建时间: 
- Git Commit: 
- Java: OpenJDK Runtime Environment / 17.0.7+7-LTS
- 数据库: PostgreSQL / 15.4 (Debian 15.4-2.pgdg120+1)
- 操作系统: Mac OS X / 14.6
- 已激活主题: [Sakura 2.4.0](https://github.com/LIlGG/halo-theme-sakura.git)
- 已启动插件:
  - [Data Studio（数据工厂） 1.0.0-alpha.2](https://github.com/halo-sigs/plugin-data-studio)
  - [shiki 代码高亮 1.0.0-SNAPSHOT](https://github.com/halo-sigs/plugin-shiki)
  - [瞬间 1.0.1-SNAPSHOT](https://github.com/halo-sigs/plugin-moments)
  - [AI 助手 1.0.0-SNAPSHOT](https://www.halo.run/store/apps/app-riNgb)
  - [Metrics Graph 1.0.0](https://github.com/guqing/plugin-metrics-graph)
  - [Markdown / HTML 内容块 1.0.0-SNAPSHOT](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [Willow Markdown 编辑器 1.0.0-beta.3](https://github.com/guqing/willow-mde)
  - [应用市场 1.5.1](https://www.halo.run/store/apps/app-VYJbF)
  - [增强备份（Backup IMproved） 1.0.0](https://halo.run/store/apps/app-dHakX)
  - [OAuth2 认证 1.3.1](https://github.com/halo-sigs/plugin-oauth2)
  - [StackEdit 1.1.1](https://github.com/halo-sigs/plugin-stackedit)
  - [链接管理 1.3.3](https://github.com/halo-sigs/plugin-links)
  - [站点迁移 1.3.0](https://github.com/halo-sigs/plugin-migrate)
  - [对象存储（Amazon S3 协议） 1.11.0-SNAPSHOT](https://github.com/halo-dev/plugin-s3)
  - [ByteMD 1.4.0](https://github.com/ruibaby/plugin-bytemd)
  - [图库管理 1.3.0](https://github.com/halo-sigs/plugin-photos)
  - [RSS 1.2.2](https://github.com/halo-dev/plugin-feed)
  - [搜索组件 1.5.0](https://github.com/halo-dev/plugin-search-widget)
  - [评论组件 2.1.0](https://github.com/halo-dev/plugin-comment-widget)
  - [Sitemap 1.1.1](https://github.com/halo-dev/plugin-sitemap)

### 使用的哪种方式运行？

Source Code

### 发生了什么？

使用基于后端登录时，在注册用户阶段可以使用中文用户名与密码进行注册。建议进行限制。

并且也可以使用特殊字符进行登录，建议进行限制

/kind bug
/area core
/milestone 2.20.x

### 复现步骤

1. 在登录页面点击注册用户。
2. 使用中文用户名与密码进行注册。
3. 可以看到注册成功并能成功登录。

**Comment by iyuzhang** [comment]
"基于后端的登录方式"是什么操作，是哪个版本有这个问题，我看了下，用户名是有校验的。

**Comment by ruibaby** [comment]
> "基于后端的登录方式"是什么操作，是哪个版本有这个问题，我看了下，用户名是有校验的。

这里说的是 main 分支，正在重构登录、注册等逻辑，将发布在 2.20。

可以查看：

https://github.com/halo-dev/halo/issues/5214
https://github.com/halo-dev/halo/pull/6488
