### ISSUE TITLE
Add Index on theme_settings.theme_id and theme_settings.setting_key to Accelerate Query

### ISSUE THREAD

**Issue by wtune** [halo-dev/halo#680]
## Problem
Missing index on table **theme_settings** column **theme_id** and **setting_key** might make the underlying query issued via [ThemeSetting#findAllByThemeId&findByThemeIdAndKey](https://github.com/halo-dev/halo/blob/2363f4adf73a13a9cf0498559c674a494c2b9905/src/main/java/run/halo/app/repository/ThemeSettingRepository.java#L25) slow.Since it's also easy to find that we always read **theme_settings** by setting_key or theme_id and sometimes insert or update, the performance impact for write operations is acceptable under common cases.
## Possible Solution
Add Index on theme_settings.theme_id and theme_settings.setting_key

**Comment by ruibaby** [comment]
merged
