### ISSUE TITLE
缩略图显示问题

### ISSUE THREAD

**Issue by wx-1124** [halo-dev/halo#6802]
### 系统信息

外部访问地址
https://blog.nanshengwx.cn
启动时间
2024-10-08 16:02
已激活主题
Hao
已启动插件
Markdown / HTML 内容块
Data Studio（数据工厂）
评论迁移
编辑器超链接卡片
页面静态缓存
链接安全跳转中台
KaTeX
OAuth2 认证
爱发电插件
友链自助提交插件
站点推送插件
朋友圈
ByteMD
文章导入导出
highlight.js 代码高亮
lightgallery.js 灯箱
评论组件
RSS
应用市场
链接管理
瞬间
Sitemap
搜索组件

### 使用的哪种方式运行？

Docker

### 发生了什么？

写文章图片是正的，预览文章就转了90°，点大图就是正的，在附件库看同理，缩略图是旋转的，但点击图片进去后是正的

### 附加信息

![微信图片_20241009142538](https://github.com/user-attachments/assets/7a1b1026-0290-4f84-916d-4f8c3d255197)
![微信图片_20241009142547](https://github.com/user-attachments/assets/1aff1632-8c75-448e-a2a2-3f8562f4e2e2)

**Comment by wx-1124** [comment]
![微信图片_20241008141411](https://github.com/user-attachments/assets/fb7513a4-9400-48d8-82a9-7030c9a495d9)
![微信图片_20241008141414](https://github.com/user-attachments/assets/15b39406-f9bd-4fe6-8e55-2d6e8b0df192)
![微信图片_20241008141421](https://github.com/user-attachments/assets/98b2d324-46f2-4375-bf69-e3d3325c2b1a)
这三张都是的，在电脑看着正常，上传缩略图是旋转的，在文章里图片也是旋转的，点开就正常了，目前用照片写的文章已发布，https://blog.nanshengwx.cn/archives/FUASjLR1，这里面有部分图片就是的，开始的合影，和后面的两鱼中加照片（三张一行）那里的图片都是这个情况

**Comment by guqing** [comment]
@wx-1124 经过查看你的图片本身就是横着的，以下是从你图片的 EXIF 中观察到的方向信息，显示旋转 90°，因此浏览图片时可能会根据此方向来展示图片所以你看到的是竖着的
<img width="701" alt="image" src="https://github.com/user-attachments/assets/b8b65955-ec1b-4ded-890a-0fa52e319789">
当通过如 EXIF Cleaner ：https://github.com/szTheory/exifcleaner 之类的软件将图片中的 EXIF 信息清除之后图片将会自动展示为横向图片，因此这与缩略图机制应该关系不大，只是因为缩略图不包含原图的 EXIF 信息导致的，如果要确保图片与 EXIF 信息一致那么可能的办法是生成缩略图前先读取 EXIF 是否包含方向信息如果包含则在生成之后旋转对应的值，但是最终是否要解决这个问题可能是一个值得讨论的问题

/remove-kind bug
/kind improvement
/priority awaiting-more-evidence

**Comment by wx-1124** [comment]
好的我明白问题的所在了，感谢答疑，这个issue需要关闭吗

**Comment by guqing** [comment]
> 好的我明白问题的所在了，感谢答疑，这个issue需要关闭吗

不需要关闭，这确实是一个问题，可能需要解决它，我们稍后会讨论一下
