### ISSUE TITLE
跨域问题

### ISSUE THREAD

**Issue by kkblock** [halo-dev/halo#682]
Access to font at 'http://xxxxxxxxxxxx:8090/anatole/source/fonts/fontawesome-webfont.woff2?v=4.7.0' from origin 'http://www.kchampion.top' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

以下是我的nginx 配置 
server {
        listen       80 default_server;
        listen       [::]:80 default_server;
        server_name  _;
        root         /usr/share/nginx/html;

        # Load configuration files for the default server block.
        include /etc/nginx/default.d/*.conf;

        location / {
	    add_header Access-Control-Allow-Origin *;
            add_header Access-Control-Allow-Headers X-Requested-With;
             add_header Access-Control-Allow-Methods GET,POST,OPTIONS;
	    proxy_pass http://127.0.0.1:8090/;
        }

        error_page 404 /404.html;
            location = /40x.html {
        }

        error_page 500 502 503 504 /50x.html;
            location = /50x.html {
        }
    }

**Comment by ruibaby** [comment]
@kkblock 请在后台博客设置中的博客地址改为你的域名。

**Comment by kkblock** [comment]
@ruibaby 谢谢，解决了。是后台根据这个设置做了什么吗？

**Comment by ruibaby** [comment]
> @ruibaby 谢谢，解决了。是后台根据这个设置做了什么吗？

根据你设置的博客地址拼接资源的绝对路径。
