### ISSUE TITLE
找回密码相关页面没有提供 globalInfo 变量

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#6821]
### 你当前使用的版本

2.20.0-SNAPSHOT

### 描述一下此特性

在 https://github.com/halo-dev/halo/pull/6488 重构登录、注册等页面的过程中，为登录和注册页面提供了 globalInfo 变量，用于判断是否开启了注册等功能，但其他页面比如找回密码、totp 没有添加，期望能够统一提供。

/area core
/kind improvement
/milestone 2.20.x

**Comment by JohnNiang** [comment]
/reopen

目前还有登出页面没有提供对应的变量。我将重新打开当前 Issue。
