### ISSUE TITLE
恢复备份，没有自动重启容器，需要自己手动重启

### ISSUE THREAD

**Issue by chengzhongxue** [halo-dev/halo#6827]
### 系统信息

- 外部访问地址: https://kunkunyu.com
- 启动时间: 2024-10-11 21:58
- 版本: 2.19.3
- 构建时间: 2024-09-10 17:46
- Git Commit: b6ec7b9
- Java: IBM Semeru Runtime Open Edition / 21.0.4+7-LTS
- 数据库: MySQL Community Server - GPL / 8.0.39
- 操作系统: Linux / 3.10.0-957.1.3.el7.x86_64
- 已激活主题: [THYUU/星度 1.0.0](https://kunkunyu.com)
- 已启动插件:
  - [评论组件 2.4.0](https://github.com/halo-dev/plugin-comment-widget)
  - [友链自助提交插件定制版 1.0.0-SNAPSHOT-1](https://github.com/halo-arcade/link-submit-theme)
  - [朋友圈 1.3.5](https://github.com/chengzhongxue/plugin-friends-new)
  - [豆瓣 1.2.1](https://github.com/chengzhongxue/plugin-douban)
  - [链上好文 1.0.1](https://github.com/guqing/plugin-share-post-via-link)
  - [THYUU/星度评论组件 1.0.0-kky-3](https://github.com/chengzhongxue/plugin-thyuu-comment)
  - [Netease Music 1.0.0-alpha.7](https://github.com/chengzhongxue/plugin-netease-music)
  - [编辑器超链接卡片 1.0.3](https://github.com/halo-sigs/plugin-editor-hyperlink-card)
  - [Lsky Pro 兰空图床 0.2.1](https://github.com/ichenhe/halo-lsky-pro)
  - [对象存储（Amazon S3 协议） 1.11.0](https://github.com/halo-dev/plugin-s3)
  - [Metrics Graph 1.0.0](https://github.com/guqing/plugin-metrics-graph)
  - [Markdown / HTML 内容块 1.2.0](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [图库管理 1.4.0](https://github.com/halo-sigs/plugin-photos)
  - [增强备份（Backup IMproved） 1.1.1](https://www.halo.run/store/apps/app-dHakX)
  - [Vditor 编辑器 1.8.0](https://github.com/justice2001/halo-plugin-vditor)
  - [链接管理 1.5.0](https://github.com/halo-sigs/plugin-links)
  - [Data Studio（数据工厂） 1.0.0-alpha.2](https://github.com/halo-sigs/plugin-data-studio)
  - [Meilisearch 2.0.1](https://github.com/Rainsheep/halo-plugin-meilisearch)
  - [Umami 1.4.0](https://github.com/halo-sigs/plugin-umami)
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.6.2](https://github.com/halo-dev/plugin-search-widget)
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [应用市场 1.5.1](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker

### 发生了什么？

恢复备份，没有自动重启容器，需要自己手动重启

**Comment by chengzhongxue** [comment]
2.20.0-rc.1 也有这个问题

**Comment by Anyexyz** [comment]
本人测试：
2.19.3 备份恢复到 2.19.3 正常
2.19.3 备份恢复到 2.20.0：不显示“正在恢复，稍后重启”那个弹窗，刷新后发现仅恢复了主题和设置，文章内容未恢复，重启后正常。

**Comment by chengzhongxue** [comment]
> 本人测试： 2.19.3 备份恢复到 2.19.3 正常 2.19.3 备份恢复到 2.20.0-rc.1：不显示“正在恢复，稍后重启”那个弹窗，刷新后发现仅恢复了主题和设置，文章内容未恢复，重启后正常。

我也是

**Comment by ruibaby** [comment]
原因是重启接口调用失败。

<img width="1652" alt="image" src="https://github.com/user-attachments/assets/2859e933-945c-4a00-abe7-5ace492c55ac">

**Comment by JohnNiang** [comment]
/assign

经过排查发现是 CSRF Token 的问题。我将尝试在 CSRF 配置中移除接口 `/actuator/restart`。
