### ISSUE TITLE
Add Index on posts.(type,status) and posts.create_time to Accelerate Query

### ISSUE THREAD

**Issue by wtune** [halo-dev/halo#683]
## Problem
Missing index on table **posts** column **create_time** and **(type, status)** might make the underlying query slow.
From [PostService](https://github.com/halo-dev/halo/blob/master/src/main/java/run/halo/app/service/PostService.java)、[BasePostService](https://github.com/halo-dev/halo/blob/master/src/main/java/run/halo/app/service/base/BasePostService.java) and other related file, we can find that we always read **posts** by **type**(DiscriminatorColumn, 0 for posts and 1 for sheet) and **status** order by **create_time** and sometimes insert or update, so adding index on these column can improve the query efficiency significantly.
## Possible Solution
Add Index on posts.(type,status) and posts.create_time

**Comment by ruibaby** [comment]
merged
