### ISSUE TITLE
登陆失败后重置了保持登录选项

### ISSUE THREAD

**Issue by wan92hen** [halo-dev/halo#6835]
### 系统信息

- 外部访问地址: 
- 启动时间: 2024-10-12 13:49
- 版本: 2.20.0-rc.1
- 构建时间: 2024-10-11 17:58
- Git Commit: 218ffa3
- Java: IBM Semeru Runtime Open Edition / 21.0.4+7-LTS
- 数据库: H2 / 2.3.232
- 操作系统: Linux / 5.15.153.1-microsoft-standard-WSL2
- 已激活主题: [Earth 1.10.0](https://github.com/halo-dev/theme-earth)
- 已启动插件:
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [搜索组件 1.6.2](https://github.com/halo-dev/plugin-search-widget)
  - [应用市场 1.5.1](https://www.halo.run/store/apps/app-VYJbF)
  - [评论组件 2.4.0](https://github.com/halo-dev/plugin-comment-widget)

### 使用的哪种方式运行？

Docker

### 发生了什么？

登录页面登录失败后，原本勾选的保持登录选项变成了取消勾选状态，期望登录失败后可以保持之前的勾选状态。

**Comment by ruibaby** [comment]
其实建议将这个选项状态保留在浏览器，不管是否登录成功
