### ISSUE TITLE
2.20 未激活的版本，也会显示和切换到短信登录点击后发送后只会提示失败

### ISSUE THREAD

**Issue by mjsoftking** [halo-dev/halo#6843]
### 系统信息

- 启动时间: 2024-10-12 12:47
- 版本: 2.20.0-rc.1
- 构建时间: 2024-10-11 17:58
- Git Commit: 218ffa3
- Java: IBM Semeru Runtime Open Edition / 21.0.4+7-LTS
- 数据库: MySQL Community Server - GPL / 8.4.2
- 操作系统: Linux / 6.1.27
- 已激活主题: [Dream2.0 Plus 1.3.1.beta1](https://github.com/zsjy/halo-theme-dream2.0-plus.git)
- 已启动插件:
  - [OAuth2 认证 1.4.0-rc.1](https://github.com/halo-sigs/plugin-oauth2)
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.6.2](https://github.com/halo-dev/plugin-search-widget)
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [评论组件 2.4.0](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场 1.5.1](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker

### 发生了什么？

![image](https://github.com/user-attachments/assets/8ba7cf46-81c3-4db9-867e-35fe9e107773)

### 复现步骤

![image](https://github.com/user-attachments/assets/b05e8ee6-6d32-4d71-bdf7-930ed23ad985)

**Comment by ruibaby** [comment]
将在下一个 RC 版本修复。

**Comment by ruibaby** [comment]
已经在 2.20 正式版修复。

/close
