### ISSUE TITLE
2.20 的初始化页面遗漏了 h2 警告

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#6845]
### 你当前使用的版本

2.20.0-rc.1

### 描述一下此特性

Halo 2.19 在 https://github.com/halo-dev/halo/pull/6564 中为初始化页面添加了 H2 数据检查的提示，但重构初始化页面之后遗漏了此功能，建议加上。

/area core
/kind improvement
/milestone 2.20.x

**Comment by JohnNiang** [comment]
建议将使用数据库信息添加至 Global Info 数据中。这样就可以方便地在模板中使用了。

**Comment by ruibaby** [comment]
目前这个判断只会在 setup 用，并且 Console 的概览页面本身也是需要调用 /actuator/info 去拿部分数据的，所以直接给 setup 模板塞 usingH2database 即可。
