### ISSUE TITLE
写文章时无法生成标题目录,makdown自带的生成标题目录也无法使用

### ISSUE THREAD

**Issue by abcxiaobu** [halo-dev/halo#6851]
### 系统信息

https://www.xiaobu.xyz/

### 使用的哪种方式运行？

Docker

### 发生了什么？

写文章时无法生成标题目录,连makdown的标题目录功能 (@[doc]) 也无法使用

**Comment by ruibaby** [comment]
Halo 的默认编辑器非 Markdown 编辑器，并且没有提供 TOC 的功能，TOC 通常建议通过主题在前端实现，两种解决方式：

1. 找一个支持 TOC 生成的主题，如果你当前使用的主题不支持或者支持有问题，建议向主题反馈。
2. 使用一个支持 TOC 的编辑器插件，比如 https://github.com/justice2001/halo-plugin-vditor

/kind support
