### ISSUE TITLE
安装S3对象存储插件后，无法访问/console

### ISSUE THREAD

**Issue by yblpoi** [halo-dev/halo#6858]
### 系统信息

- 外部访问地址：yblgzbbl.cn
- 目前状态： Nginx日志显示499
- 安装插件：[对象存储（Amazon S3 协议） 1.11.0](https://github.com/halo-dev/plugin-s3)
- halo 版本：2.19.3

### 使用的哪种方式运行？

Docker

### 发生了什么？

昨天想尝试建立一个又拍云OSS的存储，但是配置完成之前，突然和后台失去了连接：
```
{
    "msg": "timeout",
    "code": "50402005",
    "id": "b95f7ee9c8be0b4adcb47a5b32feb8b9"
}
```
随后尝试重启halo，依然无法进入console

### 相关日志输出

```shell
117.148.177.217 - - [14/Oct/2024:08:59:54 +0800] "GET /console HTTP/1.1" 499 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0"
117.148.177.217 - - [14/Oct/2024:09:00:11 +0800] "GET /console HTTP/1.1" 499 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0"
117.148.177.217 - - [14/Oct/2024:09:01:35 +0800] "GET /console HTTP/1.1" 499 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0"
117.148.177.217 - - [14/Oct/2024:09:01:52 +0800] "GET /console HTTP/1.1" 499 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0"
117.148.177.217 - - [14/Oct/2024:09:02:15 +0800] "GET /console HTTP/1.1" 499 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0"
```

### 附加信息

重启Halo过程的Log
[_opt_1panel_apps_halo_halo_docker-compose.yml-20241014085950.log](https://github.com/user-attachments/files/17357912/_opt_1panel_apps_halo_halo_docker-compose.yml-20241014085950.log)

**Comment by yblpoi** [comment]
禁用所有插件后解决，但是无法定位到具体的原因

**Comment by JohnNiang** [comment]
Hi @yblpoi ，建议提供以下禁用之前启用的插件列表。如果禁用插件可解决，应该是某个插件导致整个系统阻塞了。

/triage needs-information

**Comment by yblpoi** [comment]
- 外部访问地址: https://yblgzbbl.cn
- 启动时间: 2024-10-16 04:31
- 版本: 2.19.3
- 构建时间: 2024-09-10 17:46
- Git Commit: b6ec7b9
- Java: IBM Semeru Runtime Open Edition / 21.0.4+7-LTS
- 数据库: PostgreSQL / 17.0
- 操作系统: Linux / 5.15.0-122-generic
- 已激活主题: [Walker 1.11.1](https://www.halo.run/store/apps/app-GHgAR)
- 已启动插件:
  - [Trailing Slash 1.0.0](https://github.com/halo-sigs/plugin-trailing-slash)
  - [Media Optimizer 1.1.0](https://github.com/guqing/plugin-cloudinary)
  - [对象存储（Amazon S3 协议） 1.11.0](https://github.com/halo-dev/plugin-s3)
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [Meilisearch 2.0.1](https://github.com/Rainsheep/halo-plugin-meilisearch)
  - [Docsme 1.0.0-alpha.8](https://www.halo.run/store/apps/app-yffxw)
  - [图库管理 1.4.0](https://github.com/halo-sigs/plugin-photos)
  - [文章导入导出 1.2.4](https://jhacker.cn/2023/halo-plugin-export2doc)
  - [Markdown / HTML 内容块 1.2.0](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [站点推送插件 1.5.2](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [编辑器超链接卡片 1.0.3](https://github.com/halo-sigs/plugin-editor-hyperlink-card)
  - [lightgallery.js 灯箱 1.2.1](https://github.com/halo-sigs/plugin-lightgallery)
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [评论组件 2.4.0](https://github.com/halo-dev/plugin-comment-widget)
  - [搜索组件 1.6.2](https://github.com/halo-dev/plugin-search-widget)
  - [页面静态缓存 1.2.1](https://github.com/halo-sigs/plugin-page-cache)
  - [链接管理 1.5.0](https://github.com/halo-sigs/plugin-links)
  - [文章限制阅读 1.4.2](https://www.halo.run/store/apps/app-IzWXo)
  - [瞬间 1.8.0](https://github.com/halo-sigs/plugin-moments)
  - [highlight.js 代码高亮 1.3.2](https://github.com/halo-sigs/plugin-highlightjs)
  - [应用市场 1.5.1](https://www.halo.run/store/apps/app-VYJbF)
  - [WebP Cloud](https://github.com/webp-sh/halo-plugin-webp-cloud)
