### ISSUE TITLE
使用cloudflare CDN代理 控制台报错

### ISSUE THREAD

**Issue by la02w** [halo-dev/halo#6864]
### 系统信息

- 外部访问地址: 
- 启动时间: 2024-10-14 10:37
- 版本: 2.19.3
- 构建时间: 2024-09-10 17:45
- Git Commit: 9ffb1bb
- Java: IBM Semeru Runtime Open Edition / 21.0.4+7-LTS
- 数据库: H2 / 2.2.224
- 操作系统: Linux / 5.15.0-77-generic
- 已激活主题: [Earth 1.9.0](https://github.com/halo-dev/theme-earth)
- 已启动插件:
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.6.2](https://github.com/halo-dev/plugin-search-widget)
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [评论组件 2.4.0](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场 1.4.0](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

美国vps
cloudflare CDN代理后就出现报错，进入页面会出现手机模式的导航栏,过一会儿会消失
![image](https://github.com/user-attachments/assets/17f70e99-211f-4dcd-944e-70a2d6aee4ee)
![image](https://github.com/user-attachments/assets/a7bcd17e-7f63-41e8-8a21-827848cca589)
**报错位置**
![image](https://github.com/user-attachments/assets/454bbc13-a851-4682-8e0c-10e9b2b81f8e)

**Comment by ruibaby** [comment]
关闭这个功能：

<img width="1132" alt="image" src="https://github.com/user-attachments/assets/5af1b05d-3a9b-4593-8dc1-d2f0d27646f0">

/kind support
