### ISSUE TITLE
.halo2根目录下空白

### ISSUE THREAD

**Issue by NorLorikein** [halo-dev/halo#6872]
### 系统信息

- 外部访问地址: http://localhost:8090/
- 启动时间: 2024-10-15 23:09
- 版本: 2.20.3
- 构建时间: 2024-10-15 17:26
- Git Commit: b95a83a
- Java: IBM Semeru Runtime Open Edition / 21.0.4+7-LTS
- 数据库: Source distribution / 5.7.43-log
- 操作系统: Linux / 6.1.0-10-amd64
- 已激活主题: [Sakura 2.4.0](https://github.com/LIlGG/halo-theme-sakura.git)
- 已启动插件:
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.6.2](https://github.com/halo-dev/plugin-search-widget)
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [评论组件 2.5.0](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场 1.5.1](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

root目录下的.halo2根目录中为空白，没有生成各类工作目录
![Image](https://github.com/user-attachments/assets/254770ec-0ea9-47f1-b2c4-8e753f1bb1db)

**Comment by JohnNiang** [comment]
请提供完整的复现步骤。

/triage needs-information
