### ISSUE TITLE
提供重新加载主题文件的选项

### ISSUE THREAD

**Issue by HowieHz** [halo-dev/halo#6873]
### 描述一下此特性

我在开发主题的时候修改 settings.yaml 和 theme.yaml 文件时主题不能重新读取，只能删除主题再重新安装
希望提供选项可以 手动 强制 重新读取主题文件

**Comment by ruibaby** [comment]
https://docs.halo.run/developer-guide/theme/config#%E6%9B%B4%E6%96%B0%E9%85%8D%E7%BD%AE

**Comment by HowieHz** [comment]
😂😂😇😇
谢谢
