### ISSUE TITLE
更新2.20.x 后灯箱插件无效果

### ISSUE THREAD

**Issue by wxyShine** [halo-dev/halo#6875]
### 系统信息

- 外部访问地址: https://www.wxy97.com
- 启动时间: 2024-10-16 08:25
- 版本: 2.20.3
- 构建时间: 2024-10-15 17:29
- Git Commit: 3a3e0e8
- Java: IBM Semeru Runtime Open Edition / 21.0.4+7-LTS
- 数据库: PostgreSQL / 16.4 (Debian 16.4-1.pgdg120+2)
- 操作系统: Linux / 6.1.0-10-amd64
- 已激活主题: [Walker 1.11.1](https://www.halo.run/store/apps/app-GHgAR)
- 已启动插件:
  - [lightgallery.js 灯箱 1.2.1](https://github.com/halo-sigs/plugin-lightgallery)
  - [友链自助提交插件 2.0.4](https://github.com/liuyiwuqing/halo-plugin-links-submit)
  - [链上好文 1.0.1](https://github.com/guqing/plugin-share-post-via-link)
  - [编辑器超链接卡片 1.0.3](https://github.com/halo-sigs/plugin-editor-hyperlink-card)
  - [Docsme 1.0.0-alpha.8](https://www.halo.run/store/apps/app-yffxw)
  - [豆瓣 1.2.1](https://github.com/chengzhongxue/plugin-douban)
  - [Data Studio（数据工厂） 1.0.0-alpha.2](https://github.com/halo-sigs/plugin-data-studio)
  - 联系表单 1.0.2
  - [Umami 1.4.0](https://github.com/halo-sigs/plugin-umami)
  - [highlight.js 代码高亮 1.3.2](https://github.com/halo-sigs/plugin-highlightjs)
  - [静态网页服务 1.0.0-alpha.5](https://www.halo.run/store/apps/app-gFkMn)
  - [OAuth2 认证 1.4.1](https://github.com/halo-sigs/plugin-oauth2)
  - [SEO 工具集 1.1.0](https://www.halo.run/store/apps/app-FNGbT)
  - [Vditor 编辑器 1.8.0](https://github.com/justice2001/halo-plugin-vditor)
  - [文本绘图 1.3.0](https://github.com/halo-sigs/plugin-text-diagram)
  - [Meilisearch 2.0.1](https://github.com/Rainsheep/halo-plugin-meilisearch)
  - [AI 助手 1.0.0](https://www.halo.run/store/apps/app-riNgb)
  - [增强备份（Backup IMproved） 1.1.1](https://www.halo.run/store/apps/app-dHakX)
  - [Metrics Graph 1.1.0](https://github.com/guqing/plugin-metrics-graph)
  - [Markdown / HTML 内容块 1.2.0](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [文章限制阅读 Pro 1.4.2](https://www.halo.run/store/apps/app-TzRqd)
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.6.2](https://github.com/halo-dev/plugin-search-widget)
  - [评论组件 2.5.0](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场 1.5.1](https://www.halo.run/store/apps/app-VYJbF)
  - [瞬间 1.8.0](https://github.com/halo-sigs/plugin-moments)
  - [链接管理 1.5.0](https://github.com/halo-sigs/plugin-links)
  - [图库管理 1.4.0](https://github.com/halo-sigs/plugin-photos)
  - [对象存储（Amazon S3 协议） 1.12.0](https://github.com/halo-dev/plugin-s3)

### 使用的哪种方式运行？

Docker

### 发生了什么？

站点地址:  https://www.wxy97.com/archives/dc228e38-00e9-4cef-98dc-8a8098cbc185

### 复现步骤

更新版本之前正常使用的，更新后 点击图片无反应。
插件配置如图
![Image](https://github.com/user-attachments/assets/ae7dbf5b-4dea-4f5f-bfa6-ff019589cd2b)

**Comment by wxyShine** [comment]
发现原因了  上面没有配置 [内容页面匹配]   访问页面时不会加载lightgallery.min.js 
配置上[内容页面匹配]后  页面会加载lightgallery.min.js 就正常了。

(之前也一直没配置好像 就能用

**Comment by ruibaby** [comment]
可以复现，看起来是页面匹配规则功能失效了。

cc @halo-dev/sig-halo 看看是插件需要适配还是 Halo 的改动影响了这个表现

**Comment by JohnNiang** [comment]
可能是 https://github.com/halo-dev/halo/pull/6680 的修改导致在插件中无法获取 ServerWebExchange，最终导致插件无法正常工作。

/kind bug
/remove-triage needs-information
/assign @guqing

**Comment by guqing** [comment]
/remove-triage needs-information
/kind bug
/area core
/milestone 2.20.x

这是一个 bug，由 https://github.com/halo-dev/halo/pull/6680 改动导致插件中的 TemplateProcessor 扩展点中无法获取到请求上下文导致

**Comment by wxyShine** [comment]
更新halo-pro:2.20.4 后  瞬间页面 和 相册页面 依旧无效

**Comment by wxyShine** [comment]
更改配置后好了  ![Image](https://github.com/user-attachments/assets/cb38225e-e57f-4de3-89c9-e94c61563e01)
