### ISSUE TITLE
2.20.3 后台重新登录后，菜单没了？

### ISSUE THREAD

**Issue by ahong18s** [halo-dev/halo#6882]
### 系统信息

- 版本 2.20.3
- 专业版 是
- 环境 1Panel 1.10.19

### 使用的哪种方式运行？

Docker

### 发生了什么？

后台管理界面，登录失效了，在弹窗的登录窗口里重新登录后，大多数的功能菜单消失了（截图）。

刷新页面，无效。

关闭这个浏览器页签，在新的浏览器页签里访问，并从前台重新进入后台后，显示正常了。

### 复现步骤

1. 进入后台管理
2. 等待登录失效后，在弹出的登录窗口里重新登录
3. 大部分菜单消失，刷新无效，关闭页签再恢复——无效，ctrl+f5会导致重定向404

### 附加信息

截图：[https://github.com/ahong18s/ISSUE/blob/master/halo.png](https://github.com/ahong18s/ISSUE/blob/master/halo.png)

**Comment by JohnNiang** [comment]
Halo 2.20 登录之后默认会跳转到 /uc（个人中心）。如果你想要跳转至 /console（管理页面），需要点击左下角的“设置”按钮。

/triage unresolved

**Comment by ahong18s** [comment]
@JohnNiang 再就是注册时，第一个“用户名”填写了中文，“提交注册“没有任何反应，也没有任何错误信息。

应该提示错误，或只允许输入符合规则的内容。

**Comment by ahong18s** [comment]
看起来像是被新特性“登录后跳转个人中心”覆盖了路由行为，但管理员在管理界面时，“重新登录”不应该被重定向到“个人中心”？！

**Comment by ruibaby** [comment]
> [@JohnNiang](https://github.com/JohnNiang) 再就是注册时，第一个“用户名”填写了中文，“提交注册“没有任何反应，也没有任何错误信息。
> 
> 应该提示错误，或只允许输入符合规则的内容。

没有复现这个问题。

![Image](https://github.com/user-attachments/assets/5cfe2cd1-541e-4ce4-8d93-3aa6f4188973)

**Comment by ruibaby** [comment]
> 看起来像是被新特性“登录后跳转个人中心”覆盖了路由行为，但管理员在管理界面时，“重新登录”不应该被重定向到“个人中心”？！

如果你是未登录时直接访问 /console，跳转到登录页面登录之后会跳转到 /console，我们有实现记住上一个地址的功能。

**Comment by ahong18s** [comment]
@ruibaby 登录了，当时我去处理别的事情，再回到后台页面上时，提示失效并弹窗登录窗口！登录后就这样子了。

**Comment by ahong18s** [comment]
> > [@JohnNiang](https://github.com/JohnNiang) 再就是注册时，第一个“用户名”填写了中文，“提交注册“没有任何反应，也没有任何错误信息。
> > 应该提示错误，或只允许输入符合规则的内容。
> 
> 没有复现这个问题。
> 
> ![Image](https://github.com/user-attachments/assets/5cfe2cd1-541e-4ce4-8d93-3aa6f4188973)

我按照你输入的内容，的确是提示错误了，例如不是“你好你好”的场景：

https://github.com/ahong18s/ISSUE/blob/master/halo/%E6%B3%A8%E5%86%8C%E6%97%B6%E6%9C%AA%E9%AA%8C%E8%AF%81%E7%94%A8%E6%88%B7%E5%90%8D%EF%BC%9F2024-10-17%2018-26-57.mp4

**Comment by ruibaby** [comment]
> https://github.com/ahong18s/ISSUE/blob/master/halo/%E6%B3%A8%E5%86%8C%E6%97%B6%E6%9C%AA%E9%AA%8C%E8%AF%81%E7%94%A8%E6%88%B7%E5%90%8D%EF%BC%9F2024-10-17%2018-26-57.mp4

从这个视频知道为什么了，这是 Firefox 浏览器的密码管理功能覆盖了原有的表单验证提示：

![Image](https://github.com/user-attachments/assets/548c850e-86a5-4523-97c2-1c272333ec5d)

浏览器正常表现应该是（比如 Chrome）：

![Image](https://github.com/user-attachments/assets/6b974878-de91-4c77-858c-3f8cebd70cae)

我不确定这是否能在代码层面规避，晚点会调查一下。

**Comment by ruibaby** [comment]
> > [@ruibaby](https://github.com/ruibaby) 登录了，当时我去处理别的事情，再回到后台页面上时，提示失效并弹窗登录窗口！登录后就这样子了。
> 
> 明白了，这个时候跳转到 /login 确实没有携带当前页面的地址，这个问题会在下个版本优化一下。

更正一下这个回复：

刚刚检查代码并尝试复现并没有发现这个问题：

https://github.com/user-attachments/assets/e5fa60ab-bcc9-4ccb-9cd5-186d6878eb97

如果可以的话，可以录制一个复现视频。

**Comment by ahong18s** [comment]
> > > [@ruibaby](https://github.com/ruibaby) 登录了，当时我去处理别的事情，再回到后台页面上时，提示失效并弹窗登录窗口！登录后就这样子了。
> > 
> > 
> > 明白了，这个时候跳转到 /login 确实没有携带当前页面的地址，这个问题会在下个版本优化一下。
> 
> 更正一下这个回复：
> 
> 刚刚检查代码并尝试复现并没有发现这个问题：
> 
>  2024-10-17.23-31-48.mp4 
> 你可以录制一个复现视频来帮助我们复现。

可能需要不止一天的时间去“复现登录失效出现小弹窗形式的登录窗口”，这很难，建议你们排查“登录失效出现小弹窗形式的登录窗口”。

如果不接受建议，请关闭这个 ISSUS。

**Comment by ruibaby** [comment]
@ahong18s 

> 复现登录失效出现小弹窗形式的登录窗口

我没有理解这个小弹窗形式的登录窗口是什么，在之前的版本确实会有登录弹窗，但在 2.20 已经完全移除，正常情况应该是我视频中的那种。

此外，关于登录失效的问题，你是否有在登录的时候勾选保持登录回话？ 没有勾选的话，默认会在三十分钟没有活动的情况下登录失效，或者关闭浏览器也会登录失效。

**Comment by ruibaby** [comment]
如果你想手动复现登录失效，你可以像我的视频那样，清空浏览器的 Cookie

**Comment by JohnNiang** [comment]
> 如果你想手动复现登录失效，你可以像我的视频那样，清空浏览器的 Cookie

其实也不用这么麻烦。直接在新的标签访问 /logout 登出即可。

**Comment by ahong18s** [comment]
> [@ahong18s](https://github.com/ahong18s)
> 
> > 复现登录失效出现小弹窗形式的登录窗口
> 
> 我没有理解这个小弹窗形式的登录窗口是什么，在之前的版本确实会有登录弹窗，但在 2.20 已经完全移除，正常情况应该是我视频中的那种。
> 
> 此外，关于登录失效的问题，你是否有在登录的时候勾选保持登录回话？ 没有勾选的话，默认会在三十分钟没有活动的情况下登录失效，或者关闭浏览器也会登录失效。

是的，我无法再次遇到“小弹窗形式的登录弹窗”，我也会接受“登录后进入个人信息的后台页面”。

例如：https://github.com/ahong18s/ISSUE/blob/master/halo/%E7%AE%A1%E7%90%86%E5%91%98%E7%99%BB%E5%BD%95%E5%90%8E%E8%BF%9B%E5%85%A5%E9%A1%B5%E9%9D%A2%EF%BC%9F2024-10-18%2009-14-06.mp4

**Comment by JohnNiang** [comment]
Hi @ahong18s , 感谢持续反馈！

从视频中了解到，你在登录成功之后再次进行了登录导致被重定向到了 `/uc`。实际上这是符合预期的。

Halo 在登录成功之前保存之前访问的页面，一旦登录成功并被重定向到了指定的页面，将会清理掉之前保存的页面。所以第二次登录就跳转到了默认的重定向页面 `/uc`。

---

触发“登录弹窗”的复现步骤：

1. 打开新的标签进入文章管理页面 `/console/posts`
2. 打开新的标签访问 `/logout` 页面，点击退出登录
3. 回到文章管理页面标签，点击右上角的刷新小按钮
4. 出现“登录弹窗”

**Comment by ahong18s** [comment]
> Hi [@ahong18s](https://github.com/ahong18s) , 感谢持续反馈！
> 
> 从视频中了解到，你在登录成功之后再次进行了登录导致被重定向到了 `/uc`。实际上这是符合预期的。
> 
> Halo 在登录成功之前保存之前访问的页面，一旦登录成功并被重定向到了指定的页面，将会清理掉之前保存的页面。所以第二次登录就跳转到了默认的重定向页面 `/uc`。
> 
> 触发“登录弹窗”的复现步骤：
> 
> 1. 打开新的标签进入文章管理页面 `/console/posts`
> 2. 打开新的标签访问 `/logout` 页面，点击退出登录
> 3. 回到文章管理页面标签，点击右上角的刷新小按钮
> 4. 出现“登录弹窗”

是的，符合预期是很好的结果，当然在录屏中第二次的登录行为只有一次。

那么，我将关闭这个 ISSUE。
