### ISSUE TITLE
已删除的用户还显示在某些位置

### ISSUE THREAD

**Issue by youngledo** [halo-dev/halo#6884]
### 系统信息

- 外部访问地址: http://10.20.21.7:8090
- 启动时间: 2024-10-16 11:05
- 版本: 2.20.3
- 构建时间: 2024-10-15 17:29
- Git Commit: 3a3e0e8
- Java: IBM Semeru Runtime Open Edition / 21.0.4+7-LTS
- 数据库: MySQL Community Server - GPL / 8.4.2
- 操作系统: Linux / 6.8.0-45-generic
- 已激活主题: [Hao 1.5.8](https://github.com/chengzhongxue/halo-theme-hao)
- 已启动插件:
  - [highlight.js 代码高亮 1.3.2](https://github.com/halo-sigs/plugin-highlightjs)
  - [链接管理 1.5.0](https://github.com/halo-sigs/plugin-links)
  - [Metrics Graph 1.0.0](https://github.com/guqing/plugin-metrics-graph)
  - [阿里云 OSS 1.0.1](https://github.com/halo-sigs/plugin-alioss)
  - [Willow Markdown 编辑器 1.0.0](https://github.com/guqing/willow-mde)
  - [lightgallery.js 灯箱 1.2.1](https://github.com/halo-sigs/plugin-lightgallery)
  - [应用市场 1.5.1](https://www.halo.run/store/apps/app-VYJbF)
  - [站点迁移 1.3.0](https://github.com/halo-sigs/plugin-migrate)
  - [RSS 1.1.1](https://github.com/halo-sigs/plugin-feed)
  - [评论组件 1.7.0](https://github.com/halo-sigs/plugin-comment-widget)
  - [搜索组件 1.1.0](https://github.com/halo-sigs/plugin-search-widget)
  - [Sitemap 1.0.2](https://github.com/halo-sigs/plugin-sitemap)

### 使用的哪种方式运行？

Docker

### 发生了什么？

使用备份的数据还原的数据，还显示着已删除的用户，点开用户又看不到这个用户，无法删除。
![Image](https://github.com/user-attachments/assets/8b56568c-9c7f-4841-a7b0-a6bed7e66c21)

![Image](https://github.com/user-attachments/assets/758466d8-c5cc-44dd-a6c2-5fa6aa58ee13)

**Comment by JohnNiang** [comment]
Ghost 用户是隐藏的，主要针对“已删除”用户的占位，并无其他实际意义。可以参考 GitHub 的已删除用户设计：<https://github.com/ghost>。

/triage unresolved
/close

**Comment by youngledo** [comment]
可以删除吗，或者不显示。
