### ISSUE TITLE
初始化页面选择语言后，后续登录页没有保持所选语言

### ISSUE THREAD

**Issue by wan92hen** [halo-dev/halo#6888]
### 系统信息

- 外部访问地址: http://localhost:8090
- 启动时间: 2024-10-17 14:22
- 版本: 2.20.3
- 构建时间: 2024-10-15 17:29
- Git Commit: 3a3e0e8
- Java: IBM Semeru Runtime Open Edition / 21.0.4+7-LTS
- 数据库: MySQL Community Server - GPL / 8.4.2
- 操作系统: Linux / 5.10.134-17.2.al8.x86_64
- 已激活主题: [Earth 1.11.0](https://github.com/halo-dev/theme-earth)
- 已启动插件:
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.6.2](https://github.com/halo-dev/plugin-search-widget)
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [评论组件 2.4.0](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场 1.5.1](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker

### 发生了什么？

初始化页面选择语言后，初始化完成后跳转到登录页没有保持所选语言。

**Comment by guqing** [comment]
我试了没有复现，请看 VCR

https://github.com/user-attachments/assets/4dd2137b-0193-4459-b0a0-a8bcadcaf137

/triage needs-information

**Comment by wan92hen** [comment]
> 我试了没有复现，请看 VCR
> 
>  Kapture.2024-10-17.at.16.40.48.mp4 
> /triage needs-information

试下不用 localhost，用内网 IP 访问呢？

**Comment by ruibaby** [comment]
@wan92hen 是否使用了 1Panel 进行代理？我之前也复现过，似乎经过 1Panel 代理之后丢失了 Set-Cookie，导致没有把 language 放在 cookie 中，但是我测试加上 https 之后就可以了，暂不清楚为什么。

**Comment by guqing** [comment]
> [@wan92hen](https://github.com/wan92hen) 是否使用了 1Panel 进行代理？我之前也复现过，似乎经过 1Panel 代理之后丢失了 Set-Cookie，导致没有把 language 放在 cookie 中，但是我测试加上 https 之后就可以了，暂不清楚为什么。

原因是设置语言 cookie 的方法上 Secure 属性，因此使用 ip 访问时不是 https 的会阻止 cookie 设置，因此无法生效
