### ISSUE TITLE
2.20.4 管理员发布文章后，自动跳到了个人中心？

### ISSUE THREAD

**Issue by ahong18s** [halo-dev/halo#6901]
### 系统信息

- 外部访问地址: https://blog.thalliumcode.com
- 启动时间: 2024-10-19 08:52
- 版本: 2.20.4
- 构建时间: 2024-10-17 17:57
- Git Commit: 5734edb
- Java: IBM Semeru Runtime Open Edition / 21.0.4+7-LTS
- 数据库: MySQL Community Server - GPL / 8.4.3
- 操作系统: Linux / 6.8.0-45-generic
- 已激活主题: [Earth 1.11.0](https://github.com/halo-dev/theme-earth)
- 已启动插件:
  - [OAuth2 认证 1.4.1](https://github.com/halo-sigs/plugin-oauth2)
  - [文章导入导出 1.2.4](https://jhacker.cn/2023/halo-plugin-export2doc)
  - [Vditor 编辑器 1.8.0](https://github.com/justice2001/halo-plugin-vditor)
  - [Willow Markdown 编辑器 1.0.0](https://github.com/guqing/willow-mde)
  - [ByteMD 1.4.0](https://github.com/ruibaby/plugin-bytemd)
  - [lightgallery.js 灯箱 1.2.1](https://github.com/halo-sigs/plugin-lightgallery)
  - [瞬间 1.8.0](https://github.com/halo-sigs/plugin-moments)
  - [highlight.js 代码高亮 1.3.2](https://github.com/halo-sigs/plugin-highlightjs)
  - [增强备份（Backup IMproved） 1.1.1](https://www.halo.run/store/apps/app-dHakX)
  - [SEO 工具集 1.1.0](https://www.halo.run/store/apps/app-FNGbT)
  - [微信公众号发布 1.3.1](https://www.halo.run/store/apps/app-Dtuoa)
  - [文章限制阅读 Pro 1.4.2](https://www.halo.run/store/apps/app-TzRqd)
  - [社交 IAM 认证 1.3.2](https://www.halo.run/store/apps/app-IXZkJ)
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.6.2](https://github.com/halo-dev/plugin-search-widget)
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [评论组件 2.5.0](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场 1.6.0](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker

### 发生了什么？

发布文章后，返回到了“个人信息”页面，此时没有文章、评论等功能菜单。

并且，此时不能进入控制台，直到我关闭这个页面，从前端重新进入控制台。

I'm 管理员哒？！

### 复现步骤

1、编辑文章，md编辑器，空白内容不填写、不保存（此时没有生成id的场景）
2、离开一会儿后返回时登录失效，跳转登录页并登录后，自动重定向了编辑文章的页面，填写内容并发布文章
3、发布后，应该返回文章列表页面，但其实返回到了“个人中心-我的”，如“附加信息-截图”截图所示

### 相关日志输出

页面跳转行为，没有日志。

### 附加信息

截图：[https://github.com/ahong18s/ISSUE/blob/master/halo/%E7%BC%96%E8%BE%91%E6%96%87%E7%AB%A0%E5%90%8E%E8%87%AA%E5%8A%A8%E8%BF%94%E5%9B%9E%E5%88%B0%E4%BA%86%E4%B8%AA%E4%BA%BA%E4%B8%AD%E5%BF%83%EF%BC%9F_2024-10-19_11-55-44.png](https://github.com/ahong18s/ISSUE/blob/master/halo/%E7%BC%96%E8%BE%91%E6%96%87%E7%AB%A0%E5%90%8E%E8%87%AA%E5%8A%A8%E8%BF%94%E5%9B%9E%E5%88%B0%E4%BA%86%E4%B8%AA%E4%BA%BA%E4%B8%AD%E5%BF%83%EF%BC%9F_2024-10-19_11-55-44.png)

**Comment by ahong18s** [comment]
复现步骤1、是“新增文章”不是“编辑文章”

**Comment by ruibaby** [comment]
感谢反馈，可以复现，原因是 https://github.com/halo-dev/halo/blob/833b884bdb409f31ed5845ae2668ffd194312263/ui/console-src/modules/contents/posts/PostEditor.vue#L239 没有适配新的登录流程。

/assign
/kind bug
