### ISSUE TITLE
在2.20.x版本中, 静态资源也校验了登陆, 导致在将静态资源单独进入cdn后回源失败.

### ISSUE THREAD

**Issue by rohow** [halo-dev/halo#6908]
### System information

None

### What is the project operation method?

Docker

### What happened?

目前我的部署方式是通过nginx,将静态资源部分动态subs_filter替换为cdn的地址.

例如: 博客地址 https://blog.com, 而静态资源地址 https://static.cdn.com/blog

在之前版本中,静态资源不会校验登陆.所以这种部署方式一直没问题. 

但升级到2.20.x后, 由于现在静态资源也校验登陆,直接302到登陆页面, 导致目前cdn回源失败.

是否可以继续将静态资源排除校验呢?

**Comment by rohow** [comment]
@JohnNiang 感谢回复~ 目前是uc 和 console中的静态资源返回了302.

请问这部分的静态资源是否可以也过滤出来呢?

我目前的场景是 博客域名(https://dev.cm)在国内无法备案  但是又需要使用国内cdn(需要备案 但对于国内速度最优)  

所以我将全部静态资源匹配到国内已备案的域名上(https://static.fillcode.com) 并且使用路径做分发(eq: https://static.fillcode.com/dev-cm/)

目前我没有找到能够统一配置替换静态资源路径的功能的前提下 目前只能这么实现了...  这种配置在2.20.x之前的版本是一直生效的

**Comment by JohnNiang** [comment]
感谢进一步反馈！

后续可以考虑在认证配置中排除以下两个路径规则： `/console/assets/**` 和 `/uc/assets/**`。

/assign
/kind improvement
/area core
/milestone 2.20.x

**Comment by JohnNiang** [comment]
Hi @rohow , [Halo 2.20.6](https://github.com/halo-dev/halo/releases/tag/v2.20.6) 已经发布，非常欢迎测试当前问题是否已经解决。
