### ISSUE TITLE
验证邮箱时并未向相应的邮箱进行邮件发送

### ISSUE THREAD

**Issue by LEIYOUSU** [halo-dev/halo#6909]
### 系统信息

- 外部访问地址: 
- 启动时间: 2024-10-11 21:50
- 版本: 2.19.3
- 构建时间: 2024-09-10 17:45
- Git Commit: 9ffb1bb
- Java: IBM Semeru Runtime Open Edition / 21.0.4+7-LTS
- 数据库: H2 / 2.2.224
- 操作系统: Linux / 3.10.0-957.21.3.el7.x86_64
- 已激活主题: [Theme Joe3 1.4.0](https://github.com/jiewenhuang/halo-theme-joe3.0)
- 已启动插件:
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.6.2](https://github.com/halo-dev/plugin-search-widget)
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [评论组件 2.4.0](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场 1.4.0](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker

### 发生了什么？

![Image](https://github.com/user-attachments/assets/bb9f768d-c539-4b13-84fd-3a56d1505c89)
个人中心管理中，对电子邮箱地址进行验证的操作无法进行，因为我发现点击发送验证码之后，对应的邮箱没有收到验证码，虽然经过网络检查显示200无问题，但是邮箱确实没有收到相关的验证码

### 复现步骤

1.进入个人中心
2.点击电子邮箱验证
3。发送验证(后续就是收不到验证码也没有任何提示)

**Comment by guqing** [comment]
/triage needs-information

首先需要确保在设置-> 通知设置->邮箱通知中的配置是正确的，可以点击测试邮箱来验证
如果上述是正确的，建议检查你的收件邮箱的垃圾邮件分类是否有邮件
如果都没有建议提供相关日志

**Comment by LEIYOUSU** [comment]
感谢你所提供的解决方案，没有仔细阅读文档内容，所以才出现这样的忽略，目前已经解决了相关问题。
但是也针对这个问题提出一点小建议:对于刚刚使用Halo的人，可能文档上阅读都有所疏漏，如果能在验证邮箱的地方添加判断提示“请先进行邮箱配置”的话会更加友好。祝好!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "halo-dev/halo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月21日(星期一) 下午3:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [halo-dev/halo] 验证邮箱时并未向相应的邮箱进行邮件发送 (Issue #6909)





 
/triage needs-information
 
首先需要确保在设置-&gt; 通知设置-&gt;邮箱通知中的配置是正确的，可以点击测试邮箱来验证
 如果上述是正确的，建议检查你的收件邮箱的垃圾邮件分类是否有邮件
 如果都没有建议提供相关日志

**Comment by guqing** [comment]
> 如果能在验证邮箱的地方添加判断提示“请先进行邮箱配置”的话会更加友好。祝好!

此建议已经有两个相关的 issue https://github.com/halo-dev/halo/issues/6904 https://github.com/halo-dev/halo/issues/4930 可以关注后续

由于此问题已经解决，我就关闭 issue

/close
