### ISSUE TITLE
文章别名设置只有【根据标题】生效，其他的(例如UUID)新建文章进设置之后全是时间戳。

### ISSUE THREAD

**Issue by githuboneyarkee** [halo-dev/halo#6913]
### 系统信息

- 外部访问地址: https://blog.rwo.cc
- 启动时间: 2024-10-17 22:47
- 版本: 2.20.3
- 构建时间: 2024-10-15 17:29
- Git Commit: 3a3e0e8
- Java: IBM Semeru Runtime Open Edition / 21.0.4+7-LTS
- 数据库: PostgreSQL / 16.2
- 操作系统: Linux / 3.10.0-1160.114.2.el7.x86_64
- 已激活主题: [Chirpy 1.4.4](https://github.com/AirboZH/halo-theme-chirpy.git)
- 已启动插件:
  - [瞬间 1.7.0](https://github.com/halo-sigs/plugin-moments)
  - [链接管理 1.4.0](https://github.com/halo-sigs/plugin-links)
  - [增强备份（Backup IMproved） 1.1.1](https://www.halo.run/store/apps/app-dHakX)
  - [SEO 工具集 1.0.6](https://www.halo.run/store/apps/app-FNGbT)
  - [社交 IAM 认证 1.3.0](https://www.halo.run/store/apps/app-IXZkJ)
  - [对象存储（Amazon S3 协议） 1.10.0](https://github.com/halo-dev/plugin-s3)
  - [Umami 1.4.0](https://github.com/halo-sigs/plugin-umami)
  - [UniHalo 配置 1.0.4](https://github.com/ialley-workshop-open/plugin-uni-halo)
  - [Willow Markdown 编辑器 1.0.0](https://github.com/guqing/willow-mde)
  - [ByteMD 1.4.0](https://github.com/ruibaby/plugin-bytemd)
  - [OAuth2 认证 1.2.0](https://github.com/halo-sigs/plugin-oauth2)
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.6.2](https://github.com/halo-dev/plugin-search-widget)
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [评论组件 2.4.0](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场 1.4.0](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker

### 发生了什么？

文章别名设置除了【根据标题】，设置成其他的(例如UUID)，新建文章进设置之后全是时间戳。从之前版本一直就是，新版本一直未改善。

### 复现步骤

![Image](https://github.com/user-attachments/assets/adb99ae6-af80-4213-9995-6f6f0a2a9bc6)
![Image](https://github.com/user-attachments/assets/a2183816-f9e8-40c0-995a-bf1d88988e1c)

**Comment by JohnNiang** [comment]
Hi @githuboneyarkee , thank you for reaching out here!

我这边无法复现这个问题。无论是个人中心端还是管理端中新建文章，都是可以正常应用别名生成策略的。

**Comment by githuboneyarkee** [comment]
你好我的步骤是：
设置别名：管理控制台-点击设置-文章设置-别名设置【Short UUID】-保存
文章发布：管理控制台-文章-新建-保存-保存之后的设置-别名*(显示的是时间戳)

截止回消息时间，按照上面的流程还是，我的版本信息还是issues中的。
如果还是复现不了的话，抽个时间我可以演示的。

**Comment by ruibaby** [comment]
我这边可以复现这个问题，感谢反馈。

/kind bug
/area ui

**Comment by githuboneyarkee** [comment]
个人中心端并不确定，因为不经常用
