### ISSUE TITLE
当普通用户访问或者投稿访问时，建议添加用户自我进行Halo注册的选项

### ISSUE THREAD

**Issue by LEIYOUSU** [halo-dev/halo#6918]
### 你当前使用的版本

2.19.3

### 描述一下此特性

![Image](https://github.com/user-attachments/assets/d5402083-e471-499f-8f8a-6049d389ecaf)
我认为访客、投稿者等初始用户应该有自己注册的权限，而不是只能通过后台管理员进行添加。这样对于本身没有Halo账户的用户很不友好，我认为比较合理的设计应该是在点击登录之后，所跳转的图1的界面中添加自我注册的功能，而不仅仅只是能通过图2中管理员进行添加，否则，当一个随意的访客想要评论或者点赞的时候，没有登录账户提供它使用。
![Image](https://github.com/user-attachments/assets/77ce3d1c-1717-496f-a389-17fcd7913d54)

**Comment by ruibaby** [comment]
默认不开启注册，需要自行开启。

https://docs.halo.run/user-guide/settings#%E7%94%A8%E6%88%B7%E8%AE%BE%E7%BD%AE

/kind support

**Comment by LEIYOUSU** [comment]
解决了，谢谢! 祝好！
