### ISSUE TITLE
feat: 可否增加文章前的路径可配置？

### ISSUE THREAD

**Issue by YuppyHub** [halo-dev/halo#693]
## 概述
你好， 我用 halo 不是想单纯做一个博客，想用一些其它的分享。
现在进入到每个 『文章/分享』 里的链接是 https://www.halo.run/{archives}/share_xxx
请问花括号里的地址是不是可以做成可配置的？

**Comment by ruibaby** [comment]
下个版本支持多种风格的路径设置：https://github.com/halo-dev/halo/pull/563

但是估计不是你想要的。你这种应该可以用分类来实现，比如 `/categories/java/{slug}`，但是这个得等到后面在开发了。
