### ISSUE TITLE
[functional flaw]Backup file 500MB too large upload error 413

### ISSUE THREAD

**Issue by MNDIA** [halo-dev/halo#6935]
### System information

- Start time: 2024-10-21 14:59
- Version: 2.20.5
- Build time: 2024-10-18 21:41
- Git Commit: 0e2ad5e
- Java: IBM Semeru Runtime Open Edition / 21.0.4+7-LTS
- Database: Source distribution / 8.0.30
- Operating system: Linux / 6.1.0-26-amd64
- Activated theme: [Hao 1.5.9](https://github.com/chengzhongxue/halo-theme-hao)
- Enabled plugins:
  - [文章导入导出 1.2.4](https://jhacker.cn/2023/halo-plugin-export2doc)
  - [站点迁移 1.7.0](https://github.com/halo-sigs/plugin-migrate)
  - [ByteMD 1.4.0](https://github.com/ruibaby/plugin-bytemd)
  - [Markdown / HTML 内容块 1.2.0](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [Data Studio（数据工厂） 1.0.0-alpha.2](https://github.com/halo-sigs/plugin-data-studio)
  - [图库管理 1.4.0](https://github.com/halo-sigs/plugin-photos)
  - [lightgallery.js 灯箱 1.2.1](https://github.com/halo-sigs/plugin-lightgallery)
  - [Umami 1.4.0](https://github.com/halo-sigs/plugin-umami)
  - [链接管理 1.5.0](https://github.com/halo-sigs/plugin-links)
  - [AList 存储库 1.1.0](https://github.com/halo-sigs/plugin-alist)
  - [瞬间 1.8.0](https://github.com/halo-sigs/plugin-moments)
  - [Unsplash 1.2.1](https://github.com/halo-sigs/plugin-unsplash)
  - [highlight.js 代码高亮 1.3.2](https://github.com/halo-sigs/plugin-highlightjs)
  - [对象存储（Amazon S3 协议） 1.12.0](https://github.com/halo-dev/plugin-s3)
  - [OAuth2 认证 1.4.1](https://github.com/halo-sigs/plugin-oauth2)
  - [页面静态缓存 1.2.1](https://github.com/halo-sigs/plugin-page-cache)
  - [编辑器超链接卡片 1.1.0](https://github.com/halo-sigs/plugin-editor-hyperlink-card)
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.6.2](https://github.com/halo-dev/plugin-search-widget)
  - [应用市场 1.6.0](https://www.halo.run/store/apps/app-VYJbF)
  - [评论组件 2.4.0](https://github.com/halo-dev/plugin-comment-widget)

### What is the project operation method?

Docker

### What happened?

1. The backup is a single file and has no slice file feature
2. The truth is that backup files are usually very large
3. A backup feature that can't migrate backup files is an anomaly

500MB isn't too big, but it can't be uploaded via the backup feature.
Functional defects take time to fix, are there interim alternatives until then? Like manually placing the zip file in which folder on the server with 1panel?

### Reproduce Steps

1. Download halo backup zip from a server to a personal device
2. Use backup restore function on new server, upload halo backup zip file
3. Upload failed due to big file size, code 413

### Relevant log output

No related logs found

### Additional information

![Image](https://github.com/user-attachments/assets/80536838-f701-4bc6-a6e8-a3cc039e47cd)
![Image](https://github.com/user-attachments/assets/7aa8eac0-2c8c-4ef2-b04e-fd78d331dba6)

**Comment by JohnNiang** [comment]
Hi @MNDIA, thank you for reaching out here!

1. The error may be reported by Nginx or other reverse proxy tools. You can increase `client_max_body_size` configuration if you are using Nginx, see the [common questions](https://docs.halo.run/user-guide/faq/#%E9%99%84%E4%BB%B6%E4%B8%8A%E4%BC%A0%E6%8F%90%E7%A4%BA-413-request-entity-too-large-%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3) for more.
2. We have considered the situation that the backup file is too large to upload, so the PR https://github.com/halo-dev/halo/pull/6486 was proposed and merged. See <https://docs.halo.run/user-guide/backup> for more.

**Comment by MNDIA** [comment]
`client_max_body_size` works well, no need to make a slicing function
