### ISSUE TITLE
支持在上传附件时新建分组

### ISSUE THREAD

**Issue by QingFeng-awa** [halo-dev/halo#6942]
### 你当前使用的版本

2.20.7

### 描述一下此特性

允许在上传时新建附件分组。

### 附加信息

在上传时如果我想要新建一个分组,我就必须要打断当前操作去`附件`页面新建分组,然后再回来上传到新建的分组,非常不方便,故提出此issue。

**Comment by ruibaby** [comment]
可以和存储策略一样。

PR welcome

/good-first-issue
/kind improvement
/area ui

**Comment by LEIYOUSU** [comment]
我想认领这个 issue，我会尽快处理。谢谢！
