### ISSUE TITLE
期望支持在用户详情页面支持变更用户角色及删除用户

### ISSUE THREAD

**Issue by intoyang** [halo-dev/halo#6944]
### 你当前使用的版本

2.19.3

### 描述一下此特性

目前可以通过用户列表变更用户角色。
有时需要点击用户头像进入详情页确认用户信息，希望在此处也能添加一个快速变更角色/删除用户的入口，增加便利。

![Image](https://github.com/user-attachments/assets/276a9008-3038-4d23-83b0-107d90ff14f8)

**Comment by LEIYOUSU** [comment]
我想要认领这个issue，我会尽快处理，谢谢!
