### ISSUE TITLE
附件模块中新建存储策略或者分组应该不存在重复相同的分组或者存储策略

### ISSUE THREAD

**Issue by LEIYOUSU** [halo-dev/halo#6946]
### System information

- 外部访问地址: 
- 启动时间: 2024-10-25 20:11
- 版本: 2.20.0-SNAPSHOT
- 构建时间: 2024-10-25 20:11
- Git Commit: 733679d
- Java: OpenJDK Runtime Environment / 17.0.9+8-b1166.2
- 数据库: H2 / 2.2.224
- 操作系统: Windows 11 / 10.0
- 已激活主题: [Earth 1.9.0](https://github.com/halo-dev/theme-earth)
- 已启动插件:
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.6.2](https://github.com/halo-dev/plugin-search-widget)
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [评论组件 2.4.0](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场 1.4.0](https://www.halo.run/store/apps/app-VYJbF)

### What is the project operation method?

Docker

### What happened?

下图显示为重复创建了两个相同的分组“111”以及相同的存储策略“ces”。个人认为，当重复建组的时候应该提示:该分组已存在，实现不重名机制
![Image](https://github.com/user-attachments/assets/f4a0c499-fd99-4aad-9e1a-8d57af246c68)
![Image](https://github.com/user-attachments/assets/fdbac88b-045d-4297-9a7e-426301412f63)

**Comment by ruibaby** [comment]
可以考虑进行优化，@guqing 是否可以对 Group 的 displayName 添加唯一索引来限制？我的理解是，如果现在添加，以前如果有同名话，可能会创建索引失败，那么就只能在前端创建时查询一次来限制添加重名的分组。

/kind improvement
/good-first-issue

**Comment by guqing** [comment]
> 可以考虑进行优化，@guqing 是否可以对 Group 的 displayName 添加唯一索引来限制？我的理解是，如果现在添加，以前如果有同名话，可能会创建索引失败，那么就只能在前端创建时查询一次来限制添加重名的分组。
> 
> /kind improvement
> /good-first-issue
> 

目前最好是在前端创建时校验一下 加唯一索引可能会导致有些用户无法使用

**Comment by LEIYOUSU** [comment]
我想认领这个 issue，我会尽快处理。谢谢！
