### ISSUE TITLE
发布文章附件优化上传

### ISSUE THREAD

**Issue by acanyo** [halo-dev/halo#6948]
### 你当前使用的版本

 2.20.7专业版

### 描述一下此特性

halo配置了一堆对象存储和图床能否在粘贴图片的时候能默认选择到对象存储或者图床吗，不要默认本地附件不然这样操作起来很麻烦

**Comment by ruibaby** [comment]
https://docs.halo.run/user-guide/settings#文章设置

**Comment by acanyo** [comment]
@ruibaby 这个我知道，就是想默认我ctrl+v的时候上传能否默认如果不可以就算了，麻烦一些

**Comment by ruibaby** [comment]
这里的设置就是针对粘贴和拖拽上传的场景，你可以在这里设置对象存储的存储策略。

![Image](https://github.com/user-attachments/assets/a056b891-c861-4e64-95f6-8bbf8b534bc0)

/kind support
