### ISSUE TITLE
建议为文章图片上传添加水印功能

### ISSUE THREAD

**Issue by Joneeys** [halo-dev/halo#6954]
### Your current Halo version

2.20.7

### Describe this feature

建议在后台添加图片水印设置，是否开启水印设置，水印添加的位置设置等。

功能类似下图

![Image](https://github.com/user-attachments/assets/605c0b8c-412f-4391-b373-8550f3ca8310)

**Comment by ruibaby** [comment]
/triage duplicate

See https://github.com/halo-dev/halo/issues/5426

/close
