### ISSUE TITLE
应用市场认证有问题，安装的主题找不到

### ISSUE THREAD

**Issue by wang0yue** [halo-dev/halo#6955]
### 系统信息

- 外部访问地址: http://localhost:8090
- 启动时间: 2024-10-27 13:52
- 版本: 2.20.7
- 构建时间: 2024-10-23 21:05
- Git Commit: 9599e7c
- Java: IBM Semeru Runtime Open Edition / 21.0.4+7-LTS
- 数据库: PostgreSQL / 17.0
- 操作系统: Linux / 5.15.0-46-generic
- 已激活主题: [Earth 1.11.0](https://github.com/halo-dev/theme-earth)
- 已启动插件:
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.6.2](https://github.com/halo-dev/plugin-search-widget)
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [应用市场 1.6.0](https://www.halo.run/store/apps/app-VYJbF)
  - [评论组件 2.4.0](https://github.com/halo-dev/plugin-comment-widget)

### 使用的哪种方式运行？

Docker

### 发生了什么？

1panel一键安装，应用市场绑定个人令牌后，再刷新进入：
每次进应用市场都要同意条款，应用市场账号绑定显示未绑定但再次绑定显示"检测到有重复的名称，请重命名后重试。"。主题管理安装其他主题后，主机文件有下载的主题，但均不在已安装列表显示，也无法切换

**Comment by wang0yue** [comment]
好像是因为我反代的问题，我开放ip登上去是正常的，用域名就会出现上面的情况
用的1panel一键安装然后只改了一下--halo.external-url=https://mydomain
反代也是默认的，想请教一下该怎么设置能避免上面的情况

**Comment by ruibaby** [comment]
检查是否是 1Panel 的 waf 拦截了部分请求
