### ISSUE TITLE
阻止用户关闭某些通知选项

### ISSUE THREAD

**Issue by QingFeng-awa** [halo-dev/halo#6967]
### 你当前使用的版本

2.20.7

### 描述一下此特性

阻止用户在`/uc`关闭某些通知选项(例如邮箱验证、根据邮件地址重置密码)。

### 附加信息

上述举例到的以及未来可能会新增的敏感操作相关通知不应当被关闭。
建议将这些功能锁定开启状态,不允许用户开关。

**Comment by ruibaby** [comment]
这些似乎关闭也会发通知，应该隐藏掉。

@guqing 帮忙确定一下。

/triage needs-information

**Comment by guqing** [comment]
> 这些似乎关闭也会发通知，应该隐藏掉。
> 
> [@guqing](https://github.com/guqing) 帮忙确定一下。
> 
> /triage needs-information

确实可以隐藏掉不显示
