### ISSUE TITLE
文章管理员（系统保留）弹403: Forbidden

### ISSUE THREAD

**Issue by AR-26710** [halo-dev/halo#6976]
### 系统信息

- 外部访问地址: http://192.168.80.101:8089/
- 启动时间: 2024-10-31 11:31
- 版本: 2.20.7
- 构建时间: 2024-10-23 21:05
- Git Commit: 9599e7c
- Java: IBM Semeru Runtime Open Edition / 21.0.4+7-LTS
- 数据库: MySQL Community Server - GPL / 8.4.2
- 操作系统: Linux / 3.10.0-1160.119.1.el7.x86_64
- 已激活主题: [Joe3 YOUZI 1.1](https://github.com/jiewenhuang/halo-theme-joe3.0)
- 已启动插件:
  - 联系表单 1.0.2
  - [内容格式助手 1.2.0](https://github.com/ruibaby/plugin-content-tools)
  - [OAuth2 认证 1.4.1](https://github.com/halo-sigs/plugin-oauth2)
  - [highlight.js 代码高亮 1.3.2](https://github.com/halo-sigs/plugin-highlightjs)
  - [KaTeX 2.1.0](https://github.com/halo-sigs/plugin-katex)
  - [无色界 1.0.0](https://github.com/guqing/halo-plugin-colorless)
  - [AList 存储库 1.1.0](https://github.com/halo-sigs/plugin-alist)
  - [静态网页服务 1.0.0-alpha.5](https://www.halo.run/store/apps/app-gFkMn)
  - [文章限制阅读 1.4.2](https://www.halo.run/store/apps/app-IzWXo)
  - [Trailing Slash 1.0.0](https://github.com/halo-sigs/plugin-trailing-slash)
  - [图床插件 1.2.1](https://github.com/liuyiwuqing/halo-plugin-picture-bed)
  - [页面静态缓存 1.2.1](https://github.com/halo-sigs/plugin-page-cache)
  - [编辑器超链接卡片 1.1.0](https://github.com/halo-sigs/plugin-editor-hyperlink-card)
  - [对象存储（Amazon S3 协议） 1.12.0](https://github.com/halo-dev/plugin-s3)
  - [Willow Markdown 编辑器 1.0.0](https://github.com/guqing/willow-mde)
  - [瞬间 1.8.0](https://github.com/halo-sigs/plugin-moments)
  - [文本绘图 1.3.0](https://github.com/halo-sigs/plugin-text-diagram)
  - [AI 助手 1.0.0](https://www.halo.run/store/apps/app-riNgb)
  - [live2d 看板娘 1.2.1](https://github.com/LIlGG/plugin-live2d)
  - [Markdown / HTML 内容块 1.2.0](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [文章导入导出 1.2.4](https://jhacker.cn/2023/halo-plugin-export2doc)
  - [图库管理 1.4.0](https://github.com/halo-sigs/plugin-photos)
  - [链接管理 1.5.0](https://github.com/halo-sigs/plugin-links)
  - [Vditor 编辑器 1.8.0](https://github.com/justice2001/halo-plugin-vditor)
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.6.2](https://github.com/halo-dev/plugin-search-widget)
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [评论组件 2.5.0](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场 1.7.0](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker

### 发生了什么？

当用户分配为文章管理员（系统保留）时，创建文章、标签、分类，文章设置，会弹403: Forbidden。

分类
![Image](https://github.com/user-attachments/assets/4fba956f-6498-4d7c-b5e5-2f5d01d5e903)

标签
![Image](https://github.com/user-attachments/assets/cae32d72-2a8d-4d92-908c-6eee409234e7)

创建文章
![Image](https://github.com/user-attachments/assets/878b42a8-e700-4f4a-b283-d7f5168987aa)

文章设置
![Image](https://github.com/user-attachments/assets/9c41bf8c-6b76-41bb-bdec-da9fda4ee2bd)

### 复现步骤

为用户分配文章管理员的角色

创建文章、标签、分类，文章设置

### 相关日志输出

暂无日志

**Comment by ruibaby** [comment]
没有复现这个问题，建议先检查是否是被前置代理拦截。

/triage needs-information

**Comment by AR-26710** [comment]
> 没有复现这个问题，建议先检查是否是被前置代理拦截。
> 
> /triage needs-information

重装新的halo测试发现确实没问题.

使用原有备份后才有问题。

**Comment by AR-26710** [comment]
是不是插件问题哦~
![Image](https://github.com/user-attachments/assets/67feed90-6e4b-4e55-a474-a2c3601ed18b)

**Comment by AR-26710** [comment]
经测试确实是插件问题
是图床插件的问题
![Image](https://github.com/user-attachments/assets/93f69f4b-2300-4f15-bb07-0b76289e93b1)

**Comment by ruibaby** [comment]
> 经测试确实是插件问题 是图床插件的问题 ![Image](https://github.com/user-attachments/assets/93f69f4b-2300-4f15-bb07-0b76289e93b1)

建议向插件反馈，修复一下这个问题。
