### ISSUE TITLE
V2.20.8附件上传文件显示成功，但显示时加载异常

### ISSUE THREAD

**Issue by wenjing-xin** [halo-dev/halo#6977]
### 系统信息

- 外部访问地址: https://blog.webjing.cn
- 启动时间: 2024-10-31 12:14
- 版本: 2.20.8
- 构建时间: 2024-10-30 16:36
- Git Commit: a61a2b3
- Java: IBM Semeru Runtime Open Edition / 21.0.4+7-LTS
- 数据库: PostgreSQL / 16.4
- 操作系统: Linux / 3.10.0-1160.114.2.el7.x86_64
- 已激活主题: [Hao 1.6.7](https://githubfast.com/liuzhihang/halo-theme-hao)
- 已启动插件:
  - [友链自助提交插件 2.0.4](https://github.com/liuyiwuqing/halo-plugin-links-submit)
  - [链接安全跳转中台 1.6.1](https://github.com/wenjing-xin/plugins-links-security-detect)
  - [Data Studio（数据工厂） 1.0.0-alpha.2](https://github.com/halo-sigs/plugin-data-studio)
  - [链接管理 1.5.0](https://github.com/halo-sigs/plugin-links)
  - [Tools工具箱 1.5.0](https://github.com/liuyiwuqing/halo-plugin-tools.git)
  - [静态网页服务 1.0.0-alpha.5](https://www.halo.run/store/apps/app-gFkMn)
  - [TinyTale小程序设置 1.0.5](https://github.com/jiewenhuang/halo-plugin-TinyTale)
  - [SEO 工具集 1.1.0](https://www.halo.run/store/apps/app-FNGbT)
  - [增强备份（Backup IMproved） 1.1.1](https://www.halo.run/store/apps/app-dHakX)
  - [微信公众号发布 1.3.1](https://www.halo.run/store/apps/app-Dtuoa)
  - [OAuth2 认证 1.4.2](https://github.com/halo-sigs/plugin-oauth2)
  - [对象存储（Amazon S3 协议） 1.12.0](https://github.com/halo-dev/plugin-s3)
  - [Docsme 1.0.0-alpha.9](https://www.halo.run/store/apps/app-yffxw)
  - [瞬间 1.8.0](https://github.com/halo-sigs/plugin-moments)
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.6.2](https://github.com/halo-dev/plugin-search-widget)
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [应用市场 1.7.0](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker

### 发生了什么？

无论是本地存储策略上传还是oss存储策略上传，显示上传成功，但是图片加载异常，发现 img 的 src 属性为 undfiend

### 复现步骤

![Image](https://github.com/user-attachments/assets/bd93fc1d-e539-4489-8095-c52338746ab6)
![Image](https://github.com/user-attachments/assets/7baa9dc5-4b59-4fe3-be84-2989ae4a07e2)
![Image](https://github.com/user-attachments/assets/ec72ca8c-4e09-44b5-bf50-7b4b13d9366c)
![Image](https://github.com/user-attachments/assets/96731b52-948b-4db8-862f-b1694eb7d72a)

**Comment by ruibaby** [comment]
ping @halo-dev/sig-halo

**Comment by JohnNiang** [comment]
Hi @wenjing-xin , thank you for reaching out here!

建议重新复现之后，检查一下 Halo 的日志是否有错误，如果有的话，建议上传到这里给我们排查一下。

/triage needs-information

**Comment by wanna280** [comment]
遇到了同样的问题，通过Docker部署的，没找到Error日志，我发现是阿里云OSS插件的问题，换新的S3插件之后上传文件正常。

**Comment by ruibaby** [comment]
> 遇到了同样的问题，使用K8S通过容器部署的，没找到Halo的Error日志，在我的Halo服务上，我发现是阿里云OSS插件的问题，换新的S3插件之后上传文件正常，具体原因未知。

真实原因就是阿里云 OSS 插件不维护了，这个在仓库和应用市场都有归档说明。

**Comment by wenjing-xin** [comment]
> 遇到了同样的问题，使用K8S通过容器部署的，没找到Halo的Error日志，在我的Halo服务上，我发现是阿里云OSS插件的问题，换新的S3插件之后上传文件正常，具体原因未知。

我使用的就是

**Comment by wenjing-xin** [comment]
> > 遇到了同样的问题，使用K8S通过容器部署的，没找到Halo的Error日志，在我的Halo服务上，我发现是阿里云OSS插件的问题，换新的S3插件之后上传文件正常，具体原因未知。
> 
> 真实原因就是阿里云 OSS 插件不维护了，有些问题并没有适配新版本 Halo，这个在仓库和应用市场都有归档说明。

我使用就是新的s3插件，这个图片加载异常我后边没复线出来。日志也找不到，但是此后上传图片是正常的，不知道是什么原因。但总归之后没有遇到此类的问题😁

**Comment by wanna280** [comment]
> > 遇到了同样的问题，使用K8S通过容器部署的，没找到Halo的Error日志，在我的Halo服务上，我发现是阿里云OSS插件的问题，换新的S3插件之后上传文件正常，具体原因未知。
> 
> 真实原因就是阿里云 OSS 插件不维护了，有些问题并没有适配新版本 Halo，这个在仓库和应用市场都有归档说明。

看起来确实是这样，我之前用的是2.18的版本，阿里云OSS插件能正常用，最近升级迁移到K8S升级到了2.20，遇到了这个问题。

**Comment by JohnNiang** [comment]
重点需要关注一下 `status.permalink` 属性的值。
