### ISSUE TITLE
新建文章浏览量以及版本

### ISSUE THREAD

**Issue by yovvis** [halo-dev/halo#6980]
### 你当前使用的版本

 2.20.8

### 描述一下此特性

新建的一篇文章，他的版本状态是（草稿，基础），并没有发布。是否可以在保存的时候不叠加version，预览的时候不加visit。

### 附加信息

![文章版本](https://github.com/user-attachments/assets/83bb7e06-dca4-4b54-96cc-adb861165904)
![浏览量](https://github.com/user-attachments/assets/439b1a62-d194-4594-ba06-3e5c40ffe69b)

**Comment by ruibaby** [comment]
/triage duplicate

See https://github.com/halo-dev/halo/issues/1763

/close
