### ISSUE TITLE
使用HTML邮件取代传统邮件

### ISSUE THREAD

**Issue by QingFeng-awa** [halo-dev/halo#6985]
### 你当前使用的版本

2.20.8Pro

### 描述一下此特性

使用HTML邮件取代传统邮件以达到美观&现代化的目的。

**Comment by guqing** [comment]
目前邮件就是 HTML 的只不过样式是简单的这是为了能普遍适用，就像 GitHub 的邮件一样，如果你想要花里花哨的模板可以在插件或主题中提供以替换默认模板:
- 参考 [模板渲染与发送](https://docs.halo.run/developer-guide/plugin/api-reference/server/notification#%E6%A8%A1%E6%9D%BF%E6%B8%B2%E6%9F%93%E4%B8%8E%E5%8F%91%E9%80%81)
- Halo 内置通知模板参考 [https://github.com/halo-dev/halo/blob/main/application/src/main/resources/extensions/notification-templates.yaml]
在插件(src/main/resources/extensions)或主题(主题根目录)中提供同样的模板 YAML 将内容自定义即可
