### ISSUE TITLE
求助：halo反向代理后，前台无样式，请求没有带上固定uri

### ISSUE THREAD

**Issue by aojunhua117** [halo-dev/halo#6986]
### System information

docker-compose中已配置 - --halo.external-url=http://192.168.80.61:80/halo/ ，部署后通过端口访问没问题，通过ip/halo的方式访问，前台路由没有带上halo
![Image](https://github.com/user-attachments/assets/184c0fe0-aa21-42ac-905a-eb9a4fca58f4)

docker-compose配置：

  halo:
    image: registry.fit2cloud.com/halo/halo:2.20
    restart: on-failure:3
    depends_on:
      halodb:
        condition: service_healthy
    networks:
      halo_network:
    volumes:
      - ./halo2:/root/.halo2
    ports:
      - "18594:8090"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/actuator/health/readiness"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    environment:
      # JVM 参数，默认为 -Xmx256m -Xms256m，可以根据实际情况做调整，置空表示不添加 JVM 参数
      - JVM_OPTS=-Xmx256m -Xms256m
    command:
      - --spring.r2dbc.url=r2dbc:pool:mysql://halodb:3306/halo
      - --spring.r2dbc.username=root
      # MySQL 的密码，请保证与下方 MYSQL_ROOT_PASSWORD 的变量值一致。
      - --spring.r2dbc.password=123456
      - --spring.sql.init.platform=mysql
      # 外部访问地址，请根据实际需要修改
      - --halo.external-url=http://192.168.80.61:80/halo/

nginx配置：
    upstream halo{
        server 127.0.0.1:18594;
    }

  location /halo {
      proxy_pass http://halo;
      proxy_set_header HOST $host;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      # the max size of file to upload
      allow 192.168.0.0/16;
      deny all;
  }

### What is the project operation method?

Docker Compose

### What happened?

docker-compose中已配置 - --halo.external-url=http://192.168.80.61:80/halo/ ，部署后通过端口访问没问题，通过ip/halo的方式访问，前台路由没有带上halo
![Image](https://github.com/user-attachments/assets/184c0fe0-aa21-42ac-905a-eb9a4fca58f4)

**Comment by JohnNiang** [comment]
HI @aojunhua117 , thank you for reaching out here!

目前，Halo 暂时没有测试过配置 `context-path`（如 `/halo`）的场景的兼容性。

/triage duplicate

Close in favor of <https://github.com/halo-dev/halo/issues/5204>.

/close

**Comment by Johnny-ZTSD** [comment]
是否可以解决此特性呢？前端和后端都支持配置 `context-path`？
