### ISSUE TITLE
日志查看功能

### ISSUE THREAD

**Issue by QingFeng-awa** [halo-dev/halo#6988]
### 你当前使用的版本

2.20.8

### 描述一下此特性

新增`日志`模块,记录所有用户在console中的操作并允许用户查看。
类似于1Panel的`日志审计`。

### 附加信息

因为docsme插件的开发进度缓慢,又因Halo不好做多站点互通,我不得不给多位用户超级管理员权限。
但给超级管理员毕竟还是有风险,我怕他们乱搞我又不知道,而这个issue提出的日志模块可以让我方便的查看对应用户都干了什么,故提出此issue。

> *顺便在这个issue催催docsme更新,照这速度你得发50个alpha,正式版26年才能做出来。*

**Comment by ruibaby** [comment]
/triage duplicate

See https://github.com/halo-dev/halo/issues/5155

请不要重复提交 issue。

> 顺便在这个issue催催docsme更新,照这速度你得发50个alpha,正式版26年才能做出来。

🤷
