### ISSUE TITLE
mermaid在前台无法被解析

### ISSUE THREAD

**Issue by ccfuncy** [halo-dev/halo#699]
## 我的环境
Server 版本：1.2.0
Admin 版本：1.2.0
数据库：H2
运行模式：production
UA 信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36

---

## 错误日志
无错误日志

---

## 期望行为
![image](https://user-images.githubusercontent.com/35862080/77224009-8776c700-6b9c-11ea-87fc-62144b87703e.png)

## 当前行为
![image](https://user-images.githubusercontent.com/35862080/77224017-9bbac400-6b9c-11ea-986b-0fdb67df98a1.png)
mermaid可以在写文章预览处解析，一旦发布之后，从博客进入后无法解析

**Comment by ruibaby** [comment]
先参考这个试试：

https://halo.run/archives/use-markdown.html#%E5%9B%BE%E8%A1%A8

**Comment by ccfuncy** [comment]
抱歉，是我没有仔细阅读使用指南，问题已解决，谢谢！
