### ISSUE TITLE
SVG图片缓存问题

### ISSUE THREAD

**Issue by QingFeng-awa** [halo-dev/halo#6993]
### 系统信息

- 外部访问地址: https://www.xtreme.net.cn
- 启动时间: 2024-10-31 07:18
- 版本: 2.20.8
- 构建时间: 2024-10-30 16:36
- Git Commit: a61a2b3
- Java: IBM Semeru Runtime Open Edition / 21.0.4+7-LTS
- 数据库: MySQL Community Server - GPL / 8.4.3
- 操作系统: Linux / 6.1.0-25-amd64
- 已激活主题: [Apex 企业官网主题 1.3.0](https://www.halo.run/store/apps/app-OTFHl)
- 已启动插件:
  - [静态网页服务 1.0.0-alpha.5](https://www.halo.run/store/apps/app-gFkMn)
  - [联系表单 1.1.0](https://www.halo.run/store/apps/app-gSebd)
  - [社交 IAM 认证 1.4.0-rc.2](https://www.halo.run/store/apps/app-IXZkJ)
  - [页面静态缓存 1.2.1](https://github.com/halo-sigs/plugin-page-cache)
  - [文章限制阅读 1.4.3](https://www.halo.run/store/apps/app-IzWXo)
  - [Trailing Slash 1.0.0](https://github.com/halo-sigs/plugin-trailing-slash)
  - [lightgallery.js 灯箱 1.2.1](https://github.com/halo-sigs/plugin-lightgallery)
  - [编辑器超链接卡片 1.1.0](https://github.com/halo-sigs/plugin-editor-hyperlink-card)
  - [站点推送插件 1.5.2](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [Docsme 1.0.0-alpha.9](https://www.halo.run/store/apps/app-yffxw)
  - [OAuth2 认证 1.4.2](https://github.com/halo-sigs/plugin-oauth2)
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.6.2](https://github.com/halo-dev/plugin-search-widget)
  - [应用市场 1.7.0](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker

### 发生了什么？

上传SVG图片删除后,上传另一个同名的SVG图片会因缓存问题显示时为已删除的SVG图片。

### 复现步骤

https://pan.xtreme.net.cn/f/GzUA/2024-11-02_21-08-55.mp4

**Comment by ruibaby** [comment]
请在提交 issue 前，至少先搜索是否有相同 issue。

- https://github.com/halo-dev/halo/issues/5131
- https://github.com/halo-dev/halo/issues/4283

BTW，如果你经常出现同名资源的缓存问题，建议自行将 Cache-Control 设置为 no-cache，这样会强行经过服务器进行验证（协商缓存验证）。

设置方式：https://docs.halo.run/getting-started/install/config#:~:text=spring.web.resources.cache.cachecontrol.no%2Dcache

/close
/triage duplicate
