### ISSUE TITLE
部分主题是否有泄漏数据库密码的可能

### ISSUE THREAD

**Issue by HHHHHHHH88** [halo-dev/halo#701]
数据库被截取，只有halo库未被劫持

**Comment by ruibaby** [comment]
没有。 未被劫持什么意思。

**Comment by HHHHHHHH88** [comment]
今天被勒索病毒[cleverhorse@protonmail.com].actin搞蒙了啊

**Comment by HHHHHHHH88** [comment]
心态炸了

**Comment by JohnNiang** [comment]
请问你的服务器密码以及数据库密码强度如何？

**Comment by ruibaby** [comment]
> 数据库被截取，只有halo库未被劫持

这是 halo的库被劫持和还是没有？

**Comment by HHHHHHHH88** [comment]
可能很早之前就被劫持了    然后今天登陆其他应用登陆不上了

**Comment by HHHHHHHH88** [comment]
不瞒大家 密码123456。。。。。
