### ISSUE TITLE
feat: 支持设置 context path

### ISSUE THREAD

**Issue by LarryDpk** [halo-dev/halo#702]
## Overview

As I have other services on my servers, so I don't want to make my domain(e.g. `xxx.com`) as the blog web context root path. I want to set it as `xxx.com/blog`.
But after I set like that, many links became invalid.
Such as:
文章归档：`xxx.com/archives` but not `xxx.com/blog/archives`
默认分类：`xxx.com/categories/default` but not `xxx.com/blog/categories/default`
关于页面：`xxx.com/s/about` but not` xxx.com/blog/s/about`
...
...

I wonder if you can impliment this, so we can use 'xxx.com/blog` pointing to the halo blog.

**Comment by ruibaby** [comment]
你好，感谢你的反馈，已经接收到了你的意思。但是目前应该很少人有这种需要，所以开发可能会延后。 但这功能肯定会做。

**Comment by LarryDpk** [comment]
好的，回复这么迅速，点赞，支持Halo！

**Comment by ruibaby** [comment]
> 好的，回复这么迅速，点赞，支持Halo！

其实你目前可以用子域解决你的需求。

**Comment by LarryDpk** [comment]
> > 好的，回复这么迅速，点赞，支持Halo！
> 
> 其实你目前可以用子域解决你的需求。

嗯，是的。我想过子域名这个方案。但提一下这种需求。
也想过直接用主域名用于halo，其它服务可以用重定向的方式。
xxx.com --> halo
xxx.com/order --> order
xxx.com/finance --> finance

你先忙其它feature，我自己捣鼓一下先，哈哈。

**Comment by ruibaby** [comment]
@LarryDpk 看你怎么弄吧，为了健壮性，context path肯定是要支持的。

**Comment by ACEGuiPeng** [comment]
你好 请问如果我要自己改源码 可以怎么先临时解决这个问题？

**Comment by ruibaby** [comment]
暂时不再考虑支持子域名。

/close
