### ISSUE TITLE
md编写文章，目录不能正确地导航

### ISSUE THREAD

**Issue by shiningrise** [halo-dev/halo#7025]
### 前置条件

- [x] 已经在 [issues](https://github.com/halo-dev/halo/issues) 列表中搜索了相关问题。
- [x] 这是 Halo 项目本身存在的问题，如果是非项目本身的问题（如：安装部署问题），建议在 [Discussions](https://github.com/halo-dev/halo/discussions) 提交。
- [x] 已经尝试过停用所有的插件，排除是插件导致的问题。
- [x] 如果是插件和主题的问题，请在对应的插件和主题仓库提交。

### 系统信息

https://wxy.vip/archives/abpyuan-ma-fen-xi-zhi-abpben-di-hua

### 使用的哪种方式运行？

Docker

### 发生了什么？

md编写文章，目录不能正确地导航![Image](https://github.com/user-attachments/assets/6ddd88f9-191f-460a-a030-2730d1efb46f)

### 复现步骤

https://wxy.vip/archives/abpyuan-ma-fen-xi-zhi-abpben-di-hua

### 相关日志输出

```shell

```

**Comment by ruibaby** [comment]
原因是没有为 heading 添加 id，建议向你所使用的 md 插件反馈。

![Image](https://github.com/user-attachments/assets/67730ace-886b-4a27-a490-0e7b8b5cdaa0)

/kind support
