### ISSUE TITLE
默认编辑器多个空格只显示一个

### ISSUE THREAD

**Issue by dqy0628** [halo-dev/halo#7026]
### 前置条件

- [x] 已经在 [issues](https://github.com/halo-dev/halo/issues) 列表中搜索了相关问题。
- [x] 这是 Halo 项目本身存在的问题，如果是非项目本身的问题（如：安装部署问题），建议在 [Discussions](https://github.com/halo-dev/halo/discussions) 提交。
- [x] 已经尝试过停用所有的插件，排除是插件导致的问题。
- [x] 如果是插件和主题的问题，请在对应的插件和主题仓库提交。

### 系统信息

- 版本：2.20.9

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

多个空格只显示一个

### 复现步骤

创建一个文章，随便输入几个字符，中间输入多个空格

### 相关日志输出

```shell

```

**Comment by ruibaby** [comment]
/triage duplicate

相同问题：https://github.com/halo-dev/halo/issues/3515

其实你在 GitHub issue 回复框输入多个空格也是一样的。
