### ISSUE TITLE
最新开发版admin首页仪表盘文章数量显示错误

### ISSUE THREAD

**Issue by MrChen00** [halo-dev/halo#703]
![image](https://user-images.githubusercontent.com/51355342/77243383-75506380-6c44-11ea-8da6-03916b84cdde.png)
![image](https://user-images.githubusercontent.com/51355342/77243388-80a38f00-6c44-11ea-927b-98451c7baa3f.png)
![image](https://user-images.githubusercontent.com/51355342/77243399-9a44d680-6c44-11ea-9983-377c4d8d2975.png)
![image](https://user-images.githubusercontent.com/51355342/77243404-a2047b00-6c44-11ea-95b0-0759d98023da.png)
首页仪表盘显示的文章数量会比真实文章数量+1。该bug在最新开发版本上发现

**Comment by ruibaby** [comment]
好的，感谢反馈。

**Comment by ruibaby** [comment]
是因为把自定义页面也加进去了，已修复。
