### ISSUE TITLE
应用市场账号绑定异常

### ISSUE THREAD

**Issue by AWicls** [halo-dev/halo#7030]
### 前置条件

- [x] 已经在 [issues](https://github.com/halo-dev/halo/issues) 列表中搜索了相关问题。
- [x] 这是 Halo 项目本身存在的问题，如果是非项目本身的问题（如：安装部署问题），建议在 [Discussions](https://github.com/halo-dev/halo/discussions) 提交。
- [x] 已经尝试过停用所有的插件，排除是插件导致的问题。
- [x] 如果是插件和主题的问题，请在对应的插件和主题仓库提交。

### 系统信息

- 外部访问地址: https://www.awic.top:8443/
- 启动时间: 2024-11-13 12:51
- 版本: 2.20.9
- 构建时间: 2024-11-12 06:47
- Git Commit: ed5afb2
- Java: IBM Semeru Runtime Open Edition / 21.0.4+7-LTS
- 数据库: PostgreSQL / 16.4
- 操作系统: Linux / 6.1.0-26-amd64
- 已激活主题: [Walker 1.12.1](https://www.halo.run/store/apps/app-GHgAR)
- 已启动插件:
  - [应用市场 1.8.0](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker

### 发生了什么？

问题: `Halo`更新`2.20.8`到`2.20.9`之后就一直应用市场账号绑定异常
自排查: `1panel_waf`未拦截, 日志粗看全`INFO`

### 相关日志输出

```shell

```

**Comment by JohnNiang** [comment]
Hi @AWicls , thank you for reaching out here!

需要提供详细的异常信息，不然没有办法判断到底发生了什么。

> 另外，建议检查一下当前服务器的时间是否同步。

/triage needs-information

**Comment by AWicls** [comment]
莫名奇妙没事了,无法复现
