### ISSUE TITLE
${os} 参数识别错误导致邮件中通知为 Unknown

### ISSUE THREAD

**Issue by Anyexyz** [halo-dev/halo#7039]
### 前置条件

- [x] 已经在 [issues](https://github.com/halo-dev/halo/issues) 列表中搜索了相关问题。
- [x] 这是 Halo 项目本身存在的问题，如果是非项目本身的问题（如：安装部署问题），建议在 [Discussions](https://github.com/halo-dev/halo/discussions) 提交。
- [x] 已经尝试过停用所有的插件，排除是插件导致的问题。
- [x] 如果是插件和主题的问题，请在对应的插件和主题仓库提交。

### 系统信息

- 外部访问地址: https://www.anye.xyz
- 启动时间: 2024-11-14 00:20
- 版本: 2.20.9
- 构建时间: 2024-11-12 06:47
- Git Commit: ed5afb2
- Java: IBM Semeru Runtime Open Edition / 21.0.4+7-LTS
- 数据库: PostgreSQL / 16.4
- 操作系统: Linux / 5.15.0-124-generic
- 已激活主题: [Earth-Fixed 1.11.1](https://github.com/Anyexyz/theme-earth_fixed)
- 已启动插件:
  - [Image Stream 1.0.0-rc.1](https://github.com/halo-sigs/plugin-image-stream)
  - [内容格式助手 1.2.0](https://github.com/ruibaby/plugin-content-tools)
  - [OAuth2 认证 1.5.0-rc.1](https://github.com/halo-sigs/plugin-oauth2)
  - [社交 IAM 认证 1.4.0-rc.1](https://www.halo.run/store/apps/app-IXZkJ)
  - [对象存储（Amazon S3 协议） 1.12.0](https://github.com/halo-dev/plugin-s3)
  - [通知我 1.1.0](https://github.com/monyuan/notify-me)
  - [KaTeX 2.1.0](https://github.com/halo-sigs/plugin-katex)
  - [Metrics Graph 1.1.0](https://github.com/guqing/plugin-metrics-graph)
  - [Markdown / HTML 内容块 1.2.0](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [增强备份（Backup IMproved） 1.2.0](https://www.halo.run/store/apps/app-dHakX)
  - [联系表单 1.1.0](https://www.halo.run/store/apps/app-gSebd)
  - [微信公众号发布 1.3.1](https://www.halo.run/store/apps/app-Dtuoa)
  - [AI 助手 1.1.2](https://www.halo.run/store/apps/app-riNgb)
  - [Data Studio（数据工厂） 1.0.0-alpha.2](https://github.com/halo-sigs/plugin-data-studio)
  - [编辑器超链接卡片 1.3.0](https://github.com/halo-sigs/plugin-editor-hyperlink-card)
  - [lightgallery.js 灯箱 1.2.1](https://github.com/halo-sigs/plugin-lightgallery)
  - [Umami 1.4.0](https://github.com/halo-sigs/plugin-umami)
  - [无色界 1.0.0](https://github.com/guqing/halo-plugin-colorless)
  - [Docsme 1.0.0-alpha.10](https://www.halo.run/store/apps/app-yffxw)
  - [文本绘图 1.3.0](https://github.com/halo-sigs/plugin-text-diagram)
  - [图库管理 1.4.0](https://github.com/halo-sigs/plugin-photos)
  - [静态网页服务 1.0.0-alpha.5](https://www.halo.run/store/apps/app-gFkMn)
  - [链上好文 1.0.1](https://github.com/guqing/plugin-share-post-via-link)
  - [链接管理 1.5.0](https://github.com/halo-sigs/plugin-links)
  - [文章限制阅读 Pro 1.4.3](https://www.halo.run/store/apps/app-TzRqd)
  - [highlight.js 代码高亮 1.3.2](https://github.com/halo-sigs/plugin-highlightjs)
  - [瞬间 1.8.0](https://github.com/halo-sigs/plugin-moments)
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.6.2](https://github.com/halo-dev/plugin-search-widget)
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [评论组件 2.5.1](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场 1.8.0](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

Halo 无法识别 OpenHarmony 设备的 `user-agent`，导致在 `application/src/main/resources/extensions/notification-templates.yaml` 的 `你的 [(${site.title})] 账号被用于在 [(${os})] 上登录` 中的 `[(${os})]` 被填充为 `Unknown`。
参考 UA：`Mozilla/5.0 (Phone; OpenHarmony 5.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 ArkWeb/4.1.6.1 Mobile HuaweiBrowser/5.0.4.300`

**Comment by JohnNiang** [comment]
/good-first-issue

似乎只需要适配一下下面这个方法就行了。

https://github.com/halo-dev/halo/blob/06f3c289e8bae3c958fc4e4935ac4739aff1ac9c/application/src/main/java/run/halo/app/security/device/DeviceServiceImpl.java#L231
