### ISSUE TITLE
“菜单” 支持 i18n

### ISSUE THREAD

**Issue by HowieHz** [halo-dev/halo#7043]
### 前置条件

- [x] 已经在 [Issues](https://github.com/halo-dev/halo/issues) 列表中搜索了相关问题。
- [x] 这是和 Halo 相关的特性，如果是非项目本身的问题，建议在 [Discussions](https://github.com/halo-dev/halo/discussions) 提交。
- [x] 如果是插件和主题特性建议，请在对应的插件和主题仓库提交。

### 你当前使用的版本

2.20.9

### 描述一下此特性

/console/menus 页面 菜单项支持多语言设置
![Image](https://github.com/user-attachments/assets/35f42f24-c6a7-4b87-9b3d-184d9f086005)
![Image](https://github.com/user-attachments/assets/e2553da2-3573-479b-ade8-89a62f90954a)
设想中的实现：能支持设置不同语言以及默认项，如同 https://github.com/halo-dev/rfcs/tree/main/theme#%E4%B8%BB%E9%A2%98%E5%9B%BD%E9%99%85%E5%8C%96

**Comment by ruibaby** [comment]
Halo 将不再考虑支持多语言内容管理，详见：https://github.com/halo-dev/rfcs/issues/6#issuecomment-2481252386

/triage duplicate

**Comment by HowieHz** [comment]
主题可自行支持，等待发版 v1.10.0 https://github.com/HowieHz/halo-theme-higan-hz/releases/tag/v1.10.0-Beta.2
