### ISSUE TITLE
目录总是跳转到文章顶部

### ISSUE THREAD

**Issue by hdd1024** [halo-dev/halo#7046]
### 前置条件

- [x] 已经在 [issues](https://github.com/halo-dev/halo/issues) 列表中搜索了相关问题。
- [x] 这是 Halo 项目本身存在的问题，如果是非项目本身的问题（如：安装部署问题），建议在 [Discussions](https://github.com/halo-dev/halo/discussions) 提交。
- [x] 已经尝试过停用所有的插件，排除是插件导致的问题。
- [x] 如果是插件和主题的问题，请在对应的插件和主题仓库提交。

### 系统信息

- 外部访问地址: http://localhost:8090
- 启动时间: 2024-11-18 12:02
- 版本: 2.20.9
- 构建时间: 2024-11-12 06:47
- Git Commit: ed5afb2
- Java: IBM Semeru Runtime Open Edition / 21.0.4+7-LTS
- 数据库: MySQL Community Server - GPL / 8.4.3
- 操作系统: Linux / 6.8.4-2-pve
- 已激活主题: [Hao 1.6.0](https://github.com/chengzhongxue/halo-theme-hao)
- 已启动插件:
  - [Vditor 编辑器 1.8.0](https://github.com/justice2001/halo-plugin-vditor)
  - [highlight.js 代码高亮 1.3.2](https://github.com/halo-sigs/plugin-highlightjs)
  - [Metrics Graph 1.1.0](https://github.com/guqing/plugin-metrics-graph)
  - [内容格式助手 1.2.0](https://github.com/ruibaby/plugin-content-tools)
  - [编辑器超链接卡片 1.3.0](https://github.com/halo-sigs/plugin-editor-hyperlink-card)
  - [Image Stream 1.0.0-rc.1](https://github.com/halo-sigs/plugin-image-stream)
  - [live2d 看板娘 1.2.1](https://github.com/LIlGG/plugin-live2d)
  - [搜索组件 1.6.2](https://github.com/halo-dev/plugin-search-widget)
  - [评论组件 2.5.1](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场 1.8.0](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Source Code

### 发生了什么？

通过思源笔记发布到halo，发现点击目录中的条目总是跳转顶部。开始以为是思源笔记插件问题，就将笔记发布到语雀，在语雀中的笔记目录可以正确跳转到笔记位置。

### 相关日志输出

```shell

```

**Comment by ruibaby** [comment]
相同问题：https://github.com/halo-dev/halo/issues/7025

本质原因是渲染 Markdown 为 HTML 时没有向 heading 添加 id，Halo 本身并不提供生成 TOC 的功能，建议：

1. 向上游反馈，支持渲染 Markdown 的时候为 heading 添加 id。
2. 向你所使用的主题反馈，生成 TOC 时为 heading 添加 id。

/triage duplicate

**Comment by hdd1024** [comment]
> 相同问题：[#7025](https://github.com/halo-dev/halo/issues/7025)
> 
> 本质原因是渲染 Markdown 为 HTML 时没有向 heading 添加 id，Halo 本身并不提供生成 TOC 的功能，建议：
> 
> 1. 向上游反馈，支持渲染 Markdown 的时候为 heading 添加 id。
> 2. 向你所使用的主题反馈，生成 TOC 时为 heading 添加 id。
> 
> /triage duplicate

补充：
1. 应该和主题没关系，我将主题改为halo官方主题，点击目录中的条目也是会跳转到文章头部。
2. 我用思源笔记发布插件发布到文章halo，发布为html和markdown格式都试了，两种格式发布到hado点击目录条目都会跳转到文章顶部

**Comment by ruibaby** [comment]
上面说的很清楚了，就是 heading 标签没有在发布的时候包含 id，Halo 本身也不支持生成 TOC，所以完全是看主题能不能够支持在没有 id 的情况正确跳转。

> halo官方主题，点击目录中的条目也是会跳转到文章头部。

因为默认主题的 TOC 生成插件也不支持在没有 id 的情况正确跳转。如果你仍然认为这是 Halo 需要改动的，你可以用默认编辑器发布之后在浏览器审查元素中看看 h1、h2 是否带了 id，以及和你用 **思源笔记发布插件** 发布的做对比。

**Comment by hdd1024** [comment]
嗯嗯，那我想思源笔记发布插件作者反馈这个问题。

**Comment by terwer** [comment]
思源笔记发布插件 `v1.25.0` 已修复此问题。
