### ISSUE TITLE
主题语言资源在更新主题后存在缓存

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#7056]
### 前置条件

- [x] 已经在 [issues](https://github.com/halo-dev/halo/issues) 列表中搜索了相关问题。
- [x] 这是 Halo 项目本身存在的问题，如果是非项目本身的问题（如：安装部署问题），建议在 [Discussions](https://github.com/halo-dev/halo/discussions) 提交。
- [x] 已经尝试过停用所有的插件，排除是插件导致的问题。
- [x] 如果是插件和主题的问题，请在对应的插件和主题仓库提交。

### 系统信息

- 外部访问地址: https://demo.halo.run
- 启动时间: 2024-11-19 22:31
- 版本: 2.20.9
- 构建时间: 2024-11-12 06:43
- Git Commit: 06f3c28
- Java: IBM Semeru Runtime Open Edition / 21.0.4+7-LTS
- 数据库: PostgreSQL / 15.2 (Debian 15.2-1.pgdg110+1)
- 操作系统: Linux / 5.15.0-88-generic
- 已激活主题: [Apex 企业官网主题 1.3.0](https://www.halo.run/store/apps/app-OTFHl)
- 已启动插件:
  - [内容格式助手 1.2.0](https://github.com/ruibaby/plugin-content-tools)
  - [编辑器超链接卡片 1.3.0](https://github.com/halo-sigs/plugin-editor-hyperlink-card)
  - [Metrics Graph 1.1.0](https://github.com/guqing/plugin-metrics-graph)
  - [Vditor 编辑器 1.8.0](https://github.com/justice2001/halo-plugin-vditor)
  - [文本绘图 1.3.0](https://github.com/halo-sigs/plugin-text-diagram)
  - [Docsme 1.0.0-alpha.10](https://www.halo.run/store/apps/app-yffxw)
  - [Markdown / HTML 内容块 1.2.0](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [联系表单 1.1.0](https://www.halo.run/store/apps/app-gSebd)
  - [文章限制阅读 Pro 1.4.3](https://www.halo.run/store/apps/app-TzRqd)
  - [应用市场 1.8.0](https://www.halo.run/store/apps/app-VYJbF)
  - [KaTeX 2.1.0](https://github.com/halo-sigs/plugin-katex)
  - [ByteMD 1.4.0](https://github.com/ruibaby/plugin-bytemd)
  - [图库管理 1.4.0](https://github.com/halo-sigs/plugin-photos)
  - [瞬间 1.8.0](https://github.com/halo-sigs/plugin-moments)
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [站点迁移 1.7.0](https://github.com/halo-sigs/plugin-migrate)
  - [链接管理 1.5.0](https://github.com/halo-sigs/plugin-links)
  - [评论组件 2.5.1](https://github.com/halo-dev/plugin-comment-widget)
  - [OAuth2 认证 1.4.2](https://github.com/halo-sigs/plugin-oauth2)
  - [对象存储（Amazon S3 协议） 1.12.0](https://github.com/halo-dev/plugin-s3)
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [StackEdit 1.1.1](https://github.com/halo-sigs/plugin-stackedit)
  - [搜索组件 1.6.2](https://github.com/halo-dev/plugin-search-widget)
  - [Unsplash 1.2.1](https://github.com/halo-sigs/plugin-unsplash)
  - [highlight.js 代码高亮 1.3.2](https://github.com/halo-sigs/plugin-highlightjs)
  - [lightgallery.js 灯箱 1.2.1](https://github.com/halo-sigs/plugin-lightgallery)
  - [Umami 1.4.0](https://github.com/halo-sigs/plugin-umami)

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

主题语言资源在更新主题后缓存不会自动刷新，显示的文字为旧版本语言包。

### 复现步骤

1. 安装 <https://github.com/halo-dev/theme-earth/releases/tag/v1.12.0>，这个版本的语言包包含一处错误（下一页按钮的文字）
2. 更新 <https://github.com/halo-dev/theme-earth/releases/tag/v1.12.1>，文字依然显示错误
3. 点击主题 `清除模板缓存` 之后，恢复正常。

![Image](https://github.com/user-attachments/assets/71e9b04e-3f1d-4f22-9594-237ea81bb4e6)

### 相关日志输出

```shell

```

**Comment by JohnNiang** [comment]
默认情况下，Thymeleaf 缓存功能是开启的，所以会在解析语言的时候缓存结果。可以考虑在主题更新之后清理一下缓存即可。

/kind bug
/area core

> https://github.com/thymeleaf/thymeleaf/blob/db314973254ca8d9ee8661cf13c680b93349ee59/lib/thymeleaf/src/main/java/org/thymeleaf/messageresolver/StandardMessageResolver.java#L261
