### ISSUE TITLE
[编辑器插件开发bug] 使用Decoration.inline设置style属性后，页面无响应

### ISSUE THREAD

**Issue by Aziteee** [halo-dev/halo#7063]
### 前置条件

- [x] 已经在 [issues](https://github.com/halo-dev/halo/issues) 列表中搜索了相关问题。
- [x] 这是 Halo 项目本身存在的问题，如果是非项目本身的问题（如：安装部署问题），建议在 [Discussions](https://github.com/halo-dev/halo/discussions) 提交。
- [x] 已经尝试过停用所有的插件，排除是插件导致的问题。
- [x] 如果是插件和主题的问题，请在对应的插件和主题仓库提交。

### 系统信息

- 外部访问地址: http://localhost:8090
- 启动时间: 2024-11-22 19:37
- 版本: 2.20.7
- 构建时间: 2024-10-23 20:59
- Git Commit: 17e9f2b
- Java: IBM Semeru Runtime Open Edition / 21.0.4+7-LTS
- 数据库: H2 / 2.3.232
- 操作系统: Linux / 5.15.153.1-microsoft-standard-WSL2
- 已激活主题: [Lapis 1.1.0](https://github.com/Aziteee/halo-theme-lapis)
- 已启动插件:
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.6.2](https://github.com/halo-dev/plugin-search-widget)
  - [评论组件 2.4.0](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场 1.6.0](https://www.halo.run/store/apps/app-VYJbF)
  - [式 1.0.0-SNAPSHOT](https://github.com/Aziteee/halo-plugin-shiki)

### 使用的哪种方式运行？

Docker

### 发生了什么？

我准备编写一个shiki代码高亮的插件。我是在原highlightjs插件的基础上改的。但是使用Decoration.inline设置style属性后，页面无响应，过了一段时间后提示内存溢出了。

```ts
const decoration = Decoration.inline(from, to, {
  style: node.style,
});
```

然后我尝试把style属性改为其他的比如class

```ts
const decoration = Decoration.inline(from, to, {
  class: node.style,
});
```

结果一切正常，输出的dom如下

```html
<span class="color:#CB7676;">const </span>
<span class="color:#BD976A;">message</span>
<span class="color:#666666;"> =</span>
<span class="color:#C98A7D77;"> '</span>
<span class="color:#C98A7D;">Hello World</span>
<span class="color:#C98A7D77;">'</span>
<span class="color:#666666;">;</span>
```

然后我就想会不会是tiptap或者prosmirror的问题。于是我尝试用tiptap搞了个小demo，plugin的代码完全一样，结果能正常渲染。那么问题只可能出在halo上了

我感觉可能是halo的codeblock extension的问题

![Image](https://github.com/user-attachments/assets/2c3af0e1-0197-4bd5-8710-25ccb02515df)

这个demo的codesandbox地址如下 https://codesandbox.io/p/devbox/holy-leftpad-jxncq7

我正在开发的插件的github仓库是 https://github.com/Aziteee/halo-plugin-shiki

其中出问题的代码在 https://github.com/Aziteee/halo-plugin-shiki/blob/main/ui/src/editor/lowlight-plugin.ts 的 106 行

### 相关日志输出

```shell

```

**Comment by ruibaby** [comment]
抛开这个问题不谈，要不要考虑参与维护 https://github.com/halo-sigs/plugin-shiki

目前这个插件是完全可用的，只是可能和主题有一些兼容性问题。

或者你可以先看看这个插件的实现。

**Comment by ruibaby** [comment]
> 要不要考虑参与维护 https://github.com/halo-sigs/plugin-shiki/pull/1
> 
> 目前这个插件是完全可用的，只是可能和主题有一些兼容性问题。
> 
> 或者你可以先看看这个插件的实现。

晚点我会先合并这个 PR，再详细看看还有什么问题。

**Comment by Aziteee** [comment]
没发现原来已经有一个仓库了，我去看看

**Comment by Aziteee** [comment]
我擦。我找到原因了。没绷住，原来是我的一个深色模式的浏览器插件的锅，它会一直遍历所有节点去修改颜色，然后prosmirror发现节点被修改了又触发重绘导致死循环然后卡死。
此贴终结。

**Comment by Aziteee** [comment]
我会帮助开发原有的项目，我这个就不维护了
