### ISSUE TITLE
halo的https静态资源问题

### ISSUE THREAD

**Issue by AiHao109** [halo-dev/halo#707]
## 我的环境
halo v1.2.0.release。

---

## 错误日志
无。

---

## 期望行为
我期望当我是使用http方式访问网站的时候，所有资源以http访问，当我以https访问，我希望所有的资源都是以https方式来引用的。所以，作者可以给一点建议或者告诉我是哪部分代码可以关于设置这个的吗？

## 当前行为
我使用docker方式来部署halo，域名映射一切正常。可以通过<a>"http://xxx"</a>来正常访问。但是，我使用ssl证书配置https来访问的时候，我的nginx配置正常，使用<a>“https://xxx”</a>但是halo却无法正常访问。通过控制台查看请求发现，原来是js和css静态请求被锁定了。如图:
![图片](https://user-images.githubusercontent.com/37200516/77291306-f0834980-6d18-11ea-88f0-d102d2261e3e.png)

![图片](https://user-images.githubusercontent.com/37200516/77290776-d8f79100-6d17-11ea-92e1-d633a102f2ed.png)显示mixed block。
我百度了一下，出现这个问题的原因是因为https中引用了http资源，这个行为被浏览器禁止了。

**Comment by ruibaby** [comment]
https://halo.run/archives/use-after-installation.html#%E4%BF%AE%E6%94%B9%E5%8D%9A%E5%AE%A2%E5%9C%B0%E5%9D%80

**Comment by AiHao109** [comment]
谢谢，怪自己没认真看文档。

**Comment by ruibaby** [comment]
> 谢谢，怪自己没认真看文档。

其实也是早期设计的一个错误，下个版本已经支持自己设置绝对路径和相对路径了，且默认为相对路径。
