### ISSUE TITLE
系统恢复备份失败

### ISSUE THREAD

**Issue by acanyo** [halo-dev/halo#7070]
### 前置条件

- [x] 已经在 [issues](https://github.com/halo-dev/halo/issues) 列表中搜索了相关问题。
- [x] 这是 Halo 项目本身存在的问题，如果是非项目本身的问题（如：安装部署问题），建议在 [Discussions](https://github.com/halo-dev/halo/discussions) 提交。
- [x] 已经尝试过停用所有的插件，排除是插件导致的问题。
- [x] 如果是插件和主题的问题，请在对应的插件和主题仓库提交。

### 系统信息

- 外部访问地址: https://mmm.sd
- 启动时间: 2024-11-24 19:07
- 版本: 2.20.9
- 构建时间: 2024-11-12 06:47
- Git Commit: ed5afb2
- Java: IBM Semeru Runtime Open Edition / 21.0.4+7-LTS
- 数据库: MySQL Community Server - GPL / 8.4.3
- 操作系统: Linux / 6.1.0-10-amd64
- 已激活主题: undefined undefined
- 已启动插件:
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.6.2](https://github.com/halo-dev/plugin-search-widget)
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [评论组件 2.5.1](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场 1.8.0](https://www.halo.run/store/apps/app-VYJbF)
  - [静态网页服务 1.0.0-alpha.5](https://www.halo.run/store/apps/app-gFkMn)
  - [SEO 工具集 1.1.0](https://www.halo.run/store/apps/app-FNGbT)
  - [文章限制阅读 Pro 1.4.3](https://www.halo.run/store/apps/app-TzRqd)

### 使用的哪种方式运行？

Docker

### 发生了什么？

在恢复备份后会报错504
![Image](https://github.com/user-attachments/assets/206d329d-3a9a-4e4d-becf-e743ea5828b1)

然后尝试刷新浏览器后
![Image](https://github.com/user-attachments/assets/b9a24903-723d-4415-bafc-283ef4f8357e)

一直403疯狂刷新这个网站

尝试重启halo容器后 有进入的了 系统初始化 重新初始化后 只恢复了部分数据！
![Image](https://github.com/user-attachments/assets/fb47e37f-ce68-4e78-8eb5-4e26ed995f3f)

数据库都是mysql 数据文件已经恢复了
halo版本都是2.20.9 并且我发现我的halo用1p重装后.halo2没了

相关日志
[_opt_1panel_apps_halo_Handsome_docker-compose.yml-20241124191243.log](https://github.com/user-attachments/files/17892995/_opt_1panel_apps_halo_Handsome_docker-compose.yml-20241124191243.log)

### 相关日志输出

```shell
相关日志
[_opt_1panel_apps_halo_Handsome_docker-compose.yml-20241124191243.log](https://github.com/user-attachments/files/17892995/_opt_1panel_apps_halo_Handsome_docker-compose.yml-20241124191243.log)
```

**Comment by acanyo** [comment]
目前我通过报错来看是内存溢出

**Comment by liuchangfitcloud** [comment]
是否开启了防篡改与WAF，建议关闭后重新导入试试。

**Comment by acanyo** [comment]
> 是否开启了防篡改与WAF，建议关闭后重新导入试试。

通过工单解决了

**Comment by ruibaby** [comment]
更新一下，这个问题的本质原因时数据量稍微有点大（20w），导致恢复时间过长，导致反向代理超时（1min）。

建议后续关注：https://github.com/halo-dev/halo/issues/5419

关于过量数据的问题可能来自于某些插件的日志。
