### ISSUE TITLE
org.springframework.dao.TransientDataAccessResourceException: executeMany; SQL [SELECT extensions.* FROM extensions WHERE extensions.name = ? LIMIT 2]; Request queue limit reached

### ISSUE THREAD

**Issue by HowieHz** [halo-dev/halo#7071]
### 前置条件

- [x] 已经在 [issues](https://github.com/halo-dev/halo/issues) 列表中搜索了相关问题。
- [x] 这是 Halo 项目本身存在的问题，如果是非项目本身的问题（如：安装部署问题），建议在 [Discussions](https://github.com/halo-dev/halo/discussions) 提交。
- [x] 已经尝试过停用所有的插件，排除是插件导致的问题。
- [x] 如果是插件和主题的问题，请在对应的插件和主题仓库提交。

### 系统信息

- 外部访问地址: https://howiehz.top
- 启动时间: 2024-11-21 23:45
- 版本: 2.20.9
- 构建时间: 2024-11-12 06:47
- Git Commit: ed5afb2
- Java: IBM Semeru Runtime Open Edition / 21.0.4+7-LTS
- 数据库: MariaDB / 10.11.9-MariaDB-ubu2204
- 操作系统: Linux / 6.1.0-26-amd64
- 已激活主题: [彼岸-皓改 1.12.0](https://github.com/howiehz/halo-theme-higan-hz.git)
- 已启动插件:
  - [Vditor 编辑器 1.8.0](https://github.com/justice2001/halo-plugin-vditor)
  - [站点推送插件 1.5.2](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [Markdown / HTML 内容块 1.2.0](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [Metrics Graph 1.1.0](https://github.com/guqing/plugin-metrics-graph)
  - [Meilisearch 2.0.1](https://github.com/Rainsheep/halo-plugin-meilisearch)
  - [图库管理 1.4.0](https://github.com/halo-sigs/plugin-photos)
  - [瞬间 1.8.0](https://github.com/halo-sigs/plugin-moments)
  - [通知我 1.1.0](https://github.com/monyuan/notify-me)
  - [OAuth2 认证 1.4.2](https://github.com/halo-sigs/plugin-oauth2)
  - [文章导入导出 1.2.4](https://jhacker.cn/2023/halo-plugin-export2doc)
  - [链接管理 1.5.0](https://github.com/halo-sigs/plugin-links)
  - [lightgallery.js 灯箱 1.2.1](https://github.com/halo-sigs/plugin-lightgallery)
  - [highlight.js 代码高亮 1.3.2](https://github.com/halo-sigs/plugin-highlightjs)
  - [Willow Markdown 编辑器 1.0.0](https://github.com/guqing/willow-mde)
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.6.2](https://github.com/halo-dev/plugin-search-widget)
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [评论组件 2.5.1](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场 1.8.0](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker

### 发生了什么？

#7059 不断报错后
一段时间 halo 会崩溃无法访问
报错如 `org.springframework.dao.TransientDataAccessResourceException: executeMany; SQL [SELECT extensions.* FROM extensions WHERE extensions.name = ? LIMIT 2]; Request queue limit reached`

### 相关日志输出

```shell
https://wwzt.lanzoul.com/iTv5S2g4609i
```

**Comment by JohnNiang** [comment]
Hi @HowieHz , thank you for reaching out here!

> 请在提交 Issue 之前搜索一下是否存在类似的 Issue，参考`前置条件第一条`。如果已经存在，请不要重复提交 Issue。

/triage duplicate

See https://github.com/halo-dev/halo/issues/7055 for more.

/close
