### ISSUE TITLE
针对私密文章访问方式的一些疑问

### ISSUE THREAD

**Issue by mark07x** [halo-dev/halo#709]
首先私密文章好像不能刷新，我推测输入密码后提供一个立即过期的临时token（因为我没学过java后端开发，其实并没去看代码，但是看到刷新一会就失效了这样的行为觉得很像）

它在网络较慢的环境下是否能正常访问呢？此外直接显示403（而且好像还是把500渲染成403？这样是有什么特定的于缘由么）的做法，emm似乎不是特别...友好？如果能够token过期（或者提供了不正确的token）直接渲染一个输入密码界面是不是也是一个比较合适的选择呢？

然后貌似私密文章的评论是不受保护的，comment api好像不需要验证。但如果继续沿用临时token就没办法评论了，或许能找到一个比较合理的解决方案同时让文章和评论都能受到保护？Wordpress的私密文章访问权限似乎跟cookie绑定？而且是持续很时间，下一次也不需要输入密码。或许也可以提供这种方式的的选项？

因为是高中生，可能知识上有许多疏漏之处，如果有什么错误还请谅解。

**Comment by ruibaby** [comment]
1. 是的，目前使用的一次性 token，默认 10s 会失效。
2. 能，确实需要在 token 失效后跳转到密码输入页面。
3. 评论确实未做限制。

这些我们都会在后期做优化，在这个版本发布之后。感谢反馈。
