### ISSUE TITLE
[建议] 标签页希望能显示出tag.metadata.name，仅显示即可

### ISSUE THREAD

**Issue by MoConWu** [halo-dev/halo#7090]
### 前置条件

- [x] 已经在 [Issues](https://github.com/halo-dev/halo/issues) 列表中搜索了相关问题。
- [x] 这是和 Halo 相关的特性，如果是非项目本身的问题，建议在 [Discussions](https://github.com/halo-dev/halo/discussions) 提交。
- [x] 如果是插件和主题特性建议，请在对应的插件和主题仓库提交。

### 你当前使用的版本

2.20

### 描述一下此特性

希望能在后台的标签页，或标签详细信息中，看到tag.metadata.name。

**Comment by ruibaby** [comment]
建议说明具体用途，然后看看是否有代替方案。

**Comment by MoConWu** [comment]
官方的API中提供了：`tagFinder.getByName(name)`和`tagFinder.getByNames(names)`，然而name却比较麻烦获得，这就导致使用起来很不方便。

**Comment by ruibaby** [comment]
如果你开发主题需要让用户设置标签，那么应该是在主题设置中让用户选择，而不是手动去得到 metadata.name 去填写，目前表单定义提供了 tagSelect，可参考：https://docs.halo.run/developer-guide/form-schema#tagselect

**Comment by MoConWu** [comment]
> 如果你开发主题需要让用户设置标签，那么应该是在主题设置中让用户选择，而不是手动去得到 metadata.name 去填写，目前表单定义提供了 tagSelect，可参考：https://docs.halo.run/developer-guide/form-schema#tagselect

明白了
