### ISSUE TITLE
建议增加自定义邮件通知模板

### ISSUE THREAD

**Issue by Anyexyz** [halo-dev/halo#7104]
### 前置条件

- [x] 已经在 [Issues](https://github.com/halo-dev/halo/issues) 列表中搜索了相关问题。
- [x] 这是和 Halo 相关的特性，如果是非项目本身的问题，建议在 [Discussions](https://github.com/halo-dev/halo/discussions) 提交。
- [x] 如果是插件和主题特性建议，请在对应的插件和主题仓库提交。

### 描述一下此特性

可以在通知功能中允许管理员自定义/恢复默认邮件模板，以增强邮件通知。

**Comment by guqing** [comment]
/triage duplicate with https://github.com/halo-dev/halo/issues/6985
