### ISSUE TITLE
feat: 是否考虑加强后台登陆安全性

### ISSUE THREAD

**Issue by xun404** [halo-dev/halo#712]
## 概述
增加诸如 MFA，二维码登陆、oAuth（github google等）等安全登陆方式么？

## 动机

目前单纯的账密登陆安全性还是不是很强

## 详细解释

正常账密登陆后，再要求使用两步验证码验证，最好增加登陆ip变化后自动注销功能，已经微信推送通知功能等

**Comment by ruibaby** [comment]
可以考虑，不过目前短期内不会进行开发了。

**Comment by JohnNiang** [comment]
可以考虑再发送一次短信验证码来验证。

**Comment by xun404** [comment]
有开发规范么？也许我能做一些贡献

**Comment by JohnNiang** [comment]
@xun404 https://halo.run/archives/develop-application-structure
