### ISSUE TITLE
初始化后，登录页面卡住，后端报错

### ISSUE THREAD

**Issue by haiyang1024** [halo-dev/halo#7147]
### 前置条件

- [x] 已经在 [issues](https://github.com/halo-dev/halo/issues) 列表中搜索了相关问题。
- [x] 这是 Halo 项目本身存在的问题，如果是非项目本身的问题（如：安装部署问题），建议在 [Discussions](https://github.com/halo-dev/halo/discussions) 提交。
- [x] 已经尝试过停用所有的插件，排除是插件导致的问题。
- [x] 如果是插件和主题的问题，请在对应的插件和主题仓库提交。

### 系统信息

登录就有问题

### 使用的哪种方式运行？

Fat Jar

### 发生了什么？
初始化后，登录页面卡住，后端报错
![Image](https://github.com/user-attachments/assets/97d3cc0a-f705-413f-9081-ab31c7274beb)

![Image](https://github.com/user-attachments/assets/9918fc8b-8a8a-4a35-b034-a914dd92012e)

### 复现步骤

![Image](https://github.com/user-attachments/assets/5e725725-63fc-4f85-97f6-d607da9668f3)

### 相关日志输出

```shell

```

**Comment by ruibaby** [comment]
这是 2.20.0 的 bug，你可以重启或者升级到最新版本来解决此问题。

JAR 的最新发行版建议查看：https://download.halo.run/

/kind support

**Comment by haiyang1024** [comment]
重启后可以了
