### ISSUE TITLE
增加仅特定角色可访问文章和附件的功能

### ISSUE THREAD

**Issue by ssxzi** [halo-dev/halo#7151]
### 前置条件

- [x] 已经在 [Issues](https://github.com/halo-dev/halo/issues) 列表中搜索了相关问题。
- [x] 这是和 Halo 相关的特性，如果是非项目本身的问题，建议在 [Discussions](https://github.com/halo-dev/halo/discussions) 提交。
- [x] 如果是插件和主题特性建议，请在对应的插件和主题仓库提交。

### 你当前使用的版本

2.20.12

### 描述一下此特性

文章和附件发布时可以选择仅某些角色（用户组）可见。

**Comment by ssxzi** [comment]
[https://github.com/halo-dev/halo/issues/4024](https://github.com/halo-dev/halo/issues/4024)

**Comment by ssxzi** [comment]
希望增加仅特定角色可访问附件的功能

**Comment by ruibaby** [comment]
/triage duplicate

See https://github.com/halo-dev/halo/issues/4024

/close

**Comment by ruibaby** [comment]
> 希望增加仅特定角色可访问附件的功能

不要在同一个 issue 提交多个问题。
