### ISSUE TITLE
建议新增一个快速指向本页的超链接定位锚点

### ISSUE THREAD

**Issue by Kelilix** [halo-dev/halo#7156]
### 前置条件

- [x] 已经在 [Issues](https://github.com/halo-dev/halo/issues) 列表中搜索了相关问题。
- [x] 这是和 Halo 相关的特性，如果是非项目本身的问题，建议在 [Discussions](https://github.com/halo-dev/halo/discussions) 提交。
- [x] 如果是插件和主题特性建议，请在对应的插件和主题仓库提交。

### 你当前使用的版本

2.20.12

### 描述一下此特性

1、在编辑器内想要增加一个超链接，链接到本篇其他章节时，目前我的操作是：
【创建对应章节】-【发布本篇】-【获取超链接】-【重新编辑本篇插入超链接】
建议增加一个快速定位的锚点，例如/thispage/xxxxx，就可以快速定位到本篇的xxxxx章节
2、同时我希望这个快速定位的锚点是跨文章的，比如我想把一组段落从一篇文章搬到另一篇中，其中涉及到内部超链接跳转，我希望不需要重新修改超链接，能够自动识别到是新的文章

**Comment by ruibaby** [comment]
/triage duplicate

See https://github.com/halo-dev/halo/issues/7098

/close
