### ISSUE TITLE
feat: 可以考虑 支持导出到hexo吗

### ISSUE THREAD

**Issue by xiongyizhu** [halo-dev/halo#716]
## 概述

希望能支持导出到hexo

## 动机

可以毫无顾虑从hexo转过来，就算将来服务器到期了还可以再转回去

**Comment by ruibaby** [comment]
会做的。实际上已有相关接口，只是还没有用到。

**Comment by ruibaby** [comment]
已经支持：https://github.com/halo-dev/halo/releases/tag/v1.4.3

**Comment by liangyuanpeng** [comment]
> 已经支持：https://github.com/halo-dev/halo/releases/tag/v1.4.3

这个支持指的是导出MD文件吧，是否有可能将主题也同时导出为静态博客主题?我没有查看相关源码，因此不确定在技术上的实施问题

**Comment by ruibaby** [comment]
> > 已经支持：https://github.com/halo-dev/halo/releases/tag/v1.4.3
> 
> 这个支持指的是导出MD文件吧，是否有可能将主题也同时导出为静态博客主题?我没有查看相关源码，因此不确定在技术上的实施问题

不会做。
