### ISSUE TITLE
代码块语言只有auto

### ISSUE THREAD

**Issue by yuanshi1602** [halo-dev/halo#7169]
### 前置条件

- [x] 已经在 [issues](https://github.com/halo-dev/halo/issues) 列表中搜索了相关问题。
- [x] 这是 Halo 项目本身存在的问题，如果是非项目本身的问题（如：安装部署问题），建议在 [Discussions](https://github.com/halo-dev/halo/discussions) 提交。
- [x] 已经尝试过停用所有的插件，排除是插件导致的问题。
- [x] 如果是插件和主题的问题，请在对应的插件和主题仓库提交。

### 系统信息

- 外部访问地址: 
- 启动时间: 2024-12-25 18:02
- 版本: 2.19.3
- 构建时间: 2024-09-10 17:45
- Git Commit: 9ffb1bb
- Java: IBM Semeru Runtime Open Edition / 21.0.4+7-LTS
- 数据库: H2 / 2.2.224
- 操作系统: Linux / 6.8.0-49-generic
- 已激活主题: [Earth 1.9.0](https://github.com/halo-dev/theme-earth)
- 已启动插件:
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.6.2](https://github.com/halo-dev/plugin-search-widget)
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [评论组件 2.4.0](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场 1.4.0](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker

### 发生了什么？

使用默认主题，代码块语言只有auto，没有其他选项。2.19.3 到2.20.12都有一样的问题，降级到2.16至2.18这几个版本是正常的

### 相关日志输出

```shell

```

### 附加信息

![image](https://github.com/user-attachments/assets/a71e4d66-76bf-4434-81d2-f654d92ca8e0)
![image](https://github.com/user-attachments/assets/cac20625-7f57-4848-83aa-64eef01b6ce9)

**Comment by ruibaby** [comment]
2.19+ 已经移除了内置的代码高亮，详见：https://github.com/halo-dev/halo/releases/tag/v2.19.0

<img width="1201" alt="Image" src="https://github.com/user-attachments/assets/6cd532ec-fcd4-4d3a-99d2-f8ba8ab546e5" />

https://www.halo.run/store/apps/app-sqpgf?tab=releases

**Comment by yuanshi1602** [comment]
> 2.19+ 已经移除了内置的代码高亮，详见：https://github.com/halo-dev/halo/releases/tag/v2.19.0
> 
> <img alt="Image" width="1201" src="https://private-user-images.githubusercontent.com/21301288/398565357-6cd532ec-fcd4-4d3a-99d2-f8ba8ab546e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxMzI0MTYsIm5iZiI6MTczNTEzMjExNiwicGF0aCI6Ii8yMTMwMTI4OC8zOTg1NjUzNTctNmNkNTMyZWMtZmNkNC00ZDNhLTk5ZDItZjhiYThhYjU0NmU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI1VDEzMDgzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5ZDQ1N2NhYjg0YTJkODdiZmI1ODBlYmQ3ZjZiMWVhMTlkYzkxNDQwOTIzMDhiNDVhMzYwY2JhZDgwNDI3NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.o4hpgHIbbkpHY3F-0mNS2H6CboKjOR_ZaddXQ1nTt88">
> https://www.halo.run/store/apps/app-sqpgf?tab=releases

多谢，安装了highlight可以了
