### ISSUE TITLE
默认编辑器支持插入超链接

### ISSUE THREAD

**Issue by exialin** [halo-dev/halo#7177]
### 前置条件

- [x] 已经在 [Issues](https://github.com/halo-dev/halo/issues) 列表中搜索了相关问题。
- [x] 这是和 Halo 相关的特性，如果是非项目本身的问题，建议在 [Discussions](https://github.com/halo-dev/halo/discussions) 提交。
- [x] 如果是插件和主题特性建议，请在对应的插件和主题仓库提交。

### 你当前使用的版本

 2.20.12

### 描述一下此特性

使用默认编辑器的过程中，想插入超链接，突然发现似乎没有这个功能？还是说我没有找到？

**Comment by VoidYun** [comment]
选中文本就能看到了

![Image](https://github.com/user-attachments/assets/d4a98d37-93d3-41d2-8e33-d6c36d990869)

**Comment by exialin** [comment]
> 选中文本就能看到了
> 
> ![Image](https://github.com/user-attachments/assets/d4a98d37-93d3-41d2-8e33-d6c36d990869)

原来是这样，有点难发现
