### ISSUE TITLE
希望分类目录支持添加子目录

### ISSUE THREAD

**Issue by NGLSL** [halo-dev/halo#72]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://docs.halo.run/)
- [ ] [Github Wiki 常见问题](https://github.com/ruibaby/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [ ] [其他 Issues](https://github.com/ruibaby/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [x] 添加新的特性或者功能
- [ ] 请求技术支持

有些文章需要分类的也不太好分，希望支持分类目录支持添加子目录，现在不支持子分类目录。

**Comment by ruibaby** [comment]
@NGLSL 好的，我会好好考虑的，请关注版本发布。

**Comment by Wu-XiaoLin** [comment]
希望在后续的版本中可以支持自定义项目名称，issuse无法提交...只能在这里留言了

**Comment by ruibaby** [comment]
@Wu-XiaoLin 自定义项目名称啥意思？ issue可以提交吧。

**Comment by Wu-XiaoLin** [comment]
@ruibaby  
![image](https://user-images.githubusercontent.com/40012676/50632411-b8141600-0f82-11e9-90b1-ce53b369b783.png) springboot的配置项目名功能
![image](https://user-images.githubusercontent.com/40012676/50632460-e5f95a80-0f82-11e9-803b-8843c45bd011.png)

**Comment by ruibaby** [comment]
@Wu-XiaoLin 不能提交 `issue` 是因为你没写title，另外，自定义 `context-path` 的需求是？ 有什么特殊的使用情况吗？

**Comment by Wu-XiaoLin** [comment]
失误，需要自定义 `context-path` 是因为服务器部署了多个项目，增加context-path以后项目内的静态资源加载不到(使用nginx代理);

**Comment by ruibaby** [comment]
@Wu-XiaoLin 你用不同的端口就行了嘛。

**Comment by ruibaby** [comment]
@Wu-XiaoLin 用nginx代理一下就行了啊，抱歉，不考虑增加 `context-path` ，你部署的时候可以自己加上。

**Comment by Wu-XiaoLin** [comment]
嗯，没关系，主要是nginx代理以后页面的静态资源都是绝对路径，加载不到，所以代理了也无法使用。

**Comment by ruibaby** [comment]
已开发完毕。
