### ISSUE TITLE
可不可以编写一些一键脚本

### ISSUE THREAD

**Issue by bestsort** [halo-dev/halo#728]
是不是可以给用户提供一些一键部署/更新的脚本?类似[这样](https://github.com/nextcloud/vm/tree/master/static)。这样也能避免一些部署/更新造成的误操作

**Comment by JohnNiang** [comment]
官方由提供相关的部署和更新教程，而且也就几行命令（核心命令也就 java -jar），没必要封装成一个脚本。

**Comment by bestsort** [comment]
> 官方有提供相关的部署和更新教程，而且也就几行命令（核心命令也就 java -jar），没必要封装成一个脚本。

比如使用 docker 部署的话， 是否可以提供几个docker-compose以支持不同需求如Nginx/Apache、 MySQL/H2这一类的呢？ 就在潜水的这一阵子来看貌似还是有一些栽在部署/更新上的小伙伴

**Comment by ruibaby** [comment]
> > 官方有提供相关的部署和更新教程，而且也就几行命令（核心命令也就 java -jar），没必要封装成一个脚本。
> 
> 比如使用 docker 部署的话， 是否可以提供几个docker-compose以支持不同需求如Nginx/Apache、 MySQL/H2这一类的呢？ 就在潜水的这一阵子来看貌似还是有一些栽在部署/更新上的小伙伴

其实大部分是栽在反向代理上。

**Comment by ruibaby** [comment]
总的来说，这个提议也不是没有必要，但是需要考虑的问题有很多。需要一个在脚本方面比较强的人。
