### ISSUE TITLE
从1.2升级到1.3时，页面报错，code这个模板的错，而theme里并没有这个模板

### ISSUE THREAD

**Issue by bjyuwenqi** [halo-dev/halo#729]
## 我的环境

---

## 错误日志

---

**Comment by bjyuwenqi** [comment]
自带的codelunatic_simple/module/navbar.ftl   

categorie.slugName   null or missing。

先不升级了。

发个补丁版本1.3.1吧，然后再升级。

**Comment by bjyuwenqi** [comment]
按照1.3的readme，操作，直接报错！加油啊，兄弟。

**Comment by JohnNiang** [comment]
可能是因为主题的不兼容，因为 1.3 重构了部分主题数据结构。

**Comment by ruibaby** [comment]
> 按照1.3的readme，操作，直接报错！加油啊，兄弟。

你确定？确定有看 release 的说明？https://github.com/halo-dev/halo/releases/tag/v1.3.0

我在 `升级步骤` 和 `注意事项` 都已说明，在未确定主题适配 1.3.0 之前不要更新。为了确保所有人都能正常更新到 1.3.0，我不仅适配了 `halo-dev` 下的所有主题，还 fork 了三个三方主题，适配之后给作者提交了 pull request，而且都已合并，也就是说 `halo.run/p/themes` 下的所有主题均已适配。

你说的报错点：

https://github.com/CodeLunatic/halo-theme-simple-bootstrap/blob/master/module/navbar.ftl#L47

并没有出现 `categorie.slugName`。

另外，请端正自己的位置，我们不存在甲方与乙方的管的。

再另外，加油啊，兄弟。

**Comment by bjyuwenqi** [comment]
我的主题里只有2个：Simple Bootstrap 和  Anatole，bootstrap是我自己安装的。
CodeLunatic是哪里来的呢？不是halo自带的吗？
这不是甲方乙方的问题，这是对自己的开源产品负责的问题。你若用甲方乙方的视角来看待，劝你别玩开源。

**Comment by ruibaby** [comment]
@bjyuwenqi 懒得和你废话，已 block
