### ISSUE TITLE
在将数据库类型改为mysql后，依然访问H2，

### ISSUE THREAD

**Issue by bjyuwenqi** [halo-dev/halo#730]
已经将H2注释掉，并且mysql配置无误，这很奇怪

## 我的环境

---

## 错误日志

---

**Comment by JohnNiang** [comment]
请给出你的配置，以及配置后的操作。

**Comment by bjyuwenqi** [comment]
server:
  port: 8090
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource

    # H2 Database 配置，如果你需要使用 MySQL，请注释掉该配置并取消注释 MySQL 的配置。
    #driver-class-name: org.h2.Driver
    #url: jdbc:h2:file:~/.halo/db/halo
    #username: admin
    #password: 123456

    # MySQL 配置，如果你需要使用 H2Database，请注释掉该配置并取消注释上方 H2Database 的配置。
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/halodb?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: xxxxxxxx

  # H2 Database 的控制台相关配置，如果你使用的是 MySQL ，请注释掉下方内容。
  #h2:
    #console:
    #  settings:
    #    web-allow-others: false
    #  path: /h2-console
    #  enabled: false
