### ISSUE TITLE
master分支下没有主题相关的资源文件

### ISSUE THREAD

**Issue by 1244791720** [halo-dev/halo#739]
halo\src\main\resources\templates\themes\anatole 路径下的文件为空造成程序跑不起来。

**Comment by ruibaby** [comment]
@1244791720 请参考 https://halo.run/archives/install-quick-start.html

**Comment by 1244791720** [comment]
> @1244791720 请参考 https://halo.run/archives/install-quick-start.html
我想解决的问题是:
    run.halo.app.exception.NotFoundException: 没有找到 id 为 caicai_anatole 的主题
这个异常我要怎么处理。

**Comment by ruibaby** [comment]
@1244791720 https://halo.run/archives/develop-application-start

**Comment by 1244791720** [comment]
手动放入了默认主题，问题已经解决了。

**Comment by JohnNiang** [comment]
git submodule init
git submodule update

**Comment by duanfurong** [comment]
@1244791720 大佬您好 我也遇到了这个问题方便请问下是怎么解决的吗，我一开始也是在thems文件下的annnote文件放了默认的主题配置文件“没有找到 id 为 caicai_anatole 的主题”这个问题也是最近才遇到的，方便请大佬详细赐教下吗，晚辈感激不尽

**Comment by ruibaby** [comment]
@duanfurong 上面全是解决方案。

**Comment by duanfurong** [comment]
@ruibaby 大佬您好  我的问题是“没有找到 id 为 caicai_anatole 的主题”我已经在相应的文件下面放置了主题的相关文件但是还是有这个问题我是在thems文件下的annnote放置的c盘下相应的文件夹也放了相应的文件。感谢大佬的赐教，晚辈感激不尽。

**Comment by ruibaby** [comment]
> @ruibaby 大佬您好 我的问题是“没有找到 id 为 caicai_anatole 的主题”我已经在相应的文件下面放置了主题的相关文件但是还是有这个问题我是在thems文件下的annnote放置的c盘下相应的文件夹也放了相应的文件。感谢大佬的赐教，晚辈感激不尽。

如果你是 clone 的代码的话，去项目目录下执行：

```
git submodule init

git submodule update
```

如果你是直接下载的源码，将 https://github.com/halo-dev/halo-theme-anatole 下载到项目的 `src/main/resources/templates/themes/` 下，重命名为 anatole，重启。
