### ISSUE TITLE
feat: 英文自动增加空格

### ISSUE THREAD

**Issue by liuyh0805** [halo-dev/halo#740]
能在英文左右自动生成空格吗？

**Comment by ruibaby** [comment]
@liuyh0805 能 非常好的建议。

**Comment by bestsort** [comment]
> @liuyh0805 能 非常好的建议。

觉得可以在 **英文、数字、符号**之间插入空白， 并作为一个可选项

**Comment by JohnNiang** [comment]
说白了，就是需要一个格式化的工具，不过是在文档保存后。不过，可以提供一种选项来让作者决定是否需要格式化 。

**Comment by ruibaby** [comment]
会在新的编辑器提供，我先关闭了。
