### ISSUE TITLE
咨询下Halo对于seo这方面，有没有什么指导文档，个人博客搭建后，文章无法被搜索引擎搜索到

### ISSUE THREAD

**Issue by Ted-Engineer** [halo-dev/halo#741]
咨询下Halo对于seo这方面，有没有什么指导文档，个人博客搭建后，文章无法被搜索引擎搜索到

**Comment by ruibaby** [comment]
https://halo.run/archives/use-after-installation.html#seo-%E8%AE%BE%E7%BD%AE

> 无法被搜索引擎搜索到很正常，你可以考虑上各种站长平台，手动或自动提交链接，兴许有帮助。
