### ISSUE TITLE
feat: 修改 admin 后台路由

### ISSUE THREAD

**Issue by ruoxiao-zh** [halo-dev/halo#742]
## 概述

 admin 后台地址直接暴露出来, 这样很危险

## 动机

部署简单, 还是很不错的, 但是有一点 admin 后台地址直接暴露出来, 这样很危险, 建议增加修改 admin 路由的功能, 或者其他的隐藏 admin 路由的方法

**Comment by ruibaby** [comment]
早已支持。https://halo.run/archives/install-with-linux.html#%E4%BF%AE%E6%94%B9%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6

**Comment by ruoxiao-zh** [comment]
ok, 是我没认真阅读文档
