### ISSUE TITLE
centos8 安装有些问题

### ISSUE THREAD

**Issue by LG17** [halo-dev/halo#744]
centOS 8
halo-1.3.1
java-1.8
按照文档部署后，访问网页，一直都是 /admin/index.html#install
没有任何错误提示…
什么原因呢

**Comment by JohnNiang** [comment]
博客首次启动需要初始化一下。

**Comment by LG17** [comment]
一直停留在这个界面，首页都会跳转到这里，一直在初始化…

**Comment by ruibaby** [comment]
> 一直停留在这个界面，首页都会跳转到这里，一直在初始化…

有填写相关信息进行初始化吗？

**Comment by LG17** [comment]
需要哪些信息啊？全是按安装文档来的，访问网址就一直停在这

**Comment by ruibaby** [comment]
> 需要哪些信息啊？全是按安装文档来的，访问网址就一直停在这

在安装页面填写博主信息和博客信息，最后点击安装按钮即可。

**Comment by LG17** [comment]
这个界面没有内容，有个转圈圈的图标

**Comment by ruibaby** [comment]
@LG17 你用的什么浏览器

**Comment by LG17** [comment]
找到问题了，我是离线安装的，很多js是cdn加载的… 离线部署有方法吗？把cdn资源放本地？

**Comment by ruibaby** [comment]
> 找到问题了，我是离线安装的，很多js是cdn加载的… 离线部署有方法吗？把cdn资源放本地？

那你可能需要自行在本地部署 admin。

参考：https://github.com/halo-dev/halo-admin

同时也不建议在无网络的情况下使用，不仅是 admin 使用了 cdn，部分主题同样有在使用。
