### ISSUE TITLE
feat: 是否支持多用户

### ISSUE THREAD

**Issue by whbq** [halo-dev/halo#753]

**Comment by ruibaby** [comment]
暂不支持。

**Comment by JohnNiang** [comment]
可以描述一下您为什么想使用多用户？

**Comment by Alicyu1024** [comment]
感觉暂时没必要开发多用户的功能吧，单用户的还有很大的开发的空间

**Comment by whbq** [comment]
额，单独对于博客是没有的。可能我想做的不是博客。



在 2020-04-08 01:17:00，"Alicyu" <notifications@github.com> 写道：

感觉暂时没必要开发多用户的功能吧，单用户的还有很大的开发的空间
