### ISSUE TITLE
文章有支持采用ID为path的方式吗

### ISSUE THREAD

**Issue by louislivi** [halo-dev/halo#757]
如题，比如
文章有支持采用ID为path的方式吗
如 `http://www.louislivi.com/archives/147`
不然每一次都需要去手动设置一个别名

**Comment by ruibaby** [comment]
@louislivi 支持 /?=id 的形式。

**Comment by louislivi** [comment]
就是 #563 这个功能 但是在我这halo中 没有固定链接这块的设置项
![image](https://user-images.githubusercontent.com/23403807/78853446-79a4bb00-7a51-11ea-9e9a-d61fbe4c5701.png)
![image](https://user-images.githubusercontent.com/23403807/78853488-8f19e500-7a51-11ea-9158-bed9e1855587.png)

**Comment by ruibaby** [comment]
博客设置右下角有个高级设置按钮

**Comment by louislivi** [comment]
这个按钮好隐密 而且只是一个icon 真的很难发现这里还有个功能= =

**Comment by ruibaby** [comment]
> 这个按钮好隐密 而且只是一个icon 真的很难发现这里还有个功能= =

那可能是你的屏幕分辨率太高。
