### ISSUE TITLE
Logo 征集

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#759]
大家好，我们现在需要一个 Logo，以保证 Halo 更好的发展。如果你有不错的设计能力和想法，欢迎参与贡献，如果我们选中你的 Logo，你的相关信息将放在 README 中合适的位置。感谢！

附：

![Snipaste_2020-04-11_23-21-13](https://user-images.githubusercontent.com/21301288/79047753-344bdd80-7c4b-11ea-85be-e3a713e6017f.png)

**Comment by Littlegolden** [comment]
群头像那个我很可的

**Comment by ruibaby** [comment]
> 群头像那个我很可的

是不错，但是和微软的某个软件库的logo相似度99%

**Comment by Littlegolden** [comment]
感觉商标也要注册下

**Comment by AmmRage** [comment]
网上各式各样的logo生成器非常多，可以选择这些自动生成的。当然，如果有商业目标考量的话，建议找专业设计师做。

**Comment by ruibaby** [comment]
> 网上各式各样的logo生成器非常多，可以选择这些自动生成的。当然，如果有商业目标考量的话，建议找专业设计师做。

只是想让 Github 组织头像，TG群 QQ群头像好看点，没有商业。

**Comment by wangwenfei2016** [comment]
logo 需要体现什么主题，要表达的内容是啥， @ruibaby

**Comment by ruibaby** [comment]
> logo 需要体现什么主题，要表达的内容是啥， @ruibaby

简洁，现代，我觉得主体可以为 Halo 的头字母 H，这是之前用的两个：

![halo](https://user-images.githubusercontent.com/21301288/80331766-8e6bb600-887b-11ea-8734-19545973e931.png)
![photo_2019-12-09_21-24-13](https://user-images.githubusercontent.com/21301288/80331771-90ce1000-887b-11ea-9a1d-c45e7633c4f0.jpg)

**Comment by wangwenfei2016** [comment]
我有个问题咨询下，目前我打算使用helo开发一个个人博客，我是在helo源码基础上进行2次开发，还需要在博客下面备注    Halo版权信息吗？@
                                   Designed by CaiCai
                                   Proudly published with Halo！

**Comment by wangwenfei2016** [comment]
> 
> 
> 大家好，我们现在需要一个 Logo，以保证 Halo 更好的发展。如果你有不错的设计能力和想法，欢迎参与贡献，如果我们选中你的 Logo，你的相关信息将放在 README 中合适的位置。感谢！
> 
> 附：
> 
> ![Snipaste_2020-04-11_23-21-13](https://user-images.githubusercontent.com/21301288/79047753-344bdd80-7c4b-11ea-85be-e3a713e6017f.png)

我有个问题咨询下，目前我打算使用helo开发一个个人博客，我是在helo源码基础上进行2次开发，还需要在博客下面备注    Halo版权信息吗？@
                                   Designed by CaiCai
                                   Proudly published with Halo！

**Comment by ruibaby** [comment]
> > 大家好，我们现在需要一个 Logo，以保证 Halo 更好的发展。如果你有不错的设计能力和想法，欢迎参与贡献，如果我们选中你的 Logo，你的相关信息将放在 README 中合适的位置。感谢！
> > 附：
> > ![Snipaste_2020-04-11_23-21-13](https://user-images.githubusercontent.com/21301288/79047753-344bdd80-7c4b-11ea-85be-e3a713e6017f.png)
> 
> 我有个问题咨询下，目前我打算使用helo开发一个个人博客，我是在helo源码基础上进行2次开发，还需要在博客下面备注 Halo版权信息吗？@
> Designed by CaiCai
> Proudly published with Halo！

随你，中国并没有对开源项目的相关法律。

**Comment by wangwenfei2016** [comment]
可以参考JD 的，直接就2个字母HL
