### ISSUE TITLE
Halo有提供外部调用的api文档吗？

### ISSUE THREAD

**Issue by mmdapl** [halo-dev/halo#760]
Halo博客系统中的access key是用来做什么的，有对应的额外部调用的api文档吗？想在另外的系统中调用自己部署博客的接口数据，例如获取博客信息

**Comment by JohnNiang** [comment]
API  Swagger 文档是有的。

在 application.yml 中配置：

```yml
halo:
  doc-disabled: false
```

**Comment by ruibaby** [comment]
@mmdapl 上线了一个简单的，https://api.halo.run

**Comment by mmdapl** [comment]
@ruibaby @JohnNiang 我管理平台开启 api服务后，在get请求中通过api_access_key参数请求，还是401无法认证，是要把容器重启吗？

**Comment by JohnNiang** [comment]
有去博客后台配置过 access key 么？

**Comment by mmdapl** [comment]
@JohnNiang 配置后保存，然后访问使用api_access_key,在query参数中带上设置的access key，依旧出现：
{
  "status": 401,
  "message": "Missing API access key",
  "devMessage": null,
  "data": null
}
设置之后，docker restart了

**Comment by JohnNiang** [comment]
可以告诉我们请求的具体 API 是什么？（去掉域名）

**Comment by mmdapl** [comment]
@JohnNiang  /api/content/links 这个，后面跟api_access_key=后台设置的access key，好像其他的都被filter拦住了。

**Comment by ruibaby** [comment]
@mmdapl https://ryanc.cc/api/content/links?api_access_key=1111111111111111111111111111111222

**Comment by ruibaby** [comment]
不知是否解决了你的疑惑，我暂时 close 了。
