### ISSUE TITLE
Docker镜像ruibaby/halo部署的v1.3.2版本依然不支持2FA

### ISSUE THREAD

**Issue by jsuse** [halo-dev/halo#762]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/guide)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo-admin/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [x] 添加新的特性或者功能
- [ ] 请求技术支持

![2020-04-13 19-00-05屏幕截图.png](https://i.loli.net/2020/04/13/9j1UZvDr4g7dxk6.png)

Docker镜像ruibaby/halo部署的1.3.2版本依然不支持2FA

版本：1.3.2
数据库：H2 1.4.196 (2017-06-10)
运行模式：production
User Agent：Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.92 Safari/537.36

**Comment by ruibaby** [comment]
@jsuse 刷新浏览器缓存

**Comment by jsuse** [comment]
Chromium 81.0.4044.92 以及 Google Chrome 81.0.4044.92 刷新缓存后问题依旧;
Firefox 75 显示正常

**Comment by jsuse** [comment]
Firefox 75 刷新后又不显示了..

**Comment by ruibaby** [comment]
你是不是在 nginx 配置了缓存 ？或者说使用了宝塔面板？

**Comment by jsuse** [comment]
我在CloudFlare配置了缓存，刚刚Purge了就没事了LOL。非常谢谢
