### ISSUE TITLE
feat&bug: 文章访问量预览草稿的时候也会进行统计

### ISSUE THREAD

**Issue by Lostars** [halo-dev/halo#763]
## 概述

1.文章保存为草稿的时候进行预览会统计访问量；
2.登录了的情况下不统计自己的访问量；
3.文章发布时间使用的是数据创建时间，而不是实际点击发布的时间；

**Comment by zwc456baby** [comment]
第三点功能存疑。。如果需要实际点击发布时间

目前高级设置中 `年月日型` url 格式下，发布时有一个时间选择框，可以手动选择发布时间

通过这个选择框，可以手动将其修改为当前时间后再发布。

如果直接使用实际点击发布时间。会导致 `年月日` 型 url 变动。且这个 时间选择框的设定就无意义了。

如果真有修改 发布时间的需求，手动修改即可。

> 主要影响的是 年月日型 url ，对于普通的ID 型  url  不会有什么副作用

[#247](https://github.com/halo-dev/halo-admin/issues/247)

**Comment by zwc456baby** [comment]
目前手动选择发布时间只有在 `高级设置` 中 `年月日` 型url 才会出现时间选择框

建议任何 url 模式下，都有这个时间选择框。供手动选择发布时间

这样的话，对于有需要的，可以修改发布时间。对于没需要的，继续使用数据创建时间。

**Comment by JohnNiang** [comment]
1. 确实需要一个发布时间字段，在没有设置的情况下，默认采用 createTime。
1. 多种 URL 类型并存，这样能够保证最大程度的可访问性。
