### ISSUE TITLE
请求fonts.cat.net加载很慢

### ISSUE THREAD

**Issue by zhongzhouping** [halo-dev/halo#765]
## 我的环境
Server 版本：1.2.0
Admin 版本：1.2.0
数据库：MySQL
运行模式：production
启动时间：2020-04-13 23:04

---

## 错误日志

---

## 期望行为
希望找个请求可以成功，而且快一点。

## 当前行为
请求很慢，因为某个资源文件是从fonts.cat.net请求的，请求很久就失败了
![image](https://user-images.githubusercontent.com/43698606/79304619-59c73880-7f24-11ea-9a54-cf3bacb4da1d.png)

**Comment by ruibaby** [comment]
什么主题。

**Comment by ruibaby** [comment]
目前只发现 NexT 主题有引用这个资源，目前已修复，请更新主题。

https://github.com/halo-dev/halo-theme-next/commit/24991cbc0f5d9962453b0d96a1d8dfb634ae8202
