### ISSUE TITLE
移动端接口完善

### ISSUE THREAD

**Issue by PawNzZi** [halo-dev/halo#766]
您好！移动端的文章分类查询接口（Lists posts by category slug）返回的json中希望增加文章的标签。

**Comment by JohnNiang** [comment]
都是有返回的哦。

> https://api.halo.run/content-api.html

**Comment by PawNzZi** [comment]
> 都是有返回的哦。
> 
> > https://api.halo.run/content-api.html
是真的没有返回文章的标签啊，返回的是Lists posts接口。

**Comment by ruibaby** [comment]
@PawNzZi 分类查询接口为什么要返回文章的标签？这样可能不太好哦。

**Comment by PawNzZi** [comment]
分类查询，返回文章标签应该没什么影响吧。正常的Lists posts查询都能返回，分类查询只是一个细化的查询，返回的数据应该带有标签吧！

**Comment by PawNzZi** [comment]
> @PawNzZi 分类查询接口为什么要返回文章的标签？这样可能不太好哦。

分类查询，返回文章标签应该没什么影响吧。正常的Lists posts查询都能返回，分类查询只是一个细化的查询，返回的数据应该带有标签吧！

**Comment by JohnNiang** [comment]
嗯嗯，这个可以考虑。周末我们尝试实现一下。

**Comment by ruibaby** [comment]
@PawNzZi 那你是在那种情况下需要用到这个接口

**Comment by ruibaby** [comment]
应该猜到你的意思了，那也不能在分类的接口上动手脚。 另外建一个聚合查询的接口会比较好。

**Comment by PawNzZi** [comment]
> @PawNzZi 那你是在那种情况下需要用到这个接口

我开发的一个小程序，halo后台设置了多个分类。小程序前端是可以通过分类查询到下面的文章，也需要展示文章的标签。
![IMG_2150(20200416-102350)](http://image.lingyikz.cn/image/IMG_2150(20200416-102350)_1587003915607.jpg)
![IMG_2149(20200416-102335)](http://image.lingyikz.cn/image/IMG_2149(20200416-102335)_1587003901981.jpg)
看这两张图应该就知道我说的意思了！

**Comment by ruibaby** [comment]
@PawNzZi 明白，看错接口了。

**Comment by PawNzZi** [comment]
> 应该猜到你的意思了，那也不能在分类的接口上动手脚。 另外建一个聚合查询的接口会比较好。


> @PawNzZi 明白，看错接口了。
如果可以实现的话，希望能下一个版本可以完善下这个查询。

**Comment by ruibaby** [comment]
> > 如果可以实现的话，希望能下一个版本可以完善下这个查询。

🆗

**Comment by PawNzZi** [comment]
> > > 如果可以实现的话，希望能下一个版本可以完善下这个查询。

辛苦了！

**Comment by JohnNiang** [comment]
接下来将完成这个接口。
