### ISSUE TITLE
如何模拟登录自建的halo

### ISSUE THREAD

**Issue by NadamHL** [halo-dev/halo#767]
我希望通过模拟登陆自建halo博客，脚本将本地md笔记，post方式近博客，有提供api吗

**Comment by ruibaby** [comment]
api.halo.run

**Comment by NadamHL** [comment]
![image](https://user-images.githubusercontent.com/39847290/79525804-5c499f80-8096-11ea-9754-4e714018eea4.png)

如何将api_key放进请求当中吗，文档看的有些晕，希望不厌其烦指导下

![image](https://user-images.githubusercontent.com/39847290/79525983-c5c9ae00-8096-11ea-984c-4dd70f71c520.png)

**Comment by ruibaby** [comment]
你可以先用 curl 或者 postman 测试以下接口，看看是否是你代码有点问题。

**Comment by NadamHL** [comment]
![image](https://user-images.githubusercontent.com/39847290/79530493-05e25e00-80a2-11ea-96ca-9fb33bc22180.png)

我以及模拟登陆成功了，如何携带登陆成功的信息，进一步获取其他的信息，
下面是调用退出api，失败了
curl localhost:180/api/admin/loginout -X POST -d '{"access_token":"31fb78cd464e429bb0bf82dbd2ef19cf","expired_in":86400,"refresh_token":"9841aa8230cb488ab052c69817573011"}'  --header "Content-Type: application/json"

**Comment by JohnNiang** [comment]
> ![image](https://user-images.githubusercontent.com/39847290/79530493-05e25e00-80a2-11ea-96ca-9fb33bc22180.png)
> 
> 我以及模拟登陆成功了，如何携带登陆成功的信息，进一步获取其他的信息，
> 下面是调用退出api，失败了
> curl localhost:180/api/admin/loginout -X POST -d '{"access_token":"31fb78cd464e429bb0bf82dbd2ef19cf","expired_in":86400,"refresh_token":"9841aa8230cb488ab052c69817573011"}' --header "Content-Type: application/json"

logout

**Comment by NadamHL** [comment]
非常不好意思，问题提的有问题。其实我这边想提问的，正常post 登陆成功，获取了{"status":200,"message":"OK","devMessage":null,"data":{"access_token":"fc59be2cdaa3419db74cc951765f8c81","expired_in":86400,"refresh_token":"81dcdfaf81024d19bc53da687029ff9d"}}。如何使用这些信息进行下一步操作呢，例如我需要post /api/admin/posts 这个api，显示”未登陆“。

同时我使用session保存机制，携带session去请求也是失败的。

**Comment by NadamHL** [comment]
def testupfile():
    url = "http://www.test.cn/api/admin/login"
    headers = {
       # "api_key":"qweruhjkahjdfnj123",
        "Content-Type":"application/json",
        'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36',
     
    }
    body = {
        "username": "afas",
        "password": "adfa@afda",
    }
    body = json.dumps(body)
    ssion = requests.session()
    ssion.post(url=url, data=body)
    print(ssion.cookies)
    body2  = {"originalContent":"123","title":"123","status":"PUBLISHED","categoryIds":[2],"tagIds":[8]}
    body2 = json.dumps(body2)
    response = ssion.put("http://www.test.cn/api/admin/posts?autoSave=false",headers=headers,data=body2)
    print(response.status_code)

上面这段代码，就是先去模拟登陆，获取session，然后使用这个session去请求服务，但是返回结果是“未登陆”，无操作权限

**Comment by ruibaby** [comment]
将请求得到的 access_token 放到名为 `ADMIN-Authorization` 的 header 中即可。

```
def testupfile():
    url = "http://www.test.cn/api/admin/login"
    headers = {
       # "api_key":"qweruhjkahjdfnj123",
        "Content-Type":"application/json",
        'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36',
        "ADMIN-Authorization": {{ access_token }}
    }
    body = json.dumps(body)
    ssion = requests.session()
    ssion.post(url=url, data=body)
    print(ssion.cookies)
    body2  = {"originalContent":"123","title":"123","status":"PUBLISHED","categoryIds":[2],"tagIds":[8]}
    body2 = json.dumps(body2)
    response = ssion.put("http://www.test.cn/api/admin/posts?autoSave=false",headers=headers,data=body2)
    print(response.status_code)
```

**Comment by JohnNiang** [comment]
@NadamHL 我们的接口是不需要通过 session 来参与的。

**Comment by NadamHL** [comment]
感谢支持，我这边在抓session发现没有，目前就是需要"ADMIN-Authorization": {{ access_token }} 这个字段，已经成功了，非常感谢
