### ISSUE TITLE
1.2.0 -> 1.3.2后台无法打开

### ISSUE THREAD

**Issue by songjinju** [halo-dev/halo#774]
从1.2.0版本升级到1.3.2版本后，后台管理系统无法打开，静态资源404：
![WX20200420-115407](https://user-images.githubusercontent.com/7741694/79712558-bc8e4a80-82fd-11ea-931c-a0e768978d70.png)

**Comment by ruibaby** [comment]
强制刷新。

**Comment by songjinju** [comment]
> 强制刷新。

可以了，感谢
