### ISSUE TITLE
打开“所有页面”出错

### ISSUE THREAD

**Issue by chao19991005** [halo-dev/halo#776]
## 我的环境

版本：1.3.2
数据库：H2 1.4.196 (2017-06-10)
运行模式：production
User Agent：Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.25 Safari/537.36 Core/1.70.3741.400 QQBrowser/10.5.3863.400

---

## 错误日志

```
2020-04-20 20:56:36.901 ERROR 110404 --- [XNIO-1 task-25] r.h.a.controller.core.CommonController   : Request URL: [http://127.0.0.1:8090/error], URI: [/error], Request Method: [GET], IP: [127.0.0.1]
```

---

## 期望行为

应该能正常打开

## 当前行为

点击“所有页面”按钮之后弹出错误并且无法加载出来

**Comment by ruibaby** [comment]
浏览器强制刷新。

**Comment by superzhangzl** [comment]
你好，我的也出现了这个情况。强制刷新也失败了。
操作是直接使用docker进行升级后重启，nginx也重启过。

- 系统信息
> Linux VM-0-2-debian 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2 (2017-06-12) x86_64 GNU/Linux

- 日志
```
Caused by: freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> post.url  [in template "themes/anatole/post.ftl" at line 24, column 65]

----
Tip: It's the step after the last dot that caused this error, not those before it.
----
Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
        - Failed at: ${post.url}  [in template "themes/anatole/post.ftl" at line 24, column 63]
----
        at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:134) ~[freemarker-2.3.29.jar!/:2.3.29]
        at freemarker.core.EvalUtil.coerceModelToTextualCommon(EvalUtil.java:479) ~[freemarker-2.3.29.jar!/:2.3.29]
        at freemarker.core.EvalUtil.coerceModelToStringOrMarkup(EvalUtil.java:401) ~[freemarker-2.3.29.jar!/:2.3.29]
        at freemarker.core.EvalUtil.coerceModelToStringOrMarkup(EvalUtil.java:370) ~[freemarker-2.3.29.jar!/:2.3.29]
        at freemarker.core.DollarVariable.calculateInterpolatedStringOrMarkup(DollarVariable.java:100) ~[freemarker-2.3.29.jar!/:2.3.29]
        at freemarker.core.DollarVariable.accept(DollarVariable.java:63) ~[freemarker-2.3.29.jar!/:2.3.29]
```

**Comment by ruibaby** [comment]
> 你好，我的也出现了这个情况。强制刷新也失败了。
> 操作是直接使用docker进行升级后重启，nginx也重启过。
> 
> * 系统信息
> 
> > Linux VM-0-2-debian 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2 (2017-06-12) x86_64 GNU/Linux
> 
> * 日志
> 
> ```
> Caused by: freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
> ==> post.url  [in template "themes/anatole/post.ftl" at line 24, column 65]
> 
> ----
> Tip: It's the step after the last dot that caused this error, not those before it.
> ----
> Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
> ----
> 
> ----
> FTL stack trace ("~" means nesting-related):
>         - Failed at: ${post.url}  [in template "themes/anatole/post.ftl" at line 24, column 63]
> ----
>         at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:134) ~[freemarker-2.3.29.jar!/:2.3.29]
>         at freemarker.core.EvalUtil.coerceModelToTextualCommon(EvalUtil.java:479) ~[freemarker-2.3.29.jar!/:2.3.29]
>         at freemarker.core.EvalUtil.coerceModelToStringOrMarkup(EvalUtil.java:401) ~[freemarker-2.3.29.jar!/:2.3.29]
>         at freemarker.core.EvalUtil.coerceModelToStringOrMarkup(EvalUtil.java:370) ~[freemarker-2.3.29.jar!/:2.3.29]
>         at freemarker.core.DollarVariable.calculateInterpolatedStringOrMarkup(DollarVariable.java:100) ~[freemarker-2.3.29.jar!/:2.3.29]
>         at freemarker.core.DollarVariable.accept(DollarVariable.java:63) ~[freemarker-2.3.29.jar!/:2.3.29]
> ```

希望大家升级前能看更新说明，https://halo.run/archives/halo-130-released.html#%E5%8D%87%E7%BA%A7%E6%AD%A5%E9%AA%A4

**Comment by superzhangzl** [comment]
sorry，找到原因了。
是看了说明按照说明里的更新的，不过更新完以后需要在控制台手动升级一下正在使用的默认主题即可。
打扰了
