### ISSUE TITLE
feat: 希望支持小专栏（专题）的功能

### ISSUE THREAD

**Issue by GuiZi** [halo-dev/halo#783]
## 希望支持小专栏的功能
多篇文章组成一个小专栏

## 动机
有时想写针对一个小专题相关的文章，目前的困境是单独写多篇文章吧，没组织关系，写成一篇吧，又爆长...

感谢halo的开源

**Comment by ruibaby** [comment]
目前的分类无法满足你的需求吗？

**Comment by ruibaby** [comment]
由于已经 3 天没有继续讨论，先 close 了。如果后续有其他问题，你可以选择 reopen。
