### ISSUE TITLE
在博客设置中设置取消全局绝对路径导致无法访问需要密码的文章

### ISSUE THREAD

**Issue by iobincn** [halo-dev/halo#785]
取消全局绝对路径会影响到需要密码访问的文章，输入密码后跳转的网址只有archives/...，archives前面的域名不见了

**Comment by iobincn** [comment]
访问RSS也遇到同样问题

**Comment by Tert-butyllithium** [comment]
我想尝试解决这个问题，但是"取消全局绝对路径"是什么啊……

**Comment by iobincn** [comment]
高级设置里面的一个选项发自我的华为手机-------- 原始邮件 --------发件人： Tert-butyllithium <notifications@github.com>日期： 2020年5月14日周四 17:59收件人： halo-dev/halo <halo@noreply.github.com>抄送： H521 <iobincn@gmail.com>, Author <author@noreply.github.com>主    题： Re: [halo-dev/halo] 在博客设置中设置取消全局绝对路径导致无法访问需要密码的文章 (#785)

我想尝试解决这个问题，但是"取消全局绝对路径"是什么啊……
