### ISSUE TITLE
增加短信/微信/钉钉等通知方式进度及问题反馈

### ISSUE THREAD

**Issue by xun404** [halo-dev/halo#786]
## 概述

目前仅支持email的通知方式，有一定的局限性；计划增加短信微信钉钉等新的通知方式

## 动机

通知过于单一，多增加几种选择
 
## 详细解释

1. 短信通知
    计划支持三大云平台的短信接口
    1. 阿里云：0.045元/条，支持验证码和普通短信形式；但普通短信形式个人审核很严
    2. 腾讯云：0.047元/条，支持验证码和普通短信形式；普通短信可使用网站备案验证，但签名会为备案时的网站名
    3. 百度云：0.045元/条，支持验证码和普通短信形式；没用过百度云，看文档是不支持个人？？希望有用过的小伙伴来补充

首先会支持阿里云和腾讯云，百度云看需求情况，其他平台暂不考虑。
 
2. 微信通知
    目前有四种形式可以接入微信通知
    1. 认证的公众平台的账号，这部分会完整支持，支持客服消息和模版消息，但是会涉及accessToken的分布问题，如你有a服务已经正常申请了accessToken，b服务在申请时会使a申请的accessToken实效
    2. 测试沙盒公众平台的账号，非常推荐这种方式接入，不需要任何认证即可使用完整版的公众平台功能
    3. 企业微信账号，适合使用企业微信的同学，这部分没什么好说的
    4. Server酱等第三方接口，这类接口消息展示不够全面，并且对涉密信息有泄漏风险，接口调用也有限制，但是申请使用没有成本。

3. 钉钉通知

    适合使用钉钉的同学，目前仅支持群组消息，消息没限制。

**有什么想法和意见的同学一起交流下。**

**Comment by ruibaby** [comment]
@xun404 抱歉，这种客制化的需求暂不考虑，直到完成插件机制。

**Comment by xun404** [comment]
@ruibaby 插件机制有具体的时间计划么？

**Comment by ruibaby** [comment]
> @ruibaby 插件机制有具体的时间计划么？

暂无。
