### ISSUE TITLE
The  halo system has  global  stored-xss vulnerability

### ISSUE THREAD

**Issue by Jayway007** [halo-dev/halo#798]
1、The administrator logs in and creates a new article which title and content are “<img src=1 onerror=alert(document.domain)>”：
![one](https://user-images.githubusercontent.com/22486282/80469366-0bc62200-8973-11ea-9545-a15e640780ff.png)

2、Then every user viewing this article at the front desk will be hurt by this xss vulnerability：
![two](https://user-images.githubusercontent.com/22486282/80469928-d66e0400-8973-11ea-94b4-da923822cd1f.png)

**Comment by Jayway007** [comment]
another vulnerability?<a href=www.baidu.com>test</a>

**Comment by JohnNiang** [comment]
All article contents are created by the owner.

**Comment by Jayway007** [comment]
<a href=../../../../../../baidu.com>test1</a>

**Comment by Jayway007** [comment]
<a href=../../../../..//baidu.com>test2</a>

**Comment by JohnNiang** [comment]
So we render all contents trustfully by default.

**Comment by Jayway007** [comment]
However, there is another scenario,the user can write the payload at the front desk comment，here：
![image](https://user-images.githubusercontent.com/22486282/80557823-c9e8ba80-8a0a-11ea-82fa-c7f2f3f7fa54.png)

https://xss.pt/wnWMp.jpg is malicious server that I built to receive cookies
When the administrator views this comment in the background, the <a> link of the commenter ’s ID will be the website address.
![image](https://user-images.githubusercontent.com/22486282/80557938-2946ca80-8a0b-11ea-8073-6df57a55c634.png)
If the administrator clicks on this ID, the attacker will receive the administrator's cookie and other information
![image](https://user-images.githubusercontent.com/22486282/80557993-4da2a700-8a0b-11ea-93d7-e146e6f01ea6.png)
Of course, there are other attacks on xss
