### ISSUE TITLE
关于自行编译问题汇总以及解决方法，大佬请无视。

### ISSUE THREAD

**Issue by cdoer** [halo-dev/halo#804]
以下问题请移步博客   https://blog.yxyvpn.com/2020/04/29/%E7%BC%96%E8%AF%91%E8%BF%90%E8%A1%8Chalo%E5%8D%9A%E5%AE%A2%E7%9A%84%E4%B8%80%E4%BA%9B%E9%97%AE%E9%A2%98%E6%B1%87%E6%80%BB/#more

Plugin [id: 'org.springframework.boot', version: '2.2.6.RELEASE'] was not found in any of the following sources:

Field buildProperties in run.halo.app.config.HaloConfiguration required a bean of type 'org.springframework.boot.info.BuildProperties' that could not be found.

Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.1:check (checkstyle) on project app: Failed during checkstyle execution

**Comment by ruibaby** [comment]
@cdoer 我觉得你应该发在社区，issue 不合适。

**Comment by cdoer** [comment]
@ruibaby  一般都会搜issue的，我close下，留个记录就好。

**Comment by ruibaby** [comment]
@cdoer 好主意

**Comment by wajncn** [comment]
https://blog.csdn.net/happywinterchen/article/details/105209088

解决方案

**Comment by cdoer** [comment]
@wajncn 咋了  这个只是其中一个问题而已   博客有说明 ，并且build-info的问题也是你发的这个地址
