### ISSUE TITLE
feat: 根据标题文字，在发布没有填写路径时，按规则自动生成{slug}，而不是直接汉字

### ISSUE THREAD

**Issue by cyea** [halo-dev/halo#807]
## 概述

在没有填写路径发布文章时，希望按某套规则自动生成{slug}，而不是直接汉字

## 动机

发布文章时的标题不想搞个蹩脚的英文单词，想自己有套规则去生成

## 想法

我的想法是在不自己填写slug （主要不想自己搞个蹩脚单词拼接）的时候,。而是根据文章标题进行`crc16`或者`crc32`校验算法，再以 10进制或16进制进行输出成 {slug}

>  `crc16` 算法最大支持 65535 个文章 （个人博客来说已经完全够了）

**Comment by 52Lau** [comment]
wordpress有一个pinyin的插件,它的自动生成是可以拼音或者英文翻译,遇到重复的后面加1 感觉可以参考下
![image](https://user-images.githubusercontent.com/37538641/80664239-d3d0f300-8ac8-11ea-8e86-8369680daac3.png)

wp自己也可以根据时间来生成

![image](https://user-images.githubusercontent.com/37538641/80664217-c0258c80-8ac8-11ea-90f6-fc469022fe3c.png)

**Comment by zhixiangyuan** [comment]
这也是个很强的需求，希望大佬能在下个版本上这个功能
