### ISSUE TITLE
Error executing DDL "create index categories_name on categories (name)" via JDBC Statement

### ISSUE THREAD

**Issue by 52Lau** [halo-dev/halo#809]
org.flywaydb.core.internal.license.FlywayEditionUpgradeRequiredException: Flyway Enterprise Edition or MySQL upgrade required: MySQL 5.6 is no longer supported by Flyway Community Edition, but still supported by Flyway Enterprise Edition.

想请问下,halo现在需要的数据库是什么版本的

**Comment by JohnNiang** [comment]
错误提示中已经说明了，flyway 不支持 MySQL 5.6。后面我们会考虑移除 flyway。

**Comment by 52Lau** [comment]
嗯,所以想问下,现在用什么版本

**Comment by ruibaby** [comment]
> 嗯,所以想问下,现在用什么版本


文档说的很清楚，需要 5.7 以上，不知您是否看了文档。 https://halo.run/archives/install-with-linux.html#修改配置文件

**Comment by 52Lau** [comment]
哦,抱歉,我的失误,感谢你的帮助

在文档系统开发 所需要的环境这一块可以加上说明

**Comment by ruibaby** [comment]
> 哦,抱歉,我的失误,感谢你的帮助
> 
> 在文档系统开发 所需要的环境这一块可以加上说明

好的。
