### ISSUE TITLE
构造器注入方式优化

### ISSUE THREAD

**Issue by liaozan** [halo-dev/halo#811]
翻看代码发现，现在项目中的注入都是通过构造器的方式显式注入的，是不是可以考虑用`lombok`提供的`@RequiredArgsConstructor`注解呢?
`@RequiredArgsConstructor`可以为类生成带有必需参数的构造函数。必填参数可以是final的字段的或者非空的字段，例如`@NonNull`。那样代码看起来会很简洁，而且后续对注入进行修改的时候也不需要改动构造器

**Comment by ruibaby** [comment]
我觉得是可以的。

@JohnNiang John 芳，你怎么看？

**Comment by JohnNiang** [comment]
简化代码的想法肯定是好的，但并非所有地方都适用。至少我认为在这里不适用。Java 至今没有接纳 Lombok 是有原因的。

**Comment by JohnNiang** [comment]
> > 简化代码的想法肯定是好的，但并非所有地方都适用。至少我认为在这里不适用。Java 至今没有接纳 Lombok 是有原因的。
> 
> 愿闻其详

> <http://jnb.ociweb.com/jnb/jnbJan2010.html#controversy>

看看就好，并非绝对。我认可通过 Lombok 去简化 Bean，但拒绝在其他地方使用。
