### ISSUE TITLE
在开启了文章固定链接类型地址为年月日型之后无法设置相同的地址名

### ISSUE THREAD

**Issue by RicrodoZ** [halo-dev/halo#817]
## 我的环境
版本：1.3.2
数据库：H2 1.4.196 (2017-06-10)
运行模式：production
User Agent：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36

---

## 错误日志
无

---

## 期望行为
在设置了文章固定链接类型之后，可以设置相同的地址名

## 当前行为
在开启了文章固定链接类型地址为年月日型之后无法设置相同的地址名
![image](https://user-images.githubusercontent.com/44362358/80868966-2defd500-8cd0-11ea-84ac-7697022de8f1.png)
- 相同的地址名

![image](https://user-images.githubusercontent.com/44362358/80869029-9048d580-8cd0-11ea-813e-d35a662aceba.png)

![image](https://user-images.githubusercontent.com/44362358/80868998-5d9edd00-8cd0-11ea-8345-bac9e4e06114.png)

**Comment by ruibaby** [comment]
你修改文章链接风格是对所有文章生效的，固然不能设置相同的别名

**Comment by ruibaby** [comment]
我看了你的博客，大致理解了你的需求，也就是说 /2020/05/02/leetcode-dailyquestion  和 /2020/02/03/leetcode-dailyquestion 是都可以的。

但是目前很难实现。

**Comment by RicrodoZ** [comment]
好的好的
