### ISSUE TITLE
feat: 数据可视化（类似GitHub那样的热力图）

### ISSUE THREAD

**Issue by homlex** [halo-dev/halo#837]
## 概述

数据可视化

## 动机

1. 方便查看网站访问者的地区，IP等信息，如果可以，后期还希望对访问频率过高的IP进行封锁
2. 对文章发布情况的数据进行可视化展示，比如一个格子就代表这一周/月/年的文章数量，点击格子就可以查看当前周/月/年发布的所有文章
3. 希望对访问者IP也可以进行热力分布图式的统计
4. 可视化不仅管理员可见，对一般访客亦可见（最好展示在归档页或者关于页）

效果图：

![image](https://user-images.githubusercontent.com/48396880/81499893-2bf5c980-9301-11ea-96a3-7a7039d38d93.png)

参考文档地址：https://antv-g2.gitee.io/zh/examples/heatmap/calendar/#calendar

**Comment by cxying** [comment]
私以为1，3，4其实可以自行用js、php就可以实现，可以不依赖官方，对于2可能得靠官方了，原本以为halo接口可能会提供相关数据，然后查了下[API文档](https://api.halo.run/)，但是单一个Authentication就卡住一般访客了，至少也得开放无需认证的查询接口才行（PS:本菜鸡瞎说的，有误轻喷哈2333）
(PPS:感谢大佬我发现了新大陆~  [尝试了下](https://yingserver.cn/archives/ying-acgimg-api)，太好玩了)

**Comment by homlex** [comment]
> 然后查了下[API文档](https://api.halo.run/)，

你也让我发现了新大陆，这个很有用，谢谢

其实初衷是让官方去集成这些功能从而让halo更加丰富，不过官方给了api，似乎可以自己动手了。

**Comment by ruibaby** [comment]
想法很不错，后面我们可能会提供很多小部件，让主题端去做适配。
