### ISSUE TITLE
调用halo接口异常

### ISSUE THREAD

**Issue by PulauBusing** [halo-dev/halo#842]
您好，我发现调用服务接口报异常，麻烦帮忙看下，谢谢。bug截图见图片
![image](https://user-images.githubusercontent.com/34024049/81794605-a1e67480-953d-11ea-8d5f-877d1053354b.png)
![image](https://user-images.githubusercontent.com/34024049/81794646-ad39a000-953d-11ea-81df-503300ac2ce7.png)

**Comment by ruibaby** [comment]
@PulauBusing 博客设置右下角高级设置，启用 API 并设置 Access key。

**Comment by PulauBusing** [comment]
原来，Ok了，非常感谢！

**Comment by Sev1on** [comment]
> @PulauBusing 博客设置右下角高级设置，启用 API 并设置 Access key。

2.8版本的Access key在哪里启用和设置呢

**Comment by JohnNiang** [comment]
Hi @Sev1on , Halo 2.x 目前还没有实现 Access Key 的访问方式。
