### ISSUE TITLE
feat: 希望可以提供特定情况下禁用admin api频率限制的选项

### ISSUE THREAD

**Issue by mark07x** [halo-dev/halo#843]
## 概述

希望可以添加白名单ip，通过此ip访问admin api不限制频率；或者可以干脆提供全局禁止频率限制的选项

## 动机

我在服务器上挂了一个定时运行的脚本来自动读取文章**未审核的评论**，经过特定操作后自动审核。但是经常因此触发频率限制。

## 详细解释

作为admin api真的有必要有这种限制么，我觉得**只有通过账户和密码登录时token的获取和续期时需要有频率限制。通过获取到的token执行操作就不该再限制了吧**。另外，现在是不是还不能用access key来直接访问admin api？我之前好像听说不行，就直接用账号密码来获取admin api的访问token

**Comment by ruibaby** [comment]
请问你是用的是哪个接口？ 目前仅有个别如你说的登录授权有限流的注解。 你应该贴出一个日志看看是否是限流导致你的问题。

另外 access key 只针对 content api，admin api 需要登录后获得 token 和 refresh token。 你说的自己设置的我们后面也有相关计划。 



https://github.com/halo-dev/halo/issues/474

**Comment by ruibaby** [comment]
另外，你这个脚本似乎木有必要。因为后台支持设置为不用审核评论即可显示。

**Comment by mark07x** [comment]
我直接模拟正常登陆，用用户名密码来验证获取admin api的token。
我目前认为问题可能出在token失效时。我正常的查询周期和token的检查周期相差了2分钟，可能是在这两分钟内产生了大量无效token的查询调用，造成限流
我准备先尝试优化脚本的执行逻辑来解决问题

「经过特定操作后自动审核」不代表可以无条件审核，那样的话就失去脚本的意义了

**Comment by ruibaby** [comment]
@mark07x 我先 close 了哦，你再调试调试吧，如果确实是 Halo 的问题，你可以 reopen 这个 issue。
