### ISSUE TITLE
文章页面和附件页面分页功能无效

### ISSUE THREAD

**Issue by vivi-proj** [halo-dev/halo#844]
## 我的环境

版本：1.3.2
数据库：H2 1.4.196 (2017-06-10)
运行模式：production
User Agent：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36

---

## 错误日志

实时日志页面错误，无法加载，

![Y_3C$W2)V2%FYY6O)Z}V`NG](https://user-images.githubusercontent.com/49685338/81931869-5905ed00-961d-11ea-9433-5ea616cbc4f9.png)

---

## 当前行为

![210MG`4{W E_9CN4HXM$HQ2](https://user-images.githubusercontent.com/49685338/81932024-9e2a1f00-961d-11ea-8d75-1c56865c057d.png)
点击上一页下一页，显示内容不变，控制台查看response状态OK，返回的内容是相同内容

**Comment by ruibaby** [comment]
是否使用了某种 CDN，并且没有开启参数重定向跟随。

**Comment by vivi-proj** [comment]
是的，我当时记得要开启，结果忘了，已解决，谢谢
