### ISSUE TITLE
分类列表相关BUG

### ISSUE THREAD

**Issue by wwq0071** [halo-dev/halo#849]
我已经安装了最新版的 Halo！
1. 分类类目把【默认分类】条目删除，博客主页菜单任然显示【默认分类】，点击后页面提示丢失。
2. 新建一个分类“服务”，设置【添加到菜单】，在博客主页上能正常显示，但是后台无法下架菜单“服务”，删除“服务”类别后，博客主页上任然显示，点击后同样提示页面找不到了。。

**Comment by ruibaby** [comment]
菜单是单独度数据，和任何数据都没关联。

**Comment by wwq0071** [comment]
谢谢，已经知道从外观进入菜单里进行管理了！！！
