### ISSUE TITLE
!= string comparison

### ISSUE THREAD

**Issue by sebastiancoteanu** [halo-dev/halo#850]
`if (newActivatedThemeId != activatedThemeId) {
                    activateTheme(newActivatedThemeId);
                }`

The code above existing in ThemeServiceImpl.Java will not give the outcome wanted as it uses != to compare strings. != will always be true because the strings data point to different memory locations and != checks for same reference. Therefore, `!string1.equals(string2)` is recommended here. `.equals` compares values rather than references, so if the strings above have the same value, it will evaluate to false.

**Comment by ruibaby** [comment]
I think you can fix it.

**Comment by sebastiancoteanu** [comment]
> I think you can fix it.

I added a pr in this way.

**Comment by ruibaby** [comment]
merged
