### ISSUE TITLE
feat: 文章引用图片链接时使用相对路径

### ISSUE THREAD

**Issue by a1105013796** [halo-dev/halo#852]
## 概述
文章引用图片链接时使用相对路径，而不是绝对路径
![image](https://user-images.githubusercontent.com/32124539/82031171-09322f00-96cc-11ea-9790-68e0f3c4a514.png)

## 详细解释
以目前的方式，用户更新域名之后，原来文章中的图片就不能正常显示了，如果使用相对路径的话，则可以避免这种情况。

**Comment by ruibaby** [comment]
目前你可以做的有：

1. 手动删除前面的域名。不影响任何东西。
2. 在博客设置的高级设置中，可以禁用全局相对路径，但是会影响部分功能的使用，暂时不推荐。

后面我们会提供两种形式的链接。

> 另外，就算你使用了绝对路径后续需要更换域名，也只需要去数据库批量替换域名即可。论坛有教程。

**Comment by a1105013796** [comment]
好的，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ryan Wang"<notifications@github.com&gt;; 
发送时间: 2020年5月15日(星期五) 下午4:59
收件人: "halo-dev/halo"<halo@noreply.github.com&gt;; 
抄送: "呐。"<1105013796@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [halo-dev/halo] feat: 文章引用图片链接时使用相对路径 (#852)





 
目前你可以做的有：
  
手动删除前面的域名。不影响任何东西。
 
在博客设置的高级设置中，可以禁用全局相对路径，但是会影响部分功能的使用，暂时不推荐。
  
后面我们会提供两种形式的链接。
  
另外，就算你使用了绝对路径后续需要更换域名，也只需要去数据库批量替换域名即可。论坛有教程。
