### ISSUE TITLE
feat: 文章版本控制

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#857]
## 概述

对文章内容进行版本控制。

## 动机

方便查阅每一篇文章的修改记录，也可以退回到某个版本。

## 详细解释

后端：

1. 需要一张 post_history 表。基本的表字段有 `id`，`post_id`，`content`，`version`。
2. 在保存文章之前需要先保存到 post_history 表。

前端：

版本差异展示可以使用 https://github.com/rtfpessoa/diff2html

**Comment by 52Lau** [comment]
其实不建议这样做,因为在大部分Wordpress主题里面,都提供了,数据库瘦身功能,针对WP的文章修订给关掉了,所以在halo里面没有必要再给数据加负了(h2比使用mysql快多了,哈哈)

**Comment by ruibaby** [comment]
> 其实不建议这样做,因为在大部分Wordpress主题里面,都提供了,数据库瘦身功能,针对WP的文章修订给关掉了,所以在halo里面没有必要再给数据加负了(h2比使用mysql快多了,哈哈)

也不会做成和 wp 那样，没意义。哈哈哈哈哈哈

**Comment by 52Lau** [comment]
@ruibaby 是的,玩WP也两年了,折腾不下去了,很喜欢halo这种开箱即用的感觉

**Comment by ruibaby** [comment]
> @ruibaby 是的,玩WP也两年了,折腾不下去了,很喜欢halo这种开箱即用的感觉

我们的目标就是做到尽可能的开箱即用，但是目前还差很远。当然也不是一味的堆功能，没有意义。目前我们短期的目标就是针对已有功能做优化和改进。

**Comment by JohnNiang** [comment]
得提上日程了。

**Comment by xiaofsu** [comment]
😃😃up!up!

**Comment by WenyinWei** [comment]
感觉确实没太大必要，对大多数文章作者不需要版本控制，最多融合 git 作一个可视化插件就可以了。对项目维护者而言，拒绝不必要的功能也很重要。如果需求比较紧急的话，可以手动把整个 .bash 文件夹 git 了。不过，让 .halo 文件夹自带 git 是个好主意。

**Comment by ruibaby** [comment]
> 感觉确实没太大必要，对大多数文章作者不需要版本控制，最多融合 git 作一个可视化插件就可以了。对项目维护者而言，拒绝不必要的功能也很重要。如果需求比较紧急的话，可以手动把整个 .bash 文件夹 git 了。不过，让 .halo 文件夹自带 git 是个好主意。

嗯，这是我自己一个待定的功能，也不是一定会做。
