### ISSUE TITLE
有mysql原生sql吗，想搭建基于mysql的

### ISSUE THREAD

**Issue by xduperdu** [halo-dev/halo#858]
有mysql原生sql吗，想搭建基于mysql的

**Comment by ruibaby** [comment]
@xduperdu 请先看文档。

**Comment by cxying** [comment]
> 有mysql原生sql吗，想搭建基于mysql的

mysql建一个名为 halodb 的空数据库，然后启动就可以了，表会自动建
![1](https://img-blog.csdnimg.cn/20200329211807502.png)
