### ISSUE TITLE
feat: 自定义标签返回的Variable名称可以由传递过来

### ISSUE THREAD

**Issue by 52Lau** [halo-dev/halo#862]
## 概述

自定义标签返回的Variable名称可以由传递过来

## 动机

在主题开发的时候,首页轮播用到了postTag--latest最新的文章来充当轮播的内容,由于返回的是posts 和index.ftl的变量 posts 存在冲突(因为都是在index.ftl当中)

![image](https://user-images.githubusercontent.com/37538641/82167069-2560e680-98ed-11ea-88a2-f6251da1d3bd.png)

![image](https://user-images.githubusercontent.com/37538641/82167079-2d208b00-98ed-11ea-8e44-d8105336d2cb.png)

**Comment by ruibaby** [comment]
好主意，目前你可以通过命名空间的特性来解决此问题。

**Comment by 52Lau** [comment]
嗯
