### ISSUE TITLE
feat: 分类是否可以加上状态

### ISSUE THREAD

**Issue by 52Lau** [halo-dev/halo#863]
## 概述

在categories.ftl页面中 “该模板渲染分类列表页面，用于展示用户在后台添加的所有分类目录。”
会把一些临时性的分类也展示出来,除非是删掉,这样感觉有点不是特别方便,所以想有一个状态字段来区分,可能会涉及文章的分类信息查询等

**Comment by JohnNiang** [comment]
这样的需求暂时不会考虑做。
