### ISSUE TITLE
feat: 静态存储提供私密功能

### ISSUE THREAD

**Issue by cxying** [halo-dev/halo#865]
## 概述
希望静态存储能提供私密功能，如果设置为私密的文件，只能通过后台进行访问/下载
类似于文章草稿的预览，或者系统备份的时候生成ott来进行访问/下载
而每设置的可以无限制访问/下载

## 动机
**可能说得有点啰嗦，请见谅**
1.无意中发现，halo静态存储其实挺好用的，我在docker跑了一个php-fpm，然后把它挂在到halo静态存储的所在目录，就实现了可以随时通过halo进行管理php脚本，随时可以上传php脚本来运行（也就是说我可以任意地添加动态页面了，很爽~）
2.但是在这其中就出现了一个问题：我上传的文件只能访问，而无法随时下载修改，因为每次访问就直接执行了php脚本了，于是我想了一个办法，建立多重目录，然后结合nginx的地址匹配，比如在静态储存建立了/php/open/a.php，然后nginx匹配/open/*.php，那么我访问domain.com/open/a.php的时候就会执行php脚本，当我想修改脚本的时候就可以访问domain.com/php/open/a.php下载脚本进行修改
3.**前面都是铺垫，正文来了：** 因为我的无理需求=。=就导致了任何人都可以直接下载我的php脚本，这是有一定危险性的，同时也意味着php脚本里不能够有任何敏感信息，所以希望有个限制，至少是我能够控制静态存储的哪些文件是限制访问的，防止别人下载了我的代码，于是乎，就有了这个无理的Issue...捂脸.jpg
想了下，如果要实现这个功能，可能得建新表或者加字段（没看源码不知道现在有没有这表），专门储存静态存储的信息，好像也有点小题大做...可能也不太好改=。=

**感谢耐心看完本问题**

## 详细解释
上面动机应该解释得差不多了

**Comment by ruibaby** [comment]
1. 已经做了在线修改，https://github.com/halo-dev/halo-admin/pull/152
2. 现在没有建立表，一切的操作都基于文件操作。
3. 你可以考虑使用 Nginx Basic 认证来满足你的需求。比如你在静态存储新建一个专门放你 php 文件的目录，用 Nginx 对这个目录或者说路径加密。

**Comment by cxying** [comment]
好迅速  
1.好评，坐等新版本  
2.我也觉得大概率是这么操作的
3.因为我的php服务器的目录是挂载到halo的静态存储目录的，但是静态存储并没有任何限制措施，那么任何人也可以通过halo进行下载吧？当然，前面这句话是基于我目前的知识水平，我得去研究下Nginx Basic才行 捂脸.jpg

**Comment by ruibaby** [comment]
@cxying 

不，在 Nginx 层就可以将其拦截掉。总之，可以实现你又要访问 php 页面的需求，也可以禁止他人下载 php 源文件。

**Comment by cxying** [comment]
@ruibaby 
好的，蟹蟹大佬，我去尝试下
