### ISSUE TITLE
冗余注解

### ISSUE THREAD

**Issue by CNYuYang** [halo-dev/halo#867]
Application类的：
@EnableJpaAuditing 代码没有用到审查
@EnableScheduling 代码没有定时任务
查看了原代码，发现这两个注解并没有起到该有的作用，且在很早的版本中就一直存在。

**Comment by ruibaby** [comment]
审计早期其实是有用到的，但是都免去掉之后没有取消注解。定时任务确实没有。

你可以考虑对其修改并提交 pull request，如果可以的话。

**Comment by CNYuYang** [comment]
好的，我先把代码都看完。
