### ISSUE TITLE
CDN缓存问题

### ISSUE THREAD

**Issue by Guozht** [halo-dev/halo#868]
现象：使用再博客后台添加CDN（七牛）资源之后，在七牛云后台删除上传的资源，转到博客后台之后资源并没有随之删除，之后手动在博客后台删除时提示资源找不到，不能删除。导致博客后台显示许多并不存在的资源。
![image](https://user-images.githubusercontent.com/31638230/82457790-6f61ec00-9ae8-11ea-9c78-544c090932e9.png)
![image](https://user-images.githubusercontent.com/31638230/82457855-8a346080-9ae8-11ea-89e0-a40faf1602ae.png)
期望：博客与七牛云同步，或者博客后台可以删除这些不存在的资源

**Comment by ruibaby** [comment]
很难实现，现在不管以怎样的方式上传，都是将文件信息存储在数据表中的。

**Comment by Guozht** [comment]
那可以在删除资源失败的时候把数据库也删除一下啊，现在是删除七牛云资源失败时直接提示失败跳过了数据库删除步骤，导致博客后台数据全乱了，而且是H2数据库都不好直接手动操作数据库。

**Comment by ruibaby** [comment]
> 那可以在删除资源失败的时候把数据库也删除一下啊，现在是删除七牛云资源失败时直接提示失败跳过了数据库删除步骤，导致博客后台数据全乱了，而且是H2数据库都不好直接手动操作数据库。

https://github.com/halo-dev/halo/blob/master/src/main/java/run/halo/app/service/impl/AttachmentServiceImpl.java#L134-L137

这里是先删除数据库的数据，然后再去删除物理文件的。

**Comment by ruibaby** [comment]
不过这种情况确实需要优化，等待下个版本吧。

**Comment by Guozht** [comment]
刚才又测试了一下，批量删除的时候会把第一个资源在数据库删除，之后提示错误略过了之后的文件。但是我这有69页资源~~~ 69*18个资源需要手动删除~~~天啦噜~~~崩溃ING

**Comment by Guozht** [comment]
资源批量操作  建议增加一个全部选中按钮。。。一个一个点太费劲了

**Comment by ruibaby** [comment]
@Guozht 抱歉，初期没有考虑到您这种极端的需求。不过你目前所遇到的所有缺陷，我们心里比任何人都有数，所以请耐心等待吧。
