### ISSUE TITLE
在Mac环境下导出的文件会存在.DS_Store

### ISSUE THREAD

**Issue by 52Lau** [halo-dev/halo#872]
com.alibaba.fastjson.JSONException: syntax error, pos 1, line 1, column 2PK�S�P	halo-dev/PKPK�S�Phalo-dev/.DS_Store�=

![image](https://user-images.githubusercontent.com/37538641/82724924-01960a00-9d0c-11ea-99a3-08f62ba8964f.png)

**Comment by 52Lau** [comment]
![image](https://user-images.githubusercontent.com/37538641/82725711-525c3180-9d11-11ea-814d-acad03209aa1.png)
上传完之后,后台日志也是走完了,但是页面好像不会自动跳转,刷新页面之后,又重新安装....
![image](https://user-images.githubusercontent.com/37538641/82725753-c3034e00-9d11-11ea-90c4-b56815d8f91c.png)

**Comment by ruibaby** [comment]
是还在安装的时候你就手动去刷新了吗？

**Comment by 52Lau** [comment]
没有,是等了很久,

**Comment by ruibaby** [comment]
建议清空 .halo，然后重试。

**Comment by 52Lau** [comment]
嗯

**Comment by 52Lau** [comment]
确实和这个目录有关,已经好了,

**Comment by 52Lau** [comment]
对于数据的导入能在非安装的时候实现导入么

**Comment by ruibaby** [comment]
> 对于数据的导入能在非安装的时候实现导入么

不能，安装之后就不行了。主要是为了原数据安全。
