### ISSUE TITLE
halo.run 打不开了

### ISSUE THREAD

**Issue by zyhui98** [halo-dev/halo#877]

**Comment by ruibaby** [comment]
可能只针对某个地区，我这边是正常的。。。

**Comment by zyhui98** [comment]
zhuyunhui07454:AppApollo jonny$ wget https://halo.run
--2020-05-28 11:46:12--  https://halo.run/
正在解析主机 halo.run (halo.run)... 104.31.93.90, 104.31.92.90
正在连接 halo.run (halo.run)|104.31.93.90|:443...

**Comment by ruibaby** [comment]
最近确实有很多人反应打不开，后面我们会考虑换一家服务商。
