### ISSUE TITLE
gradle在idea编译，一直下载不了idea的包

### ISSUE THREAD

**Issue by zyhui98** [halo-dev/halo#879]
建议加上

    maven {
        url 'http://dl.bintray.com/jetbrains/intellij-plugin-service'
    }

**Comment by JohnNiang** [comment]
请问，具体是什么包下载出错了呢

**Comment by zyhui98** [comment]
org.jetbrains.plugins.gradle.tooling.builder.ModelBuildScriptClasspath
应该是idea的插件，下载不了。加上那个就可以了。

**Comment by ruibaby** [comment]
这应该和 Halo 的依赖无关。

**Comment by zyhui98** [comment]
是的， 和halo无关。idea的问题。

**Comment by sunnyswag** [comment]
最后运行成的配置文件如下：
```
repositories {
    mavenLocal()
//    mavenCentral()
    maven {
        url 'http://maven.aliyun.com/nexus/content/groups/public/'
    }
    jcenter()
}
```

**原因未知**<br>
猜测可能如下：
1、之前本地跑过 halo 不过后来删了，加载的可能是本地的包
2、没有开代理，一直显示 download 但是没显示是从 aliyun 下载的，下载时没显示任何前缀
3、多折腾折腾，可能就好了...
