### ISSUE TITLE
域名访问install后台报错，ip访问是正常的

### ISSUE THREAD

**Issue by jackyjinjing** [halo-dev/halo#896]

**Comment by jackyjinjing** [comment]
![image](https://user-images.githubusercontent.com/19622894/83935499-b2aca200-a7ec-11ea-8f61-1148111533fd.png)
截图的ip和域名的ip不一致

**Comment by ruibaby** [comment]
https://jackyblog.ink/admin/index.html#/install

请问哪里不正常？

**Comment by jackyjinjing** [comment]
> https://jackyblog.ink/admin/index.html#/install
> 
> 请问哪里不正常？

找到问题了，我带了端口号访问的，谢谢
