### ISSUE TITLE
编辑器邮箱格式解析错误。

### ISSUE THREAD

**Issue by xiaofsu** [halo-dev/halo#898]
版本：1.3.2
数据库：H2 1.4.196 (2017-06-10)
运行模式：production
User Agent：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36

在使用编辑器编辑文章并发布时，和邮箱在一行的文字错误的被解析成了邮箱格式。
![image](https://user-images.githubusercontent.com/46067472/84010848-cea87300-a9a7-11ea-9114-ba532bee8327.png)

---

**Comment by ruibaby** [comment]
在 `用户：` 与邮箱之间加个空格应该可以解决此问题。

**Comment by xiaofsu** [comment]
OK，哈哈哈是可以的，你看合适的时机就关闭此issue吧...
这是markdown语法建议的吗？

**Comment by ruibaby** [comment]
是的。
