### ISSUE TITLE
后台附件中上传的图，如何获得它对应的缩略图

### ISSUE THREAD

**Issue by LIlGG** [halo-dev/halo#902]
如标题。目前我在附件中上传一个图片，无论是上传到本地或者阿里云等等上。

然后我想在前端能够获取到该图对应的缩略图，阿里云我已经配置了缩略图方案，但缺点是我要在主题中硬编写图片处理策略。当使用本地图片或者其他云的图片时这个策略就不会生效。

之所以发起一个问题而不是功能，是因为我不太了解是不是原先有这个功能，而我没有找到`已经搜索过issue和文档等` 

如果没有的话我希望能够添加一个获取图片对应缩略图的功能，毕竟有时候需要进行图片懒加载。

**Comment by ruibaby** [comment]
@LIlGG 目前没有办法解决。后台列表是展示的缩略图，你可以考虑右键复制图片链接。

**Comment by LIlGG** [comment]
> @LIlGG当前没有办法解决。后台列表是展示的前缀，你可以考虑快捷复制图片链接。

但如果右键复制的话实际上也是属于硬编码了。因为我在设计一个主题，想对图片使用懒加载模式，但懒加载需要一个缩略图作为初始背景（如果用data那种灰色的代替会显得不好看）。
以后有计划会添加一个获取图片缩略图的实体属性吗？

**Comment by ruibaby** [comment]
@LIlGG 你有没有好的想法呢？

**Comment by LIlGG** [comment]
> @LIlGG 你有没有好的想法呢？

我觉得可能有很多种解决办法

1. 上传本地文件时自动生成一个缩略图，缩略图保存到特定文件夹下，后台展示时使用生成的缩略图。缩略图对应属性可以根据图片来源`这个可以判断的吧`来拼接后缀生成对应的缩略图url，如果是本地就写入生成的缩略图地址，如果是其他云的可以拼接用户设置的图片处理策略。
2. 无论是云端的还是本地的，都在本地生成一个缩略图，然后赋予给缩略图属性并保存在库里。

我对这块也不是很熟悉，就只能提这么两处意见。当然，最好可以在附件里面设置是否生成缩略图

**Comment by LIlGG** [comment]
@ruibaby 更好的情况是用户设置文章图的时候，有一个功能按钮，就叫做缩略图设置。因为一般来说附件也不一定都需要缩略图，只有文章中才使用。

**Comment by ruibaby** [comment]
大概懂你的意思了，其实目前也不是没有解决方案，你可以在前台判断目前所用的上传方式，然后拼接缩略图链接。

伪代码：

```html
<#if options.attachment_type == 'uposs'>
   ${post.thumbnail} + ${options. oss_upyun_thumbnail_style_rule}
<#elseif options.attachment_type == 'qiniuoss'>
   // do something
</#if>
```

但是这样做并不是很推荐，不确定性太高了。后面我们会考虑一下你的建议。另外，为啥懒加载的图不设置为一个固定的呢？

**Comment by LIlGG** [comment]
@ruibaby 嗯嗯。非常感谢！！但这种做法无法解决本地上传的图获取缩略图。。不过我可以暂时用它来代替目前的硬编码。
实际上刚开始我也是采用一个固定的懒加载图。但实际效果很不好，一般由于网络关系以及原图太大，在滚动到对应的图上时它可能还是显示那个固定的懒加载图，直到原图加载完毕，然后图片突然变成另外一个图，就显得特别突兀。。如果有对应图的缩略图版本，我就可以预先加载一个模糊的版本，既能达到最低要求，也不会影响视觉效果。

**Comment by ruibaby** [comment]
@LIlGG 本地上传的方式其实也生成了缩略图，我记得应该是文件名_thumb.后缀。其实懒加载的图片处理方式有很多，你都可以试一下。你的意见我们也会考虑的。

**Comment by LIlGG** [comment]
@ruibaby 嗯嗯。很感谢很感谢！这么晚了还在回复。真的很不容易。。另外我想再问问，插件功能目前有计划吗？比较在意这个。🥺

**Comment by ruibaby** [comment]
> @ruibaby 嗯嗯。很感谢很感谢！这么晚了还在回复。真的很不容易。。另外我想再问问，插件功能目前有计划吗？比较在意这个。🥺

我们都很在意，这是下一个大的目标，但是我们现在所有核心开发工作都比较忙，没有时间集中精力来研究插件机制。后面一定会有的。

**Comment by ruibaby** [comment]
> @ruibaby 好。辛苦了！我会积极关注你们的。Java我也懂一些，如果后续有需要，希望我能替你们分担一些！

嗯好，其实附件这块本来也打算重构，你这个issue我就暂时先关掉了。加油完善你的主题哦，后面可以上架到官网上去。

**Comment by LIlGG** [comment]
刚刚找到了本地的缩略图，应该是 文件名-thumbnail.后缀。
