### ISSUE TITLE
文章的元数据怎么调用呢?

### ISSUE THREAD

**Issue by 52Lau** [halo-dev/halo#903]
在发布文章的时候有元数据可以自己添加,在主题开发文档上,没有关于元数据这一块的.能在页面上调用么?

**Comment by ruibaby** [comment]
在文章列表：

```
${post.metas.key}
```

在文章页面：

```
${metas.key}
```

抱歉，这块的文档还没有完善。

**Comment by 52Lau** [comment]
好的,感谢你的帮助

**Comment by ruibaby** [comment]
https://github.com/halo-dev/halo-theme-official

这个主题两个调用方式都用到了，你可以参考下。

**Comment by 52Lau** [comment]
好
