### ISSUE TITLE
feat: 是否考虑在评论的api接口中增加html格式

### ISSUE THREAD

**Issue by fuzui** [halo-dev/halo#907]
## 概述

希望在connect api的评论列表接口中，可以有像文章详情`formatContent`字段和日志列表中`content`字段一样返回html格式的内容。

## 动机

在其他应用开发api调用时可以省去markdown转html这一步。

## 详细解释

例如文章详情拥有`formatContent`和`originalContent`两个字段；
例如日记列表拥有`content`和`sourceContent`两个字段；
因评论也支持markdown，故希望评论列表也可以拥有两个这样的字段。

**感谢halo这个优秀的开源项目！**

**Comment by ruibaby** [comment]
Halo 2 的评论现在支持 raw 和 content。

/close
