### ISSUE TITLE
域名带端口 后台跳转失败

### ISSUE THREAD

**Issue by samondlee** [halo-dev/halo#909]
NGINX 使用官方默认配置 反代 了halo

格式为 xxx.com:1234/

当再xxxx.com:1234/admin 回车时halo会自动跳转到 xxxx.com/admin/index.html 而不是xxxx.com:1234/admin/index.html导致跳转失败，需要手动加入端口号。

**Comment by ruibaby** [comment]
请提供你的配置。

**Comment by samondlee** [comment]
```
server
    {
        listen 1234;
        listen [::]:1234;
        server_name halo.xxxx.cn halo.xxxx.moe halo.xxxx.moe;


	client_max_body_size 1024m;

    location / {
        proxy_set_header HOST $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_pass http://127.0.0.1:8090/;
    }
	
	access_log off;
}
```

**Comment by ruibaby** [comment]
```
server
    {
        listen 1234;
        listen [::]:1234;
        server_name halo.xxxx.cn halo.xxxx.moe halo.xxxx.moe;


	client_max_body_size 1024m;

    location / {
        proxy_set_header HOST $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_pass http://127.0.0.1:8090;
    }
	
	access_log off;
}
```

试试。

**Comment by samondlee** [comment]
> ```
> server
>     {
>         listen 1234;
>         listen [::]:1234;
>         server_name halo.xxxx.cn halo.xxxx.moe halo.xxxx.moe;
> 
> 
> 	client_max_body_size 1024m;
> 
>     location / {
>         proxy_set_header HOST $host;
>         proxy_set_header X-Forwarded-Proto $scheme;
>         proxy_set_header X-Real-IP $remote_addr;
>         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
> 
>         proxy_pass http://127.0.0.1:8090;
>     }
> 	
> 	access_log off;
> }
> ```
> 
> 试试。

内容看起来一样，我了试一下，并且清空了 浏览器缓存，仍然跳转不带端口的地址

**Comment by caltong** [comment]
遇到同样的问题，似乎/admin 跳转的默认是80端口，如果nginx反代自定义的非80端口就会出问题

**Comment by kfyidrig** [comment]
> ```
> server
>     {
>         listen 1234;
>         listen [::]:1234;
>         server_name halo.xxxx.cn halo.xxxx.moe halo.xxxx.moe;
> 
> 
> 	client_max_body_size 1024m;
> 
>     location / {
>         proxy_set_header HOST $host;
>         proxy_set_header X-Forwarded-Proto $scheme;
>         proxy_set_header X-Real-IP $remote_addr;
>         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
> 
>         proxy_pass http://127.0.0.1:8090/;
>     }
> 	
> 	access_log off;
> }
> ```
> 
> @ruibaby
> 你好 配置如上
> 
> 并且在后台
> http://halo.xxxx.xxx:1234/admin/index.html#/system/options
> 
> 的 博客地址： 也是配置了端口的http://halo.xxxx.xxx:1234

博客的地址不需要后面的1234端口，访问不带端口的就好了

**Comment by samondlee** [comment]
> > ```
> > server
> >     {
> >         listen 1234;
> >         listen [::]:1234;
> >         server_name halo.xxxx.cn halo.xxxx.moe halo.xxxx.moe;
> > 
> > 
> > 	client_max_body_size 1024m;
> > 
> >     location / {
> >         proxy_set_header HOST $host;
> >         proxy_set_header X-Forwarded-Proto $scheme;
> >         proxy_set_header X-Real-IP $remote_addr;
> >         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
> > 
> >         proxy_pass http://127.0.0.1:8090/;
> >     }
> > 	
> > 	access_log off;
> > }
> > ```
> > 
> > 
> > @ruibaby
> > 你好 配置如上
> > 并且在后台
> > http://halo.xxxx.xxx:1234/admin/index.html#/system/options
> > 的 博客地址： 也是配置了端口的http://halo.xxxx.xxx:1234
> 
> 博客的地址不需要后面的1234端口，访问不带端口的就好了

80端口是封的必须得设置端口，另外如果后台博客地址去掉端口则前端js等资源显示不出来。

**Comment by kfyidrig** [comment]
80端口不可用的话，你使用的NAT吧？？？

NAT网络环境下，你运行jar程序之后，jar程序会监听一个端口，你好像是1234端口，这个端口对于的IP是所有ip，也就是外网内网127.0.0.1都可以访问

你此时用nignx反代，conf里面也应该监听1234端口，也就是 proxy_pass http://127.0.0.1:8090/;

这个1234端口就已经被用了，此时你可以通过nignx代理访问博客，默认的是外网80端口，也就是通过你的域名，可以直接访问

但是你说NAT的话，外网和你的机子端口会存在一个映射，你可以定义一个端口映射，内网80，外网不要是1234就好了

nat不支持http跳转https

**Comment by caltong** [comment]
> > > ```
> > > server
> > >     {
> > >         listen 1234;
> > >         listen [::]:1234;
> > >         server_name halo.xxxx.cn halo.xxxx.moe halo.xxxx.moe;
> > > 
> > > 
> > > 	client_max_body_size 1024m;
> > > 
> > >     location / {
> > >         proxy_set_header HOST $host;
> > >         proxy_set_header X-Forwarded-Proto $scheme;
> > >         proxy_set_header X-Real-IP $remote_addr;
> > >         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
> > > 
> > >         proxy_pass http://127.0.0.1:8090/;
> > >     }
> > > 	
> > > 	access_log off;
> > > }
> > > ```
> > > 
> > > 
> > > @ruibaby
> > > 你好 配置如上
> > > 并且在后台
> > > http://halo.xxxx.xxx:1234/admin/index.html#/system/options
> > > 的 博客地址： 也是配置了端口的http://halo.xxxx.xxx:1234
> > 
> > 
> > 博客的地址不需要后面的1234端口，访问不带端口的就好了
> 
> 80端口是封的必须得设置端口，另外如果后台博客地址去掉端口则前端js等资源显示不出来。

是nginx反代配置的问题，加上这个` $server_port `就可以保留端口跳转了
`proxy_set_header Host $host:$server_port; # 保留端口跳转`
内网环境实测可行，但是加上一层路由器端口转发又会出现新的端口错误（重定向的端口是nginx的监听端口）

**Comment by samondlee** [comment]
> > > > ```
> > > > server
> > > >     {
> > > >         listen 1234;
> > > >         listen [::]:1234;
> > > >         server_name halo.xxxx.cn halo.xxxx.moe halo.xxxx.moe;
> > > > 
> > > > 
> > > > 	client_max_body_size 1024m;
> > > > 
> > > >     location / {
> > > >         proxy_set_header HOST $host;
> > > >         proxy_set_header X-Forwarded-Proto $scheme;
> > > >         proxy_set_header X-Real-IP $remote_addr;
> > > >         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
> > > > 
> > > >         proxy_pass http://127.0.0.1:8090/;
> > > >     }
> > > > 	
> > > > 	access_log off;
> > > > }
> > > > ```
> > > > 
> > > > 
> > > > @ruibaby
> > > > 你好 配置如上
> > > > 并且在后台
> > > > http://halo.xxxx.xxx:1234/admin/index.html#/system/options
> > > > 的 博客地址： 也是配置了端口的http://halo.xxxx.xxx:1234
> > > 
> > > 
> > > 博客的地址不需要后面的1234端口，访问不带端口的就好了
> > 
> > 
> > 80端口是封的必须得设置端口，另外如果后台博客地址去掉端口则前端js等资源显示不出来。
> 
> 是nginx反代配置的问题，加上这个`$server_port`就可以保留端口跳转了
> `proxy_set_header Host $host:$server_port; # 保留端口跳转`
> 内网环境实测可行，但是加上一层路由器端口转发又会出现新的端口错误（重定向的端口是nginx的监听端口）

哇 成功解决，感谢。。。。
