### ISSUE TITLE
CheckStyle.xml相关优化

### ISSUE THREAD

**Issue by caochenhins** [halo-dev/halo#913]
1.删除多余TypecastParenPad 
CheckStyle.xml文件第90行 删除 
`
<module name="TypecastParenPad">
`

2.引入SuppressionCommentFilter
希望作者在Checkstyle.xml 25行 加上 以下过滤器, 可以自定义忽略一些规则
`<module name="SuppressionCommentFilter">`
            `<property name="offCommentFormat" value="CHECKSTYLE:CLOSE"/>`
            `<property name="onCommentFormat" value="CHECKSTYLE:OPEN"/>`
            `<property name="checkFormat" value=".*"/>`
  `</module>`

**Comment by JohnNiang** [comment]
好的，我们的测试后再考虑修改。

**Comment by caochenhins** [comment]
好的, 谢谢
1.删除多余TypecastParenPad
是指 最新版源码中出现了2个相同的module, 不影响使用, 但是建议把保留一条即可.
`<module name="TypecastParenPad"/>`
`<module name="TypecastParenPad"/>`
