### ISSUE TITLE
开发者选项 实时日志 功能优化 日志滚动条默认定位到底部

### ISSUE THREAD

**Issue by caochenhins** [halo-dev/halo#914]
开发者选项 实时日志 功能优化 自动滚动到最后一行

该页面:
src\views\system\developer\tabs\RuntimeLogs.vue

第64行, 加入如下代码可实现:
  updated() {
    // 滚动条定位到底部
    this.$el.querySelector('.CodeMirror-scroll').scrollTop = this.$el.querySelector('.CodeMirror-scroll').scrollHeight
  },

**Comment by ruibaby** [comment]
@caochenhins 你可以考虑提一个 pull request

**Comment by caochenhins** [comment]
好的, 已提交 @ruibaby
