### ISSUE TITLE
注册成服务时无法读取配置文件信息

### ISSUE THREAD

**Issue by Alex-Zhuo** [halo-dev/halo#923]
## 我的环境
版本：1.3.2
数据库：MySQL 5.7.18-20170830-log
运行模式：production
User Agent：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36

---

## 错误日志

---

## 期望行为
在application.yaml中配置了数据库以及端口信息，halo用户使用java -jar 命令启动时一切正常，当注册成为系统服务时，端口变成了默认的8090。

**Comment by JohnNiang** [comment]
```diff
[Unit]
Description=Halo Service
Documentation=https://halo.run
After=network-online.target
Wants=network-online.target

[Service]
+User=halo
Type=simple
ExecStart=/usr/bin/java -server -Xms256m -Xmx256m -jar YOUR_JAR_PATH
ExecStop=/bin/kill -s QUIT $MAINPID
Restart=always
StandOutput=syslog

StandError=inherit

[Install]
WantedBy=multi-user.target
```

**Comment by Alex-Zhuo** [comment]
> ```shell
> sudo vim /etc/systemd/system/halo.service
> ```
> 
> ```diff
> [Unit]
> Description=Halo Service
> Documentation=https://halo.run
> After=network-online.target
> Wants=network-online.target
> 
> [Service]
> +User=halo
> Type=simple
> ExecStart=/usr/bin/java -server -Xms256m -Xmx256m -jar YOUR_JAR_PATH
> ExecStop=/bin/kill -s QUIT $MAINPID
> Restart=always
> StandOutput=syslog
> 
> StandError=inherit
> 
> [Install]
> WantedBy=multi-user.target
> ```

还是不行。
配置文件如下（修改后已执行systemctl daemon-reload）：
![image](https://user-images.githubusercontent.com/32348122/85005213-0de67900-b18b-11ea-9930-423ccbd5a8a4.png)

**Comment by JohnNiang** [comment]
请把 “+” 号去掉。

**Comment by Alex-Zhuo** [comment]
> 请把 “+” 号去掉。

还是一样的

**Comment by Alex-Zhuo** [comment]
已解决，感谢，之前可能是NGINX缓存导致
