### ISSUE TITLE
支持二级路由的配置吗

### ISSUE THREAD

**Issue by Cenergy** [halo-dev/halo#927]
比如将halo部署在domain.com/blog/ 这个路由下

**Comment by ruibaby** [comment]
https://github.com/halo-dev/halo/issues/702

**Comment by Cenergy** [comment]
感谢您的回答，支持！😄 👍

**Comment by ruibaby** [comment]
> 感谢您的回答，支持！😄 👍  

那这个 issue 我就先关了哦。
