### ISSUE TITLE
feat: 希望增加设置个人所在地址

### ISSUE THREAD

**Issue by Stars-One** [halo-dev/halo#931]
个人信息中默认显示地址的是北京海淀 希望增加设置个人所在地的选项

**Comment by ruibaby** [comment]
没有明白你的意思。

**Comment by Stars-One** [comment]
![](https://img2020.cnblogs.com/blog/1210268/202006/1210268-20200623111446001-1956504508.png)

https://img2020.cnblogs.com/blog/1210268/202006/1210268-20200623111446001-1956504508.png

如图,默认显示的是北京海淀

**Comment by ruibaby** [comment]
请去主题作者仓库提交 issue，这和 Halo 无关。https://github.com/CodeLunatic/halo-theme-simple-bootstrap

**Comment by Stars-One** [comment]
他使用的模版变量`settings.user_location`,那数据不是由halo提供的吗?,如图
![](https://img2020.cnblogs.com/blog/1210268/202006/1210268-20200623112135645-1305455645.png)

https://img2020.cnblogs.com/blog/1210268/202006/1210268-20200623112135645-1305455645.png

**Comment by JohnNiang** [comment]
在主题设置处，可以配置哦。

**Comment by Stars-One** [comment]
感谢@JohnNiang  ok,已解决
