### ISSUE TITLE
run.halo.app.exception.ThemePropertyMissingException: /home/xxx/.halo/templates/themes/anatole 没有说明文件 

### ISSUE THREAD

**Issue by lesvere** [halo-dev/halo#937]
gradle build -x test
java -jar build/libs/halo-1.3.2.jar

然后就报错了

cd /home/xxx/.halo/templates/themes/anatole
ls -la
drwxr-xr-x 3 xxx xxx 4096 Jun 30 10:51 .
drwxr-xr-x 3 xxx xxx 4096 Jun 30 10:44 ..
drwxr-xr-x 5 xxx xxx 4096 Jun 30 10:51 halo-theme-material

**Comment by ruibaby** [comment]
你的 anatole 主题文件夹为什么会有另外一个主题，因为没有 theme.yaml，所以抛异常。

目前最简单的解决方法，删除 `/home/xxx/.halo/templates/themes`，重启。

**Comment by lesvere** [comment]
☁  themes  pwd
/home/xxx/.halo/templates/themes
☁  themes  ls -la
total 12
drwxr-xr-x 3 xxx xxx 4096 Jun 30 11:02 .
drwxr-xr-x 3 xxx xxx 4096 Jun 30 10:44 ..


依旧报错如下。

我在想，我自己cone一个主题，在哪里修改主题名称？

**Comment by ruibaby** [comment]
https://halo.run/archives/develop-application-start#%E5%85%8B%E9%9A%86%E9%A1%B9%E7%9B%AEoptional

**Comment by lesvere** [comment]
> https://halo.run/archives/develop-application-start#%E5%85%8B%E9%9A%86%E9%A1%B9%E7%9B%AEoptional

敬大佬，万分感谢！
