### ISSUE TITLE
宝塔面板，liunx，部署halo，打不开

### ISSUE THREAD

**Issue by v28321** [halo-dev/halo#938]
- 我已经安装了最新版的 Halo
  - 我已经搜索了已有的 Issues 列表中有关的信息
  - 我已经搜索了论坛中有关的信息：https://bbs.halo.run
  - 我已经阅读了 Halo 的 FAQ：https://halo.run/archives/other-faq
-->

 有没有宝塔安装的教程，

**Comment by ruibaby** [comment]
你提供的信息没法为你判断。
