### ISSUE TITLE
开发者你们好，请问附件怎么上传七牛云

### ISSUE THREAD

**Issue by kfyidrig** [halo-dev/halo#939]
开发者你们好，我想请教两件事情：
1.博客支持cdn吗？？
2.我使用h2数据库运行了博客jar程序，为什么目录没看到数据库文件，还有上传的附件？

**Comment by kfyidrig** [comment]
看到了，在系统设置的附件设置

**Comment by JohnNiang** [comment]
1. 是否支持 CDN 和博客程序无关；
2. h2 数据库文件默认在 ~/.halo/db/halo.mv.db，上传的附件默认在 ~/.halo/upload 目录。

> 详情参考：https://halo.run/archives/install-with-linux.html#%E8%BF%90%E8%A1%8C-halo
