### ISSUE TITLE
halo部署后，怎样有效提高全站的访问速度？

### ISSUE THREAD

**Issue by mmdapl** [halo-dev/halo#944]
目前采用docker部署halo服务，应该是由于halo后端部署方式+SEO以及服务器带宽低的问题，全站访问较慢，请问有什么提高全站访问速度的方法吗？比如如何采用cdn加速之类的

**Comment by ruibaby** [comment]
> 应该是由于halo后端部署方式+SEO

没有明白。

目前我的博客使用的又拍云全站加速。回源地址填的 ip+端口。域名解析到又拍云提供的 cname 即可。

**Comment by mmdapl** [comment]
谢谢，按照 `目前我的博客使用的又拍云全站加速。回源地址填的 ip+端口。域名解析到又拍云提供的 cname 即可。` 已经接入又拍云，但是通过域名访问提供的接口有问题

目前不能通的情况：https://blog.142vip.cn/api/admin/posts?page=2&size=10&api_access_key=123456

能通的情况：http://view.142vip.cn:8090/api/content/posts?api_access_key=123456

我是回源地址填写： view.142vip.cn+8090端口，通过域名不能访问后台接口是应为代理的问题吗?

另外：又拍云全站加速有，管理页面的文章分页，似乎没有效果，一直只能拿到第一页数据，若不走全局加速，分页是正常的

**Comment by ruibaby** [comment]
在 cdn 设置中：

1. 缓存控制 -> 参数跟随 -> 全程跟随。
2. 性能优化 -> 重定向跟随 -> 开启。

应该就可以了。

**Comment by mmdapl** [comment]
fix  已配置原来是没有跟随参数； 站长是否可以通过指向又拍云的域名和api_access_key访问接口？ 目前我测试只能通过回源地址进行访问拿到数据

**Comment by ruibaby** [comment]
> fix 已配置原来是没有跟随参数； 站长是否可以通过指向又拍云的域名和api_access_key访问接口？ 目前我测试只能通过回源地址进行访问拿到数据

access key 可以放到 header

https://api.halo.run/content-api.html#section/Authentication/Access_key_from_header

**Comment by mmdapl** [comment]
谢站长，目前一切fix，无法访问通是个人设置原因，可以close
