### ISSUE TITLE
feat: 新增评论增加用户头像字段

### ISSUE THREAD

**Issue by LIlGG** [halo-dev/halo#946]
## 概述
是否能够在评论中增加用户头像字段？

## 动机
目前我正在开发评论组件，但在国内使用Gravatar实在是不友好，因此我想使用拉取QQ头像/其他头像的方式。

## 详细解释
目前遇到的问题是，拉取到的QQ头像无法保存在评论字段中进行返显。经过查看，发现Halo新增评论字段与数据库中没有类似头像链接这样的字段。这意味着我只能使用Gravatar头像。且如若某个评论组件不使用邮箱，将会导致没有头像可以显示【当然目前没有这样的评论组件】。

**Comment by JohnNiang** [comment]
但是，要考虑用户输入的链接可能具有攻击性。

**Comment by LIlGG** [comment]
> 但是，要考虑用户输入的链接可能具有攻击性。
。这个问题确实需要考虑。或许可以考虑不增加链接。而只增加特定的内容，例如QQ号这种。然后再由前端根据QQ号拉取头像

不过这种字段，包括前面我看到的那个为评论增加html的那个，这种字段实际上都不应该存在于评论的字段中。应该说就类似于自定义字段。我看wp似乎有这样的功能，但对于wp我了解的不是很多。

如果没有别的方法，就增加一个通用字段或者通用的评论字段的附属表，然后由主题开发者决定存储什么内容吧。

**Comment by ruibaby** [comment]
> > 但是，要考虑用户输入的链接可能具有攻击性。
> 
> 。这个问题确实需要考虑。或许可以考虑不增加链接。而只增加特定的内容，例如QQ号这种。然后再由前端根据QQ号拉取头像
> 
> 不过这种字段，包括前面我看到的那个为评论增加html的那个，这种字段实际上都不应该存在于评论的字段中。应该说就类似于自定义字段。我看wp似乎有这样的功能，但对于wp我了解的不是很多。
> 
> 如果没有别的方法，就增加一个通用字段或者通用的评论字段的附属表，然后由主题开发者决定存储什么内容吧。

目前文章和自定义页面支持了 meta 自定义字段，后面我们想办法给评论也加上，应该能比较好的解决这个问题。

**Comment by LIlGG** [comment]
> > > 但是，要考虑用户输入的链接可能具有攻击性。
> > 
> > 
> > 。这个问题确实需要考虑。或许可以考虑不增加链接。而只增加特定的内容，例如QQ号这种。然后再由前端根据QQ号拉取头像
> > 不过这种字段，包括前面我看到的那个为评论增加html的那个，这种字段实际上都不应该存在于评论的字段中。应该说就类似于自定义字段。我看wp似乎有这样的功能，但对于wp我了解的不是很多。
> > 如果没有别的方法，就增加一个通用字段或者通用的评论字段的附属表，然后由主题开发者决定存储什么内容吧。
> 
> 目前文章和自定义页面支持了 meta 自定义字段，后面我们想办法给评论也加上，应该能比较好的解决这个问题。

我看评论字段似乎有ipAddress，但目前都为"" 是还没实装吗

**Comment by ruibaby** [comment]
@LIlGG 这个问题似乎是因为之前用的异步的方式设置的 ipAddress，不过后面的版本已经被 @JohnNiang 修复了， @JohnNiang Right？

**Comment by JohnNiang** [comment]
> > > > 但是，要考虑用户输入的链接可能具有攻击性。
> > > 
> > > 
> > > 。这个问题确实需要考虑。或许可以考虑不增加链接。而只增加特定的内容，例如QQ号这种。然后再由前端根据QQ号拉取头像
> > > 不过这种字段，包括前面我看到的那个为评论增加html的那个，这种字段实际上都不应该存在于评论的字段中。应该说就类似于自定义字段。我看wp似乎有这样的功能，但对于wp我了解的不是很多。
> > > 如果没有别的方法，就增加一个通用字段或者通用的评论字段的附属表，然后由主题开发者决定存储什么内容吧。
> > 
> > 
> > 目前文章和自定义页面支持了 meta 自定义字段，后面我们想办法给评论也加上，应该能比较好的解决这个问题。
> 
> 我看评论字段似乎有ipAddress，但目前都为"" 是还没实装吗

评论的 IP 地址为敏感信息，所以在返回前端前已经过滤了。

**Comment by LIlGG** [comment]
@JohnNiang 那如果评论使用后端驱动开发而不是使用组件调用API的方式是不是就能获得这个IP地址并尝试渲染？？

**Comment by JohnNiang** [comment]
为什么会有把评论者的 IP 地址渲染出去的需求呢？这样对评论者不友好。

**Comment by LIlGG** [comment]
> 为什么会有把评论者的 IP 地址渲染出去的需求呢？这样对评论者不友好。

不是渲染IP，而是根据ip获取省市这种。部分主题也可能有这样的需求。

**Comment by JohnNiang** [comment]
那这种需求是可以完成的。你可以在创建新评论的 listener 中异步更新就好了。

**Comment by LIlGG** [comment]
> 那这种需求是可以完成的。你可以在创建新评论的 listener 中异步更新就好了。

emmm 当前用户新创建的评论我确实能取到省市并且更新，但是一刷新重新请求接口就没有了。除非我使用外接数据库的方式来保存省市。。

**Comment by LIlGG** [comment]
由于 1.x 已经停止维护，见 https://www.halo.run/archives/halo-1.x-eol，因此此 PR 已过时。

2.x 版本中如果想实现类似功能，可以通过自定义评论插件的形式来做。

/close
