### ISSUE TITLE
安装的时候那个主题文件有问题吧？

### ISSUE THREAD

**Issue by sheiy** [halo-dev/halo#947]
docker最新的镜像 配置yaml文件为自己的mysql数据库然后去网页上初始化会报错

启动成功后先不去初始化   把anatole主题换成anatole github上最新的一份release代码就ok了

**Comment by ruibaby** [comment]
@sheiy 请提供异常信息，最新的镜像已经发布三个多月了，不至于现在才发现默认主题有问题。
