### ISSUE TITLE
ads.txt 存放目录

### ISSUE THREAD

**Issue by HuRuWo** [halo-dev/halo#949]
设置谷歌广告 ads.txt 需要放在根目录下

```
如果您要验证是否正确发布了文件，请使用网络浏览器访问 ads.txt 网址 (https://example.com/ads.txt)，看看是否可以成功查看文件内容。如果可以，就说明 AdSense 可顺利找到该文件。
```
无论如何放都不能成功 https://example.com/ads.txt 

根目录不是./halo吗

**Comment by ruibaby** [comment]
没有所谓的根目录。

但是我们模拟了一个，默认是关闭的。

https://halo.run/archives/use-hidden-features.html#%E5%BC%80%E5%8F%91%E8%80%85%E9%80%89%E9%A1%B9

**Comment by HuRuWo** [comment]
nice 成功了。你这回复可太快了

**Comment by woodchen-ink** [comment]
> 没有所谓的根目录。
> 
> 但是我们模拟了一个，默认是关闭的。
> 
> https://halo.run/archives/use-hidden-features.html#%E5%BC%80%E5%8F%91%E8%80%85%E9%80%89%E9%A1%B9

链接可以再发下吗，这个失效了

**Comment by ruibaby** [comment]
> > 没有所谓的根目录。
> > 但是我们模拟了一个，默认是关闭的。
> > [halo.run/archives/use-hidden-features.html#%E5%BC%80%E5%8F%91%E8%80%85%E9%80%89%E9%A1%B9](https://halo.run/archives/use-hidden-features.html#%E5%BC%80%E5%8F%91%E8%80%85%E9%80%89%E9%A1%B9)
> 
> 链接可以再发下吗，这个失效了

因为 2.x 的静态目录托管还没有管理页面，所以暂时没有文档。现在你可以在工作目录（.halo2）中手动创建 static 目录，然后里面的文件就会挂载到网站根目录。

**Comment by woodchen-ink** [comment]
> > > 没有所谓的根目录。
> > > 但是我们模拟了一个，默认是关闭的。
> > > [halo.run/archives/use-hidden-features.html#%E5%BC%80%E5%8F%91%E8%80%85%E9%80%89%E9%A1%B9](https://halo.run/archives/use-hidden-features.html#%E5%BC%80%E5%8F%91%E8%80%85%E9%80%89%E9%A1%B9)
> > 
> > 
> > 链接可以再发下吗，这个失效了
> 
> 因为 2.x 的静态目录托管还没有管理页面，所以暂时没有文档。现在你可以在工作目录（.halo2）中手动创建 static 目录，然后里面的文件就会挂载到网站根目录。

好的，谢谢，回复速度真快👍

**Comment by zx9588** [comment]
https://zxalive.com/archives/halo-root-directory-add-ads-txt

**Comment by 569258yin** [comment]
我以页面的形式添加了一个ads.txt的页面链接，结果发现不对。现在我按照创建static/ads.txt文件的方式，并将之前的页面删除了，但是访问 xxxx.com/ads.txt 一直报404

我同样在static下创建了test.html文件，是可以通过xxx.com/test.html访问的，现在这种情况应该怎么解决？？好像是之前页面的ads.txt链接被页面一直占用了，无法转到静态页面上

**Comment by woodchen-ink** [comment]
> 我以页面的形式添加了一个ads.txt的页面链接，结果发现不对。现在我按照创建static/ads.txt文件的方式，并将之前的页面删除了，但是访问 xxxx.com/ads.txt 一直报404
> 
> 我同样在static下创建了test.html文件，是可以通过xxx.com/test.html访问的，现在这种情况应该怎么解决？？好像是之前页面的ads.txt链接被页面一直占用了，无法转到静态页面上 @ruibaby

建议参考这篇帖子: https://q58.org/t/topic/49

原本放static, google也会经常抓取不到, 按照这个帖子里不会有问题

**Comment by 569258yin** [comment]
> > 我以页面的形式添加了一个ads.txt的页面链接，结果发现不对。现在我按照创建static/ads.txt文件的方式，并将之前的页面删除了，但是访问 xxxx.com/ads.txt 一直报404
> > 我同样在static下创建了test.html文件，是可以通过xxx.com/test.html访问的，现在这种情况应该怎么解决？？好像是之前页面的ads.txt链接被页面一直占用了，无法转到静态页面上 @ruibaby
> 
> 建议参考这篇帖子: https://q58.org/t/topic/49
> 
> 原本放static, google也会经常抓取不到, 按照这个帖子里不会有问题

好的，没想到用nginx去代理，一直想用halo去弄了，已经弄好了，感谢支持~~~

**Comment by JohnNiang** [comment]
建议试试 [Halo 静态网页服务插件](https://www.halo.run/store/apps/app-gFkMn)。
