### ISSUE TITLE
后台首页提示网络错误

### ISSUE THREAD

**Issue by Stars-One** [halo-dev/halo#957]
后台进入首页,会提示网络错误,虽然不影响使用,但是有点强迫症,想问问是什么原因

![](https://img2020.cnblogs.com/blog/1210268/202007/1210268-20200710091710770-813184335.png)

**Comment by Stars-One** [comment]
图片地址:https://img2020.cnblogs.com/blog/1210268/202007/1210268-20200710091710770-813184335.png

**Comment by JohnNiang** [comment]
当前位置和服务器网络不太稳定。

**Comment by JohnNiang** [comment]
你可以按 F12 选择网络栏，看看具体是哪个请求超时了呢。

**Comment by Stars-One** [comment]
控制台报错信息 ![](https://img2020.cnblogs.com/blog/1210268/202007/1210268-20200710092122607-369867029.png)

https://img2020.cnblogs.com/blog/1210268/202007/1210268-20200710092122607-369867029.png

我之前在nginx配置里,是把http重定向到了https,是不是这个的原因?

**Comment by JohnNiang** [comment]
错误原因：ERR_TOO_MANY_REDIRECTS。你可以好好排查一下，应该是服务端配置的问题。

**Comment by Stars-One** [comment]
已解决
我将nginx配置中的 `rewrite ^(.*)$ https://$host$1 permanent; `改为了
```
if ($http_x_forwarded_proto = 'http'){
    return 301 https://$host$request_uri;
    }
```
