### ISSUE TITLE
feat:  Post实体类能否加入文章url的字段

### ISSUE THREAD

**Issue by Stars-One** [halo-dev/halo#958]
主要是想加个转载声明的头部,需要当前文章url

虽然可以通过js拿到当前的文章的链接,

个人觉得还是从后台直接拿到数据这种方式比较友好,而且也是方便之后的主题开发者使用,能否考虑一下?

**Comment by ruibaby** [comment]
`${post.fullPath!}`

**Comment by Stars-One** [comment]
> `${post.fullPath!}`
> 
> `post` `sheet` `category` `tag` 都带有 fullPath。

好的,那边的开发文档并没有这个字段的说明,麻烦更新一下文档
