### ISSUE TITLE
feat: post input function need to enhance

### ISSUE THREAD

**Issue by VictorChan1** [halo-dev/halo#963]
## 概述
文章导入功能建议添加多一些解析md文档中的关于文章元数据。

## 动机
在使用文章导入功能的时候直接就发布了，tags和title都没办法编辑

**Comment by ruibaby** [comment]
标签和标题都可以再编辑，至于解析元数据都写都是支持的，不过需要固定的格式才可以。

**Comment by VictorChan1** [comment]
> 标签和标题都可以再编辑，至于解析元数据这些都是支持的，不过需要固定的格式才可以。

请问是支持什么格式？？

**Comment by ruibaby** [comment]
```
---
title: test
categories:
  - category1
  - category2
tags: 
  - tag1
  - tag2

---
```

**Comment by VictorChan1** [comment]
> ---
> title: test
> categories:
>   - category1
>   - category2
> tags: 
>   - tag1
>   - tag2
> 
> ---

那缩略图链接和摘要的key是什么？我试了preview和content-preview都不行

**Comment by ruibaby** [comment]
缩略图是 thumbnail，摘要没有。

**Comment by VictorChan1** [comment]
> 缩略图是 thumbnail，摘要没有。

好的 谢谢
