### ISSUE TITLE
markdown 流程图显示错误

### ISSUE THREAD

**Issue by Guozht** [halo-dev/halo#966]
## 我的环境

版本：1.3.2
数据库：H2 1.4.196 (2017-06-10)
运行模式：production
User Agent：Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

## 期望行为
markdown 流程图正常显示

## 当前行为
预览界面正常，发布之后显示错误（无法显示，显示的是markdown内容）

**Comment by ruibaby** [comment]
https://halo.run/archives/use-markdown.html#%E5%9B%BE%E8%A1%A8

**Comment by Guozht** [comment]
> https://halo.run/archives/use-markdown.html#%E5%9B%BE%E8%A1%A8

我确保markdown 语法是正确的，只是显示错误，刚才用你发的这个链接试了一下，也是预览正确，发布之后就显示错误了。

**Comment by ruibaby** [comment]
请提供文章链接。

**Comment by Guozht** [comment]
> 请提供文章链接。

https://www.gnsoft.ltd/archives/markdown%E7%9A%84%E5%9F%BA%E6%9C%AC%E8%AF%AD%E6%B3%95%E4%BD%BF%E7%94%A8

**Comment by ruibaby** [comment]
没有发现 mermaid 的依赖，上面给你的链接就是让你添加 mermaid 的依赖。

![image](https://user-images.githubusercontent.com/21301288/87264513-c2f22400-c4f2-11ea-95c1-f8ee80d8e02b.png)

**Comment by Guozht** [comment]
> 没有发现 mermaid 的依赖，上面给你的链接就是让你添加 mermaid 的依赖。
> 
> ![image](https://user-images.githubusercontent.com/21301288/87264513-c2f22400-c4f2-11ea-95c1-f8ee80d8e02b.png)

已经好了，谢谢:+1:
