### ISSUE TITLE
markdown 转义失败？

### ISSUE THREAD

**Issue by Guozht** [halo-dev/halo#968]
halo站点链接：[markdown的基本语法使用](https://www.gnsoft.ltd/archives/markdown的基本语法使用)

**Comment by Guozht** [comment]
@ruibaby

**Comment by JohnNiang** [comment]
> @ruibaby

Hold on!

**Comment by JohnNiang** [comment]
你可以贴出部分源内容以及渲染之后的样子，对比一下。方便我们快速知道你的问题所在。

**Comment by Guozht** [comment]
这个是源内容
![FireShot Capture 003](https://user-images.githubusercontent.com/31638230/87370082-9b639000-c5b4-11ea-91b4-30ef9e4abe45.png)

这个是渲染之后的
![FireShot Capture 005](https://user-images.githubusercontent.com/31638230/87370112-afa78d00-c5b4-11ea-8a58-3ae05788a9fa.png)

**Comment by JohnNiang** [comment]
可以考虑用缩进（4 个字符）来替代 **```** 解决这个问题。如下：

        ```
        ```

**Comment by Guozht** [comment]
> 可以考虑用缩进（4 个字符）来替代 **```** 解决这个问题。如下：
> 
> ```
>     ```
>     ```
> ```

这种办法确实可以正常显示了，但是整体对齐上稍微有点瑕疵，能用转义符就好了，转义符现在是不是有BUG？

**Comment by JohnNiang** [comment]
我这边测试过，不会对对齐造成影响。

> 前面一定要是 4 个空格哦，多余的空格会被渲染出来。

**Comment by JohnNiang** [comment]
> > 可以考虑用缩进（4 个字符）来替代 **```** 解决这个问题。如下：
> > ```
> >     ```
> >     ```
> > ```
> 
> 这种办法确实可以正常显示了，但是整体对齐上稍微有点瑕疵，能用转义符就好了，转义符现在是不是有BUG？

转义本身应该是没有问题的。在`代码块`中的任何内容本身就会被原样输出的，这个就是 markdown 的规则。

**Comment by Guozht** [comment]
![FireShot Capture 006](https://user-images.githubusercontent.com/31638230/87371241-81777c80-c5b7-11ea-99bf-0e4b99d45953.png)
我说的是这种，我这用四个空格渲染出来没有对齐啊

**Comment by ruibaby** [comment]
@Guozht markdown
```language
代码块

``

**Comment by ruibaby** [comment]
![image](https://user-images.githubusercontent.com/21301288/87371448-f77be380-c5b7-11ea-83b5-ae8d85fc93e7.png)

**Comment by Guozht** [comment]
@ruibaby  解决了:+1:
