### ISSUE TITLE
feat: 增加helm部署方式

### ISSUE THREAD

**Issue by donggangcj** [halo-dev/halo#969]
## 概述

面向那些有`kubernetes cluster`集群的用户（通常是有钱人）,简化和优化部署管理流程。

## 动机
让部署方式更加多元化，同时播下一颗云原生的种子。

## 详细解释

需要进行的工作：

1. 开发helm chart，目前halo的组件不是特别复杂，应该会比较简单；
2. 推送到helm hub中；
3. 部署文档的修改；

**Comment by JohnNiang** [comment]
tql！希望能顺利推进。

**Comment by ruibaby** [comment]
在继续吗？

**Comment by donggangcj** [comment]
目前还没有，没有收集足够的需求和建议，我先关闭这个issue，如果有需要，再打开它。

**Comment by JohnNiang** [comment]
/reopen
/kind feature
/area core

Support links:
- <https://bbs.halo.run/d/3016-%E5%BB%BA%E8%AE%AE%E6%96%B0%E5%A2%9Ehelm%E9%83%A8%E7%BD%B2%E6%96%B9%E6%B3%95>(From Chinese forum)

**Comment by YEDEDD** [comment]
这个还会支持吗。自己写了半天也没搞好

**Comment by JohnNiang** [comment]
Hi @YEDEDD ，可以试试：<https://github.com/wan92hen/halo-chart>。

> 有什么问题可直接在对应的仓库提交 issue。

**Comment by ruibaby** [comment]
目前已经在 https://github.com/halo-sigs/charts 中提供。

/close

**Comment by octopushep** [comment]
docker.io/bitnami/postgresql:15.4.0-debian-11-r45这个镜像八百年前就被删了 helm部署方式实际上已经失效了 请更新

**Comment by JohnNiang** [comment]
Hi @octopushep , please see https://github.com/halo-sigs/charts/pull/16 for more.
