### ISSUE TITLE
1.2 升级 1.3 sql执行出错 求大神指点 

### ISSUE THREAD

**Issue by ailonghun** [halo-dev/halo#971]
![image](https://user-images.githubusercontent.com/45844357/87508028-0b4f4480-c6a1-11ea-8582-f4e1b5104b84.png)

**Comment by ailonghun** [comment]
update posts set `slug`=`url`;
Unique index or primary key violation: "UK_QMMSO8QXJPBXWEGDTP0L90390_INDEX_4 ON PUBLIC.POSTS(SLUG) VALUES ('taro', 22)"; SQL statement:
update posts set `slug`=`url` [23505-196] 23505/23505

**Comment by ruibaby** [comment]
有多个 url 为 taro 的数据，而 slug 加了唯一约束，所以报错。先修改相同 url 的数据吧。

**Comment by ruibaby** [comment]
你修改好之后，建议清空 flyway_history 这张表的数据，再运行 1.3.x。

**Comment by ailonghun** [comment]
@ruibaby 感谢问题已经解决了
