### ISSUE TITLE
代码Bug Report: User类没有getMfaType()方法, IDEA报红。具体见截图。

### ISSUE THREAD

**Issue by mebest100** [halo-dev/halo#974]
## 我的环境

---

## 错误日志

---

**Comment by mebest100** [comment]
![image](https://user-images.githubusercontent.com/11530991/87871147-a49f9300-c9e0-11ea-8af3-75d71b00c53f.png)

**Comment by ruibaby** [comment]
https://halo.run/archives/develop-application-start#所需要的环境
