### ISSUE TITLE
feat: markdown 导入兼容 hugo

### ISSUE THREAD

**Issue by zhixiangyuan** [halo-dev/halo#975]
## 概述

新增 hugo 全站导入功能，我来实现

## 动机

之前用 hugo 作为博客，但文章很多需要自动导入到 halo

## 详细解释

上传 hugo 博客压缩包则自动导入到 halo

**Comment by ruibaby** [comment]
hugo 都是 Markdown 文档，现在已经支持，你可以试试，如果目前的 Markdown 导入不能满足你的需求你可以考虑做一下对 hugo Markdown 格式的兼容。

单独做 hugo 导入的功能不可取。

**Comment by zhixiangyuan** [comment]
> hugo 都是 Markdown 文档，现在已经支持，你可以试试，如果目前的 Markdown 导入不能满足你的需求你可以考虑做一下对 hugo Markdown 格式的兼容。
> 
> 单独做 hugo 导入的功能不可取。

markdown 里面引用的图片之前我是写的本站相对路径，所以不只是要导入单个 markdown，要将连带的图片一起导入进来

**Comment by ruibaby** [comment]
> > hugo 都是 Markdown 文档，现在已经支持，你可以试试，如果目前的 Markdown 导入不能满足你的需求你可以考虑做一下对 hugo Markdown 格式的兼容。
> 
> > 
> 
> > 单独做 hugo 导入的功能不可取。
> 
> 
> 
> markdown 里面引用的图片之前我是写的本站相对路径，所以不只是要导入单个 markdown，要将连带的图片一起导入进来

如果你打算再对以前的图片所引用的话，你可以考虑把图片文件夹放在 .halo 下的 static 目录，那就是针对你站点的相对路径了。

**Comment by zhixiangyuan** [comment]
> > > hugo 都是 Markdown 文档，现在已经支持，你可以试试，如果目前的 Markdown 导入不能满足你的需求你可以考虑做一下对 hugo Markdown 格式的兼容。
> > 
> > 
> > > 
> > 
> > 
> > > 单独做 hugo 导入的功能不可取。
> > 
> > 
> > markdown 里面引用的图片之前我是写的本站相对路径，所以不只是要导入单个 markdown，要将连带的图片一起导入进来
> 
> 如果你不打算再对以前的图片所引用的话，你可以考虑把图片文件夹放在 .halo 下的 static 目录，那就是针对你站点的相对路径了。

大佬牛皮，那我改成直接在原来 markdown 导入上兼容 hugo

**Comment by est7** [comment]
halo版本 1.3.2
markdown文件导入时无法正常显示img
把本地文件上传至.halo/static/asserts后，使用`![img](asserts/1122690-f27ad5d50259febc.png)`无法正常显示图片

**Comment by ruibaby** [comment]
> halo版本 1.3.2
> 
> markdown文件导入时无法正常显示img
> 
> 把本地文件上传至.halo/static/asserts后，使用`![img](asserts/1122690-f27ad5d50259febc.png)`无法正常显示图片

/asserts/xxx
