### ISSUE TITLE
主题图片不能显示，确定主题已经安装。

### ISSUE THREAD

**Issue by mebest100** [halo-dev/halo#976]

**Comment by mebest100** [comment]
![image](https://user-images.githubusercontent.com/11530991/87871999-be90a400-c9e7-11ea-84e4-bb2697deeb7d.png)

**Comment by ruibaby** [comment]
在后台的个人资料中设置头像或者博客设置中设置logo

**Comment by mebest100** [comment]
![image](https://user-images.githubusercontent.com/11530991/87872019-e97af800-c9e7-11ea-9f05-481b6326085b.png)

**Comment by mebest100** [comment]
![image](https://user-images.githubusercontent.com/11530991/87872036-04e60300-c9e8-11ea-8a30-1a94eb11e3e2.png)

**Comment by mebest100** [comment]
这个已经安装的主题不是已经有默认的logo了吗，为什么显示不出来呢

**Comment by ruibaby** [comment]
@mebest100 如果你想要这个logo，在博客设置的logo里写上 /anatole/source/images/logo@2x.png 即可。

**Comment by mebest100** [comment]
这样设置了也出不来啊，得手动上传才行，真是服了，还是谢谢你！

![image](https://user-images.githubusercontent.com/11530991/87872279-9ace5d80-c9e9-11ea-806a-a1d772dc03e4.png)

![image](https://user-images.githubusercontent.com/11530991/87872239-6064c080-c9e9-11ea-9f94-1ff40b52bff3.png)

![image](https://user-images.githubusercontent.com/11530991/87872262-838f7000-c9e9-11ea-8e7a-978711863ae9.png)

![image](https://user-images.githubusercontent.com/11530991/87872292-bc2f4980-c9e9-11ea-9d85-2d15757e6045.png)
