### ISSUE TITLE
feat: 考虑自定义页面可以输入html内容

### ISSUE THREAD

**Issue by stars-one** [halo-dev/halo#978]
自定义页面的内容只能以MD格式来书写,我输入了html内容,发现页面乱了....可以考虑以html内容输入吗?

我觉得可以在自定义页面发布的时候,增加一个选项,如果勾选了,就不使用mrakdown相关的库进行解析

**Comment by Stars-One** [comment]
折腾了一番,发现问题解决了,不过,觉得还是不够友好,必须要没有tab缩进才行,每次还得将写好的html格式全部取消缩进,觉得有些麻烦,可以考虑上述的想法,加个选项来控制是否采用MD解析

**Comment by JohnNiang** [comment]
@Stars-One 很早就有这样的想法了。提供一个开关决定是否需要用 md 渲染，因为最终的效果都是 html。

**Comment by WenyinWei** [comment]
我想在博客里面引入相当数量的可视化内容，所以也希望这点能得到增强，或者说让用户更加灵活。

**Comment by ruibaby** [comment]
目前 Halo 2 实现了一个编写 HTML 代码的插件：https://www.halo.run/store/apps/app-NgHnY

/close
