### ISSUE TITLE
后台Markdown对于 `ax^2 + bx + c = 0`样式渲染有问题

### ISSUE THREAD

**Issue by hshanx** [halo-dev/halo#982]
## 我的环境

![image](https://user-images.githubusercontent.com/23736683/87899215-12040000-ca83-11ea-98af-adb99d9d4bfa.png)

---

---

## 期望行为

对于`ax^2 + bx + c = 0`和`x = {-b \pm \sqrt{b^2-4ac} \over 2a}.`这种格式能够正确返回

## 当前行为
![image](https://user-images.githubusercontent.com/23736683/87899306-5abbb900-ca83-11ea-91a7-74322cae21b9.png)

> 完整格式： When $a \ne 0$, there are two solutions to (ax^2 + bx + c = 0) and they are $$x = {-b \pm \sqrt{b^2-4ac} \over 2a}.$$

**Comment by JohnNiang** [comment]
Got it. 晚点儿写一个相关的测试类。

**Comment by ruibaby** [comment]
结合：

1. https://github.com/halo-dev/halo/issues/607

2. https://halo.run/archives/use-markdown.html#%E6%95%B0%E5%AD%A6%E5%85%AC%E5%BC%8F

**Comment by hshanx** [comment]
建议后端不渲染Markdown ，直接扔给前端处理@ruibaby

**Comment by JohnNiang** [comment]
> 建议后端不渲染Markdown ，直接扔给前端处理@ruibaby

主题中应该是能够获取到对应的源格式的内容，可以在前端处理。
