### ISSUE TITLE
对于AbstractVisitEventListener的executor 构建是不是可以设置个最大线程数?

### ISSUE THREAD

**Issue by listener-He** [halo-dev/halo#984]
> 目前的线程池创建是使用默认构造器创建
`
this.executor = Executors.newCachedThreadPool();

public static ExecutorService newCachedThreadPool() {
        return new ThreadPoolExecutor(0, Integer.MAX_VALUE,
                                      60L, TimeUnit.SECONDS,
                                      new SynchronousQueue<Runnable>());
    }
`
这样不会随着文章数的增加而创建多少个线程吗?

**Comment by JohnNiang** [comment]
确实会随着文章访问数不断增加，但是 java doc 中有这么一段描述：

> Threads that have not been used for sixty seconds are terminated and removed from the cache. Thus, a pool that remains idle for long enough will not consume any resources.

线程会在 60s 后被干掉并从线程池中移除，不会消耗过多的资源。

**Comment by listener-He** [comment]
如果只是少量对访问是没问题的，但是如果在一定事件内比较大对活跃数时这样的方式开销就比较大了。是不是考虑换一种方式？而并非使用线程池去处理? 
我觉得一个线程应该也能达到一样的效果吧? 我个人对抽象类调整了下 [链接](https://blog.hehouhui.cn/archives/halo-post-read)

**Comment by JohnNiang** [comment]
文中使用的方法非常不错，我打算采纳，您可以考虑提 PR 或者我们自己集成（会署名）。

**Comment by listener-He** [comment]
我先把bug修复下，刚刚测试出一个定时处理阅读数时出现没执行的问。修复后我在提交一个PR，如果我忘了您也可以自己集成下。修复后我会更新文章。

**Comment by JohnNiang** [comment]
这里可以利用 Pull Request 自动关闭 Issue 功能，不必手动关闭的：P

**Comment by listener-He** [comment]
嗯嗯,除了平缓阅读控制外我可不可以在做些扩展? 如单个客户端阅读频率等.ReadAbstract还有些扩展



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "John Niang"<notifications@github.com&gt;; 
发送时间: 2020年7月21日(星期二) 晚上9:22
收件人: "halo-dev/halo"<halo@noreply.github.com&gt;; 
抄送: "Java-何厚辉"<hehouhui@foxmail.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [halo-dev/halo] 对于AbstractVisitEventListener的executor 构建是不是可以设置个最大线程数? (#984)





 
这里可以利用 Pull Request 自动关闭 Issue 功能，不必手动关闭的：P

**Comment by ruibaby** [comment]
@listener-He 分开提交pr吧。

**Comment by listener-He** [comment]
估计不好分开提交,在我构思中是基于Read去实现的。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ryan Wang"<notifications@github.com&gt;; 
发送时间: 2020年7月21日(星期二) 晚上9:33
收件人: "halo-dev/halo"<halo@noreply.github.com&gt;; 
抄送: "Java-何厚辉"<hehouhui@foxmail.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [halo-dev/halo] 对于AbstractVisitEventListener的executor 构建是不是可以设置个最大线程数? (#984)





 
@listener-He 分开提交pr吧。

**Comment by JohnNiang** [comment]
> 估计不好分开提交,在我构思中是基于Read去实现的。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Ryan Wang"<notifications@github.com&gt;; 发送时间: 2020年7月21日(星期二) 晚上9:33 收件人: "halo-dev/halo"<halo@noreply.github.com&gt;; 抄送: "Java-何厚辉"<hehouhui@foxmail.com&gt;; "Mention"<mention@noreply.github.com&gt;; 主题: Re: [halo-dev/halo] 对于AbstractVisitEventListener的executor 构建是不是可以设置个最大线程数? (#984) @listener-He 分开提交pr吧。 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

可以考虑在当前 PR 中，因为有关联。
