### ISSUE TITLE
feat: 放弃后端渲染 Markdown 文本。

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#989]
## 概述

放弃在保存文章的时候再渲染 Markdown，直接使用编辑器渲染好的 html 文档。

## 动机

1. 很难保证前后端渲染一致，除非自己造 Markdown 渲染引擎，但很显然目前我们没有这个能力。
2. 后续计划为放弃使用 Markdown 编辑器，将基于 tiptap 引擎实现一个编辑器，类似语雀的编辑器，但同时保留部分常用 Markdown 语法。同时，旧的 Markdown 编辑器将继续保留一段时间，但默认编辑器将不再是 Markdown 编辑器。

**Comment by ruibaby** [comment]
相关问题和讨论：

1. https://github.com/halo-dev/halo/issues/982
2. https://github.com/halo-dev/halo/issues/607
3. https://github.com/halo-dev/halo/issues/604

**Comment by Smith-Cruise** [comment]
这个大概多久能够实现，感觉要很大的改动啊。

**Comment by ruibaby** [comment]
> 这个大概多久能够实现，感觉要很大的改动啊。

下个 beta

**Comment by JohnNiang** [comment]
不建议直接干掉后端渲染 markdown，这样会导致所有主题都得改。可以提供一个选项获取到源 markdown 格式的内容，供主题自行渲染。等所有主题都稳定之后再彻底放弃。

**Comment by ruibaby** [comment]
> 不建议直接干掉后端渲染 markdown，这样会导致所有主题都得改。可以提供一个选项获取到源 markdown 格式的内容，供主题自行渲染。等所有主题都稳定之后再彻底放弃。

怎么会呢？我的意思是直接用编辑器渲染好的 html。

**Comment by zhixiangyuan** [comment]
大佬加油，目前编辑器使用体验真的不好，期待大佬下个版本

**Comment by zhixiangyuan** [comment]
vscode web ide 也挺好用，大佬要不要考虑集成这个

**Comment by ruibaby** [comment]
> vscode web ide 也挺好用，大佬要不要考虑集成这个

那也太大了

**Comment by 1395181540** [comment]
我觉得语雀的编辑器用起来最舒服,干脆用语雀编写文档,Webhook推送更新,通过语雀API获取文档内容.类似vuepress的插件vuepress-plugin-yuque

**Comment by ruibaby** [comment]
> 我觉得语雀的编辑器用起来最舒服,干脆用语雀编写文档,Webhook推送更新,通过语雀API获取文档内容.类似vuepress的插件vuepress-plugin-yuque

但终究还得自己写。

**Comment by zhixiangyuan** [comment]
> > 我觉得语雀的编辑器用起来最舒服，干脆用语雀编写文档，Webhook 推送更新，通过语雀 API 获取文档内容。类似 vuepress 的插件 vuepress-plugin-yuque
> 
> 但终究还得自己写。

大佬，啥时候新的编辑器能上线，好期待

**Comment by RealKiro** [comment]
markdown编辑器目前有2个问题有待改进
1. 当文章很长很长的时候，偶尔想偷懒用下下面的工具，应该在拖动滚动栏的时候锁定（不然又重新回到顶部很麻烦）
![image](https://user-images.githubusercontent.com/33367701/88823718-fbcf1000-d1f7-11ea-899d-8260b981546c.png)

2. markdown编辑框和预览框能做到同步显示具体哪一行吗？因为不同步不方便直接观察效果（大雾
![image](https://user-images.githubusercontent.com/33367701/88824395-dd1d4900-d1f8-11ea-9f11-e234f38f54b8.png)

**Comment by codeyee** [comment]
markdown编辑器建议可以集成vditor，所见即所得的模式，体验类似于Typora，同时也支持经典的双栏编辑，项目地址 https://github.com/Vanessa219/vditor

**Comment by codeyee** [comment]
> markdown编辑器目前有2个问题有待改进
> 
> 1. 当文章很长很长的时候，偶尔想偷懒用下下面的工具，应该在拖动滚动栏的时候锁定（不然又重新回到顶部很麻烦）
>    ![image](https://user-images.githubusercontent.com/33367701/88823718-fbcf1000-d1f7-11ea-899d-8260b981546c.png)
> 2. markdown编辑框和预览框能做到同步显示具体哪一行吗？因为不同步不方便直接观察效果（大雾
>    ![image](https://user-images.githubusercontent.com/33367701/88824395-dd1d4900-d1f8-11ea-9f11-e234f38f54b8.png)

这个不同步的问题其实可以通过在左边栏在插入图片时就渲染图片来解决，我看到CSDN的编辑器就是通过类似这种方式来解决双栏编辑器两边不同步的问题

**Comment by codeyee** [comment]
> 我觉得语雀的编辑器用起来最舒服,干脆用语雀编写文档,Webhook推送更新,通过语雀API获取文档内容.类似vuepress的插件vuepress-plugin-yuque

语雀不完全支持markdown语法，多少都有点别扭

**Comment by zhixiangyuan** [comment]
大佬，新的更换编辑器的版本啥时候能上？

**Comment by ruibaby** [comment]
> 大佬，新的更换编辑器的版本啥时候能上？

反正不会太快。

**Comment by zhixiangyuan** [comment]
> > 大佬，新的更换编辑器的版本啥时候能上？
> 
> 反正不会太快。

最近发现很好用的笔记软件，notion，编辑时的手感还挺好的，如果 halo 后台能用上这样的编辑器应该很舒服

**Comment by XuCpeng** [comment]
可否考虑支持Metaweblog API，这样就可以直接通过第三方编辑器（例如Mweb）推送文章

**Comment by ruibaby** [comment]
> 可否考虑支持Metaweblog API，这样就可以直接通过第三方编辑器（例如Mweb）推送文章

早些时候的版本写了这个功能，后面没有维护就放弃了。可能未来会考虑再支持，但不会是首要开发任务。

**Comment by zhixiangyuan** [comment]
> > 可否考虑支持 Metaweblog API，这样就可以直接通过第三方编辑器（例如 Mweb）推送文章
> 
> 早些时候的版本写了这个功能，后面没有维护就放弃了。可能未来会考虑再支持，但不会是首要开发任务。

大佬，今年年底前有没有可能用上新的编辑器？

**Comment by zhixiangyuan** [comment]
@ruibaby 大佬，新年快乐，2021 年了，咱们的新编辑器啥时候能上？

**Comment by zhixiangyuan** [comment]
@ruibaby 大佬，关于编辑器我有个想法，编辑器这块我碰到的最大的痛点其实就是文章内容比较多的时候会卡顿，这是最无法接受的。

所以其实可以实现一个最简单的版本，只有一个输入框，快捷功能就两个，command +v 上传图片，command +s 保存为草稿就行了，其实别的功能花里胡哨没啥用。

大佬能不能开发个这样的编辑器，放个版本出来，先替换掉原来的编辑器

**Comment by ruibaby** [comment]
> @ruibaby 大佬，关于编辑器我有个想法，编辑器这块我碰到的最大的痛点其实就是文章内容比较多的时候会卡顿，这是最无法接受的。
> 
> 所以其实可以实现一个最简单的版本，只有一个输入框，快捷功能就两个，command +v 上传图片，command +s 保存为草稿就行了，其实别的功能花里胡哨没啥用。
> 
> 大佬能不能开发个这样的编辑器，放个版本出来，先替换掉原来的编辑器

但这只是你的需求，如果只放一个输入框，如何保证不被骂？

**Comment by ruibaby** [comment]
@zhixiangyuan 你可以考虑 fork 一个 halo-dev/halo-admin ，修改之后独立部署一套。就像  admin.halo.run

**Comment by zhixiangyuan** [comment]
> @zhixiangyuan 你可以考虑 fork 一个 halo-dev/halo-admin ，修改之后独立部署一套。就像 admin.halo.run

老哥，新的编辑器啥时候能上？

**Comment by ruibaby** [comment]
> > @zhixiangyuan 你可以考虑 fork 一个 halo-dev/halo-admin ，修改之后独立部署一套。就像 admin.halo.run
> 
> 
> 
> 老哥，新的编辑器啥时候能上？
> 
> 

正在写，基本可以使用，还需要完善一些功能。

但是得等到1.5.0。

**Comment by ruibaby** [comment]
@zhixiangyuan 

![Snipaste_2021-04-20_18-54-13](https://user-images.githubusercontent.com/21301288/115384793-05772880-a20a-11eb-9ee6-246483b6b666.png)
![Snipaste_2021-04-20_18-54-39](https://user-images.githubusercontent.com/21301288/115384800-0740ec00-a20a-11eb-9284-2fb12d47422f.png)
![Snipaste_2021-04-20_18-55-09](https://user-images.githubusercontent.com/21301288/115384803-0740ec00-a20a-11eb-9a0a-b03d50364b5b.png)
![Snipaste_2021-04-20_18-55-24](https://user-images.githubusercontent.com/21301288/115384804-07d98280-a20a-11eb-989d-003abe02511e.png)

可以先行看看图片，后续我们会在合适的时机开放仓库并提供预览地址收集反馈。

**Comment by zhixiangyuan** [comment]
> Markdown 编辑器也重新写了一个。

棒

**Comment by syniii** [comment]
@ruibaby 1.5这个月底能发布不？我比较关心这个md的这个功能

**Comment by JohnNiang** [comment]
> @ruibaby 1.5这个月底能发布不？我比较关心这个md的这个功能

Please see https://github.com/halo-dev/halo/releases/tag/v1.5.0-alpha.1

**Comment by Mrered** [comment]
> > 可否考虑支持Metaweblog API，这样就可以直接通过第三方编辑器（例如Mweb）推送文章
> 
> 早些时候的版本写了这个功能，后面没有维护就放弃了。可能未来会考虑再支持，但不会是首要开发任务。

请问目前还有计划开发嘛，2.7已经用了一段时间了。
