### ISSUE TITLE
删除主题时 theme_setting 表没删除主题的数据

### ISSUE THREAD

**Issue by zhixiangyuan** [halo-dev/halo#995]
删除主题时 theme_setting 表没删除主题的数据，导致安装老版本主题后出现问题删除了该主题，但是过了一段时间后切换到新主题依然不生效。建议在删除主题的时候将 theme_setting 表中关于该主题的配置也全部清除

**Comment by ruibaby** [comment]
将在删除主题的时候提供一个删除配置的选项。
