### ISSUE TITLE
主题保存按钮重复点击

### ISSUE THREAD

**Issue by zhixiangyuan** [halo-dev/halo#996]
目前主题保存按钮重复点击是在前端以遮罩的形式防止重复点击的并发问题，但是我这边出现有时候遮罩没遮住被点击两次的情况。

点击两次后导致主题配置被保存两次，出现重复数据造成主题数据出错。

**Comment by ruibaby** [comment]
请问你的版本是？

**Comment by zhixiangyuan** [comment]
> 请问你的版本是？

1.3.2

**Comment by ruibaby** [comment]
> > 请问你的版本是？
> 
> 
> 
> 1.3.2，这个情况我在本地使用的时候没出现，但是在部署到服务器的时候出现过

你可以升级到 1.4.0 beta1 试试，这个版本做了大量优化。

**Comment by zhixiangyuan** [comment]
好

**Comment by zhixiangyuan** [comment]
> > > 请问你的版本是？
> > 
> > 
> > 1.3.2，这个情况我在本地使用的时候没出现，但是在部署到服务器的时候出现过
> 
> 你可以升级到 1.4.0 beta1 试试，这个版本做了大量优化。

试了 1.4.0 beta1，依然存在这个问题
