### ISSUE TITLE
feat: 添加友链时不会校验现有域名是否重复

### ISSUE THREAD

**Issue by zhixiangyuan** [halo-dev/halo#997]
# 概述

添加友链时校验该域名是否已添加

## 动机

当添加的友链很多时不记得该友链之前是否添加过

**Comment by JayM118** [comment]
unsubscribe




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "halo-dev/halo"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月30日(星期三) 下午2:05
收件人:&nbsp;"halo-dev/halo"<halo@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [halo-dev/halo] feat: 添加友链时不会校验现有域名是否重复 (#997)





 
Closed #997.
